### ISSUE TITLE
while 方法可能少写break

### ISSUE THREAD

**Issue by timlincool** [hankcs/HanLP#1]
java新手第一次使用github,如有缺失请见谅

使用 findbugs找到的，报以下错误
Value of Node.label from previous case is overwritten here due to switch statement fall through [Scariest(1), High confidence]

在 com.hankcs.hanlp.dependency.common.Node的第182行

            case wh:
                label = "x";
            case begin:
                label = "root";
                break;

case wh 没有break ,不确定这样是否会造成问题。

**Comment by hankcs** [comment]
谢谢指正，一时疏忽了。

这部分代码的作用是将词性从新版北大标注集映射到旧版，以兼容句法分析所使用的清华依存语料库。以w开头的词性是一些标点符号，可能会对标点造成影响。不过清华依存语料库中完全没有标点，所以对最终结果没有影响，倒是有些不严谨。

我已加上break，再次感谢。
