### ISSUE TITLE
你好，最近遇到一个关于hanlp.properties的问题

### ISSUE THREAD

**Issue by XiliangSong** [hankcs/HanLP#100]
我使用的IDE是Eclipse，配置好jar包和hanlp.properties文件后，能够正常使用，但在下次打开的时候，偶尔会出现hanlp.properties文件无缘无故的消失的问题，这个是怎么一回事啊？

**Comment by focusheart** [comment]
不知道你是怎么配置的？以前我在别的项目遇到过类似的情况呢，有以下几个可能：
1. .properties文件放置的位置不合适，eclipse会自动过滤
2. 换了workspace，不是同一个项目内了。
3. 配置jar的方式不对，有时候是引用，有时候是复制，绝对路径和相对路径的问题

一般都是检查自己的Eclipse配置解决的。

2015-12-15 22:18 GMT+08:00 Song Xiliang <notifications@github.com>:

**Comment by hankcs** [comment]
有些IDE会在build的时候自动清空class目录，所以最安全的做法是放到resource或src目录里。

**Comment by hankcs** [comment]
另外，如果你依然觉得放置配置文件是件困难事，你现在可以设一个绝对路径：
https://github.com/hankcs/HanLP/commit/00b320e995c110e1450d50c42180d4fb89561945
