### ISSUE TITLE
在线学习并序列化后的新模型无效

### ISSUE THREAD

**Issue by HitomeRyuu** [hankcs/HanLP#1004]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.6.8
我使用的版本是：1.6.8

## 我的问题

在线学习后的新模型无效
## 复现问题

 您好，感谢您的开源！我正在尝试感知机的在线学习方法。用learn方法在线学习后，用getPerceptronSegmenter().getModel().save()进行了序列化并保存到模型，但是注释掉序列化和learn之后再次调用DemoPerceptronLexicalAnalyzer.java并没有达到在线学习的效果 

### 步骤

1. 首先把DemoPerceptronLexicalAnalyzer.java源代码中序列化的注释去掉，然后运行，得到正确的在线学习结果，并序列化覆盖原来的CWS.bin模型
2. 然后注释掉序列化语句和在线学习learn方法
3. 接着再次运行DemoPerceptronLexicalAnalyzer.java

### 触发代码

```
 public class DemoPerceptronLexicalAnalyzer extends TestUtility
{
    public static void main(String[] args) throws IOException
    {
        PerceptronLexicalAnalyzer analyzer = new PerceptronLexicalAnalyzer(HanLP.Config.PerceptronCWSModelPath,
                                                                           HanLP.Config.PerceptronPOSModelPath,
                                                                           HanLP.Config.PerceptronNERModelPath);

        // 任何模型总会有失误，特别是98年这种陈旧的语料库
        System.out.println(analyzer.analyze("总统普京与特朗普通电话讨论太空探索技术公司"));
        // 支持在线学习
        //analyzer.learn("与/c 特朗普/nr 通/v 电话/n 讨论/v [太空/s 探索/vn 技术/n 公司/n]/nt");

        // 学习到新知识
        System.out.println(analyzer.analyze("总统普京与特朗普通电话讨论太空探索技术公司"));
        // 还可以举一反三
        System.out.println(analyzer.analyze("主席和特朗普通电话"));

        // 知识的泛化不是死板的规则，而是比较灵活的统计信息
        System.out.println(analyzer.analyze("我在浙江金华出生"));
        //analyzer.learn("在/p 浙江/ns 金华/ns 出生/v");

        System.out.println(analyzer.analyze("我在四川金华出生，我的名字叫金华"));

        // 在线学习后的模型支持序列化，以分词模型为例：
        //analyzer.getPerceptronSegmenter().getModel().save(HanLP.Config.PerceptronCWSModelPath);

        // 请用户按需执行对空格制表符等的预处理，只有你最清楚自己的文本中都有些什么奇怪的东西
        System.out.println(analyzer.analyze("空格 \t\n\r\f&nbsp;统统都不要"
                                                .replaceAll("\\s+", "")    // 去除所有空白符
                                                .replaceAll("&nbsp;", "")  // 如果一些文本中含有html控制符
        ));
    }
}
```
### 期望输出

```
总统/n 普京/nr 与/p 特朗普/nr 通/v 电话/n 讨论/v [太空/s 探索/vn 技术/n 公司/n]/nt
总统/n 普京/nr 与/p 特朗普/nr 通/v 电话/n 讨论/v [太空/s 探索/vn 技术/n 公司/n]/nt
主席/n 和/c 特朗普/nr 通/v 电话/n
我/r 在/p 浙江/ns 金华/ns 出生/v
我/r 在/p 四川/ns 金华/ns 出生/v ，/w 我/r 的/u 名字/n 叫/v 金华/nr
空格/n 统统/d 都/d 不要/d
```

### 实际输出

```
总统/n 普京/nr 与/p 特朗普/b 通/vn 电话/n 讨论/v 太空/s 探索/vn 技术/n 公司/n
总统/n 普京/nr 与/p 特朗普/b 通/vn 电话/n 讨论/v 太空/s 探索/vn 技术/n 公司/n
主席/n 和/c 特朗普/b 通/vn 电话/n
我/r 在/p [浙江/ns 金华/nz]/nt 出生/v
我/r 在/p 四川/ns 金华/nr 出生/v ，/w 我/r 的/u 名字/n 叫/v 金华/nr
空格/n 统统/d 都/d 不要/d
```

## 其他信息

CWS.bin是用pku98训练的；
我能确定序列化已经生效，有一次save到config.POS里面去了，再运行的时候会报错模型输入有误，重新训练了POS才能继续运行；
感谢您的时间！

做了了两天实验又发现了新问题，如果单独为某一类实体特地训练了一个NER模型，这个模型是覆盖在基础语料模型上，还是另外储存？如果是覆盖的话，有模型序列化到模型的方法吗？如果是另外储存，那下次调用analyze方法的时候需要一次把两个模型都读取才行？
谢谢！

**Comment by hankcs** [comment]
1. 两个“金华”的词性标注属于词性标注模型的职责，所以你应该序列化词性标注模型而不仅仅是CWS模型。see `com.hankcs.hanlp.model.perceptron.PerceptronLexicalAnalyzer#getPerceptronPOSTagger`
1. 一个Analyzer只接受一个NER模型。一个NER模型可以支持任意种实体。所以你的问题是个伪命题。检查你的语料，检查每种实体的数量，如果有n种实体且样本均衡，你的NER模型就是一个好模型。

**Comment by HitomeRyuu** [comment]
> 1. 两个“金华”的词性标注属于词性标注模型的职责，所以你应该序列化词性标注模型而不仅仅是CWS模型。see `com.hankcs.hanlp.model.perceptron.PerceptronLexicalAnalyzer#getPerceptronPOSTagger`
> 2. 一个Analyzer只接受一个NER模型。一个NER模型可以支持任意种实体。所以你的问题是个伪命题。检查你的语料，检查每种实体的数量，如果有n种实体且样本均衡，你的NER模型就是一个好模型。

感谢回复！那我可以这样理解吗，一次序列化只能保存一种类型（分词or标注）的在线学习，如果同时learn了不同类型，就无法在一个模型上序列化？

**Comment by hankcs** [comment]
你说的类型如果指的是这些事情，一个模型只做一件事情（CWS、POS、NER）。如果你指的是NER的类型，前面说过，一个NER模型可以支持任意种实体。但在线学习不可能学到新的实体类型。可能需要看一些论文才能理解这些概念。

**Comment by HitomeRyuu** [comment]
> 你说的类型如果指的是这些事情，一个模型只做一件事情（CWS、POS、NER）。如果你指的是NER的类型，前面说过，一个NER模型可以支持任意种实体。但在线学习不可能学到新的实体类型。可能需要看一些论文才能理解这些概念。

感谢您的耐心解答！
