### ISSUE TITLE
能否基于Word2VecTrainer做word2vec的增量训练？

### ISSUE THREAD

**Issue by Wangyq9527** [hankcs/HanLP#1005]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕

## 版本号

当前最新版本号是：1.6.8
我使用的版本是：1.6.8

## 我的问题
1、我在尝试用HanLP的Word2Vec做文档相似性分析，想问下通过Word2VecTrainer可否做word2vec向量词的增量训练，我做了尝试，发现会覆盖已有文件，请问是否有其他方法，谢谢！

**Comment by hankcs** [comment]
目前显然没有增量功能，可行的思路是加载模型，用加载到的参数作为初始值进行训练。由于全量训练速度可以接受，增量训练没有多少实际意义。

**Comment by Wangyq9527** [comment]
收到，谢谢
