### ISSUE TITLE
python 调用时候出现的乱码问题

### ISSUE THREAD

**Issue by lxj0276** [hankcs/HanLP#101]
本人环境是win7 64bit，python2.7.*版本，按照http://www.hankcs.com/nlp/python-calls-hanlp.html用的时候，在输出print(HanLP.segment('你好，欢迎在Python中调用HanLP的API'))时出现乱码，问下怎么可以解决，现在就是卡在<class 'jpype._jclass.java.util.ArrayList'>（(HanLP.segment('你好，欢迎在Python中调用HanLP的API'))的数据类型是<class 'jpype._jclass.java.util.ArrayList'>）数据类型往python转化时不知道怎么做，对java一点都不了解。

**Comment by hankcs** [comment]
请尝试：
0. # -*- coding:utf-8 -*-
0. u'你好，欢迎在Python中调用HanLP的API'
0. text = '文本'，下个断点看看到底是什么编码。

**Comment by Tony-Wang** [comment]
text = u'文本'
u加了吗？
java出来都是unicode
```
    content = u"海巡署南部地区巡防局岸巡第72大队昨天表示，于昨凌晨2时15分许，西屿乡池西村池西执检区的守望人员，发现1名老百姓欲前往该港上架区进行上架时，疑因风浪过大不慎遭到强风吹落而落水，情况紧急，该所随即派员前往抢救落水的民众，并顺利、平安的将他就上岸来，受助民众很感谢岸巡人员适时的伸出援手。"
    TraditionalChineseTokenizer = JClass("com.hankcs.hanlp.tokenizer.TraditionalChineseTokenizer")
    TraditionalChineseTokenizer.SEGMENT.enableAllNamedEntityRecognize(True)
    termList = TraditionalChineseTokenizer.segment(content)
    words = []
    for i in range(termList.size()):
        words.append("%s\%s\%s" % (termList[i].word, termList[i].nature, translatePOS(str(termList[i].nature))))
    print u" ".join(words)
```

**Comment by lxj0276** [comment]
加u也不行，我已经知道怎么解决了，需要把得到的结果列表元素利用toString转化一下就可以了

**Comment by hankcs** [comment]
感谢大家的反馈，很好的参考。

**Comment by lxj0276** [comment]
还有一个问题，我想问一下，就是词库里的\data\dictionary\custom\现代汉语补充词库.txt,比如：一一道来	l	4   第一个是词语，第二个是词性吗，还有数字是什么意思

**Comment by hankcs** [comment]
语料库中该单词以该词性出现的频次

**Comment by lxj0276** [comment]
就是词频，对吧，还有个问题，如果我拿到语料库以后，哪个接口是可以得到这个词库

**Comment by hankcs** [comment]
请参考：https://github.com/hankcs/HanLP/wiki/%E8%AE%AD%E7%BB%83%E5%88%86%E8%AF%8D%E6%A8%A1%E5%9E%8B

**Comment by lxj0276** [comment]
好的，谢谢~
后续有没有增加情感分析方面模块的打算呢

**Comment by hankcs** [comment]
其实就是文本分类，有这个计划。

**Comment by yarayu** [comment]
http://www.hankcs.com/nlp/python-calls-hanlp.html         1.2.8的版本，别人机器上运行没有问题，但在我的机器上运行“依存句法分析”部分     为何会报jpype._jexception.OutOfMemoryErrorPyRaisable: java.lang.OutOfMemoryError: Java heap space错误？

**Comment by hankcs** [comment]
startJVM(getDefaultJVMPath(), "-Djava.class.path=C:\hanlp\hanlp-1.2.8.jar;C:\hanlp", "-Xms1g")

**Comment by yarayu** [comment]
测   https://github.com/hankcs/HanLP#3配置文件    上面的例子时，好多例子都报相应类没有segment或seg属性，如“11. 日本人名识别”    是否可以打开com\hankcs\hanlp\recognition\nr中的这些类呢？若可以，如何打开才能保证非乱码呢？

**Comment by hankcs** [comment]
请详细描述你的问题，附带示例代码和报错信息。

**Comment by hankcs** [comment]
JClass用错了，请谷歌它的用法和Java的包名

**Comment by yarayu** [comment]
Demo4(索引分词)， 我转为python代码却没有问题：

# demo4(索引分词)
HanLP = JClass('com.hankcs.hanlp.tokenizer.IndexTokenizer')
print HanLP.segment(u"主副食品").toString()

 

 

 

那demo11（日本名）用JClass应该是可以的，我把关于Japanese 的所有类都一一试过了，均不可。

**Comment by hankcs** [comment]
你根本没明白JClass是什么，只凭你一两个试验什么都不能说明。
请谷歌它的用法和Java的包名用法。

**Comment by leemanyan** [comment]
用Pycharm运行时显示内存溢出是什么原因呢？本人字典下的也是完整版不是mini版的jpype._jexception.VirtualMachineErrorPyRaisable: java.lang.OutOfMemoryError: Java heap space

**Comment by leemanyan** [comment]
谢谢了

**Comment by miaomushan** [comment]
我的环境python2.7+jdk1.6(32位)，请教下：
print(HanLP.segment(u"你好，欢迎使用HanLP汉语处理包！"))
报错：
jpype._jexception.OutOfMemoryErrorPyRaisable: java.lang.OutOfMemoryError: Java heap space
然后修改为：
startJVM(getDefaultJVMPath(), "-Djava.class.path=C:\hanlp\hanlp-1.2.8.jar;C:\hanlp", "-Xms1g")
输出：
Error occurred during initialization of VM
Incompatible minimum and maximum heap sizes specified

**Comment by lxj0276** [comment]
@miaomushan 路径是不是应该"\\"

**Comment by leemanyan** [comment]
@lxj0276 你好，运行时突然出现jpype._jexception.ExceptionPyRaisable: java.lang.Exception: Class com.hankcs.hanlp.HanLP not found的错误，之前不小心卸载了python2换成3，现在又换成2就变成这样了，有没有解决办法呢~

**Comment by hankcs** [comment]
循序渐进地解决问题。

0. 先说分词。不挂载外部词典，直接用portable对内存的需求是低于120MB的。挂载了默认的词典之后，对内存的需求是至少120MB。如果你挂载了自己的任何词典，都必须考虑词典的大小。
0. 再说句法分析。句法分析光模型就有200MB，显然不适用上一个标准，这时候必须加大JVM内存至1G。
0. 然后说Java的问题。为何不先在Java下面测试一遍，然后再用JPype调用呢？
0. JVM默认有多个不同意义的内存参数，其默认值是未知的。对于Incompatible minimum and maximum heap sizes specified，请试试-Xms512m -Xmx1g
0. Python解释器本身也要耗费内存，具体大小未知。
0. 测试平台有讲究，Win32下JVM能申请到的最大内存约1G左右。JPype可能以pipeline的形式调用JVM，是否存在父子进程等机制导致JVM能拿到手的内存更低？

**Comment by miaomushan** [comment]
Segment nShortSegment = new NShortSegment().enableCustomDictionary(false).enablePlaceRecognize(true).enableOrganizationRecognize(true);
请教下，这句用是否可以写成如下这样（java）？
Segment NShortSegment1 = new NShortSegment()
NShortSegment1.enableCustomDictionary(false);
NShortSegment1.enablePlaceRecognize(true);
NShortSegment1.enableOrganizationRecognize(true);
如何改写成python语法格式？
Segment = JClass('com.hankcs.hanlp.seg.Segment')
Segment1=Segment()
print Segment1.seg(u"刘喜杰石国祥会见吴亚琴先进事迹报告团成员").toString()

**Comment by hankcs** [comment]
可以写成这样：
Segment NShortSegment1 = new NShortSegment()
NShortSegment1.enableCustomDictionary(false);
NShortSegment1.enablePlaceRecognize(true);
NShortSegment1.enableOrganizationRecognize(true);

python应该可以一样调用的，jclass选择NShortSegment

**Comment by hankcs** [comment]
具体Java语法请简单Google一下，特别需要注意抽象类。

**Comment by miaomushan** [comment]
NShortSegment=JClass('com.hankcs.hanlp.seg.NShort.NShortSegment')
NShortSegment1=NShortSegment()
print NShortSegment.seg(u"刘喜杰石国祥会见吴亚琴先进事迹报告团成员").toString()
改为最简单形式，也报错：
RuntimeError: No matching overloads found. at native\common\jp_method.cpp:121

**Comment by miaomushan** [comment]
NShortSegment=JClass('com.hankcs.hanlp.seg.NShort.NShortSegment')
# NShortSegment.enableCustomDictionary(False)
# NShortSegment.enablePlaceRecognize(True)
# NShortSegment.enableOrganizationRecognize(True)
NShortSegment1=NShortSegment()
print NShortSegment1.seg(u"刘喜杰石国祥会见吴亚琴先进事迹报告团成员").toString()

RuntimeError: Multiple overloads possible. at native\common\jp_method.cpp:109

写成最简单格式 还是报“多个重载的可能”,请楼主指点下 ，这块应该怎么修改？

**Comment by miaomushan** [comment]
NShortSegment=JClass('com.hankcs.hanlp.seg.NShort.NShortSegment')
# NShortSegment.enableCustomDictionary(False)
# NShortSegment.enablePlaceRecognize(True)
# NShortSegment.enableOrganizationRecognize(True)
NShortSegment1=NShortSegment()
print NShortSegment1.seg(u"刘喜杰石国祥会见吴亚琴先进事迹报告团成员").toString()

RuntimeError: Multiple overloads possible. at native\common\jp_method.cpp:109

写成最简单格式 还是报“多个重载的可能”,请楼主指点下 ，这块应该怎么修改？

**Comment by miaomushan** [comment]
NShortSegment=JClass('com.hankcs.hanlp.seg.NShort.NShortSegment')
# NShortSegment.enableCustomDictionary(False)
# NShortSegment.enablePlaceRecognize(True)
# NShortSegment.enableOrganizationRecognize(True)
NShortSegment1=NShortSegment()
print NShortSegment1.seg(u"刘喜杰石国祥会见吴亚琴先进事迹报告团成员").toString()
RuntimeError: Multiple overloads possible. at native\common\jp_method.cpp:109
写成最简单格式 还是报“多个重载的可能”,请楼主指点下 ，这块应该怎么修改？

**Comment by leefionglee** [comment]
@hankcs   用python调用parseDependency,  请问怎么遍历对应的内容？  python版应该如何遍历？ 下面的代码报错； 
python:

`for item in st:
    print item.LEMMA`


JAVA:

`for (CoNLLWord word : sentence)
        {
            System.out.printf("%s --(%s)--> %s\n", word.LEMMA, word.DEPREL, word.HEAD.LEMMA);
        }`

**Comment by leefionglee** [comment]
@Tony-Wang

**Comment by ljdawn** [comment]
目前我用的python2.  无论是加u还是不加u  在文件开头已经写了encoding  还是提示UnicodeEncodeError: 'ascii' codec can't encode character u'\u6211' in position 1: ordinal not in range(128)  或者UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)

**Comment by arthurtalkgoal** [comment]
@ljdawn, I used HanLP in python too; so far I am happy with it.

I bet the ```System.out.printf``` can create a lot of such encoding error in python2. I avoid all these output from JAVA.

Can you try directly return as an array of objects and loop in python?

**Comment by yangershu** [comment]
我使用的是python2.7 jpype 调用hanlp，执行HanLP.segment(content)后返回的是，'**jpype._jclass.java.util.ArrayList**'，请问我该怎么样将这个转换成python的list呢？还有就是我想把'**jpype._jclass.java.util.ArrayList**'这个结果print出来的时候，会报**UnicodeDecodeError: 'ascii' codec can't decode byte 0xa8 in position 144: ordinal** 这个错误

**Comment by ljdawn** [comment]
@arthurtalkgoal  OK, I will try that , thank you ^_^

**Comment by lhongda** [comment]
@miaomushan 

试试将语句改成这样：

print NShortSegment1.seg(JString(u"刘喜杰石国祥会见吴亚琴先进事迹报告团成员)").toString()

**Comment by guduxingzou** [comment]
亲测，换Python3可以解决乱码问题

**Comment by fengfan0721** [comment]
startJVM(getDefaultJVMPath(), "-Djava.class.path=/home/ff/Downloads/hanlp-portable-1.3.4.jar:data/hanlp")
HanLP = JClass('com.hankcs.hanlp.HanLP')
# 中文分词
a='抚州市华鑫工程咨询有限公司关于金溪县中医院腹腔镜采购项目（采购编号：FZHX-2016-G049）公开招标公告'
segment = HanLP.newSegment().enableOrganizationRecognize(true)

请问python怎么调用这个机构名称的接口啊？

**Comment by yangershu** [comment]
非常抱歉，才看到邮件。不知道你现在是否已经解决问题

startJVM(getDefaultJVMPath(), "-Djava.class.path=/home/ff/Downloads/hanlp-portable-1.3.4.jar:data/hanlp")
HanLP = JClass('com.hankcs.hanlp.HanLP')
segment = HanlP..newSegment().enableOrganizationRecognize(True)

best regards

在 2017-07-25 17:27:10，"fengfan0721" <notifications@github.com> 写道：


startJVM(getDefaultJVMPath(), "-Djava.class.path=/home/ff/Downloads/hanlp-portable-1.3.4.jar:data/hanlp")
HanLP = JClass('com.hankcs.hanlp.HanLP')

中文分词

a='抚州市华鑫工程咨询有限公司关于金溪县中医院腹腔镜采购项目（采购编号：FZHX-2016-G049）公开招标公告'
segment = HanLP.newSegment().enableOrganizationRecognize(true)

请问python怎么调用这个机构名称的接口啊？

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
