### ISSUE TITLE
Translating docs and codebase to English

### ISSUE THREAD

**Issue by bdteo** [hankcs/HanLP#1012]
Are there any forks of this repository that translate it into English ?

**Comment by imic07** [comment]
use google translate plugin

**Comment by hankcs** [comment]
Thanks for your request. In short, I'll translate the [documentation](https://github.com/hankcs/HanLP/blob/master/README.md) soon. Actually I've been considering it for a long time. The only problem is too much effort for translating everything while currently the majority of this project is only intended for Chinese. I do notice many international users from U.S. and Japan are using this project too, some of them even made extensions on it, which I really appreciate. Here is the statistics for recent months.

<img width="1066" alt="stat" src="https://user-images.githubusercontent.com/5326890/48297076-171b4a00-e46e-11e8-8340-7b5a9178c25f.png">

I'll start with translating the documentation into English and Japanese. After that, HanLP 2.0 is awaiting its rebirth as an international project, for which code base will be in English, multilingual processing will be supported. Hope this can benefit more global users.

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
