### ISSUE TITLE
人名识别错误

### ISSUE THREAD

**Issue by chasuner** [hankcs/HanLP#102]
反馈一部分人名识别的问题:
我爱杨云宵
龙与凤的传说
陌上花开缓缓归
鱼和水的故事
陕西榕怡公司
陈雯晴要努力

**Comment by hankcs** [comment]
你好，感谢反馈。

0. 目前的算法在一些语境中存在召回率高准确率低的情况，等待改进中。
0. 对于古诗的支持有点勉强
0. [陕西/ns, 榕怡/nr, 公司/nis]从分词的角度来讲无可厚非，榕怡可以看做一个公司的名字，只不过不是人的名字。
0. 目前有暂时的解决方案：https://github.com/hankcs/HanLP/commit/73ef2ee112f305618073b72e2c506fd6d3989bca
