### ISSUE TITLE
命名实体提取，时间词识别有误

### ISSUE THREAD

**Issue by Samurais** [hankcs/HanLP#1020]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕

## 版本号

我使用的版本是：1.6.8

## 我的问题
```
            CRFLexicalAnalyzer analyzer = new CRFLexicalAnalyzer();
            Sentence wordList = analyzer.analyze("下周四天气怎么样");
```

输出结果：
![image](https://user-images.githubusercontent.com/3538629/48359900-f276da80-e6d8-11e8-9bd4-fff6e366d647.png)

该结果符合预期。

```
            CRFLexicalAnalyzer analyzer = new CRFLexicalAnalyzer();
            Sentence wordList = analyzer.analyze("下周三天气怎么样");
            System.out.println(wordList);
```

输出结果

![image](https://user-images.githubusercontent.com/3538629/48359938-03275080-e6d9-11e8-8676-3cb230f9570b.png)

该结果不符合预期，应该将*下周三*识别为时间词。

请问怎么能提高时间词的识别效果？

### 触发代码

```
    public void testDateNer() {
        try {
            CRFLexicalAnalyzer analyzer = new CRFLexicalAnalyzer();
            Sentence wordList = analyzer.analyze("下周三天气怎么样");
            System.out.println(wordList);
        } catch (IOException e) {
            e.printStackTrace();
        }

    }
```

**Comment by hankcs** [comment]
感谢反馈，配送的CRF模型训练自98年1月份的小型语料库，只做演示不做生产用。请自行训练大型模型，或者用[1亿语料库上训练的感知机](http://hanlp.com/?sentence=%E4%B8%8B%E5%91%A8%E4%B8%89%E5%A4%A9%E6%B0%94%E6%80%8E%E4%B9%88%E6%A0%B7)。

**Comment by Samurais** [comment]
请问这个“1亿语料库上训练的感知机”如何获取，我看文档中没有体现，只是提供HTTP接口访问么？

**Comment by Samurais** [comment]
好的，感谢！
 




------------------
Cheers.
Hai Liang Wang, CEO, Chatopera




 
 
 
------------------ Original ------------------
From: "hankcs"; 
Date: 2018年11月13日(星期二) 凌晨0:35
To: "hankcs/HanLP"; 
Cc: "Samurais"; "Author"; 
Subject: Re: [hankcs/HanLP] 命名实体提取，时间词识别有误 (#1020)

 

感谢反馈，配送的CRF模型训练自98年1月份的小型语料库，只做演示不做生产用。请自行训练大型模型，或者用1亿语料库上训练的感知机。

**Comment by hankcs** [comment]
随1.6.8发布的，默认的感知机词法分析器会自动加载。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
