### ISSUE TITLE
未进行修改, 自定义词典缓存失败

### ISSUE THREAD

**Issue by imagecser** [hankcs/HanLP#1025]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

使用python3.7.1 版本, 直接pip 安装得到
Windows 10 家庭中文版1803 17134.376
当前最新版本号是：1.7.0
我使用的版本是：1.7.0

## 我的问题
在我使用pip 安装后, 在命令行运行`hanlp segment` 下载过jar和data后, 输入测试任意用句, 会出现报错信息.

## 复现问题

在我清空以前的hanlp文件后, 重新pip 安装, 没有对data 中的任何数据修改, 直接使用hanlp segment即出现问题.

### 触发代码

```
$ hanlp segment
测试用句

```

### 实际输出

```
十一月 17, 2018 3:09:57 下午 com.hankcs.hanlp.dictionary.CustomDictionary loadDat
警告: 读取失败，问题发生在java.lang.ArrayIndexOutOfBoundsException: 7
        at com.hankcs.hanlp.utility.ByteUtil.bytesHighFirstToInt(ByteUtil.java:239)
        at com.hankcs.hanlp.corpus.io.ByteArray.nextInt(ByteArray.java:68)
        at com.hankcs.hanlp.dictionary.CustomDictionary.loadDat(CustomDictionary.java:325)
        at com.hankcs.hanlp.dictionary.CustomDictionary.loadMainDictionary(CustomDictionary.java:64)
        at com.hankcs.hanlp.dictionary.CustomDictionary.<clinit>(CustomDictionary.java:51)
        at com.hankcs.hanlp.seg.Segment.combineByCustomDictionary(Segment.java:203)
        at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.segSentence(ViterbiSegment.java:57)
        at com.hankcs.hanlp.seg.Segment.seg(Segment.java:557)

十一月 17, 2018 3:09:57 下午 com.hankcs.hanlp.dictionary.CustomDictionary load
严重: 自定义词典c:/program读取错误！java.io.FileNotFoundException: c:\program (系统找不到指定的文件。)
十一月 17, 2018 3:09:57 下午 com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
警告: 失败：c:/program
十一月 17, 2018 3:09:57 下午 com.hankcs.hanlp.dictionary.CustomDictionary load
严重: 自定义词典c:/program读取错误！java.io.FileNotFoundException: c:\program (系统找不到指定的文件。)
十一月 17, 2018 3:09:57 下午 com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
警告: 失败：c:/program
十一月 17, 2018 3:09:57 下午 com.hankcs.hanlp.dictionary.CustomDictionary load
严重: 自定义词典c:/program读取错误！java.io.FileNotFoundException: c:\program (系统找不到指定的文件。)
十一月 17, 2018 3:09:57 下午 com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
警告: 失败：c:/program
十一月 17, 2018 3:09:57 下午 com.hankcs.hanlp.dictionary.CustomDictionary load
严重: 自定义词典c:/program读取错误！java.io.FileNotFoundException: c:\program (系统找不到指定的文件。)
十一月 17, 2018 3:09:57 下午 com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
警告: 失败：c:/program
十一月 17, 2018 3:09:57 下午 com.hankcs.hanlp.dictionary.CustomDictionary load
严重: 自定义词典c:/program读取错误！java.io.FileNotFoundException: c:\program (系统找不到指定的文件。)
十一月 17, 2018 3:09:57 下午 com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
警告: 失败：c:/program
十一月 17, 2018 3:09:57 下午 com.hankcs.hanlp.dictionary.CustomDictionary load
严重: 自定义词典c:/program读取错误！java.io.FileNotFoundException: c:\program (系统找不到指定的文件。)
十一月 17, 2018 3:09:57 下午 com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
警告: 失败：c:/program
十一月 17, 2018 3:09:57 下午 com.hankcs.hanlp.dictionary.CustomDictionary load
严重: 自定义词典c:/program读取错误！java.io.FileNotFoundException: c:\program (系统找不到指定的文件。)
十一月 17, 2018 3:09:57 下午 com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
警告: 失败：c:/program
十一月 17, 2018 3:09:57 下午 com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
警告: 没有加载到任何词条
十一月 17, 2018 3:09:57 下午 com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
警告: 自定义词典c:/program files/python37/lib/site-packages/pyhanlp/static/data/dictionary/custom/CustomDictionary.txt缓存失败！
java.lang.NullPointerException
        at com.hankcs.hanlp.dictionary.CustomDictionary.loadMainDictionary(CustomDictionary.java:116)
        at com.hankcs.hanlp.dictionary.CustomDictionary.<clinit>(CustomDictionary.java:51)
        at com.hankcs.hanlp.seg.Segment.combineByCustomDictionary(Segment.java:203)
        at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.segSentence(ViterbiSegment.java:57)
        at com.hankcs.hanlp.seg.Segment.seg(Segment.java:557)

测试/vn 用/p 句/q
```

谢谢您的解答!

**Comment by hankcs** [comment]
你好，感谢反馈。
刚才用卸载重装试验，未能复现问题，一些正常：
<img width="711" alt="hankcs com 2018-11-17 at 11 06 06 am" src="https://user-images.githubusercontent.com/5326890/48663087-f1d3a080-ea58-11e8-9a8a-f620ef98e011.png">

你的问题在于安装路径中含有空格`c:/program files`，造成错误截断，这是Windows老大难的问题。解决方案如下：

1. 编辑`c:/program files/python37/lib/site-packages/pyhanlp/static/hanlp.properties`第一行，将`root=c:/program files/python37/lib/site-packages/pyhanlp/static`改为`d:`。然后将`c:/program files/python37/lib/site-packages/pyhanlp/static/data`这个文件夹剪切到d盘根目录。当然这里的root路径可以自己设置，只要不含空格都行。
1. 用Linux。

**Comment by happyxuezhou** [comment]
错误如下：
from pyhanlp import *

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-14-683ea047796e> in <module>
----> 1 from pyhanlp import *

C:\ProgramData\Anaconda3\lib\site-packages\pyhanlp\__init__.py in <module>
    120 
    121 
--> 122 _start_jvm_for_hanlp()
    123 
    124 

C:\ProgramData\Anaconda3\lib\site-packages\pyhanlp\__init__.py in _start_jvm_for_hanlp()
     73             raise ValueError(
     74                 "配置错误: 数据包 %s 不存在，请修改配置文件中的root" %
---> 75                 HANLP_DATA_PATH)
     76     elif not os.path.isfile(PATH_CONFIG):
     77         raise ValueError(

ValueError: 配置错误: 数据包 c:/programdata/anaconda3/lib/site-packages/pyhanlp/static\data 不存在，请修改配置文件中的root

不存在data文件夹
版本anaconda, python3.7，系统win7

**Comment by hankcs** [comment]
> 错误如下：
> from pyhanlp import *
> 
> ValueError Traceback (most recent call last)
> in
> ----> 1 from pyhanlp import *
> 
> C:\ProgramData\Anaconda3\lib\site-packages\pyhanlp__init__.py in
> 120
> 121
> --> 122 _start_jvm_for_hanlp()
> 123
> 124
> 
> C:\ProgramData\Anaconda3\lib\site-packages\pyhanlp__init__.py in _start_jvm_for_hanlp()
> 73 raise ValueError(
> 74 "配置错误: 数据包 %s 不存在，请修改配置文件中的root" %
> ---> 75 HANLP_DATA_PATH)
> 76 elif not os.path.isfile(PATH_CONFIG):
> 77 raise ValueError(
> 
> ValueError: 配置错误: 数据包 c:/programdata/anaconda3/lib/site-packages/pyhanlp/static\data 不存在，请修改配置文件中的root
> 
> 不存在data文件夹
> 版本anaconda, python3.7，系统win7

`pip3 install -U pyhanlp` 或运行这三句话可以自动修复。

https://github.com/hankcs/pyhanlp/blob/4e0193807d040e905c9ddab9b859df4829634140/tests/demos/demo_download_again.py#L4-L8

另外不要在不相关的issue下乱留言！
