### ISSUE TITLE
android开发文件无法写入到data/dictionary/person/nrf.txt.trie.dat

### ISSUE THREAD

**Issue by LongyueChang** [hankcs/HanLP#1026]
当前最新版本号是：
我使用的版本是：1.7.0

## 我的问题
在android机上面做动态分词，经常会抛出
11-20 19:26:18.068 1366-2392/com.mtrobot.studio.mtrobotstudio_product E/CrashHandler: java.lang.IllegalAccessError: 不支持写入data/dictionary/person/nrf.txt.trie.dat！请在编译前将需要的数据放入app/src/main/assets/data

该异常直接导致应用程序崩溃，并且我们的系统是root权限的，不会发生读写失败的问题，查看系统日志发现nrf.txt.trie.dat从未写入成功过，请大牛帮忙解决,谢谢

**Comment by LongyueChang** [comment]
comment

**Comment by AnyListen** [comment]
`data/dictionary/person/nrf.txt.trie.dat` 应该是 jar 包的资源路径，因此不支持写入

**Comment by hankcs** [comment]
异常已经说明了解决方案。
检查你android项目的app/src/main/assets下面有没有`data/dictionary/person/nrf.txt.trie.dat`，没有的话下载相应文件放到对应位置。

**Comment by hankcs** [comment]
https://github.com/hankcs/HanLPAndroidDemo/tree/master/app/src/main/assets

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
