### ISSUE TITLE
感知机分词识别的一些疑问

### ISSUE THREAD

**Issue by l06066hb** [hankcs/HanLP#1030]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.7.0
我使用的版本是：1.7.0。

## 我的问题
非常感谢作者开放自己的亿级训练结果，在使用中有些疑问希望能给予帮助：
1.使用感知机分词时对一些比较明显不是人名的词或符号识别为人名，如“否”，“归档”这些字或词单独出现时 识别为nr   "普卡客户"中的“普卡”会被识别为地名等
2.在线演示的模型和1.6.8发布的模型是一个么，我看到之前有人问到这个，差异主要在现代汉语词典，不过使用的时候一般我在本地识别不如预期的时候，拿到在线演示上面测试时效果更好一些，有点不清楚这之间具体有哪些差异导致。
3.现在的使用上包含的人名地名较多，  常常会将地名识别成人名，我现在的解决办法只有加词典，请问下还有更好的方式解决么。 

### 步骤
词典和模型使用的1.7.0版本，加了些地名的词典 但已确认出现问题的词的不在新加的词典中出现

### 触发代码

```
    public void testIssue1234() throws Exception
    {
        PerceptronLexicalAnalyzer analyzer = new PerceptronLexicalAnalyzer();
        System.out.println(analyzer.analyze("归档"));
        System.out.println(analyzer.analyze("普卡客户"));
        System.out.println(analyzer.analyze("谢师傅帮忙处理"))；
    }
```
### 期望输出

```
期望输出
```
归档/vn
普卡客户/n
谢/v 师傅/n 帮忙/v 处理/v
### 实际输出
归档/nr
普卡/ns 客户/n
谢/nr 师傅/n 帮忙/v 处理/v

```
实际输出
```

## 其他信息

![qq 20181122140354](https://user-images.githubusercontent.com/18030444/48884619-2cc24380-ee60-11e8-8d9d-da0f8374c31f.png)
![qq 20181122140502](https://user-images.githubusercontent.com/18030444/48884620-2cc24380-ee60-11e8-96a7-d37ae4f49b3d.png)
![qq 20181122140536](https://user-images.githubusercontent.com/18030444/48884622-2d5ada00-ee60-11e8-89fb-acc6be19706c.png)

**Comment by hankcs** [comment]
感谢反馈，简而言之，词法分析器由CWS、POS和NER三个模型驱动。线上使用的CWS模型与1.6.8、1.7.0完全一致`MD5 (cws.bin) = d0219e83566db14a834a8cef915a2668`。线上使用的POS和NER是训练自1998年6个月的语料库，而发行版则仅仅训练自1个月的语料库。
你的体验就是由于语料库规模造成的，同样“普卡客户”的问题也可以通过自行标注语料库重新训练或在线学习来解决，请参考wiki中感知机一章。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
