### ISSUE TITLE
已经成词的词不能通过learn拆分

### ISSUE THREAD

**Issue by zzl221000** [hankcs/HanLP#1032]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕

## 版本号

当前最新版本号是：1.7.0
我使用的版本是：1.7.0

## 我的问题
北京百度网讯科技有限公司，用感知机分词永远都是一个词，用learn手动分开既然没用

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

```
   PerceptronLexicalAnalyzer analyzer = new PerceptronLexicalAnalyzer();
   analyzer.learn("北京 百度 网讯 科技 有限公司")
   analyzer.analyze("北京百度网讯科技有限公司");
```
### 期望输出

```
[北京/ns 百度/nz 网讯/n 科技/n 有限公司/n]/nt
```

### 实际输出

```
北京百度网讯科技有限公司/nt
```

**Comment by hankcs** [comment]
```        
analyzer.enableCustomDictionary(false);
```

**Comment by zzl221000** [comment]
@hankcs  谢谢
