### ISSUE TITLE
欢迎参加HanLP线下技术交流会

### ISSUE THREAD

**Issue by hankcs** [hankcs/HanLP#1034]
感谢大家对HanLP的支持，欢迎参与12月7号于青岛举办的HanLP主题论坛。这次论坛由大快搜索举办，在美丽的海滨城市崂山举行。主题包括Hadoop解决方案DKH、FreeRCH2和HanLP。会后有崂山爬山、游园和农家宴等活动。宾至如归，公司负责会议期间的住宿和餐食。

HanLP主题论坛将介绍HanLP1.7的技术干货，并且会发布HanLP2.0的消息。现在**征集两位开发者**（个人或公司）分享自己的开发案例，欢迎大家踊跃报名。详细的介绍请参考[
会议介绍](https://github.com/hankcs/HanLP/files/2617987/2018.docx)和[邀请函](https://github.com/hankcs/HanLP/files/2617988/2018.docx)。

感兴趣的朋友可以直接留下联系方式，也可以通过如下方式咨询主办方：

联 系 人：赵金鹏
联系电话：15554211163
尊席诚待，特此盛邀！

**Comment by hankcs** [comment]
诸位有空吗？@AnyListen @TylunasLi @Samurais @jimichan @stevewyl @wupeiwen @JiongZhu @JohnsonYoung630 @shikeio @liangpz521 @pengcong90 @xuxuanbo @yangbajing @beyai @KennFalcon @donbeave

**Comment by jimichan** [comment]
在上海，好远 @hankcs 两天的活动你也出现参加么

**Comment by AnyListen** [comment]
12 月 7 号正在出差中 (；′⌒`)

**Comment by hankcs** [comment]
太遗憾了，我现在也不在中国。

**Comment by gaoyongbing** [comment]
尽量去，但不保证，近期事情太多了

发自我的 iPhone

**Comment by jimichan** [comment]
@hankcs 你不在的话 飞过去也没啥意思 😆

**Comment by Samurais** [comment]
感谢邀请，我在北京，公司事情比较多，不能前往，遥祝大家玩的开心！

**Comment by KennFalcon** [comment]
抱歉，刚看到邮件，在杭州，可能无法到达，谢谢邀请

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
