### ISSUE TITLE
import pyhanlp后jupyter notebook无法print

### ISSUE THREAD

**Issue by kingzone** [hankcs/HanLP#1039]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕

## 版本号

当前最新版本号是：
我使用的版本是：最新版

## 我的问题
jupyter notebook中import pyhanlp后无法print出任何内容

**Comment by kingzone** [comment]
原因是pyhanlp会重定向输出到日志中，如下恢复stdout，即可在jupyter notebook打印
`import sys 
nb_stdout = sys.stdout
import pyhanlp
# from pyhanlp import *
sys.stdout = nb_stdout`

**Comment by hankcs** [comment]
谢谢反馈，HanLP的Java代码有日志，Python部分好像没有日志。我再确认下。

**Comment by meidongyang** [comment]
> 原因是pyhanlp会重定向输出到日志中，如下恢复stdout，即可在jupyter notebook打印
> import sys
> nb_stdout = sys.stdout
> import pyhanlp
> sys.stdout = nb_stdout

有用，但希望在下一个版本修复这个问题

**Comment by hankcs** [comment]
pyhanlp没有重新向日志，应该是jpype重新向的。
