### ISSUE TITLE
使用pyhanlp进行分词时意外停止报错Process finished with exit code -1073740940 (0xC0000374)

### ISSUE THREAD

**Issue by jwc19890114** [hankcs/HanLP#1045]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.3.4
我使用的版本是：1.3.4

## 我的问题

语料库是wiki繁体最新版本
在两次操作的时候都会报错
1.繁体转简体
2.使用感知机分词
都是运行到第57行报Process finished with exit code -1073740940 (0xC0000374)

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

# coding=utf8
from opencc import OpenCC
import codecs,sys
from pyhanlp import *
'''
使用感知机进行分词，需要调用
PerceptronLexicalAnalyzer = JClass('com.hankcs.hanlp.model.perceptron.PerceptronLexicalAnalyzer')
analyzer = PerceptronLexicalAnalyzer()
seg=analyzer.seg(sentence)
'''
def cut_words(sentence):
    #print sentence
    # seg=HanLP.segment(sentence)
    PerceptronLexicalAnalyzer = JClass('com.hankcs.hanlp.model.perceptron.PerceptronLexicalAnalyzer')
    analyzer = PerceptronLexicalAnalyzer()
    seg=analyzer.seg(sentence)
    print(seg)
    print(type(seg))
    list=[]
    for s in seg:
        list.append(s.word)
    condition = lambda t: t != " "
    new_list = filter(condition, list)
    after_cut = " ".join(new_list)
    return after_cut

filepath=r'C:\Users\01\Desktop\【】NLP\[01]learning-file\wiki.zh.text'
f=codecs.open('wiki.zh.jian2.txt','r',encoding="utf8")
target = codecs.open("wiki.zh.seg.txt", 'w',encoding="utf8")
line_num=1
line = f.readline()

while line:
    print('---- processing ', line_num, ' article----------------')
    line_seg=cut_words(line)
    target.writelines(line_seg)
    print(line_seg)
    line_num = line_num + 1
    line = f.readline()
f.close()
target.close()
exit()

**Comment by frfy** [comment]
> 可能是由于维基中的表情符引起的，参考：#971

不是由的，在提取关键词中也遇到了这个问题，能跑部分结果但是跑到中间突然就意外停止

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
