### ISSUE TITLE
getAccuracy的返回值个数如何控制？

### ISSUE THREAD

**Issue by HitomeRyuu** [hankcs/HanLP#1049]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.7.0
我使用的版本是：1.7.0

## 我的问题
请教一下模型训练，也就是PerceptronTrainer里面的getAccuracy函数何时会返回一个准确度p，何时又会返回三个值p、r、f。这个返回是和语料有关吗？请问有明确的标准使得训练结果能得到一个p值或得到3个值吗？谢谢！

**Comment by hankcs** [comment]
这与具体任务有关，与语料库无关。对于POS，metric就是Accuracy，而CWS和NER的metric都是P、R、F1。这无法也无需控制，如果真的需要用另一种metric去度量准确率，请重载train方法实现自己的metric计算。
