### ISSUE TITLE
女士、先生、老师（姓+职位）之类的人名无法识别

### ISSUE THREAD

**Issue by vhuabigger** [hankcs/HanLP#105]
例如：
赵科长 
李女士 
朱女士 
张老师 
张女士 
侯女士
相似的应该还：王医生、周律师等 
这点是否可以改进下

**Comment by hankcs** [comment]
已经做出了改进：
https://github.com/hankcs/HanLP/commit/bfe9f7cce68fb3fd52a2cc148e43b7e3a71a92b8
https://github.com/hankcs/HanLP/commit/7934e40ad00e2f9fb5adf98d9126c051f8782051

由于人民日报并不将王医生作为一个人名，所以上述补丁的作用有限。

**Comment by vhuabigger** [comment]
大神辛苦，还有一个问题 ，我有一个句子是【南阳信威招标代理有限公司开标厅】，但是分出来的是【南/b、阳信威招标代理有限公司开标厅/nt】，我在自定义词典中添加了【南阳信威招标代理有限公司开标厅 nt 1024】但还是不行，分出来的结果是一样的，另外貌似我每次在自定义词典中添加新词都需要删除对应的bin文件，这点可以改进下吗（哈哈，主要是太懒了）？还有个地方不知道怎么使用，就是停止词，我看了下停止词，里面应该是有标点符号的，但是我每次分出来的词都是带有标点的，这个是需要在什么地方启用吗？

**Comment by hankcs** [comment]
0. https://github.com/hankcs/HanLP#8-用户自定义词典
0. 文档和demo里其实都有，恕不一一代查。
