### ISSUE TITLE
请问hanlp有没有类似jieba分词的全模式

### ISSUE THREAD

**Issue by mimimiracle** [hankcs/HanLP#1052]
比如：
“我来到北京清华大学”
用jieba分词：
【全模式】: 我/ 来到/ 北京/ 清华/ 清华大学/ 华大/ 大学
【精确模式】: 我/ 来到/ 北京/ 清华大学
全模式把特殊名词之类的切分出来之后，还可以继续切分下去，hanlp有类似的功能吗

**Comment by AnyListen** [comment]
enbaleIndexMode(true) 即可；还可以设置最细粒度 enbaleIndexMode(1)

**Comment by mimimiracle** [comment]
> enbaleIndexMode(true) 即可；还可以设置最细粒度 enbaleIndexMode(1)

非常感谢！
