### ISSUE TITLE
用来做搜索分词，但是时间有点慢，怎么办？

### ISSUE THREAD

**Issue by yuye2133** [hankcs/HanLP#1053]
query很短，一般在2-6个词之间，但是要使用40ms的时间，请问这是正常的吗？还是我调用方法不对呀。。

**Comment by jimichan** [comment]
要想解决问题，你得提供上下文，没头没尾的来一句，无法回答

**Comment by hankcs** [comment]
你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真填写，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
![issue](http://wx1.sinaimg.cn/large/006Fmjmcly1ft2hnlwc22j30q90bcgpe.jpg)
