### ISSUE TITLE
如何设置自定义词典最高优先级级 不管其他词分词效果

### ISSUE THREAD

**Issue by whyhuiyan** [hankcs/HanLP#1054]
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

当前最新版本号是：HanLP v1.2.8
我使用的版本是：portable-1.7.0

## 我的问题

自定义了一批词，并使词具有统一的词性，但是部分词未按自定义词典分词；我不需要考虑其它分词的准确性，只要求自定义的词被全部识别。谢谢

    public void testIssue1234() throws Exception
    {
        CustomDictionary.insert("中关村科技","company  10");
        CustomDictionary.insert("人民网","company  10");

       HanLP.newSegment().enableCustomDictionaryForcing(true);
        System.out.println(HanLP.segment("人民网，中关村科技园区管理委员会副巡视员刘航介绍了"));
    }

 期望输出
[人民网/company, ，/w, 中关村科技/company，园区/ns, 管理/vn, 委员会/n, 副/b, 巡视员/n, 刘航/nr, 介绍/v, 了/ul]

实际输出
[人民网/company, ，/w, 中关村/ns, 科技园区/ns, 管理/vn, 委员会/n, 副/b, 巡视员/n, 刘航/nr, 介绍/v, 了/ul]

**Comment by AnyListen** [comment]
```
Segment segment =  HanLP.newSegment().enableCustomDictionaryForcing(true);
System.out.println(segment.segment("人民网，中关村科技园区管理委员会副巡视员刘航介绍了"));
```

**Comment by Lighfer** [comment]
> ```
> Segment segment =  HanLP.newSegment().enableCustomDictionaryForcing(true);
> System.out.println(segment.seg("人民网，中关村科技园区管理委员会副巡视员刘航介绍了"));
> ```

我这边也有同样的问题, 版本是portable-1.7.1, 下面这段代码:

```java
public static void main(final String[] args) throws Exception {
        String text = "被处罚金200元, 并通报";

        log.debug("使用自定义词典之前: {}", HanLP.newSegment().seg(text));

        CustomDictionary.insert("罚金", "fj 10000000");

        Segment segment =  HanLP.newSegment().enableCustomDictionaryForcing(true);

        log.debug("使用自定义词典之后: {}", segment.seg(text));
}
```

的实际输出是:

```text
使用自定义词典之前: [被/p, 处罚金/nz, 200/m, 元/q, ,/w,  /w, 并/c, 通报/v]
使用自定义词典之后: [被/p, 处罚金/nz, 200/m, 元/q, ,/w,  /w, 并/c, 通报/v]
```

插入词典的词没有起作用,

**Comment by baiziyuandyufei** [comment]
我这里也有类似问题。
/**
 * 第一个Demo，惊鸿一瞥
 *
 * @author hankcs
 */
public class DemoAtFirstSight
{
    public static void main(String[] args)
    {
        System.out.println("首次编译运行时，HanLP会自动构建词典缓存，请稍候……");
        HanLP.Config.enableDebug();         // 为了避免你等得无聊，开启调试模式说点什么:-)
        HanLP.newSegment().enableCustomDictionaryForcing(true);
        System.out.println(HanLP.segment("私信必回"));
    }
}
期望输出 私信 必回
实际输出 
首次编译运行时，HanLP会自动构建词典缓存，请稍候……
Feb 07, 2019 8:38:44 PM com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
信息: 自定义词典开始加载:data/dictionary/custom/CustomDictionary.txt
Feb 07, 2019 8:38:44 PM com.hankcs.hanlp.dictionary.CustomDictionary <clinit>
信息: 自定义词典加载成功:3312个词条，耗时50ms
Feb 07, 2019 8:38:44 PM com.hankcs.hanlp.dictionary.CoreDictionary load
信息: 核心词典开始加载:data/dictionary/CoreNatureDictionary.txt
Feb 07, 2019 8:38:44 PM com.hankcs.hanlp.dictionary.CoreDictionary <clinit>
信息: data/dictionary/CoreNatureDictionary.txt加载成功，153093个词条，耗时38ms
粗分词网：
0:[ ]
1:[私, 私信]
2:[信, 信必]
3:[必]
4:[回]
5:[ ]

Feb 07, 2019 8:38:44 PM com.hankcs.hanlp.dictionary.CoreBiGramTableDictionary <clinit>
信息: 开始加载二元词典data/dictionary/CoreNatureDictionary.ngram.txt.table
Feb 07, 2019 8:38:44 PM com.hankcs.hanlp.dictionary.CoreBiGramTableDictionary <clinit>
信息: data/dictionary/CoreNatureDictionary.ngram.txt.table加载成功，耗时136ms
粗分结果[私/ag, 信必/nz, 回/v]
Feb 07, 2019 8:38:44 PM com.hankcs.hanlp.dictionary.nr.PersonDictionary <clinit>
信息: data/dictionary/person/nr.txt加载成功，耗时80ms
人名角色观察：[  K 1 A 1 ][私 D 6 ][信必 A 20833310 ][回 L 45 B 16 K 12 C 1 ][  K 1 A 1 ]
人名角色标注：[ /K ,私/D ,信必/A ,回/K , /K]
[私/ag, 信必/nz, 回/v]

我已经把CoreNatureDictionary.txt中的“信必”这个词语删掉了，而且在CustomDictionary.txt中增加了“必回 v 1000”。还有，值得注意的是，加载CustomDictionary.txt的信息中加载词条数跟实际的CustomDictionary.txt中的行数不一致，实际添加了“必回”之后行数为3314行，但是调试信息显示只加载了3312行。还有就是从CoreNatureDictionary.txt中删除了“信必”后，行数实际为153092行，但是调试信息显示加载了153093个词条，感觉程序读取的完全不是看到的这几张词表。

@AnyListen

**Comment by msute** [comment]
> 请确认下列注意事项：
> 
> * 我已仔细阅读下列文档，都没有找到答案：
>   
>   * [首页文档](https://github.com/hankcs/HanLP)
>   * [wiki](https://github.com/hankcs/HanLP/wiki)
>   * [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
> * 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
> * 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
> * [x]  我在此括号内输入x打钩，代表上述事项确认完毕。
> 
> 当前最新版本号是：HanLP v1.2.8 我使用的版本是：portable-1.7.0
> 
> ## 我的问题
> 自定义了一批词，并使词具有统一的词性，但是部分词未按自定义词典分词；我不需要考虑其它分词的准确性，只要求自定义的词被全部识别。谢谢
> 
> ```
> public void testIssue1234() throws Exception
> {
>     CustomDictionary.insert("中关村科技","company  10");
>     CustomDictionary.insert("人民网","company  10");
> 
>    HanLP.newSegment().enableCustomDictionaryForcing(true);
>     System.out.println(HanLP.segment("人民网，中关村科技园区管理委员会副巡视员刘航介绍了"));
> }
> ```
> 
> 期望输出 [人民网/company, ，/w, 中关村科技/company，园区/ns, 管理/vn, 委员会/n, 副/b, 巡视员/n, 刘航/nr, 介绍/v, 了/ul]
> 
> 实际输出 [人民网/company, ，/w, 中关村/ns, 科技园区/ns, 管理/vn, 委员会/n, 副/b, 巡视员/n, 刘航/nr, 介绍/v, 了/ul]

请问你这个问题是否已经解决了？我现在遇到同样问题，自定义的词典里，有些词与原生自带词典冲突，即使删除了也无法使用我自定义的

**Comment by zzx1314** [comment]
请问这个问题应该怎么解决，我也遇到了同样的问题
