### ISSUE TITLE
旧版的data文件404了

### ISSUE THREAD

**Issue by Lighfer** [hankcs/HanLP#1058]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.7.1
我使用的版本是：1.6.4

## 我的问题

从releases页面中，找到v1.6.4常规维护版, 里面的 data-for-1.6.4.zip 链接失效了, 404

**Comment by hankcs** [comment]
你好，由于服务器磁盘有限，旧版数据包将会依序删除。推荐使用最新版，或使用git checkout相应版本data。
