### ISSUE TITLE
使用繁體分詞後，髮變發

### ISSUE THREAD

**Issue by gunblues** [hankcs/HanLP#1059]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.7.1
我使用的版本是：1.6.8

## 我的问题
使用 TraditionalChineseTokenizer.segment 來分詞 "飛利浦整髮造型吹風梳"

### 期望输出

```
[飛利浦/ntc, 整髮/v, 造型/n, 吹風/vn, 梳/v]
```

### 实际输出

```
[飛利浦/ntc, 整發/v, 造型/n, 吹風/vn, 梳/v]
```

### 其他信息
用NLPTokenizer.analyze來分詞則是期望的輸出

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。
