### ISSUE TITLE
关于句法分析的问题

### ISSUE THREAD

**Issue by lxj0276** [hankcs/HanLP#106]
我现在可以利用hanlp进行句法分析，我看到你另外一个项目https://github.com/hankcs/MainPartExtractor，是关于提取句子主干的，我想问一下，我得到句法分析结果以后，我怎么来提取句子主干呢

**Comment by hankcs** [comment]
需要自己编写规则。

**Comment by lxj0276** [comment]
难道不能直接调用你写好的这个程序吗，哈哈哈

**Comment by hankcs** [comment]
一个是短语结构树，一个是依存结构树。

**Comment by lxj0276** [comment]
可以帮我编译一下吗，我电脑里没有java环境，没用过java

**Comment by hankcs** [comment]
对不起，请容我谢绝。

**Comment by hankcs** [comment]
现在有点忙，下一版本的发布时间应该马上了。

**Comment by lxj0276** [comment]
好的~

**Comment by lxj0276** [comment]
我编译完了，配置的时候，提示“Class com.hankcs.nlp.lex not found”，具体不清楚哪里出问题了。我是把javaee-web-api-6.0.jar，jcl-over-slf4j-1.6.4.jar，logback-classic-0.9.28.jar，MainPartExtractor-1.0.jar，slf4j-api-1.6.4.jar，stanford-parser-3.3.1.jar这些放到一个文件里的

**Comment by hankcs** [comment]
这两个项目根本风马牛不相及，不用瞎搞了。

**Comment by hankcs** [comment]
一个是用斯坦福的库，一个是我自己写的，不能搞一块的。
