### ISSUE TITLE
pyhanlp支持word2vec模型训练吗？

### ISSUE THREAD

**Issue by defineconst** [hankcs/HanLP#1060]
pyhanlp支持word2vec模型训练吗？谢谢！

**Comment by defineconst** [comment]
from pyhanlp import *

WordVectorModel = JClass('com.hankcs.hanlp.mining.word2vec.WordVectorModel')
DocVectorModel = JClass('com.hankcs.hanlp.mining.word2vec.DocVectorModel')
Word2VecTrainer = JClass('com.hankcs.hanlp.mining.word2vec.Word2VecTrainer')

TRAIN_FILE_NAME = '搜狗文本分类语料库已分词.txt'
MODEL_FILE_NAME = "word2vec.txt"

# 训练模型
trainerBuilder = Word2VecTrainer()
word2vec = trainerBuilder .train(TRAIN_FILE_NAME, MODEL_FILE_NAME);
doc2vec = DocVectorModel(word2vec)

是这样训练吗？多谢！

**Comment by hankcs** [comment]
是的

**Comment by defineconst** [comment]
> 是的

谢谢回复！

**Comment by ieliwb** [comment]
谢谢
