### ISSUE TITLE
关于分词问题

### ISSUE THREAD

**Issue by huangxz** [hankcs/HanLP#1065]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.7.1
我使用的版本是：1.7.1

## 我的问题
最近下载最新的版本1.7.1，运行 DemoCRFLexicalAnalyzer 和 DemoPerceptronLexicalAnalyzer 测试分词，发现 微软公司於1975年由比爾·蓋茲和保羅·艾倫創立，18年啟動以智慧雲端、前端為導向的大改組。对于人名的识别不对，以前版本我记得是没问题的。现在分词的结果是：
微软公司/ntc 於/p 1975年/t 由/p 比爾·蓋茲/n 和/c 保羅·艾倫/nr 創立/v ，/w 18年/t 啟動/v 以/p 智慧/n 雲端/n 、/w 前端/f 為/v 導向/n 的/u 大/a 改組/vn 。/w

## 复现问题
运行 DemoCRFLexicalAnalyzer 类中的方法

### 步骤
运行 DemoCRFLexicalAnalyzer 类中的方法

### 触发代码
public static void main(String[] args) throws IOException
    {
        CRFLexicalAnalyzer analyzer = new CRFLexicalAnalyzer();
        analyzer.enableAllNamedEntityRecognize(true)
        .enableCustomDictionary(true)
        .enableOrganizationRecognize(true)
        .enablePartOfSpeechTagging(true)
        .enableTranslatedNameRecognize(true)
        .enableNameRecognize(true);
        
        String[] tests = new String[]{
            "商品和服务",
            "上海华安工业（集团）公司董事长谭旭光和秘书胡花蕊来到美国纽约现代艺术博物馆参观",
            "微软公司於1975年由比爾·蓋茲和保羅·艾倫創立，18年啟動以智慧雲端、前端為導向的大改組。", 
            "微软公司於1975年由比尔·盖茨和保罗·艾伦创立，18年启动以智慧云端、前端为导向的大改组。" 
        };
        for (String sentence : tests)
        {
            System.out.println(analyzer.analyze(sentence));
//            System.out.println(analyzer.seg(sentence));
        }
    }

期望输出
微软公司/ntc 於/p 1975年/t 由/p 比爾·蓋茲/nrf 和/c 保羅·艾倫/nrf 創立/v ，/w 18年/t 啟動/v 以/p 智慧/n 雲端/n 、/w 前端/n 為/v 導向/n 的/u 大/a 改組/vn 。/w

实际输出
微软公司/ntc 於/p 1975年/t 由/p 比爾·蓋茲/n 和/c 保羅·艾倫/v 創立/v ，/w 18年/t 啟動/v 以/p 智慧/n 雲端/n 、/w 前端/n 為/v 導向/n 的/u 大/a 改組/vn 。/w
存在问题的地方：比爾·蓋茲/n 和/c 保羅·艾倫/v
这两个人名识别不对。

**Comment by hankcs** [comment]
MD5 (data/model/perceptron/pku199801/pos.bin) = 7ee5ee87b5800f28dbc88d11fe11ab02

微软公司/ntc 於/p 1975年/t 由/p 比爾·蓋茲/n 和/c 保羅·艾倫/nr 創立/v ，/w 18年/t 啟動/v 以/p 智慧/n 雲端/n 、/w 前端/f 為/v 導向/n 的/u 大/a 改組/vn 。/w

**Comment by huangxz** [comment]
您好，不好意，我检查了data/model/perceptron/pku199801/pos.bin 的md5值是一样的
![image](https://user-images.githubusercontent.com/10459338/50624877-02839b80-0f5f-11e9-8d4f-775d56496172.png)

**Comment by hankcs** [comment]
感谢指出，data/model/perceptron/pku199801/pos.bin是感知机模型，一切正常。但CRF模型的确未能正确预测词性，可选择自行训练pos模型。
