### ISSUE TITLE
pyhanlp in flask

### ISSUE THREAD

**Issue by defineconst** [hankcs/HanLP#1069]
您好。
我想基于flask，把pyhanlp做成一个服务，比如词向量模型。如下：
@app.route('/NLPWordNearest', methods=['POST'])
def NLPWordNearest():
    Word = request.form.get('Word')
    WordVectorModel = JClass('com.hankcs.hanlp.mining.word2vec.WordVectorModel')
    MODEL_FILE_NAME = r"E:\NLP\Model.txt"
    # 初始化模型
    word2vec = WordVectorModel(MODEL_FILE_NAME)

    if word2vec != None:
        word = word2vec.nearest(Word)
        return getResult(word)
    else:
        rst = make_response(errorResp("单词分析错误！"))
        rst.headers['Access-Control-Allow-Origin'] = '*'
        return rst

系统没有报错，可加载模型后服务自动死掉了。

port:9999
 * Debugger is active!
 * Debugger PIN: 284-694-472
 * Running on http://0.0.0.0:9999/ (Press CTRL+C to quit)

Process finished with exit code -1

谢谢！

**Comment by w392807287** [comment]
JClass换成SafeJClass试试。应该是多线程的问题

**Comment by achenjie** [comment]
您好，有没有试过在基于 python  flask做成一个服务，调用DocVectorModel

**Comment by hankcs** [comment]
你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真填写，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
![issue](http://wx1.sinaimg.cn/large/006Fmjmcly1ft2hnlwc22j30q90bcgpe.jpg)
