### ISSUE TITLE
求问demo（hanlp.com）里面用的分词器和依存句法分析器

### ISSUE THREAD

**Issue by iamyuchen** [hankcs/HanLP#1070]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕

## 版本号

当前最新版本号是：
我使用的版本是：1.7.1

## 我的问题
请问demo（http://hanlp.com）使用了什么分词器和依存分析器？

我在demo上测了一些句子，发现效果比较好，然而在本地使用1.7.1代码测试。发现和demo有很大差距

1. 首先是分词器。
NeuralNetworkDependencyParser.compute(String sentence)使用的是CharacterBasedSegment，无法使用自定义词典，所以效果不太好。我给替换成了ViterbiSegment分词器，效果还可以，但是和demo还是有些出入，想问下demo中使用的分词器是哪个？

2. 依存句法分析器
测试句子：我送她一束花

demo的结果：
![21_05_33__01_02_2019](https://user-images.githubusercontent.com/11264714/50593202-56946e80-0ed2-11e9-9947-df12a1505ac3.jpg)

本地测试代码：
NeuralNetworkDependencyParser dependencyParser = new NeuralNetworkDependencyParser();
dependencyParser.setSegment(new ViterbiSegment());
System.out.println(dependencyParser.parse("我送她一束花。"));
本地测试结果：
![21_07_51__01_02_2019](https://user-images.githubusercontent.com/11264714/50593297-c0ad1380-0ed2-11e9-833f-b64f84158655.jpg)

试了一些句子，并没有分析出间宾关系，然而demo中可以正常分析出。所以想请问下demo中使用的依存句法分析器有什么不同，谢谢！

**Comment by hankcs** [comment]
开源项目欢迎直接看代码：https://github.com/hankcs/pyhanlp/blob/master/pyhanlp/server.py#L34

**Comment by pxxgogo** [comment]
我发现了一个相似的问题，目前是1.7.3版本。 目前做依存树分析默认的分词器应该是NLPTokenizer（感知机）。我用这个server.py自己搭了一个demo服务器，发现依存树解析结果和官网demo的结果不同。就拿上面“我送她一束花” 举例。 自己搭的服务器，分词会把“一束花”分在一起。 请问是因为用的模型不同，还是说分词方法不同？

**Comment by hankcs** [comment]
> 我发现了一个相似的问题，目前是1.7.3版本。 目前做依存树分析默认的分词器应该是NLPTokenizer（感知机）。我用这个server.py自己搭了一个demo服务器，发现依存树解析结果和官网demo的结果不同。就拿上面“我送她一束花” 举例。 自己搭的服务器，分词会把“一束花”分在一起。 请问是因为用的模型不同，还是说分词方法不同？

官网没挂那么多词典。

**Comment by pxxgogo** [comment]
> > 我发现了一个相似的问题，目前是1.7.3版本。 目前做依存树分析默认的分词器应该是NLPTokenizer（感知机）。我用这个server.py自己搭了一个demo服务器，发现依存树解析结果和官网demo的结果不同。就拿上面“我送她一束花” 举例。 自己搭的服务器，分词会把“一束花”分在一起。 请问是因为用的模型不同，还是说分词方法不同？
> 
> 官网没挂那么多词典。

感谢！

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
