### ISSUE TITLE
NLPTokenizer分词可能存在bug，分词时不能按用户自定义词典切分

### ISSUE THREAD

**Issue by Helen0804** [hankcs/HanLP#1072]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [ ] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：portable-1.7.1
我使用的版本是：portable-1.7.1

## 我的问题

NLPTokenizer分词可能存在bug，分词时不能按用户自定义词典切分

### 触发代码

```
    public static void main(String[] args) throws IOException
    {
      		CustomDictionary.insert("晚霞", "wx 1");
		System.out.println(NLPTokenizer.segment("我的希望是希望张晚霞的背影被晚霞映红"));
        // 注意观察下面两个“希望”的词性、两个“晚霞”的词性
		System.out.println(NLPTokenizer.analyze("我的希望是希望张晚霞的背影被晚霞映红").translateLabels());
    }
```
### 期望输出

```
[我/r, 的/u, 希望/n, 是/v, 希望/v, 张晚霞/nr, 的/u, 背影/n, 被/p, 晚霞/wx, 映红/nr]
我/代词 的/助词 希望/名词 是/动词 希望/动词 张晚霞/人名 的/助词 背影/名词 被/介词 晚霞/wx 映红/人名
```

### 实际输出

```
[我/r, 的/u, 希望/n, 是/v, 希望/v, 张晚霞/nr, 的/u, 背影/n, 被/p, 晚霞/n, 映红/nr]
我/代词 的/助词 希望/名词 是/动词 希望/动词 张晚霞/人名 的/助词 背影/名词 被/介词 晚霞/wx 映红/人名
```

**Comment by leestar123** [comment]
在代码里加上：NLPTokenizer.ANALYZER.enableCustomDictionaryForcing(true);
然后就会强制使用你定义的词典了

**Comment by Helen0804** [comment]
测试了没有改善

**Comment by hankcs** [comment]
NLPTokenizer.ANALYZER.enableCustomDictionaryForcing(true).enableAllNamedEntityRecognize(false);
        CustomDictionary.insert("晚霞", "wx 1");
        System.out.println(NLPTokenizer.segment("我的希望是希望张晚霞的背影被晚霞映红"));

**Comment by Helen0804** [comment]
NLPTokenizer.ANALYZER.enableCustomDictionaryForcing(true).enableAllNamedEntityRecognize(true);
两者能兼容吗？
