### ISSUE TITLE
chisquareScore = stats.n * Math.pow(N11 * N00 - N10 * N01, 2) / ((N11 + N01) * (N11 + N10) * (N10 + N00) * (N01 + N00))计算值溢出

### ISSUE THREAD

**Issue by sd1026203** [hankcs/HanLP#1075]
ChiSquareFeatureExtractor中的这行代码N11等变量均为int型， 计算时会引发数值溢出， 虽然不会报错， 但是计算结果是错误的
2000L * 82 * 2001 * 3919 = 1286074716000
但是实际程序中：
2000 * 82 * 2001 * 3919 = 1879494496，这个值是错误的， 导致卡方检测运算结果其实是错误的

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。
