### ISSUE TITLE
CustomDictionary中返回KeySet

### ISSUE THREAD

**Issue by gfzhx** [hankcs/HanLP#1082]
建议在CustomDictionary用户自定义词典中，增加返回所有Key的方法，目前只能通过getTrie().keySet()返回，但此方法已经不建议使用了，因此建议增加一个返回KeySet的方法，方便直接使用。

**Comment by hankcs** [comment]
你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真填写，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
![issue](http://wx1.sinaimg.cn/large/006Fmjmcly1ft2hnlwc22j30q90bcgpe.jpg)
