### ISSUE TITLE
这个分词分成这样，为啥呢？

### ISSUE THREAD

**Issue by NikolaDai** [hankcs/HanLP#1085]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [ ] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.7.1
我使用的版本是：1.7.1

## 我的问题
分词错误

"努力造就一支忠诚干净担当的高素质干部队伍"分词错误
### 触发代码

```
List<Term> testA = HanLP.segment("努力造就一支忠诚干净担当的高素质干部队伍");
```
### 期望输出

```
期望输出:一支/  忠诚/ 干净
```

### 实际输出

```
一/支忠诚/ 干净
```

## 其他信息
none

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考https://github.com/hankcs/HanLP/commit/86bd21276b19b91753825a4fcb0e58c9808a65bc 。
如果还有问题，欢迎重开issue。
