### ISSUE TITLE
衍生项目之 elasticsearch-hanlp 分词插件包

### ISSUE THREAD

**Issue by AnyListen** [hankcs/HanLP#1087]
项目地址：https://github.com/AnyListen/elasticsearch-analysis-hanlp
兼容范围：ES5.X、ES6.X

基于 HanLP 的 Elasticsearch 中文分词插件，核心功能：
- 内置词典，无需额外配置即可使用；
- 支持用户自定义词典；
- 支持远程词典热更新（待开发）；
- 内置多种分词模式，适合不同场景；
- 拼音过滤器（待开发）；
- 简繁体转换过滤器（待开发）。

**Comment by AnyListen** [comment]
@hankcs 帮忙在 wiki 里面添加一下呢

**Comment by hankcs** [comment]
感谢贡献，已经收录：https://github.com/hankcs/HanLP/wiki/%E8%A1%8D%E7%94%9F%E9%A1%B9%E7%9B%AE#elasticsearch-analysis-hanlp-anylisten
