### ISSUE TITLE
index模式分词问题

### ISSUE THREAD

**Issue by baby1937** [hankcs/HanLP#1089]
问题

句子1：
"减持计划时间过半的进展" 
结果如下：
减持/nz [0:2]
计划/n [2:4]
时间/n [4:6]
过/uguo [6:7]
半/mq [7:8]
的/ude1 [8:9]
进展/vn [9:11]

句子2：
"减持计划时间过半"
结果如下：
减持/nz [0:2]
计划/n [2:4]
时间/n [4:6]
过半/vi [6:8]

为什么“过半”这个词会发生成这样的分词变化，期望是分出来“过半”这个词。能帮忙看下吗？

版本

程序版本号：hanlp-portable-1.7.1
数据版本号：data-for-1.7.1.zip

触发代码
List<Term> termList = IndexTokenizer.segment("减持计划时间过半");

**Comment by baby1937** [comment]
再次呼唤作者，请教下上面这个问题，查了下核心词典是包含“过半”这个词的，如下：
![image](https://user-images.githubusercontent.com/8623402/53542690-98e8cd80-3b5a-11e9-8c66-10871dbde823.png)
另外接续词里也是有“过半@的”这样的接续的，如下：
![image](https://user-images.githubusercontent.com/8623402/53542734-c766a880-3b5a-11e9-8e80-c95984db9873.png)
但就是分成了“过”和“半”，麻烦帮看下什么原因，我需要怎么调整？谢谢。

**Comment by hankcs** [comment]
你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真填写，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
![issue](http://wx1.sinaimg.cn/large/006Fmjmcly1ft2hnlwc22j30q90bcgpe.jpg)
