### ISSUE TITLE
pyhanlp如何调用java版本的聚类方法

### ISSUE THREAD

**Issue by skeletonli** [hankcs/HanLP#1090]
注意事项
请确认下列注意事项：
我已仔细阅读下列文档，都没有找到答案： 
首页文档
wiki
常见问题
我已经通过Google和issue区检索功能搜索了我的问题，也没有找到答案。
我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
 我在此括号内输入x打钩，代表上述事项确认完毕。
版本号
当前最新版本号是：
我使用的版本是：hanlp-1.7.0
我的问题：
在 com.hankcs.hanlp.mining.cluster.ClusterAnalyzer 中，ClusterAnalyzer的初始化是用泛型参数：
public class ClusterAnalyzer<K>
{...}
但是jpype中没找到传泛型参数的方法，请问如何用python调用？

**Comment by hankcs** [comment]
https://github.com/hankcs/pyhanlp/blob/4c1a5da4f00877600810c6b34431fc1755b75242/tests/demos/demo_text_clustering.py

**Comment by skeletonli** [comment]
非常感谢
