### ISSUE TITLE
关于复合词的问题

### ISSUE THREAD

**Issue by mdning** [hankcs/HanLP#1094]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：HanLP 1.7.1
我使用的版本是：HanLP 1.7.0

## 我的问题
非常感谢作者提供功能强大的工具。
1.我使用data-for-1.7.1的模型进行分词和词性标记，假如我要处理的句子为：“香港特别行政区的张朝阳说商品和服务是三原县鲁桥食品厂的主营业务。”，按照结构化感知机标注框架中的说明，“香港特别行政区”和“三原县鲁桥食品厂”应该作为复合词出现在结果中，但是我利用感知机模型进行分词时并没有得到说明中的结果。
2.分词结果："[香港/ns, 特别/a, 行政区/n]/ns"表明香港特别行政区是作为一个词进行分割的，和结果：“香港特别行政区/ns”的区别是什么？我的理解是，对于前者，当“香港特别行政区”这几个字出现在一起的时候，作为一个词分割，只出现“香港”的时候，也可以把香港分割出来，比如“香港是购物天堂”会被分成“香港/ns 是/v 购物/v 天堂/n”，而对于后者，如果训练数据中只有标注的“香港特别行政区/ns”，而没有“香港/ns”的标注，关于香港的分割及标记可能会出错。

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

```
    String sentence = "香港特别行政区的张朝阳说商品和服务是三原县鲁桥食品厂的主营业务。";
PerceptronLexicalAnalyzer segmenter = new PerceptronLexicalAnalyzer(
                "data-for-1.7.1\\data\\model\\perceptron\\pku199801\\cws.bin",
                "data-for-1.7.1\\data\\model\\perceptron\\pku199801\\pos.bin");
        Sentence sentence = segmenter.analyze(sentences);
        System.out.println(sentence);
```
### 期望输出
[香港/ns 特别/a 行政区/n]/ns 的/n 张朝阳/nr 说/v 商品/n 和/c 服务/vn 是/v [三原县/ns 鲁桥/nz 食品厂/n]/nt 的/z 主营/vn 业务/n

### 实际输出

香港/ns 特别行政区/nz 的/u 张朝阳/nr 说/v 商品/n 和/c 服务/vn 是/v 三原县/ns 鲁桥/nz 食品厂/n 的/u 主营/vn 业务/n 。/w

**Comment by hankcs** [comment]
Analyzer是Segmenter、POSTagger和NERecognizer的pipleline。复合词是NERecognizer识别的，`特别行政区/nz`来自用户词典。

```java
        PerceptronLexicalAnalyzer analyzer = new PerceptronLexicalAnalyzer();
        analyzer.enableCustomDictionary(false);
        System.out.println(analyzer.analyze("香港特别行政区的张朝阳说商品和服务是三原县鲁桥食品厂的主营业务。"));
        analyzer = new PerceptronLexicalAnalyzer(new PerceptronSegmenter(), new PerceptronPOSTagger());
        analyzer.enableCustomDictionary(false);
        System.out.println(analyzer.analyze("香港特别行政区的张朝阳说商品和服务是三原县鲁桥食品厂的主营业务。"));
```

输出

```
[香港/ns 特别/a 行政区/n]/ns 的/u 张朝阳/nr 说/v 商品/n 和/c 服务/vn 是/v [三原县/ns 鲁桥/ns 食品厂/n]/nt 的/u 主营业务/n 。/w
香港/ns 特别/a 行政区/n 的/u 张朝阳/nr 说/v 商品/n 和/c 服务/vn 是/v 三原县/ns 鲁桥/ns 食品厂/n 的/u 主营业务/n 。/w
```

**Comment by mdning** [comment]
1.“三原县鲁桥食品厂”也是一样的原理吗？因为我在词典中好像没有找到这个词。并不是词典中必须有“三原县鲁桥食品厂/nt”这样的用例，才能识别出这个词，是这样吗？
触发代码：
PerceptronLexicalAnalyzer analyzer = new PerceptronLexicalAnalyzer();
        analyzer.enableCustomDictionary(false);
        System.out.println(analyzer.analyze("香港特别行政区的张朝阳说商品和服务是三原县鲁桥食品厂的主营业务。"));
        isExistDic("香港特别行政区");
        isExistDic("三原县鲁桥食品厂");
        analyzer = new PerceptronLexicalAnalyzer(new PerceptronSegmenter(), new PerceptronPOSTagger());
        analyzer.enableCustomDictionary(false);
        System.out.println(analyzer.analyze("香港特别行政区的张朝阳说商品和服务是三原县鲁桥食品厂的主营业务。"));
        isExistDic("香港特别行政区");
        isExistDic("三原县鲁桥食品厂");
    public static void isExistDic(String word)
    {
        if (HanLP.Config.Normalization) word = CharTable.convert(word);
        if (contains(word))
        {
            System.out.println(word + " : " + "Exist");
        }
        else
        {
            System.out.println(word + " : " + "Not Exist");
        }
    }
实际输出：
香港特别行政区 : Not Exist
三原县鲁桥食品厂 : Not Exist
[香港/ns 特别/a 行政区/n]/ns 的/u 张朝阳/nr 说/v 商品/n 和/c 服务/vn 是/v [三原县/ns 鲁桥/nz 食品厂/n]/nt 的/u 主营/vn 业务/n 。/w
香港/ns 特别/a 行政区/n 的/u 张朝阳/nr 说/v 商品/n 和/c 服务/vn 是/v 三原县/ns 鲁桥/nz 食品厂/n 的/u 主营/vn 业务/n 。/w
香港特别行政区 : Not Exist
三原县鲁桥食品厂 : Not Exist
2.

**Comment by hankcs** [comment]
1. 你可以试试`香港特别行政区的张朝阳说商品和服务是四原县鲁桥食品厂的主营业务。`乃至“五原”“上海”之类的单词
1. 请参考https://github.com/hankcs/HanLP/wiki/%E7%BB%93%E6%9E%84%E5%8C%96%E6%84%9F%E7%9F%A5%E6%9C%BA%E6%A0%87%E6%B3%A8%E6%A1%86%E6%9E%B6

**Comment by HitomeRyuu** [comment]
新增复合词应该只能通过训练新模型或者在线学习已存在的实体得到。词典只能新增识别单词。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
