### ISSUE TITLE
KBeamArcEagerDependencyParser 缺少data文件

### ISSUE THREAD

**Issue by king6065** [hankcs/HanLP#1095]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.7.1
我使用的版本是：1.7.1

## 我的问题

从github上拿的最新代码和data. 使用KBeamArcEagerDependencyParser做句法分析
运行缺少 data/model/dependency/perceptron.bin
和 data/model/perceptron/ctb/pos.bin

**Comment by AnyListen** [comment]
请下载完整版的 data 文件，见 release 页面

**Comment by king6065** [comment]
> 请下载完整版的 data 文件，见 release 页面

就是下的完整的data。里面并没有这两个文件

**Comment by hankcs** [comment]
这是刚刚提交的代码，预计在下一个版本发布模型。
