### ISSUE TITLE
pyhanlp有rasa的组件吗，类似tokenizer_jieba这样的

### ISSUE THREAD

**Issue by xiyuan27** [hankcs/HanLP#1096]
最近在看RASA, 觉得分词组件还是HanLP好，请问pyhanlp有rasa的组件吗，类似tokenizer_jieba这样的？
tokenizer_jieba在下面的里面有介绍
https://blog.csdn.net/u010505246/article/details/82997100
https://www.jianshu.com/u/4b912e917c2e
https://blog.csdn.net/u010505246/article/details/83276354

**Comment by hankcs** [comment]
你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真填写，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
![issue](http://wx1.sinaimg.cn/large/006Fmjmcly1ft2hnlwc22j30q90bcgpe.jpg)

**Comment by hankcs** [comment]
你好，感谢反馈，这是个好主意。

**Comment by hughwang-me** [comment]
所以 支持吗？？
