### ISSUE TITLE
分词中人名识别报错 java.lang.ArrayIndexOutOfBoundsException: 3

### ISSUE THREAD

**Issue by lambo-shan-yym** [hankcs/HanLP#1097]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [ ] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：protable-1.7.1
我使用的版本是：protable-1.7.1

## 我的问题
maven引用protable-1.7.1版本的hanlp,将data 添加到src/main/resource下，并添加hanlp.properties文件
其中root设置为空，设置自定义的适配器，分词时显示
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.ArrayIndexOutOfBoundsException: 3
![image](https://user-images.githubusercontent.com/33078372/53071575-93b5ce00-351d-11e9-8390-4e6a11d7fa0d.png)
如果我把data放在本地下，并设置root为data父目录的绝对路径或把人名识别关闭则不会有报错信息

### 步骤

1. 首先maven引用protable1.7.1
2. 然后将下载的data数据加入resource文件下
![image](https://user-images.githubusercontent.com/33078372/53071864-6584be00-351e-11e9-86b3-d71c68ec64fd.png)
3. 接着自定义适配器，添加hanlp.properties，root置空，设置对应的适配器
![image](https://user-images.githubusercontent.com/33078372/53071922-9664f300-351e-11e9-8b70-f991393dc761.png)
### 触发代码

```
    public static void main(String[] args) {
        HanLP.Config.enableDebug(true);
        String text = "泽田依子是上外日本文化经济学院的外教";
        System.out.println(HanLP.segment(text));
}
```
### 期望输出

```
期望输出 正确的分词结果并且不会抛异常
```

### 实际输出

```
实际输出：输出了分词结果，但是却抛异常了
```

## 其他信息
![image](https://user-images.githubusercontent.com/33078372/53071887-7b927e80-351e-11e9-81c2-33b1c3bf76d2.png)
![image](https://user-images.githubusercontent.com/33078372/53071893-8220f600-351e-11e9-9015-60a0759cc840.png)

**Comment by lambo-shan-yym** [comment]
如果没有io适配器,root设置为相对路径“./”也会报同样的错误
我的jdk是1.8.0_151

**Comment by hankcs** [comment]
你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真填写，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
![issue](http://wx1.sinaimg.cn/large/006Fmjmcly1ft2hnlwc22j30q90bcgpe.jpg)
