### ISSUE TITLE
可以提供隐马维特比训练命名实体的语料格式吗？

### ISSUE THREAD

**Issue by HitomeRyuu** [hankcs/HanLP#1098]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.7.1
我使用的版本是：1.7.1

## 我的问题

hanks你好，在你的帮助下我这边已经熟悉感知机的操作，所以现在想试试用隐马和维特比来训练新实体。
我参照wiki中的https://github.com/hankcs/HanLP/wiki/%E8%A7%92%E8%89%B2%E6%A0%87%E6%B3%A8%E5%91%BD%E5%90%8D%E5%AE%9E%E4%BD%93  进行了仿写，
但是在TestNRDctionaryMaker.java中的语料文件【"data/dictionary/2014_dictionary.txt"】和【D:\JavaProjects\CorpusToolBox\data\2014\】并没有在任何地方找到，希望可以提供该处语料所需的格式，以准备新实体的语料。
我已在relese中下载了最新的data的压缩包并没有找到对应文件，https://github.com/hankcs/HanLP/issues/311  这个issue中所提供的页面也已经找不到了。
感谢您的时间！

**Comment by hankcs** [comment]
Hi，2014语料质量较差，版权隐患较大，所以没有公开。可考虑使用98年语料库做实验，格式是一致的：http://hanlp.linrunsoft.com/release/corpus/pku98.zip 。dictionary.txt应当是自动生成的。

**Comment by HitomeRyuu** [comment]
EasyDictionary.create()和CorpusLoader.walk()都是读取这个语料吗？

**Comment by HitomeRyuu** [comment]
dictionary.txt如果没有的话会直接警告“通用词典data/dictionary/不存在！”，应该不是自动生成的。
如果这两处都填写pku98的话会报错“Exception in thread "main" java.lang.NumberFormatException: For input string: "希望/n"”
我猜想dictionary.txt应该是单独的人名/地名/公司名的词典吧？

**Comment by hankcs** [comment]
的确，在训练NR隐马的时候，dictionary.txt是一个人名词典。任何被包含在dictionary.txt中的词语会根据情况标注为U或Z等角色。你可以从语料库本身提取人名，也可以使用外部的人名词典。

**Comment by HitomeRyuu** [comment]
成功了，在EasyDictionary.create()中添加文件的格式是一行一个（人名实体）单词，在CorpusLoader.walk()中添加的文件是98年语料。这样应该是自动对照98年语料给单词里面的实体训练角色吧。
希望可以帮到其他训练隐马模型的人。

**Comment by huangxz** [comment]
您好，您训练后，会有效果吗？我以前做了NT的
![image](https://user-images.githubusercontent.com/10459338/53866625-ef5b7d80-402c-11e9-9f22-6bf784cbb179.png)
但把训练完的文件，替换到 HanLP\data\dictionary\organization 没发现有区别，不知道这样用法对吗，还请@hankcs 指导一下，谢谢
