### ISSUE TITLE
能否提供中国少数民族的姓名的拾取，精度如何。

### ISSUE THREAD

**Issue by cmdares** [hankcs/HanLP#110]
您好，目前使用您的项目测试中国少数民族姓名拾取情况，精准度不是太好。
如维族、蒙族、藏族人的姓名，希望能够为中国的人名称提取优先做一定的优化，谢谢。

**Comment by hankcs** [comment]
你好，你能提供相应的训练语料吗？

**Comment by cmdares** [comment]
目前只是做了些测试，发现拾取出的结果不大准确。您说的语料，是指人为标引好的句子，其中包含有这些人名，是吗？

**Comment by hankcs** [comment]
对的，巧妇难为无米之炊嘛，人民日报里面没几个少数民族姓名。

**Comment by cmdares** [comment]
http://zhidao.baidu.com/question/535842867.html?fr=iks&word=%C3%C9%D7%E5%C8%CB%D0%D5%C3%FB&ie=gbk
刚找到了一个，你看看这个能否用上，最多也就是词库。

**Comment by cmdares** [comment]
针对DemoChineseNameRecognition 这个测试类的测试用例
增加几个样例：
"签约仪式前，秦光荣、阿布杜勒·哈尼德、阿布来提阿卜杜热西提 、仇和、穆拉帝力、乌兰托雅、斯琴格日乐、 娜仁高娃和宫本正太郎等一同会见了企业家次桑。",
"请收回李西300元钱",
"请收回李硒300元钱",
"请收回李硒任300元钱",
"请收回李任硒300元钱",

看看人名称标引的效果，有一定的问题。

**Comment by hankcs** [comment]
我对这些问题感到厌倦，我利用人民日报这么小的数据集做了一个通用的分词+命名实体识别系统，人们却指望它能用在汉语所有的专门领域。

而人们却从来没想过新闻语境与开放语境的区别，机器学习测试集与全集的巨大不对称性。

**Comment by hankcs** [comment]
人们也从未想过提供任何有质量的领域语料，那为什么要指望我的系统无中生有呢？

**Comment by hankcs** [comment]
这个问题到此为止吧，欢迎提出其他问题。
