### ISSUE TITLE
贝叶斯分类时，增加一条样本后特征百分比骤降

### ISSUE THREAD

**Issue by ray9527** [hankcs/HanLP#1102]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [ ] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.7.2
我使用的版本是：1.7.1

## 我的问题
样本语料库分为4类：
【代理人】：代理人，委托代理人，委托诉讼代理人，辩护人，辩护人王磊
【关键人】：负责人，法定代表人，代表人，法人
【原告】：原告，申请人，上诉人，起诉人，解除保全申请人，申请人（原审原告）
【被告】：被告，被申请人，被上诉人，被起诉人，被上诉人（原审被告）

贝叶斯训练模型：
![image](https://user-images.githubusercontent.com/32827610/53224039-42891400-36ae-11e9-8811-9518f93cca41.png)

在被告目录下增加一条：被申请人（原审原告）

再执行贝叶斯：
![image](https://user-images.githubusercontent.com/32827610/53224096-73694900-36ae-11e9-89ff-16b049f310b0.png)

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

```
    private static void trainAndSaveMode() throws IOException
    {
        IClassifier classifier = new NaiveBayesClassifier(); // 创建分类器，更高级的功能请参考IClassifier的接口定义
        classifier.train(CORPUS_FOLDER);                     // 训练后的模型支持持久化，下次就不必训练了
        IOUtil.saveObjectTo(((NaiveBayesClassifier) classifier).getModel(), MODEL_PATH);
    }

    private static void predict()
    {
        NaiveBayesModel naiveBayesModel =(NaiveBayesModel) IOUtil.readObjectFrom(MODEL_PATH);
        IClassifier naiveBayesClassifier = new NaiveBayesClassifier(naiveBayesModel);
        predict(naiveBayesClassifier, "上诉人（原审被告）");
    }
```
### 期望输出

```
期望输出
```
导致特征获取异常的原因是什么？
随着样本增加，希望特征数选取正常
### 实际输出

```
实际输出
```

**Comment by hankcs** [comment]
你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真填写，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
![issue](http://wx1.sinaimg.cn/large/006Fmjmcly1ft2hnlwc22j30q90bcgpe.jpg)
