### ISSUE TITLE
自定义词库无效问题

### ISSUE THREAD

**Issue by li1996heng** [hankcs/HanLP#1106]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕

## 版本号

当前最新版本号是：1.7.2
我使用的版本是：1.7.2

## 我的问题
![image](https://user-images.githubusercontent.com/24597473/53779150-12593500-3f3a-11e9-8e69-f8983733e830.png)

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

```
    public static void main(String[] args) {
    {
       // 动态增加
        CustomDictionary.add("攻城狮");
        CustomDictionary.add("娶白富美");
        // 强行插入
        CustomDictionary.insert("娶白富美", "nz 1024");
        // 删除词语（注释掉试试）
        CustomDictionary.remove("迎娶");
        System.out.println(CustomDictionary.add("单身狗", "nz 1024 n 1"));
        System.out.println(CustomDictionary.get("单身狗"));

        String text = "攻城狮逆袭单身狗，迎娶白富美，走上人生巅峰";  // 怎么可能噗哈哈！

        // AhoCorasickDoubleArrayTrie自动机扫描文本中出现的自定义词语
        final char[] charArray = text.toCharArray();
        CustomDictionary.parseText(charArray, new 
 AhoCorasickDoubleArrayTrie.IHit<CoreDictionary.Attribute>()
        {
            @Override
            public void hit(int begin, int end, CoreDictionary.Attribute value)
            {
                System.out.printf("[%d:%d]=%s %s\n", begin, end, new String(charArray, begin, end - begin), value);
            }
        });

        // 自定义词典在所有分词器中都有效
        System.out.println(HanLP.segment(text));
    }
```
### 期望输出

```
期望输出  
true
nz 1024 n 1 
[0:3]=攻城狮 nz 1 
[5:8]=单身狗 nz 1024 n 1 
[10:14]=娶白富美 nz 1024 
[11:14]=白富美 nr 33 
[攻城狮/nz, 逆袭/nz, 单身狗/nz, ，/w, 迎/v, 娶白富美/nr, ，/w, 走上/v, 人生/n, 巅峰/n]
```

### 实际输出

```
实际输出  
true
nz 1024 n 1 
[0:3]=攻城狮 nz 1 
[5:8]=单身狗 nz 1024 n 1 
[10:14]=娶白富美 nz 1024 
[11:14]=白富美 nr 33 
[攻城狮/nz, 逆袭/nz, 单身狗/nz, ，/w, 迎娶/v, 白富美/nr, ，/w, 走上/v, 人生/n, 巅峰/n]
```

**Comment by hankcs** [comment]
你需要将其加入CoreDictionary，并且加入相应的bigram。或者使用LexicalAnalyzer并enableCustomDictionaryForcing

**Comment by JNUpython** [comment]
HanLP.newSegment().enableCustomDictionaryForcing(true);
我也遇到同样的问题：CustomDictionary.insert("s诉讼", "keyword 1024");
分词：诉讼 可以获得keyword属性，
分词：诉讼事项 结果：诉   讼事    项
自定义词汇不一定能分出来

**Comment by hankcs** [comment]
> HanLP.newSegment().enableCustomDictionaryForcing(true);
> 我也遇到同样的问题：CustomDictionary.insert("s诉讼", "keyword 1024");
> 分词：诉讼 结果： 诉讼 keyword，
> 分词：诉讼事项 结果：诉 讼事 项
> 自定义词汇不一定能分出来

请使用`HanLP.newSegment("感知机").enableCustomDictionaryForcing(true);`
