### ISSUE TITLE
如何ByteArray.createByteArray载入jar包内部的bin文件

### ISSUE THREAD

**Issue by whaozl** [hankcs/HanLP#1108]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：
我使用的版本是：1.6.8

## 我的问题

我使用ByteArray.createByteArray载入jar包内部的bin文件，使用了AhoCorasickDoubleArrayTrie这个结构
想把这个词典bin放到jar包里面，但是直接传入路径报错，我的词典路径是：
com/data/core/element/searchname_element.csv
```
    /**
     * 载入词典
     */
    public static boolean loadDat(String path, AhoCorasickDoubleArrayTrie<String> trie) {
        ByteArray byteArray = ByteArray.createByteArray(path + Predefine.BIN_EXT);
        if (byteArray == null) return false;
        int size = byteArray.nextInt();
        String[] valueArray = new String[size];
        for (int i = 0; i < valueArray.length; ++i)
        {
            valueArray[i] = byteArray.nextString();
        }
        trie.load(byteArray, valueArray);
        return true;
    }
```
调用方法是：
```
        String actPath=dictPath.substring(0, dictPath.lastIndexOf('.'));//去掉文件扩展名
        AhoCorasickDoubleArrayTrie<String> act =new AhoCorasickDoubleArrayTrie<String>();
        try{
            loadDat(actPath, act);//尝试载入
        }catch (Exception ex){
            ex.printStackTrace();
        }
```

### 步骤

复现问题，把该代码放到main函数下即可执行

### 触发代码

```
    public void testIssue1234() throws Exception
    {
        CustomDictionary.add("用户词语");
        System.out.println(StandardTokenizer.segment("触发问题的句子"));
    }
```
### 期望输出

```
我想该代码可以正常载入自己产生的缓存bin词典，通过loadDat载入
```

### 实际输出

```
实实际报出异常，是因为只能载入外部路径吗?不支持jar包里面的路径？
```

**Comment by hankcs** [comment]
com.hankcs.hanlp.corpus.io.ByteArrayOtherStream#createByteArrayOtherStream(java.io.InputStream)

**Comment by whaozl** [comment]
感谢哈，懂了
