### ISSUE TITLE
不能下载数据data-for-1.7.2.zip

### ISSUE THREAD

**Issue by wuxiangli91** [hankcs/HanLP#1113]
不能下载数据data-for-1.7.2.zip

**Comment by tinghaoyang** [comment]
档案连线不稳定，用续传软件下载就可以了

**Comment by CapAllen** [comment]
同样遇到这个问题，用续传软件居然要下一天。。。。已经下载好的好心人能分享一个链接吗

**Comment by hankcs** [comment]
你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真填写，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
![issue](http://wx1.sinaimg.cn/large/006Fmjmcly1ft2hnlwc22j30q90bcgpe.jpg)
