### ISSUE TITLE
使用NLPTokenizer报：data\dictionary\other\CharType.bin (系统找不到指定的文件。)

### ISSUE THREAD

**Issue by SimmsJeason** [hankcs/HanLP#1114]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [ ] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.7.2
我使用的版本是：1.7.2.

## data\dictionary\other\CharType.bin (系统找不到指定的文件。)

##只是一个简单的demo，直接调用NLPTonizer.segment("我的文档内容，篇幅大概有300字"）
执行报错

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

```
System.out.println(NLPTokenizer.segment("部分文档：截止目前，申通、中通、圆通、汇通（现在叫百世）阿里都参了股，还在还剩韵达，不过我估计年内也会入股。"
```
### 期望输出

```
期望输出
```

### 实际输出

```
读取data/dictionary/other/CharType.bin时发生异常java.io.FileNotFoundException: data\dictionary\other\CharType.bin (系统找不到指定的文件。)
```

**Comment by hankcs** [comment]
你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真填写，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
![issue](http://wx1.sinaimg.cn/large/006Fmjmcly1ft2hnlwc22j30q90bcgpe.jpg)

**Comment by aixinalei** [comment]
@SimmsJeason  您解决这个问题了吗？

**Comment by hankcs** [comment]
非portable版要自己配data路径。
