### ISSUE TITLE
spark使用hanlp，提供一种简单的方案

### ISSUE THREAD

**Issue by zhanggok** [hankcs/HanLP#1116]
spark使用hanlp，提供一种简单的方案。我只用分词和自定义词典的功能，搜索了其他类似的问题和答案感觉对我来说太麻烦了，提供一个简单的方案。
一定是在各种Partitions函数里用，我是mapPartitions，自定义词典，我采用下面的代码
     def addStopWord(){
      CustomDictionary.dat.synchronized{
         brdicStopDic.value.foreach(x=> {
          CoreStopWordDictionary.add(x)})
      }
    }
简单就是添加停用词的函数里加锁，因为大数据环境下运行，词典添加多次就多次没有关系，不在乎这点性能，如果不加锁会报ArrayIndexOutOfBoundsException异常，原因很简单，并发调用。上面的函数是个例子，找了个静态对象 CustomDictionary.dat加锁，只要能保证线程安全，用其他对象也一样。

**Comment by hankcs** [comment]
你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真填写，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
![issue](http://wx1.sinaimg.cn/large/006Fmjmcly1ft2hnlwc22j30q90bcgpe.jpg)

**Comment by hankcs** [comment]
感谢分享，这些全局对象的改动未考虑线程安全问题，的确需要用户自行同步。
