### ISSUE TITLE
老白干酒汉字转拼音问题

### ISSUE THREAD

**Issue by ifree711** [hankcs/HanLP#1118]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕

## 版本号

当前最新版本号是：1.7.2
我使用的版本是：1.7.2

## 我的问题

针对中文"老白干酒"的拼音转换问题，正确读音应该为“laobaiganjiu”"lbgj"，使用HanLP.convertToPinyinList()方法得到的是“laobaiqianjiu”。
虽然我通过在拼音字典中添加词项的方式可以解决，想知道这个问题产生的原因？

此外还碰到了“阿=a1,e1”，需要获取某个多音字的所有读音该调用什么方法实现？

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

```
        String text = "老白干酒";
        List<Pinyin> pinyinList = HanLP.convertToPinyinList(text);
        System.out.println(pinyinList);
```
### 期望输出

```
期望输出 laobaiganjiu
```

### 实际输出 

```
实际输出 laobaiqianjiu  干字单独正确，但在老白干酒中被当做了千
```

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。

**Comment by lengyuan** [comment]
新您好。
似乎这个问题并没有修复
在v1.8.3中
老白干儿 正确输出为 lao3 bai2 gan1 er2

但是在下面两个词组里面，干还是输出为qian2
老白干 lao3 bai2 qian2
老白干酒 lao3 bai2 qian2

我想问一下，”干“在pinyin.txt里面只有gan1和gan4两个读音，为什么会输出qian2的拼音？
干=gan1,gan4

谢谢
