### ISSUE TITLE
关于data-for-1.7.2.zip下载慢的问题，提供一个私人云盘链接供大家下载

### ISSUE THREAD

**Issue by Jooeeee** [hankcs/HanLP#1119]
https://drive.google.com/open?id=1NEN5KoPkgw0o_hpENfUyo0sitZtiIORN

**Comment by hankcs** [comment]
你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真填写，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
![issue](http://wx1.sinaimg.cn/large/006Fmjmcly1ft2hnlwc22j30q90bcgpe.jpg)

**Comment by hankcs** [comment]
谢谢热心帮助，现在数据包已经放在了更快的服务器上。

**Comment by Barzarrhey** [comment]
还是很慢诶，我这里20KB/s

**Comment by hankcs** [comment]
这个链接会快一点吗？ http://www.mathcs.emory.edu/~hhe43/hanlp/data-for-1.7.5.zip

**Comment by hankcs** [comment]
> 还是很慢诶，我这里20KB/s

这个链接会快一点吗？ http://www.mathcs.emory.edu/~hhe43/hanlp/data-for-1.7.5.zip

**Comment by Barzarrhey** [comment]
这个快一点啦，稳定在70K左右，谢谢您

发件人: hankcs <notifications@github.com>
答复: hankcs/HanLP <reply@reply.github.com>
日期: 2019年11月19日 星期二 00:39
收件人: hankcs/HanLP <HanLP@noreply.github.com>
抄送: Barzarrhey <pcmosfet@outlook.com>, Comment <comment@noreply.github.com>
主题: Re: [hankcs/HanLP] 关于data-for-1.7.2.zip下载慢的问题，提供一个私人云盘链接供大家下载 (#1119)


还是很慢诶，我这里20KB/s

这个链接会快一点吗？ http://www.mathcs.emory.edu/~hhe43/hanlp/data-for-1.7.5.zip

**Comment by ningshixian** [comment]
http://download.hanlp.com/
这个链接下载速度很快
