### ISSUE TITLE
Where I can find the CI service?

### ISSUE THREAD

**Issue by gustavosizilio** [hankcs/HanLP#1120]
Is this project using continuous integration services (e.g., Travis-CI or Jenkings)? Or has it used at any point of its lifetime?

**Comment by hankcs** [comment]
Hi, sorry for the delay. This project has never used any CI, as it's easy enough to compile in one command:

```
mvn install -DskipTests
```

See [wiki](https://github.com/hankcs/HanLP/wiki/%E7%BC%96%E8%AF%91%E8%BF%90%E8%A1%8C) for more options, you may need a Google translator.

We are planning to release 2.0 version in the summer, which will be Python/TensorFlow based and CI friendly. Our documentation/community will use English as the default language too.

**Comment by gustavosizilio** [comment]
Thanks Very much!
