### ISSUE TITLE
dat分词大部分带“不”字的都分词错误

### ISSUE THREAD

**Issue by endcy** [hankcs/HanLP#1122]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.7.2
我使用的版本是：1.7.2

## 我的问题
@hankcs 使用双数组trie树分词时，发现一个比较影响业务结果的问题：
如果待分词语句中带有“不……”的格式，“……”表示形容词或动词，大部分语句会分词错误，如“不成功”、“不失败”、“不好看”等等，会分词为“不成”+“功”、“不失”+“败”等等，在CoreNatureDictionary.txt词典和用户词典CustomDictionary.txt及现代汉语补充词库.txt等等词典中删除相关词如“不失”、“不成”才能分词成功。
这里的dat分词器，似乎并没有用到CoreNatureDictionary.ngram.txt及ngram.mini等模型（和它们缓存bin文件），利用[#384](https://github.com/hankcs/HanLP/issues/384)的方式修正无效。
使用dat分词器的话，有什么方式能修复这类问题吗？

### 触发代码

```
    public void testIssue1234() throws Exception
    {
        Segment segment = HanLP.newSegment("dat");
        List<Term> termList1 = segment .seg("老是显示不正确");
        List<Term> termList2 = segment .seg("东西不好看，分词不失败是大概率事件");
        //遍历list输出word
    }
```
### 期望输出

```
老是    显示    不    正确
东西    不    好看   ，    分词    不    失败     是    大   概率    事件
```

### 实际输出

```
老是    显示    不正    确
东西    不好    看   分词    不失    败     是    大概    率    事件
```
（这里的“大概率”，分词成了“大概    率”也错误了）
## 其他信息

使用viterbi和crf分词结果是正确的，但是为什么选用dat极速分词，因为我发现在做相似度匹配时，使用dat分词然后使用文档向量相似匹配，效果是最好的，猜测原因可能是大多数word2vec词向量模型的分词采用的是这种极速分词的方式。

**Comment by hankcs** [comment]
极速分词实现的是正向最长匹配，你可以试着实现一下逆向最长匹配。将词典中的每个词逆转，构造dat传入分词器，分词前对文本也先反转，最后对结果中的每个词反转回来。
