### ISSUE TITLE
中文数字切断

### ISSUE THREAD

**Issue by xunyuw** [hankcs/HanLP#113]
hanlp.ViterbiSegment(u‘十二、完成总经理交办的其他工作。’)

十 m
二 m
、 w
完成 v
总经理 nnt
交办 vn
的 ude1
其他 rzv
工作 vn
。 w

**Comment by hankcs** [comment]
[十二/m, 、/w, 完成/v, 总经理/nnt, 交办/vn, 的/ude1, 其他/rzv, 工作/vn, 。/w]

你版本太旧

**Comment by xunyuw** [comment]
好吧，还有个问题，为啥、的词性不是wn

**Comment by hankcs** [comment]
语料不是完美的
