### ISSUE TITLE
依存关系拆分与官网不一致

### ISSUE THREAD

**Issue by humingxinghxs** [hankcs/HanLP#1135]
注意事项
请确认下列注意事项：

我已仔细阅读下列文档，都没有找到答案：
首页文档
wiki
常见问题
我已经通过Google和issue区检索功能搜索了我的问题，也没有找到答案。
我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
 我在此括号内输入x打钩，代表上述事项确认完毕。
**版本号**
当前最新版本号是：1.7.2
我使用的版本是：1.7.2

**我的问题**
依存关系拆分最新版与官网预览不一致

复现问题
步骤
触发代码
   String  chineseSentence = “你爸叫什么?”;
   CoNLLSentence sentence = HanLP.parseDependency(chineseSentence);
        System.out.println(sentence);
        List<WordRelate> wordRelateList = new ArrayList<WordRelate>();
        // 可以方便地遍历它
        for (CoNLLWord word : sentence) {
            System.out.printf("%s --(%s)--> %s\n", word.LEMMA, word.DEPREL, word.HEAD.LEMMA);
            WordRelate wordRelate = new WordRelate();
            wordRelate.setCont(word.LEMMA);
            wordRelate.setId(word.ID);
            wordRelate.setParent(word.HEAD.ID);
            wordRelate.setRelate(RelateEnum.getEnumByKey(word.DEPREL).getRelateTag());
            wordRelate.setPos(word.POSTAG);
            wordRelateList.add(wordRelate);
        }

期望输出
1	你	你	r	r	_	2	定中关系	_	_
2	爸	爸	n	n	_	0	主谓关系	_	_
3	叫	叫	v	v	_	2	核心关系	_	_
4	什么	什么	r	r	_	3	动宾关系	_	_
5	?	?	wp	w	_	3	标点符号	_	_

make
实际输出

1	你	你	r	r	_	2	主谓关系	_	_
2	爸	爸	v	v	_	0	核心关系	_	_
3	叫	叫	v	v	_	2	并列关系	_	_
4	什么	什么	r	r	_	3	动宾关系	_	_
5	?	?	wp	w	_	3	标点符号	_	_

**Comment by hankcs** [comment]
两处用的词性标注模型不一样，演示用的是[98年6个月的大模型](https://pan.baidu.com/s/1kuZLaDriEi3MGhroEBGl5w)。
