### ISSUE TITLE
reload热更新问题

### ISSUE THREAD

**Issue by CCMBChina** [hankcs/HanLP#1136]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.7.2
我使用的版本是：1.7.2

## 我的问题
需要实现载入内存后字典的更新
想达到效果如修改txt词典增加词语后，jar能重新载入
发现提供了CustomDictionary.reload，故使用此api过程中产生了与预期不一致的分词情况

### 步骤

1. 首先在dictionary下新增自定义词典menu.txt,其中有词盒饭 日料，运行如下代码
2. 然后在线程sleep时往词典中新增 真好吃

### 触发代码

```
    public void testIssue1234() throws Exception
    {
         String text = "盒饭日料真好吃"；
         System.out.println(StandardTokenizer.segment(text ));
          Thread.sleep(60000); //此时在新增的词典menu.txt中加入 <真好吃>
         CustomDictionary.reload();
        System.out.println(StandardTokenizer.segment(text));
    }
```
### 期望输出

期望第一次输出：<盒饭> <日料> <真> <好吃>
期望第二次输出：<盒饭> <日料> <真好吃>
期望输出
```

### 实际输出

第一次输出：<盒饭> <日料> <真> <好吃>
第二次输出：<盒饭> <日料> <真> <好吃>

reload并没有更新各个分词器中dat原有数据内容 ，仅更新了 CustomDictionary中自有的dat
```
实际输出
```

## 其他信息

<!-- 任何可能有用的信息，包括截图、日志、配置文件、相关issue等等。-->

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。

**Comment by CCMBChina** [comment]
@hankcs 感谢 请问什么时候合到1.7.2 或者1.7.3

**Comment by hankcs** [comment]
没有固定的计划，建议自行编译。
