### ISSUE TITLE
关键词提取会将 Markdown 语法中的符号计算进去

### ISSUE THREAD

**Issue by GuoZhaoHui628** [hankcs/HanLP#1142]
比如输入如下：

-最短路分词、N-最短路分词
-感知机分词、CRF分词
-极速词典分词
-索引全切分模式
-用户自定义词典

会输出如下：

[-, 分词, 词典]

**Comment by hankcs** [comment]
你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真修改，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
![issue](http://wx1.sinaimg.cn/large/006Fmjmcly1ft2hnlwc22j30q90bcgpe.jpg)
