### ISSUE TITLE
 想知道opennlp训练maxEnt模型的训练参数是什么样子的 初学者 希望不吝赐教

### ISSUE THREAD

**Issue by 826564596** [hankcs/HanLP#1146]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [ ] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.7.2
我使用的版本是：1.6.8

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

```
    public void testIssue1234() throws Exception
    {
        CustomDictionary.add("用户词语");
        System.out.println(StandardTokenizer.segment("触发问题的句子"));
    }
```
### 期望输出

```
期望输出
```

### 实际输出

```
实际输出
```

**Comment by hankcs** [comment]
你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真修改，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
![issue](http://wx1.sinaimg.cn/large/006Fmjmcly1ft2hnlwc22j30q90bcgpe.jpg)

**Comment by 826564596** [comment]
想训练自己的最大熵模型，一直再翻opennlp的文档，发现 opennlp   ParserTrainer 的headRules文档上都没有写他具体是个什么东西。所有就来找你看看能不能给我讲讲那是个啥，希望能提供一下opennlp最大熵模型的训练参数以及headrules文件。谢谢！

**Comment by hankcs** [comment]
HanLP旧版本只是利用了opennlp的maxent代码，没有利用parser，似乎使用的默认超参数。maxent parser已经被神经网络parser替代，不再维护了。

**Comment by 826564596** [comment]
大学生仅供学习，从码农场过来的，想实现一下你那篇最大熵的依存句法分析器。你的最大熵模型是否是从opennlp 命令行CLI 训练的。

**Comment by hankcs** [comment]
> 大学生仅供学习，从码农场过来的，想实现一下你那篇最大熵的依存句法分析器。你的最大熵模型是否是从opennlp 命令行CLI 训练的。

时间太长，不记得了。这篇文章并不好，高阶特征的处理是拍脑袋决定的。
