### ISSUE TITLE
核心词典生成的示例代码出现错误

### ISSUE THREAD

**Issue by starkingpku** [hankcs/HanLP#115]
HanLP版本v1.2.8，示例代码是项目wiki页面用于训练HMM-NGram模型的代码：
`
        final NatureDictionaryMaker dictionaryMaker = new NatureDictionaryMaker();
        CorpusLoader.walk("path/to/your/corpus", new CorpusLoader.Handler()
        {
            @Override
            public void handle(Document document)
            {
                dictionaryMaker.compute(document.getComplexSentenceList());
            }
        });
        dictionaryMaker.saveTxtTo("data/test/CoreNatureDictionary");
`
错误原因是dictionaryMaker.compute()输入的链表存在CompoundWord，而Precompile.java中95行：
`
    public static Word compile(IWord word)
    {
        return compile((Word)word);
    }`
强行将word转为Word所致。

所以我想问，HanLP的API dictionaryMaker.compute()以后打算接受CompoundWord吗？现在wiki页面的调用会出问题。

**Comment by starkingpku** [comment]
另外，我看到在NatureDictionaryMaker.java中有如下的代码：
`
        final NatureDictionaryMaker dictionaryMaker = new NatureDictionaryMaker();
        CorpusLoader.walk("D:\\JavaProjects\\CorpusToolBox\\data\\2014", new CorpusLoader.Handler()
        {
            @Override
            public void handle(Document document)
            {
                dictionaryMaker.compute(CorpusUtil.convert2CompatibleList(document.getSimpleSentenceList(false))); // 再打一遍不拆分的
                dictionaryMaker.compute(CorpusUtil.convert2CompatibleList(document.getSimpleSentenceList(true)));  // 先打一遍拆分的
            }
        });
        dictionaryMaker.saveTxtTo("data/test/CoreNatureDictionary");  `
@hankcs 实际在制作核心词典时真是这么处理两遍吗（一遍不拆分，一遍拆分）？

**Comment by hankcs** [comment]
0. 感谢反馈，wiki的确写得不对。
0. public static Word compile(IWord word)的确有点暴力，最初没想到要将训练接口开放出来。
0. List<IWord>是Java泛型的老毛病，设计得也不优雅。
0. dictionaryMaker.compute()以后会接受CompoundWord的，暂时的解决方案请参考你粘贴出来的NatureDictionaryMaker.java中的代码。
0. 的确处理了两遍，希望分得细的人可以选择单个词，希望分得粗的可以选择复合词，我是中立的。
