### ISSUE TITLE
CollectionUtility.sortMapByValue方法在存在bug

### ISSUE THREAD

**Issue by wyuz1028** [hankcs/HanLP#1159]
v1.72版本存在bug，最新版master中依然存在
com.hankcs.hanlp.classification.utilities.CollectionUtility中
public static <K, V extends Comparable<V>> Map<K, V> sortMapByValue(Map<K, V> input, final boolean desc)方法存在bug
ArrayList<Map.Entry<K, V>> entryList = new ArrayList<Map.Entry<K, V>>(input.size());
中的input.size()应该改为input.entrySet()

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。
