### ISSUE TITLE
最新的jar(1.7.3)包在pyhanlp下有兼容性问题

### ISSUE THREAD

**Issue by hxrain** [hankcs/HanLP#1163]
将pyhanlp库目录中的hanlp-1.7.2.jar换成了hanlp-1.7.3.jar,data目录也更新为最新版后,发现之前跑的好好的程序,现在出现各种缺失元素方法的异常.
维特比分词器好使,感知器分词器不好使.

**Comment by zhangruinan** [comment]
crf分词需要load data文件夹中训练好的`crf.bin.txt`模型, 可以自己对照一下data 里的properties file 里指定的路径是否与data 文件夹一致就好.

**Comment by hxrain** [comment]
不是词典的问题.是java的对象在py中的调用方法有变更.

**Comment by harry0731** [comment]
> 将pyhanlp库目录中的hanlp-1.7.2.jar换成了hanlp-1.7.3.jar,data目录也更新为最新版后,发现之前跑的好好的程序,现在出现各种缺失元素方法的异常.
> 维特比分词器好使,感知器分词器不好使.

我也遇到一樣的問題
錯誤訊息顯示
`TypeError: 'com.hankcs.hanlp.model.crf.CRFLexicalAnalyzer' object is not callable`

**Comment by hankcs** [comment]
```
$ hanlp -v
jar  1.7.3

>>> from pyhanlp import *
>>> CRFLexicalAnalyzer = JClass("com.hankcs.hanlp.model.crf.CRFLexicalAnalyzer")
>>> analyzer = CRFLexicalAnalyzer()
>>> print(analyzer.analyze('ok'))
ok/nr
```

**Comment by hxrain** [comment]
1. 在1.7.3/pyhanlp里面,PerceptronLexicalAnalyzer ,没有seg方法了,调用的时候,出现异常:jpype._jexception.NoSuchElementExceptionPyRaisable: java.util.NoSuchElementException
而调用segment方法就没问题.
2 使用HanLP.newSegment('crf')也一样,没有seg方法了,出异常.

**Comment by hankcs** [comment]
> 1. 在1.7.3/pyhanlp里面,PerceptronLexicalAnalyzer ,没有seg方法了,调用的时候,出现异常:jpype._jexception.NoSuchElementExceptionPyRaisable: java.util.NoSuchElementException
>    而调用segment方法就没问题.
>    2 使用HanLP.newSegment('crf')也一样,没有seg方法了,出异常.

无法复现此问题，我的测试代码：

```python
    CRFLexicalAnalyzer = JClass("com.hankcs.hanlp.model.crf.CRFLexicalAnalyzer")
    analyzer = CRFLexicalAnalyzer()
    print(analyzer.seg("商品和服务"))
```
