### ISSUE TITLE
关于corpus.dependency.CoNll.CoNLLWord类中POSTAG和CPOSTAG的一些歧义性问题。

### ISSUE THREAD

**Issue by pxxgogo** [hankcs/HanLP#1166]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是 1.7.3
我使用的版本是：1.7.3
pyhanlp 0.1.45

## 我的问题

您好，我有个关于句法依存解析的问题。看文档发现com.hankcs.hanlp.corpus.dependency.CoNll.CoNLLWord 类有CPOSTAG和POSTAG两个属性，其中CPOSTAG是粗粒度词性，POSTAG是细粒度词性。然而我在测试demo中那个例子的时候发现似乎不太清楚。例子是：上海华安工业（集团）公司董事长谭旭光和秘书胡花蕊来到美国纽约现代艺术博物馆参观。
其中 谭旭光 和 胡花蕊 的POSTAG是nr， CPOSTAG是nh。 这两个好像类别差别好像非常大。
所以想请问关于这两个属性的具体解释。

## 复现问题
直接调用以下触发代码

### 触发代码

```
t = HanLP.parseDependency("上海华安工业（集团）公司董事长谭旭光和秘书胡花蕊来到美国纽约现代艺术博物馆参观")
for word in t.iterator():  
    print("%d: %s --(%s)--> %s (%s, %s)" % (word.ID, word.LEMMA, word.DEPREL, word.HEAD.LEMMA, word.POSTAG, word.CPOSTAG))
```

### 实际输出

```
1: 上海华安工业（集团）公司 --(定中关系)--> 董事长 (nt, ni)
2: 董事长 --(定中关系)--> 谭旭光 (n, n)
3: 谭旭光 --(主谓关系)--> 来到 (nr, nh)
4: 和 --(左附加关系)--> 胡花蕊 (c, c)
5: 秘书 --(定中关系)--> 胡花蕊 (n, n)
6: 胡花蕊 --(并列关系)--> 谭旭光 (nr, nh)
7: 来到 --(核心关系)--> ##核心## (v, v)
8: 美国纽约现代艺术博物馆 --(动宾关系)--> 来到 (ns, ns)
9: 参观 --(并列关系)--> 来到 (v, v)
```

**Comment by pxxgogo** [comment]
我又找到了CPOSTAG的词性标注表：
https://github.com/hankcs/HanLP/blob/9456aebab678ef0ecfcd0a367d29a04e878c112a/src/main/java/com/hankcs/hanlp/dependency/nnparser/util/PosTagUtil.java
原来POSTAG和CPOSTAG是不同的词性标注表。

**Comment by hankcs** [comment]
是的，CTB标注集跟PKU是两套体系。
