### ISSUE TITLE
词性nx与nz的区别是什么？

### ISSUE THREAD

**Issue by starkingpku** [hankcs/HanLP#117]
在Nature.java中说nz是其他专名，nx是字母专名，这是什么意思？另外，在包com.hankcs.hanlp.utility的Predifine.java预定义了
`/**
             * 专有名词 nx
             */
            TAG_PROPER = "未##专";
`
而没有预定义nz。
我在人民日报语料库中发现“人民网”的词性是nz，不是nt。
那么在程序中，nt、nz、nx到底是如何区别的？

**Comment by lanxinxichen** [comment]
http://www.hankcs.com/nlp/part-of-speech-tagging.html HanLP词性标注集
词语标注集兼容《ICTPOS3.0汉语词性标记集》
词语标注集兼容《现代汉语语料库加工规范——词语切分与词性标注》

**Comment by starkingpku** [comment]
我知道，我是说标注集规范和预定义的有冲突。而且，既然预定义了nx，为什么不预定义nz呢？ @lanxinxichen

**Comment by hankcs** [comment]
0. 并不冲突，nx和nz在更抽象的层次都是专名。正如nrj和nrf都在预定义中对应TAG_PEOPLE一样。
0. 语料是人做的，无法保证其一定完美。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
