### ISSUE TITLE
自定义词 添加到 CustomDictionary 里面就可以被识别，自己加载词典就不被识别

### ISSUE THREAD

**Issue by 99sun99** [hankcs/HanLP#1171]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：
我使用的版本是：

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

```
    public void testIssue1234() throws Exception
    {
        CustomDictionary.add("用户词语");
        System.out.println(StandardTokenizer.segment("触发问题的句子"));
    }
```
### 期望输出

```
期望输出
```

### 实际输出

```
实际输出
```

**Comment by 99sun99** [comment]
sorry for the bad description. I just want to say~
I have already deleted the bin files and add the new dictionary name into the hanlp.properties. And it does not work.
However when I directly add up new words into CustomDictionary.txt. It can successfully identify the new word. 
why?

**Comment by hankcs** [comment]
有触发代码吗？

**Comment by 99sun99** [comment]
CustomDictionaryPath=data/dictionary/custom/CustomDictionary.txt; resume_nouns.txt ns; 现代汉语补充词库.txt; 
CustomDictionaryPath=data/dictionary/custom/CustomDictionary.txt; resume_nouns.txt ; 现代汉语补充词库.txt; 
我把 resume_nouns.txt分别用上面两种形式加入到 hanlp.properties里面。其他字典都有效，好像只有新加入的 resume_nouns.txt 没有任何反应。

我把“个白” 这个词 作为一个特有名词，加入到了  resume_nouns.txt里面 标注了词性和频率。结果个 白两个字还是被切开了。
但是我把“个白” 加入到 CustomDictionary.txt就识别了，这两个字就不切开了。

下面是代码:
string="个白正确应该不会被切开。"
    words=cut_hanlp(string) 
    print(words)

还有一个问题是CustomDictionary.txt文件为什么只有这个文件会变成bin文件呢？为啥其他的词典就算被用到了也没有变成bin文件呢？


非常感谢！！！

**Comment by hankcs** [comment]
十有八九是你的词典编码不对之类的问题，你可以用com.hankcs.hanlp.dictionary.CustomDictionary#get检查是否能取到。

**Comment by MaaaxYang** [comment]
我也遇到这个问题了，我来描述下出现的条件；
首先我自定义了字典 比如a.txt 
路径我修改如下：
`
HanLP.Config.CustomDictionaryPath = new String[]{
                "data/dictionary/custom/CustomDictionary.txt",
                "data/dictionary/custom/a.txt"
        };
`

a.txt 文件内容如下：
`
美团 ent 1
今日头条 ent 1
`

执行分词代码：
`
StandardTokenizer.SEGMENT.enableCustomDictionaryForcing(true);
StandardTokenizer.segment("美团今年都有哪些客户")
`
输出结果：
`
[美团/nt, 今年/t, 都/d, 有/v, 哪些/r, 客户/n]
`

输出的结果，“美团这个词的词性并没有变成ent”

**Comment by MaaaxYang** [comment]
如果我直接使用：
`
CustomDictionary.add("美团","ent");
`

就可以正确输出

**Comment by MaaaxYang** [comment]
@hankcs  
我看了下加载部分的代码：
![image](https://user-images.githubusercontent.com/17725725/58535060-7761b580-821f-11e9-9475-cfd210d23082.png)
下面的代码不会执行，
`if (loadDat(mainPath, dat)) return true;`
到这一步直接return true了。

进入这个方法里面这个方法也是返回false
`isDicNeedUpdate(path, customDicPath)`

因为默认的HanLP.Config.IOAdapter 是 ResourceIOAdapter

所以如果想要能够正确加载自定义的词典，必须把这个配置改成FileIOAdapter

当然我改成FileIOAdapter 能够正常识别字典的词性了。

我觉得这应该是一个BUG。

**Comment by hankcs** [comment]
改成`FileIOAdapter`只是拥有了自动检测文件是否更新的便利。但是[`ResourceIOAdapter `](https://github.com/hankcs/HanLP/blob/6817646a344e77f27ae4649a3c222c91e061355b/src/main/java/com/hankcs/hanlp/corpus/io/ResourceIOAdapter.java#L28)仍然保证在删除了bin的情况下重新生成bin。你可以继续使用`ResourceIOAdapter`，删除.bin，然后通过`HanLP.Config.enableDebug();`观察是否加载了你的新词典。

**Comment by hankcs** [comment]
最开始的设计是一定要删除缓存才会生效的，`ResourceIOAdapter `无法检测缓存是否陈旧所以一定返回`false`，这并不违背设计初衷。

**Comment by MaaaxYang** [comment]
> 改成`FileIOAdapter`只是拥有了自动检测文件是否更新的便利。但是[`ResourceIOAdapter `](https://github.com/hankcs/HanLP/blob/6817646a344e77f27ae4649a3c222c91e061355b/src/main/java/com/hankcs/hanlp/corpus/io/ResourceIOAdapter.java#L28)仍然保证在删除了bin的情况下重新生成bin。你可以继续使用`ResourceIOAdapter`，删除.bin，然后通过`HanLP.Config.enableDebug();`观察是否加载了你的新词典。

我试过了，删除调.bin 后，ResourceIOAdapter 不会加载新的词典

**Comment by hankcs** [comment]
这与我的试验结果不同。另外如果没有bin的话，加载会失败，程序应当会抛异常终止才对。既然没有终止，说明加载的是jar内部的bin，也说明配置文件没有放到该放的位置。如果你执行下列代码，

```java
        HanLP.Config.enableDebug();
        HanLP.Config.IOAdapter = new ResourceIOAdapter();
        HanLP.Config.CustomDictionaryPath = new String[]{"data/dictionary/custom/my.txt"};
        System.out.println(CustomDictionary.get("测试词语"));
```java

并且删除my.txt.bin，应当可以看到my.txt.bin的重新生成。

**Comment by weibingtie** [comment]
![image](https://user-images.githubusercontent.com/26989457/59004305-c0cb8980-884b-11e9-93d1-f102f5dd1dff.png)
![image](https://user-images.githubusercontent.com/26989457/59004324-d2ad2c80-884b-11e9-88fb-0f2e1c8a95fa.png)

CustomDictionary.add()方法只适用当前执行吗？ 添加一次后，再调用就没用了

**Comment by hankcs** [comment]
add返回词典是否已经含有词条。如果你想覆盖，应当用insert。

**Comment by miyami** [comment]
我添加了一个自定义词典，有个词在核心词典中也有，不管把词频调多大，都不能生效，请问有什么办法可以强制自定义词典优先核心词典吗？

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
