### ISSUE TITLE
自定义词典存在长词，自定义词性 以m或x 开头，会被修改词性

### ISSUE THREAD

**Issue by tiandiweizun** [hankcs/HanLP#1172]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.7.3
我使用的版本是：1.7.3

## 我的问题
自定义词典存在长词，自定义词性 以m或x 开头，会被修改词性

### 步骤

1. 添加带有自定义词性的自定义分词词典，自定义.txt

我的额度 xyz 1000
提高额度 my 1000

2. 修改hanlp.properties，在CustomDictionaryPath添加自定义词典(自定义.txt)
3. 调用HanLP.segment("我的额度不够，需要提高额度")

### 触发代码

```

```
### 期望输出

```
[我的额度/xyz, 不够/a, ，/w, 需要/v, 提高额度/my]
```

### 实际输出

```
[我的额度/x, 不够/a, ，/w, 需要/v, 提高额度/mq]
```
### 原因分析
自定义分词的时候，在拼接词的时候，ViterbiSegment的combineWords方法调用Vertex的compileRealWord方法，在词性以x和m开头的时候，导致词性修改

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。

**Comment by tiandiweizun** [comment]
厉害，速度真快
