### ISSUE TITLE
python 封装的hanlp-1.7.3 运行报错

### ISSUE THREAD

**Issue by Freakwill** [hankcs/HanLP#1177]
下面是报错信息。
Python3.7， macOS
hanlp-1.7.3

> 
> Using local /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyhanlp/static/hanlp-1.7.3-release.zip, ignore https://github.com/hankcs/HanLP/releases/download/v1.7.3/hanlp-1.7.3-release.zip
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.7/bin/hanlp", line 6, in <module>
>     from pyhanlp.main import main
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyhanlp/__init__.py", line 122, in <module>
>     _start_jvm_for_hanlp()
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyhanlp/__init__.py", line 39, in _start_jvm_for_hanlp
>     from pyhanlp.static import STATIC_ROOT, hanlp_installed_data_version, HANLP_DATA_PATH
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyhanlp/static/__init__.py", line 309, in <module>
>     install_hanlp_jar()
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyhanlp/static/__init__.py", line 200, in install_hanlp_jar
>     with zipfile.ZipFile(jar_zip, "r") as archive:
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/zipfile.py", line 1222, in __init__
>     self._RealGetContents()
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/zipfile.py", line 1289, in _RealGetContents
>     raise BadZipFile("File is not a zip file")
> zipfile.BadZipFile: File is not a zip file

**Comment by hankcs** [comment]
```bash
wget --content-disposition http://nlp.hankcs.com/download.php?file=jar -P /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyhanlp/static/
```

欢迎汇报网络问题。

**Comment by Freakwill** [comment]
> ```shell
> wget --content-disposition http://nlp.hankcs.com/download.php?file=jar -P /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyhanlp/static/
> ```

这个命令运行时成功的，但是错误并没有消除。hanlp-1.7.3-release.zip应该已经存在了，再下载一次就是hanlp-1.7.3-release.zip.1

**Comment by hankcs** [comment]
那就删除旧的zip `rm -rf *.zip`
