### ISSUE TITLE
textrank如何获取关键词的权重？

### ISSUE THREAD

**Issue by weiruchenai** [hankcs/HanLP#1187]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.7.3
我使用的版本是：1.7.3

## 我的问题

阅读了文档，关于textrank的介绍里只有方法extractKeyword(String content, int size)，即输入文档与要提取的关键词数量，返回相应数量的关键词。但是对于不同关键词的权重，是否有接口可以获取呢？

### 触发代码

```
String content = "程序员(英文Programmer)是从事程序开发、维护的专业人员。一般将程序员分为程序设计人员和程序编码人员，但两者的界限并不非常清楚，特别是在中国。软件从业人员分为初级程序员、高级程序员、系统分析员和项目经理四大类。";
List<String> keywordList = HanLP.extractKeyword(content, 5);
System.out.println(keywordList);
```
### 期望输出

能否有接口可以获取到不同关键词的权重呢？

**Comment by hankcs** [comment]
`com.hankcs.hanlp.summary.TextRankKeyword#getTermAndRank(java.lang.String, int)`，需创建TextRankKeyword对象。

**Comment by weiruchenai** [comment]
了解了解，多谢！！！
