### ISSUE TITLE
URLTokenizer.segment(text);会导致程序卡住

### ISSUE THREAD

**Issue by hupengcool** [hankcs/HanLP#1188]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：portable-1.7.3
我使用的版本是：portable-1.7.3

## 我的问题

在使用URLTokenizer的时候会遇到程序卡住的情况，dubug了一下，会一直卡在matcher.find()
### 步骤

1. 见下面代码，必定触发

### 触发代码

```
    public void testIssue() throws Exception
    {
        String text = "随便写点啥吧？abNfxbGRIAUQfGGgvesskbrhEfvCdOHyxfWBq";
        List< Term > terms = URLTokenizer.segment(text);
    }
```
### 期望输出

```
期望能够正确执行完
```

### 实际输出

```
实际程序会一直卡在matcher.find()
```

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。
