### ISSUE TITLE
pyhanlp中如何关闭中文依存自动转换

### ISSUE THREAD

**Issue by BrambleXu** [hankcs/HanLP#1189]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：pyhanlp v0.1.22
我使用的版本是：pyhanlp v0.1.22

## 我的问题

pyhanlp中如何关闭中文依存自动转换. 输出的时候句法依存是中文。如何输出英文呢？

![image](https://user-images.githubusercontent.com/10768193/58684668-ecfe8a80-83b3-11e9-8494-30be8b7b4b05.png)

我看到了博主用java时的设置是可以关闭的，http://www.hankcs.com/nlp/parsing/neural-network-based-dependency-parser.html。

![image](https://user-images.githubusercontent.com/10768193/58684736-38b13400-83b4-11e9-905c-b23369b08401.png)

使用pyhanlp的话可以直接关闭吗？

**Comment by hankcs** [comment]
`NeuralNetworkDependencyParser=JClass(com.hankcs.hanlp.dependency.nnparser.NeuralNetworkDependencyParser)`

然后像Java一样调即可。

**Comment by BrambleXu** [comment]
搞定了，非常感谢！
