### ISSUE TITLE
分词不准确，不能按照自定义词典分词

### ISSUE THREAD

**Issue by xiaolongWinterSun** [hankcs/HanLP#1192]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x ] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.7.3
我使用的版本是：1.7.3

## 我的问题

自定义词典分词不准确，原因是因为英文逗号引起的

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

```
    public static void main(String[] args) {
        String str = "c,我们都喜欢c语言，color,c++,c#,";
        CustomDictionary.add("c","zdy");
        CustomDictionary.add("c++","zdy");
        System.out.println(HanLP.segment(str));
    }
```
### 期望输出

```
[c/zdy, ,/w, 我们/r, 都/d, 喜欢/v, c/zdy, 语言/n, ，/w, color/nx, ,/w, c++/zdy,  /w, ,/w, c#/nx, ,/w]
```

### 实际输出

```
[c/zdy, ,/w, 我们/r, 都/d, 喜欢/v, c/zdy, 语言/n, ，/w, color/nx, ,/w, c/zdy, ++,/w, c#/nx, ,/w]
```

**Comment by hankcs** [comment]
```java
        String str = "c,我们都喜欢c语言，color,c++,c#,";
        CustomDictionary.add("c","zdy");
        CustomDictionary.add("c++","zdy");
        StandardTokenizer.SEGMENT.enableCustomDictionaryForcing(true);
        System.out.println(HanLP.segment(str));
```
