### ISSUE TITLE
自定义词典根据不同用户使用不同词典

### ISSUE THREAD

**Issue by hualiang9602** [hankcs/HanLP#1197]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [ ] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：
我使用的版本是：portable-1.7.2

## 我的问题
自定义词典CustomDictionary能不能，“选择不同的词典“进行分词？
就是根据不同的用户，使用不同的自定义词典进行分词。

或者是能否给CustomDictionary添加一个类型，根据不同类型进行 添加“词汇”，以及分词，不同类型互不影响

**Comment by hualiang9602** [comment]
@hankcs 请问，您有办法能解决这个问题吗？

**Comment by AnyListen** [comment]
使用 ViterbiSegment 分词器，可以设置自定义词典，实现不同用户使用不同词典

**Comment by tiandiweizun** [comment]
这个需要自己实现，目前我已经实现了，有需要可以私信

**Comment by huangxz** [comment]
@tiandiweizun 关于不同用户自定义词典能否分享一下，谢谢

**Comment by hualiang9602** [comment]
> 这个需要自己实现，目前我已经实现了，有需要可以私信

您好，能够发到 我的邮箱里面吗,万分感谢！
hualiang9602@qq.com

**Comment by AnyListen** [comment]
ViterbiSegment 分词器又一个重载，可用传自定义的词典路径；
不同的用户，只需要 new 不同的 ViterbiSegment，然后传入不同词典路径即可。
```
/**
     * @param customPath 自定义字典路径（绝对路径，多词典使用英文分号隔开）
     */
    public ViterbiSegment(String customPath)
    {
        loadCustomDic(customPath, false);
    }
```

**Comment by tiandiweizun** [comment]
@hualiang9602 已经发送， @huangxz 可以提供一下邮箱，我建议可以使用AnyListen的方案，这样项目更容易维护。

**Comment by huangxz** [comment]
@tiandiweizun 非常感谢，xinzhuhuang@163.com

**Comment by tiandiweizun** [comment]
@huangxz 已经发送

**Comment by huangxz** [comment]
@tiandiweizun 收到，非常感谢

**Comment by hualiang9602** [comment]
@tiandiweizun 已收到，非常感谢

**Comment by hualiang9602** [comment]
@AnyListen 非常感谢~~

**Comment by zbo2018** [comment]
@AnyListen   @tiandiweizun   您好，能够发到 我的邮箱里面吗,万分感谢！
825547140@qq.com

**Comment by tiandiweizun** [comment]
@zbo2018 已发

**Comment by zbo2018** [comment]
@tiandiweizun   已收到，谢谢

**Comment by SamaDream** [comment]
@tiandiweizun 您好，源码能够发到我的邮箱吗？非常感谢！
shanguangsama@gmail.com

**Comment by tiandiweizun** [comment]
@SamaDream 目前hanlp自身已经实现了，我也发一份以前的给你吧。

**Comment by SamaDream** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    好的，万分感谢。
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2022年8月25日 09:29
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [hankcs/HanLP] 自定义词典根据不同用户使用不同词典 (#1197)
        
      
    
  
  

@SamaDream 目前hanlp自身已经实现了，我也发一份以前的给你吧。

**Comment by stevenshane** [comment]
> @SamaDream 目前hanlp自身已经实现了，我也发一份以前的给你吧。

您好，HanLP在哪里实现了能告知吗？找了一圈还是没找到呢~你的实现能够发到我的邮箱里面吗,万分感谢！
[214074094@qq.com](mailto:214074094@qq.com)

**Comment by SamaDream** [comment]
> > @SamaDream目前hanlp自己已经发现了，我也发一份以上的给你吧。
> 
> 您好，HanLP在哪现实发现了能告知吗？找到了一圈还是没有找到呢~你的现实能发到我的邮箱里吗，万分感谢！ [214074094@qq.com](mailto:214074094@qq.com)

https://github.com/hankcs/HanLP/issues/1339

**Comment by tiandiweizun** [comment]
> > @SamaDream 目前hanlp自身已经实现了，我也发一份以前的给你吧。
> 
> 您好，HanLP在哪里实现了能告知吗？找了一圈还是没找到呢~你的实现能够发到我的邮箱里面吗,万分感谢！ [214074094@qq.com](mailto:214074094@qq.com)

https://github.com/hankcs/HanLP/issues/1339

**Comment by zzllkk2003** [comment]
@tiandiweizun 你好，
能够发到 我的邮箱里面吗,万分感谢！
zlj23852588@hotmail.com

**Comment by tiandiweizun** [comment]
已发送

**Comment by tiandiweizun** [comment]
> @tiandiweizun 你好， 能够发到 我的邮箱里面吗,万分感谢！ [zlj23852588@hotmail.com](mailto:zlj23852588@hotmail.com)

已发送

**Comment by tiandiweizun** [comment]
> @tiandiweizun 你好， 能够发到 我的邮箱里面吗,万分感谢！ [zlj23852588@hotmail.com](mailto:zlj23852588@hotmail.com)

邮件无法发送，参见： https://github.com/hankcs/HanLP/issues/1339 
![image](https://user-images.githubusercontent.com/13550295/227438416-195384d4-52e8-4316-9972-cfe9ea943791.png)

**Comment by tiandiweizun** [comment]
由于1.8.4 其实对多实例（多租户支持的不是很好），希望CustomDictionary里面的默认的Default（DynamicCustomDictionary）共享，不同租户有不同的  自定义词典时，此时需要把HanLP.newSegment().customDictionary=重新赋值。由于希望使用Default，且各个租户间隔离，这就必然使得Default实例化多个，导致重复占用内存。顾把基于**1.7.8**的代码贴在这里。
[custom-HanLP.zip](https://github.com/hankcs/HanLP/files/12273406/custom-HanLP.zip)
