### ISSUE TITLE
基于flask，把pyhanlp做成一个服务，调用出错

### ISSUE THREAD

**Issue by achenjie** [hankcs/HanLP#1201]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕

## 版本号

当前最新版本号是：1.7.2
我使用的版本是：1.7.2

## 我的问题

基于flask，把pyhanlp做成一个服务，调用文档向量模型进行语义查询，遇到以下问题，以第一种方式代码调用服务，系统没有报错，可加载模型后服务自动死掉；以第二种代码调用服务，就能够正常输出结果，我想了解的是第一种调用方式的报错原因是什么？

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

第一种：
```
@app.route('/api/nearest/parse', methods=['POST'])
def NearestParse():
    request_object = json.loads(request.get_data().decode('utf-8'))
    text = request_object['text']

    DocVectorModel = SafeJClass('com.hankcs.hanlp.mining.word2vec.DocVectorModel')
    doc2vec = DocVectorModel(word2vec._proxy)

    docs = []
    
    for idx, doc in enumerate(docs):
        doc2vec.addDocument(idx, doc)
        
    for res in interpreter.nearest(text):
        print(res.getKey().intValue(), round(res.getValue().floatValue(), 2))
        
if __name__ == '__main__':
    WordVectorModel = SafeJClass('com.hankcs.hanlp.mining.word2vec.WordVectorModel')
    word2vec = WordVectorModel(word2vec_path)
    init_log()
    start_model_server()

```

第二种：
```
@app.route('/api/nearest/parse', methods=['POST'])
def NearestParse():
    request_object = json.loads(request.get_data().decode('utf-8'))
    text = request_object['text']

    docs = []
    
    for idx, doc in enumerate(docs):
        doc2vec.addDocument(idx, doc)
        
    for res in interpreter.nearest(text):
        print(res.getKey().intValue(), round(res.getValue().floatValue(), 2))
        
if __name__ == '__main__':
    WordVectorModel = SafeJClass('com.hankcs.hanlp.mining.word2vec.WordVectorModel')
    DocVectorModel = SafeJClass('com.hankcs.hanlp.mining.word2vec.DocVectorModel')
    word2vec = WordVectorModel(word2vec_path)
    doc2vec = DocVectorModel(word2vec._proxy)
    init_log()
    start_model_server()

```

### 期望输出

```
第一种能够正常输出结果
```

### 实际输出

```
服务自动死掉
```

**Comment by hankcs** [comment]
我不熟悉flash，应该是jpype与多线程的问题。你可以直接用JClass，然后在每个API里面调这段代码试试：

```
if not jpype.isThreadAttachedToJVM():
    jpype.attachThreadToJVM()
```

参考：https://lsvih.com/2017/06/09/%E8%A7%A3%E5%86%B3flask%E6%85%A2%E7%9A%84%E9%97%AE%E9%A2%98-%E4%BB%A5%E5%8F%8A%E5%BC%80%E5%90%AF%E5%A4%9A%E7%BA%BF%E7%A8%8B%E4%B9%8B%E5%90%8Ejpype%E7%9A%84%E9%94%99%E8%AF%AF/

**Comment by achenjie** [comment]
谢谢，问题已解决

**Comment by YOskrskR** [comment]
您好 请问下第一个问题怎么解决的

**Comment by achenjie** [comment]
> 您好 请问下第一个问题怎么解决的

JVM 并没有能为新开启的线程提供服务，解决方法加入
 if not jpype.isThreadAttachedToJVM():
        jpype.attachThreadToJVM()
即可，如
if __name__ == '__main__':
    if not jpype.isThreadAttachedToJVM():
        jpype.attachThreadToJVM()
    WordVectorModel = SafeJClass('com.hankcs.hanlp.mining.word2vec.WordVectorModel')
    word2vec = WordVectorModel(word2vec_path)
    init_log()
    start_model_server()

**Comment by YOskrskR** [comment]
非常感谢，我这边问题解决了

**Comment by Alapocas** [comment]
您好，我在flask外调用这些类的时候用JClass就可以了，但一旦移植到flask里面就必须用SafeJClass调用，请问这是因为flask会自动开启多线程的原因吗？谢谢。
