### ISSUE TITLE
在1.7.3/pyhanlp里面,PerceptronLexicalAnalyzer ,没有seg方法了

### ISSUE THREAD

**Issue by hxrain** [hankcs/HanLP#1202]
在1.7.3/pyhanlp里面,PerceptronLexicalAnalyzer ,没有seg方法了,调用的时候,出现异常:jpype._jexception.NoSuchElementExceptionPyRaisable: java.util.NoSuchElementException
而调用segment方法就没问题.(而此方法也不是所有的分词器都有)
使用HanLP.newSegment('crf')也一样,没有seg方法了,出异常.

**Comment by hankcs** [comment]
【自动回复】你好，感谢反馈。
由于未按要求填写，本issue被暂时标记为无效。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真修改，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
![issue](http://wx1.sinaimg.cn/large/006Fmjmcly1ft2hnlwc22j30q90bcgpe.jpg)

**Comment by gongkecun** [comment]
对的！我到处找问题的答案都没有！

**Comment by hankcs** [comment]
[《提问的智慧》](http://doc.zengrong.net/smart-questions/cn.html)
