### ISSUE TITLE
CoNLLWord类的注释中疑似出现拼写错误？

### ISSUE THREAD

**Issue by xinfeng1i** [hankcs/HanLP#1206]
`CoNLLWord`类的第 24行 对变量`LEMMA`注释中写道

> 当前词语（或标点）的原型或词干，在中文中，此列与FORM相同

但是该文件（以及整个项目）中并没有对`FORM`变量的定义，所以这里是不是出现了拼写错误，应该是`NAME`变量。还是我理解的偏差？

注：同样的问题还出现在该文件的第 61、76 行。

**Comment by xinfeng1i** [comment]
Sorry, 是我自己理解错了，`FORM`是CoNLL格式中定义的 （如下）

>  CoNLL 格式:
>  ID FORM LEMMA PLEMMA POS PPOS FEAT PFEAT HEAD PHEAD DEPREL PDEPREL
> 
>  例子:
>  1	mnoha	mnoho	mnoho	C	C	SubPOS=a|Cas=6	SubPOS=a|Cas=6	7	7

**Comment by hankcs** [comment]
由于FORM和LEMMA在中文里面是一样的，所以就只保留了一个。
