### ISSUE TITLE
python 多进程 调用阻塞

### ISSUE THREAD

**Issue by lifuqiang2016** [hankcs/HanLP#1208]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [ ] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：
我使用的版本是：

## python 多进程同时调用阻塞

hanlp = HanLP.segment(text)

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

```
    public void testIssue1234() throws Exception
    {
        CustomDictionary.add("用户词语");
        System.out.println(StandardTokenizer.segment("触发问题的句子"));
    }
```
### 期望输出

```
期望输出
```

### 实际输出

```
实际输出
```

**Comment by 17621192638** [comment]
同样遇到这个问题，在windows下多进程调用没问题，到了linux下程序就会僵死,用的safaclass

**Comment by lifuqiang2016** [comment]
你的问题解决了？


673393475@qq.com
 
发件人： 蒋泽涌
发送时间： 2019-06-24 17:55
收件人： hankcs/HanLP
抄送： lifuqiang2016; Author
主题： Re: [hankcs/HanLP] python 多进程 调用阻塞 (#1208)
同样遇到这个问题，在windows下多进程调用没问题，到了linux下程序就会僵死,用的safaclass

**Comment by 17621192638** [comment]
没有..卡了1个多星期了，很奇怪的问题.而且看论坛其它人好像都没遇到过.


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: lifuqiang2016 <notifications@github.com>
发送时间: 2019年6月25日 08:57
收件人: hankcs/HanLP <HanLP@noreply.github.com>
抄送: 蒋泽涌 <905414225@qq.com>, Comment <comment@noreply.github.com>
主题: 回复：[hankcs/HanLP] python 多进程 调用阻塞 (#1208)

**Comment by lifuqiang2016** [comment]
本地调用的这个多进程和单进程性能差不多，我给单独提出来了。如果找到解决办法，分享一下哈



673393475@qq.com
 
发件人： 蒋泽涌
发送时间： 2019-06-25 09:06
收件人： hankcs/HanLP
抄送： lifuqiang2016; Author
主题： Re: [hankcs/HanLP] python 多进程 调用阻塞 (#1208)
没有..卡了1个多星期了，很奇怪的问题.而且看论坛其它人好像都没遇到过. 


发自我的iPhone 

------------------ 原始邮件 ------------------ 
发件人: lifuqiang2016 <notifications@github.com> 
发送时间: 2019年6月25日 08:57 
收件人: hankcs/HanLP <HanLP@noreply.github.com> 
抄送: 蒋泽涌 <905414225@qq.com>, Comment <comment@noreply.github.com> 
主题: 回复：[hankcs/HanLP] python 多进程 调用阻塞 (#1208)

**Comment by 17621192638** [comment]
嗯嗯.好的👌


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: lifuqiang2016 <notifications@github.com>
发送时间: 2019年6月25日 09:17
收件人: hankcs/HanLP <HanLP@noreply.github.com>
抄送: 蒋泽涌 <905414225@qq.com>, Comment <comment@noreply.github.com>
主题: 回复：[hankcs/HanLP] python 多进程 调用阻塞 (#1208)



 
 本地调用的这个多进程和单进程性能差不多，我给单独提出来了。如果找到解决办法，分享一下哈 
 
 
 
 673393475@qq.com 
   
 发件人： 蒋泽涌 
 发送时间： 2019-06-25 09:06 
 收件人： hankcs/HanLP 
 抄送： lifuqiang2016; Author 
 主题： Re: [hankcs/HanLP] python 多进程 调用阻塞 (#1208) 
 没有..卡了1个多星期了，很奇怪的问题.而且看论坛其它人好像都没遇到过.  
 
 
 发自我的iPhone  
 
 ------------------ 原始邮件 ------------------  
 发件人: lifuqiang2016 <notifications@github.com>  
 发送时间: 2019年6月25日 08:57  
 收件人: hankcs/HanLP <HanLP@noreply.github.com>  
 抄送: 蒋泽涌 <905414225@qq.com>, Comment <comment@noreply.github.com>  
 主题: 回复：[hankcs/HanLP] python 多进程 调用阻塞 (#1208)

**Comment by hankcs** [comment]
【自动回复】你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真修改，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
![issue](http://wx1.sinaimg.cn/large/006Fmjmcly1ft2hnlwc22j30q90bcgpe.jpg)
