### ISSUE TITLE
DemoWord2Vec.java语义距离计算容易出现GC Overhead limit exceeded报错

### ISSUE THREAD

**Issue by yanxuexu007** [hankcs/HanLP#1209]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [ ] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.7.3
我使用的版本是：1.7.3

## 我的问题
HanLP/src/test/java/com/hankcs/demo/DemoWord2Vec.java大量调用的时候非常容易出现GC Overhead limit exceeded报错

## 复现问题

我训练了自己的词向量文件，并采用DemoWord2Vec的参考代码进行调用，当有大量的语句重复调用计算语义距离的时候，经常就会出现GC Overhead limit exceeded的错误。

### 触发代码
	/**
	 * 读取训练好的模型
	 */
	public static WordVectorModel loadModel(){
		try {
			return new WordVectorModel(ResourceConfig.DEFAULT_SEMANTIC_MODEL_FILE);;
		}catch(Exception ex) {
			logger.info("SemanticDistanceComputingService loadModel error: "+ex.getMessage());
		}
		return null;
	}
### 期望输出

这段代码由于每次执行都要重新去读一次词向量的文件，因此很容易造成GC的问题，建议是在类中增加静态变量存放WordVectorModel信息，并保证该信息不为null的时候，直接返回静态信息，否则则new一个WordVectorModel信息，避免出现GC的错误。
```
期望输出
```

### 实际输出

```
实际输出
```

**Comment by hankcs** [comment]
【自动回复】你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真修改，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
![issue](http://wx1.sinaimg.cn/large/006Fmjmcly1ft2hnlwc22j30q90bcgpe.jpg)
