### ISSUE TITLE
求问使用自定义辞典对初始分词结果修改的机制

### ISSUE THREAD

**Issue by starkingpku** [hankcs/HanLP#121]
v1.2.8版本下的标准分词结果：
String text = "攻城狮逆袭单身狗";
System.out.println(HanLP.segment(text));
分词结果是：攻城/狮/逆袭/单身/狗

但若增加了自定义词，如下：
CustomDictionary.add("城狮","nz 100000");   //假设"城狮"是词
CustomDictionary.add("单身狗");
分词结果是：攻城/狮/逆袭/单身狗
单身狗的分词是对的，可是为什么没有把“城狮”分成一个词呢？
我知道现在的HanLP标准分词是先对句子粗分词，再利用自定义辞典进行修正。那么现在自定义辞典修正的基本思路是什么？(相关部分代码我没看明白)
自定义词的词频对修正有影响吗？(为什么我给"城狮"的词频设为100000还是没法分出来？)

**Comment by hankcs** [comment]
0. 自定义词典的机制是，对粗分结果进行合并，而不是保证一定分出来
0. 最初是直接进词图的，然而bigram会抵制它，所以只有靠词频提高它分出来的概率
0. 词频在当前版本没有影响。

**Comment by sheenshine** [comment]
对于分词的机制，是否有考虑中文语法？遇到把小区名字分成单字

**Comment by hankcs** [comment]
你的问题缺少基本NLP知识。

**Comment by guyuexue** [comment]
分词“查房价”，一直将“查房”分到一起，我添加了“房价”用户词典，并将核心词典中“查房”词的词性后面的数字改低还是没有效果。
1:[查, 查房]
2:[房, 房价]
3:[价]
4:[ ]

粗分结果[查房/vi, 价/n]
人名角色观察：[  A 22202445 ][查房 A 22202445 ][价 C 1 ][  A 22202445 ]
人名角色标注：[ /A ,查房/A ,价/C , /A]
[查房/vi, 价/n]

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
