### ISSUE TITLE
分词后的标签都对应的中文在哪里？比如rr、vi

### ISSUE THREAD

**Issue by pangwh** [hankcs/HanLP#1212]
Segment segment = HanLP.newSegment().enableOrganizationRecognize(true);
			for (String sentence : testCase)
			{
			    List<Term> termList = segment.seg(sentence);
			    for (Term term : termList) {
			    	System.out.println(term.nature);
			    	System.out.println(term.word);
//			    	System.out.println(PartOfSpeechTagDictionary.translate(term.nature.toString()));
				}
			   
			}
这里的term里面包含了词语以及对应的词性标注标签，那么请问这个标签对应的中文对照表在哪里可以看到呢？比如 “我”对应的rr   “叫”对应vi

**Comment by xinfeng1i** [comment]
@pangwh 不太明白你的意思，是要找词性对应的释义吗？如果是的话，查看这里的表格：
http://www.hankcs.com/nlp/part-of-speech-tagging.html

**Comment by hankcs** [comment]
【自动回复】你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真修改，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
![issue](http://wx1.sinaimg.cn/large/006Fmjmcly1ft2hnlwc22j30q90bcgpe.jpg)
