### ISSUE TITLE
词语拆分之后不能复用

### ISSUE THREAD

**Issue by ManufactureBUG** [hankcs/HanLP#1213]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [ ] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.7.3
我使用的版本是：1.7.3

## 我的问题

添加自定义分词后，数据中的词语只能用一次。使得有些自定义词语不能拆分。
### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

```
                   //添加自定义词条
                //比如说buffer = “123”；自定义的词条是12、123、23； 
		List<CustomWord> customList = wordFrequencyService.queryCustomList();
		for (CustomWord customWord : customList) {
				CustomDictionary.add(customWord.getWord());
		}
		  // 自定义词典在所有分词器中都有效
		  System.out.println(HanLP.segment(buffer));
		 List<Term> segment = HanLP.segment(buffer);
```
### 期望输出

```
期望输出：12、123、23、
```

### 实际输出

```
实际输出：12、3
```

**Comment by xinfeng1i** [comment]
@ManufactureBUG 默认的分词器的结果各个单元之间是不会overlap的，如果需要同时分出123/12/23这样的结果，需要调用索引分词器 `com.hankcs.hanlp.tokenizer.IndexTokenizer `

**Comment by ManufactureBUG** [comment]
> @ManufactureBUG 默认的分词器的结果各个单元之间是不会overlap的，如果需要同时分出123/12/23这样的结果，需要调用索引分词器 `com.hankcs.hanlp.tokenizer.IndexTokenizer `

您好，我尝试了IndexTokenizer，但是并没有效果...，`/**
 * 索引分词器
 * @author hankcs
 */
public class IndexTokenizer
{
    /**
     * 预置分词器
     */
    public static final Segment SEGMENT = HanLP.newSegment().enableIndexMode(true);
    public static List<Term> segment(String text)
    {
        return SEGMENT.seg(text);
    }
`

**Comment by ManufactureBUG** [comment]
> @ManufactureBUG 默认的分词器的结果各个单元之间是不会overlap的，如果需要同时分出123/12/23这样的结果，需要调用索引分词器 `com.hankcs.hanlp.tokenizer.IndexTokenizer `

我又测试了一次数字，数字可以达到我说的那种效果但是文字并没有很理想，比如说拆分文档为“分词器分词器分词器分词器分词器分词器”，然后自定义了两个分词词条分别为“分词器”“分词器分”，这是分词结果就不对了。

**Comment by hankcs** [comment]
【自动回复】你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真修改，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
![issue](http://wx1.sinaimg.cn/large/006Fmjmcly1ft2hnlwc22j30q90bcgpe.jpg)
