### ISSUE TITLE
感知机模型人名识别错误

### ISSUE THREAD

**Issue by lingjiameng** [hankcs/HanLP#1214]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：
我使用的版本是：pyhanlp 0.1.45

## 我的问题

对句子 “这时我女儿凤霞推门进来，又摇摇晃晃地把门关上。凤霞尖声细气地对我说：”分词，
会得到“。凤霞”也是个人名这种匪夷所思的结果。把句号改成逗号，分词结果就会变正常。
我已将“凤霞”加入词典，结果是相同的

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

```

txt = "这时我女儿凤霞推门进来，又摇摇晃晃地把门关上，凤霞尖声细气地对我说："
data_path = "/home/dream/miniconda3/envs/py37/lib/python3.7/site-packages/pyhanlp/static/data/model/perceptron/large/cws.bin"
PerceptronLexicalAnalyzer = JClass('com.hankcs.hanlp.model.perceptron.PerceptronLexicalAnalyzer')
analyzer = PerceptronLexicalAnalyzer(data_path,
                                    HanLP.Config.PerceptronPOSModelPath,
                                    HanLP.Config.PerceptronNERModelPath)
print(analyzer.seg(txt))
```
### 期望输出

```
[这时/r, 我/r, 女儿/n, 凤霞/nr, 推门/v, 进来/v, ，/w, 又/d, 摇摇晃晃/v, 地/u, 把/p, 门关/n, 上/f, 。/w, 凤霞/nr, 尖声/nz, 细气/a, 地/u, 对/p, 我/r, 说/v, ：/w]
```

### 实际输出

```
[这时/r, 我/r, 女儿/n, 凤霞/nr, 推门/v, 进来/v, ，/w, 又/d, 摇摇晃晃/v, 地/u, 把/p, 门关/n, 上/f, 。 凤霞/nr, 尖声/nz, 细气/a, 地/u, 对/p, 我/r, 说/v, ：/w]
```

**Comment by hankcs** [comment]
这是因为训练语料是一句句的，句号从来都是作为结尾。你可以使用在线学习纠正它。

```java
    public void testIssue1214() throws IOException
    {
        analyzer.learn("关上/s 。/w 凤霞/nr 尖声/nz");
        String text = "这时我女儿凤霞推门进来，又摇摇晃晃地把门关上。凤霞尖声细气地对我说：";
//        analyzer.getPerceptronSegmenter().getModel().save(Config.CWS_MODEL_FILE);
        assertTrue(analyzer.analyze(text).toString().contains("关上/s 。/w 凤霞/nr 尖声/nz"));
    }
```

**Comment by shanwenxiang** [comment]
data/model/perceptron/large/cws.bin 加载失败 什么原因呢，按照文档操作的，只是跑了一个main方法而已
