### ISSUE TITLE
请问这个"data/test/crf/cws-template.txt"模板在哪里

### ISSUE THREAD

**Issue by WilliamShen2019** [hankcs/HanLP#1218]

**Comment by ecmagod** [comment]
同问

**Comment by ecmagod** [comment]
CRFSegmenter segmenter = new CRFSegmenter(null);
        segmenter.convertCorpus("data/test/pku98/199801.txt", "data/test/crf/cws-corpus.tsv");  segmenter.dumpTemplate("data/test/crf/cws-template.txt");
代码生成出来的
