### ISSUE TITLE
关于添加词典的问题

### ISSUE THREAD

**Issue by lxj0276** [hankcs/HanLP#122]
我新添加一个词典，出现这个错误
严重: 自定义词典D:/hanlp/data/dictionary/custom/word.txt读取错误！java.lang.IllegalArgumentException: No enum constant com.hankcs.hanlp.corpus.tag.Nature.INT'L，这是怎么回事呢

**Comment by hankcs** [comment]
0. 单词不能含有空格
0. 词性必须是Nature中固定的那些

**Comment by lxj0276** [comment]
如果我这个是英文机构名称，中间带空格的，我应该怎么添加

**Comment by lxj0276** [comment]
@hankcs 求助啊

**Comment by lxj0276** [comment]
~~~求助

**Comment by lxj0276** [comment]
求助

**Comment by hankcs** [comment]
0. com.hankcs.hanlp.dictionary.CustomDictionary#insert(java.lang.String, java.lang.String)
0. 未来会支持空格

**Comment by lxj0276** [comment]
是在CustomDictionary.class里添加？

**Comment by hankcs** [comment]
CustomDictionary.insert("Android 5.0", "nz 1024");

**Comment by lxj0276** [comment]
我把项目部署到linux时，出现这个错误，SEVERE: 自定义词典configNLP/hanlp/data/dictionary/custom/全国地名大全.txt读取错误！java.io.FileNotFoundException: configNLP/hanlp/data/dictionary/custom/全国地名大全.txt (No such file or directory)

我已经把hanlp.properties中的root设置为root=configNLP/hanlp/，并且自定义词典前面加空格了，请问下怎么解决@hankcs

**Comment by hankcs** [comment]
0. 异常说得很清楚了，java.io.FileNotFoundException: configNLP/hanlp/data/dictionary/custom/全国地名大全.txt (No such file or directory)
0. 极有可能是服务器中文文件名编码不是utf-8造成的
0. 你把本地生成的data/dictionary/custom/CustomDictionary.txt.bin部署到服务器的对应位置就能快速解决问题

**Comment by tjusan** [comment]
请教一下，如何批量的向用户词典中添加自定义的词，（符合标准格式）。

**Comment by tigerneil** [comment]
@hankcs 现在还没有支持空格吧。只能是动态插入。。

**Comment by hankcs** [comment]
@tigerneil 对的，事情太多忙忘了，应该提供一个友好的词条格式的。我现在设想的形式是

0. 优先以\t分割
0. 考虑到\t在文本编辑器里很难插入，所以有部分用户可能直接敲了空格，在没有\t的情况下用空格切分当前词条

其实也可以来个正则表达式，不过词典的加载速度就下去了。或者在配置文件里加个配置项，允许用户指定分隔符，这样在效率上应该好一些。

如果有任何意见，欢迎提出来。

**Comment by driventokill** [comment]
用\t还是有点问题，如果文件里面都是词条，没有词性，那么不包含\t，但是里面的英文词中间包含了空格，还是没法区分。是不是可以考虑用逗号分隔？也不需要特别自定义，csv 结尾的文件就这样处理

**Comment by hankcs** [comment]
@driventokill 这是个好主意，可以替代掉我提的那些复杂的分隔符规则，已经merge。

**Comment by cleverpig** [comment]
Mark 一下！另外，文本自定义词典的格式一定要用UTF8无BOM格式编码。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。

**Comment by vesper1012** [comment]
这个全国地名大全.txt应该在哪里下呢
