### ISSUE TITLE
python3.6.5和java1.8.0.151，安装hanlp1.7.4，报错：OSError: JVM cannot be restarted

### ISSUE THREAD

**Issue by leofionn** [hankcs/HanLP#1220]
我下载安装的是hanlp1.7.4，使用以下代码，报错：：OSError: JVM cannot be restarted
```
from jpype import *
startJVM(getDefaultJVMPath(), "-Djava.class.path=D:\python_projects\zhengzebiaodashi\hanlp\hanlp-1.3.4.jar;D:\python_projects\zhengzebiaodashi\hanlp",
         "-Xms1g",
         "-Xmx1g") # 启动JVM，Linux需替换分号;为冒号:
```

**Comment by hankcs** [comment]
【自动回复】你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真修改，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
![issue](http://wx1.sinaimg.cn/large/006Fmjmcly1ft2hnlwc22j30q90bcgpe.jpg)
