### ISSUE TITLE
pyhanlp中，Analyzer类好像不能在enableCustomDictionaryForcing(True)后使用seg()，

### ISSUE THREAD

**Issue by qq184861643** [hankcs/HanLP#1221]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：hanlp-1.7.4.jar
我使用的版本是：hanlp-1.7.4.jar

## 我的问题

1. 我想要在分词前强制启动自定义词典，分词结果使用CoreStopWordDictionary类过滤停用词。Tokenizer类没有enableCustomDictionaryForcing方法，所以只能使用Analyzer类分词。Analyzer类实例化后有两个分词方法，一个seg()，一个segment()。segment()方法产生的结果是LinkedList类，对它调用CoreStopWordDictionaryapply()会报错。seg()方法产生的结果是ArrayList类，可以正常过滤停用词。但是对分词器使用#enableCustomDictionaryForcing后，使用seg()方法会直接报java.util.NoSuchElementException。请问这个有办法解决吗？
如果上述问题无法解决，有什么方案能在pyhanlp里，同时使用enableCustomDictionaryForcing和CoreStopWordDictionary吗？

2. 对默认分词器的分词结果执行CoreStopWordDictionary.apply()返回的结果为None，1.7.3版本没有这个问题。

## 复现问题

![image](https://user-images.githubusercontent.com/20453470/60585884-5b73a580-9dc3-11e9-90a5-bad816737bf0.png)

![image](https://user-images.githubusercontent.com/20453470/60634009-d11d5700-9e3f-11e9-8728-94c9e24b6516.png)

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。

你可以使用下面的jar覆盖pyhanlp安装目录中的jar。

[hanlp-1.7.4.jar.zip](https://github.com/hankcs/HanLP/files/3357416/hanlp-1.7.4.jar.zip)

**Comment by qq184861643** [comment]
> 感谢反馈，已经修复，请参考上面的commit。
> 如果还有问题，欢迎重开issue。
> 
> 你可以使用下面的jar覆盖pyhanlp安装目录中的jar。
> 
> [hanlp-1.7.4.jar.zip](https://github.com/hankcs/HanLP/files/3357416/hanlp-1.7.4.jar.zip)

@hankcs 您好，我刚测试了一下，第一个问题解决了，十分感谢~但是对默认分词结果过滤停用词，返回结果为None的bug依然未修复。

**Comment by hankcs** [comment]
apply本来就不返回结果的，传入的list会被修改但不返回。
