### ISSUE TITLE
如何在一堆包含多个角色和多个号码的文本中，按不同角色的相关信息去识别对应的号码，如下：

### ISSUE THREAD

**Issue by WilliamShen2019** [hankcs/HanLP#1222]
@hankcs 
您好，我新手接触nlp，接到一个需求去在文本中识别不同角色的账号，我的思路如下，不知道这样对不对，请指教：

我的文本示例：
        演员周星驰（电话号码：12345678966）在1998年出演过《大话西游》，导演是王晶（电话号码：34567889922），一同参演这部电影的还有演员吴孟达（QQ号：12342314），同时王晶导演又请了周帆导演（微信号：asfd1234234）来一同指导。
       邓超，电话：12343453425，去年参演了电影《影》，这部电影的导演是王二麻子，他的手机号是：324523523534，王二麻子觉得自己导演的不行，又请了张艺谋（微信号：234532kjhk）一同指导。

我使用了crf分词去标注这段文本：
        演员周星驰/ACTOR（/W 电话号码/TEL ：/W 12345678966/ACT_TEL ）W 在1998年出演过/AA 《/W 大话西游/MOVIE 》/W ，/W 导演是王晶/DIR （/W 电话号码/TEL ：/W 34567889922/DIR_TEL ）/W ，/W 一同参演这部电影的还有/AA 演员吴孟达/ACTOR （/W QQ号/QQ ：/W 12342314/ACT_QQ ）/W ，/W 同时/AA 王晶导演/DIR 又请了/AA 周帆导演/DIR （/W 微信号/WX ：/W asfd1234234/DIR_WX ）/W 来一同指导/AA 。/W 
       邓超/ACTOR ，/W 电话/TEL ：/W 12343453425/ACT_TEL ，/W 去年参演了电影/AA 《/W 影/MOVIE 》/W ，/W 这部电影的/AA 导演是王二麻子/DIR ，/W 他的手机号是/TEL ：/W 324523523534/DIR_TEL ，/W 王二麻子/DIR 觉得自己导演的不行/AA ，/W 又请了张艺谋/DIR （/W 微信号/WX ：/W 234532kjhk/DIR_TEL ）/W 一同指导/AA 。W

语料标记涉及到的词性：
               /AA 是无关信息，/W是标点符号；
               /ACTOR,/ACT_TEL,/ACT_QQ,/ACT_WX  (演员及其各种号码)；
               /DIR,/DIR_TEL,/DIR_QQ,/DIR_WX  (导演及其各种号码)。

我有1亿多条这种数据，要在其中识别出演员的各种账号：/ACT_TEL,/ACT_QQ,/ACT_WX,和导演的各种账号：/DIR_TEL,/DIR_QQ,/DIR_TEL,

标记了大概500条这种数据，
然后用 CRFSegmenter 和 CRFPOSTagger 去分别训练cws.bin 和 pos.bin,
然后  CRFLexicalAnalyzer crfLexicalAnalyzer = new CRFLexicalAnalyzer(“cws.bin”，“pos.bin”);   
用 crfLexicalAnalyzer.analyze("我的文本")，去获取相关词性的号码，这样是否正确，
我在训练了几次后发现，各种号码的识别正确率还行，但是角色的正确率却不高，比如  12345678966  应该识别为 /ACT_TEL，但却识别成了 /DIR_TEL；
这种情况下是要加大训练量还是要通过别的什么办法来提高正确率，请指教，谢谢！！！

**Comment by hankcs** [comment]
【自动回复】你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真修改，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
![issue](http://wx1.sinaimg.cn/large/006Fmjmcly1ft2hnlwc22j30q90bcgpe.jpg)
