### ISSUE TITLE
分词问题

### ISSUE THREAD

**Issue by monkeyWie** [hankcs/HanLP#1223]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.7.4
我使用的版本是：1.7.4

## 我的问题

`长大`分词问题

## 复现问题
对长大进行分词，某些情况下会分成`长、大`
### 步骤

1. 准备句子`希望长大`
2. 使用分词
3. 查看结果

### 触发代码

```
    public void testIssue1234() throws Exception
    {
        HanLP.segment("希望长大").forEach(term -> System.out.print(term.word+","));
    }
```
### 期望输出

分词成 `希望`+`长大`

```
希望,长大,
```

### 实际输出

分词成 `希望`+`长`+`大`
```
希望,长,大,
```

## 其他信息

使用`长大以后`进行分词就正常，分词结果是
```
长大,以后,
```

**Comment by hankcs** [comment]
请使用data包。[希望/v, 长大/vi]

**Comment by monkeyWie** [comment]
@hankcs 是用的data包：http://nlp.hankcs.com/download.php?file=data
但是没效果，您可以复现下看看。

**Comment by hankcs** [comment]
你的配置没有生效。

```
        HanLP.Config.enableDebug();
        assertEquals("[希望/v, 长大/vi]", HanLP.segment("希望长大").toString());
```
