### ISSUE TITLE
IndexTokenizer索引分词器没有使用到使用 CustomDictionary.add()动态添加的词典

### ISSUE THREAD

**Issue by ManufactureBUG** [hankcs/HanLP#1225]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [ ] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.7.4
我使用的版本是：1.7.3

## 我的问题
IndexTokenizer索引分词器没有使用到使用 CustomDictionary.add()动态添加的词典，
我需要对拆分对象的词语复用，比如“分词器分词器分词器分词器分词器分词器”，对这个字符串进行拆分，使用CustomDictionary.add(“词器分”)动态添加自定义的词条“词器分”；，拆分时可以拆分出正确数量的6个“分词器”和5个“词器分”这两个词

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

```
//测试viterbi分词器开启索引分词
				Segment newSegment = HanLP.newSegment("viterbi");
				Segment segment3 = newSegment.enableIndexMode(2);
				segment3.enableCustomDictionary(true);
				
				//添加自定义词条
				List<CustomWord> customList = wordFrequencyService.queryCustomList();
				for (CustomWord customWord : customList) {
					boolean add = CustomDictionary.add(customWord.getWord());
					System.out.println(add);
				}
				final char[] charArray = buffer.toCharArray();
				CustomDictionary.parseText(buffer, new AhoCorasickDoubleArrayTrie.IHit<CoreDictionary.Attribute>()
		        {
		            @Override
		            public void hit(int begin, int end, CoreDictionary.Attribute value)
		            {
		            	  System.out.printf("[%d:%d]=%s %s\n", begin, end, new String(charArray, begin, end - begin), value);
		            }
		        });
				System.out.println(segment3.seg(buffer));
				// 自定义词典在所有分词器中都有效
		        //List<Term> segment = HanLP.segment(buffer);
				/*
				 * IndexTokenizer tokenizer = new IndexTokenizer(); List<Term> segment = tokenizer.segment(buffer);
				 * 
				 * System.out.println( tokenizer.segment(buffer)); System.out.println(tokenizer.seg2sentence(buffer));
				 */
				//索引分词器
				List<Term> segment = IndexTokenizer.segment(buffer);
				System.out.println(segment);
				//crf分词
		        CRFLexicalAnalyzer analyzer = new CRFLexicalAnalyzer();
		        Segment segment2 = analyzer.enableIndexMode(1);
		        List<Term> seg = segment2.seg(buffer);
```
### 期望输出

```
期望输出
```

### 实际输出

```
实际输出
```

**Comment by hankcs** [comment]
【自动回复】你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真修改，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
![issue](http://wx1.sinaimg.cn/large/006Fmjmcly1ft2hnlwc22j30q90bcgpe.jpg)
