### ISSUE TITLE
linux下字典路径找不到 请问怎么解决

### ISSUE THREAD

**Issue by wasd345** [hankcs/HanLP#1228]
02:13:50 [http-nio-8080-exec-10] ERROR HanLP - 自定义词典data/dictionary/custom/CustomDictionary.txt读取错误！java.io.FileNotFoundException: data/dictionary/custom/CustomDictionary.txt (No such file or directory)
02:13:50 [http-nio-8080-exec-10] WARN  HanLP - 失败：data/dictionary/custom/CustomDictionary.txt
02:13:50 [http-nio-8080-exec-10] ERROR HanLP - 自定义词典data/dictionary/custom/现代汉语补充词库.txt读取错误！java.io.FileNotFoundException: data/dictionary/custom/现代汉语补充词库.txt (No such file or directory)
02:13:50 [http-nio-8080-exec-10] WARN  HanLP - 失败：data/dictionary/custom/现代汉语补充词库.txt
02:13:50 [http-nio-8080-exec-10] ERROR HanLP - 自定义词典data/dictionary/custom/全国地名大全.txt读取错误！java.io.FileNotFoundException: data/dictionary/custom/全国地名大全.txt (No such file or directory)
02:13:50 [http-nio-8080-exec-10] WARN  HanLP - 失败：data/dictionary/custom/全国地名大全.txt
02:13:50 [http-nio-8080-exec-10] ERROR HanLP - 自定义词典data/dictionary/custom/人名词典.txt读取错误！java.io.FileNotFoundException: data/dictionary/custom/人名词典.txt (No such file or directory)
02:13:50 [http-nio-8080-exec-10] WARN  HanLP - 失败：data/dictionary/custom/人名词典.txt
02:13:50 [http-nio-8080-exec-10] ERROR HanLP - 自定义词典data/dictionary/custom/机构名词典.txt读取错误！java.io.FileNotFoundException: data/dictionary/custom/机构名词典.txt (No such file or directory)
02:13:50 [http-nio-8080-exec-10] WARN  HanLP - 失败：data/dictionary/custom/机构名词典.txt
02:13:50 [http-nio-8080-exec-10] ERROR HanLP - 自定义词典data/dictionary/custom/上海地名.txt读取错误！java.io.FileNotFoundException: data/dictionary/custom/上海地名.txt (No such file or directory)
02:13:50 [http-nio-8080-exec-10] WARN  HanLP - 失败：data/dictionary/custom/上海地名.txt
02:13:50 [http-nio-8080-exec-10] ERROR HanLP - 自定义词典data/dictionary/person/nrf.txt读取错误！java.io.FileNotFoundException: data/dictionary/person/nrf.txt (No such file or directory)
02:13:50 [http-nio-8080-exec-10] WARN  HanLP - 失败：data/dictionary/person/nrf.txt
02:13:50 [http-nio-8080-exec-10] WARN  HanLP - 没有加载到任何词条
02:13:50 [http-nio-8080-exec-10] ERROR HanLP - 自定义词典data/dictionary/custom/CustomDictionary.txt不存在！java.io.FileNotFoundException: data/dictionary/custom/CustomDictionary.txt.bin (No such file or directory)
02:13:50 [http-nio-8080-exec-10] WARN  HanLP - 自定义词典[data/dictionary/custom/CustomDictionary.txt, data/dictionary/custom/现代汉语补充词库.txt, data/dictionary/custom/全国地名大全.txt ns, data/dictionary/custom/人名词典.txt, data/dictionary/custom/机构名词典.txt, data/dictionary/custom/上海地名.txt ns, data/dictionary/person/nrf.txt nrf]加载失败
02:13:50 [http-nio-8080-exec-10] WARN  HanLP - 读取data/dictionary/CoreNatureDictionary.txt.bin时发生异常java.io.FileNotFoundException: data/dictionary/CoreNatureDictionary.txt.bin (No such file or directory)
02:13:50 [http-nio-8080-exec-10] WARN  HanLP - 核心词典data/dictionary/CoreNatureDictionary.txt不存在！java.io.FileNotFoundException: data/dictionary/CoreNatureDictionary.txt (No such file or directory)

**Comment by hankcs** [comment]
【自动回复】你好，感谢反馈。
由于未按要求填写，本issue被暂时标记为无效。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真修改，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
![issue](http://wx1.sinaimg.cn/large/006Fmjmcly1ft2hnlwc22j30q90bcgpe.jpg)
