### ISSUE TITLE
词典中Frequency数值的意义

### ISSUE THREAD

**Issue by KevinGF** [hankcs/HanLP#123]
请问词典中Frequency数值具有什么意义，是怎么来的，以及其大小对分词结果具有什么影响？

**Comment by hankcs** [comment]
0. 代表在某个语料库中某单词以某词性出现的频次
0. 其实一个词典就是一个模型，是通过训练得到的：https://github.com/hankcs/HanLP/wiki/%E8%AE%AD%E7%BB%83%E5%88%86%E8%AF%8D%E6%A8%A1%E5%9E%8B
0. 在BiGram分词和HMM词性标注中都有用到：http://www.hankcs.com/nlp/%E7%BB%B4%E7%89%B9%E6%AF%94%E7%AE%97%E6%B3%95%E5%9C%A8%E5%88%86%E8%AF%8D%E4%B8%AD%E7%9A%84%E5%BA%94%E7%94%A8.html 以及 http://www.hankcs.com/nlp/part-of-speech-tagging.html

**Comment by KevinGF** [comment]
当用户自定义词典时Frequency数值如何设置呢？

**Comment by hankcs** [comment]
0. 从分词的目的来讲，在当前版本下该数值是没起作用的
0. 从词性标注来讲，会影响最终这个词语被标上什么词性

**Comment by KevinGF** [comment]
了解了，谢谢
