### ISSUE TITLE
如何按不同角色去识别其对应的相关信息

### ISSUE THREAD

**Issue by WilliamShen2019** [hankcs/HanLP#1241]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.7.4
我使用的版本是：1.7.3

您好，我新手接触nlp，接到一个需求去在文本中识别不同角色的账号，我的思路如下，不知道这样对不对，请指教：

我的文本示例：
演员周星驰（电话号码：12345678966）在1998年出演过《大话西游》，导演是王晶（电话号码：34567889922），一同参演这部电影的还有演员吴孟达（QQ号：12342314），同时王晶导演又请了周帆导演（微信号：asfd1234234）来一同指导。
邓超，电话：12343453425，去年参演了电影《影》，这部电影的导演是王二麻子，他的手机号是：324523523534，王二麻子觉得自己导演的不行，又请了张艺谋（微信号：234532kjhk）一同指导。

我使用了crf分词去标注这段文本：
演员周星驰/ACTOR（/W 电话号码/TEL ：/W 12345678966/ACT_TEL ）W 在1998年出演过/AA 《/W 大话西游/MOVIE 》/W ，/W 导演是王晶/DIR （/W 电话号码/TEL ：/W 34567889922/DIR_TEL ）/W ，/W 一同参演这部电影的还有/AA 演员吴孟达/ACTOR （/W QQ号/QQ ：/W 12342314/ACT_QQ ）/W ，/W 同时/AA 王晶导演/DIR 又请了/AA 周帆导演/DIR （/W 微信号/WX ：/W asfd1234234/DIR_WX ）/W 来一同指导/AA 。/W
邓超/ACTOR ，/W 电话/TEL ：/W 12343453425/ACT_TEL ，/W 去年参演了电影/AA 《/W 影/MOVIE 》/W ，/W 这部电影的/AA 导演是王二麻子/DIR ，/W 他的手机号是/TEL ：/W 324523523534/DIR_TEL ，/W 王二麻子/DIR 觉得自己导演的不行/AA ，/W 又请了张艺谋/DIR （/W 微信号/WX ：/W 234532kjhk/DIR_TEL ）/W 一同指导/AA 。W

语料标记涉及到的词性：
/AA 是无关信息，/W是标点符号；
/ACTOR,/ACT_TEL,/ACT_QQ,/ACT_WX (演员及其各种号码)；
/DIR,/DIR_TEL,/DIR_QQ,/DIR_WX (导演及其各种号码)。

我有1亿多条这种数据，要在其中识别出演员的各种账号：/ACT_TEL,/ACT_QQ,/ACT_WX,和导演的各种账号：/DIR_TEL,/DIR_QQ,/DIR_TEL,

标记了大概500条这种数据，
然后用 CRFSegmenter 和 CRFPOSTagger 去分别训练cws.bin 和 pos.bin,
然后 CRFLexicalAnalyzer crfLexicalAnalyzer = new CRFLexicalAnalyzer(“cws.bin”，“pos.bin”);
用 crfLexicalAnalyzer.analyze("我的文本")，去获取相关词性的号码，这样是否正确，
我在训练了几次后发现，各种号码的识别正确率还行，但是角色的正确率却不高，比如 12345678966 应该识别为 /ACT_TEL(演员手机号码)，但却识别成了 /DIR_TEL(导演手机号码)；
这种情况下是要加大训练量还是要通过别的什么办法来提高正确率，请指教，谢谢！！！

**Comment by hankcs** [comment]
1. 训练集太小。
2. 单词颗粒度太大，导致特征稀疏。

**Comment by yaleimeng** [comment]
其实这个任务有更简单方式完成啊，通过演员+导演名单就能解决角色问题，然后正则表达式就可以提取联系方式，再跟左边最近的人物进行匹配即可。
为什么要通过序列标注来完成呢？ @

**Comment by WilliamShen2019** [comment]
你说的“演员+导演名单”是什么意思；
还有我的语料特别复杂，其中这两种角色数量非常庞大，位置也不固定，并不单单是我列举的这两条语料的状况，比如导演后边后边再跟一堆演员和电影的信息，然后再跟上一串电话，qq，微信号，需要从上下文语义上去判断是导演的信息，还是演员的信息，而且微信号五花八门，微信号的正则咋写啊

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
