### ISSUE TITLE
AhoCorasickDoubleArrayTrieSegment 使用自定义词典，分词结果词性为空

### ISSUE THREAD

**Issue by bijialin** [hankcs/HanLP#1245]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号
portable-1.7.4

当前最新版本号是：v1.7.4
我使用的版本是：portable-1.7.4

## 我的问题

AhoCorasickDoubleArrayTrieSegment 使用自定义词典，分词结果词性为空

### 步骤

1. 首先创建词性TreeMap
2. 然后初始化AhoCorasickDoubleArrayTrieSegment并使用TreeMap的关键词
3. 接着进行AhoCorasickDoubleArrayTrieSegment分词

### 触发代码

```
  public static void main(String[] args) {
		TreeMap<String, CoreDictionary.Attribute> dictionary = new TreeMap<>();
		dictionary.put("高冰种", CoreDictionary.Attribute.create("fcz 1"));
		AhoCorasickDoubleArrayTrieSegment segment = new AhoCorasickDoubleArrayTrieSegment(dictionary);
		List<Term> termList = segment.seg("高冰种正阳辣绿萤火虫手镯");
		termList.forEach(System.out::println);
	}
```
### 期望输出

```
高冰种/fcz
```

### 实际输出

```
高冰种/null
```

**Comment by hankcs** [comment]
需要`enablePartOfSpeechTagging`。

**Comment by bijialin** [comment]
@hankcs  可以了，非常感谢

**Comment by bijialin** [comment]
@hankcs  我按treeMap的方式初始化AhoCorasickDoubleArrayTrieSegment后，我的自定义词典包含
“裂 fc 1” ，coreDicitonary里面也包含“裂”这个关键词，可以指定词典的优先级，然后返回“裂 fc 1”吗？

**Comment by hankcs** [comment]
AhoCorasickDoubleArrayTrieSegment不使用核心词典，只使用你传入的TreeMap。

**Comment by bijialin** [comment]
![image](https://user-images.githubusercontent.com/29999249/61769900-6d72c200-ae1e-11e9-996e-9b887cbb7a0a.png)
![image](https://user-images.githubusercontent.com/29999249/61769931-87140980-ae1e-11e9-91a0-3d9446b22cb6.png)
![image](https://user-images.githubusercontent.com/29999249/61769953-9abf7000-ae1e-11e9-8648-c690dfcf1fac.png)
@hankcs 我的词典里面已经添加了“裂 2 1”但是分词后，返回的还是“裂/nz”

**Comment by hankcs** [comment]
请给出最精简的完整触发代码。

**Comment by bijialin** [comment]
````
public static void main(String[] args) {
		TreeMap<String, CoreDictionary.Attribute> dictionary = new TreeMap<>();
		dictionary.put("裂", CoreDictionary.Attribute.create("fcz 1"));
				Segment segment = new AhoCorasickDoubleArrayTrieSegment(dictionary).enablePartOfSpeechTagging(true);
		List<Term> termList = segment.seg("裂纹");
		termList.forEach(System.out::println);
	}
````

**Comment by hankcs** [comment]
> ```
> public static void main(String[] args) {
> 		TreeMap<String, CoreDictionary.Attribute> dictionary = new TreeMap<>();
> 		dictionary.put("裂", CoreDictionary.Attribute.create("fcz 1"));
> 		Segment segment = new AhoCorasickDoubleArrayTrieSegment(dictionary)
> .enablePartOfSpeechTagging(true);
> 		List<Term> termList = segment.seg("裂纹");
> 		termList.forEach(System.out::println);
> 	}
> ```

`AhoCorasickDoubleArrayTrieSegment`会把相同词性的单字碎片合并到一起，你可以override `com.hankcs.hanlp.seg.DictionaryBasedSegment#posTag`为空函数。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
