### ISSUE TITLE
Pyhanlp 的User Guide

### ISSUE THREAD

**Issue by FontTian** [hankcs/HanLP#1247]
https://github.com/FontTian/pyhanlp_user_guide

去年自己写了个Pyhanlp 的user guide。忘记和你说一下了。
这是CSDN博客列表：https://blog.csdn.net/fontthrone/article/category/8073727

**Comment by hankcs** [comment]
感谢贡献，已经收录到wiki中：https://github.com/hankcs/pyhanlp/wiki

**Comment by FontTian** [comment]
好的ヽ(￣▽￣)و。
