### ISSUE TITLE
寻求解决方案：人名、电话、省市区识别问题中的：人名识别问题

### ISSUE THREAD

**Issue by bushuaigege** [hankcs/HanLP#1248]
当前最新版本号是：portable-1.7.4
我使用的版本是：portable-1.7.3

## 我的问题

需求：从一串文本中提取电话、省市区（单独提取），人名
实现逻辑：建议对应的省、市、区词库（使用的是CustomDictionary.insert强行插入） 、人名单独的俩个词典

## 复现问题
![image](https://user-images.githubusercontent.com/9693917/61531356-2faa1e00-aa59-11e9-874d-048e126c79a0.png)

打印词性如下：
一串文本中：黄英男 12345328978 湖南娄底双峰A街道华洪水大厦A座102

这种情况会把：华洪水和黄英男都视为人名，我的大概思路为：多个/nr情况以最远距离的为准，但不知道是否有其他实现思路，或者可行api

@hankcs 这么多人的问题，打扰了~~^V^

**Comment by liujie19880815** [comment]
建个地名词典，把华洪水大厦当成地名

**Comment by l06066hb** [comment]
友情提示：你的提问格式不符合规范  修改一下也许会获得帮助 另外我也有同样的需求  通过词典来控制的话 ，涉及的词典和词典的量级以及这种地标住址不是很好控制 ，现在也没什么特别好的办法

**Comment by jimichan** [comment]
电话号码非常容易，使用规则就行。

如果你需要单独提前人名
参考 [mynlp](https://github.com/mayabot/mynlp) 中有个独立的人名提取功能，是基于
字符级别的，排除歧义和性能都很棒。

```xml
<dependency>
  <groupId>com.mayabot.mynlp</groupId>
  <artifactId>mynlp-segment</artifactId>
  <version>3.0.0</version>
</dependency>
```

```java
PerceptronPersonNameService pps = Mynlps.instanceOf(PerceptronPersonNameService.class);

List<PersonName> names = pps.findName(" 黄英男 12345328978 湖南娄底双峰A街道华洪水大厦A座102");

 System.out.println(names);
```
输出:
```txt
[PersonName(name=黄英男, offset=1)]
```

**Comment by bushuaigege** [comment]
> 友情提示：你的提问格式不符合规范 修改一下也许会获得帮助 另外我也有同样的需求 通过词典来控制的话 ，涉及的词典和词典的量级以及这种地标住址不是很好控制 ，现在也没什么特别好的办法

第一次提问，感谢指正，有什么可以参考链接嘛
![image](https://user-images.githubusercontent.com/9693917/68557989-99b85a00-0472-11ea-90c0-7ffc6bd5a287.png)

**Comment by bushuaigege** [comment]
> 电话号码非常容易，使用规则就行。
> 
> 如果你需要单独提前人名
> 参考 https://github.com/mayabot/mynlp 中有个独立的人名提取功能，是基于
> 字符级别的，排除歧义和性能都很棒。
> 
> ```
> <dependency>
>   <groupId>com.mayabot.mynlp</groupId>
>   <artifactId>mynlp-segment</artifactId>
>   <version>3.0.0</version>
> </dependency>
> ```
> 
> ```java
>        PerceptronPersonNameService pps = Mynlps.instanceOf(PerceptronPersonNameService.class);
> 
>         List<PersonName> names = pps.findName(" 黄英男 12345328978 湖南娄底双峰A街道华洪水大厦A座102");
>         List<PersonName> names2 = pps.findName("小明送给张贺年老师一张贺年卡");
> 
>         System.out.println(names);
>         System.out.println(names2);
> ```
> 
> 输出:
> 
> ```
> [PersonName(name=黄英男, offset=1)]
> [PersonName(name=小明, offset=0), PersonName(name=张贺年, offset=4)]
> ```


话说我是maven引用，还需要用guava？
`com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.NoClassDefFoundError: com/google/common/io/ByteSource`

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
