### ISSUE TITLE
词性标准和依存句法分析问题

### ISSUE THREAD

**Issue by ecnumjc** [hankcs/HanLP#126]
您的词性标准是自己定义的还是参考某标准？谢谢

**Comment by hankcs** [comment]
每个词性的意思请查阅http://www.hankcs.com/nlp/part-of-speech-tagging.html#h2-8

**Comment by hankcs** [comment]
训练自2014年人民日报切分语料
词语标注集兼容《ICTPOS3.0汉语词性标记集》
词语标注集兼容《现代汉语语料库加工规范——词语切分与词性标注》

**Comment by furaoing** [comment]
一点建议，现在的HanLp词性标注里有一部分Tag实际上是领域标签/命名实体标签而非传统意义上的词性（名词，形容词，动词等）， 如g开头的学术词汇。 在词性上，个人认为g开头的标签实际上是n标签的一个子集。   建议把词性标签和领域/实体标签分开， 如n_g （下划线分隔）。

**Comment by hankcs** [comment]
0. 感谢建议，这取决于训练的时候用了什么语料库，我个人没有太多的精力去清洗数据了
0. 你也可以自行将g改为n，或干脆在98年人民日报上训练

**Comment by furaoing** [comment]
我公司这里上个月刚用hanlp替代掉了nlpir作nlp基础件，用的是自己做的一个hanlp fork。词性我们改过了，但还不完善，可能春节后会把领域属性和一些命名实体加上去，合适的话我会贡献出来。

Rao Fu
raofu

**Comment by hankcs** [comment]
太好了，期待你们的工作成果，这会是一次很有意义的开源贡献。

**Comment by sheenshine** [comment]
对于词性，我想请教两位，怎么增加新的词性标注？在具体的业务领域，往往需要在词性的基础上增加点业务概念

**Comment by furaoing** [comment]
在Nature.java这个文件的nature枚举里添加新的词性，然后在自定义词库或者默认词库里修改/添加对应的词性

Rao Fu
raofu

**Comment by sheenshine** [comment]
分词时，为何中国银行在核心词典的词性是ntcb，而结果分出来却是nt呢？

**Comment by furaoing** [comment]
应该是hanlp的自定义词典或者你自行添加的词库把核心词典里“中国银行”这个词的词性覆盖掉了

**Comment by sheenshine** [comment]
我用的是Viterbi分词，词性在Vertex.java里面有个compileRealWord 方法里面被改的

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
