### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by liuchenbaidu** [hankcs/HanLP#1260]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内v输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：pyhanlp 0.1.45
我使用的版本是：pyhanlp 0.1.45

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码
res=analyzertxt.repeatedBisection(0.1)
### 期望输出

```
期望输出
```

### 实际输出

```
实际输出
```

## 其他信息
Traceback (most recent call last):
  File "test_cluster.py", line 65, in <module>
    res=cluster(filename)
  File "test_cluster.py", line 60, in cluster
    res=analyzertxt.repeatedBisection(0.3)
jpype._jexception.NullPointerExceptionPyRaisable: java.lang.NullPointerException

**Comment by hankcs** [comment]
请给出完整代码。

**Comment by liuchenbaidu** [comment]
linux: ubuntu
python 3.6
analyzer = ClusterAnalyzer()
    analyzer.addDocument("赵一", "流行, 流行, 流行, 流行, 流行, 流行, 流行, 流行, 流行, 流行, 蓝调, 蓝调, 蓝调, 蓝调, 蓝调, 蓝调, 摇滚, 摇滚, 摇滚, 摇滚")
    analyzer.addDocument("钱二", "爵士, 爵士, 爵士, 爵士, 爵士, 爵士, 爵士, 爵士, 舞曲, 舞曲, 舞曲, 舞曲, 舞曲, 舞曲, 舞曲, 舞曲, 舞曲")
    analyzer.addDocument("张三", "古典, 古典, 古典, 古典, 民谣, 民谣, 民谣, 民谣")
    analyzer.addDocument("李四", "爵士, 爵士, 爵士, 爵士, 爵士, 爵士, 爵士, 爵士, 爵士, 金属, 金属, 舞曲, 舞曲, 舞曲, 舞曲, 舞曲, 舞曲")
    analyzer.addDocument("王五", "流行, 流行, 流行, 流行, 摇滚, 摇滚, 摇滚, 嘻哈, 嘻哈, 嘻哈")
    analyzer.addDocument("马六", "古典, 古典, 古典, 古典, 古典, 古典, 古典, 古典, 摇滚")
    print(analyzer.repeatedBisection(0.12))  # 自动判断聚类数量k
这个就可以出现，
当然我是跑大量句子分类发现的，然后设置beta<1.0都不可以。

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。
