### ISSUE TITLE
关于自定义词典和核心词典中的频次问题

### ISSUE THREAD

**Issue by changetoblow** [hankcs/HanLP#1261]
hankcs  你好! 可以讲一下自定义词典和核心词典中的频次的作用吗.我看了相关的Issues并没有得到解惑,谢谢.

**Comment by yaleimeng** [comment]
原始词频通常是从大规模语料中统计得到的。词频高的，出现更频繁，成词概率就更大。
自定义词组经常需要自己估计词频。对于专业术语来说，真实频次不会很高，可以人为设高一些，比如来个500、1000什么的。
至于你说自己领域的自定义词典里面，其实不同词条的词频是不同的，应该怎么弄？其实认真地估计一下当然是最好的。但规模大了估计也没那个精力。干脆就全部一样了。
反正最终目的是分词能分出来，词性正确。达到目的就行了

**Comment by changetoblow** [comment]
@yaleimeng 非常感谢你的回答, 频次在你的解说下,我已经明白了它的用处, 但是我还有一点疑问,
我看到词典中有的 词条 有两个 词性 不同的频次 例如  "咨询 vn 1252	v 316" 可以再次帮我解惑一下吗? 非常感谢

**Comment by yaleimeng** [comment]
这是一个词有多种词性的时候，其实在实际语境中词频往往是相差很大的，有主次之分。
您举的例子表明，”咨询 “用作vn词性的频次远高于v的频次，那么词性标注时，更大概率就是vn。

**Comment by changetoblow** [comment]
非常感谢你的解惑, 祝你工作顺利,事事顺心
