### ISSUE TITLE
分词结果是否支持不进行词性标注呢？

### ISSUE THREAD

**Issue by lxw0109** [hankcs/HanLP#1264]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.7.4
我使用的版本是：1.7.4

## 我的问题
```java
System.out.println(HanLP.segment("你好，欢迎使用HanLP汉语处理包！"));
```
的输出结果为
```
[你好/l, ，/w, 欢迎/v, 使用/v, HanLP/nx, 汉语/nz, 处理/v, 包/v, ！/w]
```
我想知道，有没有参数或者有没有其他接口能够支持不进行分词后的词性标注，例如
```
[你好, ，, 欢迎, 使用, HanLP, 汉语, 处理, 包, ！]
```

**Comment by hankcs** [comment]
HanLP.Config.ShowTermNature = false;

**Comment by lxw0109** [comment]
Thank you very much ~
