### ISSUE TITLE
命令hanlp找不到，需要如何配置?

### ISSUE THREAD

**Issue by lihaiming** [hankcs/HanLP#1266]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.7.4
我使用的版本是：1.7.4

## 复现问题

根据 https://github.com/hankcs/pyhanlp 提到 “使用命令hanlp segment进入交互分词模式”，然而：
[root@ec-n1-1d68-0005 ~]# hanlp
-bash: hanlp: command not found

是不是还差什么配置没有做好？

**Comment by lihaiming** [comment]
难道需要自己写一个脚本，

[root@ec-n1-1d68-0005 tools]# cat hanlp2
python /usr/local/python3/lib/python3.7/site-packages/pyhanlp/main.py $1

---
[root@ec-n1-1d68-0005 tools]# hanlp2 -v
jar  1.7.4: /usr/local/python3/lib/python3.7/site-packages/pyhanlp/static/hanlp-1.7.4.jar
data 1.7.4: /usr/local/python3/lib/python3.7/site-packages/pyhanlp/static/data
config    : /usr/local/python3/lib/python3.7/site-packages/pyhanlp/static/hanlp.properties

[root@ec-n1-1d68-0005 tools]# hanlp2 segment <<< '好好学习天天向上'
好好学习/n 天天向上/nz

**Comment by hankcs** [comment]
正常情况下，root用户pip安装的可执行文件会放到/usr/local/bin/hanlp。如果你不是用root用户安装，则该文件可能在你的home目录里，root用户看不到。你可以sudo pip install pyhanlp试试。或者找到hanlp文件，软连接到你的path里去。

**Comment by lihaiming** [comment]
找到了，多谢。

[root@ec-n1-1d68-0005 /]# find . -name hanlp
./usr/local/python3/bin/hanlp
