### ISSUE TITLE
Dataset release suggestions

### ISSUE THREAD

**Issue by navigaid** [hankcs/HanLP#1268]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：v1.7.4
我使用的版本是：v1.7.4

## 我的问题

Hi! 

It took me hours to download the dataset for [v1.7.4](https://github.com/hankcs/HanLP/releases/tag/v1.7.4) following the links you provided in the release notes (both [data-for-1.7.4.zip](http://114.115.185.60/file/data-for-1.7.4.zip) and [网盘](https://pan.baidu.com/s/1Xl1KLjhM34ouEmYqaT-6cg) are pretty slow).

Judging from older issues it seems other people had the same problem downloading the dataset file:
- https://github.com/hankcs/HanLP/issues/1074
- https://github.com/hankcs/HanLP/issues/1042

Is it possible for you to publish the dataset directly it to the github release page along with the source code like [this](https://github.com/navigaid/HanLP/releases/tag/v1.7.4) in future releases? Thanks for your awesome work.

**Comment by hankcs** [comment]
Hi,

Sure, that's a great suggestion. I'll upload it now.

**Comment by navigaid** [comment]
Now I'll close this issue since it's been fixed. :)
