### ISSUE TITLE
关于自定义词典，在线学习 复合词及自定义词性标注的问题

### ISSUE THREAD

**Issue by yangjie8421** [hankcs/HanLP#1269]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕

## 版本号

当前最新版本号是：1.7.4
我使用的版本是：1.7.4

## 我的问题

总的需求是自定义词性和复合词能够结合起来
例如下面一段话：
String text = "腰酸、乏力、口干、目涩、手足心热、夜尿多、脉细或弱";

使用的方法默认的分词结果为：
腰酸/n 、/w 乏力/a 、/w 口干/n 、/w 目涩/Ng 、/w 手足/n 心热/n 、/w 夜尿多/j 、/w 脉/Ng 细/a 或/c 弱/a

我希望的效果：
腰酸/n 、/w 乏力/a 、/w 口干/n 、/w 目涩/Ng 、/w  [手足心/n 热/a] /clinic 、/w 夜尿多/j 、/w 脉/Ng 细/a 或/c 弱/a

我尝试了在线学习和自定义词典两种方法，发现都没办法得到预想的效果。

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

1、自定义词典：
词典：手足心热 clinic 1000

String text = "腰酸、乏力、口干、目涩、手足心热、夜尿多、脉细或弱";

        PerceptronLexicalAnalyzer analyzer = new 
                   PerceptronLexicalAnalyzer(HanLP.Config.PerceptronCWSModelPath,
                HanLP.Config.PerceptronPOSModelPath,
                HanLP.Config.PerceptronNERModelPath);

        System.out.println(analyzer.analyze(text));

### 期望输出

腰酸/n 、/w 乏力/a 、/w 口干/n 、/w 目涩/Ng 、/w  [手足心/n 热/a] /clinic 、/w 夜尿多/j 、/w 脉/Ng 细/a 或/c 弱/a

### 实际输出

腰酸/n 、/w 乏力/a 、/w 口干/n 、/w 目涩/Ng 、/w 手足心热/clinic 、/w 夜尿多/j 、/w 脉/Ng 细/a 或/c 弱/a

这种方式分词和词性标注是对的，但却不是复合词

2、在线学习的方式：
String text = "腰酸、乏力、口干、目涩、手足心热、夜尿多、脉细或弱";

        PerceptronLexicalAnalyzer analyzer = new PerceptronLexicalAnalyzer(HanLP.Config.PerceptronCWSModelPath,
                HanLP.Config.PerceptronPOSModelPath,
                HanLP.Config.PerceptronNERModelPath);

        analyzer.getNERTagSet().nerLabels.add("clinic");
        analyzer.learn("[手足心/n  热/a]/clinic");
        System.out.println(analyzer.analyze(text));

### 期望输出

腰酸/n 、/w 乏力/a 、/w 口干/n 、/w 目涩/Ng 、/w  [手足心/n 热/a] /clinic 、/w 夜尿多/j 、/w 脉/Ng 细/a 或/c 弱/a

### 实际输出
腰酸/n 、/w 乏力/a 、/w 口干/n 、/w 目涩/Ng 、/w 手足心热/n 、/w 夜尿多/j 、/w 脉/Ng 细/a 或/c 弱/a

这种方式分词是对的，但是词性标注是错的，也不是复合词

**Comment by hankcs** [comment]
1. 自定义词典中的词语不一定是命名实体，在实现上不会保留合并前的单词，所以不会输出复合词。你可以参考override com.hankcs.hanlp.tokenizer.lexical.AbstractLexicalAnalyzer#analyze不要调用 com.hankcs.hanlp.tokenizer.lexical.AbstractLexicalAnalyzer#segmentWithAttribute并自行匹配。
2. 原始语料中有几百万ns、nr和nt，而你只提供一个clinic，这造成严重的样本比例失衡，模型不会学到新知识。

建议标注自己的医疗命名实体识别语料库。

**Comment by yangjie8421** [comment]
关于医疗命名实体识别语料库，我有两个疑问：
1、如果采用自己标注的库进行训练的话，原有附带的语料库要不要保留呢？如果需要保留我有什么办法能够把两者合并或者我直接在原来的语料库上进行添加？
2、如果要建立自己的医疗实体命名语料库，建议是采用crf还是感知机或其他方式进行？

**Comment by hankcs** [comment]
1. 在重新标注的基础上保留，即把原来语料库中的医疗名词也标注出来，视新的clinic规模决定是否识别nt等标签。示例：http://file.hankcs.com/corpus/plane-re.zip
2. 建议感知机，比较快。

**Comment by yangjie8421** [comment]
不好意思，可能是我表述的还不是很清楚。
在原来的data目录下有例如：cws.bin 这些文件，我愿意是我有没有办法新建一个医疗名词的文件进行训练，然后把训练的结果合并到这些bin文件里面？如果不行的话，按照您上面的意思，我直接修改原始预料库（如：199801.txt）的标注然后再进行训练么？

**Comment by hankcs** [comment]
是的，你无法用模型叠加语料库，你只能用语料库叠加语料库。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
