### ISSUE TITLE
在linux下python时JVM路径问题

### ISSUE THREAD

**Issue by lxj0276** [hankcs/HanLP#127]
我用了绝对路径，还是找不到，jpype._jexception.RuntimeExceptionPyRaisable: java.lang.RuntimeException: Class com.hankcs.hanlp.HanLP not found，不知道怎么解决

**Comment by hankcs** [comment]
0. http://www.hankcs.com/nlp/python-calls-hanlp.html
0. Linux的路径分隔符为:

**Comment by lxj0276** [comment]
路径分隔符我用的是“/”

**Comment by hankcs** [comment]
你没懂，分割两个路径的符号，Windows是;，Linux为:

startJVM(getDefaultJVMPath(), "-Djava.class.path=C:\hanlp\hanlp-1.2.7.jar;C:\hanlp")

**Comment by lxj0276** [comment]
已经可以了，谢谢~才接触linux，不太了解一些用法。
