### ISSUE TITLE
同义词多次出现会被覆盖

### ISSUE THREAD

**Issue by yangyang303** [hankcs/HanLP#1278]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [√] 我在此括号内输入x打钩，代表上述事项确认完毕

## 版本号

当前最新版本号是：1.7.4
我使用的版本是：1.7.4

## 我的问题

如果同一个词多次出现，会被替换，例如：Aa01A01=北京 北京人   Aa01A02=北京 北京天安门

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

```
    for (Synonym synonym : synonymList)
                {
                    treeMap.put(synonym.realWord, new SynonymItem(synonym, synonymList, type));
                    // 这里稍微做个test
                    //assert synonym.getIdString().startsWith(line.split(" ")[0].substring(0, line.split(" ")[0].length() - 1)) : "词典有问题" + line + synonym.toString();
                }
```
### 期望输出

这里可以判断是否存在，存在则追加，反之新增
```
北京 北京人 北京天安门
```

### 实际输出

```
北京 北京天安门
```

**Comment by hankcs** [comment]
这实际上属于一词多义现象，目前的实现是把多义项所属的簇合并了，正确方法是用集合储存。
