### ISSUE TITLE
使用gevent多进程启动flask报错Error occurred during initialization of VM Could not reserve enough space for object heap

### ISSUE THREAD

**Issue by achenjie** [hankcs/HanLP#1279]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕

## 版本号

当前最新版本号是：1.7.4
我使用的版本是：1.7.4

## 我的问题

你好，在使用gevent多进程启动flask服务时，在服务中有一个模块使用到hanlp中的文本相似度分析，调用方法如下述代码，启动服务时报错Error occurred during initialization of VM; Could not reserve enough space for object heap，若是将该模块从服务中移除，重新启动服务，服务可以正常启动。

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

```
from pyhanlp import SafeJClass

@app.route('/api/nearest/parse', methods=['POST'])
def NearestParse():
    request_object = json.loads(request.get_data().decode('utf-8'))
    text = request_object['text']

    docs = []
    
    for idx, doc in enumerate(docs):
        doc2vec.addDocument(idx, doc)
        
    for res in interpreter.nearest(text):
        print(res.getKey().intValue(), round(res.getValue().floatValue(), 2))

class start_model_server:
    def __init__(self, port):
        self.port = port
    
    def start_new_server(self): 
        server = WSGIServer(('0.0.0.0', self.port), app)
        server.init_socket()
        server.start()
        server.start_accepting()
        server._stop_event.wait()
        
if __name__ == '__main__':
    WordVectorModel = SafeJClass('com.hankcs.hanlp.mining.word2vec.WordVectorModel')
    DocVectorModel = SafeJClass('com.hankcs.hanlp.mining.word2vec.DocVectorModel')
    word2vec = WordVectorModel(word2vec_path)
    doc2vec = DocVectorModel(word2vec._proxy)
    from multiprocessing import Process
    ports = [6000,6001,6002,6003]
    for port in ports:
        s = start_model_server(port)
        p = Process(target=s.start_new_server)
        p.start()
```
### 期望输出

```
服务正常启动
```

### 实际输出

```
Error occurred during initialization of VM
Could not reserve enough space for object heap
```

**Comment by achenjie** [comment]
还有就是，若只是移除了代码块，但是保留着from pyhanlp import SafeJClass这句代码，服务启动一样会报Error occurred during initialization of VM；Could not reserve enough space for object heap错误

**Comment by hankcs** [comment]
`from pyhanlp import`会触发核心词典的加载，这需要一些内存。不妨检查一下你的机器有多少内存，其他模块吃了多少，还剩下多少给pyhanlp。

**Comment by achenjie** [comment]
我机器是4核16g，我之前也怀疑过是否是内存的问题，于是做了以下验证：
1、打开pyhanlp下__int__.py文件，注释掉所有API列表，重新启动服务，仍然报该错误；
2、注释其它模块的所有服务，只保留文本相似度分析的模块，重新启动服务，仍然报该错误；
3、不使用多进程进行启动服务，服务正常启动，触发代码：
      ```
           start_model_server()
      ```
4、不使用多进程启动服务，使用多线程启动服务，服务正常启动，触发代码：
     ```
            import threading    
            threads = []
            ports = [6000,6001,6002,6003]
            for port in ports:
                s = start_model_server(port)
                thread = threading.Thread(target = s.start_new_server)
                threads.append(thread)
            for thread in threads:
                thread.setDaemon(True)
                thread.start()
            thread.join()
     ```
5、使用多进程启动服务，只用一个进程，服务正常启动，触发代码：
     ```
            ports = [6000]
            for port in ports:
                s = start_model_server(port)
                p = Process(target=s.start_new_server)
                p.start()
     ```

问题：若使用多进程启动服务，一个进程可以正常启动，一个进程以上就会报该错误，之前使用多线程时也会遇到该问题，查找原因之后才知道 JVM 并没有能为新开启的线程提供服务，解决方法加入
```
if not jpype.isThreadAttachedToJVM():
      jpype.attachThreadToJVM()
```
这个多进程报错的问题是不是跟JVM有关，类似于多线程？

**Comment by achenjie** [comment]
我机器是4核16g，我之前也怀疑过是否是内存的问题，于是做了以下验证：
1、打开pyhanlp下__int__.py文件，注释掉所有API列表，重新启动服务，仍然报该错误；
2、注释其它模块的所有服务，只保留文本相似度分析的模块，重新启动服务，仍然报该错误；
3、不使用多进程进行启动服务，服务正常启动，触发代码：
```
start_model_server()
```
4、不使用多进程启动服务，使用多线程启动服务，服务正常启动，触发代码：
```
import threading 
threads = [] 
ports = [6000,6001,6002,6003] 
for port in ports: 
      s = start_model_server(port) 
      thread = threading.Thread(target = s.start_new_server) 
      threads.append(thread) 
for thread in threads: 
      thread.setDaemon(True) 
      thread.start() 
thread.join()
```
5、使用多进程启动服务，只用一个进程，服务正常启动，触发代码： 
```
ports = [6000] 
for port in ports: 
      s = start_model_server(port) 
      p = Process(target=s.start_new_server) 
      p.start()
```
问题：若使用多进程启动服务，一个进程可以正常启动，一个进程以上就会报该错误，之前使用多线程时也会遇到该问题，查找原因之后才知道 JVM 并没有能为新开启的线程提供服务，解决方法加入
```
if not jpype.isThreadAttachedToJVM():
      jpype.attachThreadToJVM()
```
这个多进程报错的问题是不是跟JVM有关，类似于多线程？

**Comment by hankcs** [comment]
请参考：https://github.com/hankcs/HanLP/issues/1211 https://github.com/hankcs/HanLP/issues/1201

**Comment by achenjie** [comment]
之前这连个issue也是我问的，都是多线程的问题，这个已经解决了，目前遇到的是多进程的问题，是不是JVM不支持为新开启的进程提供服务？

**Comment by achenjie** [comment]
之前这两个issue也是我问的，都是多线程的问题，这个已经解决了，目前遇到的是多进程的问题，是不是JVM不支持为新开启的进程提供服务？

**Comment by hankcs** [comment]
我也不清楚jpype多进程的机制，以我的粗浅的理解：

1. Python的多线程就是多进程模拟的
2. 高并发应该用Java做。

**Comment by achenjie** [comment]
好的，非常感谢！我再研究研究，内存是充足，就是不清楚为什么会报这个错误，我对java不熟，开发用的是python
