### ISSUE TITLE
当地名第二位是方位词时 分词不准确

### ISSUE THREAD

**Issue by warlockhades** [hankcs/HanLP#1284]
* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号
当前最新版本号是：hanlp-1.7.4
我使用的版本是：hanlp-1.5.0

## 我的问题
在用户自定义词典文本中配置了地名“淮南 ns 100“ 100是较大的词频 但当输入”6月28日淮南“时，不能得到”淮南“
分词结果为[6/m, 月/qt, 28/m, 日淮南/ns]

## 复现问题
Segment SEGMENT = HanLP.newSegment()
					.enableCustomDictionaryForcing(true)
					.enableNameRecognize(true)
					.enableTranslatedNameRecognize(true)
					.enableJapaneseNameRecognize(true)
					.enablePlaceRecognize(true)
					.enableOrganizationRecognize(true)
					.enablePartOfSpeechTagging(true);

### 步骤
1. 首先在\data\dictionary\custom下添加了新文本文件 使用utf-8编码 crlf换行
2. 然后在配置文件中添加"淮南 ns 100"

### 期望输出
期望分词结果为[6,月,28,日,淮南]

### 实际输出
实际分词结果为[6,月,28,日淮南]
没有分出地名淮南

## 其他信息
“肥东”、“肥西”等 第二个字是方位词的 不著名的 地名 都会分成“日肥东”，“日肥西”

**Comment by hankcs** [comment]
请使用1.7.4，不存在此问题。

```
[6月/t, 28/m, 日/b, 淮南/ns]
```
