### ISSUE TITLE
分词badcase“十一推送内容”，不知如何纠正

### ISSUE THREAD

**Issue by tiandiweizun** [hankcs/HanLP#1288]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.7.4
我使用的版本是：1.7.4

## 我的问题

下载了1.7.4的数据包  HanLP.segment来分词“十一推送内容”，出现badcase，不知如何纠正

### 步骤

HanLP.segment("十一推送内容")

### 期望输出

```
十一/推送/内容
```
### 实际输出

```
十/一推/送/内容
```

**Comment by hankcs** [comment]
未能复现，一切正常 [十一/m, 推/v, 送/v, 内容/n] 。你是否挂载了“一推”之类的自定义词库？

**Comment by tiandiweizun** [comment]
我再次确认了一下，我的输出结果没有问题，我没有挂载自定义词库
1. 使用的是 release页面的data-for-1.7.4
2. 调用的接口是 HanLP.segment("十一推送内容")，非NLPTokenizer。

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。
