### ISSUE TITLE
jvm内存问题

### ISSUE THREAD

**Issue by lxj0276** [hankcs/HanLP#129]
有个问题很困惑，是不是jvm比较占内存，我在用python时，还是比较平稳的，但是在用jvm调用hanlp时，就会飙升上去

**Comment by hankcs** [comment]
分词内存120MB以上（-Xms120m -Xmx120m -Xmn64m）

句法分析的时候，模型本身就有500-600MB。

**Comment by hankcs** [comment]
这个问题应该解决了，如果还有问题，欢迎再开issue。
