### ISSUE TITLE
jpype调用错误

### ISSUE THREAD

**Issue by MingxuanLiu** [hankcs/HanLP#1291]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：
我使用的版本是：1.7.4

## 我的问题
jpype调用报错：jpype._jclass.ArrayIndexOutOfBoundsException: 1208
整体报错：
Traceback (most recent call last):
  File "entity_2.py", line 123, in <module>
    main()
  File "entity_2.py", line 48, in main
    sentence = HanLP.parseDependency(line)
jpype._jclass.ArrayIndexOutOfBoundsException: 1208

## 复现问题
没有额外的操作，只是调用了句法分析这个接口。

### 触发代码
sentence = HanLP.parseDependency(line)

**Comment by hankcs** [comment]
能把引发问题的这一行print出来吗？

**Comment by MingxuanLiu** [comment]
打印sentence么？
但是我是运行在9w+个句子上，前面一直是很正常的，但是运行到某一句就会报错，没有查看是哪一句出了问题。我可以加个print，但是看报错的话，报错的这一句话的sentence应该是打印不出来。
会不会是多个句子连续操作的时候，会有内存上的错误？因为我在运行的时候，单个句子单独运行的结果，有时候跟这个句子在连续9w+个句子中的运行结果不一样，会不会有内存覆盖的问题？

**Comment by MingxuanLiu** [comment]
> 能把引发问题的这一行print出来吗？
打印sentence么？
但是我是运行在9w+个句子上，前面一直是很正常的，但是运行到某一句就会报错，没有查看是哪一句出了问题。我可以加个print，但是看报错的话，报错的这一句话的sentence应该是打印不出来。
会不会是多个句子连续操作的时候，会有内存上的错误？因为我在运行的时候，单个句子单独运行的结果，有时候跟这个句子在连续9w+个句子中的运行结果不一样，会不会有内存覆盖的问题？

**Comment by hankcs** [comment]
不可能是内存问题。

你可以try catch，在抛异常的时候打印。

**Comment by MingxuanLiu** [comment]
Exception:  <class 'Exception'>
error:  1208
repr:  ArrayIndexOutOfBoundsException()
err.message:  <bound method _JException.message of ArrayIndexOutOfBoundsException()>
Traceback (most recent call last):
  File "entity_2.py", line 104, in main
    sentence = HanLP.parseDependency(line)
jpype._jclass.java.lang.ArrayIndexOutOfBoundsException: 1208
traceback:  None
traceback.format_exc():  Traceback (most recent call last):
  File "entity_2.py", line 104, in main
    sentence = HanLP.parseDependency(line)
jpype._jclass.java.lang.ArrayIndexOutOfBoundsException: 1208

> 不可能是内存问题。
> 
> 你可以try catch，在抛异常的时候打印。

Exception:  <class 'Exception'>
error:  1208
repr:  ArrayIndexOutOfBoundsException()
err.message:  <bound method _JException.message of ArrayIndexOutOfBoundsException()>
Traceback (most recent call last):
  File "entity_2.py", line 104, in main
    sentence = HanLP.parseDependency(line)
jpype._jclass.java.lang.ArrayIndexOutOfBoundsException: 1208
traceback:  None
traceback.format_exc():  Traceback (most recent call last):
  File "entity_2.py", line 104, in main
    sentence = HanLP.parseDependency(line)
jpype._jclass.java.lang.ArrayIndexOutOfBoundsException: 1208


> 不可能是内存问题。
> 
> 你可以try catch，在抛异常的时候打印。

Exception:  <class 'Exception'>
error:  1208
repr:  ArrayIndexOutOfBoundsException()
err.message:  <bound method _JException.message of ArrayIndexOutOfBoundsException()>
Traceback (most recent call last):
  File "entity_2.py", line 104, in main
    sentence = HanLP.parseDependency(line)
jpype._jclass.java.lang.ArrayIndexOutOfBoundsException: 1208
traceback:  None
traceback.format_exc():  Traceback (most recent call last):
  File "entity_2.py", line 104, in main
    sentence = HanLP.parseDependency(line)
jpype._jclass.java.lang.ArrayIndexOutOfBoundsException: 1208

这是详细报错信息。

**Comment by MingxuanLiu** [comment]
> 不可能是内存问题。
> 
> 你可以try catch，在抛异常的时候打印。

Exception:  <class 'Exception'>
error:  1208
repr:  ArrayIndexOutOfBoundsException()
err.message:  <bound method _JException.message of ArrayIndexOutOfBoundsException()>
Traceback (most recent call last):
  File "entity_2.py", line 104, in main
    sentence = HanLP.parseDependency(line)
jpype._jclass.java.lang.ArrayIndexOutOfBoundsException: 1208
traceback:  None
traceback.format_exc():  Traceback (most recent call last):
  File "entity_2.py", line 104, in main
    sentence = HanLP.parseDependency(line)
jpype._jclass.java.lang.ArrayIndexOutOfBoundsException: 1208
这是详细报错信息

**Comment by hankcs** [comment]
你要捕获这个异常然后打印line。

**Comment by MingxuanLiu** [comment]
> 你要捕获这个异常然后打印line。

print了一下好像是因为这句话太长了，hanlp对长度是有限制的么？

**Comment by MingxuanLiu** [comment]
> > 你要捕获这个异常然后打印line。
> 
> print了一下好像是因为这句话太长了，hanlp对长度是有限制的么？

**Comment by MingxuanLiu** [comment]
> 你要捕获这个异常然后打印line。

可或缺的日常细节中，他们是抱着装尿不湿的巨大纸箱而来的快递小哥，是用冻伤的手给我做早餐的煎饼摊老板，是我吓得拉住他的工作服16/1902]
下窗台而他耐心宽慰我的四川小伙。那些面孔那么具体，那么鲜活。    对每一个这样的个体来说，出身、天赋、教育、命运、能力、志趣、环境……
都可能决定他们将离开哪里，走向哪里。    我知道，有的快递员会抢劫杀人，有的小摊食品细菌超标，有的大哥搬个柜子可能漫天要价。还有人会
说：“等火烧到你家你就闭嘴了。”    可是，难道这座城市，没有了他们，就没有谎言、罪恶和灾难了吗？在人性和劳动面前，谁也不比谁高一等。
    反正，下一次快递小哥来的时候，我会跟我女儿说：“这个快递员叔叔就是圣诞老人。”    ——在她还相信美好的年纪。 ￼〖点滴〗没有这样的人
    作者：李碧华    某选美评委一再表示，她与其他几位在评判时早已取得共识。她说：“十二个女孩子中，是没有靓到可以不考虑她们的操行就
让她们拿奖的。”——世上哪有“惊为天人”，可让人完全不作任何考虑便全部投她一票的美女？若有，相由心生，一定亦令人如沐春风。既然没有，一
切便只是小众的比较了。    靓不靓，得公认。    选美年年有。当选的认为公平，落选的认为黑暗而“贱”（好新鲜的形容词。岂非也踹了自己一脚
），累得有头有面的评委们出来澄清一番。此乃后遗症。    一场游戏，参加的都是些十来二十岁博出位的小女孩，真令人叹为观止——不要紧，明年
继续跳舞。用知识来评判的话，很有意思。    没有人靓到可不讲操行。借用一下——  没有人有才华到可不讲风骨。  没有人得势到可不问良心。
没有人能干到可不靠朋友。  没有人霸道到可不求事实真相。  没有人富贵到可不信命。  没有人幸运到可不择手段。  没有人聪明到可不坠落情网
。  没有人——  〖乐吧〗两则    、【不挑食】  成熟的大人不会挑食。成熟的大人会说：“这个我不能吃，吃了会过敏。”    【拍水】  出门的时
候在电梯里遇到一个用双手狂拍自己脸的小宝宝，一旁他的奶奶非常淡定地  说：“又学妈妈往脸上拍水呢？” ￼〖话题〗香港的高楼与北京的大树
  作者：汪曾祺    香港多高楼，无大树。    中环一带，高楼林立，车如流水。楼多在五六十层以上。因为都很高，所以也显不出哪一座特别突出
。建筑材料中钢筋水泥已经少见了。多是飞机钢、合金铝、透亮的玻璃、纯黑的大理石。香港马路窄，无行道树。寸土如金，无隙地可种树也。  这
个城市，五光十色，只是缺少必要的、足够的绿。    半山有树。    山顶有树。  只是似乎没有人注意这些树，欣赏这些树。树被人忽略了。
海洋公园有树，都修剪得很规整。这里有从世界各地移来的植物。扶桑花皆如碗大，有深红、浅红、白色的，内地少见。但是游人极少在这些过于鲜
艳的花木之间流连。他们到这里来的目的是乘坐“疯狂飞天车”、浪船、“八脚鱼”之类的富于刺激性的、使人晕眩的游乐玩意。  我对这些玩意全都不
敢领教，只是吮吸着可口可乐，看看年轻人乘坐这些玩意时兴奋紧张的神情，听他们在危险的瞬间发出惊呼。我老了。  我坐在酒店的房间里（我在
香港极少逛街，张辛欣说我从北京到香港就是换一个地方坐着），想起北京的大树，中山公园、劳动人民文化宫、天坛的柏树，北海的白皮松。  渡
海到大屿岛梅窝参加内地和香港作家的交流营，住了两天。这是香港人度假的地方，很安静。海、沙滩、礁石。错错落落，不太高的建筑。上山的小
道。我现在明白了，为什么居住在高度现代化的城市的人需要度假。他们需要暂时离开紧张的生活节奏，需要安静，需要清闲。    古华看看大屿山
，两次提出疑问：“为什么山上没有大树？”他说：“如果有十棵大松树，不要多，有十棵，就大不一样了！”山上山下是有树的。台湾相思树，枝叶都
很美。只是大树确实是没有。    没有古华家乡的大松树。    也没有北京的大柏树、白皮松。  “所谓故国者，非谓有乔木之谓也。”然而没有乔木
，是不成其为故国的。至少在明朝的时候，北京的大树就有了名。北京有大树，北京才成为北京。  回北京，下了飞机，坐在“的士”里，与同车作家
谈起香港的速度。    司机在前面搭话：“北京将来也会有那样的速度！”他的话不错。北京也是要高度现代化的，会有高速度的。现代化、高速度以
后的北京会是什么样子呢？想起那些大树，我就觉得安心了。现代化之后的北京，还会是北京。 〖看点〗 辨 冤    作者：刘云生  　  宋代的钱
若水，因仁孝知名，以诚待人，襟怀坦荡。他担任同州推官，主管司法行政。他的一位同僚曾经向富翁借钱，富翁知道，这是肉包子打狗，没借。不
久，这富人家的一个女仆逃亡，这个同僚就唆使女仆的父母，状告富家父子杀人掩尸。一顿棍子下来，富翁屈打成招，被判死罪。  钱若水觉得疑点
太多，把案子压了下来。同僚找上门来，冲他一顿乱骂，说他和富家有说不清道不明的关系。  钱若水笑笑说：“这一刀下去，几个人都要人头落地
，我再仔细看看好不好？”  后来，钱若水悄悄派人找到逃亡的女仆，把案子移送到知州大人手上，一桩冤假错案，就此平反。知州当堂解除枷锁，
富翁一家号啕大哭，叩头不断，感恩戴德。知州受不了，就说：“不是我救了你家，是钱推官。”富豪一家去拜见钱若水，钱若水闭门不见，传话说：
“是知州大人明察秋毫，跟我一点关系都没有。”富豪一家绕墙痛哭，久久不去。  后来，知州大人要给钱若水请功，钱若水摇头摆手：“大人，我只
想不冤杀无辜，这是本分，从没想过要立功升官。你要一报功，我那同僚一家不就完了吗？”  这就是历史上著名的钱若水辨冤。  ※谢谢浏览※  以
上为本期手机报全部内容    【彩信简介】本手机报每周5期，逢周一至周五出版。  【订阅方法】请编辑短信dub（大小写均可）发送至10659000，
即可订阅；发送qxdub（大小写均可）至10659000，即可退订。每月信息费5元。  客服电话：拨打本地10000    【温馨提示】  ●请将阅读完的彩信定期删除，以保证留有更多空间接收新的彩信内容。   ●感谢您收看本期内容，下期内容更精彩！

**Comment by hankcs** [comment]
分词接口是没有限制的，parseDependency应该也是没有限制的，但是对超过一句话的文本分析句法树是没有任何意义的。

**Comment by hankcs** [comment]
你可以先用`com.hankcs.hanlp.utility.SentencesUtil#toSentenceList(java.lang.String)`分句。

**Comment by MingxuanLiu** [comment]
> 你可以先用`com.hankcs.hanlp.utility.SentencesUtil#toSentenceList(java.lang.String)`分句。

好的！谢谢您！

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
