### ISSUE TITLE
hanlp和pyhanlp的dependency parse结果不一致

### ISSUE THREAD

**Issue by lan2720** [hankcs/HanLP#1294]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [ ] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：
我使用的版本是：

jar  1.7.4: lib/python3.7/site-packages/pyhanlp-0.1.49-py3.7.egg/pyhanlp/static/hanlp-1.7.4.jar
data 1.7.4: lib/python3.7/site-packages/pyhanlp-0.1.49-py3.7.egg/pyhanlp/static/data
config    : lib/python3.7/site-packages/pyhanlp-0.1.49-py3.7.egg/pyhanlp/static/hanlp.properties

## 我的问题

```
sent = "中国11家主流快递公司宣布开启备战双11"
from pyhanlp import HanLP, JClass
sentence = HanLP.parseDependency(sent)
print([w.LEMMA for w in sentence.iterator()])
```
得到的结果是: ['中国', '11', '家主', '流', '快递公司', '宣布', '开启', '备战', '双', '11']

但是，直接在命令行中使用`hanlp segment <<< "中国11家主流快递公司宣布开启备战双11"`(或hanlp parse)得到的结果是:
中国/ns 11/m 家/q 主流/n 快递公司/nis 宣布/v 开启/v 备战/vi 双/q 11/m

明显第二个是对的，也就是pyhanlp的结果为什么和hanlp不一致呢？

**Comment by lan2720** [comment]
![错误截图.png](http://ww1.sinaimg.cn/large/901f9a6fgy1g7u6trg40wj20mf0ec40q.jpg)
在customDict中没有任何自己insert的词(只是默认的static/data/dictionary/custom/CustomDictionary.txt等文件)
为什么在enforce前后会出现这么大的不同呢？检查了下CustomDictionary.txt中没有“同””比增“”长“这样的词呀 。

**Comment by lan2720** [comment]
这种问题同样出现在sent = "中国11家主流快递公司宣布开启备战双11"这个case中
为什么enableCustomDictionaryForcing后会出现一些诡异的分词（这些词不存在于自定义词典中）

**Comment by hankcs** [comment]
未能复现

```
$ python3
Python 3.6.6 (default, Sep 14 2018, 21:44:44) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> sent = "中国11家主流快递公司宣布开启备战双11"
>>> from pyhanlp import HanLP, JClass
sentence = HanLP.parseDependency(sent)
print([w.LEMMA for w in sentence.iterator()])>>> sentence = HanLP.parseDependency(sent)

>>> print([w.LEMMA for w in sentence.iterator()])
['中国', '11', '家', '主流', '快递公司', '宣布', '开启', '备战', '双', '11']

$ hanlp -v
jar  1.7.4: python3.6/site-packages/pyhanlp/static/hanlp-1.7.4.jar
data 1.7.4: python3.6/site-packages/pyhanlp/static/data
config    : python3.6/site-packages/pyhanlp/static/hanlp.properties
```

在1.7.4中parser使用的是NLPTokenizer，如果你修改StandardTokenizer改变了parser的行为，那么说明你用的不是1.7.4。你hanlp -v和import的不是同一个pyhanlp。

**Comment by lan2720** [comment]
@hankcs 不好意思这里的命名产生了误解，StandardTokenizer=JClass("com.hankcs.hanlp.tokenizer.NLPTokenizer")，这里我调用的是NLPTokenizer
完整的复现代码如下:
```
In [1]: sent = "中国11家主流快递公司宣布开启备战双11"

In [2]: from pyhanlp import HanLP, JClass

In [3]: sentence = HanLP.parseDependency(sent)

In [4]: print([w.LEMMA for w in sentence.iterator()])
['中国', '11', '家', '主流', '快递公司', '宣布', '开启', '备战', '双', '11']

In [5]: nlpTokenizer = JClass("com.hankcs.hanlp.tokenizer.NLPTokenizer")

In [6]: nlpTokenizer.ANALYZER.enableCustomDictionaryForcing(True)
Out[6]: <jpype._jclass.com.hankcs.hanlp.model.perceptron.PerceptronLexicalAnalyzer at 0x1417237d0>

In [7]: sentence = HanLP.parseDependency(sent)

In [8]: print([w.LEMMA for w in sentence.iterator()])
['中国', '11', '家主', '流', '快递公司', '宣布', '开启', '备战', '双', '11']

In [9]: nlpTokenizer.ANALYZER.enableCustomDictionaryForcing(False)
Out[9]: <jpype._jclass.com.hankcs.hanlp.model.perceptron.PerceptronLexicalAnalyzer at 0x141ccb8d0>

In [10]: sentence = HanLP.parseDependency(sent)

In [11]: print([w.LEMMA for w in sentence.iterator()])
['中国', '11', '家', '主流', '快递公司', '宣布', '开启', '备战', '双', '11']
```
我目前的疑问在于，强制使用自定义词典后，对分词结果的影响比较奇怪，自定义词典txt文件里也没有这些词，为什么会被分成这样呢？
![错误截图.png](http://ww1.sinaimg.cn/large/901f9a6fgy1g7v6115f52j20jb0cmmzk.jpg)
多谢解答~

**Comment by lan2720** [comment]
这里我没有insert任何新词到自定义词典中，customDictionary只有您data/dictionary/custom/下的原始文件

**Comment by lan2720** [comment]
这里`nlpTokenizer.ANALYZER.enableCustomDictionaryForcing(True)`是因为我想在custom dictionary中增加一些特定领域的专有名词，希望能强制分出来这些词，不知道是否有更好的方式能强制分出来。
但目前看到是还没有insert新词其分词效果就受到了不好的影响

**Comment by hankcs** [comment]
> 家主

```
find . -name "*.txt" | xargs grep -i "家主" 
./custom/现代汉语补充词库.txt:国家主义  nz      19
./custom/现代汉语补充词库.txt:国家主权  nz      3
./custom/现代汉语补充词库.txt:家主      n       202
./custom/现代汉语补充词库.txt:家主儿    n       3
```

**Comment by hankcs** [comment]
你可以只挂载你的词典。

**Comment by lan2720** [comment]
@hankcs 非常感谢！
