### ISSUE TITLE
性能测试 DoubleArrayTrie 内存使用 > AhoCorasickDoubleArrayTrie >  Bintrie

### ISSUE THREAD

**Issue by shengjiz** [hankcs/HanLP#1295]
## 版本号

当前最新版本号是：
我使用的版本是：1.7.2

## 我的问题
按照原理 
   对DAT 、 ACDat 、Bintrie 进行性能测试

测试文本 : 

"最近正在做一个自己的NLP库，刚起步的第一个问题就是字典的储存与查询。毫无疑问，最佳的数据结构是Trie树，同时为了平衡效率和空间，决定使用双数组Trie树。现在的问题是，双数组Trie树是一个压缩的Trie树";

测试词典: 
CoreNatureDictionary.txt

JVM 堆设置: -Xms2g Xmx2g 

性能分析工具: JConsole  

测试结果 : 
按照原理 DAT 的内存使用应该是三者最小的
但目前测到的结果 DAT > ACDAT > Bintrie 
反而 Bintrie 堆内存使用最小

性能方面 : DAT 性能约等于 ACDAT > Bintrie 

### 触发代码

```
        String text = "最近正在做一个自己的NLP库，刚起步的第一个问题就是字典的储存与查询。毫无疑问，最佳的数据结构是Trie树，同时为了平衡效率和空间，决定使用双数组Trie树。现在的问题是，双数组Trie树是一个压缩的Trie树";

public void testACDAT() throws InterruptedException {
        Thread.sleep(10000);
        Runtime.getRuntime().gc();
        TreeMap<String, CoreDictionary.Attribute> map = new TreeMap<String, CoreDictionary.Attribute>();
        IOUtil.LineIterator iterator = new IOUtil.LineIterator("data/dictionary/CoreNatureDictionary.txt");
        while (iterator.hasNext())
        {
            String line = iterator.next().split("\\s")[0];
            map.put(line, new CoreDictionary.Attribute(Nature.n));
        }
        Runtime.getRuntime().gc();
        System.out.println(" Map 构建成功 !!!!!");
        Thread.sleep(10000);

        //AhoCorasickDoubleArrayTrie<CoreDictionary.Attribute> act = new AhoCorasickDoubleArrayTrie<CoreDictionary.Attribute>();
        //DoubleArrayTrie<CoreDictionary.Attribute> act = new DoubleArrayTrie<CoreDictionary.Attribute>();
        BinTrie<CoreDictionary.Attribute> act = new BinTrie<CoreDictionary.Attribute>();
        long timeMillis = System.currentTimeMillis();
        act.build(map);
        System.out.println("构建耗时：" + (System.currentTimeMillis() - timeMillis) + " ms");
        timeMillis = System.currentTimeMillis();
        for(int i = 0 ; i < 30000000; i ++){
            act.parseText(text, new AhoCorasickDoubleArrayTrie.IHit<CoreDictionary.Attribute>() {
                @Override
                public void hit(int begin, int end, CoreDictionary.Attribute value) {

                }
            });
        }
        System.out.println("分词耗时：" + (System.currentTimeMillis() - timeMillis) + " ms");
    }
```
### 期望输出

```
期望输出
```

### 实际输出

```
实际输出
```

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
