### ISSUE TITLE
CRFSegment 如何忽略标点？

### ISSUE THREAD

**Issue by kid1412z** [hankcs/HanLP#13]
segment.seg(sentence); 如何配置才能忽略句子中的标点？发现这个方法会把标点和词的组合作为新词

**Comment by hankcs** [comment]
举个bad case？
语料库中有些词语可能由汉字和标点组成，干扰了CRF

**Comment by kid1412z** [comment]
尼玛不是新词，王尼玛是新词 ===> “，王尼玛”

**Comment by kid1412z** [comment]
周杰伦在出品范特西之后，又出品了依然范特西 ===>"周杰伦","范特西","，又","范特西"
还有就是不会过滤重复对吧？

**Comment by hankcs** [comment]
是有问题，逗号被我转义为句号，模型对句号给出的分值不合理，可能是语料中存在错误地将句号和词语组合到一起的情况。
现在将表示终止的标点都转义为逗号，消除了这个问题：

[尼玛, 不是, 新词, ，, 王尼玛, 是, 新词]
[周杰伦, 在, 出品, 范特西, 之后, ，, 又, 出品, 了, 依然, 范特西]

过滤重复是什么意思？见过一遍的词语记下来？CRF分词不是基于词的。

**Comment by hankcs** [comment]
你将CharTable.bin.yes更新到最新就能解决问题了。

**Comment by hankcs** [comment]
结果证实了我的猜想，2014人民日报语料库里面有不少句号标错了：

方言/n 版/n [新年/t 祝福/vn]/nz 。你/rr 的/ude1 一段/mq 话/n

**Comment by kid1412z** [comment]
我下载的貌似是1.2.0的data，还有更新的吗？

**Comment by hankcs** [comment]
没有，只改动了一个文件CharTable.bin.yes，你直接从代码库checkout一份，然后替换过去就行了

**Comment by kid1412z** [comment]
多谢！

**Comment by kid1412z** [comment]
替换掉文件之后，就不能用了。报以下错误： 
com.hankcs.hanlp.dictionary.other.CharTable <clinit>
严重: 字符正规化表加载失败，原因如下：
java.io.StreamCorruptedException: invalid stream header: 0A0A0A3C
我用的是1.2.2版本，data版本是1.2.0  从代码库下载了CharTable.bin.yes替换的

**Comment by hankcs** [comment]
我倾向于认为这是checkout出问题了。
Anyway，你可以下载[data-for-1.2.2.zip](http://pan.baidu.com/s/1i3DyYYL)，这个通过了测试。
