### ISSUE TITLE
word2vec 模型有1个G，无论设置多少内存给模型，都感觉不是一般的慢，无法使用。

### ISSUE THREAD

**Issue by yangnianen** [hankcs/HanLP#1304]
我的word2vec 模型有1个G，发现运行docVectorModel.nearest 方法是在太慢，我应该如何提高模型训练好的，预测速度？现在大于 20秒以上，真痛心，压根没法用呢

**Comment by hankcs** [comment]
效率瓶颈有两个方面：

1. 单词查找。你可以传入一个你认为比较快的Map：https://github.com/hankcs/HanLP/blob/3c214ec2a68f51fc88420d76c37774592befc11d/src/main/java/com/hankcs/hanlp/mining/word2vec/WordVectorModel.java#L39
2. 向量点积。你可以尝试重载https://github.com/hankcs/HanLP/blob/7c7e202d743e002c610815c3dfebe08325cfb360/src/main/java/com/hankcs/hanlp/mining/word2vec/AbstractVectorModel.java#L96 用多线程实现点积。
