### ISSUE TITLE
 分类训练的目录结构能否支持一个文件里头包含很多个文章的?

### ISSUE THREAD

**Issue by nice2mu** [hankcs/HanLP#1306]
/**
     * 用UTF-8编码的语料训练模型
     *
     * @param folderPath  用UTF-8编码的分类语料的根目录.目录必须满足如下结构:<br>
     *                    根目录<br>
     *                    ├── 分类A<br>
     *                    │   └── 1.txt<br>
     *                    │   └── 2.txt<br>
     *                    │   └── 3.txt<br>
     *                    ├── 分类B<br>
     *                    │   └── 1.txt<br>
     *                    │   └── ...<br>
     *                    └── ...<br>
     *                    文件不一定需要用数字命名,也不需要以txt作为后缀名,但一定需要是文本文件.

原支持格式如上

但是假设文本有几十万个的话,文件系统压力很大. 

所以能不能支持一下
一个目录有几个文件  文件名代表分类,  文件里头每一行就是一个文章.

经济.1
经济.2

体育.1
体育.2

军事.1
军事.2
军事.3

类似以上

万分感谢

**Comment by hankcs** [comment]
建议使用 https://github.com/hankcs/HanLP/blob/0ec10804902417fd2c1294c84b6830482a262d13/src/main/java/com/hankcs/hanlp/classification/classifiers/IClassifier.java#L138 接口。
