### ISSUE TITLE
命名实体识别问题

### ISSUE THREAD

**Issue by congjiao1988** [hankcs/HanLP#131]
文本 = "交易账号：96600009934569490中国银行股份有限公司济南";

分词结果 [交易/vn, 账号/n, ：/w, 96600009934569490中国银行股份有限公司济南/nt]

BasicTokenizer中SEGMENT = HanLP.newSegment().enableAllNamedEntityRecognize(true).enableCustomDictionary(true);

貌似只开启命名实体识别或是自定义词典中的一个就能将数字和机构名分开，若两个同时开启则当做一个整体，这个问题怎么解决呢

**Comment by hankcs** [comment]
0. 暂时需要你去写过滤逻辑
0. 在缺乏人工或规则过滤的情况下，不建议开启机构名识别
