### ISSUE TITLE
运行本书ch02 evaluate_cws 会报错

### ISSUE THREAD

**Issue by time-py** [hankcs/HanLP#1317]
运行后报错 错误为：
jpype._jclass.NoClassDefFoundError: java.lang.NoClassDefFoundError: com/hankcs/hanlp/HanLP

**Comment by hankcs** [comment]
下载 http://hanlp.com/static/release/hanlp-1.7.5-release.zip ，解压为 pyhanlp/static/hanlp-1.7.5.jar

**Comment by cllx** [comment]
下载解压了 pyhanlp/static/hanlp-1.7.5.jar之后还是报这个错 不知道为什么

**Comment by time-py** [comment]
> 下载解压了 pyhanlp/static/hanlp-1.7.5.jar之后还是报这个错 不知道为什么

把下载下来的文件名称改一下 不要和hanlp包的名称重复

**Comment by cllx** [comment]
我是用的python3.8装的pyhanlp，把 http://hanlp.com/static/release/hanlp-1.7.5-release.zip解压后放在D:\软件\python3.8\Lib\site-packages\pyhanlp\static这个目录下的，hanlp.properties里也是写的这个目录，始终报错jpype._jclass.NoClassDefFoundError: java.lang.NoClassDefFoundError: com/hankcs/hanlp/HanLP

**Comment by time-py** [comment]
> 我是用的python3.8装的pyhanlp，把 [http://hanlp.com/static/release/hanlp-1.7.5-release.zip解压后放在D:\软件\python3.8\Lib\site-packages\pyhanlp\static这个目录下的，hanlp.properties里也是写的这个目录，始终报错jpype._jclass.NoClassDefFoundError](http://hanlp.com/static/release/hanlp-1.7.5-release.zip%E8%A7%A3%E5%8E%8B%E5%90%8E%E6%94%BE%E5%9C%A8D:%5C%E8%BD%AF%E4%BB%B6%5Cpython3.8%5CLib%5Csite-packages%5Cpyhanlp%5Cstatic%E8%BF%99%E4%B8%AA%E7%9B%AE%E5%BD%95%E4%B8%8B%E7%9A%84%EF%BC%8Chanlp.properties%E9%87%8C%E4%B9%9F%E6%98%AF%E5%86%99%E7%9A%84%E8%BF%99%E4%B8%AA%E7%9B%AE%E5%BD%95%EF%BC%8C%E5%A7%8B%E7%BB%88%E6%8A%A5%E9%94%99jpype._jclass.NoClassDefFoundError): java.lang.NoClassDefFoundError: com/hankcs/hanlp/HanLP

你也是运行ch02 evaluate_cws文件报的这个错误吧，你从git-hub拉下来的代码文件，pyhanlp-master 这个文件里面 项目文件叫pyhanlp 你把这个文件名改一下就行，我改成了pyhanlp_test

**Comment by cllx** [comment]
我是用pip3安装的pyhanlp，我把python的安装目录site-packages下的pyhanlp包名称改成了pyhanlp_test，hanlp.properties里的路径也改了，重新运行还是不行，太难了

**Comment by hankcs** [comment]
> 我是用pip3安装的pyhanlp，我把python的安装目录site-packages下的pyhanlp包名称改成了pyhanlp_test，hanlp.properties里的路径也改了，重新运行还是不行，太难了

多查[文档](https://github.com/hankcs/pyhanlp/wiki/%E6%89%8B%E5%8A%A8%E9%85%8D%E7%BD%AE)，网络不好缺什么下什么。

**Comment by time-py** [comment]
> 我是用pip3安装的pyhanlp，我把python的安装目录site-packages下的pyhanlp包名称改成了pyhanlp_test，hanlp.properties里的路径也改了，重新运行还是不行，太难了

我想你是误解我的意思了，首先 你确定是运行  运行本书ch02 evaluate_cws.py 文件 报错，如果是 你看下这个文件的目录，这个文件的根目录的名称 和你 site-packages下的包得名称是一致的，要改动名字的是你 这个 evaluate_cws.py文件上级的目录名称 不是更改你site-packages下的文件名称

**Comment by cllx** [comment]
好的 谢谢

**Comment by hankcs** [comment]
运行这三句话可以自动修复。

https://github.com/hankcs/pyhanlp/blob/4e0193807d040e905c9ddab9b859df4829634140/tests/demos/demo_download_again.py#L4-L8

**Comment by cllx** [comment]
好的 谢谢@hankcs
