### ISSUE TITLE
HanLP加载自定义字典的Bug。

### ISSUE THREAD

**Issue by HongZhaoHua** [hankcs/HanLP#1318]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [ ] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.7.5
我使用的版本是：1.7.5

### 步骤

1. 在存在hanlp.properties配置文件的情况下,设置多个字典并用;分割.
例如:CustomDictionaryPath=a.txt;b.txt;c.txt;
    hanlp会启动绝对路径搜索的方式加载自定义字典.
2. 由于hanlp会尝试从第一个mainPath(寻找a.txt.bin),并在加载成功的情况下,立刻返回.
    导致b.txt;c.txt不会被加载.

### 触发代码

```
在CustomDictionary::public static boolean loadMainDictionary(String mainPath, String path[], DoubleArrayTrie<CoreDictionary.Attribute> dat, boolean isCache)方法中.

logger.info("自定义词典开始加载:" + mainPath);
        if (loadDat(mainPath, dat)) return true;
```

**Comment by hankcs** [comment]
https://github.com/hankcs/HanLP/issues/789

**Comment by HongZhaoHua** [comment]
已经有其它人报告此Bug了?

**Comment by HongZhaoHua** [comment]
明白了，以第一个字典名称作为所有字典的bin。
