### ISSUE TITLE
安装过程出现的问题，以及最后安装成功的版本号，汇报一下

### ISSUE THREAD

**Issue by chenwenhang** [hankcs/HanLP#1319]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：pyhanlp 0.1.50
我使用的版本是：pyhanlp 0.1.47

## 我的问题

环境参数：
* win10
* jdk 1.8
* python 3.7

失败安装过程：
* 第一次：直接`pip install pyhanlp` （版本0.1.50），自动安装依赖jpype1（版本0.7.0），下载data文件执行`hanlp`报错：`startJVM() got an unexpected keyword argument 'convertStrings'`
* 第二次：`pip install pyhanlp=0.1.47`，`pip install jpype1=0.6.2`，执行报错：`AttributeError: module '_jpype' has no attribute 'setResource'`

成功过程：
* `pip install pyhanlp=0.1.47`
* `pip install jpype1=0.6.3`

**Comment by hankcs** [comment]
Linux一切正常，Windows待查。

```
pip3 install pyhanlp
Successfully installed jpype1-0.7.0 pyhanlp-0.1.50
hanlp segment <<< 商品和服务
商品/n 和/cc 服务/vn
```

**Comment by hankcs** [comment]
Windows查无此问题。
<img width="711" alt="hankcs com 2019-11-06 at 8 55 17 PM" src="https://user-images.githubusercontent.com/5326890/68353513-d59c9980-00d7-11ea-9233-6ab927dc180e.png">
环境是conda。

**Comment by chenwenhang** [comment]
不知道为啥我这是报错的，那可能是我这环境有问题
