### ISSUE TITLE
报错java.lang.NoClassDefFoundError: com/hankcs/hanlp/HanLP

### ISSUE THREAD

**Issue by cllx** [hankcs/HanLP#1321]
如题，我安装了pyhanlp后，运行HanLP = JClass('com.hankcs.hanlp.HanLP')就报题目的错误，请问这个错是什么原因，要怎么解决呢？小白一枚，请大家棒棒忙解答一下

**Comment by hankcs** [comment]
https://github.com/hankcs/HanLP/issues/1317
