### ISSUE TITLE
所有的分词器运行一段时间后，将数字识别成nz

### ISSUE THREAD

**Issue by hqmshhxx** [hankcs/HanLP#1323]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：portable-1.7.5
我使用的版本是：portable-1.7.5

## 我的问题

PerceptronLexicalAnalyzer   ViterbiSegment 等分词器在运行一段时间后，将数字识别成nz

### 步骤

1. 首先 以ViterbiSegment分词器为例

### 触发代码

```
    private static Segment segment = HanLP.newSegment().enableOffset(true);

    public List<EntityResult> resolve(String sentence) {
        List<EntityResult> entities = new ArrayList<>();
        List<Term> termList = segment.seg(sentence);
        log.info("QuantityResolver termList={}",termList);
    }
```
### 期望输出

```
termList=[1/m, 加/v, 2/m]
```

### 实际输出

```
termList=[1/nz, 加/v, 2/nz]
```

## 其他信息

此resolve(String sentence)接口1s执行1-5次，1个小时后就会识别错误

**Comment by hankcs** [comment]
Hi，我很重视你的问题。但我并没有发现类似问题，http://hanlp.com/ 已经连续运行了 125 days 也没有出现类似问题。Viterbi中数词是通过如下方法确定词性的，这个方法是绝对线程安全的。

https://github.com/hankcs/HanLP/blob/8b5d79df10e93a8f2b359108814a47f544d96adf/src/main/java/com/hankcs/hanlp/seg/NShort/Path/AtomNode.java#L45-L80

**Comment by hqmshhxx** [comment]
查了一下，发现从数据库中读取了用户自定义的词加入到了CustomDictionary，里面有一定量的数字，直接用CustomDictionary.add()进行了加载导致了数字的词性为Nature.nz。正在验证是否是这个原因导致的

**Comment by hqmshhxx** [comment]
确实这个原因导致的。
