### ISSUE TITLE
分句问题

### ISSUE THREAD

**Issue by quicksandznzn** [hankcs/HanLP#1326]
想要把句子
 ”然后跟您讲解一下车况和当地的优惠政策先生您看尾号5920是您本人的手机号吧“
分成下面俩段句子有什么办法吗
 然后跟您讲解一下车况和当地的优惠政策
 先生您看尾号5920是您本人的手机号吧

**Comment by brotherb** [comment]
应该没办法吧

**Comment by quicksandznzn** [comment]
> 应该没办法吧
想从依存句发分析的角度入手靠谱嘛

**Comment by quicksandznzn** [comment]
想从依存句发分析的角度入手靠谱嘛 @brotherb

**Comment by hankcs** [comment]
邀请你在 https://bbs.hankcs.com/ 交流非bug问题。这个项目的watcher有一千多人，并非每个人都对一般问题感兴趣。
