### ISSUE TITLE
Linux环境引用data数据包时报错

### ISSUE THREAD

**Issue by cjm327** [hankcs/HanLP#1327]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕

## 版本号

当前最新版本号是：portable-1.7.5
我使用的版本是：portable-1.7.5

## 我的问题

在linux部署，在引用data数据包的时候发生下载错误，遇到两个问题：
1、我把data数据包是放置于/eyas/templete/ 目录下（/eyas为硬盘分区），而且hanlp.properties中的设置是 root=/eyas/templete/，但是却引用不到数据包。
2、基于问题1，程序触发重新下载操作，却下载不了数据包，报错内容：java.io.IOException: No file to download. Server replied HTTP code: 302

<i>本人是小白，如果问的问题太low，请见谅、稍微耐心指导下哈。谢谢！</i>

**Comment by hankcs** [comment]
除了测试代码外，HanLP不会自动下载data。你能解释一下是谁发起了下载吗？

**Comment by cjm327** [comment]
我是用测试代码改造的 o((⊙﹏⊙))o

**Comment by hankcs** [comment]
你需要补丁 https://github.com/hankcs/HanLP/commit/2874b1416ed2d17e792480ca42d322f1db7c4815

**Comment by cjm327** [comment]
好的，明白了，谢谢老哥指导！感谢谢谢谢谢谢！
