### ISSUE TITLE
用相同的词库，比对了1.2.6和2.8，发现6效果好

### ISSUE THREAD

**Issue by sheenshine** [hankcs/HanLP#133]
比如2.8分出4个何文，2.6分出何文全，j何文桂，何文玲，何文莲

**Comment by hankcs** [comment]
0. 因为127版本增加了用户词典的优先级
0. 不使用人名词典.txt就行了：CustomDictionaryPath=data/dictionary/custom/CustomDictionary.txt; 现代汉语补充词库.txt; 全国地名大全.txt ns; 机构名词典.txt; 上海地名.txt ns;data/dictionary/person/nrf.txt nrf

**Comment by sheenshine** [comment]
了解，谢谢！
