### ISSUE TITLE
您好，我想请教一下关于从网络上公开的98年人民日报语料库到HanLP自带词典的处理过程

### ISSUE THREAD

**Issue by yuzhengyao** [hankcs/HanLP#1337]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.7.5
我使用的版本是：1.7.5

## 我的问题
1、在网络上有公开的98年人民日报语料库，有已经标注的和未标注的，我查看之前的lssues,有人说过网上98年的人民日报语料是由北大人工联合标注的，请问：最原始的新闻语料是文章，整个标注过程是怎样的？将所有的新闻文章收集起来，然后进行人工分词并且标注词性，然后按照规范整理后发布，就变成我们看到的网上的带有标注的公开语料库了？
2、如果第一个问题是人工分词并标注的，那现在我们已经有了被人工分词并标注好了的新的98年人民日报语料库（**下面第一张图**）
![image](https://user-images.githubusercontent.com/43544445/70107064-71420b00-1680-11ea-95f6-51168be49915.png)
经过怎样的处理得到HanLP中所用到的txt词典，例如mini.txt（**下面第二张图**）
![image](https://user-images.githubusercontent.com/43544445/70107614-f4b02c00-1681-11ea-80f9-c06f8627534f.png)
就是由被人工分词并标注好了的新的98年人民日报语料库  到  HanLP中所用到的txt词典，例如mini.txt或HanLP中其他的词典     之间经过了怎样的处理过程，是脚本程序吗？如果是脚本程序的话，在HanLP包中有源码吗？若没有的话可以给我讲一下思路吗？ HanLP中所用到的txt词典中的词频是怎样来的，脚本程序在最开始怎样统计每个单词的词频的？在最最开始就是用TF-IDF算法进行统计吗？
换句话说，我想问，从最原始的没有经过任何加工的生语料（也就是原文章）经过怎样的处理才可以变成可以被HanLP使用的词典文件，或者我想要自己制作专用语料库，从最开始的专用领域文章文本经过人工分词标注后**再**经过怎**样的处理**可以得到能够被HanLP使用的词典文件，并且可以将我自己的专用语料库对应的词典替换掉HanLP自带词典。
请求大神解答！十分感谢

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

```
    public void testIssue1234() throws Exception
    {
        CustomDictionary.add("用户词语");
        System.out.println(StandardTokenizer.segment("触发问题的句子"));
    }
```
### 期望输出

```
期望输出
```

### 实际输出

```
实际输出
```

**Comment by hankcs** [comment]
你的问题三言两语说不清楚，你可以看[《自然语言处理入门》](http://nlp.hankcs.com/book.php)或随书源码。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
