### ISSUE TITLE
添加分析字典时，词频输入项应如何理解并实际应用

### ISSUE THREAD

**Issue by sxgkwei** [hankcs/HanLP#1341]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕

## 版本号

当前最新版本号是：1.7.5
我使用的版本是：1.7.5

## 我的问题

首页演示代码：
8. 用户自定义词典 
中的演示语句：
  System.out.println(CustomDictionary.add("单身狗", "nz 1024 n 1"));
其中 1024 这个词频，应该如何理解及使用？

假设实际中有大文本段 txt，因为业务领域问题，我目前有一个专有名词 word，需要添加入动态字典。那我当然可以人为的定义一个它的词性，但词频我如何能知道呢？而这个字典，我是拿去分析txt，包括以后可能出现的 txt 的。如果按照词频的汉语意思，就是词出现的次数。实际中我连文本都在业务系统一直动态增加着，我显然不可能知道它会出现多少次吧。

故而，有如上问题。

## 其他信息

不知道是否能联系到 “蝴蝶效应” 站点的管理员，吐槽一下那个站点。
1，不明原因的个人无法注册，提示 ：ip地址已经注册，联系管理员。中国有独立IP的个人有几个啊，我们公司对外都没有独立IP吧，这个判定限制，作为个人，我都不知道怎样处理。是联系bbs管理员呢，还是联系持有这个IP的管理员，还是我们这栋大厦的物业团队。
2，github 似乎可以授权登录，但也很奇怪，我已经弹出窗口授权成功了，但没有直接登录上去，弹出一个登录/注册的层，我也不知道点哪个，反正点登录，登录不了，点注册，又回到吐槽1描述的情况。哎，难办。

**Comment by hankcs** [comment]
1. 词频是在某个语料库中unigram的频次，越高越容易分出来，但不是绝对的，会受距离公式中的其他因子影响。你可以看代码了解具体是怎么算的，或者看[《自然语言处理入门》](http://nlp.hankcs.com/book.php)。
1. IP问题说明“蝴蝶效应”很受欢迎。后台限制每个IP只能注册若干个新账号，你们大厦有很多人注册了。这个限制放宽了一些，你可以再试试。
1. GitHub授权测试正常。

![2019-12-05_22-10-32](https://user-images.githubusercontent.com/5326890/70292597-9d5aaa80-17ac-11ea-8e3d-8a59ca2547ee.png)

**Comment by sxgkwei** [comment]
> 1. 词频是在某个语料库中unigram的频次，越高越容易分出来，但不是绝对的，会受距离公式中的其他因子影响。你可以看代码了解具体是怎么算的，或者看[《自然语言处理入门》](http://nlp.hankcs.com/book.php)。
> 2. IP问题说明“蝴蝶效应”很受欢迎。后台限制每个IP只能注册若干个新账号，你们大厦有很多人注册了。这个限制放宽了一些，你可以再试试。
> 3. GitHub授权测试正常。
> 
> ![2019-12-05_22-10-32](https://user-images.githubusercontent.com/5326890/70292597-9d5aaa80-17ac-11ea-8e3d-8a59ca2547ee.png)

谢谢回答。
1，我还是无法理解词频的使用场景——即使我知道它不是绝对被分出来。通过你的解释，还是没有看出在一个动态始终增加的语料库中，怎样给出一个合理的词频数字。
2，“蝴蝶效应”已经正常登陆了，看来之前连github也不能登陆，还是IP限制总数导致的不能注册问题引发的。
3，“蝴蝶效应”刚登陆成功后，有个页面bug：右上角通知一个机器人欢迎消息，页面被强制只能点这个消息，点了之后，消息出现，页面遮罩层依旧存在，不能进行其它操作。必须刷新一下网页，才能正常。

**Comment by hankcs** [comment]
> > 1. 词频是在某个语料库中unigram的频次，越高越容易分出来，但不是绝对的，会受距离公式中的其他因子影响。你可以看代码了解具体是怎么算的，或者看[《自然语言处理入门》](http://nlp.hankcs.com/book.php)。
> > 2. IP问题说明“蝴蝶效应”很受欢迎。后台限制每个IP只能注册若干个新账号，你们大厦有很多人注册了。这个限制放宽了一些，你可以再试试。
> > 3. GitHub授权测试正常。
> > 
> > ![2019-12-05_22-10-32](https://user-images.githubusercontent.com/5326890/70292597-9d5aaa80-17ac-11ea-8e3d-8a59ca2547ee.png)
> 
> 谢谢回答。
> 1，我还是无法理解词频的使用场景——即使我知道它不是绝对被分出来。通过你的解释，还是没有看出在一个动态始终增加的语料库中，怎样给出一个合理的词频数字。
> 2，“蝴蝶效应”已经正常登陆了，看来之前连github也不能登陆，还是IP限制总数导致的不能注册问题引发的。
> 3，“蝴蝶效应”刚登陆成功后，有个页面bug：右上角通知一个机器人欢迎消息，页面被强制只能点这个消息，点了之后，消息出现，页面遮罩层依旧存在，不能进行其它操作。必须刷新一下网页，才能正常。

语料是语言中采样的一个子空间，应当随语言变化而变化，亦即重新训练模型。
网站应该是有个js没加载成功。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
