### ISSUE TITLE
import pyhanlp时报错（ImportError: numpy.core.multiarray failed to import）

### ISSUE THREAD

**Issue by zhengtong0807** [hankcs/HanLP#1343]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕

## 版本号

当前最新版本号是：0.1.57
我使用的版本是：0.1.57

## 我的问题

在根据书上步骤安装好之后，import pyhanlp时报错
C:\Users\ZzT>python
Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyhanlp
D:\Anaconda3\lib\site-packages\numpy\core\__init__.py:29: UserWarning: loaded more than 1 DLL from .libs:
D:\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.IPBC74C7KURV7CB2PKT5Z5FNR3SIBV4J.gfortran-win_amd64.dll
D:\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.TXA6YQSD3GCQQC22GEQ54J2UDCXDXHWN.gfortran-win_amd64.dll
  stacklevel=1)
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Anaconda3\lib\site-packages\pyhanlp\__init__.py", line 12, in <module>
    from jpype import JClass, startJVM, getDefaultJVMPath, isThreadAttachedToJVM, attachThreadToJVM, java, \
  File "D:\Anaconda3\lib\site-packages\jpype\__init__.py", line 17, in <module>
    from ._jpackage import *
  File "D:\Anaconda3\lib\site-packages\jpype\_jpackage.py", line 19, in <module>
    import _jpype
ImportError: numpy.core.multiarray failed to import

经查询百度，初步判定是numpy版本不匹配造成的，但是尝试了numpy1.16.0,1.16.5,1.17.4 之后，均没有解决，求晗哥解答，非常感谢

**Comment by hankcs** [comment]
你64位的系统为什么要装32位的conda呢？

**Comment by zhengtong0807** [comment]
这个应该不影响吧，我一直用的好好的，这个报错只是numpy有问题，想知道有没有具体解决方式😄😄😄



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: hankcs <notifications@github.com&gt;
发送时间: 2019年12月6日 23:13
收件人: hankcs/HanLP <HanLP@noreply.github.com&gt;
抄送: 张政统 <946196891@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[hankcs/HanLP] import pyhanlp时报错（ImportError: numpy.core.multiarray failed to import） (#1343)




你64位的系统为什么要装32位的conda呢？

**Comment by hankcs** [comment]
> 这个应该不影响吧，我一直用的好好的，这个报错只是numpy有问题，想知道有没有具体解决方式😄😄😄 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: hankcs <notifications@github.com&gt; 发送时间: 2019年12月6日 23:13 收件人: hankcs/HanLP <HanLP@noreply.github.com&gt; 抄送: 张政统 <946196891@qq.com&gt;, Author <author@noreply.github.com&gt; 主题: 回复：[hankcs/HanLP] import pyhanlp时报错（ImportError: numpy.core.multiarray failed to import） (#1343) 你64位的系统为什么要装32位的conda呢？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

有影响。

**Comment by zhengtong0807** [comment]
好的，明天试一试，谢谢晗哥



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: hankcs <notifications@github.com&gt;
发送时间: 2019年12月7日 00:03
收件人: hankcs/HanLP <HanLP@noreply.github.com&gt;
抄送: 张政统 <946196891@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[hankcs/HanLP] import pyhanlp时报错（ImportError: numpy.core.multiarray failed to import） (#1343)



 
这个应该不影响吧，我一直用的好好的，这个报错只是numpy有问题，想知道有没有具体解决方式😄😄😄 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: hankcs <notifications@github.com&gt; 发送时间: 2019年12月6日 23:13 收件人: hankcs/HanLP <HanLP@noreply.github.com&gt; 抄送: 张政统 <946196891@qq.com&gt;, Author <author@noreply.github.com&gt; 主题: 回复：[hankcs/HanLP] import pyhanlp时报错（ImportError: numpy.core.multiarray failed to import） (#1343) 你64位的系统为什么要装32位的conda呢？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
有影响。

**Comment by zhengtong0807** [comment]
换成了64位，还是一样的错

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: hankcs <notifications@github.com&gt;
发送时间: 2019年12月7日 00:03
收件人: hankcs/HanLP <HanLP@noreply.github.com&gt;
抄送: 张政统 <946196891@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[hankcs/HanLP] import pyhanlp时报错（ImportError: numpy.core.multiarray failed to import） (#1343)



 
这个应该不影响吧，我一直用的好好的，这个报错只是numpy有问题，想知道有没有具体解决方式😄😄😄 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: hankcs <notifications@github.com&gt; 发送时间: 2019年12月6日 23:13 收件人: hankcs/HanLP <HanLP@noreply.github.com&gt; 抄送: 张政统 <946196891@qq.com&gt;, Author <author@noreply.github.com&gt; 主题: 回复：[hankcs/HanLP] import pyhanlp时报错（ImportError: numpy.core.multiarray failed to import） (#1343) 你64位的系统为什么要装32位的conda呢？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
有影响。

**Comment by hankcs** [comment]
你的日志说你有多个gfortran-win_amd64.dll，可能冲突。

**Comment by zhengtong0807** [comment]
确实，是因为安装了多个numpy，有可能是安装新的时候旧的没有卸载干净，这个问题以后的同学们可能也会遇到，，贴出来该大家参考，感谢博主的启发，很受用

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。

**Comment by w4sevens** [comment]
我也遇到类似的问题，但是感觉又跟大家不一样啊。。。。
------------------------PyInstaller 信息的一部分-----------
22034 INFO: Looking for dynamic libraries
22615 WARNING: lib not found: libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll dependency of c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\numpy\core\_multiarray_umath.cp38-win_amd64.pyd
22770 WARNING: lib not found: libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll dependency of c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\numpy\linalg\_umath_linalg.cp38-win_amd64.pyd
22783 WARNING: lib not found: libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll dependency of c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\numpy\linalg\lapack_lite.cp38-win_amd64.pyd
23080 INFO: Looking for eggs
------------------------------------
这个是啥意思呢
