### ISSUE TITLE
进行分词测试，怎么屏蔽自带的词典的影响

### ISSUE THREAD

**Issue by huchhong** [hankcs/HanLP#135]
我想要用SIGHAN Bakeoff 2005测试不同的分词算法的效果。这里要屏蔽Hanlp自带的词典的影响，我看data里有好多词典，要怎么做才行。

目前我的想法是用自定义的词典替换掉CoreNatureDictionary.txt，但是不知道其他词典对分词有什么影响？

**Comment by hankcs** [comment]
enableCustomDictionary(false)
