### ISSUE TITLE
对于自训练模型CRFNERecognizer的recognize 方法不能识别出正确的nertags，但是PerceptronNERecognizer却可以

### ISSUE THREAD

**Issue by zche** [hankcs/HanLP#1350]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕

## 版本号

当前最新版本号是：1.7.5
我使用的版本是：1.7.5

## 我的问题

首先非常感谢您这个项目，我在用CRF的方式训练模型的时候，当调用CRFNERecognizer的recognize 方法不能识别出复合词正确的nertags，识别出来的都是O，实际上我已经按照人民日报的格式用中括号标记出来了，可当我用感知机的方式，即PerceptronNERecognizer 这个对象  是可以识别出我的复合词的正确nertags的，稍后我把CRF的代码列出来，请您看下是否有问题。

### 步骤

1. 首先 看下我的标记语料 如下：
[潘婷/nr 氨基酸/n 洗/v 护/v 套装/n 乳液/n 修护/v 洗发/v 水/n]/baj 500/m ml/q 搭配/v [3/m 分钟/q 奇迹/n 护发素/nz]/baj 70/m ml 新旧/q 包装/n 随机/d 发货/v ，/w 价格/n ￥/v 59.90/m ，/w 适合/v 头皮/n ：/w 干性/n ，/w 功效/n ：/w 水/n 润/v 。/w
这是训练词性模型和ner模型的语料，分词模型的语料 是去掉 词性标记和中括号之后的 单词
2. 然后 用hanlp提供（CRFSegmenter，CRFPOSTagger，CRFNERecognizer三个接口对象）的CRF接口分别训练分词模型，词性模型以及NER模型
3. 接着 用CRFNERecognizer 的recognize  方法 期望获取每个单词对应的nertag

### 触发代码

```
    str1 = '潘婷氨基酸洗护套装乳液修护洗发水500ml搭配3分钟奇迹护发素70ml 新旧包装随机发货，价格￥59.90，适合头皮：干性，功效：水润。'
    seg = CRFSegmenter(cws_path)
    wordList = seg.segment(str1)
    tagger = CRFPOSTagger(pos_path)
    pos_tags = tagger.tag(wordList)
    customNerTags = ['baj']
    ner = CRFNERecognizer(train_model+".txt",customNerTags)
    arrNer = ner.recognize(list(wordList),list(pos_tags))
    ner_tags = list([p for p in list(arrNer)])
    print(ner_tags)
```
### 期望输出

```
['B-baj', 'M-baj', 'M-baj', 'M-baj', 'M-baj', 'M-baj', 'M-baj', 'M-baj', 'E-baj', 'O', 'O', 'O', 'B-baj', 'M-baj', 'M-baj', 'E-baj', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O']
```

### 实际输出

```
['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O']
```

## 其他信息

以上期望输出的结果是我用感知机的相关对象（PerceptronSegmenter，PerceptronPOSTagger，PerceptronNERecognizer）输出的

**Comment by hankcs** [comment]
CRF的特征模板要复杂一些：

https://github.com/hankcs/HanLP/blob/7761ef5f9ecef82213a48ae055fdcfa500a62fcc/src/main/java/com/hankcs/hanlp/model/crf/CRFNERecognizer.java#L165-L170

如果你的语料库很小，有可能过拟合了。

**Comment by zche** [comment]
> CRF的特征模板要复杂一些：
> 
> https://github.com/hankcs/HanLP/blob/7761ef5f9ecef82213a48ae055fdcfa500a62fcc/src/main/java/com/hankcs/hanlp/model/crf/CRFNERecognizer.java#L165-L170
> 
> 如果你的语料库很小，有可能过拟合了。

感谢回答，过些时间我在多准备些语料库试下

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
