### ISSUE TITLE
test中demo的例子在pycharm报错 

### ISSUE THREAD

**Issue by sjtuxiaoming** [hankcs/HanLP#1357]
我使用的版本是：hanlp-1.7.5.jar   基于python3.7的anaconda
12月17日 通过pip install pyhanlp包
如截图所示，在copy学习 pyhanlp demo 代码上，pycharm报错
![image](https://user-images.githubusercontent.com/17291290/70996821-8f8f1880-210e-11ea-8cc3-bd014d172aad.png)

运行的是demo中的例行代码https://github.com/hankcs/pyhanlp/blob/master/tests/demos/demo_sentiment_analysis.py
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：hanlp-1.7.5.jar
我使用的版本是：hanlp-1.7.5.jar  

## 我的问题
如截图所示，在copy学习 pyhanlp demo 代码上，pycharm报错

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

```
    public void testIssue1234() throws Exception
    {
        CustomDictionary.add("用户词语");
        System.out.println(StandardTokenizer.segment("触发问题的句子"));
    }
```
### 期望输出

```
期望输出
```

### 实际输出

```
实际输出
```

**Comment by hankcs** [comment]
请clone整个project而不仅仅是demo文件夹，这些demo依赖一个工具类：

https://github.com/hankcs/pyhanlp/blob/master/tests/test_utility.py#L21

**Comment by sjtuxiaoming** [comment]
> 请clone整个project而不仅仅是demo文件夹，这些demo依赖一个工具类：
> 
> https://github.com/hankcs/pyhanlp/blob/master/tests/test_utility.py#L21

你好，我是使用pip install pyhanlp, 然后直接pycharm中新建项目用来测试学习各项功能。
然后在涉及到引用：from tests.test_utility import ensure_data 时，出现pycharm报错，如文中截图。
按道理来说，既然已经安装好pyhanlp包，是不该出现这情况的。
不过，我现在为了继续学习，是手动把ensure_data这个函数，copy过来了。 python版本3.7。

**Comment by hankcs** [comment]
test中的代码不会发布到pip中。

**Comment by sjtuxiaoming** [comment]
> test中的代码不会发布到pip中。

OK👌那就搞清楚原因了，感谢第一时间解答！ 买了你的书在看，nlp讲得很好，也学到很多工程思维， 感谢🙏

**Comment by annie007** [comment]
我也遇到这个问题：所有的引用tests下的包都是找不到 类似于“ModuleNotFoundError: No module named 'tests.test_utility' “ 然后把pyhanlp-master 添加到pycharm的搜索路径里面所有的文件都会报：urllib.error.HTTPError: HTTP Error 403: Forbidden 。
我是整个pyhanlpdown下来的 期待您的回复
