### ISSUE TITLE
pyhanlp/tests/book/ch02/dat.py的问题

### ISSUE THREAD

**Issue by xieyu567** [hankcs/HanLP#1358]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.7.5
我使用的版本是：1.7.5

python: 3.7.3
jpype: 0.7.0
运行pyhanlp/tests/book/ch02/dat.py出现错误。

![image](https://user-images.githubusercontent.com/22760903/71138277-e8150180-2245-11ea-9ac3-9f5dda41fc87.png)

**Comment by hankcs** [comment]
试试旧版如何：https://github.com/hankcs/pyhanlp/commit/49202d2210d97b075e35c90aa20b9cbe3b31f413

**Comment by xieyu567** [comment]
![image](https://user-images.githubusercontent.com/22760903/71156291-afdbe600-227a-11ea-86a4-3b55f3ff4704.png)
仍然还是报错

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。
