### ISSUE TITLE
HanLP词频

### ISSUE THREAD

**Issue by gyz-GitHub** [hankcs/HanLP#136]
HanLP词频怎么统计，rank没有加入词频权重。如何实现 ？

**Comment by intohole** [comment]
第一，textrank 是支持权重的 ；但是怎么按照你这个词频权重是件怎么算权重？ 一般停用词词频很高

**Comment by hankcs** [comment]
为什么算法一定要用词频？

**Comment by gyz-GitHub** [comment]
1.停用词及停用词的词频忽略。
2.算法可以不用词频。

问题:
1.分词后如何快速得到词频个数，不使用迭代，性能是非线性的。
2.如何在rank的关键字统计的时候，附带加入这个关键字的词频功能。

**Comment by hankcs** [comment]
0. 这是你自己的业务逻辑，你需要自己hack segSentence方法
0. 同上
