### ISSUE TITLE
加载CoreDictionaryPath显示SSL和URL证书验证失败

### ISSUE THREAD

**Issue by TibbersBao** [hankcs/HanLP#1361]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕

## 版本号
当前最新版本号是：1.7.5
我使用的版本是：1.7.5

## 我的问题
使用最新版书籍P35页代码加载HanLP的核心词典库，出现SSL，及URL证书验证失败。代码来自ch02的utitil.py.
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)>

试着使用全局不检测SSL及URl未能解决

## 复现问题
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
添加代码以无视SSL证书检测，无效

### 代码复现

```
  from pyhanlp import *
# 全局取消证书验证

import ssl
ssl._create_default_https_context = ssl._create_unverified_context



def load_dictionary():
    '''
    加载HanLp中的mini词库
    :return: 一个set形式的词库
    '''
    IOUtil=JClass('com.hankcs.hanlp.corpus.io.IOUtil')
    path = HanLP.Config.CoreDictionaryPath.replace('.txt', '.mini.txt')
    dic = IOUtil.loadDictionary([path])
    return set(dic.keySet())

if __name__ == '__main__':
    dic = load_dictionary()
    print(len(dic))
    print(list(dic)[0])
```
### 期望输出

返回一个set的形式的词库

## 其他信息

MAC Python3.7, Pycharm

**Comment by hankcs** [comment]
国内网络特色。

https://github.com/hankcs/pyhanlp/wiki/%E6%89%8B%E5%8A%A8%E9%85%8D%E7%BD%AE

**Comment by TibbersBao** [comment]
<img width="610" alt="截屏2019-12-2514 01 46" src="https://user-images.githubusercontent.com/44196988/71434373-26fff700-271f-11ea-89d6-aefdb202842c.png">
我尝试这手动配置，并且严格按照配置页目录所示，并且里面的data 以及jar包文件都在，然后hanlp.properties文件内的root的目录也是data的目录。但是在pycharm加载的时候还是不行,显示的是相同的错误，但是我在terminate下运行hanlp segement是可以运行的，可以做到分词。为什么在pycharm下就一直出这个url,ssL 的错，搞不懂，感觉不像是配置问题，因为按照要求都配置成功了。

**Comment by hankcs** [comment]
你的pycharm用的可能是另一个python。

**Comment by TibbersBao** [comment]
我使用jupyter notebook成功了，但是用pycharm失败了。然后我在pycharm的解释器里将解释器改成了anaconda3的解释器。再次运行就成功了。可能是系统默认了使用anaconda3的python3.7. 就pip安装的都已经l默认到了ananconda下面。所以导致之前安装的python3无法调用到。谢谢。问题已经解决，是pycharm使用的python不一致导致的

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。值此2020新年之际，我很高兴地宣布，HanLP2.0发布了。HanLP2.0
