### ISSUE TITLE
hanlp elasticsearch插件

### ISSUE THREAD

**Issue by avazhouhong** [hankcs/HanLP#1362]
希望可以开源一个ealsticsearch插件，elasticsearch的分词插件ik,无法支持分布式的动态修改词库，希望可以有一套基于hanlp的elasticsearch插件，并且支持分布式。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。值此2020新年之际，我很高兴地宣布，HanLP2.0发布了。HanLP2.0
