### ISSUE TITLE
为什么在机构名识别代码中对nis词性hard code了K, 1000和D, 1000

### ISSUE THREAD

**Issue by xunyuw** [hankcs/HanLP#137]
为什么在机构名识别代码中对nis词性hard code了K, 1000和D, 1000，
导致分词有问题
 "2007年1月9日，阿里巴巴集团在上海宣布旗下公司阿里软件正式成立。",
N-最短分词：[2007年/t, 1月/t, 9日/t, ，/w, 阿里巴巴集团/nt, 在/p, 上海/ns, 宣布/v, 旗下/d, 公司阿里软件/nt, 正式成立/v, 。/w]
最短路分词：[2007/m, 年/qt, 1/m, 月/n, 9/m, 日/b, ，/w, 阿里巴巴集团/nt, 在/p, 上海/ns, 宣布/v, 旗下/d, 公司阿里软件/nt, 正式成立/v, 。/w]

**Comment by hankcs** [comment]
感谢反馈。

0. 就像注释中说的一样，想构成更长的机构名，比如某某公司某某分公司
0. 问题应该是DGD这个模式串带来的。

**Comment by hankcs** [comment]
[阿里巴巴集团/nt, 在/p, 上海/ns, 宣布/v, 旗下/d, 公司/nis, 阿里软件/nt, 正式/ad, 成立/vi]
