### ISSUE TITLE
pyhanlp配置问题：HANLP_JAR_PATH已配置，报错不是jar文件，已使用 '/'

### ISSUE THREAD

**Issue by InfiYond** [hankcs/HanLP#1371]
请确认下列注意事项：

我已仔细阅读下列文档，都没有找到答案：
首页文档
wiki
常见问题
我已经通过Google和issue区检索功能搜索了我的问题，也没有找到答案。
我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
 我在此括号内输入x打钩，代表上述事项确认完毕
版本号
当前最新版本号是：1.7.6
我使用的版本是：1.7.6

我的问题

HANLP_JAR_PATH和HANLP_ROOT_PATH已配置为static
运行from pyhanlp import *，报错ValueError: 配置错误: HANLP_JAR_PATH=D:\anaconda\Lib\site-packages\pyhanlp\static 不是jar文件
我已经将环境变量HANLP_JAR_PATH和HANLP_ROOT_PATH的路径改为D:/anaconda/Lib/site-packages/pyhanlp/static，properties文件的root路径也修改了

**Comment by hankcs** [comment]
```

$cd lib/python3.6/site-packages/pyhanlp/static/
$ ls
data             hanlp.properties     index.html   __pycache__
hanlp-1.7.6.jar  hanlp.properties.in  __init__.py  README.url
$ rm -f *.jar *.properties
$ hanlp
下载 http://hanlp.com/static/release/hanlp-1.7.6-release.zip 到 lib/python3.6/site-packages/pyhanlp/static/hanlp-1.7.6-release.zip
100.00%, 1 MB, 407 KB/s, 还有 0 分  0 秒   
usage: hanlp [-h] [-v] {segment,parse,serve,update} ...

HanLP: Han Language Processing v1.7.6

```
