### ISSUE TITLE
pyhanlp和hanlp

### ISSUE THREAD

**Issue by OKtang** [hankcs/HanLP#1372]
你好，
请问pyhanlp和hanlp是什么关系呢？然后pyhanlp的依存句法分析，支持输入分好词的句子嘛？谢谢回复 ~
新年快乐

**Comment by hankcs** [comment]
pyhanlp=1.x，是Java版hanlp1.x的wrapper，传统机器学习路线。
hanlp现在发布了2.0，基于深度学习，与pyhanlp再无关系。
支持。
