### ISSUE TITLE
java 版不同 module 下使用不同的配置

### ISSUE THREAD

**Issue by luobotaxinghu** [hankcs/HanLP#1374]
作者你好， 我在两个不同的 module 下配置不同的 hanlp.properties ， 在第三个 module  下调用两个 module ， 发现用的都是同一份配置， 有什么办法让 不同的 module 用不同的   hanlp.properties 配置吗？ 谢谢

**Comment by hankcs** [comment]
https://github.com/hankcs/HanLP/issues/1339
