### ISSUE TITLE
这个版本没有zip包啊，程序里下载报错

### ISSUE THREAD

**Issue by chelseXie** [hankcs/HanLP#1375]
![image](https://user-images.githubusercontent.com/11661959/71723130-71dbe600-2e66-11ea-9a8d-a34ae0beb1e6.png)

**Comment by hankcs** [comment]
报什么错？

**Comment by chelseXie** [comment]
--2020-01-04 11:27:38--  https://github.com/hankcs/HanLP/releases/download/v2.0.0-alpha.0/hanlp-2.0.0-alpha.0-release.zip
Resolving github.com (github.com)... 13.250.177.223
Connecting to github.com (github.com)|13.250.177.223|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-01-04 11:27:39 ERROR 404: Not Found.


上面是错误，应该是pyhanlp包要下载最新的语料包，没有找到就报错

**Comment by chelseXie** [comment]
> 报什么错？

--2020-01-04 11:27:38-- https://github.com/hankcs/HanLP/releases/download/v2.0.0-alpha.0/hanlp-2.0.0-alpha.0-release.zip
Resolving github.com (github.com)... 13.250.177.223
Connecting to github.com (github.com)|13.250.177.223|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-01-04 11:27:39 ERROR 404: Not Found.

上面是错误，应该是pyhanlp包要下载最新的语料包，没有找到就报错

**Comment by hankcs** [comment]
```
pip3 install -U pyhanlp
hanlp update
```
pyhanlp跟hanlp2.0再无关系。
