### ISSUE TITLE
加载MSRA NER 预训练模型的时候报错

### ISSUE THREAD

**Issue by yunyu-Mr** [hankcs/HanLP#1377]
环境 Ubuntu 18.04, Python 3.6
```
In [2]: recognizer = hanlp.load(hanlp.pretrained.ner.MSRA_NER_BERT_BASE_CN)
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-2-736be980464f> in <module>
----> 1 recognizer = hanlp.load(hanlp.pretrained.ner.MSRA_NER_BERT_BASE_CN)

~/.local/lib/python3.6/site-packages/hanlp/__init__.py in load(save_dir, meta_filename, **kwargs)
     40     save_dir = hanlp.pretrained.ALL.get(save_dir, save_dir)
     41     from hanlp.utils.component_util import load_from_meta_file
---> 42     return load_from_meta_file(save_dir, meta_filename, **kwargs)
     43
     44

~/.local/lib/python3.6/site-packages/hanlp/utils/component_util.py in load_from_meta_file(save_dir, meta_filename, **kwargs)
     30     obj: Component = object_from_class_path(cls, **kwargs)
     31     if hasattr(obj, 'load') and os.path.isfile(os.path.join(save_dir, 'config.json')):
---> 32         obj.load(save_dir)
     33     obj.meta['load_path'] = load_path
     34     return obj

~/.local/lib/python3.6/site-packages/hanlp/common/component.py in load(self, save_dir, logger, **kwargs)
    225         self.load_config(save_dir)
    226         self.load_vocabs(save_dir)
--> 227         self.build(**merge_dict(self.config, training=False, logger=logger, **kwargs, overwrite=True, inplace=True))
    228         self.load_weights(save_dir)
    229         self.load_meta(save_dir)

~/.local/lib/python3.6/site-packages/hanlp/common/component.py in build(self, logger, **kwargs)
    236         self.transform.build_config()
    237         self.model = self.build_model(**merge_dict(self.config, training=kwargs.get('training', None),
--> 238                                                    loss=kwargs.get('loss', None)))
    239         self.transform.lock_vocabs()
    240         optimizer = self.build_optimizer(**self.config)

~/.local/lib/python3.6/site-packages/hanlp/components/taggers/transformers/transformer_tagger.py in build_model(self, transformer, max_seq_length, **kwargs)
     37         tokenizer: PreTrainedTokenizer = AutoTokenizer.from_pretrained(transformer)
     38         self.transform.tokenizer = tokenizer
---> 39         transformer: TFPreTrainedModel = TFAutoModel.from_pretrained(transformer, name=os.path.basename(transformer))
     40         self.transform.transformer_config = transformer.config
     41

~/.local/lib/python3.6/site-packages/transformers/modeling_tf_auto.py in from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
    219             return TFRobertaModel.from_pretrained(pretrained_model_name_or_path, *model_args, **kwargs)
    220         elif 'bert' in pretrained_model_name_or_path:
--> 221             return TFBertModel.from_pretrained(pretrained_model_name_or_path, *model_args, **kwargs)
    222         elif 'openai-gpt' in pretrained_model_name_or_path:
    223             return TFOpenAIGPTModel.from_pretrained(pretrained_model_name_or_path, *model_args, **kwargs)

~/.local/lib/python3.6/site-packages/transformers/modeling_tf_utils.py in from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
    311         ret = model(model.dummy_inputs, training=False)  # build the network with dummy inputs
    312
--> 313         assert os.path.isfile(resolved_archive_file), "Error retrieving file {}".format(resolved_archive_file)
    314         # 'by_name' allow us to do transfer learning by skipping/adding layers
    315         # see https://github.com/tensorflow/tensorflow/blob/00fad90125b18b80fe054de1055770cfb8fe4ba3/tensorflow/python/keras/engine/network.py#L1339-L1357

AssertionError: Error retrieving file /home/smtech/.cache/torch/transformers/987cd265ea1aa9cd7e884caf8dd86c2e764e5114ee9a14a67686c1fe05f7a26c.h5
```

**Comment by hankcs** [comment]
Error retrieving file /home/smtech/.cache/torch/transformers
BERT是由huggingface发布的，试试挂VPN或去对方[GitHub](https://github.com/huggingface/transformers)反馈。

```python
>>> from transformers import AutoModel
>>> model = AutoModel.from_pretrained("bert-base-chinese")
I0104 02:38:42.993685 140275634001664 file_utils.py:377] https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-chinese-pytorch_model.bin not found in cache or force_download set to True, downloading to 
Downloading: 100%|███████████████████████████| 412M/412M [00:07<00:00, 51.6MB/s]
```

**Comment by initNlper** [comment]
AttributeErrorTraceback (most recent call last)
<ipython-input-40-d0ea03507990> in <module>
      1 import hanlp
----> 2 recognizer = hanlp.load(hanlp.pretrained.ner.MSRA_NER_BERT_BASE_ZH)

AttributeError: module 'hanlp.pretrained.ner' has no attribute 'MSRA_NER_BERT_BASE_ZH'

**Comment by hankcs** [comment]
> AttributeErrorTraceback (most recent call last)
> in
> 1 import hanlp
> ----> 2 recognizer = hanlp.load(hanlp.pretrained.ner.MSRA_NER_BERT_BASE_ZH)
> 
> AttributeError: module 'hanlp.pretrained.ner' has no attribute 'MSRA_NER_BERT_BASE_ZH'

pip3 install hanlp -U

**Comment by initNlper** [comment]
Downloading: 0%
417k/478M [00:50<17:11:00, 7.73kB/s]
您好，我想问一下，在Load bert_base_ner的模型的时候，下载的特别慢。
/home/deeplearn/.hanlp/ner/ner_bert_base_msra_20191230_20574，查看到已经下面是有文件的了，这个是缺了上面描述的bert么？但是看文件大小不一样

**Comment by hankcs** [comment]
.hanlp下面是hanlp的模型，bert是huggingface的。

**Comment by hankcs** [comment]
国内下载[Google的源](https://storage.googleapis.com/albert_models/albert_xxlarge_zh.tar.gz)会快一点吗？我考虑去掉huggingface

**Comment by initNlper** [comment]
> 国内下载[Google的源](https://storage.googleapis.com/albert_models/albert_xxlarge_zh.tar.gz)会快一点吗？我考虑去掉huggingface

反正我挂了SSR，10几KB在下...

**Comment by hankcs** [comment]
不挂呢？我在北京的华为云可以上800KB

**Comment by initNlper** [comment]
![image](https://user-images.githubusercontent.com/59408132/71763763-9b564980-2f1a-11ea-8603-e687ded9bf9a.png)

**Comment by hankcs** [comment]
我的意思是直接 wget https://storage.googleapis.com/albert_models/albert_xxlarge_zh.tar.gz
如果这个速度可以我就用google的。

**Comment by initNlper** [comment]
![image](https://user-images.githubusercontent.com/59408132/71763790-0273fe00-2f1b-11ea-8fa1-76a0d1b68cc2.png)
这个好多了。。

**Comment by hankcs** [comment]
谢谢，那就用这个了。

**Comment by initNlper** [comment]
下载了google的Pretrain_model，可以手动解压到某个指定路径么？以替换原来下载不了的

**Comment by hankcs** [comment]
不行，两个格式不一样

**Comment by yunyu-Mr** [comment]
pip -U 更新代码之后，现在 HTTPConnection fail 了。可否提供手动下载方式？

```
SSLError                                  Traceback (most recent call last)
~/.local/lib/python3.6/site-packages/transformers/tokenization_utils.py in _from_pretrained(cls, pretrained_model_name_or_path, *init_inputs, **kwargs)
    378                 else:
--> 379                     resolved_vocab_files[file_id] = cached_path(file_path, cache_dir=cache_dir, force_download=force_download, proxies=proxies, resume_download=resume_download)
    380         except EnvironmentError:

~/.local/lib/python3.6/site-packages/transformers/file_utils.py in cached_path(url_or_filename, cache_dir, force_download, proxies, resume_download, user_agent)
    210             force_download=force_download, proxies=proxies,
--> 211             resume_download=resume_download, user_agent=user_agent)
    212     elif os.path.exists(url_or_filename):

~/.local/lib/python3.6/site-packages/transformers/file_utils.py in get_from_cache(url, cache_dir, force_download, proxies, etag_timeout, resume_download, user_agent)
    369             else:
--> 370                 http_get(url, temp_file, proxies=proxies, resume_size=resume_size, user_agent=user_agent)
    371

~/.local/lib/python3.6/site-packages/transformers/file_utils.py in http_get(url, temp_file, proxies, resume_size, user_agent)
    284         headers['Range'] = 'bytes=%d-' % (resume_size,)
--> 285     response = requests.get(url, stream=True, proxies=proxies, headers=headers)
    286     if response.status_code == 416:  # Range not satisfiable

/usr/lib/python3/dist-packages/requests/api.py in get(url, params, **kwargs)
     71     kwargs.setdefault('allow_redirects', True)
---> 72     return request('get', url, params=params, **kwargs)
     73

/usr/lib/python3/dist-packages/requests/api.py in request(method, url, **kwargs)
     57     with sessions.Session() as session:
---> 58         return session.request(method=method, url=url, **kwargs)
     59

/usr/lib/python3/dist-packages/requests/sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    519         send_kwargs.update(settings)
--> 520         resp = self.send(prep, **send_kwargs)
    521

/usr/lib/python3/dist-packages/requests/sessions.py in send(self, request, **kwargs)
    629         # Send the request
--> 630         r = adapter.send(request, **kwargs)
    631

/usr/lib/python3/dist-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    505                 # This branch is for urllib3 v1.22 and later.
--> 506                 raise SSLError(e, request=request)
    507

SSLError: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /models.huggingface.co/bert/bert-base-chinese-vocab.txt (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:852)'),))
```

**Comment by hankcs** [comment]
> pip -U 更新代码之后，现在 HTTPConnection fail 了。可否提供手动下载方式？
> 
> ```
> SSLError                                  Traceback (most recent call last)
> ~/.local/lib/python3.6/site-packages/transformers/tokenization_utils.py in _from_pretrained(cls, pretrained_model_name_or_path, *init_inputs, **kwargs)
>     378                 else:
> --> 379                     resolved_vocab_files[file_id] = cached_path(file_path, cache_dir=cache_dir, force_download=force_download, proxies=proxies, resume_download=resume_download)
>     380         except EnvironmentError:
> 
> ~/.local/lib/python3.6/site-packages/transformers/file_utils.py in cached_path(url_or_filename, cache_dir, force_download, proxies, resume_download, user_agent)
>     210             force_download=force_download, proxies=proxies,
> --> 211             resume_download=resume_download, user_agent=user_agent)
>     212     elif os.path.exists(url_or_filename):
> 
> ~/.local/lib/python3.6/site-packages/transformers/file_utils.py in get_from_cache(url, cache_dir, force_download, proxies, etag_timeout, resume_download, user_agent)
>     369             else:
> --> 370                 http_get(url, temp_file, proxies=proxies, resume_size=resume_size, user_agent=user_agent)
>     371
> 
> ~/.local/lib/python3.6/site-packages/transformers/file_utils.py in http_get(url, temp_file, proxies, resume_size, user_agent)
>     284         headers['Range'] = 'bytes=%d-' % (resume_size,)
> --> 285     response = requests.get(url, stream=True, proxies=proxies, headers=headers)
>     286     if response.status_code == 416:  # Range not satisfiable
> 
> /usr/lib/python3/dist-packages/requests/api.py in get(url, params, **kwargs)
>      71     kwargs.setdefault('allow_redirects', True)
> ---> 72     return request('get', url, params=params, **kwargs)
>      73
> 
> /usr/lib/python3/dist-packages/requests/api.py in request(method, url, **kwargs)
>      57     with sessions.Session() as session:
> ---> 58         return session.request(method=method, url=url, **kwargs)
>      59
> 
> /usr/lib/python3/dist-packages/requests/sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
>     519         send_kwargs.update(settings)
> --> 520         resp = self.send(prep, **send_kwargs)
>     521
> 
> /usr/lib/python3/dist-packages/requests/sessions.py in send(self, request, **kwargs)
>     629         # Send the request
> --> 630         r = adapter.send(request, **kwargs)
>     631
> 
> /usr/lib/python3/dist-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
>     505                 # This branch is for urllib3 v1.22 and later.
> --> 506                 raise SSLError(e, request=request)
>     507
> 
> SSLError: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /models.huggingface.co/bert/bert-base-chinese-vocab.txt (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:852)'),))
> ```

我过会儿发一个新版本，用Google的源。

**Comment by hankcs** [comment]
pip install --upgrade hanlp
