### ISSUE TITLE
预训练模型下载太慢，尝试了很多次都失败了

### ISSUE THREAD

**Issue by carrytameng** [hankcs/HanLP#1379]
recognizer = hanlp.load(hanlp.pretrained.ner.MSRA_NER_BERT_BASE_ZH)

Downloading:   0%|          | 939k/478M [07:50<2643:19:23, 50.2B/s]

请问通过其它工具下载完成，放在哪个目录下？我在日志里看到从./cache/*** 里加载

**Comment by hankcs** [comment]
pip install --upgrade hanlp

**Comment by carrytameng** [comment]
Thanks!
