### ISSUE TITLE
无法使用词性标注，NER等功能

### ISSUE THREAD

**Issue by woshizmz** [hankcs/HanLP#1381]
当我运行以下示例代码：
tagger = hanlp.load(hanlp.pretrained.pos.CTB5_POS_RNN_FASTTEXT)
得到了以下错误:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'hanlp.pretrained.pos' has no attribute 'CTB5_POS_RNN_FASTTEXT'
我们的功能还在开发状态吗？

**Comment by hankcs** [comment]
你在用什么版本？

`pip install --upgrade hanlp`

**Comment by hankcs** [comment]
变量名改了，ide没提示你吗？

https://github.com/hankcs/HanLP/blob/fbbb38af3a70b7bfd05b384c0e5027a9cb9b36ab/hanlp/pretrained/pos.py#L6-L7

**Comment by woshizmz** [comment]
> 你在用什么版本？
> 
> `pip install --upgrade hanlp`

VERSION
    2.0.0-alpha.10

更新后并没有改善！

**Comment by hankcs** [comment]
变量名改成CTB5_POS_RNN_FASTTEXT_ZH了。

**Comment by woshizmz** [comment]
> CTB5_POS_RNN_FASTTEXT_ZH

OK，谢谢，希望有时间也将其他功能的变量名改变同步到<Code>上吧！
