### ISSUE TITLE
寻找词性对照表

### ISSUE THREAD

**Issue by StephenZMZ** [hankcs/HanLP#1385]
当我运行词性标注程序获得结果后
>>> tagger(['我', '的', '希望', '是', '希望', '和平'])
['PN', 'DEG', 'NN', 'VC', 'VV', 'NN']

我希望有一个份对应的’词性对照表‘，知道DEG或者VV代表什么.

**Comment by hankcs** [comment]
请参考CTB标注集，或[《自然语言处理入门》](http://nlp.hankcs.com/book.php)。

**Comment by hankcs** [comment]
有空了也会出一份文档，可能要等很久了。
