### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by hankcs** [hankcs/HanLP#1386]
Planning to fully document all the codes and set up a documentation service.

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form.

**Comment by Gandalfthegreat** [comment]
Hi, what is the progress of the document? Looking forward to it and thanks a lot for your effort!

**Comment by hankcs** [comment]
> Hi, what is the progress of the document? Looking forward to it and thanks a lot for your effort!

Hi, thanks for your attention. I'm working on a PyTorch backend now. I will get to the documentation after that.

**Comment by hankcs** [comment]
Hi @Gandalfthegreat , our documentation is finally online now https://hanlp.hankcs.com/docs/index.html
