### ISSUE TITLE
RESTful API in Python

### ISSUE THREAD

**Issue by hankcs** [hankcs/HanLP#1388]
Implement a RESTful API in Python, then release it to pypi.

**Comment by NLPpupil** [comment]
请问这个怎么用？

**Comment by hankcs** [comment]
一个远程调用API，还在开发中，等正式发布了再看文档吧。

**Comment by Du-Jia** [comment]
win10
anaconda 虚拟环境
已经安装好了tensorflow2.1及其相关依赖包
执行pip install hanlp命令之后仍会自动安装tensorflow2.1，是否是BUG？

**Comment by Du-Jia** [comment]
补充：
已安装的包列表：
(TF2.1) PS D:\Download> pip list
Package                  Version
------------------------ -------------------
absl-py                  0.9.0
astor                    0.8.1
cachetools               4.0.0
certifi                  2019.11.28
chardet                  3.0.4
cloudpickle              1.2.2
cycler                   0.10.0
cytoolz                  0.10.1
dask                     2.9.2
decorator                4.4.1
gast                     0.2.2
google-auth              1.11.0
google-auth-oauthlib     0.4.1
google-pasta             0.1.8
grpcio                   1.26.0
h5py                     2.10.0
idna                     2.8
imageio                  2.6.1
JPype1                   0.7.0
Keras                    2.3.1
Keras-Applications       1.0.8
Keras-Preprocessing      1.1.0
kiwisolver               1.1.0
Markdown                 3.1.1
matplotlib               3.1.1
mkl-fft                  1.0.15
mkl-random               1.1.0
mkl-service              2.3.0
networkx                 2.4
numpy                    1.18.1
oauthlib                 3.1.0
olefile                  0.46
opt-einsum               3.1.0
Pillow                   7.0.0
pip                      19.3.1
protobuf                 3.11.2
pyasn1                   0.4.8
pyasn1-modules           0.2.8
pyhanlp                  0.1.61
pyparsing                2.4.6
python-dateutil          2.8.1
pytz                     2019.3
PyWavelets               1.1.1
PyYAML                   5.3
requests                 2.22.0
requests-oauthlib        1.3.0
rsa                      4.0
scikit-image             0.15.0
scipy                    1.4.1
setuptools               44.0.0.post20200106
six                      1.13.0
tensorboard              2.1.0
tensorflow-gpu           2.1.0
tensorflow-gpu-estimator 2.1.0
termcolor                1.1.0
toolz                    0.10.0
tornado                  6.0.3
urllib3                  1.25.8
Werkzeug                 0.16.0
wheel                    0.33.6
wincertstore             0.2
wrapt                    1.11.2
出现问题：
(TF2.1) PS D:\Download> pip install hanlp
Collecting hanlp
  Using cached https://files.pythonhosted.org/packages/06/ee/1f5539a9a7b351c41e81f0567db691b4c0ddb8ba3b06a72f6a4a334219ec/hanlp-2.0.0a32.tar.gz
Collecting tensorflow==2.1.0
  Downloading https://files.pythonhosted.org/packages/34/d5/ce8c17971067c0184c9045112b755be5461d5ce5253ef65a367e1298d7c5/tensorflow-2.1.0-cp37-cp37m-win_amd64.whl (355.8MB)
     |                                | 61kB 53kB/s eta 1:50:08

**Comment by hankcs** [comment]
> win10
> anaconda 虚拟环境
> 已经安装好了tensorflow2.1及其相关依赖包
> 执行pip install hanlp命令之后仍会自动安装tensorflow2.1，是否是BUG？

1. 不是bug。
1. hanlp依赖 tensorflow，你安装的是tensorflow-gpu
1. The tensorflow pip package now includes GPU support by default (same as tensorflow-gpu) for both Linux and Windows. This runs on machines with and without NVIDIA GPUs. tensorflow-gpu is still available, and CPU-only packages can be downloaded at tensorflow-cpu for users who are concerned about package size.

**Comment by Luna-Lovegoood** [comment]
请问大约什么时间发布呢

**Comment by hankcs** [comment]
> 请问大约什么时间发布呢

最近比较忙，请留意[蝴蝶效应](https://bbs.hankcs.com/)上的消息。

**Comment by minda163** [comment]
请问这个RESTful API发布了吗？

**Comment by hankcs** [comment]
暂时还没有，暂定7月份发布。

**Comment by minda163** [comment]
翘首以盼

**Comment by xiayuqingyi** [comment]
买了书在学习，书中说配套代码在tests/book/...文件夹中，没有找到啊？

**Comment by huiskelly** [comment]
请问支持gpu版本的hanlp现在有了吗？

**Comment by hankcs** [comment]
已经发布 https://github.com/hankcs/HanLP/tree/doc-zh

**Comment by shengtaovvv** [comment]
请问完整的python native API文档在哪里，我看发布的这个只是快速上手指南，很多功能没有找到怎么调用，比如文本相识度计算
