### ISSUE TITLE
使用jvm参数修改root路径后，本地调试读取不到词典！

### ISSUE THREAD

**Issue by 1003020910** [hankcs/HanLP#1395]
按照如下方式，采用第二种方式，在jvm启动参数中添加root目录，然后将hanlp.properties配置文件中的root配置删除，结果读取不到词典。
![image](https://user-images.githubusercontent.com/49811193/72126059-b3f4b280-33a5-11ea-9f6c-ddcf4f56a692.png)

**Comment by hankcs** [comment]
【自动回复】你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真修改，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
![issue](http://wx1.sinaimg.cn/large/006Fmjmcly1ft2hnlwc22j30q90bcgpe.jpg)
