### ISSUE TITLE
ModuleNotFoundError: No module named 'regex'

### ISSUE THREAD

**Issue by butlerwilson** [hankcs/HanLP#1396]
**Describe the bug**

**ModuleNotFoundError: No module named 'regex'**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
Python 3.7.5 (default, Jan  6 2020, 17:18:04)
[Clang 11.0.0 (clang-1100.0.33.16)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import hanlp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/.pyenv/versions/3.7.5/lib/python3.7/site-packages/hanlp/__init__.py", line 6, in <module>
    import hanlp.common
  File "/Users/user/.pyenv/versions/3.7.5/lib/python3.7/site-packages/hanlp/common/__init__.py", line 4, in <module>
    from . import component
  File "/Users/user/.pyenv/versions/3.7.5/lib/python3.7/site-packages/hanlp/common/component.py", line 17, in <module>
    from hanlp.common.structure import SerializableDict
  File "/Users/user/.pyenv/versions/3.7.5/lib/python3.7/site-packages/hanlp/common/structure.py", line 6, in <module>
    from hanlp.utils.io_util import save_json, save_pickle, load_pickle, load_json, filename_is_json
  File "/Users/user/.pyenv/versions/3.7.5/lib/python3.7/site-packages/hanlp/utils/__init__.py", line 5, in <module>
    from . import rules
  File "/Users/user/.pyenv/versions/3.7.5/lib/python3.7/site-packages/hanlp/utils/rules.py", line 3, in <module>
    from hanlp.utils.english_tokenizer import tokenize_english
  File "/Users/user/.pyenv/versions/3.7.5/lib/python3.7/site-packages/hanlp/utils/english_tokenizer.py", line 12, in <module>
    from regex import compile, DOTALL, UNICODE, VERBOSE
ModuleNotFoundError: No module named 'regex'
```

**Describe the current behavior**
ModuleNotFoundError: No module named 'regex'

**Expected behavior**
No error, no warning.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Darwin MacBook 19.2.0
- Python version: 3.7.5
- HanLP version: 2.0.0a10

**Other info / logs**

**Solved**

```
pip install regex
```

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form.

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form.

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form.

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form.

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form.

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form.

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form.

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form.

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form.

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form.

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form.

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form.

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form.

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form.

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form.

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form.

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form.

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form.

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form.

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form.

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form.

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form.

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form.

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form.

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form.

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form.

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form.

**Comment by hankcs** [comment]
Sorry, the spam filter is malfunctioning. I'm looking into this issue now.

**Comment by hankcs** [comment]
Fixed, thanks @butlerwilson for spotting this.
