### ISSUE TITLE
Error in component_util.py file. Should be sys.exit(), but instead it is exit(). Also need to import sys 

### ISSUE THREAD

**Issue by ElToro13** [hankcs/HanLP#1399]
**Describe the bug**
I am trying to run NER with hanlp, but it is giving me an error. I am running the following comman in Google Colab with GPU

recognizer = hanlp.load(hanlp.pretrained.ner.CONLL03_NER_BERT_BASE_UNCASED_EN)

**Code to reproduce the issue**
Following were my Cell values in Colab
!pip install --hanlp
import hanlp
recognizer = hanlp.load(hanlp.pretrained.ner.CONLL03_NER_BERT_BASE_UNCASED_EN)

```python
```

**Describe the current behavior**
When I run the said code, I get the follwoing error and point to this file "component_util.py"
NameError: name 'exit' is not defined on line 56

**Expected behavior**
The command should have ran successfully allowing me to Find Named Entity in  sentence

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab with GPU
- Python version: 3.6
- HanLP version: 2.0.0

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
Seems like Google Colab changed the IO object which breaks the redirection. I'll look into this.

**Comment by hankcs** [comment]
I released a patch, could you retry after `pip install -U hanlp`? If the issue persists, welcome to reopen it.

**Comment by ElToro13** [comment]
Nope. Same error. Its mad with that exit ord as it is not defined

**Comment by hankcs** [comment]
Yes, I'm testing with Colab too, will find a solution soon.

**Comment by hankcs** [comment]
No it works on Colab. `pip install -U hanlp`. Let me close it but feel free to submit new issues.
