### ISSUE TITLE
PlaceDictionary调用的疑问

### ISSUE THREAD

**Issue by starkingpku** [hankcs/HanLP#140]
句子"蓝翔给宁夏固原市彭阳县红河镇黑牛沟村捐赠了挖掘机"粗切分后得到 "[蓝, 翔, 给, 宁夏, 固原市, 彭, 阳, 县, 红, 河镇, 黑, 牛, 沟, 村, 捐赠, 了, 挖掘机]。在地名识别阶段，在PlaceRecognition.java第109行涉及从地名词典ns.txt中读取地名的NS枚举类型的代码，如下：
EnumItem<NS> NSEnumItem = PlaceDictionary.dictionary.get(vertex.word);
问题是，我发现当程序执行到vertex.word是“宁夏”时，返回的NSEnumItem为null，而我查了ns.txt发现存在记录"宁夏 G 351"。请问是该返回null吗？我怎么觉得理应该返回"G 351"呢？哪里出现问题了？

**Comment by hankcs** [comment]
感谢反馈
0.             EnumItem<NS> NSEnumItem = PlaceDictionary.dictionary.get(vertex.word);  // 此处用等效词，更加精准
0. 这是后面加的逻辑，在训练的时候没有执行相同的逻辑

**Comment by starkingpku** [comment]
我没有看明白，"宁夏 G 351"这种地名该不该加入到ns.txt呢？

**Comment by starkingpku** [comment]
还有机构词典的调用，也不太清楚机制。比如，EnumItem<NT> NTEnumItem = OrganizationDictionary.dictionary.get(vertex.word);
当vertex.word=“上海”时，返回的NTEnumItem的内容是“G 92134 B 1200 A 470 D 84 X 4”。
而我查看了nt.txt文件，并没有“上海”这个词条，这是怎么回事呢？

**Comment by hankcs** [comment]
所有问题都是由数据决定的，训练的时候用了什么数据，导致后面出什么结果。
上海是地名，所以对应 未##地 G 92134 B 1200 A 470 D 84 X 4
