### ISSUE TITLE
hanlp.properties 的root远程配置

### ISSUE THREAD

**Issue by shaohualuan** [hankcs/HanLP#1400]
**Describe the bug**
我使用相对路径root=./ 配置hanlp.properties 在某些项目（老版本tomcat是不成功的，springboot项目没有问题）
因此我想采用绝对路径+远程data目录的形式进行hanlp对词库的访问

我的配置如下
root=http://ip:port/
#核心词典路径
CoreDictionaryPath=data/dictionary/CoreNatureDictionary.txt
.....

我保证通过http://ip:port/filename 可以直接获取到线上的词库内容，但是依旧存在
警告: 核心词典http://ip:port/data/dictionary/CoreNatureDictionary.txt不存在！java.io.FileNotFoundException: http:\ip:port\data\dictionary\CoreNatureDictionary.txt (文件名、目录名或卷标语法不正确。)

**Comment by hankcs** [comment]
【自动回复】你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真修改，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
![issue](http://wx1.sinaimg.cn/large/006Fmjmcly1ft2hnlwc22j30q90bcgpe.jpg)
