### ISSUE TITLE
2.0.0-alpha.25 加载 CTB5_POS_RNN 出错

### ISSUE THREAD

**Issue by SoaringTiger** [hankcs/HanLP#1403]
**Describe the bug**
2.0.0-alpha.25 加载 CTB5_POS_RNN 出错

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
tokenizer = hanlp.load('CTB5_POS_RNN')
print(tokenizer('商品和服务'))
```

**Describe the current behavior**
加载 CTB5_POS_RNN 出错

试了几次，此处出错
Downloading **https://github.com/SUDA-LA/CIP/archive/master.zip#BPNN/data/embed.txt** to /root/.hanlp/thirdparty/github.com/SUDA-LA/CIP/archive/master.zip
**100.00%, 4 KB/4 KB, 14.1 MB/s, ETA 0 s**     
......
**FileNotFoundError**: [Errno 2] No such file or directory: '/root/.hanlp/thirdparty/github.com/SUDA-LA/CIP/archive/master/BPNN/data/embed.txt'

**Expected behavior**
能够运行测试代码

**System information**
- Ubuntu 18.04
- Python version: 3.6
- HanLP version: 2.0.0-alpha.25

**Other info / logs**
Downloading https://file.hankcs.com/hanlp/pos/ctb5_pos_rnn_20191229_015325.zip to /root/.hanlp/pos/ctb5_pos_rnn_20191229_015325.zip
100.00%, 52.4 MB/52.4 MB, 4.2 MB/s, ETA 0 s        
Extracting /root/.hanlp/pos/ctb5_pos_rnn_20191229_015325.zip to /root/.hanlp/pos
Downloading https://github.com/SUDA-LA/CIP/archive/master.zip#BPNN/data/embed.txt to /root/.hanlp/thirdparty/github.com/SUDA-LA/CIP/archive/master.zip
**100.00%, 4 KB/4 KB, 14.1 MB/s, ETA 0 s**      
Extracting /root/.hanlp/thirdparty/github.com/SUDA-LA/CIP/archive/master.zip to /root/.hanlp/thirdparty/github.com/SUDA-LA/CIP/archive
Failed to load https://file.hankcs.com/hanlp/pos/ctb5_pos_rnn_20191229_015325.zip. See stack trace below
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/hanlp/utils/component_util.py", line 43, in load_from_meta_file
    obj.load(save_dir, **load_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/hanlp/common/component.py", line 244, in load
    self.build(**merge_dict(self.config, training=False, logger=logger, **kwargs, overwrite=True, inplace=True))
  File "/usr/local/lib/python3.6/dist-packages/hanlp/common/component.py", line 255, in build
    loss=kwargs.get('loss', None)))
  File "/usr/local/lib/python3.6/dist-packages/hanlp/components/taggers/rnn_tagger.py", line 34, in build_model
    embeddings = build_embedding(embeddings, self.transform.word_vocab, self.transform)
  File "/usr/local/lib/python3.6/dist-packages/hanlp/layers/embeddings/__init__.py", line 53, in build_embedding
    trainable=config.get('embedding_trainable', False))
  File "/usr/local/lib/python3.6/dist-packages/hanlp/layers/embeddings/word2vec.py", line 22, in __init__
    self.vocab, self.array_np = self._load(path, vocab, normalize)
  File "/usr/local/lib/python3.6/dist-packages/hanlp/layers/embeddings/word2vec.py", line 50, in _load
    word2vec, dim = load_word2vec(path)
  File "/usr/local/lib/python3.6/dist-packages/hanlp/utils/io_util.py", line 420, in load_word2vec
    with open(realpath, encoding='utf-8', errors='ignore') as f:
**FileNotFoundError**: [Errno 2] No such file or directory: '/root/.hanlp/thirdparty/github.com/SUDA-LA/CIP/archive/master/BPNN/data/embed.txt'
https://file.hankcs.com/hanlp/pos/ctb5_pos_rnn_20191229_015325.zip was created with hanlp-2.0.0, while you are running 2.0.0-alpha.25. Try to upgrade hanlp with
pip install --upgrade hanlp

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
苏大删库了。

感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。
