### ISSUE TITLE
怎么查看GPU是否成功使用

### ISSUE THREAD

**Issue by NLPpupil** [hankcs/HanLP#1406]
**Describe the bug**
pip安装之后，可以成功运行NER，但是增加batch后GPU的显存始终停留在100多MB，怎么查看GPU是否成功使用？

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
你可能没装好显卡驱动和cuda。你可以`export HANLP_SHOW_TF_LOG=1`去检查日志。另外，这类问题应该发在其他地方或自行搜索。
