### ISSUE TITLE
pycharm下安装出错

### ISSUE THREAD

**Issue by BiRocco** [hankcs/HanLP#1407]
E:\1Study\毕设\python_prj\NLP2\venv\Scripts\python.exe E:/1Study/毕设/python_prj/NLP2/test.py
Traceback (most recent call last):
  File "E:/1Study/毕设/python_prj/NLP2/test.py", line 1, in <module>
    from pyhanlp import *
  File "E:\1Study\毕设\python_prj\NLP2\venv\lib\site-packages\pyhanlp\__init__.py", line 12, in <module>
    from jpype import JClass, startJVM, getDefaultJVMPath, isThreadAttachedToJVM, attachThreadToJVM, java, \
ImportError: cannot import name 'JVMNotFoundException' from 'jpype' (E:\1Study\毕设\python_prj\NLP2\venv\lib\site-packages\jpype\__init__.py)__

**Comment by hankcs** [comment]
【自动回复】你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真修改，然后耐心等待下周末处理。
咨询类的问题应该发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
![issue](http://wx1.sinaimg.cn/large/006Fmjmcly1ft2hnlwc22j30q90bcgpe.jpg)
