### ISSUE TITLE
拼音转换 “看着” 应该是 kanzhe

### ISSUE THREAD

**Issue by afeiych** [hankcs/HanLP#1408]
如题

**Comment by afeiych** [comment]
现在是：kan4,zhuo2

**Comment by hankcs** [comment]
【自动回复】你好，感谢反馈。
由于未按要求填写，本issue被暂时标记为无效。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真修改，然后耐心等待下周末处理。
咨询类的问题应该发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
![issue](http://wx1.sinaimg.cn/large/006Fmjmcly1ft2hnlwc22j30q90bcgpe.jpg)

**Comment by hankcs** [comment]
现在是正确的啊。

原文,看,着,！,
拼音（数字音调）,kan4,zhe5,none5,
拼音（符号音调）,kàn,zhe,none,
拼音（无音调）,kan,zhe,none,
声调,4,5,5,
声母,k,zh,none,
韵母,an,e,none,
输入法头,k,zh,none,
jie zhi none none none none nian none
jie zhi 2 0 1 2 nian ，
