### ISSUE TITLE
pipeline Object of type 'CoNLLWord' is not JSON serializable

### ISSUE THREAD

**Issue by SoaringTiger** [hankcs/HanLP#1409]
**Describe the bug**
pipeline  syntactic_parser  输出的结果 通过 json dump 失败    .

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
import hanlp
import json

tokenizer = hanlp.load('CTB6_CONVSEG')
tagger = hanlp.load('CTB5_POS_RNN')
syntactic_parser = hanlp.load('CTB7_BIAFFINE_DEP_ZH')

text = '测试一下这个方法能否使用。'

pipeline = hanlp.pipeline() \
            .append(hanlp.utils.rules.split_sentence, output_key='sentences') \
            .append(tokenizer, output_key='tokens') \
            .append(tagger, output_key='part_of_speech_tags')
            .append(syntactic_parser, input_key=('tokens', 'part_of_speech_tags'), output_key='syntactic_dependencies')

output = pipeline(text)

print(output)    # **结果能正常打印**

with open('output.json',"w") as f:
    json.dump(output, f, indent=4, ensure_ascii=False)
```

**Describe the current behavior**
json.dump 失败

**Expected behavior**
能正常 JSON serializable

**System information**
- OS Platform and Distribution: Ubuntu 18.04
- Python version: 3.6
- HanLP version: hanlp 2.0.0a30

**Other info / logs**
Traceback (most recent call last):
  File "down.py", line 33, in <module>
    json.dump(output, f, indent=4, ensure_ascii=False)
  File "/usr/lib/python3.6/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/lib/python3.6/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.6/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.6/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'CoNLLWord' is not JSON serializable

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
目前CoNLLWord的序列化需要如下实现的：https://github.com/hankcs/HanLP/blob/ca50edb77f744187bd8b45e05cb268eba6c2ef7f/hanlp/common/document.py#L48
