### ISSUE TITLE
pip install hanlp会自动下载tensorflow2.1

### ISSUE THREAD

**Issue by NLPpupil** [hankcs/HanLP#1411]
**Describe the bug**
pip install hanlp会自动下载tensorflow2.1，并覆盖已有的tensorflow-gpu2.0

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```bash
pip install hanlp
```

**Describe the current behavior**
```bash
Collecting hanlp
  Using cached hanlp-2.0.0a33.tar.gz (130 kB)
Collecting tensorflow==2.1.0
  Using cached tensorflow-2.1.0-cp36-cp36m-manylinux2010_x86_64.whl (421.8 MB)
```

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):16.04.1-Ubuntu
- Python version: 3.6
- HanLP version: hanlp-2.0.0a33

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
这是正常现象，hanlp指定依赖tf2.1，低版本高版本tf都不兼容。如果你想保留你的tf，可以在virtual env中安装hanlp。
