### ISSUE TITLE
hanlp 2.0.0a33 pipeline 自定义 output_key 后，json 序列化结果残留sentences 、 tokens、part_of_speech_tags 等字段

### ISSUE THREAD

**Issue by SoaringTiger** [hankcs/HanLP#1412]
**Describe the bug**
hanlp 2.0.0a33 pipeline 自定义 output_key 后，json 序列化结果残留**sentences 、 tokens、part_of_speech_tags、named_entities、syntactic_dependencies、semantic_dependencies** 等字段

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
import hanlp
import json

print('正在加载')

tokenizer = hanlp.load('CTB6_CONVSEG')
tagger = hanlp.load('CTB5_POS_RNN')
syntactic_parser = hanlp.load('CTB7_BIAFFINE_DEP_ZH')
semantic_parser = hanlp.load('SEMEVAL16_TEXT_BIAFFINE_ZH')

# 下面自定义了 ouput_key
pipeline = hanlp.pipeline() \
    .append(hanlp.utils.rules.split_sentence, output_key='s') \
    .append(tokenizer, output_key='t') \
    .append(tagger, output_key='p') \
    .append(syntactic_parser, input_key=('t', 'p'), output_key='syn', conll=False) \
    .append(semantic_parser, input_key=('t', 'p'), output_key='sem', conll=False)
print(pipeline)

text = '''HanLP是一系列模型与算法组成的自然语言处理工具包，目标是普及自然语言处理在生产环境中的应用。
HanLP具备功能完善、性能高效、架构清晰、语料时新、可自定义的特点。
内部算法经过工业界和学术界考验，配套书籍《自然语言处理入门》已经出版。
'''

doc = pipeline(text)
print(doc)  # 打印结果正常，没有残留字段

with open('output.json',"w") as f:
    json.dump(doc, f, indent=4, ensure_ascii=False)    # 序列化的结果有残留字段
```

**Describe the current behavior**
json 序列化后的结果，存在下面一些“**未定义字段**”
{
    "sentences": [],
    "tokens": [],
    "part_of_speech_tags": [],
    "named_entities": [],
    "syntactic_dependencies": [],
    "semantic_dependencies": [],
    "s": [
        "HanLP是一系列模型与算法组成的自然语言处理工具包，目标是普及自然语言处理在生产环境中的应用。",
        "HanLP具备功能完善、性能高效、架构清晰、语料时新、可自定义的特点。",
        "内部算法经过工业界和学术界考验，配套书籍《自然语言处理入门》已经出版。"
    ],
...

**Expected behavior**
**未定义字段不出现**

**System information**
- OS Platform and Distribution:18.04
- Python version:3.6
- HanLP version:hanlp 2.0.0a33

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。
