### ISSUE TITLE
load数据中的error

### ISSUE THREAD

**Issue by Roottan** [hankcs/HanLP#1419]
**Describe the bug**
过程是这样的：
通过hanlp.pretrained.ALL  取得了load在变量后进行批量load，发现出错很多：

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
```

**Describe the current behavior**
A clear and concise description of what happened.
hanlp.load('GLOVE_6B_ROOT')
hanlp.load('GLOVE_6B_50D')
hanlp.load('GLOVE_6B_100D')
hanlp.load('GLOVE_6B_200D')
hanlp.load('GLOVE_6B_300D')
hanlp.load('GLOVE_840B_300D')
hanlp.load('PTB_POS_RNN_FASTTEXT_EN')
hanlp.load('FLAIR_LM_FW_WMT11_EN')
hanlp.load('FLAIR_LM_BW_WMT11_EN')
hanlp.load('CONVSEG_W2V_NEWS_TENSITE')
hanlp.load('CONVSEG_W2V_NEWS_TENSITE_WORD_PKU')
hanlp.load('CONVSEG_W2V_NEWS_TENSITE_WORD_MSR')
hanlp.load('CONVSEG_W2V_NEWS_TENSITE_CHAR')
hanlp.load('SEMEVAL16_EMBEDDINGS_CN')
hanlp.load('SEMEVAL16_EMBEDDINGS_300_NEWS_CN')
hanlp.load('SEMEVAL16_EMBEDDINGS_300_TEXT_CN')
hanlp.load('CTB5_FASTTEXT_300_CN')
hanlp.load('TENCENT_AI_LAB_EMBEDDING')
hanlp.load('RADICAL_CHAR_EMBEDDING_100')

hanlp.load()   时发生错误。

**Expected behavior**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 prof  X64
- Python version:  Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32
- HanLP version: hanlp==2.0.0a36

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
详细的信息如下：
******第一:******
hanlp.load('GLOVE_6B_ROOT')
hanlp.load('GLOVE_6B_50D')
hanlp.load('GLOVE_6B_100D')
hanlp.load('GLOVE_6B_200D')
hanlp.load('GLOVE_6B_300D')
hanlp.load('GLOVE_840B_300D')
hanlp.load('PTB_POS_RNN_FASTTEXT_EN')
hanlp.load('FLAIR_LM_FW_WMT11_EN')
hanlp.load('FLAIR_LM_BW_WMT11_EN')
hanlp.load('CONVSEG_W2V_NEWS_TENSITE')
hanlp.load('CONVSEG_W2V_NEWS_TENSITE_WORD_PKU')
hanlp.load('CONVSEG_W2V_NEWS_TENSITE_WORD_MSR')
hanlp.load('CONVSEG_W2V_NEWS_TENSITE_CHAR')
hanlp.load('SEMEVAL16_EMBEDDINGS_CN')
hanlp.load('SEMEVAL16_EMBEDDINGS_300_NEWS_CN')
hanlp.load('SEMEVAL16_EMBEDDINGS_300_TEXT_CN')
hanlp.load('CTB5_FASTTEXT_300_CN')
hanlp.load('TENCENT_AI_LAB_EMBEDDING')
hanlp.load('RADICAL_CHAR_EMBEDDING_100')

这几个下载报类似这样在错误：
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36\lib\site-packages\hanlp\__init__.py", line 51, in load
    return load_from_meta_file(save_dir, meta_filename, transform_only=transform_only, load_kwargs=load_kwargs, **kwargs)
  File "C:\Python36\lib\site-packages\hanlp\utils\component_util.py", line 34, in load_from_meta_file
    raise FileNotFoundError(f'The identifier {save_dir} resolves to a non-exist meta file {metapath}. {tips}')
FileNotFoundError: The identifier C:\Users\Roottan\AppData\Roaming\hanlp\hanlp\lm\flair_lm_wmt11_en_20191229_033714\flair_lm_bw_wmt11_en resolves to a non-exist meta file C:\Users\****\AppData\Roaming\hanlp\hanlp\lm\flair_lm_wmt11_en_20191229_033714\flair_lm_bw_wmt11_en\meta.json.

就是报：meta.json 文件找不到。

******第二:********
hanlp.load('MSRA_NER_BERT_BASE_ZH')
hanlp.load('MSRA_NER_ALBERT_BASE_ZH')
hanlp.load('CONLL03_NER_BERT_BASE_UNCASED_EN')
hanlp.load('CHNSENTICORP_BERT_BASE_ZH')
报类似以下的错：
Done loading 197 BERT weights from: C:\Users\****\AppData\Roaming\hanlp\thirdparty\storage.googleapis.com\bert_models\2018_11_03\chinese_L-12_H-768_A-12\bert_model.ckpt into <bert.model.BertModelLayer object at 0x0000020C43D25828> (prefix:bert). Count of weights not found in the checkpoint was: [0]. Count of weights with mismatched shape: [0]
Unused weights from checkpoint:
        bert/pooler/dense/bias
        bert/pooler/dense/kernel
        cls/predictions/output_bias
        cls/predictions/transform/LayerNorm/beta
        cls/predictions/transform/LayerNorm/gamma
        cls/predictions/transform/dense/bias
        cls/predictions/transform/dense/kernel
        cls/seq_relationship/output_bias
        cls/seq_relationship/output_weights

就是报：Unused weights from checkpoint:

******第三:********
hanlp.load('SST2_BERT_BASE_EN')
Failed to load https://file.hankcs.com/hanlp/classification/sst2_bert_base_uncased_en_20200104_175422.zip. See stack trace below
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\hanlp\utils\component_util.py", line 39, in load_from_meta_file
    obj: Component = object_from_class_path(cls, **kwargs)
  File "C:\Python36\lib\site-packages\hanlp\utils\reflection.py", line 24, in object_from_class_path
    class_path = str_to_type(class_path)
  File "C:\Python36\lib\site-packages\hanlp\utils\reflection.py", line 37, in str_to_type
    cls = getattr(importlib.import_module(module_name), class_name)
  File "C:\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'hanlp.components.classifiers.bert_text_classifier'
https://file.hankcs.com/hanlp/classification/sst2_bert_base_uncased_en_20200104_175422.zip was created with hanlp-2.0.0-alpha.5, while you are running 2.0.0-alpha.36. Try to upgrade hanlp with
pip install --upgrade hanlp
If the problem persists, please submit an issue to https://github.com/hankcs/HanLP/issues .

说明：pip install --upgrade hanlp   不能解决问题。

******第四:********
hanlp.load('SST2_ALBERT_BASE_EN')
>>> hanlp.load('SST2_ALBERT_BASE_EN')
Fetching ALBERT model: albert_base version: 2
albert_base.tar.gz: 0.00B [00:00, ?B/s]
Failed to load https://file.hankcs.com/hanlp/classification/sst2_albert_base_20200122_205915.zip. See stack trace below
Traceback (most recent call last):

hanlp.load('EMPATHETIC_DIALOGUES_SITUATION_ALBERT_BASE_EN')
Fetching ALBERT model: albert_base version: 2
albert_base.tar.gz: 0.00B [00:00, ?B/s]
Failed to load https://file.hankcs.com/hanlp/classification/empathetic_dialogues_situation_albert_base_20200122_212250.zip. See stack trace below
Traceback (most recent call last):
  File "C:\Python36\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Python36\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Python36\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Python36\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Python36\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Python36\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\Python36\lib\http\client.py", line 1392, in connect
    super().connect()
  File "C:\Python36\lib\http\client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Python36\lib\socket.py", line 724, in create_connection
    raise err
  File "C:\Python36\lib\socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\hanlp\utils\component_util.py", line 48, in load_from_meta_file
    obj.load(save_dir, **load_kwargs)
  File "C:\Python36\lib\site-packages\hanlp\common\component.py", line 244, in load
    self.build(**merge_dict(self.config, training=False, logger=logger, **kwargs, overwrite=True, inplace=True))
  File "C:\Python36\lib\site-packages\hanlp\common\component.py", line 255, in build
    loss=kwargs.get('loss', None)))
  File "C:\Python36\lib\site-packages\hanlp\components\classifiers\transformer_classifier.py", line 153, in build_model
    tagging=False)
  File "C:\Python36\lib\site-packages\hanlp\layers\transformers\loader.py", line 84, in build_transformer
    transformer))
  File "C:\Python36\lib\site-packages\bert\loader_albert.py", line 179, in fetch_tfhub_albert_model
    fetched_file = pf.utils.fetch_url(fetch_url, fetch_dir=fetch_dir, local_file_name=local_file_name)
  File "C:\Python36\lib\site-packages\params_flow\utils\fetch_unpack.py", line 48, in fetch_url
    urllib.request.urlretrieve(url, local_path, report_hook, data=None)
  File "C:\Python36\lib\urllib\request.py", line 248, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Python36\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python36\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "C:\Python36\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "C:\Python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Python36\lib\urllib\request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Python36\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试 失败。>
https://file.hankcs.com/hanlp/classification/empathetic_dialogues_situation_albert_base_20200122_212250.zip was created with hanlp-2.0.0-alpha.27, while you are running 2.0.0-alpha.36. Try to upgrade hanlp with
pip install --upgrade hanlp
If the problem persists, please submit an issue to https://github.com/hankcs/HanLP/issues .

hanlp.load('EMPATHETIC_DIALOGUES_SITUATION_ALBERT_LARGE_EN')

这几个经检查是https://tfhub.dev 上不去的原因，用代理后解决，在此不得不吐槽一下，国内作程序研究，double hit：
albert_models_tfhub = {
    "albert_base":    "https://tfhub.dev/google/albert_base/{version}?tf-hub-format=compressed",
    "albert_large":   "https://tfhub.dev/google/albert_large/{version}?tf-hub-format=compressed",
    "albert_xlarge":  "https://tfhub.dev/google/albert_xlarge/{version}?tf-hub-format=compressed",
    "albert_xxlarge": "https://tfhub.dev/google/albert_xxlarge/{version}?tf-hub-format=compressed",
}

******第五:********
tokenizer = hanlp.load('SST2_ALBERT_BASE_EN')
>>> tokenizer = hanlp.load('EMPATHETIC_DIALOGUES_SITUATION_ALBERT_LARGE_EN')
Fetching ALBERT model: albert_large version: 2
Already  fetched:  albert_large.tar.gz
already unpacked at: C:\Users\Roottan\AppData\Roaming\hanlp\thirdparty\tfhub.dev\google\albert_large\albert_large
Done loading 23 BERT weights from: C:\Users\****\AppData\Roaming\hanlp\thirdparty\tfhub.dev\google\albert_large\albert_large into <bert.model.BertModelLayer object at 0x000001DCDF95B828> (prefix:albert_2). Count of weights not found in the checkpoint was: [0]. Count of weights with mismatched shape: [0]
Unused weights from saved model:
        bert/pooler/dense/bias
        bert/pooler/dense/kernel
        cls/predictions/output_bias
        cls/predictions/transform/LayerNorm/beta
        cls/predictions/transform/LayerNorm/gamma
        cls/predictions/transform/dense/bias
        cls/predictions/transform/dense/kernel

不知道是个案还是大家会遇到的通病

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
【自动回复】你好，感谢反馈。
由于未按要求填写，本issue被暂时标记为无效。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真修改，然后耐心等待下周末处理。
咨询类的问题应该发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
![issue](http://wx1.sinaimg.cn/large/006Fmjmcly1ft2hnlwc22j30q90bcgpe.jpg)

**Comment by hankcs** [comment]
感谢反馈，已经修复。

1. ```
   FileNotFoundError: The identifier C:\Users\Roottan\AppData\Roaming\hanlp\hanlp\lm\flair_lm_wmt11_en_20191229_033714\flair_lm_bw_wmt11_en resolves to a non-exist meta file C:\Users**\AppData\Roaming\hanlp\hanlp\lm\flair_lm_wmt11_en_20191229_033714\flair_lm_bw_wmt11_en\meta.json.
   ```

   应该是下载失败了，尝试删除`flair_lm_wmt11_en_20191229_033714`目录后重试。

2. `Unused weights from checkpoint:`不是错误，是第三方库`bert-tf2`的日志。

3. 刚修复了这个问题。

4. 试试国内镜像：https://od.hankcs.com/hanlp/datav2/

5. 同2

**Comment by Roottan** [comment]
十分感谢解决和回复，今天重试了一下，确实发生了变化。以前的几个问题也解决大部分。这还有几个问题。
我是先用pip3 install --upgrade hanlp 更新再load 的。
****第一
tokenizer = hanlp.load('PTB_POS_RNN_FASTTEXT_EN')
tokenizer = hanlp.load('CTB5_FASTTEXT_300_CN')
tokenizer = hanlp.load('CTB5_BIAFlFINE_DEP_ZH')
下载后，下次load还要再下载（目录中相应在文件已存在。但还会提示新下载）。

另外发现：
    tokenizer = hanlp.load('CTB5_BIAFFINE_DEP_ZH')
         https://file.hankcs.com/hanlp/embeddings/ctb.fasttext.300.txt.zip 
    tokenizer = hanlp.load('CTB5_FASTTEXT_300_CN')
         https://file.hankcs.com/hanlp/embeddings/ctb.fasttext.300.txt.zip
这两者的url是一样，不知道是否正确？

****第二
tokenizer = hanlp.load('SEMEVAL16_EMBEDDINGS_300_NEWS_CN')
tokenizer = hanlp.load('SEMEVAL16_EMBEDDINGS_300_TEXT_CN')
tokenizer = hanlp.load('GLOVE_6B_ROOT')
tokenizer = hanlp.load('GLOVE_6B_50D')
tokenizer = hanlp.load('GLOVE_6B_100D')
tokenizer = hanlp.load('GLOVE_6B_200D')
tokenizer = hanlp.load('GLOVE_6B_300D')
tokenizer = hanlp.load('GLOVE_840B_300D')
tokenizer = hanlp.load('FLAIR_LM_FW_WMT11_EN')
tokenizer = hanlp.load('FLAIR_LM_BW_WMT11_EN')
tokenizer = hanlp.load('CONVSEG_W2V_NEWS_TENSITE')
tokenizer = hanlp.load('CONVSEG_W2V_NEWS_TENSITE_WORD_PKU')
tokenizer = hanlp.load('CONVSEG_W2V_NEWS_TENSITE_WORD_MSR')
tokenizer = hanlp.load('CONVSEG_W2V_NEWS_TENSITE_CHAR')
tokenizer = hanlp.load('SEMEVAL16_EMBEDDINGS_CN')
tokenizer = hanlp.load('TENCENT_AI_LAB_EMBEDDING')
tokenizer = hanlp.load('RADICAL_CHAR_EMBEDDING_100')

这些load还是会报：找不到：meta.json
具体例如：
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36\lib\site-packages\hanlp\__init__.py", line 51, in load
    return load_from_meta_file(save_dir, meta_filename, transform_only=transform_only, load_kwargs=load_kwargs, **kwargs)
  File "C:\Python36\lib\site-packages\hanlp\utils\component_util.py", line 34, in load_from_meta_file
    raise FileNotFoundError(f'The identifier {save_dir} resolves to a non-exist meta file {metapath}. {tips}')
FileNotFoundError: The identifier C:\Users\****\AppData\Roaming\hanlp\thirdparty\downloads.cs.stanford.edu\nlp\data\glove.6B resolves to a non-exist meta file C:\Users\****\AppData\Roaming\hanlp\thirdparty\downloads.cs.stanford.edu\nlp\data\glove.6B\meta.json.
>>> tokenizer = hanlp.load('GLOVE_6B_50D')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36\lib\site-packages\hanlp\__init__.py", line 51, in load
    return load_from_meta_file(save_dir, meta_filename, transform_only=transform_only, load_kwargs=load_kwargs, **kwargs)
  File "C:\Python36\lib\site-packages\hanlp\utils\component_util.py", line 34, in load_from_meta_file
    raise FileNotFoundError(f'The identifier {save_dir} resolves to a non-exist meta file {metapath}. {tips}')
FileNotFoundError: The identifier C:\Users\****\AppData\Roaming\hanlp\thirdparty\downloads.cs.stanford.edu\nlp\data\glove.6B\glove.6B.50d.txt resolves to a non-exist meta file C:\Users\****\AppData\Roaming\hanlp\thirdparty\downloads.cs.stanford.edu\nlp\data\glove.6B\glove.6B.50d.txt\meta.json.
>>> tokenizer = hanlp.load('GLOVE_6B_100D')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36\lib\site-packages\hanlp\__init__.py", line 51, in load
    return load_from_meta_file(save_dir, meta_filename, transform_only=transform_only, load_kwargs=load_kwargs, **kwargs)
  File "C:\Python36\lib\site-packages\hanlp\utils\component_util.py", line 34, in load_from_meta_file
    raise FileNotFoundError(f'The identifier {save_dir} resolves to a non-exist meta file {metapath}. {tips}')
FileNotFoundError: The identifier C:\Users\****\AppData\Roaming\hanlp\thirdparty\downloads.cs.stanford.edu\nlp\data\glove.6B\glove.6B.100d.txt resolves to a non-exist meta file C:\Users\****\AppData\Roaming\hanlp\thirdparty\downloads.cs.stanford.edu\nlp\data\glove.6B\glove.6B.100d.txt\meta.json.
>>> tokenizer = hanlp.load('GLOVE_6B_200D')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36\lib\site-packages\hanlp\__init__.py", line 51, in load
    return load_from_meta_file(save_dir, meta_filename, transform_only=transform_only, load_kwargs=load_kwargs, **kwargs)
  File "C:\Python36\lib\site-packages\hanlp\utils\component_util.py", line 34, in load_from_meta_file
    raise FileNotFoundError(f'The identifier {save_dir} resolves to a non-exist meta file {metapath}. {tips}')
FileNotFoundError: The identifier C:\Users\****\AppData\Roaming\hanlp\thirdparty\downloads.cs.stanford.edu\nlp\data\glove.6B\glove.6B.200d.txt resolves to a non-exist meta file C:\Users\****\AppData\Roaming\hanlp\thirdparty\downloads.cs.stanford.edu\nlp\data\glove.6B\glove.6B.200d.txt\meta.json.

。。。。。。
说明：应该与下载没关系，我用不同的下载的方式下载文件再存入目录仍然存在这些报错的提示。

**Comment by hankcs** [comment]
1. 两个模型地址不一样，递归下载部分相同文件。
2. `FLAIR_LM_FW_WMT11_EN `已修复。glove是第三方模型，不能用hanlp.load加载。

**Comment by qixiang109** [comment]
我也遇到同样的问题，无论已执行了多少遍 

```python
hanlp.load(CTB5_BIAFFINE_DEP_ZH)
```
都会重新下载，而不是使用缓存

```sh
Downloading https://file.hankcs.com/hanlp/embeddings/ctb.fasttext.300.txt.zip
```

只有CTB5_BIAFFINE_DEP_ZH这个模型有问题

> ****第一
> tokenizer = hanlp.load('PTB_POS_RNN_FASTTEXT_EN')
> tokenizer = hanlp.load('CTB5_FASTTEXT_300_CN')
> tokenizer = hanlp.load('CTB5_BIAFlFINE_DEP_ZH')
> 下载后，下次load还要再下载（目录中相应在文件已存在。但还会提示新下载）。

**Comment by hankcs** [comment]
> 我也遇到同样的问题，无论已执行了多少遍
> 
> ```python
> hanlp.load(CTB5_BIAFFINE_DEP_ZH)
> ```
> 
> 都会重新下载，而不是使用缓存
> 
> ```shell
> Downloading https://file.hankcs.com/hanlp/embeddings/ctb.fasttext.300.txt.zip
> ```
> 
> 只有CTB5_BIAFFINE_DEP_ZH这个模型有问题
> 
> > ****第一
> > tokenizer = hanlp.load('PTB_POS_RNN_FASTTEXT_EN')
> > tokenizer = hanlp.load('CTB5_FASTTEXT_300_CN')
> > tokenizer = hanlp.load('CTB5_BIAFlFINE_DEP_ZH')
> > 下载后，下次load还要再下载（目录中相应在文件已存在。但还会提示新下载）。

感谢反馈，已经修复。

**Comment by KangChou** [comment]
我想知道这个文件ctb.fasttext.300.txt是干什么用的？
@hankcs

**Comment by TNightmare** [comment]
CTB6_CONVSEG，这个也有这个问题


> > 我也遇到同样的问题，无论已执行了多少遍
> > ```python
> > hanlp.load(CTB5_BIAFFINE_DEP_ZH)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 都会重新下载，而不是使用缓存
> > ```shell
> > Downloading https://file.hankcs.com/hanlp/embeddings/ctb.fasttext.300.txt.zip
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 只有CTB5_BIAFFINE_DEP_ZH这个模型有问题
> > > ****第一
> > > tokenizer = hanlp.load('PTB_POS_RNN_FASTTEXT_EN')
> > > tokenizer = hanlp.load('CTB5_FASTTEXT_300_CN')
> > > tokenizer = hanlp.load('CTB5_BIAFlFINE_DEP_ZH')
> > > 下载后，下次load还要再下载（目录中相应在文件已存在。但还会提示新下载）。
> 
> 感谢反馈，已经修复。

这个模型CTB6_CONVSEG也是有这种问题

**Comment by TNightmare** [comment]
> CTB6_CONVSEG，这个也有这个问题
> 
> > > 我也遇到同样的问题，无论已执行了多少遍
> > > ```python
> > > hanlp.load(CTB5_BIAFFINE_DEP_ZH)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 都会重新下载，而不是使用缓存
> > > ```shell
> > > Downloading https://file.hankcs.com/hanlp/embeddings/ctb.fasttext.300.txt.zip
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 只有CTB5_BIAFFINE_DEP_ZH这个模型有问题
> > > > ****第一
> > > > tokenizer = hanlp.load('PTB_POS_RNN_FASTTEXT_EN')
> > > > tokenizer = hanlp.load('CTB5_FASTTEXT_300_CN')
> > > > tokenizer = hanlp.load('CTB5_BIAFlFINE_DEP_ZH')
> > > > 下载后，下次load还要再下载（目录中相应在文件已存在。但还会提示新下载）。
> > 
> > 
> > 感谢反馈，已经修复。
> 
> 这个模型CTB6_CONVSEG也是有这种问题

下载成功并且解压后，还是会Failed to load https://file.hankcs.com/hanlp/tok/ctb6_convseg_nowe_nocrf_20200110_004046.zip
