### ISSUE TITLE
地名识别模型的一点理解和困惑

### ISSUE THREAD

**Issue by starkingpku** [hankcs/HanLP#142]
输入：“蓝翔给宁夏固原市彭阳县红河镇黑牛沟村捐赠了挖掘机”
输出：[蓝翔/nr, 给/p, 宁夏/ns, 固原市/ns, 彭阳县/ns, 红/a, 河镇/ns, 黑牛沟村/ns, 捐赠/v, 了/ule, 挖掘机/n]
其中，【红河镇】识别错误。

探其原因，首先在粗分阶段，结果如下：
[蓝/a, 翔/vg, 给/p, 宁夏/ns, 固原市/ns, 彭/nz, 阳/ag, 县/n, 红/a, 河镇/ns, 黑/a, 牛/n, 沟/n, 村/n, 捐赠/v, 了/ule, 挖掘机/n]
然后，地名角色观察阶段：
[  S 1139590 A 23975 ][蓝 C 29 B 1 D 1 ][翔 C 50 D 10 A 5 ][给 A 453 B 79 X 6 ][宁夏 Z 41339414 ][固原市 Z 41339414 ][彭 C 85 ][阳 D 1255 C 81 B 1 ][县 H 6878 B 25 A 23 D 19 X 3 ][红 C 1000 B 46 A 3 ][河镇 Z 41339414 ][黑 C 960 B 25 ][牛 D 24 C 8 B 7 ][沟 H 107 D 90 E 36 C 27 B 14 A 3 ][村 H 4467 D 68 B 28 A 8 C 3 ][捐赠 B 10 A 1 ][了 A 4115 B 97 ][挖掘机 B 1 ][  B 1322 ]
最后，地名角色标注阶段：
[ /A ,蓝/C ,翔/D ,给/B ,宁夏/Z ,固原市/Z ,彭/C ,阳/D ,县/H ,红/B ,河镇/Z ,黑/C ,牛/D ,沟/E ,村/H ,捐赠/B ,了/A ,挖掘机/B , /A]

由于粗分后，"红河镇"被分为了"红/河镇"，而不是"红/河/镇"，那么在地名角色观察阶段，词“河镇”就没法用地名角色简表中的角色标记，“河”应该是D(中国地名第二个字)，"镇"应该是H(中国地名的后缀)，"河镇"应该是DH吧？即地名的尾部与后缀成词的现象，是不是要单独在设定一个新的角色标记？由于地名识别是在句子粗分词的基础上做的，所以地名识别的输入存在单词的情况是在所难免的，想必也会出现诸如“中国地名第一个字与第二个字成词”的情况，现有的地名角色简表也无法涵盖。

如果我理解错了，即"河镇"不是DH，那又是什么呢？我参看了 @hankcs 的blog关于地名识别的文章，其中地名角色观察阶段的“河镇”的角色是[H 1000]，不仅如此，"宁夏"、"固原市"的角色也是[H 1000]，我猜测作者可能是笔误，在HanLP代码中H代表中国地名后缀，而G代表整个地址，我猜测作者在blog上的意思是“河镇”、“宁夏”、“固原市”的观察角色都是真个地址，即G。如果是这样，那么为什么在我跑的程序中，“河镇”、“宁夏”、“固原市”的观察角色都是Z呢？作者是不是在地名辞典ns.txt中不加入“河镇”、“宁夏”、“固原市”作为地名的角色，而是只靠在核心词典中将这些常用地名识别出来，是这样的意图吗？

**Comment by hankcs** [comment]
在HanLP这样面向生产环境而不是论文试验的系统中，这些dirty的现象都会有处理，但未必能完全处理掉。
整个地名的确被设计为当做“后缀”或“前缀”来用。

            if (Nature.ns == vertex.getNature() && vertex.getAttribute().totalFrequency <= 1000)
            {
                if (vertex.realWord.length() < 3)               // 二字地名，认为其可以再接一个后缀或前缀
                    tagList.add(new EnumItem<NS>(NS.H, NS.G));
                else
                    tagList.add(new EnumItem<NS>(NS.G));        // 否则只可以再加后缀
                continue;
            }

最初设计的时候完全按照论文来，后来又根据开放语言环境做了调整，你的意见也是其中一环。
系统复杂度高了，在后面的调整中有时候会影响前面的算法，现在已经改回来了。
