### ISSUE TITLE
module 'hanlp' has no attribute 'load'

### ISSUE THREAD

**Issue by zxy1991** [hankcs/HanLP#1420]
**Describe the bug**
AttributeError: module 'hanlp' has no attribute 'load'

**System information**
- OS Platform and Distribution (e.g., Centos7):
- Python version:3.7
- HanLP version:2.0

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form.

**Comment by hankcs** [comment]
Could you provide essential information? Thanks.

**Comment by zxy1991** [comment]
code:
import hanlp
tokenizer = hanlp.load('PKU_NAME_MERGED_SIX_MONTHS_CONVSEG')

result:
  File "E:\py\hanlp.py", line 3, in <module>
    tokenizer = hanlp.load('PKU_NAME_MERGED_SIX_MONTHS_CONVSEG')
AttributeError: module 'hanlp' has no attribute 'load'

**Comment by hankcs** [comment]
No, you should never name your code hanlp.py, which conflicts with hanlp.
