### ISSUE TITLE
HanLP2.x支持多进程有问题

### ISSUE THREAD

**Issue by MingxuanLiu** [hankcs/HanLP#1424]
**Describe the bug**
在使用多进程执行HanLP2.x的时候会出现进程错乱的问题。

**Code to reproduce the issue**
recognizer = hanlp.load(hanlp.pretrained.ner.MSRA_NER_BERT_BASE_ZH)
    tokenizer = hanlp.load('PKU_NAME_MERGED_SIX_MONTHS_CONVSEG')
    tagger = hanlp.load(hanlp.pretrained.pos.CTB5_POS_RNN_FASTTEXT_ZH)
    syntactic_parser = hanlp.load(hanlp.pretrained.dep.CTB7_BIAFFINE_DEP_ZH)
    semantic_parser = hanlp.load(hanlp.pretrained.sdp.SEMEVAL16_TEXT_BIAFFINE_ZH)

    pipeline = hanlp.pipeline() \
    .append(hanlp.utils.rules.split_sentence, output_key='sentences') \
    .append(tokenizer, output_key='tokens') \
    .append(tagger, output_key='part_of_speech_tags') \
    .append(syntactic_parser, input_key=('tokens', 'part_of_speech_tags'), output_key='syntactic_dependencies') #\
    .append(semantic_parser, input_key=('tokens', 'part_of_speech_tags'), output_key='semantic_dependencies')

    pool = multiprocessing.Pool(processes=20)
    for filename in os.listdir(split_path):
        f_path = os.path.join(split_path, filename)
        num = int(f_path.split('_')[-1])
        print("Process:" + str(num))
        print(os.popen("wc -l " + f_path).read().split(' ')[0])
        # pool.apply_async(test, (num, ))
        try:
            # print('nani')
            pool.apply_async(multi_process, (num, f_path, result_path, plate,))
        except Exception as e:
            print(e)

```python
```

**Describe the current behavior**
执行几个句子就会终止

**Expected behavior**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version:
- HanLP version:

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [ ] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
【自动回复】你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真修改，然后耐心等待下周末处理。
咨询类的问题应该发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
![issue](http://wx1.sinaimg.cn/large/006Fmjmcly1ft2hnlwc22j30q90bcgpe.jpg)
