### ISSUE TITLE
调用CharTabel，把“幺”改为“么”不合理

### ISSUE THREAD

**Issue by tiandiweizun** [hankcs/HanLP#1427]
**Describe the bug**

调用CharTabel，把“幺”改为“么”不合理，虽然 么 也有1的意思，且也有发音为yao的，但是么通常不代表幺的意思，且幺字已经是正则化的，没有必要进一步改变，需要去掉CharTable.txt里面幺=么

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
 System.out.println(CharTable.convert("幺妹的手机号码是幺三二开头的"));
```

**Describe the current behavior**
A clear and concise description of what happened.

么妹的手机号码是么三二开头的

**Expected behavior**

幺妹的手机号码是幺三二开头的

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): win10
- Python version: java
- HanLP version: 1.7.6

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。
