### ISSUE TITLE
hanlp在linux下进行新词发现和Windows进行新词发现的个数不一样！

### ISSUE THREAD

**Issue by caseware66** [hankcs/HanLP#1429]
startJVM(getDefaultJVMPath(), "-Djava.class.path=C:/Users/chenxi/PycharmProjects/HanLp/hanlp-1.7.6.jar;C:/Users/chenxi/PycharmProjects/HanLp")
    newword=JClass("com.hankcs.hanlp.mining.word.NewWordDiscover")
    content='七彩西昌｜乌桕树,我们明年再见！风景如画的邛泸景区，轻轻松松随手一拍，便是大师级的作品。乌桕树的一身红衣，已随寒风渐渐褪去。留下乳白色坚硬的果实，倒影在波光粼粼的湖面上。那一粒粒果实，像极了天上的点点繁星，不小心落入人世繁华。我喜欢你，鲜红似火的树叶，也喜欢你，犹如繁星点点的果实。你的一颦一笑，早已深深刻在我的心里。综合整理五彩凉山智慧旅游公共服务平台更多精彩文章请看这里！我心归处是凉山从A到Z，爱上螺髻山的26个理由吴小莉下了飞机，好像来错地方！镶嵌在凉山群山之间的湖泊，给你最纯净的温柔西马倒计时14天这才是正确打开西马的方式最美秋景秋日里的泸沽湖，真的美哭我了！5年后，凉山文旅产业如何蝶变旅游创建首批“大凉山优秀旅游特色小镇”评选之布拖县乐安乡旅游创建首批“大凉山优秀旅游特色小镇”评选之普格县荞窝镇旅游创建首批“大凉山优秀旅游特色小镇”评选之宁南县幸福镇期待您是下一个！'
    newword = newword(4, 0.00005, 0.5, 100, True)
    newword=newword.discover(content,10)
    print(newword)

在Windows下新词发现的个数为零个，在linux下发现的是[西马, 乌桕树]

**Comment by hankcs** [comment]
【自动回复】你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真修改，然后耐心等待下周末处理。
咨询类的问题应该发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
![issue](http://wx1.sinaimg.cn/large/006Fmjmcly1ft2hnlwc22j30q90bcgpe.jpg)
