### ISSUE TITLE
人名识别角色标注的问题

### ISSUE THREAD

**Issue by starkingpku** [hankcs/HanLP#143]
输入：区长庄木弟新年致辞
粗分结果[区长/nnt, 庄/ag, 木/ng, 弟/n, 新年/t, 致辞/vi]
人名角色观察：[  A 42634591 ][区长 G 1 K 1 ][庄 B 263 E 53 D 40 C 13 L 9 K 1 ][木 B 106 C 85 D 39 E 15 L 13 K 2 ][弟 D 60 E 11 K 10 C 2 ][新年 L 47 K 2 Z 1 ][致辞 L 13 ][  A 42634591 ]
人名角色标注：[ /A ,区长/K ,庄/B ,木/C ,弟/D ,新年/L ,致辞/L , /A]
识别出人名：庄木 BC
识别出人名：庄木弟 BCD

问题：
1.既然识别出正确人名庄木弟(BCD)，为何还要识别出庄木(BC)呢？直接选庄木弟(BCD)作为人名识别结果不可以吗？
2. 人名识别中，角色A表示其他角色。在语料中，词汇“新年”、"致辞"等应该都有可能存在A角色情况吧，怎么在角色观察中都没有A及其出现频次呢？作者是怎么生成词汇的角色&词频词典的？感觉有关A的数据都删除了吧？

**Comment by hankcs** [comment]
0. 统计模型中没有什么一定，都有可能，看谁的概率高了
0. 对，放进去浪费资源

**Comment by starkingpku** [comment]
怎么会浪费资源呢？主要是为了算法准确率而删除其他角色A的统计信息？比如，上面例子中，可能语料中"庄", "木", "弟"这三字都有可能有角色A的统计频数，那么算法纳入A后最后识别结果有可能是庄/A 木/A 第/A。于是降低了准确率。

**Comment by hankcs** [comment]
因为所有的A加起来几乎就是汉语词表的大小，而我只关注这个词在人名中扮演什么角色。由于训练集不大，只有一年的人民日报，如果把A放进去，我认为召回率不高，毕竟"木", "弟"还是很生僻的名字。另一方面，倾向于把零散的字符组合起来，也是许多分词算法常见的目标。

**Comment by leefionglee** [comment]
新手请教一下， 这上面的A B C D H这些字母分别代表什么意思，还有 新年/L ,致辞/L？   这里的L这些代表什么？

如果我想增加人名，是不是直接在地名的文件中添加就可以了？

**Comment by hankcs** [comment]
http://www.hankcs.com/nlp/chinese-name-recognition-in-actual-hmm-viterbi-role-labeling.html
