### ISSUE TITLE
HanLP 有官方的dockers部署吗？

### ISSUE THREAD

**Issue by jtyoui** [hankcs/HanLP#1433]
请问：官方有HanLP 的dockers部署吗？直接能调restful接口的那种。

**Comment by hankcs** [comment]
【自动回复】你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://raw.githubusercontent.com/hankcs/HanLP/master/.github/ISSUE_TEMPLATE/bug_report.md)认真修改，然后耐心等待下周末处理。
提问前先Google，建议您读一读[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md#%E7%AE%80%E4%BB%8B)。感谢您宝贵的时间，您没有在注意事项上打勾，可能浪费了彼此的时间。您提的问题可能已经在文档或issue区回答过了，也许您应该首先[RTFM](https://baike.baidu.com/item/RTFM/3961783)，或者[UTFSE](https://www.urbandictionary.com/define.php?term=utfse)。
![rtfmtractor](https://user-images.githubusercontent.com/5326890/70371066-200e6300-189c-11ea-9e36-3a766a0630a3.jpg)
如果您认为是bug，那么请您按模板认真改一改，reopen这个issue。否则，咨询类的问题应该好好改一改，写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。
如果您不修改的话，恐怕没有人能够回复您，我们也会错失一次改进的机会或者一次友好的讨论。开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
![issue](http://wx1.sinaimg.cn/large/006Fmjmcly1ft2hnlwc22j30q90bcgpe.jpg)
