### ISSUE TITLE
batch为32时报错，其他数字不报错

### ISSUE THREAD

**Issue by heibaicai** [hankcs/HanLP#1434]
**Describe the bug**
用的是python,cpu跑的代码,用hanlp.pipeline()进行分析，输入batch为32时报错，其他数字不报错

下面是报出的错误信息：

UnknownError                              Traceback (most recent call last)
<ipython-input-88-3f7e6c8a5769> in <module>
      9 for i in tqdm(rand_loader):
     10     print(i)
---> 11     doc = pipeline(i)
     12     #print(doc)
     13 end=time.time()

D:\Anaconda3\envs\pytorch\lib\site-packages\hanlp\components\pipeline.py in __call__(self, doc, **kwargs)
     95     def __call__(self, doc: Document, **kwargs) -> Document:
     96         for component in self:
---> 97             doc = component(doc)
     98         return doc
     99 

D:\Anaconda3\envs\pytorch\lib\site-packages\hanlp\common\component.py in __call__(self, data, **kwargs)
     49 
     50     def __call__(self, data, **kwargs):
---> 51         return self.predict(data, **kwargs)
     52 
     53     @staticmethod

D:\Anaconda3\envs\pytorch\lib\site-packages\hanlp\components\pipeline.py in predict(self, doc, **kwargs)
     48         if unpack:
     49             kwargs['_hanlp_unpack'] = True
---> 50         output = self.component(input, **kwargs)
     51         if isinstance(output, types.GeneratorType):
     52             output = list(output)

D:\Anaconda3\envs\pytorch\lib\site-packages\hanlp\common\component.py in __call__(self, data, **kwargs)
     49 
     50     def __call__(self, data, **kwargs):
---> 51         return self.predict(data, **kwargs)
     52 
     53     @staticmethod

D:\Anaconda3\envs\pytorch\lib\site-packages\hanlp\common\component.py in predict(self, data, batch_size, **kwargs)
    453         num_samples = 0
    454         data_is_list = isinstance(data, list)
--> 455         for idx, batch in enumerate(dataset):
    456             samples_in_batch = tf.shape(batch[-1] if isinstance(batch[-1], tf.Tensor) else batch[-1][0])[0]
    457             if data_is_list:

D:\Anaconda3\envs\pytorch\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py in __next__(self)
    628 
    629   def __next__(self):  # For Python 3 compatibility
--> 630     return self.next()
    631 
    632   def _next_internal(self):

D:\Anaconda3\envs\pytorch\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py in next(self)
    672     """Returns a nested structure of `Tensor`s containing the next element."""
    673     try:
--> 674       return self._next_internal()
    675     except errors.OutOfRangeError:
    676       raise StopIteration

D:\Anaconda3\envs\pytorch\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py in _next_internal(self)
    663         return self._element_spec._from_compatible_tensor_list(ret)  # pylint: disable=protected-access
    664       except AttributeError:
--> 665         return structure.from_compatible_tensor_list(self._element_spec, ret)
    666 
    667   @property

D:\Anaconda3\envs\pytorch\lib\contextlib.py in __exit__(self, type, value, traceback)
    128                 value = type()
    129             try:
--> 130                 self.gen.throw(type, value, traceback)
    131             except StopIteration as exc:
    132                 # Suppress StopIteration *unless* it's the same exception that

D:\Anaconda3\envs\pytorch\lib\site-packages\tensorflow_core\python\eager\context.py in execution_mode(mode)
   1898   finally:
   1899     ctx.executor = executor_old
-> 1900     executor_new.wait()
   1901 
   1902 

D:\Anaconda3\envs\pytorch\lib\site-packages\tensorflow_core\python\eager\executor.py in wait(self)
     65   def wait(self):
     66     """Waits for ops dispatched in this executor to finish."""
---> 67     pywrap_tensorflow.TFE_ExecutorWaitForAllPendingNodes(self._handle)
     68 
     69   def clear_error(self):

UnknownError: AssertionError: unable to assign 22 datapoints to 32 clusters
Traceback (most recent call last):

  File "D:\Anaconda3\envs\pytorch\lib\site-packages\tensorflow_core\python\ops\script_ops.py", line 236, in __call__
    ret = func(*args)

  File "D:\Anaconda3\envs\pytorch\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py", line 789, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "D:\Anaconda3\envs\pytorch\lib\site-packages\hanlp\components\parsers\conll.py", line 239, in generator
    buckets = dict(zip(*kmeans(lengths, n_buckets)))

  File "D:\Anaconda3\envs\pytorch\lib\site-packages\hanlp\components\parsers\alg.py", line 52, in kmeans
    assert len(d) >= k, f"unable to assign {len(d)} datapoints to {k} clusters"

AssertionError: unable to assign 22 datapoints to 32 clusters

	 [[{{node PyFunc}}]]

**Comment by hankcs** [comment]
【自动回复】你好，感谢反馈。
由于未按要求填写，本issue被暂时标记为无效。请按[issue模板](https://raw.githubusercontent.com/hankcs/HanLP/master/.github/ISSUE_TEMPLATE/bug_report.md)认真修改，然后耐心等待下周末处理。
如果您提的是bug或feature request，那么请您按模板认真改一改，reopen这个issue。否则，咨询类的问题应该好好改一改，写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。
如果您不修改的话，恐怕没有人能够回复您，我们也会错失一次改进的机会或者一次友好的讨论。开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。
