### ISSUE TITLE
hanlp 2.0 python版本耗时很长

### ISSUE THREAD

**Issue by shaohualuan** [hankcs/HanLP#1436]
**Describe the bug**
hanlp 2.0 python版本基础分词器与命名实体识别等接口耗时超长

**Code to reproduce the issue**
 

```   recognizer = hanlp.load(hanlp.pretrained.ner.MSRA_NER_BERT_BASE_ZH)
    print(recognizer([
                      list('胡智研发效率工程部等等美国新华社日报cisco')]))
```

**Describe the current behavior**
基础分词器测试分词耗时大概要180ms左右
命名实体识别耗时大概要600ms左右

**Expected behavior**
基础分词器测试分词耗时大概要10ms左右
命名实体识别耗时大概要100ms以内

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version: 3.6
- HanLP version: 2.0

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [ ] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
【自动回复】你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://raw.githubusercontent.com/hankcs/HanLP/master/.github/ISSUE_TEMPLATE/bug_report.md)认真修改，然后耐心等待下周末处理。
如果您提的是bug或feature request，那么请您按模板认真改一改，reopen这个issue。否则，咨询类的问题应该好好改一改，写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。
如果您不修改的话，恐怕没有人能够回复您，我们也会错失一次改进的机会或者一次友好的讨论。开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
