### ISSUE TITLE
高手，问下词典自定义并怎么制作 ？

### ISSUE THREAD

**Issue by gyz-GitHub** [hankcs/HanLP#144]

**Comment by gyz-GitHub** [comment]
类似于用户通过导入一些txt文章，训练成语料，然后用语料生成词典，在将词典替换hanlp原生词典。中间的训练成语料和生成词典怎么弄呀...

**Comment by hankcs** [comment]
https://github.com/hankcs/HanLP/wiki/%E8%AE%AD%E7%BB%83%E5%88%86%E8%AF%8D%E6%A8%A1%E5%9E%8B

**Comment by gyz-GitHub** [comment]
打扰一下，这个“训练分词模型”是基于已经有的语料的，有没有直接将文本字符串转换成语料(通过hanlp基本的分词能过转换成二次语料)的接口或工具？
目前需要将用户的文本训练成语料，在将语料加载到hanlp，然后做分词、关键字、摘要功能。

**Comment by hankcs** [comment]
是基于已经有的语料的

直接将文本字符串转换成语料(通过hanlp基本的分词能过转换成二次语料)的接口或工具没有意义。
