### ISSUE TITLE
pyhanlp 与  java上的hanlp分词结果不一致？ 请问是什么原因？  

### ISSUE THREAD

**Issue by pyshltcyh** [hankcs/HanLP#1440]
**Describe the bug**

我用Python下载了pyhanlp, version update 到了1.7.7，同样，在java maven project我用了hanlp-portable-1.7.7, 但是我发现分词结果竟然不一致。
请问有什么解决方法吗？ 还是我用的方法不对？

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
test case: “内河运输”
pyhanlp中Hanlp.segment结果：“内河运输”
Java中Hanlp.segment结果：“内河 运输
```python
```

**Describe the current behavior**
A clear and concise description of what happened.

**Expected behavior**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version:
- HanLP version:

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [ ] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
【自动回复】你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://raw.githubusercontent.com/hankcs/HanLP/master/.github/ISSUE_TEMPLATE/bug_report.md)认真修改，然后耐心等待下周末处理。
如果您提的是bug或feature request，那么请您按模板认真改一改，reopen这个issue。否则，咨询类的问题应该好好改一改，写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。
如果您不修改的话，恐怕没有人能够回复您，我们也会错失一次改进的机会或者一次友好的讨论。开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。

**Comment by 991697456** [comment]
son of bitch
