### ISSUE TITLE
Pyhanlp与java Hanlp分词结果不一致

### ISSUE THREAD

**Issue by pyshltcyh** [hankcs/HanLP#1441]
**Describe the bug**
我用Python下载了pyhanlp, version update 到了1.7.7，同样，在java maven project我用了hanlp-portable-1.7.7, 但是我发现分词结果竟然不一致。
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
test case: “内河运输”
```python
```
Hanlp.segment(“内河运输”)

**Describe the current behavior**
A clear and concise description of what happened.
pyhanlp中Hanlp.segment结果：“内河运输”
Java中Hanlp.segment结果：“内河 运输”
**Expected behavior**
pyhanlp与java中Hanlp.segment结果应该一致才对。
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Centos 7.4
- Python version:3.6.2
- HanLP version:1.7.7

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
non
* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
https://github.com/hankcs/HanLP/issues/1294
