### ISSUE TITLE
hanlp+jupyter的docker镜像

### ISSUE THREAD

**Issue by WalterInSH** [hankcs/HanLP#1449]
**Describe the feature and the current behavior/state.**
目前官方文档里没有提供更快上手HanLP 的方式，所以我做了一个HanLP + Jupyter 的Docker镜像，可以帮助感兴趣的人更快上手体验。
walterinsh/hanlp:2.0.0a41-jupyter

[https://github.com/WalterInSH/hanlp-jupyter-docker](https://github.com/WalterInSH/hanlp-jupyter-docker)

如果满足你们的期望，可以加在文档里。

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
会使用docker，期望快速尝试的人

**Are you willing to contribute it (Yes/No):**
yes

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Debian
- Python version: 3.6
- HanLP version: 2.0.0a41

**Any other info**

* [x] I've carefully completed this form.

**Comment by hankcs** [comment]
感谢支持，已经加入首页文档。
