### ISSUE TITLE
三个人总是被错误区分为”三“”个人”

### ISSUE THREAD

**Issue by huchhong** [hankcs/HanLP#145]
句子里只要有“三个人”这样的词，总是会错误划分为“三”，“个人”。

我看CoreNatureDictionary里“个人”的词频很高，试着把它的词频降到１，发现也没有作用。只有把“个人”这个词条删除才能正确分词。可是“个人”确实是可以作为词出现，像这样的问题有办法解决吗？

我试了哈工大的语言云demo，发现是可以区分这两种情况的。

**Comment by hankcs** [comment]
感谢反馈，已经做了改进：

[我/rr, 个人/n, 认为/v, 三/m, 个/q, 人/n, 的/ude1, 力量/n, 大于/v, 1/m, 个/q, 人/n, ，/w, 所以/c, 个人/n, 应该/v, 服从/v, 集体/n]
