### ISSUE TITLE
默认下载tensorflow的CPU版本

### ISSUE THREAD

**Issue by possible1402** [hankcs/HanLP#1450]
`pip install hanlp`
会下载tensorflow的cpu版，即使我已经安装好tensorflow-gpu 2.1.0
请问怎样能调用GPU呢？

**Comment by hankcs** [comment]
【自动回复】你好，感谢反馈。
由于未按要求填写，本issue被暂时标记为无效。请按[issue模板](https://raw.githubusercontent.com/hankcs/HanLP/master/.github/ISSUE_TEMPLATE/bug_report.md)认真修改，然后耐心等待下周末处理。
如果您提的是bug或feature request，那么请您按模板认真改一改，reopen这个issue。否则，咨询类的问题应该好好改一改，写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。
如果您不修改的话，恐怕没有人能够回复您，我们也会错失一次改进的机会或者一次友好的讨论。开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
