### ISSUE TITLE
高并发情况下，调用词法分析，句法依赖接口，耗时较长

### ISSUE THREAD

**Issue by zy158** [hankcs/HanLP#1451]
您好，我在使用1.X版的hanlp的java接口时，高并发（每秒150请求）调用词法分析和句法依赖接口，耗时很长，但cpu利用率和内存没有明显增加，请问是怎么回事？是该功能不支持高并发场景吗？

**Comment by hankcs** [comment]
【自动回复】你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://raw.githubusercontent.com/hankcs/HanLP/master/.github/ISSUE_TEMPLATE/bug_report.md)认真修改，然后耐心等待下周末处理。
如果您提的是bug或feature request，那么请您按模板认真改一改，reopen这个issue。否则，咨询类的问题应该好好改一改，写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。
如果您不修改的话，恐怕没有人能够回复您，我们也会错失一次改进的机会或者一次友好的讨论。开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
