### ISSUE TITLE
高并发情况下，调用词法分析，句法依赖接口，耗时较长

### ISSUE THREAD

**Issue by zy158** [hankcs/HanLP#1452]
**Describe the bug**
您好，我在使用1.X版的hanlp的java接口时，高并发（每秒150请求）调用词法分析和句法依赖接口，耗时很长，但cpu利用率和内存没有明显增加，请问是怎么回事？是依赖关系等功能暂时不能用于高并发场景吗？

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
`CRFSegmenter segmenter = new CRFSegmenter(HanLP.Config.CRFCWSModelPath);
CRFLexicalAnalyzer analyzer = new CRFLexicalAnalyzer(HanLP.Config.CRFCWSModelPath, HanLP.Config.CRFPOSModelPath, HanLP.Config.CRFNERModelPath);
NeuralNetworkDependencyParser nndp = new NeuralNetworkDependencyParser();

List<String> wordList = segmenter.segment(text);
List<String> poss = Arrays.asList(analyzer.tag(wordList));
List<Term> termList = new ArrayList<Term>();
List<Nature> natureList = new ArrayList<Nature>();
for (int i = 0; i < wordList.size(); i++) {

            Nature nature = getNature(poss.get(i));
            natureList.add(nature);

 }
for (int i = 0; i < wordList.size(); i++) {
            Term term = new Term(wordList.get(i), natureList.get(i));
            termList.add(term);
}
CoNLLSentence result = nndp.parse(termList);`

**Describe the current behavior**
A clear and concise description of what happened.
利用了分词，词性，拼音，和依赖关系做算法的特征，所以在预测的过程中需要先调用这些接口生成text的特征，然后进行预测。text以每秒150个请求传入，每次特征生成耗时快2s左右，cpu和内存并没有占满。但并发次数降低，耗时会大幅度下降，如每秒20个请求，每次特征生成耗时300ms。如果不使用句法依赖，只使用分词和词性，同样并发数，耗时1s左右。如果只使用拼音接口，同样并发数，耗时400ms左右。是依赖关系等功能暂时不能用于高并发场景吗？希望您能帮我解答。

**Expected behavior**
无

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version: Java 1.8
- HanLP version: 1.x

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
无

* [ ] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
【自动回复】你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://raw.githubusercontent.com/hankcs/HanLP/master/.github/ISSUE_TEMPLATE/bug_report.md)认真修改，然后耐心等待下周末处理。
如果您提的是bug或feature request，那么请您按模板认真改一改，reopen这个issue。否则，咨询类的问题应该好好改一改，写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。
如果您不修改的话，恐怕没有人能够回复您，我们也会错失一次改进的机会或者一次友好的讨论。开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。

**Comment by zy158** [comment]
您好，不知道修改之后是不是符合模板要求
