### ISSUE TITLE
pyhanlp 和 Hanlp 分词结果不一致, 词性不一致

### ISSUE THREAD

**Issue by yan-rui** [hankcs/HanLP#1454]
**Describe the bug**
pyhanlp 和 java 版的Hanlp分词结果不一致
词性也不一致

**Code to reproduce the issue**

pyhanlp,  0.1.63
```python
from pyhanlp import *
print(HanLP.segment('你说的这句话没有根据,根据以往的经验,我是对的.'))
[你/rr, 说/v, 的/ude1, 这/rzv, 句话/q, 没有/v, 根据/p, ,/w, 根据/p, 以往/t, 的/ude1, 经验/n, ,/w, 我/rr, 是/vshi, 对/p, 的/ude1, ./w]
```
com.hankcs:hanlp:portable-1.7.5
```java
String text = "你说的这句话没有根据,根据以往的经验,我是对的.";
System.out.println(HanLP.segment(text));
[你/r, 说/v, 的/uj, 这/r, 句话/q, 没/d, 有/v, 根据/p, ,/w, 根据/p, 以往/t, 的/uj, 经验/n, ,/w, 我/r, 是/v, 对/p, 的/uj, ./w]
```

**Describe the current behavior**
pyhanlp 的分词 没有/v,  词性: 你/rr
Hanlp 分词: 没/d, 有/v,  词性: 你/r

**Expected behavior**
表现一致

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version: 3.62
- HanLP version: portable-1.7.5

**Other info / logs**
None

* [x] I've completed this form and searched the web for solutions.

**Comment by yan-rui** [comment]
把java版换成pyhanlp依赖一致的1.7.7后结果如下
```java
[你/r, 说/v, 的/uj, 这/r, 句话/q, 没/d, 有/v, 根据/p, ,/w, 根据/p, 以往/t, 的/uj, 经验/n, ,/w, 我/r, 是/v, 对/p, 的/uj, ./w]
```

**Comment by hankcs** [comment]
老生常谈了，检查一下配置文件是否一致。
