### ISSUE TITLE
com.hankcs.hanlp.mining.cluster.ClusterAnalyzer.repeatedBisection(ClusterAnalyzer.java:242)

### ISSUE THREAD

**Issue by windtalker01** [hankcs/HanLP#1457]
**Describe the bug**
不同的测试字符串情况下，有的是在0.2的时候报这个错，有的0.1的时候报这个错
Exception in thread "main" java.lang.NullPointerException
	at com.hankcs.hanlp.mining.cluster.ClusterAnalyzer.repeatedBisection(ClusterAnalyzer.java:242)
	at com.hankcs.hanlp.mining.cluster.ClusterAnalyzer.repeatedBisection(ClusterAnalyzer.java:206)
	at HanLPTest$.main(HanLPTest.scala:31)
	at HanLPTest.main(HanLPTest.scala)
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```scala语言：
val analyzer: ClusterAnalyzer[String] = new ClusterAnalyzer[String]()
    val strs: List[(String, String)] = List[(String, String)](
      ("1","中国辽宁沈阳大东区望花北街【望花中街111-8号万城6号楼2单元20-4号】 (鑫淼海鲜馆附近)"),
      ("2","中国辽宁沈阳大东区【万城6号楼2单元20-4号】"),
      ("3","辽宁沈阳市大东区三环内望花中街111-8号万城6号楼2单元20-4号"))
    for ((id, str) <- strs) {
      analyzer.addDocument(id, str)
    }
    println(analyzer.repeatedBisection(0.01))
```

**Describe the current behavior**
A clear and concise description of what happened.
调整到较高的参数后不报错，如0.3，就不报错
**Expected behavior**
如何解决这个问题。
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version: scala 2.11
- HanLP version: portable-1.7.7

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
无
* [ ] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
【自动回复】你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://raw.githubusercontent.com/hankcs/HanLP/master/.github/ISSUE_TEMPLATE/bug_report.md)认真修改，然后耐心等待下周末处理。
如果您提的是bug或feature request，那么请您按模板认真改一改，reopen这个issue。否则，咨询类的问题应该好好改一改，写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。
如果您不修改的话，恐怕没有人能够回复您，我们也会错失一次改进的机会或者一次友好的讨论。开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
