### ISSUE TITLE
jpype提示依存句法分析出错

### ISSUE THREAD

**Issue by leemanyan** [hankcs/HanLP#146]
请问jpype._jexception.VirtualMachineErrorPyRaisable: java.lang.OutOfMemoryError: Java heap space
为何会超时呢？

**Comment by miaomushan** [comment]
请教下这个怎么解决？我刚才也遇到了。

**Comment by leemanyan** [comment]
pycharm的内存配置也改了，初始128，最大1024，但依然是那个问题，求博主解答

**Comment by hankcs** [comment]
不关pycharm的事，试试这个参数：

startJVM(getDefaultJVMPath(), "-Djava.class.path=C:\hanlp\hanlp-1.2.8.jar;C:\hanlp", "-Xms1g -Xmx1g")
