### ISSUE TITLE
test

### ISSUE THREAD

**Issue by windtalker01** [hankcs/HanLP#1461]
**Describe the bug**
test

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```scala
test
```

**Describe the current behavior**
A clear and concise description of what happened.
tesxz

**Expected behavior**
test

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): xxx
- Python version: 2.11
- HanLP version:1.78

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
xxxtest

* [ ] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form then reopen it.
