### ISSUE TITLE
ClusterAnalyzer.repeatedBisection limit_eval参数值太小时，报空指针

### ISSUE THREAD

**Issue by windtalker01** [hankcs/HanLP#1463]
**Describe the bug**
使用文本聚类算法中二分聚类算法，limit_eval参数值太小时，报空指针.
不同的测试字符串情况下，有的是在0.2的时候报空指针，有的0.1的时候报空指针

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
from pyhanlp import *

ClusterAnalyzer = JClass('com.hankcs.hanlp.mining.cluster.ClusterAnalyzer')

if __name__ == '__main__':
    analyzer = ClusterAnalyzer()
    analyzer.addDocument("1","大东区望花北街")
    analyzer.addDocument("2","大东区万城6号楼2单元20-4号")
    analyzer.addDocument("3","花中街111-8号万城6号楼2单元20-4号")
    print(analyzer.repeatedBisection(3))    # 重复二分聚类
    print(analyzer.repeatedBisection(0.05))  # 自动判断聚类数量k
```

**Describe the current behavior**
A clear and concise description of what happened.
针对不同组的字符串，limit_eval调整到较大的参数，可以运行

**Expected behavior**
增加null判断，或检查算法里导致null的bug

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):windows10 
- Python version: 3.6.0
- HanLP version:1.7.7

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
Traceback (most recent call last):
  File "C:/work/项目/乐信大数据/虚假报单分析/classer/classer/hanlp.py", line 11, in <module>
    print(analyzer.repeatedBisection(0.05))  # 自动判断聚类数量k
jpype._jclass.NullPointerException: java.lang.NullPointerException
* [ ] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
【自动回复】你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://raw.githubusercontent.com/hankcs/HanLP/master/.github/ISSUE_TEMPLATE/bug_report.md)认真修改，然后耐心等待下周末处理。
如果您提的是bug或feature request，那么请您按模板认真改一改，reopen这个issue。否则，咨询类的问题应该好好改一改，写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。
如果您不修改的话，恐怕没有人能够回复您，我们也会错失一次改进的机会或者一次友好的讨论。开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
