### ISSUE TITLE
调用词性标注模型直接报错

### ISSUE THREAD

**Issue by hezhihao10** [hankcs/HanLP#1467]
**Describe the bug**
调用词性标注模型直接报错

**Code to reproduce the issue**
'''
测试HanLP功能
'''

import hanlp

tokenizer = hanlp.load('PKU_NAME_MERGED_SIX_MONTHS_CONVSEG')
word_list = tokenizer('商品和服务')
print(word_list)
tagger = hanlp.load(hanlp.pretrained.pos.PTB_POS_RNN_FASTTEXT_EN)
pos_list = tagger(word_list)
print(pos_list)

```python
```

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  win10
- Python version: python3.6
- HanLP version:  2.0.0-alpha.42.

**Other info / logs**
ValueError: C:\Users\shuhe\AppData\Roaming\hanlp\thirdparty\elit-models.s3-us-west-2.amazonaws.com\cc.en.300.bin.zip.downloading has wrong file format!
https://file.hankcs.com/hanlp/pos/ptb_pos_rnn_fasttext_20200103_145337.zip was created with hanlp-2.0.0-alpha.1, while you are running 2.0.0-alpha.42. Try to upgrade hanlp with
pip install --upgrade hanlp

* [ ] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
【自动回复】你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://raw.githubusercontent.com/hankcs/HanLP/master/.github/ISSUE_TEMPLATE/bug_report.md)认真修改，然后耐心等待下周末处理。
如果您提的是bug或feature request，那么请您按模板认真改一改，reopen这个issue。否则，咨询类的问题应该好好改一改，写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。
如果您不修改的话，恐怕没有人能够回复您，我们也会错失一次改进的机会或者一次友好的讨论。开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
