### ISSUE TITLE
能否使用1.1x，而非2.1.0作为tensorflow的默认版本？

### ISSUE THREAD

**Issue by qixiang109** [hankcs/HanLP#1469]
我发现hanlp会强制把我的tf 1.14.0刷新成tf2.1.0，我理解hanlp必须基于tf2.x工作是吧？

对我个人使用倒是无妨，但是tf2.x的环境依赖和1.1x还是有点区别的，在很多服务器场景无法顺利使用，会报一些1.1x中不存在的“找不到lib_xxx.so”之类的问题。

一点小小的瑕疵，就会限制了hanlp在严肃商业场景的发展。

不知道能否支持tf 1.14

**Describe the feature and the current behavior/state.**

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Are you willing to contribute it (Yes/No):**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version:
- HanLP version:

**Any other info**

* [ ] I've carefully completed this form.

**Comment by hankcs** [comment]
【自动回复】你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://raw.githubusercontent.com/hankcs/HanLP/master/.github/ISSUE_TEMPLATE/bug_report.md)认真修改，然后耐心等待下周末处理。
如果您提的是bug或feature request，那么请您按模板认真改一改，reopen这个issue。否则，咨询类的问题应该好好改一改，写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。
如果您不修改的话，恐怕没有人能够回复您，我们也会错失一次改进的机会或者一次友好的讨论。开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
