### ISSUE TITLE
求教连接java的class丢失了，该如何找回？

### ISSUE THREAD

**Issue by leemanyan** [hankcs/HanLP#147]
运行时突然出现jpype._jexception.ExceptionPyRaisable: java.lang.Exception: Class com.hankcs.hanlp.HanLP not found的错误，之前不小心卸载了python2换成3，现在又换成2就变成这样了，跪求高人的解决办法

**Comment by hankcs** [comment]
应该是jar的路径错了。

**Comment by leemanyan** [comment]
路径看了好像没问题
`# -*- coding:utf-8 -*-
from jpype import *

startJVM(getDefaultJVMPath(), "-Djava.class.path=D:\PycharmProjects\untitled\hanlp-protable-1.2.8.jar;D:\PycharmProjects\untitled")
HanLP = JClass('com.hankcs.hanlp.HanLP')
# 中文分词
print(HanLP.segment('你好，欢迎在Python中调用HanLP的API'))`
jdk、python、jpype都重装过，位数也都相同，但还是会报错
`Traceback (most recent call last):
  File "D:/PycharmProjects/untitled/main.py", line 8, in <module>
    HanLP = JClass('com.hankcs.hanlp.HanLP')
  File "C:\Python27\lib\site-packages\jpype\_jclass.py", line 54, in JClass
    raise _RUNTIMEEXCEPTION.PYEXC("Class %s not found" % name)
jpype._jexception.ExceptionPyRaisable: java.lang.Exception: Class com.hankcs.hanlp.HanLP not found`

**Comment by leemanyan** [comment]
而且谷歌了下基本都是说JDK版本问题，是这样吗？我都换成32位的都还是不行
	
1）thanks for the answer but I still have same error: Traceback (most recent call last): File "aa.py", line 14, in <module> A = JClass('stm.Stm') File "/usr/lib/python2.7/dist-packages/jpype/_jclass.py", line 54, in JClass raise _RUNTIMEEXCEPTION.PYEXC("Class %s not found" % name) jpype._jexception.ExceptionPyRaisable: java.lang.Exception: Class stm.Stm not found – Jeren May 12 '14 at 13:17 
  	 	
Make sure the class is built (/home/jeren/Desktop/Project/TweetParse/Parse_Tweets/stm/build/classes/stm/Stm.‌​class exists). Check Java version using by your Python library and by your Java compiler. Also when you resolve that you will need to add default (no-arg) constructor to instantiate a = A(). – Radim May 12 '14 at 13:50
  	 	
Stm.class exists! how can I use constructor with arguments??? is it possible anyway??????? – Jeren May 12 '14 at 14:08
  	 	
Check Java version using by your Python library and by your Java compiler ===> both use java 1.7 – Jeren May 12 '14 at 15:46 
  	 	
I solved it by changing the JDK I used from 1.6 to 1.7 .. thanks to Radim for comments :) – Jeren May 12 '14 at 17:46

2) Problem was that my Python was 32 bits and my java sdk (including the javac bytecode compiler) was 64 bits. I uninstalled the java sdk and re-installed a 32bits version. Done! Solved!

**Comment by hankcs** [comment]
0. 安装JDK非常简单，分清楚32位和64位即可，必须与OS和Python的位数一致
0. 针对不同位数，不同Python版本也有不同的JPype版本
0. 我手上没有出问题的机器，无法进一步试错
0. 你是“卸载了python2换成3，现在又换成2”导致这个问题，情况更复杂

**Comment by leemanyan** [comment]
先感谢博主解答。本人将换一台电脑尝试，不过新电脑OS是64位的，JDK和python有64位的，但JPype官网好像只有win32的，JPype-0.5.4.2.win32-py2.7。不知这样有没有影响？

**Comment by hankcs** [comment]
应该可以通过编译的方式得到64位，另外pychar的pip install其实也是编译安装。

**Comment by leemanyan** [comment]
感谢博主，换到linux下一样的问题，暂未找到解决办法，以后再做尝试

**Comment by hankcs** [comment]
我怀疑jar包是否破损了？拓展名改为.zip试试看能不能解压。

**Comment by leemanyan** [comment]
尝试了都不行，portable版的和正式版的都试过，对Java的运行不是很了解，估计是调用JVM的过程中出了什么茬子
