### ISSUE TITLE
hanlp-2.0.0a43加载ner模型报错，hanlp与模型版本不匹配

### ISSUE THREAD

**Issue by xuetrdi** [hankcs/HanLP#1470]
**Describe the bug**
hanlp版本和ner模型版本不匹配

**Code to reproduce the issue**
hanlp.load(hanlp.pretrained.ner.MSRA_NER_BERT_BASE_ZH)

```python
```

**Describe the current behavior**
A clear and concise description of what happened.

**Expected behavior**

**System information**
- OS Platform: Linux Ubuntu 16.04
- Python version: Python 3.6
- HanLP version:hanlp-2.0.0a43

**Other info / logs**
错误提示：
https://file.hankcs.com/hanlp/ner/ner_bert_base_msra_20200104_185735.zip was created with hanlp-2.0.0-alpha.5, while you are running 2.0.0-alpha.43. Try to upgrade hanlp with
pip install --upgrade hanlp
但是安装了hanlp-2.0.0-alpha.5版本的提示
Failed to download https://file.hankcs.com/hanlp/ner/ner_bert_base_msra_20191230_205748.zip due to timeout('The read operation timed out',). Please download it to /home/ubuntu/.hanlp/ner/ner_bert_base_msra_20191230_205748.zip by yourself. Or consider upgrading pip install -U hanlp

**Comment by hankcs** [comment]
【自动回复】你好，感谢反馈。
由于未按要求填写，本issue被暂时标记为无效。请按[issue模板](https://raw.githubusercontent.com/hankcs/HanLP/master/.github/ISSUE_TEMPLATE/bug_report.md)认真修改，然后耐心等待下周末处理。
如果您提的是bug或feature request，那么请您按模板认真改一改，reopen这个issue。否则，咨询类的问题应该好好改一改，写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。
如果您不修改的话，恐怕没有人能够回复您，我们也会错失一次改进的机会或者一次友好的讨论。开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。

**Comment by hankcs** [comment]
请参考 https://bbs.hankcs.com/t/topic/833
