### ISSUE TITLE
在使用命名实体识别模块时内存溢出崩溃

### ISSUE THREAD

**Issue by chengzhaoan** [hankcs/HanLP#1471]
**Describe the bug**
在使用命名实体识别模块时内存溢出崩溃
模型文件
ner_bert_base_msra_20200104_185735.zip
chinese_L-12_H-768_A-12.zip
在循环调用识别文本中的公司名称时，开始阶段内存稳定，一段时间后内存线性增长，每秒钟增长1M多，直到占用所有内存16G 崩溃

**Code to reproduce the issue**

```python
import hanlp 
recognizer = hanlp.load(hanlp.pretrained.ner.MSRA_NER_BERT_BASE_ZH) 
def getentityAI(row):     
    entitys = []     
    text = row['文本']     
    words = text.split(',') 
    #print(words) 
    for word in words: 
        #print(word)       
        res = recognizer(list(word))         
        #print(res)         
        if len(res)>0:             
            for re in res:                 
                if len(re[0]) > 3 and re[1]=='NT': 
                    #print(re)                     
                    entitys.append(re[0])     
                    #print(text)     
                    #print(entitys)     
    return ','.join(entitys) 
#df['实体名称s'] = df.apply(getentity,axis=1) 

```

**Describe the current behavior**

**Expected behavior**

**System information**
- win7 64为
- Python version: 3.7
- HanLP version:2.0.0a43

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [ ] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
【自动回复】你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://raw.githubusercontent.com/hankcs/HanLP/master/.github/ISSUE_TEMPLATE/bug_report.md)认真修改，然后耐心等待下周末处理。
如果您提的是bug或feature request，那么请您按模板认真改一改，reopen这个issue。否则，咨询类的问题应该好好改一改，写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。
如果您不修改的话，恐怕没有人能够回复您，我们也会错失一次改进的机会或者一次友好的讨论。开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
