### ISSUE TITLE
能否增加多语言支持？比如韩文 日文 中文

### ISSUE THREAD

**Issue by memaxiaofeng** [hankcs/HanLP#1474]
**Describe the feature and the current behavior/state.**
支持多语言分词,或分词多语言化
**Will this change the current api? How?**
可能需要更新
**Who will benefit with this feature?**
有国际业务的或跨国,想对于日新月异的中国 很是需要
**Are you willing to contribute it (Yes/No):**
yes
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version:
- HanLP version:

**Any other info**

* [x] I've carefully completed this form.

**Comment by hankcs** [comment]
1. 目前的设计是语言无关的，你已经可以用fit接口训练任意语种。
1. 正在开发一个新的多语种联合模型。

**Comment by hankcs** [comment]
https://hanlp.hankcs.com/docs/tutorial.html

**Comment by XingyuZhu-Pamela** [comment]
> https://hanlp.hankcs.com/docs/tutorial.html

您好，请问当前支持哪些语种呢，有支持语种的列表吗？

**Comment by hankcs** [comment]
目前：


Afrikaans , Akkadian , Akuntsu , Albanian , Amharic , AncientGreek (to 1453) , Ancient Hebrew , Apurinã , Arabic , Armenian , AssyrianNeo-Aramaic , Bambara , Basque , Beja , Belarusian , Bengali , Bhojpuri , Breton , Bulgarian , Catalan , Cebuano , Central Siberian Yupik , Chinese , Chukot , ChurchSlavic , Coptic , Croatian , Czech , Danish , Dutch , Emerillon , English , Erzya , Estonian , Faroese , Finnish , French , Galician , German , Gothic , Guajajára , Guarani , Hebrew , Hindi , Hittite , Hungarian , Icelandic , Indonesian , Irish , Italian , Japanese , Javanese , K'iche' , Kangri , Karelian , Karo(Brazil) , Kazakh , Khunsari , Komi-Permyak , Komi-Zyrian , Korean , Latin , Latvian , Ligurian , LiteraryChinese , Lithuanian , Livvi , LowGerman , Madi , Makuráp , Maltese , Manx , Marathi , MbyáGuaraní , Modern Greek (1453-) , Moksha , Mundurukú , Nayini , Neapolitan , Nigerian Pidgin , NorthernKurdish , Northern Sami , Norwegian , OldFrench (842-ca. 1400) , OldRussian , Old Turkish , Persian , Polish , Portuguese , Romanian , Russia Buriat , Russian , Sanskrit , ScottishGaelic , Serbian , SkoltSami , Slovak , Slovenian , Soi , South Levantine Arabic , Spanish , Swedish , SwedishSign Language , SwissGerman , Tagalog , Tamil , Tatar , Telugu , Thai , Tupinambá , Turkish , Uighur , Ukrainian , Umbrian , UpperSorbian , Urdu , Urubú-Kaapor , Vietnamese , Warlpiri , Welsh , Western Armenian , WesternFrisian , Wolof , Xibe , Yakut , Yoruba , YueChinese
