### ISSUE TITLE
下载Data失败

### ISSUE THREAD

**Issue by newmrxu** [hankcs/HanLP#1475]
---
name: 🐛Bug report
about: Create a report to help us improve
title: 'Import时不能下载data'
labels: bug
assignees: hankcs

---
**Describe the bug**
当我使用jupyter notebook运行import pyhanlp会下载data-1.7.zip，一直会出现timeout，而当我手工下载data-1.7.zip并将复制到/opt/anaconda3/lib/python3.7/site-packages/pyhanlp/static/，并将其重命名为data-1.7.7.zip时，下次运行import pyhanlp还是会自动下载该文件。

而当我使用IPython命令行运行Import pyhanlp时，又会自动下载data-1.7.5.zip文件，虽然文件夹也已经有该文件（我手工下载后放入）。请问是何回事呢？

**Code to reproduce the issue**

```import pyhanlp
```

**Describe the current behavior**
不能完成下载pyhanlp所需的data文件，也无法识别手工下载的data文件。

**Expected behavior**
完成下载

**System information**
- MacOS 10.15
- Anaconda python3.7
- HanLP version:latest

**Other info / logs**
screenshot included

* [ ] I've completed this form and searched the web for solutions.

![hanlp](https://user-images.githubusercontent.com/62363087/82623297-6705d000-9c12-11ea-90d6-515ecd1a012b.png)
![hanlp2](https://user-images.githubusercontent.com/62363087/82623310-708f3800-9c12-11ea-87af-c22cc5546346.png)

**Comment by hankcs** [comment]
【自动回复】你好，感谢反馈。
由于未按要求填写，本issue被暂时标记为无效。请按[issue模板](https://raw.githubusercontent.com/hankcs/HanLP/master/.github/ISSUE_TEMPLATE/bug_report.md)认真修改，然后耐心等待下周末处理。
如果您提的是bug或feature request，那么请您按模板认真改一改，reopen这个issue。否则，咨询类的问题应该好好改一改，写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。
如果您不修改的话，恐怕没有人能够回复您，我们也会错失一次改进的机会或者一次友好的讨论。开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。

**Comment by hankcs** [comment]
命名为data-1.7.5.zip就好了。

**Comment by hankcs** [comment]
刚试了下，文件名data-for-1.7.7.zip是可以的。

使用本地 pyhanlp/static/data-for-1.7.7.zip, 忽略 https://file.hankcs.com/hanlp/data-for-1.7.zip
解压 data.zip...

**Comment by newmrxu** [comment]
问题是，在static文件夹里面已经有了3个data文件：
data-for-1.7.zip
data-for-1.7.5.zip
data-for-1.7.7.zip
这些文件都是我之前手工下载后放到这里的（我相信他们都是一样的文件），但我运行import pyhanlp时，还是要下载data-for-1.7.5.zip，而下载都是无一例外会timeout的。这样就始终没有办法使用pyhanlp。

请见附图。
![hanlp3](https://user-images.githubusercontent.com/62363087/82675843-001b0200-9c78-11ea-8641-63d84e022202.png)

**Comment by hankcs** [comment]
删除data文件夹和hanlp.properties两个文件后重试。

根据 https://github.com/hankcs/pyhanlp/blob/master/pyhanlp/static/__init__.py#L135 ，只需data-for-1.7.7.zip一个文件即可。

**Comment by newmrxu** [comment]
谢谢你的建议，麻烦您了。我按照你所说，
1）把data文件夹及hanlp.properties两个文件都删除后，
2）然后我再删除data-for-1.7.zip及1.7.5删除，只保留data-for-1.7.7.zip
3) 再运行import pyhanlp，发现仍然要下载data-for-1.7.5.zip，
4)然后我再把data-for-1.7.5.zip重新拷贝进来，仍然要下载data-for-1.7.5.zip
所以问题仍然未得到解决。

附上截图。再次感谢。
![hanlp4](https://user-images.githubusercontent.com/62363087/82721678-1ebddf00-9cf2-11ea-9eb0-3bda2da3407b.png)

**Comment by hankcs** [comment]
我怀疑你截图的文件夹根本不是/opt，建议用命令行wget ... -O 到opt这个目录。
