### ISSUE TITLE
www.hanlp.com登不上去了？有人能看一下吗？

### ISSUE THREAD

**Issue by zhangyuankai2018** [hankcs/HanLP#1478]
**Describe the bug**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
```

**Describe the current behavior**
A clear and concise description of what happened.

**Expected behavior**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version:
- HanLP version:

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [ ] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form.

**Comment by hankcs** [comment]
备案中，请暂时使用海外镜像：https://hanlp.hankcs.com/

**Comment by zhangyuankai2018** [comment]
你好，海外镜像也不能用了？梯子能上google但是上不去网站

**Comment by hankcs** [comment]
可以。

**Comment by zhangyuankai2018** [comment]
感谢你及时的回复，目前还是没能登上镜像，可能问题出自我这里。
