### ISSUE TITLE
词典里收录很多动词＋名词合成的词是为了什么？

### ISSUE THREAD

**Issue by huchhong** [hankcs/HanLP#148]
比如”打篮球“这样的词出现在核心词典里，搞得分词总是不理想，特别是句法依存分析导致也很混乱。正常语义里，像这样的词不是应该分开考虑，这样主谓宾才能明确。

**Comment by hankcs** [comment]
0. 词典=模型，模型训练自2014人民日报语料，不存在主观收录不收录的问题
0. 1998mini词典拆词比较细碎，你可以配置用98版的
0. 你还可以自己训练一个模型，对复合词采取拆分策略

**Comment by huchhong** [comment]
多谢解释
