### ISSUE TITLE
同一个词，词性定义不同分词结果不同

### ISSUE THREAD

**Issue by qqxhb** [hankcs/HanLP#1486]
### 注意事项
请确认下列注意事项：

我已仔细阅读下列文档，都没有找到答案：
- 首页文档
- wiki
- 常见问题
- 我已经通过Google和issue区检索功能搜索了我的问题，也没有找到答案。
- 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。

- [√ ]  我在此括号内输入x打钩，代表上述事项确认完毕

### 版本号
当前最新版本号是：1.7.5
我使用的版本是：1.7.5

### 我的问题
String sentence="以前开沃尔沃越野转弯也似乎有这个问题。";
如果自定义词性为：开沃 c_304_90 4000
分词结果是
以前/f, 开沃/c_304_90, 尔/rg, 沃/vg, 越野/vn, 转弯/w1_020000_000, 也/stop, 似乎/d, 有/v, 这个/stop, 问题/n,

如果自定义词性为：开沃 xby 4000
分词结果是
以前/f, 开/v, 沃尔沃/c_19_20001_329_2, 越野/vn, 转弯/w1_020000_000, 也/stop, 似乎/d, 有/v, 这个/stop, 问题/n

如果需要第一种词性 怎么定义才能得到第二种分词结果呢

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://raw.githubusercontent.com/hankcs/HanLP/master/.github/ISSUE_TEMPLATE/bug_report.md)认真修改，然后耐心等待下周末处理。
如果您提的是bug或feature request，那么请您按模板认真改一改，reopen这个issue。
否则，咨询类的问题请先搜索一下。99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。
如果您不修改的话，恐怕没有人能够回复您，我们也会错失一次改进的机会或者一次友好的讨论。开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
