### ISSUE TITLE
segment.seg wrong

### ISSUE THREAD

**Issue by MachineSan** [hankcs/HanLP#1488]
**Describe the bug**
当我使用以下这段代码时：
segment = HanLP.newSegment().enableNameRecognize(True)
result = segment.seg("某一段话")

此时我在我的Ubuntu系统下并不会报错，并会返回结果
但当我在Windows系统下却报错：
TypeError: Ambiguous overloads found for com.hankcs.hanlp.seg.Segment.seg(str) between:
	public java.util.List com.hankcs.hanlp.seg.Segment.seg(char[])
	public java.util.List com.hankcs.hanlp.seg.Segment.seg(java.lang.String)

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
```

**Describe the current behavior**
Ubuntu下正常返回结果，Windows下没有

**Expected behavior**
应该正常返回结果

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu16.04 and Windows10
- Python version: Python3.8
- HanLP version:  HanLp1.7.7

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [ ] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://raw.githubusercontent.com/hankcs/HanLP/master/.github/ISSUE_TEMPLATE/bug_report.md)认真修改，然后耐心等待下周末处理。
如果您提的是bug或feature request，那么请您按模板认真改一改，reopen这个issue。
否则，咨询类的问题请先搜索一下。99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。
如果您不修改的话，恐怕没有人能够回复您，我们也会错失一次改进的机会或者一次友好的讨论。开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。

**Comment by hankcs** [comment]
![hankcs com 2020-06-08 at 11 03 00 AM](https://user-images.githubusercontent.com/5326890/84046261-d94b1400-a977-11ea-9a19-6c815a9daffa.png)
![hankcs com 2020-06-08 at 11 01 37 AM](https://user-images.githubusercontent.com/5326890/84046272-dcde9b00-a977-11ea-8e4a-7da12497b81d.png)

**Comment by MachineSan** [comment]
> ![hankcs com 2020-06-08 at 11 03 00 AM](https://user-images.githubusercontent.com/5326890/84046261-d94b1400-a977-11ea-9a19-6c815a9daffa.png)
> 
> ![hankcs com 2020-06-08 at 11 01 37 AM](https://user-images.githubusercontent.com/5326890/84046272-dcde9b00-a977-11ea-8e4a-7da12497b81d.png)
> 
> 


segment = HanLP.newSegment().enableNameRecognize(True)
result = segment.seg("某一段话")

我之前这样写可以成功，返回结果，但是现在这样写报错了，可能区别较大的就是我之前的python版本是3.5，现在的版本是3.8，而且我看了对应源码里有seg这个方法，所以我不太明白为什么这会报错

**Comment by hankcs** [comment]
看截图，你必须用图示的jpype版本号，这是最要紧的。你可能在升级python的过程中把jpype升级了。
