### ISSUE TITLE
java portable-1.7.7 data/dictionary/place缺少文件ns.txt.bin

### ISSUE THREAD

**Issue by keke9036** [hankcs/HanLP#1491]
**Describe the bug**
java portable-1.7.7版本， data/dictionary/place缺少文件ns.txt.bin

**Code to reproduce the issue**
1. 引入maven依赖
<dependency>
    <groupId>com.hankcs</groupId>
    <artifactId>hanlp</artifactId>
    <version>portable-1.7.7</version>
</dependency>

2. 运行“地址识别”官方demo
```java
String[] testCase = new String[]{
        "武胜县新学乡政府大楼门前锣鼓喧天",
        "蓝翔给宁夏固原市彭阳县红河镇黑牛沟村捐赠了挖掘机",
};
Segment segment = HanLP.newSegment().enablePlaceRecognize(true);
for (String sentence : testCase)
{
    List<Term> termList = segment.seg(sentence);
    System.out.println(termList);
}
```

**Describe the current behavior**
报错，提示data/dictionary/place缺少文件ns.txt.bin。
查看依赖包中，缺少此文件

**Expected behavior**
正常运行

**System information**
- Ubuntu 16
- Java version: 11
- HanLP version: portable-1.7.7

* [ ] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被暂时标记为无效。请按[issue模板](https://raw.githubusercontent.com/hankcs/HanLP/master/.github/ISSUE_TEMPLATE/bug_report.md)认真修改，然后耐心等待下周末处理。
如果您提的是bug或feature request，那么请您按模板认真改一改，reopen这个issue。
否则，咨询类的问题请先搜索一下。99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。
如果您不修改的话，恐怕没有人能够回复您，我们也会错失一次改进的机会或者一次友好的讨论。开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。

**Comment by hankcs** [comment]
感谢反馈，已经修复。
如果还有问题，欢迎重开issue。
