### ISSUE TITLE
安装失败，请问是什么原因

### ISSUE THREAD

**Issue by SamLiu666** [hankcs/HanLP#1492]
**Describe the bug**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
```

**Describe the current behavior**
A clear and concise description of what happened.

**Expected behavior**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version:
- HanLP version:

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [ ] I've completed this form and searched the web for solutions.
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:D:\Anaconda\envs\segment\libs /LIBPATH:D:\Anaconda\envs\segment\PCbuild\amd64 "/LIBPATH:D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64" /EXPORT:PyInit_fasttext_pybind build\temp.win-amd64-3.7\Release\python/fasttext_module/fasttext/pybind/fasttext_pybind.obj build\temp.win-amd64-3.7\Release\src\args.obj build\temp.win-amd64-3.7\Release\src\densematrix.obj build\temp.win-amd64-3.7\Release\src\dictionary.obj build\temp.win-amd64-3.7\Release\src\fasttext.obj build\temp.win-amd64-3.7\Release\src\loss.obj build\temp.win-amd64-3.7\Release\src\main.obj build\temp.win-amd64-3.7\Release\src\matrix.obj build\temp.win-amd64-3.7\Release\src\meter.obj build\temp.win-amd64-3.7\Release\src\model.obj build\temp.win-amd64-3.7\Release\src\productquantizer.obj build\temp.win-amd64-3.7\Release\src\quantmatrix.obj build\temp.win-amd64-3.7\Release\src\utils.obj build\temp.win-amd64-3.7\Release\src\vector.obj /OUT:build\lib.win-amd64-3.7\fasttext_pybind.cp37-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.7\Release\python/fasttext_module/fasttext/pybind\fasttext_pybind.cp37-win_amd64.lib
    fasttext_pybind.obj : warning LNK4197: 多次指定导出“PyInit_fasttext_pybind”；使用第一个规范
      正在创建库 build\temp.win-amd64-3.7\Release\python/fasttext_module/fasttext/pybind\fasttext_pybind.cp37-win_amd64.lib 和对象 build\temp.win-amd64-3.7\Release\python/fasttext_module/fasttext/pybind\fasttext_pybind.cp37-win_amd64.exp
    正在生成代码
    已完成代码的生成
    LINK : fatal error LNK1158: 无法运行“rc.exe”
    error: command 'D:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1158
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'D:\Anaconda\envs\segment\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\liu\\AppData\\Local\\Temp\\pip-install-d1z_cm56\\fasttext\\setup.py'"'"'; __file__='"'"'C:\\Users\\liu\\AppData\\Local\\Temp\\pip-install-d1z_cm56\\fasttext\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\liu\AppData\Local\Temp\pip-record-4rd6003o\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\Anaconda\envs\segment\Include\fasttext' Check the logs for full command output.

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://raw.githubusercontent.com/hankcs/HanLP/master/.github/ISSUE_TEMPLATE/bug_report.md)认真修改，然后耐心等待下周末处理。
如果您提的是bug或feature request，那么请您按模板认真改一改，reopen这个issue。
否则，咨询类的问题请先搜索一下。99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。
如果您不修改的话，恐怕没有人能够回复您，我们也会错失一次改进的机会或者一次友好的讨论。开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
