### ISSUE TITLE
jvm.dll文件在对应路径下存在但startJvm找不到

### ISSUE THREAD

**Issue by MachineSan** [hankcs/HanLP#1496]
**Describe the bug**

pyhanlp和JPype1都安装好了对应的环境，并且JAVA环境也配置好了，cmd运行java也是ok的。
但是运行代码时，jvm.dll文件在对应路径下存在但startJvm找不到

**Code to reproduce the issue**

import pyhanlp
# 机构名识别,标注为nt
def organization_recognize(sentence):
    segment = HanLP.newSegment().enableOrganizationRecognize(True)
    return segment.seg(sentence)
print(organization_recognize('dawdaw'))

```python
```

**Describe the current behavior**
程宇运行时报错无法找到jvm.dll文件，但该文件在对应路径下存在

**Expected behavior**

正常执行

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 7
- Python version: python3.8
- HanLP version: jpype1-0.7.0 pyhanlp-0.1.66

**Other info / logs**
具体信息如图：

![1](https://user-images.githubusercontent.com/65661595/85613616-a51c6680-b68c-11ea-8a74-b6f92f0f42c5.png)
![2](https://user-images.githubusercontent.com/65661595/85613620-a64d9380-b68c-11ea-9561-2402145f5bde.png)
![3](https://user-images.githubusercontent.com/65661595/85613630-a8afed80-b68c-11ea-8a35-91441ead366e.png)

* [ ] I've completed this form and searched the web for solutions.
并未找到解决方案

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://raw.githubusercontent.com/hankcs/HanLP/master/.github/ISSUE_TEMPLATE/bug_report.md)认真修改，然后耐心等待下周末处理。
如果您提的是bug或feature request，那么请您按模板认真改一改，reopen这个issue。
否则，咨询类的问题请先搜索一下。99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。
如果您不修改的话，恐怕没有人能够回复您，我们也会错失一次改进的机会或者一次友好的讨论。开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。

**Comment by hankcs** [comment]
You could wire this to jpype community: 

https://github.com/jpype-project/jpype/issues/539

**Comment by MachineSan** [comment]
Thank you!
