### ISSUE TITLE
数组遍历越界－v1.2.8版本

### ISSUE THREAD

**Issue by StardustZhou** [hankcs/HanLP#150]
需要分词的字符串：“双十二”加油有折扣还有红包
分词方式： List<Term> terms = HanLP.newSegment().enableCustomDictionary(true).enableAllNamedEntityRecognize(true).enableNumberQuantifierRecognize(true).seg(
                content.trim());

错误提示：Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 17
	at com.hankcs.hanlp.seg.common.WordNet.add(WordNet.java:101)
	at com.hankcs.hanlp.seg.common.WordNet.addAll(WordNet.java:201)
	at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.segSentence(ViterbiSegment.java:95)
	at com.hankcs.hanlp.seg.Segment.seg(Segment.java:422)
	at org.nlp.sentiment.ModelUtilsByRuleMap.calSentimentScore(ModelUtilsByRuleMap.java:177)
	at org.nlp.sentiment.ModelUtilsByRuleMap.calEmotionType(ModelUtilsByRuleMap.java:210)

**Comment by hankcs** [comment]
感谢反馈，这是由多个模块组合不严谨造成的，影响使用了mini词典的版本。现在已经修复：

[“/w, 双十二/m, ”/w, 加油/v, 有/v, 折扣/n, 还有/v, 红包/n]

如果还有问题，欢迎继续讨论。

**Comment by StardustZhou** [comment]
嗯，数词模块还是问题，我进行了修改，不知道这么改会不会引起其他的问题。
  if (cur != null &&
                        (cur.hasNature(Nature.q) || cur.hasNature(Nature.qv) || cur.hasNature(Nature.qt))
                        ) {
                    if (config.indexMode) {
                        wordNetAll.add(line, new Vertex(sbQuantifier.toString(), new CoreDictionary.Attribute(Nature.m)));
                    }
                    sbQuantifier.append(cur.realWord);
                    pre.attribute = new CoreDictionary.Attribute(Nature.mq);
                    pre.wordID = -1;    // -1代表NGram模型中的“万能词”，保证二次维特比得分一定更高
                    iterator.remove();
                    // 确定cur指向不符合数据规则的第一个节点
                    cur = iterator.next();
                }

                if (sbQuantifier.length() != pre.realWord.length()) {

                    pre.realWord = sbQuantifier.toString();
                    pre.word = Predefine.TAG_NUMBER;
                    pre.wordID = CoreDictionary.M_WORD_ID;
                    /**
                     *  由于remove节点,需要对后面节点进行from修正
                     */
                    cur.from = null;
                    cur.updateFrom(pre);

                    sbQuantifier.setLength(0);
                }

**Comment by StardustZhou** [comment]
主要新加：
// 确定cur指向不符合数据规则的第一个节点
cur = iterator.next();

/**
                 *  由于remove节点,需要对后面节点进行from修正
                 */
                cur.from = null;
                cur.updateFrom(pre);

**Comment by hankcs** [comment]
感谢提供进一步的指正。

这算是以前遗留的问题了，曾经在旧版本中引发过类似的问题。由于要进行多次最短路算法，所以每次执行最短路前按道理来讲都应该将vertex的from指针清空，但考虑到效率的问题迟迟没有这么做。

你提供的解决方案的第一行就足够达到清空指针的目的了：

cur.from = null;
