### ISSUE TITLE
添加文本标点

### ISSUE THREAD

**Issue by huangge1985** [hankcs/HanLP#1502]
**Describe the feature and the current behavior/state.**
    在一段无标点文本中，添加标点断句
**Will this change the current api? How?**
  不会
**Who will benefit with this feature?**
    可用于语音识别所生成的文本，将无标点的文本断句
**Are you willing to contribute it (Yes/No):**
   Yes
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version:
- HanLP version:

**Any other info**
  No
* [x] I've carefully completed this form.

**Comment by hankcs** [comment]
这项功能是可行的，你能说一下你的文本场景吗？或者提供几个样本？

**Comment by huangge1985** [comment]
场景：

机械设备操作，有操作员（专门负责设备的操作）和工程师：
要运行设备或作一些测试的时候，工程师会给操作员下一连串的操作指令，如把测试台架开起来，给控制器上低压，然后上高压，再把转速升到5000rpm, 扭矩加上200Nm....，操作员按要求操作设备。
给指令的时候，会一次性给很多指令，然后操作员按这些指令连续操作。

如是设备能理解连续语音指令，这些重复且繁琐的事情就不用操作员了，设备自己完成。

在语音转换时候，也可以实现分句，应该是判断静音的时间长，实现分句；
不过感觉这种方式不是很靠谱，说话时候周围可能有噪音，或说话的语速/停顿习惯不一样，或者再极端一点，急着上厕所了，几句话一口气说完了，中间没有停顿。

所以想着，有没有可能语音转文本之后再分句。

**Comment by hankcs** [comment]
工业控制的文本还是很稀缺的，用通用领域的文本可能很难训练出能用的模型。如果能找到一些工业控制的语料，可以用2.x的Tagger试一试。

**Comment by huangge1985** [comment]
恩，理解，我尝试一下，有问题再请教，谢谢！！
