### ISSUE TITLE
分词之后，和原句中的文字不一致

### ISSUE THREAD

**Issue by qqxhb** [hankcs/HanLP#1507]
**Describe the bug**
分词之后词和原文不一致

**Code to reproduce the issue**

```java
String paragraph ="客观来讲，这一价格与福特猛禽相比有着不小优势，但当疫情刚刚过去，国人会花20万元买一辆皮卡吗？";
Segment  segment = HanLP.newSegment().enableCustomDictionaryForcing(true).enableIndexMode(true).enableMultithreading(true);
  List<Term> termList = segment.seg(paragraph);
```

**Describe the current behavior**
 分词之后termList 中 ‘“猛禽”  变成了  “勐禽”

**Expected behavior**
希望分词之后和原句中的词保持一致
即termList 依然是 ‘“猛禽” 两个字
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): win7
- java version: 1.8 
- HanLP version: 1.7.3

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
![分词](https://user-images.githubusercontent.com/30866940/87658023-35326500-c78e-11ea-9379-f84a10beaab2.png)

* [ ] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://raw.githubusercontent.com/hankcs/HanLP/master/.github/ISSUE_TEMPLATE/bug_report.md)认真修改，然后耐心等待下周末处理。
如果您提的是bug或feature request，那么请您按模板认真改一改，reopen这个issue。
否则，咨询类的问题请先搜索一下。99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。
如果您不修改的话，恐怕没有人能够回复您，我们也会错失一次改进的机会或者一次友好的讨论。开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。

**Comment by qqxhb** [comment]
> 【自动回复】您好，感谢反馈。
> 由于未按要求填写，本issue被自动关闭。请按[issue模板](https://raw.githubusercontent.com/hankcs/HanLP/master/.github/ISSUE_TEMPLATE/bug_report.md)认真修改，然后耐心等待下周末处理。
> 如果您提的是bug或feature request，那么请您按模板认真改一改，reopen这个issue。
> 否则，咨询类的问题请先搜索一下。99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。
> 如果您不修改的话，恐怕没有人能够回复您，我们也会错失一次改进的机会或者一次友好的讨论。开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。

模本中的所有要素都包含了，不知您说的是哪儿不符合要求？
