### ISSUE TITLE
分词之后词和原文不一致，分词之后有的汉字和原文中不一致

### ISSUE THREAD

**Issue by qqxhb** [hankcs/HanLP#1509]
**Describe the bug**

分词之后词和原文不一致，分词之后有的汉字和原文中不一致示例源码如下。

**Code to reproduce the issue**

```java
String paragraph ="客观来讲，这一价格与福特猛禽相比有着不小优势，但当疫情刚刚过去，国人会花20万元买一辆皮卡吗？";
Segment  segment = HanLP.newSegment().enableCustomDictionaryForcing(true).enableIndexMode(true).enableMultithreading(true);
  List<Term> termList = segment.seg(paragraph);
```

**Describe the current behavior**

 分词之后termList 中 ‘“猛禽”  变成了  “勐禽”

**Expected behavior**

希望分词之后和原句中的词保持一致
即termList 依然是 ‘“猛禽” 两个字

**System information**

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): win7
- java version: 1.8 
- HanLP version: 1.7.3

**Other info / logs**
最后的分词结果，在下面的截图中，可以看到。
![分词](https://user-images.githubusercontent.com/30866940/87658023-35326500-c78e-11ea-9379-f84a10beaab2.png)

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
关闭下列配置：

https://github.com/hankcs/HanLP/blob/82a48f9eaa1b0286ee2f2bd6b3a61b0fc7b50ef5/src/main/java/com/hankcs/hanlp/HanLP.java#L208-L211

**Comment by qqxhb** [comment]
> 关闭下列配置：
> 
> https://github.com/hankcs/HanLP/blob/82a48f9eaa1b0286ee2f2bd6b3a61b0fc7b50ef5/src/main/java/com/hankcs/hanlp/HanLP.java#L208-L211

谢谢。
