### ISSUE TITLE
HanLP.java访问资源文件使用绝对路径的问题

### ISSUE THREAD

**Issue by zxxvscs** [hankcs/HanLP#1510]
您好，最近在使用Hanlp过程中遇到了一些问题。我用的是java 的 1.7.7版本，在加载HanLP的资源文件时，我发现源码里用的都是绝对路径的方式，而不是inputstream的方式访问文件，这导致我在引用的时候，出现了跨jar包的问题。当然我可以将data资源文件放到您提示的 根目录（或tomcat其它）也可以访问。我想问下，HanLP.java 这个文件在加载资源的时候，有没有更新使用inputstream的方式呢？我在论坛找不到相关问题，在此来提问了！

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被暂时标记为无效。请按[issue模板](https://raw.githubusercontent.com/hankcs/HanLP/master/.github/ISSUE_TEMPLATE/bug_report.md)认真修改，然后耐心等待下周末处理。
如果您提的是bug或feature request，那么请您按模板认真改一改，reopen这个issue。
否则，咨询类的问题请先搜索一下。99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。
如果您不修改的话，恐怕没有人能够回复您，我们也会错失一次改进的机会或者一次友好的讨论。开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
