### ISSUE TITLE
如何设置切分词的长度，比如只想获取2-5之间的词结果

### ISSUE THREAD

**Issue by 991697456** [hankcs/HanLP#1514]
**Describe the feature and the current behavior/state.**

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Are you willing to contribute it (Yes/No):**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version:
- HanLP version:

**Any other info**

* [ ] I've carefully completed this form.

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form then reopen it.

**Comment by 991697456** [comment]
<dependency>
		    <groupId>com.hankcs</groupId>
		    <artifactId>hanlp</artifactId>
		    <version>portable-1.7.6</version>
		</dependency>
