### ISSUE TITLE
输入一个词语，要求返回与这个词相关的词语。除了词向量聚类还有别的方法吗

### ISSUE THREAD

**Issue by csw9270** [hankcs/HanLP#1516]
**Describe the feature and the current behavior/state.**
求一种能够处理标题所说任务的方法，只需要思路就可以。
**Will this change the current api? How?**
如果我可以完成这个功能，会开源代码并贡献给这个项目
**Who will benefit with this feature?**
We
**Are you willing to contribute it (Yes/No):**
Yes
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version:
- HanLP version:

**Any other info**

* [x] I've carefully completed this form.

**Comment by hankcs** [comment]
你可以了解一下WordNet/HowNet，其中的上下位关系比词向量的层次聚类更精准，一词多义是词向量无法捕捉的。

**Comment by JohnWHYH** [comment]
word2vec 你可以尝试一下
