### ISSUE TITLE
python使用pyhanlp无tests.test_utility模组

### ISSUE THREAD

**Issue by Bunnypark** [hankcs/HanLP#1521]
**Describe the feature and the current behavior/state.**
您好。本人为入门者，尝试过直接使用命令安装总是出错，于是直接下载的hanlp代码放到python文件夹下，能够成功调用。
**Will this change the current api? How?**
但是后续学习需要使用到from tests.test_utility import ensure_data。但提示无该模组。
**Who will benefit with this feature?**
请问如何解决？
**Are you willing to contribute it (Yes/No):**
Yes
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows10 x64
- Python version:3.8.5
- HanLP version:0.1.61

**Any other info**
None
* [ ] I've carefully completed this form.
Yes

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://raw.githubusercontent.com/hankcs/HanLP/master/.github/ISSUE_TEMPLATE/bug_report.md)认真修改，然后耐心等待下周末处理。
如果您提的是bug或feature request，那么请您按模板认真改一改，reopen这个issue。
否则，咨询类的问题请先搜索一下。99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。
如果您不修改的话，恐怕没有人能够回复您，我们也会错失一次改进的机会或者一次友好的讨论。开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
