### ISSUE TITLE
手动安装的pyhanlp无tests.test_utility模组

### ISSUE THREAD

**Issue by Bunnypark** [hankcs/HanLP#1522]
**Describe the feature and the current behavior/state.**
自动安装失败，使用手动安装，from pyhanlp import *可以成功调用hanlp
**Will this change the current api? How?**
但是后续学习遇到了这个代码——from tests.test_utility import ensure_data
**Who will benefit with this feature?**
提示不存在这个模组，请问如何解决？
**Are you willing to contribute it (Yes/No):**
yes
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version:
- HanLP version:

**Any other info**

* [x] I've carefully completed this form.

**Comment by hankcs** [comment]
https://bbs.hankcs.com/
