### ISSUE TITLE
1.7.8版本缺少com.hankcs.hanlp.utility.TestUtility;类。

### ISSUE THREAD

**Issue by 56600535** [hankcs/HanLP#1524]
## 在使用1.7.8版本时，使用文本分类功能发现 缺少com.hankcs.hanlp.utility.TestUtility;类。
![image](https://user-images.githubusercontent.com/49943200/89723278-b2b46280-da26-11ea-8a8c-eab4d1dcf3b0.png)

在文档中并没有找到有说关于替换此类的说明

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，咨询类的问题请先搜索一下。99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

如果您不修改的话，恐怕没有人能够回复您，我们也会错失一次改进的机会或者一次友好的讨论。开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
