### ISSUE TITLE
hanlp句子依存结构分析问题

### ISSUE THREAD

**Issue by kingoftheerath** [hankcs/HanLP#1529]
**Describe the bug**
hanlp句子依存结构分析好像有点问题

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```java
```

**Describe the current behavior**
句子依存结构分析好像不太对，比如：小明去市场买菜
分析结果为：1:[小明:nz->去:vf]:SBV; -1:[去:vf->null]:HED; 3:[市场:n->买菜:nz]:ATT; 1:[买菜:nz->去:vf]:VOB
结果是：主  谓  定语 宾语
结果不应该是：主  谓  宾语  宾补 吗

**Expected behavior**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version:
- HanLP version:1.7.8

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [ ] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，咨询类的问题请先搜索一下。99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

如果您不修改的话，恐怕没有人能够回复您，我们也会错失一次改进的机会或者一次友好的讨论。开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
