### ISSUE TITLE
模型优化问题

### ISSUE THREAD

**Issue by arcral** [hankcs/HanLP#1534]
**Describe the feature and the current behavior/state.**
我想问一下是否可以考虑使用tensorflow-lite或者openvino作为推理后端，这样的话可以避免依赖整个tensorflow或pytorch库，也能提高加载速度，对于gpu资源不是很丰富的用户也更加友好，能够提升桌面cpu端的推理速度。
如果使用transformer的话，是否可以使用模型蒸馏减少堆叠层数（例如, DistilBert），同样能提升推理速度

**Will this change the current api? How?**
no

**Who will benefit with this feature?**
everyone who use this

**Are you willing to contribute it (Yes/No):**
可以做，但是可能没有足够的资源做

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version:
- HanLP version:

**Any other info**

* [ ] I've carefully completed this form.

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

如果您不修改的话，恐怕没有人能够回复您，我们也会错失一次改进的机会或者一次友好的讨论。开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
