### ISSUE TITLE
hanlp需要增加hdfs路径读取功能

### ISSUE THREAD

**Issue by sjyttkl** [hankcs/HanLP#1548]
**Describe the feature and the current behavior/state.**
hanlp需要增加hdfs路径读取功能
**Will this change the current api? How?**
 增加hdfs IOAdapter 
**Who will benefit with this feature?**
增强功能的适用性，不然每次修改词典，还需要重新打包；在公司大数据环境下里是不合适的
**Are you willing to contribute it (Yes/No):**
yes
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):   linux 、 Distribution
- Python version: none
- HanLP version:  portable1.7.8

**Any other info**
hanlp java版本，需要增加hdfs 的操作。如果只是把字典，或者模型放在 jar里太大了。
希望可以授予分支权限，我已经写完代码了。让我提交下分支吧。谢谢。🙏
* [x] I've carefully completed this form.

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被暂时标记为无效。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

如果您不修改的话，恐怕没有人能够回复您，我们也会错失一次改进的机会或者一次友好的讨论。开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。

**Comment by hankcs** [comment]
Hi, 请勾选最后的单选框。

**Comment by sjyttkl** [comment]
ok

**Comment by hankcs** [comment]
目前IOAdapter是通过配置文件指定然后反射创建的，这么做的目的之一是避免引入各种依赖。您引入了Hadoop依赖吗？

**Comment by hankcs** [comment]
对你的开源精神表示感谢，但如果你按现有的设计去做，你试图解决的问题并不存在。
