### ISSUE TITLE
加载bin模型，提示outofmemory

### ISSUE THREAD

**Issue by liuxialong** [hankcs/HanLP#155]
但加载txt模型没有问题.
环境：mac，idea
－xms也调的很大，不是－xms的问题。
crf＋＋版本0.53

**Comment by hankcs** [comment]
请给出jar版本和data版本以及加载代码。

**Comment by liuxialong** [comment]
1、maven引用
   <dependency>
      <groupId>com.hankcs</groupId>
      <artifactId>hanlp</artifactId>
      <version>portable-1.2.8</version>
    </dependency>

2、模型版本
version: 100
cost-factor: 1
maxid: 5326970
xsize: 1

用的CRF＋＋版本为：0.53

3、调用代码：
import com.hankcs.hanlp.model.crf.CRFModel;
    public static CRFModel crfModel;

       String path = "model.v5";
        //System.out.print(path);
        crfModel = CRFModel.loadBin(path); //这里如果换成loadTxt,模型换成txt模型就不会报错。

请帮忙看下，谢谢

**Comment by hankcs** [comment]
https://github.com/hankcs/HanLP/wiki/FAQ#%E4%B8%BA%E4%BB%80%E4%B9%88%E5%8A%A0%E8%BD%BD%E6%88%91%E8%87%AA%E5%B7%B1%E8%AE%AD%E7%BB%83%E7%9A%84crf%E6%A8%A1%E5%9E%8B%E5%A4%B1%E8%B4%A5%E4%BA%86

**Comment by hankcs** [comment]
/**
     * 加载Bin形式的CRF++模型<br>
     *     注意该Bin形式不是CRF++的二进制模型,而是HanLP由CRF++的文本模型转换过来的私有格式
     * @param path
     * @return
     */
    public static CRFModel loadBin(String path)
