### ISSUE TITLE
HanLP 2.0词性标注集哪里可以找到？只能搜到小写的1.x版本的

### ISSUE THREAD

**Issue by hz7715** [hankcs/HanLP#1554]
求助，HanLP 2.0词性标注集哪里可以找到？
2.0的词性标注都换成了大写字母: CC, VV, DEG, PU, CD等等，我想知道每一个对应什么词性

找了一大圈没有找到2.0对应的标注集。。只搜到了1.x的：http://www.hankcs.com/nlp/part-of-speech-tagging.html#h2-8

万分感谢！

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version: 3.7
- HanLP version: 2.0

**Any other info**

* [ ] I've carefully completed this form.

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被暂时标记为无效。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

如果您不修改的话，恐怕没有人能够回复您，我们也会错失一次改进的机会或者一次友好的讨论。开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
