### ISSUE TITLE
HanLP 2.0词性标注集（中英文）何时可以公布文档？想知道DEG, PU, CD等标注分别对应什么词性

### ISSUE THREAD

**Issue by hz7715** [hankcs/HanLP#1555]
**Describe the feature and the current behavior/state.**
求助，HanLP 2.0词性标注集（中英文）哪里可以找到？
2.0的词性标注都换成了大写字母: CC, VV, DEG, PU, CD等等，我想知道每一个对应什么词性

找了一大圈没有找到2.0对应的标注集。。只搜到了1.x的：http://www.hankcs.com/nlp/part-of-speech-tagging.html#h2-8

万分感谢！

**Will this change the current api? How?**
不会影响api，但是为了便于使用的话，还是很需要这个标注集。。

**Who will benefit with this feature?**
所有使用方

**Are you willing to contribute it (Yes/No):**
Yes

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version:3.7
- HanLP version:2.0

**Any other info**
感谢作者的共享！
* [x] I've carefully completed this form.

**Comment by hankcs** [comment]
最近非常忙，实在没时间写文档。可能在下一个长假之前，文档会一直没时间写。不过你可以根据模型名称前面的语料库标示符（CTB，HanLP会使用很多种语料库）搜索到对应的资料，比如CTB的：

https://www.cs.brandeis.edu/~clp/ctb/posguide.3rd.ch.pdf

**Comment by hankcs** [comment]
https://hanlp.hankcs.com/docs/annotations/index.html
