### ISSUE TITLE
hanlp.pretrained.sdp.SEMEVAL16_NEWS_BIAFFINE_ZH无法使用

### ISSUE THREAD

**Issue by silencemaker** [hankcs/HanLP#1559]
**Describe the bug**
语法依存分析时无法下载SEMEVAL16_NEWS_BIAFFINE_ZH模型，提示更新hanlp到2.0.0的方法不可用
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
syntactic_parser = hanlp.load(hanlp.pretrained.sdp.SEMEVAL16_NEWS_BIAFFINE_ZH)
```

**Describe the current behavior**
A clear and concise description of what happened.
想要使用syntactic_parser 进行语法的依存分析
**Expected behavior**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux centos 3.10.0-1062.4.1.el7.x86_64 
- Python version:3.7.4
- HanLP version:2.0.0a60

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
https://file.hankcs.com/hanlp/sdp/semeval16-news-biaffine_20191231_235407.zip was created with hanlp-2.0.0, while you are running a lower version: 2.0.0-alpha.60. 
Please upgrade hanlp with:
pip install --upgrade hanlp
If the problem still persists, please submit an issue to https://github.com/hankcs/HanLP/issues .
When reporting an issue, make sure to paste the FULL ERROR LOG above.
* [ ] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

如果您不修改的话，恐怕没有人能够回复您，我们也会错失一次改进的机会或者一次友好的讨论。开源项目维护不易，HanLP用户以十万计，而主要维护者只有我一人。我有自己的full-time研究工作，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
