### ISSUE TITLE
修改了hanlp.properties第一行的目录指向DATA的父目录，还是不能用句法分析

### ISSUE THREAD

**Issue by mjc0819** [hankcs/HanLP#156]
jpype._jexception.LinkageErrorPyRaisable: java.lang.ExceptionInInitializerError
句法分析运行的时候报这个错误，请问怎么解决呀。
-Djava.class.path=C:\hanlp\hanlp-1.2.8.jar;C:\hanlp 这是HanLP.jar和HanLP.properties的位置。
root=C:/hanlp1  这是DATA的父目录。

C:\Users\***\workspacex86\python1\src 这是项目的目录
请问要怎么解决呢，多谢了~

**Comment by hankcs** [comment]
请给出全部堆栈错误日志

**Comment by mjc0819** [comment]
Traceback (most recent call last):
  File "C:\Users\***\workspacex86\python1\src\test.py", line 35, in <module>
    print(HanLP.parseDependency("徐先生还具体帮助他确定了把画雄鹰、松鼠和麻雀作为主攻目标。"))
jpype._jexception.LinkageErrorPyRaisable: java.lang.ExceptionInInitializerError
请问是这个吗

**Comment by hankcs** [comment]
这还不够，需要能定位到Java的stack trace

**Comment by hankcs** [comment]
一般这类问题都是路径配置错误引起的，但你没找到输出的警告日志。这个问题没什么意思。
