### ISSUE TITLE
Cannot process Supplementary Character in Java / 无法在Java中处理Supplementary字符

### ISSUE THREAD

**Issue by hurui200320** [hankcs/HanLP#1563]
**Describe the bug**
When handling supplementary character, HanLP(I tested with pinyin and word segmentation) couldn't handle the supplementary character properly. For short. Java represent a unicode character > 0xFFFF as two sepeprate char, thus HanLP treat them as two seperate Chinese character when getting Pinyin on it. However, those chars not assigned to any validate charset, so the pinyin result would be two 'none', rather than one 'none'.

Word segmentation cannot recognize it, but would always keep them as a word.

处理[Supplementary字符](https://www.oracle.com/technical-resources/articles/javase/supplementary.html)时，HanLP（我测试了拼音标注和分词）似乎没法恰当的处理Supplementary字符。简单地说，Java将0xFFFF以上的Unicode字符表示为两个char，因此HanLP在标注拼音的时候会将其视为两个独立的汉字。然而这些char的值特意的没有指定给任意有效的字符集，因此拼音标注的结果是两个'none'，而不是一个'none'

分词也并不能识别这种字符，但是分词总会确保这些字符是一个词，结果中不会产生破碎的char。

**Code to reproduce the issue**

```kotlin
println(HanLP.convertToPinyinList("鼖").map { it.pinyinWithToneMark })
```

**Describe the current behavior**
Get: `[none, none]`
`鼖` would be represent as `\uD87E\uDE1B` in Java, none of them is validate Chinese character. So got 2 `none`.
`鼖`在Java中被表示为 `\uD87E\uDE1B`，每一个单独的char都不是有效的中文字符，因此得到了两个`none`。

**Expected behavior**
Should get: `[fén]`, or at least a `[none]`

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 2004
- Java version: Java11
- HanLP version: 1.7.8

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [ ] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

如果您不修改的话，恐怕没有人能够回复您，我们也会错失一次改进的机会或者一次友好的讨论。开源项目维护不易，HanLP用户以十万计，而主要维护者只有我一人。我有自己的full-time研究工作，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
