### ISSUE TITLE
Which word segmentation is faster in python or java

### ISSUE THREAD

**Issue by Key2Love** [hankcs/HanLP#1565]
**Describe the feature and the current behavior/state.**
I want to try HanLP in spark in scala(in scala, i can directly use HanLP Java version 1.x) or pyspark(HanLP 2.x), the dataset is billion level, so i want to know  which one is better
**Will this change the current api? How?**
No
**Who will benefit with this feature?**
No
**Are you willing to contribute it (Yes/No):**
No
**System information**
- OS Platform and Distribution : Linux Ubuntu 16.04
- Python version: 3.7
- HanLP version: 2.x in Python, 1.x in Java
- Scala version: 2.11.x
- Java version: 1.8

**Any other info**
thank you for your support, i tried to find the post button in its bbs but couldn't find it. BTW, hava a happy national day!
* [ ] I've carefully completed this form.

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form when open a new issue.
