### ISSUE TITLE
安装错误

### ISSUE THREAD

**Issue by hyliush** [hankcs/HanLP#1567]
**Describe the bug**
安装错误
ERROR: Command errored out with exit status 1: 'E:\ANACONDA\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\RUBYEE~1\\AppData\\Local\\Temp\\pip-install-u00y0kxk\\fasttext\\setup.py'"'"'; __file__='"'"'C:\\Users\\RUBYEE~1\\AppData\\Local\\Temp\\pip-install-u00y0kxk\\fasttext\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\RUBYEE~1\AppData\Local\Temp\pip-record-aebnzzte\install-record.txt' --single-version-externally-managed --compile --install-headers 'E:\ANACONDA\Include\fasttext' Check the logs for full command output.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
pip install hanlp

```python
```

**Describe the current behavior**
A clear and concise description of what happened.
安装命令出现错误
**Expected behavior**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version: 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]
- HanLP version:

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [ ] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

如果您不修改的话，恐怕没有人能够回复您，我们也会错失一次改进的机会或者一次友好的讨论。开源项目维护不易，HanLP用户以十万计，而主要维护者只有我一人。我有自己的full-time研究工作，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
