### ISSUE TITLE
依存树结构错误，存在多个成分与root构成语义关系，破坏了一个句子中只有一个成分是核心成分的原则。

### ISSUE THREAD

**Issue by glacierck** [hankcs/HanLP#1571]
**Describe the bug**
中文依存分析存在多个成分与root构成语义关系的情况，这破坏了一个句子中只有一个成分是核心成分的原则。
语义依存分析是建立在依存语法（Dependency Grammar，DG）基础上，依存语法描述了句子中词与词之间的依存结构，法国语言学家Robinson将依存语法总结为以下四个原则：
1. 一个句子中只有一个成分是核心成分
2. 其他成分直接依存于某一成分
3. 任何成分不能依存于两个或两个以上的成分
4. 依存成分之间不能有交叉

与运行环境、版本、准确率无关。看了作者了博文，内容、截图基本与LTP一致、但为何实际设计中没有坚持这些原则？
测试贴图：
![image](https://user-images.githubusercontent.com/21599896/95830632-91475e00-0d6a-11eb-9b67-fdf680982a10.png)
作者github上的图：
![image](https://user-images.githubusercontent.com/21599896/95830784-cc499180-0d6a-11eb-8427-4882dc7b6161.png)

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

开源项目维护不易，HanLP用户以十万计，而主要维护者只有我一人。我有自己的full-time研究工作，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
