### ISSUE TITLE
load LARGE_ALBERT_BASE 失败

### ISSUE THREAD

**Issue by v-juma1** [hankcs/HanLP#1576]
**Describe the bug**
1. <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)>
**Code to reproduce the issue**
tokenizer = hanlp.load('LARGE_ALBERT_BASE')
```
```

**Describe the current behavior**
加载LARGE_ALBERT_BASE模型时报如上错误,貌似是需要在访问https之前验证SSL证书，是否可以加到load方法中？
**Expected behavior**
加载模型报错

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):mac os
- Python version:3.6.0
- HanLP version:2.0.0a64

**Other info / logs**
发生异常: URLError
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)>
  File "/Users/majun/Desktop/albert_predict_estimator/src/get_attr.py", line 11, in <module>
    tokenizer = hanlp.load('LARGE_ALBERT_BASE')

* [ ] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

开源项目维护不易，HanLP用户以十万计，而主要维护者只有我一人。我有自己的full-time研究工作，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
