### ISSUE TITLE
spark-shell中无法分布式执行依存句法分析

### ISSUE THREAD

**Issue by jimmy-walker** [hankcs/HanLP#1578]
**Describe the bug**
spark-shell中只能本地使用hanlp的依存句法功能，在udf或分区中无法使用。

**Code to reproduce the issue**
报错信息：`Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.hankcs.hanlp.tokenizer.NLPTokenizer`

```scala
import com.hankcs.hanlp.HanLP
import com.hankcs.hanlp.corpus.io.IIOAdapter
import java.io._;
import org.apache.hadoop.conf.Configuration;
import org.apache.hadoop.fs.FileSystem;
import org.apache.hadoop.fs.Path;
import com.hankcs.hanlp.utility.Predefine
import java.net.URI;
Predefine.HANLP_PROPERTIES_PATH = "/data1/XXXX/file/upload/hanlp.properties"

class HadoopFileIoAdapter extends IIOAdapter {
    @Override
    def open(path: String): java.io.InputStream = {
        val conf: Configuration = new Configuration();
        val fs: FileSystem = FileSystem.get(URI.create(path), conf);
        fs.open(new Path(path));
    }   
 
    @Override
    def create(path: String): java.io.OutputStream = {
        val conf: Configuration = new Configuration();
        val fs: FileSystem = FileSystem.get(URI.create(path), conf);
        fs.create(new Path(path));
    }
}
HanLP.Config.IOAdapter = new HadoopFileIoAdapter();
HanLP.parseDependency("徐先生还具体帮助他确定了把画雄鹰、松鼠和麻雀作为主攻目标。")

val keyword_hanlp = udf{(kw: String) =>
  HanLP.parseDependency(kw).toString
}

val df_test = df_final.withColumn("hanlp", keyword_hanlp($"kw"))
df_test.select("kw", "hanlp").show
```

**Describe the current behavior**
我试着在spark-shell中加载portable包’hanlp-portable-1.7.8.jar’，并且将data放到hdfs上，配置了hanlp.properties和ioadapter。
本地进行依存句法是可以执行的。但是运用udf或分布式执行就会报错：`Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.hankcs.hanlp.tokenizer.NLPTokenizer`

**Expected behavior**
希望不要报错，udf顺利执行

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Spark version: 2.4.5
- HanLP version:1.7.8

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
`Predefine.HANLP_PROPERTIES_PATH = "/data1/XXXX/file/upload/hanlp.properties"`是一种硬编码的用法，它强制每个节点从该节点的`/data1/XXXX/file/upload/hanlp.properties`读取配置文件，那么你有在每个节点上存放该配置文件吗？非要硬编码的话不如在你的open方法里为每个path头部拼接一下root。

配置文件应当放在spark启动时的classpath目录，或者打包到具体业务的jar中。
