### ISSUE TITLE
麻烦给CRFSegmenter添加流的读取方式，方便直接从jar包里直接读取bin文件

### ISSUE THREAD

**Issue by xiaoheizai** [hankcs/HanLP#1580]
**Describe the feature and the current behavior/state.**

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Are you willing to contribute it (Yes/No):**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version:
- HanLP version:

**Any other info**

* [x] I've carefully completed this form.

**Comment by hankcs** [comment]
已经有了。
