### ISSUE TITLE
依存句法分析结果存在依存环、无虚根root的问题，不满足公理

### ISSUE THREAD

**Issue by pinkw** [hankcs/HanLP#1582]
依存句法分析结果中，存在依存环以及无root的情况，不满足四条公理

使用以下语句可以复现问题：

紧抓EPC发展趋势平台建设助力降本增效装饰工程总承包（EPC）因其可以降低管理难度、缩短工期、减少建筑成本，同时提高施工效率与质量，为各方创造更多的经济价值的优势而成为建筑业未来的发展主流趋势，也因此成为公司重点培育的业务板块，并将成为公司新的业务增长极。

**System information**
- OS Platform and Distribution:  Linux Ubuntu 18.04
- Python version: 3.7
- HanLP version: 2.0.0a66

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

开源项目维护不易，HanLP用户以十万计，而主要维护者只有我一人。我有自己的full-time研究工作，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
