### ISSUE TITLE
请求增加主动初始化功能

### ISSUE THREAD

**Issue by yidasanqian** [hankcs/HanLP#1584]
**Describe the feature and the current behavior/state.**
第一次调用分词：NLPTokenizer.segment(word)，耗时5s左右
**Will this change the current api? How?**
no
**Who will benefit with this feature?**
quoter
**Are you willing to contribute it (Yes/No):**
no

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows
- Python version:
- HanLP version: 1.7.5

**Any other info**

* [x] I've carefully completed this form.

**Comment by hankcs** [comment]
NLPTokenizer.segment(“这就是初始化”);

**Comment by yidasanqian** [comment]
不能单独把初始化功能提取到一个方法里吗，只能分词才初始化？

**Comment by hankcs** [comment]
那就直接 new 

https://github.com/hankcs/HanLP/blob/1.x/src/main/java/com/hankcs/hanlp/tokenizer/NLPTokenizer.java#L39

**Comment by hankcs** [comment]
就一句话的事，何必专门做个方法
