### ISSUE TITLE
调用了分词的接口，发现我的程序无法写文件了

### ISSUE THREAD

**Issue by oftenliu** [hankcs/HanLP#1587]
**Describe the bug**
调用了分词的接口，发现我的程序无法写文件了

**Code to reproduce the issue**

token = load('LARGE_ALBERT_BASE')
output = token('商品和服务')
fd = open('output.txt','w')

for item in output:
fd.write(item+'\n')

**Describe the current behavior**
A clear and concise description of what happened.

**Expected behavior**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 16.04
- Python version:3.6.8
- HanLP version:2.0.0-alpha.67

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
Hi，

1. 尽量避免 `from hanlp import *`
2. 测试无此问题，请参考 https://colab.research.google.com/drive/1PosehrI1-r7Q3Qnsq6nYc0tdvxLXm3Yu?usp=sharing

**Comment by oftenliu** [comment]
hi，我跑了你的程序，但是在我机器上还是同样的bug

Python 3.6.2 (v3.6.2:5fd33b5926, Jul 16 2017, 20:11:06) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import hanlp
>>> tokenizer = hanlp.load(hanlp.pretrained.cws.LARGE_ALBERT_BASE)
2020-12-01 15:40:32.486682: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-12-01 15:40:32.505188: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x14b0ae9b0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-12-01 15:40:32.505215: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
>>> print(tokenizer('商品和服务'))
['商品', '和', '服务']
>>> fd = open('1.txt','w')
>>> fd.write('good')
4
>>> open('1.txt','r').read()
''
>>>

**Comment by hankcs** [comment]
挺不可思议的，HanLP本身没有hook文件IO。我能想到的原因可能有：

1. 你的磁盘被某个进程定时清理了，比如你的当前路径是tmp之类。
1. 不太清楚你的机器上什么包与TensorFlow发生了冲突，你可以试试用conda创建一个干净的环境再一个一个安装你需要的包去排查。

**Comment by hankcs** [comment]
> hi，我跑了你的程序，但是在我机器上还是同样的bug
> 
> ```
> >>> import hanlp
> >>> fd = open('1.txt','w')
> >>> fd.write('good')
> 4
> >>> open('2.txt','r').read()
> 'good'
> >>> tokenizer = hanlp.load(hanlp.pretrained.cws.LARGE_ALBERT_BASE)
> >>> print(tokenizer('商品和服务'))
> ['商品', '和', '服务']
> >>> fd = open('3.txt','w')
> >>> fd.write('good')
> 4
> >>> open('3.txt','r').read()
> ''
> >>> 
> ```

刚才又发现你的代码里又有一个问题，你写文件之后没有close，操作系统不一定flush到磁盘。你应该

```
fd = open('3.txt','w')
fd.write('good')
fd.close()
```
