### ISSUE TITLE
module 'tensorflow.python.keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'

### ISSUE THREAD

**Issue by learnpythontheew** [hankcs/HanLP#1588]
**Describe the bug**

报错 ： module 'tensorflow.python.keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
import hanlp
```

**Describe the current behavior**
安装了graphviz 之后 再运行 代码开始报错，卸载掉graphviz 重新安装 tensorflow对应版本依然报错。

**Expected behavior**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux 18.4
- Python version:3.6
- HanLP version:2.0.0a67

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
你的tf版本不对，请重新 `pip install hanlp -U`
