### ISSUE TITLE
TypeError: build_callbacks() got multiple values for argument 'logger'

### ISSUE THREAD

**Issue by callzhang** [hankcs/HanLP#1589]
**Describe the bug**
TypeError: build_callbacks() got multiple values for argument 'logger'

**Code to reproduce the issue**
```
import hanlp
from hanlp.datasets.classification.sentiment import CHNSENTICORP_ERNIE_TRAIN, CHNSENTICORP_ERNIE_TEST, CHNSENTICORP_ERNIE_VALID

classifier = hanlp.load('LARGE_ALBERT_BASE')

# Train classifer
classifier.fit(CHNSENTICORP_ERNIE_TRAIN, CHNSENTICORP_ERNIE_VALID, save_dir, transformer='albert_large_zh')

```

**Describe the current behavior**
TypeError: build_callbacks() got multiple values for argument 'logger'

**Expected behavior**
Model got trained

**System information**

**Other info / logs**
In `components.py`L326, it is trying to create a redundant logger, which caused this problem. Please take a look 

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
Thanks, this bug has been resolved. 

BTW, your code doesn't make sense since `LARGE_ALBERT_BASE ` is a tokenization model while `CHNSENTICORP_ERNIE_*` is a document classification corpus.

**Comment by callzhang** [comment]
I see. Thanks. Now I used this code to train:
```
classifier = TransformerClassifier(TransformerTextTransform(y_column=0))
classifier.fit(TRANIN_SET, DEV_SET, save_dir,
               transformer='albert_base_zh', batch_size=64)
```
Does this make sense?

**Comment by hankcs** [comment]
Yes. Feel free to read our [training scripts](https://github.com/hankcs/HanLP/tree/master/tests/train).

**Comment by callzhang** [comment]
Thank you! Can I train multi-label classification using HanLP?

**Comment by hankcs** [comment]
Currently no multi-label implementation. But it's very trivial to modify a multi-class classifier into a  multi-label one. Just need to replace `softmax` with `sigmoid`.

**Comment by hankcs** [comment]
Loss to be `BinaryCrossentropy`:

https://github.com/hankcs/HanLP/blob/bcd7ec73eefd11a76145e02caa61477f398b8623/hanlp/components/classifiers/transformer_classifier.py#L129

Prediction to be `Y > 0`:

https://github.com/hankcs/HanLP/blob/bcd7ec73eefd11a76145e02caa61477f398b8623/hanlp/components/classifiers/transformer_classifier.py#L83

Dataset in .tsv format: `x_columns`: at most 2 columns being a sentence pair while in most cases just one column being the doc content. `y_column` being the single label, which shall be modified to load a list of labels.

https://github.com/hankcs/HanLP/blob/ca50edb77f744187bd8b45e05cb268eba6c2ef7f/hanlp/transform/table.py#L31-L40

When multi labels are encoded, the tensor shaple should be `[num_labels]`. There might be other places needed to be slightly changed, but they should also be very trivial. I'm not sure how familiar you are with TensorFlow, but our codes should be very easy to extend for deep learning researchers.

**Comment by callzhang** [comment]
Really appreciated! Your reply is very helpful. Let me try it tomorrow. Good night!

**Comment by callzhang** [comment]
@hankcs I think you should use `SparseCategoricalCrossentropy` for multi-label/multi-class classification. 
[doc](https://www.tensorflow.org/api_docs/python/tf/keras/metrics/SparseCategoricalCrossentropy)

**Comment by hankcs** [comment]
tf `sigmoid_cross_entropy_with_logits ` should be equivalent to keras  `BinaryCrossentropy `. That's a downside of tf2, you got multiple APIs for the same function.

**Comment by callzhang** [comment]
Thanks. Another question: how to adapt the output_type to the list of multi-label? Here it was tf.string. 
```
def create_types_shapes_values(self) -> Tuple[Tuple, Tuple, Tuple]:
        max_length = self.config.max_length
        types = (tf.int32, tf.int32, tf.int32), **tf.string**
```

**Comment by hankcs** [comment]
Type has to be tf.string. Shape has to be a vector of shape `(None,)`. You can consult TF's manual or refer to HanLP's tagger code where tags are a vector of tf.string.

**Comment by callzhang** [comment]
I think the problem is in `label_vocab`'s lookup method, where list type of labels is not handled.
https://github.com/hankcs/HanLP/blob/c46dc719ce1ad2e64d793eedce5f7f641592f7b7/hanlp/common/vocab.py#L186-L189
However, I wasn't able to change it because the code run in tf runtime and the `token_tensor` cannot be viewed using `token_tensor.numpy()`. Can you provide insight on how to fix it?

**Comment by callzhang** [comment]
Need help! I got `Can not squeeze dim[1], expected a dimension of 1, got 25 [Op:Squeeze]` when computing loss using `BinaryCrossentropy`.
The total label counts is 25. And I have padded the Y value with `<pad>` to match the size of 25.
I cannot figure out why it is trying to squeeze the label shape at dim[1]. 
Can you provide some insights?

**Comment by hankcs** [comment]
Your prediction and target should both be of shape `(batch_size, 25)`, where each item is either 0 or 1. You don't pad Y to 25, you create a 25 dim vector for each sample.

**Comment by callzhang** [comment]
I figured out the error, it was due to the metrics, which also has to be changed to `BinaryCrossentropy`. How to create a 25 dim vector without padding? Like this: `[label1, label2, None, None....]`?

**Comment by hankcs** [comment]
A binary vector where label indices are set to 1.
