### ISSUE TITLE
HanLP 1.x 加载 bin 的错误

### ISSUE THREAD

**Issue by zhuyuanxiang** [hankcs/HanLP#1594]
**Describe the bug**
连续加载两次模型时，第二次没有加载而是直接使用第一次加载的模型

**Code to reproduce the issue**

```java
    public static void main(String[] args) {
        // 第一次执行会报出警告，然后会转换 txt 文件为 bin 文件，后面就不再报错
        // 连续执行两次时，第二次使用的是第一次载入的 bin 文件
        // 交换以下现场代码的顺序就可以看到区别
        show_subtitle("my_cws_model");
        trainBigram(MY_CWS_CORPUS_PATH, MY_MODEL_PATH);
        loadBigram(MY_MODEL_PATH);
        show_subtitle("msr_ngram");
        trainBigram(MSR_TRAIN_PATH, MSR_MODEL_PATH);
        loadBigram(MSR_MODEL_PATH);
    }
```

详情可以参考：https://github.com/zhuyuanxiang/Hanlp-Books-Examples/blob/main/src/main/java/ch03/sec03/DemoNgramSegment.java

**Describe the current behavior**
--------------->my_cws_model<---------------
「商品」的词频：2
「商品@和」的频次：1
[商品, 和, 服务]
[货币, 和, 服务]
--------------->msr_ngram<---------------
「商品」的词频：2
「商品@和」的频次：1
[商品, 和, 服务]
[货币, 和, 服务]

**Expected behavior**
--------------->my_cws_model<---------------
「商品」的词频：2
「商品@和」的频次：1
[商品, 和, 服务]
[货币, 和, 服务]
--------------->msr_ngram<---------------
「商品」的词频：1
「商品@和」的频次：0
[商品, 和, 服务]
[货币, 和, 服务]

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Python version:
- Java version: 8.0
- HanLP version: 1.7.8

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
感谢反馈。这个演示的本意是让用户注释掉一个运行另一个的，如果要让程序同时运行两个，得参考上面新加的reload方法。

**Comment by zhuyuanxiang** [comment]
OK.
thks!
感谢你的及时反馈。
