### ISSUE TITLE
CRF模型 地址

### ISSUE THREAD

**Issue by nlpener** [hankcs/HanLP#16]
您好，我是nlp新手，想使用CRF分词，但缺少模型文件，之前提供的地址也已失效，能够重新分享下，谢谢！

**Comment by hankcs** [comment]
你好，我一般会在这里发布新模型：https://github.com/hankcs/HanLP/releases
CTRL + F 搜索 data就能找到。
旧模型可能不兼容，所以就取消分享了。

**Comment by nlpener** [comment]
@hankcs 最新的是data-for-1.2.2不？可是我运行测试CRF分词一直出错，但其他模式的分词均可以正常运行。
出错信息：

    Exception in thread "main" java.lang.NullPointerException
	    at com.hankcs.hanlp.seg.CRF.CRFSegment.segSentence(CRFSegment.java:61)
	    at com.hankcs.hanlp.seg.Segment.seg(Segment.java:144)
	    at com.cn.demo.TestCRFSegment.main(TestCRFSegment.java:16)

**Comment by hankcs** [comment]
0. 把调试模式打开看看。
0. 把jar版本号，hanlp.properties提出来看看。

**Comment by nlpener** [comment]
@hankcs hanlp-1.1.2.jar，properties只修改了root项，指向data的父目录。Debug打开后，table的值拿到

    你   null	
    看	  null	
    过	  null	
    穆	  null	
    赫	  null	
    兰	  null	
    道	  null	
    吗	  null	
再下一步就出错了，应该是CRFSegmentModel没有接收到table。怀疑模型文件是否不匹配之类的，获取的最新模型文件是：data-for-1.2.2/data/model/CRFSegmentModel.txt.bin

**Comment by hankcs** [comment]
你应该使用hanlp-1.2.2.jar，两个版本相差太远了，不兼容的。

**Comment by nlpener** [comment]
@hankcs 我只注意data的版本却忽视了HanLP的版本，不好意思。使用hanlp-1.2.2.jar和data-for-1.2.2，后，测试CRF分词，出现如下错误：

    com.hankcs.hanlp.model.CRFSegmentModel <clinit>
    严重: CRF分词模型加载 D:/Hanlp/data-for-1.2.2/data/model/segment/CRFSegmentModel.mini.txt 失败，耗时 22 ms
看了模型加载来自于HanLP.java 160行：

    public static String CRFSegmentModelPath = "data/model/segment/CRFSegmentModel.mini.txt";
而data中segment目录下CRFSegmentModel文件名为：CRFSegmentModel.txt.bin。

**Comment by hankcs** [comment]
0. 最新版的CRFSegmentModel文件名的确是CRFSegmentModel.txt.bin，这是通过properties配置的。只要你下载了hanlp-1.2.2-release.zip，就能得到正确的配置文件，旧版的配置文件不做修改就会出问题。
0. 这是个很简单的事情，你可以自己修改配置文件。

**Comment by nlpener** [comment]
@hankcs 非常感谢，由于是小白用户，给您添麻烦了。对于CRF分词，想知道内存有限制吗？因为有时候因为内存限制导致提示

    java.lang.OutOfMemoryError: Java heap space

**Comment by hankcs** [comment]
不客气，至少512MB```-Xms512m -Xmx512m -Xmn256m```，毕竟模型就有100多MB，加载到内存中更大。
发生OutOfMemoryError可能是你输入的文本太长了。事实上，如果把一个几MB的文本文件一下子读进来丢给分词器是极其不合理的，你可以按行读取，也可以按句号分割成行，然后分词，或者试试enableMultithreading(int threadNumber)

**Comment by nlpener** [comment]
@hankcs 感谢您的建议

**Comment by ilovejiabao** [comment]
@hankcs 您好，抱歉打扰。 data-for-1.7.5版本的数据包已经不包含CRFSegmentModel.txt.bin文件了吗？如果是这样，我该如何进行CRF分词？
