### ISSUE TITLE
TableTransform中，调用read_cells时所用的参数名，和函数定义中的参数名不一致

### ISSUE THREAD

**Issue by zhufengyun** [hankcs/HanLP#1600]
**Describe the bug**
read_cells函数：在TableTransform中，调用read_cells时所用的参数名，和函数定义中的参数名不一致

**Code to reproduce the issue**
调用的位置：
class TableTransform
def file_to_inputs
for cells in read_cells(filepath, **skip_header**=self.config.skip_header, delimiter=self.config.delimiter)

read_cells函数在io_utils.py中的定义为：
def read_cells(filepath: str, delimiter='auto', strip=True, **skip_first_line**=False)

**Describe the current behavior**
无法调用read_cells

**Expected behavior**
None

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): not related
- Python version: not related
- HanLP version: 2.1.0a0

**Other info / logs**
None

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。
