### ISSUE TITLE
CoreStopWordDictionary.dictionary.clear()空指针

### ISSUE THREAD

**Issue by zerofancy** [hankcs/HanLP#1603]
**Describe the bug**

调用`CoreStopWordDictionary.reload()`后调用`CoreStopWordDictionary.dictionary.clear()`会空指针。

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```java
CoreStopWordDictionary.reload()
CoreStopWordDictionary.dictionary.clear()
```

**Describe the current behavior**
A clear and concise description of what happened.

执行`CoreStopWordDictionary.dictionary.clear()`时`equivalenceClassMDAGNodeHashMap`空指针异常。

**Expected behavior**

正确清空停用词。

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):macOS Big Sur 11.0.1 20B29 x86_64.
- Python version:非python版本
- HanLP version:1.7.8

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

分析原因为`StopWordDictionary.reload()`时执行了`MDAG.simplify()`，其中有`equivalenceClassMDAGNodeHashMap = null;`

`MDAGSet.clear()`方法中`equivalenceClassMDAGNodeHashMap.clear();`没有判空。

相关：[https://github.com/hankcs/HanLP/commit/a57645c739b403b5fe8ae7cba0fb44d0dd992317](https://github.com/hankcs/HanLP/commit/a57645c739b403b5fe8ae7cba0fb44d0dd992317)

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。
