### ISSUE TITLE
自定义词典对KBeamArcEagerDependencyParser无效

### ISSUE THREAD

**Issue by jimmy-walker** [hankcs/HanLP#1604]
**Describe the bug**
添加新词进入自定义词典后，KBeamArcEagerDependencyParser仍然无法对该词进行正确分词。

**Code to reproduce the issue**
添加"申请笔 n 100"进入自定义词典
```scala
val parser = new KBeamArcEagerDependencyParser()
parser.parse("又有新的申请笔可以拿了")
```
```
1      又      又      A       AD      _       2       advmod  _       _
2       有      有      V       VE      _       0       ROOT    _       _
3       新      新      V       VA      _       6       rcmod   _       _
4       的      的      D       DEC     _       3       cpm     _       _
5       申请    申请    N       NN      _       6       nn      _       _
6       笔      笔      N       NN      _       8       nsubj   _       _
7       可以    可以    V       VV      _       8       mmod    _       _
8       拿      拿      V       VV      _       2       dep     _       _
9       了      了      S       SP      _       2       dep     _       _
```

**Describe the current behavior**
即使添加了新词，仍然无法对新词进行正确分词，而另一个接口HanLP.parseDependency可以根据新加入的词进行正确分词

**Expected behavior**
期待能通过加入自定义词典，KBeamArcEagerDependencyParser能够先正确分词，并在此基础上返回正确结果
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux
- Scala version:2.12.2
- HanLP version:1.7.8

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
Hi，KBeamArcEagerDependencyParser的自定义词典是默认关闭的，为了在CTB上面跑分。你可以将其开启：

```java
1	又	又	A	AD	_	2	advmod	_	_
2	有	有	V	VE	_	0	ROOT	_	_
3	新	新	V	VA	_	5	rcmod	_	_
4	的	的	D	DEC	_	3	cpm	_	_
5	申请笔	申请笔	n	nz	_	7	nsubj	_	_
6	可以	可以	V	VV	_	7	mmod	_	_
7	拿	拿	V	VV	_	2	dep	_	_
8	了	了	A	AS	_	7	asp	_	_
9	。	。	P	PU	_	2	punct	_	_
```

**Comment by jimmy-walker** [comment]
> Hi，KBeamArcEagerDependencyParser的自定义词典是默认关闭的，为了在CTB上面跑分。你可以将其开启：
> 
> ```java
> 1	又	又	A	AD	_	2	advmod	_	_
> 2	有	有	V	VE	_	0	ROOT	_	_
> 3	新	新	V	VA	_	5	rcmod	_	_
> 4	的	的	D	DEC	_	3	cpm	_	_
> 5	申请笔	申请笔	n	nz	_	7	nsubj	_	_
> 6	可以	可以	V	VV	_	7	mmod	_	_
> 7	拿	拿	V	VV	_	2	dep	_	_
> 8	了	了	A	AS	_	7	asp	_	_
> 9	。	。	P	PU	_	2	punct	_	_
> ```

@hankcs 感谢您的回复。我按照方法开启了自定义词典，但发现有一个词总是被切错。请问这有什么办法吗？
我设置自己的自定义词典，代替了默认的自定义词典：
```
代表作 NN 1000
· PU 1000
```
但是在KBeamArcEagerDependencyParser下，始终被切分为"作· "，无论我在自定义词典中设置多大的词频，都无法解决这个问题。请问这个应该如何改正呢？

```java
        IDependencyParser parser = new KBeamArcEagerDependencyParser();
        System.out.printf(parser.parse("这是我的代表作").toString());
        System.out.printf(parser.parse("这是我的代表作·").toString());
```

```
1   这   这   P   PN  _   2   top _   _
2   是   是   V   VC  _   0   ROOT    _   _
3   我   我   P   PN  _   5   assmod  _   _
4   的   的   D   DEG _   3   assm    _   _
5   代表作 代表作 N   NN  _   2   attr    _   _

1   这   这   P   PN  _   2   top _   _
2   是   是   V   VC  _   0   ROOT    _   _
3   我   我   P   PN  _   5   assmod  _   _
4   的   的   D   DEG _   3   assm    _   _
5   代表  代表  N   NN  _   6   nsubj   _   _
6   作·  作·  V   VV  _   2   ccomp   _   _
```

**Comment by hankcs** [comment]
你可以把·加到词典里然后enableCustomDictionaryForcing，也可以CharTable['·']='。'

**Comment by jimmy-walker** [comment]
> 你可以把·加到词典里然后enableCustomDictionaryForcing，也可以CharTable['·']='。'

谢谢你。我在看源码时看到了这个方法，感谢。

**Comment by seabiscuityj** [comment]
> > Hi，KBeamArcEagerDependencyParser的自定义词典是默认关闭的，为了在CTB上面跑分。你可以将其开启：
> > ```java
> > 1	又	又	A	AD	_	2	advmod	_	_
> > 2	有	有	V	VE	_	0	ROOT	_	_
> > 3	新	新	V	VA	_	5	rcmod	_	_
> > 4	的	的	D	DEC	_	3	cpm	_	_
> > 5	申请笔	申请笔	n	nz	_	7	nsubj	_	_
> > 6	可以	可以	V	VV	_	7	mmod	_	_
> > 7	拿	拿	V	VV	_	2	dep	_	_
> > 8	了	了	A	AS	_	7	asp	_	_
> > 9	。	。	P	PU	_	2	punct	_	_
> > ```
> 
> @hankcs 感谢您的回复。我按照方法开启了自定义词典，但发现有一个词总是被切错。请问这有什么办法吗？
> 我设置自己的自定义词典，代替了默认的自定义词典：
> 
> ```
> 代表作 NN 1000
> · PU 1000
> ```
> 
> 但是在KBeamArcEagerDependencyParser下，始终被切分为"作· "，无论我在自定义词典中设置多大的词频，都无法解决这个问题。请问这个应该如何改正呢？
> 
> ```java
>         IDependencyParser parser = new KBeamArcEagerDependencyParser();
>         System.out.printf(parser.parse("这是我的代表作").toString());
>         System.out.printf(parser.parse("这是我的代表作·").toString());
> ```
> 
> ```
> 1   这   这   P   PN  _   2   top _   _
> 2   是   是   V   VC  _   0   ROOT    _   _
> 3   我   我   P   PN  _   5   assmod  _   _
> 4   的   的   D   DEG _   3   assm    _   _
> 5   代表作 代表作 N   NN  _   2   attr    _   _
> 
> 1   这   这   P   PN  _   2   top _   _
> 2   是   是   V   VC  _   0   ROOT    _   _
> 3   我   我   P   PN  _   5   assmod  _   _
> 4   的   的   D   DEG _   3   assm    _   _
> 5   代表  代表  N   NN  _   6   nsubj   _   _
> 6   作·  作·  V   VV  _   2   ccomp   _   _
> ```

请问该怎么开启KBeamArcEagerDependencyParser的自定义词典？

**Comment by jimmy-walker** [comment]
@seabiscuityj  可以修改KBeamArcEagerDependencyParser.java中的源码
```java
enableCustomDictionaryForcing(true)
```

**Comment by seabiscuityj** [comment]
> @seabiscuityj 可以修改KBeamArcEagerDependencyParser.java中的源码
> 
> ```java
> enableCustomDictionaryForcing(true)
> ```

谢谢回复，按照建议重新训练了模型。
另外，还有一个问题想请教您，我在用NeuralNetworkDependencyParser进行依存句法分析的时候，总是提示空指针异常。

我的做法是：运行ch13下的DemoNeuralParser，就报错空指针异常。不知道是哪儿出问题？期待您的回答。

我的版本是HanLP1.8.0，按照提示下载了数据包data，NNParserModel.txt.bin的存放路径就是源码中的NNParserModelPath指向的"data/model/dependency/NNParserModel.txt"。

**Comment by jimmy-walker** [comment]
> > @seabiscuityj 可以修改KBeamArcEagerDependencyParser.java中的源码
> > ```java
> > enableCustomDictionaryForcing(true)
> > ```
> 
> 谢谢回复，按照建议重新训练了模型。
> 另外，还有一个问题想请教您，我在用NeuralNetworkDependencyParser进行依存句法分析的时候，总是提示空指针异常。
> 
> 我的做法是：运行ch13下的DemoNeuralParser，就报错空指针异常。不知道是哪儿出问题？期待您的回答。
> 
> 我的版本是HanLP1.8.0，按照提示下载了数据包data，NNParserModel.txt.bin的存放路径就是源码中的NNParserModelPath指向的"data/model/dependency/NNParserModel.txt"。

sorry，这个情况我没遇到过，或许你可以新开个贴@下作者。

**Comment by seabiscuityj** [comment]
> > > @seabiscuityj 可以修改KBeamArcEagerDependencyParser.java中的源码
> > > ```java
> > > enableCustomDictionaryForcing(true)
> > > ```
> > 
> > 
> > 谢谢回复，按照建议重新训练了模型。
> > 另外，还有一个问题想请教您，我在用NeuralNetworkDependencyParser进行依存句法分析的时候，总是提示空指针异常。
> > 我的做法是：运行ch13下的DemoNeuralParser，就报错空指针异常。不知道是哪儿出问题？期待您的回答。
> > 我的版本是HanLP1.8.0，按照提示下载了数据包data，NNParserModel.txt.bin的存放路径就是源码中的NNParserModelPath指向的"data/model/dependency/NNParserModel.txt"。
> 
> sorry，这个情况我没遇到过，或许你可以新开个贴@下作者。

非常感谢您的回复！作者似乎是建议新的issue放到论坛上提，我在蝴蝶效应论坛上发过帖子但是还没有回复。

**Comment by seabiscuityj** [comment]
> > > @seabiscuityj 可以修改KBeamArcEagerDependencyParser.java中的源码
> > > ```java
> > > enableCustomDictionaryForcing(true)
> > > ```
> > 
> > 
> > 谢谢回复，按照建议重新训练了模型。
> > 另外，还有一个问题想请教您，我在用NeuralNetworkDependencyParser进行依存句法分析的时候，总是提示空指针异常。
> > 我的做法是：运行ch13下的DemoNeuralParser，就报错空指针异常。不知道是哪儿出问题？期待您的回答。
> > 我的版本是HanLP1.8.0，按照提示下载了数据包data，NNParserModel.txt.bin的存放路径就是源码中的NNParserModelPath指向的"data/model/dependency/NNParserModel.txt"。
> 
> sorry，这个情况我没遇到过，或许你可以新开个贴@下作者。

还有几点问题想请教您：
1. 使用的是什么版本，是portable吗？
2. 有手动下载数据包data吗？
3. hanlp.properties这份文件放在什么路径下？（我是clone到本地，将hanlp.properties放在src目录下，在文件里面配置了root路径为data数据包的父目录）

**Comment by jimmy-walker** [comment]
> > > > @seabiscuityj 可以修改KBeamArcEagerDependencyParser.java中的源码
> > > > ```java
> > > > enableCustomDictionaryForcing(true)
> > > > ```
> > > 
> > > 
> > > 谢谢回复，按照建议重新训练了模型。
> > > 另外，还有一个问题想请教您，我在用NeuralNetworkDependencyParser进行依存句法分析的时候，总是提示空指针异常。
> > > 我的做法是：运行ch13下的DemoNeuralParser，就报错空指针异常。不知道是哪儿出问题？期待您的回答。
> > > 我的版本是HanLP1.8.0，按照提示下载了数据包data，NNParserModel.txt.bin的存放路径就是源码中的NNParserModelPath指向的"data/model/dependency/NNParserModel.txt"。
> > 
> > 
> > sorry，这个情况我没遇到过，或许你可以新开个贴@下作者。
> 
> 还有几点问题想请教您：
> 
> 1. 使用的是什么版本，是portable吗？
> 2. 有手动下载数据包data吗？
> 3. hanlp.properties这份文件放在什么路径下？（我是clone到本地，将hanlp.properties放在src目录下，在文件里面配置了root路径为data数据包的父目录）

1.我是下载源代码，自己编译的，没用portable。版本是1.7.8。
2.手动下载了数据包。
3.hanlp.properties放在了target/classes目录下。
