### ISSUE TITLE
CharTabel 归一化部分字符存在错误

### ISSUE THREAD

**Issue by tiandiweizun** [hankcs/HanLP#1614]
**Describe the bug**
1. 有个issue关于[调用CharTabel，把“幺”改为“么”不合理](https://github.com/hankcs/HanLP/issues/1427)portable修复了，但是下载1.7.5 zip包有问题，后发现CharTable.txt.bin md5不一致
2. 以下字符有问题：其中第一列是原始字符，第二列是归一化后字符，括号表示 建议可以考虑括号内字符替换原有归一化内容
猛	勐
蜺	霓
脊	嵴
骼	胳
拾	十
劈	噼
溜	熘
呱	哌
怵	憷
糸	纟（丝）
乾	干
艸	艹（草）

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```java
public void testCharTable() {
        Map<String, String> normalizationBadCase = new HashMap<>();
        normalizationBadCase.put("猛", "猛");
        normalizationBadCase.put("蜺", "蜺");
        normalizationBadCase.put("脊", "脊");
        normalizationBadCase.put("骼", "骼");
        normalizationBadCase.put("拾", "拾");
        normalizationBadCase.put("劈", "劈");
        normalizationBadCase.put("溜", "溜");
        normalizationBadCase.put("呱", "呱");
        normalizationBadCase.put("怵", "怵");
        normalizationBadCase.put("糸", "丝");
        normalizationBadCase.put("乾", "乾");
        normalizationBadCase.put("艸", "草");
        for (Map.Entry<String, String> entry : normalizationBadCase.entrySet()) {
            assert CharTable.convert(entry.getKey()).equals(entry.getValue());
        }
    }
```

**Describe the current behavior**
A clear and concise description of what happened.

**Expected behavior**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows
- Python version:
- HanLP version: 1.8.0

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [ ] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

开源项目维护不易，HanLP用户以十万计，而主要维护者只有我一人。我有自己的full-time研究工作，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
