### ISSUE TITLE
HanLP2.1分词，刚刚作者update后又报新的错

### ISSUE THREAD

**Issue by hz7715** [hankcs/HanLP#1617]
**Describe the bug**
您好，感谢作者及时的回复上一个bug！

但我刚刚重新pip install hanlp -U 之后，并同时尝试本地git pull，再运行同样的代码，会报如下新的错误，说是无法load模型，但我之前已经下载过这个模型到我本地了：

(base) river@riverdeMacBook-Pro mtl % ll
total 0
drwxr-xr-x 3 river staff 96 2 23 01:21 ./
drwxr-xr-x 4 river staff 128 2 22 21:36 ../
drwxr-xr-x 13 river staff 416 2 22 22:10 close_tok_pos_ner_srl_dep_sdp_con_electra_small_20210111_124159/

**Code to reproduce the issue**
完整代码和上一个issue中的一样

```python
import hanlp

HanLP = hanlp.load(hanlp.pretrained.mtl.CLOSE_TOK_POS_NER_SRL_DEP_SDP_CON_ELECTRA_SMALL_ZH) # 世界最大中文语料库
tok = HanLP[‘tok/coarse’]

# 读取自定义词表
beauty_vocab = set()
with open(’…/data/userdict.txt’, ‘r’, encoding=‘utf-8’) as fin:
    for line in fin:
        beauty_vocab.add(line.strip())
tok.dict_combine = beauty_vocab

text = ‘我最心水的那些 红：对口红这种东西真的是毫无抵抗力啊 每次入了新色就在蓝朋友手臂上试 他总会说 女生到底需要有多少口红啊 身为一个直男可能真的不懂 红有一百种 哈哈哈哈 言归正传 阿玛尼红管501 503 504 阿玛尼红管真的是我最爱的唇釉了 入的第一支是504 第一次用就被惊艳到了 竟然有这么丝滑的唇釉 完全是奶油慕斯质地 还呈现很高级的哑光感 真的是超爱 爱不释手 后来又相继收了501和503 以后一定还会继续收 喜爱程度 ysl方管17 13 17是我春夏用的最多次的一支 几乎每天都在用 不知道今天擦什么的时候就用它 准没错 一个夏天过去就下去了一大截 喜爱程度 13是后期入的 相比17利用率就没有那么高 怎么说呢 13还是有些挑皮的 素颜涂肯定是土爆了 喜爱程度 mac子弹头 see sheer也是我的心头爱 刚买的时候每天都放包里 随时补 超级滋润 颜色炒鸡日常 上班涂完全不会显得突兀 超爱 喜爱程度 chill小辣椒 也是超爱的一支 怎么涂都好看 毫不夸张 秋冬不知道涂啥时 擦它总不会出错 喜爱程度 雅诗兰黛love系列 300橘红色 310梅子色 都是我爱的颜色 很显白 喜爱程度 阿玛尼小胖丁504 大名鼎鼎的奶油橘 各种被夸 扛不住风种草的 但是！真的没有那么好 好吗 无论后涂薄涂感觉都不是很满意 我通常是叠加哑光其他口红上面用 喜爱程度 tf16 风老大的番茄色 忍不住入的 但是使用率很低 不知道为啥 可能不够日常 也可能是不舍得用 偷笑R 喜爱程度 香奈儿58 也是跟风入的 据说各种适合秋冬 适合黄皮 毫不犹豫拿下 but有点斯望 并不是很好驾驭啊 而且感觉不显白！ 喜爱程度 ysl黑管402 这只是盲选的 适合春夏 感觉一般 中规中矩 喜爱程度 ysl镜面唇釉09 水红色 颜色不错 但是但是 这个唇釉的质地我真的是爱不起来 不能抿嘴 粘粘的 很不好上均匀 喜爱程度 3ce 南瓜色116 干！巨干！炒鸡干！根本不能用 买之前被颜色吸引 很多人都说它很干 我心想 再干能干成啥样 前一天晚上做唇膜 早晨先用唇部打底再涂 上班不到两小时 嘴就干到起皮 南瓜色口红很多 千万别买这一支 喜爱程度 最后说一句 本人黄皮 唇色浅 干起皮唇纹重 借蓝票的胳膊试色 仅供参考 第一次写这么长的笔记 手指断了 好了就酱 叹气R’

cut_res = HanLP(text, tasks=‘tok/coarse’)
print(cut_res)
```

**Describe the current behavior**
我刚刚重新pip install hanlp -U 之后，并同时尝试本地git pull，再运行同样的代码，会报如下新的错误，说是无法load模型，但我之前已经下载过这个模型到我本地了：

(base) river@riverdeMacBook-Pro mtl % ll
total 0
drwxr-xr-x 3 river staff 96 2 23 01:21 ./
drwxr-xr-x 4 river staff 128 2 22 21:36 ../
drwxr-xr-x 13 river staff 416 2 22 22:10 close_tok_pos_ner_srl_dep_sdp_con_electra_small_20210111_124159/

**Expected behavior**
1. 还请教原作者，如何解决这个问题。。万分感谢！
2. 另外还有个问题：是否修复之后、[自定义词表]可以用于open模型以及close模型？这两种模型的主要区别是什么？ 因为之前试文本分词的时候有些样本碰到tok/fine会报错，有些碰到tok/coarse会报错。。。open模型只有'tok'这个key，而close模型有'tok/fine'和'tok/coarse'两种，是否自定义词表也都可以用于这2种模式？我的业务场景需要粒度比较细的、语义信息更丰富的(分割成更长的)短语，是不是close模型的'tok/coarse'的效果会最好？

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
mac OS 10.15.7

- Python version:
python 3.9.2

- HanLP version:
hanlp==2.1.0a20
hanlp-common==0.0.6
hanlp-trie==0.0.2
torch==1.7.1

**Other info / logs**
完整报错信息如下：

Failed to load https://file.hankcs.com/hanlp/mtl/close_tok_pos_ner_srl_dep_sdp_con_electra_small_20210111_124159.zip. See traceback below:
================================ERROR LOG BEGINS================================
Traceback (most recent call last):
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/hanlp/utils/component_util.py", line 81, in load_from_meta_file
obj.load(save_dir, verbose=verbose, **kwargs)
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/hanlp/common/torch_component.py", line 183, in load
self.to(devices)
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/hanlp/common/torch_component.py", line 519, in to
devices = cuda_devices(devices)
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/hanlp/utils/torch_util.py", line 73, in cuda_devices
query = gpus_available()
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/hanlp/utils/torch_util.py", line 46, in gpus_available
nvmlShutdown()
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pynvml/nvml.py", line 772, in nvmlShutdown
fn = get_func_pointer("nvmlShutdown")
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pynvml/nvml.py", line 387, in get_func_pointer
raise NVMLError(NVML_ERROR_UNINITIALIZED)
pynvml.nvml.NVMLError_Uninitialized: Uninitialized
=================================ERROR LOG ENDS=================================
Please upgrade hanlp with:
pip install --upgrade hanlp

If the problem still persists, please submit an issue to https://github.com/hankcs/HanLP/issues
When reporting an issue, make sure to paste the FULL ERROR LOG above.

* [ ] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

开源项目维护不易，HanLP用户以十万计，而主要维护者只有我一人。我有自己的full-time研究工作，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
