### ISSUE TITLE
HanLP2.1分词报新的错：Failed to load https://file.hankcs.com/hanlp/mtl/close_tok_pos_ner_srl_dep_sdp_con_electra_small_20210111_124159.zip

### ISSUE THREAD

**Issue by hz7715** [hankcs/HanLP#1618]
**Describe the bug**

您好，感谢作者及时的回复上一个bug！

但我刚刚重新pip install hanlp -U 之后，并同时尝试本地git pull，再运行同样的代码，会报如下新的错误，说是无法load模型，但我之前已经下载过这个模型到我本地了：

(base) river@riverdeMacBook-Pro mtl % ll
total 0
drwxr-xr-x 3 river staff 96 2 23 01:21 ./
drwxr-xr-x 4 river staff 128 2 22 21:36 ../
drwxr-xr-x 13 river staff 416 2 22 22:10 close_tok_pos_ner_srl_dep_sdp_con_electra_small_20210111_124159/

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

完整代码如下

```python

import hanlp

HanLP = hanlp.load(hanlp.pretrained.mtl.CLOSE_TOK_POS_NER_SRL_DEP_SDP_CON_ELECTRA_SMALL_ZH) # 世界最大中文语料库
tok = HanLP[‘tok/coarse’]

# 读取自定义词表
beauty_vocab = set()
with open(’…/data/userdict.txt’, ‘r’, encoding=‘utf-8’) as fin:
    for line in fin:
        beauty_vocab.add(line.strip())
tok.dict_combine = beauty_vocab

text = ‘我最心水的那些 红：对口红这种东西真的是毫无抵抗力啊 每次入了新色就在蓝朋友手臂上试 他总会说 女生到底需要有多少口红啊 身为一个直男可能真的不懂 红有一百种 哈哈哈哈 言归正传 阿玛尼红管501 503 504 阿玛尼红管真的是我最爱的唇釉了 入的第一支是504 第一次用就被惊艳到了 竟然有这么丝滑的唇釉 完全是奶油慕斯质地 还呈现很高级的哑光感 真的是超爱 爱不释手 后来又相继收了501和503 以后一定还会继续收 喜爱程度 ysl方管17 13 17是我春夏用的最多次的一支 几乎每天都在用 不知道今天擦什么的时候就用它 准没错 一个夏天过去就下去了一大截 喜爱程度 13是后期入的 相比17利用率就没有那么高 怎么说呢 13还是有些挑皮的 素颜涂肯定是土爆了 喜爱程度 mac子弹头 see sheer也是我的心头爱 刚买的时候每天都放包里 随时补 超级滋润 颜色炒鸡日常 上班涂完全不会显得突兀 超爱 喜爱程度 chill小辣椒 也是超爱的一支 怎么涂都好看 毫不夸张 秋冬不知道涂啥时 擦它总不会出错 喜爱程度 雅诗兰黛love系列 300橘红色 310梅子色 都是我爱的颜色 很显白 喜爱程度 阿玛尼小胖丁504 大名鼎鼎的奶油橘 各种被夸 扛不住风种草的 但是！真的没有那么好 好吗 无论后涂薄涂感觉都不是很满意 我通常是叠加哑光其他口红上面用 喜爱程度 tf16 风老大的番茄色 忍不住入的 但是使用率很低 不知道为啥 可能不够日常 也可能是不舍得用 偷笑R 喜爱程度 香奈儿58 也是跟风入的 据说各种适合秋冬 适合黄皮 毫不犹豫拿下 but有点斯望 并不是很好驾驭啊 而且感觉不显白！ 喜爱程度 ysl黑管402 这只是盲选的 适合春夏 感觉一般 中规中矩 喜爱程度 ysl镜面唇釉09 水红色 颜色不错 但是但是 这个唇釉的质地我真的是爱不起来 不能抿嘴 粘粘的 很不好上均匀 喜爱程度 3ce 南瓜色116 干！巨干！炒鸡干！根本不能用 买之前被颜色吸引 很多人都说它很干 我心想 再干能干成啥样 前一天晚上做唇膜 早晨先用唇部打底再涂 上班不到两小时 嘴就干到起皮 南瓜色口红很多 千万别买这一支 喜爱程度 最后说一句 本人黄皮 唇色浅 干起皮唇纹重 借蓝票的胳膊试色 仅供参考 第一次写这么长的笔记 手指断了 好了就酱 叹气R’

cut_res = HanLP(text, tasks=‘tok/coarse’)
print(cut_res)
```

**Describe the current behavior**
A clear and concise description of what happened.

我刚刚重新pip install hanlp -U 之后，并同时尝试本地git pull，再运行同样的代码，会报如下新的错误，说是无法load模型，但我之前已经下载过这个模型到我本地了：

(base) river@riverdeMacBook-Pro mtl % ll
total 0
drwxr-xr-x 3 river staff 96 2 23 01:21 ./
drwxr-xr-x 4 river staff 128 2 22 21:36 ../
drwxr-xr-x 13 river staff 416 2 22 22:10 close_tok_pos_ner_srl_dep_sdp_con_electra_small_20210111_124159/

**Expected behavior**

1. 还请教原作者，如何解决这个问题。。万分感谢！
2. 另外还有个问题：是否修复之后、[自定义词表]可以用于open模型以及close模型？这两种模型的主要区别是什么？ 因为之前试文本分词的时候有些样本碰到tok/fine会报错，有些碰到tok/coarse会报错。。。open模型只有'tok'这个key，而close模型有'tok/fine'和'tok/coarse'两种，是否自定义词表也都可以用于这2种模式？我的业务场景需要粒度比较细的、语义信息更丰富的(分割成更长的)短语，是不是close模型的'tok/coarse'的效果会最好？

**System information**

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
mac OS 10.15.7

- Python version:
python 3.9.2

- HanLP version:
hanlp==2.1.0a20
hanlp-common==0.0.6
hanlp-trie==0.0.2
torch==1.7.1

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

完整报错信息如下：

Failed to load https://file.hankcs.com/hanlp/mtl/close_tok_pos_ner_srl_dep_sdp_con_electra_small_20210111_124159.zip. See traceback below:
================================ERROR LOG BEGINS================================
Traceback (most recent call last):
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/hanlp/utils/component_util.py", line 81, in load_from_meta_file
obj.load(save_dir, verbose=verbose, **kwargs)
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/hanlp/common/torch_component.py", line 183, in load
self.to(devices)
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/hanlp/common/torch_component.py", line 519, in to
devices = cuda_devices(devices)
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/hanlp/utils/torch_util.py", line 73, in cuda_devices
query = gpus_available()
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/hanlp/utils/torch_util.py", line 46, in gpus_available
nvmlShutdown()
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pynvml/nvml.py", line 772, in nvmlShutdown
fn = get_func_pointer("nvmlShutdown")
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pynvml/nvml.py", line 387, in get_func_pointer
raise NVMLError(NVML_ERROR_UNINITIALIZED)
pynvml.nvml.NVMLError_Uninitialized: Uninitialized
=================================ERROR LOG ENDS=================================
Please upgrade hanlp with:
pip install --upgrade hanlp

If the problem still persists, please submit an issue to https://github.com/hankcs/HanLP/issues
When reporting an issue, make sure to paste the FULL ERROR LOG above.

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
你是否用的是最新版？对应 https://github.com/hankcs/HanLP/commit/171bd2df65aa38069c38b9ede9b02cd901654f96 版本号 2.1.0-alpha.22

**Comment by hz7715** [comment]
> 你是否用的是最新版？对应 [171bd2d](https://github.com/hankcs/HanLP/commit/171bd2df65aa38069c38b9ede9b02cd901654f96) 版本号 2.1.0-alpha.22

是的，hanlp==2.1.0a22

**Comment by hankcs** [comment]
> [自定义词表]可以用于open模型以及close模型？

是

> 这两种模型的主要区别是什么？ 

open训练自开源语料，给大家跑分公平比较用的。网上大部分人比较准确率的方法都是错的，给他们一个开源语料横向比较。
close训练自闭源语料，我们雇人标注了世界上最大的中文语料库，效果是最好的。

> 因为之前试文本分词的时候有些样本碰到tok/fine会报错，有些碰到tok/coarse会报错。。。

有bug尽管提，前几版也改了些bug

> open模型只有'tok'这个key，而close模型有'tok/fine'和'tok/coarse'两种，是否自定义词表也都可以用于这2种模式？

可以

> 我的业务场景需要粒度比较细的、语义信息更丰富的(分割成更长的)短语，是不是close模型的'tok/coarse'的效果会最好？

你的需求是矛盾的。你可能指的是非美容相关的词语你想颗粒度细一点，美容词汇粗一点，这样你应该用tok/fine

**Comment by hankcs** [comment]
> > 你是否用的是最新版？对应 [171bd2d](https://github.com/hankcs/HanLP/commit/171bd2df65aa38069c38b9ede9b02cd901654f96) 版本号 2.1.0-alpha.22
> 
> 是的，hanlp==2.1.0a22

这不可能。你可能安装了doc-zh分支，你应该切换到master分支。

**Comment by hz7715** [comment]
> > > 你是否用的是最新版？对应 [171bd2d](https://github.com/hankcs/HanLP/commit/171bd2df65aa38069c38b9ede9b02cd901654f96) 版本号 2.1.0-alpha.22
> > 
> > 
> > 是的，hanlp==2.1.0a22
> 
> 这不可能。你可能安装了doc-zh分支，你应该切换到master分支。

我刚刚试了下，我直接pip update之后运行没有报错了，但我git pull 更新之后，本地调close模型会报如上的错。。

**Comment by hankcs** [comment]
> git pull

你git pull 的分支不对，要用master

**Comment by hz7715** [comment]
> > [自定义词表]可以用于open模型以及close模型？
> 
> 是
> 
> > 这两种模型的主要区别是什么？
> 
> open训练自开源语料，给大家跑分公平比较用的。网上大部分人比较准确率的方法都是错的，给他们一个开源语料横向比较。
> close训练自闭源语料，我们雇人标注了世界上最大的中文语料库，效果是最好的。
> 
> > 因为之前试文本分词的时候有些样本碰到tok/fine会报错，有些碰到tok/coarse会报错。。。
> 
> 有bug尽管提，前几版也改了些bug
> 
> > open模型只有'tok'这个key，而close模型有'tok/fine'和'tok/coarse'两种，是否自定义词表也都可以用于这2种模式？
> 
> 可以
> 
> > 我的业务场景需要粒度比较细的、语义信息更丰富的(分割成更长的)短语，是不是close模型的'tok/coarse'的效果会最好？
> 
> 你的需求是矛盾的。你可能指的是非美容相关的词语你想颗粒度细一点，美容词汇粗一点，这样你应该用tok/fine

感谢作者的回复！最后一个问题我的意思是，希望能不要切分的太细，保留语义信息比较完整的短语：比如“红管口红” 而不是“红管”，“口红” 之类的。。

**Comment by hz7715** [comment]
> > git pull
> 
> 你git pull 的分支不对，要用master


(base) river@riverdeMacBook-Pro HanLP % python3 hanlp-close.py 
Failed to load https://file.hankcs.com/hanlp/mtl/close_tok_pos_ner_srl_dep_sdp_con_electra_small_20210111_124159.zip. See traceback below:
================================ERROR LOG BEGINS================================
Traceback (most recent call last):
  File "/Users/river/Desktop/1-tag-recall/note-tag/HanLP/hanlp/utils/component_util.py", line 81, in load_from_meta_file
    obj.load(save_dir, verbose=verbose, **kwargs)
  File "/Users/river/Desktop/1-tag-recall/note-tag/HanLP/hanlp/common/torch_component.py", line 183, in load
    self.to(devices)
  File "/Users/river/Desktop/1-tag-recall/note-tag/HanLP/hanlp/common/torch_component.py", line 519, in to
    devices = cuda_devices(devices)
  File "/Users/river/Desktop/1-tag-recall/note-tag/HanLP/hanlp/utils/torch_util.py", line 73, in cuda_devices
    query = gpus_available()
  File "/Users/river/Desktop/1-tag-recall/note-tag/HanLP/hanlp/utils/torch_util.py", line 46, in gpus_available
    nvmlShutdown()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pynvml/nvml.py", line 772, in nvmlShutdown
    fn = get_func_pointer("nvmlShutdown")
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pynvml/nvml.py", line 387, in get_func_pointer
    raise NVMLError(NVML_ERROR_UNINITIALIZED)
pynvml.nvml.NVMLError_Uninitialized: Uninitialized
=================================ERROR LOG ENDS=================================
Please upgrade hanlp with:
pip install --upgrade hanlp

If the problem still persists, please submit an issue to https://github.com/hankcs/HanLP/issues
When reporting an issue, make sure to paste the FULL ERROR LOG above.
(base) river@riverdeMacBook-Pro HanLP % git status
位于分支 master
您的分支与上游分支 'origin/master' 一致。

**Comment by hankcs** [comment]
> tok/coarse

哦，那就用 tok/coarse

**Comment by hankcs** [comment]
> > > git pull
> > 
> > 
> > 你git pull 的分支不对，要用master
> 
> (base) river@riverdeMacBook-Pro HanLP % python3 hanlp-close.py
> Failed to load https://file.hankcs.com/hanlp/mtl/close_tok_pos_ner_srl_dep_sdp_con_electra_small_20210111_124159.zip. See traceback below:
> ================================ERROR LOG BEGINS================================
> Traceback (most recent call last):
> File "/Users/river/Desktop/1-tag-recall/note-tag/HanLP/hanlp/utils/component_util.py", line 81, in load_from_meta_file
> obj.load(save_dir, verbose=verbose, **kwargs)
> File "/Users/river/Desktop/1-tag-recall/note-tag/HanLP/hanlp/common/torch_component.py", line 183, in load
> self.to(devices)
> File "/Users/river/Desktop/1-tag-recall/note-tag/HanLP/hanlp/common/torch_component.py", line 519, in to
> devices = cuda_devices(devices)
> File "/Users/river/Desktop/1-tag-recall/note-tag/HanLP/hanlp/utils/torch_util.py", line 73, in cuda_devices
> query = gpus_available()
> File "/Users/river/Desktop/1-tag-recall/note-tag/HanLP/hanlp/utils/torch_util.py", line 46, in gpus_available
> nvmlShutdown()
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pynvml/nvml.py", line 772, in nvmlShutdown
> fn = get_func_pointer("nvmlShutdown")
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pynvml/nvml.py", line 387, in get_func_pointer
> raise NVMLError(NVML_ERROR_UNINITIALIZED)
> pynvml.nvml.NVMLError_Uninitialized: Uninitialized
> =================================ERROR LOG ENDS=================================
> Please upgrade hanlp with:
> pip install --upgrade hanlp
> 
> If the problem still persists, please submit an issue to https://github.com/hankcs/HanLP/issues
> When reporting an issue, make sure to paste the FULL ERROR LOG above.
> (base) river@riverdeMacBook-Pro HanLP % git status
> 位于分支 master
> 您的分支与上游分支 'origin/master' 一致。

不太对，你查一下这个文件的 md5 看看一不一致

$ md5 /Users/river/Desktop/1-tag-recall/note-tag/HanLP/hanlp/utils/torch_util.py

MD5 (hanlp/utils/torch_util.py) = 9e29c636d1d3530e9f5106171cb94b32

**Comment by hz7715** [comment]
> > tok/coarse
> 
> 哦，那就用 tok/coarse

好滴，了解，谢谢作者这么晚还及时回复！谢谢作者的分享！我先直接调接口跑吧，接口跑没有再报错了

**Comment by hz7715** [comment]
> > > > git pull
> > > 
> > > 
> > > 你git pull 的分支不对，要用master
> > 
> > 
> > (base) river@riverdeMacBook-Pro HanLP % python3 hanlp-close.py
> > Failed to load https://file.hankcs.com/hanlp/mtl/close_tok_pos_ner_srl_dep_sdp_con_electra_small_20210111_124159.zip. See traceback below:
> > ================================ERROR LOG BEGINS================================
> > Traceback (most recent call last):
> > File "/Users/river/Desktop/1-tag-recall/note-tag/HanLP/hanlp/utils/component_util.py", line 81, in load_from_meta_file
> > obj.load(save_dir, verbose=verbose, **kwargs)
> > File "/Users/river/Desktop/1-tag-recall/note-tag/HanLP/hanlp/common/torch_component.py", line 183, in load
> > self.to(devices)
> > File "/Users/river/Desktop/1-tag-recall/note-tag/HanLP/hanlp/common/torch_component.py", line 519, in to
> > devices = cuda_devices(devices)
> > File "/Users/river/Desktop/1-tag-recall/note-tag/HanLP/hanlp/utils/torch_util.py", line 73, in cuda_devices
> > query = gpus_available()
> > File "/Users/river/Desktop/1-tag-recall/note-tag/HanLP/hanlp/utils/torch_util.py", line 46, in gpus_available
> > nvmlShutdown()
> > File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pynvml/nvml.py", line 772, in nvmlShutdown
> > fn = get_func_pointer("nvmlShutdown")
> > File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pynvml/nvml.py", line 387, in get_func_pointer
> > raise NVMLError(NVML_ERROR_UNINITIALIZED)
> > pynvml.nvml.NVMLError_Uninitialized: Uninitialized
> > =================================ERROR LOG ENDS=================================
> > Please upgrade hanlp with:
> > pip install --upgrade hanlp
> > If the problem still persists, please submit an issue to https://github.com/hankcs/HanLP/issues
> > When reporting an issue, make sure to paste the FULL ERROR LOG above.
> > (base) river@riverdeMacBook-Pro HanLP % git status
> > 位于分支 master
> > 您的分支与上游分支 'origin/master' 一致。
> 
> 不太对，你查一下这个文件的 md5 看看一不一致
> 
> $ md5 /Users/river/Desktop/1-tag-recall/note-tag/HanLP/hanlp/utils/torch_util.py
> 
> MD5 (hanlp/utils/torch_util.py) = 9e29c636d1d3530e9f5106171cb94b32

不一致：

5b86dbb9662e883a1e949b01da9476ed

**Comment by hankcs** [comment]
> > > tok/coarse
> > 
> > 
> > 哦，那就用 tok/coarse
> 
> 好滴，了解，谢谢作者这么晚还及时回复！谢谢作者的分享！我先直接调接口跑吧，接口跑没有再报错了

没事，我这边正中午。

**Comment by hankcs** [comment]
> > 不太对，你查一下这个文件的 md5 看看一不一致
> > $ md5 /Users/river/Desktop/1-tag-recall/note-tag/HanLP/hanlp/utils/torch_util.py
> > MD5 (hanlp/utils/torch_util.py) = 9e29c636d1d3530e9f5106171cb94b32
> 
> 不一致：
> 
> 5b86dbb9662e883a1e949b01da9476ed

可能国内的GitHub有什么缓存之类的，你可以等明天，删了本地clone重新clone一次。

**Comment by hz7715** [comment]
> 可能国内的GitHub有什么缓存之类的，你可以等明天，删了本地clone重新clone一次。

噢，好滴，我明天试试

**Comment by hz7715** [comment]
> 没事，我这边正中午。

啊哈哈，你在海外哦，作者太强了，一个人完成这么庞大的项目！膜dalao😄

**Comment by hankcs** [comment]
> > 没事，我这边正中午。
> 
> 啊哈哈，你在海外哦，作者太强了，一个人完成这么庞大的项目！膜dalao😄

没有没有，这个项目也是建立在开源工作基础上的。

**Comment by hz7715** [comment]
> 可能国内的GitHub有什么缓存之类的，你可以等明天，删了本地clone重新clone一次。

我刚刚删除重新clone之后就ok啦！

另外还想请教一下：我想save一个更小的模型，close模型中的2种分词分别对应哪个词性标注结果呢？
tok/fine 和 tok/coarse 与 pos/pku, pos/ctb, pos/863。。。


['con', 'dep', 'ner/msra', 'ner/ontonotes', 'ner/pku', 'pos/863', 'pos/ctb', 'pos/pku', 'sdp', 'srl', 'tok/coarse', 'tok/fine']

**Comment by hankcs** [comment]
模型和结果的key是一一对应的，'tok/coarse', 'tok/fine'分别是粗分和细分。

**Comment by hz7715** [comment]
> 模型和结果的key是一一对应的，'tok/coarse', 'tok/fine'分别是粗分和细分。

我的意思是不知道它们对应哪个【词性标注】的结果，因为有3种pos/pku, pos/ctb, pos/863，但它们命名没有对应fine/coarse...

**Comment by hankcs** [comment]
对应结果中的第一个分词key，默认fine是第一个所以默认对应细分。

**Comment by hz7715** [comment]
> 对应结果中的第一个分词key，默认fine是第一个所以默认对应细分。

噢，了解。。

另外还有个问题：关于自定义词表
之前我用pyhanlp的时候，自定义词表还需要定义词性词频之类的；而现在hanlp2.1版本，基于模型的分词，添加自定义词表只需要词本身，关于这个我有2个小问题：
1. 是否需要人工将词表中的词按其字符串长度从大到小排序，以便模型进行最长匹配？
2. 2.1版本基于模型训练，是否有用到pyhanlp当中几十万的自定义词表的数据呢？我是否还有必要把pyhanlp当中涉及的词表(现代汉语词典、机构名、等等等)添加到这里的自定义词表中。。这样做还能进一步优化结果吗。。

**Comment by hankcs** [comment]
> 是否需要人工将词表中的词按其字符串长度从大到小排序，以便模型进行最长匹配？

不需要

> 2.1版本基于模型训练，是否有用到pyhanlp当中几十万的词表(现代汉语词典、机构名、等等等)的数据呢？我是否还有必要把pyhanlp当中涉及的词表添加到这里的自定义词表中。。这样做还能进一步优化结果吗。。

大部分场景不需要，2.1的效果可以说是领先1.x几个代差，只有少数新词需要。

**Comment by hz7715** [comment]
> > 是否需要人工将词表中的词按其字符串长度从大到小排序，以便模型进行最长匹配？
> 
> 不需要
> 
> > 2.1版本基于模型训练，是否有用到pyhanlp当中几十万的词表(现代汉语词典、机构名、等等等)的数据呢？我是否还有必要把pyhanlp当中涉及的词表添加到这里的自定义词表中。。这样做还能进一步优化结果吗。。
> 
> 大部分场景不需要，2.1的效果可以说是领先1.x几个代差，只有少数新词需要。

好的，感谢作者回复！
只是可不可以暂时先不关闭这个ISSUE呀。。我明天白天跑一下CASE，有个分词上的问题还想问下你。。

**Comment by hankcs** [comment]
还是关闭了吧，提问请上论坛，我最近几天都可以回复。

**Comment by hz7715** [comment]
求助作者，我在linux上安装，又报错了.....我已经手动下载了模型文件到指定目录下了。。还是不行，也确认了hanlp版本号，都是最新的
hanlp==2.1.0a22
hanlp-common==0.0.6
hanlp-trie==0.0.2

系统信息：Linux version 3.10.0-1127.el7.x86_64

代码如下:

# -*- coding: utf-8 -*-
import hanlp
from hanlp.components.mtl.multi_task_learning import MultiTaskLearning
from hanlp.components.mtl.tasks.tok.tag_tok import TaggingTokenization
from tests import cdroot

cdroot()
HanLP: MultiTaskLearning = hanlp.load(hanlp.pretrained.mtl.CLOSE_TOK_POS_NER_SRL_DEP_SDP_CON_ELECTRA_BASE_ZH)
tok: TaggingTokenization = HanLP['tok/coarse']
tok.dict_force = None
tok.dict_combine = {'和服', '服务行业'}
print(f'合并模式:\n{HanLP("商品和服务行业")["tok/coarse"]}')


报错信息：

(hanlp2.1) [app@search-gpu01 HanLP-master]$ python hanlp-close.py
Failed to load https://file.hankcs.com/hanlp/mtl/close_tok_pos_ner_srl_dep_sdp_con_electra_base_20210111_124519.zip. See traceback below:
================================ERROR LOG BEGINS================================
Traceback (most recent call last):
  File "/data/user/river/HanLP-master/hanlp/utils/component_util.py", line 81, in load_from_meta_file
    obj.load(save_dir, verbose=verbose, **kwargs)
  File "/data/user/river/HanLP-master/hanlp/common/torch_component.py", line 173, in load
    self.load_config(save_dir, **kwargs)
  File "/data/user/river/HanLP-master/hanlp/common/torch_component.py", line 125, in load_config
    self.config[k] = Configurable.from_config(v)
  File "/data/user/miniconda3/envs/hanlp2.1/lib/python3.9/site-packages/hanlp_common/configurable.py", line 30, in from_config
    return cls(**deserialized_config)
  File "/data/user/river/HanLP-master/hanlp/layers/embeddings/contextual_word_embedding.py", line 141, in __init__
    self._transformer_tokenizer = TransformerEncoder.build_transformer_tokenizer(self.transformer,
  File "/data/user/river/HanLP-master/hanlp/layers/transformers/encoder.py", line 124, in build_transformer_tokenizer
    return AutoTokenizer.from_pretrained(transformer, use_fast=use_fast, do_basic_tokenize=do_basic_tokenize)
  File "/data/user/miniconda3/envs/hanlp2.1/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 362, in from_pretrained
    config = AutoConfig.from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "/data/user/miniconda3/envs/hanlp2.1/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 368, in from_pretrained
    config_dict, _ = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/data/user/miniconda3/envs/hanlp2.1/lib/python3.9/site-packages/transformers/configuration_utils.py", line 417, in get_config_dict
    resolved_config_file = cached_path(
  File "/data/user/miniconda3/envs/hanlp2.1/lib/python3.9/site-packages/transformers/file_utils.py", line 1078, in cached_path
    output_path = get_from_cache(
  File "/data/user/miniconda3/envs/hanlp2.1/lib/python3.9/site-packages/transformers/file_utils.py", line 1264, in get_from_cache
    raise ValueError(
ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.
=================================ERROR LOG ENDS=================================
If the problem still persists, please submit an issue to https://github.com/hankcs/HanLP/issues
When reporting an issue, make sure to paste the FULL ERROR LOG above.

**Comment by hankcs** [comment]
https://bbs.hankcs.com/t/topic/3427/2
