### ISSUE TITLE
HanLP里有自定义词性的功能么？比如AnsjSeg中可以通过 FilterModifWord.insertStopNatures()来自定义词性

### ISSUE THREAD

**Issue by nmdxpc** [hankcs/HanLP#162]
我想给用户词典中的词定义为“userDefine”这个词性，比如AnsjSeg中可以通过 FilterModifWord.insertStopNatures(“userDefine”)来自定义词性，HanLP中除了修改Term.enum代码外，有没有直接可用的方法？

**Comment by hankcs** [comment]
开发中

**Comment by bookling** [comment]
如何给新词自定义词性，该部分功能开发完成了吗？

**Comment by hankcs** [comment]
https://github.com/hankcs/HanLP/blob/master/src/test/java/com/hankcs/demo/DemoCustomNature.java
