### ISSUE TITLE
Is this normal when I load the 'LARGE_ALBERT_BASE'?

### ISSUE THREAD

**Issue by SilverLyan** [hankcs/HanLP#1620]
**Describe the bug**
Is this normal when I load the 'LARGE_ALBERT_BASE'?

**Code to reproduce the issue**
tokenizer = hanlp.load('LARGE_ALBERT_BASE')

```python
```

**Describe the current behavior**
run the code: tokenizer = hanlp.load('LARGE_ALBERT_BASE')

**Expected behavior**
Maybe it should finish without any output? But it prints long logs.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS
- Python version: 3.7.6
- HanLP version:  hanlp 2.1.0a22   hanlp-common 0.0.6    hanlp-trie    0.0.2

**Other info / logs**
loader: No value for:[albert/embeddings/word_embeddings_projector/projector:0], i.e.:[bert/embeddings/word_embeddings_2] in:[/Users/yan/.hanlp/embeddings/albert_base_zh/model.ckpt-best]
loader: No value for:[albert/embeddings/word_embeddings_projector/bias:0], i.e.:[bert/embeddings/word_embeddings_2/bias] in:[/Users/yan/.hanlp/embeddings/albert_base_zh/model.ckpt-best]
loader: No value for:[albert/encoder/layer_shared/attention/self/query/kernel:0], i.e.:[bert/encoder/layer_shared/attention/self/query/kernel] in:[/Users/yan/.hanlp/embeddings/albert_base_zh/model.ckpt-best]
loader: No value for:[albert/encoder/layer_shared/attention/self/query/bias:0], i.e.:[bert/encoder/layer_shared/attention/self/query/bias] in:[/Users/yan/.hanlp/embeddings/albert_base_zh/model.ckpt-best]
loader: No value for:[albert/encoder/layer_shared/attention/self/key/kernel:0], i.e.:[bert/encoder/layer_shared/attention/self/key/kernel] in:[/Users/yan/.hanlp/embeddings/albert_base_zh/model.ckpt-best]
loader: No value for:[albert/encoder/layer_shared/attention/self/key/bias:0], i.e.:[bert/encoder/layer_shared/attention/self/key/bias] in:[/Users/yan/.hanlp/embeddings/albert_base_zh/model.ckpt-best]
loader: No value for:[albert/encoder/layer_shared/attention/self/value/kernel:0], i.e.:[bert/encoder/layer_shared/attention/self/value/kernel] in:[/Users/yan/.hanlp/embeddings/albert_base_zh/model.ckpt-best]
loader: No value for:[albert/encoder/layer_shared/attention/self/value/bias:0], i.e.:[bert/encoder/layer_shared/attention/self/value/bias] in:[/Users/yan/.hanlp/embeddings/albert_base_zh/model.ckpt-best]
loader: No value for:[albert/encoder/layer_shared/attention/output/dense/kernel:0], i.e.:[bert/encoder/layer_shared/attention/output/dense/kernel] in:[/Users/yan/.hanlp/embeddings/albert_base_zh/model.ckpt-best]
loader: No value for:[albert/encoder/layer_shared/attention/output/dense/bias:0], i.e.:[bert/encoder/layer_shared/attention/output/dense/bias] in:[/Users/yan/.hanlp/embeddings/albert_base_zh/model.ckpt-best]
loader: No value for:[albert/encoder/layer_shared/attention/output/LayerNorm/gamma:0], i.e.:[bert/encoder/layer_shared/attention/output/LayerNorm/gamma] in:[/Users/yan/.hanlp/embeddings/albert_base_zh/model.ckpt-best]
loader: No value for:[albert/encoder/layer_shared/attention/output/LayerNorm/beta:0], i.e.:[bert/encoder/layer_shared/attention/output/LayerNorm/beta] in:[/Users/yan/.hanlp/embeddings/albert_base_zh/model.ckpt-best]
loader: No value for:[albert/encoder/layer_shared/intermediate/kernel:0], i.e.:[bert/encoder/layer_shared/intermediate/dense/kernel] in:[/Users/yan/.hanlp/embeddings/albert_base_zh/model.ckpt-best]
loader: No value for:[albert/encoder/layer_shared/intermediate/bias:0], i.e.:[bert/encoder/layer_shared/intermediate/dense/bias] in:[/Users/yan/.hanlp/embeddings/albert_base_zh/model.ckpt-best]
loader: No value for:[albert/encoder/layer_shared/output/dense/kernel:0], i.e.:[bert/encoder/layer_shared/output/dense/kernel] in:[/Users/yan/.hanlp/embeddings/albert_base_zh/model.ckpt-best]
loader: No value for:[albert/encoder/layer_shared/output/dense/bias:0], i.e.:[bert/encoder/layer_shared/output/dense/bias] in:[/Users/yan/.hanlp/embeddings/albert_base_zh/model.ckpt-best]
loader: No value for:[albert/encoder/layer_shared/output/LayerNorm/gamma:0], i.e.:[bert/encoder/layer_shared/output/LayerNorm/gamma] in:[/Users/yan/.hanlp/embeddings/albert_base_zh/model.ckpt-best]
loader: No value for:[albert/encoder/layer_shared/output/LayerNorm/beta:0], i.e.:[bert/encoder/layer_shared/output/LayerNorm/beta] in:[/Users/yan/.hanlp/embeddings/albert_base_zh/model.ckpt-best]
Done loading 5 BERT weights from: /Users/yan/.hanlp/embeddings/albert_base_zh/model.ckpt-best into <bert.model.BertModelLayer object at 0x7fd6c181cd10> (prefix:albert). Count of weights not found in the checkpoint was: [18]. Count of weights with mismatched shape: [0]
Unused weights from checkpoint: 
	bert/encoder/embedding_hidden_mapping_in/bias
	bert/encoder/embedding_hidden_mapping_in/kernel
	bert/encoder/transformer/group_0/inner_group_0/LayerNorm/beta
	bert/encoder/transformer/group_0/inner_group_0/LayerNorm/gamma
	bert/encoder/transformer/group_0/inner_group_0/LayerNorm_1/beta
	bert/encoder/transformer/group_0/inner_group_0/LayerNorm_1/gamma
	bert/encoder/transformer/group_0/inner_group_0/attention_1/output/dense/bias
	bert/encoder/transformer/group_0/inner_group_0/attention_1/output/dense/kernel
	bert/encoder/transformer/group_0/inner_group_0/attention_1/self/key/bias
	bert/encoder/transformer/group_0/inner_group_0/attention_1/self/key/kernel
	bert/encoder/transformer/group_0/inner_group_0/attention_1/self/query/bias
	bert/encoder/transformer/group_0/inner_group_0/attention_1/self/query/kernel
	bert/encoder/transformer/group_0/inner_group_0/attention_1/self/value/bias
	bert/encoder/transformer/group_0/inner_group_0/attention_1/self/value/kernel
	bert/encoder/transformer/group_0/inner_group_0/ffn_1/intermediate/dense/bias
	bert/encoder/transformer/group_0/inner_group_0/ffn_1/intermediate/dense/kernel
	bert/encoder/transformer/group_0/inner_group_0/ffn_1/intermediate/output/dense/bias
	bert/encoder/transformer/group_0/inner_group_0/ffn_1/intermediate/output/dense/kernel
	bert/pooler/dense/bias
	bert/pooler/dense/kernel
	cls/predictions/output_bias
	cls/predictions/transform/LayerNorm/beta
	cls/predictions/transform/LayerNorm/gamma
	cls/predictions/transform/dense/bias
	cls/predictions/transform/dense/kernel
	cls/seq_relationship/output_bias
	cls/seq_relationship/output_weights
	global_step

* [ ] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

开源项目维护不易，HanLP用户以十万计，而主要维护者只有我一人。我有自己的full-time研究工作，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
