### ISSUE TITLE
pyhanlp多进程问题

### ISSUE THREAD

**Issue by jiangxiaolin** [hankcs/HanLP#1625]
**Describe the bug**
使用pyhanlp在多线程下测试无问题，在多进程下会出现异常。

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```from multiprocessing import Pool
from tqdm import tqdm
from bert4keras.snippets import parallel_apply
import argparse
import pandas as pd
from pyhanlp import HanLP, SafeJClass
from jpype import JClass, startJVM, getDefaultJVMPath, isThreadAttachedToJVM, attachThreadToJVM

def test_process(tmp: int):
    print(str(tmp) + '\n')
    #print(tripnlp.cut("商品和服务"))
    print(HanLP.segment("商品和服务"))
    return str(tmp)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='')
    parser.add_argument('-mode', '--mode', type=str, default='pool', help='')
    # 获取相关参数
    args = parser.parse_args()
    mode = args.mode
    if mode == 'apply':
        result = parallel_apply(func=test_process, iterable=tqdm(range(20)),
                                workers=20, max_queue_size=1500, callback=None, )
        print(result)
        print('END')
    elif mode == 'pool':
        pool_ = Pool(20)
        result = pool_.map(test_process, tqdm(range(10)))
        pool_.close()
        pool_.join()
        print(result)
        print('END')
```

**Describe the current behavior**
A clear and concise description of what happened.

HanLP segment ->: 
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f994b134449, pid=79026, tid=0x00007f9960d80700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_121-b13) (build 1.8.0_121-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.121-b13 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [_jpype.cpython-35m-x86_64-linux-gnu.so+0x35449]  JPJavaEnv::NewString(unsigned short const*, int)+0x29
#
# Core dump written. Default location: /data1/jiangxl/bert4keras-master/pretraining/core or core.79026
#
# Can not save log file, dump to screen..
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f994b134449, pid=79026, tid=0x00007f9960d80700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_121-b13) (build 1.8.0_121-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.121-b13 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [_jpype.cpython-35m-x86_64-linux-gnu.so+0x35449]  JPJavaEnv::NewString(unsigned short const*, int)+0x29
#
# Core dump written. Default location: /data1/jiangxl/bert4keras-master/pretraining/core or core.79026
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#

---------------  T H R E A D  ---------------

Current thread is native thread

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x0000000000000000

Registers:
RAX=0x0000000001f26eb0, RBX=0x0000000000000000, RCX=0x0000000000000000, RDX=0x00000000008ddd00
RSP=0x00007f9960d7dc60, RBP=0x0000000001f26eb0, RSI=0x0000000000000000, RDI=0x00000000008ddd00
R8 =0x0000000000000000, R9 =0x000000000000000c, R10=0x0000000000000002, R11=0x0000000000a16e00
R12=0x00007f981c001910, R13=0x0000000000000005, R14=0x00007f9960d7dde0, R15=0x00007f9960d7dd60
RIP=0x00007f994b134449, EFLAGS=0x0000000000010202, CSGSFS=0x0000000000000033, ERR=0x0000000000000004
  TRAPNO=0x000000000000000e

Top of Stack: (sp=0x00007f9960d7dc60)
0x00007f9960d7dc60:   00007f9960d7dca0 00007f981c001910
0x00007f9960d7dc70:   0000000000000005 00007f9960d7dca0
0x00007f9960d7dc80:   0000000001de9df8 00007f994b142f2f
0x00007f9960d7dc90:   00007f9960d7dcbf 00007f990c0d80f8
0x00007f9960d7dca0:   00007f994b3805d0 00007f981c0018f0
0x00007f9960d7dcb0:   0000000000000005 0000000000512e89
0x00007f9960d7dcc0:   0000000000000000 0000000000000001
0x00007f9960d7dcd0:   0000000000000001 00007f994b13f6d8
0x00007f9960d7dce0:   0000000000000000 0000000000000001
0x00007f9960d7dcf0:   0000000000000008 0000000000000000
0x00007f9960d7dd00:   00007f9960d7dde0 0000000000000001
0x00007f9960d7dd10:   0000000001de9df8 00007f9960d7dd5f
0x00007f9960d7dd20:   00007f9960d7dde0 0000000000000001
0x00007f9960d7dd30:   00007f990c0cce10 00007f994b140b03
0x00007f9960d7dd40:   00007f9960d7de00 00007f9960d7dde0
0x00007f9960d7dd50:   0000000000000000 00007f9960d7dde0
0x00007f9960d7dd60:   00007f981c001670 00007f981c0018d0
0x00007f9960d7dd70:   00007f9960d7de00 00007f99bdff9ad8
0x00007f9960d7dd80:   0000000000000001 00007f981c0018d0
0x00007f9960d7dd90:   00007f9960d7de00 00007f994b1674a2
0x00007f9960d7dda0:   00007f9960d7ddd0 00007f9960d7dde0
0x00007f9960d7ddb0:   00007f9960d7ddcf 00007f994b0e8f00
0x00007f9960d7ddc0:   00007f994b0e3188 0000000000474a23
0x00007f9960d7ddd0:   00007f981c0018d0 00007f99c53dd630
0x00007f9960d7dde0:   00007f981c0015b0 00007f981c0015b8
0x00007f9960d7ddf0:   00007f981c0015b8 00007f9960d7de40
0x00007f9960d7de00:   00007f994b380590 00007f981c001600
0x00007f9960d7de10:   00007f981c001608 00007f981c001608
0x00007f9960d7de20:   0000000000000004 00007f994b0e8f00
0x00007f9960d7de30:   00007f994b167380 0000000001f26eb0
0x00007f9960d7de40:   00007f994b0e8f00 0000000000000000
0x00007f9960d7de50:   00007f990c0cce10 0000000000437e60 

Instructions: (pc=0x00007f994b134449)
0x00007f994b134429:   f4 55 53 48 83 ec 08 e8 4b d3 fe ff 48 89 c3 e8
0x00007f994b134439:   93 c9 fe ff 48 8b 10 48 89 c7 ff 52 30 48 89 c5
0x00007f994b134449:   48 8b 03 44 89 ea 48 89 df 4c 89 e6 ff 90 18 05
0x00007f994b134459:   00 00 48 89 c3 e8 6d c9 fe ff 48 89 c7 48 8b 00 

Register to memory mapping:

RAX=0x0000000001f26eb0 is an unknown value
RBX=0x0000000000000000 is an unknown value
RCX=0x0000000000000000 is an unknown value
RDX=0x00000000008ddd00: <offset 0x4ddd00> in python3 at 0x0000000000400000
RSP=0x00007f9960d7dc60 is an unknown value
RBP=0x0000000001f26eb0 is an unknown value
RSI=0x0000000000000000 is an unknown value
RDI=0x00000000008ddd00: <offset 0x4ddd00> in python3 at 0x0000000000400000
R8 =0x0000000000000000 is an unknown value
R9 =0x000000000000000c is an unknown value
R10=0x0000000000000002 is an unknown value
R11=0x0000000000a16e00 is an unknown value
R12=0x00007f981c001910 is an unknown value
R13=0x0000000000000005 is an unknown value
R14=0x00007f9960d7dde0 is an unknown value
R15=0x00007f9960d7dd60 is an unknown value

Stack: [0x00007f9960581000,0x00007f9960d81000],  sp=0x00007f9960d7dc60,  free space=8179k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [_jpype.cpython-35m-x86_64-linux-gnu.so+0x35449]  JPJavaEnv::NewString(unsigned short const*, int)+0x29

---------------  P R O C E S S  ---------------

VM state:not at safepoint (normal execution)

VM Mutex/Monitor currently owned by a thread: None

Heap:
 PSYoungGen      total 305664K, used 124003K [0x00000000d5580000, 0x00000000eaa80000, 0x0000000100000000)
  eden space 262144K, 47% used [0x00000000d5580000,0x00000000dce98e28,0x00000000e5580000)
  from space 43520K, 0% used [0x00000000e8000000,0x00000000e8000000,0x00000000eaa80000)
  to   space 43520K, 0% used [0x00000000e5580000,0x00000000e5580000,0x00000000e8000000)
 ParOldGen       total 699392K, used 0K [0x0000000080000000, 0x00000000aab00000, 0x00000000d5580000)
  object space 699392K, 0% used [0x0000000080000000,0x0000000080000000,0x00000000aab00000)
 Metaspace       used 4217K, capacity 5120K, committed 5376K, reserved 1056768K
  class space    used 466K, capacity 496K, committed 512K, reserved 1048576K

Card table byte_map: [0x00007f9939e9c000,0x00007f993a29d000] byte_map_base: 0x00007f9939a9c000

Marking Bits: (ParMarkBitMap*) 0x00007f994b091c80
 Begin Bits: [0x00007f9914000000, 0x00007f9916000000)
 End Bits:   [0x00007f9916000000, 0x00007f9918000000)

Polling page: 0x00007f99c5444000

CodeCache: size=245760Kb used=4071Kb max_used=4086Kb free=241688Kb
 bounds [0x00007f993a65d000, 0x00007f993aa6d000, 0x00007f994965d000]
 total_blobs=565 nmethods=309 adapters=166
 compilation: enabled

Compilation events (10 events):
Event: 0.787 Thread 0x0000000001d60800  305       4       com.hankcs.hanlp.model.perceptron.model.LinearModel::load (165 bytes)
Event: 0.790 Thread 0x0000000001d69000  306       1       java.nio.Buffer::position (5 bytes)
Event: 0.790 Thread 0x0000000001d69000 nmethod 306 0x00007f993aa368d0 code [0x00007f993aa36a20, 0x00007f993aa36b30]
Event: 0.820 Thread 0x0000000001d6b800  307       1       java.nio.channels.spi.AbstractInterruptibleChannel::isOpen (5 bytes)
Event: 0.820 Thread 0x0000000001d6b800 nmethod 307 0x00007f993aa25590 code [0x00007f993aa256e0, 0x00007f993aa257f0]
Event: 0.825 Thread 0x0000000001d60800 nmethod 305 0x00007f993aa5b190 code [0x00007f993aa5b4c0, 0x00007f993aa5cba8]
Event: 0.872 Thread 0x0000000001d67000  308       3       java.lang.ThreadLocal::getMap (5 bytes)
Event: 0.872 Thread 0x0000000001d67000 nmethod 308 0x00007f993aa3e410 code [0x00007f993aa3e580, 0x00007f993aa3e6f0]
Event: 0.883 Thread 0x0000000001d6d800  309       3       java.lang.ThreadLocal::get (38 bytes)
Event: 0.883 Thread 0x0000000001d6d800 nmethod 309 0x00007f993aa5aa50 code [0x00007f993aa5abe0, 0x00007f993aa5af98]

GC Heap History (0 events):
No events

Deoptimization events (10 events):
Event: 0.542 Thread 0x0000000001780000 Uncommon trap: reason=array_check action=maybe_recompile pc=0x00007f993aa18bf8 method=java.util.AbstractCollection.toArray([Ljava/lang/Object;)[Ljava/lang/Object; @ 119
Event: 0.542 Thread 0x0000000001780000 Uncommon trap: reason=array_check action=maybe_recompile pc=0x00007f993aa18bf8 method=java.util.AbstractCollection.toArray([Ljava/lang/Object;)[Ljava/lang/Object; @ 119
Event: 0.542 Thread 0x0000000001780000 Uncommon trap: reason=array_check action=maybe_recompile pc=0x00007f993aa18bf8 method=java.util.AbstractCollection.toArray([Ljava/lang/Object;)[Ljava/lang/Object; @ 119
Event: 0.641 Thread 0x0000000001780000 Uncommon trap: reason=unstable_if action=reinterpret pc=0x00007f993aa0d7a0 method=java.util.TreeMap.getEntry(Ljava/lang/Object;)Ljava/util/TreeMap$Entry; @ 36
Event: 0.653 Thread 0x0000000001780000 Uncommon trap: reason=unstable_if action=reinterpret pc=0x00007f993aa2cc90 method=com.hankcs.hanlp.corpus.io.ByteArrayFileStream.ensureAvailableBytes(I)V @ 10
Event: 0.663 Thread 0x0000000001780000 Uncommon trap: reason=unstable_if action=reinterpret pc=0x00007f993aa37664 method=com.hankcs.hanlp.corpus.io.ByteArrayFileStream.ensureAvailableBytes(I)V @ 10
Event: 0.692 Thread 0x0000000001780000 Uncommon trap: reason=unstable_if action=reinterpret pc=0x00007f993aa40950 method=com.hankcs.hanlp.collection.trie.datrie.IntArrayList.load(Lcom/hankcs/hanlp/corpus/io/ByteArray;)Z @ 31
Event: 0.702 Thread 0x0000000001780000 Uncommon trap: reason=unstable_if action=reinterpret pc=0x00007f993aa20240 method=com.hankcs.hanlp.corpus.io.ByteArrayFileStream.ensureAvailableBytes(I)V @ 10
Event: 0.745 Thread 0x0000000001780000 Uncommon trap: reason=unstable_if action=reinterpret pc=0x00007f993aa3f010 method=com.hankcs.hanlp.model.perceptron.model.LinearModel.load(Lcom/hankcs/hanlp/corpus/io/ByteArray;)Z @ 106
Event: 0.750 Thread 0x0000000001780000 Uncommon trap: reason=unstable_if action=reinterpret pc=0x00007f993aa14e28 method=java.util.ArrayList.grow(I)V @ 15

Internal exceptions (7 events):
Event: 0.061 Thread 0x0000000001780000 Exception <a 'java/lang/NoSuchMethodError': Method sun.misc.Unsafe.defineClass(Ljava/lang/String;[BII)Ljava/lang/Class; name or signature does not match> (0x00000000d5587ca8) thrown at [/HUDSON3/workspace/8-2-build-linux-amd64/jdk8u121/8372/hotspot/src/sh
Event: 0.061 Thread 0x0000000001780000 Exception <a 'java/lang/NoSuchMethodError': Method sun.misc.Unsafe.prefetchRead(Ljava/lang/Object;J)V name or signature does not match> (0x00000000d5587f90) thrown at [/HUDSON3/workspace/8-2-build-linux-amd64/jdk8u121/8372/hotspot/src/share/vm/prims/jni.c
Event: 0.209 Thread 0x0000000001780000 Exception <a 'java/security/PrivilegedActionException'> (0x00000000d56adce0) thrown at [/HUDSON3/workspace/8-2-build-linux-amd64/jdk8u121/8372/hotspot/src/share/vm/prims/jvm.cpp, line 1390]
Event: 0.209 Thread 0x0000000001780000 Exception <a 'java/security/PrivilegedActionException'> (0x00000000d56adef0) thrown at [/HUDSON3/workspace/8-2-build-linux-amd64/jdk8u121/8372/hotspot/src/share/vm/prims/jvm.cpp, line 1390]
Event: 0.210 Thread 0x0000000001780000 Exception <a 'java/security/PrivilegedActionException'> (0x00000000d56b01c8) thrown at [/HUDSON3/workspace/8-2-build-linux-amd64/jdk8u121/8372/hotspot/src/share/vm/prims/jvm.cpp, line 1390]
Event: 0.210 Thread 0x0000000001780000 Exception <a 'java/security/PrivilegedActionException'> (0x00000000d56b03d8) thrown at [/HUDSON3/workspace/8-2-build-linux-amd64/jdk8u121/8372/hotspot/src/share/vm/prims/jvm.cpp, line 1390]
Event: 0.255 Thread 0x0000000001780000 Exception <a 'java/lang/NoClassDefFoundError': Ljava/lang;> (0x00000000d576d2c0) thrown at [/HUDSON3/workspace/8-2-build-linux-amd64/jdk8u121/8372/hotspot/src/share/vm/classfile/systemDictionary.cpp, line 199]

**Expected behavior**
正常分词输出

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version:
- HanLP version:

python3.5
pyhanlp 0.1.44
JPype1 0.6.3

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
你需要在主进程执行初始化：

```
from multiprocessing import Pool
from tqdm import tqdm
from pyhanlp import HanLP

print(HanLP.segment('hello'))


def test_process(tmp: int):
    print(str(tmp) + '\n')
    print(HanLP.segment("商品和服务"))
    return str(tmp)


pool_ = Pool(2)
result = pool_.map(test_process, tqdm(range(10)))
pool_.close()
pool_.join()
print(result)
print('END')

```
