### ISSUE TITLE
用Hanlp中的NLPTokenizer分词时，对数据库中的45000数据没问题，当对50000数据分词后，就产生空指针错误！

### ISSUE THREAD

**Issue by nmdxpc** [hankcs/HanLP#163]
![image](https://cloud.githubusercontent.com/assets/17736168/13973846/ccb7b3a4-f0e1-11e5-8e26-f64a5a6d66d3.png)
![image](https://cloud.githubusercontent.com/assets/17736168/13973847/d2c1852c-f0e1-11e5-873e-9cc0a987cd0f.png)
有知道这是什么原因的么？

**Comment by hankcs** [comment]
你并不懂如何交流。你既不告诉我你用的是什么版本，也不告诉我你是怎么调用的，还不告诉我那5000条数据是什么。

这种issue在正常情况下不应该被回复，我今天恰好有空，所以勉强说说。

很明显你传入了一个空指针的String进去，你指望底层库容忍你的粗心，然而我的思维是效率至上，不愿为你检查参数。

既然错了，就应该尽快汇报出来，而不是让别人背黑锅，就是这么设计的。
