### ISSUE TITLE
Issue on page /api/hanlp/pretrained/word2vec.html

### ISSUE THREAD

**Issue by peter6888** [hankcs/HanLP#1632]
when try to load this, I see below error. Shall I create a separate config.json? 

`>>> w2v = hanlp.load(hanlp.pretrained.word2vec.RADICAL_CHAR_EMBEDDING_100)
Downloading https://file.hankcs.com/hanlp/embeddings/radical_char_vec_20191229_013849.zip#character.vec.txt to /Users/pe.li/.hanlp/embeddings/radical_char_vec_20191229_013849.zip
100.00%, 3.7 MB/3.7 MB, 2.9 MB/s, ETA 0 s
Extracting /Users/pe.li/.hanlp/embeddings/radical_char_vec_20191229_013849.zip to /Users/pe.li/.hanlp/embeddings
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pe.li/miniconda3/envs/hanlp/lib/python3.8/site-packages/hanlp/__init__.py", line 44, in load
    return load_from_meta_file(save_dir, 'meta.json', verbose=verbose, **kwargs)
  File "/Users/pe.li/miniconda3/envs/hanlp/lib/python3.8/site-packages/hanlp/utils/component_util.py", line 53, in load_from_meta_file
    raise FileNotFoundError(f'The identifier {save_dir} resolves to a non-exist meta file {metapath}. {tips}')
FileNotFoundError: The identifier /Users/pe.li/.hanlp/embeddings/radical_char_vec_20191229_013849/character.vec.txt resolves to a non-exist meta file /Users/pe.li/.hanlp/embeddings/radical_char_vec_20191229_013849/character.vec.txt/config.json.`

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form when open a new issue.
