### ISSUE TITLE
FileNotFoundError: The identifier cc.en.300.bin resolves to a non-exist meta file config.json

### ISSUE THREAD

**Issue by peter6888** [hankcs/HanLP#1633]
**Describe the bug**
FileNotFoundError when try to load word2vec pre-trainned model

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
import hanlp
fst = hanlp.load(hanlp.pretrained.fasttext.FASTTEXT_CC_300_EN)
```

**Describe the current behavior**
load FASTTEXT_CC_300_EN failed with FileNotFoundError

**Expected behavior**
load FASTTEXT_CC_300_EN model should success 

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS
- Python version: Python 3.8.8
- HanLP version: Version: 2.1.0a36

**Other info / logs**
```
(hanlp) ACTIONTRUSTNAME:~ pe.li$ python
Python 3.8.8 (default, Feb 24 2021, 13:46:16)
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import hanlp
>>> fst = hanlp.load(hanlp.pretrained.fasttext.FASTTEXT_CC_300_EN)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pe.li/miniconda3/envs/hanlp/lib/python3.8/site-packages/hanlp/__init__.py", line 43, in load
    return load_from_meta_file(save_dir, 'meta.json', verbose=verbose, **kwargs)
  File "/Users/pe.li/miniconda3/envs/hanlp/lib/python3.8/site-packages/hanlp/utils/component_util.py", line 53, in load_from_meta_file
    raise FileNotFoundError(f'The identifier {save_dir} resolves to a non-exist meta file {metapath}. {tips}')
FileNotFoundError: The identifier /Users/pe.li/.hanlp/thirdparty/dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.en.300.bin resolves to a non-exist meta file /Users/pe.li/.hanlp/thirdparty/dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.en.300.bin/config.json.
```

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
For some thirdparty embeddings, you'll need to create coressponding object and call its `load`, e.g.

https://github.com/hankcs/HanLP/blob/bce4a4e2dabcc9e0a07bfa3f8eed3ae351657041/hanlp/layers/embeddings/fast_text.py#L18-L22
