### ISSUE TITLE
convertToPinyinList方法，返回了所有同音字的拼音。

### ISSUE THREAD

**Issue by liuyan731** [hankcs/HanLP#1634]
**Describe the bug**
convertToPinyinList方法，返回了所有同音字的拼音。

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```Java
System.out.println(HanLP.convertToPinyinString("你好", " ", false));
// ni hao hao
```

**Describe the current behavior**
convertToPinyinList方法返回了多音字所有的拼音，导致返回的拼音字符串有多余的多音字，同时当需要转拼音字符串有中英混杂时，会出现报错IndexOutOfBoundaryException。1.7.8无此问题。

**Expected behavior**
“你好”返回“ni hao”而不是“ni hao hao”。

**System information**
- Linux、Windows
- Python version:
- HanLP version:1.8.0

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。
