### ISSUE TITLE
维特比分隔识别人名的问题

### ISSUE THREAD

**Issue by yoyokko** [hankcs/HanLP#164]
新华社专电（记者熊琳）《鬼吹灯》作者张牧野认为电影《九层妖塔》涉嫌侵犯著作权，将中国电影股份有限公司和导演陆川起诉至北京市西城区人民法院。记者20日从法院获悉，在受理该案后，应被告之一陆川申请，法院追加梦想者电影（北京）有限公司、乐视影业（北京）有限公司为本案共同被告。今年1月7日，《鬼吹灯》作者张牧野起诉称。电影《九层妖塔》系由《鬼吹灯之精绝古城》改编拍摄而成，但《九层妖塔》的故事情节、人物设置、故事背景均与原著相差甚远，超出了法律允许的必要的改动范围，构成对原著的歪曲和篡改，给原告造成了精神伤害，侵犯了原告的保护作品完整权。故将中国电影股份有限公司及陆川诉至法院，请求法院判令二被告立即停止侵权行为，向张牧野公开赔礼道歉、消除影响，并赔偿张牧野损失100万元人民币。本案立案后，被告之一陆川申请追加梦想者电影（北京）有限公司、乐视影业（北京）有限公司为共同被告。陆川认为梦想者电影（北京）有限公司与乐视影业（北京）有限公司为电影《九层妖塔》出品方即影片著作权人，应当作为共同被告参加本案诉讼。张牧野亦同意将梦想者电影公司和乐视影业追加为共同被告。西城法院在充分考虑原被告意见的基础上，为了便于查清案件事实，按照相关法律规定，已同意追加上述二公司为本案被告。

上面这段文本，在 PersonRecognition.Recognition.roleTag 后，熊琳 的角色标注为 [熊 B 885 D 16 C 4 E 4 K 1 ][琳 D 511 E 355 C 89 L 1 ]，这两个词是从词典里查出来的，但是在 PersonRecognition.Recognition.viterbiExCompute 后将 熊琳 的角色标注改为了 熊/D ,琳/L 。

这个是转移概率矩阵有问题吗？

**Comment by yoyokko** [comment]
G,6,0,0,1000,0,0,0,0,2907,1000,0,0,0,0,0

G->D的概率比 G->B 的概率高 1000?

改成

G,6,0,0,0,0,0,0,0,2907,1000,0,0,0,0,0

熊/B ,琳/E 
识别出人名：熊琳 BE
识别出人名：方即 BC

请教下这个转移概率矩阵是怎么得出来的呢？

**Comment by yoyokko** [comment]
方即得问题，通过添加自定义词典解决。
出品方 nn 3
出品 v 2

**Comment by hankcs** [comment]
请参考http://www.hankcs.com/nlp/chinese-name-recognition-in-actual-hmm-viterbi-role-labeling.html

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
