### ISSUE TITLE
使用HanLP搭配Solr 4.10與Tomcat 7.0.68，在使用"analysis"用來驗證中文分詞的結果，卻出現下列錯誤訊息"null:java.lang.RuntimeException: java.lang.AbstractMethodError"

### ISSUE THREAD

**Issue by vincentchien** [hankcs/HanLP#165]
您好，我使用HanLP搭配Solr 4.10與Tomcat 7.0.68，在solr admin 介面使用"analysis"用來驗證中文分詞的結果，卻出現下列錯誤訊息"null:java.lang.RuntimeException: java.lang.AbstractMethodError"，請問是什麼原因呢？我使用的插件版本為hanlp-portable-1.2.9.jar,hanlp-solr-plugin-1.0.3.jar，還請您協助我排除這個問題，謝謝！

**Comment by hankcs** [comment]
你好，该插件只支持Solr5.x。

**Comment by hankcs** [comment]
你可以直接运行demohttps://github.com/hankcs/HanLP/blob/master/src/test/java/com/hankcs/demo/DemoTraditionalChineseSegment.java查看繁体中文分词效果，如果要用到solr4上面，需要自行降级。如果还有问题，欢迎继续讨论。

**Comment by vincentchien** [comment]
謝謝你的回覆

hankcs <notifications@github.com> 於 2016年3月25日 星期五寫道：
