### ISSUE TITLE
有些中文字會誤判為標點符號（ctb: PU)

### ISSUE THREAD

**Issue by u8621011** [hankcs/HanLP#1650]
**Describe the bug**
有些中文字會誤判為標點符號.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
import hanlp

HanLP = hanlp.load(hanlp.pretrained.mtl.CLOSE_TOK_POS_NER_SRL_DEP_SDP_CON_ELECTRA_SMALL_ZH)

test_cases = [
        '嗯..啊..我們沒有收到檢舉啊',
        '普丁就大量的來汙衊希拉蕊',
        '去洗那個鹼 去洗那個鹽',
        '福島那個是爆炸的問題 核電廠那個氚洗不掉的',
        '像它的模式可以改成15分鐘或者是永..永久',
        '禿溜窩 哈批溜 歐普搜',
    ]   

for c in test_cases:
    HanLP(c, tasks=['tok/fine', 'pos/ctb'])

```

**Describe the current behavior**
這幾個字會誤判為 標點符號 (PU）: 

嗯..（PU）：嗯..啊..我們沒有收到檢舉啊
啊..（PU）：嗯..啊..我們沒有收到檢舉啊
衊（PU）：普丁就大量的來汙衊希拉蕊
鹼（PU）： 去洗那個鹼
氚（PU）： 福島那個是爆炸的問題 核電廠那個氚洗不掉的
永（PU）：像它的模式可以改成15分鐘或者是永..永久
溜（PU）：禿溜窩 哈批溜 歐普搜

**Expected behavior**
應該至少要知道是中文。不論詞性正確與否

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Windows 10
- Python version: Python 3.7.3 
- HanLP version:  2.1.0a38

**Other info / logs**
```
2021-05-14 09:42:45,673 - unittest - INFO - {
  "tok/fine": [
    "嗯..",
    "啊..",
    "我們",
    "沒有",
    "收到",
    "檢舉",
    "啊"
  ],
  "pos/ctb": [
    "PU",
    "PU",
    "PN",
    "VV",
    "VV",
    "NN",
    "SP"
  ]
}

2021-05-14 09:42:45,694 - unittest - INFO - {
  "tok/fine": [
    "普丁",
    "就",
    "大量",
    "的",
    "來汙",
    "衊",
    "希拉蕊"
  ],
  "pos/ctb": [
    "NR",
    "AD",
    "CD",
    "DEV",
    "VV",
    "PU",
    "NR"
  ]
}

2021-05-14 09:42:45,712 - unittest - INFO - {
  "tok/fine": [
    "去",
    "洗",
    "那",
    "個",
    "鹼"
  ],
  "pos/ctb": [
    "VV",
    "VV",
    "DT",
    "M",
    "PU"
  ]
}

2021-05-14 09:42:45,772 - unittest - INFO - {
  "tok/fine": [
    "核電廠",
    "那",
    "個",
    "氚",
    "洗",
    "不",
    "掉",
    "的"
  ],
  "pos/ctb": [
    "NN",
    "DT",
    "M",
    "PU",
    "VV",
    "AD",
    "VV",
    "SP"
  ]
}

2021-05-14 09:42:45,792 - unittest - INFO - {
  "tok/fine": [
    "像",
    "它",
    "的",
    "模式",
    "可以",
    "改成",
    "15",
    "分鐘",
    "或者",
    "是",
    "永..",
    "永久"
  ],
  "pos/ctb": [
    "P",
    "PN",
    "DEG",
    "NN",
    "VV",
    "VV",
    "CD",
    "M",
    "CC",
    "VC",
    "PU",
    "VA"
  ]
}


2021-05-14 09:42:45,830 - unittest - INFO - {
  "tok/fine": [
    "哈批",
    "溜"
  ],
  "pos/ctb": [
    "IJ",
    "PU"
  ]
}

2021-05-14 09:42:45,830 - unittest - INFO - {
  "tok/fine": [
    "哈批",
    "溜"
  ],
  "pos/ctb": [
    "IJ",
    "PU"
  ]
}
```

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
`..`的问题可能是由于SMALL model的domain transfer能力较差，用BASE model就好了，或者加到词典里：

```
HanLP['tok/fine'].dict_force = {'..'}
```

`衊鹼`的简繁映射有误，暂时的修复办法：

```
HanLP.config['transform']._table['衊'] = '蔑'
HanLP.config['transform']._table['鹼'] = '碱'
```

不过我不太懂`禿溜窩 哈批溜 歐普搜`这句话，CTB是完全简体语境，所以还是用BASE比较好一些。

See https://colab.research.google.com/drive/1NaAGYJIULwOrorYcirsJ9SYSzy585btx?usp=sharing

**Comment by u8621011** [comment]
很感謝如此完整的回覆以及建議。 已經試著使用 BASE model 來整個跑一次，但是發生了新的 bug，也已經提報。

另外看到您的回覆才發現，原來內部的繁體中文分詞是採用轉換到簡體後，然後分詞，再轉回簡體中文的方式？

很驚訝這樣的方式下，還有這麼高的準確率，也很佩服您正在進行的事情。


想順便跟您請教，HanLP 2.1 目前有沒有比較完整的，可以試著自行訓練 繁體中文 model 的指示？


`禿溜窩 哈批溜 歐普搜` 這句話其實我也不懂是什麼意思，因為我這些 test case 是 youtube 上的字幕語料，所以有很多口語甚至網路用語或者 youtuber 胡亂發出來的火星文 XD

**Comment by u8621011** [comment]
> `..`的问题可能是由于SMALL model的domain transfer能力较差，用BASE model就好了，或者加到词典里：
> 
> ```
> HanLP['tok/fine'].dict_force = {'..'}
> ```
> 
> `衊鹼`的简繁映射有误，暂时的修复办法：
> 
> ```
> HanLP.config['transform']._table['衊'] = '蔑'
> HanLP.config['transform']._table['鹼'] = '碱'
> ```
> 
> 不过我不太懂`禿溜窩 哈批溜 歐普搜`这句话，CTB是完全简体语境，所以还是用BASE比较好一些。
> 
> See https://colab.research.google.com/drive/1NaAGYJIULwOrorYcirsJ9SYSzy585btx?usp=sharing

使用 base modal 重跑了一次。在 base modal 有一些 test case 會有奇怪的 POS誤判（PU & EM) 。

如下：
```python
test_cases = [
    '痾...怎麼給我斷在這裡!!!',  # 痾: PU
    '有一個很高的跑酷的地圖欸', # 欸: PU
    '咕奈(´・ω・)', # 咕奈(´・ω・): EM(unknown pos?)
    '矽膠墊', # 墊: PU
    '所以牛奶要把它煮到滾是不是', # 滾: PU
    '要回煮把它煮到再度地變穠稠',    # 穠: PU
    '那裡有那個吔', # 吔: PU
    '哇(´･_･`)', # 哇(´･_･`): EM(unknown pos)
    '清潔溜溜', # 溜溜: PU
    '對啊~我人真好(*´V`)~', # 好(*´V`)~: EM
    '這個是真..的', # ..的: PU
    '哇(,,ﾟДﾟ)', # 哇(,,: PU
    '哈(*´･д･)?', # 哈(*´･д･): EM(unknown pos)
    '上面的道具欄..嘸啊!', # 嘸: PU
    '所以你看我們的蛋糕糊', # 糊: PU
    '去洗那個鹼', # 鹼: PU
    '財源滾滾來', # 滾滾: PU
    '芋頭還有土雞下窯焢耶', # 焢: PU
    '幾小時也過去了', # 了: PU
    '既然沒有辦法牽罟', # 罟: PU
    '(就是呂 游 蘇 謝)', # 謝): EM(unknown pos)
    '嗷(´・ω・)', # 嗷(´・ω・): EM(unknown pos)
    '拜託', # 託: PU
    '嘿(´・ω・)', # 嘿(´・ω・): EM(unknown pos)
    '路..', # 路..: PU
    '好~像是', #  ~像: PU
]    
```

**Comment by hankcs** [comment]
- EM是emoji
- ..的问题请使用自定义词典
- 由于CTB中的句子大部分最后一个单词是PU，所以你的case里面很多最后一个字符被当成了PU。
    - 这属于domain transfer的问题，目前没有很好的解决方案，除非有繁体的非正式语料
    - 我会尝试data augment，但这需要一段时间，我会在新模型发布的时候关闭这个issue

**Comment by u8621011** [comment]
>   * 这属于domain transfer的问题，目前没有很好的解决方案，除非有繁体的非正式语料
我們是一個語言學習平台，也在試著透過使用者的自學歷程來收集 詞典/語料。  如果有明確一點的資訊，或許我們可將搜集到的語料貢獻出來與大家分享。

>   * 我会尝试data augment，但这需要一段时间，我会在新模型发布的时候关闭这个issue于是你会收到通知
好的，很感謝您。

**Comment by hankcs** [comment]
> 我們是一個語言學習平台，也在試著透過使用者的自學歷程來收集 詞典/語料。 如果有明確一點的資訊，或許我們可將搜集到的語料貢獻出來與大家分享。

太好了，HanLP有一个`pretty_print`方法会打印漂亮的输出，单词之间用空格隔开，词性之间用/隔开：

```
    doc = HanLP(c, tasks=['tok/fine', 'pos/ctb'])
    doc.pretty_print()

咕奈(´・ω・)/EM
矽膠/NN 墊/PU
```

如果你注意到任何断词或词性的错误，欢迎将其改成后发给我。比如上面的例子应该改为：

```
咕奈/IJ (´・ω・)/EM
矽膠/NN 墊/NN
```

**Comment by u8621011** [comment]
@hankcs 一個題外話。

POS 系統，你有沒有個人比較傾向哪個？  當初我挑選 CTB 是看起來相對簡單，其他如 PKU/863 好像略顯複雜，感覺一般人很難區別這麼詳細。

**Comment by hankcs** [comment]
我也比较喜欢CTB，所以将CTB作为模型的默认选项。CTB对词法的归类更科学一些，比如名词和形容词的界限非常清晰。词法本身也是短语句法的一部分，而PKU和863就没有这个优势了。在多语种环境下，CTB与UD更相似，未来发展也更promising。

**Comment by u8621011** [comment]
> 太好了，HanLP有一个`pretty_print`方法会打印漂亮的输出，单词之间用空格隔开，词性之间用/隔开：
> 
> ```
>     doc = HanLP(c, tasks=['tok/fine', 'pos/ctb'])
>     doc.pretty_print()
> 
> 咕奈(´・ω・)/EM
> 矽膠/NN 墊/PU
> ```
> 
> 如果你注意到任何断词或词性的错误，欢迎将其改成后发给我。比如上面的例子应该改为：
> 
> ```
> 咕奈/IJ (´・ω・)/EM
> 矽膠/NN 墊/NN
> ```

詞性的部分要將連結時程上沒有這麼快。  因為整體架構也正在設計規劃中而已。

不過如果單純的 分詞語料  倒是可以在更近期倒給你。  只是不知道幫助大不大？

**Comment by hankcs** [comment]
非常有帮助，你可以通过 hankcshe@gmail.com 联系我，谢谢。

**Comment by hankcs** [comment]
最新发布的`CLOSE_TOK_POS_NER_SRL_DEP_SDP_CON_ERNIE_GRAM_ZH`对这个问题有所改善：https://colab.research.google.com/drive/1NaAGYJIULwOrorYcirsJ9SYSzy585btx?usp=sharing

**Comment by u8621011** [comment]
很感謝通知~   近期再找個時間安排升版測試~

**Comment by hankcs** [comment]
刚刚发布了一个新的pos模型，采用我的一篇偏旁部首字向量的论文，现在基本解决了这个问题。详见colab：https://colab.research.google.com/drive/15K5bo4RT61awXi2Ssi97m5FG2VPeqpxJ?usp=sharing

如果解决了你的问题的话，随时可以关闭这个issue。

**Comment by forrestbing** [comment]
我也遇到了这个问题，简体中文如何通过 HanLP['tok/fine'].dict_force = {'..'} 插入带有词性的自定义分词呢，能否给个示例，现在只知道自定义分词，不知道该如何自定义词性

**Comment by u8621011** [comment]
經過再次測試確認已解決，很感謝您的協助。
