### ISSUE TITLE
韵母识别问题

### ISSUE THREAD

**Issue by dsx4602** [hankcs/HanLP#166]
用的hanlp-1.2.9+data-for-1.2.8-standard，用Java运行如下代码作为测试：
`String text="依山会略句率学子";`
`List<Pinyin> listPinyin = HanLP.convertToPinyinList(text);`
`for (Pinyin pinyin : listPinyin){`
`System.out.printf("%s,", pinyin.getYunmu());`
`}`
结果却是“i,an,ui,ue,u,v,ue,eng,”，最后“子”的韵母错了，这是为什么呢？

**Comment by hankcs** [comment]
感谢反馈，拼音词典已经修复：https://github.com/hankcs/HanLP/issues/166
