### ISSUE TITLE
centos 加载依存句法报错

### ISSUE THREAD

**Issue by Zxiaoma** [hankcs/HanLP#1664]
**Describe the bug**
其他功能OK，但是加载依存句法的时候出错了

**Code to reproduce the issue**
报错内容
dependency_info = HanLP.parseDependency(sentence)
jpype._jclass.ExceptionInInitializerError: None
```python
```

**Describe the current behavior**
直接报错退出

**Expected behavior**
win系统都好好的，部署到linux就跪了，希望能运行起来吧

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  centos7
- Python version: 3.6.8
- HanLP version: 1.7.5
- JDK version：1.8.0_252

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
路径配错了，HanLP.Config.enableDebug()自行排查。
