### ISSUE TITLE
cannot import name 'albert_models_tfhub' from 'bert' 

### ISSUE THREAD

**Issue by hxj8059** [hankcs/HanLP#1665]
**Describe the bug**
bert包里没有albert_models_tfhub
  File "C:\ProgramData\Anaconda3\envs\nlp\lib\site-packages\hanlp\layers\transformers\loader_tf.py", line 9, in <module>
    from bert import albert_models_tfhub, fetch_tfhub_albert_model, load_stock_weights
ImportError: cannot import name 'albert_models_tfhub' from 'bert' (C:\ProgramData\Anaconda3\envs\nlp\lib\site-packages\bert\__init__.py)

**Code to reproduce the issue**
import hanlp
import bert
from hanlp_restful import HanLPClient

test1 = '葛鹤军先生:博士学位。2008年至2011年就职于中诚信证券评估有限公司、中诚信国际信用评级有限公司。2011年11月加盟银华基金管理有限公司,历任研究员、基金经理助理。现任投资管理三部基金经理。自2014年10月8日起担任“银华中证中票50指数债券型证券投资基金(LOF)”“银华信用债券型证券投资基金(LOF)”的基金经理;自2014年10月8日起至2016年4月25日担任“银华中证成长股债恒定组合30/70指数证券投资基金”基金经理;自2015年4月24日起担任“银华泰利灵活配置混合型证券投资基金”基金经理;自2015年5月6日起担任“银华恒利灵活配置混合型证券投资基金”基金经理;自2015年6月17日起担任“银华信用双利债券型证券投资基金”基金经理;自2016年8月5日起担任“银华通利灵活配置混合型证券投资基金”基金经理;自2016年12月5日开始担任“银华上证10年期国债指数证券投资基金”基金经理;自2016年12月5日开始担任“银华上证5年期国债指数证券投资基金”基金经理;自2017年4月17日开始担任“银华中债-10年期国债期货期限匹配金融债指数证券投资基金”基金经理;自2017年4月17日开始担任“银华中债-5年期国债期货期限匹配金融债指数证券投资基金”基金经理。2018年7月加入长盛基金管理有限公司,现任固定收益部执行总监,自2018年12月6日起任长盛盛琪一年期定期开放债券型证券投资基金基金经理。拟任长盛安鑫中短债债券型证券投资基金基金经理。2020年9月29日起担任长盛盛裕纯债债券型证券投资基金基金经理。'

HanLP = hanlp.load(hanlp.pretrained.ner.MSRA_NER_ALBERT_BASE_ZH)
HanLP(test1)

```python
```

**Describe the current behavior**
启动不了

**Expected behavior**
正常启动

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version:
- HanLP version:

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
请不要自己安装第三方包，版本不对。请参考：https://hanlp.hankcs.com/docs/install.html#import-error
