### ISSUE TITLE
pip install hanlp[full] 的时候有依赖冲突

### ISSUE THREAD

**Issue by hxj8059** [hankcs/HanLP#1668]
**Describe the bug**
进行full的hanlp安装时，有2.1和2.0两个版本同时安装而且依赖的tf版本不同，无法安装。

WARNING: hanlp 2.0.0a5 does not provide the extra 'full'
  Using cached hanlp-2.0.0a4.tar.gz (872 kB)
WARNING: hanlp 2.0.0a4 does not provide the extra 'full'
  Using cached hanlp-2.0.0a3.tar.gz (867 kB)
WARNING: hanlp 2.0.0a3 does not provide the extra 'full'
ERROR: Cannot install hanlp[full]==2.0.0a10, hanlp[full]==2.0.0a11, hanlp[full]==2.0.0a12, hanlp[full]==2.0.0a13, hanlp[full]==2.0.0a14, hanlp[full]==2.0.0a15, hanlp[full]==2.0.0a16, h
anlp[full]==2.0.0a17, hanlp[full]==2.0.0a18, hanlp[full]==2.0.0a19, hanlp[full]==2.0.0a20, hanlp[full]==2.0.0a21, hanlp[full]==2.0.0a22, hanlp[full]==2.0.0a24, hanlp[full]==2.0.0a25, h
anlp[full]==2.0.0a26, hanlp[full]==2.0.0a27, hanlp[full]==2.0.0a28, hanlp[full]==2.0.0a29, hanlp[full]==2.0.0a3, hanlp[full]==2.0.0a30, hanlp[full]==2.0.0a31, hanlp[full]==2.0.0a32, ha
nlp[full]==2.0.0a33, hanlp[full]==2.0.0a34, hanlp[full]==2.0.0a35, hanlp[full]==2.0.0a36, hanlp[full]==2.0.0a37, hanlp[full]==2.0.0a38, hanlp[full]==2.0.0a39, hanlp[full]==2.0.0a4, han
lp[full]==2.0.0a40, hanlp[full]==2.0.0a41, hanlp[full]==2.0.0a42, hanlp[full]==2.0.0a43, hanlp[full]==2.0.0a44, hanlp[full]==2.0.0a45, hanlp[full]==2.0.0a46, hanlp[full]==2.0.0a47, han
lp[full]==2.0.0a48, hanlp[full]==2.0.0a49, hanlp[full]==2.0.0a5, hanlp[full]==2.0.0a50, hanlp[full]==2.0.0a51, hanlp[full]==2.0.0a52, hanlp[full]==2.0.0a53, hanlp[full]==2.0.0a54, hanl
p[full]==2.0.0a55, hanlp[full]==2.0.0a56, hanlp[full]==2.0.0a57, hanlp[full]==2.0.0a58, hanlp[full]==2.0.0a59, hanlp[full]==2.0.0a6, hanlp[full]==2.0.0a60, hanlp[full]==2.0.0a61, hanlp
[full]==2.0.0a62, hanlp[full]==2.0.0a63, hanlp[full]==2.0.0a64, hanlp[full]==2.0.0a65, hanlp[full]==2.0.0a66, hanlp[full]==2.0.0a67, hanlp[full]==2.0.0a68, hanlp[full]==2.0.0a69, hanlp
[full]==2.0.0a8, hanlp[full]==2.0.0a9, hanlp[full]==2.1.0a0, hanlp[full]==2.1.0a1, hanlp[full]==2.1.0a10, hanlp[full]==2.1.0a11, hanlp[full]==2.1.0a12, hanlp[full]==2.1.0a13, hanlp[ful
l]==2.1.0a14, hanlp[full]==2.1.0a15, hanlp[full]==2.1.0a16, hanlp[full]==2.1.0a17, hanlp[full]==2.1.0a18, hanlp[full]==2.1.0a19, hanlp[full]==2.1.0a2, hanlp[full]==2.1.0a20, hanlp[full
]==2.1.0a21, hanlp[full]==2.1.0a22, hanlp[full]==2.1.0a23, hanlp[full]==2.1.0a24, hanlp[full]==2.1.0a25, hanlp[full]==2.1.0a26, hanlp[full]==2.1.0a27, hanlp[full]==2.1.0a28, hanlp[full
]==2.1.0a29, hanlp[full]==2.1.0a3, hanlp[full]==2.1.0a30, hanlp[full]==2.1.0a31, hanlp[full]==2.1.0a32, hanlp[full]==2.1.0a33, hanlp[full]==2.1.0a34, hanlp[full]==2.1.0a35, hanlp[full]
==2.1.0a36, hanlp[full]==2.1.0a37, hanlp[full]==2.1.0a38, hanlp[full]==2.1.0a4, hanlp[full]==2.1.0a41, hanlp[full]==2.1.0a42, hanlp[full]==2.1.0a43, hanlp[full]==2.1.0a44, hanlp[full]=
=2.1.0a45, hanlp[full]==2.1.0a46, hanlp[full]==2.1.0a47, hanlp[full]==2.1.0a48, hanlp[full]==2.1.0a5, hanlp[full]==2.1.0a50, hanlp[full]==2.1.0a51, hanlp[full]==2.1.0a52, hanlp[full]==
2.1.0a53, hanlp[full]==2.1.0a6, hanlp[full]==2.1.0a7, hanlp[full]==2.1.0a8 and hanlp[full]==2.1.0a9 because these package versions have conflicting dependencies.

The conflict is caused by:
    hanlp[full] 2.1.0a53 depends on tensorflow==2.3.0; extra == "full"
    hanlp[full] 2.1.0a52 depends on tensorflow==2.3.0; extra == "full"
    hanlp[full] 2.1.0a51 depends on tensorflow==2.3.0; extra == "full"
    hanlp[full] 2.1.0a50 depends on tensorflow==2.3.0; extra == "full"
    hanlp[full] 2.1.0a48 depends on tensorflow==2.3.0; extra == "full"
    hanlp[full] 2.1.0a47 depends on tensorflow==2.3.0; extra == "full"
    hanlp[full] 2.1.0a46 depends on tensorflow==2.3.0; extra == "full"
    hanlp[full] 2.1.0a45 depends on tensorflow==2.3.0; extra == "full"
    hanlp[full] 2.1.0a44 depends on tensorflow==2.3.0; extra == "full"
    hanlp[full] 2.1.0a43 depends on tensorflow==2.3.0; extra == "full"
    hanlp[full] 2.1.0a42 depends on tensorflow==2.3.0
    hanlp[full] 2.1.0a41 depends on tensorflow==2.3.0
    hanlp[full] 2.1.0a38 depends on tensorflow==2.3.0
    hanlp[full] 2.1.0a37 depends on tensorflow==2.3.0
    hanlp[full] 2.1.0a36 depends on tensorflow==2.3.0
    hanlp[full] 2.1.0a35 depends on tensorflow==2.3.0
    hanlp[full] 2.1.0a34 depends on tensorflow==2.3.0
    hanlp[full] 2.1.0a33 depends on tensorflow==2.3.0
    hanlp[full] 2.1.0a32 depends on tensorflow==2.3.0
    hanlp[full] 2.1.0a31 depends on tensorflow==2.3.0
    hanlp[full] 2.1.0a30 depends on tensorflow==2.3.0
    hanlp[full] 2.1.0a29 depends on tensorflow==2.3.0
    hanlp[full] 2.1.0a28 depends on tensorflow==2.3.0
    hanlp[full] 2.1.0a27 depends on tensorflow==2.3.0
    hanlp[full] 2.1.0a26 depends on tensorflow==2.3.0
    hanlp[full] 2.1.0a25 depends on tensorflow==2.3.0
    hanlp[full] 2.1.0a24 depends on tensorflow==2.3.0
    hanlp[full] 2.1.0a23 depends on tensorflow==2.3.0
    hanlp[full] 2.1.0a22 depends on tensorflow==2.3.0
    hanlp[full] 2.1.0a21 depends on tensorflow==2.3.0
    hanlp[full] 2.1.0a20 depends on tensorflow==2.3.0
    hanlp[full] 2.1.0a19 depends on tensorflow==2.3.0
    hanlp[full] 2.1.0a18 depends on tensorflow==2.3.0
    hanlp[full] 2.1.0a17 depends on tensorflow==2.3.0
    hanlp[full] 2.1.0a16 depends on tensorflow==2.3.0
    hanlp[full] 2.1.0a15 depends on tensorflow==2.3.0
    hanlp[full] 2.1.0a14 depends on tensorflow==2.3.0
    hanlp[full] 2.1.0a13 depends on tensorflow==2.3.0
    hanlp[full] 2.1.0a12 depends on tensorflow==2.3.0
    hanlp[full] 2.1.0a11 depends on tensorflow==2.3.0
    hanlp[full] 2.1.0a10 depends on tensorflow==2.3.0
    hanlp[full] 2.1.0a9 depends on tensorflow==2.3.0
    hanlp[full] 2.1.0a8 depends on tensorflow==2.3.0
    hanlp[full] 2.1.0a7 depends on tensorflow==2.3.0
    hanlp[full] 2.1.0a6 depends on tensorflow==2.3.0
    hanlp[full] 2.1.0a5 depends on tensorflow==2.3.0
    hanlp[full] 2.1.0a4 depends on tensorflow==2.3.0
    hanlp[full] 2.1.0a3 depends on tensorflow==2.3.0
    hanlp[full] 2.1.0a2 depends on tensorflow==2.3.0
    hanlp[full] 2.1.0a1 depends on tensorflow==2.3.0
    hanlp[full] 2.1.0a0 depends on tensorflow==2.3.0
    hanlp[full] 2.0.0a69 depends on tensorflow==2.3.0
    hanlp[full] 2.0.0a68 depends on tensorflow==2.3.0
    hanlp[full] 2.0.0a67 depends on tensorflow==2.3.0
    hanlp[full] 2.0.0a66 depends on tensorflow==2.3.0
    hanlp[full] 2.0.0a65 depends on tensorflow==2.3.0
    hanlp[full] 2.0.0a64 depends on tensorflow==2.3.0
    hanlp[full] 2.0.0a63 depends on tensorflow==2.3.0
    hanlp[full] 2.0.0a62 depends on tensorflow==2.3.0
    hanlp[full] 2.0.0a61 depends on tensorflow==2.3.0
    hanlp[full] 2.0.0a60 depends on tensorflow==2.3.0
    hanlp[full] 2.0.0a59 depends on tensorflow==2.3.0
    hanlp[full] 2.0.0a58 depends on tensorflow==2.3.0
    hanlp[full] 2.0.0a57 depends on tensorflow==2.3.0
    hanlp[full] 2.0.0a56 depends on tensorflow==2.3.0
    hanlp[full] 2.0.0a55 depends on tensorflow==2.3.0
    hanlp[full] 2.0.0a54 depends on tensorflow==2.3.0
    hanlp[full] 2.0.0a53 depends on tensorflow==2.3.0
    hanlp[full] 2.0.0a52 depends on tensorflow==2.3.0
    hanlp[full] 2.0.0a51 depends on tensorflow==2.3.0
    hanlp[full] 2.0.0a50 depends on tensorflow==2.1.0
    hanlp[full] 2.0.0a49 depends on tensorflow==2.1.0
    hanlp[full] 2.0.0a48 depends on tensorflow==2.1.0
    hanlp[full] 2.0.0a47 depends on tensorflow==2.1.0
    hanlp[full] 2.0.0a46 depends on tensorflow==2.1.0
    hanlp[full] 2.0.0a45 depends on tensorflow==2.1.0
    hanlp[full] 2.0.0a44 depends on tensorflow==2.1.0
    hanlp[full] 2.0.0a43 depends on tensorflow==2.1.0
    hanlp[full] 2.0.0a42 depends on tensorflow==2.1.0
    hanlp[full] 2.0.0a41 depends on tensorflow==2.1.0
    hanlp[full] 2.0.0a40 depends on tensorflow==2.1.0
    hanlp[full] 2.0.0a39 depends on tensorflow==2.1.0
    hanlp[full] 2.0.0a38 depends on tensorflow==2.1.0
    hanlp[full] 2.0.0a37 depends on tensorflow==2.1.0
    hanlp[full] 2.0.0a36 depends on tensorflow==2.1.0
    hanlp[full] 2.0.0a35 depends on tensorflow==2.1.0
    ...

**Code to reproduce the issue**

```python
pip install hanlp[full] 
```

**Describe the current behavior**
pip提示冲突，无法安装

**Expected behavior**
正常安装
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows10
- Python version: 3.9.5
- HanLP version: full

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
Hi，这是正常情况。由于TF的兼容性很差，所以每个HanLP版本依赖一个特定的TF版本，2.1升级了TF版本之后必然与之前的版本不兼容。可以通过创建venv或conda环境来解决。

**Comment by hxj8059** [comment]
用conda新建的环境pip装的就是这样，是不是pip install hanlp[full]的时候hanlp装的版本太多了？

**Comment by hankcs** [comment]
是因为tf2.3最高只支持Python3.8，你得创建一个Python3.8的环境才能跑tf2.3。
```
conda install python=3.8 -y
pip install hanlp[full]
```

**Comment by hxj8059** [comment]
感谢！成功装好了

**Comment by aaronzhangTechGeek** [comment]
> 用conda新建的环境pip装的就是这样，是不是pip install hanlp[full]的时候hanlp装的版本太多了？

万分感谢，用你的方法解决了 not compatiable 的问题
