### ISSUE TITLE
关于多音字“莎”的拼音解析优化建议

### ISSUE THREAD

**Issue by RekaDowney** [hankcs/HanLP#1669]
**Describe the feature and the current behavior/state.**
**莎**这个多音字一般常见于人名，比如：`莎士比亚`，`丽莎`等，当前只发现在`莎草`这个词里读作 `suo`。
目前的拼音词典里将`suo`排在了`sha`前面，导致所有人名、地名的拼音转换全都不正确，是否将`sha`作为词典的第一顺位解析比较合适呢？

**Will this change the current api? How?**
修改词典文件[data/dictionary/pinyin/pinyin.txt](https://github.com/hankcs/HanLP/blob/1.x/data/dictionary/pinyin/pinyin.txt#L21325)，将`莎=suo1,sha1`调整成`莎=sha1,suo1`。

**Who will benefit with this feature?**
基本所有人都会受益于这次改动，毕竟`莎草`也已经定义到词典中了，剩余情况基本都是解释成`sha`。

**Are you willing to contribute it (Yes/No):**
如果有必要的话，我可以提交PR。当然作者直接调整会更快些。

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
- Python version: Java
- HanLP version: 
```xml
<dependency>
    <groupId>com.hankcs</groupId>
    <artifactId>hanlp</artifactId>
    <version>portable-1.8.2</version>
</dependency>
```

**Any other info**

* [ ] I've carefully completed this form.

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

开源项目维护不易，HanLP用户以十万计，而主要维护者只有我一人。我有自己的full-time研究工作，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
