### ISSUE TITLE
pos/ctb词性识别差异较大

### ISSUE THREAD

**Issue by SunnyZ-L** [hankcs/HanLP#1671]
**Describe the bug**
【整箱】金龙鱼五常稻花香原香稻大米2.5kg*4/箱新米

上面这条语句中2.5kg pos/ctb词性标注时，被标注成了url，感觉差异有点大，并且通过 *海量级native API* 的python语言进行识别，仍然被识别成了URL
![图片](https://user-images.githubusercontent.com/56599784/129319120-4df90514-9747-4f02-9beb-a0ff7ac1bdee.png)
![图片](https://user-images.githubusercontent.com/56599784/129319786-9ba92cb4-e99f-4f28-a63a-6e225e19d661.png)

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
test = ['【整箱】金龙鱼五常稻花香原香稻大米2.5kg*4/箱新米']
HanLP: MultiTaskLearning = hanlp.load(
    hanlp.pretrained.mtl.CLOSE_TOK_POS_NER_SRL_DEP_SDP_CON_ELECTRA_BASE_ZH)
lp = HanLP(test)
print(lp)
```

**Describe the current behavior**
A clear and concise description of what happened.

**Expected behavior**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): win10
- Python version: 3.8.10
- HanLP version: test = ['【整箱】金龙鱼五常稻花香原香稻大米2.5kg*4/箱新米']

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
应该是CTB中新闻占主导的原因，很少见到电商领域。下个模型计划引入一些数据增强的手段，这个issue留作tracking。

**Comment by hankcs** [comment]
最新发布的`CLOSE_TOK_POS_NER_SRL_DEP_SDP_CON_ERNIE_GRAM_ZH`对这个问题有所改善。

**Comment by zhj12388** [comment]
我也有一个类似的问题：“极简生活炭金炫洁牙刷双重植毛工艺双倍清洁”句子通过hanlp分词得到的结果牙刷都不是一个词，
得到的分词结果如下：极简生活,生活,炭,金炫,洁牙,刷,双重,植,毛,工艺,双倍,清洁
我配置过“极简生活”和“炭金炫洁”，结果“炭金炫洁”还是不识别，关键是牙刷被拆开很尴尬

**Comment by hankcs** [comment]
根据我们的[最新研究](https://aclanthology.org/2021.emnlp-main.451)，多任务学习的优势在于速度和显存，然而精度往往不如单任务模型。请使用最新发布的单任务模型：

https://colab.research.google.com/drive/1nE_Y7-sPPo8wnSp8Hao4jlz2LKTNYksl?usp=sharing
