### ISSUE TITLE
import hanlp bug on hanlp-2.1.0a55

### ISSUE THREAD

**Issue by wenchengxucool** [hankcs/HanLP#1672]
import hanlp的时候，出现AttributeError 
---------------------------------------------------------------------------
AttributeError       Traceback (most recent call last)
/var/folders/31/7mbjndl966d92drq1zvt9t3c0000gn/T/ipykernel_30433/3724283222.py in <module>
----> 1 import hanlp #Successfully installed hanlp-2.1.0a55

~/anaconda3/lib/python3.7/site-packages/hanlp/__init__.py in <module>
      8 from hanlp.version import __version__
      9 
---> 10 hanlp.utils.ls_resource_in_module(hanlp.pretrained)
     11 
     12 
AttributeError: module 'hanlp' has no attribute 'utils' 

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS montery 
- Python version: Python 3.7.3
- HanLP version:hanlp-2.1.0a55

**Other info / logs** 

* [x] I've completed this form and searched the web for solutions.

**Comment by wenchengxucool** [comment]
补充：pip3 install hanlp -U/pip install hanlp -U/pip install hanlp三种安装方式都是这样

**Comment by hankcs** [comment]
无法复现，请参考：
1. https://colab.research.google.com/drive/1KPX6t1y36TOzRIeB4Kt3uJ1twuj6WuFv?usp=sharing
2. https://github.com/hankcs/HanLP/runs/3346866465?check_suite_focus=true

可能是你意外删了某些文件，试试卸载后重新安装。
