### ISSUE TITLE
DoubleArrayTrie里的LongestSearcher的next方法，当传入的treemap的value为null时，会引发bug

### ISSUE THREAD

**Issue by tiandiweizun** [hankcs/HanLP#1673]
**Describe the bug**

DoubleArrayTrie里的LongestSearcher的next方法，当传入的treemap的value为null时，会引发bug
![image](https://user-images.githubusercontent.com/13550295/130592417-32ae4155-0ea3-4c7a-ad17-9fd2c67e92a5.png)

**Code to reproduce the issue**

```java
 public void testLongestSearcherWithNullValue() {
        TreeMap<String, String> buildFrom = new TreeMap<String, String>();
        TreeMap<String, String> buildFromValueNull = new TreeMap<String, String>();
        String[] keys = new String[]{"he", "her", "his"};
        for (String key : keys) {
            buildFrom.put(key, key);
            buildFromValueNull.put(key, null);
        }
        DoubleArrayTrie<String> trie = new DoubleArrayTrie<String>(buildFrom);
        DoubleArrayTrie<String> trieValueNull = new DoubleArrayTrie<String>(buildFromValueNull);

        String text = "her3he6his-hers! ";

        DoubleArrayTrie<String>.LongestSearcher searcher = trie.getLongestSearcher(text.toCharArray(), 0);
        DoubleArrayTrie<String>.LongestSearcher searcherValueNull = trieValueNull.getLongestSearcher(text.toCharArray(), 0);

        while (true) {
            boolean next = searcher.next();
            boolean nextValueNull = searcherValueNull.next();

            if (next && nextValueNull) {
                assertTrue(searcher.begin == searcherValueNull.begin && searcher.length == searcherValueNull.length);
            } else if (next || nextValueNull) {
                assert false;
                break;
            } else {
                break;
            }
        }
    }
```

**Describe the current behavior**
由于map传入的value为null，即使存在，也查不到

**Expected behavior**
根据length或者index进行判断
修复参见pull request (https://github.com/hankcs/HanLP/pull/1674)

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): win10
- Python version: xxx
- HanLP version: 1.8.2

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
感谢反馈，已经合并
