### ISSUE TITLE
文本分类 字典识别 出错

### ISSUE THREAD

**Issue by c58pj5j78AO1FWF7hQ1V53GEMY0Jj** [hankcs/HanLP#1677]
![E7NZ~MWO~(O$UD)0C MG 8X](https://user-images.githubusercontent.com/41079986/132792154-3ac71b93-413d-4945-9d21-3333d564451a.png)

文本分类里面模型加载出错。

根目录:C:\Users\KING\PycharmProjects\hankcs-pyhanlp\pyhanlp\static\data\test\搜狗文本分类语料库迷你版
加载中...
[体育]...24.20%Traceback (most recent call last):
  File "C:/Users/KING/PycharmProjects/hankcs-pyhanlp/tests/book/ch11/旅游.py", line 48, in <module>
    classifier = train_or_load_classifier()
  File "C:/Users/KING/PycharmProjects/hankcs-pyhanlp/tests/book/ch11/旅游.py", line 34, in train_or_load_classifier
    classifier.train(sogou_corpus_path)
jpype._jclass.ArrayIndexOutOfBoundsException: java.lang.ArrayIndexOutOfBoundsException: 0

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

开源项目维护不易，HanLP用户以十万计，而主要维护者只有我一人。我有自己的full-time研究工作，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
