### ISSUE TITLE
有的模型在windows无法使用，因为windows不允许创建名为con的目录

### ISSUE THREAD

**Issue by BlinkDL** [hankcs/HanLP#1679]
**Describe the bug**
有的模型在windows无法使用，因为windows不允许创建名为con的目录。

这是windows无法使用的目录名列表：
CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9.

由于 NPCMJ_UD_KYOTO_TOK_POS_CON_BERT_BASE_CHAR_JA 模型会试图创建一个 con 目录，因此会出现python错误：
NotADirectoryError: [WinError 267] 目录名称无效。:

**Code to reproduce the issue**
在windows执行下列命令，在下载完毕后，就会看到上述错误。
```python
HanLP = hanlp.load(hanlp.pretrained.mtl.NPCMJ_UD_KYOTO_TOK_POS_CON_BERT_BASE_CHAR_JA)
```

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
Windows毛病真多。
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。
