### ISSUE TITLE
人名识别不准确

### ISSUE THREAD

**Issue by xiyangzp** [hankcs/HanLP#168]
林军和大壮从侧门，被两个警察带进了市场旁边的一个大院内，随即直接进了办公楼里。

　　“这派出所挺大啊？”林军看着狭长的走廊，表情有些惊愕的说了一句。

　　“大哥，这是市局七处！”男警察斜眼回了一句。

　　市公安局第七刑侦大队，俗称七处，部门职责是主抓特大重点案件。

　　“咋给我们带这儿来了？”林军听后一愣。

　　“来，左边一个，右边一个，靠着暖气站好！”女警冲着林军和大壮，俏脸面无表情的说道。

　　二人听到这话，也没争辩，随后各自靠着暖气站了下来。而女警走进办公室取了两幅手铐，随即将二人分别铐在暖气管子上说道：“等着吧，一会派出所过来取你们俩。”

　　林军右手被铐上时,正好与女警脸对脸，随即他双眼本能的打量了女警一下。

　　她的长相有些特别，长发披肩，五官精致，但鼻梁很高，眼窝较深，一双灵动的大眼睛非常夺目。看着有点不像汉人五官，而是有点像史密斯夫妇中的安吉丽娜.茱莉！

　　女警身段挺直，个子起码一米七左右，上半身套着一件紧身的半袖警服衬衫，领口扣子系的一丝不苟。她下半身穿着黑蓝色宽松的长裤，脚上蹬着一双平底的黑色瓢鞋，整个人的气质给人一种充满活力，英姿飒爽的感觉。

　　“哎，郑警官，我俩这就是喝多了瞎闹腾，犯不上在你这儿占地方。你给我俩松开，我俩一块去派出所和解了得了。”大壮此刻已经有点被揍的醒酒了，他左手捂着还在淌血的嘴唇，随即含糊不清的喊道。

　　“闭上你的嘴，呆着！”女警厌恶的扫了他一眼，随后冲收发室喊道：“李叔，帮忙看一下，一会把他们交给派出所就行。”

　　“好叻！”　收发室的大爷回了一句。

　　随后女警踩着平底鞋就上了楼，而跟他一起的那个男警察转身再次去了市场，继续去给加班的同事买盒饭。

　　走廊内，工作人员来回穿梭，而林军和大壮相互对视了一眼。

　　“操你玛，你等出去的！我让你知道，你打我的那一酒瓶子有多无知！”大壮看着林军小声骂道。

　　林军将头扭过去，根本没回话。

　　......

　　四十分钟以后，派出所一个民警，带着一个二十六七的青年，并肩走进了走廊。民警进来以后，就直接走进了办公室，而青年腋下夹着包，脖子上挂着佛牌，手里搓着珠子冲大壮骂道：“一天净他妈给我惹事儿！”

　　“涛，你看他给我干的，嘴唇子都整豁豁了。”大壮指着自己的嘴唇子说道。

　　“你闭嘴吧！”青年回了一句，随后朝着民警走进的办公室走去。

　　二十分钟以后，民警和青年走了出来。

　　“王涛，谁是你朋友啊？”民警虎着脸，背手问道。

　　“就他！”叫王涛的青年指了指大壮。

　　民警扫了一眼林军和大壮，随即皱眉问道：“就这点破事儿，还用我调解啊？用验伤吗？”

　　“我不用！”大壮思考了一下，干脆的回道。

　　“我也不用！”林军扫了一眼三人，也面无表情的回道。

　　“真不用啊？”民警冲着林军再次问道。

　　“不用。”林军毫不犹豫的摇了摇头。

　　“打开，走吧！”民警随手拿着钥匙交给了王涛。

　　王涛接过钥匙，将大壮的铐子打开，然后又将钥匙扔给了林军。

　　“谭哥，麻烦了，明儿请你吃饭啊。”王涛笑着冲民警说道。

　　“轻点嘚瑟比啥都强，走吧，走吧。”民警淡然的摆了摆手。

　　“那我走了，谭哥！”

　　王涛冲民警打了个招呼，随后带着大壮扬长而去。林军摘下手铐以后，竖起大拇指冲民警说道：“这案子办的真利索！”

　　“你还有事儿啊？”民警回头，面无表情的问道。

　　“呵呵，没事儿。”林军放下手铐，随即头也不回的走出了七处。

　　.......

　　一个半小时以后，时间接近晚上七点多。

　　林军刚刚收拾完自己的小摊，并将烧烤用具放在了张小乐的三轮子上。

　　“今天不出了？”

　　张小乐站在一旁，张嘴问道。

　　“还出啥出，货都让他踩了。”林军有点心烦的回道。

　　“行，那我跟你把东西送回去。”张小乐穿着工作服，挺仗义的回了一句。

　　“不用了，你卖货吧，车借我用用就行。”林军骑上三轮子，咧嘴一笑说道。

　　“要不今天你别送了，东西直接扔我这儿得了。”张小乐明显有点担心的说道。

　　“呵呵。”林军一笑，也没多说，骑车就走了。

　　．．．．．．．

　　市场后方的小路上，林军健硕有力的双腿蹬着人力三轮车，顺着灯光昏暗的街道一路前行。

　　“咚咚咚！”

　　距离存放烧烤用具的车棚，还有一半路程时，小路对面突然泛起一阵农用三轮子的声响。

　　“吱嘎！”

　　林军踩了一脚刹车，右脚点地，眯着眼睛向前方望去。

　　“就那个傻Ｂ，一会给我往死怼他！”骑在三轮子上的大壮，满嘴漏风的大吼了一句。

　　大壮喊完，对方三轮车距离林军不超过二十米远后停滞，几乎同时，一副极为震撼的画面出现在林军眼中！

　　农用三轮子是摩托式的，马力很小，具体大小也就跟路边拉黑活的那种“摩的”差不多，而这车的车斗载重量，估计也就能拉几袋百斤重的大米。

　　但今天这个农用三轮子却突破了极限，就不足一米半长的车斗，竟然宛若春运火车车厢一般，拥挤得往下跳人！

　　一个，两个，三个.......

　　数秒过后，车斗之上竟然跳下来七个成年人！七个啊！天知道他们是怎么挤上去的，此场景即使跟印度三哥PK一下，那他妈也不差啥了！

　　“我操！”林军数着对方跳下来的人，脸色被雷的有点惊愕。

　　“呼啦啦！”

　　大壮跳下摩托车，右手从车斗中抽出一把片刀，随即带着七个人，手里拿着铁棍子，镐把子，镰刀，还有街头斗殴中百年难得一见的炉钩子等异样凶器，蜂拥着冲向林军。

　　“咣当当！”

　　林军下车，在自知无法躲避这场斗殴之时，立马回手从三轮车上抽出一根半米长的空心钢管，随后眉头都没皱一下，迈步就冲向人群。

　　双方碰见，基本没有废话，直接就开怼。

　　对方一个老农，抡着镰刀直接刨向林军，而林军侧身一闪，右臂摆动幅度很小，但右手攥着的钢管却闪电般的抽在了老农的手腕上。

　　当的一声，老农本能一缩手，林军手持钢管对着他脑袋，眨眼间就抽了三下，直接将其放倒。

　　其余众人冲上，林军左手抓过一人的脖领子，宛若拎着鸡崽子一般，直接将其摆在身前，随即他身体晃了一下，右手攥着钢管，对着旁边的大壮，反手就抽了过去！

　　“嘭！”

　　钢管抽在大壮嘴上，他疼的一蹦半米高。

　　“噼里啪啦！”

　　对方砸下来的武器，根本无处躲避的干在林军和对方那人的身上。

　　“往他手上砍！就照一万块钱干他了！”大壮捂着嘴，跳脚吼道。

　　林军额头，胳膊开始冒血，他左胳膊一甩，右腿一扫，直接将抓着的汉子绊倒。

　　“操你玛，我拿枪说话，拿刀吃饭的时候，你们还蹲地沟垄里唱东方红呢！”林军根本没管其他人，双手攥着钢管，胳膊卯足劲的往抡了数下。

　　“嘭！”

　　“嘭！”

　　“嘭！”

　　三声脆响，在林军身下这人的脑袋上，脖子上，后背上接连响起！

　　“呼啦啦！”

　　林军心黑手狠的干完这三下，人群顿时散开，众人看着他稍微有那么点犯怵！

　　“唰唰！”

　　与此同时，街口处有四台出租车匆忙赶来，这些车支着远光灯，停在路边。

　　“咣当！”

　　车门推开，张小乐扯脖子喊道：“军，谁他妈要干你啊？”

　　大壮团伙一看街口停了四台出租车，同时双眼又被大灯晃的看不清楚张小斌带来多少人，所以，他们第一时间掉头就跑，连能拉七个人的神奇农用三轮子都扔下了。

　　“咣当！”

　　林军脸不红气不喘的将钢管扔进自己的三轮车，随后伸手熟练的摸了一下后背。手指碰触皮肤，他感觉出后背没有刀伤，但回头再看右臂的时候，一个不足半指长的刀口，流着血，而皮肉已经翻开了。

　　“没事儿吧？”张小乐呼哧带喘的跑过来问道。

　　“没事儿，胳膊上划了一下。”林军拿起车上的餐巾纸，一下抽出了半盒的厚度堵在了伤口上，随即扭头冲着张小乐问道：“你都带谁过来的？”

　　“带个屁，四台出租车全是空的，现在的人，能借给你钱，就算好哥们了，哪有还能帮忙干仗的？”张小乐随口回了一句。

　　“谢了，乐乐！”林军愣了一下，随即认真的说道。

　　“谢的事儿回头再说，走吧，上医院看看！”张小乐拉着林军，继续说道：“他们这帮人，全是周边农村的，相互都认识，一会说不定叫来多少人！”

　　“他们跟谁玩的？”林军思考一下，直接问道。

　　“你要干啥啊？”张小乐一愣。

　　“这点破事儿不整明白了，我看是没完没了了。”林军低头回道。

　　“军，犯得上吗？”张小乐一听这话，顿时沉默几秒后皱眉问道。

　　“干都干了，你说咋整？今天要是没个结果，那明天我还能不能干活了？”林军简洁明了的回了一句，随即再次问道：“他们是跟谁玩的？”

　　“王涛。”张小乐思考了一下，随后还是如实相告。

　　“二十多岁，脖子上挂着佛牌儿，没事儿手里还愿意搓着珠子，是他吗？”林军脑中瞬间想起在七处走廊碰见的那个青年。

　　“对！”

　　“他不行，段位太低，他上面还有人吗？”林军摇头再问。

　　“大哥，你太狂点了吧？”张小乐愣了一下，随即惊愕的问道。

　　“这事儿跟你说不明白，一个段位，一个谈法！”林军干脆的回道。

　　“……王涛是跟满北伐玩的！”

　　“他在哪儿？”

　　“满北伐是整建筑的，手里有车队，人好像在江北望江别苑的三期工地里呢！”张小乐回了一句。

　　“谢了，你帮我把东西送回去，回来请你吃饭！”林军听完以后拍了拍张小乐的肩膀，随即转身就走。

　　两分钟以后，林军单人单骑，打了一辆出租车，直奔江北望江别苑。

这样一段文本，识别人名结果是：[林军, 史密斯, 安吉丽娜, 茱莉, 郑警官, 李叔, 操你玛, 都整豁, 王涛, 瑟比, 张小乐, 米高, 钱干他, 黑手, 张小斌, 连能拉, 都带谁]
请问识别出的这些不准确的，应该怎样才能尽量排除？

**Comment by hankcs** [comment]
这些大量使用方言和网络用语的网络小说建议使用CRFSegment。

[嘴唇子, 都, 整, 豁豁, 了]

**Comment by xiyangzp** [comment]
CRFSegment为什么比较适合呢？试过了，比较准确，但是不是很全。

**Comment by hankcs** [comment]
这涉及到底层模型原理了，请查一下论文。
