### ISSUE TITLE
我可以修改这一行的测评词性种类吗

### ISSUE THREAD

**Issue by Ya1002** [hankcs/HanLP#1685]
https://github.com/hankcs/HanLP/blob/7b03824e3986e799d128315a079cf7b355c95502/src/main/java/com/hankcs/hanlp/model/perceptron/utility/Utility.java#L382

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form when open a new issue.
