### ISSUE TITLE
TypeError: Ambiguous overloads found for com.hankcs.hanlp.seg.Segment.seg(str) between

### ISSUE THREAD

**Issue by Farm-M** [hankcs/HanLP#1686]
TypeError: Ambiguous overloads found for com.hankcs.hanlp.seg.Segment.seg(str) between:
	public java.util.List com.hankcs.hanlp.seg.Segment.seg(char[])
	public java.util.List com.hankcs.hanlp.seg.Segment.seg(java.lang.String)

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form when open a new issue.
