### ISSUE TITLE
三元组提取的问题

### ISSUE THREAD

**Issue by hujiaweibujidao** [hankcs/HanLP#169]
@hankcs 感谢你开发的HanLP工具，实在太棒了！

我刚学NLP，有个问题想向你请教。
我有这么个需求，输入是一个句子，输出是能表达句子语义的三元组（主谓宾）。例如：

原句：格言是简练而含义深刻并具有教育意义的警句。
结果：（格言，定义，简练而含义深刻并具有教育意义的警句）

原句：儿化具有区别词义、区分词性和表示感情色彩的作用。
结果：（儿化，作用，区别词义、区分词性和表示感情色彩）

原句：点号又分句末点号和句内点号。
结果：（点号，包含，句末点号和句内点号）

我看过你写的提取句子主谓宾的项目，所以我打算用类似的方法来做，但是自己刚入门NLP，不知道行不行。你有什么方法或者建议么？

谢谢！

**Comment by hankcs** [comment]
大致就是句法分析+规则吧
ROOT一般是谓语，左右两边找主语和宾语，当然还涉及到很多规则修正

**Comment by hujiaweibujidao** [comment]
@hankcs 谢谢你。我还想问下，类似word embeding或者神经网络等技术对这个需求会有作用么？或者说作用大么？

**Comment by hankcs** [comment]
据据Chen and Manning试验，对句法分析的效果提升很大。

**Comment by ljdawn** [comment]
hankcs你好。请问下三元组融合有啥好的办法么？只能靠自己写规则？  谢谢。

**Comment by hankcs** [comment]
这实际上属于知识提取，据我所知，能发挥实际作用的方案都是基于规则的。

**Comment by ljdawn** [comment]
@hankcs  谢谢。。。 写规则实在是太😖。。天天看数据

**Comment by crapthings** [comment]
@hujiaweibujidao @ljdawn 你们这个问题研究的怎么样了哦

**Comment by hujiaweibujidao** [comment]
@crapthings 已经毕业了，不搞了。当时还是采用了人工标注的方式处理的，标注系统是基于开源的Pundit系统二次开发的，可以了解下。

**Comment by crapthings** [comment]
@hujiaweibujidao 
Pundit 这是啥
