### ISSUE TITLE
func 'input_is_single_sample()' has a bug 

### ISSUE THREAD

**Issue by RayyaRTHU** [hankcs/HanLP#1692]
**Describe the bug**
In 'components/taggers/transformers/transform_tf.py' file, the function in line 117 maybe wrong.

def input_is_single_sample(self, input: Union[List[str], List[List[str]]]) -> bool:
        return isinstance(input[0], str)

**Code to reproduce the issue**

import hanlp
import unittest
ner1 = hanlp.load(hanlp.pretrained.ner.MSRA_NER_BERT_BASE_ZH)

class TestNER(unittest.TestCase):
    def test_ner_multi_sent(self):
        texts = [
            '北京市海淀区海淀大街天使大厦5层小邮局， 收件人王小二',
            '北京市海淀区清华大学明德楼， 收件人王小二']
        doc = ner1(texts)
        print(doc1)

if __name__ == '__main__':
    unittest.main()

**Describe the current behavior**
with the current behavior, the func 'input_is_single_sample()' will return True for the input, which is not expected.  
As a result, the NER result is wrong.
[('北京市海淀区海淀大街天使大厦5层小邮局， 收件人王小二', 'NS', 0, 1), ('北京市海淀区清华大学明德楼， 收件人王小二', 'NS', 1, 2)]

**Expected behavior**
The func 'input_is_single_sample()' should  return False. And NER result should be like this:
[[('北京市', 'NS', 0, 3), ('海淀区', 'NS', 3, 6), ('海淀大街', 'NS', 6, 10), ('天使大厦', 'NS', 10, 14), ('王小二', 'NR', 24, 27)], [('北京市', 'NS', 0, 3), ('海淀区', 'NS', 3, 6), ('清华大学', 'NT', 6, 10), ('明德楼', 'NS', 10, 13), ('王小二', 'NR', 18, 21)]]

**System information**
No Need.
The bug is in Master brach and doc-zh brach.

**Other info / logs**
No Need.

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
Hi, thank you for your question. However, it's not a bug. The input to this component is not str or a list of str, but it's expected to be a list of chars or a list of such lists. It's designed this way to match with token level NER.

See also the demo:

https://github.com/hankcs/HanLP/blob/bce4a4e2dabcc9e0a07bfa3f8eed3ae351657041/plugins/hanlp_demo/hanlp_demo/zh/tf/demo_ner.py#L7
