### ISSUE TITLE
crf模型在处理emoji时报错

### ISSUE THREAD

**Issue by Gooklim** [hankcs/HanLP#1696]
crf模型在处理emoji时报错(wordbasedsegmenter不会报错), 样例代码如下:

```
from jpype import java

from pyhanlp import *

text = '😱😱😱你好，欢迎在😱Pytho😱😱n中😱调用HanLP的API   😱😱😱😱😱😱😱😱😱😱'

String = java.lang.String
java_string = String(text.encode(), 'UTF8')
string_from_java = str(java_string).encode('utf-16', errors='surrogatepass').decode('utf-16')
print('原文：' + string_from_java)
print('HanLP分词结果')
crflex = HanLP.newSegment("crf")
for term in crflex.seg(java_string):
    print(str(term.word).encode('utf-16', errors='surrogatepass').decode('utf-16'))
```

报错信息: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 0: invalid continuation byte

系统: MAC Big Sur, I7. 
python 3.6.8
HanLP Jar version: 1.8.2
pyhanlp version: 0.1.79

其他信息: 
crf模型在输入八字节的单emoji时, 会拆成两个4字节的字返回
![image](https://user-images.githubusercontent.com/16161025/141045326-a63338dd-f5c1-4b47-bea0-f0c0a04718f6.png)

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

开源项目维护不易，HanLP用户以十万计，而主要维护者只有我一人。我有自己的full-time研究工作，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
