### ISSUE TITLE
crf模型在处理emoji时报错

### ISSUE THREAD

**Issue by Gooklim** [hankcs/HanLP#1697]
**问题描述:**
crf模型在处理emoji时报错(wordbasedsegmenter不会报错), 样例代码如下:

**复现代码**

```
from jpype import java

from pyhanlp import *

text = '😱😱😱你好，欢迎在😱Pytho😱😱n中😱调用HanLP的API   😱😱😱😱😱😱😱😱😱😱'

String = java.lang.String
java_string = String(text.encode(), 'UTF8')
string_from_java = str(java_string).encode('utf-16', errors='surrogatepass').decode('utf-16')
print('原文：' + string_from_java)
print('HanLP分词结果')
crflex = HanLP.newSegment("crf")
for term in crflex.seg(java_string):
    print(str(term.word).encode('utf-16', errors='surrogatepass').decode('utf-16'))
```

**报错信息**
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 0: invalid continuation byte

**System information**
系统: MAC Big Sur, I7.
python 3.6.8
HanLP Jar version: 1.8.2
pyhanlp version: 0.1.79

**其他信息**
crf模型在输入八字节的单emoji时, 会拆成两个4字节的字返回
![image](https://user-images.githubusercontent.com/16161025/141046032-da8161a6-d3a0-4db0-ab28-f3f32c729024.png)

* [x] I've completed this form and searched the web for solutions.

**Comment by Gooklim** [comment]
[](https://github.com/hankcs/HanLP/issues/971)
和这个问题类似, 但不能解决上述crf模型的问题

**Comment by hankcs** [comment]
Hi, 因为CRF分词器是字符级模型。而Java的字符（char）一定是双字节的，最终导致一个4字节的表情符被拆成2个双字节字符。word based分词器没有这个问题，因为2个双字节是一起返回的。解决方案是将表情符加入到词典中：

```python
text = '😱😱😱你好，欢迎在😱Pytho😱😱n中😱调用HanLP的API   😱😱😱😱😱😱😱😱😱😱'
CustomDictionary.add('😱')
```

你可以将所有[emoji](https://unicode.org/emoji/charts/full-emoji-list.html)加入词典。

**Comment by Gooklim** [comment]
> Hi, 因为CRF分词器是字符级模型。而Java的字符（char）一定是双字节的，最终导致一个4字节的表情符被拆成2个双字节字符。word based分词器没有这个问题，因为2个双字节是一起返回的。解决方案是将表情符加入到词典中：
> 
> ```python
> text = '😱😱😱你好，欢迎在😱Pytho😱😱n中😱调用HanLP的API   😱😱😱😱😱😱😱😱😱😱'
> CustomDictionary.add('😱')
> ```
> 
> 你可以将所有[emoji](https://unicode.org/emoji/charts/full-emoji-list.html)加入词典。

感谢解答! 那有办法把返回的2个双字节再组成一个表情吗? 是要对pyhanlp做修改吗?

**Comment by hankcs** [comment]
你把emoji加入词典后，词典会帮你合并的。你自己在Python里也可以合并，如果你知道字符串算法的话。
