### ISSUE TITLE
关于分词器对空格的处理!

### ISSUE THREAD

**Issue by a198720** [hankcs/HanLP#17]
先举例:
代码:
StandardTokenizer.SEGMENT.enableNumberQuantifierRecognize(true);
List<Term> termList = StandardTokenizer.segment("4月30号 9点钟");
System.out.println(termList);
termList = StandardTokenizer.segment("4月30号9点钟");
System.out.println(termList);
termList = StandardTokenizer.segment("4月30日9点钟");
System.out.println(termList);
===========================结果====================================
[4月/mq, 30/m, 号null/nz, 9点/m, 钟/n]
[4月/mq, 30号9点/m, 钟/n]
[4月/mq, 30日/mq, 9点/m, 钟/n]

其实 我理想中的效果应该是:
[4月/mq, 30号/mq, 9点钟/mq]
[4月/mq, 30号/mq, 9点钟/mq]
[4月/mq, 30日/mq, 9点钟/mq]

请教博主,这个问题  该如何去解决呢?

**Comment by hankcs** [comment]
首先，你应该在用mini词典，mini词典没有```点钟 qt 185```这个词条。
然后，你的自定义词典可能有问题，空格在我这边是分成[4/m, 月/n, 30号/mq,  /w, 9点钟/mq]，而不是你给出的null，你可以下个断点看看这个null是哪里来的。
最后，30号9点的错误合并是因为，mini词典里面号有m词性，这是不合理的，删掉即可。
现在，分词结果是：
```
[4月/mq, 30号/mq,  /w, 9点钟/mq]
[4月/mq, 30号/mq, 9点钟/mq]
[4月/mq, 30日/mq, 9点钟/mq]
```
关于这个空格是否应当作为一个标点w存在，我觉得无所谓，反正在搜索的时候肯定会被过滤掉。可以再讨论。

**Comment by a198720** [comment]
找到问题原因了,是配置文件中的规范化参数这地方.我设置的为true.这块在对空格处理后,将/w 词性转换成了 /nx  外文符号的词性. 建议这块儿可以不对空格做处理.
============================================================
 #规范化处理 （繁体->简体，全角->半角，大写->小写），切换配置后必须删缓存
Normalization=true

**Comment by hankcs** [comment]
谢谢建议，' '被规范化为'\u0000'，这是不合理的。'\u0000'的Unicode码是0，会导致双数组trie树出问题。通过调整data/dictionary/other/CharTable.bin.yes即可修复这个问题。
