### ISSUE TITLE
汉字转拼音问题

### ISSUE THREAD

**Issue by qq528** [hankcs/HanLP#170]
原文：吉林省长春药房,
拼音（数字音调）,ji2,lin2,sheng3,zhang3,chun1,yao4,fang2,
拼音（符号音调）,jí,lín,shěng,zhǎng,chūn,yào,fáng,
拼音（无音调）,ji,lin,sheng,zhang,chun,yao,fang,
声调,2,2,3,3,1,4,2,
声母,j,l,sh,zh,ch,y,f,
韵母,i,in,eng,ang,un,ao,ang,
输入法头,j,l,sh,zh,ch,y,f,

很明显zhang3这个拼音是错的，是否可以考虑加上分词来获取拼音呢？

**Comment by hankcs** [comment]
0. 你可以先分词，然后调拼音接口
0. 你也可以在拼音词典中加一句吉林省=...
0. 作为底层库的开发者，我不去限制用户的想象力
