### ISSUE TITLE
广告词分词效果不好，配置词组也不起作用---极简生活炭金炫洁牙刷双重植毛工艺双倍清洁

### ISSUE THREAD

**Issue by zhj12388** [hankcs/HanLP#1701]
**Describe the bug**
elasticsearch-hanlp插件 hanlp编译版本1.7.8

_analyze POST
{
"analyzer": "hanlp",
"text": "极简生活炭金炫洁牙刷双重植毛工艺双倍清洁"
}

配置过 ”极简生活” 和 “炭金炫洁”，牙刷被拆开了，没有牙刷这个词

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
```

**Describe the current behavior**

炭金炫洁 配置过词没有分出来，牙刷也被拆开了，没有牙刷这个词。具体内容如下：

分词效果如下：
{
"tokens": [
{
"token": "极简生活",
"start_offset": 0,
"end_offset": 4,
"type": "pp",
"position": 0
}
,
{
"token": "炭",
"start_offset": 4,
"end_offset": 5,
"type": "n",
"position": 1
}
,
{
"token": "金炫",
"start_offset": 5,
"end_offset": 7,
"type": "nr",
"position": 2
}
,
{
"token": "洁牙",
"start_offset": 7,
"end_offset": 9,
"type": "nz",
"position": 3
}
,
{
"token": "刷",
"start_offset": 9,
"end_offset": 10,
"type": "v",
"position": 4
}
,
{
"token": "双重",
"start_offset": 10,
"end_offset": 12,
"type": "b",
"position": 5
}
,
{
"token": "植",
"start_offset": 12,
"end_offset": 13,
"type": "v",
"position": 6
}
,
{
"token": "毛",
"start_offset": 13,
"end_offset": 14,
"type": "n",
"position": 7
}
,
{
"token": "工艺",
"start_offset": 14,
"end_offset": 16,
"type": "n",
"position": 8
}
,
{
"token": "双倍",
"start_offset": 16,
"end_offset": 18,
"type": "n",
"position": 9
}
,
{
"token": "清洁",
"start_offset": 18,
"end_offset": 20,
"type": "a",
"position": 10
}
]
}

**Expected behavior**
极简生活，炭金炫洁，牙刷，双重，植毛，工艺，双倍，清洁

**System information**
- OS Platform and Distribution (e.g., Linux CentOS7.9和Win7都是这个效果):
- Python version: 没有依赖
- HanLP version: 1.7.8
自己编译过

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [ ] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

开源项目维护不易，HanLP用户以十万计，而主要维护者只有我一人。我有自己的full-time研究工作，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
