### ISSUE TITLE
[linux] fail to pip install hanlp 

### ISSUE THREAD

**Issue by PirateX0** [hankcs/HanLP#1706]
**Describe the bug**
I install hanlp on windows successfully but fail to install hanlp on linux.

**Code to reproduce the issue**
pip install hanlp

**Describe the current behavior**
installation take hours and finally failed. see logs below.

**Expected behavior**
install successfully.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux 8e9e71981ec3 5.3.0-51-generic #44~18.04.2-Ubuntu SMP Thu Apr 23 14:27:18 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Python version:
3.10
- HanLP version: 2.1

**Other info / logs**
INFO: pip is looking at multiple versions of tokenizers to determine which version is compatible with other requirements. This could take a while.
  Downloading regex-2021.11.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (763 kB)
     |████████████████████████████████| 763 kB 114.8 MB/s 
  Downloading regex-2021.10.23-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (763 kB)
     |████████████████████████████████| 763 kB 93.0 MB/s 
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking

ERROR: Exception:
Traceback (most recent call last):
  File "/opt/conda/envs/dict/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 173, in _main
    status = self.run(options, args)
  File "/opt/conda/envs/dict/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "/opt/conda/envs/dict/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 315, in run
    requirement_set = resolver.resolve(
  File "/opt/conda/envs/dict/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 94, in resolve
    result = self._result = resolver.resolve(
  File "/opt/conda/envs/dict/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 472, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/opt/conda/envs/dict/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 383, in resolve
    raise ResolutionTooDeep(max_rounds)
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 2000000

* [x] I've completed this form and searched the web for solutions.
https://stackoverflow.com/questions/66008760/pips-dependency-resolver-takes-way-too-long-to-solve-the-conflict
使用pip install hanlp --use-deprecated=legacy-resolver可以解决问题
此外，要先安装pytorch>=1.6，再执行上述命令。

虽然通过上述办法解决了问题，但希望能够提供方便的安装，以及说明需要什么依赖。

**Comment by hankcs** [comment]
感谢汇报问题。pip 20.3发布了一个new dependency resolver，搜了一下，基本大家都在抱怨安装太慢。具体谁最慢？是huggingface的tokenizer依赖的regex最慢。
![hankcs com 2022-01-12 at 10 24 37 AM](https://user-images.githubusercontent.com/5326890/149169563-6b4f4079-9815-4121-a0c7-86900831cefd.png)
我不知道它的具体原理，但我试了一下，它的原理大致是把依赖的package的所有版本都下载下来，然后检查它们的依赖条件。根据所有版本综合考虑，决定满足所有条件的最优版本。听上去挺美好，其实遍历下载成本太高，基本相当于一个pypi的爬虫。

虽然我不认为这是HanLP的责任，毕竟[软件依赖](https://github.com/hankcs/HanLP/blob/6df38e33fa3d84de90736dee1064566ca502ce6f/setup.py#L37)这里写得一清二楚了。我可以做的事情仅限于把依赖的版本写得更细一些，但这样也会丧失兼容性。

关于PyTorch，更加不是没说明依赖导致的问题。截止今日，PyTorch官方没有发布Python 3.10的包：https://github.com/hpcaitech/ColossalAI/issues/119#issuecomment-1007163133
从因果上来讲，正是因为PyTorch官方没有发布Python 3.10的包，才导致pip的new dependency resolver遍历所有软件依赖，从而导致耗费这么长时间。

所以问题的正确解决方案是降级到Python 3.9及以下，一分钟内就安装完毕。

**Comment by PirateX0** [comment]
谢谢详细的解答。
