### ISSUE TITLE
WordVectorModel增加自定义model的构造函数

### ISSUE THREAD

**Issue by ananas-hebo** [hankcs/HanLP#1709]
**Describe the feature and the current behavior/state.**
我从 https://github.com/Embedding/Chinese-Word-Vectors， 下载了一些词向量。
数据量比较大，构建成hanlp的格式后，文件比较大load比较慢。
想自行初始化TreeMap后放入WordVectorModel。

但目前把AbstractVectorModel(Map)，构造函数覆盖掉了。

**Will this change the current api? How?**
Yes.

```
TreeMap<String, Vector> model = new TreeMap<String, Vector>();
// ... 自定义的构建model数据
WordVectorModel wordVectorModel = new WordVectorModel(model);
```
增加WordVectorModel构造函数，不知为何把父类的构造函数屏蔽掉了，希望开放出来
```
WordVectorModel(Map<K, Vector> storage);
```

**Who will benefit with this feature?**

**Are you willing to contribute it (Yes/No):**
Yes

**System information**
- Mac os
- Python version: None
- HanLP version: 1.8.2

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

开源项目维护不易，HanLP用户以十万计，而主要维护者只有我一人。我有自己的full-time研究工作，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
