### ISSUE TITLE
ViterbiSegment 添加是否进行 Normalize 的配置方法

### ISSUE THREAD

**Issue by XhstormR** [hankcs/HanLP#1714]
**Describe the feature and the current behavior/state.**
目前只有一种方式开关 Normalization，且影响全局，不能以单个对象控制。 
`HanLP.Config.Normalization = true`
 
**Will this change the current api? How?**
希望 ViterbiSegment 添加配置方法，能够单独配置是否进行 Normalize。eg:  
`new ViterbiSegment().enableNormalize(bool)`

**Who will benefit with this feature?**

**Are you willing to contribute it (Yes/No):**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version:
- HanLP version:

**Any other info**

* [x] I've carefully completed this form.

**Comment by hankcs** [comment]
感谢建议，请参考上面的commit。
