### ISSUE TITLE
教程代码tok = hanlp.load(hanlp.pretrained.tok.COARSE_ELECTRA_SMALL_ZH)  无法成功加载，已经尝试pip install --upgrade hanlp，提示No module named 'tokenizers.tokenizers'

### ISSUE THREAD

**Issue by Renguangdong** [hankcs/HanLP#1725]
OS: Windows-10-10.0.22598-SP0
Python: 3.8.12
PyTorch: 1.11.0+cpu
HanLP: 2.1.0-beta.24
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Input In [11], in <cell line: 1>()
----> 1 tok = hanlp.load(hanlp.pretrained.tok.COARSE_ELECTRA_SMALL_ZH)
      2 tok

File F:\ananconda\lib\site-packages\hanlp\__init__.py:43, in load(save_dir, verbose, **kwargs)
     41     from hanlp_common.constant import HANLP_VERBOSE
     42     verbose = HANLP_VERBOSE
---> 43 return load_from_meta_file(save_dir, 'meta.json', verbose=verbose, **kwargs)

File F:\ananconda\lib\site-packages\hanlp\utils\component_util.py:170, in load_from_meta_file(save_dir, meta_filename, transform_only, verbose, **kwargs)
    168 except:
    169     pass
--> 170 raise e from None

File F:\ananconda\lib\site-packages\hanlp\utils\component_util.py:91, in load_from_meta_file(save_dir, meta_filename, transform_only, verbose, **kwargs)
     89 assert cls, f'{meta_filename} doesn\'t contain classpath field'
     90 try:
---> 91     obj: Component = object_from_classpath(cls)
     92     if hasattr(obj, 'load'):
     93         if transform_only:
     94             # noinspection PyUnresolvedReferences

File F:\ananconda\lib\site-packages\hanlp_common\reflection.py:27, in object_from_classpath(classpath, **kwargs)
     26 def object_from_classpath(classpath, **kwargs):
---> 27     classpath = str_to_type(classpath)
     28     if inspect.isfunction(classpath):
     29         return classpath

File F:\ananconda\lib\site-packages\hanlp_common\reflection.py:44, in str_to_type(classpath)
     34 """convert class path in str format to a type
     35 
     36 Args:
   (...)
     41 
     42 """
     43 module_name, class_name = classpath.rsplit(".", 1)
---> 44 cls = getattr(importlib.import_module(module_name), class_name)
     45 return cls

File F:\ananconda\lib\importlib\__init__.py:127, in import_module(name, package)
    125             break
    126         level += 1
--> 127 return _bootstrap._gcd_import(name[level:], package, level)

File <frozen importlib._bootstrap>:1014, in _gcd_import(name, package, level)

File <frozen importlib._bootstrap>:991, in _find_and_load(name, import_)

File <frozen importlib._bootstrap>:975, in _find_and_load_unlocked(name, import_)

File <frozen importlib._bootstrap>:671, in _load_unlocked(spec)

File <frozen importlib._bootstrap_external>:843, in exec_module(self, module)

File <frozen importlib._bootstrap>:219, in _call_with_frames_removed(f, *args, **kwds)

File F:\ananconda\lib\site-packages\hanlp\components\tokenizers\transformer.py:10, in <module>
      8 from hanlp.common.dataset import SamplerBuilder
      9 from hanlp.common.transform import TransformList
---> 10 from hanlp.components.taggers.transformers.transformer_tagger import TransformerTagger
     11 from hanlp.datasets.tokenization.loaders.txt import TextTokenizingDataset, generate_tags_for_subtokens
     12 from hanlp.metrics.f1 import F1

File F:\ananconda\lib\site-packages\hanlp\components\taggers\transformers\transformer_tagger.py:15, in <module>
     13 from hanlp.common.transform import FieldLength, TransformList
     14 from hanlp.common.vocab import Vocab
---> 15 from hanlp.components.classifiers.transformer_classifier import TransformerComponent
     16 from hanlp.components.taggers.tagger import Tagger
     17 from hanlp.datasets.ner.loaders.tsv import TSVTaggingDataset

File F:\ananconda\lib\site-packages\hanlp\components\classifiers\transformer_classifier.py:19, in <module>
     17 from hanlp.components.distillation.schedulers import LinearTeacherAnnealingScheduler
     18 from hanlp.layers.scalar_mix import ScalarMixWithDropoutBuilder
---> 19 from hanlp.layers.transformers.encoder import TransformerEncoder
     20 from hanlp.layers.transformers.pt_imports import PreTrainedModel, AutoTokenizer, BertTokenizer, AutoTokenizer_
     21 from hanlp.layers.transformers.utils import transformer_sliding_window, build_optimizer_scheduler_with_transformer

File F:\ananconda\lib\site-packages\hanlp\layers\transformers\encoder.py:12, in <module>
     10 from hanlp.layers.scalar_mix import ScalarMixWithDropout, ScalarMixWithDropoutBuilder
     11 from hanlp.layers.transformers.resource import get_tokenizer_mirror
---> 12 from hanlp.layers.transformers.pt_imports import PreTrainedModel, PreTrainedTokenizer, AutoTokenizer, AutoModel_, \
     13     BertTokenizer, AutoTokenizer_
     14 from hanlp.layers.transformers.utils import transformer_encode
     17 # noinspection PyAbstractClass

File F:\ananconda\lib\site-packages\hanlp\layers\transformers\pt_imports.py:13, in <module>
     11 if os.environ.get('TOKENIZERS_PARALLELISM', None) is None:
     12     os.environ["TOKENIZERS_PARALLELISM"] = "false"
---> 13 from transformers import BertTokenizer, BertConfig, PretrainedConfig, \
     14     AutoConfig, AutoTokenizer, PreTrainedTokenizer, BertTokenizerFast, AlbertConfig, BertModel, AutoModel, \
     15     PreTrainedModel, get_linear_schedule_with_warmup, AdamW, AutoModelForSequenceClassification, \
     16     AutoModelForTokenClassification, optimization, BartModel
     19 class AutoModel_(AutoModel):
     20     @classmethod
     21     def from_pretrained(cls, pretrained_model_name_or_path, *model_args, training=True, **kwargs):

File <frozen importlib._bootstrap>:1039, in _handle_fromlist(module, fromlist, import_, recursive)

File F:\ananconda\lib\site-packages\transformers\file_utils.py:2768, in _LazyModule.__getattr__(self, name)
   2766 elif name in self._class_to_module.keys():
   2767     module = self._get_module(self._class_to_module[name])
-> 2768     value = getattr(module, name)
   2769 else:
   2770     raise AttributeError(f"module {self.__name__} has no attribute {name}")

File F:\ananconda\lib\site-packages\transformers\file_utils.py:2767, in _LazyModule.__getattr__(self, name)
   2765     value = self._get_module(name)
   2766 elif name in self._class_to_module.keys():
-> 2767     module = self._get_module(self._class_to_module[name])
   2768     value = getattr(module, name)
   2769 else:

File F:\ananconda\lib\site-packages\transformers\file_utils.py:2779, in _LazyModule._get_module(self, module_name)
   2777     return importlib.import_module("." + module_name, self.__name__)
   2778 except Exception as e:
-> 2779     raise RuntimeError(
   2780         f"Failed to import {self.__name__}.{module_name} because of the following error (look up to see its traceback):\n{e}"
   2781     ) from e

RuntimeError: Failed to import transformers.models.bert.tokenization_bert because of the following error (look up to see its traceback):
No module named 'tokenizers.tokenizers'
=================================ERROR LOG ENDS=================================

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form when open a new issue.
