### ISSUE TITLE
启用用户词典，分词结果中的坐标是错误的

### ISSUE THREAD

**Issue by weblearngit** [hankcs/HanLP#1727]
**Describe the bug**
启用用户词典，分词结果中的坐标是错误的。

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
import hanlp
tok = hanlp.load(hanlp.pretrained.tok.FINE_ELECTRA_SMALL_ZH)

tok.config.output_spans = True

tok.dict_force = None
tok.dict_combine = None
sent = '我先去看医生'
print(tok(sent))

tok.dict_combine = set({'先去'})
print(tok(sent))

# 输出，先去 的坐标应该是 1,3：
[['我', 0, 1], ['先', 1, 2], ['去', 2, 3], ['看', 3, 4], ['医生', 4, 6]]
[['我', 0, 1], ['先去', 1, 2], ['看', 2, 3], ['医生', 3, 4]]
```

**Describe the current behavior**
A clear and concise description of what happened.

**Expected behavior**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  win10
- Python version: python3.9.7
- HanLP version: hanlp-2.1.0b26

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。
