### ISSUE TITLE
TupleTrieDict的len不一致

### ISSUE THREAD

**Issue by weblearngit** [hankcs/HanLP#1728]
**Describe the bug**
TupleTrieDict 初始化前合并数据，与初始化后更新数据，len(TupleTrieDict)的结果不一致

**Code to reproduce the issue**
分批添加数据key有643142（dict1方式），合并后key的量为632400（dict2方式）。
程序运行时，发现 dict1方式 节省了时间，请问 TupleTrieDict 的此种现象，是特性，还是bug？

```python
    from hanlp_trie.dictionary import TupleTrieDict

    dict1 = TupleTrieDict({"aa": 1})
    print(len(dict1), dict1["aa"])  # 输出 1 1

    dict1["aa"] += 2
    print(len(dict1), dict1["aa"])  # 输出 2 3

    dict2 = TupleTrieDict({"aa": 4})
    print(len(dict2), dict2["aa"])  # 输出 1 4
```

**Describe the current behavior**
A clear and concise description of what happened.

**Expected behavior**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version: 3.9.7
- HanLP version: 2.1.0b27

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。

另外，`TupleTrieDict`假定key为Tuple类型，非Tuple类型的key会被类型转换为Tuple，所以`aa`其实相当于`('a', 'a')`。
