### ISSUE TITLE
hanlp.load(hanlp.pretrained.ner.MSRA_NER_BERT_BASE_ZH)报错，无法加载模型

### ISSUE THREAD

**Issue by crcleavity** [hankcs/HanLP#1729]
**Describe the bug**
我运行了
`hanlp.load(hanlp.pretrained.ner.MSRA_NER_BERT_BASE_ZH)`然后出现报错，无法加载模型

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
`hanlp.load(hanlp.pretrained.ner.MSRA_NER_BERT_BASE_ZH)`
```python
```
```
import hanlp
hanlp.load(hanlp.pretrained.ner.MSRA_NER_BERT_BASE_ZH)
```
**Describe the current behavior**
A clear and concise description of what happened.
目前，加载模型后报错，我分别在自己本地和google的colab上都不行，尝试pip upgrade hanlp[full] -U也后同样会报错
**Expected behavior**
能够正常加载模型，完成ner任务
**System information**
- OS Platform and Distribution:Linux-5.4.188+-x86_64-with-Ubuntu-18.04-bionic
- Python version:3.7.13
- HanLP version:2.1.0-beta.27

**Other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
Failed to load https://file.hankcs.com/hanlp/ner/ner_bert_base_msra_20211227_114712.zip.
If the problem still persists, please submit an issue to https://github.com/hankcs/HanLP/issues
When reporting an issue, make sure to paste the FULL ERROR LOG below.
================================ERROR LOG BEGINS================================
OS: Linux-5.4.188+-x86_64-with-Ubuntu-18.04-bionic
Python: 3.7.13
PyTorch: 1.11.0+cu113
TensorFlow: 2.8.0
HanLP: 2.1.0-beta.27

OSError                                   Traceback (most recent call last)
[<ipython-input-26-b5faac023b11>](https://localhost:8080/#) in <module>()
----> 1 hanlp.load(hanlp.pretrained.ner.MSRA_NER_BERT_BASE_ZH)

11 frames
[/usr/local/lib/python3.7/dist-packages/hanlp/__init__.py](https://localhost:8080/#) in load(save_dir, verbose, **kwargs)
     41         from hanlp_common.constant import HANLP_VERBOSE
     42         verbose = HANLP_VERBOSE
---> 43     return load_from_meta_file(save_dir, 'meta.json', verbose=verbose, **kwargs)
     44 
     45 

[/usr/local/lib/python3.7/dist-packages/hanlp/utils/component_util.py](https://localhost:8080/#) in load_from_meta_file(save_dir, meta_filename, transform_only, verbose, **kwargs)
    169         except:
    170             pass
--> 171         raise e from None
    172 
    173 

[/usr/local/lib/python3.7/dist-packages/hanlp/utils/component_util.py](https://localhost:8080/#) in load_from_meta_file(save_dir, meta_filename, transform_only, verbose, **kwargs)
     97             else:
     98                 if os.path.isfile(os.path.join(save_dir, 'config.json')):
---> 99                     obj.load(save_dir, verbose=verbose, **kwargs)
    100                 else:
    101                     obj.load(metapath, **kwargs)

[/usr/local/lib/python3.7/dist-packages/hanlp/common/keras_component.py](https://localhost:8080/#) in load(self, save_dir, logger, **kwargs)
    212         self.load_config(save_dir)
    213         self.load_vocabs(save_dir)
--> 214         self.build(**merge_dict(self.config, training=False, logger=logger, **kwargs, overwrite=True, inplace=True))
    215         self.load_weights(save_dir, **kwargs)
    216         self.load_meta(save_dir)

[/usr/local/lib/python3.7/dist-packages/hanlp/common/keras_component.py](https://localhost:8080/#) in build(self, logger, **kwargs)
    223         self.transform.build_config()
    224         self.model = self.build_model(**merge_dict(self.config, training=kwargs.get('training', None),
--> 225                                                    loss=kwargs.get('loss', None)))
    226         self.transform.lock_vocabs()
    227         optimizer = self.build_optimizer(**self.config)

[/usr/local/lib/python3.7/dist-packages/hanlp/components/taggers/transformers/transformer_tagger_tf.py](https://localhost:8080/#) in build_model(self, transformer, max_seq_length, **kwargs)
     32 
     33     def build_model(self, transformer, max_seq_length, **kwargs) -> tf.keras.Model:
---> 34         model, tokenizer = build_transformer(transformer, max_seq_length, len(self.transform.tag_vocab), tagging=True)
     35         self.transform.tokenizer = tokenizer
     36         return model

[/usr/local/lib/python3.7/dist-packages/hanlp/layers/transformers/loader_tf.py](https://localhost:8080/#) in build_transformer(transformer, max_seq_length, num_labels, tagging, tokenizer_only)
      9 
     10 def build_transformer(transformer, max_seq_length, num_labels, tagging=True, tokenizer_only=False):
---> 11     tokenizer = AutoTokenizer_.from_pretrained(transformer)
     12     if tokenizer_only:
     13         return tokenizer

[/usr/local/lib/python3.7/dist-packages/hanlp/layers/transformers/pt_imports.py](https://localhost:8080/#) in from_pretrained(cls, pretrained_model_name_or_path, use_fast, do_basic_tokenize)
     68         tokenizer = cls.from_pretrained(get_tokenizer_mirror(transformer), use_fast=use_fast,
     69                                         do_basic_tokenize=do_basic_tokenize,
---> 70                                         **additional_config)
     71         tokenizer.name_or_path = transformer
     72         return tokenizer

[/usr/local/lib/python3.7/dist-packages/transformers/models/auto/tokenization_auto.py](https://localhost:8080/#) in from_pretrained(cls, pretrained_model_name_or_path, *inputs, **kwargs)
    483             if not isinstance(config, PretrainedConfig):
    484                 config = AutoConfig.from_pretrained(
--> 485                     pretrained_model_name_or_path, trust_remote_code=trust_remote_code, **kwargs
    486                 )
    487             config_tokenizer_class = config.tokenizer_class

[/usr/local/lib/python3.7/dist-packages/transformers/models/auto/configuration_auto.py](https://localhost:8080/#) in from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
    650         kwargs["name_or_path"] = pretrained_model_name_or_path
    651         trust_remote_code = kwargs.pop("trust_remote_code", False)
--> 652         config_dict, _ = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
    653         if "auto_map" in config_dict and "AutoConfig" in config_dict["auto_map"]:
    654             if not trust_remote_code:

[/usr/local/lib/python3.7/dist-packages/transformers/configuration_utils.py](https://localhost:8080/#) in get_config_dict(cls, pretrained_model_name_or_path, **kwargs)
    546         original_kwargs = copy.deepcopy(kwargs)
    547         # Get config dict associated with the base config file
--> 548         config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
    549 
    550         # That config file may point us toward another config file to use.

[/usr/local/lib/python3.7/dist-packages/transformers/configuration_utils.py](https://localhost:8080/#) in _get_config_dict(cls, pretrained_model_name_or_path, **kwargs)
    635         except EnvironmentError:
    636             raise EnvironmentError(
--> 637                 f"Can't load config for '{pretrained_model_name_or_path}'. If you were trying to load it from "
    638                 "'https://huggingface.co/models', make sure you don't have a local directory with the same name. "
    639                 f"Otherwise, make sure '{pretrained_model_name_or_path}' is the correct path to a directory "

OSError: Can't load config for 'bert-base-chinese'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'bert-base-chinese' is the correct path to a directory containing a config.json file
=================================ERROR LOG ENDS=================================
* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
无法复现：https://colab.research.google.com/drive/189FJ7boDchzrdv3H6zKBojimvKsIMJ8l?usp=sharing

中国有时候无法访问 https://huggingface.co/models ，请自行找镜像。
