### ISSUE TITLE
中英文混排下对英文的分词错误

### ISSUE THREAD

**Issue by mikulely** [hankcs/HanLP#1735]
**Describe the bug**

中英文混合的句子分词没有拆分标点，英文以及中文。(第一次接触 NLP，也有可能是我不会用,谢谢。)

**Code to reproduce the issue**

使用 HanLP README 中的文档在线测试， see https://hanlp.hankcs.com/?sentence=HanLP%E6%AF%8F%E6%AC%A1%E5%8F%91%E5%B8%83%E9%83%BD%E9%80%9A%E8%BF%87%E4%BA%86Linux%E3%80%81macOS%E5%92%8CWindows%E4%B8%8APython3.6%E8%87%B33.9%E7%9A%84%E5%8D%95%E5%85%83%E6%B5%8B%E8%AF%95%EF%BC%8C%E4%B8%8D%E5%AD%98%E5%9C%A8%E5%AE%89%E8%A3%85%E9%97%AE%E9%A2%98&mul=on 

**Describe the current behavior**

![image](https://user-images.githubusercontent.com/4464227/169633666-d9113707-3141-402c-8b11-15fba61dec42.png)

**Expected behavior**

1. 标点符号和名字应该分开
2. 中文和英文应该分开

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version:
- HanLP version:

**Other info / logs**

使用场景是尝试通过 HanLP 来发现中英文混排的技术文档的风格问题。

* [ ] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

开源项目维护不易，HanLP用户以十万计，而主要维护者只有我一人。我有自己的full-time研究工作，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
