### ISSUE TITLE
com.hankcs.hanlp.collection.AhoCorasick.AhoCorasickDoubleArrayTrie#getState 线程占用99CPU

### ISSUE THREAD

**Issue by zhujiawen12345** [hankcs/HanLP#1736]
**Describe the bug**
现网发现一台服务器CPU很高，查询堆栈发现一个线程一直RUNNABLE状态 CPU占用99.9，持续时间7天以上，
线程堆栈信息见图：
![image](https://user-images.githubusercontent.com/31981598/169731187-66653ab1-324c-44d5-a3df-d35bc00228ba.png)
看了下代码，是不是什么场景导致了getState里面死循环？
**Code to reproduce the issue**
暂不清楚如何触发

```Java 
```

**Describe the current behavior**
无

**Expected behavior**
无

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux 
- HanLP version: portable-1.8.2

**Other info / logs**

 I've completed this form and searched the web for solutions.
已搜索

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

开源项目维护不易，HanLP用户以十万计，而主要维护者只有我一人。我有自己的full-time研究工作，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
