### ISSUE TITLE
com.hankcs.hanlp.collection.AhoCorasick.AhoCorasickDoubleArrayTrie#getState 长时间占用线程 CPU99.9

### ISSUE THREAD

**Issue by zhujiawen12345** [hankcs/HanLP#1737]
**Describe the bug**
堆栈显示 com.hankcs.hanlp.collection.AhoCorasick.AhoCorasickDoubleArrayTrie#getState(AhoCorasickDoubleArrayTrie.java:402)长时间占用线程(时间超过一周)，线程状态一直RUNNABLE,CPU占用达99.9.

**Code to reproduce the issue**
暂不清楚怎么触发的

``JAVA``

**Describe the current behavior**
无

**Expected behavior**
无

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- Python version:
- HanLP version: portable-1.8.2

**Other info / logs**

* [x] I've completed this form and searched the web for solutions.
已搜索

**Comment by hankcs** [comment]
需要提供触发代码才能帮到你。你至少可以把AhoCorasickDoubleArrayTrie.save下来，在你本地跑你的文本试试能不能触发。能触发就能修复，如果不能，说明不是AhoCorasickDoubleArrayTrie的问题。这个数据结构理论已经成熟没有漏洞，工程上已经用了七八年了，没听说过类似的问题。
