### ISSUE TITLE
FINE_ELECTRA_SMALL_ZH 解析部分面积单位出错

### ISSUE THREAD

**Issue by SoaringTiger** [hankcs/HanLP#1742]
**Describe the bug**
tok模型: **FINE_ELECTRA_SMALL_ZH**   (close_tok_fine_electra_small_20220612_114112.zip)
例1 输入： 中国面积是960万平方千米
结果: "中国", "面积",  "是", **"960万",  _"平方",  "千",  "米"_** 
_错误_："平方千米" 被 分为 **_"平方",  "千", "米"_**

例2 输入： 中国面积是960万千米²
结果: "中国", "面积",  "是", **"960万", _"千",  "米",  "²"_** 
_错误_: "千米²" 被 分为 **_"千",  "米",  "²"_**

例3 输入:  中国面积是9600000km²
结果: "中国", "面积",  "是", **"_9600000km²"_** 
_错误_: "9600000km²" 应 分为 **_"9600000",  "km²"_**

**Current behavior**
改用模型 CTB9_TOK_ELECTRA_BASE_CRF 后，例1、例2 结果正确， 类似例子还有 "中国面积是9600000公里²", "教室面积是180米²"
例3结果则仍然相同。

**Expected behavior**
对类似度量单位实现正确分词

**System information**
- OS Platform and Distribution: Linux Ubuntu 16.04
- Python version: 3.9
- HanLP version: 2.1b31

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
这一版无论是语料还是模型，对平方公里，平方米的处理都是正确的。由于语料库中没有平方千米、千米²这种比较不书面语的用法，所以对此的支持不好。不过这也是自定义词典的用武之地了，建议参考例子自己加到词典里：https://github.com/hankcs/HanLP/blob/master/plugins/hanlp_demo/hanlp_demo/zh/demo_custom_dict_stl.py#L20
