### ISSUE TITLE
UD_ONTONOTES_TOK_POS_LEM_FEA_NER_SRL_DEP_SDP_CON_MMINILMV2L6模型处理文本时报错

### ISSUE THREAD

**Issue by MacGuffin230** [hankcs/HanLP#1753]
**Describe the bug**
UD_ONTONOTES_TOK_POS_LEM_FEA_NER_SRL_DEP_SDP_CON_MMINILMV2L6模型处理文本时报错

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
import hanlp

model4 = hanlp.load(hanlp.pretrained.mtl.UD_ONTONOTES_TOK_POS_LEM_FEA_NER_SRL_DEP_SDP_CON_MMINILMV2L6)
model4("~(=^‥^)_ ~(=^‥^)_ ~(=^‥^)_")
```

**Describe the current behavior**
A clear and concise description of what happened.
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-12-d6c0a38fb7b1> in <module>
----> 1 model4("~(=^‥^)_ ~(=^‥^)_ ~(=^‥^)_")

~/.local/lib/python3.6/site-packages/hanlp/components/mtl/multi_task_learning.py in __call__(self, data, **kwargs)
    769 
    770     def __call__(self, data, **kwargs) -> Document:
--> 771         return super().__call__(data, **kwargs)
    772 
    773     def __getitem__(self, task_name: str) -> Task:

/opt/app/conda/lib/python3.6/site-packages/torch/autograd/grad_mode.py in decorate_context(*args, **kwargs)
     26         def decorate_context(*args, **kwargs):
     27             with self.__class__():
---> 28                 return func(*args, **kwargs)
     29         return cast(F, decorate_context)
     30 

~/.local/lib/python3.6/site-packages/hanlp/common/torch_component.py in __call__(self, *args, **kwargs)
    636             **kwargs: Used in sub-classes.
    637         """
--> 638         return super().__call__(*args, **merge_dict(self.config, overwrite=True, **kwargs))

~/.local/lib/python3.6/site-packages/hanlp/common/component.py in __call__(self, *args, **kwargs)
     34 
     35         """
---> 36         return self.predict(*args, **kwargs)

~/.local/lib/python3.6/site-packages/hanlp/components/mtl/multi_task_learning.py in predict(self, data, tasks, skip_tasks, resolved_tasks, **kwargs)
    503             # Run the first task, let it make the initial batch for the successors
    504             output_dict = self.predict_task(first_task, first_task_name, batch, results, run_transform=True,
--> 505                                             cls_is_bos=cls_is_bos, sep_is_eos=sep_is_eos)
    506             # Run each task group in order
    507             for group_id, group in enumerate(target_tasks):

~/.local/lib/python3.6/site-packages/hanlp/components/mtl/multi_task_learning.py in predict_task(self, task, output_key, batch, results, output_dict, run_transform, cls_is_bos, sep_is_eos)
    593         output_dict, batch = self.feed_batch(batch, output_key, output_dict, run_transform, cls_is_bos, sep_is_eos,
    594                                              results)
--> 595         self.decode_output(output_dict, batch, output_key)
    596         results[output_key].extend(task.prediction_to_result(output_dict[output_key]['prediction'], batch))
    597         return output_dict

~/.local/lib/python3.6/site-packages/hanlp/components/mtl/multi_task_learning.py in decode_output(self, output_dict, batch, task_name)
    733                 output_per_task['mask'],
    734                 batch,
--> 735                 self.model.decoders[task_name])
    736 
    737     def update_metrics(self, batch: Dict[str, Any], output_dict: Dict[str, Any], metrics: MetricDict, task_name):

~/.local/lib/python3.6/site-packages/hanlp/components/mtl/tasks/tok/tag_tok.py in decode_output(self, output, mask, batch, decoder, **kwargs)
    122     def decode_output(self, output: Union[torch.Tensor, Dict[str, torch.Tensor], Iterable[torch.Tensor], Any],
    123                       mask: torch.BoolTensor, batch: Dict[str, Any], decoder, **kwargs) -> Union[Dict[str, Any], Any]:
--> 124         return TransformerTaggingTokenizer.decode_output(self, output, mask, batch, decoder)
    125 
    126     def update_metrics(self, batch: Dict[str, Any],

~/.local/lib/python3.6/site-packages/hanlp/components/tokenizers/transformer.py in decode_output(self, logits, mask, batch, model)
    111             output = output.tolist()
    112         prediction = self.id_to_tags(output, [len(x) for x in batch['token']])
--> 113         return self.tag_to_span(prediction, batch)
    114 
    115     def tag_to_span(self, batch_tags, batch: dict):

~/.local/lib/python3.6/site-packages/hanlp/components/tokenizers/transformer.py in tag_to_span(self, batch_tags, batch)
    129                     for start, end, label in custom_words:
    130                         if end - start == 1:
--> 131                             tags[start] = S
    132                         else:
    133                             tags[start] = 'B'

IndexError: list assignment index out of range
​

**Expected behavior**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version:
- HanLP version:

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [ ] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

开源项目维护不易，HanLP用户以十万计，而主要维护者只有我一人。我有自己的full-time研究工作，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
