### ISSUE TITLE
Hanlp native无法下载模型

### ISSUE THREAD

**Issue by 1312354o** [hankcs/HanLP#1757]
**Describe the bug**

无法下载hanlp native模型 failed to download a hanlp native model

Download failed due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='file.hankcs.workers.dev', port=443): Max retries exceeded with url: /hanlp/transformers/electra_zh_base_20210706_125233.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000024B8D5CA4C0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))")).

Failed to load https://file.hankcs.com/hanlp/mtl/close_tok_pos_ner_srl_dep_sdp_con_electra_base_20210111_124519.zip.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
HanLP = hanlp.load(hanlp.pretrained.mtl.CLOSE_TOK_POS_NER_SRL_DEP_SDP_CON_ELECTRA_BASE_ZH)
```

**Describe the current behavior**
模型下载失败

**Expected behavior**
模型成功下载

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Python version:  Python 3.8.8 
- HanLP version: 2.1.0b35

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
ConnectionError                           Traceback (most recent call last)
<ipython-input-33-7a52ebc07181> in <module>
----> 1 HanLP = hanlp.load(hanlp.pretrained.mtl.CLOSE_TOK_POS_NER_SRL_DEP_SDP_CON_ELECTRA_BASE_ZH)

E:\anacoda\lib\site-packages\hanlp\__init__.py in load(save_dir, verbose, **kwargs)
     41         from hanlp_common.constant import HANLP_VERBOSE
     42         verbose = HANLP_VERBOSE
---> 43     return load_from_meta_file(save_dir, 'meta.json', verbose=verbose, **kwargs)
     44 
     45 

E:\anacoda\lib\site-packages\hanlp\utils\component_util.py in load_from_meta_file(save_dir, meta_filename, transform_only, verbose, **kwargs)
     30     identifier = save_dir
     31     load_path = save_dir
---> 32     save_dir = get_resource(save_dir)
     33     if save_dir.endswith('.json'):
     34         meta_filename = os.path.basename(save_dir)

E:\anacoda\lib\site-packages\hanlp\utils\io_util.py in get_resource(path, save_dir, extract, prefix, append_location, verbose)
    338             realpath += compressed
    339         if not os.path.isfile(realpath):
--> 340             path = download(url=path, save_path=realpath, verbose=verbose)
    341         else:
    342             path = realpath

E:\anacoda\lib\site-packages\hanlp\utils\io_util.py in download(url, save_path, save_dir, prefix, append_location, verbose)
    183             elif hasattr(e, 'args') and e.args and isinstance(e.args, tuple) and isinstance(e.args[0], str):
    184                 e.args = (e.args[0] + '\n' + remove_color_tag(message),) + e.args[1:]
--> 185             raise e from None
    186         remove_file(save_path)
    187         os.rename(tmp_path, save_path)

E:\anacoda\lib\site-packages\hanlp\utils\io_util.py in download(url, save_path, save_dir, prefix, append_location, verbose)
    153             if verbose:
    154                 downloader.subscribe(DownloadCallback(show_header=False))
--> 155             downloader.start_sync()
    156         except BaseException as e:
    157             remove_file(tmp_path)

E:\anacoda\lib\site-packages\hanlp_downloader\down.py in start_sync(self)
    112             raise RuntimeError('Download has already been started.')
    113 
--> 114         self.run()
    115 
    116     def pause(self):

E:\anacoda\lib\site-packages\hanlp_downloader\down.py in run(self)
    150         s.mount('https://', adapter)
    151 
--> 152         r = s.get(self.url, stream=True, headers=self.headers)
    153         if r.status_code != 200:
    154             raise HTTPError(self.url, r.status_code, f'Internet error', r.headers, None)

E:\anacoda\lib\site-packages\requests\sessions.py in get(self, url, **kwargs)
    553 
    554         kwargs.setdefault('allow_redirects', True)
--> 555         return self.request('GET', url, **kwargs)
    556 
    557     def options(self, url, **kwargs):

E:\anacoda\lib\site-packages\requests\sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    540         }
    541         send_kwargs.update(settings)
--> 542         resp = self.send(prep, **send_kwargs)
    543 
    544         return resp

E:\anacoda\lib\site-packages\requests\sessions.py in send(self, request, **kwargs)
    675             # Redirect resolving generator.
    676             gen = self.resolve_redirects(r, request, **kwargs)
--> 677             history = [resp for resp in gen]
    678         else:
    679             history = []

E:\anacoda\lib\site-packages\requests\sessions.py in <listcomp>(.0)
    675             # Redirect resolving generator.
    676             gen = self.resolve_redirects(r, request, **kwargs)
--> 677             history = [resp for resp in gen]
    678         else:
    679             history = []

E:\anacoda\lib\site-packages\requests\sessions.py in resolve_redirects(self, resp, req, stream, timeout, verify, cert, proxies, yield_requests, **adapter_kwargs)
    235             else:
    236 
--> 237                 resp = self.send(
    238                     req,
    239                     stream=stream,

E:\anacoda\lib\site-packages\requests\sessions.py in send(self, request, **kwargs)
    653 
    654         # Send the request
--> 655         r = adapter.send(request, **kwargs)
    656 
    657         # Total elapsed time of the request (approximately)

E:\anacoda\lib\site-packages\requests\adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    514                 raise SSLError(e, request=request)
    515 
--> 516             raise ConnectionError(e, request=request)
    517 
    518         except ClosedPoolError as e:

ConnectionError: HTTPSConnectionPool(host='file.hankcs.workers.dev', port=443): Max retries exceeded with url: /hanlp/mtl/close_tok_pos_ner_srl_dep_sdp_con_electra_base_20210111_124519.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000024B8D6288E0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
无法复现：https://colab.research.google.com/drive/14PCqfgipX2VHnuAeRwBruFigUEmIhfEy?usp=sharing

你是否解压了`C:\Users\xxxx\AppData\Roaming\hanlp\mtl\close_tok_pos_ner_srl_dep_sdp_con_electra_small_20210111_124159.zip`导致它变成了一个文件夹？你不能解压它，参考：https://hanlp.hankcs.com/install.html#%E4%B8%8B%E8%BD%BD%E9%94%99%E8%AF%AF

**Comment by 1312354o** [comment]
没有解压文件
![X$NV9Q@T5ZCO LJW3T@IPRG](https://user-images.githubusercontent.com/78574705/177682620-cdfd120d-628b-4714-8f28-14a5f6f98512.png)

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。
