### ISSUE TITLE
求教：load BERT 模型报错

### ISSUE THREAD

**Issue by aaronzhangTechGeek** [hankcs/HanLP#1758]
**Code to reproduce the issue**
**recog = hanlp.load(hanlp.pretrained.ner.MSRA_NER_BERT_BASE_ZH)**

Failed to load https://file.hankcs.com/hanlp/ner/ner_bert_base_msra_20211227_114712.zip.
If the problem still persists, please submit an issue to https://github.com/hankcs/HanLP/issues
When reporting an issue, make sure to paste the FULL ERROR LOG below.
================================ERROR LOG BEGINS================================
OS: Windows-10-10.0.19041-SP0
Python: 3.8.3
PyTorch: 1.12.0+cpu
TensorFlow: 2.6.0
HanLP: 2.1.0-beta.36

OSError                                   Traceback (most recent call last)
<ipython-input-6-0638e9495b92> in <module>
----> 1 recog = hanlp.load(hanlp.pretrained.ner.MSRA_NER_BERT_BASE_ZH)

~\AppData\Roaming\Python\Python38\site-packages\hanlp\__init__.py in load(save_dir, verbose, **kwargs)
     41         from hanlp_common.constant import HANLP_VERBOSE
     42         verbose = HANLP_VERBOSE
---> 43     return load_from_meta_file(save_dir, 'meta.json', verbose=verbose, **kwargs)
     44 
     45 

~\AppData\Roaming\Python\Python38\site-packages\hanlp\utils\component_util.py in load_from_meta_file(save_dir, meta_filename, transform_only, verbose, **kwargs)
    173         except:
    174             pass
--> 175         raise e from None
    176 
    177 

~\AppData\Roaming\Python\Python38\site-packages\hanlp\utils\component_util.py in load_from_meta_file(save_dir, meta_filename, transform_only, verbose, **kwargs)
     97             else:
     98                 if os.path.isfile(os.path.join(save_dir, 'config.json')):
---> 99                     obj.load(save_dir, verbose=verbose, **kwargs)
    100                 else:
    101                     obj.load(metapath, **kwargs)

~\AppData\Roaming\Python\Python38\site-packages\hanlp\common\keras_component.py in load(self, save_dir, logger, **kwargs)
    212         self.load_config(save_dir)
    213         self.load_vocabs(save_dir)
--> 214         self.build(**merge_dict(self.config, training=False, logger=logger, **kwargs, overwrite=True, inplace=True))
    215         self.load_weights(save_dir, **kwargs)
    216         self.load_meta(save_dir)

~\AppData\Roaming\Python\Python38\site-packages\hanlp\common\keras_component.py in build(self, logger, **kwargs)
    222     def build(self, logger, **kwargs):
    223         self.transform.build_config()
--> 224         self.model = self.build_model(**merge_dict(self.config, training=kwargs.get('training', None),
    225                                                    loss=kwargs.get('loss', None)))
    226         self.transform.lock_vocabs()

~\AppData\Roaming\Python\Python38\site-packages\hanlp\components\taggers\transformers\transformer_tagger_tf.py in build_model(self, transformer, max_seq_length, **kwargs)
     32 
     33     def build_model(self, transformer, max_seq_length, **kwargs) -> tf.keras.Model:
---> 34         model, tokenizer = build_transformer(transformer, max_seq_length, len(self.transform.tag_vocab), tagging=True)
     35         self.transform.tokenizer = tokenizer
     36         return model

~\AppData\Roaming\Python\Python38\site-packages\hanlp\layers\transformers\loader_tf.py in build_transformer(transformer, max_seq_length, num_labels, tagging, tokenizer_only)
      9 
     10 def build_transformer(transformer, max_seq_length, num_labels, tagging=True, tokenizer_only=False):
---> 11     tokenizer = AutoTokenizer_.from_pretrained(transformer)
     12     if tokenizer_only:
     13         return tokenizer

~\AppData\Roaming\Python\Python38\site-packages\hanlp\layers\transformers\pt_imports.py in from_pretrained(cls, pretrained_model_name_or_path, use_fast, do_basic_tokenize)
     66         if use_fast and not do_basic_tokenize:
     67             warnings.warn('`do_basic_tokenize=False` might not work when `use_fast=True`')
---> 68         tokenizer = cls.from_pretrained(get_tokenizer_mirror(transformer), use_fast=use_fast,
     69                                         do_basic_tokenize=do_basic_tokenize,
     70                                         **additional_config)

~\AppData\Roaming\Python\Python38\site-packages\transformers\models\auto\tokenization_auto.py in from_pretrained(cls, pretrained_model_name_or_path, *inputs, **kwargs)
    533         if config_tokenizer_class is None:
    534             if not isinstance(config, PretrainedConfig):
--> 535                 config = AutoConfig.from_pretrained(
    536                     pretrained_model_name_or_path, trust_remote_code=trust_remote_code, **kwargs
    537                 )

~\AppData\Roaming\Python\Python38\site-packages\transformers\models\auto\configuration_auto.py in from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
    703         kwargs["name_or_path"] = pretrained_model_name_or_path
    704         trust_remote_code = kwargs.pop("trust_remote_code", False)
--> 705         config_dict, _ = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
    706         if "auto_map" in config_dict and "AutoConfig" in config_dict["auto_map"]:
    707             if not trust_remote_code:

~\AppData\Roaming\Python\Python38\site-packages\transformers\configuration_utils.py in get_config_dict(cls, pretrained_model_name_or_path, **kwargs)
    551         original_kwargs = copy.deepcopy(kwargs)
    552         # Get config dict associated with the base config file
--> 553         config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
    554 
    555         # That config file may point us toward another config file to use.

~\AppData\Roaming\Python\Python38\site-packages\transformers\configuration_utils.py in _get_config_dict(cls, pretrained_model_name_or_path, **kwargs)
    639             )
    640         except EnvironmentError:
--> 641             raise EnvironmentError(
    642                 f"Can't load config for '{pretrained_model_name_or_path}'. If you were trying to load it from "
    643                 "'https://huggingface.co/models', make sure you don't have a local directory with the same name. "

OSError: Can't load config for 'bert-base-chinese'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'bert-base-chinese' is the correct path to a directory containing a config.json file
=================================ERROR LOG ENDS=================================

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form when open a new issue.
