### ISSUE TITLE
跑文本相似度时报错！

### ISSUE THREAD

**Issue by Zengpr** [hankcs/HanLP#1761]
OSError: It looks like the config file at 'C:\Users\EDY\AppData\Roaming\hanlp\transformers\electra_zh_base_20210706_125233.zip' is not a valid JSON file.
![image](https://user-images.githubusercontent.com/22451062/178700301-9591d6a6-1b48-48e2-93a8-449e98ef235a.png)

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form when open a new issue.
