### ISSUE TITLE
hanlp.common.transform.NormalizeCharacter转换后和原句不同

### ISSUE THREAD

**Issue by geasyheart** [hankcs/HanLP#1762]
**Describe the bug**

[这里](https://github.com/hankcs/HanLP/blob/eb3e891f39949568ff1bfb2751ef9a585aa695a8/hanlp/common/transform.py#L493)，比如使用句子`与此同时，我们也为用户提供了客服申诉渠道、文档找回路径。`经过此函数转换后变成了`与此同时,我们也为用户提供了客服申诉渠道,文档找回路径。`

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python

```

**Describe the current behavior**
A clear and concise description of what happened.

**Expected behavior**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version:
- HanLP version:

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
这个函数的目的就是为了正规化字符，如果一定与原句一模一样，岂不是做无用功？

**Comment by geasyheart** [comment]
如果`，`转`,`这种我还能理解，你如果把`、`转成`,`这样就不太合适了吧

**Comment by hankcs** [comment]
的确，有不合理的地方。不过标点符号中半角似乎没有顿号？这份转换表统一将大部分标点符号转为半角（英文），其实对处理社交媒体上的文本很有优势。现在网络上能像你我这样区分逗号和顿号的人已经不多见了。

**Comment by geasyheart** [comment]
嗯嗯，我也是发现input_ids和您不一样时才发现的这个问题，如果需要基于您的结果继续训练或者后处理的话，就需要稍加注意了😃😃
