### ISSUE TITLE
提取关键词

### ISSUE THREAD

**Issue by wanghaisheng** [hankcs/HanLP#177]
我有大量如下格式的文本
```
姓名：张三性别：男年龄18身-高180cm发 型-飞机头母亲姓名：张妈妈......
```
这里的“姓名 性别 年龄 身高 发型”仅仅为了说明，实际上有大量的类似关键词 ，且每个文本中关键词出现的次数是不定的(有的包含其中10个 有的包含其中一个) 但每个关键词最多只会出现一次(姓名和母亲姓名认为是两个关键词)
希望能够实现提取到所有关键词(移除关键词内的特殊符号如空格、-等)列表，同时能够在关键词处添加分隔符
如下
```
姓名：张三 性别：男 年龄18 身高180cm 发型-飞机头 母亲姓名：张妈妈......
```
是否可以使用您提供的库实现，可否给予一些专业意见

**Comment by hankcs** [comment]
你对关键词的理解恐怕与一般意义不同，另外分隔符之类的属于用户自己的业务逻辑。

**Comment by wanghaisheng** [comment]
不好意思 困扰之处 这种应该如何表达才专业呢

**Comment by hankcs** [comment]
你认为关键字是由你决定的，而不是算法决定的，那么你应该自己写规则规定哪些是，哪些不是。

**Comment by wanghaisheng** [comment]
也不是 我认为关键词是算法去发现和筛选 我来决定
