### ISSUE TITLE
列表形式的输入，不同模型的结果长度不一致

### ISSUE THREAD

**Issue by jiauy** [hankcs/HanLP#1778]
**Describe the bug**
处理列表形式的输入，tok对于空字符串或单个标点是有返回值的，pos 和dep则没有返回值，导致tok的结果不能和pos 和 dep的结果一一对齐
**Code to reproduce the issue**

```python
import hanlp
tok  = hanlp.load(hanlp.pretrained.tok.COARSE_ELECTRA_SMALL_ZH)
pos = hanlp.load(hanlp.pretrained.pos.PKU_POS_ELECTRA_SMALL)
dep = hanlp.load(hanlp.pretrained.dep.PMT1_DEP_ELECTRA_SMALL)

text = ['你好', '']
tok_r = tok(text)
# [['你好'], ['']]
pos_r = pos(tok_r)
# [['l']]  期望的返回应该是 [['l'], []]
dep_r = dep(tok_r)
# [[{'id': 1, 'form': '你好', 'cpos': None, 'pos': None, 'head': 0, 'deprel': 'HED', 'lemma': None, 'feats': None, 'phead': None, 'pdeprel': None}]]
len(tok_r) != len(pos_r) ==len(dep_r)
# True
```

**Describe the current behavior**
处理列表形式的输入，tok对于空字符串或单个标点是有返回值的，pos 和dep则没有返回值，导致tok的结果不能和pos 和 dep的结果一一对齐

**Expected behavior**
对于空字符串或单个标点等，pos 和dep也需要有个空列表的结果进行占位，用于对文本进行标注。

**System information**
- macos 11.6 
- Python version: 3.8.12
- HanLP version: 2.1.0b37

**Other info / logs**
no

* [x] I've completed this form and searched the web for solutions.

**Comment by jiauy** [comment]
### 这个结果返回也很不好用

```python
import hanlp

dep = hanlp.load(hanlp.pretrained.dep.PMT1_DEP_ELECTRA_SMALL)

dep([[''],  ['你', '好']])
# []
```

**Comment by hankcs** [comment]
的确存在这个问题。但是`['']`应当视作仅含有一个单词`''`的已分词句子，结果应当仅含有一个元素。`[]`的词性/DEP结果才应该是'[]'，0个元素。

感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。
