### ISSUE TITLE
关于HanLP计算文章相似度问题

### ISSUE THREAD

**Issue by ct-wen** [hankcs/HanLP#178]
之前用Ansj，现刚发现HanLP，还不熟悉，但觉得HanLP非常不错。冒昧请教博主，我希望通过HanLP实现计算两个文章的相似度，盼大神提供使用HanLP实现文章相似度的大概思路或功能，感激不尽~我看https://github.com/ysc/word/tree/master/src/main/java/org/apdplat/word/analysis已有诸多算法实现，但我依然希望使用HanLP，可惜没有类似功能，着实遗憾，亟盼作者提供帮助。

**Comment by hankcs** [comment]
你好，

0. 这类相似度计算是很原始很朴素的，引入这些计算方法的优先级很低
0. 如果对你很有吸引力，你可以将HanLP输出的List<Term>转为对方的List<Word>，应该十分简单

**Comment by hankcs** [comment]
另外，这些相似度计算方法本质上是基于规则的，而HanLP倾向于基于统计。也许未来会新增相似度计算接口，但内部用的会是一些更高级的模型。

**Comment by plum1999** [comment]
@hankcs 作为一款开源分词组件，希望增加文本相似度比对、词频功能，尤其是相似度算法，对于一般开发人员是很难的实现的，所以这些对于很多开发者来说是很需要的。如ictclas这款分词器就有相似、词频这些功能

**Comment by hankcs** [comment]
好的，我会仔细考虑这些建议的。

**Comment by hankcs** [comment]
纠正一下，ictclas不是开源的。

**Comment by DusonWang** [comment]
相似度算法可以参考simhash

**Comment by shaogx** [comment]
语义相似度计算能实现就好了

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。

**Comment by xu0612204126** [comment]
HanLp2.0 是不是只支持Python，没有java版本？
