### ISSUE TITLE
java  DynamicCustomDictionary load 词典时候不生效

### ISSUE THREAD

**Issue by duanfa** [hankcs/HanLP#1782]
**Describe the bug**
DynamicCustomDictionary

**Code to reproduce the issue**
  dictionary.load("/home/duanfa/trash/845.txt");
  DynamicCustomDictionary load 词典时候不生效 
845.txt 文件内容

爱慕官方花园速写内衣女无钢圈中厚杯小胸聚拢蕾丝文胸AM171791 nz 1
爱慕官方花 nz 1

 用  insert 生效
  dictionary.insert("爱慕官方花园速写内衣女无钢圈中厚杯小胸聚拢蕾丝文胸AM171791", "N 1");

或者在hanlp.properties里面配置
CustomDictionaryPath=data/dictionary/custom/duanfa/845.txt 
生效后，把 data/dictionary/custom/duanfa/845.txt.bin  拷贝到 /home/duanfa/trash/  目录下，dictionary.load("/home/duanfa/trash/845.txt");就可以生效了

版本
 <dependency>
            <groupId>com.hankcs</groupId>
            <artifactId>hanlp</artifactId>
            <version>portable-1.8.3</version>
        </dependency>

```import com.hankcs.hanlp.HanLP;
import com.hankcs.hanlp.dictionary.DynamicCustomDictionary;
import com.hankcs.hanlp.seg.Segment;
import com.hankcs.hanlp.seg.common.Term;

public class LoadCustomFile {
	public DynamicCustomDictionary dictionary = new DynamicCustomDictionary();
	public Segment hanlpSegmenter;

	public LoadCustomFile() {
		try {
			hanlpSegmenter = HanLP.newSegment();
			hanlpSegmenter.enableCustomDictionary(dictionary).enableCustomDictionaryForcing(true);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	public static void main(String[] args) {
		String text = "爱慕官方花园速写内衣女无钢圈中厚杯小胸聚拢蕾丝文胸AM171791";
		LoadCustomFile lcf = new LoadCustomFile();
		lcf.dictionary.load("/home/duanfa/trash/845.txt");
		for (Term term : lcf.hanlpSegmenter.seg(text)) {
			System.out.println(term);
		}
	}
}
```
代码打印结果：
爱慕/vn
官方/n
花园/n
速写/n
内衣/n
女/b
无/v
钢圈/n
中/f
厚/a
杯/q
小/a
胸/ng
聚拢/v
蕾/ng
丝/q
文/ng
胸/ng
AM/nx
171791/m

**Describe the current behavior**
A clear and concise description of what happened.

**Expected behavior**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version:
- HanLP version:

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [x] I've completed this form and searched the web for solutions.

**Comment by duanfa** [comment]
先把动态insert的新词保存成bin文件，然后下次load就可以了

**Comment by Huyueeer** [comment]
@duanfa 请问一下您，保存成bin是指比方说`xxx.txt`变成`xxx.txt.bin`吗？

**Comment by duanfa** [comment]
> @duanfa 请问一下您，保存成bin是指比方说`xxx.txt`变成`xxx.txt.bin`吗？

save的时候就会自己保存成.bin后缀的文件
