### ISSUE TITLE
BinTrie和DoubleArrayTrie序列化失败

### ISSUE THREAD

**Issue by B-RF** [hankcs/HanLP#1784]
**Describe the bug**
这边使用HanLP 1.8.3的jar进行学习测试时，发现BinTrie和DoubleArrayTrie都是可序列化的，但是执行序列化时，提示hanlp.corpus.tag.Nature不是序列化实现~进行开发时会导致异常结束。

**Describe the current behavior**
序列化时抛出异常，序列化失败。

**Expected behavior**
希望可以序列化正常~

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Java version:JDK 11
- HanLP version:1.8.3

**Other info / logs**
java.io.NotSerializableException: com.hankcs.hanlp.corpus.tag.Nature

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
这两个泛型容器设计上不支持序列化value，只保存key。
