### ISSUE TITLE
CRF分词模型的训练 和 CRF分词视标点为新词问题

### ISSUE THREAD

**Issue by Renzhh** [hankcs/HanLP#18]
CRF分词模型使用的是什么语料？以及-f, -c参数的选取。只能通过不断的测试，选取经过测试选取效果好的？

另，经使用1.2.2版的HanLP和data，测试CRF分词，测试数据如下：

    "《夜晚的骰子》通过描述浅草的舞女在暗夜中扔骰子的情景,寄托了作者对庶民生活区的情感",
    "这个像是真的[委屈]前面那个打扮太江户了，一点不上品...@hankcs", 
关闭词性标注的分词效果如下：

    [《, 夜晚, 的, 骰子, 》, 通过, 描述, 浅草, 的, 舞女, 在, 暗夜, 中, 扔, 骰子, 的, 情景, ,, 寄托, 了, 作者, 对, 庶民, 生活区, 的, 情感]
    [这个, 像, 是, 真的, [, 委屈, ], 前面, 那个, 打扮, 太, 江户, 了, ，, 一点, 不, 上品, ., ., ., @, hankcs]
再查阅词典CoreNatureDictionary.txt，不存在其中的标注为null词性的词视为新词，以上两例句识别出的新词分别为：

    识别到新词：,(wc: 1)
    识别到新词：@(wc: 1), hankcs(wc: 1), [(wc: 1), ](wc: 1), .(wc: 3)
整体效果不错，诸如"hankcs"词识别出了，但像",", "@", "[", "]", "."等标点符号也被视为新词。能够在CRF分词之后加入停用词之类的做法，过滤掉此类的词呢？

谢谢！

**Comment by hankcs** [comment]
感谢建议。

0. 2014人民日报语料库
0. 调参是个苦活，硬件条件有限，训练一个模型得12个小时，所以暂未考虑。如果你有更好的机器，可以自行训练，只要输出文本形式的模型，HanLP就可以读取。
0. 用词性是否为null来判断新词的确很朴素。我的确在构想提供更实用的API，但是我倾向于只提供接口，向用户隐藏内部的细节（基于CRF？基于TnT？基于信息熵？）。内部的实现当然会考虑标点的问题，考虑排重，考虑用户词典，过滤停用词、过滤英文、数词、日期、人名……所以这套东西虽然没什么难度，但是还是有点工作量的，大约会在七月份去做掉。在此之前，欢迎继续讨论，提供宝贵意见。

**Comment by Renzhh** [comment]
@hankcs 可以分享下这份语料，或其他标注好的语料吗？打算重新训练CRF模型。
上面你说的这些工作量还是很大的。看你CRF训练模型的介绍，使用了unigram和bigram两种特征模板，有没有考虑结合信息熵、互信息以及TF-IDF等特征？我打算做，但不知如何将这些特征加入CRF训练模型中，还请赐教。

**Comment by hankcs** [comment]
这些特征不太可能跟CRF融合到一起。
我没有原语料的版权，但是BMES切分后应该并不侵权。这里面经过了我的预处理和调整，主要人工校正了一些错误。http://pan.baidu.com/s/1jGh9nka

我推荐使用的特征模板是：

# Unigram
U00:%x[-1,0]
U01:%x[0,0]
U02:%x[1,0]
U03:%x[-1,0]%x[0,0]
U04:%x[0,0]%x[1,0]
U05:%x[-1,0]%x[1,0]

# Bigram
B

欢迎调参训练后分享你的成果。

**Comment by Renzhh** [comment]
谢谢您的分享！

**Comment by Renzhh** [comment]
@hankcs 之前看到的结合CRF结合左右信息熵、互信息、TF-IDF特征的论文

    “陈飞,刘奕群,魏超,张云亮,张敏,马少平.基于条件随机场方法的开放领域新词发现.软件学报,2013,24(5): 1051-1060. http://www.jos.org.cn/1000-9825/4254.htm”
不过论文中没有说明方法，只说采用了上述的特征进行新词发现，列出了实验结果。

**Comment by hankcs** [comment]
这篇论文我看完了，他们挺能搞的。具体方法我能猜个大概，先分词，然后统计信息熵、互信息，tf-idf等数值并且离散化，最后人工采用01tag标注分词结果。于是就得到了一个训练文件，送进CRF训练得到模型。最终做新词识别的时候，也把信息熵、互信息，tf-idf统计一遍，得到一个观测序列，送到CRF模型里面标注一下，得到01序列，将000……1合并得到新词。

也只有坐在实验室才能想出这么折腾的法子啊，另外，对语料的数量级要求估计不低，人工标注也费时费力，估计很难用于生产环境。

个人观点，非专业意见，仅供参考。

**Comment by Renzhh** [comment]
@hankcs 就您分享的2014人民日报BMES切分后的语料，在Ubuntu14.04 CRF++-0.58下进行训练，但提示如下错误：

    encoder.cpp(340) [feature_index.open(templfile, trainfile)] feature_index.cpp(174) [max_size == size] inconsistent column size: 2 1 2014_people_daily.data
搜索了下，发现example的训练语料每行不仅包含单字和BMES标注，其中第二列还有词性的标注，我使用的语料只有单字和BMES标注两列，不知是不是因为这个导致报错

**Comment by hankcs** [comment]
根据不同的语料编写不同的模板，而不是呆板地去套example
http://www.hankcs.com/nlp/the-crf-model-format-description.html

**Comment by Renzhh** [comment]
我使用的特征模板就是

    # Unigram
    U00:%x[-2,0]
    U01:%x[-1,0]
    U02:%x[0,0]
    U03:%x[1,0]
    U04:%x[2,0]
    U05:%x[-2,0]/%x[-1,0]/%x[0,0]
    U06:%x[-1,0]/%x[0,0]/%x[1,0]
    U07:%x[0,0]/%x[1,0]/%x[2,0]
    U08:%x[-1,0]/%x[0,0]
    U09:%x[0,0]/%x[1,0]
     
    # Bigram
    B
而报错是
    
    feature_index.cpp(174) [max_size == size] inconsistent column size: 2 1 2014_people_daily.data
基于BMES标注的语料，准备建立分词模型。我再检查下语料

**Comment by hankcs** [comment]
0. 首先，我猜这是由于语料的换行符是/r/n，而*nix的换行符是/n造成的
0. 这个模板我测试的效果不好，体积大，过拟合

**Comment by Renzhh** [comment]
找到原因了，是有空格行导致

    本		S
    年		S
    的		S
    交		B
    易		E
    。		S
    
    
    《		S
    纽		B
    约		M
    时		M
    报		E
    》		S
    报		B
    道		E
    说		S
    ，		S
发现在语料很多句子结束部分后面还会多空出几行，检测出并删掉就可以正常地进行训练了。
模板的效果还得使用测试集测试，观察效果才能定夺哪种模板效果更好。
看到您上面推荐使用的模板了：

    # Unigram
    U00:%x[-1,0]
    U01:%x[0,0]
    U02:%x[1,0]
    U03:%x[-1,0]%x[0,0]
    U04:%x[0,0]%x[1,0]
    U05:%x[-1,0]%x[1,0]
    
    # Bigram
    B

**Comment by hankcs** [comment]
感谢指出问题，虽然我这边空格没导致报错。

训练集是个好主意，我凭主观感觉并不严谨。

**Comment by Renzhh** [comment]
使用自己训练好的CRF模型，放到本地，替换默认你提供的CRFSegmentModel.txt.bin模型，但出错了。请教，.bin的模型缓存是怎么生成的，或者说从训练来的Model怎么得到？

**Comment by hankcs** [comment]
像我上面提到的一样，只要让CRF++输出文本形式的模型，HanLP就可以读取。
路径直接填文本模型的路径，HanLP第一次读取后会自动转换一个同名的bin文件出来，这样下次载入就会直接载入bin，快很多。

**Comment by hankcs** [comment]
如果你把文本形式的模型改成CRFSegmentModel.txt.bin，会导致HanLP把它当成了缓存，直接以binary形式读取了，于是就出问题了。

**Comment by Renzhh** [comment]
我确实是将CRF++输出的模型文件SegModel.txt放到data/model下，并修改的hanlp.properties，将CRFSegmentModelPath修改为自己训练的SegModel.txt文件。但运行程序，出错了

**Comment by hankcs** [comment]
具体出了什么错误呢？OutOfMemory吗？

**Comment by Renzhh** [comment]
@hankcs 通过Debug已经解决，谢谢你的指点！
