### ISSUE TITLE
修改一行代码可以让DAT构建速度提升N倍

### ISSUE THREAD

**Issue by qiangwang** [hankcs/HanLP#1801]
**Describe the feature and the current behavior/state.**

https://github.com/hankcs/HanLP/blob/1323221c38e9188b19cef3f770eec40148a459ac/src/main/java/com/hankcs/hanlp/collection/trie/DoubleArrayTrie.java#L167

`int pos = Math.max(siblings.get(0).code + 1, nextCheckPos) - 1;`
改成
`int pos = Math.max(siblings.get(0).code, nextCheckPos);`

构建速度可以提升很多而且表现稳定，缺点是最终构建出的DAT大小微增。但是不清楚背后原理，您可以测试一下，下面是我的测试数据：

<img width="633" alt="image" src="https://user-images.githubusercontent.com/1414826/213084924-2dd7248d-d0ee-4476-b110-74b93be7a1d9.png">

其中保留nextCheckPos为原版代码，去掉nextCheckPos用作对比，核心循环计数是在循环体内做了一个`count++`计数：
![image](https://user-images.githubusercontent.com/1414826/213085116-83c7c0c8-fa47-4b14-95fa-9307af0d067a.png)

**Will this change the current api? How?**

No

**Who will benefit with this feature?**

Anyone who uses DAT

**Are you willing to contribute it (Yes/No):**

Yes

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Big Sur
- Python version:
- HanLP version: hanlp-portable-1.8.3.jar

**Any other info**

* [x] I've carefully completed this form.

**Comment by hankcs** [comment]
感谢共享你的发现。我认为，去掉减1后，`nextCheckPos `在很多时候不会被`-1`。又由于循环体开始时会对`pos`+1：
https://github.com/hankcs/HanLP/blob/d34dab3aa5a3f6eaf25c198ecadaed4aa0fb9270/src/main/java/com/hankcs/hanlp/collection/trie/DoubleArrayTrie.java#L178
这就导致每次调用`insert`其实都是从`nextCheckPos+1`开始搜索，每次都空出来了1个位置，于是导致了DAT体积微增。空出来的位置越多，下次`insert`越容易搜索到空闲空间，所以搜索时间就降下来了。

不过DAT的构建一般是离线进行，时间开销不敏感。另外，体积增大意味着内存占用也增大。时间与空间，不同场景有不同的偏好吧。如果你有兴趣给所有`build`方法加一个`boolean fast`参数，我很乐意merge。

原理可参考[《自然语言处理入门》](http://nlp.hankcs.com/book.php) P56。

**Comment by qiangwang** [comment]
好的，感谢解惑，我们的应用场景是会频繁变更和构建，构建时间需要稳定在1s以内。
建议是加个enableFastBuild成员变量，不用层层透传，也不影响现存接口，我找时间提个mr。
