### ISSUE TITLE
文件流未正确关闭

### ISSUE THREAD

**Issue by zjqer** [hankcs/HanLP#1806]
**Describe the bug**
VectorsReader类的readVectorFile()方法未正确关闭文件流，导致资源泄漏
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
使用Word2VecTrainer的train方法，或者new 一个WordVectorModel对象，进程进行中，删除模型文件比如model.txt，会无法删除
```java
```

**Describe the current behavior**
A clear and concise description of what happened.

**Expected behavior**
我在使用该jar进行词向量模型训练或者文档转换为向量后，模型文件始终删除不掉，文件资源积压
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):任何系统都会出现
- Python version:
- HanLP version:目前发现1.5-1.8.3的版本都会出现该问题

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
[VectorsReader.java](https://github.com/hankcs/HanLP/blob/v1.8.3/src/main/java/com/hankcs/hanlp/mining/word2vec/VectorsReader.java)
* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
感谢反馈，已经修复，请检查上面的commit是否解决了这个问题。
如果还有问题，欢迎重开issue。

**Comment by zjqer** [comment]
确认修复。请问修复版本什么时候发布呢

**Comment by hankcs** [comment]
已发布：https://github.com/hankcs/HanLP/releases/tag/v1.8.4
