### ISSUE TITLE
加载MSRA_NER_ALBERT_BASE_ZH失败

### ISSUE THREAD

**Issue by LUOQING1994** [hankcs/HanLP#1810]
**Describe the bug**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
```

**Describe the current behavior**
使用pip install --upgrade hanlp[full]安装最新版本的hanlp，并使用ner = hanlp.load(hanlp.pretrained.ner.MSRA_NER_ALBERT_BASE_ZH)进行模型加载，但报如下错误：
![image](https://user-images.githubusercontent.com/20340633/227485545-c2209a84-f2f8-4be4-afa7-dfbac81b528d.png)

**Expected behavior**
期望能正常加载

**System information**
- OS Platform and Distribution:inux-5.4.0-139-generic-x86_64-with-glibc2.27
- Python version:3.8.0
- HanLP version:2.1.0-beta.46

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
https://github.com/hankcs/HanLP/blob/6dbd5a8e428cbde3192f30c26930e5c785839061/plugins/hanlp_demo/hanlp_demo/zh/demo_pipeline.py#L8
