### ISSUE TITLE
成分句法分析会修改原始文本，如修改中文的标点符号？

### ISSUE THREAD

**Issue by FutureWithoutEnding** [hankcs/HanLP#1811]
**成分句法分析修改原始文本**

**Code to reproduce the issue**
```python
import hanlp
from hanlp import pretrained

tokenizer_model = pretrained.tok.COARSE_ELECTRA_SMALL_ZH
tokenizer = hanlp.load(tokenizer_model)

toks = tokenizer("栏目下的一个节目，这个节目主要探讨的是英语口语的常用表达、词汇的起源和其背后的故事。")
print(toks)

constituency_model = pretrained.constituency.CTB9_CON_ELECTRA_SMALL
parser = hanlp.load(constituency_model)
tree = parser(toks)
print(tree)
```

**Describe the current behavior**
![image](https://user-images.githubusercontent.com/53685945/230709750-3b17e2c4-4eb3-4fa2-a491-4da61f79a4d3.png)
为了好展示，修改了token是输出格式（为了代码的简洁，没有包含在演示代码中）

**Expected behavior**
保持原来的中文标点。

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  CentOS Linux release 7.9.2009 (Core)
- Python version: Python 3.8.16
- HanLP version: 2.1.0b47

**Other info / logs**
None

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
感谢反馈，已经修复，请检查上面的commit是否解决了这个问题。
如果还有问题，欢迎重开issue。
