### ISSUE TITLE
成分句法分析的标注标准

### ISSUE THREAD

**Issue by FutureWithoutEnding** [hankcs/HanLP#1814]
**Describe the bug**
严格意义上，这不算一个Bug，是一个问题。（https://bbs.hankcs.com/ 上没有注册成功）

Github Readme中，说明的“成分句法分析”的标注标准是Chinese Tree Bank：https://hanlp.hankcs.com/docs/annotations/constituency/ctb.html
上述页面上的所有Tag：
```
'ADJP', 'ADVP', 'CLP', 'CP', 'DNP', 'DP', 'DVP', 'FRAG', 'INTJ',
'IP', 'LCP', 'LST', 'MSP', 'NN', 'NP', 'PP', 'PRN', 'QP', 'ROOT', 'UCP',
'VCD', 'VCP', 'VNV', 'VP', 'VPT', 'VRD', 'VSB'
```

而我在自己数据集上生成的所有Tag：
```
'CLP', 'QP', 'NP', 'ADJP', 'ADVP', 'IP', 'VP', 'PP', 'VSB',
'TOP', 'DP', 'LCP', 'CP', 'DNP', 'PRN', 'DVP', 'VRD', 'VCP',
'UCP', 'VCD', 'VPT', 'VNV', 'DFL', 'FLR', 'INTJ', 'LST', 'INC',
'EMO', 'FRAG', 'SKIP', 'IMG', 'IP=9', 'OTH', 'NP=2', 'NP=3', 'TYPO', 'IP=4'
```
实际生成的Tag与网页上的不一致：
- ROOT -> TOP
- 没有生成过'MSP'和'NN'（数据量不小）
- 生成的'DFL'、'EMO'、'FLR'、'IMG'、'INC'、'IP=4'、'IP=9'、'NP=2'、'NP=3'、'OTH'、'SKIP'、'TYPO'不在网页上

**Code to reproduce the issue**
None

**Describe the current behavior**
None

**Expected behavior**
希望得到一个所有可能生成的Tag（标签）列表。
更新网页上的标注标准。

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): None
- Python version: None
- HanLP version: None

**Other info / logs**
None

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
如果你能描述一下bbs为什么没有注册成功，我可能可以帮助你注册。

关于标注标准，一个个讨论。

1. 的确CTB中既没有TOP也没有ROOT。TOP是按照英文ptb习惯为每棵树创建的根结点，而CTB的根结点大部分是IP，少部分是其他，用TOP既可以统一根结点，也可以在模型错误地预测了两个子树的时候能将其连接为一棵树。按照这个逻辑，已经删除了文档中的ROOT。
2. MSP可以测测“所”字结构。NN是词性标注的结果，多个NN的成分为NP而不是NN。你可以通过这个colab验证：https://colab.research.google.com/drive/1W1YVp5U2L0SrJuV44aCJAI6bCcz4r4vV?usp=sharing
3. 这些带“-”的成分属于sub categories，请参考 https://bbs.hankcs.com/t/topic/4449 。模型发布后文档还没有跟上，因为找不到合适的中文翻译。你可以参考 https://www.cs.brandeis.edu/~clp/ctb/parseguide.3rd.ch.pdf 理解，也欢迎贡献翻译。

**Comment by FutureWithoutEnding** [comment]
感谢您的回复。
The Bracketing Guidelines for the Penn Chinese Treebank是2000年的，后续没有更新吗？
bbs，没有注册成功的原因是，我的github邮箱是outlook邮箱，好像是不支持outlook，而且无法修改邮箱。

**Comment by hankcs** [comment]
> 感谢您的回复。
> 
> The Bracketing Guidelines for the Penn Chinese Treebank是2000年的，后续没有更新吗？

没有更新。

> 
> bbs，没有注册成功的原因是，我的github邮箱是outlook邮箱，好像是不支持outlook，而且无法修改邮箱。

微软粗暴地屏蔽了许多机房的ip，导致论坛发出的注册邮件收不到，所以我们bbs也不再支持微软系列邮箱。GitHub支持将某个邮箱设为默认，你只需要换用gmail之类的主流邮箱就可以收到邮件。
