### ISSUE TITLE
成分句法分析的sampler_builder、batch_size参数

### ISSUE THREAD

**Issue by FutureWithoutEnding** [hankcs/HanLP#1815]
**Describe the bug**
指定batch_size参数不起作用

**Code to reproduce the issue**
```python
import hanlp
from hanlp import pretrained

tokenizer_model = pretrained.tok.COARSE_ELECTRA_SMALL_ZH
tokenizer = hanlp.load(tokenizer_model, devices=0)
constituency_model = pretrained.constituency.CTB9_CON_ELECTRA_SMALL
parser = hanlp.load(constituency_model)

s = "栏目下的一个节目，这个节目主要探讨的是英语口语的常用表达、词汇的起源和其背后的故事。"
sentences = [s] * 100
tokens = tokenizer(sentences, batch_size=bs)
parseing_tree = parser(batch_tokens, batch_size=bs)
```

**Describe the current behavior**
指定batch_size是不生效的，会自动加载config中的sampler_builder。
sampler_builder中：
- Tokenizer的batch_size是32
- constituency的batch_size是10

对于Tokenizer，添加`sampler_builder=None`就可以使batch_size生效: 
```
tokens = tokenizer(sentences, sampler_builder=None, batch_size=bs)
```
对于constituency，即使添加`sampler_builder=None`，也不会使batch_size生效，
```
parseing_tree = parser(batch_tokens, sampler_builder=None, batch_size=bs)
```

**Expected behavior**
对于Tokenizer和constituency：
- 指定了batch_size参数就起作用，不需要和sampler_builder=None配合
     - （即当指定了batch_size就要屏蔽config中的sampler_builder）

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04.4 LTS
- Python version: Python 3.8.16
- HanLP version: 2.1.0b48

**Other info / logs**
None

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
感谢反馈，已经修复，请检查上面的commit是否解决了这个问题。
如果还有问题，欢迎重开issue。

`batch_size`优先级和效率都不如`sampler_builder`高，建议直接修改`sampler_builder`中的`batch_size`:

```
print(parser.config.sampler_builder.batch_size)
parser.config.sampler_builder.batch_size = 10
```
