### ISSUE TITLE
在使用文本相似度比较时，两个字符串交换一下位置，得出来的文本相似度不一样

### ISSUE THREAD

**Issue by callmebyZJ** [hankcs/HanLP#1819]
**Describe the bug**
在使用文本相似度比较时，两个字符串交换一下位置，得出来的文本相似度不一样

**Code to reproduce the issue**
![image](https://user-images.githubusercontent.com/77441902/236605940-f5f62acf-d3f8-4a9b-adb1-b2d2edf342d3.png)

```python
```

**Describe the current behavior**
点击运行后，发现文本相似度的值不同

**Expected behavior**
交换字符串的位置，应该得到的文本相似度是一样的。

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version:
- HanLP version:

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
这是由于positional embedding导致的，是单塔模型固有的缺陷，请关注后续双塔模型的发布。
