### ISSUE TITLE
branch:portable - com/hankcs/hanlp/collection/trie/bintrie/BinTrie.java全切分问题

### ISSUE THREAD

**Issue by wxy929629** [hankcs/HanLP#1820]
同:https://bbs.hankcs.com/t/2-4-5/5393
**Describe the bug**
在2.4.5 前缀树的妙用代码com/hankcs/hanlp/collection/trie/bintrie/BinTrie.java
中, 假设词典为[中华, 中华人", 华人], 输入文本为[中华人], 那么i这个变量会不断自增 最终切出的词只有[中华, 中华人], 但是这个方法是全切分吗？是否应该切出[华人]这个词, 不知道是否我理解有误, 感谢解答

**Code to reproduce the issue**
`public class BinTriedTest {
    public static void main(String[] args) throws IOException {
        // 加载词典
        TreeMap<String, CoreDictionary.Attribute> dictionary =
            IOUtil.loadDictionary("data/dictionary/TestDictionary.txt");
        final BinTrie<CoreDictionary.Attribute> binTrie = new BinTrie<CoreDictionary.Attribute>(dictionary);
        List<String> wordlist = segmentFully("中华人", binTrie);
        System.out.println(wordlist);
    }

    public static List<String> segmentFully(final String text, BinTrie<CoreDictionary.Attribute> dictionary)
    {
        final List<String> wordList = new LinkedList<String>();
        dictionary.parseText(text, new AhoCorasickDoubleArrayTrie.IHit<CoreDictionary.Attribute>()
        {
            @Override
            public void hit(int begin, int end, CoreDictionary.Attribute value)
            {
                wordList.add(text.substring(begin, end));
            }
        });
        return wordList;
    }}`
![image](https://github.com/hankcs/HanLP/assets/27196120/6020e0a2-6813-485a-9c1d-dfe16fc9a43c)
![image](https://github.com/hankcs/HanLP/assets/27196120/9a431398-ec6c-44eb-88e8-8f504e10a05a)
![image](https://github.com/hankcs/HanLP/assets/27196120/b7eb537e-955b-4415-94e9-c5be6fa92f0f)

**Describe the current behavior**
![image](https://github.com/hankcs/HanLP/assets/27196120/eecbc8a8-7071-4d31-9ed6-2f97226a19e3)

output: [中华, 中华人]

**Expected behavior**
expected output: [中华, 中华人,华人]

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version:
- HanLP version:portable

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
dup: https://github.com/hankcs/HanLP/pull/1775
