### ISSUE TITLE
python3.10时，tf支持版本最低是2.8.0，setup中却只能等于2.6.0

### ISSUE THREAD

**Issue by SWHL** [hankcs/HanLP#1821]
**Describe the bug**
- python3.10时，安装`extras_require=tf`时，`tensorflow==2.6.0`不能被满足
https://github.com/hankcs/HanLP/blob/31c34ec86f71fe91f1fe6d86e7ca8575c80e2306/setup.py#L24

- 因为[pypi](https://pypi.org/project/tensorflow/2.6.0/#files)中最多支持到python3.9

    ![image](https://github.com/hankcs/HanLP/assets/28639377/f5a7632b-193b-43f9-8f4b-358c5d1eca4e)

**Expected behavior**
- 期待库检查时，可适当放松版本限制

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux CentOS 7
- Python version: 3.10
- HanLP version: 2.1.0b49

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
1. 版本号pin得很严格是因为tensorflow的兼容性实在太差了：https://bbs.hankcs.com/t/topic/2360/2?u=hankcs
2. 如果你能测试出一个兼容目前模型的tf更高版本，我很乐意接受pr。

**Comment by SWHL** [comment]
- 目前的问题是：仓库说是兼容`python==3.10`，但是涉及到`tensorflow`包的情况时，`python==3.10`就不行了。你看有没有必要做一些说明啥的
- 我现在用的是`python==3.10`，`tensorflow==2.8.0`，注释掉了`hanlp`中库版本检验部分，目前来看能用，并没有经过全面测试哈，仅供参考。

**Comment by hankcs** [comment]
的确是缺少说明。不过每次升级tf都会造成很大的维护负担，后面考虑drop tf。
