### ISSUE TITLE
Moving model to GPUs [0]

### ISSUE THREAD

**Issue by ncbwct** [hankcs/HanLP#1824]
Moving model to GPUs [0] ...Failed to load https://file.hankcs.com/hanlp/mtl/close_tok_pos_ner_srl_dep_sdp_con_electra_small_20210111_124159.zip
If the problem still persists, please submit an issue to https://github.com/hankcs/HanLP/issues
When reporting an issue, make sure to paste the FULL ERROR LOG below.
================================ERROR LOG BEGINS================================
OS: Windows-10-10.0.22621-SP0
Python: 3.9.16
PyTorch: 2.0.1+cpu
HanLP: 2.1.0-beta.50

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form when open a new issue.
