### ISSUE TITLE
Only connect to mybinder.org when website visitor click on `run`

### ISSUE THREAD

**Issue by rgaiacs** [hankcs/HanLP#1826]
Hi,

I noticed that, during load of https://hanlp.hankcs.com/en/, a connection to https://mybinder.org/ will be created. Because https://mybinder.org/ is running with reduced capacity since May 2023 (details at https://blog.jupyter.org/mybinder-org-reducing-capacity-c93ccfc6413f), would be possible to wait until the website vistor clicks on `run` to connect to https://mybinder.org/?

Screenshot of the website immediately after load and before full connection to https://mybinder.org/ is established:

![Screenshot 2023-06-28 at 15-02-38 HanLP](https://github.com/hankcs/HanLP/assets/1506457/718b1011-1eb4-4670-aa92-d1fca63a65ca)

Screenshot of number of requests from https://hanlp.hankcs.com/en/ to https://mybinder.org/

![Screenshot 2023-06-28 at 15-07-07 Pod Activity - Dashboards - Grafana](https://github.com/hankcs/HanLP/assets/1506457/616ec5f3-6563-4427-8b6b-3bb1adfc7732)

Thanks!

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form when open a new issue.
