### ISSUE TITLE
Unable to run in Docker; Can HanLP have some way to pre-install the pretrained models files? at pip install time?

### ISSUE THREAD

**Issue by tx0c** [hankcs/HanLP#1827]
**Describe the bug**
When running inside docker with another username, it can't find the pretrained model files,

**Code to reproduce the issue**
the HanLP is trying to download the pretrained on first-time, this may not work under environments with no Internet access, (e.g. behind a Corporate firewall,)

so I use a little trick to run a this part code in docker building phase, to pre-warm up HanLP to not have to download again, it does download the necessary pretrained models files, and indeed work if run the container with same root username,
```log
Step 22/26 : RUN python3 ./app/text/tokenizer.py
 ---> Running in 241d468253cd
Downloading https://file.hankcs.com/hanlp/tok/fine_electra_small_20220615_231803.zip to /root/.hanlp/tok/fine_electra_small_20220615_231803.zip
100%  43.5 MiB 440.1 KiB/s ETA:  0 s [=========================================]
Decompressing /root/.hanlp/tok/fine_electra_small_20220615_231803.zip to /root/.hanlp/tok
Downloading https://file.hankcs.com/hanlp/utils/char_table_20210602_202632.json.zip to /root/.hanlp/utils/char_table_20210602_202632.json.zip
100%  26.7 KiB  26.7 KiB/s ETA:  0 s [=========================================]
Decompressing /root/.hanlp/utils/char_table_20210602_202632.json.zip to /root/.hanlp/utils
Downloading https://file.hankcs.com/hanlp/transformers/electra_zh_small_20210706_125427.zip to /root/.hanlp/transformers/electra_zh_small_20210706_125427.zip
100%  41.2 KiB  41.2 KiB/s ETA:  0 s [=========================================]
Decompressing /root/.hanlp/transformers/electra_zh_small_20210706_125427.zip to /root/.hanlp/transformers
```

**Describe the current behavior**
however, it downloaded those files to `/root/.hanlp/...`, and at run-time it often be run under another username, (e.g. AWS Lambda Container use another temporary generated username), then the same code would try to download again to `/home/username/.hanlp/...`

**Expected behavior**
Can HanLP have some way to pre-install the pretrained models files? at pip install time?

Or support a common path like `PRETRAIN_FILES_DIR=/common/path/`, so any user run this would get it from a common path;

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 22.04
- Python version: `3.10`
- HanLP version: `hanlp==2.1.0b50`  (we use this but this is not HanLP version specific)

**Other info / logs**

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
Hi @tx0c , thanks for your question, we have you covered. Please refer to the configuration doc at: https://hanlp.hankcs.com/docs/configure.html

Basically, HanLP uses the environment variable `HANLP_HOME` to specify the load path of all HanLP-managed resources. Note that HuggingFace transformers manage their own resources differently which could be addressed following their guideline at: https://huggingface.co/docs/transformers/installation?highlight=transformers_cache#cache-setup

**Comment by hankcs** [comment]
HanLP model sizes range from 10MB to 1GB, many of them won't fit in PyPI's quota ([the default size limit on PyPI is 60MB](https://www.dampfkraft.com/code/distributing-large-files-with-pypi.html#:~:text=Just%20Distribute%20the%20Data,of%20the%20package%20after%20compression.)).

**Comment by tx0c** [comment]
sounds like reasonable :+1:
