### ISSUE TITLE
我在跑hanlp.load(hanlp.pretrained.mtl.CLOSE_TOK_POS_NER_SRL_DEP_SDP_CON_ELECTRA_BASE_ZH) 的时候发现一个问题，循环跑第89次会出现这个报错，换了个高显存的显卡同样会出现，是cuda版本有限制吗

### ISSUE THREAD

**Issue by a1120235890** [hankcs/HanLP#1828]
./aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [385,0,0], thread: [124,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [385,0,0], thread: [125,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [385,0,0], thread: [126,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [385,0,0], thread: [127,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
2023-07-25 09:55:39,634 - ERROR - CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

ERROR 2023-07-25 09:55:39,634-1d: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

2023-07-25 09:55:39,634 - INFO - CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

INFO  2023-07-25 09:55:39,634-1d: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form when open a new issue.
