### ISSUE TITLE
find a category of words that HanLP can't tokenize well: 米蘭昆德拉 / 唐納德川普 / 米歇爾·奥巴馬 /etc

### ISSUE THREAD

**Issue by tx0c** [hankcs/HanLP#1829]
**Describe the bug**
find a category of words (外國人名) that HanLP can't tokenize well: 米蘭昆德拉 / 唐納德川普 / 米歇爾·奥巴馬 /etc

**Code to reproduce the issue**

```python
In [88]: tok = hanlp.load(hanlp.pretrained.tok.COARSE_ELECTRA_SMALL_ZH)
                                   
In [89]: tok(["米蘭昆德拉", "米蘭·昆德拉", "为什么余华说米兰·昆德拉是三流小说家？", "米蘭昆德拉", "唐納德川普", "米歇爾·奥巴馬"])
Out[89]: 
[['米蘭昆德拉'],
 ['米蘭·昆德拉'],
 ['为什么', '余华', '说', '米兰·昆德拉', '是', '三流', '小说家', '？'],
 ['米蘭昆德拉'],
 ['唐納德川普'],
 ['米歇爾·奥巴馬']]

In [84]: tok = hanlp.load(hanlp.pretrained.tok.FINE_ELECTRA_SMALL_ZH)
Downloading https://file.hankcs.com/hanlp/tok/fine_electra_small_20220615_231803.zip to /home/ubuntu/.hanlp/tok/fine_electra_small_20220615_231803.zip
100%  43.5 MiB   2.6 MiB/s ETA:  0 s [=============================================================]
Decompressing /home/ubuntu/.hanlp/tok/fine_electra_small_20220615_231803.zip to /home/ubuntu/.hanlp/tok
                                   
In [85]: tok(["米蘭昆德拉", "米蘭·昆德拉", "为什么余华说米兰·昆德拉是三流小说家？", "米蘭昆德拉", "唐納德川普", "米歇爾·奥巴馬"])
Out[85]: 
[['米蘭昆德拉'],
 ['米蘭·昆德拉'],
 ['为什么', '余华', '说', '米兰·昆德拉', '是', '三流', '小说家', '？'],
 ['米蘭昆德拉'],
 ['唐納德', '川普'],
 ['米歇爾·奥巴馬']]
```

**Describe the current behavior**
all names seem to be always not cut

**Expected behavior**
those foreign full names should be tokenized between their first name and last name, the FINE_ one seems be able to cut '唐納德' '川普' but not much better, many other foreign full names are still not cut

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version: 3.10
- HanLP version:

In [87]: hanlp.__version__
Out[87]: '2.1.0-beta.50'

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
According to the [fine-grained standard CTB](https://hanlp.hankcs.com/docs/annotations/tok/ctb.html#personal-name):

> 2.2.1 Personal name
Treat it as one word. Don’t give the internal structure unless there is a space between two names (in foreign alphabet).

> Ex:张胜利/NR,卡尔[Karl].马克斯[Maxx]/NR, John/NR Smith/NR.

So `FINE_ELECTRA_SMALL_ZH ` is mostly consistent with the standard except that `唐納德川普` should be `['唐納德川普']`. Nevertheless, any machine learning model makes errors and the error rate of `FINE_ELECTRA_SMALL_ZH` is ~1%.

**Comment by tx0c** [comment]
I'm comparing with another older parsing lib (jieba) which is able to cut names to 2 parts,

and I suggest HanLP should have a config let users decide to cut or not,

this has a large use cases, e.g. in search products, if an article has mentioned `米歇爾·奥巴馬` many times but never `奥巴馬` alone, at index'ing phase, it has no pre parsed `奥巴馬`,
when user can search by `奥巴馬` is better also match articles who contains `米歇爾·奥巴馬`

```python
In [91]: tok(["米蘭昆德拉", "米蘭·昆德拉", "为什么余华说米兰·昆德拉是三流小说家？", "米蘭昆德拉", "唐納德川普", "米歇爾·奥巴馬", "諸葛亮", "周恩来"])
Out[91]: 
[['米蘭昆德拉'],
 ['米蘭·昆德拉'],
 ['为什么', '余华', '说', '米兰·昆德拉', '是', '三流', '小说家', '？'],
 ['米蘭昆德拉'],
 ['唐納德川普'],
 ['米歇爾·奥巴馬'],
 ['諸葛亮'],
 ['周恩来']]
```

some chinese names are the same logic, if pre parsed contains only `諸葛亮先生` but user search by `諸葛` or `諸葛 & 先生`, we expect this should have a match


**Describe the current behavior**
people names always match a whole, and require an exact same match,

**Expected behavior**
expect can cut by first name last names separately;   if don't want it to be default, at least give users a config to decide cut or not:   cut `諸葛亮先生`  => `諸葛 & 亮 & 先生`

**Comment by tx0c** [comment]
and how about the foreign names `'米兰·昆德拉'` with a separator `·` should this be cut to 2 parts?

we expect it should have 2 parts of `米兰` & `昆德拉` then `昆德拉` can match this full name
