### ISSUE TITLE
NLPTokenizer不同语句分析的结果为什么会不同？

### ISSUE THREAD

**Issue by kingdeewang** [hankcs/HanLP#183]
List<Term> termList = NLPTokenizer.segment("张三是我哥哥");
 System.out.println(termList);

[张/q, 三/m, 是/vshi, 我/rr, 哥哥/n]

List<Term> termList = NLPTokenizer.segment("张三教授正在教授自然语言处理课程");
    	System.out.println(termList);

[张三/nr, 教授/nnt, 正在/d, 教授/v, 自然/n, 语言/n, 处理/vn, 课程/n]

**Comment by hankcs** [comment]
感谢反馈，有个参数设置得不好，已经做了调整
