### ISSUE TITLE
调用粗粒度分词API疑是存在内存泄漏？

### ISSUE THREAD

**Issue by Dynamsoft-Jerson** [hankcs/HanLP#1832]
**Describe the bug**
针对一批法律文书（民事判决书，文件大小从2k-10k不等），循环调用粗粒度分词API进行全文分词（CPU mode），发现内存会持续上涨，最终内存溢出。

**Code to reproduce the issue**

```python
import os
import hanlp
import time
import psutil

def batch_parse_info(root_path):
    tok_model = hanlp.load('COARSE_ELECTRA_SMALL_ZH')

    fs_list = os.listdir(root_path)
    for fs in fs_list:
        full_fs = root_path + os.sep + fs

        content = ''
        with open(full_fs, 'r', encoding='utf-8') as f:
            for line in f:
                content += line + '\n'

        process = psutil.Process()
        memory_info1 = process.memory_info()
        result = tok_model(content)
        memory_info = process.memory_info()

        print(f"Memory info：{memory_info1.rss/1024.0/1024.0} MB, {memory_info.rss/1024.0/1024.0} MB, {(memory_info.rss-memory_info1.rss)/1024.0/1024.0} MB")

if __name__ == '__main__':
    root_path = r'C:\Users\Jerson\MySource\anaconda\private-projects\data\final\liuyahaofile\民事判决书\原告'

    tm_beg = time.time()
    batch_parse_info(root_path)
    tm_end = time.time()
    
    print(f'Cost time: {tm_end-tm_beg}s')
```

**Describe the current behavior**

以下是部分日志：
Memory info：194.4296875 MB, 212.2265625 MB, 17.796875 MB
Memory info：212.2265625 MB, 212.35546875 MB, 0.12890625 MB
Memory info：212.35546875 MB, 213.3359375 MB, 0.98046875 MB
Memory info：213.3359375 MB, 214.21484375 MB, 0.87890625 MB
Memory info：214.21484375 MB, 215.55859375 MB, 1.34375 MB
Memory info：215.55859375 MB, 215.63671875 MB, 0.078125 MB
Memory info：215.63671875 MB, 216.0234375 MB, 0.38671875 MB
Memory info：216.0234375 MB, 216.02734375 MB, 0.00390625 MB
Memory info：216.02734375 MB, 216.03515625 MB, 0.0078125 MB
Memory info：216.03515625 MB, 216.0625 MB, 0.02734375 MB
Memory info：216.0625 MB, 216.06640625 MB, 0.00390625 MB
Memory info：216.06640625 MB, 216.0703125 MB, 0.00390625 MB
Memory info：216.0703125 MB, 216.0625 MB, -0.0078125 MB
Memory info：216.06640625 MB, 216.0703125 MB, 0.00390625 MB
Memory info：216.07421875 MB, 216.08203125 MB, 0.0078125 MB
Memory info：216.08203125 MB, 216.078125 MB, -0.00390625 MB
Memory info：216.078125 MB, 221.6015625 MB, 5.5234375 MB
Memory info：221.6015625 MB, 221.87890625 MB, 0.27734375 MB
Memory info：221.87890625 MB, 221.875 MB, -0.00390625 MB
Memory info：221.875 MB, 222.41015625 MB, 0.53515625 MB
Memory info：222.41015625 MB, 223.0 MB, 0.58984375 MB
Memory info：223.0 MB, 223.16015625 MB, 0.16015625 MB
Memory info：223.1640625 MB, 223.15625 MB, -0.0078125 MB
Memory info：223.15625 MB, 225.859375 MB, 2.703125 MB
Memory info：225.859375 MB, 225.6171875 MB, -0.2421875 MB
Memory info：225.6171875 MB, 225.37109375 MB, -0.24609375 MB
Memory info：225.37109375 MB, 225.36328125 MB, -0.0078125 MB
Memory info：225.3671875 MB, 225.37890625 MB, 0.01171875 MB
Memory info：225.37890625 MB, 225.390625 MB, 0.01171875 MB
Memory info：225.390625 MB, 225.41796875 MB, 0.02734375 MB
Memory info：225.42578125 MB, 227.04296875 MB, 1.6171875 MB
Memory info：227.046875 MB, 226.80078125 MB, -0.24609375 MB
Memory info：226.80078125 MB, 226.8125 MB, 0.01171875 MB
Memory info：226.8125 MB, 226.81640625 MB, 0.00390625 MB
Memory info：226.81640625 MB, 226.80859375 MB, -0.0078125 MB
Memory info：225.80859375 MB, 226.3125 MB, 0.50390625 MB
Memory info：226.3125 MB, 226.44140625 MB, 0.12890625 MB
Memory info：226.44140625 MB, 226.43359375 MB, -0.0078125 MB
Memory info：226.43359375 MB, 226.4375 MB, 0.00390625 MB
Memory info：226.4375 MB, 226.375 MB, -0.0625 MB
Memory info：226.375 MB, 226.58203125 MB, 0.20703125 MB
Memory info：226.58203125 MB, 226.73046875 MB, 0.1484375 MB
Memory info：226.73046875 MB, 226.71875 MB, -0.01171875 MB
Memory info：226.71875 MB, 226.734375 MB, 0.015625 MB
Memory info：226.734375 MB, 226.7265625 MB, -0.0078125 MB
Memory info：226.7265625 MB, 229.109375 MB, 2.3828125 MB
Memory info：229.109375 MB, 227.86328125 MB, -1.24609375 MB
Memory info：227.86328125 MB, 229.11328125 MB, 1.25 MB
Memory info：229.11328125 MB, 229.14453125 MB, 0.03125 MB
Memory info：229.14453125 MB, 228.89453125 MB, -0.25 MB
Memory info：228.89453125 MB, 228.90625 MB, 0.01171875 MB
Memory info：228.90625 MB, 228.90625 MB, 0.0 MB
Memory info：228.90625 MB, 228.91015625 MB, 0.00390625 MB
Memory info：228.91015625 MB, 230.1484375 MB, 1.23828125 MB
Memory info：230.1484375 MB, 230.1484375 MB, 0.0 MB
Memory info：230.1484375 MB, 230.16015625 MB, 0.01171875 MB
Memory info：230.16015625 MB, 230.171875 MB, 0.01171875 MB
Memory info：230.171875 MB, 229.9296875 MB, -0.2421875 MB
Memory info：229.9296875 MB, 229.9296875 MB, 0.0 MB
Memory info：229.9296875 MB, 229.94140625 MB, 0.01171875 MB
Memory info：229.94140625 MB, 229.9453125 MB, 0.00390625 MB
Memory info：229.9453125 MB, 231.2109375 MB, 1.265625 MB
Memory info：231.2109375 MB, 231.21484375 MB, 0.00390625 MB
Memory info：231.21484375 MB, 230.96484375 MB, -0.25 MB
Memory info：230.96484375 MB, 230.9765625 MB, 0.01171875 MB
Memory info：230.9765625 MB, 230.984375 MB, 0.0078125 MB
Memory info：230.984375 MB, 230.9765625 MB, -0.0078125 MB
Memory info：230.9765625 MB, 230.9765625 MB, 0.0 MB
Memory info：230.9765625 MB, 230.98046875 MB, 0.00390625 MB
Memory info：230.98046875 MB, 230.984375 MB, 0.00390625 MB
Memory info：230.984375 MB, 230.98046875 MB, -0.00390625 MB
Memory info：230.98046875 MB, 230.98046875 MB, 0.0 MB
Memory info：230.98046875 MB, 230.98046875 MB, 0.0 MB
Memory info：230.98046875 MB, 230.98046875 MB, 0.0 MB
Memory info：230.98046875 MB, 230.98046875 MB, 0.0 MB
Memory info：230.98046875 MB, 230.984375 MB, 0.00390625 MB
Memory info：230.984375 MB, 230.98828125 MB, 0.00390625 MB
Memory info：230.98828125 MB, 230.9921875 MB, 0.00390625 MB
Memory info：230.9921875 MB, 230.99609375 MB, 0.00390625 MB
Memory info：230.99609375 MB, 231.0 MB, 0.00390625 MB
Memory info：231.0 MB, 231.00390625 MB, 0.00390625 MB
Memory info：231.00390625 MB, 231.00390625 MB, 0.0 MB
Memory info：231.00390625 MB, 231.0078125 MB, 0.00390625 MB
Memory info：231.0078125 MB, 231.01171875 MB, 0.00390625 MB
Memory info：231.015625 MB, 231.015625 MB, 0.0 MB
Memory info：231.015625 MB, 231.0078125 MB, -0.0078125 MB
Memory info：231.0078125 MB, 231.01953125 MB, 0.01171875 MB
Memory info：231.01953125 MB, 231.0234375 MB, 0.00390625 MB
Memory info：231.0234375 MB, 231.0078125 MB, -0.015625 MB
Memory info：231.0078125 MB, 231.0078125 MB, 0.0 MB
Memory info：231.0078125 MB, 231.0078125 MB, 0.0 MB
Memory info：231.0078125 MB, 231.01171875 MB, 0.00390625 MB
Memory info：231.01171875 MB, 231.01953125 MB, 0.0078125 MB
Memory info：231.01953125 MB, 231.61328125 MB, 0.59375 MB
Memory info：231.61328125 MB, 231.62890625 MB, 0.015625 MB
Memory info：231.62890625 MB, 231.64453125 MB, 0.015625 MB
Memory info：231.64453125 MB, 231.64453125 MB, 0.0 MB
Memory info：231.64453125 MB, 231.65234375 MB, 0.0078125 MB
Memory info：231.65234375 MB, 231.640625 MB, -0.01171875 MB
Memory info：231.640625 MB, 232.265625 MB, 0.625 MB
Memory info：232.265625 MB, 232.28125 MB, 0.015625 MB
Memory info：232.28125 MB, 232.48828125 MB, 0.20703125 MB
Memory info：232.48828125 MB, 232.50390625 MB, 0.015625 MB
Memory info：232.50390625 MB, 232.26953125 MB, -0.234375 MB
Memory info：232.26953125 MB, 232.265625 MB, -0.00390625 MB
Memory info：232.265625 MB, 232.26171875 MB, -0.00390625 MB
Memory info：232.26171875 MB, 232.265625 MB, 0.00390625 MB
Memory info：232.265625 MB, 232.265625 MB, 0.0 MB
Memory info：232.265625 MB, 232.26953125 MB, 0.00390625 MB
Memory info：232.26953125 MB, 232.265625 MB, -0.00390625 MB
Memory info：232.265625 MB, 232.265625 MB, 0.0 MB

**Expected behavior**

内存较稳定，不会持续上涨

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10/ Linux version 5.10.102.1-microsoft-standard-WSL2
- Python version: 3.8.5
- HanLP version: 2.1.0b42. 也尝试升级到2.1.0b50，问题依旧

**Other info / logs**

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
不存在，你需要理解如下事实。其中列出了链接的都是文档已经介绍的。

1. transformer内存占用与输入文本的长度的平方成正比。
2. 众所周知，Transformer的输入有长度限制（通常是512）。幸运地是，HanLP的滑动窗口技巧完美地突破了该限制。只要你的内存（显存）足够，HanLP就可以处理无限长的句子：https://github.com/hankcs/HanLP/blob/doc-zh/plugins/hanlp_demo/hanlp_demo/zh/tok_stl.ipynb
3. Native API的输入单位为句子，需使用[多语种分句模型](https://github.com/hankcs/HanLP/blob/master/plugins/hanlp_demo/hanlp_demo/sent_split.py)或[基于规则的分句函数](https://github.com/hankcs/HanLP/blob/master/hanlp/utils/rules.py#L19)先行分句：https://github.com/hankcs/HanLP/tree/doc-zh#%E6%B5%B7%E9%87%8F%E7%BA%A7native-api

所以，你直接输入整篇文档的做法是错误的。你应该先分句，并且最好限制每个句子的最大长度不超过500，最后再传给模型。

**Comment by Dynamsoft-Jerson** [comment]
@hankcs 
问题补充：
1）我选择长度为440个字符（含中文汉字、数字、标点）的一个句子，循环跑粗粒度分词的Native API，内存依然会上涨，何解？
2）基于tok结果跑后续的pos或ner模型，输入的长度是按照原始字符数计算，还是按照分词后词的数量来评估是否达到transformers上限（512）

谢谢不吝指教！

**Comment by hankcs** [comment]
1. 这是由于PyTorch的缓存机制造成的：其中之一是对于每个输入长度，PyTorch都会缓存一个计算图。如果你对内存不增长要求很高，你可以试试：
   1. 定期调用`gc.collect()`，因为Python自身不会在你每个循环后一定去清理垃圾。
   2. 使用GPU做推理，并且使用`torch.cuda.empty_cache()`释放显存。
   3. 导出onnx，自己写推理。此时输入长度固定为一个值，对于长度小于该值的文本会造成计算浪费。
   4. 向PyTorch社区反馈：https://github.com/pytorch/pytorch/issues/68114
   5. 使用restful API。至少服务器上从未发生过GPU显存占用不可控的情况。
2. 按字符计算，同时最好预留一些盈余。比如有些韩文字符虽然是单个字符，但transformer会将其视作2个单位。
