### ISSUE TITLE
ViterbiSegment加载自定义词典时未正确替换DoubleArrayTrie

### ISSUE THREAD

**Issue by wxy929629** [hankcs/HanLP#1833]
**Describe the bug**
版本:1.8.4
触发代码: com/hankcs/hanlp/seg/Viterbi/ViterbiSegment.java 中的loadCustomDic(String customPath, boolean isCache)
测试用例:com/hankcs/hanlp/seg/SegmentTest.java
`    public void testExtendViterbi() throws Exception
    {
        HanLP.Config.enableDebug(false);
        String path = System.getProperty("user.dir") + "/" + "data/dictionary/custom/CustomDictionary.txt;" +
            System.getProperty("user.dir") + "/" + "data/dictionary/custom/全国地名大全.txt";
        path = path.replace("\\", "/");
        String text = "一半天帕克斯曼是走不出丁字桥镇的";
        Segment segment = HanLP.newSegment().enableCustomDictionary(false);
        Segment seg = new ViterbiSegment(path);
        System.out.println("不启用字典的分词结果：" + segment.seg(text));
        System.out.println("默认分词结果：" + HanLP.segment(text));
        seg.enableCustomDictionaryForcing(true).enableCustomDictionary(true);
        List<Term> termList = seg.seg(text);
        System.out.println("自定义字典的分词结果：" + termList);
    }`

测试结果:
`不启用字典的分词结果：[一半/mq, 天/qt, 帕克斯曼/nrf, 是/vshi, 走/v, 不/d, 出/vf, 丁字/nz, 桥镇/ns, 的/ude1]
默认分词结果：[一半天/nz, 帕克斯曼/nrf, 是/vshi, 走/v, 不/d, 出/vf, 丁字/nz, 桥镇/ns, 的/ude1]
自定义字典的分词结果：[一半天/nz, 帕克斯曼/nrf, 是/vshi, 走/v, 不/d, 出/vf, 丁字/nz, 桥镇/ns, 的/ude1]`

全国地名大全.txt中是包含'丁字桥镇'词条的
![image](https://github.com/hankcs/HanLP/assets/27196120/fdd19809-3bbc-476c-834e-15d035eda78c)

```python
```

**Describe the current behavior**
在ViterbiSegment类中的, loadCustomDic(String customPath, boolean isCache)方法, 调用DynamicCustomDictionary.loadMainDictionary(mainPath, path, dat, isCache, config.normalization);构建dat完成后并未替换原本的
DoubleArrayTrie, 导致分词并未使用加载的词典

**Expected behavior**
 '丁字桥镇'词应该被正确切出

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- Python version:
- HanLP version:1.8.4

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [ ] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

开源项目维护不易，HanLP用户以十万计，而主要维护者只有我一人。我有自己的full-time研究工作，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
