### ISSUE TITLE
ViterbiSegment加载自定义词典时未正确替换DoubleArrayTrie

### ISSUE THREAD

**Issue by wxy929629** [hankcs/HanLP#1834]
**Describe the bug**
ViterbiSegment加载自定义词典时未正确替换DoubleArrayTrie

**Code to reproduce the issue**
com/hankcs/hanlp/seg/Viterbi/ViterbiSegment.java
```java
    private void loadCustomDic(String customPath, boolean isCache)
    {
        if (TextUtility.isBlank(customPath))
        {
            return;
        }
        logger.info("开始加载自定义词典:" + customPath);
        DoubleArrayTrie<CoreDictionary.Attribute> dat = new DoubleArrayTrie<CoreDictionary.Attribute>();
        String path[] = customPath.split(";");
        String mainPath = path[0];
        StringBuilder combinePath = new StringBuilder();
        for (String aPath : path)
        {
            combinePath.append(aPath.trim());
        }
        File file = new File(mainPath);
        mainPath = file.getParent() + "/" + Math.abs(combinePath.toString().hashCode());
        mainPath = mainPath.replace("\\", "/");
        DynamicCustomDictionary.loadMainDictionary(mainPath, path, dat, isCache, config.normalization);
    }
```
com/hankcs/hanlp/seg/SegmentTest.java
```java
    public void testExtendViterbi() throws Exception
    {
        HanLP.Config.enableDebug(false);
        String path = System.getProperty("user.dir") + "/" + "data/dictionary/custom/CustomDictionary.txt;" +
            System.getProperty("user.dir") + "/" + "data/dictionary/custom/全国地名大全.txt";
        path = path.replace("\\", "/");
        String text = "一半天帕克斯曼是走不出丁字桥镇的";
        Segment segment = HanLP.newSegment().enableCustomDictionary(false);
        Segment seg = new ViterbiSegment(path);
        System.out.println("不启用字典的分词结果：" + segment.seg(text));
        System.out.println("默认分词结果：" + HanLP.segment(text));
        seg.enableCustomDictionaryForcing(true).enableCustomDictionary(true);
        List<Term> termList = seg.seg(text);
        System.out.println("自定义字典的分词结果：" + termList);
    }
```

**Describe the current behavior**
加载CustomDictionary.txt与全国地名大全.txt中, 应该包含'丁字桥镇'词条, 但实际的分词中并未切出
![image](https://github.com/hankcs/HanLP/assets/27196120/fa80c919-a984-446e-a2fa-bf03d27b5147)
![image](https://github.com/hankcs/HanLP/assets/27196120/f25fff1a-1e95-47aa-bc9a-f5957292fae1)

**Expected behavior**
'丁字桥镇'词条应被切出

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):macos 13.3.1 (a) (22E772610a)
- Python version: n/a
- HanLP version: 1.8.4

**Other info / logs**
com/hankcs/hanlp/seg/Viterbi/ViterbiSegment.java中的loadCustomDic(String customPath, boolean isCache)在加载完DoubleArrayTrie后应替换对应词典
![image](https://github.com/hankcs/HanLP/assets/27196120/fa42b9bf-77c4-4489-b07a-adb17772f8a3)

* [x] I've completed this form and searched the web for solutions.

**Comment by wxy929629** [comment]
详见https://github.com/hankcs/HanLP/pull/1835, 如有不足之处请指教, 感谢

**Comment by hankcs** [comment]
已经merge，感谢pr!
