### ISSUE TITLE
关于使用文档中dep、sdp的结果不明确

### ISSUE THREAD

**Issue by haorenyuan7777777** [hankcs/HanLP#1836]
dep的结果：[(4, 'ba'),
 (3, 'amod'),
 (4, 'nsubj'),
 (0, 'root'),
 (4, 'prep'),
 (7, 'nn'),
 (8, 'nn'),
 (9, 'lobj'),
 (13, 'dep'),
 (11, 'amod'),
 (13, 'nn'),
 (13, 'nn'),
 (14, 'nn'),
 (15, 'nn'),
 (16, 'nn'),
 (5, 'pobj'),
 (4, 'punct'),
 (19, 'advmod'),
 (20, 'amod'),
 (21, 'lobj'),
 (24, 'dep'),
 (23, 'amod'),
 (24, 'nn'),
 (25, 'nn'),
 (26, 'nsubj'),
 (4, 'conj'),
 (26, 'dobj'),
 (4, 'punct'),
 (35, 'dep'),
 (29, 'clf'),
 (35, 'prep'),
 (34, 'assmod'),
 (32, 'assm'),
 (31, 'pobj'),
 (4, 'conj'),
 (4, 'punct'),
 (4, 'cc'),
 (48, 'prep'),
 (40, 'advmod'),
 (42, 'amod'),
 (42, 'nn'),
 (43, 'nn'),
 (38, 'pobj'),
 (48, 'prep'),
 (47, 'assmod'),
 (45, 'assm'),
 (44, 'pobj'),
 (4, 'conj'),
 (48, 'dobj'),
 (4, 'punct'),
 (52, 'nn'),
 (53, 'nsubj'),
 (4, 'conj'),
 (53, 'rcomp'),
 (56, 'nn'),
 (57, 'nn'),
 (53, 'dobj'),
 (4, 'punct'),
 (60, 'nsubj'),
 (4, 'conj'),
 (60, 'dobj'),
 (60, 'punct'),
 (60, 'conj'),
 (63, 'ccomp'),
 (64, 'dobj'),
 (4, 'punct')]
 
但是在文档中我没有找到列表中的每一个元祖中的数字的含义，同样的，还包括sdp的结果中的数字。希望可以在文档中更新对应的说明。

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

开源项目维护不易，HanLP用户以十万计，而主要维护者只有我一人。我有自己的full-time研究工作，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
