### ISSUE TITLE
希望可以增加自定义词典功能，对于分错的词语可以人为纠正。

### ISSUE THREAD

**Issue by haorenyuan7777777** [hankcs/HanLP#1837]
**Describe the feature and the current behavior/state.**
目前没有发现存在自定义词典的功能。在一些特定场景中，如：螺栓紧固，会被分词为 螺栓、紧、固。但是在该场景中，我们更希望得到螺栓、紧固。
**Will this change the current api? How?**
也许需要增加一个add_word()接口去实现该功能。
**Who will benefit with this feature?**
每一个使用hanlp并希望hanlp能越来越好的人都会获益。
**Are you willing to contribute it (Yes/No):**
力有不逮
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Dedian
- Python version: 3.7.4
- HanLP version: 2.1.0b50

**Any other info**
no
* [x] I've carefully completed this form.

**Comment by zZZ-github-life** [comment]
有的呀，自定义词典

**Comment by hankcs** [comment]
https://github.com/hankcs/HanLP/blob/doc-zh/plugins/hanlp_demo/hanlp_demo/zh/tok_stl.ipynb
