### ISSUE TITLE
load PMT1_DEP_ELECTRA_SMALL 时报错

### ISSUE THREAD

**Issue by ChiuHsin** [hankcs/HanLP#1843]
================================ERROR LOG BEGINS================================
OS: Windows-10-10.0.19041-SP0
Python: 3.8.11
PyTorch: 1.9.1+cpu
HanLP: 2.1.0-beta.50
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
d:\PycharmProjects\mednlp_project\mednlp_train\mishu_entity_extract.ipynb 单元格 64 in ()
      1 import hanlp
      3 HanLP = hanlp.pipeline() \
      4     .append(hanlp.utils.rules.split_sentence, output_key='sentences') \
      5     .append(hanlp.load('FINE_ELECTRA_SMALL_ZH'), output_key='tok') \
      6     .append(hanlp.load('CTB9_POS_ELECTRA_SMALL'), output_key='pos') \
      7     .append(hanlp.load('MSRA_NER_ELECTRA_SMALL_ZH'), output_key='ner', input_key='tok') \
----> 8     .append(hanlp.load('PMT1_DEP_ELECTRA_SMALL', conll=0), output_key='dep', input_key='tok')\
      9     .append(hanlp.load('CTB9_CON_ELECTRA_SMALL'), output_key='con', input_key='tok')

File d:\ProgramData\Anaconda3\envs\mednlp\lib\site-packages\hanlp\__init__.py:43, in load(save_dir, verbose, **kwargs)
     41     from hanlp_common.constant import HANLP_VERBOSE
     42     verbose = HANLP_VERBOSE
---> 43 return load_from_meta_file(save_dir, 'meta.json', verbose=verbose, **kwargs)

File d:\ProgramData\Anaconda3\envs\mednlp\lib\site-packages\hanlp\utils\component_util.py:186, in load_from_meta_file(save_dir, meta_filename, transform_only, verbose, **kwargs)
    184 except:
    185     pass
--> 186 raise e from None

File d:\ProgramData\Anaconda3\envs\mednlp\lib\site-packages\hanlp\utils\component_util.py:106, in load_from_meta_file(save_dir, meta_filename, transform_only, verbose, **kwargs)
    104 else:
    105     if os.path.isfile(os.path.join(save_dir, 'config.json')):
...
    459     if not _raise_exceptions_for_missing_entries:

OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like hfl/chinese-electra-180g-small-discriminator is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
=================================ERROR LOG ENDS=================================

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

开源项目维护不易，HanLP用户以十万计，而主要维护者只有我一人。我有自己的full-time研究工作，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
