### ISSUE TITLE
TransformerNamedEntityRecognizerTF 无法识别data的max_seq_length #1845

### ISSUE THREAD

**Issue by xiajing10** [hankcs/HanLP#1846]
**Describe the bug**
TransformerNamedEntityRecognizerTF 无法给输入的data按照max_seq_length分开，总是读了开头就将后续数据全部报错超出max_seq_length。经过比较transformer_ner里的TransformerNamedEntityRecognizer，怀疑是缺少build_dataset TSVTaggingDataset和TSVTaggingDataset。

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
import hanlp
from hanlp.components.ner.ner_tf import TransformerNamedEntityRecognizerTF

recognizer = TransformerNamedEntityRecognizerTF()
save_dir = 'data/model/ner/finetune_ner_bert-base-chinese_msra'
CONLL03_RESUME_TRAIN="train.tsv"
CONLL03_RESUME_TEST="val.tsv"
recognizer.fit(CONLL03_RESUME_TRAIN, CONLL03_RESUME_TEST, save_dir,
                epochs=10,
                adam_epsilon=1e-6,
                warmup_steps=0.1,
                weight_decay=0.01,
                word_dropout=0.1,  
                max_seq_len=1024,
                char_level=True,
                hard_constraint=True,
                transformer='bert-base-chinese',
                finetune=hanlp.pretrained.ner.MSRA_NER_BERT_BASE_ZH,
                seed=0)
```

**Describe the current behavior**
WARNING Input tokens [...] exceed the max sequence length of 126. The exceeded part will be truncated and ignored. You are recommended to split your long text into several sentences within 126 tokens beforehand.

数据以tsv形式读取后没有在后续进行split。

**Expected behavior**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):MacOS
- Python version:3.9
- HanLP version:2.1.0b50

**Other info / logs**
no

* [] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

开源项目维护不易，HanLP用户以十万计，而主要维护者只有我一人。我有自己的full-time研究工作，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
