### ISSUE TITLE
" unpack (expected 4, got 3)" from HanLP(['XXXXX']) 运行错误

### ISSUE THREAD

**Issue by 1558359609** [hankcs/HanLP#1850]
**Describe the bug**
在本地运行SDP语义依存分析模型时候出现了bug

**Code to reproduce the issue**

```python
import hanlp
import torch

xx=hanlp.pretrained.sdp.SEMEVAL15_PSD_BIAFFINE_EN
HanLP = hanlp.load(xx,devices=torch.device('cpu')) 
HanLP(['abc def ghk'])
```

**Describe the current behavior**
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
[d:\Projects\vscode\oj\oj1.ipynb](file:///D:/Projects/vscode/oj/oj1.ipynb) Cell 3 line 6
      [4](vscode-notebook-cell:/d%3A/Projects/vscode/oj/oj1.ipynb#W3sZmlsZQ%3D%3D?line=3) xx=hanlp.pretrained.sdp.SEMEVAL1[5](vscode-notebook-cell:/d%3A/Projects/vscode/oj/oj1.ipynb#W3sZmlsZQ%3D%3D?line=4)_PSD_BIAFFINE_EN
      5 HanLP = hanlp.load(xx,devices=torch.device('cpu')) 

**Expected behavior**
----> [6](vscode-notebook-cell:/d%3A/Projects/vscode/oj/oj1.ipynb#W3sZmlsZQ%3D%3D?line=5) HanLP(['abc def ghk'])

File [c:\Users\dongyuwu\.conda\envs\hanlp\lib\site-packages\hanlp\common\component.py:36](file:///C:/Users/dongyuwu/.conda/envs/hanlp/lib/site-packages/hanlp/common/component.py:36), in Component.__call__(self, *args, **kwargs)
     25 def __call__(self, *args, **kwargs):
     26     """
     27     A shortcut for :func:`~hanlp.common.component.predict`.
     28 
   (...)
     34 
     35     """
---> 36     return self.predict(*args, **kwargs)

File [c:\Users\dongyuwu\.conda\envs\hanlp\lib\site-packages\hanlp\common\keras_component.py:479](file:///C:/Users/dongyuwu/.conda/envs/hanlp/lib/site-packages/hanlp/common/keras_component.py:479), in KerasComponent.predict(self, data, batch_size, **kwargs)
    477 data_is_list = isinstance(data, list)
    478 print(dataset)
--> 479 for idx, batch in enumerate(dataset):
    480     samples_in_batch = tf.shape(
    481         batch[-1] if isinstance(batch[-1], tf.Tensor) else batch[-1][0])[0]
    482     if data_is_list:
...

ValueError: not enough values to unpack (expected 4, got 3)

	 [[{{node PyFunc}}]] [Op:IteratorGetNext] name:

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version:3.8.18
- HanLP version:  2.1.0b51

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
https://github.com/hankcs/HanLP/blob/doc-zh/plugins/hanlp_demo/hanlp_demo/en/demo_sdp.py#L11
