### ISSUE TITLE
无法下载CTB9_POS_ELECTRA_SMALL_TF

### ISSUE THREAD

**Issue by quokka007** [hankcs/HanLP#1852]
**Describe the bug**
无法下载CTB9_POS_ELECTRA_SMALL_TF，似乎是下载连接失效了。
[HanLP文档](https://hanlp.hankcs.com/docs/api/hanlp/pretrained/pos.html)提供的下载链接：https://file.hankcs.com/hanlp/pos/pos_ctb_electra_small_20211227_121341.zip

**Code to reproduce the issue**

```python
pos = hanlp.load(hanlp.pretrained.pos.CTB9_POS_ELECTRA_SMALL_TF)
```

**Describe the current behavior**
无法下载，提示<HTTPError 500: 'Internet error'>

**Expected behavior**
正常下载

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version:
- HanLP version:

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
已经重新上传。
感谢反馈，已经修复，请检查上面的commit是否解决了这个问题。
如果还有问题，欢迎重开issue。

**Comment by quokka007** [comment]
已经解决了，十分感谢！
