### ISSUE TITLE
有个词语分的有误

### ISSUE THREAD

**Issue by ljwps** [hankcs/HanLP#186]
2016-4-12 16:18:00 com.hankcs.hanlp.dictionary.CoreDictionary load
信息: 核心词典开始加载:data/dictionary/CoreNatureDictionary.mini.txt
2016-4-12 16:18:00 com.hankcs.hanlp.dictionary.CoreDictionary <clinit>
信息: data/dictionary/CoreNatureDictionary.mini.txt加载成功，85585个词条，耗时265ms
粗分词网：
0:[ ]
1:[江, 江苏]
2:[苏]
3:[句]
4:[容, 容人]
5:[人]
6:[ ]

2016-4-12 16:18:00 com.hankcs.hanlp.dictionary.CoreBiGramTableDictionary <clinit>
信息: 开始加载二元词典data/dictionary/CoreNatureDictionary.ngram.mini.txt.table
2016-4-12 16:18:00 com.hankcs.hanlp.dictionary.CoreBiGramTableDictionary <clinit>
信息: data/dictionary/CoreNatureDictionary.ngram.mini.txt.table加载成功，耗时156ms
2016-4-12 16:18:00 com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
信息: 自定义词典开始加载:data/dictionary/custom/CustomDictionary.txt
2016-4-12 16:18:00 com.hankcs.hanlp.dictionary.CustomDictionary <clinit>
信息: 自定义词典加载成功:83911个词条，耗时313ms
粗分结果[江苏/ns, 句/q, 容人/v]
2016-4-12 16:18:00 com.hankcs.hanlp.dictionary.common.CommonDictionary load
信息: 加载值data/dictionary/person/nr.txt.value.dat成功，耗时33ms
2016-4-12 16:18:00 com.hankcs.hanlp.dictionary.common.CommonDictionary load
信息: 加载键data/dictionary/person/nr.txt.trie.dat成功，耗时31ms
2016-4-12 16:18:01 com.hankcs.hanlp.dictionary.nr.PersonDictionary <clinit>
信息: data/dictionary/person/nr.txt加载成功，耗时313ms
人名角色观察：[  A 22202445 ][江苏 K 3 L 1 ][句 K 3 L 1 ][容人 A 22202445 ][  A 22202445 ]
人名角色标注：[ /A ,江苏/K ,句/K ,容人/A , /A]
江苏/ns
句/q
容人/v

照道理：应该分词成  江苏、句容、人  或者  江苏、句容人

**Comment by hankcs** [comment]
请使用非mini模型，或者将 句容 加入自定义词典即可。

[江苏/ns, 句容/ns, 人/n]
