### ISSUE TITLE
中文名包含多音字时生成的拼音只有一个，例如 ‘李娜’ 生成拼音为 ‘Li Nuo’

### ISSUE THREAD

**Issue by syw-dreamland** [hankcs/HanLP#1862]
**Describe the bug**
中文名包含多音字时生成的拼音只有一个，例如 ‘李娜’ 生成拼音为 ‘Li Nuo’

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Win10

- HanLP version:1.7.8

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
https://github.com/hankcs/HanLP/blob/18e5c7a1ae1337a92af6529f64168993990b3286/src/main/java/com/hankcs/hanlp/dictionary/py/PinyinDictionary.java#L134
