### ISSUE TITLE
执行open_small.py时报'utf-8' codec can't decode byte 0xb4 in position 0: invalid start byte

### ISSUE THREAD

**Issue by hiking-coder** [hankcs/HanLP#1863]
作者大大，本人小白在尝试使用hanlp2.1执行train的demo时，一直卡在导入from hanlp.datasets.ner.msra import 导入数据这关，然后也搜索了您论坛上的解决方案，如下设置
![image](https://github.com/hankcs/HanLP/assets/83748516/edcee08e-536b-48c8-8ddf-32f34b4c7307)
但还是一直执行后报如下错误
![image](https://github.com/hankcs/HanLP/assets/83748516/23378c60-744d-4dfe-a609-63855fff44d9)

请问是什么原因呢，先感谢大佬了

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
Hi, please refer to the doc: https://github.com/hankcs/HanLP/blob/2ab077001c7a08d7a9ac51e77d9b8603fdb16fa1/docs/api/hanlp/datasets/index.md#L12
