### ISSUE TITLE
Add a custom dictionary type that supports spaces

### ISSUE THREAD

**Issue by wallezhang** [hankcs/HanLP#1866]
**Describe the feature and the current behavior/state.**

Currently, custom dictionary can't contain spaces because the segmentation is based on spaces. It is recommended to add a custom dictionary in a format that uses commas to split word, word type, and word frequency.

**Will this change the current api? How?**

No.

**Who will benefit with this feature?**

Users who need to include spaces in their custom dictionaries will benefit from this.

**Are you willing to contribute it (Yes/No):**

Yes.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): All system.
- Python version: N/A
- HanLP version: Portable-1.8.4

**Any other info**

None.

* [x] I've carefully completed this form.

**Comment by wallezhang** [comment]
I think a new custom dictionary type can be added to ensure that users using older versions can still use custom dictionaries separated by spaces.

**Comment by hankcs** [comment]
Hi, .csv and .tsv have already been implemented:

https://github.com/hankcs/HanLP/blob/1323221c38e9188b19cef3f770eec40148a459ac/src/main/java/com/hankcs/hanlp/dictionary/DynamicCustomDictionary.java#L235

You can just go ahead and rename your dic to these extensions.

**Comment by wallezhang** [comment]
> Hi, .csv and .tsv have already been implemented:
> 
> https://github.com/hankcs/HanLP/blob/1323221c38e9188b19cef3f770eec40148a459ac/src/main/java/com/hankcs/hanlp/dictionary/DynamicCustomDictionary.java#L235
> 
> You can just go ahead and rename your dic to these extensions.

Ok, thanks for your reply. I'll try it.
