### ISSUE TITLE
Hanlp2.x版本的本地调用（依存句法分析）问题

### ISSUE THREAD

**Issue by PKQZPC** [hankcs/HanLP#1868]
关于依存句法分析，我在本地尝试了不同的 HanLP 2.x 版本，包括单任务和多任务的不同版本，然而，我发现本地部署的输出结果与在线演示存在较大差异。我想了解一下，在线版本对应的是本地部署的哪一种版本或搭配？另外，我希望得到一些建议，以便通过本地部署实现与在线演示相同的效果。

谢谢！

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

开源项目维护不易，HanLP用户以十万计，而主要维护者只有我一人。我有自己的full-time研究工作，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
