### ISSUE TITLE
如何设置替换匹配

### ISSUE THREAD

**Issue by kingdeewang** [hankcs/HanLP#187]
我现在在自定义字段中设置了“中国好声音第一季”为音乐专辑类型， 我想后面无论是“中国好声音第二季”还是“中国好声音第三季”等等都可以识别为音乐专辑类型，这个该如何去做？

**Comment by hankcs** [comment]
正则

**Comment by kingdeewang** [comment]
你好，能否详细说明一下？

**Comment by intohole** [comment]
就是你自己写规则去匹配， 现在没有这么智能的算法，去实现你说的功能
