### ISSUE TITLE
portable 1.8.4的更新 请尽快推到portable分支 现在分支上还是1.8.3

### ISSUE THREAD

**Issue by XenoAmess** [hankcs/HanLP#1872]
**Describe the feature and the current behavior/state.**
1.8.3
**Will this change the current api? How?**
no
**Who will benefit with this feature?**
everyone
**Are you willing to contribute it (Yes/No):**
yes but can't
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version:
- HanLP version:
1.8.4
**Any other info**

* [x] I've carefully completed this form.

**Comment by hankcs** [comment]
Done.
