### ISSUE TITLE
cpu docker安装时候会装cuda环境

### ISSUE THREAD

**Issue by cpla13** [hankcs/HanLP#1881]
![image](https://github.com/hankcs/HanLP/assets/37918873/d0b247a8-6e06-4096-893c-05330c825b93)
FROM python:3.8.16
WORKDIR /home/byze

COPY hanlp2 /home/byze/hanlp2
COPY static /home/byze/static
COPY model /home/byze/model
ENV  HANLP_HOME=/home/byze/model
RUN mkdir work
RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip --no-cache-dir install hanlp fastapi==0.94.1 uvicorn  cn_clip python-multipart boto3

ENTRYPOINT ["python", "-u", "./hanlp2/ner_app.py"]
CMD ["test"]

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form when open a new issue.
