### ISSUE TITLE
cpu docker部署安装依赖cuda环境

### ISSUE THREAD

**Issue by cpla13** [hankcs/HanLP#1883]
cpu docker部署安装依赖cuda环境
image

Code to reproduce the issue
![image](https://github.com/hankcs/HanLP/assets/37918873/cc8ddaf1-4ec0-4178-be77-fa052b9f825a)

FROM python:3.8.16
WORKDIR /home/byze

COPY hanlp2 /home/byze/hanlp2
COPY static /home/byze/static
COPY model /home/byze/model
ENV HANLP_HOME=/home/byze/model
RUN mkdir work
RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip --no-cache-dir install hanlp fastapi==0.94.1 uvicorn  python-multipart boto3

ENTRYPOINT ["python", "-u", "./hanlp2/ner_app.py"]
CMD ["test"]

System information

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): centos7.9
Python version: 3.8.16
HanLP version: 2.1

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
1. 是pytorch觉得你的系统依赖cuda，不是HanLP依赖cuda。HanLP只依赖pytorch，pytorch说它依赖什么就依赖什么，HanLP不参与决策。
2. 你可以在装HanLP之前，先装一个CPU版的pytorch
