### ISSUE TITLE
悄悄地问：分词模型能否“理解”语意？

### ISSUE THREAD

**Issue by wencan** [hankcs/HanLP#1884]
```
*&%￥#%￥……&（每次还要打的不一样，我也是不容易啊）
```
上面一段文本
使用 https://hanlp.hankcs.com/demos/tok.html 分词
把 “打的”分做了一个词
“打的”，在日常生活中好像仅仅是指搭乘出租车。这段文本显然与此无关。

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
1. 分词任务就是初步地理解语义，详见[《自然语言处理入门》](http://nlp.hankcs.com/book.php)
2. 不需要悄悄地问，目前分词准确率在0.98左右，也就是平均一百个单词，可能有一两个错误
3. 这个案例已经修复了，请重试

**Comment by wencan** [comment]
@hankcs 
请教
是如何“修复”？
微调？ 微调是否会导致原本正确的分词出错？

**Comment by hankcs** [comment]
对，微调。第二个问题需要统计基础才能理解。详见[《自然语言处理入门》](http://nlp.hankcs.com/book.php)，GitHub仅受理bug。
