### ISSUE TITLE
phraseTree引发的import error

### ISSUE THREAD

**Issue by oasis-0927** [hankcs/HanLP#1885]
**Describe the bug**
python3.9+中将cgi.escape 移除，修改为html.escape ，新版本的nltk库中已经进行修改，但是由于本项目引用的是没有进行相关修改的phraseTree，因此在python 3.9+的环境中使用pretty_print方法会报错。

是否可以尝试将phraseTree都统一替换为nltk.tree 来解决此问题。

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
import hanlp
from hanlp_common.document import Document


def merge_pos_into_con(doc: Document):
	flat = isinstancse(doc['pos'][0], str)
	if flat:
		doc = Document((k, [v]) for k, v in doc.items())
	for tree, tags in zip(doc['con'], doc['pos']):
		offset = 0
		for subtree in tree.subtrees(lambda t: t.height() == 2):
			tag = subtree.label()
			if tag == '_':
				subtree.set_label(tags[offset])
			offset += 1
	if flat:
		doc = doc.squeeze()
	return doc


con = hanlp.load('CTB9_CON_FULL_TAG_ELECTRA_SMALL')
tok = hanlp.load(hanlp.pretrained.tok.COARSE_ELECTRA_SMALL_ZH)
pos = hanlp.load(hanlp.pretrained.pos.CTB9_POS_ELECTRA_SMALL)
nlp = hanlp.pipeline().append(pos, input_key='tok', output_key='pos') \
	.append(con, input_key='tok', output_key='con')
doc = nlp(tok=["2021年", "HanLPv2.1", "带来", "最", "先进", "的", "多", "语种", "NLP", "技术", "。"])['con']
doc.pretty_print()
```

**Describe the current behavior**
A clear and concise description of what happened.

**Expected behavior**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version:
- HanLP version:

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
![image](https://github.com/hankcs/HanLP/assets/29737578/49fdf6aa-4e0c-4892-aff0-692cf2a61a4a)

* [] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

开源项目维护不易，HanLP用户以十万计，而主要维护者只有我一人。我有自己的full-time研究工作，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
