### ISSUE TITLE
Python调用hanlp如何将HanLP.properties放图classpath中。

### ISSUE THREAD

**Issue by mjc0819** [hankcs/HanLP#189]
这是项目文档说明：最后将HanLP.properties放入classpath即可，对于任何项目，都可以放到src或resources目录下，编译时IDE会自动将其复制到classpath中。

我的IDE是eclipse。请问python项目，应该将HanLP.properties放在哪里，怎么放入classpath中~

**Comment by mjc0819** [comment]
我的IDE是eclipse

**Comment by hankcs** [comment]
照做即可：http://www.hankcs.com/nlp/python-calls-hanlp.html

**Comment by mjc0819** [comment]
这个上面是这样写的：其中，依存句法分析模型不包含在hanlp-portable.jar中，必须下载data后通过hanlp.properties关联，详见项目文档。
项目文档这样写的：这是项目文档说明：最后将HanLP.properties放入classpath即可，对于任何项目，都可以放到src或resources目录下，编译时IDE会自动将其复制到classpath中。
但不会具体怎么放到classpath中。我将HanLP.properties的路径指向DATA父目录了。然后将它和hanlp.jar放在同一个文件夹里面。请问还需要怎么做才算放入classpath中了~多谢啦~

**Comment by mjc0819** [comment]
我再描述一下我的情况吧，不好意思，我是刚开始用，觉得您这个工具真心不错，请谅解一下。我将HanLP.properties和hanlp-1.2.9.jar一起放在C:\hanlp下，将data和src放在C:\hanlpp路径下。已经将HanLP.properties的root改为C:/hanlpp/，可是用句法分析，还是会报错。jpype._jexception.ExceptionPyRaisable: java.lang.Exception: Class com.hankcs.hanlp.HanLP not found

**Comment by hankcs** [comment]
最关键的是在这里设置：

startJVM(getDefaultJVMPath(), "-Djava.class.path=C:\hanlp\hanlp-1.2.8.jar;C:\hanlp", "-Xms1g", "-Xmx1g")

请检查：
0. 路径放对了吗？
0. 版本号对上了吗？

**Comment by mjc0819** [comment]
startJVM(getDefaultJVMPath(), "-Djava.class.path=C:\hanlp\hanlp-1.2.9.jar;C:\hanlp", "-Xms1g", "-Xmx1g")
这是我的设置。其它功能能用，就是句法依存这种需要用data包的不行。版本都是用的1.2.9最新的。

**Comment by hankcs** [comment]
这个跟data应该没有关系，因为你的报错是
 java.lang.Exception: Class com.hankcs.hanlp.HanLP not found

而不是data找不到

**Comment by hankcs** [comment]
你应该贴一下调用代码

**Comment by mjc0819** [comment]
哦不好意思。刚开始是路径配置出问题。现在改对后，报错为：
Traceback (most recent call last):
  File "C:\Users\牟俊超\workspace\asd\123.py", line 37, in <module>
    print(HanLP.parseDependency("徐先生还具体帮助他确定了把画雄鹰、松鼠和麻雀作为主攻目标。"))
jpype._jexception.LinkageErrorPyRaisable: java.lang.ExceptionInInitializerError

**Comment by mjc0819** [comment]
from jpype import startJVM,getDefaultJVMPath,JClass,shutdownJVM
 
startJVM(getDefaultJVMPath(), "-Djava.class.path=C:\hanlp\hanlp-1.2.9.jar;C:\hanlp", "-Xms1g", "-Xmx1g")
HanLP = JClass('com.hankcs.hanlp.HanLP')

# 中文分词
print(HanLP.segment('你好，欢迎在Python中调用HanLP的API'))
testCases = [
    "商品和服务",
    "结婚的和尚未结婚的确实在干扰分词啊",
    "买水果然后来世博园最后去世博会",
    "中国的首都是北京",
    "欢迎新老师生前来就餐",
    "工信处女干事每月经过下属科室都要亲口交代24口交换机等技术性器件的安装工作",
    "随着页游兴起到现在的页游繁盛，依赖于存档进行逻辑判断的设计减少了，但这块也不能完全忽略掉。"]
for sentence in testCases: 
    print(HanLP.segment(sentence))
# 命名实体识别与词性标注
NLPTokenizer = JClass('com.hankcs.hanlp.tokenizer.NLPTokenizer')
print(NLPTokenizer.segment('新奥公司拟出资7.5亿美元（约合人民币49.06亿元）收购联信创投的100%股权。'))
# 关键词提取
document = "水利部水资源司司长陈明忠9月29日在国务院新闻办举行的新闻发布会上透露，" \
           "根据刚刚完成了水资源管理制度的考核，有部分省接近了红线的指标，" \
           "有部分省超过红线的指标。对一些超过红线的地方，陈明忠表示，对一些取用水项目进行区域的限批，" \
           "严格地进行水资源论证和取水许可的批准。"
print(HanLP.extractKeyword(document, 2))
# 自动摘要
print(HanLP.extractSummary(document, 3))
# 依存句法分析

print(HanLP.parseDependency("徐先生还具体帮助他确定了把画雄鹰、松鼠和麻雀作为主攻目标。"))
shutdownJVM()

**Comment by hankcs** [comment]
你可能在用32位Windows，win32不支持大内存的jvm

**Comment by mjc0819** [comment]
我特点确认了一下。我用的是64位的WINDOWS 7。为什么会这样TT

**Comment by hankcs** [comment]
内存是否在4g以上？

**Comment by yesseecity** [comment]
請教一下，在ubuntu:16.10 (Docker的容器內)上 不使用IDE，發現下面問題 這該如何解？
1.  "-Djava.class.path=/root/tid_home/myProject/python/hanLP/hanlp-1.3.2/hanlp-1.3.2.jar"
command line 回應：
>嚴重: 没有找到HanLP.properties，可能会导致找不到data
>(中間略過)
>现在HanLP将尝试从/root/tid_home/myProject/python/hanLP读取data……
>(後面略過)

2. 改成 "-Djava.class.path=/root/tid_home/myProject/python/hanLP/hanlp-1.3.2/hanlp-1.3.2.jar;/root/tid_home/myProject/python/hanLP/hanlp-1.3.2/"
回應:
>Traceback (most recent call last):
>  File "hanLP-demo.py", line 11, in <module>
>    HanLP = JClass('com.hankcs.hanlp.HanLP')
>  File "/usr/local/lib/python2.7/dist-packages/JPype1-0.6.2-py2.7-linux-x86_64.egg/jpype/_jclass.py", line 55, in JClass
>    raise _RUNTIMEEXCEPTION.PYEXC("Class %s not found" % name)
jpype._jexception.RuntimeExceptionPyRaisable: java.lang.RuntimeException: Class com.hankcs.hanlp.HanLP not found

3. 我發現 "-Djava.class.path=/root/tid_home/myProject/python/hanLP/hanlp-1.3.2/hanlp-1.3.2.jar;"
多一個分號就會出現跟第2點一樣的問題

資料放置如下
/root/tid_home/myProject/python/hanLP/hanLP-demo.py 
/root/tid_home/myProject/python/hanLP/hanlp-1.3.2/data/
/root/tid_home/myProject/python/hanLP/hanlp-1.3.2/hanlp-1.3.2.jar

指行用指令
> python /root/tid_home/myProject/python/hanLP/hanLP-demo.py

**Comment by yesseecity** [comment]
自解：
> "-Djava.class.path=/root/tid_home/myProject/python/hanLP/hanlp-1.3.2/hanlp-1.3.2.jar:/root/tid_home/myProject/python/hanLP/hanlp-1.3.2/"
把「;」換成「:」

**Comment by guduxingzou** [comment]
亲测，路径一定要放在C:\hanlp下，不要放到其他文件夹下，否则会报错！

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。

**Comment by ferdinand4366** [comment]
说一下我遇到这个问题后的解决方案：首先hanlp.properties、hanlp-1.7.8.jar和hanlp-1.7.8-sources.jar这三个文件是要放在你的项目下，可以在工程下新建个类似src的文件夹放进去，然后配置classpath，其实就是这条命令`startJVM(getDefaultJVMPath(),
         "-Djava.class.path=E:/pythonstudy/src/hanlp-1.7.8.jar;E:/pythonstudy/src",
         "-Xms1g",
         "-Xmx1g")`
这里的pythonstudy是我的工程文件，src是我新建用来放资源文件的
至于data文件放在哪是随意的，只要注意路劲下不要有中文，然后将路劲修改到hanlp.properties中就行
