### ISSUE TITLE
无法加载ner预训练模型

### ISSUE THREAD

**Issue by gzh5425** [hankcs/HanLP#1894]
**Describe the bug**
标题：加载ner_bert_base_msra模型时出错

内容：
我在尝试加载HanLP中的`ner_bert_base_msa_20211227_114712.zip`模型时遇到了问题。我可以成功加载其他如MTL的模型，但是加载此NER模型时报错。以下是我的环境配置和错误日志：

- 操作系统：Windows-10-10.0.22631-SP0
- Python版本：3.10.11
- PyTorch版本：2.3.0+cpu
- TensorFlow版本：2.16.1
- HanLP版本：2.1.0-beta.57

Failed to load https://file.hankcs.com/hanlp/ner/ner_bert_base_msra_20211227_114712.zip
If the problem still persists, please submit an issue to https://github.com/hankcs/HanLP/issues
When reporting an issue, make sure to paste the FULL ERROR LOG below.
================================ERROR LOG BEGINS================================
OS: Windows-10-10.0.22631-SP0
Python: 3.10.11
PyTorch: 2.3.0+cpu
TensorFlow: 2.16.1
HanLP: 2.1.0-beta.57
An error occurred: module 'keras._tf_keras.keras.layers' has no attribute 'AbstractRNNCell'

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

import hanlp
import pandas as pd

def identify_chinese_names(text, ner_model):

    try:
        text = str(text)
        entities = ner_model(text)
        names = [entity[0] for entity in entities if entity[1] == 'NR']
        return names
    except Exception as e:
        print(f"Error processing text: {e}")
        return []

def main():
    try:

        NER = hanlp.load(hanlp.pretrained.ner.MSRA_NER_BERT_BASE_ZH)
        file_path = 'D:\\datas\\clan_relationship_pop_FDI\\names01.csv'
        data = pd.read_csv(file_path)

        data['investor'] = data['investor'].astype(str)

        data['names'] = data['investor'].apply(lambda x: identify_chinese_names(x, NER))

        output_path = 'D:\\datas\\clan_relationship_pop_FDI\\names02.csv'
        data.to_csv(output_path, index=False)
        print("处理完成，输出文件已保存至:", output_path)
    except Exception as e:
        print(f"An error occurred: {e}")

if __name__ == '__main__':
    main()

```python
```

**Describe the current behavior**
A clear and concise description of what happened.
我在尝试加载HanLP中的`ner_bert_base_msa_20211227_114712.zip`模型时遇到了问题。我可以成功加载其他如MTL的模型，但是加载此NER模型时报错。以下是我的环境配置和错误日志：
**Expected behavior**
我希望利用hanlp识别大量字符串中的人物姓名。

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows-10-10.0.22631-SP0
- Python version: 3.10.11
- HanLP version: 2.1.0-beta.57

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Failed to load https://file.hankcs.com/hanlp/ner/ner_bert_base_msra_20211227_114712.zip
If the problem still persists, please submit an issue to https://github.com/hankcs/HanLP/issues
When reporting an issue, make sure to paste the FULL ERROR LOG below.
================================ERROR LOG BEGINS================================
OS: Windows-10-10.0.22631-SP0
Python: 3.10.11
PyTorch: 2.3.0+cpu
TensorFlow: 2.16.1
HanLP: 2.1.0-beta.57
An error occurred: module 'keras._tf_keras.keras.layers' has no attribute 'AbstractRNNCell'

* [ ] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

开源项目维护不易，HanLP用户以十万计，而主要维护者只有我一人。我有自己的full-time研究工作，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
