### ISSUE TITLE
多gpu 分词报错

### ISSUE THREAD

**Issue by zhangfan-algo** [hankcs/HanLP#1895]
![image](https://github.com/hankcs/HanLP/assets/47747764/9f1862da-6816-4d1e-aa3b-89665f2551bd)

**Comment by zhangfan-algo** [comment]
使用的是这个 模型 hanlp.load(hanlp.pretrained.tok.MSR_TOK_ELECTRA_BASE_CRF,devices=[0,1,2,3,4,5,6,7])

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form when open a new issue.
