### ISSUE TITLE
zip下载不了

### ISSUE THREAD

**Issue by QLinfeng** [hankcs/HanLP#1896]
**Describe the bug**
Downloading https://file.hankcs.com/hanlp/tok/fine_electra_small_20220615_231803.zip to /root/.hanlp/tok/fine_electra_small_20220615_231803.zip
Download failed due to SSLError(MaxRetryError("HTTPSConnectionPool(host='file.hankcs.com', port=443): Max retries exceeded with url: /hanlp/tok/fine_electra_small_20220615_231803.zip (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1007)')))")).
Please re-try or download it to /root/.hanlp/tok/fine_electra_small_20220615_231803.zip by yourself with:

        wget https://file.hankcs.com/hanlp/tok/fine_electra_small_20220615_231803.zip -O /root/.hanlp/tok/fine_electra_small_20220615_231803.zip

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
HanLP = hanlp.pipeline() \
    .append(hanlp.utils.rules.split_sentence, output_key='sentences') \
    .append(hanlp.load('FINE_ELECTRA_SMALL_ZH'), output_key='tok') \
    .append(hanlp.load('CTB9_POS_ELECTRA_SMALL'), output_key='pos') \
    .append(hanlp.load('MSRA_NER_ELECTRA_SMALL_ZH'), output_key='ner', input_key='tok') \
    .append(hanlp.load('CTB9_DEP_ELECTRA_SMALL', conll=0), output_key='dep', input_key='tok')\
    .append(hanlp.load('CTB9_CON_ELECTRA_SMALL'), output_key='con', input_key='tok')
HanLP('2021年HanLPv2.1为生产环境带来次世代最先进的多语种NLP技术。阿婆主来到北京立方庭参观自然语义科技公司。')
```python
```

**Describe the current behavior**
A clear and concise description of what happened.
zip下载不了，在电脑上试了也不行
**Expected behavior**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version:3.10
- HanLP version:2.1.0b57

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [x] I've completed this form and searched the web for solutions.

**Comment by QLinfeng** [comment]
地址改了，亲测下面这个可以
`https://ftp.hankcs.com/hanlp`

**Comment by hankcs** [comment]
感谢反馈，已经修复。
如果还有问题，欢迎重开issue。
