### ISSUE TITLE
今天运行hanlp的时候显示的是服务器维护中，请刷新重试。

### ISSUE THREAD

**Issue by hjh0915** [hankcs/HanLP#1897]
**Describe the bug**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
```

**Describe the current behavior**
A clear and concise description of what happened.

**Expected behavior**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version:
- HanLP version:

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [x] I've completed this form and searched the web for solutions.

**Comment by webSue** [comment]
如果你是调用在线restful api，我理解这是正常现象？我之前调用时也会碰到

**Comment by hankcs** [comment]
感谢反馈，已经恢复服务。
