### ISSUE TITLE
ViterbiSegment对应短词语辨识问题

### ISSUE THREAD

**Issue by timlincool** [hankcs/HanLP#19]
请问ViterbiSegment对应短词语辨识不佳,是不是跟训练语料是长文章有关？

例如 可乐、年货  这些词 会分成 [可 ,乐]  ,[年 , 货]
在CoreNatureDictionary.txt 已经有出现   可乐、年货 
但CoreNatureDictionary.ngram.txt 里没有 
可乐@末##末
年货@末##末

这些有比较优雅的方式解决吗？ 还是必须添加语料至CoreNatureDictionary.ngram.txt ?

**Comment by hankcs** [comment]
感谢反馈，以前我也注意到这个问题，但是一直没有找到很好的方法解决，以下可供参考：

0. 在有```乐@末##末 5```的情况下，没有```可乐@末##末```会造成可乐没有竞争力。2014人民日报语料库大，但似乎造成了模型的过拟合。
0. 换用mini词典可以暂时解决这个问题。
0. 调整com/hankcs/hanlp/utility/Predefine.java的平滑因子，使得两个节点的代价一定比一个大。

目前采用了第3种方法，最佳参数还有待测试。
