### ISSUE TITLE
简繁转换分歧词识别某些情况下转换错误

### ISSUE THREAD

**Issue by JaynLeaew** [hankcs/HanLP#190]
今天在使用HanLP在做简繁转换的时候发现有如下分歧词识别错误：
"宏安地产" -> "巨集安地產"
"香港联交所主板IPO上市" -> "香港聯交所主機板IPO上市"

这明显是有问题的，我用chinese-utils的转换就是正确的，望修复

**Comment by hankcs** [comment]
感谢反馈，已经修复。

目前的简繁词典是写爬虫从百度抓取的，可能没有旧版那么好。你可以使用1.2.5及以前的版本：https://github.com/hankcs/HanLP/blob/v1.2.5/data/dictionary/tc/TraditionalChinese.txt
