### ISSUE TITLE
词性标注的'单任务'示例中关于自定义词典的部分结果与预期不符

### ISSUE THREAD

**Issue by Codedcy** [hankcs/HanLP#1903]
**Describe the bug**
在词性标注的'单任务'示例中关于自定义词典的部分结果与预期不符：
![image](https://github.com/user-attachments/assets/cf96cf11-953d-41ff-8a5d-fac25ef6fe2c)
完全按照示例中的代码运行，'Hanlp'的自定义词性标注未生效，本地尝试过后发现中文的自定义词性可以生效，英文的自定义词性没有生效

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
import hanlp
hanlp.pretrained.pos.ALL # 语种见名称最后一个字段或相应语料库
pos = hanlp.load(hanlp.pretrained.pos.CTB9_POS_ELECTRA_SMALL)
pos(["我", "的", "希望", "是", "希望", "张晚霞", "的", "背影", "被", "晚霞", "映红", "。"])
print(pos.dict_tags)
pos.dict_tags = {'HanLP': 'state-of-the-art-tool'}
pos(["HanLP", "为", "生产", "环境", "带来", "次", "世代", "最", "先进", "的", "多语种", "NLP", "技术", "。"])
```

**Describe the current behavior**
为'HanLP'设置的词性：'state-of-the-art-tool' 未生效，分词结果中,'HanLP'的词性为'NR'

**Expected behavior**
分词结果中，'HanLP'的词性应该为'state-of-the-art-tool'

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): google colab 在线环境 Ubuntu 22.04.3
- Python version: 3.10
- HanLP version: 2.1

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
感谢反馈，已经修复，请检查上面的commit是否解决了这个问题。
如果还有问题，欢迎重开issue。
