### ISSUE TITLE
IndexError: index out of range in self

### ISSUE THREAD

**Issue by dalinautoagents** [hankcs/HanLP#1916]
测试数据：
`{"data":["ートピック冬はとても塞くなりますあなたの国にはどんな季節がありますか？竹的国家有邸季帝?春は桜の毛が咲きます季節の特徴を理解することができる。ご08能理解各季帝的特点。在看迅介韶日本四季的短后L3- 1STheJapan Foundationートピック季飾と天気冬はとても寒くなります警贈を聞きましょう。清忻禄音。自本を紹介する映像を見ています。竹正在看不介韶日本的祝叛。たくさん根多学校初級Ｌ3-2STheJapan Foundationートピック季節と天気冬はとても寒くなります初級Ｌ3- 3STheJapan Foundationートピック季節と天気冬はとても寒くなりますど09会話を聞きましょう。清忻対活。(1それぞれの臼の季節は、а-ｄのどれですか。(２もういちど聞きましょう。ートピック季節と天気3冬はとても寒くなります皆分の歯の義節について話しましょう。脱脱自己国家的季帝帖。会話を聞きましょう。(103-09)03-1003-11清忻対活。03003-11(２シャドーイングしましよう。03-10清眼速。自分のÈや住んでいるところの季節について話し(３しましょう。脱脱自己国家或自己住的地方的季帝帖。  ', '<table>\n<tr><td  >冬はとても寒くなります</td></tr>\n<tr><td  >薫解スクリプト</td></tr>\n<tr><td  >春は桜の花が咲きます</td></tr>\n<tr><td  >0)03-03 暑はの毛が咲きます。 暖かくなります。</td></tr>\n<tr><td  >梅雨は静がたくさん降ります。 じめじめしています。</td></tr>\n<tr><td  >賢は暑いです。 セミが鳴きます。 弊義が休みになります。</td></tr>\n<tr><td  >萩はすずしくなります。 もみじがきれいです。 姿は寒いです。 雪が降ります。</td></tr>\n<tr><td  >2 どんな義節がありますか？</td></tr>\n<tr><td  >0)03-05 Ａ：ジョーイさんの歯には、 どんな義節がありますか？ Ｂょちゃ準単費です。</td></tr>\n<tr><td  >A：そうですか。</td></tr>\n<tr><td  rowspan=6 >2 90-c0( Ａ：タムさんの国には、 どんな季節がありますか？ Ｂ：雨季と乾季があります。 A：そうですか。 Ｂ：乾季はとても暑いです。 A：ヘ-. Ｂ：でも、 雨季は歩しすずしくなります。 静がたくさん降ります。</td></tr>\n\n\n\n\n\n<tr><td  >Ａ：バヤルさんの歯には、</td></tr>\n</table>  "]}
`
版本：hanlp==2.1.0-beta.61
模型：tok_mul

依然报上面的错

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

开源项目维护不易，HanLP用户以十万计，而主要维护者只有我一人。我有自己的full-time研究工作，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
