### ISSUE TITLE
jar包中的CustomDictionary.txt和data-for-1.7.5.zip中的CustomDictionary.txt不一致

### ISSUE THREAD

**Issue by zhujiawen12345** [hankcs/HanLP#1921]
**Describe the bug**
jar包中的CustomDictionary.txt和data-for-1.7.5.zip中的CustomDictionary.txt不一致

**Code to reproduce the issue**

```     
        HanLP.Config.enableDebug();
        String text = "血洗天安门广场";
        System.out.println(HanLP.segment(text));
        CoreDictionary.Attribute attribute = CustomDictionary.get("天安门广场");
        System.out.println(attribute);

```

**Describe the current behavior**
对‘血洗天安门广场’进行分词，得到结果是[血洗/v, 天安门广场/nz]，经debug发现是自定义词典中存在‘天安门广场 nz 36’,这里为啥jar包中的CustomDictionary.txt和data-for-1.7.5.zip中的CustomDictionary.txt不一致？

**Expected behavior**
预期分词结果：[血洗/v, 天安门/ns, 广场/n]

同时我对比了演示地址的分词结果：
![image](https://github.com/user-attachments/assets/4b43983d-302d-4dfc-9aa6-10c9a008c2b8)

**System information**
- window11
- HanLP version:portable-1.8.4

**Other info / logs**
粗分词网：
0:[ ]
1:[血, 血洗]
2:[洗]
3:[天, 天安, 天安门]
4:[安]
5:[门]
6:[广, 广场]
7:[场]
8:[ ]

粗分结果[血洗/v, 天安门广场/nz]

人名角色观察：[  K 1 A 1 ][血洗 A 20833310 ][天安门广场 A 20833310 ][  K 1 A 1 ]
人名角色标注：[ /K ,血洗/A ,天安门广场/A , /A]
[血洗/v, 天安门广场/nz]

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
设计上没有commitment去让portable的数据与非portable的一模一样。

**Comment by zhujiawen12345** [comment]
我看了portal分支源码中的数据跟jar包中的数据也不一致
