### ISSUE TITLE
能否归档HanLP2.1.0b58

### ISSUE THREAD

**Issue by Skybluebluede** [hankcs/HanLP#1924]
**Describe the feature and the current behavior/state.**
开发者你好，我看到HanLP软件在pipy上已经更新到了2.1.0b62，但是在github上只更新到1.8.4，请问能不能将最新的beta版本代码归档在github上？我的组织要求引用开源代码或软件时必须保证合规可信，目前项目开发依赖于HanLP2.1.0b58，希望这个版本可以归档到github。
**Will this change the current api? How?**
no
**Who will benefit with this feature?**
everyone
**Are you willing to contribute it (Yes/No):**
yes
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version:3.11.4
- HanLP version:2.1.0b58

**Any other info**

* [x] I've carefully completed this form.

**Comment by hankcs** [comment]
可以。考虑到2.1.0b58已经是一个很旧的版本，我有几个更好的提议：

1. 我创建一个最新的2.1.0b62的release，包含代码归档。2.1.0b62相较于b58修复了至少4个bug，在接口上是完全兼容的，模型和准确率也一模一样。
2. 使用pypi上的代码归档：https://pypi.org/project/hanlp/2.1.0b58/#files 

我正在考虑未来在发布到pypi的时候自动在GitHub上创建一个release。

**Comment by Skybluebluede** [comment]
感谢！等待您的归档。

**Comment by hankcs** [comment]
已发布：https://github.com/hankcs/HanLP/releases/tag/v2.1.0-beta.62
