### ISSUE TITLE
项目启动后提示警告

### ISSUE THREAD

**Issue by yangfei4913438** [hankcs/HanLP#1925]
**Describe the bug**

**Describe the current behavior**
项目启动后，输出一行警告。

**Expected behavior**
按理说不应该出现这种警告。

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  MacOS 15.1
- Python version: 3.12.6
- HanLP version: 2.1.0b62

**Other info / logs**
/Users/xxx/.local/share/virtualenvs/neon_assistant-Ews7tDas/lib/python3.12/site-packages/hanlp/utils/io_util.py:28: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import parse_version

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
感谢反馈，已经修复，请检查上面的commit是否解决了这个问题。
如果还有问题，欢迎重开issue。
