### ISSUE TITLE
Failed to load https://file.hankcs.com/hanlp/ner/ner_bert_base_msra_20211227_114712.zip

### ISSUE THREAD

**Issue by River-liu-yun** [hankcs/HanLP#1926]
Failed to load https://file.hankcs.com/hanlp/ner/ner_bert_base_msra_20211227_114712.zip
If the problem still persists, please submit an issue to https://github.com/hankcs/HanLP/issues
When reporting an issue, make sure to paste the FULL ERROR LOG below.
================================ERROR LOG BEGINS================================
OS: Windows-10-10.0.26100-SP0
Python: 3.9.20
PyTorch: 2.1.2+cpu
TensorFlow: 2.13.1
HanLP: 2.1.0-beta.62
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Cell In[2], line 5
      1 import hanlp
      3 # 查看所有命名实体识别模型
      4 #print(hanlp.pretrained.ner.ALL)
----> 5 ner = hanlp.load(hanlp.pretrained.ner.MSRA_NER_BERT_BASE_ZH)
      6 sentences = [
      7    ['兰州', '银行', '2022', '年度报告', '特别', '重视', '绿色', '金融', '发展', '！', '通过', '多种', '绿色', '信贷', '产品', '支持', '环保', '项目', '。']]
      8 entities = ner(sentences, tasks='ner*')

File D:\anaconda3\envs\py39env\lib\site-packages\hanlp\__init__.py:43, in load(save_dir, verbose, **kwargs)
     41     from hanlp_common.constant import HANLP_VERBOSE
     42     verbose = HANLP_VERBOSE
---> 43 return load_from_meta_file(save_dir, 'meta.json', verbose=verbose, **kwargs)

File D:\anaconda3\envs\py39env\lib\site-packages\hanlp\utils\component_util.py:186, in load_from_meta_file(save_dir, meta_filename, transform_only, verbose, **kwargs)
    184 except:
    185     pass
--> 186 raise e from None

File D:\anaconda3\envs\py39env\lib\site-packages\hanlp\utils\component_util.py:106, in load_from_meta_file(save_dir, meta_filename, transform_only, verbose, **kwargs)
    104 else:
    105     if os.path.isfile(os.path.join(save_dir, 'config.json')):
--> 106         obj.load(save_dir, verbose=verbose, **kwargs)
    107     else:
    108         obj.load(metapath, **kwargs)

File D:\anaconda3\envs\py39env\lib\site-packages\hanlp\common\keras_component.py:215, in KerasComponent.load(self, save_dir, logger, **kwargs)
    213 self.load_config(save_dir)
    214 self.load_vocabs(save_dir)
--> 215 self.build(**merge_dict(self.config, training=False, logger=logger, **kwargs, overwrite=True, inplace=True))
    216 self.load_weights(save_dir, **kwargs)
    217 self.load_meta(save_dir)

File D:\anaconda3\envs\py39env\lib\site-packages\hanlp\common\keras_component.py:225, in KerasComponent.build(self, logger, **kwargs)
    223 def build(self, logger, **kwargs):
    224     self.transform.build_config()
--> 225     self.model = self.build_model(**merge_dict(self.config, training=kwargs.get('training', None),
    226                                                loss=kwargs.get('loss', None)))
    227     self.transform.lock_vocabs()
    228     optimizer = self.build_optimizer(**self.config)

File D:\anaconda3\envs\py39env\lib\site-packages\hanlp\components\taggers\transformers\transformer_tagger_tf.py:34, in TransformerTaggerTF.build_model(self, transformer, max_seq_length, **kwargs)
     33 def build_model(self, transformer, max_seq_length, **kwargs) -> tf.keras.Model:
---> 34     model, tokenizer = build_transformer(transformer, max_seq_length, len(self.transform.tag_vocab), tagging=True)
     35     self.transform.tokenizer = tokenizer
     36     return model

File D:\anaconda3\envs\py39env\lib\site-packages\hanlp\layers\transformers\loader_tf.py:11, in build_transformer(transformer, max_seq_length, num_labels, tagging, tokenizer_only)
     10 def build_transformer(transformer, max_seq_length, num_labels, tagging=True, tokenizer_only=False):
---> 11     tokenizer = AutoTokenizer_.from_pretrained(transformer)
     12     if tokenizer_only:
     13         return tokenizer

File D:\anaconda3\envs\py39env\lib\site-packages\hanlp\layers\transformers\pt_imports.py:65, in AutoTokenizer_.from_pretrained(cls, pretrained_model_name_or_path, use_fast, do_basic_tokenize)
     63 if use_fast and not do_basic_tokenize:
     64     warnings.warn('`do_basic_tokenize=False` might not work when `use_fast=True`')
---> 65 tokenizer = cls.from_pretrained(get_tokenizer_mirror(transformer), use_fast=use_fast,
     66                                 do_basic_tokenize=do_basic_tokenize,
     67                                 **additional_config)
     68 tokenizer.name_or_path = transformer
     69 return tokenizer

File D:\anaconda3\envs\py39env\lib\site-packages\transformers\models\auto\tokenization_auto.py:939, in AutoTokenizer.from_pretrained(cls, pretrained_model_name_or_path, *inputs, **kwargs)
    936 tokenizer_class_py, tokenizer_class_fast = TOKENIZER_MAPPING[type(config)]
    938 if tokenizer_class_fast and (use_fast or tokenizer_class_py is None):
--> 939     return tokenizer_class_fast.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
    940 else:
    941     if tokenizer_class_py is not None:

File D:\anaconda3\envs\py39env\lib\site-packages\transformers\tokenization_utils_base.py:2197, in PreTrainedTokenizerBase.from_pretrained(cls, pretrained_model_name_or_path, cache_dir, force_download, local_files_only, token, revision, trust_remote_code, *init_inputs, **kwargs)
   2194 # If one passes a GGUF file path to `gguf_file` there is no need for this check as the tokenizer will be
   2195 # loaded directly from the GGUF file.
   2196 if all(full_file_name is None for full_file_name in resolved_vocab_files.values()) and not gguf_file:
-> 2197     raise EnvironmentError(
   2198         f"Can't load tokenizer for '{pretrained_model_name_or_path}'. If you were trying to load it from "
   2199         "'https://huggingface.co/models', make sure you don't have a local directory with the same name. "
   2200         f"Otherwise, make sure '{pretrained_model_name_or_path}' is the correct path to a directory "
   2201         f"containing all relevant files for a {cls.__name__} tokenizer."
   2202     )
   2204 for file_id, file_path in vocab_files.items():
   2205     if file_id not in resolved_vocab_files:

OSError: Can't load tokenizer for 'bert-base-chinese'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'bert-base-chinese' is the correct path to a directory containing all relevant files for a BertTokenizerFast tokenizer.
=================================ERROR LOG ENDS=================================

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

开源项目维护不易，HanLP用户以十万计，而主要维护者只有我一人。我有自己的full-time研究工作，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
