### ISSUE TITLE
hanlp.load 出现illegal hardware instruction

### ISSUE THREAD

**Issue by Lucky759** [hankcs/HanLP#1928]
**Describe the bug**
在程序运行完hanlp.load()后，不再向下运行分词，而是停止了，并且没有报错信息

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
import hanlp
hanlp.pretrained.mtl.ALL # MTL多任务，具体任务见模型名称，语种见名称最后一个字段或相应语料库
HanLP = hanlp.load(hanlp.pretrained.mtl.CLOSE_TOK_POS_NER_SRL_DEP_SDP_CON_ELECTRA_BASE_ZH)
doc = HanLP(['2021年HanLPv2.1为生产环境带来次世代最先进的多语种NLP技术。', '阿婆主来到北京立方庭参观自然语义科技公司。'])
print(doc)
```

**Describe the current behavior**
A clear and concise description of what happened.
无任何打印结果

**Expected behavior**
正确打印分词结果

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  macos monterey 12.5
- Python version: 3.9.8
- HanLP version: 2.1.0b64

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
应该是你在M系列芯片的macos上安装了x64指令集的pytorch。建议安装arm指令集的python，然后安装hanlp。

**Comment by Lucky759** [comment]
> 应该是你在M系列芯片的macos上安装了x64指令集的pytorch。建议安装arm指令集的python，然后安装hanlp。

我已经通过`uname -m`检查过，安装的是arm64架构的python

**Comment by Lucky759** [comment]
确实是这个问题导致的，已经把电脑的python环境做了全面的清理，问题得到了解决，感谢！
