### ISSUE TITLE
非法指令

### ISSUE THREAD

**Issue by qiangzihome** [hankcs/HanLP#1930]
**Describe the bug**
hanlp Version: 2.1.0b64 ，Python Version: 3.8.20

import hanlp
tok = hanlp.load(hanlp.pretrained.tok.COARSE_ELECTRA_SMALL_ZH)
Downloading https://file.hankcs.com/hanlp/tok/coarse_electra_small_20220616_012050.zip to /root/.hanlp/tok/coarse_electra_small_20220616_012050.zip
100% 43.5 MiB 6.6 MiB/s ETA: 0 s [=============================================================]
Decompressing /root/.hanlp/tok/coarse_electra_small_20220616_012050.zip to /root/.hanlp/tok
非法指令

[root@localhost ~]# python
Python 3.8.20 (default, Dec 9 2024, 13:56:32)

import hanlp
tok = hanlp.load(hanlp.pretrained.tok.COARSE_ELECTRA_SMALL_ZH)
非法指令

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
```

**Describe the current behavior**
A clear and concise description of what happened.

**Expected behavior**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version:
- HanLP version:

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

 [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
https://github.com/hankcs/HanLP/issues/1928

**Comment by qiangzihome** [comment]
[root@localhost home]# cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)

用的是centos7 x86_64

**Comment by hankcs** [comment]
可能是你的CPU太旧了，不支持torch的某些新的intel加速指令。建议把torch的版本往下降级降到能用为止。
