### ISSUE TITLE
请问如何使已标注的复合词不被拆分

### ISSUE THREAD

**Issue by heiox** [hankcs/HanLP#1935]
**Describe the bug**
目前使用PERCEPTRON训练含有标注复合词的语料，sentence是选取自语料中含有复合词的一段，结果中复合词却没有被标注，并被拆分了。

语料部分内容示例：
[一次性/b 白勺/n]/n 1/m 箱/q
[中/a 马夹袋/n]/n 4/m 包/q

**Code to reproduce the issue**
```
PerceptronLexicalAnalyzer analyzer = new PerceptronLexicalAnalyzer(Config.PERCEPTRON_CWS_CUSTOM_MODEL_FILE, Config.PERCEPTRON_POS_CUSTOM_MODEL_FILE, Config.PERCEPTRON_NER_CUSTOM_MODEL_FILE);
analyzer.enableCustomDictionary(new DynamicCustomDictionary(CUSTOM_DICTIONARY_PATH));

Sentence sentenceResult = analyzer.analyze(sentence.replaceAll("\s+", “”));
sentenceResult.mergeCompoundWords();
log.info(sentenceResult.wordList.toString());
```

**Describe the current behavior**
输出结果：

> 一次性/b 白勺/n 1/m 箱/q 中/a 马夹袋/n 4/m 包/q

**Expected behavior**

> 一次性白勺/n 1/m 箱/q 中马夹袋/n 4/m 包/q

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS 15.2  
- HanLP version: portable-1.8.5

**Other info / logs**
none

* 

- [x]  I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
感知器机是一个随机算法,不保证一定100%拟合训练集。可尝试调参，或试试在线学习。

**Comment by heiox** [comment]
> 感知器机是一个随机算法,不保证一定100%拟合训练集。可尝试调参，或试试在线学习。

谢谢回复，我试过学习（一次性白勺 1 箱 中马夹袋 4 包）；也尝试过更改train函数的maxIteration=150（不过看输出Iter50左右后，accuracy就趋于稳定了，测试分词标注结果还是未标注复合词，就又改回50了），测试示例试过很多，结果都还是没标注出一个复合词。

`analyzer.getPerceptronSegmenter().learn("一次性白勺 1 箱 中马夹袋 4 包")`

**Comment by hankcs** [comment]
复合词是NER的结果，你应该把`n`加入到NER的`tagSet`里面去训练NER模型。
