### ISSUE TITLE
汉语转拼音功能，涉及到比较复杂的多音字 就不行了

### ISSUE THREAD

**Issue by jsl1992** [hankcs/HanLP#1937]
**Describe the bug**

引用maven，使用 
`
        <dependency>
            <groupId>com.hankcs</groupId>
            <artifactId>hanlp</artifactId>
            <version>portable-1.8.5</version>
        </dependency>
`

`
    public static void main(String[] args) {
        String text = "厦门行走";

        // 使用 HanLP 进行拼音转换，HanLP 会处理多音字
        String pinyin = HanLP.convertToPinyinString(text, "", true);

        System.out.println(pinyin);  // xiàmén xíngzǒu
        System.out.println(HanLP.convertToPinyinFirstCharString(text, "", true));
        System.out.println(HanLP.convertToPinyinString("人要是行，干一行行一行，一行行行行行。人要是不行，干一行不行一行，一行不行行行不行。", " ", false));
    }

`
输出不对
`
ren yao shi xing ， gan yi xing xing yi xing ， yi xing xing xing xing xing 。 ren yao shi bu xing ， gan yi xing bu xing yi xing ， yi xing bu xing xing xing bu xing 。
`

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
```

**Describe the current behavior**
A clear and concise description of what happened.

**Expected behavior**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version:
- HanLP version:

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
在`data/dictionary/pinyin/pinyin.txt`里加入`干一行行一行`等等的拼音就可以了。
