### ISSUE TITLE
在nr.txt中添加了"才会有 A 1"为什么他还被识别为nr

### ISSUE THREAD

**Issue by a741424975game** [hankcs/HanLP#194]
识别的文章如下：

　　原标题：“原来严肃的说教还可以这么接地气”
　　随着网络的急速发展，人们发现，网络文化不仅是当代文化的重要组成，更是当代文化的一大亮点，它还能很好地吸收、融合传统文化，从而转化出独特的、受到网络时代广大群众喜爱的新文化形式、文化产品。
　　顺应时代潮流，才能有所作为。北京市多年积极指导、鼓励属地主要网站传承优秀传统文化，打造多彩网络文化，并发挥组织作用，协调属地主要网站联手举办丰富的网络文化活动。市网信办相关负责人表示，建设网络文化，必须坚持正确导向，积极宣传正能量，传播党的主张。但是，党的理论路线、方针政策往往庄重严肃，宏观性、理论性强，其大众化、普及性传播是个难点。近年来，北京网信办与属地主要网站充分沟通、合作，先通过专家讲座、编辑培训等方式，帮助网站将党的政策主张“揉碎”、“吃透”，再通过共同策划，用网络语言、网络表达方式进行梳理、呈现，传播效果明显。
　　这样的例子比比皆是，2013年，由新浪微博倡议的“光盘行动”成为当年的十大新闻热词。从这次行动的操作中可以看出积极运用新的方式，开发出受到网络时代大众喜爱的文化产品的重要意义。当初新浪微博接到的宣传任务是“倡导节约型社会”。考虑到“节约”二字太宽泛，不便操作，新浪微博的编辑们经过头脑风暴，提出了“光盘行动”这个形象、生动又贴地气的口号。“光盘行动”一经推出迅速得到广泛认可。网民成为“自来水”，自发呼吁亲人朋友践行“光盘行动”，形成了良好的社会效应。
　　2014年社会主义核心价值观的宣传报道中，属地网站通过深入学习、理解，将社会主义核心价值观通过网络语言进行解读。搜狐网的专题“你读得懂的社会主义核心价值观”，用俏皮幽默的动漫形式，从网民熟悉的生活角度切入，展示社会主义核心价值观在国家、社会和家庭三个层面的价值目标和准则，使其适合不同的人群去接收、消化，那些往日看上去就高大上的理论，拉近了和普通人的距离。
　　2016年全国“两会”报道中，新浪网将H5与音频嵌入技术结合，推出“听，习近平说”、“强哥这一年都批评了谁”。中华网提炼政府工作报告中的民生红利，用“H5+微信红包”的形式推出“你有一个来自李克强的红包”。搜狐打造全景策划“跟着代表上两会”，传递代表委员声音。新浪微博与VR结合的两会微直播，带领网民近距离看两会。这些精彩的产品大多在社交媒体形成了“刷屏”的现象。
　　相关负责人介绍，在互联网上传播党的声音，应该当好转换器。要紧跟网络发展，勇于创新、注重实效，快速学习新媒体手段，鼓励网站放手干，运用网络思维，采用网络语言，表达口语化、接地气，巧妙融合图片、图表、漫画、动漫、视频、H5、音频等新媒体手段，确保传播实效，打造充满活力的鼠标文化、移动文化，才能在网民生活工作中起到实实在在的指导作用。有网民留言表示，原以为严肃的说教，还可以这么接地气。本版文/本报记者 李泽伟
　　（北京青年报）
责任编辑：赵家明 SN146
人总在追求圆满。事情要做得圆满，交友要交得圆满，文字要写得圆满。只有在感觉到圆满之时，才会有真正的喜乐。
近日，美国总统奥巴马抵达沙特开启他的“告别之旅”，而结果却是无比冷清。与以往沙特国王亲赴机场“迎来送往”相比，奥巴马此次沙特之行可谓“寒酸至极”。
给领导写讲话稿的机会，材料狗的一生只有两次机会，第一没写好的时候，领导会很客气地把你叫到办公室来，和颜悦色地对你说：“小同志，这篇文章还有很多许多需要斟酌的地方，你再回去改改。”
中国大陆房地产市场启动于上世纪90年代中后期。如果以最高转让期限70年计算，较早一批商品房，实际剩下50年左右。
Copyright 
1996-2016 SINA Corporation, All Rights Reserved
新浪公司

**Comment by hankcs** [comment]
请认真阅读文档：https://github.com/hankcs/HanLP#储存形式
