### ISSUE TITLE
CRF新词识别

### ISSUE THREAD

**Issue by lijianbo0130** [hankcs/HanLP#196]
这个方法一旦开启自定义词典就无法识别新词了么？
Segment segment = new CRFSegment();
segment.enableCustomDictionary(true);// 开启自定义词典
所以enableCustomDictionary()必须设置为false?
感觉这样有点不太合理啊。
我还要吐槽！！！！
感觉对数字和字母的识别意义不大。如：
public static void main(String[] args) {
        Segment segment = new CRFSegment();
        segment.enableCustomDictionary(false);// 开启自定义词典
        segment.enablePartOfSpeechTagging(true);
        List<Term> termList = segment.seg("    阿莫西林是"
                + "TJGP-2015-ZP-5722,"
                + "乐视超级手机能否承载贾布斯的生态梦 "
                + "停业整顿停业");
        System.out.println(termList);
        for (Term term : termList) {
            if (term.nature == null) {
                System.out.println("识别到新词：" + term.word);
            }
        }

```
}
```

结果：
识别到新词：  
识别到新词：阿莫西林
识别到新词：TJGP
识别到新词：-
识别到新词：2015
识别到新词：-
识别到新词：ZP
识别到新词：-
识别到新词：5722
识别到新词：,
识别到新词：贾布斯
识别到新词： 
识别到新词：停业

这些汉字的词，我觉得还行。但是这里各种非汉字都会被识别成新词。我觉得这个问题造成这个方法的可用性。大大降低啊。

我目前想做一个给很多新的文章，识别出文章里面新的词。
现有的方法：
使用过的方法。先分词，如果有一个一个的字没有成词。如：我的名字-李健博不会成任何词。就把他们组合起来。用HMM，或者CRF识别一下是不是新词。
优点：能够剔除上面[TJGP,2015]这样的词，召回应该是比较高的。
缺点：准确率低。大量的(实体名，尤其是人名，会混在里面)使得还需要大量人工。
创新方法：
用上面的方法和hanlp结合：
比如:李健博在hanlp中会被识别为人名，这样的词就不要了。
楼主觉得我这个创意咋样？因为我对hanlp不是太了解。所以希望楼主看一看这样做的可行性。
个人觉得hanlp的CRF方法很好，但是因为[TJGP,2015]这样的原因使得无法真正的投入使用，实在是十分可惜。

**Comment by hankcs** [comment]
感谢建议，最初设计CRF的确是准备主要用于新词识别的。后来有很多用户把CRF拿来做分词，抱怨为什么出来的词性是null，抱怨为什么不能用自定义词典，于是就改掉了。
等有空再重新设计新词识别的功能吧，在此之前你可以尝试：

0. 修改com.hankcs.hanlp.seg.CRF.CRFSegment#toVertexList 以避免null消失的问题。
0. 利用com.hankcs.hanlp.utility.TextUtility#isAllLetter 等方法过滤掉字母、标点等等

**Comment by lijianbo0130** [comment]
现在还是无法用自定义词典对么?

**Comment by hankcs** [comment]
0. 现在可以。两个功能放在一个模块里，只是没时间去设计而已。
0. 对。

**Comment by lijianbo0130** [comment]
好的，那我看下源码。自己试着修改一下。

**Comment by chenjun0210** [comment]
你好，大神，请教一下，现在这边已经将自定义词典与CRF结合在一起了吗？我这边想用来做新词识别功能。CRF通过词性为null来识别新词，其实是和主词典来匹配的是吧。可能识别出的新词却在自定义词典中是吧。这个现在能解决了吗？谢谢

**Comment by hankcs** [comment]
暂未实现，一点业务逻辑而已，大家写个子类就可以实现的吧。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
