### ISSUE TITLE
CRF识别的一个bug

### ISSUE THREAD

**Issue by lijianbo0130** [hankcs/HanLP#199]
代码：
		Segment segment = new CRFSegment();
		segment.enableCustomDictionary(false);// 开启自定义词典
		segment.enablePartOfSpeechTagging(true);
		List<Term> termList = segment.seg("更多采购");
		System.out.println(termList);
		for (Term term : termList) {
			if (term.nature == null) {
				System.out.println("识别到新词：" + term.word);
			}
		}

结果：
[更多/ad, 采购/null]
识别到新词：采购
但是采购这个词在词库中是存在的，并不是新词。

**Comment by hankcs** [comment]
感谢指正，已经修复。
