### ISSUE TITLE
能否提供1.对系统架构做一个详细的讲解 2.代码文件和算法原理对应关系

### ISSUE THREAD

**Issue by studyhs** [hankcs/HanLP#200]

**Comment by hankcs** [comment]
http://www.hankcs.com/nlp/

**Comment by studyhs** [comment]
网站上只有算法的讲解啊。。

**Comment by hankcs** [comment]
这是我在时间允许范围内能做的事情了。

**Comment by studyhs** [comment]
恩 又有谁的时间有那么多呢

**Comment by intohole** [comment]
真心赞 hackcs

2016-04-29 11:46 GMT+08:00 hs <notifications@github.com>:

**Comment by intohole** [comment]
嗯 有多时间多学啊 ， 大神写了那么多算法


2016-04-29 11:46 GMT+08:00 hs <notifications@github.com>:

**Comment by studyhs** [comment]
hankcs

**Comment by studyhs** [comment]
@intohole hankcs
