### ISSUE TITLE
例子中"只有自信的程序员才能把握未来"

### ISSUE THREAD

**Issue by lg003x** [hankcs/HanLP#205]
例子中"只有自信的程序员才能把握未来"，用MainPartExtractor提取主谓宾，结果是程序员才能把握未来，正确的结果应该是：程序员把握未来
是不是 "才能" 这个停用词没有启用，如果是，需要怎么启用。如果不是，请问问题出在哪？

**Comment by hankcs** [comment]
该项目与HanLP无关，并且已经不再维护。

**Comment by skiplai** [comment]
昨天刚好也在考虑这个问题，既然找到原因就说一下。希望hankcs不要介意

句法树:(ROOT [74.116]
  (IP
    (NP
      (CP
        (IP
          (VP
            (ADVP (AD 只))
            (VP (VE 有)
              (NP (NN 自信)))))
        (DEC 的))
      (NP (NN 程序员) (NN 才能)))
    (VP (VV 把握)
      (NP (NT 未来)))))

因为才能作为了名词，NN合并作为主语了。
把句子分词时改用TaggedWord，把词性标注也传入就可以解决。

**Comment by hankcs** [comment]
我不介意 那个项目没有用hanlp分词 也不想看斯坦福那堆杂乱的代码

**Comment by lg003x** [comment]
这个项目不是你写的？？






在 2016-05-13 21:21:54，"hankcs" <notifications@github.com> 写道：


我不介意 那个项目没有用hanlp分词 也不想看斯坦福那堆杂乱的代码

**Comment by lg003x** [comment]
https://github.com/hankcs/MainPartExtractor
   这不在你的项目下吗？






在 2016-05-13 21:21:54，"hankcs" <notifications@github.com> 写道：


我不介意 那个项目没有用hanlp分词 也不想看斯坦福那堆杂乱的代码

**Comment by hankcs** [comment]
用了斯坦福的库，详见lib，这是我不维护的原因之一。

**Comment by lg003x** [comment]
我已经去掉了斯坦福的相关代码了，都使用HanLP
主要是用了斯坦福的没事清楚，所以就一直不搞定，这才联系了您，望见谅
