### ISSUE TITLE
繁体分词

### ISSUE THREAD

**Issue by supercarl87** [hankcs/HanLP#206]
当前分词词典和模型好像都是基于简体中文的，效果不错。但是对于繁体中文,似乎效果不佳，即使加入一些词语，也还是会被当做简体中文出来。

```
    CustomDictionary.add("捷運站");
    CustomDictionary.add("臺北");

"臺北大眾捷運股份有限公司"
[臺/n, 北大/j, 眾/nz, 捷/j, 運/n, 股份有限公司/nis]
```

但是如果把文本转化为简体，分词就蛮不错的。

```
input = HanLP.convertToSimplifiedChinese(input);
[台北/ns, 大众/n, 轻轨/n, 股份有限公司/nis]
```
1. 是否有比较好的繁体词典推荐
2. 能否支持繁体中文分词（分词时候可以有繁体模型和简体模型）
3. 是否可以根据转化为简体的结果来分原来的句子（根据简体中文分词的位置）

**Comment by hankcs** [comment]
0. https://github.com/hankcs/HanLP/tree/master/data/dictionary/tc
0. https://github.com/hankcs/HanLP/blob/master/src/test/java/com/hankcs/demo/DemoTraditionalChineseSegment.java
0. 请仔细阅读文档

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
