### ISSUE TITLE
分词bug

### ISSUE THREAD

**Issue by bluedesire** [hankcs/HanLP#21]
对一片文本进行分词，发现会抛IllegalArgumentException异常，每次必现。不知道是什么原因，能解释一下吗？是我使用的方法不对吗？我跑了几千篇文章都没问题，只有这篇文章有问题。

测试文本：
　　昨日，陈燕和导盲犬到达雍和宫站准备换乘2号线。根据当天起实施的新规，导盲犬被允许乘坐地铁和火车。新京报记者 王贵彬 摄
　　 
　　地铁内一位小女孩见到导盲犬有些害怕，陈燕表示导盲犬很安全，“就是踩到它的脚，它也不会咬你。”新京报记者 王贵彬 摄
　　 
　　昨日，地铁西直门站，流动巡查的北京市轨道交通执法大队执法人员，胸前佩戴执法记录仪。
　　实习生 彭子洋 摄
　　轨道交通执法队执法首日未开罚单
　　《北京市轨道交通运营安全条例》实施，初期对乞讨卖艺以劝导为主；被拒11次导盲犬终乘地铁
　　新京报讯 实施首日，北京首支轨道交通执法队也于当天开始进地铁执法，当天并未开出罚单。交通执法部门相关负责人表示，法规实施前期以劝导为主。
　　最终目标：站均两名执法人员
　　根据《条例》规定，在地铁里乞讨、卖艺将被处以50元以上1000元以下罚款。在车站、车厢内派发广告等物品的，面临最高1万元的罚款。作为依照法规执法的北京市轨道交通执法大队昨天首次进地铁工作，当天上午，记者在西直门等地铁车站看到，在闸机处和换乘通道内，身着交通执法制服的执法人员两人一组流动巡查。
　　执法队相关负责人告诉记者，目前流动巡查对于发现违规的人员，可能首先进行劝导询问，一开始不会进行处罚。若出现严重情节，如不停止违法违规行为的，会采取强制措施以及处罚，“执法人员都要进行现场取证”。
　　据统计，轨道交通执法大队正式上岗的第一天，大队全员上岗，在兼顾地铁全线网的情况下，重点对1号线、2号线、4号线、5号线、10号线的70个重点车站进行监管，巡视车站97座，劝阻在地铁站内玩轮滑行为3起；劝阻摆摊小商贩4起；劝阻散发小广告1起；劝阻翻越闸机2起。
　　交通执法总队副总队长梁建伟介绍，轨道交通执法大队现正式编制共有88人，按照地铁运营公司管理范围分为5个中队，和一个专门负责应对重点车站重点时段或大客流冲击时安全保障的机动中队。
　　“我们的最终目标是318个站，平均每站两名执法人员”，梁建伟说，执法大队后续还会招聘人员辅助执法，同时借助地铁运营方为执法提供保障。
　　滑板车等或将禁入地铁
　　梁建伟介绍，执法队员职责包括对危害轨道交通设备设施安全的行为、危害轨道交通运营安全的行为及轨道交通相关单位不落实安全生产主体责任的行为实施行政处罚，其中有41项行政处罚，5项行政强制。
　　“法规实施前期，我们还是以劝阻为主。”梁建伟说，条例对在车站、车厢内乞讨卖艺、派发广告以及其他危害地铁安全的行为都有了规定，但实施上有具体问题，还需要制定细则来进一步明确，目前细则正在研究中，将于1个月到2个月内出台。
　　北京地铁运营公司相关负责人表示，《条例》中提到，在车站内禁止从事滑板、轮滑、自行车等运动。下一步，滑板、轮滑等运动器具可能禁止带入地铁。目前，有关禁带物品的目录相关部门还在进一步完善，之前允许带的大型工具等等，未来或列入违禁名单中。
　　■ 探访
　　乘客：打击乞讨不能仅靠罚款
　　昨日中午1时许，记者在地铁2号线宣武门站看到一位妇女拿着一个音箱，一边放音乐一边向乘客乞讨，一节车厢内，只有一位年轻的女乘客给了她1元钱。根据《北京市轨道交通运营安全条例》，对地铁乞讨卖艺等危害地铁运营安全的行为，轨道交通执法人员可实施行政处罚。
　　记者随后拨打了地铁车厢内贴着的北京地铁监督电话96165。得知是举报乞讨卖艺行为后，接线员询问了线路、车站、列车运行方向、所在车厢以及乞讨人员行进的方向等信息，并表示会马上联系车站工作人员。
　　“乞讨卖艺行为让人感到厌烦”，同车乘客谢女士表示，自己曾有过多次在地铁上睡着后被乞讨者吵醒的经历，但她同时认为对这些人员还是应以劝导为主。同车大多数乘客也认为，地铁中的乞讨行为一般都有组织，不处罚乞讨卖艺组织者，但靠罚款难以杜绝这样的行为。
　　此外，大多数乘客对于散发小广告“深恶痛绝”，称该行为使地铁车厢内环境脏乱。京港地铁安全部门负责人介绍，他们工作人员对地铁内散发小广告的行为只能劝阻，而不能没收他们的小广告。5月1日以后，有了条例的支持，会在这方面加强管理。
　　导盲犬珍妮终于“获准”乘地铁
　　此前被拒11次；《条例》明确视力残障者可携带导盲犬进站乘车
　　在经历了11次被拒绝以后，导盲犬珍妮昨天终于感受了一把北京地铁。此次《条例》明确，视力残障者可携带导盲犬进站乘车。
　　昨天上午，地铁5号线天通苑站，视障人士陈燕牵着导盲犬珍妮，来到地铁天通苑站，车站工作人员检查了视力残障证件、导盲犬证件后，向陈燕发放了福利票。
　　在工作人员引导下，陈燕和导盲犬顺利进站。站在带无障碍标志的候车门前，陈燕反复指一下标志，又拍一下珍妮的头，告诉它要记住这个位置。
　　嘀嘀嘀，地铁门打开，珍妮小心翼翼地走进车厢，它引导陈燕找到车厢接口处的空位置后停住，等陈燕站定后，珍妮静静的趴在脚边。车厢里其他乘客对导盲犬乘车非常感兴趣，但并没有人引逗，珍妮也丝毫没有躁动行为。5号线换乘2号线也有工作人员引导，这次，陈燕找到一个座位坐下，珍妮依旧卧在她脚边。
　　陈燕说，乘坐公共交通工具的能力，是导盲犬在训练时的必修课。珍妮昨天的表现很好，并没有对人群有恐惧感。她希望，通过这一次的实践，让更多人了解视力残障人士对公共出行的需求，了解导盲犬。目前全国“持证”的导盲犬也不过七八十只，北京市目前共有9只，市区有7只，郊区有2只。

代码如下：
		StringBuffer article = new StringBuffer();
		String line;
		try(BufferedReader out = new BufferedReader(new FileReader("C:/Users/huan.wang/Desktop/corpus.txt"))) {
			while((line = out.readLine()) != null) {
				article.append(line);
			}
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		List<Term> words = HanLP.segment(article.toString());
		for(Term w : words) {
			System.out.println(w);
		}

异常栈信息：
Exception in thread "main" java.lang.IllegalArgumentException: Illegal Capacity: -1
	at java.util.ArrayList.<init>(Unknown Source)
	at com.hankcs.hanlp.seg.WordBasedGenerativeModelSegment.convert(WordBasedGenerativeModelSegment.java:241)
	at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.segSentence(ViterbiSegment.java:114)
	at com.hankcs.hanlp.seg.Segment.seg(Segment.java:384)
	at com.hankcs.hanlp.tokenizer.StandardTokenizer.segment(StandardTokenizer.java:50)
	at com.hankcs.hanlp.HanLP.segment(HanLP.java:371)

**Comment by hankcs** [comment]
感谢反馈，已经复现。这是一个过度优化带来的Bug，影响1.2.2版本。在GitHub的最新代码中，不再会产生这个问题。解决方案如下：

0. 编译GitHub中的最新代码，替换1.2.2版
0. 使用mini词典

**Comment by hankcs** [comment]
或者升级到刚才发布的新版本：https://github.com/hankcs/HanLP/releases/tag/v1.2.3

**Comment by chenshayanluo** [comment]
对一篇含有“迈凯伦法拉利恩佐兰博基尼”、“迈凯伦塞纳迈凯伦卡宾”的文本采用标准分词时，分词的结果中包含这些长词。如果将这上述两个词连在一起，分词结果是两个词的结合。对于音译名的分词，连在一起的音译词会被当作一个词。是要用索引分词吗？
代码如下：
List<Term> termList1 = HanLp.segment("迈凯伦法拉利恩佐兰博基尼, 迈凯伦塞纳迈凯伦卡宾");
List<Term> termList2 = HanLp.segment("迈凯伦法拉利恩佐兰博基尼迈凯伦塞纳迈凯伦卡宾");
System.out.println(termList1);
System.out.println(termList2);
结果如下：
[迈凯伦法拉利恩佐兰博基尼/nrf, ，/w, 迈凯伦塞纳迈凯伦卡宾/nrf]
[迈凯伦法拉利恩佐兰博基尼迈凯伦塞纳迈凯伦卡宾/nrf]
