### ISSUE TITLE
关于机构识别

### ISSUE THREAD

**Issue by lijianbo0130** [hankcs/HanLP#210]
K,L,M,P,S,W这几个标注分别代表什么？我只找到了一部分的标注的意义。
但是这几个的意义在网页上找不到。
我最近手工标注了一批语料。
汇总的结果如下:
模式  正确  错误  总共  正确率
CD  513 2512    3025    0.169586777
GD  2055    564 2619    0.78465063
FD  1695    694 2389    0.709501884
CCD 555 1790    2345    0.236673774
有全部的标注语料，但是没贴出来。
有没有什么比较好的改进建议？
我目前想到的只有一些统计加规则的方法。比如：CD的正确率较低。就定一些类型C和D无法成词。

**Comment by hankcs** [comment]
0. 请参考 com/hankcs/hanlp/corpus/tag/NT.java
0. 目前机构名识别的确较弱，无论是从隐马模型本身的标注能力来讲，还是从当初的训练语料来讲，都不是最优的，甚至这种角色标注从原理上可能就有这些问题。
0. 但最大的问题还是语料，语料质量高了、数量大了，再差的算法都可以得出不差的效果。语料的成本是高昂的，而自然语境又是复杂的，很难兼顾准确率和召回率。
0. 就目前较为经济的改进方式是，在现有语料的基础上，人工标注一些语料，混合起来重新训练。

**Comment by zhangskills** [comment]
请问一下，自己训练会得到的 `SomeName.tr.txt` 怎么跟旧的 `nt.tr.txt` 文件合并？

**Comment by hankcs** [comment]
请参考com.hankcs.hanlp.corpus.dictionary.DictionaryMaker#combine(java.lang.String...)

**Comment by zhangskills** [comment]
不好意思，训练之后生成3个文件：

1. SomeName.txt：单词角色词典
2. SomeName.ngram.txt：二元接续词典（在命名实体识别中没有用处）
3. SomeName.tr.txt：角色转移矩阵

DictionaryMaker#combine 貌似只能合并 “单词角色词典”，不能合并“角色转移矩阵”，或者说，训练出来的3个文件只有“单词角色词典”有用？

**Comment by hankcs** [comment]
“角色转移矩阵”得自己写代码合并了

**Comment by qdchenxiaoyan** [comment]
转移矩阵可以采用叠加的方式

**Comment by qdchenxiaoyan** [comment]
转移矩阵可以采用矩阵相加的方式叠加

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
