### ISSUE TITLE
char数组使用建议

### ISSUE THREAD

**Issue by jimichan** [hankcs/HanLP#212]
程序中多出使用
char[] chars = string.toCharArray()
然后通过下标访问char ，如 chars[i] 这类代码

其实JDK中toCharArray的具体实现是
 char result[] = new char[value.length];
        System.arraycopy(value, 0, result, 0, value.length);
相当于每次toCharArray就会多出堆上copy的动作

建议直接使用 
string.charAt(i)代替

测试结论：charAt方法在性能稍微优势的情况下，减少GC消耗

=========性能测试代码=============
public static void main(String[] args) {
        String string = "abcedfghijklml";
        int len = string.length();
        char[] cc = string.toCharArray();

```
    for(int k=0;k<len;k++){
        char x = cc[k];
    }

    for(int k=0;k<len;k++){
        char x = string.charAt(k);
    }
    long t1 = System.currentTimeMillis();
    for(int i=0;i<500000;i++){
        char[] c = string.toCharArray();

        for(int k=0;k<len;k++){
            char x = c[k];
        }
    }
    long t2 = System.currentTimeMillis();       
    for(int i=0;i<500000;i++){
        for(int k=0;k<len;k++){
            char x = string.charAt(k);
        }
    }
    long t3 = System.currentTimeMillis();

    System.out.println(t2-t1);
    System.out.println(t3-t2);
}
```

**Comment by hankcs** [comment]
0. 我知道这个trick，但String的最终效率是更低的。
0. 因为程序中有大量的函数调用，而String是传值而不是传引用，这会导致更多的内存拷贝。

**Comment by jimichan** [comment]
不会吧???
Java复制并传递了“引用”的值，而不是对象.
String是实现的CharSequence接口，String并不是私有类型数据，只是个不可变对象而已。
如果string传递是copy内容，那么就真的要刷新我世界观了

**Comment by hankcs** [comment]
感谢指正，第2条考虑的确不成立。

当初决定用char[]还有其他考虑，比如：
0. 某些分词器需要修改传入的文本，如简繁转换
0. 代码直观性上用下标更好

目前看来，似乎对速度和内存占用都没好处。

感谢建议！以后会逐步改过来，也欢迎提交pull request。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
