### ISSUE TITLE
分词错误

### ISSUE THREAD

**Issue by iwaller** [hankcs/HanLP#217]
您好，我在调用HanLP.segment("我遗忘我的密码了")进行分词时，发现分词不准确，结果为：[我/r, 遗/vg, 忘我/b, 的/uj, 密码/n, 了/ul]，而准确结果应该是：[我，遗忘，我，的，密码，了]，
这是什么原因？ 麻烦大神帮忙看看，谢谢。

**Comment by hankcs** [comment]
可以自己改的。

**Comment by iwaller** [comment]
非常感谢^^
