### ISSUE TITLE
分词器对"三年"的分词结果不是很理想

### ISSUE THREAD

**Issue by a198720** [hankcs/HanLP#22]
测试代码:
List<Term> termList = StandardTokenizer.segment("三年");
System.out.println(termList);
termList = StandardTokenizer.segment("3年");
System.out.println(termList);
termList = StandardTokenizer.segment("三 年");
System.out.println(termList);
termList = StandardTokenizer.segment("三元");
System.out.println(termList);
termList = StandardTokenizer.segment("3元");
System.out.println(termList);
======================分词结果======================================
[三/m, 年/n]
[3年/m]
[三/m,  /w, 年/q]
[三元/nz]
[3元/mq]

首先查看词库,找到关于年和元的相关信息:
年 D 219 B 61 C 42 L 20 K 12 E 8  
年 B 105 D 57 A 11 X 1	
年	q	2421	n	95	m	1  
年 qt 14340	

元 P 47 D 2 A 1	
元 D 957 C 672 E 60 B 22 K 3 L 1	
元	q	1536	tg	5	n	1

词库中对年的统计,明显量词的词频比较高,但是为什么分出来是名词呢.我的代码已经是最新的代码了.

**Comment by hankcs** [comment]
感谢反馈，问题确认，正在解决中。

**Comment by hankcs** [comment]
太感谢您了，这是个隐藏得很深的bug，由于双数组trie查询结构写得有问题，当词典中有“三年期”词条时，“三年”这个句子中的“年”就没查出来。

现在已经解决了这个问题，欢迎运行com.hankcs.test.seg.TestSegment#testIssue22这个方法来检查效果。

**Comment by a198720** [comment]
呵呵! 您客气了!我这只是添点砖,增点瓦.  我验证了下,貌似引用这两个路径的话还是不行:
#核心词典路径
CoreDictionaryPath=data/dictionary/CoreNatureDictionary.txt
#2元语法词典路径
BiGramDictionaryPath=data/dictionary/CoreNatureDictionary.ngram.txt
你那边试试

**Comment by hankcs** [comment]
我这边是正常的

com.hankcs.test.seg.TestSegment#testIssue22

```
qt 14340 
[三/m, 年/qt]
[三元/b]
[三年/mq]
```

**Comment by a198720** [comment]
是我的词库的问题.
