### ISSUE TITLE
DoubleArrayTrie的一个resize bug

### ISSUE THREAD

**Issue by jimichan** [hankcs/HanLP#220]
由于初始分配内存位65536*32为1M空间，所以程序中基本没有出发resize方法
但是如果将初始大小设置位10240 然后执行core词典build的时候
你会发现下面这个代码的 double l 会是个超级大数 1万多，会导致内存爆点。
你检查一下这边的逻辑是否有问题
   
        begin = pos - siblings.get(0).code; // 当前位置离第一个兄弟节点的距离
            if (allocSize <= (begin + siblings.get(siblings.size() - 1).code))
            {
                // progress can be zero // 防止progress产生除零错误
                double l = (1.05 > 1.0 * keySize / (progress + 1)) ? 1.05 : 1.0
                        * keySize / (progress + 1);
                resize((int) (allocSize * l));
            }

**Comment by hankcs** [comment]
原作者的意图不清楚，但我应该修复了这个问题。
