### ISSUE TITLE
修改核心词性词频词典

### ISSUE THREAD

**Issue by raiky** [hankcs/HanLP#221]
比如你在data/dictionary/CoreNatureDictionary.txt中发现了一个不是词的词，或者词性标注得明显不对，那么你可以修改它，然后删除缓存文件使其生效。

请问，我现在修改了某词的词性，怎样才能使其生效？删除哪些缓存文件？？谢谢

**Comment by raiky** [comment]
追问，现在我无法使用用户自定义词典，比如我在自定义词典中定义了“刷单”，但是分词的时候还是将其分成了“刷”、“单”。

**Comment by hankcs** [comment]
https://github.com/hankcs/HanLP#储存形式

**Comment by qdchenxiaoyan** [comment]
；[上海市	ns	1
；[城镇	n	1
；[市	n	2
；不	d	1
；也	d	2
；乡镇	n	1
；占用	v	1
；在	p	1
；大	a	1
；她	rr	3
；工人们	nz	1
；工信部	nz	1
；市县	n	1
；并	cc	1
；旅游	vn	1
；晴好	a	1


前面带标点符号 是什么意思呢？？

**Comment by hankcs** [comment]
这是语料库中的错误，已经删除，谢谢指正。
