### ISSUE TITLE
关于词典打包问题

### ISSUE THREAD

**Issue by heshanshanhg3** [hankcs/HanLP#226]
我修改了hanlp算法里的功能，重新打包成jar文件，其他程序调用，运行成功。但是把调用程序打包成.jar文件严重: 没有找到HanLP.properties，可能会导致找不到data
========Tips========
请将HanLP.properties放在下列目录：
Web项目则请放到下列目录：
Webapp/WEB-INF/lib
Webapp/WEB-INF/classes
Appserver/lib
JRE/lib
并且编辑root=PARENT/path/to/your/data,请问这个问题怎么解决，我尝试把对应的properites版本修改打包调用的时候报错：核心词典加载失败。

**Comment by hankcs** [comment]
请问版本。

**Comment by heshanshanhg3** [comment]
hankcs，我修改的是12.8版本。

**Comment by hankcs** [comment]
你应该用portable分支代码，下载portable的jar包解压得倒data放进去，然后打包

**Comment by heshanshanhg3** [comment]
@hankcs, 在https://github.com/hankcs/HanLP/tree/portable portable分支代码，创建maven工程，把data加载到resource目录里，打包后其他程序调用，报错下载核心词典data/dictionary/CoreNatureDictionary.mini.txt加载失败

**Comment by hankcs** [comment]
请单步一下加载逻辑。

**Comment by heshanshanhg3** [comment]
谢谢@hankcs 帮忙，我的问题解决了。

**Comment by giantchou** [comment]
@heshanshanhg3  你好，请问你对HanLP-portable-1.2.10打包使用的命令是mvn package吗？为什么我打包后词典文件不在jar中，是我pom.xml配置不对吗？

**Comment by giantchou** [comment]
今天发现一个问题，就是通过git clone 命令获取源代码的时候，master和portable分支获取的代码是一样的，都是https://github.com/hankcs/HanLP.git一个地址，所以我打包的hanlp-portable-1.2.10.jar不包含字典，请问如何获取portable分支的代码？

**Comment by breakjiang** [comment]
@heshanshanhg3 请教下最后是怎么打包成功的？

**Comment by kangzhun** [comment]
@heshanshanhg3  请教下最后您是如何打包成功的

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
