### ISSUE TITLE
NShortSegment用户字典问题

### ISSUE THREAD

**Issue by So-Far-So-Good** [hankcs/HanLP#227]
在使用NShortSegment分词的时候，添加了用户自定义词，CustomDictionary.add("自由侠", "n 100000000");无法分出该词，其他分词器倒是可以，请问下是用户词典在该分词器中不起作用么？

**Comment by hankcs** [comment]
已经修复，欢迎测试。

**Comment by So-Far-So-Good** [comment]
刚才测试了NShortSegment下，刚开始cpu100%,没过一会就达到1000%

**Comment by hankcs** [comment]
请给出测试数据和代码。

**Comment by hankcs** [comment]
https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE
