### ISSUE TITLE
"齐云山高纯山茶油"分词bug

### ISSUE THREAD

**Issue by liuia** [hankcs/HanLP#23]
偶然遇到这个广告词，目前的nlp分词结果是“齐云山高/ns, 纯/a, 山茶油/nf”
正确的应该是“齐云山 高纯 山茶油”

**Comment by yuchaozhou** [comment]
hankcs闭关修练去了，估计暂时回答不了你问题。

CustomDictionary.txt 中添加 “齐云山” “高纯”词项
CoreNatureDictionary.ngram.txt 中添加相应2gram词频

**Comment by hankcs** [comment]
你好，抱歉没有及时回复。
感谢@yuchaozhou帮忙。

另一种解决方案是删除data/dictionary/custom/现代汉语补充词库.txt里面的
山高	ns	3

得到

[齐云山/nr, 高纯/nr, 山茶油/nf]

虽然被当成人名了，不过从分词的角度来讲，也算凑合。
