### ISSUE TITLE
自定义字典分词错误

### ISSUE THREAD

**Issue by kingdeewang** [hankcs/HanLP#232]
自定了单田芳，三国演义。 且系统允许自定义字典。 但是还是分成了单田芳三/nz, 国/n, 演义/n，能否帮查一下？

**Comment by hankcs** [comment]
请给出测试数据和代码。

**Comment by kingdeewang** [comment]
测试数据 ke为 单田芳三国演义

public  Segment segment = new CRFSegment().enableCustomDictionary(true).
enableNameRecognize(true).
enableIndexMode(false).enableOrganizationRecognize(false);
	
   List<Term> termList = segment.seg(key);
	        for(Term term:termList)
	        {
	        	log.info("-----分解后的分词" + termList  + (System.currentTimeMillis() - starttime) +"(ms)：");
}
分词结果为：
单田芳三/nz, 国/n, 演义/n

**Comment by hankcs** [comment]
这个问题是无解的，语料库中从来没出现过三国演义这个词语，只能重新训练。

**Comment by kingdeewang** [comment]
三国演义是自定义的字典中定义的。 并非没有。
