### ISSUE TITLE
多个标点符号分成一个词。

### ISSUE THREAD

**Issue by kotomo** [hankcs/HanLP#233]
主要有几方面分原因**:(**1)经济进入转型期,新常态下需求本身有所放缓。
比如这句中 :( 分成一个词了
这种问题可以解决吗？

**Comment by hankcs** [comment]
[主要/b, 有/vyou, 几/d, 方面/n, 分/qt, 原因/n, :/w, (/w, 1/m, )/w, 经济/n, 进入/v, 转型期/n, ,/w, 新/a, 常态/n, 下/f, 需求/n, 本身/rz, 有所/v, 放缓/v, 。/w]

**Comment by hankcs** [comment]
https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE
