### ISSUE TITLE
自定义词典删除词语失效

### ISSUE THREAD

**Issue by scjiaer** [hankcs/HanLP#234]
你好，在使用自定义词典的例子时，发现如下问题：
加入自定义词组能够使原先被分割开的固定搭配保持整体不切分，但是如果之后再使用remove等方法移除该组合，那么将不起作用。

        import com.hankcs.hanlp.HanLP;
        import com.hankcs.hanlp.dictionary.CustomDictionary;

        public class DemoCustomDictionary {
          public static void main(String[] args) {
            String customTerm = "攻城狮";
            String text = "攻城狮逆袭单身狗，迎娶白富美，走上人生巅峰";
            System.out.println("原始分词结果");
            System.out.println("CustomDictionary.get(customTerm)=" + CustomDictionary.get(customTerm));
            System.out.println(HanLP.segment(text));
            // 动态增加
            CustomDictionary.add(customTerm);
            System.out.println("添加自定义词组分词结果");
            System.out.println("CustomDictionary.get(customTerm)=" + CustomDictionary.get(customTerm));
            System.out.println(HanLP.segment(text));
            // 删除词语
            CustomDictionary.remove(customTerm);
            System.out.println("删除自定义词组分词结果");
            System.out.println("CustomDictionary.get(customTerm)=" + CustomDictionary.get(customTerm));
            System.out.println(HanLP.segment(text));
          }
        }

最后输出结果

      原始分词结果
      CustomDictionary.get(customTerm)=null
      [攻城/vi, 狮/ng, 逆袭/nz, 单身/n, 狗/n, ，/w, 迎娶/v, 白富美/nr, ，/w, 走上/v, 人生/n, 巅峰/n]
      添加自定义词组分词结果
      CustomDictionary.get(customTerm)=nz 1 
      [攻城狮/nz, 逆袭/nz, 单身/n, 狗/n, ，/w, 迎娶/v, 白富美/nr, ，/w, 走上/v, 人生/n, 巅峰/n]
      删除自定义词组分词结果
      CustomDictionary.get(customTerm)=null
      [攻城狮/nz, 逆袭/nz, 单身/n, 狗/n, ，/w, 迎娶/v, 白富美/nr, ，/w, 走上/v, 人生/n, 巅峰/n]

想问下是不允许这种临时性操作吗还是另有其他？

另外，HanLP是否支持用户自定义分词结果(已经过人为分词的语句之间使用空格或者###等特殊符号间隔)，然后通过一种特定的Tokenizer分割成数组形式然后传入Segment进行POS分析。
比如这句`我很想要个宝宝,但觉得好难才有,早二个月怀上了,但流去了`，
假设"正确"的分词结果为
`我 很 想 要 个 宝宝 , 但 觉得 好难 才 有 , 早 二个月 怀上 了 , 但 流去 了`，不知道该如何在HanLP操作得到分析结果等

感谢！

运行环境
HanLP v1.2.9 
Ubuntu 14.04 x86_64
JDK 1.8.0_73

**Comment by hankcs** [comment]
感谢反馈，已经修复。

这属于实现上不严谨造成的问题。
