### ISSUE TITLE
如何建立 情感分析, 识别文本蕴涵(RTE)等平台

### ISSUE THREAD

**Issue by arthurtalkgoal** [hankcs/HanLP#236]
在英文文本挖掘，可以找到一些情感分析, 识别文本蕴涵 的應用和平台。

在中文文本挖掘，我找到的是東拼西湊的方案，例如 python 的nltk +jieba (分詞)。

作為統一的中文文本挖掘系統，HanLP 是非常合適的。 

HanLP 有沒有相關的方法/方案，能建成如下的平台：

情感分析、 识别文本蕴涵(RTE)系統、Hadoop/Spark 結合、机构名识别模块的核心模型 (http://www.hankcs.com/nlp/ner/place-name-recognition-model-of-the-stacked-hmm-viterbi-role-labeling.html)

我十分樂意參與相關開發。

**Comment by hankcs** [comment]
感谢建议。

0. 这是个很宏大的命题，需要一点一滴的积累
0. 情感分析将会在1.4版本中加入。初级的情感分析主要归结为文本分类任务，我已经完成了贝叶斯和SVM的分类模型。其中贝叶斯会开源，而SVM受限于版权无法开源，未来可能会探究神经网络模型。
0. 已经有一些热心的NLP爱好者向我捐赠了情感词词典，可用于特征提取。
0. RTE则暂时没有开发计划，涉及到QA系统我认为应该归结到知识图谱任务中去。这是个很高级的任务，至少复杂程度跟机器翻译是平级的。而HanLP最初的宗旨是一个基础类库，而不是如此复杂的业务系统。如果要做，可能也是另外开项目。
0. Hadoop/Spark的集成反而非常简单，只需将模型和词典的文件读取代码适配到HDFS等分布式文件系统上去。前期只需将这些代码抽象成interface，后面提供个hdfs-io-plugin即可。
0. 机构名识别在计算资源充足的情况可以考虑使用更复杂的算法，训练更准确的模型。毕竟目前的模块考虑经济性更多。
0. 欢迎参与完善，特别是hdfs-io-plugin。

**Comment by arthurtalkgoal** [comment]
@hankcs , ```情感分析将会在1.4版本中加入。```  我的項目要使用很多情感分析，在 這個repository 的tag 找不到v1.4 (到v1.2.9) 。  請問能commit 一起開發嗎？

**Comment by hankcs** [comment]
感谢支持，v1.4是未来的版本号。欢迎commit，我忙完了工作会逐步提交我的文本分类代码的。

**Comment by arthurtalkgoal** [comment]
Stephen, 謝謝你的回覆。

主要指的是`利用Spark的MLlib来当计算工具'，如果只限用來分詞太浪費 hanlp了。

比如在 extraction, classification 兩個步驟， hanlp 可做的是提取人名、公司名等，然後因應 sentiment 態度，把記錄分類、標籤。  這簡單的例子，可以预期 hanlp 能成為hadoop/spark很好用的一個模組。

Svm 這些方法在大数據中直接應用可能有樽頸，例如有人谈過 parallel SVM 去解決，這些問題成為一個模組後可一一解決

Arthur CHAN 
Chief Executive Officer
CatchTop Limited 營銷科技有限公司



2016 年 6 月 24 日上午10:11, 上午10:11，在 Stephen Kuo <notifications@github.com> 已写:

**Comment by SunnyWiki** [comment]
如何将hanlp 应用到spark中  rdd.map( line => hanlp.segment(line) ) 提示item没有序列化

**Comment by samuelqiu2015** [comment]
@hankcs模型因为不支持序列化，所以无法broadcast，在spark上也只能像单机那样使用... 
![image](https://cloud.githubusercontent.com/assets/19728187/26302525/1f7f232c-3f17-11e7-896f-716d5224935e.png)

**Comment by hankcs** [comment]
@samuelqiu2015 CRFSegment几乎没有什么成员变量要序列化的。可参考com.hankcs.hanlp.model.crf.CRFModel#save实现序列化接口。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
