### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by lg003x** [hankcs/HanLP#237]
http://www.hankcs.com/nlp/hanlp.html　这里说的以下功能，有实例吗？或是代码在哪？
语料库工具
分词语料预处理
词频词性词典制作
BiGram统计
词共现统计
CoNLL语料预处理
CoNLL UA/LA/DA评测工具

**Comment by hankcs** [comment]
https://github.com/hankcs/HanLP/tree/master/src/test/java/com/hankcs/demo
https://github.com/hankcs/HanLP/wiki
开发比文档快。

**Comment by liuyunfang** [comment]
请问下，当我循环不停的进行分词的时候，在循环分词期间改变CustomDictionary.txt.bin文件，却不能实时更新，发现只有重新启动程序的时候才能更新bin文件，使新增的词语生效，查看了代码，发现是因为用了static实现部分，但是一直都没找到怎样在分词期间进行词语匹配的部分，是树呢还是缓存文件bin呢还是dat啊

**Comment by hankcs** [comment]
https://github.com/hankcs/HanLP/issues/182
