### ISSUE TITLE
能否提供主词典动态删除方法？

### ISSUE THREAD

**Issue by timlincool** [hankcs/HanLP#24]
看了下原码，发现BinTrie有提供remove方法，所以自定义词典可以动态删除。
不过DoubleArrayTrie好像并没有提供删除方法，请问是为什么？是否是因为数据结构的问题？

建议能提供主词典动态删除方法，因为若是把hanLP拿来做生产环境solr的分词，服务不能停，
如果要修改词库的话，建议能有动态删除所有词库的方法。

谢谢！

**Comment by hankcs** [comment]
你好，抱歉没有及时回复。

DAT比较特殊，动态增删非常复杂。如果你很需要删除操作的话，可以给每个key新增一个状态变量，删除则置为false，粗分的时候忽略状态为false的词语。
