### ISSUE TITLE
CRFSegment 哪下載

### ISSUE THREAD

**Issue by arthurtalkgoal** [hankcs/HanLP#241]
在data.zip 中沒有CRFSegmentModel.txt, 固DemoCRFSegment.java 有如下錯誤:
```
java -classpath ".:../hanlp/src/main/java/"  com/hankcs/demo/DemoCRFSegment
Jun 14, 2016 1:02:29 AM com.hankcs.hanlp.model.CRFSegmentModel <clinit>
SEVERE: CRF分词模型加载 hanlp/data/model/segment/CRFSegmentModel.txt 失败，耗时 5 ms
```

我在 http://www.hankcs.com也找不到相關文章。請問在哪可下載或怎樣建立？

謝謝.

**Comment by hankcs** [comment]
只需有data/model/segment/CRFSegmentModel.txt.bin 即可，请检查是否是full版的data，以及配置文件路径是否配好了。

**Comment by arthurtalkgoal** [comment]
謝謝＠hankcs ，你真的很用功維護這個項目， 感激。

我已成功運行這個分析器。請問有沒有建立這些model.txt 的格式範例？

謝謝

**Comment by hankcs** [comment]
不客气，有关CRF训练的知识请参考：
http://www.hankcs.com/nlp/the-crf-model-format-description.html

**Comment by arthurtalkgoal** [comment]
Thanks again @hankcs
