### ISSUE TITLE
TraditionalChineseToker cannot use CustomerDictionary

### ISSUE THREAD

**Issue by arthurtalkgoal** [hankcs/HanLP#242]
I am testing different tokenizer performance, I found that the TraditionalChineseTokenizer does not apply the CustomDicionary as the others do.

```
CustomDictionary.add("銀主盤", "nz 1024 n 1");
  Segment segment = HanLP.newSegment().enableCustomDictionary(true).enableNameRecognize(true);

        for (String sentence : testCase)
        {
            System.out.println( "\n\n" + "Sentence" + sentence);
            System.out.println("HanLP");
            List<Term> termList = segment.seg(sentence);
            System.out.println(termList);

            termList = TraditionalChineseTokenizer.segment(sentence);
            System.out.println("TraditionalChineseTokenizer");
            System.out.println(termList);


            termList = NLPTokenizer.segment(sentence);
            System.out.println("NLPTokenizer");
            System.out.println(termList);
        }
```

Results
Sentence (Only TraditionalChineseTokenizer does not apply the "銀主盤" new word in CustomDictionary.)

```

銀主盤,好多人等緊樓市大跌!
HanLP
[銀主盤/nz, ,/w, 好多/mq, 人/n, 等/udeng, 緊/n, 樓/n, 市/n, 大跌/v, !/w]
TraditionalChineseTokenizer
[銀/ng, 主盤/n, ,/w, 好多/mq, 人/n, 等/udeng, 緊/d, 樓市/n, 大跌/v, !/w]
NLPTokenizer
[銀主盤/nz, ,/w, 好多人/nt, 等/udeng, 緊/n, 樓/n, 市/n, 大跌/v, !/w]
```

**Comment by arthurtalkgoal** [comment]
啊. 原來簡體字加入 CustomDictionary, 繁體才找到。 是TraditionalChineseToken 用簡體找 dictionary!

其他的Tokernizer 反而正確的找CustomDictionary.

```
CustomDictionary.add("银主盘", "nz 1024 n 1");

Sentence銀主盤,好多人等緊樓市大跌!
HanLP
[銀/n, 主/ag, 盤/n, ,/w, 好多/mq, 人/n, 等/udeng, 緊/n, 樓/w, 市/n, 大跌/v, !/w, /nx]
TraditionalChineseTokenizer
[銀主盤/nz, ,/w, 好多/m, 人/n, 等/udeng, 緊/d, 樓市/n, 大跌/v, !/w]
NLPTokenizer
[銀/n, 主/ag, 盤/n, ,/w, 好多人/nt, 等/udeng, 緊/n, 樓/w, 市/n, 大跌/v, !/w, /nx]

```

讓我試一下debug.

**Comment by Tony-Wang** [comment]
hankcs使用的人民日报的语料训练，繁体中文的语言习惯不同于简体，需要累积自己的语料重新训练字典。

**Comment by hankcs** [comment]
是的，虽然支持繁体分词，但内核还是简体的，繁体先转为简体，分词后再转为繁体。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
