### ISSUE TITLE
正规化全角标点符号会转成半角逗号

### ISSUE THREAD

**Issue by liuia** [hankcs/HanLP#25]
System.out.println(CharTable.convert('！'));
结果是','，而不是'!'

**Comment by hankcs** [comment]
你好，抱歉没有及时回复。

0. 这是一个临时措施带来的问题，原因：https://github.com/hankcs/HanLP/issues/13
0. com.hankcs.hanlp.dictionary.other.CharTable#CONVERT可以直接改成你想要的转义字符
