### ISSUE TITLE
mac下 heap Size

### ISSUE THREAD

**Issue by jackalsin** [hankcs/HanLP#251]
很有可能我是在问蠢问题：
我在windows运行无任何问题，1000次跑下来benchmark在122mb左右（自己的程序）
但帮助其他人部署在Mac下出现了heap size 问题
使用Intellij和Eclipse均无法跑起Demo1
-Xmx6g 传入VMoption还是无果，
-Xmx4g -Xmx2g -Xmn2g也已经试过

`
System.out.println(HanLP.segment("你好，欢迎使用HanLP汉语处理包！"));
`

`usr/lib/jvm/java-8-oracle/bin/java -d64 -Xmx6g -Didea.launcher.port=7534 -Didea.launcher.bin.path=/home/master/Prog/idea-IU-145.1617.8/bin -Dfile.encoding=UTF-8 -classpath /usr/lib/jvm/java-8-oracle/jre/lib/charsets.jar:/usr/lib/jvm/java-8-oracle/jre/lib/deploy.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/dnsns.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/jaccess.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/jfxrt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/localedata.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/nashorn.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/sunec.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/zipfs.jar:/usr/lib/jvm/java-8-oracle/jre/lib/javaws.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jce.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jfr.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jfxswt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jsse.jar:/usr/lib/jvm/java-8-oracle/jre/lib/management-agent.jar:/usr/lib/jvm/java-8-oracle/jre/lib/plugin.jar:/usr/lib/jvm/java-8-oracle/jre/lib/resources.jar:/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar:/home/master/Documents/<Project Name>/target/classes:/home/master/.m2/repository/junit/junit/4.12/junit-4.12.jar:/home/master/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/home/master/Documents/<Project Name>/lib/hanlp-1.2.9.jar:/home/master/Prog/idea-IU-145.1617.8/lib/idea_rt.jar com.intellij.rt.execution.application.AppMain Main
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at com.hankcs.hanlp.dictionary.CoreDictionary.loadDat(CoreDictionary.java:141)
	at com.hankcs.hanlp.dictionary.CoreDictionary.load(CoreDictionary.java:63)
	at com.hankcs.hanlp.dictionary.CoreDictionary.<clinit>(CoreDictionary.java:40)
	at com.hankcs.hanlp.seg.common.Vertex.<clinit>(Vertex.java:56)
	at com.hankcs.hanlp.seg.common.WordNet.<init>(WordNet.java:71)
	at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.segSentence(ViterbiSegment.java:40)
	at com.hankcs.hanlp.seg.Segment.seg(Segment.java:441)
	at com.hankcs.hanlp.tokenizer.StandardTokenizer.segment(StandardTokenizer.java:50)
	at com.hankcs.hanlp.HanLP.segment(HanLP.java:386)
	at Main.main(Main.java:30)
`

**Comment by hankcs** [comment]
我也在使用mac，一切正常：
```
/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/bin/java -Xms120m -Xmx120m -Xmn64m -Didea.launcher.port=7533 "-Didea.launcher.bin.path=/Applications/IntelliJ IDEA.app/Contents/bin"
```
 我怀疑你拷贝过去的data破损了。你可以从代码库clone一份，重新生成bin。

**Comment by jackalsin** [comment]
感谢回复，正在测试

其实我问题很诡异，RedHat也没问题，Ubuntu却有问题

**Comment by jackalsin** [comment]
多谢，已经解决，问题如下：
每一次新的data的字典会自动创建.txt.bin文件，此部分文件需要在每一台新的机子上重新编译，不可以使用git lfs track
多谢回复。

**Comment by hankcs** [comment]
好的，二进制bin文件不应该提交到版本库。git有可能在其中插入了解决冲突的标记，这破坏了文件。
