### ISSUE TITLE
C#中调用Hanlp.dll文件执行程序出现以下错误

### ISSUE THREAD

**Issue by 727626652** [hankcs/HanLP#256]
![image](https://cloud.githubusercontent.com/assets/19245664/16475947/29d8d9b6-3eb5-11e6-8873-5a4770a76945.png)

**Comment by 727626652** [comment]
该文章【http://www.hankcs.com/nlp/call-hanlp-in-csharp.html】中描述不够详细，经过测试发现 上面的问题是缺少DLL造成，需要引用这几个
![image](https://cloud.githubusercontent.com/assets/19245664/16478080/ea5121bc-3ec9-11e6-9cf1-58605aa7a3d2.png)

**Comment by hankcs** [comment]
感谢反馈，可能跟C#版本和IKVM版本有关。VS2013是可以直接跑的。

**Comment by YangliAtGitHub** [comment]
我用的是HanLp 1.2.7 + VS2015+.net 4.6.2。只需要前三个 IKVM包，不需要JNI. 不知道 1.2.10是不是有修改 。

**Comment by hankcs** [comment]
不太可能，引发问题的这句话是java的system方法，跟HanLP没有关系。

**Comment by RockNHawk** [comment]
IKVM 停止更新了，不支持 .NET Core ，咋整。。。没法在 .NET Core 上用 HanLP 了啊。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
