### ISSUE TITLE
关键词提取算法会出现重复关键词

### ISSUE THREAD

**Issue by bluedesire** [hankcs/HanLP#26]
List<String> textrank = HanLP.extractKeyword(article, 5);

输出：市场 设备 idc 穿戴 fitbit fitbit
输入：新浪科技讯 北京时间6月7日早间消息，IDC近期公布了“全球市场季度可穿戴设备跟踪报告”，第一季度Fitbit是全球排名第一的可穿戴设备厂商。然而，随着苹果Apple Watch的全面开售，Fitbit的优势很可能将不复存在。

　　IDC公布的数据显示，2015年第一季度，Fitbit、小米和Garmin是全球前三大可穿戴设备厂商。不过，苹果今年4月开始销售Apple Watch。因此当第二季度数据发布时，苹果将跻身这一排行的前列。

　　IDC可穿戴设备研究经理雷蒙·拉马斯(Ramon Llamas)表示：“Apple Watch很可能将成为其他可穿戴设备的对比对象。这将迫使竞争对手采取措施，以保持在市场的领先优势。”

　　整体来看，第一季度可穿戴设备市场同比增长200%，全球出货量为1140万个。这表明，这一市场非常强劲。

　　拉马斯表示：“第一季度，即‘后假日季’时段销售滑坡不明显，这表明可穿戴设备市场非常强劲。终端用户的兴趣不断提升，而相关厂商可以提供多样化的设备和体验。此外，新兴市场的需求正在上升，而厂商渴望把握这些新机会。”

　　导致Apple Watch无法主宰市场的一大障碍在于，这款产品的入门价格较高。IDC指出，价格下降是推动可穿戴设备销售火爆的原因之一。Apple Watch的起步价格为349美元，是其他可穿戴设备平均价格的3倍。IDC估计，有40%的可穿戴设备价格低于100美元。

　　IDC全球移动设备跟踪报告高级分析师杰特什·乌布拉尼(Jitesh Ubrani)表示：“与任何新生市场一样，价格下降非常猛烈。在平均价格下降的情况下，苹果携一款高价产品入市将检验用户是否愿意为某一品牌，或是受市场关注的产品而支付更高的价格。”

　　IDC的数据显示，第一季度，Fitbit的设备出货量为390万个，市场份额为34%，这是由于Charge、Charge HR和Surge等新产品的需求强劲。此外，用户也在继续追捧Fitbit的Flex、One和Zip等产品。IDC认为，同时专注于休闲和高端市场是Fitbit取得成功的重要原因。

　　Fitbit的市场份额比排名第二的小米高10%。小米排名第二主要是依靠小米手环在中国国内市场的销售。IDC认为，小米将很快进一步开拓国际市场，从而成为Fitbit的有力竞争对手。

　　与Fitbit类似，Garmin也提供了多样化的可穿戴设备产品。不过，Garmin的市场份额仅略高于6%。

　　三星排名第四。IDC分析师指出，三星的表现不佳主要是由于，其Gear设备只能连接某些高端的三星智能手机。

　　Jawbone、索尼和Pebble正在争夺市场第五的位置，而第一季度Jawbone取得了领先。拉马斯和乌尔巴尼表示，Jawbone的UP MOVE和UP24第一季度带来了帮助。而随着第二季度Jawbone再推出两款新产品，这样的优势还将得到加强。(维金)

**Comment by hankcs** [comment]
你好，抱歉没有及时回复。

看样子你已经解决了问题，在我这边

```
        String text = "新浪科技讯 北京时间6月7日早间消息，IDC近期公布了“全球市场季度可穿戴设备跟踪报告”，第一季度Fitbit是全球排名第一的可穿戴设备厂商。然而，随着苹果Apple Watch的全面开售，Fitbit的优势很可能将不复存在。\n" +
                "\n" +
                "　　IDC公布的数据显示，2015年第一季度，Fitbit、小米和Garmin是全球前三大可穿戴设备厂商。不过，苹果今年4月开始销售Apple Watch。因此当第二季度数据发布时，苹果将跻身这一排行的前列。\n" +
                "\n" +
                "　　IDC可穿戴设备研究经理雷蒙·拉马斯(Ramon Llamas)表示：“Apple Watch很可能将成为其他可穿戴设备的对比对象。这将迫使竞争对手采取措施，以保持在市场的领先优势。”\n" +
                "\n" +
                "　　整体来看，第一季度可穿戴设备市场同比增长200%，全球出货量为1140万个。这表明，这一市场非常强劲。\n" +
                "\n" +
                "　　拉马斯表示：“第一季度，即‘后假日季’时段销售滑坡不明显，这表明可穿戴设备市场非常强劲。终端用户的兴趣不断提升，而相关厂商可以提供多样化的设备和体验。此外，新兴市场的需求正在上升，而厂商渴望把握这些新机会。”\n" +
                "\n" +
                "　　导致Apple Watch无法主宰市场的一大障碍在于，这款产品的入门价格较高。IDC指出，价格下降是推动可穿戴设备销售火爆的原因之一。Apple Watch的起步价格为349美元，是其他可穿戴设备平均价格的3倍。IDC估计，有40%的可穿戴设备价格低于100美元。\n" +
                "\n" +
                "　　IDC全球移动设备跟踪报告高级分析师杰特什·乌布拉尼(Jitesh Ubrani)表示：“与任何新生市场一样，价格下降非常猛烈。在平均价格下降的情况下，苹果携一款高价产品入市将检验用户是否愿意为某一品牌，或是受市场关注的产品而支付更高的价格。”\n" +
                "\n" +
                "　　IDC的数据显示，第一季度，Fitbit的设备出货量为390万个，市场份额为34%，这是由于Charge、Charge HR和Surge等新产品的需求强劲。此外，用户也在继续追捧Fitbit的Flex、One和Zip等产品。IDC认为，同时专注于休闲和高端市场是Fitbit取得成功的重要原因。\n" +
                "\n" +
                "　　Fitbit的市场份额比排名第二的小米高10%。小米排名第二主要是依靠小米手环在中国国内市场的销售。IDC认为，小米将很快进一步开拓国际市场，从而成为Fitbit的有力竞争对手。\n" +
                "\n" +
                "　　与Fitbit类似，Garmin也提供了多样化的可穿戴设备产品。不过，Garmin的市场份额仅略高于6%。\n" +
                "\n" +
                "　　三星排名第四。IDC分析师指出，三星的表现不佳主要是由于，其Gear设备只能连接某些高端的三星智能手机。\n" +
                "\n" +
                "　　Jawbone、索尼和Pebble正在争夺市场第五的位置，而第一季度Jawbone取得了领先。拉马斯和乌尔巴尼表示，Jawbone的UP MOVE和UP24第一季度带来了帮助。而随着第二季度Jawbone再推出两款新产品，这样的优势还将得到加强。(维金)";
        System.out.println(HanLP.extractKeyword(text, 5));
```

输出：

```
[市场, 设备, IDC, 穿戴, Fitbit]
```
