### ISSUE TITLE
请问HanLP.properties

### ISSUE THREAD

**Issue by yaojuncn** [hankcs/HanLP#260]
请问hanlp.properties文件,
没看到发布页 https://github.com/hankcs/HanLP/releases
有这个文件的例子， 

请问是只要这样一行就好了么？
root=/myhanlpdata/

**Comment by hankcs** [comment]
https://github.com/hankcs/HanLP/releases/download/v1.2.10/hanlp-1.2.10-release.zip
请仔细阅读文档

**Comment by hankcs** [comment]
hanlp.properties一般和jar打包在同一个zip包中。

配置文件的作用是告诉HanLP数据包的位置，只需修改第一行

root=usr/home/HanLP/
为data的父目录即可，比如data目录是/Users/hankcs/Documents/data，那么root=/Users/hankcs/Documents/ 。

**Comment by yaojuncn** [comment]
谢谢！
