### ISSUE TITLE
HanLP自定义字典不生效

### ISSUE THREAD

**Issue by llssyy** [hankcs/HanLP#266]
您好，我按照官网的方法配置了properties，而且也进行了对bin的删除，但是就是不能进行对我的字典.txt里的添加的词进行识别，字典里定义了人才报告厅，麻烦您帮我看一下。
![qq 20160705130443](https://cloud.githubusercontent.com/assets/20194150/16574453/a1e3515c-42b1-11e6-91f3-750f619e34d2.png)
![qq 20160705130632](https://cloud.githubusercontent.com/assets/20194150/16574452/a1d56236-42b1-11e6-8783-48e99c4c4cd9.png)
![qq 20160705130748](https://cloud.githubusercontent.com/assets/20194150/16574451/a1d3eeba-42b1-11e6-9cd1-5384baadecda.png)

**Comment by hankcs** [comment]
文件编码必须是utf-8

**Comment by llssyy** [comment]
这个解决了 谢谢大神

**Comment by ln94223** [comment]
这个怎么配置的可以详细说一下嘛  我的自定义词典和你格式相同

**Comment by ln94223** [comment]
关键词提取的词库

**Comment by alreadyeleven** [comment]
也是遇到同样的问题，请问是怎么解决的？

**Comment by alreadyeleven** [comment]
我自己创建的用户词典也是不起作用，而且显示词典加载信息时，没有出现自己创建的词典被加载了，这是怎么回事？

**Comment by lglhuada** [comment]
我也碰到这个问题了，求大神解答

**Comment by llssyy** [comment]
目录结构看一下


发自网易邮箱大师
在2016年11月10日 09:48，Guangliang Liu 写道:

我也碰到这个问题了，求大神解答

**Comment by lglhuada** [comment]
用CustomDictionary.add()的方法加入词典也不发挥作用，用的分词为HanLP.segment()，properties中自定义词典没有被加载进入。求解答哪些需要注意的事项？

**Comment by fangyuan930917** [comment]
要删除缓存文件哦

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
