### ISSUE TITLE
地址集体识别

### ISSUE THREAD

**Issue by llssyy** [hankcs/HanLP#267]
您好，我是第一次使用hanlp，我想请教一下对于“北京市海淀区学院路31号北京航空航天大学体育馆”这个整体地址有什么方法可以集体一次性识别出来吗？而不是北京市/ns海淀区/ns学院路/nz31/m号/q北京航空航天大学/nt体育馆/n这中怎么把他们变为北京市海淀区学院路31号北京航空航天大学体育馆/ns。麻烦您了
谢谢您。

**Comment by hankcs** [comment]
这必须做很多统计上和规则上的工作，不是几句话能说得清楚的。我曾经做过一个商业项目，就是面向地址的分词和识别，花了一两个月的时间。

**Comment by arthurtalkgoal** [comment]
@llssy 這項目要求如果可以的話，以找出地理訊息為主、而不是保留地址文本，那麼用現有的　Geocoding 技術便容易做。
例如baidu API 等。

**Comment by dianhu** [comment]
@hankcs博主，你好：
　目前我也在做一个地图的产品，其中要做一个自己的地址库。主要目的有二，一是对查询地址地址通过地址分词来返回词典中记录的相关地址的经纬度，二是当自己库中没有的时候，查询第三方的解析，然后通过分词(还有距离等因素)来判断第三方的解析哪个更靠谱。现在的做法是建了一个地址的词典，用的正向最大匹配，然后再根据地址词的上级下关系，上下文关系等一系列人定的规则来进行分词。遇到未登陆词，如分词结果不好，又人为的添加相应的规则。一般的地址能够很好的区分，如"四川省成都市锦江区大慈市路远洋太古里"分为"四川省|2|成都市|3|锦江区|4|大慈市路|6|远洋太古里|10|",但”贵州省安顺市东门坡东方时代广场“就分成了”贵州省|2|安顺市|3|东门|30|坡东方|4|时代广场|10|“，理想的是”贵州省|2|安顺市|3|东门坡|6|东方时代广场|10|“,当然这个和词典有很大关系。想请教一下，在词典只有相对少的情况下，如15万左右，有没有更好的基于统计的模型来解决地址方面的相关分词呢？

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
