### ISSUE TITLE
Class com.hankcs.hanlp.HanLP not found

### ISSUE THREAD

**Issue by judy111** [hankcs/HanLP#270]
hankcs大神，调用hanlp时碰到如下问题，怎么解决？另外，对项目文档里的这句话也不能理解“最后将HanLP.properties放入classpath即可，对于任何项目，都可以放到src或resources目录下，编译时IDE会自动将其复制到classpath中。‘’,求解答？多谢！！！

![78_d1 v13tj1r_6 0 lqu9w](https://cloud.githubusercontent.com/assets/19303343/16736512/d3455124-47bf-11e6-94b4-b6d686e2c43c.png)

**Comment by hankcs** [comment]
0. JPype本身问题不少，不如原生Java好用
0. 检查jar路径是否正确，jar包是否破损
0. 试试Python3
0. 试试64位环境

**Comment by judy111** [comment]
那请问项目文档里的这句话也什么意思，即“最后将HanLP.properties放入classpath即可，对于任何项目，都可以放到src或resources目录下，编译时IDE会自动将其复制到classpath中。‘’，对java不熟，所以不太懂

**Comment by hankcs** [comment]
JVM启动的时候会在classpath下查找class和properties，这句话就是在指定classpath：
-Djava.class.path=C:\hanlp\hanlp-1.2.8.jar;C:\hanlp
请Google一下Java的基本知识，毕竟语言是前提条件。

**Comment by judy111** [comment]
好的，谢谢hankcs

**Comment by msw0126** [comment]
你好，我使用scala开发spark，已经添加了maven依赖，提交任务到spark以后为什么还会报错"Caused by: java.lang.ClassNotFoundException: com.hankcs.hanlp.HanLP"呢？谢谢

**Comment by hankcs** [comment]
请查阅spark部署文档，应该是开发时编译通过，但运行时hanlp.jar没有部署上去。

**Comment by liuyt-15** [comment]
> 请查阅spark部署文档，应该是开发时编译通过，但运行时hanlp.jar没有部署上去。

您好，请问用spark-submit 添加了--jars 引入hanlp外部包，为什么还是会报找不到class的错误呢？

**Comment by hankcs** [comment]
> > 请查阅spark部署文档，应该是开发时编译通过，但运行时hanlp.jar没有部署上去。
> 
> 您好，请问用spark-submit 添加了--jars 引入hanlp外部包，为什么还是会报找不到class的错误呢？而spark -shell --jars则可以成功

不好意思，我对spark不熟悉，没有用过这个命令。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
