### ISSUE TITLE
java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by judy111** [hankcs/HanLP#273]
请问hankcs，调用依存句法分析，出现初始化错误该如何解决，多谢多谢！ps：分词等功能正常
![vcp wuh b8 5n h aopw9p](https://cloud.githubusercontent.com/assets/19303343/16901354/92c08520-4c73-11e6-8f71-0e8d36710819.png)

**Comment by hankcs** [comment]
不支持32位Windows
请参考https://github.com/hankcs/HanLP/issues/101#issuecomment-192333906

**Comment by Carrylaw** [comment]
博主，我64位的WINDOWS也会出现上述问题

**Comment by hankcs** [comment]
see https://github.com/hankcs/HanLP/issues/180
