### ISSUE TITLE
默认的繁体转换好奇怪

### ISSUE THREAD

**Issue by woodwind** [hankcs/HanLP#276]
舞台：舞颱
因为：囙爲
青梅竹马：青楳竹馬

**Comment by hankcs** [comment]
有人也提议过：https://github.com/hankcs/HanLP/issues/211

这个问题马上摆到日程上去。

**Comment by henrykey** [comment]
是否可以基于多字词进行简繁转换，转换词库和分词库对应，利用你的分词模型分完词依词转换，这样一简对多繁的问题可以避免

**Comment by hankcs** [comment]
@henrykey 

感谢建议，目前简繁词库和分词“词库”是毫无关联的，如果简繁转换这个简单任务执行前还需要进行分词，那么是否在计算量上太浪费？

**Comment by woodwind** [comment]
@hankcs 

如果不分词的话，一简对多繁是否有必要呢？另外你的demo里面那个词应该是香港的说法，但是台湾的汉语用法和香港的又不一样，如果处理的话很难做得很好。是否考虑再简化一下转换，直接一对一？

**Comment by hankcs** [comment]
一对一就是分拆成两个词典，简繁和繁简。用户根据自己的语言再做微调。

**Comment by henrykey** [comment]
@hankcs 
基于分词的想法是把准确度放在第一位考虑的；随便转转的确不用...

**Comment by hankcs** [comment]
@henrykey 其实繁体分词就是这么做的，你把该接口出来的结果拼接一下，就是你要的比较准确的转换。

**Comment by leeyc0** [comment]
另外也發現有若干單字出現錯誤轉換：

「幣」錯誤轉換成「蔽」（正確是「币」）
「繫」錯誤不轉換（正確是「系」）
「憑藉」的「藉」字錯誤不轉換（應轉換成「凭借」）
「眾」錯誤不轉換（正確是「众」）
「龕」錯誤不轉換（正確是「龛」）

暫時發現這些，如果還有的話會再回應。

**Comment by leeyc0** [comment]
另外也建議把繁體「質素」和簡體「素质」等同，方便索引

**Comment by hankcs** [comment]
谢谢指正，欢迎直接修改繁简对应词典data/dictionary/tc/TraditionalChinese.txt。我会在近期添加一个SimplifiedChinese.txt，不会影响这个词典。

**Comment by hankcs** [comment]
目前单字的繁简转换也可以通过com.hankcs.hanlp.dictionary.other.CharTable来做，像“幣”等等就是在那里修改的。你可以根据我的最新commit了解修改方法，谢谢。

**Comment by leeyc0** [comment]
因為我是直接使用 solr，所以不太方便自行定義 CharTable。請問有沒有 CharTable.bin.yes 的原始檔可以讓我直接修改？這也方便我直接提交更正好的轉換表。

註：我剛剛又抓到了「產」沒有轉換成「产」這個錯誤……

另外，可否告訴我 hanlp-portable-1.2.10.jar 內的 data\dictionary\tc\TraditionalChinese.txt.bin 和 TraditionalChinese.txt.reverse.bin 是怎麼生成的？

**Comment by hankcs** [comment]
0. 已经将对应位置@你了。
0. 这两个文件是TraditionalChinese.txt的缓存，由程序com.hankcs.hanlp.dictionary.ts.BaseChineseDictionary#saveDat自动生成，替换掉hanlp-portable-1.2.10.jar内的对应文件即可生效。

**Comment by leeyc0** [comment]
那沒辦法了，即是我每次發現問題都要修改源文件再編譯……

**Comment by hankcs** [comment]
你也可以用配置文件指定用外部的TraditionalChinese.txt。

**Comment by leeyc0** [comment]
另外，我發現「後」沒有轉換成「后」。

不過這個的簡轉繁倒是有點麻煩：

「前后」的「后」（方位）對應繁體字是「後」
「皇后」的「后」（帝位）對應繁體字仍然是「后」
不過「后宮」的「后」對應繁體字卻是「後」：這個後是指背後，不是指皇后……

**Comment by hankcs** [comment]
这就是TraditionalChinese.txt的存在意义了，这里面已经支持

以后等你当上皇后
以後等妳當上皇后

这种转换了。

**Comment by hankcs** [comment]
TraditionalChinese.txt的转换是基于词的，而CharTable是基于字的。

**Comment by leeyc0** [comment]
嗯。那問題就是「後期」這沒有轉成「后期」了。

**Comment by hankcs** [comment]
往TraditionalChinese.txt里加一句
後期=后期
就行了

**Comment by hankcs** [comment]
另外，System.out.println(HanLP.convertToSimplifiedChinese("後期"));
是可以得到后期的，你说的问题不存在。

**Comment by leeyc0** [comment]
那就怪了，我用hanlp-portable-1.2.10.jar在solr跑的確有這個問題…

**Comment by leeyc0** [comment]
2626756 INFO  (qtp110456297-18) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/cores params={indexInfo=false&wt=json&_=1469863699151} status=0 QTime=0
粗分词网：
0:[ ]
1:[後]
2:[期]
3:[ ]

粗分结果[後/nr, 期/q]
2626764 INFO  (qtp110456297-18) [   x:test] o.a.s.c.S.Request [test]  webapp=/solr path=/analysis/field params={analysis.fieldvalue=後期&analysis.fieldname=_text_&analysis.showmatch=true&verbose_output=0&wt=json&_=1469863699342} status=0 QTime=1
2626771 INFO  (qtp110456297-19) [   x:test] o.a.s.c.S.Request [test]  webapp=/solr path=/admin/luke params={show=schema&wt=json&_=1469863699342} status=0 QTime=10
2626778 INFO  (qtp110456297-20) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/system params={wt=json&_=1469863699152} status=0 QTime=20

**Comment by hankcs** [comment]
我们讨论的不是一个问题，这个issue讨论的是简繁转换，而你讨论的是繁体中文分词。你可以这样描述问题：

        List<Term> termList = TraditionalChineseTokenizer.segment("後期");
        System.out.println(termList);

我就知道你在说什么了。

**Comment by leeyc0** [comment]
嗯，那就是我搞錯了，因為我沒有搞清楚問題本質，沒想到是 tokenizer 問題。

**Comment by hankcs** [comment]
分词之前需要将繁体转为简体，而这个转换目前是用CharTable做的，所以没有convertToSimplifiedChinese那么准。

**Comment by hankcs** [comment]
分完词之后再将每个词转换为繁体。

**Comment by hankcs** [comment]
为什么不用convertToSimplifiedChinese呢？因为转换前后字数发生了变化，我认为这不符合分词器的设计目标。
曾经有一版本是用convertToSimplifiedChinese做的，然后convertToTraditionalChinese。由于上面提到的一个简体字对应多个繁体字的原因，所以最终得到的繁体中文与原文不同，又不符合我的设计目标了。

**Comment by hankcs** [comment]
后来Tony-Wang提交了一个pr，在简体到繁体的环节直接按照下标去原文找对应的繁体。思路是挺好的，但是代码有bug。所以在稳定版中去掉了这个设计，如果你对此感兴趣，可以试试这个思路。由于大陆用户没有这个需求，而我工作比较忙，所以一直没有做，比较抱歉了。

**Comment by leeyc0** [comment]
上面說了，我是直接使用 hanlp-solr-plugin 在 solr 跑的，所以我沒法直接控制分詞轉換問題。或者我直接把繁體 txt 先餵 google translate 再餵 solr 算了 :D

**Comment by hankcs** [comment]
我提交了一个新patch，可以在现有的机制下提升繁简分词的效果：https://github.com/hankcs/HanLP/commit/4fa0b0f7fc1dcc87ccdd06c959dfc4345e2b7b75

至少目前TraditionalChineseTokenizer.segment("後期");是没问题的。

你可以替换CharTable.bin.yes应用这个patch。

**Comment by leeyc0** [comment]
System.out.println(HanLP.convertToSimplifiedChinese("線"));
錯誤轉換為「缐」，應為「线」

**Comment by leeyc0** [comment]
剛 checkout 了最新版本，似乎還是沒解決問題。
繁體是線 (留意左邊的糸是三點水)，不是缐(一劃)

**Comment by hankcs** [comment]
由于这个地方经常需要改动，所以我将其改为文本形式，欢迎直接修改并向我提交pull request，谢谢！
https://github.com/hankcs/HanLP/blob/master/data/dictionary/other/CharTable.txt

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
