### ISSUE TITLE
歧义分词解决

### ISSUE THREAD

**Issue by henrykey** [hankcs/HanLP#277]
我第一次试这个hanlp，觉得分词很好，试了一些容易引起歧义句子，大部分没问题。以下4句是CRFSeg出错的：
"在这些企业中国有企业有十个",
"新建地铁中将禁止商业摊点",
"方程的解除了零以外还有其它的…",
"这的确定不下来",

CRFSeg的结果：
[在, 这些, 企业, 中国, 有, 企业, 有, 十个]
[新建, 地铁, 中将, 禁止, 商业, 摊点]
[方程, 的, 解除, 了, 零以外, 还有, 其它, 的, …]
[这, 的, 确定, 不, 下来]

segment(标准分词)的结果：
[在/p, 这些/rz, 企业/n, 中/f, 国有企业/nz, 有/vyou, 十/m, 个/q]
[新建/v, 地铁/n, 中/f, 将/d, 禁止/v, 商业/n, 摊点/n]
[方程/n, 的/ude1, 解除/v, 了/ule, 零/m, 以外/f, 还有/v, 其它/rz, 的/ude1, …/w]
[这/rzv, 的/ude1, 确定/v, 不/d, 下来/vf]

标准分词中前两个对了，后两个依然是错的。我的问题是：
1、segment使用的什么方法？
2、可以通过什么办法进一步改进分词的准确率吗？（你的分词准确率已经很好了）

谢谢！

Henry

**Comment by hankcs** [comment]
感谢使用，

0. 标准分词使用的是BiGram概率最大化模型
0. 部分问题可以人工直接修改BiGram模型，比如https://github.com/hankcs/HanLP/commit/a91125a9ca42b155097d0a0f32ab96af2dacbfb2#diff-3b7160909c34e8e8b221f2da9648ca42 。但这样的效果是有限的，过量的人工修改会使模型失去统计意义。比如，类似"方程的解除了零以外还有其它的…"这种句子“的@解除”“了@数词”本身较常见，必须将“的@解”调到很大的值才行。这是BiGram语言模型本身的局限性。再者，语料是人民日报，其中几乎没有类似上述两个口语化的句子。
0. 长远的解决方法是更海量更精美的语料库，以及更复杂的语言模型。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
