### ISSUE TITLE
如何添加新的停用词

### ISSUE THREAD

**Issue by newthis** [hankcs/HanLP#28]
我在dictionary目录下的默认停用词文件中添加新的停用词，重新运行之后发现新的停用词没有去掉

**Comment by liuia** [comment]
所有字典都会建立缓存文件，所以修改字典后需要删除缓存文件，一般是同名文件的bin文件

**Comment by hankcs** [comment]
对，感谢楼上，应该没问题了吧

**Comment by newthis** [comment]
哦， 还是有问题，按照楼主的方法去做，还是不行，删掉stopwords缓存之后，再添加新的停用词

**Comment by hankcs** [comment]
调一下com.hankcs.hanlp.dictionary.stopword.CoreStopWordDictionary#contains单步追踪
