### ISSUE TITLE
CRFModel的构造函数有个问题，直接使用会失败！

### ISSUE THREAD

**Issue by flystarhe** [hankcs/HanLP#281]
你好，想通过你的CRFModel的loadBin加载你自带的bin模型或使用loadTxt加载自己训练的crf++模型。加载没有报错，但是tag工作却提示空指针。

看了你CRFSegmentModel类的加载代码，这里你用的是`new BinTrie<FeatureFunction>()`初始化CRFModel，而在CRFModel的构造函数中使用的是`new DoubleArrayTrie<FeatureFunction>()`。这个是不是版本升级，不一致问题。

修改相关的DoubleArrayTrie为BinTrie后，tag函数工作正常。

**Comment by hankcs** [comment]
不是，这是为了让用户能够挑选何种trie作为内部的储存结构。如果你想自己加载，不如看看代码其他地方是怎么调用的。

**Comment by flystarhe** [comment]
再请教一个问题，用你的方法可以加载3列或4列数据训练的crf模型吗？

**Comment by flystarhe** [comment]
比如，这种：
毎	k	B
日	k	I
新	k	I
聞	k	I
社	k	I
特	k	B
別	k	I
顧	k	B
問	k	I
４	n	B

**Comment by hankcs** [comment]
可以，虽然没有示例，但支持多列特征模板：

    /**
     * 用来解析模板的正则表达式
     */
    static final Pattern pattern = Pattern.compile("%x\\[(-?\\d*),(\\d*)]");

**Comment by flystarhe** [comment]
去看了一遍，请问是不是直接重新实现一个Table类与之对应就可以了。默认的Table是3列。

如果我要使用2个特征列的model，就实现一个n*4的Table.v。前两列存特征，倒数第二列存原始字符，最后一列始终对应最终的标记。

**Comment by hankcs** [comment]
数量正确，顺序严格按特征模板来。

**Comment by TylunasLi** [comment]
出现该问题，有可能是在调用TestCRF测试代码（用了DoubleArrayTire）后，将生成的bin直接加载到CRFSegment（其中用了BinTire）导致的。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
