### ISSUE TITLE
使用java servlet 实现有点问题。

### ISSUE THREAD

**Issue by lanlover** [hankcs/HanLP#282]
博主，你好，辛苦了。我用java servlet 调用语言包，运行不成功，这是测试代码。调试运行，提示“网站无法显示该页面/  HTTP 500 /最可能的原因是:
•该网站正在进行维护。
•该网站有程序错误。
”
 请教哪里出问题了。

我用的编译器是eclipse-jee-neon-R-win32，   demo在控制台模式下没有问题。这是部分代码

import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.hankcs.hanlp.HanLP;

public class HelloWorld extends HttpServlet implements javax.servlet.Servlet{

```
    public HelloWorld() {
        super();
    }       
    protected void doGet(HttpServletRequest request, HttpServletResponse response) 
        throws ServletException, IOException {
        //response.getWriter().write("Hello");
        request.setCharacterEncoding("utf-8");
        response.setContentType("text/html;charset=utf-8");
        PrintWriter out = response.getWriter();
        String u=request.getParameter("userinput");
        out.println("<br/>输入:"+u);
        out.println("首次编译运行时");
        out.println(HanLP.segment("你好，欢迎使用HanLP汉语处理包！接下来请从其他Demo中体验HanLP丰富的功能~"));
    ....................................
```

**Comment by yueritian** [comment]
使用## 非maven方式部署可正常使用，请检查环境。

**Comment by tigerich** [comment]
这和是否用Maven无关，和HanLP也没有太大的关系。

是否在web容器下面跑得呢？用的什么容器呢？(Tomcat, JBOSS, Jetty...?)

像我这里调试的时候就会用make jetty 运行起jetty容器，就可以跑servlet了。

**Comment by lanlover** [comment]
多谢tigerich我用的是Tomcat.

**Comment by lanlover** [comment]
经过测试，终于找到问题，是因为没有把语言包放到WEB-INF下的“lib”文件夹（必须有） ,lib下主要用于放置第三方jar包，tomcat将自动加载。之前我把包导入到根目录下的reference libraries下（创建servlet自动生成的目录）。忽视了WEB-IN 下的lib目录。
深层次的原因我现在还没有查到，可能是reference libraries是开发阶段用的吧，WEB-IN 下的lib是运行阶段使用的。如果有知道原因的可以告知。谢谢

**Comment by tigerich** [comment]
不需要把语言包放在系统自动加载的路径。语言包由相应HanLP的类自动加载。
加载路径可以用以下文件来设置：
**/src/main/resources/hanlp.properties**

具体文件内容为：（按照你自身情况，替换其中｛｝内容）
```

root={/path/to/your/language/pack/files}
CustomDictionaryPath={/path/to/your/self-defined/language/pack/files}
```

**Comment by zw1987213** [comment]
我想你的问题其实是这样，你设置了你的WEB工程编译环境，这样的代码可能不会编译错误。但是，eclipse却没有设置好打包需要包含的lib包，这样，你打war包时，里面没有包含hanlp的jar包。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
