### ISSUE TITLE
錯誤繁簡轉換字詞

### ISSUE THREAD

**Issue by leeyc0** [hankcs/HanLP#284]
請更新相關字詞表，謝謝

單字轉換：
產/产 (沒有轉換)
溝/沟 (錯誤轉換為钩)
為/为 (沒有轉換)
僱/雇 (沒有轉換)

以下只能使用詞語表，不能單字轉換：
夥伴 -> 伙伴
由於 -> 由于
位於 -> 位于

**Comment by hankcs** [comment]
我最新的代码没有这个错误啊？

        System.out.println(CharTable.convert("產溝為僱"));
        System.out.println(HanLP.convertToSimplifiedChinese("夥伴由於位於"));

产沟为雇
伙伴由于位于

**Comment by leeyc0** [comment]
那可能又是 tokenizer 的問題了。只是原來solr搜尋單字也會出問題這點有點奇怪。

**Comment by hankcs** [comment]
你可以把出现问题的句子丢进com.hankcs.hanlp.tokenizer.TraditionalChineseTokenizer#segment(java.lang.String)试试，我会协助解决的。

**Comment by leeyc0** [comment]
測試了一下，看來是 hanlp-portable-1.2.10.jar 內帶 data 的問題，需要更新，應該沒事了。
