### ISSUE TITLE
CRFmodel计算结果与crf++的crf_test结果不一致。

### ISSUE THREAD

**Issue by liulhdarks** [hankcs/HanLP#285]
CRFmodel加载了crf++ 0.58版本训练出来的模型后，tag后的结果与采用该crf++自带的crf_test计算出来的结果不一样。这是为什么呢，算法有什么不一样的地方吗？从结果来看crf_test的结果要准确很多，CRFmodel计算出来的结果很多是错误的。
`CRFModel model = CRFModel.loadTxt("F:\\studio\\CRF++-0.58\\CRF++-0.58\\example\\model.txt",
                new CRFModel(new DoubleArrayTrie<FeatureFunction>()));
        System.out.println(model);
        Table table = new Table();
        table.v = new String[][]{
            {"微鲸", "ns", null},
            {"创新", "vn", null},
            {"营销",  "n", null},
            {"抢占",  "v", null},
            {"电视",  "n", null},
            {"先机",  "n", null}
        };
        model.tag(table);
        System.out.println(table);`

[crf_train.txt](https://github.com/hankcs/HanLP/files/392253/crf_train.txt)
[crf_test.txt](https://github.com/hankcs/HanLP/files/392252/crf_test.txt)

**Comment by hankcs** [comment]
感谢反馈，

0. 目前CRF相关算法都不是参考CRF++写的。
0. 我知道CRFModel代码是不对的，tag方法的计算结果是贪心而不是全局最优
0. 为此我在CRFSegmentModel中覆写了CRFModel的tag方法
0. 后来工作繁忙，没有及时将这部分解码代码通用化、回写到CRFModel中。另一方面，CRFModel也没有在其他模块排上用场，甚至没有打算将其开放出去。
0. 如果你有兴趣，可以参考CRF++或CRFSegmentModel的tag方法完成这项工作。

**Comment by liulhdarks** [comment]
但是我没看到CRFSegmentModel与CRFModel的tag有什么太大差别，几乎就是把tagSize写死成分词的4，然后加了net[0][idM] = -1000.0; net[0][idE] = -1000.0; 这两个限定。然后CRFModel在回溯时遍历每个tag找最大，变成了写死的int maxTag = net[size - 1][idS] > net[size - 1][idE] ? idS : idE;

**Comment by hankcs** [comment]
那就是我后来回写了，但这版代码依然存在解码问题，需要参考CRF++重写解码算法。

**Comment by liulhdarks** [comment]
好的，谢谢，我去看看crf_test的源码。希望你有时间也能解决一下这个解码的问题。

**Comment by XiaoLiuAI** [comment]
@liulhdarks   有一个很明显的问题, `atomSegmentToTable` 方法中把数字替换成了M, 把英文字母替换成了W,这些特征在crf++的原始训练数据中是不存在,或者不一致的. 那么用类似2017的数据训练出来的模型在遇到替换之后的文本的时候,必然会出现结果不一致的情况. 

@hankcs 在例子 `testPrepareCRFTrainingCorpus` 中并没有体现这种替换,那么是否应该在文档中说明或者提供一致的例子?

**Comment by hankcs** [comment]
@XiaoLiuAI `testPrepareCRFTrainingCorpus`与解码代码是一致的，其中调用了`com.hankcs.test.model.TestCRF#compile`，已经做了转换了。

文档中的确应该提一句，感谢建议。

**Comment by XiaoLiuAI** [comment]
@hankcs 并不是完全一样的逻辑. `com.hankcs.test.model.TestCRF#compile` 里面的逻辑是通过pos来决定是否进行M和W的替换. 但是在CRFSegment里面,pos是不存在的,是通过字符本身来进行替换,用正则表达式来概括说明就是 `[0-9][0-9\\.%]*` 替换为M, `[a-zA-Z ]+`替换为W. 

在compile中,像人民日报里面的"2017年"的pos就不是m,不会被替换,而"1万"则会被替换. 而解码的时候"2017年"会被替换成"M年","1万"会被替换成"M万".这样很明显会造成training时候的输入和解码时候的输入有系统性的偏差.

**Comment by hankcs** [comment]
@XiaoLiuAI 的确是的，破坏了模型的一致性。我记得当时是因为有用户反映数词和英文有被截断的现象，所以做了这个预处理。如果要取消的话，不如把`com.hankcs.hanlp.seg.CRF.CRFSegment#atomSegmentToTable`改成非静态方法给子类重载掉。是否需要什么样的预处理都让子类决定。

**Comment by XiaoLiuAI** [comment]
@hankcs 数字和英文截断的问题来源于人民日报数据集. 个人建议是,保持训练逻辑/模型和数据集的一致性,然后在crf的结果上应用规则进行修正. 就像类似crf结果上加入词典进行修正的流程设计.

**Comment by hankcs** [comment]
@XiaoLiuAI 好的，以后遇到这种问题会把规则放到模型之后处理的。就目前而言，代码与旧模型匹配吧。

**Comment by shibing624** [comment]
CRF模型之后，会添加这种对数词、英文、日期的优化处理的吗？

**Comment by tangjie010101** [comment]
@liulhdarks CFR解码问题参考后解决了吗

**Comment by zhaodp** [comment]
@hankcs 请问CRF的解码跟CRF++一致了吗现在？

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
