### ISSUE TITLE
HanLP.java 对CustomDictionaryPath 里面的路径设置错误。

### ISSUE THREAD

**Issue by tigerich** [hankcs/HanLP#286]
HanLP/src/main/java/com/hankcs/hanlp/HanLP.java

请按以下修改，否则成功无法加载。

    -                String[] pathArray = p.getProperty("CustomDictionaryPath", "dictionary/custom/CustomDictionary.txt").split(";");
    +                String[] pathArray = p.getProperty("CustomDictionaryPath", "data/dictionary/custom/CustomDictionary.txt").split(";");

**Comment by hankcs** [comment]
配置文件的作用是告诉HanLP数据包的位置，只需修改第一行

root=usr/home/HanLP/
为data的父目录即可，比如data目录是/Users/hankcs/Documents/data，那么root=/Users/hankcs/Documents/ 。

**Comment by hankcs** [comment]
谢谢指正，这样做了之后统一性更高。

**Comment by hankcs** [comment]
你也可以直接提交pull request的，这样我就不会看错了。
