### ISSUE TITLE
data-for-1.2.10.zip 鍵結失效

### ISSUE THREAD

**Issue by leeyc0** [hankcs/HanLP#288]
https://github.com/hankcs/HanLP/releases
新版数据包：data-for-1.2.10.zip

連結好像已經不在網盤

**Comment by hankcs** [comment]
这又是大陆的中国特色吧。
<img width="313" alt="2016-08-03 5 50 04" src="https://cloud.githubusercontent.com/assets/5326890/17361477/4e87f0c2-59a3-11e6-987d-a258091bcc0b.png">


更新了：http://pan.baidu.com/s/1geWzSNx
