### ISSUE TITLE
求助：时间相关分词问题

### ISSUE THREAD

**Issue by tigerich** [hankcs/HanLP#289]
**原句：“我想在明天上午9点听一个儿童故事”**
 
- 如果用默认的分词方法：HanLP.newSegment() 获得结果为：
> [我/z, 想/s, 在/dg, 明/ad, 天上/i, 午/l, 9/m, 点/q, 听/s, 一个/Rg, 儿童故事/ngsch]

- 如果用CRFSegment结果变为：
> [我/z, 想/s, 在/dg, 明天/i, 上午/tam, 9/nz, 点/q, 听/s, 一个/Rg, 儿童故事/ngsch]

**如果原句改为：“我想在明天上午九点听一个儿童故事”**
- 如果用默认的分词方法:
[我/z, 想/s, 在/dg, 明/ad, 天上/i, 午/l, 九/m, 点/q, 听/s, 一个/Rg, 儿童故事/ngsch]

- 如果用CRFSegment：
> [我/z, 想/s, 在/dg, 明天/i, 上午九/nz, 点/q, 听/s, 一个/Rg, 儿童故事/ngsch]

另外，我在分词中采用了个性化的词性如下：

```
  CustomDictionary.add("故事", 	"ngs 1024");
  CustomDictionary.add("儿童故事", "ngsch 2048");
  CustomDictionary.add("昨天", 	"tzt 1024");
  CustomDictionary.add("今天", 	"tjt 1024");
  CustomDictionary.add("明天", 	"tmt 1024");
  CustomDictionary.add("后天", 	"tht 1024");
  CustomDictionary.add("上午", 	"tam 1024");
  CustomDictionary.add("下午", 	"tpm 1024");
```

请问，**如何能正确分出时间呢？**
比如能分出： [明天 上午 9 点] 

万分感谢～

**Comment by tigerich** [comment]
貌似如果能先把“九”正规化为“9” 就可以较好实现。但是如添加这样的转换呢？
我修改了一下ChartTable不起作用呢。另外最好能提供custom配置方式。

**Comment by hankcs** [comment]
感谢反馈，现在可以自定义正规化表了：
https://github.com/hankcs/HanLP/commit/28c6586e702cbdf614165d83f66f11d9a413e285

**Comment by tigerich** [comment]
感谢！ 追问一下，为啥默认的分词方法不能正确分词，即使是我用了自定义的单词（像‘明天’、‘上午’之类）？如果只用CRFSegment分词有什么问题呢？

**Comment by hankcs** [comment]
你用的是98年的小模型，换成2014的就没问题了。

[我/rr, 想/v, 在/p, 明天/t, 上午/t, 九/m, 点/qt, 听/v, 一个/mq, 儿童/n, 故事/n]

**Comment by tigerich** [comment]
请问如何换成2014年的模型呢？

我是已经下载了data-for-1.2.10.zip包（有625.8MB）后解开，并且让项目指向该包解开后的目录，这是不是就是已经用上了2014年的模型呢？如果不是，该如何设置？

谢谢～

**Comment by tigerich** [comment]
发现删除了bin文件之后就可以了。谢谢！
