### ISSUE TITLE
按照你手册上提供方法添加人名误判不成功

### ISSUE THREAD

**Issue by michaelliu03** [hankcs/HanLP#29]
按照你提供的方法，修改了data /dictionary / person / nr.txt，加入一个新词条，但是系统依然误判。
比如：“万余元” 本不该是人名，添加该词条，但是最终结果依然误判！求解决方法。

**Comment by yuchaozhou** [comment]
确定添加新词条后也一同清理了*.bin词典缓存？

**Comment by michaelliu03** [comment]
多谢指点！^_^

**Comment by michaelliu03** [comment]
尝试清除*.bin 词典缓存，添加了多条词条到data /dictionary / person / nr.txt 中，
目前在结果中只有一词条进行误判处理，其余依旧误判。求解决方法。

**Comment by yuchaozhou** [comment]
把你测试的结果贴一下，然后再详细描述一下问题。

**Comment by hankcs** [comment]
万余元 A 1

应该就可以了，请说明详情

**Comment by hankcs** [comment]
其实这种词语还有一个办法，余元可以作为一个量词 mq 嘛，搜狗拼音也能打出来说明这个词语也比较常用了

**Comment by michaelliu03** [comment]
博主您好！我查了您相关的帮助和代码，试图修改nr.txt.比如我在此字典中加入了
万余元 A 1  钱是 A 1 应对其 A 1   方就其 A 1   微智 A 1  途歌 A 1  曾两度 A 1 鹿晗暖 A 1 帅比萌 A 1
么? A 1 .........等词语来试图提高对人名识别的精度，但是我跑出来的结果是，加入的词语有一部分进行了处理，有一部分没有进行处理。比如我之前给的例子中“万余元 ” 就被处理了 。未被处理的词语比如我在这里提到的“钱是 ”，“ 应对其” 等应该怎么去除掉。感谢您的回复！

**Comment by hankcs** [comment]
0. 抱歉现在才回复
0. 鹿晗暖是一个收录在data/dictionary/custom/人名词典.txt中的人名，如果你认为不是人名，可以删掉，或者不加载这个用户词典
0. 从代码的角度上讲，不可能存在一部分有效一部分失效的情况
0. 请保证每个词语都换行，同时删除了data/dictionary/person/nr.txt.trie.dat和data/dictionary/person/nr.txt.value.dat这两个缓存文件
0. 你提交的这部分bad case我已经整合到nr词典中了，你可以check out最新词典然后重建缓存，跑如下test代码，肯定没问题的。

```
        String[] textArray = "万余元 A 1 钱是 A 1 应对其 A 1 方就其 A 1 微智 A 1 途歌 A 1 曾两度 A 1 帅比萌 A 1".split("A 1");
        System.out.println(Arrays.toString(textArray));
        for (String text : textArray)
        {
            List<Term> termList = StandardTokenizer.segment(text);
            System.out.println(termList);
            for (Term term : termList)
            {
                assertEquals(false, term.nature == Nature.nr);
            }
        }
```
