### ISSUE TITLE
使用语句依赖项分析数组越界

### ISSUE THREAD

**Issue by DecstionBack** [hankcs/HanLP#295]
对于文章长度比较短的，使用自带的依存关系处理没有任何问题，但是对于长文章却提示数组越界问题，请问一下应该怎样使依存关系处理长的文章？现在想到的一个方法是将长文章分几段进行处理，请问一下您有没有好的方法解决对于长文本的依存关系处理？谢谢~

**Comment by hankcs** [comment]
https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE
