### ISSUE TITLE
中文数字分词效果不佳

### ISSUE THREAD

**Issue by tigerich** [hankcs/HanLP#296]
比如像如下分词
> 一百二十五乘以十二等于几
结果是：

> [一百二十五/m, 乘以/matml, 十/m, 二等/b, 于/p, 几/d]

如果采取字符转换：一：1；二：2；。。。九：9；则不利于转换成阿拉伯数字（因为像一万零几的情况不好处理）。
所以要是分词能把中文切出来，像：
> [一百二十五/m, 乘以/matml, 十二/m等于/mateq, 几/d]
就会比较理想。

貌似**等于**在这个句子中无法很好被自定义词性标准切出来, 而“二等”如果在一起很容易被标准为'b'词性，但是等于的自定义词性的词频已经是设置很高了，而且如果把**等于**排到第一个或者在它的前面加一个”的结果“又可以被标准了。

请问，这样的问题该如何解决呢？

谢！！
R

**Comment by hankcs** [comment]
感谢反馈，

0. 目前的数词识别是在词典全词图生成之后进行，详见com.hankcs.hanlp.seg.WordBasedGenerativeModelSegment#GenerateWordNet
0. 你可以将其提前，或专门写个数词识别的方法，利用CharType，这是很简单的事情。
0. 我不建议这样做，因为这会拖慢速度，你可以比较一下。

**Comment by tigerich** [comment]
经过源码分析，我感觉问题是因为核心词库对数词类不敏感（比如**十二**对核心词库来说应该是新词），导致粗分词的结果是“二等”，而不是“十二”，“等于”。因此我改成用CRFSegment分词，能正确分出“十二”来。但是词性却无法标注为“m”而是“nz”。这一块如何解决呢？

**Comment by hankcs** [comment]
0. CRFSegment的词性问题可以加个后处理逻辑
0. CharType的作用是获得char的类型，与CharTable不同

**Comment by tigerich** [comment]
发现对CoreNatureDictionary.txt添加该类数词就能解决问题。
