### ISSUE TITLE
java servlet调用依赖分析，除了加载配置文件。还需要显式输出一下才可以

### ISSUE THREAD

**Issue by lanlover** [hankcs/HanLP#298]
博主，你好。感谢你的付出。我在调用依赖分析的时候。发现
                        Properties properties = new Properties();
                        //第一行代码
            properties.load(getServletContext().getResourceAsStream("/WEB-INF/hanlp.properties"));
                        //第二行代码
            out.println("root="+properties.getProperty("root"));
                         //第三行代码
                  如果只有第一行和第二行代码，调试不成功。如果执行一遍第三行代码，调试就通过。
                   如果调试通过，注释第三行代码，依然可以通过。不知道这个是怎么个原理。

**Comment by hankcs** [comment]
0. 我不清楚你的加载逻辑，HanLP本身的加载逻辑通过了从web到android的测试。
0. 如果加载配置文件对你来说是个麻烦事，你可以用com.hankcs.hanlp.utility.Predefine#HANLP_PROPERTIES_PATH=hanlp.properties的路径解决。

**Comment by lanlover** [comment]
回复很快，赞
第一，你说的加载逻辑是这样，就是初始化阶段，我发现做普通的分词没有问题，就是做依赖解析的时候不成功。后来查了一篇你的文章，在jsp/servlet中有三种办法。我就用了其中那种
                        Properties properties = new Properties();
			properties.load(getServletContext().getResourceAsStream("/WEB-INF/hanlp.properties"));
                        方法，但是依旧没有调试通过。后来我想测试一下倒底这个属性文件加载没有，就用了输出语句，把这个属性文件里的第一个属性输（out.println("root="+properties.getProperty("root"));）。结果再测试的时候就发现可以做依赖解析了。
第二你说的这个办法，对我来说还有点陌生，我也是刚接触java。能否给个这方面的背景知识链接。我学习一下。
再次表示感谢！

**Comment by hankcs** [comment]
我的建议是你先看看web容器启动时的错误日志，在com/hankcs/hanlp/HanLP.java里面打些日志，这样才能明确问题，形成有效的交流。

**Comment by lanlover** [comment]
恩，知道了。其实刚开始我也准备看一下日志，可是发现\apache-tomcat-9.0.0.M8-windows-x86\apache-tomcat-9.0.0.M8\logs 这个里面的日志都是几天前的，没有当前的日志。比如今天是8月12号，里面的日志最近的是catalina.2016-08-09.log。不知道是不是日志的地方没找对地方。

**Comment by crapthings** [comment]
com.hankcs.hanlp.utility.Predefine#HANLP_PROPERTIES_PATH=hanlp.properties

这什么语法

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
