### ISSUE TITLE
java Servlet 中 out.println(word.HEAD);无法输出

### ISSUE THREAD

**Issue by lanlover** [hankcs/HanLP#299]
对于CoNLL格式，很奇怪，其他字段都可以输出，唯独HEAD，加了这行代码就错误。
             CoNLLSentence sentence = HanLP.parseDependency(""+u);
            //out.println(sentence);
            // 可以方便地遍历它
           for (CoNLLWord word : sentence)
            {
                out.println(word.LEMMA);
                out.println(word.CPOSTAG);
               // out.println(word.HEAD);
                out.println(word.DEPREL);  
            }

**Comment by hankcs** [comment]
+u是什么？你得给我完整可运行的代码。

**Comment by lanlover** [comment]
u 是用户输入的句子 ，抱歉在测试，所以取名字的时候都没认真写。
测试代码如下
import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.hankcs.hanlp.HanLP;
import com.hankcs.hanlp.seg.Segment;
import com.hankcs.hanlp.seg.common.Term;
import com.hankcs.hanlp.corpus.dependency.CoNll.CoNLLSentence;
import com.hankcs.hanlp.corpus.dependency.CoNll.CoNLLWord;

import java.util.Properties;

public class HelloWorld extends HttpServlet implements javax.servlet.Servlet{
		public HelloWorld() {
			super();
		}   	
	protected void doGet(HttpServletRequest request, HttpServletResponse response) 
		    throws ServletException, IOException {
			request.setCharacterEncoding("utf-8");
			response.setContentType("text/html;charset=utf-8");
			PrintWriter out = response.getWriter();
			String u=request.getParameter("userinput");
			out.println("<br/>输入:"+u);
			//测试分词
			out.println(HanLP.segment(""+u));
			//HanLP.Config.enableDebug();
			//加载配置文件
			Properties properties = new Properties();
			properties.load(getServletContext().getResourceAsStream("/WEB-INF/hanlp.properties"));
			out.println("root="+properties.getProperty("root"));			
			//依赖分析	
			CoNLLSentence sentence = HanLP.parseDependency(""+u);
	        //out.println(sentence);
	        // 可以方便地遍历它
	       for (CoNLLWord word : sentence)
	        {
	            out.println(word.LEMMA);
	            out.println(word.CPOSTAG);
	            out.println(word.HEAD);
	            out.println(word.DEPREL);	           
	           
	        }	       	
		
		}  	
		
        	protected void doPost(HttpServletRequest request, HttpServletResponse response) 
		    throws ServletException, IOException {
			// TODO Auto-generated method stub
		} 
}

**Comment by hankcs** [comment]
我要的是到底什么句子

**Comment by lanlover** [comment]
。。。博主，我是按你要求提供代码的呀。句子就是测试用句啊，比如“城建成为外商投资青海的新热点”。加了那句out.println(word.HEAD);浏览器就显示错误了。

**Comment by lanlover** [comment]
语句就是普通的测试语句。比如“城建成为外商投资青海的新热点”
我又测试了一下，如果加了那句out.println(word.HEAD);，点击 run as 运行后，在编译器内部的弹出的浏览器提示出错。但是如果我把整个url地址拷贝到单独启动的浏览器地址栏里比如http://localhost:8182/serletTest/NewFile.html直接在浏览器里运行，再输入语句 ，提交后浏览器返回的就没有问题。

**Comment by hankcs** [comment]
有些事情要明确一下

0. 首先，我不管你是servlet还是什么地方运行。
0. 如果句法分析模块有bug，那么它肯定能在本地触发这个bug。如果你本地无法复现这个bug，那么就是你servlet里面写的不对。
0. 你问问题要考虑听者的感受，听者不会专门为你搭建一个web环境，去测试这么乱的一段代码。
0. 如果你没怎么注意这个习惯，请阅读一下：https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE

然后回到这个问题，这句话根本不会触发任何bug：

```
CoNLLSentence sentence = HanLP.parseDependency("城建成为外商投资青海的新热点");
        System.out.println(sentence);
        // 可以方便地遍历它
        for (CoNLLWord word : sentence)
        {
            System.out.printf("%s --(%s)--> %s\n", word.LEMMA, word.DEPREL, word.HEAD.LEMMA);
        }
        // 也可以直接拿到数组，任意顺序或逆序遍历
        CoNLLWord[] wordArray = sentence.getWordArray();
        for (int i = wordArray.length - 1; i >= 0; i--)
        {
            CoNLLWord word = wordArray[i];
            System.out.printf("%s --(%s)--> %s\n", word.LEMMA, word.DEPREL, word.HEAD.LEMMA);
        }
```

输出

```
1	城建	城建	n	n	_	2	主谓关系	_	_
2	成为	成为	v	v	_	0	核心关系	_	_
3	外商投资	外商投资	nz	nz	_	4	定中关系	_	_
4	青海	青海	ns	ns	_	7	定中关系	_	_
5	的	的	u	ude1	_	4	右附加关系	_	_
6	新	新	a	a	_	7	定中关系	_	_
7	热点	热点	n	n	_	2	动宾关系	_	_

城建 --(主谓关系)--> 成为
成为 --(核心关系)--> ##核心##
外商投资 --(定中关系)--> 青海
青海 --(定中关系)--> 热点
的 --(右附加关系)--> 青海
新 --(定中关系)--> 热点
热点 --(动宾关系)--> 成为
热点 --(动宾关系)--> 成为
新 --(定中关系)--> 热点
的 --(右附加关系)--> 青海
青海 --(定中关系)--> 热点
外商投资 --(定中关系)--> 青海
成为 --(核心关系)--> ##核心##
城建 --(主谓关系)--> 成为
```

如果你仍然认为该模块有问题，按照我示范给你的方式，用最少的代码，把问题展示出来给大家看。

**Comment by lanlover** [comment]
好的，谨听博主教诲。不同的编译环境会遇到不同的问题，很多与你提供的系统没有关系。只是环境设置或其它设置的问题。作为初学者有时就是瞎子抹黑，不知道该如何继续下去。希望楼主别误解啊：）我只是有时希望专家给个思路或点拨一下。这样会少走很多弯路。

**Comment by hankcs** [comment]
0. “不同的编译环境会遇到不同的问题”，该问题对Java而言是不存在的。对于HanLP这种算法密集的库，只要IO不出问题，放到任何环境的运行结果都是一样的。不可能在本地1+1=2，到了web容器里面就1+1=3了。
0. 我并不是专家，也没有针对任何人。我只是希望大家能够先打好基本功，再上来做应用
0. 特别是NLP技术，让本应该很昂贵的技术落入很低的门槛，是好事，也是坏事

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
