### ISSUE TITLE
请问该如何切分*/

### ISSUE THREAD

**Issue by timlincool** [hankcs/HanLP#3]
输入  鱼300g*2/组

使用  HanLP.newSegment() 
切分结果 [鱼/n, 300g*2//nx, 组/n]

使用 AhoCorasickSegment().enablePartOfSpeechTagging(true)
切分结果 [鱼/nz, 300g*2//nx, 组/nz]

使用 NShortSegment()
切分结果 [鱼/n, 300g*2//nx, 组/n]

都是  [鱼, 300g*2/, 组]

请问该如何配置才能切出
[鱼, 300g, * ,2,  / , 组]  or  [鱼, 300 , g, *,2 , / , 组] ?

/////////////////////
补上 鱼300克*2/组的情形

 [鱼/n, 300/m, 克/q, *2//nx, 组/n]
仍有 *2/ 切为一个词的情况发生

**Comment by hankcs** [comment]
已优化。

*号的确应该被视作分隔符，而不是单字节字符。

**Comment by timlincool** [comment]
不好意思，刚测试过还是有些问题

鱼300克*2/组
分为
[鱼/nz, 300/m, 克/nz, */w, 2//nx, 组/nz]

2跟/ 会连在一起  

或许可以改为配置的方式，让使用者决定需要切分哪些字符
不过可能就要有能生成CharType.dat.yes的源码了
