### ISSUE TITLE
自定义词典似乎没用

### ISSUE THREAD

**Issue by jdb110** [hankcs/HanLP#30]
System.out.println(CustomDictionary.add("高大上","a 1024"));
termList = HanLP.segment("外观绝对高大上，不信的是没见过.");
System.out.println(termList);

输出结果

[外观/n, 绝对/d, 高大/a, 上/f, ，/w, 不信/v, 的/ude1, 是/vshi, 没/d, 见过/v, ./w]

**Comment by yuchaozhou** [comment]
只在词典添加一词，在分词第一阶段会切分出来，没有问题。
问题出在ngram词频上，删掉ngram缓存，你需要将"绝对@高大上"添加入ngram词典。
不过，还存在一个问题，ngram加载缓存时，@hanckcs 对产后接续词进行了是否在核心词典的检测，如果在则加载，若不在则跳过。所以，此处直接用CustomDictionary还存在问题，ngram接续词不会成功加载。
这点或许还是需要后续开发完善的。

目前直接将“高大上”加入核心词典后，问题解决。

[外观/n, 绝对/d, 高大上/a, ，/w, 不信/v, 的/ude1, 是/vshi, 没/d, 见过/v, ./w]

**Comment by jdb110** [comment]
增加个CoreNatureDictionary.add的方法就好了

**Comment by jdb110** [comment]
建议：增加个CoreNatureDictionary.add的方法，CoreDictionaryPath可以向CustomDictionaryPath一样追加多个词典。

**Comment by hankcs** [comment]
问题的确如@yuchaozhou所言，在于缺少NGram接续。所以需要

0. 把词加到CoreNatureDictionary.txt里
0. 把接续加到CoreNatureDictionary.ngram.txt里

带有Core字样的是训练出来的模型，不太希望用户增删，而且双数组tire动态增删代价非常大。所以不打算实现CoreNatureDictionary.add
