### ISSUE TITLE
使用AhoCorasickDoubleArrayTrieSegment分词，自定义词典加载成功，自定义词典中有一条为“酸 n 1000”和“碱 n 1000” “金属 n 1000”，如果待分词的句子为“酸的”，分词结果为“酸的 nz”。如果是“金属的”，结果就正常，为“金属 n  的nz”，经测试的，自定义词典中有单个字的情况都有这个bug

### ISSUE THREAD

**Issue by dongaotong** [hankcs/HanLP#302]

**Comment by hankcs** [comment]
严格上来讲，这并不属于bug，而是特意设计为这种功能的。
0. 如果词典中没有该字符的词条，则相邻相同类型的字符合并成为一个词，如汉字和汉字合并，字母和字母合并
0. 如果你要去掉这种特性，要么在词典中加入这个单字（从Core词典拷贝所有单字到你的词典，很简单）
0. 要么修改com.hankcs.hanlp.seg.Other.AhoCorasickDoubleArrayTrieSegment第77行，用字符填充wordNet。

**Comment by dongaotong** [comment]
首先谢谢hankcs的回复
第一，你第一条中提到“如果词典中没有该字符的词条”但是我的自定义词典中已经有了单字----“酸 n 1000”，只是和core词典中词性不同，仍然有这种现象。
第二，由于对分词算法不是太了解，看了好久AhoCorasickDoubleArrayTrieSegment也没看明白怎么修改。
这个对我们这个项目很重要，我也研究hanlp研究了好久，真的不想再去研究其他的分词系统了。可不可以麻烦你说具体一些，谢谢了

**Comment by dongaotong** [comment]
另外我发第一个帖子时，我使用的hanlp版本是1.2.10，今天刚换了这个1.2.11，这两个版本中的AhoCorasickDoubleArrayTrieSegment第77行都没有出现wordNet。真不知道怎么修改，可能是对里面算法不了解的原因。

**Comment by hankcs** [comment]
segment.enablePartOfSpeechTagging(false);

或者打补丁：

[local_history.patch.zip](https://github.com/hankcs/HanLP/files/428851/local_history.patch.zip)

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
