### ISSUE TITLE
自定义词典分词问题

### ISSUE THREAD

**Issue by GuanGuanHuang** [hankcs/HanLP#303]
遇到这么一个问题. 请指教
输入 "微搜集成手册"     分词结果   [微, 搜集, 成, 手册]
如果把  "微搜" 加入自定义词典中.  分词结果还是这样.
在 WordBasedGenerativeModelSegment 中的GenerateWordNet方法 生成词网,注释了自定义分词的代码.   如果开启后. 可以得到分词结果  [微搜, 集成, 手册].   这段代码开启是否有其他影响
![image](https://cloud.githubusercontent.com/assets/4652356/17685809/050db75a-639a-11e6-9e72-58464762d8bf.png)

在生成词网后再引入自定义词典是不是就只能对未成词的字进行合并了
if (config.useCustomDictionary)
 {
        combineByCustomDictionary(vertexList);
}

**Comment by hankcs** [comment]
凭我的记忆，这里的代码开启后用户词典的优先级会变成最高，即用户词典中的词一定会分出来。如果这是你的需求，开启后并无不妥。
后面的combineByCustomDictionary就可以注释掉了。

**Comment by TylunasLi** [comment]
这个问题属于“未登录词交集型歧义”。即又有未登录词（Core词典中没有的词），它的字又和前后有交错。
BiGram模型分词算法的处理策略不能处理“未登录词交集型歧义”，
这段代码之所以默认注释掉，是因为一个比较复杂的原因：
HanLP中如果开启了命名实体识别再添加自定义词典，为保证自定词典词能分出来，给了它们很高的概率。
开启这段代码。就会导致自定义词典在计算时概率奇高，把原本正确的结果全搞乱了。
例如电力服务中有“户表”一词，开启这段代码，就会导致出现概率更高的“用户表示” 分词为 “用 户表 示”。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
