### ISSUE TITLE
Hanlp Segment类seg分词方法报内存溢出错误

### ISSUE THREAD

**Issue by JoyChung** [hankcs/HanLP#305]
在使用Hanlp对获取的文本进行预处理的时候，当处理的是重复的相同内容文本时正常，当处理大量不同文本时报内存溢出的错误。
`				for (File txt : files) {
					content = readtxt(txt.getAbsolutePath());
					// 分词
					/*System.out.println(content);*/
					word_arr = StopWordsHandler.mPhraseDel(segmentNoTag.seg(content));
				/*	word_arr = new ArrayList<String>();
					for (int i = 0; i < 10000; i++){
						word_arr.add("大冒险");
					}*/
					//System.out.println("content:"+content+"；size："+word_arr.size());
					fileContent.add(StringUtils.strip(word_arr.toString().replaceAll(",", "\t"),"[]")+"\t");
					count++;
				}`
如果把content换成固定字符串就不会报错。请问是什么原因呢？

**Comment by hankcs** [comment]
你把这么多文件拼凑成这么大一个字符串，是不对的。
按文件或按行处理。

**Comment by JoyChung** [comment]
我是按每个文件处理分词的，只是在分词之后才存在一起，每个文件的大小不过三四行。

**Comment by JoyChung** [comment]
我需要对每个文件进行按行处理么？但是我把content换成其中一个文件的内容，运行2000次循环也不会报错，就是用content就不行

**Comment by hankcs** [comment]
每个文件进行按行处理

**Comment by JoyChung** [comment]
可是我在执行读取文件后，把content换成两到三个文件内容拼成的字符串也不会报错呀

**Comment by hankcs** [comment]
事实上，你给定一个JVM内存，比如说256MB吧，总有一个足够长的字符串能让任何程序OOM，更别说分词器了。
你的这些文本文件中肯定有一个达到了这个阈值。

**Comment by JoyChung** [comment]
嗯嗯，找到了，那我设个阈值吧，谢谢你的耐心回答^-^~~
