### ISSUE TITLE
关于模型问题

### ISSUE THREAD

**Issue by cindyShao** [hankcs/HanLP#306]
@hankcs 您好。 请问输入模型是否可以缩减尺寸？在Android设备上跑离线版本，发现使用依存语法接口的时候，载入模型有800M大小，导致设备不能正常运行。请问模型加载过程是用到相应接口的时候再加载还是初始化的时候统一加载？

**Comment by hankcs** [comment]
0. 是用到相应接口的时候再加载
0. 但依存句法模型光文件都有几百兆，在Android设备上还是够呛的，不知道Android单app的内存限制是多少

**Comment by cindyShao** [comment]
1、对于手机来说，android手机单app内存限制是512M，最大可以达到1G，不过一般不推荐使用超过512M。加载依存句法模型之后，光首次加载就超过800M了，程序显示out of memory。

**Comment by cindyShao** [comment]
请问能否通过自己训练模型，达到减小模型占用的目的？

**Comment by cindyShao** [comment]
@hankcs

**Comment by hankcs** [comment]
0. 你说首次加载就超过800M了，是否意味着加载成功？
0. 如果加载成功的话你应该限制一下句子长度
0. 重新训练不现实，你没有语料
0. 有几个小模型，maxent之类的，但效果不好

**Comment by cindyShao** [comment]
1.首次加载不包括依存语法调用，只是分词功能。只是在后面的依存语法调用中，Android系统显示out of memory。
2.句子长度应该限制在多少长度以下？复杂度有要求否？

new question：
1.发现在使用HMM segment的时候，new Segment对象花了8.298秒的时间，这个时间延迟是不是太大？

**Comment by hankcs** [comment]
0. 分词用不了那么多内存的，你是否在用CRF分词。或者你看到的应该包含了其他Android相关组件占用的内存
0. 可以信手给个，100字。
0. HMM2模型同样很大

**Comment by cindyShao** [comment]
如果我有语料，如何进行训练得到模型？您的介绍中并未提及。非常感谢！

**Comment by hankcs** [comment]
NNParser训练部分并没有移植。
