### ISSUE TITLE
可以提供生成语料库的测试用例吗？

### ISSUE THREAD

**Issue by shibing624** [hankcs/HanLP#311]
我想生成自己特定行业领域的词库，需要用到hanlp的词库生成工具，生成类似CoreNatureDictionary.ngram.txt和CoreNatureDictionary.txt的文件。希望能提供代码NatureDictionaryMaker.java下 139行列出的“D:\JavaProjects\CorpusToolBox\data\2014”路径下的文件，我方便整理语料格式。

**Comment by hankcs** [comment]
https://github.com/hankcs/HanLP/wiki/%E8%AE%AD%E7%BB%83%E5%88%86%E8%AF%8D%E6%A8%A1%E5%9E%8B

**Comment by shibing624** [comment]
i see,thx

**Comment by shibing624** [comment]
请把现在Hanlp未解决的中文分词问题以及已经知道还未处理的问题罗列出来，比如：专业术语识别、缩略语识别、新词发现问题，以及句法分析、情感分析还有待完善的问题。希望能为开源NLP贡献一份力。

**Comment by hankcs** [comment]
太感谢了，欢迎参与改进，贡献你的力量：

https://github.com/hankcs/HanLP/wiki/ToDoList
