### ISSUE TITLE
用户词库的问题

### ISSUE THREAD

**Issue by Icomming** [hankcs/HanLP#312]
目前自带的CustomDictionary.txt.bin是17M多，我在CustomDictionary.txt中添加自定义词也可以起作用，但是新的自动生成的CustomDictionary.txt.bin只有685K，而且分词效果下降了，请问17M的CustomDictionary.txt.bin是如何生成的？还是需要运行什么函数？

**Comment by hankcs** [comment]
#自定义词典路径，用;隔开多个自定义词典，空格开头表示在同一个目录，使用“文件名 词性”形式则表示这个词典的词性默认是该词性。优先级递减。
#另外data/dictionary/custom/CustomDictionary.txt是个高质量的词库，请不要删除
CustomDictionaryPath=data/dictionary/custom/CustomDictionary.txt; 现代汉语补充词库.txt; 全国地名大全.txt ns; 人名词典.txt; 机构名词典.txt; 上海地名.txt ns;data/dictionary/person/nrf.txt nrf

**Comment by Icomming** [comment]
非常感谢，是我路径没设对，问题解决。
