### ISSUE TITLE
文本中有英文时，分词结果有问题

### ISSUE THREAD

**Issue by linker1119** [hankcs/HanLP#313]
hello

world
上面是原始文本（存储在一个文件），中间有个换行。分词结果为：
<hello

world>
尖括号括起来的是一个词，没有分词hello和world。
直接使用的HanLP.segment方法
如何解决？

**Comment by hankcs** [comment]
感谢反馈，临时解决方案：

CharType.type['\n'] = CharType.CT_DELIMITER;
System.out.println(HanLP.segment("hello\n" + "world"));

**Comment by hankcs** [comment]
已解决https://github.com/hankcs/HanLP/commit/0a51c90f4c12707d0b34643dae98dca64bd38c9a
