### ISSUE TITLE
分词中出现了漏字现象, 是否为bug

### ISSUE THREAD

**Issue by cicido** [hankcs/HanLP#319]
在不采用日文姓名识别的情况下，对“北川景子参演了林诣彬导演的《速度与激情3》” 进行分词，
结果为：
“[北川/nr, 景/ng, 参演/v, 了/ul, 林诣彬/nr, 导演/n, 的/uj, 《/w, 速度/n, 与/p, 激情/n, 3/m, 》/w]”
发现‘子’字丢失。

**Comment by hankcs** [comment]
请问版本号

**Comment by hankcs** [comment]
[北川景子/nrj, 参演/v, 了/ul, 林诣彬/nr, 导演/n, 的/uj, 《/w, 速度/n, 与/p, 激情/n, 3/m, 》/w]
[林志玲/nr, 亮/v, 相/d, 网友/n, :/w, 确定/v, 不是/c, 波/j, 多/m, 野/b, 结/v, 衣/ng, ？/w]
[龟/n, 山/n, 千/m, 广/a, 和/c, 近/a, 藤/n, 公园/n, 在/p, 龟/n, 山/n, 公园/n, 里/f, 喝酒/v, 赏/v, 花/v]

        
String[] testCase = new String[]{
                "北川景子参演了林诣彬导演的《速度与激情3》",
                "林志玲亮相网友:确定不是波多野结衣？",
                "龟山千广和近藤公园在龟山公园里喝酒赏花",
        };
        Segment segment = HanLP.newSegment();
        for (String sentence : testCase)
        {
            List<Term> termList = segment.seg(sentence);
            System.out.println(termList);
        }

**Comment by hankcs** [comment]
你可能改了什么地方

**Comment by cicido** [comment]
版本1.3.0有这种问题，1.3,1分词没有，已测试。

**Comment by hankcs** [comment]
感谢反馈，1.3.1修复了1.3.0的自定义词典的合并逻辑
