### ISSUE TITLE
如何添加新的停用词（还是不行）

### ISSUE THREAD

**Issue by newthis** [hankcs/HanLP#32]
我在dictionary目录下的默认停用词文件中添加新的停用词，重新运行之后发现新的停用词没有去掉。
如果先删除缓存文件再添加词语也不行，但按照这种方法添加自定义词语是有效的，但添加停用词不行。

**Comment by hankcs** [comment]
https://github.com/hankcs/HanLP/issues/28#issuecomment-117935418
