### ISSUE TITLE
标准分词，最短路分词，N最短路分词的区别

### ISSUE THREAD

**Issue by konghuarukhr** [hankcs/HanLP#321]
我原来的理解是：
标准分词就是用动态规划去算词图的最短路径
最短路分词就是用Dijkstra算法算词图的最短路径
N最短路就是用那个什么NShortPath算法算词图的最短路径
这些分词方式仅仅是算法不同，最终的分词效果是一样的。

但文档中说：
```
N最短路分词器NShortSegment比最短路分词器慢，但是效果稍微好一些，对命名实体识别能力更强。
```
才知道这些方式可能不仅仅是求最短路径的算法有区别，最终的分词效果都是会不一样的。

我想请问一下：
1. 这三个分词算法有什么区别？
2. 为什么能出不同的分词效果？

**Comment by hankcs** [comment]
标准分词与最短路效果是一样的，NShortPath在N条最短路上跑NER，所以命名实体召回率稍高一些。

**Comment by konghuarukhr** [comment]
了解了。谢谢！
