### ISSUE TITLE
portable-1.2.11版本“工信处”在index模式分词分成“工信处/n 工信处/nt”

### ISSUE THREAD

**Issue by konghuarukhr** [hankcs/HanLP#322]
请问一下，为什么会分出来两个不同词性的词？而且我看词典也没找到工信处词性为n的词条。

**Comment by hankcs** [comment]
感谢反馈。
data/dictionary/custom/CustomDictionary.txt中的
工信处 n 288
在portable-1.2.11的index模式下引发了不恰当的重复计算。

该问题在portable-1.3.1中已修复，请使用最新版。
