### ISSUE TITLE
开启Normalization后分词结果出问题

### ISSUE THREAD

**Issue by konghuarukhr** [hankcs/HanLP#323]
版本1.3.1

代码：
`HanLP.Config.Normalization = true;
StandardTokenizer.SEGMENT.enableOrganizationRecognize(true);
System.out.println(StandardTokenizer.segment("我的爱就是爱自然语言处理。"));`

运行结果是：
> [我/rr, 的/ude1, 爱/v, 就是/v, 爱自然语言处理./nt]

**Comment by hankcs** [comment]
已修正，谢谢
