### ISSUE TITLE
如何将HanLP代码与data目录下的词典文件打成一个jar?

### ISSUE THREAD

**Issue by cicido** [hankcs/HanLP#325]

**Comment by cicido** [comment]
我clone master下代码，现在想把代码与词典文件打成一个jar，以提交到分布式环境执行分词。看了一个portable包的打包方式，把portable下的pom.xml文件放在master代码下，在intellij idea测了一下，发现不行。是不是portable打包方式中代码有修改？

**Comment by cicido** [comment]
portable jar包是如何打包的？是通过maven吗？

**Comment by cicido** [comment]
master代码中，我data目录放在resoures目录下，能成功打包。 将此包放在工作项目中，发现找不到相关的词典文件，一般是什么原因？

**Comment by cicido** [comment]
我下载了portable jar包，发现pom.xml是不把hanlp.properties文件打包进来的。那在HanLP.java会直接抛异常啊

**Comment by cicido** [comment]
我明白了，谢谢

**Comment by cicido** [comment]
比较portable分支与master分支下HanLP.java代码差异

**Comment by cicido** [comment]
不好意思，这个打包问题还是没能解决。能否发我一个portable jar包打包的pom.xml， 或者portal方式的源代码及pom.xml.  portal分支的pom.xml并不能将data下面的词典文件加入。现在主要的问题是：
如果将词典与代码打成一个jar包，并代码读取词典文件必然用到getResourceAsStream函数，则必然要修改所有词典的文件读取方式。而当前的词典读取都是基于文件名字符串，非URL. 一直没有搞清楚，打好包的portal jar是如何做到的？有没有修改过代码之类的？

**Comment by hankcs** [comment]
https://github.com/hankcs/HanLP/pull/297

**Comment by cicido** [comment]
thanks!

**Comment by fangyuan930917** [comment]
我也遇到相似的问题，能方便问下您是怎么访问到自己定义的词典的吗？@cicido

**Comment by cicido** [comment]
@fangyuan930917, 暂时不可以，太费时间了，所以没有搞了。奇怪的一点就在于，portable版本的可以与词典打成一个jar包，但是看portable代码，并没有代码改动。我不知道我后来有没有尝试做portal源码打包，你可以试一下。

**Comment by cicido** [comment]
@fangyuan930917 , 我已经解决此问题。 需要的话，留下联系方式。

**Comment by jianchih** [comment]
@cicido 方便請教一下您是怎麼解決問題的呢？

**Comment by hollypany** [comment]
请问是如何解决的？ @cicido 联系方式：QQ 1965678754

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。

**Comment by maplellf** [comment]
> 我也遇到相似的问题，能方便问下您是怎么访问到自己定义的词典的吗？@cicido
