### ISSUE TITLE
使用StandardTokenizer分词时出现数组越界的错误（用CustomDictionary增加了一些词）

### ISSUE THREAD

**Issue by nhfmaster** [hankcs/HanLP#326]
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 45
	at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.viterbi(ViterbiSegment.java:140)
	at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.segSentence(ViterbiSegment.java:101)
	at com.hankcs.hanlp.seg.Segment.seg(Segment.java:441)
	at com.hankcs.hanlp.tokenizer.StandardTokenizer.segment(StandardTokenizer.java:40)

**Comment by hankcs** [comment]
版本号 触发代码

**Comment by nhfmaster** [comment]
那请问该如何解决呢

**Comment by hankcs** [comment]
给我版本号 触发代码

**Comment by nhfmaster** [comment]
1.2.9       List<Term> termList = StandardTokenizer.segment(para);

**Comment by hankcs** [comment]
用131

**Comment by nhfmaster** [comment]
好的 谢谢

**Comment by nhfmaster** [comment]
可是使用了131还是会出现这个问题

**Comment by hankcs** [comment]
请给出引发问题的句子

**Comment by nhfmaster** [comment]
“零售+分销”双龙头，处方外流重要收益标的，估值合理长期市值空间广大

**Comment by hankcs** [comment]
请在这段代码的基础上重现问题。

```
    public void testIssue326() throws Exception
    {
        System.out.println(StandardTokenizer.segment("“零售+分销”双龙头，处方外流重要收益标的，估值合理长期市值空间广大"));
    }
```

**Comment by hankcs** [comment]
请在复现问题后reopen issue，我会很乐意解决，谢谢。

**Comment by hankcs** [comment]
[“/w, 零售/vn, +/w, 分销/vn, ”/w, 双龙/ns, 头/n, ，/w, 处方/n, 外流/vi, 重要/a, 收益/n, 标的/n, ，/w, 估值/vi, 合理/a, 长期/d, 市值/n, 空间/n, 广大/b]

https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE

**Comment by hankcs** [comment]
如果问题涉及到用户词典，你可以通过com.hankcs.hanlp.dictionary.CustomDictionary#add(java.lang.String)接口模拟。

**Comment by nhfmaster** [comment]
好的 我稍后试一下 谢谢
