### ISSUE TITLE
采用默认分词结果不准确

### ISSUE THREAD

**Issue by kingdeewang** [hankcs/HanLP#328]
采用默认分词
输入内容为： 金阳观音山支行，分词结果：
[金阳/ns, 观音山/nz, 支行/n]
但是采用 NShortSegment分词，结果为
[金阳观音山支行/nt]

默认的分词实例为：
public static Segment segment = HanLP.newSegment().enableCustomDictionary(true).enableNameRecognize(true).enablePlaceRecognize(true).enableOrganizationRecognize(true);
Nshort分词实例为：
private static Segment nShortSegment = new NShortSegment().enableCustomDictionary(true).enablePlaceRecognize(true).enableOrganizationRecognize(true);

另外一个问题是： 为什么Nshort分词不支持自定义字典？

**Comment by hankcs** [comment]
的确，NShort命名实体识别能力高那么一点点，实际上并不实用。
Nshort是支持词典的。

**Comment by kingdeewang** [comment]
那为什么我设置nShortSegment 支持自定义，实际上并没有支持？ 是不是最新的版本支持？ 另外默认的分词，为什么会设置自定义字典后分词就不准确了？ 如果设置enableCustomDictionary(false)，结果和nShortSegment 分词结果是一致的。

**Comment by hankcs** [comment]
你试试把 观音山 词性设为ns，应该就可以。

**Comment by kingdeewang** [comment]
修改后成了，分词结果是这样的：
金阳/ns, 观音山/ns, 支行/n

**Comment by hankcs** [comment]
你肯定有个地方弄错了。

        Segment segment = HanLP.newSegment().enableCustomDictionary(true).enableNameRecognize(true).enablePlaceRecognize(true).enableOrganizationRecognize(true);
        CustomDictionary.insert("观音山", "ns 10");
        System.out.println(segment.seg(
                "金阳观音山支行"
        ));

[金阳观音山支行/nt]

**Comment by kingdeewang** [comment]
设置enableCustomDictionary(false);，显示是正确的。 下面是调试信息，大师能否协助看一下？
粗分词网：
0:[ ]
1:[金, 金阳]
2:[阳]
3:[观, 观音, 观音山]
4:[音]
5:[山]
6:[支, 支行]
7:[行]
8:[ ]

粗分结果[金阳/ns, 观音山/ns, 支行/n]
人名角色观察：[  A 22202445 ][金阳 X 1 ][观音山 A 22202445 ][支行 L 7 ][  A 22202445 ]
人名角色标注：[ /A ,金阳/X ,观音山/A ,支行/L , /A]
地名角色观察：[  S 1139590 A 23975 ][金阳 G 1 H 1 ][观音山 G 1 ][支行 B 138 ][  B 1322 ]
地名角色标注：[ /A ,金阳/G ,观音山/G ,支行/B , /A]
机构名角色观察：[  S 1169907 ][金阳 G 92134 B 1200 A 470 D 84 X 4 ][观音山 G 92134 B 1200 A 470 D 84 X 4 ][支行 B 27 C 5 D 1 ][  B 8423 ]
机构名角色标注：[ /S ,金阳/G ,观音山/G ,支行/D , /S]
识别出机构名：金阳观音山支行 GGD
细分词网：
0:[ ]
1:[金阳, 金阳观音山支行]
2:[]
3:[观音山]
4:[]
5:[]
6:[支行]
7:[]
8:[ ]

[金阳观音山支行/nt]



粗分词网：
0:[ ]
1:[金, 金阳]
2:[阳]
3:[观, 观音, 观音山]
4:[音]
5:[山]
6:[支, 支行]
7:[行]
8:[ ]

粗分结果[金阳/ns, 观音山/ns, 支行/n]
人名角色观察：[  A 22202445 ][金阳 X 1 ][观音山 A 22202445 ][支行 L 7 ][  A 22202445 ]
人名角色标注：[ /A ,金阳/X ,观音山/A ,支行/L , /A]
地名角色观察：[  Z 21619956 ][金阳 G 1 H 1 ][观音山 G 1 ][支行 B 138 ][  Z 21619956 ]
地名角色标注：[ /Z ,金阳/G ,观音山/G ,支行/B , /Z]
机构名角色观察：[  S 1169907 ][金阳 G 92134 B 1200 A 470 D 84 X 4 ][观音山 G 92134 B 1200 A 470 D 84 X 4 ][支行 B 27 C 5 D 1 ][  Z 21149365 ]
机构名角色标注：[ /S ,金阳/G ,观音山/G ,支行/B , /S]
[金阳/ns, 观音山/ns, 支行/n]

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
