### ISSUE TITLE
机构名识别导致的切词错误

### ISSUE THREAD

**Issue by liuia** [hankcs/HanLP#33]
按照要求，城镇居民医保和新农合政策范围内住院费用支付比例分别达到70%以上和75%左右。适当提高城镇居民医保和新农合门诊统筹待遇水平。 国务院医改办政策组负责人傅卫在接受记者采访时表示，从深化医改以来，基本医疗保障制度建设加快推进，医保保障水平也在不断提高，各级政府对城镇居民医保和新农合的补助标准从2008年的人均80元提高到了2013年的280元。到2015年，城镇居民医保和新农合政府补助标准将提高到每人每年360元以上。 不过，也有专家担心，随着保障水平提升，不断增加的医保基金支出正对医保基金“收支平衡、略有结余”的运行原则形成压力，甚至在一些地区造成超支风险。 记者了解到，国务院此前发文要求，在今年6月底前各省要全面启动城乡居民大病保险试点工作。大病医保的资金来源于现有医保基金的结余，即从城镇居民医保基金、新农合基金中划出，采取向商业保险机构购买保险的方式，不再额外增加群众个人缴费负担。 财经评论员余丰慧认为，如果提高大病保险保障水平，扩大报销种类，提高报销比例，而只在医保基金结余的存量上要资金来源，很快将造成两个方面的问题：一是可能影响到医保的资金支付，二是结余资金远远不够。 对此，《任务》要求，推进城乡居民基本医保制度整合和完善筹资机制。完善政府、单位和个人合理分担的基本医保筹资机制。此外，研究建立稳定可持续、动态调整的筹资机制，在逐步提高整体筹资标准的同时，按照积极稳妥、逐步到位的原则，逐步提高个人缴费占整体筹资的比重。 而根据此前相关要求，城镇居民医疗保险个人缴费应随总筹资水平作相应调整，个人缴费应占人均总筹资20%左右。对此，中央财经大学教授褚福灵在接受记者采访时表示，目前各地正研究建立城镇居民医疗保险财政补助和个人缴费科学合理、协同增长的机制，强化个人缴费义务。 惠民回购大型医疗设备降低检查费 《任务》指出，降低药品和高值医用耗材价格，降低大型医用设备检查、治疗价格，已贷款或集资购买的大型设备原则上由政府回购，回购有困难的限期降低价格。价格调整政策要与医保支付政策相衔接。 “老百姓抱怨看病贵的问题能够真正缓解了。”一位不愿透露姓名的业内人士指出，多年来患者抱怨看病贵，主要集中在诊疗费用上包括大型设备的检查费用等方面。政府也让医院降价，当大型设备的成本、维修费用都摆在那里，成本必然分摊到患者的检查费用中。 记者5月28日致电卫计委新闻宣传司副司长宋树立了解具体的回购政策，但截至记者发稿前，电话一直无法接通。 记者从食药总局主办的医疗器械质量万里行活动中了解到，国内大约近70%的大型医疗设备从销售到售后服务均被GE、西门子、飞利浦等跨国公司垄断。这体现在技术和耗材上的垄断直接导致市场竞争不充分，价格虚高。为了追求更高的利润，生产厂家从提供维修的配件中赚取高额差价成为主要盈利手段，售后服务提供商实际上变成了医疗设备配件销售商。 据对山东菏泽一家医院的调查，目前医疗设备厂家售后保质期一般都是一年，之后的维修有全保、技术保和单次维修3种情况。厂家对几种设备的维修报价如下：美国产64排VCT，一年全保38万元，一年技术保15万元，单次人工费3.1万元；美国产单排CT一年全保30万元，一年技术保13.6万元，单次人工费1.1万元……由于目前国家没有一个大致统一的定价标准，基本上由医院和厂家谈判，最后还是厂家说了算。 “不少进口的大型医疗设备维修费用占产品本身费用的三分之一或二分之一，甚至有的已经超过了产品价格。因此，卫生局让医院降低检查费用价格，根本就不可能，而用回购这一手段解决了诊疗费用高的问题。”上述人士指出。 鼓励实现跨省联合招标降低药价 “尽管跨省招标在政府采购中并不是一个新鲜事，但这是药品行业第一次提出。”中国医药企业管理协会副会长牛正乾28日表示，跨省联合招标可能推进招标环节的公开、透明。 《任务》在“加快推行公立医院改革”中指出，鼓励跨省联合招标采购保证药品质量安全，切实降低药品价格，有条件的地区要建立与基层基本药物采购联动的机制。逐步规范集中采购药品的剂型、规格和包装。推进高值医用耗材公开透明、公平竞争网上阳光采购。药品和高值医用耗材采购数据实行部门和区域共享。 中投顾问医药行业研究员许玲妮指出，县级医院联合招标能够降低药品配送费用，这部分差价分摊到药品上有利于降低药品价格，而且有利于平衡招标药品的质量和价格，改变以往备受业界诟病“唯低价是取”的招标规则。 不少医药企业的董事长都向记者表示，现行以省为单位的药品集中招标采购制度存在不少弊端，劳民伤财，应该进行改革。 许玲妮指出，药品招标采购规则存在漏洞，缺乏由政府部门提供必要的、较全面的药品信息。二是药品集中招标采购监督管理难以到位，招标后没有规范的信息反馈程序，监管部门无法对招标人合同履行情况进行有效监管，使集中招标采购活动“先热后凉，流于形式”。 “招投标本来是国际上通行的一种比较好的市场化采购方式，但目前我国政府包办的药品招标政策严重异化，成为药品进入市场所执行的二次行政管制。”葵花药业集团董事长关彦斌指出，现行药品招投标的实质是把药品进入医疗机构使用的正常市场行为变成了行政审批，并且同种产品不同区域年年审批，招标主管部门成了药品领域的最大审批权机构。 不过，许玲妮也指出，药品跨省联合招标采购是否可行与各省的区位有关，因为药企要承担运输成本，如果到两省距离不一样，承担的运费成本明显不同，如果按照统一招标并不合理。“比如北京、天津这两个直辖市，辖区较小，药企统一配送承担的费用差不多的情况下，跨省联合招标采购是可行的。”

启用机构名识别后，切词结果会把  "葵花  当做机构名

**Comment by hankcs** [comment]
当前版本识别结果为：
[葵花/n, 药业/nis, 集团/nis, 董事长/nnt, 关彦斌/nr, 指出/v]

**Comment by hankcs** [comment]
通过修改词典可以达到识别目的，请参考：
https://github.com/hankcs/HanLP/commit/e4adc73b67f36d59bc1bd3778b47e80697456045

**Comment by liuia** [comment]
这个错误在于，把标点符号 “ 本身当做词的一部分，”葵花 只是其中一个例子，如果用句号‘。’作为断句后再切词，就不会有这个问题

**Comment by liuia** [comment]
需要完整的，从“按照要求”开始整段切词，最后切词结果会是  行政/n, 管制/vn, ，"葵花/nt, 药业/nis, 集团/nis, 董事长/nnt

**Comment by hankcs** [comment]
你的版本可能过久，最新版：

System.out.println(NLPTokenizer.segment(
                "”成为药品进入市场所执行的二次行政管制。”葵花药业集团董事长关彦斌指出，"
        ));

输出：

[”/w, 成为/v, 药品/n, 进入/v, 市场/n, 所/usuo, 执行/v, 的/ude1, 二/m, 次/qv, 行政/n, 管制/vn, 。/w, ”/w, 葵花药业集团/nt, 董事长/nnt, 关彦斌/nr, 指出/v, ，/w]

**Comment by liuia** [comment]
代码已经是github里面master分支最新版本。这个bug的重现方式 需要完整的，从“按照要求”开始整段切词
你这么短的句子自然是没问题

[按照/p, 要求/n, ，/w, 城镇/n, 居民/n, 医保/n, 和/cc, 新农合/nz, 政策/n, 范围内/nz, 住院/vn, 费用/n, 支付/v, 比例/n, 分别/d, 达到/v, 70/m, %/nx, 以上/f, 和/cc, 75/m, %/nx, 左右/f, ，/w, 适当/a, 提高/v, 城镇/n, 居民/n, 医保/n, 和新农合/nt, 门诊/nis, 统筹/vd, 待遇/n, 水平/n, ，/w,  国务院医改办政策/nt, 组/n, 负责人/nnt, 傅卫在/nr, 接受/v, 记者/nnt, 采访/v, 时/ng, 表示/v, ，/w, 从/p, 深化/v, 医改/nz, 以来/f, ，/w, 基本/a, 医疗/n, 保障/vn, 制度/n, 建设/vn, 加快/v, 推进/vi, ，/w, 医保/n, 保障/vn, 水平/n, 也/d, 在/p, 不断/d, 提高/v, ，/w, 各级/r, 政府/nis, 对/p, 城镇/n, 居民/n, 医保/n, 和/cc, 新农合/nz, 的/ude1, 补助/vn, 标准/n, 从/p, 2008/m, 年/qt, 的/ude1, 人均80/nt, 元/q, 提高/v, 到/v, 了/ule, 2013年的280/nt, 元/q, ，/w, 到/v, 2015/m, 年/qt, ，/w, 城镇/n, 居民/n, 医保/n, 和新农合/nt, 政府/nis, 补助/vn, 标准/n, 将/d, 提高/v, 到/v, 每人/r, 每年360/nt, 元/q, 以上/f, ，/w,  /w, 不过/c, ，/w, 也/d, 有/vyou, 专家/nnt, 担心/v, ，/w, 随着/p, 保障/vn, 水平/n, 提升/v, ，/w, 不断/d, 增加/v, 的/ude1, 医保/n, 基金/n, 支出/n, 正/d, 对/p, 医保/n, 基金/n, "/w, 收支/n, 平衡/a, 、/w, 略有结余/nz, "/w, 的/ude1, 运行/vn, 原则/n, 形成/v, 压力/n, ，/w, 甚至/d, 在/p, 一些/m, 地区/n, 造成/v, 超支/v, 风险/n, ，/w,  /w, 记者/nnt, 了解到/v, ，/w, 国务院/nt, 此前/t, 发文/vi, 要求/n, ，/w, 在/p, 今年/t, 6/m, 月底/t, 前/f, 各省/r, 要/v, 全面/ad, 启动/v, 城乡/n, 居民/n, 大病/v, 保险/n, 试点/vn, 工作/vn, ，/w, 大病/v, 医保/n, 的/ude1, 资金来源/nz, 于/p, 现有医保/nt, 基金/n, 的/ude1, 结余/n, ，/w, 即/v, 从城镇居民医保/nt, 基金/n, 、/w, 新农合/nz, 基金/n, 中/f, 划出/v, ，/w, 采取/v, 向商业保险/nt, 机构/n, 购买/v, 保险/n, 的/ude1, 方式/n, ，/w, 不再/d, 额外/b, 增加/v, 群众/n, 个人/n, 缴费/vn, 负担/n, ，/w,  /w, 财经/n, 评论员/nnt, 余丰慧/nr, 认为/v, ，/w, 如果/c, 提高/v, 大病/v, 保险/n, 保障/vn, 水平/n, ，/w, 扩大/v, 报销/v, 种类/n, ，/w, 提高/v, 报销/v, 比例/n, ，/w, 而/cc, 只/d, 在/p, 医保/n, 基金/n, 结余/n, 的/ude1, 存量/n, 上/f, 要/v, 资金/n, 来源/n, ，/w, 很快/d, 将/d, 造成/v, 两/m, 个/q, 方面/n, 的/ude1, 问题/n, ：/w, 一/m, 是/vshi, 可能/v, 影响/vn, 到/v, 医保/n, 的/ude1, 资金/n, 支付/v, ，/w, 二/m, 是/vshi, 结余/n, 资金/n, 远远/d, 不够/a, ，/w,  /w, 对此/d, ，/w, 《/w, 任务/n, 》/w, 要求/n, ，/w, 推进/vi, 城乡/n, 居民/n, 基本/a, 医保/n, 制度/n, 整合/vn, 和/cc, 完善/v, 筹资/vi, 机制/n, ，/w, 完善/v, 政府/nis, 、/w, 单位/n, 和/cc, 个人/n, 合理/a, 分担/v, 的/ude1, 基本/a, 医保/n, 筹资/vi, 机制/n, ，/w, 此外/c, ，/w, 研究/vn, 建立/v, 稳定/an, 可持续/nz, 、/w, 动态/n, 调整/vn, 的/ude1, 筹资/vi, 机制/n, ，/w, 在/p, 逐步/d, 提高/v, 整体/n, 筹资/vi, 标准/n, 的/ude1, 同时/c, ，/w, 按照/p, 积极/ad, 稳妥/a, 、/w, 逐步/d, 到位/vi, 的/ude1, 原则/n, ，/w, 逐步/d, 提高/v, 个人/n, 缴费/vn, 占/v, 整体/n, 筹资/vi, 的/ude1, 比重/n, ，/w,  /w, 而/cc, 根据/p, 此前/t, 相关/vn, 要求/n, ，城镇居民医疗/nt, 保险/n, 个人/n, 缴费/vn, 应/v, 随/p, 总/b, 筹资/vi, 水平/n, 作/v, 相应/vi, 调整/vn, ，/w, 个人/n, 缴费/vn, 应/v, 占/v, 人均/a, 总/b, 筹资/vi, 20/m, %/nx, 左右/f, ，/w, 对此/d, ，/w, 中央财经大学/ntu, 教授/nnt, 褚福灵/nr, 在/p, 接受/v, 记者/nnt, 采访/v, 时/ng, 表示/v, ，/w, 目前/t, 各地/rzs, 正/d, 研究/vn, 建立/v, 城镇/n, 居民/n, 医疗/n, 保险/n, 财政/n, 补助/vn, 和/cc, 个人/n, 缴费/vn, 科学/n, 合理/a, 、/w, 协同/vd, 增长/v, 的/ude1, 机制/n, ，/w, 强化/v, 个人/n, 缴费/vn, 义务/n, ，/w,  /w, 惠民/ns, 回购/v, 大型/b, 医疗/n, 设备/n, 降低/v, 检查费/n,  /w, 《/w, 任务/n, 》/w, 指出/v, ，/w, 降低/v, 药品/n, 和/cc, 高值/nr, 医用/b, 耗材/n, 价格/n, ，/w, 降低/v, 大型/b, 医用/b, 设备/n, 检查/vn, 、/w, 治疗/vn, 价格/n, ，/w, 已/d, 贷款/n, 或/c, 集资/vi, 购买/v, 的/ude1, 大型/b, 设备/n, 原则上/nz, 由/p, 政府/nis, 回购/v, ，/w, 回购/v, 有/vyou, 困难/an, 的/ude1, 限期/vd, 降低/v, 价格/n, ，/w, 价格/n, 调整/vn, 政策/n, 要/v, 与/cc, 医保/n, 支付/v, 政策/n, 相/d, 衔接/vi, ，/w,  "/w, 老百姓/n, 抱怨/v, 看病/vi, 贵/a, 的/ude1, 问题/n, 能够/v, 真正/d, 缓解/v, 了/ule, ，/w, "/w, 一/m, 位/q, 不愿/nz, 透露/v, 姓名/n, 的/ude1, 业内人士/n, 指出/v, ，/w, 多年来/d, 患者/n, 抱怨/v, 看病/vi, 贵/a, ，/w, 主要/b, 集中/v, 在/p, 诊疗/vn, 费用/n, 上包括/nt, 大型/b, 设备/n, 的/ude1, 检查/vn, 费用/n, 等/udeng, 方面/n, ，/w, 政府/nis, 也/d, 让/v, 医院/nis, 降价，当/nt, 大型/b, 设备/n, 的/ude1, 成本/n, 、/w, 维修/vn, 费用/n, 都/d, 摆/v, 在/p, 那里/rzs, ，/w, 成本/n, 必然/d, 分摊/v, 到/v, 患者/n, 的/ude1, 检查/vn, 费用/n, 中/f, ，/w,  /w, 记者/nnt, 5/m, 月/n, 28/m, 日致电卫计委/nt, 新闻/n, 宣传司/nis, 副司长/nnt, 宋/tg, 树立/v, 了解/v, 具体/a, 的/ude1, 回购/v, 政策/n, ，/w, 但/c, 截至/v, 记者/nnt, 发稿/vi, 前/f, ，/w, 电话/n, 一直/d, 无法/v, 接通/v, ，/w,  /w, 记者从食/nt, 药/n, 总局/nis, 主办/v, 的医疗器械质量/nt, 万里/nr, 行/ng, 活动/vn, 中/f, 了解到/v, ，/w, 国内/s, 大约/d, 近/a, 70%的大型/nt, 医疗/n, 设备/n, 从/p, 销售/vn, 到/v, 售后服务/n, 均/d, 被/pbei, ge/nx, 、/w, 西门子/nrj, 、/w, 飞利浦/ntc, 等/udeng, 跨国公司/nis, 垄断/vn, ，/w, 这/rzv, 体现/v, 在/p, 技术/n, 和/cc, 耗材/n, 上/f, 的/ude1, 垄断/vn, 直接/ad, 导致/v, 市场/n, 竞争/vn, 不/d, 充分/ad, ，/w, 价格/n, 虚高/nz, ，/w, 为了/p, 追求/v, 更高/d, 的/ude1, 利润/n, ，/w, 生产厂家/n, 从/p, 提供/v, 维修/vn, 的/ude1, 配件/n, 中/f, 赚取/v, 高额/b, 差价/n, 成为/v, 主要/b, 盈利/vn, 手段/n, ，/w, 售后服务/n, 提供商/n, 实际上/d, 变成了医疗设备/nt, 配件/n, 销售商/nnd, ，/w,  据对/nt, 山东/ns, 菏泽/ns, 一家/n, 医院/nis, 的/ude1, 调查/vn, ，/w, 目前/t, 医疗/n, 设备/n, 厂家/n, 售后/vi, 保质期/n, 一般/ad, 都/d, 是/vshi, 一/m, 年/qt, ，/w, 之后的/nt, 维修/vn, 有/vyou, 全保/nr, 、/w, 技术/n, 保和/v, 单次/nz, 维修/vn, 3/m, 种/q, 情况/n, ，/w, 厂家/n, 对/p, 几/d, 种/q, 设备/n, 的/ude1, 维修/vn, 报价/vn, 如下/vi, ：/w, 美国/nsf, 产/v, 64/m, 排/v, vct/nx, ，/w, 一/m, 年/qt, 全保/nr, 38/m, 万元/q, ，/w, 一/m, 年/qt, 技术/n, 保/v, 15/m, 万元/q, ，/w, 单次/nz, 人工费/nz, 3.1/m, 万元/q, ，/w, 美国/nsf, 产/v, 单排/nz, ct/nx, 一/m, 年全保/nr, 30/m, 万元/q, ，/w, 一/m, 年/qt, 技术/n, 保/v, 13.6/m, 万元/q, ，/w, 单次/nz, 人工费/nz, 1.1/m, 万元/q, ，/w, ，/w, 由于/p, 目前/t, 国家/n, 没有/v, 一个/mq, 大致/d, 统一/vn, 的/ude1, 定价/n, 标准/n, ，/w, 基本上/d, 由/p, 医院/nis, 和/cc, 厂家/n, 谈判/vn, ，/w, 最后/f, 还是/c, 厂家/n, 说了算/vl, ，/w,  "/w, 不少/m, 进口/vn, 的/ude1, 大型/b, 医疗/n, 设备/n, 维修/vn, 费用/n, 占/v, 产品/n, 本身/rz, 费用/n, 的/ude1, 三/m, 分之一/n, 或/c, 二分/v, 之一/rz, ，/w, 甚至/d, 有的/rz, 已经/d, 超过/v, 了/ule, 产品/n, 价格/n, ，/w, 因此/c, ，/w, 卫生局/nis, 让/v, 医院/nis, 降低/v, 检查/vn, 费用/n, 价格/n, ，/w, 根本/a, 就/d, 不/d, 可能/v, ，/w, 而/cc, 用/p, 回购/v, 这/rzv, 一手/d, 段/q, 解决/v, 了/ule, 诊疗/vn, 费用/n, 高/a, 的/ude1, 问题/n, ，/w, "/w, 上述/b, 人士/n, 指出/v, ，/w,  /w, 鼓励/v, 实现/v, 跨省/d, 联合/vd, 招标/vn, 降低/v, 药价/n,  "/w, 尽管/c, 跨省/d, 招标/vn, 在/p, 政府/nis, 采购/vn, 中/f, 并/cc, 不是/c, 一个/mq, 新鲜事/n, ，/w, 但/c, 这/rzv, 是/vshi, 药品/n, 行业/n, 第一/m, 次/qv, 提出/v, ，/w, "中国医药企业/nt, 管理/vn, 协会/nis, 副会长/nnt, 牛正乾/nr, 28/m, 日/b, 表示/v, ，/w, 跨省/d, 联合/vd, 招标/vn, 可能/v, 推进/vi, 招标/vn, 环节/n, 的/ude1, 公开/ad, 、/w, 透明/a, ，/w,  /w, 《/w, 任务/n, 》/w, 在/p, "/w, 加快/v, 推行/v, 公立/b, 医院/nis, 改革/vn, "/w, 中/f, 指出/v, ，/w, 鼓励/v, 跨省/d, 联合/vd, 招标/vn, 采购/vn, 保证/v, 药品/n, 质量/n, 安全/an, ，/w, 切实/ad, 降低/v, 药品/n, 价格/n, ，/w, 有条件/nz, 的/ude1, 地区/n, 要/v, 建立/v, 与/cc, 基层/n, 基本/a, 药物/n, 采购/vn, 联动/vn, 的/ude1, 机制/n, ，/w, 逐步/d, 规范/v, 集中/v, 采购/vn, 药品/n, 的/ude1, 剂型/n, 、/w, 规格/n, 和/cc, 包装/n, ，/w, 推进/vi, 高/a, 值/n, 医用/b, 耗材/n, 公开/ad, 透明/a, 、/w, 公平竞争/nz, 网上/s, 阳光/n, 采购/vn, ，/w, 药品/n, 和/cc, 高值/nr, 医用/b, 耗材/n, 采购/vn, 数据/n, 实行/v, 部门/n, 和/cc, 区域/n, 共享/v, ，/w,  中投顾问/nt, 医药/n, 行业/n, 研究员/nnt, 许玲妮/nr, 指出，/nt, 县级/b, 医院/nis, 联合/vd, 招标/vn, 能够/v, 降低/v, 药品/n, 配送/vn, 费用/n, ，/w, 这/rzv, 部分/n, 差价/n, 分摊/v, 到/v, 药品/n, 上/f, 有利于/v, 降低/v, 药品/n, 价格/n, ，/w, 而且/c, 有利于/v, 平衡/a, 招标/vn, 药品/n, 的/ude1, 质量/n, 和/cc, 价格/n, ，/w, 改变/v, 以往/t, 备受/v, 业界/n, 诟病/n, "/w, 唯/d, 低价/n, 是/vshi, 取/v, "/w, 的/ude1, 招标/vn, 规则/n, ， 不少/nt, 医药/n, 企业/n, 的/ude1, 董事长/nnt, 都向/nr, 记者/nnt, 表示/v, ，/w, 现行以省/nt, 为/p, 单位/n, 的/ude1, 药品/n, 集中/v, 招标/vn, 采购/vn, 制度/n, 存在/v, 不少/m, 弊端/n, ，/w, 劳民伤财/vl, ，/w, 应该/v, 进行改革/v, ，/w,  /w, 许玲妮/nr, 指出/v, ，/w, 药品/n, 招标/vn, 采购规则/n, 存在/v, 漏洞/n, ，/w, 缺乏/v, 由/p, 政府部门/n, 提供/v, 必要/a, 的/ude1, 、/w, 较/d, 全面/ad, 的/ude1, 药品/n, 信息/n, ，/w, 二/m, 是/vshi, 药品/n, 集中/v, 招标/vn, 采购/vn, 监督管理/v, 难以/d, 到位/vi, ，/w, 招标/vn, 后/f, 没有/v, 规范/v, 的/ude1, 信息反馈/gi, 程序/n, ，/w, 监管部门/n, 无法/v, 对/p, 招标人/nz, 合同/n, 履行/v, 情况/n, 进行/vn, 有效/a, 监管/vn, ，/w, 使/v, 集中/v, 招标/vn, 采购/vn, 活动/vn, "/w, 先热/v, 后/f, 凉/a, ，/w, 流于形式/vl, "/w, ，/w,  "/w, 招投标/n, 本来/d, 是/vshi, 国际上/nz, 通行/vi, 的/ude1, 一/m, 种/q, 比较/d, 好/a, 的/ude1, 市场化/vn, 采购/vn, 方式/n, ，/w, 但/c, 目前/t, 我国/n, 政府/nis, 包办/v, 的/ude1, 药品/n, 招标/vn, 政策/n, 严重/a, 异化/vn, ，/w, 成为/v, 药品进入/nt, 市场/n, 所/usuo, 执行/v, 的/ude1, 二/m, 次/qv, 行政/n, 管制/vn, ，"葵花/nt, 药业/nis, 集团/nis, 董事长/nnt, 关彦斌/nr, 指出/v, ，/w, 现行/b, 药品/n, 招投标/n, 的/ude1, 实质/n, 是/vshi, 把/pba, 药品进入/nt, 医疗/n, 机构/n, 使用/v, 的/ude1, 正常/a, 市场/n, 行为/n, 变成/v, 了/ule, 行政/n, 审批/vn, ，/w, 并且/c, 同/p, 种/q, 产品/n, 不同/a, 区域/n, 年年/d, 审批/vn, ，/w, 招标/vn, 主管/vn, 部门/n, 成/v, 了/ule, 药品/n, 领域/n, 的/ude1, 最大/gm, 审批权/n, 机构/n, ，/w,  /w, 不过/c, ，/w, 许玲妮/nr, 也/d, 指出/v, ，/w, 药品/n, 跨省/d, 联合/vd, 招标/vn, 采购/vn, 是否/v, 可行/a, 与/cc, 各省/r, 的/ude1, 区位/n, 有关/vn, ，/w, 因为/c, 药/n, 企/ng, 要/v, 承担/v, 运输/vn, 成本/n, ，/w, 如果/c, 到/v, 两省/nz, 距离/n, 不/d, 一样/uyy, ，/w, 承担/v, 的/ude1, 运费/n, 成本/n, 明显/a, 不同/a, ，/w, 如果/c, 按照/p, 统一/vn, 招标/vn, 并不/d, 合理/a, ，/w, "比如北京/nt, 、/w, 天津/ns, 这/rzv, 两/m, 个/q, 直辖市/n, ，/w, 辖区/n, 较小/d, ，/w, 药/n, 企/ng, 统一/vn, 配送/vn, 承担/v, 的/ude1, 费用/n, 差不多/al, 的/ude1, 情况下/nz, ，/w, 跨省/d, 联合/vd, 招标/vn, 采购/vn, 是/vshi, 可行/a, 的/ude1, ，/w, "/w]

**Comment by hankcs** [comment]
感谢反馈，是写代码的时候疏忽了。
已经解决：https://github.com/hankcs/HanLP/commit/d24b6e179865f2533fef1723fb035f4cb933c66a

**Comment by hankcs** [comment]
另外，机构名识别是很多公司想做或在做的功能。目前HanLP中的机构名识别还处于一个初级的实验性阶段，语料也没有经过仔细的校验，仅供参考。
