### ISSUE TITLE
HanLP修改主词典需要注意什么？

### ISSUE THREAD

**Issue by konghuarukhr** [hankcs/HanLP#333]
请问一下：
项目需要，想用自己的词库分词。
但是做带词性和词频的词典，还有对应的BiGram词典又没有工具做，所以我想把HanLP词典中和我自己词典中都有的词保留；HanLP词典中有的，我自己词典中没有的词删掉；HanLP词典中没有，我自己词典中有的词放到custom词典中，这样靠谱不？

我能想到的问题有两个：
1. CoreDictionaryPath这个配置对应的词典中的内容，除了带“##”的字符串外（这个删了会报java.lang.ArrayIndexOutOfBoundsException异常），别的词条我可以随意增删吗？
2. 改了CoreDictionaryPath那个词典，对应的BiGramDictionaryPath词典，如果还是用原来的，会不会有什么问题？
3. 还有没有别的问题？

谢谢。

**Comment by hankcs** [comment]
0. 可以
0. 程序不会有问题，效果会变差
0. 应该没有了

**Comment by konghuarukhr** [comment]
用户词典增加的词，没有切分出来：

	public static void testString() {
		CustomDictionary.add("学院风");
		CustomDictionary.add("潜水服");
		String text = "潜水服和学院风秋装";
		List<Term> terms = null;
		terms = IndexSegmenter.seg(text);
		System.out.print("Index: ");
		for (Term term : terms) {
			System.out.print(term.word + " ");
		}
		System.out.println();
		terms = QuerySegmenter.seg(text);
		System.out.print("Query: ");
		for (Term term : terms) {
			System.out.print(term.word + " ");
		}
		System.out.println();
	}

返回结果是：

Index: 潜水 服和 学院 风秋装 
Query: 潜水 服和 学院 风秋装 

1. 好像HanLP粗切分之后，遇到一系列连续的单字的话，会把这串连续的单字合并成一个词？导致后续没有和用户词典中的词匹配到了？是这个原因吗？

2. 如果是这种情况，那我如果大幅度删减CoreDictionary中的词，即使我在CustomDictionary中也加入了大量的词，是不是这些词很多时候都是切分不出来的？

3. 我想到的方法是有两种：要么我把在CustomDictionary中的词直接放到CoreDictionary中，这种光有词，没有词性和词频的词条，肯定影响分词准确度。HanLP中默认词性和词频是怎么给的？

4. 另外一种方法，要么我得改一下HanLP连续单字成词的策略，单字就按单字切出来。这样就没问题了。但是HanLP既然选择将连续单字合并成词，必然有原因，我想了解一下，这是出于什么原因这么做的呢？

5. 另外，把词放在CustomDictionary词典中还有一个不利的地方：索引分词时，细粒度的词即使在CustomDictionary词典中存在，也分不出来。

**Comment by hankcs** [comment]
请参考：https://github.com/hankcs/HanLP/wiki/FAQ#%E4%B8%BA%E4%BB%80%E4%B9%88%E4%BF%AE%E6%94%B9%E4%BA%86%E8%AF%8D%E5%85%B8%E8%BF%98%E6%98%AF%E6%B2%A1%E6%9C%89%E6%95%88%E6%9E%9C

引擎盖下，不是词典。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
