### ISSUE TITLE
ExtractSummary的问题

### ISSUE THREAD

**Issue by bingyupiaoyao** [hankcs/HanLP#338]
您好，非常感谢您提供这么好的开源项目，但是在看ExtractSummary时发现，对博文中这个例子做summary，得到的结果是：[无限算法的产生是由于未能确定的定义终止条件, 这类算法在有限的时间内终止, 有限的非确定算法]，和文中所说不一致，请问问题出在哪？谢谢

**Comment by hankcs** [comment]
不客气。这是正常的，最初版本的分词和停用词与现在相比都发生了变化。

**Comment by bingyupiaoyao** [comment]
感谢答复！
