### ISSUE TITLE
使用默认分词，全角标点符号词性标注均为“/xu”

### ISSUE THREAD

**Issue by persisted** [hankcs/HanLP#339]
博主您好，源码是最新版本的。按照词典中的标注中文标点符号词性应该为“w”，Nature中更是定义了更细分的类型，但是分词后确都是“/xu”。
======================分词代码：
Segment nShortSegment = new NShortSegment().enableCustomDictionary(false).enablePlaceRecognize(true).enableOrganizationRecognize(true);
        Segment shortestSegment = new DijkstraSegment().enableCustomDictionary(false).enablePlaceRecognize(true).enableOrganizationRecognize(true);
        String[] testCase = new String[]{
                "\"（F-35）“闪电工。，【】‘、”\""
        };
        for (String sentence : testCase)
        {
            System.out.println("N-最短分词：" + nShortSegment.seg(sentence) + "\n最短路分词：" + shortestSegment.seg(sentence));
        }
==================分词结果：
[F-/nx, 35/m, “/xu, 闪电/n, 工/n, ”/xu]
N-最短分词：["/w, （/xu, F-/nx, 35/m, ）/xu, “/xu, 闪/vx, 电工/nnt, 。/xu, ，/xu, 【/xu, 】/xu, ‘/xu, 、/xu, ”/xu, "/w]
最短路分词：["/w, （/xu, F-/nx, 35/m, ）/xu, “/xu, 闪/vx, 电工/nnt, 。/xu, ，/xu, 【/xu, 】/xu, ‘/xu, 、/xu, ”/xu, "/w]

**Comment by hankcs** [comment]
官方版一切正常

N-最短分词：["/w, 《/w, f/nx, ·35/m, 》/w, "/w, 闪/v, 电工/n, .,/w, 《/w, 》/w, ‘/w, 、/w, ""/w]
最短路分词：["/w, 《/w, f/nx, ·/w, 35/m, 》/w, "/w, 闪/v, 电工/n, .,/w, 《/w, 》/w, ‘/w, 、/w, ""/w]

请确认是否做了什么改动。

**Comment by persisted** [comment]
博主您好，非常感谢及时回复。经测试发现，是由于在Nature.java中直接添加了一个“自定领域词”的词性类型引起的，代码位置如下：
 /**
     * 计算机相关词汇
     */
    gi,

    /**
     * 自定义领域词
     */
    gndip,

    /**
     * 简称略语
     */
    j,

如果采用动态添加Nature.create("gndip"); 不会出现问题。
===============================

请问，是否添加方式不对，或者建议如何添加一个新的词性类型，谢谢！

**Comment by hankcs** [comment]
清除缓存即可。

**Comment by persisted** [comment]
清除缓存后问题解决。多谢！

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
