### ISSUE TITLE
时间标准化的问题

### ISSUE THREAD

**Issue by turn88** [hankcs/HanLP#34]
不知道大神有没有时间加一个时间标准化的模块？另外，时间的判断好像也有些问题，例如  下午/t, 3/m, 时由/nr, 北京/ns, 出发/v, 这句话就没有把下午3时整个判断为时间，希望大神能改进下，谢谢。

**Comment by hankcs** [comment]
String text = "下午3时由北京出发";
        StandardTokenizer.SEGMENT.enableNumberQuantifierRecognize(true);
        System.out.println(StandardTokenizer.segment(text));

这样就行了
