### ISSUE TITLE
采用默认维特比分词，默认分词结果为什么为空的？

### ISSUE THREAD

**Issue by kingdeewang** [hankcs/HanLP#341]
key=电台情歌
粗分词网：
0:[ ]
1:[电, 电台]
2:[台]
3:[情, 情歌]
4:[歌]
5:[ ]

粗分结果[]
人名角色观察：[  A 22202445 ][电台情歌  A 22202445 ]
人名角色标注：[ /A ,电台情歌 /A]
地名角色观察：[  S 1139590 A 23975 ][电台情歌  Z 21619956 ]
地名角色标注：[ /A ,电台情歌 /A]
[]

**Comment by hankcs** [comment]
[电台/nis, 情歌/n]
https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE
