### ISSUE TITLE
自定义词典index分词：带“我”字词汇某些情况下无法分出

### ISSUE THREAD

**Issue by judaschrist** [hankcs/HanLP#343]
使用index模式分词 + 自定义词典进行分词，设置如下：
配置文件中添加：mydic.txt n 作为自定义词典
词典中包含：

> 酷我音乐
> 酷我
> 酷狗音乐
> 酷狗

分词器配置：
`seg = HanLP.newSegment().enableIndexMode(true).enableNameRecognize(true).enableCustomDictionary(true).enableTranslatedNameRecognize(true);`

对“酷我音乐”分词，结果里没有酷我

> [酷我音乐/n, 音乐/n]

对酷狗音乐，则可以得到预期结果

> [酷狗音乐/n, 酷狗/n, 音乐/n]

后经测试，发现如果词汇中带由我字，则无法分出句子中较短的带“我”字的词汇，除非没有其他的分词可能，例如下面分词结果

> 天天酷我：[天天/d, 酷我/n]

类似的例子：
词表如下：

> 暴风集团股份有限公司
> 暴风
> 合一信息技术（北京）有限公司
> 合一
> 我查查信息技术（上海）有限公司
> 我查查

分词结果：

> 
> 暴风集团股份有限公司：[暴风集团股份有限公司/n, 暴风/n, 集团/nis, 股份/n, 有限/a, 有限公司/nis, 公司/nis] （包含暴风）
> 合一信息技术（北京）有限公司：[合一信息技术（北京）有限公司/n, 合一/vi, 信息/n, 信息技术/gi, 技术/n, 北京/ns, 有限/a, 有限公司/nis, 公司/nis]（包含合一）
> 我查查信息技术（上海）有限公司：[我查查信息技术（上海）有限公司/n, 查查/v, 信息/n, 信息技术/gi, 技术/n, 上海/ns, 有限/a, 有限公司/nis, 公司/nis]（不包含我查查）
> 我查查信息技术（上海）有限公司今天宣布：[我查查信息技术（上海）有限公司/n, 查查/v, 信息/n, 信息技术/gi, 技术/n, 上海/ns, 有限/a, 有限公司/nis, 公司/nis, 今天/t, 宣布/v] （不包含我查查）
> 我查查信息：[我查查/n, 查查/v, 信息/n]（没有其他更长的分词可能，所以包含我查查）

因为分词器设置了index模式，所以应该包含尽可能多的分词可能，因此这个问题是否是一个潜在问题？

**Comment by hankcs** [comment]
否。
index模式会对正常分词结果中长度大于2的词语全切分，全切分结果不会含有任何单字。

**Comment by hankcs** [comment]
不过既然用户词典中指定了酷我是一个词，也许这种结果的确显得有点意外。

**Comment by judaschrist** [comment]
感觉您没有理解我的问题。我并没有质疑不包含单字的问题，切分结果中当然不包含单字，但是出现的问题是包含“我”的**多字词汇**都无法分出。给定词表：

> 合一信息技术（北京）有限公司
> 合一
> 我查查信息技术（上海）有限公司
> 我查查

“合一信息技术（北京）有限公司”的分词结果：

> [合一信息技术（北京）有限公司/n, 合一/vi, 信息/n, 信息技术/gi, 技术/n, 北京/ns, 有限/a, 有限公司/nis, 公司/nis]

包含“合一”，而“我查查信息技术（上海）有限公司“的分词结果：

> [我查查信息技术（上海）有限公司/n, 查查/v, 信息/n, 信息技术/gi, 技术/n, 上海/ns, 有限/a, 有限公司/nis, 公司/nis]

不包含“我查查”，测试了多个包含“我”字的公司名称，包括“酷我”，“我在找你”，“我爱卿”，等，都存在这个问题。如何解释这种结果呢？

**Comment by hankcs** [comment]
我理解你的问题，但问题的本质不在“我”这个字上。只是程序在全切分的时候没有重视用户词典中次长的词语而已，我已改进了这个问题，欢迎测试。

**Comment by judaschrist** [comment]
感谢hankcs，经测试已经解决了上述问题！
不过感觉并不是你提到的不够重视用户词典的问题。因为自定义词典中的其他词都能分出来，只是带有“我”字的词分不出来，感觉是个特例，我依然感觉是一个潜在的问题，hankcs有空时可以进一步查证
anyway，用你的方法已经bypass了这个问题，Thanks!
