### ISSUE TITLE
很高级  分词成了 很高  和 级  ,   要怎么做?

### ISSUE THREAD

**Issue by nice2mu** [hankcs/HanLP#344]
[java/nx, 是/v, 一/m, 种/q, 很高/d, 级/q, 的/uj, 语言/n]

**Comment by hankcs** [comment]
[java/nx, 是/v, 一/m, 种/q, 很/d, 高级/nr, 的/uj, 语言/n]
你用的不是官方版本。
https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE
