### ISSUE TITLE
使用HMM-Viterbi（标准分词）模式无法获取词性

### ISSUE THREAD

**Issue by BleethNie** [hankcs/HanLP#346]
版本号：hanlp-1.3.1
方式一：使用HanLP静态分词器可以获取词性
String text = "乐视超级手机能否承载贾布斯的生态梦";
Segment segment = HanLP.newSegment();
segment.enablePartOfSpeechTagging(true);
List<Term> termList = segment.seg(text);
System.err.println(termList);

输出结果：[乐/a, 视/vg, 超级/b, 手机/n, 能否/v, 承载/v, 贾/nz, 布斯/nrf, 的/ude1, 生态/n, 梦/n]

方式二：直接new 一个HMMSegment类无法获取词性
String text = "乐视超级手机能否承载贾布斯的生态梦";
Segment segment =new HMMSegment();
segment.enablePartOfSpeechTagging(true);
List<Term> termList = segment.seg(text);
System.err.println(termList);

输出结果：[乐/null, 视/null, 超级/null, 手机/null, 能否/null, 承载/null, 贾布斯/null, 的/null, 生态/null, 梦/null]

不知这是不是bug

**Comment by hankcs** [comment]
不是，两者是不同的segment。
https://github.com/hankcs/HanLP/blob/master/src/test/java/com/hankcs/demo/DemoHMMSegment.java
