### ISSUE TITLE
nr词典格式问题

### ISSUE THREAD

**Issue by grayeagles** [hankcs/HanLP#349]
你好！我用的是1.3.1的程序和1.3.0的data。在分词时会有一些词被错误的标成了人名，比如考考你，都喜欢。按照您的说明，我把这些词加上 A 1添加在nr.txt的后面，但是运行时就出现错误了，提示是：十一月 24, 2016 10:27:04 上午 com.hankcs.hanlp.corpus.io.IOUtil readBytes
警告: 读取D:/data/data-for-1.3.0/data/dictionary/person/nr.txt.value.dat时发生异常java.io.FileNotFoundException: D:\data\data-for-1.3.0\data\dictionary\person\nr.txt.value.dat (系统找不到指定的文件。)
十一月 24, 2016 10:27:04 上午 com.hankcs.hanlp.dictionary.nr.NRDictionary onLoadValue
严重: 读取D:/data/data-for-1.3.0/data/dictionary/person/nr.txt失败[java.lang.NumberFormatException: For input string: "1阿哈"]
该词典这一行格式不对：欧对 A 1阿哈 A 1考考你 A 1微盘 A 1布用谢 A 1南阳 A 1都喜欢 A 1
人名词典加载失败：D:/data/data-for-1.3.0/data/dictionary/person/nr.txt
请问这是什么原因？

**Comment by grayeagles** [comment]
把这几个词删掉就没有问题，但是这几个词我完全按照您的说明添加的，而且格式也和nr.txt中前面的词一样。

**Comment by hankcs** [comment]
要换行，一行一个词。

**Comment by grayeagles** [comment]
可以了，十分感谢

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
