### ISSUE TITLE
使用 python 调用 Hanlp.parseDependency 时报错

### ISSUE THREAD

**Issue by yangershu** [hankcs/HanLP#350]
RT：
[按照http://www.hankcs.com/nlp/python-calls-hanlp.html](http://www.hankcs.com/nlp/python-calls-hanlp.html) 例子进行的测试
报错的log`java.lang.NullPointerExceptionPyRaisable: java.lang.NullPointerException`
求助~

**Comment by hankcs** [comment]
你给的信息太少，请仔细检查data路径，其他功能是否正常
