### ISSUE TITLE
HanLP.convertToSimplifiedChinese('奔驰')　=> 賓士

### ISSUE THREAD

**Issue by Poordeveloper** [hankcs/HanLP#351]
好明显的bug

**Comment by hankcs** [comment]
https://zh.wikipedia.org/wiki/%E6%A2%85%E8%B3%BD%E5%BE%B7%E6%96%AF-%E8%B3%93%E5%A3%AB
梅赛德斯-奔驰（Mercedes-Benz，根据地区与时期的不同分别有奔驰、宾士、平治、梅赛德斯、朋驰等多种中文简称），是一家以豪华和高性能著称的德国汽车品牌[1]，总部设于德国斯图加特。旗下产品有各式乘用车、中大型商用车辆。目前梅赛德斯-奔驰是戴姆勒公司旗下的成员之一。

**Comment by hankcs** [comment]
http://www.mercedes-benz.com.tw/content/taiwan/mpc/mpc_taiwan_website/twng/home_mpc/passengercars.html

**Comment by Poordeveloper** [comment]
In [2]: HanLP.convertToSimplifiedChinese('习近平治党')
Out[2]: '习近奔驰党'
