### ISSUE TITLE
在对简体中文调用HanLP.convertToSimplifiedChinese出现的一些bug

### ISSUE THREAD

**Issue by Poordeveloper** [hankcs/HanLP#352]
因为在使用中我们不知道文章是否简体或者繁体，所以我们一概使用简体转化，在处理如下词汇时候问题严重

> '民乐', '奶油', '战列舰', '房价', '标致', '沃尓沃', '富豪', '大众', '马自达',
> '克拉', '厄瓜多', '塔吉克', '安的列', '尼日', '洛哈', '漢堡', '艾森豪', '裁判',
> '福斯', '芝士', '起司', '房屋', '忌廉', '平治',
> '空中客车', '笑星', '谐星', '奔驰', '零钱', '老年痴呆症'

最危险的是把“习近平治党”搞成了“习近奔驰党”，在天朝，这可是杀头的罪

```
In [5]: HanLP.convertToSimplifiedChinese('習近平治黨')
Out[5]: '习近奔驰党'

```

**Comment by hankcs** [comment]
感谢，简繁词典的确没有习近平，平治是奔驰在香港的名称。
词典是大家共同维护的，如果你发现了任何问题，欢迎参考如下方式修改并提交pull request。

**Comment by hankcs** [comment]
另外，还可以删除奔驰相关的分歧词。

你的需求其实可以试试com.hankcs.hanlp.dictionary.other.CharTable#convert(java.lang.String)，这个是按字转换的，效率更高。

**Comment by Poordeveloper** [comment]
谢谢，我还是用com.hankcs.hanlp.dictionary.other.CharTable吧
