### ISSUE TITLE
请教日期实体词提取的问题

### ISSUE THREAD

**Issue by leteor** [hankcs/HanLP#356]
我在二元继续词典里定义了未##数@年、未##数@月、未##数@日等
也清除了词典的缓存
但实际分词时2007年1月11日还是会被分成2007/m, 年/qt, 1/m, 月/n, 11/m, 日/b
如何能合并成“2007年”、“1月”、“11日”甚至是“2007年1月11日”呢？
请指教。

**Comment by leteor** [comment]
已经找到方法解决了。
谢谢。

**Comment by shanshouchen** [comment]
最终的解决方案，能否分享一下
