### ISSUE TITLE
Trie抛出nullpoint异常

### ISSUE THREAD

**Issue by chenying99** [hankcs/HanLP#357]
大神好，我调用hanlp分词时， 抛出如下异常：

java.lang.NullPointerException
	at com.hankcs.hanlp.algoritm.ahocorasick.trie.Trie.getState(Trie.java:212)
	at com.hankcs.hanlp.algoritm.ahocorasick.trie.Trie.parseText(Trie.java:140)
	at com.hankcs.hanlp.dictionary.nt.OrganizationDictionary.parsePattern(OrganizationDictionary.java:3749)
	at com.hankcs.hanlp.recognition.nt.OrganizationRecognition.Recognition(OrganizationRecognition.java:70)
	at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.segSentence(ViterbiSegment.java:97)
	at com.hankcs.hanlp.seg.Segment.seg(Segment.java:466)
	
【测试时，如果不开启命名实体识别功能，则正常运行】

我测试时，打印出来是下面的地方 currentState为null

/**
     * 跳转到下一个状态
     *
     * @param currentState 当前状态
     * @param character    接受字符
     * @return 跳转结果
     */
    private static State getState(State currentState, Character character)
    {
    	
        State newCurrentState = currentState.nextState(character);  // 先按success跳转
        while (newCurrentState == null) // 跳转失败的话，按failure跳转
        {
        	
            currentState = currentState.failure();

      **//这里我打印出 currentState为nullpoint**
           
            newCurrentState = currentState.nextState(character);
        }
       
        return newCurrentState;
    }

我的调用方式这这样的：

public HanlpTokenizer(String text) {
		//tokenizer = new StringTokenizer(tokens);
		//System.out.println("当前文本:"+text);
		
		//System.out.println("构造函数");
		tokens = new ArrayList<String>();
		
		
		Segment defaultSegment = StandardTokenizer.SEGMENT
				.enablePartOfSpeechTagging(true).enableOffset(true)
				.enableNameRecognize(true).enablePlaceRecognize(true)
				.enableOrganizationRecognize(true);
		
		if(text!=null&&text.trim().length()>0)
		{
			//System.out.println(text);
			//List<Term> list=null;
			try {
				//System.out.println("输入："+text);
				List<Term> list = defaultSegment.seg(text);
				//System.out.println(list);							
				
				
			} catch (Exception e) {
				// TODO: handle exception
				e.printStackTrace();
				System.out.println(text);
				
				//System.out.println(e);
			}
		}		
		
	}

最外层是在多线程里面调用的 谢谢

**Comment by hankcs** [comment]
请问究竟是哪句text导致抛出异常，谢谢。

**Comment by chenying99** [comment]
大神好，我观察了一下，每次运行输出那些text是不固定的

问题有点奇怪：

比如我在main方法里面运行1000次都不会抛出异常

Segment defaultSegment = StandardTokenizer.SEGMENT
				.enablePartOfSpeechTagging(true).enableOffset(true)
				.enableNameRecognize(true).enablePlaceRecognize(true)
				.enableOrganizationRecognize(true);
		String str="到了16世纪，算术、初等代数、以及三角学等初等数学已大体完备。17世纪变量概念的产生使人们开始研究变化中的量与量的互相关系和图形间的互相变换。在研究经典力学的过程中，发明了微积分。随着自然科学和技术的进一步发展，为研究数学基础而产生的集合论和数理逻辑等也开始慢慢发展。";
		
		for(int i=0;i<1000;i++)
		{
			try {
				defaultSegment.seg(str);
				
			} catch (Exception e) {
				// TODO: handle exception
				System.out.println("有没有异常:"+e);
			}
		}



如果我在线程里面调用

  @Override
        public void run() {
            try {
            	Segment  defaultSegment=StandardTokenizer.SEGMENT.enablePartOfSpeechTagging(true).enableOffset(true)
                		.enableNameRecognize(true).enablePlaceRecognize(true)
                		.enableOrganizationRecognize(true);
            	
                while (shouldWork.get()) {
                    LabelledDocument document = stringsBuffer.take();

                    if (document == null || document.getContent() == null)
                        break;

                    processing.incrementAndGet();
                    
                    String str=document.getContent();
                    try {
                    	 List<Term> list = defaultSegment.seg(str);
						
					} catch (Exception e) {
						// TODO: handle exception
						System.out.println("TokenizerThread抛出异常:\n"+e);
						System.out.println(str);
					}
                   

                    Sequence<VocabWord> sequence = sentenceTransformer.transformToSequence(str);

                    for (String label: document.getLabels()) {
                        sequence.addSequenceLabel(new VocabWord(1.0, label));
                    }

                    if (sequence != null)
                        sequencesBuffer.put(sequence);

                    processing.decrementAndGet();
                }
            } catch (InterruptedException e) {
                // do nothing
                shutdown();
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        }

TokenizerThread抛出异常:
java.lang.NullPointerException
到了16世纪，算术、初等代数、以及三角学等初等数学已大体完备。17世纪变量概念的产生使人们开始研究变化中的量与量的互相关系和图形间的互相变换。在研究经典力学的过程中，发明了微积分。随着自然科学和技术的进一步发展，为研究数学基础而产生的集合论和数理逻辑等也开始慢慢发展。
TokenizerThread抛出异常:
java.lang.NullPointerException
地理质性方法（Geographic Qualitative Methods），或民族志学（Ethnography）的研究技术被人文地理学家所采用。文化地理学有利用质性研究的传统，而质性研究亦被人类学及社会学利用。人文地理学家透过参与观察（Participant observation）及深入访问取得质性资料。
TokenizerThread抛出异常:
java.lang.NullPointerException
数学从古至今便一直不断地延展，且与科学有丰富的相互作用，并使两者都得到好处。数学在历史上有著许多的发现，并且直至今日都还不断地发现中。依据Mikhail B. Sevryuk于美国数学会通报2006年1月的期刊中所说，“存在于数学评论资料库中论文和书籍的数量自1940年(数学评论的创刊年份)现已超过了一百九十万份，而且每年还增加超过七万五千份的细目。此一学海的绝大部份为新的数学定理及其证明。”

**Comment by chenying99** [comment]
而且 Segment defaultSegment = StandardTokenizer.SEGMENT
						.enablePartOfSpeechTagging(true).enableOffset(true)
						.enableNameRecognize(true).enablePlaceRecognize(true)
						.enableOrganizationRecognize(true);
放在构造函数里面初始化或成员变量声明初始化  都一样（都会抛出上面的异常）

**Comment by chenying99** [comment]
创建了多个线程

 for (int x = 0; x < threads.length; x++) {
            threads[x] = new TokenizerThread(x, transformer,stringBuffer, buffer, processing);
            threads[x].start();
        }

**Comment by hankcs** [comment]
应该是上游Robert Bor的代码非线程安全。
应该解决了：https://github.com/hankcs/HanLP/commit/b60d57c7dbb2762d0967bd19dd4059ac738f3720
如果还有问题欢迎重开issue。
