### ISSUE TITLE
Viterbi 算法中求解最大概率都变成加法，非乘法

### ISSUE THREAD

**Issue by shanghai-Jerry** [hankcs/HanLP#359]
com.hankcs.hanlp.algoritm 下的Viterbi算法求解最大概率都变成加法，这是为何？`V[0][y] = start_p[y] + emit_p[y][obs[0]];`

**Comment by hankcs** [comment]
因为都提前取了对数。

**Comment by shanghai-Jerry** [comment]
哦， 明白了。

**Comment by zeekvfu** [comment]
@hankcs 
hello，请教下：
Viterbi 解码时，把乘法运算转化为加法运算，目的是为了减小计算开销么？
因为加法运算比乘法运算开销小。虽然需要取对数，但是只要提前计算一次即可。
是这样么？

**Comment by hankcs** [comment]
不是，而是为了防止下溢出。

**Comment by zeekvfu** [comment]
@hankcs Thanks :-)
