### ISSUE TITLE
初始化分词器时，字符类型对应表加载失败（CharType.dat.yes）

### ISSUE THREAD

**Issue by chenying99** [hankcs/HanLP#361]
大神好，这个异常不是每一次都出现（偶尔出现）

下面我在eclipse上测试时的输出的信息

**********************************************************************************

十二月 06, 2016 1:59:13 下午 com.hankcs.hanlp.HanLP$Config <clinit>
严重: 没有找到HanLP.properties，可能会导致找不到data
========Tips========
请将HanLP.properties放在下列目录：
D:\workspace\****\target\classes
Web项目则请放到下列目录：
Webapp/WEB-INF/lib
Webapp/WEB-INF/classes
Appserver/lib
JRE/lib
并且编辑root=PARENT/path/to/your/data
现在HanLP将尝试从D:\workspace\****读取data……
十二月 06, 2016 1:59:13 下午 com.hankcs.hanlp.corpus.io.IOUtil readBytes
警告: 读取data/dictionary/CoreNatureDictionary.txt.bin时发生异常java.nio.channels.ClosedByInterruptException
十二月 06, 2016 1:59:25 下午 com.hankcs.hanlp.corpus.io.IOUtil readBytes
警告: 读取data/dictionary/other/CharType.dat.yes时发生异常java.nio.channels.ClosedByInterruptException
字符类型对应表加载失败：data/dictionary/other/CharType.dat.yes

****************************************************************************************

然后程序到这里就结束了

对应目录 文件是存在的 【data/dictionary/other/CharType.dat.yes】

**Comment by chenying99** [comment]
对应目录  文件是存在的  【data/dictionary/other/CharType.dat.yes】

**Comment by hankcs** [comment]
将hanlp.properties放到src顶级目录并修改root即可。实在搞不定就用portable版吧。

**Comment by kingsdu** [comment]
@hankcs
我也遇到了这个问题，我下载的数据并没有这个文件，然后我随便找一个文件修改了文件名称为“CharType.dat.yes”，然后就可以运行出结果了。
请问，这个文件在哪里下载啊，我下载的600多M的data中都没有这个文件。

**Comment by hankcs** [comment]
最新版已经不需要这个文件了

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
