### ISSUE TITLE
CoreStopWordDictionary里面 FILTER 过滤器实际表现与注释不符

### ISSUE THREAD

**Issue by ljw7630** [hankcs/HanLP#365]
注释为: "核心停用词典的核心过滤器，词性属于名词、动词、副词、形容词，并且不在停用词表中才不会被过滤" 但实际上, 就算是满足条件的名词/动词 只要长度为1, 也会被干掉. 对应 代码:
line 94: `if (term.word.length() > 1 && !CoreStopWordDictionary.contains(term.word))`

**Comment by ljw7630** [comment]
考虑到一些名词/动词 实际长度确实为1, 这里是不是一个bug呢?

**Comment by chenying99** [comment]
这个属于业务需求，可以自定义

**Comment by hankcs** [comment]
哦，文档太旧了，@chenying99 说的很对。
