### ISSUE TITLE
关于动态添加字典的问题

### ISSUE THREAD

**Issue by chenhanbao** [hankcs/HanLP#367]
hankcs，您好，非常感谢您为大家提供了如此方便的NLP工具。我现在遇到的问题是在分词之前可以获取到当前文档的很多实体缩写名称。然后想通过CustomDictionary.insert()方法动态添加字典增加识别的精确度。但是很多添加的字典没法准确识别，不知道是因为什么？是不是我使用的方法有错误？

@Test
	public void dictionaryTest() {
		Segment segment = HanLP.newSegment().enableCustomDictionary(true)
				.enableOrganizationRecognize(true);
		String str = "现在总统数码港、自由闲、北海高岭、总统大酒店四家签订了协议";
		List<Term> termList = segment.seg(str);
		CustomDictionary.insert("总统数码港", "nt 1024");
		CustomDictionary.insert("自由闲", "nt 1024");
		CustomDictionary.insert("北海高岭", "nt 1024");
		CustomDictionary.insert("总统大酒店", "nt 1024");
		System.out.println(termList);
	}
结果是这样的
[现在/t, 总统/nnt, 数码港/nz, 、/w, 自由/a, 闲/v, 、/w, 北海/ns, 高/a, 岭/ng, 、/w, 总统/nnt, 大酒店四家/nt, 签订/v, 了/ule, 协议/n]

**Comment by hankcs** [comment]
不客气，动态插入的词条会在下次分词时生效，应该这样调：

Segment segment = HanLP.newSegment().enableCustomDictionary(true)
                .enableOrganizationRecognize(true);
        CustomDictionary.insert("总统数码港", "nt 1024");
        CustomDictionary.insert("自由闲", "nt 1024");
        CustomDictionary.insert("北海高岭", "nt 1024");
        CustomDictionary.insert("总统大酒店", "nt 1024");

        String str = "现在总统数码港、自由闲、北海高岭、总统大酒店四家签订了协议";
        List termList = segment.seg(str);
        System.out.println(termList);

**Comment by chenhanbao** [comment]
是我太粗心了，这个测试案例写的时候没有细看，直接粘贴的。非常感谢解答

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
