### ISSUE TITLE
繁体中文识别人名

### ISSUE THREAD

**Issue by Tony-Wang** [hankcs/HanLP#37]
"「國際足球總會」（FIFA）主席布拉特（Sepp Blatter）5月29日連任成功."

将“任成功”识别为人名，感觉粗暴的将“任成功”加到nr.txt里似乎不妥，也许某些语境里真有人叫“任成功”，不知道有没有更好的处理办法。

**Comment by hankcs** [comment]
繁体中文请优先使用繁体分词器：

System.out.println(TraditionalChineseTokenizer.segment(
                "5月29日連任成功."
        ));

输出：

[「/w, 國際足球/nz, 總會/nis, 」/w, （/w, FIFA/nx, ）/w, 主蓆/nnt, 布拉特/nrf, （/w, Sepp/nx,  /w, Blatter/nx, ）/w, 5/m, 月/n, 29/m, 日/b, 連任/v, 成功/a, ./w]

**Comment by hankcs** [comment]
简繁混合的模式下，最好开启自动正规化，详细请通过IDE阅读这些配置项的文档

        HanLP.Config.Normalization = true;
        System.out.println(StandardTokenizer.segment(
                "5月29日連任成功.简体中文连任成功"
        ));

[5/m, 月/n, 29/m, 日/b, 连任/v, 成功/a, ./w, 简体中文/gi, 连任/v, 成功/a]

**Comment by Tony-Wang** [comment]
谢谢，问题得到了解决。
