### ISSUE TITLE
自定义词典不起作用

### ISSUE THREAD

**Issue by DisneyLu** [hankcs/HanLP#370]
1、在data\dictionary\custom目录下新建自定义词典my.txt，内容如下：
      风中有朵雨做的云
      一千个伤心的理由
      忘情水
2、在hanlp.properties中增加my.txt
CustomDictionaryPath=data/dictionary/custom/CustomDictionary.txt; my.txt ns; 现代汉语补充词库.txt; 全国地名大全.txt ns; 人名词典.txt; 机构名词典.txt; 上海地名.txt;data/dictionary/person/nrf.txt nrf
3、测试：
   String content = "张学友的一千个伤心的理由是一首好听的歌";
   Segment seg = HanLP.newSegment().enableCustomDictionary(true);
   List<Term> termList = seg.seg(content);
   System.out.println(termList);
   List<String> keywordList = HanLP.extractKeyword(content, 5);
   System.out.println(keywordList);

   输出结果如下：
[张学友/nr, 的/ude1, 一千个/nz, 伤心/a, 的/ude1, 理由/n, 是/vshi, 一/m, 首/q, 好听/a, 的/ude1, 歌/n]
[张学友, 理由, 伤心, 一千个, 好听]

4、结论：
     自定义词典没起到作用
     （如果在分词之前执行了CustomDictionary.add("一千个伤心的理由");就能起作用）

请问我的用法有问题吗？

**Comment by DisneyLu** [comment]
补充说明：已经删除了缓存CustomDictionary.txt.bin，并重新生成了，还是不行的

**Comment by hankcs** [comment]
极有可能是词典加载出了问题，请删除缓存后HanLP.Config.enableDebug()观察调试输出。

**Comment by DisneyLu** [comment]
**貌似加载自定义词典没问题啊，如下DEBUG信息：**

十二月 14, 2016 10:19:51 上午 com.hankcs.hanlp.dictionary.CoreDictionary load
信息: 核心词典开始加载:E:/BaiduYunDownload/HanLP/data/dictionary/CoreNatureDictionary.txt
十二月 14, 2016 10:19:51 上午 com.hankcs.hanlp.dictionary.CoreDictionary <clinit>
信息: E:/BaiduYunDownload/HanLP/data/dictionary/CoreNatureDictionary.txt加载成功，153115个词条，耗时80ms
十二月 14, 2016 10:19:51 上午 com.hankcs.hanlp.dictionary.other.CharType <clinit>
信息: 字符类型对应表开始加载 E:/BaiduYunDownload/HanLP/data/dictionary/other/CharType.dat.yes
十二月 14, 2016 10:19:51 上午 com.hankcs.hanlp.dictionary.other.CharType <clinit>
信息: 字符类型对应表加载成功，耗时42 ms
十二月 14, 2016 10:19:51 上午 com.hankcs.hanlp.dictionary.CoreBiGramTableDictionary <clinit>
信息: 开始加载二元词典E:/BaiduYunDownload/HanLP/data/dictionary/CoreNatureDictionary.ngram.txt.table
粗分词网：
0:[ ]
1:[张]
2:[学, 学友]
3:[友]
4:[的]
5:[一千个]
6:[]
7:[个]
8:[伤, 伤心]
9:[心]
10:[的]
11:[理, 理由]
12:[由]
13:[是]
14:[一]
15:[首]
16:[好, 好听]
17:[听]
18:[的]
19:[歌]
20:[ ]

十二月 14, 2016 10:19:51 上午 com.hankcs.hanlp.dictionary.CoreBiGramTableDictionary <clinit>
信息: E:/BaiduYunDownload/HanLP/data/dictionary/CoreNatureDictionary.ngram.txt.table加载成功，耗时88ms
十二月 14, 2016 10:19:51 上午 com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
信息: 自定义词典开始加载:E:/BaiduYunDownload/HanLP/data/dictionary/custom/CustomDictionary.txt
十二月 14, 2016 10:19:51 上午 com.hankcs.hanlp.corpus.io.IOUtil readBytes
警告: 读取E:/BaiduYunDownload/HanLP/data/dictionary/custom/CustomDictionary.txt.bin时发生异常java.io.FileNotFoundException: E:\BaiduYunDownload\HanLP\data\dictionary\custom\CustomDictionary.txt.bin (系统找不到指定的文件。)
十二月 14, 2016 10:19:51 上午 com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
信息: 以默认词性[n]加载自定义词典E:/BaiduYunDownload/HanLP/data/dictionary/custom/CustomDictionary.txt中……
十二月 14, 2016 10:19:51 上午 com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
**信息: 以默认词性[ns]加载自定义词典E:/BaiduYunDownload/HanLP/data/dictionary/custom/songs.txt中……**
十二月 14, 2016 10:19:51 上午 com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
信息: 以默认词性[n]加载自定义词典E:/BaiduYunDownload/HanLP/data/dictionary/custom/现代汉语补充词库.txt中……
十二月 14, 2016 10:19:52 上午 com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
信息: 以默认词性[ns]加载自定义词典E:/BaiduYunDownload/HanLP/data/dictionary/custom/全国地名大全.txt中……
十二月 14, 2016 10:19:52 上午 com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
信息: 以默认词性[n]加载自定义词典E:/BaiduYunDownload/HanLP/data/dictionary/custom/人名词典.txt中……
十二月 14, 2016 10:19:52 上午 com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
信息: 以默认词性[n]加载自定义词典E:/BaiduYunDownload/HanLP/data/dictionary/custom/机构名词典.txt中……
十二月 14, 2016 10:19:52 上午 com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
信息: 以默认词性[n]加载自定义词典E:/BaiduYunDownload/HanLP/data/dictionary/custom/上海地名.txt中……
十二月 14, 2016 10:19:52 上午 com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
信息: 以默认词性[nrf]加载自定义词典E:/BaiduYunDownload/HanLP/data/dictionary/person/nrf.txt中……
十二月 14, 2016 10:19:52 上午 com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
信息: 正在构建DoubleArrayTrie……
十二月 14, 2016 10:19:55 上午 com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
信息: 正在缓存词典为dat文件……
十二月 14, 2016 10:20:34 上午 com.hankcs.hanlp.dictionary.CustomDictionary <clinit>
**信息: 自定义词典加载成功:409703个词条，耗时42734ms**
粗分结果[张学友/nr, 的/ude1, 一千个/nz, 伤心/a, 的/ude1, 理由/n, 是/vshi, 一/m, 首/q, 好听/a, 的/ude1, 歌/n]
十二月 14, 2016 10:20:34 上午 com.hankcs.hanlp.dictionary.common.CommonDictionary load
信息: 加载值E:/BaiduYunDownload/HanLP/data/dictionary/person/nr.txt.value.dat成功，耗时30ms
十二月 14, 2016 10:20:34 上午 com.hankcs.hanlp.dictionary.common.CommonDictionary load
信息: 加载键E:/BaiduYunDownload/HanLP/data/dictionary/person/nr.txt.trie.dat成功，耗时30ms
人名角色观察：[  A 22202445 ][张学友 A 22202445 ][的 L 15411 K 11354 M 96 C 1 ][一千个 A 22202445 ][伤心 L 9 ][的 L 15411 K 11354 M 96 C 1 ][理由 A 22202445 ][是 K 2507 L 2504 M 123 C 10 E 1 ][一 C 1202 L 469 D 462 K 42 E 21 M 1 ][首 L 111 C 17 K 12 D 3 ][好听 A 22202445 ][的 L 15411 K 11354 M 96 C 1 ][歌 E 189 D 32 C 19 K 7 L 4 ][  A 22202445 ]
人名角色标注：[ /A ,张学友/A ,的/K ,一千个/A ,伤心/L ,的/K ,理由/A ,是/K ,一/C ,首/D ,好听/A ,的/K ,歌/E , /A]
[张学友/nr, 的/ude1, 一千个/nz, 伤心/a, 的/ude1, 理由/n, 是/vshi, 一/m, 首/q, 好听/a, 的/ude1, 歌/n]
十二月 14, 2016 10:20:34 上午 com.hankcs.hanlp.dictionary.nr.PersonDictionary <clinit>
信息: E:/BaiduYunDownload/HanLP/data/dictionary/person/nr.txt加载成功，耗时79ms
粗分词网：
0:[ ]
1:[张]
2:[学, 学友]
3:[友]
4:[的]
5:[一千个]
6:[]
7:[个]
8:[伤, 伤心]
9:[心]
10:[的]
11:[理, 理由]
12:[由]
13:[是]
14:[一]
15:[首]
16:[好, 好听]
17:[听]
18:[的]
19:[歌]
20:[ ]

粗分结果[张学友/nr, 的/ude1, 一千个/nz, 伤心/a, 的/ude1, 理由/n, 是/vshi, 一/m, 首/q, 好听/a, 的/ude1, 歌/n]
人名角色观察：[  A 22202445 ][张学友 A 22202445 ][的 L 15411 K 11354 M 96 C 1 ][一千个 A 22202445 ][伤心 L 9 ][的 L 15411 K 11354 M 96 C 1 ][理由 A 22202445 ][是 K 2507 L 2504 M 123 C 10 E 1 ][一 C 1202 L 469 D 462 K 42 E 21 M 1 ][首 L 111 C 17 K 12 D 3 ][好听 A 22202445 ][的 L 15411 K 11354 M 96 C 1 ][歌 E 189 D 32 C 19 K 7 L 4 ][  A 22202445 ]
人名角色标注：[ /A ,张学友/A ,的/K ,一千个/A ,伤心/L ,的/K ,理由/A ,是/K ,一/C ,首/D ,好听/A ,的/K ,歌/E , /A]
[张学友, 理由, 伤心, 一千个, 好听]

**Comment by hankcs** [comment]
奇怪，麻烦        System.out.println(LexiconUtility.getAttribute("一千个伤心的理由")); 看看到底有没有加载成功。

**Comment by DisneyLu** [comment]
LexiconUtility.getAttribute("一千个伤心的理由") = null

在分词结束之后打印的

**Comment by hankcs** [comment]
噢，你应该使用UTF-8编码的txt文件。

**Comment by DisneyLu** [comment]
确实是编码问题，OK了，非常感谢

**Comment by DisneyLu** [comment]
咨询下，对于歌曲和古代文学形式（诗词歌赋等），是不是只能通过自定义词典解决呢？

**Comment by hankcs** [comment]
现有的语料库全部都是针对现代汉语的，无法在统计模型上支持古汉语，的确只能靠词典了。

**Comment by xtuyaowu** [comment]
我也是不起作用。

**Comment by wttc** [comment]
在核心词库CoreNatureDictionary.txt中，有两个词，
华安 ns 33
精华 n 76

Segment nShortSegment = new NShortSegment()
				.enableCustomDictionary(false).enablePlaceRecognize(true)
				.enableOrganizationRecognize(true);
		String[] testCase = new String[] { "草本精华安全无添加"};
		for (String sentence : testCase) {
			System.out.println("N-最短分词：" + nShortSegment.seg(sentence)
					+ "\n最短路分词：" + shortestSegment.seg(sentence));
		}
分词结果是：草本，精，华安，全，无，添加
为什么精华比华安的频率高，反而是华安能分出来？

**Comment by hankcs** [comment]
https://github.com/hankcs/HanLP/issues/384

**Comment by KevinChen1994** [comment]
我现在使用自定义词典不生效。已经检查过文件编码格式为UTF-8了，删除了CustomDictionary.txt.bin。请问使用自定义词典生效后会生成.bin的文件吗？

**Comment by hankcs** [comment]
对，你可以在代码最开头HanLP.Config.enableDebug();排查问题。

**Comment by Samurais** [comment]
是不是只有 "index" 分词支持自定义词典？

**Comment by hankcs** [comment]
都支持，请参考：https://github.com/hankcs/HanLP/issues/303#issuecomment-274254306

**Comment by chyang2015** [comment]
即使是UTF-8格式的词典，还是不起作用，怎么办

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
