### ISSUE TITLE
关于关键词提取问题，单个字的名词好像被过滤掉了

### ISSUE THREAD

**Issue by Moving521** [hankcs/HanLP#373]
你好 !我发现一个问题不知道是不是您故意为之。在提取关键词的时候单个字的名词 被过滤掉了吧，例如一篇关于时的文章 竟然没有时这个关键词，
我看了下你的源码 版本 1.3.1 com.hankcs.hanlp.summary.TextRankKeyword.class 类中的方法shouldInclude
/**
* 是否应当将这个term纳入计算，词性属于名词、动词、副词、形容词
*
* @param term
* @return 是否应当
*/
public boolean shouldInclude(Term term){
...
default:
{
if (term.word.trim().length() > 1 && !CoreStopWordDictionary.contains(term.word))
{
return true;
}
} //这句话是不是有点不妥？ 希望能及时收到回复！我的邮箱 515504936@qq.com
...
return false;
}

**Comment by hankcs** [comment]
https://github.com/hankcs/HanLP/issues/365

**Comment by Moving521** [comment]
term.word.trim().length() > 1  这句话把单字名词过滤掉了啊！
