### ISSUE TITLE
用户自定义词典

### ISSUE THREAD

**Issue by fangyuan930917** [hankcs/HanLP#374]
请问如果在hanlp.properties文件中配置了用户自定义词典

CustomDictionaryPath=data/dictionary/custom/CustomDictionary.txt; 流行新歌词汇.txt; 电影大全词典.txt;　现代汉语补充词库.txt; 全国地名大全.txt ns; 人名词典.txt; 
之后
 val content="我喜欢看小岛惊魂，阿甘正传，致命ID，禁闭岛,小叮当与海盗仙子，肖申克的救赎.我喜欢听阿波狂想曲"
　println(StandardTokenizer.segment(content))

是优先去根据用户自定义的词典进行分词吗，如果我希望先标准分词，之后再用户自定义词典分词应该怎样操作呢？
有没有可以显示手动关闭用户自定义词典分词的功能，之后要用的时候再启用的函数呢？

**Comment by hankcs** [comment]
0. https://github.com/hankcs/HanLP/wiki/FAQ#%E4%B8%BA%E4%BB%80%E4%B9%88%E4%BF%AE%E6%94%B9%E4%BA%86%E8%AF%8D%E5%85%B8%E8%BF%98%E6%98%AF%E6%B2%A1%E6%9C%89%E6%95%88%E6%9E%9C
0.  Segment segment = StandardTokenizer.SEGMENT.enableCustomDictionary(false);

**Comment by fangyuan930917** [comment]
hancks您好，最近使用hanlp自定义词典功能在打包的时候遇到了一些trick 
我的hanlp.properties文件放在项目的resource下，打包的时候会自己导入
通过一些其他途径，我也在打包后生成了data/dictionary/custom/一些自定义词典
打完包后hanlp.properties和data是位于同一层级，我不知道您是通过哪种方式来读入自定义词典的，但好像您不是采用getResource这种方式
现在我在hanlp.properties中设置root=. (当前目录),在集群上运行时，然后一直提示找不到Data，也无法使用自定义词典，这是我的hanlp.properties
#本配置文件中的路径的根目录，根目录+其他路径=绝对路径
#Windows用户请注意，路径分隔符统一使用/
root=./
#src/main/resources/
#核心词典路径
CoreDictionaryPath=data/dictionary/CoreNatureDictionary.txt
#2元语法词典路径
BiGramDictionaryPath=data/dictionary/CoreNatureDictionary.ngram.txt
#停用词词典路径
CoreStopWordDictionaryPath=data/dictionary/stopwords.txt
#同义词词典路径
CoreSynonymDictionaryDictionaryPath=data/dictionary/synonym/CoreSynonym.txt
#人名词典路径
PersonDictionaryPath=data/dictionary/person/nr.txt
#人名词典转移矩阵路径
PersonDictionaryTrPath=data/dictionary/person/nr.tr.txt
#繁简词典路径
TraditionalChineseDictionaryPath=data/dictionary/tc/TraditionalChinese.txt
#自定义词典路径，用;隔开多个自定义词典，空格开头表示在同一个目录，使用“文件名 词性”形式则表示这个词典的词性默认是该词性。优先级递减。
#另外data/dictionary/custom/CustomDictionary.txt是个高质量的词库，请不要删除
CustomDictionaryPath=data/dictionary/custom/CustomDictionary.txt; MusicDictionary.txt; MovieDictionary.txt; LanguageAddDictionary.txt LocationDictionary.txt ns; PeopleNameDictionary.txt; OrgnizationDictionary.txt; 
#CRF分词模型路径
#CRFSegmentModelPath=data/model/segment/CRFSegmentModel.txt
#HMM分词模型
#HMMSegmentModelPath=data/model/segment/HMMSegmentModel.bin
#分词结果是否展示词性
ShowTermNature=true



运行时候提示结果
17/01/04 14:23:37 WARN HanLP: root=./ 这个目录下没有data
17/01/04 14:23:37 WARN HanLP: 读取./data/dictionary/custom/CustomDictionary.txt.bin时发生异常java.io.FileNotFoundException: ./data/dictionary/custom/CustomDictionary.txt.bin (没有那个文件或目录)
17/01/04 14:23:37 WARN HanLP: 失败：./data/dictionary/custom/CustomDictionary.txt
17/01/04 14:23:37 WARN HanLP: 失败：./data/dictionary/custom/MusicDictionary.txt
17/01/04 14:23:37 WARN HanLP: 失败：./data/dictionary/custom/MovieDictionary.txt
17/01/04 14:23:37 WARN HanLP: 已激活自定义词性功能,由于采用了反射技术,用户需对本地环境的兼容性和稳定性负责!
如果用户代码X.java中有switch(nature)语句,需要调用CustomNatureUtility.registerSwitchClass(X.class)注册X这个类
17/01/04 14:23:37 WARN HanLP: 失败：./data/dictionary/custom/LanguageAddDictionary.txt
17/01/04 14:23:37 WARN HanLP: 失败：./data/dictionary/custom/PeopleNameDictionary.txt
17/01/04 14:23:37 WARN HanLP: 失败：./data/dictionary/custom/OrgnizationDictionary.txt
17/01/04 14:23:37 WARN HanLP: 失败：./data/dictionary/custom/
17/01/04 14:23:37 WARN HanLP: 没有加载到任何词条
17/01/04 14:23:37 ERROR HanLP: 自定义词典./data/dictionary/custom/CustomDictionary.txt不存在！java.io.FileNotFoundException: ./data/dictionary/custom/CustomDictionary.txt.bin (没有那个文件或目录)
17/01/04 14:23:37 WARN HanLP: 自定义词典[./data/dictionary/custom/CustomDictionary.txt, ./data/dictionary/custom/MusicDictionary.txt, ./data/dictionary/custom/MovieDictionary.txt, ./data/dictionary/custom/LanguageAddDictionary.txt LocationDictionary.txt ns, ./data/dictionary/custom/PeopleNameDictionary.txt, ./data/dictionary/custom/OrgnizationDictionary.txt, ./data/dictionary/custom/]加载失败



我想问下您，读取自定义词典的代码是在哪个类呢，是否root路径应该针对该类来定义？ 谢谢～

**Comment by hankcs** [comment]
非portable版无法读取jar包中的data，图方便的话可以用zip解压工具替换portable版jar中的data

**Comment by fangyuan930917** [comment]
我使用的是"portable-1.3.1"的hanlp呀

**Comment by fangyuan930917** [comment]
我是自己建立了一个自己的data目录，放在工程根目录下，并没有使用hancks：portable-1.3.1.jar中的data，是需要我对hancks的jar包中的data目录进行修改 添加自定义词典吗

**Comment by cicido** [comment]
我也有同样的问题。关注

**Comment by tankle** [comment]
在pom里面引用了portable 版本，然后还需要加入自定义的词典，这个在properties中怎么配置？

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
