### ISSUE TITLE
名字识别的问题

### ISSUE THREAD

**Issue by allenxu** [hankcs/HanLP#387]
你好，
最近发现hanlp对名字的识别有时候会有些偏差，比如“全季吧”被识别成了nr。
看nr.txt里的内容没有看懂，请问有什么办法可以解决这个问题吗？
多谢！

**Comment by allenxu** [comment]
有一定的误命中率，比如误命中关键年，则可以通过在data/dictionary/person/nr.txt加入一条关键年 A 1来排除关键年作为人名的可能性，也可以将关键年作为新词登记到自定义词典中。

sorry，发现这段，解决了

**Comment by allenxu** [comment]
改了以后出现了连带问题，“住全季” 被识别成了nt 。 这下wiki没写怎么改nt.txt了，能告知一下吗？

**Comment by hankcs** [comment]
请参考https://github.com/hankcs/HanLP/commit/c51bdc27e24158387af291e0362aca49ccd5609a
http://www.hankcs.com/nlp/ner/place-name-recognition-model-of-the-stacked-hmm-viterbi-role-labeling.html

**Comment by allenxu** [comment]
多谢~

**Comment by smile0925** [comment]
三个字的名字有时候被识别成两个字（缺少第三个字），这种情况怎么解决？

**Comment by 15773200610** [comment]
大佬们请教一下，像江河、汪洋这种既是名词也是人名，默认判断是名词。。需要怎么改成判断结果为人名呢
