### ISSUE TITLE
CRF model bin文件可以怎么生成对应的txt文件吗

### ISSUE THREAD

**Issue by jkneng** [hankcs/HanLP#388]
想在C++环境里用hanlp里的CRF分词模型，但不知道怎么解析。
如果能转换为对应的txt文件，就可以使用CRF++来转换读取了
如果不能生成为txt文件的话， @hankcs 可以分享一份吗，谢谢！

**Comment by hankcs** [comment]
0. 无此功能
0. CRFSegmentModel.txt是CRF++训练出来的文本模型，转成bin之后就删掉了。

**Comment by jkneng** [comment]
@hankcs 了解了，谢谢~

**Comment by Jactor-Sue** [comment]
@hankcs 请问是如何将训练出来的.txt文件转换为.bin 的呢？我的目的是希望使用自己用CRF++训练出来的模型代替HanLP提供的模型。希望有时间能回答一下，谢谢！

**Comment by hankcs** [comment]
@Jactor-Sue 请参考：https://github.com/hankcs/HanLP/wiki/FAQ#%E4%B8%BA%E4%BB%80%E4%B9%88%E5%8A%A0%E8%BD%BD%E6%88%91%E8%87%AA%E5%B7%B1%E8%AE%AD%E7%BB%83%E7%9A%84crf%E6%A8%A1%E5%9E%8B%E5%A4%B1%E8%B4%A5%E4%BA%86
