### ISSUE TITLE
CRF分词不能用

### ISSUE THREAD

**Issue by Bahramudin** [hankcs/HanLP#389]
我当用CRF分词器的时候Java会抛异常：

> ```
> 读取data/model/segment/CRFSegmentModel.txt.bin时发生异常java.lang.NullPointerException
> 在读取过程中发生错误java.lang.NullPointerException
> CRF分词模型加载 data/model/segment/CRFSegmentModel.txt 失败，耗时 55 ms
> java.io.FileNotFoundException: data\model\segment\CRFSegmentModel.txt (系统找不到指定的路径。)
> ```

请问这是怎么回事呢，怎么能解决。谢谢！！

**Comment by hankcs** [comment]
1. 请使用最新版
2. 原因是你没有正确配置hanlp.properties，请参考首页文档

**Comment by Bahramudin** [comment]
你好！我用的已经是最新版本`<version>portable-1.3.2</version>`。这个都已经自动下载的资料，跑了几个算法都可以，比如 **标准分词**， **NLP分词**都可以，可是当用**CRF分词**的时候就出问题，那这个我怎么配置，能说具体一点吗，百度上也没有找到什么好的资料，文档也没说的很清楚，其实用maven都自己可以配置的。然后我尝试下载zip包也半天下不下来，不知道怎么回事事儿，我的网络还是挺快的，好像是你们服务器不行，经常超时或者无法下载。谢谢！

**Comment by hankcs** [comment]
1. 请参考https://github.com/hankcs/HanLP#下载与配置
文档已经写明portable版在未配置的情况下只能使用基本功能（除CRF分词、依存句法分析外的全部功能）。如果用户有自定义的需求，可以参考方式二，使用hanlp.properties进行配置。
2. 我只有一台服务器，压力过大，请使用网盘分流。

**Comment by Bahramudin** [comment]
你好！我已经下载了Jar包和数据包，都已经能跑了，现在关键是那个对数据包的路径能不能做个动态的，现在是静态的，这个不太方便，如果我把项目打包的话 就那些数据在另个电脑就没有，并且我得单独copy，那怕是copy还得放在一模一样的目录里。我想能不能这样做，我们把需要的词典放在项目里，然后程序就直接从项目里面找就行了，当项目打包的时候就不用担心其他东西了，直接哪里都能用。谢谢！！

**Comment by hankcs** [comment]
https://github.com/hankcs/HanLP/issues/380
