### ISSUE TITLE
运行时出现文件读取问题 这个com.hankcs.hanlp.corpus.io.IOUtil包运行出错

### ISSUE THREAD

**Issue by kelciej** [hankcs/HanLP#391]
![1](https://cloud.githubusercontent.com/assets/19542871/22288090/570e707e-e330-11e6-9def-0bfb92f50d1d.PNG)
![2](https://cloud.githubusercontent.com/assets/19542871/22288091/570f1614-e330-11e6-8a65-0373bd1c1554.PNG)
![3](https://cloud.githubusercontent.com/assets/19542871/22288092/5711489e-e330-11e6-989d-79e2419b39bf.PNG)

我指定的root是在C盘eclipse的workplace路径下，并且我的D盘并没有 Doc\语料库 这个文件夹，所以特来请求大神，帮我看一下是什么原因？？？拜托了

**Comment by TylunasLi** [comment]
请不要直接执包中的main()方法，这些方法本应剥离到test中用于处理训练数据，其中的路径都是写死的。
同样也请注意，不要扫描本库中的包（如集成到Spring时）。

**Comment by hankcs** [comment]
感谢反馈，感谢 @TylunasLi 解答，已经去掉了这些main方法

**Comment by wangpeng138375** [comment]
请问在移除main方法之前，main里面有个“2014_dictionary.txt”，请问这个词典和“CoreNatureDictionary.txt”里面的词是一样的吗？因为我发现在HMM做中文人名识别的时候，是基于“CoreNatureDictionary.txt”做的词图。

**Comment by hankcs** [comment]
具体我记不清了，从名字来看，就是一样的。

**Comment by wangpeng138375** [comment]
为什么nr.tr.txt 中没有Y（姓与单名成词）标签？nr.txt中也没有这个标签？
