### ISSUE TITLE
关于词的重叠无法被识别的问题

### ISSUE THREAD

**Issue by moshangshaoguang** [hankcs/HanLP#393]
例如：石/ng, 台东/ns, 柱/ng, 食品/n, 有限公司
由于“台东“已经被标记成ns，“石台“也被标记成ns，“东柱“也被标记成了ns 最后显示的结果，就是例子中显示的那样，怎么去修改才能让它变成  石台/ns 东柱/ns 食品/n 有限公司呢，在不删除 “台东“被标记成ns的情况下

**Comment by hankcs** [comment]
https://github.com/hankcs/HanLP/issues/384

**Comment by moshangshaoguang** [comment]
你确定我说的意思跟这个#384的是一样的 我的是也修正了但是不能被识别，我都标记成ns 最后的结果也不是G，最后出来的结果 石/Z, 台东/G, 柱/Z, 食品/C, 有限公司D    我想要的结果是 石台/G 东柱/G食品/C 有限公司D  在文件中我已经 把 石台  台东 东柱 都标记成了 ns了 结果是识别出了 台东 是G 而石台 东柱 都没有被识别出来

**Comment by TylunasLi** [comment]
意思是修改 data/dictionary/CoreNatureDictionary.ngram.txt 并更新缓存。
同时你也要修改 data/dictionary/CoreNatureDictionary.txt 把“东柱”加入核心词典。
机构名识别基于正确的分词结果，但是你的例子产生了“含有未登录词的交集型歧义”。所以仅仅修改自定义词典还不够，需要再修改以上两个词典，各告诉分词器正确的切分路径。

**Comment by moshangshaoguang** [comment]
非常感谢，现在我知道问题出在哪了

**Comment by kelciej** [comment]
@TylunasLi, 你好， data/dictionary/CoreNatureDictionary.ngram.txt词典怎么修改，
／@未##人	16
／@画	2
／@诗	1
：@末##末	3258
；@末##末	2636
＞@未##数	1
？@末##末	771
［@附记	1
］@末##末	1
买@水果 1
然后@来 1
我@遗忘 10
遗忘@我 10

里面的一次词语的标注我看不太懂，能稍微解释一下么，谢谢！

**Comment by kelciej** [comment]
@moshangshaoguang ，你好，你的问题解决了么？只要修改核心词典和二元词典就可以了么，代码方面需要增加或者修改什么内容么？？
一下面是我的测试代码的内容，但是一直出错，

CRFSegment segment = new CRFSegment();
		String ss="哪些药产自上海";	
		segment.enableCustomDictionary(true);
		List<Term> seg = segment.seg(ss);

输出结果：
[哪些/r, 药产/nz, 自/p, 上海/ns]

理想结果：
[哪些/r, 药/n, 产自/v, 上海/ns]
方便的话，请指导一下
