### ISSUE TITLE
很多人名nr被标记状态词zg，这是为什么呢

### ISSUE THREAD

**Issue by xinheblue** [hankcs/HanLP#398]
比如
[按照/dg, 习近平/zg, 指示/yg, 和/pbei, 李克强/zg, 要求/yg, ，/xx, 外交部/ntcb, 和/pbei, 我国/yg, 驻/s, 马来西亚/nr2, 使领馆/yg, 加强/s, 同/dg

我看了下训练字典里面，习近平和李克强都是nr

**Comment by hankcs** [comment]
https://github.com/hankcs/HanLP#修改方法

**Comment by TylunasLi** [comment]
你修改了Nature类还把你自己的词性加在了前面。此时一定要清理缓存。
Nature类是枚举值，缓存序列化时存储的是枚举的序号。所以改变Nature类的后必须清缓存。
