### ISSUE TITLE
大赞，不过摘要效果有点问题

### ISSUE THREAD

**Issue by lipiji** [hankcs/HanLP#4]
提供的例子结果是：
[无限算法的产生是由于未能确定的定义终止条件, 这类算法在有限的时间内终止, 这类算法在有限的一段时间内终止]

看来还是有很多优化空间的。

不过这么全面的NLP package已经很赞了，剩下的优化过程其实相对容易一些啦~

**Comment by hankcs** [comment]
嗯，谢谢支持。
自动摘要是个很复杂的问题，现在由TextRank提供的摘要功能只做到大概能用。未来的发展是个长远问题。

**Comment by hankcs** [comment]
不好意思，今天发现问题还出在停用词词典的编码问题上，自从将JDK版本从1.7降级到1.6后，InputStreamReader的默认编码不再是UTF-8，导致停用词词典失效了，最终使得自动摘要的效果降低。
现在这个例子结果应该是：
[无限算法的产生是由于未能确定的定义终止条件, 这类算法在有限的时间内终止, 这类算法在有限的一段时间内终止]

**Comment by hankcs** [comment]
不好意思，今天发现问题还出在停用词词典的编码问题上，自从将JDK版本从1.7降级到1.6后，InputStreamReader的默认编码不再是UTF-8，导致停用词词典失效了。

至于具体效果，虽然没有提升，但避免了下降吧。
