### ISSUE TITLE
自定义词的词形分词后出现错误

### ISSUE THREAD

**Issue by weisong82** [hankcs/HanLP#403]
北京拉手网络技术有限公司 ntc 1  词典标注ntc

代码打印也是ntc 1        System.out.println(LexiconUtility.getAttribute("北京拉手网络技术有限公司"));

但是在一个简历文本里面做了分词， 虽然识别出了这个实体，但是词性变成了nt。。
 
"工作描述：\t工作职责\n" +
                "负责拉手网后台系统产品（PC端和无线端）,包括：待办事项、任务管理、供应商管理、合同管理、团购单管理、变更与特批、客服中心、数据中心\n" +

**Comment by hankcs** [comment]
请给一段触发代码复现问题

**Comment by weisong82** [comment]
System.out.println("hanlp="+extraCompany(HanLP.segment(content)));

        System.out.println(LexiconUtility.getAttribute("北京拉手网络技术有限公司"));

        String test =                 "公司：北京拉手网络技术有限公司\n" +
                "职位：高级产品经理\n" +
                "开始日期：2013-08；结束日期：2049-12\n" +
                "工作内容：\n" ;

        final List<Term> segment = HanLP.segment(test);
        for (Term t: segment
             ) {
            System.out.println(t.word+t.nature+t.getFrequency());
        }


ntc 1 
公司nis15771
：w1
北京拉手网络技术有限公司nt1

w0
职位n778
：w1
高级a1337
产品n6727
经理nnt956

**Comment by hankcs** [comment]
问题应该解决了。
