### ISSUE TITLE
词典分割符（空格）对于英文实体的问题

### ISSUE THREAD

**Issue by hanwei2008** [hankcs/HanLP#404]
例如organization.txt的第一条数据
Valor Capital Group	nhy	1
英文实体内存在空格，从而导致词典读取错误
建议修改方式:
１、（强烈推荐）解析词典方式：取倒数第一个为词频、倒数第二个为词性、其它为词
２、将词的分隔符设置为零宽字符等几乎不可能在实际文本中出现的词

**Comment by hankcs** [comment]
感谢建议
1. 这个问题已经有些讨论了，因为忙，一直没有做改进。暂时的方法是通过CustomDictionary动态加入。
2. 你推荐的方式没有考虑到多个词性的问题
3. 空格实在太方便了，其他字符不是那么方便输入
3. 我的想法是同时支持\t和空格两种分隔符，若某行含有\t则用\t分割，否则用空格分割

比如
MacBook Pro 2016[制表符]词性A[制表符]1000[制表符]词性B[制表符]200

如无补充，下一版应该会加入。

**Comment by yesseecity** [comment]
用這個記號來當分隔符`;` 你們覺得如何？

**Comment by hankcs** [comment]
;宽度有点小，在文本中没有其他符号醒目

**Comment by driventokill** [comment]
刚才没有看到这个计划，是否可以考虑用标准的 csv 来提供支持？也不用在配置文件上引入太多东西。用 \t 有一个问题就是在没有词性标注的行还是会存在被错误的按照空格分割的问题。csv 很多编辑器是可以智能的展示成表格的形式的，就不怕逗号宽度太小导致看起来不醒目了。我提交了一个 PR：
https://github.com/hankcs/HanLP/pull/463

**Comment by hankcs** [comment]
@driventokill 这是个好主意，可以替代掉我提的那些复杂的分隔符规则，已经merge。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
