### ISSUE TITLE
demo演示结果和实际运行结果不同

### ISSUE THREAD

**Issue by alexanderwh** [hankcs/HanLP#409]
demo某段结果为：
[欢迎/v, 新/a, 老/a, 师生/n, 前来/vi, 就餐/vi]
[工信处/nt, 女干事/n, 每月/r, 经过/p, 下属/v, 科室/n, 都/d, 要/v, 亲口/d, 交代/v, 24/m, 口/n, 交换机/n, 等/udeng, 技术性/n, 器件/n, 的/ude1, 安装/v, 工作/vn]
[随着/p, 页游/nz, 兴起/v, 到/v, 现在/t, 的/ude1, 页游/nz, 繁盛/a, ，/w, 依赖于/v, 存档/vi, 进行/vn, 逻辑/n, 判断/v, 的/ude1, 设计/vn, 减少/v, 了/ule, ，/w, 但/c, 这/rzv, 块/q, 也/d, 不能/v, 完全/ad, 忽略/v, 掉/v, 。/w]
[中国科学院计算技术研究所/nt, 的/ude1, 宗成庆/nr, 教授/nnt, 正在/d, 教授/v, 自然语言处理/nz, 课程/n]
实际运行结果为：
[欢迎/v, 新/a, 老师/n, 生前/t, 来/v, 就餐/v]
[工信处/n, 女/b, 干事/n, 每月/r, 经过/p, 下属/v, 科室/n, 都要/nr, 亲口/d, 交代/v, 24/m, 口/q, 交换机/n, 等/u, 技术性/n, 器件/n, 的/uj, 安装/v, 工作/vn]
[随着/p, 页/q, 游兴/n, 起/v, 到/v, 现在/t, 的/uj, 页游/nz, 繁盛/an, ，/w, 依赖于/v, 存档/vn, 进行/v, 逻辑/n, 判断/v, 的/uj, 设计/vn, 减少/v, 了/ul, ，/w, 但/c, 这块/r, 也/d, 不能/v, 完全/ad, 忽略/v, 掉/v, 。/w]
[中国科学院/n, 计算/v, 技术/n, 研究所/n, 的/uj, 宗成庆/nr, 教授/n, 正在/d, 教授/n, 自然/d, 语言/n, 处理/v, 课程/n]

**Comment by hankcs** [comment]
我不太明白你的意思，用一段代码说明问题如何？

**Comment by AlexanderWu95** [comment]
@hankcs 发现是我一开始用的portable版导致demo结果与实际结果不一致，但是从旧词典改用默认词典后bakeoff-2005语料的准确率和召回率反而下降了不少，这是什么原因？

**Comment by hankcs** [comment]
1. 非portable训练自人民日报2014，与bakeoff-2005分词标准不同
1. portable训练自98人民日报，可能与bakeoff-2005有少量相似之处
1. 用A语料训练的模型在B语料上测准确率和召回率没有意义

**Comment by NicolJiang** [comment]
时间推移到 2019 年，DEMO 的表现似乎退步了：
http://hanlp.com/?sentence=%E6%AC%A2%E8%BF%8E%E6%96%B0%E8%80%81%E5%B8%88%E7%94%9F%E5%89%8D%E5%8E%BB%E4%BD%93%E9%AA%8C

欢迎新老师生前来参观 -> 欢迎 新 老师生 前来 参观
欢迎新老师生前来学习 -> 欢迎 新 老师 生前 来 学习
欢迎新老师生前去体验 -> 欢迎 新 老师 生前 去 体验

**Comment by hankcs** [comment]
> 时间推移到 2019 年，DEMO 的表现似乎退步了：
> http://hanlp.com/?sentence=%E6%AC%A2%E8%BF%8E%E6%96%B0%E8%80%81%E5%B8%88%E7%94%9F%E5%89%8D%E5%8E%BB%E4%BD%93%E9%AA%8C
> 
> 欢迎新老师生前来参观 -> 欢迎 新 老师生 前来 参观
> 欢迎新老师生前来学习 -> 欢迎 新 老师 生前 来 学习
> 欢迎新老师生前去体验 -> 欢迎 新 老师 生前 去 体验

在线演示采用的是感知机算法，处理不好这个个例很正常。如果你使用ViterbiSegment，得到的结果是一致的。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
