### ISSUE TITLE
某个句子分词有误

### ISSUE THREAD

**Issue by Aaha0625** [hankcs/HanLP#411]
测试了句子：对敌人很有用  和 对敌方很有用。
前者分词错误，后者正确。
前者被分成了  “对敌  人  很 有用”；后者分成了 “对  敌方 很  有用”  

另：“有用”为自定义词典添加的，用的CoreNatureDictionary.mini.txt，请问下哪里有 非mini版本的词库下载？

感谢作者。

**Comment by yesseecity** [comment]
詞庫在這邊
https://github.com/hankcs/HanLP/releases

对敌 是vn沒錯，比較常見的地方是軍隊用語
用CRFSegment 去分顯示正常

**Comment by hankcs** [comment]
善用搜索：https://github.com/hankcs/HanLP/issues/393
