### ISSUE TITLE
NShortSegment分词 java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by lytk01** [hankcs/HanLP#417]
代码如下：
`NShortSegment segment=new NShortSegment().enableAllNamedEntityRecognize(true).enablePlaceRecognize(true);
						List<Term> terms=segment.seg(text);`

总是分到这段话时出来内存错误：
“第一部分马克思主义哲学原理　　复习总思路……………………………………………………………………1　　第一章马克思主义哲学是科学的世界观和方法论………………………3　　第二章世界的物质性和人的实践活动……………………………………15　　第三章世界的联系、发展及其规律………………………………………30　　第四章认识的本质和过程…………………………………………………51　　第五章人类社会的本质和基本结构………………………………………76　　第六章社会发展规律和历史创造者………………………………………97　　第七章社会发展和人的发展………………………………………………112　　第二部分马克思主义政治经济学原理　　复习总思路……………………………………………………………………125　　第一章导论…………………………………………………………………128　　第二章社会经济制度与经济运行的一般原理……………………………134　　第三章资本主义生产关系的实质及其发展阶段…………………………152　　第四章资本的运行…………………………………………………………183　　第五章社会主义生产关系的实质与经济制度……………………………199　　第六章社会主义市场经济体制和经济运行………………………………211　　第七章经济全球化与国际经济关系………………………………………224　　第三部分毛泽东思想概论　　复习总思路…………………………………………………………………231　　第一章毛泽东思想是马克思主义中国化的理论成果……………………234　　第二章新民主主义革命的总路线和基本纲领……………………………241　　第三章新民主主义革命的基本问题………………………………………259　　第四章社会主义改造的理论原则与经验总结……………………………276　　第五章社会主义若干重大理论问题的探索成果…………………………285　　第六章社会主义建设的方针政策…………………………………………296　　第七章掌握毛泽东思想的活的灵魂，坚持和发展毛泽东思想…………310　　第四部分邓小平理论和“三个代表”重要思想概论　　复习总思路…………………………………………………………………323　　第一章邓小平理论是当代中国的马克思主义……………………………327　　第二章“三个代表”重要思想是马克思主义中国化的最新理论成果…332　　第三章解放思想、实事求是、与时俱进…………………………………341　　第四章社会主义的本质和根本任务………………………………………348　　第五章社会主义初级阶段和党的基本路线、基本纲领…………………355　　第六章科学发展观和社会主义建设的发展战略…………………………364　　第七章中国特色社会主义经济……………………………………………389　　第八章中国特色社会主义政治……………………………………………402　　第九章中国特色社会主义文化……………………………………………415　　第十章“一国两制”和实现祖国的完全统一……………………………424　　第十一章维护世界和平，促进共同发展…………………………………430　　第十二章中国特色社会主义事业的依靠力量和领导核心………………437　　第五部分当代世界经济与政治　　复习总思路…………………………………………………………………446　　第一章当代世界经济的发展变化与基本趋势……………………………449　　第二章当代世界政治的发展变化与基本趋势……………………………462　　第三章当今时代主题与建立国际新秩序…………………………………479　　第四章战后发达资本主义国家的经济与政治……………………………487　　第五章战后发展中国家的政治与经济……………………………………502　　第六章战后社会主义国家的经济与政治…………………………………210　　第七章独联体成员国与冷战后东欧国家的经济与政治…………………518　　第八章中国对外关系及在世界上的地位与作用…………………………526更多信息请访问：新浪考研频道考研论坛考研博客圈　　特别说明：由于各方面情况的不断调整与变化，新浪网所提供的所有考试信息仅供参考，敬请考生以权威部门公布的正式信息为准。”

**Comment by yesseecity** [comment]
你 JAVA 所給的 Memory 不夠用
試試搜尋這個： -Xms1g,  -Xmx1g + 你所用的開發軟件/環境

**Comment by lytk01** [comment]
应该不是我给的内存不够，我试过-Xms1g, -Xmx1g ，单独这一段话，也是会出现java.lang.OutOfMemoryError: GC overhead limit exceeded错误的

**Comment by yesseecity** [comment]
有試過給更多的  memory ?

**Comment by lytk01** [comment]
没有，但我用别分词方法分这段话就没事，只有用NShortSegment分词方法分词，分上边那段话时，会报这样的错误：
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at com.hankcs.hanlp.seg.NShort.Path.NShortPath.getPaths(NShortPath.java:206)
	at com.hankcs.hanlp.seg.NShort.Path.NShortPath.getNPaths(NShortPath.java:269)
	at com.hankcs.hanlp.seg.NShort.NShortSegment.BiSegment(NShortSegment.java:165)
	at com.hankcs.hanlp.seg.NShort.NShortSegment.segSentence(NShortSegment.java:58)
	at com.hankcs.hanlp.seg.Segment.seg(Segment.java:558)
	at com.jry.tools.TestMain.main(TestMain.java:14)

**Comment by hankcs** [comment]
这是因为NShortSegment的算法复杂度很高。你应该逐行处理，避免内存峰值过高。

```
        Segment segment = new NShortSegment().enableAllNamedEntityRecognize(true).enablePlaceRecognize(true);
        String text = "第一部分马克思主义哲学原理　　复习总思路……………………………………………………………………1　　第一章马克思主义哲学是科学的世界观和方法论………………………3　　第二章世界的物质性和人的实践活动……………………………………15　　第三章世界的联系、发展及其规律………………………………………30　　第四章认识的本质和过程…………………………………………………51　　第五章人类社会的本质和基本结构………………………………………76　　第六章社会发展规律和历史创造者………………………………………97　　第七章社会发展和人的发展………………………………………………112　　第二部分马克思主义政治经济学原理　　复习总思路……………………………………………………………………125　　第一章导论…………………………………………………………………128　　第二章社会经济制度与经济运行的一般原理……………………………134　　第三章资本主义生产关系的实质及其发展阶段…………………………152　　第四章资本的运行…………………………………………………………183　　第五章社会主义生产关系的实质与经济制度……………………………199　　第六章社会主义市场经济体制和经济运行………………………………211　　第七章经济全球化与国际经济关系………………………………………224　　第三部分毛泽东思想概论　　复习总思路…………………………………………………………………231　　第一章毛泽东思想是马克思主义中国化的理论成果……………………234　　第二章新民主主义革命的总路线和基本纲领……………………………241　　第三章新民主主义革命的基本问题………………………………………259　　第四章社会主义改造的理论原则与经验总结……………………………276　　第五章社会主义若干重大理论问题的探索成果…………………………285　　第六章社会主义建设的方针政策…………………………………………296　　第七章掌握毛泽东思想的活的灵魂，坚持和发展毛泽东思想…………310　　第四部分邓小平理论和“三个代表”重要思想概论　　复习总思路…………………………………………………………………323　　第一章邓小平理论是当代中国的马克思主义……………………………327　　第二章“三个代表”重要思想是马克思主义中国化的最新理论成果…332　　第三章解放思想、实事求是、与时俱进…………………………………341　　第四章社会主义的本质和根本任务………………………………………348　　第五章社会主义初级阶段和党的基本路线、基本纲领…………………355　　第六章科学发展观和社会主义建设的发展战略…………………………364　　第七章中国特色社会主义经济……………………………………………389　　第八章中国特色社会主义政治……………………………………………402　　第九章中国特色社会主义文化……………………………………………415　　第十章“一国两制”和实现祖国的完全统一……………………………424　　第十一章维护世界和平，促进共同发展…………………………………430　　第十二章中国特色社会主义事业的依靠力量和领导核心………………437　　第五部分当代世界经济与政治　　复习总思路…………………………………………………………………446　　第一章当代世界经济的发展变化与基本趋势……………………………449　　第二章当代世界政治的发展变化与基本趋势……………………………462　　第三章当今时代主题与建立国际新秩序…………………………………479　　第四章战后发达资本主义国家的经济与政治……………………………487　　第五章战后发展中国家的政治与经济……………………………………502　　第六章战后社会主义国家的经济与政治…………………………………210　　第七章独联体成员国与冷战后东欧国家的经济与政治…………………518　　第八章中国对外关系及在世界上的地位与作用…………………………526更多信息请访问：新浪考研频道考研论坛考研博客圈　　特别说明：由于各方面情况的不断调整与变化，新浪网所提供的所有考试信息仅供参考，敬请考生以权威部门公布的正式信息为准。";
        for (String sentence : SentencesUtil.toSentenceList(text))
        {
            System.out.println(segment.seg(sentence));
        }
```


[第/m, 一部分/mq, 马克思主义/n, 哲学原理/nz, 　　/w, 复习/vn, 总/b, 思路/n, ……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[1/m, 　　/w, 第一/m, 章/q, 马克思主义/n, 哲学/n, 是/vshi, 科学/n, 的/ude1, 世界观/n, 和/cc, 方法论/n, ……/w]
[……/w]
[……/w]
[……/w]
[…/w, 3/m, 　　/w, 第二/m, 章/q, 世界/n, 的/ude1, 物质性/nz, 和/cc, 人/n, 的/ude1, 实践/vn, 活动/vn, ……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[15/m, 　　/w, 第三/m, 章世界/nr, 的/ude1, 联系/v, 、/w, 发展/vn, 及其/cc, 规律/n, ……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[…/w, 30/m, 　　/w, 第四/m, 章/q, 认识/v, 的/ude1, 本质/n, 和/cc, 过程/n, ……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[…/w, 51/m, 　　/w, 第五/m, 章人类/nr, 社会/n, 的/ude1, 本质/n, 和/cc, 基本/a, 结构/n, ……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[…/w, 76/m, 　　/w, 第六/m, 章社会/nr, 发展/vn, 规律/n, 和/cc, 历史/n, 创造者/n, ……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[…/w, 97/m, 　　/w, 第七/m, 章/q, 社会发展/v, 和/cc, 人/n, 的/ude1, 发展/vn, ……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[112/m, 　　/w, 第二/m, 部分/n, 马克思主义/n, 政治经济学/n, 原理/n, 　　/w, 复习/vn, 总/b, 思路/n, ……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[125/m, 　　/w, 第一/m, 章/q, 导论/n, ……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[…/w, 128/m, 　　/w, 第二/m, 章社会/nr, 经济制度/nz, 与/cc, 经济运行/nz, 的/ude1, 一般/ad, 原理/n, ……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[…/w, 134/m, 　　/w, 第三/m, 章/q, 资本主义/n, 生产关系/n, 的/ude1, 实质/n, 及其/cc, 发展/vn, 阶段/n, ……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[152/m, 　　/w, 第四/m, 章/q, 资本/n, 的/ude1, 运行/vn, ……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[183/m, 　　/w, 第五/m, 章/q, 社会主义/n, 生产关系/n, 的/ude1, 实质/n, 与/cc, 经济制度/nz, ……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[…/w, 199/m, 　　/w, 第六/m, 章/q, 社会主义/n, 市场经济/n, 体制/n, 和/cc, 经济运行/nz, ……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[211/m, 　　/w, 第七/m, 章/q, 经济/n, 全球化/vn, 与/cc, 国际/n, 经济/n, 关系/n, ……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[…/w, 224/m, 　　/w, 第三/m, 部分/n, 毛泽东思想/n, 概论/n, 　　/w, 复习/vn, 总/b, 思路/n, ……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[…/w, 231/m, 　　/w, 第一/m, 章/q, 毛泽东思想/n, 是/vshi, 马克思主义/n, 中国/ns, 化/v, 的/ude1, 理论/n, 成果/n, ……/w]
[……/w]
[……/w]
[……/w]
[234/m, 　　/w, 第二/m, 章/q, 新民主主义革命/n, 的/ude1, 总路线/n, 和/cc, 基本纲领/nz, ……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[…/w, 241/m, 　　/w, 第三/m, 章/q, 新民主主义革命/n, 的/ude1, 基本/a, 问题/n, ……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[…/w, 259/m, 　　/w, 第四/m, 章/q, 社会主义/n, 改造/vn, 的/ude1, 理论/n, 原则/n, 与/cc, 经验总结/nz, ……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[…/w, 276/m, 　　/w, 第五/m, 章/q, 社会主义/n, 若干/m, 重大/a, 理论/n, 问题/n, 的/ude1, 探索/v, 成果/n, ……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[285/m, 　　/w, 第六/m, 章/q, 社会主义/n, 建设/vn, 的/ude1, 方针政策/nz, ……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[296/m, 　　/w, 第七/m, 章/q, 掌握/v, 毛泽东思想/n, 的/ude1, 活/v, 的/ude1, 灵魂/n, ，/w]
[坚持/v, 和/cc, 发展/vn, 毛泽东思想/n, ……/w]
[……/w]
[310/m, 　　/w, 第四/m, 部分/n, 邓小平理论/n, 和/cc, “/w, 三个代表/nz, ”/w, 重要/a, 思想/n, 概论/n, 　　/w, 复习/vn, 总/b, 思路/n, ……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[…/w, 323/m, 　　/w, 第一/m, 章/q, 邓小平理论/n, 是/vshi, 当代/t, 中国/ns, 的/ude1, 马克思主义/n, ……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[…/w, 327/m, 　　/w, 第二/m, 章/q, “/w, 三个代表/nz, ”/w, 重要/a, 思想/n, 是/vshi, 马克思主义/n, 中国/ns, 化/v, 的/ude1, 最新/a, 理论/n, 成果/n, …/w, 332/m, 　　/w, 第三/m, 章/q, 解放思想/vl, 、/w, 实事求是/vl, 、/w, 与时俱进/nz, ……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[…/w, 341/m, 　　/w, 第四/m, 章/q, 社会主义/n, 的/ude1, 本质/n, 和/cc, 根本任务/n, ……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[…/w, 348/m, 　　/w, 第五/m, 章/q, 社会主义/n, 初级阶段/nz, 和/cc, 党的基本/l, 路线/n, 、/w, 基本纲领/nz, ……/w]
[……/w]
[……/w]
[…/w, 355/m, 　　/w, 第六/m, 章/q, 科学发展观/nz, 和/cc, 社会主义/n, 建设/vn, 的/ude1, 发展/vn, 战略/n, ……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[364/m, 　　/w, 第七/m, 章/q, 中国/ns, 特色/n, 社会主义/n, 经济/n, ……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[…/w, 389/m, 　　/w, 第八/m, 章/q, 中国/ns, 特色/n, 社会主义/n, 政治/n, ……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[…/w, 402/m, 　　/w, 第九/m, 章/q, 中国/ns, 特色/n, 社会主义/n, 文化/n, ……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[…/w, 415/m, 　　/w, 第十/m, 章/q, “/w, 一国两制/n, ”/w, 和/cc, 实现/v, 祖国/n, 的/ude1, 完全/ad, 统一/vn, ……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[…/w, 424/m, 　　/w, 第十一/m, 章/q, 维护/v, 世界/n, 和平/n, ，/w]
[促进/v, 共同/d, 发展/vn, ……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[…/w, 430/m, 　　/w, 第十二/m, 章/q, 中国/ns, 特色/n, 社会主义/n, 事业/n, 的/ude1, 依靠/v, 力量/n, 和/cc, 领导核心/nz, ……/w]
[……/w]
[……/w]
[437/m, 　　/w, 第五/m, 部分/n, 当代世界/nz, 经济/n, 与/cc, 政治/n, 　　/w, 复习/vn, 总/b, 思路/n, ……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[…/w, 446/m, 　　/w, 第一/m, 章/q, 当代世界/nz, 经济/n, 的/ude1, 发展/vn, 变化/vn, 与/cc, 基本/a, 趋势/n, ……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[…/w, 449/m, 　　/w, 第二/m, 章/q, 当代世界/nz, 政治/n, 的/ude1, 发展/vn, 变化/vn, 与/cc, 基本/a, 趋势/n, ……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[…/w, 462/m, 　　/w, 第三/m, 章/q, 当今/t, 时代/n, 主题/n, 与/cc, 建立/v, 国际/n, 新秩序/nz, ……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[…/w, 479/m, 　　/w, 第四/m, 章/q, 战后/t, 发达/a, 资本主义/n, 国家/n, 的/ude1, 经济/n, 与/cc, 政治/n, ……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[…/w, 487/m, 　　/w, 第五/m, 章/q, 战后/t, 发展中国家/n, 的/ude1, 政治/n, 与/cc, 经济/n, ……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[502/m, 　　/w, 第六/m, 章/q, 战后/t, 社会主义/n, 国家/n, 的/ude1, 经济/n, 与/cc, 政治/n, ……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[…/w, 210/m, 　　/w, 第七/m, 章/q, 独联体/j, 成员国/n, 与/cc, 冷战/n, 后/f, 东欧国家/nz, 的/ude1, 经济/n, 与/cc, 政治/n, ……/w]
[……/w]
[……/w]
[…/w, 518/m, 　　/w, 第八/m, 章/q, 中国/ns, 对外/vn, 关系/n, 及/cc, 在世界上/l, 的/ude1, 地位/n, 与/cc, 作用/n, ……/w]
[……/w]
[……/w]
[……/w]
[……/w]
[526/m, 更多/ad, 信息/n, 请/v, 访问/vn, ：/w, 新浪/ntc, 考研/vi, 频道/n, 考研/vi, 论坛/n, 考研/vi, 博客/n, 圈/qv, 　　/w, 特别/d, 说明/v, ：/w, 由于/p, 各/rz, 方面/n, 情况/n, 的/ude1, 不断/d, 调整/vn, 与/cc, 变化/vn, ，/w]
[新浪网所/nt, 提供/v, 的/ude1, 所有/b, 考试/vn, 信息/n, 仅供参考/l, ，/w]
[敬请/v, 考生/n, 以/p, 权威部门/n, 公布/v, 的/ude1, 正式/ad, 信息/n, 为准/v, 。/w]

**Comment by DusonWang** [comment]
NShortSegment 可以封装一个函数，内部根据换行符号，每行分词

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
