### ISSUE TITLE
能否提供SOLR5.X的支持

### ISSUE THREAD

**Issue by cmdares** [hankcs/HanLP#42]
您可以参考IK分词器的SOLR分词源码（这个版本是支持solr5的修订版）
https://github.com/EugenePig/ik-analyzer-solr5

**Comment by hankcs** [comment]
1. 没问题，这个正在做，不过最近有点忙，无法保证很快做出来。
2. solr是Lucene的子项目，其实HanLP提供了Lucene插件，如果你（或者任何人）有兴趣的话，欢迎参与移植。

**Comment by hankcs** [comment]
https://github.com/hankcs/hanlp-solr-plugin

欢迎参与改进。

**Comment by hankcs** [comment]
https://github.com/hankcs/hanlp-solr-plugin

欢迎参与改进。
