### ISSUE TITLE
关于Project打包的问题

### ISSUE THREAD

**Issue by Bahramudin** [hankcs/HanLP#421]
我在项目里用了你的jia包（maven方式和直接下载jar的方式）我在IDE里运行都没问题，我是用Swing框架做了个图形化工具，然后打包完之后一旦运行就出问题，问题信息是：

> Error: A JNI error has occurred, please check your installation and try again
> Exception in thread "main" java.lang.SecurityException: Invalid signature file d
> igest for Manifest main attributes
>         at sun.security.util.SignatureFileVerifier.processImpl(Unknown Source)
>         at sun.security.util.SignatureFileVerifier.process(Unknown Source)
>         at java.util.jar.JarVerifier.processEntry(Unknown Source)
>         at java.util.jar.JarVerifier.update(Unknown Source)
>         at java.util.jar.JarFile.initializeVerifier(Unknown Source)
>         at java.util.jar.JarFile.getInputStream(Unknown Source)
>         at sun.misc.URLClassPath$JarLoader$2.getInputStream(Unknown Source)
>         at sun.misc.Resource.cachedInputStream(Unknown Source)
>         at sun.misc.Resource.getByteBuffer(Unknown Source)
>         at java.net.URLClassLoader.defineClass(Unknown Source)
>         at java.net.URLClassLoader.access$100(Unknown Source)
>         at java.net.URLClassLoader$1.run(Unknown Source)
>         at java.net.URLClassLoader$1.run(Unknown Source)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at java.net.URLClassLoader.findClass(Unknown Source)
>         at java.lang.ClassLoader.loadClass(Unknown Source)
>         at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
>         at java.lang.ClassLoader.loadClass(Unknown Source)
>         at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

我在网上查了很多种方法 都没办法，就是很多人说了在maven文件里加这些：

```

> <artifact>*:*</artifact>
> <excludes>
>         <exclude>META-INF/*.SF</exclude>
>          <exclude>META-INF/*.DSA</exclude>
>           <exclude>META-INF/*.RSA</exclude>
> </excludes>
```

可是无论怎么样都不行。请问这是什么问题，等待回复。。。

**Comment by hankcs** [comment]
从错误信息来看跟jar包没有关系
Error: A JNI error has occurred, please check your installation and try again
看样子是Java Native Interface，也就是本地C代码有问题。应该有个什么库用了JNI，然后出错了。

**Comment by Bahramudin** [comment]
我知道JNI，可是问题是当我用你的这个库的时候就出问题了，如果用别的库的话 就没事儿，肯定是和你的库有关系，当我把你的库删除了再打包运行就欧克完全能运行。我不是新手，我非常了解Java，可是这个我怎么研究了都没法解决了，所以问你来了 看看是怎么办？

**Comment by Bahramudin** [comment]
请把这问题给我看一下是怎么解决，就是跟你的库有关系，等我不用的你的库的时候就好好的
