### ISSUE TITLE
hanlp-portable 怎样通过properties 文件配置自定义词典呢。

### ISSUE THREAD

**Issue by chenruiSundun** [hankcs/HanLP#424]

**Comment by cicido** [comment]
#425

**Comment by chenruiSundun** [comment]
protable 版内置了词典的，问题是怎么去覆盖内置的此单，转为用 properties 文件去指定。

**Comment by cicido** [comment]
修改properties文件后，重新打包.
java -cvf

**Comment by cicido** [comment]
我最近把data文件打成一个jar包， hanlp.properties打成一个jar包。并增加了一个JarIOAdapter文件,在 corpus/io下。现在能完美的在spark下面跑了。跑的时候，提交这三个包就行。词典的增删操作把以前方便多了。

**Comment by chenruiSundun** [comment]
我是集成到ES 里面作为 一个插件

**Comment by cicido** [comment]
哦，我这里考虑的更方便的对词典进行增删操作

**Comment by chenruiSundun** [comment]
protable 版默认不会去读 properties 文件，

**Comment by cicido** [comment]
properties文件提定的是外部文件位置。

**Comment by cicido** [comment]
是的，都是设置好的了

**Comment by cicido** [comment]
你可以把里面的data文件夹替换掉就好了

**Comment by cicido** [comment]
再重新打个jar包，直接用jar命令打，很方便很快

**Comment by chenruiSundun** [comment]
你知道 protable 版的源码么 ，要有源码就好了

**Comment by cicido** [comment]
有吧，你切一下分支，好像就可以了

**Comment by cicido** [comment]
portable分支与master分支在这一点上似乎是一样的

**Comment by chenruiSundun** [comment]
额 ，没注意到 还有一protable 分支 ，谢谢你！

**Comment by cicido** [comment]
ok

**Comment by chenruiSundun** [comment]
我下载 了protable 分支 ，将 data 文件夹复制到resources 文件夹下，编译能成功，但是在ES 里面 run的时候 ，报错。。

**Comment by cicido** [comment]
data文件要提前跑一下，以生成相应的bin或data后缀的词典文件，另外我发现Chartype.txt这个配置有问题。由于protable是不带hanlp.properties文件，那默认的就是那些static变量配置，那CharTypePath配的是CharType.bin文件，不是CharType.txt.bin.  而1.3.2对应的data是CharType.data.yes.这个你要具体看下。

**Comment by tankle** [comment]
portable版本感觉应该要增加一个配置， 可以进一步读取自定义词典

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
