### ISSUE TITLE
你的这个包充满了bug

### ISSUE THREAD

**Issue by Bahramudin** [hankcs/HanLP#428]
要不打包不行，要不效果不好，反正没什么好说的。都烦死了用这个包了。刚刚开始了跑这个异常：
`严重: 没有找到HanLP.properties，可能会导致找不到data` 本来是好好的，突然就这样了。怎么那么多问题。。。？？

**Comment by cicido** [comment]
我觉得不错啊，多看看源代码

**Comment by hankcs** [comment]
呵呵，人品
<img width="830" alt="2017-03-19 7 38 17" src="https://cloud.githubusercontent.com/assets/5326890/24086363/4457588a-0cdc-11e7-81cb-7385456b0488.png">
