### ISSUE TITLE
那些不在CoreNatureDictionary.txt的中词会标注什么词性

### ISSUE THREAD

**Issue by cicido** [hankcs/HanLP#429]
在查看人名词典nr.txt时。采用以下方式查找在nr.txt 但不在CoreNatureDictionary.txt中的词：
awk 'NR==FNR{a[$1]}NR>NFR{if(!($1 in a))print $0}' ../CoreNatureDictionary.txt nr.txt | wc -l
结果1901个词，这部分词该如何标注词性。人名识别中，词的角度有人名前缀，姓，名，后缀，与人名无关词等。如果这1901个词不在CoreNatureDictionary.txt, 那怎么会分出这些词来呢？ 如果分出来了，词性又是如何设置的呢？

**Comment by cicido** [comment]
除了人名，地名，机构名识别会产生新的不在CoreNatureDictionary，custom目录中的词。还有其他方式可以产生不在CoreNatureDictionary,custom目录下的词么？

**Comment by cicido** [comment]
我在“现代汉语补充词库.txt”与“机构名词典.txt”中都发现了有“阿里巴巴”这个词。同时在看custom源代码加载的时候发现，在两个词典分别加载的时候，并没有进行合并，而是后面词典的词会覆盖前面词典的词:
map.put(param[0], attribute);
也就是如果新增词的时候，是不用考虑是否与词典中的词重合的情况？

**Comment by hankcs** [comment]
0. 未登录词会标注nz，在命名实体识别中会标注Z。
0. 目前是覆盖模式，纯粹从人性出发，大部分人都喜欢凌驾于系统默认值之上。

**Comment by cicido** [comment]
ok

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
