### ISSUE TITLE
人名称提取不准确

### ISSUE THREAD

**Issue by cmdares** [hankcs/HanLP#43]
1.发现Nature源码中有 
/**
     * 蒙古姓名
     */
nr2, 但是测试并没有正确标记。比如
人名称识别的例子中：
签约仪式前，秦光荣、阿布杜勒·哈尼德、阿卜杜热西提、仇和、穆拉帝力、斯琴格日乐、 娜仁高娃、乌兰托雅和宫本正太郎等一同会见了企业家阿卜杜勒·哈米德。
使用这个句子一些人名称提取错误，或标注错误。
不太理解算法，是否一定需要加入字典？

2.再比如：
                "请收回李珅300元钱",
                "请收回李绅300元钱",
                "请收回李西300元钱",
                "请收回李硒300元钱",

标记人名：李珅 李西 正确；李绅 李硒 错误。

这个人名称标记，不用模型文件吗？

**Comment by hankcs** [comment]
0. 训练语料中只含有一个蒙古人名 鳌拜	nr2	1，无法训练识别模型。
0. 一些人名的成分与常用词冲突，暂时舍弃。
0. 算法不是万能的，第一需要人工细致标注，第二需要后期规则修正。两方面成本都很高。
0. 训练语料中珅从来没有作为人名的第二个字出现过，往词典里加入绅 D 2 E 1即可
0. 模型跟词典没有绝对的区别，我将隐马模型做成人人都可以编辑的词典形式，不代表它不是模型。
