### ISSUE TITLE
CRF识别新词似乎不起效果

### ISSUE THREAD

**Issue by endymecy** [hankcs/HanLP#436]
我使用"你看过穆赫兰道吗"这句话做实验，没有得到结果。

然后我使用同样的一篇新闻做实验，在NLPIR上面可以得到新词“国际机场” ， “马移民局”等新词，但是用hanlp无法获得。

文章如下：

环球网报道 记者 王敏日前，网名为乔妹的台湾女游客通过脸谱发文表示，自己在入境马来西亚时，因护照破损，受到马来西亚海关非人道对待，她不但被没收了手机、护照等私人物品，还被关押长达35个小时。
“03/09晚上08：30我下飞机，我依照规定排队等候盖印出关，轮到我时，盖印人员他说我护照损坏，不能进去马来西亚，他要我等一下”
乔妹表示，他回来后询问她护照为何会损坏，她解释说，在日本购物免税单被日本海关撕下时造成的破损。海关人员随即将其带入办公室表示，马来西亚不接受并将护照没收。
乔妹随后被要求进入更里边的办公室，当她进入后，手机又被没收了。这时，乔妹再次被要求进入更后面的小房间里放置行李，在那里出现了一个很凶的男子。
“我把外套放在手提行李上，他就把我的外套很大力的丢向我，行李箱往上丢，还叫我把钱拿出来，我不想给他钱，假装听不懂，然后才有一个女生来，就叫我把钱放口袋”
乔妹随后手被铐起来带进了牢房，对方仅告诉她第二天早上可回台湾。“里面黑嘛嘛，有时才有开灯，厕所好脏也没有门，只能坐地上，累了睡地上，好多人”乔妹称她还遇到了另一个台湾人。
一个细节，乔妹表示，有马来西亚工作人员向其表示，只要1000马币便能先出去，但她却分明看到墙上密密麻麻的“不要给钱，都是骗钱”的字。
贴文发布后，在马来西亚，事件迅速热起，其后，台媒也相继跟进，做出了报道。马来西亚网站“辣手网”14日下午报道，马首相东亚特使兼民都鲁区国会议员张庆信认为，这件事关乎国家形象和官员素质，可能打击马来西亚旅游业。
张庆信表示，遭扣留的台湾旅客不是罪犯，不该用这么不人道的方式对待台湾旅客。因此向内政部反映。而据台“联合新闻网”报道称，马国副首相兼内政部长阿末扎希得知后大怒，已下令彻查。
台湾“外交部”得知消息后表示，已于第一时间主动掌握讯息，并经“驻处”洽系吉隆坡国际机场移民局执法组，转述贴文所述情节，了解当日相关情形。
而马来西亚则回复，该名女性于3月9日搭乘亚洲航空班机于晚间8时30分抵达吉隆坡第2国际机场，拟入境时，因所持护照毁损，被裁定拒绝入境并予以遣返，于是在3月11日上午9时20分搭乘亚洲航空第D7372号班机返回台湾桃园国际机场。
那么，马来西亚遣返的标准作业是什么呢，台“外交部”表示，根据了解，旅客经机场移民官裁定拒绝入境并予以遣返后，倘当日无法登机返回，旅客将被安置在机场之“照护室”，并尽速进行遣返。
旅客在留置期间相关情形，马移民局例不知会各相关驻马“使领馆”单位，若马移民局认为有必要将旅客移送至机场附近的“临时安置所”，予以较长时间的留置或调查时，则将同步知会。
事件同样很快便在社交网络上发酵，截止此文时，转发数达10280次。不少网友对乔妹的遭遇表示同情，但也有些网友质疑事件的真实性，甚至表示，乔妹并不是台湾人，所做只是为了炒作。
比如有网友即认为，有人因为要红而败坏，损人不利己的行为不一定高明，更何况是损害一个国家的名誉（马来西亚）。也有网民表示自己就是马来西亚人，要求出示护照。
就此，乔妹在脸谱表示，“大家一直说我想红，我想问这个很光荣吗？你们可以体会被关的心情吗？里面环境有多糟吗？”随后更是贴上护照证明自身。
乔妹的遭遇另一方面则招来了不少岛内外的共感，名叫“Kuan wei pan”的网友表示自己也有过相同的经验，并称“你永远不要让这里的人知道你的口袋有多深”。
也有不少马来西亚的网友为乔妹的遭遇感到抱歉，这位网友表示，自己作为一个马来西他人，都为这里的键盘侠感到心寒，这样的事情发生在谁的身上，都会崩溃的。
当然也有网友看的更多些，比如这位地址显示为台北的网友这样说，如果持有的是中华人民共和国的护照，被处理的过程就会不一样。

**Comment by yesseecity** [comment]
那就加入自訂詞典吧

**Comment by hankcs** [comment]
[我, 使用, ", 你, 看过, 穆赫兰道, 吗, ", 这, 句话, 做, 实验, ，, 没有, 得到, 结果, 。, 

, 然后, 我, 使用, 同样, 的, 一篇, 新闻, 做, 实验, ，, 在, NLPIR, 上面, 可以, 得到, 新词, “, 国际, 机场, ”,  , ，,  , “马, 移民局, ”, 等, 新词, ，, 但是, 用, hanlp, 无法, 获得, 。]
分词标准不同，没有谁规定什么叫词、“你好”是一个词还是两个词。特别是训练语料中某某机场就是两个词的时候，结果当然是两个词了。

**Comment by endymecy** [comment]
你这是避重就轻了，对于你的分词器而言，“马移民局”是不是一个新词，如果是，那就是没有识别出来。哪来那么多的理由。
