### ISSUE TITLE
王国强、高峰、汪洋、张朝阳光着头、韩寒、小四 ，这里面“张朝阳”这个人名分错了

### ISSUE THREAD

**Issue by cicido** [hankcs/HanLP#439]
我在自定义词典中加入“张朝阳”这个人名，设定
张朝阳 nr 10000
照样分错
debug看了一下粗分网，里面没有"阳"字：
粗分结果[王国强/nr, 、/w, 高峰/n, 、/w, 汪洋/n, 、/w, 张/q, 朝/tg, 阳光/n, 着/uzhe, 头/n, 、/w, 韩寒/nr, 、/w, 小/a, 四/m]

我应该怎么做，才能把这个人名分对呢？

**Comment by cicido** [comment]
将这个人名加到核心词典就可以分正确了。
难道在粗分时没有用到用户自定义词典？

**Comment by hankcs** [comment]
是的，没有。
以统计分词为主，不想做词典分词。

**Comment by cicido** [comment]
这样的话，对一些需要强制分对的词只有加入核心词典了。感觉某些特定标识的词是可以起到类似标点符号的分隔作用。

**Comment by cicido** [comment]
可以配置为在粗分时也利用自定义词典进行词匹配么？

**Comment by cicido** [comment]
自定义词典在哪起作用呢?

**Comment by potenlife** [comment]
@cicido 我好想也遇到跟你类似的问题，例如“埃森哲”我想把它定义为“nt”类型，但是用默认分词打印出来的是：“nrf” 然后用 enableOrganizationRecognize(true) 后变成“埃森/ns, 哲/ng”分开了。

**Comment by hankcs** [comment]
自定义词典只起合并作用，参考https://github.com/hankcs/HanLP/issues/303

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
