### ISSUE TITLE
句法分析的逻辑建议

### ISSUE THREAD

**Issue by cmdares** [hankcs/HanLP#44]
比如针对专有名词/机构的标记逻辑
我经常在全聚汇吃饭
[我/rr, 经常/d, 在/p, 全聚/nr, 汇/v, 吃饭/vi, ，/w]

 "我经常在大铜锅吃饭，",
[我/rr, 经常/d, 在/p, 大/a, 铜/n, 锅/n, 吃饭/vi, ，/w]

"我经常在大铜锅海鲜楼吃饭，"
[我/rr, 经常/d, 在/p, 大/a, 铜/n, 锅/n, 海鲜/nf, 楼/n, 吃饭/vi, ，/w]

出现的位置最近的 介词【】动词之间且至少有一个名词出现，能否将这些词形成专有名词

**Comment by hankcs** [comment]
我在一个人看书？我在拼命写代码？
汉语不是那么简单的东西。
