### ISSUE TITLE
一些实体识别不准确的情况

### ISSUE THREAD

**Issue by huoshaochang** [hankcs/HanLP#440]
机构名前后的一些介词处理的不好，如：
南京的东南大学以前叫南京工学院
[南京/ns, 的东南大学/nt, 以前/f, 叫/vi, 南京工学院/nt]

在\data\dictionary\person\nr.txt中加了黄鹤楼 A 1还是没用
湖北最出名的烟是黄鹤楼
[湖北/ns, 最/d, 出名/a, 的/ude1, 烟/n, 是/vshi, 黄鹤楼/nr]

1998年3月1号是我的生日
[1998/m, 年/qt, 3/m, 月1号/nt, 是/vshi, 我/rr, 的/ude1, 生日/n]

**Comment by hankcs** [comment]
感谢反馈，你可能在用旧版本的data。版本库中最新的已经没有这种问题了。另外还可以参考https://github.com/hankcs/HanLP/issues/407。
        Segment segment = new DijkstraSegment().enableAllNamedEntityRecognize(true);
        System.out.println(segment.seg(
                "南京的东南大学以前叫南京工学院 1998年3月1号是我的生日"
        ));

[南京/ns, 的/ude1, 东南大学/ntu, 以前/f, 叫/vi, 南京工学院/nt,  /w, 1998/m, 年/qt, 3/m, 月1号/nt, 是/vshi, 我/rr, 的/ude1, 生日/n]

**Comment by hankcs** [comment]
这个“号”的问题也可以解决，当初语料质量的问题。有空可以把所有带D标签的词语校对一遍。

**Comment by TylunasLi** [comment]
建议机构名这一块拿更准确的预料训练。
研究了一下所谓的人民日报2014语料，机构名貌似是机器识别出来未经过校对的，在这个基础上做的话确实赚却率比较低。可以考虑仅仅用人民日报1998年语料训练机构名称识别？

**Comment by hankcs** [comment]
当时我手上只有所谓的“98半年人民日报”，看上去也像是某个分词器的输出，而不是人工校对的。如果 @TylunasLi 有高质量的98人民日报的话，我们可以一起训练个新模型，谢谢。

**Comment by wangpeng138375** [comment]
为什么nr.tr.txt 中没有Y（姓与单名成词）标签？nr.txt中也没有这个标签？

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
