### ISSUE TITLE
姓氏总结，感觉没有全，应该是训练语料少引起的

### ISSUE THREAD

**Issue by cicido** [hankcs/HanLP#442]

**Comment by cicido** [comment]
在nr.txt查找tag为B的行：
awk -v qu='"' 'index($0," B ")!=0{a=a qu $1 qu","}END{print a}' nr.txt
"丁","万","丑","世","丘","丛","东","严","丰","丹","么","义","乌","乐","乔","乙","习","乾","于","云","亓","井","亢","京","仁","仇","仉","付","仝","代","令","仪","仰","仲","仵","任","伊","伍","伏","伟","伦","伯","何","佘","余","佟","侍","依","侯","保","俞","修","候","倪","傅","储","元","兆","党","全","公","兰","关","兴","冀","冉","冒","农","冠","冯","冰","况","冷","冼","凌","凤","刀","刁","刑","刘","刚","初","利","劉","力","励","劳","勾","包","匡","区","华","卓","单","南","卜","卞","占","卢","卫","印","危","卿","历","厉","厚","原","友","双","古","台","史","叶","吉","向","吕","启","吳","吴","呂","员","周","呼","咸","唐","商","喻","嘉","回","国","圣","堵","墨","夏","奕","奚","姚","姜","姬","威","娄","娟","婁","孔","孙","孝","孟","季","学","孫","宁","宇","安","宋","完","宓","宗","官","定","宛","宜","宝","宣","宦","宫","宮","容","宾","宿","寇","寒","寸","寿","封","尉","少","尔","尚","尤","尧","尹","居","屈","展","屠","山","岑","岳","崇","崔","嵇","巢","左","巩","巫","巴","布","帅","师","帥","席","常","平","年","幸","广","庄","庐","应","庚","庞","康","庹","庾","廉","廖","延","弘","张","弥","張","强","归","彭","徐","念","忻","怀","恽","惠","慈","慎","慕","戈","戎","成","战","戚","戴","房","扈","才","扬","扶","承","招","拜","揭","操","支","敏","敖","敬","文","斐","斯","方","施","时","旷","昂","昌","明","易","昝","星","晁","晋","晏","晓","普","景","智","曲","曹","曾","望","朝","木","朱","朴","权","李","杜","束","来","杨","杭","松","林","果","柏","查","柯","柳","柴","树","栗","栾","桂","桑","桓","梁","梅","梦","植","楚","楼","樊","欧","步","武","段","殷","毋","母","毕","毛","水","永","汉","汝","江","池","汤","汪","汲","沃","沈","沐","沙","泉","泰","洛","洪","浦","海","涂","淦","清","渠","温","游","湛","滑","滕","满","漆","潘","潭","濮","炎","焦","熊","燕","牛","牟","牧","狄","独","玄","玉","王","班","琼","瑞","甄","甘","田","申","畅","疏","白","皇","皮","益","盖","盘","盛","相","真","眭","睢","瞿","矫","石","碧","祁","祖","祝","禄","福","禚","禹","禾","秋","秘","秦","程","稽","穆","窦","章","童","竹","竺","符","简","管","籍","米","粟","糜","素","索","紫","綦","纪","练","绍","经","续","缪","罗","羅","羊","羽","翁","翟","翦","考","耿","聂","肇","肖","胡","胥","脱","腾","臧","舍","舒","良","艾","芦","芮","花","苍","苏","苑","苗","苟","英","茂","范","茅","茆","茹","荀","荆","荣","莫","菅","萧","萨","葛","董","蒋","蒙","蒯","蒲","蒿","蓝","蔚","蔡","蔺","薄","薛","虞","虢","蚩","衡","衣","衷","袁","袭","裔","裘","裴","褚","西","覃","解","言","訾","詹","謝","计","许","诸","诺","谈","谌","谢","谭","谷","貂","贝","贞","贡","贲","贵","费","贺","贾","赖","赛","赤","赫","赵","路","蹇","车","辛","辜","边","运","连","迟","逄","逢","逯","遇","邓","邝","邢","那","邬","邰","邱","邴","邵","邸","邹","郁","郎","郏","郑","郗","郜","郝","郦","郭","都","鄂","鄢","鄧","释","金","鐘","钟","钮","钱","铁","银","關","门","闪","闫","闭","闵","闻","闽","闾","阎","阙","阚","阮","阳","阴","阿","陆","陈","陳","陶","隆","隋","雍","雷","霍","青","靖","靳","鞠","韋","韓","韦","韩","项","须","顾","顿","颖","颜","风","饶","马","骆","高","魏","鱼","鲁","鲍","鹿","麦","麻","黄","黎","齐","龙","龚"

这里没有看到两字姓的，如“欧阳” 。如果强行加入nr.txt , 必然会引起概率的变化，有什么办法可以把这些姓氏补充进去？

**Comment by hankcs** [comment]
是的，当时拿了个人名库，可能的确不全，可以手工加进去的，相对全集手工加进去的毕竟是少量，不会有太大影响。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
