### ISSUE TITLE
关于是否可以组建QQ社群的小建议

### ISSUE THREAD

**Issue by potenlife** [hankcs/HanLP#445]
hankcs 你好，首先感谢你和你的团队以及好老板研发了HanLP并大公无私的开源。我是一个NLP的初学者（唯一的优势是java开发 经验有6年了），我通过百度找到由咱们这么一个工具，但是我有很多的疑惑，感觉没地方可以沟通，能否组织一个qq群，大家有问题可以问一些已经使用的比较熟练的高手们，然后大家都可以相互进步。也可以更好的发挥群众的力量。

**Comment by hankcs** [comment]
1. 感谢使用
1. 我觉得还是将GitHub作为唯一的交流平台最好。因为QQ、邮件等都是私密的，其他人看不到，搜索引擎也搜索不到。而大部分问题都是重复的，积累下来的旧问题可以在issue区或搜索引擎找到答案。
1. 我个人比较忙，恐怕无法参与即时交流。其他贡献者想必也是如此。另外我也不用QQ。
1. 开源不是一个人的事，是所有用户的事。如果GitHub上没有人回答问题，我估计QQ群一样没人回答问题。希望大家在提问的同时，尽量翻翻旧帖子，要么能找到已有答案，要么顺手帮助一下其他未解决的用户。不要只伸手，不给予。我们不是买家和卖家的关系，是互相帮助的关系。我也会尽量先回复多回复那些乐于助人的用户，维护良好的社区氛围，形成良性循环。
1. 过低的交流门槛其实并不好。有个别人士认为用了开源软件，那出现所有问题都是该开源软件造成的，社区就有义务帮他调试业务逻辑；特别是自然语言处理这种比较学术化的技术，有些术语或思想没有得到理解，有些人就会说，这个词就应该按我的标准我拍板这么分，你分的不一样还说是语料标准不同你就是在回避问题推卸责任等等。说实话我讨厌这种人，我希望这种交流少一点的好，交流门槛再提高一点比较好。

**Comment by potenlife** [comment]
hankcs，我表示理解和感谢。关于“出现问题是开源软件造成且社区有义务帮助”和“标准不一，就说明有问题”这两点我赞同你的观点，我想只要是经验丰富一点的使用开源软件或工具出了问题首先想到的是如何解决问题，并不应该如何去找社区的麻烦，我是做java的用的基本上都是开源的产品，这点都明白；然后关于后者我觉得首先NLP目前也没有达到众所周知的程度，很多都在摸索阶段，而且用在每种不同的场景肯定有一些不同的定义，例如用在智能聊天和文章解析，对于同样的词语可能要的结果不一样。然后其他的问题可能每个人想法不一样吧。
       关于这里面我也确实看了好多issue，有些人提问题或者描述问题，用的都是一种质问的口语和态度。我也很无法忍受，例如“xx是错的，我用xxx词语得出的结果不对，你们bug很多”，如果是我我就不会去回复这个人的问题，第一这个人没有基本的素养，第二人家没有帮助你的义务。但是你还是帮助回复了，有能力没脾气，但是我觉得这种人还需要指点和教育一下。
      最后我感觉HanLP在文档、Demo结构上做的非常不错，挺清晰的。我个人感觉如果有一个稍微完整一点的成功案例demo，对于类似我这种初学者可能帮助更大，毕竟初学者跟熟练者的经验和理解差距还是挺大的。
    thinks！
