### ISSUE TITLE
CRF分词模型 数字（m）和 英文字符（w）

### ISSUE THREAD

**Issue by tiandiweizun** [hankcs/HanLP#447]
看完您的CRF源码，有个疑惑，就是训练的时候，请问您是不是处理了一下，就是把连续的数字也换成了m进行训练，连续的英文字符换成w进行训练。

**Comment by rockyzhengwu** [comment]
我也看了下，应该是这样

**Comment by hankcs** [comment]
是的

**Comment by TylunasLi** [comment]
可以参看testCRF.java
也就是说，在解码的时候可以直接拿到字母和数字的词性。根据这点我修改了CRFSegment以输出词性。
