### ISSUE TITLE
关于如何分析句子且能够自定义的分类

### ISSUE THREAD

**Issue by potenlife** [hankcs/HanLP#451]
时间是很宝贵的，借用大家宝贵的时间帮我解一下疑惑，感激不尽。
-----------进入正题--------------
将要分析内容：B2B企业CMO的职责包括两块：一个是品牌，一个是销售线索。营销团队里边一定是有一群人是做品牌的，另一拨人做销售线索。简单说是一个部门是花钱的，另一个部门是去挣钱的，做品牌虽然不直接拿单，但能够给销售创造非常坚实的基础。
B2B企业有一个很大的优势，就是有着丰富并且明确的行业洞察，比如我们要做一个真正让世界变得更美好的机器人、自动化，得包含多少我们对这个行业的见解？但像卖碳酸饮料、卖巧克力的这些2C企业，就很难去表现这些。所以你看那些大的2B企业，都在不遗余力的去树立自己意见领袖的地位。例如西门子、IBM以及包括GE等在内。

希望通过上面是一篇文章的一部分，分析出以下结果：
1）相关企业：IBM,GE,西门子
2）相关行业：制造业
3）受众类别：2B
4）受众群体：管理人员、销售人员

个人思路：
我自己的思路是：里面出现了”IBM,GE,西门子“等词然后”西门子“又可以关联上制造业，文章中出现B2B字样，可以分析为2B，然后有CMO、营销团队可以对应上管理人员和销售人员。但是我不太明白如何将这些关联到不同的标签下。我的想法可能比较肤浅，还望指点。如果能够提供思路代码更好。

**Comment by hankcs** [comment]
感觉是个很个性化的词性标注或命名实体识别

**Comment by potenlife** [comment]
@hankcs  灰常感谢您的答复，词性标注我知道怎么弄，然后关于“命名试题识别”能否帮忙解释一下或者有没有参考思路代码。

**Comment by TylunasLi** [comment]
除了第一个“相关企业识别”，更像是一种文本分类问题。

**Comment by potenlife** [comment]
Thanks，对我的帮助很大。

**Comment by potenlife** [comment]
有没有适合入门的学习书籍。然后可以基于某个框架例如：“TensorFlow。另外我知道很多公司都是厚积薄发的例如：“百度NLP、Google”的一些产品，作为一个实施益者和使用者可能没有那些知识和投入，但是想站在巨人的肩膀上学习。

**Comment by hankcs** [comment]
估计没有现成的吧……

**Comment by potenlife** [comment]
多谢告知。
