### ISSUE TITLE
核心词典自定义词典同时出现时的词性优先级问题

### ISSUE THREAD

**Issue by rrrrronnie** [hankcs/HanLP#453]
想请教一下关于优先级的问题，按照文档的描述自定义词典的优先级是全局最高的？但是在核心词典中存在某个词时自定义词典加入其他词性并不能识别出自定义词性，识别出的词性是核心词典中定义的概率最大的（只测试了标准分词的情况，同时开启了隐马尔科夫判断词性），此时如果把核心词典的面这个词条删掉就可以识别出自定义的词性。应该不是转移矩阵和频数的问题测试过各种的词性和频数，似乎都是核心词典优先。不知道是不是程序设定本身就是这样呢，如果是的话除了删除核心词典相关条目不知道有没有什么好的处理方法。或者还是隐马的作用范围只针对核心词典？
非常感谢！

**Comment by hankcs** [comment]
现在用户词典是优先级最高的：

        String text = "教授正在教授自然语言处理课程";
        Segment segment = HanLP.newSegment();

        segment.enablePartOfSpeechTagging(true);
        System.out.println(segment.seg(text));
        CustomDictionary.insert("教授", "职位 1");
        System.out.println(segment.seg(text));

```
[教授/nnt, 正在/d, 教授/v, 自然语言处理/nz, 课程/n]
Mar 30, 2017 6:47:52 PM com.hankcs.hanlp.corpus.util.CustomNatureUtility <clinit>
警告: 已激活自定义词性功能,由于采用了反射技术,用户需对本地环境的兼容性和稳定性负责!
如果用户代码X.java中有switch(nature)语句,需要调用CustomNatureUtility.registerSwitchClass(X.class)注册X这个类
[教授/职位, 正在/d, 教授/职位, 自然语言处理/nz, 课程/n]
```

你可以用代码复现一下你的问题。

**Comment by rrrrronnie** [comment]
感谢回复，似乎是之前版本的问题 还用最新版后应该可以了

**Comment by SilenceWinter** [comment]
@hankcs 
您好，hankcs
我用1.7.4版本的，这个问题依旧存在，发现有时候还是核心词典更优先。
因为核心词典有“新日”，但是我在用户词典中加入“ST康得新”，结果还是分词错误，还是会分出“新日”。
当然如果我 enableCustomDictionaryForcing(true)，自然分词正确，但是这样又会影响到其他情况。
麻烦帮忙看看，十分感谢！

测试代码如下：
`       
 String text = "被实施其他风险警示后，ST康得新日涨跌幅限制为5%，股票于2019年1月23日开市起复牌";
        CustomDictionary.add("ST康得新","n 1000");
        Segment segment = HanLP.newSegment();
        System.out.println(segment.seg(text));
`

**Comment by hankcs** [comment]
那就在核心词典里加 康得新 nt 1 吧

**Comment by SilenceWinter** [comment]
@hankcs  谢谢hankcs

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
