### ISSUE TITLE
Python调用CRF分词

### ISSUE THREAD

**Issue by guduxingzou** [hankcs/HanLP#456]
@hankcs  
环境Python3，
参考demo后：https://github.com/hankcs/HanLP/tree/master/src/test/java/com/hankcs/demo 
CRF= JClass('com.hankcs.hanlp.seg.CRF.CRFSegment') 
#引入成功，
#但是  
CRF.seg('"威廉王子发表演说 呼吁保护野生动物\n"')
#报错：

Traceback (most recent call last):

  File "<ipython-input-41-a8007c89d333>", line 2, in <module>
    CRF.seg('"威廉王子发表演说 呼吁保护野生动物\n"')

RuntimeError: No matching overloads found. at native\common\jp_method.cpp:121
 求答复，thanks！

**Comment by guduxingzou** [comment]
CRF= JClass('com.hankcs.hanlp.seg.CRF.CRFSegment')
crf=CRF()
crf.seg('"威廉王子发表演说 呼吁保护野生动物\n"')
上面的方法依然报错，盼复，谢谢！

**Comment by hankcs** [comment]
https://github.com/yesseecity/hanLP-python/blob/master/server/hanlp-server.py

**Comment by guduxingzou** [comment]
非常感谢您的及时回复，只是这个需要docker，我本身的电脑之前尝试安装过docker，没有成功。调用crf分词只有这种办法吗，是不是用jclass这种方式无法实现？谢谢！

**Comment by hankcs** [comment]
我的意思是可以参考yesseecity的调用代码

**Comment by guduxingzou** [comment]
@hankcs  谢谢！我去研究一下！ths very much

**Comment by guduxingzou** [comment]
研究了一下，但是报错，在那边提了个issue。

from jpype import *
startJVM(getDefaultJVMPath(), "-Djava.class.path=C:\hanlp\hanlp-1.3.2.jar;C:\hanlp", "-Xms1g", "-Xmx1g") # 启动JVM，Linux需替换分号;为冒号:
CRFSegment = JClass('com.hankcs.hanlp.seg.CRF.CRFSegment')
segemntTool = CRFSegment().seg
content='你好，我好，大家好'
segemntTool(content)## #此句报错_

Traceback (most recent call last):

File "", line 7, in 
segemntTool(content)# #此句报错_

RuntimeError: Multiple overloads possible. at native\common\jp_method.cpp:109

**Comment by fuhao009** [comment]
我也是一样

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
