### ISSUE TITLE
你好，DoubleArrayTrie并没有看到有添加或删除某个字词的接口

### ISSUE THREAD

**Issue by hx78** [hankcs/HanLP#460]
比如“我要听雪漫频道”就被分成“我 要 听雪 漫 频道”，而我希望的是分成“我 要 听 雪漫 频道”。如果能动态地从DoubleArrayTrie结构动态删除某个字词，那我就不需要重启服务了

**Comment by TylunasLi** [comment]
DoubleArrayTrie是一种将固定词典嵌入到两个数组中的数据结构，因此难以在运行过程中动态增删条目。
你可以重新调用build()方法，把修改后的DoubleArrayTrie构建出来

**Comment by hankcs** [comment]
的确如此。

**Comment by linyixi** [comment]
DoubleArrayTrie 提供删除操作的实现网上有很多啊

**Comment by hankcs** [comment]
重点在于“代价大”上面。你可以推荐一些实现，或者做一些性能benchmark，试试动态增删的成本，或者说带来的性能下降。

**Comment by hx78** [comment]
ths.目前看来对DoubleArrayTrie进行动态的增删，其实就是对DoubleArrayTrie的重建。
