### ISSUE TITLE
“听电台北京怀旧金曲”VS“听电台北京音乐频道”

### ISSUE THREAD

**Issue by hx78** [hankcs/HanLP#461]
调用Segment segment = new NShortSegment().enableCustomDictionary(true);

1. **听电台北京怀旧金曲-->[听/v, 电/n, 台北/ns, 京/b, 怀旧/vn, 金曲/nz]**
打印词图：========按终点打印========
to:  1, from:  0, weight:04.60, word:始##始@听
to:  2, from:  1, weight:05.49, word:听@电
to:  3, from:  1, weight:10.85, word:听@电台
to:  4, from:  2, weight:10.35, word:电@台
to:  5, from:  2, weight:02.90, word:电@未##地
to:  6, from:  3, weight:11.44, word:电台@北
to:  6, from:  4, weight:10.57, word:台@北
to:  7, from:  3, weight:04.54, word:电台@未##地
to:  7, from:  4, weight:05.39, word:台@未##地
to:  8, from:  5, weight:04.28, word:未##地@京
to:  8, from:  6, weight:10.84, word:北@京
to:  9, from:  7, weight:07.56, word:未##地@怀
to:  9, from:  8, weight:11.18, word:京@怀
to: 10, from:  7, weight:09.53, word:未##地@怀旧
to: 10, from:  8, weight:11.18, word:京@怀旧
to: 11, from:  9, weight:11.50, word:怀@旧
to: 12, from: 10, weight:11.56, word:怀旧@金
to: 12, from: 11, weight:11.27, word:旧@金
to: 13, from: 10, weight:04.24, word:怀旧@金曲
to: 13, from: 11, weight:11.27, word:旧@金曲
to: 14, from: 12, weight:10.94, word:金@曲
to: 15, from: 13, weight:11.58, word:金曲@末##末
to: 15, from: 14, weight:03.15, word:曲@末##末

粗分结果[听/v, 电/n, 台北/ns, 京/b, 怀旧/vn, 金曲/nz]
人名角色观察：[  A 22202445 ][听 L 75 K 22 C 5 M 2 D 1 ][电 E 20 K 19 C 14 L 6 D 3 ][台北 K 1 ][京 C 305 E 274 D 97 B 24 ][怀旧 L 4 ][金曲 A 22202445 ][  A 22202445 ]
人名角色标注：[ /A ,听/K ,电/E ,台北/K ,京/B ,怀旧/L ,金曲/A , /A]
粗分结果[听/v, 电台/nis, 北京/ns, 怀旧/vn, 金曲/nz]
人名角色观察：[  A 22202445 ][听 L 75 K 22 C 5 M 2 D 1 ][电台 K 3 ][北京 K 37 L 28 ][怀旧 L 4 ][金曲 A 22202445 ][  A 22202445 ]
人名角色标注：[ /A ,听/K ,电台/K ,北京/K ,怀旧/L ,金曲/A , /A]
[听/v, 电/n, 台北/ns, 京/b, 怀旧/vn, 金曲/nz]

其中有一些边是找不到的，这个数值哪来的呢
“ ”@听 181
听@电 12 
听@电台 0
电@台 0
电@台北 354
电台@北 0
电台@北京 5 **查不到这个路径**
台@北 0
台@北京 21 **查不到这个路径**
台北@京 8 **查不到这个路径**
北@京 0
北京@怀 8  **查不到这个路径**
北京@怀旧 0
京@怀旧 0
怀@旧 0
怀旧@金 0
怀旧@金曲 2
旧@金曲 0
金@曲 0
金曲@“ ” 0
曲@“ ” 9

2. **听电台北京音乐频道-->[听/v, 电台/nis, 北京/ns, 音乐/n, 频道/n]**
打印词图：========按终点打印========
to:  1, from:  0, weight:04.60, word:始##始@听
to:  2, from:  1, weight:05.49, word:听@电
to:  3, from:  1, weight:10.85, word:听@电台
to:  4, from:  2, weight:10.35, word:电@台
to:  5, from:  2, weight:02.90, word:电@未##地
to:  6, from:  3, weight:11.44, word:电台@北
to:  6, from:  4, weight:10.57, word:台@北
to:  7, from:  3, weight:04.54, word:电台@未##地
to:  7, from:  4, weight:05.39, word:台@未##地
to:  8, from:  5, weight:04.28, word:未##地@京
to:  8, from:  6, weight:10.84, word:北@京
to:  9, from:  7, weight:05.53, word:未##地@音
to:  9, from:  8, weight:11.18, word:京@音
to: 10, from:  7, weight:05.12, word:未##地@音乐
to: 10, from:  8, weight:11.18, word:京@音乐
to: 11, from:  9, weight:11.52, word:音@乐
to: 12, from: 10, weight:11.02, word:音乐@频
to: 12, from: 11, weight:11.33, word:乐@频
to: 13, from: 10, weight:04.64, word:音乐@频道
to: 13, from: 11, weight:11.33, word:乐@频道
to: 14, from: 12, weight:11.46, word:频@道
to: 15, from: 13, weight:05.94, word:频道@末##末
to: 15, from: 14, weight:04.92, word:道@末##末

粗分结果[听/v, 电台/nis, 北京/ns, 音乐/n, 频道/n]
人名角色观察：[  A 22202445 ][听 L 75 K 22 C 5 M 2 D 1 ][电台 K 3 ][北京 K 37 L 28 ][音乐 L 9 ][频道 K 19 ][  A 22202445 ]
人名角色标注：[ /A ,听/K ,电台/K ,北京/K ,音乐/L ,频道/K , /A]
粗分结果[听/v, 电/n, 台北/ns, 京/b, 音乐/n, 频道/n]
人名角色观察：[  A 22202445 ][听 L 75 K 22 C 5 M 2 D 1 ][电 E 20 K 19 C 14 L 6 D 3 ][台北 K 1 ][京 C 305 E 274 D 97 B 24 ][音乐 L 9 ][频道 K 19 ][  A 22202445 ]
人名角色标注：[ /A ,听/K ,电/E ,台北/K ,京/B ,音乐/L ,频道/K , /A]
[听/v, 电台/nis, 北京/ns, 音乐/n, 频道/n]

**Comment by TylunasLi** [comment]
为了缓解Bigram数据稀疏问题 “北京” “台北” 被编译成了 未##地，共享了地名词语的上下文。
要解决这个问题，得调整路径得分（就是修改Bigram词典）。以上下文来说，“未##地@京”费用太低，“听@电台”费用太高。

**Comment by hx78** [comment]
1、问题一，下面这些路径在bigram字典是找不到的，但调试过程数值得分却不是0，而是下面的值
电台@北京 5 **查不到这个路径**
台@北京 21 **查不到这个路径**
台北@京 8 **查不到这个路径**
北京@怀 8 **查不到这个路径**
2、就上下文来说两个兔子“听电台北京”是完全一样的，后面的词组是怎么影响到分词结果的？

**“听电台北京”**完全一样
打印词图：========按终点打印========
to: 1, from: 0, weight:04.60, word:始##始@听
to: 2, from: 1, weight:05.49, word:听@电
to: 3, from: 1, weight:10.85, word:听@电台
to: 4, from: 2, weight:10.35, word:电@台
to: 5, from: 2, weight:02.90, word:电@未##地
to: 6, from: 3, weight:11.44, word:电台@北
to: 6, from: 4, weight:10.57, word:台@北
to: 7, from: 3, weight:04.54, word:电台@未##地
to: 7, from: 4, weight:05.39, word:台@未##地
to: 8, from: 5, weight:04.28, word:未##地@京
to: 8, from: 6, weight:10.84, word:北@京

**Comment by hankcs** [comment]
1. 你的问题其实 @TylunasLi 已经回答了，额外参考：

```
  System.out.println(CoreBiGramTableDictionary.getBiFrequency("电台", "北京"));
        System.out.println(CoreBiGramTableDictionary.getBiFrequency("电台", Predefine.TAG_PLACE));
```

2. 原理还请搜索BiGram分词，可能需要很长的文章才能讲清楚。
