### ISSUE TITLE
《自动摘要》文章字数达到一定量导致内存溢出

### ISSUE THREAD

**Issue by diaofantian** [hankcs/HanLP#462]
java.lang.OutOfMemoryError: GC overhead limit exceeded
    	at com.hankcs.hanlp.summary.TextRankSentence.<init>(TextRankSentence.java:74)
    	at com.hankcs.hanlp.summary.TextRankSentence.getSummary(TextRankSentence.java:253)
    	at com.hankcs.hanlp.HanLP.getSummary(HanLP.java:484)
    	at wisers.wisenews.doc.util.AutoSummaryUtil.getTextRankSummary(AutoSummaryUtil.java:299)
    	at wisers.wisenews.doc.util.AutoSummaryUtil.truncExcerptContent(AutoSummaryUtil.java:133)

我用一一篇 文章 大概有16w字左右，debug 看了 那个 切割后的句子的 sentences size 有1w以上，然后 在调用 分词排序算法时 TextRankSentence textRank = new TextRankSentence(docs);就抛出内存溢出，求大神 帮帮解释下，这个大概消耗内存 是多少，处理的量范围；谢谢

public TextRankSentence(List<List<String>> docs)
    {
        this.docs = docs;
        bm25 = new BM25(docs);
        D = docs.size();
        weight = new double[D][D];
        weight_sum = new double[D];
        vertex = new double[D];
        top = new TreeMap<Double, Integer>(Collections.reverseOrder());
        solve();
    `}```
weight = new double[D][D]; 这个当  docs.size();超过1w是就报内存溢出；

**Comment by hankcs** [comment]
给定含有D个句子文章，所需内存大致可以通过如下方式测算：

$$Mem=8 \times D^2 bytes $$

视具体机器配置，需要自行截断文章，限制最长字数。

**Comment by whitezdm** [comment]
我也是这个问题，还真是这样

**Comment by whitezdm** [comment]
巨大无比，内存超大

**Comment by intohole** [comment]
textrank会构建图的，不是内存泄漏吧 你这个1w * 1w 你把说放里面弄？

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
