### ISSUE TITLE
python实现地理命名实体识别

### ISSUE THREAD

**Issue by JinJiao8** [hankcs/HanLP#469]
我想问一下，对于地理命名实体识别，我怎么构建自己的分词词典。。。我先用python来实现这个问题。。

**Comment by hankcs** [comment]
https://github.com/hankcs/HanLP/wiki/%E8%AE%AD%E7%BB%83%E5%91%BD%E5%90%8D%E5%AE%9E%E4%BD%93%E8%AF%86%E5%88%AB%E6%A8%A1%E5%9E%8B
