### ISSUE TITLE
关于用CRF进行词性标注的几个问题

### ISSUE THREAD

**Issue by hx78** [hankcs/HanLP#472]
在使用CRF++时，发现example的例子是有3列的，中间列是词性
我做了一个简单的语料
                "放周杰伦",
                "放周杰伦的歌",
                "放电台",
                "播电台",
                "播电台北京怀旧金曲",
                "听电台",
                "要听电台",
                "我想听电台",
                "我要听电台",
                "放有声书",
                "我想听相声",
                "播鼓曲",
                "我想听鼓曲",
                "放越剧",
                "播越剧",
                "收听心动FM",
                "收听深圳动听102",

放      v       S
周      nt      B
杰      nt      M
伦      nt      E
放      v       S
周      ns      B
杰      ns      M
伦      ns      E
的      ude1    S
歌      n       S
台      n       E
播      v       S
电      a       B
台      n       E
听      v       S
电      a       B
台      n       E
我      rr      S
想      v       S
听      v       S
电      a       B
...

**Q1: “周杰伦”是一首歌曲还是一个人名**
其中 “放周杰伦”词性标注为 “放/v, 周/nt,  杰/nt, 伦/nt”
其中 “放周杰伦的歌”词性标注为 “放/v, 周/ns,  杰/ns, 伦/ns, 的/ude1, 歌/n”
这里的周杰伦分别为nt,ns属性，nt和ns只是用来测试而已，其目的是能根据上下文件确定“周杰伦”是一首歌曲还是一个人名。

**QA:“周杰伦”被拆分成“周 杰 伦”三个字后，每个字应该标注什么词性？**
周杰伦本身是一个人名，拆分成“周 杰 伦”三个字后，应该如何对每个字进行词性标注呢？

**Q3:在hanlp在，通过CRF进行词性标注会不会生效？**
我发现hanlp的词性标注是通过自定义字典实现的，CRF本身只是分词，并没有进行词性标注。
1）如果我对CRF的模型本身已经加入词性一列进行训练，那通过hanlp的CRF能否标注出词性，试了一下，发现是没有的，用的是上面的例子，所有字词词性都是null
2）我理解CRF本身是不需要词典的（或者说词典本身就在训练的语料中）,而hanlp中的CRF似乎使用了core字典。
3）hanlp的CRF分词器没有使用实体识别，这是为什么呢？

**Comment by 530154436** [comment]
多看看人家源码，尤其是那个viterbi分词器

**Comment by hankcs** [comment]
1. 你使用的example混淆了词性标注和分词两个过程。如果设计者认为这是个“joint model”的话，那也错了，因为CRF只预测一列。通常做法是将词性附加在BMES后面：B_nr
2. 字没有词性，或者说应该继承词的词性
3. 对的，本来就应该是两个过程。

**Comment by hx78** [comment]
@hankcs 
感谢。CRF比HMM有更好的消歧效果，请问你怎么没有采用CRF进行词性标注，而用HMM呢？是考虑到性能的问题吗？

**Comment by hx78** [comment]
mark
用43万个句子的语料（约25M，约100个句式）训练了一个音乐的CRF分词模型，在本地用虚拟机，开9个G的内存，跑了90分钟才训练好一个模型，但分词的效果并没有达到想要的效果；本想增大语料（对语料进行复制）以加强每种句式的概率，但发现仅仅是复制一次，即约50M，86万个句子，开了10个G也跑不起来，只能作罢。总的来说，CRF能考虑每个字词的上下文，然后进行分词，这样的分词是很合理的，我认为这里的模型分词的结果不理想和音乐的歌名、歌手等专有名词本身没有规律所造成的，也就是说CRF学习到的规律本身就是不正确的。对于音乐这些语料，我觉得已经不适用CRF来分词，反而用字典分词达到的效果要好得多，也易于控制。

**Comment by hankcs** [comment]
Q1
1. 目前单线程CRF的性能是20+万字每秒，HMM是200+，两者相差一个数量级
1. CRF一个模型几百兆，HMM几兆，两个数量级
所以可以说目前CRF\GLM\PA是超过了一般人的心理价位的，过个几年可能会有所改观。

Q2
如果是B_nr的话，则是完美的统一。

歌名的话，跟普通短语没什么区别的。比如“今天你要嫁给我”是一首歌，“明天你要嫁给我”则不是，的确没有任何统计规律在里面。
