### ISSUE TITLE
升级最新版本后角色标注识别的机构名称怎么全部匹配了

### ISSUE THREAD

**Issue by moshangshaoguang** [hankcs/HanLP#473]
我现在只是想识别出一个机构名称：陕西省渭南市蒲城迎宾商城有限公司
![image](https://cloud.githubusercontent.com/assets/20895017/24889354/13b04210-1e9c-11e7-891f-339a38b8a62a.png)
之前是根据长度优先匹配，显示的结果只有一个，现在结果是多个，需要怎么调整只让它显示的结果只有一个
最后显示的结果[陕西省/ns, 渭南市蒲城迎宾商城有限公司/nt]  之前最终的结果是[陕西省渭南市蒲城迎宾商城有限公司/nt]

**Comment by hankcs** [comment]
可能是版本库中的：https://github.com/hankcs/HanLP/commit/ab3fd3ef1645fd3c5bc80bf0d331dd9c2dfd9526引发的，这个commit的目的是提高查准率，可能不幸地降低了查全率。现在再提交一个workaround，应该解决了这个问题。

**Comment by moshangshaoguang** [comment]
还有一个问题，没升级版本之前是可以清除掉你们自带的角色匹配标注列表，使用自己的制定的规则列表；现在新版怎么没有清除规则列表的方法了（上传了几遍也没传上去图片只能文字叙述了）

**Comment by hankcs** [comment]
我从来都没有发布过这种版本，你可能使用了非官方的版本。

**Comment by moshangshaoguang** [comment]
是你们官方的，不过问题是出在我这，是我没有初始化
![image](https://cloud.githubusercontent.com/assets/20895017/25694028/0417c6ca-30df-11e7-9703-ab73dfaca9e9.png)

我标注的这个 所以一直报错。

**Comment by hankcs** [comment]
好的，解决了就好。
