### ISSUE TITLE
使用CustomDictionary.get获取核心词典单词为null，开启调试显示词库皆已加载

### ISSUE THREAD

**Issue by frf12** [hankcs/HanLP#476]
以下每次测试前都删除了bin文件
以下测试均使用源码和jar包导入两种形式测试过，结果一致
望hankcs解惑

1.CustomDictionary.get函数获取核心词典返回为Null
结果为null
但HanLP.Config.enableDebug()开启调试后，调用分词函数HanLP.extractPhrase("更多精彩请搜索王者荣耀",10);结果可以看到 搜索/vn
此时调用CustomDictionary.get(“搜索”)获取信息仍然是Null

2.自定词库未载入
HanLP.Config.enableDebug()开启调试后提示加载了自定义词典，该词典只有一条记录（王者荣耀 nz 1），但是调用分词函数HanLP.extractPhrase("更多精彩请搜索王者荣耀",10);结果可以看到 王者/n, 荣耀/an.使用CustomDictionary.get(“王者荣耀”)返回为null

3.修改已有的自定义词典未生效
使用CustomDictionary.get(“b超”)获取到了“现代汉语补充词库.txt”中的第一条记录，于是我将"王者荣耀 nz 1"添加在这个词典的开头（失败后又尝试放在结尾，仍然失败）,使用CustomDictionary.get(“王者荣耀”)返回为null，CustomDictionary.get(“b超”)仍然有返回值。

**Comment by hankcs** [comment]
1. 因为搜索属于核心词典，你可以com.hankcs.hanlp.utility.LexiconUtility#getAttribute(java.lang.String)，这个方法才会同时在两个词典中查找
2. 开启调试后提示加载了自定义词典却没有词条的问题，请确认词典是否UTF-8编码无BOM，如果不确定，复制data/dictionary/custom/CustomDictionary.txt并清空作为空白新词典。
3. 我先试试

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
