### ISSUE TITLE
model.txt如何转换为model.txt.bin

### ISSUE THREAD

**Issue by Jactor-Sue** [hankcs/HanLP#480]
您好，我在[issue#45](https://github.com/hankcs/HanLP/issues/45)中看到您提到将CRF++训练出的model.txt转换成了model.txt.bin，然后将model.txt.bin文件作为HanLP的CRF分词模型，我想请问一下这个转换过程是如何完成的，目的是什么？还望不吝赐教，谢谢！
另，我的目的是想要使用我自己用CRF++训练出来的模型替换您HanLP提供的模型来定制CRF模型。

**Comment by hankcs** [comment]
#CRF分词模型路径
CRFSegmentModelPath=data/model/segment/YourCRFSegmentModel.txt

运行后会自动得到.bin模型。

**Comment by Jactor-Sue** [comment]
谢谢，我运行了一次之后果然出现了.txt.bin文件，但是生成这个文件的目的是什么？

**Comment by kelciej** [comment]
@Jactor-Sue 您好，你的模型运行成功了么？ 方便告知一下crf_learn训练之前的格式么？

**Comment by Jactor-Sue** [comment]
你好，运行成功了，crf_learn训练使用的文本格式如下：
traindata.txt
```
迈	B
向	E
充	B
满	E
希	B
望	E
的	S
新	S
世	B
纪	E
...
```
这个文件是经如下格式的文本转换过来的
traindata_raw.txt
```
迈向  充满  希望  的  新  世纪 ...
```

**Comment by TylunasLi** [comment]
生成bin文件当然是为了更快加载。否则所有对象都要从头构建

**Comment by hankcs** [comment]
对，程序员调试会反复启动应用程序，节省大家的宝贵时间。

**Comment by Jactor-Sue** [comment]
谢谢各位

**Comment by kelciej** [comment]
@Jactor-Sue 你训练生成的model.txt也就是YourCRFSegmentModel.txt，可以用么？为什么我生成的用完之后，用CRF跑了一次，执行结果是BBBBBBBBS，你的model.txt大概有多大？

**Comment by Jactor-Sue** [comment]
我的可以用，我用人民日报语料训练的model.txt 10.7MB，用搜狗语料训练的有416MB，都可以用

**Comment by kelciej** [comment]
你可以发一份你的训练语料给我么 我这边试一直有问题

**Comment by Jactor-Sue** [comment]
地址给你，你自己去下载吧，我就不传播了。。。
[人民日报语料下载地址](http://icl.pku.edu.cn/icl_groups/corpus/dwldform1.asp)
[搜狗实验室语料下载地址](http://www.sogou.com/labs/resource/list_yuliao.php)

**Comment by kelciej** [comment]
非常感谢！

**Comment by XiaoLiuAI** [comment]
请问 @kelciej 运行成功了吗? 我在人民日报2014语料上(九十万句话)运行crf++,之后得到的模型用crf++自己的test程序运行正常,但是用HanLP加载后就是BBBBBS这样的结果. 感觉参数读取的顺序似乎不对.

**Comment by kelciej** [comment]
没有呢 现在也无可奈何了

**Comment by hankcs** [comment]
有些版本的CRF++输出的id是乱序的：http://www.hankcs.com/nlp/the-crf-model-format-description.html#comments
自己排个序转换一下就可以了。

**Comment by kelciej** [comment]
顺序就不会出现这个问题了是吧

**Comment by XiaoLiuAI** [comment]
顺序不会,但是这个其实不难在java里面实现. @hankcs  强烈建议官方修改一下. 
抛砖引玉:
```Java
        List<Pair<Integer, FeatureFunction>> featureFunctionList = new LinkedList<Pair<Integer, FeatureFunction>>(); // 读取权值的时候用

        int b = -1;// 转换矩阵的权重位置
        if (CRFModel.matrix != null)
        {
            String[] args = lineIterator.next().split(" ", 2);    // 0 B
            b = Integer.valueOf(args[0]);
        }

        while ((line = lineIterator.next()).length() != 0)
        {
            String[] args = line.split(" ", 2);
            char[] charArray = args[1].toCharArray();
            FeatureFunction featureFunction = new FeatureFunction(charArray, size);
            featureFunctionMap.put(args[1], featureFunction);
            featureFunctionList.add(new Pair(Integer.valueOf(args[0]), featureFunction));
        }

        featureFunctionList.sort(Comparator.comparing(p -> p.first));
        int end = Math.max(b, featureFunctionList.stream().max(Comparator.comparing(p -> p.first)).get().first);
        Iterator<Pair<Integer, FeatureFunction>> iter = featureFunctionList.iterator();
        for(int i=0; i<=end;){
            if(i!=b){
                // 个体权重
                FeatureFunction featureFunction = iter.next().second;
                for (int j = 0; j < size; j++)
                {
                    featureFunction.w[j] = Double.parseDouble(lineIterator.next());
                }
                i+=size;
            }else{
                // 转换矩阵
                for (int m = 0; m < size; m++)
                {
                    for (int n = 0; n < size; n++)
                    {
                        CRFModel.matrix[m][n] = Double.parseDouble(lineIterator.next());
                    }
                }
                i+=size*size;
            }
        }
```

**Comment by hankcs** [comment]
@XiaoLiuAI 感谢建议，我没有乱序的model测试，随时欢迎PR（请保持JDK1.6）

**Comment by qujinqiang** [comment]
@XiaoLiuAI  这个是正解， 这样就可以适配所有版本的CRF++了

**Comment by qujinqiang** [comment]
@XiaoLiuAI  你提交pull request没？ 你没有提交的话我就提交下。。。。

**Comment by XiaoLiuAI** [comment]
@qujinqiang 你来吧. 这阵子忙,没时间搞. 注意要保持JDK1.6.

**Comment by TylunasLi** [comment]
1. 兼容模型训练时只支持CRF++输入两列, 即“汉字\t标签”，如果增加其他列（例如大多数文献都会加入字符特征），需要修改CRFSegment和CRFSegmentModel的代码。 
2. 训练文本的字符要经过HanLP字符规范化处理，如完成全角转半角、异体字转换；
3. 训练文本的词语要经过CRFSegment中的原子化处理，即把英文字符和阿拉伯数字替换为W和M；
4. 特征数越多解码越慢，用TMPT-10特征模板后。速度和优化后的HMM不相上下了。
5. TestCRF里面用的数据结构是DAT，正式代码CRFSegment里面的数据结构是BinTrie，注意处理缓存文件。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
