### ISSUE TITLE
hankcs好，我看github上说有1.4版本的计划，请问1.4预计什么时间会出呢？可有一个大概出的时间区间？

### ISSUE THREAD

**Issue by lowpair** [hankcs/HanLP#481]
RT

**Comment by hankcs** [comment]
# 关于开发计划
感谢关注，HanLP的确有长期开发计划。
## 长期计划
长远的计划是进一步实现“统计化”，逐步去掉那些倚重“人工规则”的算法与模块，解决现有框架的[难题](https://github.com/hankcs/HanLP/issues/407#issuecomment-283738734)。长期计划中的确还包括加入更多更高级的模块和功能。
## 短期计划
这些计划由零散的主意构成，来源于issue区偶然产生的一些灵感。通常只需较少的工作量，这些计划放在《[开发计划](https://github.com/hankcs/HanLP/projects/1)》中统一维护，欢迎随时查阅。
## 时间节点
没有时间期限。因为：
### 开源项目
世界上有很多开源项目，但按照目的而言只有两种：
**1. 有商业目的的开源项目**

* 背后主要由商业公司支撑，雇佣全职员工参与开发，目的（就算不是主要目的，至少也有部分意愿）是推广行业标准（TensorFlow）、测试公司产品（Fedora）、汲取社区智慧改进产品（OpenJDK）、低价倾销后续收费（一些国产“开源”软件如Discuz）……
* 这类开源产品大部分影响深远，具有改变行业的力量。既达成了企业的商业目的，又造福了所有用户。

**2. 以兴趣主导的开源项目**

*  无商业公司支撑，没有任何商业目的。多源于某个黑客的一时兴起，“在座的工具都不好用，为什么不自己造一个呢”。或者源于史蒂夫·沃兹尼克“做出好东西就应该让更多的人使用”那种朴素的利他主义。再者就是实验学习性质的作品，在维护作品的同时得到成长。
*  这类开源项目虽然缺少资金人力，但不乏闪光之作，伟大如Linux自不必说，小领域的如[鸣谢](https://github.com/hankcs/HanLP#鸣谢)中列举的那些接地气的项目同样精彩。

毫无疑问，HanLP是属于后者的，完全基于兴趣，无商业支持，专注一个小众领域，希望做到极致。即使现在做的还不好，也在往好的方向前进。

### 项目初衷
自然语言处理本来是一个小众的圈子，综合了多个交叉学科的领域知识。不但需要较深的数学基础，还需要实现复杂算法的工程能力，并且语言学知识也不可或缺。 
HanLP作为一个开源自由的项目，初衷是降低上述技术门槛，普及统计自然语言处理到生产环境中去。即使只是一个抛砖引玉的项目，也有其坚持的东西。
为什么走统计自然语言处理的方向？因为我不喜欢那些自作聪明的“人工规则”“评分公式”，以及靠此存活的系统或“专家”。这些“人肉智能”及其机械工作应当逐步被机器替代掉。
很高兴最初的想法得到了越来越多的赞同，有越来越多的公司和个人开始关注语料库建设，开始转型到统计模型。

### 一些不愉快的人和事
除了开源项目本身固有属性外，还有一些不愉快的人和事也在阻碍HanLP的开发进度。我猜以下内容会引起部分人士的不悦，但我依然不吐不快。接受心平气和的技术辩论，但决不伺候下文中的人士。也许这些人士离开后，整个社区风气会好一些。
#### 浮躁的大环境
在目前的创业热潮下，大量商业公司蜂拥而入“数据行业”。前面提到过，自然语言处理是个涉猎较广的交叉学科。其他行业的常规工程师一般对此不感兴趣，却还要被老板逼上梁山，心情烦躁，我能理解。
绝非故作清高，issue区的确有人问出“怎么生成身份证号码”这种问题。我想正常人都不屑与办假证的小贩共事吧。另有某公司想“基于词频和BiGram做98%准确率的分词器”，创业全靠“技术专家”吹牛皮，话不投机半句多。
人以类聚，物以群分。我也没兴趣赶此时髦哗众取宠，虽然水平不高，但脸还是要的。也许避避风头，等这股热潮过去了才好。
#### 基本教养
虽然不想提，但林子大了什么鸟都有。特别是上述大环境下，涌入了个别下九流的人士。issue区，特别是那些没回复的和被closed的issue中，不时可见气势汹汹的质问语气，比如最极端的例子：https://github.com/hankcs/HanLP/issues/428
我在[另一个issue](https://github.com/hankcs/HanLP/issues/445)中也探讨了一下这个问题，当时issue作者想要更多的支持，比如QQ群之类。我只能很遗憾地回复，由于上述人群，我也爱莫能助，对方也表示理解。做开源项目不图钱，就图个开心，不是么？
#### 把开源当免费
开源的free是自由的意思，而不是免费的意思，更不代表开源社区是廉价免费劳动力。
issue区有被滥用的趋势，部分人喜欢把自己公司老板派的需求发上来，觉得开源项目维护者理所当然有义务帮他干活。常见的口吻是，“我有这样一个需求……”“我的要求是……”
另外，许多提问者也没有好的提问习惯。不会用Markdown也就算了（这其实反应了技术素养），连版本号触发代码都不写，前后因故也不提，问了半天才知道是自己改了代码；这谁猜得到，谁又有耐心猜呢？其实wiki里有篇《[如何提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)》，但大多数人都不尊重。说句不好听的，你不尊重别人，为什么要别人尊重你呢？
一旦得到满意回复，大多数人马上就消失了，连句谢谢都没有（可能上幼儿园补习礼貌课去了吧）。
有位做企业的朋友曾经说过——

> 中国的开源项目就像婊子，用完之后没人记得。

话糙理不糙，反映了大环境。估计这些人认为开源项目不但是婊子，还得是免费的婊子。

#### 不尊重版权
如果你有心的话，你会发现我在代码和文章注明了大量的论文引用，一些第三方代码也保留了全部署名。
我希望用户尊重提出了该算法的学者老师、实现了该算法的开源作者。我能在这些研究成果上改进算法库，你能在算法库上做商业应用赚钱，归根结底全是他们的功劳。我还希望借此激发一些高级用户对底层算法的兴趣，不要局限于做浮躁的工程师。
为此，我还注释了几乎全部的核心代码，写了很多附属文档。我衷心希望第一次接触自然语言处理的工程师，也能看懂代码的关键，并最终参与开源，一起完善这个不完美的小项目。最初的设想的确实现了一部分，有越来越多的contributor贡献了代码，谢谢你们！
君子不少，但小人更多。我自己就不止一次见过，将HanLP复制粘贴，所有署名和引用连同包名一起，改成自己的名字，连文档都是照抄，一个个山寨的xxxLP粉墨登场。其中一些还要假惺惺地把“基于贝尔实验室的AC自动机算法”放到最显眼的地方拉拢崇洋媚外者，其居心之龌龊、手段之卑劣，令人发指。
这还只是互联网上露出的冰山一角，在更阴暗的角落，HanLP一定多次被抹掉全部署名，改得面目全非然后重新贩售。我写了那么多的注释，反倒方便贼剽窃吗？
想想就觉得恶心。我完全不介意等这些垃圾公司倒闭之后再做新功能啊（肯定不用等多久的😉）。

## 结论
issue区的确谈到了1.4版的设想，而且说实话早就研究明白了。关注博客的读者们可能会注意到，长期计划中的GLM\CRF等也研究过了。但就在准备开源的时候，发生了类似上述的不愉快事件，我又恰好处于人生中一个非常忙的阶段，兴趣也转向了更复杂的神经网络语言模型，所以暂停了。
说了这么多正面和负面的情况，最终的结论就是，HanLP有自由的步调；每个人的一言一行都会间接影响开发步调；友好一点，开发积极性就会高一点；恶毒一点，没好处。

**Comment by lowpair** [comment]
谢谢hankcs。
不先通览文档，不调试源代码提出的基础问题，都是懒人，懒的如脖子上围着一圈大饼能饿死的人，谁都帮不了。
hankcs.com上的文章，又有语料又有源码又有论文说明又有步骤解析，在网络上成体系的这样慷慨且持续的优质内容很难得！
随着时间发展，陆续发现其他NLP领域多次提到HanLP的应用，好东西会慢慢体现出价值光芒的，祝福HanLP！
