### ISSUE TITLE
CRFSegment.cs中tag方法有一行代码没看懂

### ISSUE THREAD

**Issue by starkingpku** [hankcs/HanLP#49]
博主，在tag方法中，利用维特比方法计算字符串的标注路径时，有一段代码是if (matrix[pre][now] <= 0) continue； 为什么tag的转移概率<0，就略过了呢？

**Comment by hankcs** [comment]
这仅仅是为了运行效率，既然BMES是连续的标签，那么转移矩阵的任何一行都至少有一个值大于零，所以小于零的都不用考虑了。

**Comment by starkingpku** [comment]
第一个问题，HMM模型的发射概率p(observ|state)和状态转移概率p(state_j|state_i)是转移矩阵, CRF中的f(state_i,state_j)不是转移概率吧，只是表示状态之间相关强度吧？不知我理解的对不对。
第二个问题，对于当前状态now，假设有两个前驱状态pre1、pre2的状态转移矩阵满足matrix[pre1][now]<0 并且 matrix[pre2][now]>0，但是会不会可能net[i - 1][pre1]>net[i - 1][pre2]，造成score1>score2呢？如果这样，那么score1的计算就不应该略过了吧？

**Comment by hankcs** [comment]
的确不是转移概率，你说得有道理，感谢指正。

**Comment by starkingpku** [comment]
我采用CRF++0.58，编译时无论是mac还是linux,configure时都会遇到这个问题：
configure: error: Your compiler is not powerful enough to compile CRF++. If it should be, see config.log for more information of why it failed.
解决起来复杂吗？

**Comment by hankcs** [comment]
我没遇到过这种问题，直接编译成功了。你可以使用binary。

**Comment by starkingpku** [comment]
谢谢！
