### ISSUE TITLE
有关动态添加单词的问题

### ISSUE THREAD

**Issue by kelciej** [hankcs/HanLP#495]
hanks，你好，
在经过动态添加单词，或者单词+词性
CustomDictionary.insert(word);
CustomDictionary.add(word);
之后，应该通过什么方法才能获得该词的原分词结果和词性
比方说，强制添加了一个新词CustomDictionary.insert(“睡不着觉 xx 1”);
之后想获得该词的原来的分词结果
[睡/v, 不/d, 着/uz, 觉/v
可有方法？

**Comment by hankcs** [comment]
得自行编写业务逻辑了。

**Comment by kelciej** [comment]
嗯嗯，我知道啦，谢谢

**Comment by kelciej** [comment]
我后来解决的办法就是，把原来的分词结果，写入txt
