### ISSUE TITLE
使用solr搜索分词后的结果搜不到，麻烦解答一下。

### ISSUE THREAD

**Issue by gxy0451** [hankcs/HanLP#496]
使用hanlp分词,索引内容：“中医药大学附属医院”，solr测试字段用的是“hanlp”。
搜hanlp:"中医"能搜到，搜hanlp:"中医药"却搜不到。具体问题截图在这里：https://www.oschina.net/question/145106_2239234
麻烦作者帮忙看下，多谢！

**Comment by gxy0451** [comment]
再次呼唤作者，最近试了ik和ansj，同样的情形都可以搜索到，想请问对于hanlp是还需要其他配置么？

**Comment by hankcs** [comment]
1. 从你的截图来看，HanLP的索引分词完全正常，对于index和query，中医药的分词结果都为 中医药 中医 医药。
1. 问题可能出在你solr配置上面，你可以上传一份我们一起分析一下。
1. 或者你可以直接参考我的配置：
```
    <!-- 默认文本类型: 指定使用HanLP分词器，同时开启索引模式。
	 通过solr自带的停用词过滤器，使用"stopwords.txt"（默认空白）过滤。
	 在搜索的时候，还支持solr自带的同义词词典。-->
    <fieldType name="text_general" class="solr.TextField" positionIncrementGap="100">
      <analyzer type="index">
        <tokenizer class="com.hankcs.lucene.HanLPTokenizerFactory" enableIndexMode="true"/>
        <filter class="solr.StopFilterFactory" ignoreCase="true" words="stopwords.txt" />
        <!-- 取消注释可以启用索引期间的同义词词典
        <filter class="solr.SynonymFilterFactory" synonyms="index_synonyms.txt" ignoreCase="true" expand="false"/>
        -->
        <filter class="solr.LowerCaseFilterFactory"/>
      </analyzer>
      <analyzer type="query">
        <tokenizer class="com.hankcs.lucene.HanLPTokenizerFactory" enableIndexMode="true"/>
        <filter class="solr.StopFilterFactory" ignoreCase="true" words="stopwords.txt" />
        <filter class="solr.SynonymFilterFactory" synonyms="synonyms.txt" ignoreCase="true" expand="true"/>
        <filter class="solr.LowerCaseFilterFactory"/>
      </analyzer>
    </fieldType>
```

我上传的测试文档：
```
id,title
1,你好世界
2,商品和服务
3,和服的价格是每镑15便士
4,服务大众
5,hanlp工作正常
6,中华人民共和国中含有多个词
7,征服了人类围棋界后，阿尔法狗的下一个目标是电竞
8,中医药大学附属医院
```

运行结果完全正确：
![](http://ww1.sinaimg.cn/large/6cbb8645gy1ff0po8gd6yj20sl0lujwt.jpg)

**Comment by gxy0451** [comment]
非常感谢大神百忙之中的回复，我又仔细找了一下差别，貌我找到不好使的原因了，我用的jar包是hanlp-1.3.2.jar，通过hanlp.properties配置hanlp的data信息，data是从github上下载下来的，没有改过。我的manage-schema如下：

```
  <field name="hanlp" type="text_hanlp" multiValued="false" indexed="true" required="false" stored="true"/>
  <fieldType name="text_hanlp" class="solr.TextField">
      <analyzer type="index">
          <tokenizer class="com.hankcs.lucene.HanLPTokenizerFactory" enableIndexMode="true"/>
      </analyzer>
      <analyzer type="query">
          <tokenizer class="com.hankcs.lucene.HanLPTokenizerFactory" enableIndexMode="true"/>
      </analyzer>
  </fieldType>
```
在此配置下，solr5、solr6都试过了，都是不好使的。
如果换成hanlp-portable-1.3.2.jar，去掉hanlp.properties就能搜到了，跟你截图一样，不知道这个是为什么。

**Comment by gxy0451** [comment]
然而使用hanlp-portable.jar这个包，又出现了新的问题
![image](https://cloud.githubusercontent.com/assets/5125893/25472829/90539ea0-2b5f-11e7-9ee2-6508c1fe1134.png)

搜索hanlp:"合作"可以搜到，
![image](https://cloud.githubusercontent.com/assets/5125893/25472915/e2a0479e-2b5f-11e7-947a-1ffce459b4cf.png)

搜索hanlp:"合作社"搜索不到，
![image](https://cloud.githubusercontent.com/assets/5125893/25472816/816037be-2b5f-11e7-9f6a-a5266c9c65de.png)
在ik分词下是可以搜到的
![image](https://cloud.githubusercontent.com/assets/5125893/25472857/b5f9925e-2b5f-11e7-8ff9-1a150481bd9f.png)

这个问题不管是用portable的jar还是原始jar+hanlp.properties都存在。

**Comment by hankcs** [comment]
用不用portable关系不大，关键是hanlp.properties里面用的是什么词典。

不过真是奇怪，我这边是完全正常的：
<img width="815" alt="hankcs com 2017-04-27 9 05 18" src="https://cloud.githubusercontent.com/assets/5326890/25487048/b6efbf62-2b28-11e7-9d2e-55512a645b62.png">

我待会儿将整个solr目录打包上传上来，欢迎做个对比。方便的话，你也可以去掉敏感信息，打包一个有问题的solr上来。

**Comment by gxy0451** [comment]
hanlp.properties里面都是用的默认的词典，只改了data的目录。

**Comment by hankcs** [comment]
问题藏得有点深，不过我很乐意解决。

这是我的solr core，你可以解压到solr-5.2.1/server/solr目录下，直接搜索“合作社”试试。如果正常的话，然后往这个core里面添加你的测试文档。

[one.zip](https://github.com/hankcs/HanLP/files/961886/one.zip)

整个solr目录太大，一时半会儿上传不来。

**Comment by gxy0451** [comment]
实在麻烦你了，你稍等，我马上打个有问题的包上来。

**Comment by gxy0451** [comment]
[solr.zip](https://github.com/hankcs/HanLP/files/961917/solr.zip)
我的solr是6.1，部署在tomcat中，jar用的是hanlp-portable-1.3.2.jar和hanlp-solr-plugin-1.1.2.jar，没有加hanlp.properties

**Comment by gxy0451** [comment]
我用你的solr配置加入到我的服务中，确实能搜到title:"合作社"，但是我自己又重新加一遍，却搜不到。
你的id是9，我的是10
![image](https://cloud.githubusercontent.com/assets/5125893/25489121/7bc57526-2b9b-11e7-902c-2c529e97e482.png)
但是搜索的时候只有id为9的
![image](https://cloud.githubusercontent.com/assets/5125893/25489178/9d8d14ca-2b9b-11e7-9aa7-53f250ed05ff.png)

**Comment by hankcs** [comment]
很好，感觉离答案又近了一步。我的低版本solr无法导入你的core，但从你的反馈来看，有可能是新版本solr创建索引时发生了问题。我猜新版本对配置文件的处理方式不同，导致enableIndexMode没有生效之类。

**Comment by gxy0451** [comment]
我今天特意下的solr5.4，我再用5.4试一下，5.1没找到下载地址。

**Comment by hankcs** [comment]
所有版本都在这里：http://archive.apache.org/dist/lucene/solr/

**Comment by gxy0451** [comment]
我用solr5.5.4和solr5.2.1都尝试过了，都不好使，跟我之前发的现象一样，都是新建的找不到。我建立solr服务器的步骤如下：
1下载solr，将war或webapp文件放在tomcat的webapp中，然后将lib/ext/中的日志相关jar加入到WEB-INF/lib中
2将hanlp-portable-1.3.2.jar和hanlp-solr-plugin-1.1.2.jar放在WEB-INF/lib中
3修改web.xml中的solr路径
4启动后在documents中以如下方式添加doc
![image](https://cloud.githubusercontent.com/assets/5125893/25491434/86a8ae52-2ba2-11e7-9a93-a3a7fb394bf1.png)
5进行搜索title:"合作社"，结果只有id为9的

**Comment by gxy0451** [comment]
5.2.1中出问题的solr文件如下
[one.zip](https://github.com/hankcs/HanLP/files/962108/one.zip)

**Comment by gxy0451** [comment]
我的tomcat是8.5.4，jdk是8

**Comment by hankcs** [comment]
我在6.1下用你的配置也是新建的不行，现在开始用Luke排查index

**Comment by gxy0451** [comment]
这么晚了还在弄，太感动了。

**Comment by hankcs** [comment]
我彻底查明了原因，循序渐进地解决问题吧。

1. 按照Lucene的规范，HanLP的索引分词没有问题：
![2017-04-27_11-37-11](https://cloud.githubusercontent.com/assets/5326890/25494009/e64210ca-2b3d-11e7-9ca5-e7b040b3e813.png)
2. 按照Lucene搜索语法，你的query hanlp:"合作社"代表搜索"合作社"这个短语。短语由词构成，如果你在query中也开启索引分词的话，则代表查询 "PhraseQuery(hanlp:\"合作社 合作\")" 这个短语。该短语由两个词构成，合作社+合作。
3. 按照phase query语法，两个词之间的距离必须小于某个值，叫slop。在solr5中，StrField的slop可能默认不为0，但在solr6中TextField的slop一定默认为0。所以你的query相当于查询“合作社合作”这个句子。而事实上，文档库中没有这个句子。
4. 所以我的配置文件从来不推荐在query中开启index模式，index模式本来就只是给索引用的：
```
<fieldType name="text_cn" class="solr.TextField">
    <analyzer type="index">
        <tokenizer class="com.hankcs.lucene.HanLPTokenizerFactory" enableIndexMode="true"/>
    </analyzer>
    <analyzer type="query">
        <tokenizer class="com.hankcs.lucene.HanLPTokenizerFactory" enableIndexMode="false"/>
    </analyzer>
</fieldType>
```
1. ansj也是采用了这种策略，索引模式不开放给query用：https://github.com/NLPchina/ansj_seg/blob/6cf0dd04c8f97e94f632cb44b6e875a9ed5dc3e0/plugin/ansj_solr4_plugin/src/main/java/org/ansj/solr/AnsjTokenizerFactory.java#L71 ，我注意到你在配置ansj的时候根本没有开启index模式，ik时也没有，所以它们都是正常的。

所以最终解决方案有好几种
1. 切记不要在query中开启enableIndexMode
1. 查询串不要加引号hanlp:合作社
1. 查询串加引号的话要指定slop>0，比如hanlp:"合作社"~5

<img width="962" alt="hankcs com 2017-04-27 12 02 12" src="https://cloud.githubusercontent.com/assets/5326890/25495042/66049e74-2b41-11e7-975e-a0578cdc0d0b.png">

这个问题应该圆满解决了。
感谢你的耐心反馈，相较之下，有很多浮躁的人遇到问题从来不动脑子，一上来就开喷，既误导后来者，又挫伤开源积极性。

**Comment by gxy0451** [comment]
首先再次感谢作者不遗余力的解答这个问题。
经过我这几天的尝试，我觉得可能是这个问题:
在使用portable内置的词库分词时候，分词效果是
![image](https://cloud.githubusercontent.com/assets/5125893/25516955/c331622e-2c1f-11e7-8df1-30293f30bdad.png)
这个分词顺序是和搜索的时候分词顺序是一样的，position顺序对的上，所以全词匹配搜索才能找到。

然而使用hanlp.properties加载外部词典后，分词的顺序改了，如下图：
![image](https://cloud.githubusercontent.com/assets/5125893/25516877/659f423e-2c1f-11e7-97a4-188ff84daf6e.png)
这个导致了全词匹配的时候与关键字的分词结果"合作社 合作"词序对不上，所以需要增大slop才能匹配上。按照网上对于slop的说法（ http://blog.csdn.net/rick_123/article/details/6708527  ），需要调整2步才能匹配上，也就是hanlp:"中医药"~2才能有结果。

合作社那个问题也是同样，slop需要达到2才能匹配上：
<img width="930" alt="wx20170428-144711 2x" src="https://cloud.githubusercontent.com/assets/5125893/25517638/e69a1e1a-2c22-11e7-93f9-d7c95d211155.png">
![image](https://cloud.githubusercontent.com/assets/5125893/25517659/f897db16-2c22-11e7-9bd3-5d5f70cafaa8.png)

ik的分词结果顺序就是一致的。不知道hanlp能不能也将其改成一致的呢？

**Comment by gxy0451** [comment]
我的需求就是需要进行全词匹配，所以才会查询的时候也要设置enableIndexMode，否则全词匹配就什么都查不到了。另外还有个诡异的问题：在使用hanlp.properties外挂字典时（我的data包都是直接从百度云下载的，没有任何更改）可能会出现两个重复的分词，
![image](https://cloud.githubusercontent.com/assets/5125893/25518731/803e13ba-2c27-11e7-983f-8c5d44b89fbf.png)
![image](https://cloud.githubusercontent.com/assets/5125893/25518977/94e05c00-2c28-11e7-9444-b2b1db294214.png)

用的jar包是hanlp-portable-1.3.2.jar和hanlp-solr-plugin-1.1.2.jar

**Comment by gxy0451** [comment]
还有一个问题要麻烦问下作者，对于下图中我该怎么调整词库才能让搜索 hanlp:不准许 的结果中有“不准许张贴广告”这条记录呢？
![image](https://cloud.githubusercontent.com/assets/5125893/25521844/b8b17cb2-2c33-11e7-958b-1cec79047be2.png)

**Comment by hankcs** [comment]
不客气，你的发现更加深刻。

- 关于position的问题，HanLP与Ansj的处理方式一致，都为每个词语增加了一次position，参考ansj的代码：https://github.com/NLPchina/ansj_seg/blob/6cf0dd04c8f97e94f632cb44b6e875a9ed5dc3e0/plugin/ansj_lucene5_plugin/src/main/java/org/ansj/lucene/util/AnsjTokenizer.java#L63 。我对比了两者的索引分词，都存在你所说的顺序问题：

ansj:
[中医药/n, 中/f, 中医/nnd, 医/ng, 医药/n, 药/n]
[中医药大学/ntu, 中/f, 中医/nnd, 中医药/n, 医/ng, 医药/n, 药/n, 大/a, 大学/nis, 学/v]
HanLP:
[中医药/n, 中医/nnd, 医药/n]
[中医药大学/ntu, 中医/nnd, 中医药/n, 医药/n, 大学/nis]

- 而ik则根本没有PositionIncrementAttribute这个属性。按照Lucene官方说法，对每个词，PositionIncrementAttribute都默认为1 。为什么ik能搜索出来呢

对中医药的结果是：
0 - 3 : 中医药 | CN_WORD
0 - 2 : 中医 | CN_WORD
1 - 3 : 医药 | CN_WORD
对“中医药大学”的分词结果是：
0 - 5 : 中医药大学 | CN_WORD
0 - 3 : 中医药 | CN_WORD
0 - 2 : 中医 | CN_WORD
1 - 3 : 医药 | CN_WORD
3 - 5 : 大学 | CN_WORD

前后顺序的确是一致的，这是值得学习的地方。

- 我今天实现了一下，达到了这个效果：
[中医药/n, 中医/nnd, 医药/n]
[中医药大学/ntu, 中医药/n, 中医/nnd, 医药/n, 大学/nis]

欢迎测试：
[hanlp-1.3.3-beta.zip](https://github.com/hankcs/HanLP/files/964541/hanlp-1.3.3-beta.zip)

**Comment by hankcs** [comment]
“不准许”的问题是这样的，你将两个句子放到一起，虽然有换行，但solr的webapp实际上会去掉换行符，实际上成了一个句子。
你可以试试

```
    public void testIndexModePosition() throws Exception
    {
        CustomDictionary.insert("中医药大学");
        HanLPTokenizer tokenizer = new HanLPTokenizer(HanLP.newSegment().enableIndexMode(true), null, false);
        String testCases[] = new String[]{
          "不准许",
          "不准许张贴广告",
          "不准许和张三来往",
        };
        for (String sentence : testCases)
        {
            System.out.printf("%s\n", sentence);
            tokenizer.setReader(new StringReader(sentence));
            tokenizer.reset();
            while (tokenizer.incrementToken())
            {
                CharTermAttribute attribute = tokenizer.getAttribute(CharTermAttribute.class);
                // 偏移量
                OffsetAttribute offsetAtt = tokenizer.getAttribute(OffsetAttribute.class);
                // 距离
                PositionIncrementAttribute positionAttr = tokenizer.getAttribute(PositionIncrementAttribute.class);
                // 词性
                TypeAttribute typeAttr = tokenizer.getAttribute(TypeAttribute.class);
                System.out.printf("[%d:%d %d] %s/%s\n", offsetAtt.startOffset(), offsetAtt.endOffset(), positionAttr.getPositionIncrement(), attribute, typeAttr.type());
            }
            tokenizer.close();
        }
    }
```

输出都是稳定的：

```
不准许
[0:1 1] 不/d
[1:3 1] 准许/v
不准许张贴广告
[0:1 1] 不/d
[1:3 1] 准许/v
[3:5 1] 张贴/v
[5:7 1] 广告/n
不准许和张三来往
[0:1 1] 不/d
[1:3 1] 准许/v
[3:4 1] 和/c
[4:6 1] 张三/nr
[6:8 1] 来往/v
```

**Comment by gxy0451** [comment]
我试了一下不准许那个例子，如果在hanlp-lucene-plugin这个项目的test中直接运行你的代码是没问题的，结果跟你的一致，但如果在classpath中加入hanlp.properties（properties中只是更改了root属性，指向云盘下载的data文件夹），就会出现问题，不知道是哪个词典导致的。代码版本就是目前最新版本，版本号：bf7750966f9211dc3458f063d102eb42bab5c26d
![qq20170428-224840](https://cloud.githubusercontent.com/assets/5125893/25533957/eb9af8d4-2c64-11e7-8b7b-d316f4c16c00.jpg)

**Comment by hankcs** [comment]
的确，如果要使用14年的大词典的话，请使用版本库中最新的data，已经针对这个问题做出了优化。

**Comment by gxy0451** [comment]
我用的是data-for-1.3.2.zip

**Comment by hankcs** [comment]
我的意思是 git clone https://github.com/hankcs/HanLP.git，或点击https://github.com/hankcs/HanLP/archive/master.zip下载最新的数据，实时更新。
14年人民日报新增了大量词汇，然后质量比98年低一个档次，所以调整得比较频繁。

**Comment by gxy0451** [comment]
我更新了之前clone的hanlp项目，更新后版本号：d37f97c8d54acda7ca1c6a8baae5cf0ebbd6a775，删掉了之前缓存的bin文件，将hanlp.properties中的root指向了克隆下来的data,重新运行上面的代码，效果是这样的
![qq20170428-235745](https://cloud.githubusercontent.com/assets/5125893/25536769/8616dbe0-2c6e-11e7-8026-5d3288e8918c.jpg)
核心词典用CoreNatureDictionary.mini.txt或CoreNatureDictionary.txt结果是一样的。用户词典那个选项没有改动。

**Comment by hankcs** [comment]
在CoreNatureDictionary.ngram.txt中删除如下BiGram即可：
<img width="344" alt="hankcs com 2017-04-28 11 11 47" src="https://cloud.githubusercontent.com/assets/5326890/25537321/90f73e6c-2c03-11e7-8090-c10da36a8bd5.png">

**Comment by gxy0451** [comment]
即使删完了"不准许"这3个字的分词还是不一致的
```
不准许
[0:2 1] 不准/v
[2:3 1] 许/m
不准许张贴广告
[0:1 1] 不/d
[1:3 1] 准许/v
[3:5 1] 张贴/v
[5:7 1] 广告/n
不准许和张三来往
[0:1 1] 不/d
[1:3 1] 准许/v
[3:4 1] 和/c
[4:6 1] 张三/nr
[6:8 1] 来往/v
```

**Comment by hankcs** [comment]
继续删掉 许@末##末 32

**Comment by gxy0451** [comment]
最近麻烦大神了，目前还不知道怎么去优化这个词典，之后会去看下，争取能多帮忙完善。

**Comment by hankcs** [comment]
不客气，BiGram分词的原理很简单，如果两个词的接续出现在CoreNatureDictionary.ngram.txt中，算法会倾向于将这两个词分出来。末##末 代表句子的结束，许@末##末 存在的话，算法倾向于认为“许”应该作为句子的结束。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
