### ISSUE TITLE
请问一下汉字繁简体转换的问题？

### ISSUE THREAD

**Issue by UB1010** [hankcs/HanLP#497]
你好，我最近使用的你的HanLP-1.2.8版本中的汉字繁简体转换。
我发现一个问题，有些繁体到简体的转换，不是按原字转换的，而是换了一个词，这给我带来很大问题。
比如：文字=文本
内容=属性
在你的词典文件TraditionalChinese.txt中可以查到。类似的情况有很多。

请问，这个问题可以通过配置解决吗？可以严格按原字转换吗？

另外，你的转换词典有些遗漏的转换不了，比如：勐戳， 減肥

我想问一下，我可以在TraditionalChinese.txt中添加新的转换词表，但是不知道怎么产生bin文件，不能起作用，可以让用户修改这个转换词典吗？怎么产生bin文件？

谢谢，你的分词工具做的不错。这个问题，希望能一起处理，谢谢。

**Comment by hankcs** [comment]
噢，感谢反馈。
1. 你可以先去了解一下汉语中在字符级别存在“一简对多繁”和“一繁对多简”，在词语级别上存在“简繁分歧词”，在港澳台等地则存在“字词习惯不同”的情况：http://www.hankcs.com/nlp/simplified-traditional-chinese-conversion.html ，再来重新审视这个“简繁转换”这个命题，以及HanLP的设计所在。
1. 如果你觉得按字转换能满足你的要求，可以直接用https://github.com/hankcs/HanLP/blob/37ca334d39f64d3bbe7d6bcf7788a2ba8fbb7b81/src/main/java/com/hankcs/hanlp/dictionary/other/CharTable.java#L105
1. 恕我浅薄，我没有在任何字典、百科中找到“勐戳， 減肥”，它们看上去像是错别字或是火星文？
1. https://github.com/hankcs/HanLP#储存形式

**Comment by UB1010** [comment]
谢谢回复。
一般情况，建议通过配置选项，让用户自己选择，严格按文字转换，还是按语义转换，比如，賓士 = 宾士， 还是 賓士 = 奔驰。
而且，内容=属性  ，我看已经不是一简对多繁的问题了，我认为已经是语义错误的问题了。
同时，另外有一个比较好的工具做简繁体转换，使用率也很高，叫OpenCC，地址：https://github.com/BYVoid/OpenCC
建议你看一下，而且，我是因为详细对比了两个工具的结果，OpenCC做简繁体转换确实比较好，才给你提出问题建议的。
同时，我已经改换了工具，现在是使用OpenCC 了。
最后，“勐戳， 減肥”是我的实际应用案例。Open CC的结果："減肥"-->"减肥"

**Comment by hankcs** [comment]
1. OpenCC的确做得更好，作者的汉语修养更高。我在 http://www.hankcs.com/nlp/simplified-traditional-chinese-conversion.html 也明确提到过，参考了OpenCC，并且使用了OpenCC的简繁映射表。
1. 另外，HanLP不是通过配置实现选项的，而是利用s2tw和s2hk等不同的接口实现不同地区的转换。但对按字转换兴趣不大，虽然包装一下就行了，总归是不推荐的。
1. 麻烦问一下，“内容=属性”好像不是HanLP的输出结果。是港台人士的习惯吗？
1. 最后，对"減肥"来讲，HanLP的结果也是减肥。“勐戳”依然不知道是意思。

当然，OpenCC是个不错的选择！

**Comment by hankcs** [comment]
噢，我猜你可能在用旧版本，比如1.1.5。那就没什么讨论意义了，旧版本还没有向OpenCC看齐。新版本使用了类似的算法与词库，效果应该差不多了。

**Comment by UB1010** [comment]
我反馈的问题全部是我实际使用的结果。我花时间反馈问题也是因为我觉得HanLP做的是不错的。
我使用的是1.2.8版本，有时间我会试一下新版本。
谢谢你的工具。

**Comment by hankcs** [comment]
非常感谢你的反馈，我的意思是旧版本的问题没什么讨论意义。旧版本的确做得不好，感谢批评。
臺灣正體、香港繁體是在1.3以上版本引入的：https://github.com/hankcs/HanLP/releases/tag/v1.3.0 ，也是从这个版本开始学习OpenCC的，跟旧版本的简繁转换已经不是一个水平了。
总之，造成不便望海涵！

**Comment by UB1010** [comment]
TraditionalChinese.txt 是1.2.8版本中data\dictionary\tc 提供的，建议你check一下新版本。

**Comment by hankcs** [comment]
这是最新版本的tc目录，已经发生了本质改变：
<img width="255" alt="hankcs com 2017-04-26 10 13 04" src="https://cloud.githubusercontent.com/assets/5326890/25466325/97b4db7e-2acd-11e7-946c-47bfa816aae8.png">

**Comment by UB1010** [comment]
OK，了解了。谢谢。

**Comment by wenhelinlu** [comment]
作者你好，我用的版本是portable-1.6.4，经过实际运行发现，在繁体转简体时，“猛”会转成“勐”，“富豪”会转成“沃尔沃”。

**Comment by hankcs** [comment]
Hi，简繁词库来自OpenCC项目，可能有些错误，欢迎参与修订。

**Comment by fiveddd** [comment]
我检测了`data/dictionary/tc/t2s.txt`发现有这样一行：
>出租车=的士

这种应该不需要做转换吧？都是简体。

同时还发现一些类似的：
>凶=凶
>出=出
>划=划
>划具=划具
>划出=划出
>划到=划到

`=`号左右两边都是同样的值，是不是可以删除？
