### ISSUE TITLE
关于停用词的问题

### ISSUE THREAD

**Issue by songShiPeng** [hankcs/HanLP#498]
我在stopwords里加了停用词 ‘，’,然后在代码里加了停用词‘近日’，结果都没起作用
`      Segment segment = HanLP.newSegment();

        segment.enablePartOfSpeechTagging(true);
        segment.enableCustomDictionary(true);
        System.out.println(CoreStopWordDictionary.contains("，"));
        CoreStopWordDictionary.add("近日");
        CustomDictionary.insert("位于黄骅经济开发区");
        CustomDictionary.add("位于黄骅经济开发区");
        System.out.println(segment.seg("近日，位于黄骅经济开发区的河北宏泰专用汽车有限公司生产的新型铝合金罐式车。"));`
结果是：[近日, ，, 位于黄骅经济开发区, 的, 河北, 宏泰, 专用汽车, 有限公司, 生产的, 新型, 铝合金, 罐式, 车, 。]

**Comment by wenjiahua** [comment]
我也发现这个问题了，停用词词典里有标点符号，但是标点符号没有过滤掉。

**Comment by wenjiahua** [comment]
你这个问题解决了吗？

**Comment by AnyListen** [comment]
请参考这段代码进行移除
https://github.com/hankcs/HanLP/blob/113119793b0d4ce2c6ec2a6fbca2dc28d213822e/src/main/java/com/hankcs/hanlp/tokenizer/NotionalTokenizer.java#L46

**Comment by AnyListen** [comment]
@wenjiahua 请参考这段代码进行移除
https://github.com/hankcs/HanLP/blob/113119793b0d4ce2c6ec2a6fbca2dc28d213822e/src/main/java/com/hankcs/hanlp/tokenizer/NotionalTokenizer.java#L46

**Comment by wenjiahua** [comment]
你直接用这个分词就可以了，NotionalTokenizer.segment()这个函数可以直接去掉停用词。
