### ISSUE TITLE
Crf分词结合ngram词典不能取得理想结果

### ISSUE THREAD

**Issue by kelciej** [hankcs/HanLP#499]
@hanks, 你好。
关于下列输入
CRFSegment segment = new CRFSegment().;
segment.enableCustomDictionary(true);
		List<Term> seg = segment.seg("哪些药产自上海");

一直出现不理想的分词结果

[哪些/r, 药产/nz, 自/p, 上海/ns]

理想的结果是 [哪些/r, 药/n,产自/v, 上海/ns]

已经按照您在其他issue里面说的修改了核心词典CoreNatureDictionary.mini.txt
其中包含（产自	v	999）新增，（药	n	41	v	1）药这个词是原来就有的
也修改了CoreNatureDictionary.ngram.mini.txt
（药@产自 10000）新增，
并且在自定义词典CustomDictionary.txt中新增（产自 v 999）
删除所有缓存，并且运行，还是出现[哪些/r, 药产/nz, 自/p, 上海/ns]结果

不知道我哪里做的不对，或者缺少了哪些步骤，还请务必告知
非常感谢！
@TylunasLi

**Comment by kelciej** [comment]
版本号是1.3.2，差点忘了

**Comment by kelciej** [comment]
我刚才仔细看了貌似源代码中没有对于crf分词修正的内容。

**Comment by TylunasLi** [comment]
BiGram模型只作用于基于词图的分词方法，在HanLP里面是 Viterbi最短路分词、Dijkstra最短路分词、N-最短路分词三种。
CRF分词采用“由字构词”的策略，本身并没有涉及到Bigram模型，也不能如BiGram类算法一般简单地调整参数，只能重新训练。
请了解相关算法大致原理再来看如何调整。

**Comment by kelciej** [comment]
谢谢你的解答
