### ISSUE TITLE
请问如何用您的工具包实现新词发现功能呢？

### ISSUE THREAD

**Issue by Apeacer** [hankcs/HanLP#50]
您好，看了您的工具包的代码，感觉写的非常好，我非常佩服。可能本人水平差一些，不知道您的工具有没有实现新词发现功能，若实现了怎么用，或如何利用现有功能实现新词发现功能。

**Comment by hankcs** [comment]
你好，

CRF分词可以当成新词发现工具来用，词性标注为null的极有可能是新词，请参考：http://www.hankcs.com/nlp/segment/crf-segmentation-of-the-pure-java-implementation.html#h3-8

专门的新词发现功能是一项未来的开发计划。

**Comment by Apeacer** [comment]
好的，非常感谢！
