### ISSUE TITLE
关于model（模型）在下载的时候百度云实效还是给墙了？

### ISSUE THREAD

**Issue by wankaiss** [hankcs/HanLP#500]
你好：
        我在下载data-1.28-full（大致）的时候，百度云连接失效，请问还有什么路径或者链接吗？我尝试了翻墙去链接还是不可以的。谢谢

**Comment by hankcs** [comment]
噢，1.2.8的确莫名其妙地审核不过。你可以用最新版的，旧版不再维护了。

**Comment by wankaiss** [comment]
好了，我已经下载到最新的了。若是这种审核不通过的能否加密压缩？

**Comment by hankcs** [comment]
是个好主意。1.2.8才搞笑，是先通过了很长一段时间，然后突然不通过的。
