### ISSUE TITLE
发现个分词bug：对“阿里”，“华为”分词结果返回词性为ns（地名）

### ISSUE THREAD

**Issue by 420672771** [hankcs/HanLP#502]
对“阿里”，“华为”分词结果返回词性为ns（地名）

**Comment by hankcs** [comment]
你还别说，阿里的确是个地名：http://baike.baidu.com/item/%E9%98%BF%E9%87%8C%E5%9C%B0%E5%8C%BA

当然华为应该是标错了，感谢指正。
