### ISSUE TITLE
发现个人名分词的bug

### ISSUE THREAD

**Issue by 420672771** [hankcs/HanLP#504]
所有姓冯、于、文的名字分词都是错误的冯会被分为nz（其他专名）；于，会被分为p（介词）；文，会被分为ng（名词性语素）

**Comment by hankcs** [comment]
感谢反馈，稍微挑了一下

System.out.println(HanLP.segment(
                "冯丽丽和于丽丽以及文丽丽"
        ));

[冯丽丽/nr, 和/cc, 于丽丽/nr, 以及/cc, 文丽丽/nr]

**Comment by wangpeng138375** [comment]
"A"标签怎么会出现转移到“B”的情况，不是应该转移到“A”,"K","U"等标签，没有“B”才对吧？

**Comment by hankcs** [comment]
这个数值是后期手工加上去的，作为临时措施。因为 始##始 是A标签，如果A不能到B的话，则句子开头的人名不会被识别。

当然这个临时措施很丑陋，我会想想其他办法，欢迎提出其他修改意见。

**Comment by TylunasLi** [comment]
发现了"始##始"错误的原因: 
NRDictionaryMaker::roleTag
`wordLinkedList.addFirst(new Word(Predefine.TAG_BIGIN, "S"));`

PersonRecognition::roleObserve
`EnumItem<NR> nrEnumItem = PersonDictionary.dictionary.get(vertex.realWord);`

"始##始"标记的realWord不是"始##始"
