### ISSUE TITLE
分词问题

### ISSUE THREAD

**Issue by iwaller** [hankcs/HanLP#506]
**问题**
对句子"我想提点钱出来"进行分词，
得到结果: [我/rr, 想/v, 提/v, 点钱/nz, 出来/vf]，分词中“点钱”切分错误？

**版本**
- 程序版本号：hanlp-portable-1.2.7
- 数据版本号：data-for-1.3.2.zip

**触发代码**
```java
HanLP.segment("我想提点钱出来");
```
**代码输出**
``` 
[我/rr, 想/v, 提/v, 点钱/nz, 出来/vf]
```

**尝试**
分词结果有问题，把`点钱`作为一个词切分出来，而不是切分为`提点/v 钱/n`。
我在词库CoreNatureDictionary.txt中发现 “点钱 nz 110”，而没有“提点”词，所以我用CustomDictionary将“提点”加入，但是还是没有效果，麻烦帮忙看一下，非常感谢。

**Comment by hankcs** [comment]
感谢指正，人民日报语料库的标准认为“点钱”是一个词，里面存在大量例句：

```
消费者/n 愿意/v 多/a 花/n 点钱/nz
都/d 出/vf 点钱/nz 
```

但HanLP灵活的模型机制为用户提供了完全的控制权，你可以在
data/dictionary/CoreNatureDictionary.ngram.txt 中加一句

```
提点@钱 10
```

**Comment by iwaller** [comment]
多谢，我尝试了， 可以实现。
但由于“提点”在词典中没有出现，所有需要在data\dictionary\CoreNatureDictionary.txt中添加词“提点”才可，还有就是加入时，需要将频率调大点才行，我测试的是“提点 v 10000”才可以切分出来。
