### ISSUE TITLE
中文分词bug

### ISSUE THREAD

**Issue by FayuanLi** [hankcs/HanLP#507]
System.out.println(NLPTokenizer.segment("花了38元人民币"));
		System.out.println(HanLP.segment("花了38元人民币"));
[花/n, 了/ule, 38/m, 元/q, 人民币/n]
[花/n, 了/ule, 38/m, 元/q, 人民币/n]

**Comment by hankcs** [comment]
请问bug在哪里？
如果你觉得数量词应该合并，你完全可以

```
        StandardTokenizer.SEGMENT.enableNumberQuantifierRecognize(true);
        System.out.println(HanLP.segment("花了38元人民币"));
```

[花/n, 了/ule, 38元/mq, 人民币/n]

**Comment by FayuanLi** [comment]
不好意思我昨天刚开始用hanlp  十分感谢开源这么好的项目
花了38元人民币
花了38天
买了一块表   
这个“花”不知道是不是动词   即使不是动词那也不是名词吧   我以为这里的花和买是一样的   不知道是否可以通过在词典里面增加词性来改变结果呢  不知道在有名词和动词的情况下会做出正确选择   还有最近想要做一个句子相似性的功能  如果hanlp可以增加这种功能就好了   比方说  “你叫什么名字”和“你的名字叫什么”这种就可以当成是一样意思的句子了   就是这种基于意思一样的句子

**Comment by hankcs** [comment]
1. 词性不准确属于词性标注的问题。在人民日报2014中“花”全部被标注为n，那什么模型都无力回天了。但98年的语料标注是准确的，你可以使用mini模型
1. 我们恰好在讨论：https://github.com/hankcs/HanLP/issues/505#issuecomment-297569962
2. 你可以了解一下LSA，可能有用
