### ISSUE TITLE
提取关键词、短语

### ISSUE THREAD

**Issue by lizhitao0923** [hankcs/HanLP#51]
你好，HanLP提取新闻的关键词或短语的时候效果总不尽人意，通常提取出来的词不是特别能表达出新闻关键关注点，有啥好的解决方案吗？

**Comment by hankcs** [comment]
0. TextRank算法的确只有这个程度的效果，任何算法肯定都无法做到跟人一样。
0. 单文档关键字算法无法利用背景知识，可能需要探索补充外部知识库，比如某个词在互联网的丰度，新鲜程度等等。
0. 如果你发现了更好用的算法\开源项目，欢迎向我推荐。

**Comment by zhengzhuangjie** [comment]
请问一下，怎么样再提取文章概要时，尽量把带数字的语句提取出来？
