### ISSUE TITLE
核心字典中“每xx”的词性是不是有误？

### ISSUE THREAD

**Issue by hx78** [hankcs/HanLP#514]
版本1.3.2
毎	nz	10  // 其他专名？
每	rz	4131 // 指示代词？
每一年	nz	31 //应该为t?
每一方	nz	1
每一次	d	188
每一步	d	44
每七年	nz	1 //应该为t?
每个	r	2135   //应该为m?
每五年	nz	4 //应该为t?
每亩	r	117 //应该为m?
每人	r	904
每件	d	61
每份	r	17 //应该为m?
每位	r	201 
每况愈下	vl	22
每包	nz	16 //应该为m?
每匹	nz	2 //应该为m?
每十年	nz	5 //应该为t?
每半年	nz	24 //应该为t?
每吨	q	123 //应该为m?
每周	r	603 //应该为t?
每周三	nz	21 //应该为t?
每四年	nz	10  //应该为t?
每回	nz	8
每场	r	45
每块	r	16
每夜	nz	14 //应该为t?
每天	r	5072 //应该为t?
每头	nz	15
每套	r	23
每家	r	117
每局	r	2
每层	d	27
每年	r	3400 //应该为t?
每张	r	116
每当	p	185
每户	r	120
每批	nz	7
每排	nz	17
每支	r	16
每斤	nz	141
每日	r	1636 //应该为t?
每旬	nz	1
每时每刻	bl	15
每星期	d	17
每晚	r	248 //应该为t?
每月	r	1329 //应该为t?
每期	r	36
每条	d	54
每样	nz	5
每桶	r	14
每次	r	1501
每段路	nz	1
每每	d	59
每片	d	17
...

**Comment by hankcs** [comment]
是的，感谢指出。2014语料的问题实在不少，98年的好一些。欢迎fork一份，将你的补丁push上来。

**Comment by hx78** [comment]
词性不好标注，按自己理解修改了一些，仅针对“每xx" 
[修正核心字典“每xx”的词性](https://github.com/hx78/HanLP/commit/b9678b3b0a4bcbd39154b20bbac8eb48ec0fe9b0)

**Comment by hankcs** [comment]
太棒了，你能发个pull request给我吗？谢谢

**Comment by hx78** [comment]
@hankcs 已经pull request
