### ISSUE TITLE
等效词串都有哪些

### ISSUE THREAD

**Issue by hx78** [hankcs/HanLP#515]
[Bigram分词中的等效词串](http://www.hankcs.com/nlp/segment/bigram-word-equivalent-word-in-string.html)
你的文章列举了一些等效词性，请问除了下面这些，还有哪些呢?
未##地, 始##始, 未##它, 未##团, 未##数, 未##专, 未##时, 未##串, 末##末, 未##人

这里的未有什么含义吗？未登录词？这样会不会影响到已经登录的字词呢？

eg:移除每天晚上二十一点的日程
在加入”移除  v 100"后，移和除还是分开的

> 版本1.3.2，NS分词

************START**************
打印词图：========按终点打印========
to:  1, from:  0, weight:04.60, word:始##始@移
to:  2, from:  0, weight:04.60, word:始##始@移除
to:  3, from:  1, weight:02.31, word:移@除
to:  4, from:  2, weight:11.25, word:移除@每
to:  4, from:  3, weight:05.70, word:除@每
to:  5, from:  2, weight:11.25, word:移除@未##时
to:  5, from:  3, weight:03.40, word:除@未##时
to:  6, from:  4, weight:10.58, word:每@天
to:  7, from:  5, weight:04.76, word:未##时@晚
to:  7, from:  6, weight:10.04, word:天@晚
to:  8, from:  5, weight:02.52, word:未##时@未##时
to:  8, from:  6, weight:04.07, word:天@未##时
to:  9, from:  7, weight:10.68, word:晚@上
to: 10, from:  8, weight:02.52, word:未##时@未##时
to: 10, from:  9, weight:04.09, word:上@未##时
to: 14, from: 11, weight:05.57, word:未##时@点
to: 15, from: 10, weight:03.04, word:未##时@的
to: 15, from: 12, weight:03.04, word:未##时@的
to: 15, from: 13, weight:03.04, word:未##时@的
to: 15, from: 14, weight:02.98, word:点@的
to: 16, from: 15, weight:05.62, word:的@日
to: 17, from: 15, weight:05.67, word:的@日程
to: 18, from: 16, weight:10.10, word:日@程
to: 19, from: 17, weight:03.52, word:日程@末##末
to: 19, from: 18, weight:06.15, word:程@末##末

粗分结果[移/v, 除/p, 每天/t, 晚上/t, 二十一点/t, 的/ude1, 日程/n]

**Comment by hankcs** [comment]
0. 对这个问题来讲，你可以直接删除 移@除 。我实在想不出任何上下文中需要把移除分为移+除的情况，估计是语料问题。比如在98年语料中，根本没有 移@除 这个BiGram。
0. “未”的确代表未登录词，所有确定为该词性的词语都会被compile为等效词串，以平滑数据稀疏的问题。至于具体都有哪些，请参考 https://github.com/hankcs/HanLP/blob/master/src/main/java/com/hankcs/hanlp/utility/Predefine.java#L92 。
0. 私以为，HanLP虽然写得不够好，但文档写得还算非常全面的

**Comment by hx78** [comment]
确实很全面，不好意思，代码没有看得很仔细
