### ISSUE TITLE
在C#中使用自定义词典，新建Nature失败

### ISSUE THREAD

**Issue by sefira** [hankcs/HanLP#516]
当前最新版本号是：v1.3.2
我使用的版本是：v1.3.2

## 我的问题

我意图在C#中使用HanLP，按照教程[在CSharp中调用HanLP](http://www.hankcs.com/nlp/call-hanlp-in-csharp.html)我已经成功使用iKVM打包，并在C#运行用例。不过我想新建用户字典并新建Nature，以满足我识别自定义类型实体的要求，如新建名人类型：nrmy。

在Java中通过修改hanlp.properties可以添加新的类型nrmy，在写代码的时候添加Nature.create("nrmy")也没问题。以上两步做完之后Java代码可以识别新添加的nrmy实体。

不过C#代码会显示无法从hanlp.properties中读取新的类型nrmy。新的类型完全失效。

## 复现问题
```Java
        static void Main(string[] args)
        {
            java.lang.System.getProperties().setProperty("java.class.path", "mypath");
            Nature.create("nrmy");
            CustomDictionary.insert("白富美", "nrmy 1024");
            Console.WriteLine(HanLP.segment("欢迎在CSharp中调用HanLP的API"));
            Console.ReadKey();
        }
```

## 报错：
WARNING: 已激活自定义词性功能,由于采用了反射技术,用户需对本地环境的兼容性和稳定性负责!
如果用户代码X.java中有switch(nature)语句,需要调用CustomNatureUtility.registerSwitchClass(X.class)注册X这个类

Unhandled Exception: java.lang.IllegalArgumentException: Could not set the enum ---> java.lang.IllegalAccessException: Can not set static final [Lcom.hankcs.hanlp.corpus.tag.Nature; field com.hankcs.hanlp.corpus.tag.Nature.$VALUES to [Lcom.hankcs.hanlp.corpus.tag.Nature;
   at IKVM.NativeCode.sun.reflect.ReflectionFactory.FieldAccessorImplBase.FieldAccessor`1.lazySet(Object obj, T value)
   at IKVM.NativeCode.sun.reflect.ReflectionFactory.FieldAccessorImplBase.FieldAccessor`1.lazySet(Object obj, T value, FieldAccessor`1 acc)
   at IKVM.NativeCode.sun.reflect.ReflectionFactory.FieldAccessorImplBase.ObjectField.set(Object obj, Object value)
   at com.hankcs.hanlp.corpus.util.ReflectionHelper.setStaticFinalField(Field field, Object value)
   at com.hankcs.hanlp.corpus.util.EnumBuster.addByValue(Enum e)
   --- End of inner exception stack trace ---
   at com.hankcs.hanlp.corpus.util.EnumBuster.addByValue(Enum e)
   at com.hankcs.hanlp.corpus.util.CustomNatureUtility.addNature(String name)
   at com.hankcs.hanlp.corpus.tag.Nature.create(String name)
   at HanLPSharp.Program.Main(String[] args) in mypath

**Comment by hankcs** [comment]
感谢反馈，至少让大家明确了目前C#中暂不支持自定义词性这个事实。

目前对C#的“政策”与对JDK的一样：https://github.com/hankcs/HanLP/wiki/FAQ#%E5%8A%A0%E5%85%A5%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%8D%E6%80%A7%E5%90%8E%E5%8F%91%E7%94%9Farrayindexoutofboundsexception

我并不是C#爱好者，所以不清楚IKVM如何实现反射。不过我提议C#用户参考http://www.hankcs.com/program/java/enum-java-examples-of-dynamic-modification.html ，尝试合力出一个C#的补丁。上游版本库会很乐意接受你们的工作，谢谢！

**Comment by hankcs** [comment]
1. 抛砖引玉一下，$VALUES是JDK中enum类型的value字段名称
1. 也许IKVM中不叫这个名字，是否可以向IKVM社区求助？

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
