### ISSUE TITLE
字母数字混合的编号分词错误

### ISSUE THREAD

**Issue by zxkane** [hankcs/HanLP#517]
HanLP版本`1.3.2`

测试用例如下，
```java
@Test public void wordSegment2() {
        HanLP.Config.enableDebug();
        assertThat(new NShortSegment().enableCustomDictionary(true).seg("1000000438L01").stream().map(w -> w.word))
                .containsExactly("1000000438L01");
    }
```

HanLP按词性把编号拆分了。如果想保留完整编号，应该如何设置？

> 打印词图：========按终点打印========
> to:  1, from:  0, weight:04.56, word:始##始@未##数
> to:  2, from:  1, weight:07.60, word:未##数@未##串
> to:  3, from:  2, weight:07.06, word:未##串@未##数
> to:  4, from:  3, weight:03.69, word:未##数@末##末
> 
> 粗分结果[1000000438/m, L/nx, 01/m]

**Comment by hankcs** [comment]
修改所有英文字母类型即可。

```
        CharType.type['L'] = CharType.CT_NUM;
        System.out.println(HanLP.segment("1000000438L01"));
```

**Comment by zxkane** [comment]
@hankcs , 编号里出现任何字母都可能。

我按类似方法修改数字为Letter,

```java
IntStream.rangeClosed(0, 9).forEach(n -> {
            CharType.type[String.valueOf(n).charAt(0)] = CharType.CT_LETTER;
        });
```

数字跟字母的词性仍然不同。
[1000000438/n, L/nx, 01/n]

**Comment by hankcs** [comment]
需要在调用分词方法之前，即任何segment方法之前，调用你的修改代码。

**Comment by zxkane** [comment]
我就是在分词之前修改的。如果把数字都改成letter,分词结果还是断开了。按你建议的把字母都改为数字结果是期望的。

2017年5月5日 11:07，"hankcs" <notifications@github.com>写道：

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。

**Comment by oschina** [comment]
> CharType.type[String.valueOf(n).charAt(0)] = CharType.type['L']

`
        String text = "1000000438L01";
        CharType.type['L'] = CharType.type[String.valueOf(text).charAt(0)];
        System.out.println(new NShortSegment().enableCustomDictionary(true).seg(text));
`

结果还是：
[1000000438/m, l/nx, 01/m]

请教一下，怎么不起作用啊

**Comment by oschina** [comment]
另外，如果这个字符串中的字母数字是一种混编的状态，而且不一定是什么字符，怎么能不让它们被切分呢？
