### ISSUE TITLE
人名和組織機構識別經常包含標點的問題

### ISSUE THREAD

**Issue by Tony-Wang** [hankcs/HanLP#52]
例如机构识别出：“美國，中華隊”
标点问题需要一个解决方案，CommonAhoCorasickSegmentUtil会把标点作为未知语素和前后的语素合并，显然不太合理。标点分词的优先级应该提高。

**Comment by hankcs** [comment]
0. 麻烦提供一段触发代码。
0. 有更简单的方法，那就是让标点成为已知语素，也就是在词典中加入这个标点（不知道是什么标点没有收录？）

**Comment by Tony-Wang** [comment]
"「旗津黑沙玩藝節」是高雄首度舉辦大型專業沙雕展覽活動，以「高雄FUN IN中」為主題，結合高雄取景電影、觀光旅遊、海陸空交通等港都魅力，製作16座創意主題沙雕，包括象徵高雄起飛的「高飛」及再出發的堅強志氣「熊志」、和取材自電影「痞子英雄」、「愛琳娜」和「愛的麵包魂」等創作，每一件作品都融入高雄文藝氣息或景點，尤其是沙雕區入口的高捷少女「小穹」的作品，更吸引大批遊客合影拍照。"

分词出："活動，以「高雄"，”主題，結合高雄“为 nt

**Comment by hankcs** [comment]
这个问题与CommonAhoCorasickSegmentUtil无关，问题出在机构名HMM训练的时候，将所有的标点符号都作为W标签引入模型了，事实上不是所有的标点符号在所有时候都能成为机构名的一部分的。

暂时的解决方案是删掉HMM中的标点的W标签。

**Comment by Tony-Wang** [comment]
"基隆市長林右昌對義消人員長期協助消防救災工作"
[基隆市/ns, 長林/ns, 右/f, 昌對義/nr, 消/v, 人員/n, 長朞/d, 協助/v, 消防/b, 捄烖/vn, 工作/vn]
把“义消人员”加到自定义词库
[基隆市/ns, 長林/ns, 右/f, 昌對/nr, 義消人員/n, 長朞/d, 協助/v, 消防/b, 捄烖/vn, 工作/vn]
在CoreNatureDictionary.ngram.txt添加“基隆@市长 1”没有变化。
这个怎么解决？

**Comment by Tony-Wang** [comment]
```
"基隆市長林右昌對義消人員長期協助消防救災工作"
[基隆市/ns, 長林/ns, 右/f, 昌對義/nr, 消/v, 人員/n, 長朞/d, 協助/v, 消防/b, 捄烖/vn, 工作/vn]
```
把“义消人员”加到自定义词库
```
[基隆市/ns, 長林/ns, 右/f, 昌對/nr, 義消人員/n, 長朞/d, 協助/v, 消防/b, 捄烖/vn, 工作/vn]
```
在CoreNatureDictionary.ngram.txt添加“基隆@市长 1”没有变化。
这个怎么解决？

**Comment by hankcs** [comment]
你没有贴调用代码，我只能猜。

我猜你用错了分词器。

        HanLP.Config.enableDebug();
        String text = "市長林右昌對義消人員長期協助消防救災工作";
        System.out.println(TraditionalChineseTokenizer.segment(text));

[市長/n, 林右昌/nr, 對/p, 義/ng, 消/v, 人員/n, 長朞/d, 協助/v, 消防/b, 捄烖/vn, 工作/vn]

**Comment by hankcs** [comment]
我们一起来看这个问题

        HanLP.Config.enableDebug();
        Segment segment = new DijkstraSegment();
        System.out.println(segment.seg(
                "基隆市长林右昌对义消人员长期协助消防救灾工作"
        ));

粗分词图：========按终点打印========
to:  1, from:  0, weight:04.60, word:始##始@基
to:  2, from:  0, weight:03.41, word:始##始@未##地
to:  3, from:  0, weight:03.41, word:始##始@未##地
to:  4, from:  1, weight:11.46, word:基@隆
to:  5, from:  2, weight:03.32, word:未##地@市
to:  5, from:  4, weight:11.54, word:隆@市
to:  6, from:  2, weight:03.41, word:未##地@市长
to:  6, from:  4, weight:11.54, word:隆@市长
to:  7, from:  3, weight:02.31, word:未##地@长
to:  7, from:  5, weight:09.88, word:市@长
to:  8, from:  6, weight:11.08, word:市长@林
to:  8, from:  7, weight:05.63, word:长@林
to:  9, from:  8, weight:11.02, word:林@右
to: 10, from:  9, weight:11.31, word:右@昌
to: 11, from: 10, weight:04.23, word:昌@对
to: 12, from: 11, weight:08.28, word:对@义
to: 13, from: 12, weight:04.74, word:义@消
to: 14, from: 13, weight:11.52, word:消@人
to: 15, from: 13, weight:03.01, word:消@人员
to: 16, from: 14, weight:08.30, word:人@员
to: 17, from: 15, weight:09.30, word:人员@长
to: 17, from: 16, weight:11.32, word:员@长
to: 18, from: 15, weight:07.47, word:人员@长期
to: 18, from: 16, weight:11.32, word:员@长期
to: 19, from: 17, weight:10.38, word:长@期
to: 20, from: 18, weight:10.84, word:长期@协
to: 20, from: 19, weight:10.79, word:期@协
to: 21, from: 18, weight:10.84, word:长期@协助
to: 21, from: 19, weight:10.79, word:期@协助
to: 22, from: 20, weight:11.48, word:协@助
to: 23, from: 21, weight:11.30, word:协助@消
to: 23, from: 22, weight:11.40, word:助@消
to: 24, from: 21, weight:06.13, word:协助@消防
to: 24, from: 22, weight:11.40, word:助@消防
to: 25, from: 23, weight:11.52, word:消@防
to: 26, from: 24, weight:10.89, word:消防@救
to: 26, from: 25, weight:11.12, word:防@救
to: 27, from: 24, weight:10.89, word:消防@救灾
to: 27, from: 25, weight:11.12, word:防@救灾
to: 28, from: 26, weight:11.26, word:救@灾
to: 29, from: 27, weight:11.54, word:救灾@工
to: 29, from: 28, weight:11.53, word:灾@工
to: 30, from: 27, weight:01.11, word:救灾@工作
to: 30, from: 28, weight:11.53, word:灾@工作
to: 31, from: 29, weight:11.27, word:工@作
to: 32, from: 30, weight:04.86, word:工作@末##末
to: 32, from: 31, weight:04.80, word:作@末##末

粗分结果[基隆市/ns, 长/a, 林/ng, 右/f, 昌/ag, 对/p, 义/ng, 消/v, 人员/n, 长期/d, 协助/v, 消防/b, 救灾/vn, 工作/vn]

**Comment by hankcs** [comment]
基隆被转义为 未##地 ，所以这么改解决不了问题。

长林是data/dictionary/custom/全国地名大全.txt中引入的一个地名，既然引起问题，那么就删掉吧。

人名识别是在粗分的基础上进行的，所以无法在粗分的时候就知道后面有人名。

**Comment by hankcs** [comment]
至少目前解决了基隆市长这个问题：https://github.com/hankcs/HanLP/commit/7374ea3bba7336e82e899a429107e58e4f890630

后面再看看有人名的情况如何处理。

**Comment by hankcs** [comment]
曾经在很早的版本里面，我也将原子分词的词图作为人名识别的基础，但是这么做会降低人名识别的准确率，也不符合论文的标准做法。

**Comment by hankcs** [comment]
我看到在98年的语料中是：
信息:    市长 frequency:   109, 市长@林 nTwoWordsFreq:  0, weight:11.57
2015-9-1 20:50:32 com.hankcs.hanlp.utility.MathTools calculateWeight
信息:     长 frequency:   315, 长@林 nTwoWordsFreq:  0, weight:11.48

但是14年语料：
信息:    市长 frequency:  1592, 市长@林 nTwoWordsFreq:  0, weight:11.08
2015-9-1 20:51:22 com.hankcs.hanlp.utility.MathTools calculateWeight
信息:     长 frequency:  5550, 长@林 nTwoWordsFreq:  0, weight:10.38

市长的词频与长的词频之比由1/3下降到1/5，导致市长很不占优势。也许是语言的变化，也许是语料错误太多或者分得过细。

那么就有如下的解决方案：
0. 使用98年的模型，将14年的词典挂载为用户词典。
0. 手工降低长的词频
0. 手工增加市长的词频
0. 手工加入市长@林 1

目前我采用了第3种办法。

        CustomDictionary.insert("义消人员");
        String text = "基隆市長林右昌對義消人員長期協助消防救災工作";
        System.out.println(TraditionalChineseTokenizer.segment(text));

[基隆/ns, 市長/n, 林右昌/nr, 對/p, 義消人員/nz, 長朞/d, 協助/v, 消防/b, 捄烖/vn, 工作/vn]

**Comment by Tony-Wang** [comment]
```
签约仪式前，秦光荣、李纪恒、仇和、王春桂等一同会见了参加签约的企业家。
```
这里的“王春桂”被识别为 王春/ns 桂/b，原因是因为自定义字典里的全国地名有“王春”，目前只能在删掉字典项吗？如果要解决，是不是要引入另外一层HMM？

**Comment by hankcs** [comment]
这个词典里面有很多噪音：

黄建
黄思娟
黄文平
周建丽
周建军
周建婷
周建平
周建明
周建毅
周建玲
周建琴
周建鹏
周徐
周方
周明兴
周映梅
周映武
周映盛
周映鑫
周映青
周春燕
周智伟
周机

现在已经被过滤掉了。

并不需要再加一层HMM，因为用户词典只是在原模型上打补丁，优先级不应超过模型。本来我准备在代码里将基于用户词典的合并移动到最后，但是考虑到机构名识别中可能会用到部分用户词典中的机构名后缀等，所以没有。

**Comment by Tony-Wang** [comment]
```
王春是个美丽的地方，住着一个美丽的姑娘叫王春。
```
我的意思是同保留识别```王春```的地名与人名识别能力。

**Comment by hankcs** [comment]
那么这应该属于词性标注负责的工作，然而目前只有复杂度大于5（王春/nr, 是/vshi, 个/q, 美丽/a, 的/ude1, 地方/n，地方到王春的距离是5）的模型，或者人工规则才可能辨识它。考虑到成本很高，所以不太现实。
