### ISSUE TITLE
发现个bug

### ISSUE THREAD

**Issue by luoyexuge** [hankcs/HanLP#520]
太差劲了!花了几百块钱什么毛病都没看出来！各种套路你付钱给狗狗看病结果屁都看不出来！想给狗狗看病的我劝你们千万不要去那家医院！妈的坑的一批！祝帮我家狗狗看病的那个戴眼镜的胖子全家爆炸.md

对上面这段文本进行分词看看，以md为结尾的会报错

**Comment by hankcs** [comment]
[太/d, 差劲/a, 了/ule, !/w, 花/n, 了/ule, 几/d, 百/m, 块钱/q, 什么/ry, 毛病/n, 都/d, 没看/v, 出来/vf, ！/w, 各种/rz, 套路/n, 你/rr, 付钱/v, 给/p, 狗狗/n, 看病/vi, 结果/n, 屁/n, 都/d, 看不出来/v, ！/w, 想/v, 给/p, 狗狗/n, 看病/vi, 的/ude1, 我/rr, 劝/v, 你们/rr, 千万/m, 不要/d, 去/vf, 那家/r, 医院/nis, ！/w, 妈/n, 的/ude1, 坑/n, 的/ude1, 一/m, 批/q, ！/w, 祝帮/nr, 我家/n, 狗狗/n, 看病/vi, 的/ude1, 那个/rz, 戴眼镜/nz, 的/ude1, 胖子/n, 全家/n, 爆炸/vn, ./w, md/nx]

**Comment by 420672771** [comment]
测试了一下，没毛病啊，你报了什么错嘛

**Comment by luoyexuge** [comment]
太感谢你你了，还发邮件过来，我找到原因了，我是自定义词汇中有md ，如果用URL 分词的话会报错，不信你可以试试




发自网易邮箱大师
在2017年05月05日 14:34，420672771 写道：

测试了一下，没毛病啊，你报了什么错嘛

**Comment by hankcs** [comment]
```
    public void test() throws Exception
    {
        CustomDictionary.add("md", "n 1");
        System.out.println(URLTokenizer.segment("太差劲了!花了几百块钱什么毛病都没看出来！各种套路你付钱给狗狗看病结果屁都看不出来！想给狗狗看病的我劝你们千万不要去那家医院！妈的坑的一批！祝帮我家狗狗看病的那个戴眼镜的胖子全家爆炸.md"));
    }
```

[太/d, 差劲/a, 了/ule, !/w, 花/n, 了/ule, 几/d, 百/m, 块钱/q, 什么/ry, 毛病/n, 都/d, 没看/v, 出来/vf, ！/w, 各种/rz, 套路/n, 你/rr, 付钱/v, 给/p, 狗狗/n, 看病/vi, 结果/n, 屁/n, 都/d, 看不出来/v, ！/w, 想/v, 给/p, 狗狗/n, 看病/vi, 的/ude1, 我/rr, 劝/v, 你们/rr, 千万/m, 不要/d, 去/vf, 那家/r, 医院/nis, ！/w, 妈/n, 的/ude1, 坑/n, 的/ude1, 一/m, 批/q, ！/w, 祝/v, 帮/v, 我家/n, 狗狗/n, 看病/vi, 的/ude1, 那个/rz, 戴眼镜/nz, 的/ude1, 胖子/n, 全家/n, 爆炸/vn, ./w, md/n]

**Comment by hankcs** [comment]
由于未提供足够信息，所以只能关闭这个issue。欢迎参考[《如何提问》](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，重新提一个友好的issue。
