### ISSUE TITLE
关于层叠HMM中文实体识别的过程

### ISSUE THREAD

**Issue by yuanlisky** [hankcs/HanLP#521]
hankcs你好！
我在用python做中文实体识别的分词器，想请教一个问题，你的层叠HMM中文实体识别中，不同的实体识别之间是如何传递的。我的策略是先进行人名识别，将结果传递，再进行地名识别，再将结果传递，最后进行机构名识别。但是当多个实体识别同时开启时，会出现一点问题。
比如：
`s = '南翔向宁夏固原市彭阳县红河镇黑牛沟村捐赠了挖掘机'`

当只开启地名识别时，可以正确分词：
`['南翔', '向', '宁夏', '固原市', '彭阳县', '红河镇', '黑牛沟村', '捐赠', '了', '挖掘机']`

但是当我同时开启人名识别和地名识别时，分词结果就不太好了。
人名识别结果：
 `['南翔', '向', '宁夏', '固原市', '彭阳县', '红河镇', '黑', '牛沟村', '捐赠', '了', '挖掘机']`

将结果作为传递给地名识别，结果不能正确分出`'黑牛沟村'`
地名识别结果：
 `['南翔', '向', '宁夏', '固原市', '彭阳县', '红河镇', '黑', '牛沟村', '捐赠', '了', '挖掘机']`

我用HanLP试了下，发现，当只开启人名识别时，和我错误的结果一致：
`[南翔/ns, 向/p, 宁夏/ns, 固原市/ns, 彭阳县/ns, 红河镇/ns, 黑/a, 牛沟村/nr, 捐赠/v, 了/ule, 挖掘机/n]`

但是同时开启人名和地名识别，则可以得到正确的结果：
`[南翔/ns, 向/p, 宁夏/ns, 固原市/ns, 彭阳县/ns, 红河镇/ns, 黑牛沟村/ns, 捐赠/v, 了/ule, 挖掘机/n]`

我想请教下，当同时开启了人名和地名识别时，你是如何处理的。

**Comment by hankcs** [comment]
千言万语，都不如代码详细，请参考：https://github.com/hankcs/HanLP/blob/master/src/main/java/com/hankcs/hanlp/seg/Viterbi/ViterbiSegment.java#L72

**Comment by yuanlisky** [comment]
嗯。单步了一下整个识别过程，基本有眉目了，但是又有新的问题
为什么在人名识别中`"始##始"`标签是[  A 22202445 ] 而不是字典中的[  S 1163553 ]？
`粗分结果[秦光荣/nr, 、/w, 李纪恒/nr, 、/w, 仇/n, 和/cc, 等/udeng, 一同/d, 会见/v, 了/ule, 参加/v, 签约/vi, 的/ude1, 企业家/nnt]`
`人名角色观察：[  A 22202445 ][秦光荣 A 22202445 ][、 M 19857 L 5234 K 4094 ][李纪恒 A 22202445 ][、 M 19857 L 5234 K 4094 ][仇 B 86 D 2 E 1 ][和 M 15401 L 2868 K 2281 D 538 C 164 E 34 ][等 L 3948 K 39 M 15 ][一同 L 66 K 6 ][会见 L 63 K 12 M 3 ][了 K 2796 L 202 M 1 ][参加 L 412 K 22 M 1 ][签约 L 10 K 7 ][的 L 15411 K 11354 M 96 C 1 ][企业家 K 21 ][  A 22202445 ]`
`人名角色标注：[ /A ,秦光荣/A ,、/K ,李纪恒/A ,、/K ,仇/B ,和/C ,等/L ,一同/K ,会见/L ,了/K ,参加/L ,签约/K ,的/L ,企业家/K , /A]`

**Comment by hankcs** [comment]
- 因为是按照https://github.com/hankcs/HanLP/blob/master/src/main/java/com/hankcs/hanlp/recognition/nr/PersonRecognition.java#L85来查的
- 后来还有人提出https://github.com/hankcs/HanLP/issues/504#issuecomment-299857556 ，于是硬编码为A和K。
- 可能按照转义词串来查更好，我再想想。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
