### ISSUE TITLE
发现TextUtility.isAllSingleByte的bug，不知道分词过程会调用吗

### ISSUE THREAD

**Issue by junphine** [hankcs/HanLP#526]
while (i < len && b[i] < 128)
            {
                i++;
            }

----------------

b[i] < 128 应该改成 b[i] >0.

byte的取值范围是-128到127 和char不一样

还有我觉得应该没必要转换成gbk，直接用charAt(i)是否小于128即可判断。

**Comment by hankcs** [comment]
感谢指出

1. 该方法仅在NShortSegment中间接调用，移植自SharpICTCLAS。
1. 已经修复了

如果还有问题，欢迎重开issue。
