### ISSUE TITLE
需要怎么处理不去加载内部的角色组和列表

### ISSUE THREAD

**Issue by moshangshaoguang** [hankcs/HanLP#529]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕

## 版本号

当前最新版本号是：portable-1.3.3
我使用的版本是：portable-1.3.2

## 我的问题
 trie = new AhoCorasickDoubleArrayTrie<String>();
        TreeMap<String, String> patternMap = new TreeMap<String, String>();
        addKeyword(patternMap, "CCCCCCCCD");
        addKeyword(patternMap, "CCCCCCCD");
        addKeyword(patternMap, "CCCCCCD");
        addKeyword(patternMap, "CCCCCCGD");
        addKeyword(patternMap, "CCCCCCICCCCD");
        addKeyword(patternMap, "CCCCCCPD");
        addKeyword(patternMap, "CCCCCD");
        addKeyword(patternMap, "CCCCCDD");
需要怎么处理才能避开记载你们内部的这个角色标注列表，我有自己的角色标注列表。
机构名角色观察：[  S 1169909 ][沈阳 G 97524 ][硕 P 7 ][润 C 116 ][机械电子 F 1000 ][设备 C 273 B 2 ][有限公司 K 1000 D 1000 ][  B 8425 ]
机构名角色标注：[ /S ,沈阳/G ,硕/P ,润/C ,机械电子/F ,设备/C ,有限公司/D , /S]
识别出机构名：机械电子设备有限公司 FCD
识别出机构名：润机械电子设备有限公司 CFCD
识别出机构名：设备有限公司 CD
###期望输出
机械电子设备有限公司 FCD
输出这个结果的原因是我的列表中不存在C开头的角色标注组合
### 实际输出
[沈阳/ns, 硕/ag, 润机械电子设备有限公司/nt]   注意第二个  润机械电子设备有限公司 CFCD

每次调用都会默认记载内部的角色标注列表

**Comment by hankcs** [comment]
- com.hankcs.hanlp.dictionary.nt.OrganizationDictionary#trie 储存了所有的模式串，是public的
- 所以只需要用你的Map重新build一次就行了

**Comment by moshangshaoguang** [comment]
谢谢指导，已解决

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
