### ISSUE TITLE
我是觉得自定义词典优先级应该大于核心词典.

### ISSUE THREAD

**Issue by ahkimkoo** [hankcs/HanLP#53]
我是觉得自定义词典优先级应该大于核心词典, 或者说有一个选项可以设置优先级. 像一些行业的词汇, 通过人民日报这种通俗语料库是识别不出来的. 比如说: 宝马X5, 八荣八耻, 三严三实. 这些专用词语在分词时候是应当被提取出来的. 当然, 你要说可以修改核心词典, 但我认为修改核心词典又是过重的做法, 词典都不好管理. 还是希望有自定义词典优先级的设置.

**Comment by OTAKU-Wang** [comment]
好像通过配置是可以设置的

**Comment by hankcs** [comment]
这不是优先级的问题，目前配置也无法改。

最新版可以分出来。

        Segment segment = new DijkstraSegment();
        CustomDictionary.insert("宝马X5");
        CustomDictionary.insert("三严三实");
        System.out.println(segment.seg(
                "比如说: 宝马X5, 八荣八耻, 三严三实"
        ));

[比如说/vl, :/w,  /w, 宝马X5/nz, , /w, 八荣八耻/nz, , /w, 三严三实/nz]

**Comment by laoyang945** [comment]
优酷总裁魏明介绍了优酷2015年的内容战略，表示要以“大电影、大网剧、大综艺”为关键词
把「网剧」加到自定义词典里面，怎么分都是「大网/剧」，请教这里应该怎么弄

**Comment by hankcs** [comment]
data/dictionary/CoreNatureDictionary.txt中已经有网剧，所以应该通过调NGram模型解决。
请参考：https://github.com/hankcs/HanLP/commit/f8e789de2f32d650319af85f0db2853f4aacb469

自定义词典是对模型的补丁，优先级不能超过模型，所以不保证一定能分出来。

**Comment by laoyang945** [comment]
求教，「新一波」应该分成「新/一波」或者不分，但是现在分成了「新一/波」，这里应该怎么做修改呢，还是改ngram吗？

**Comment by hankcs** [comment]
删掉 data/dictionary/custom/全国地名大全.txt 中的 新一

一部分人觉得觉得自定义词典优先级应该大于核心词典，可是真的实施了之后，又带来了干扰的问题，所谓众口难调。

**Comment by laoyang945** [comment]
我加了个词「新一波」……另外，是整个custom文件夹里面的文件编译出来一个bin对吗？然后请教一下，ngram里面的@，末##末是什么意思呢？

**Comment by hankcs** [comment]
0. 是的，准确来讲，是配置文件指定的那些词典
0. @ 是分隔符，末##末是句子结尾

**Comment by laoyang945** [comment]
另外请教一下，停用词是不分大小写的吧？

**Comment by hankcs** [comment]
区分

**Comment by n3xtchen** [comment]
```java
CustomDictionaryPath=data/dictionary/custom/CustomDictionary.txt;  现代汉语补充词库.txt; 全国地名大全.txt ns; 人名词典.txt; 机构名词典.txt; 上海地名.txt ns;data/dictionary/person/nrf.txt nrf;
```
请问下配置文件，配了这么多，为什么只加载了 ｀CustomDictionaryPath=data/dictionary/custom/CustomDictionary.txt;｀ 
```java
...
INFO: 自定义词典开始加载:/Users/ichexw/Dev/shared_project/jiayou/information_extraction/data/dictionary/custom/CustomDictionary.txt
Nov 17, 2015 10:53:23 PM com.hankcs.hanlp.dictionary.CustomDictionary <clinit>
INFO: 自定义词典加载成功:409706个词条，耗时322ms
```

如果把后一个提到第一个才会生效，后面的几个都不奏效，请问这是我配置出错的问题吗？麻烦看一下

我使用的版本

```gradle
compile 'com.hankcs:hanlp:portable-1.2.7'
```

**Comment by wanghaisheng** [comment]
```
        CustomDictionary.insert("10^9/L", "clear-unit 1024");

        String text = "1*白细胞计数WBC6.623.50-9.5010^9/L";  // 怎么可能噗哈哈！


        Segment segment = new DijkstraSegment();

        System.out.println(segment.seg(
                text
        ));

```

 6.623/m, ./w, 50/m, -/nx, 9.5010/m, ^/nx, 9/m, //w, L/nx

自定义词典中的词未生效

**Comment by hankcs** [comment]
将com.hankcs.hanlp.seg.Segment#combineByCustomDictionary中的逻辑移入com.hankcs.hanlp.seg.WordBasedGenerativeModelSegment#GenerateWordNet即可。

**Comment by bushuaigege** [comment]
> 删掉 data/dictionary/custom/全国地名大全.txt 中的 新一
> 
> 一部分人觉得觉得自定义词典优先级应该大于核心词典，可是真的实施了之后，又带来了干扰的问题，所谓众口难调。

 确实很多场景有这个需求，可以默认核心词典，给外部设置入口，通过api插入自定义词典，词语太多情况下不优雅

**Comment by hankcs** [comment]
新版实现了`com.hankcs.hanlp.seg.Segment#enableCustomDictionaryForcing`
