### ISSUE TITLE
关于语义距离计算的问题

### ISSUE THREAD

**Issue by tinyfroglee** [hankcs/HanLP#531]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：hanlp-1.3.3-release
我使用的版本是：hanlp-1.3.3-release

## 我的问题
在调用[语义距离](https://github.com/hankcs/HanLP#20-语义距离)和语义相似度方法时，出现语义相似度为0。

### 步骤

1. 首先，我通过[关键词提取](https://github.com/hankcs/HanLP#14-关键词提取)获取了某个句子的关键词。例如，[程序员, 程序, 分为, 人员, 软件]。
2. 然后，我对获得的关键词进行语义距离和语义相似度的计算。计算结果中，与“程序员”一词相关的记录，语义距离为无穷，语义相似度为0。

新手，刚接触分词，以下是自己做出的一些尝试与猜想，如有描述不当，还请批评指正。
1.猜想需要添加“程序员”到自定义词典，尝试了动态增加词语“程序员”，结果无变化。
2.猜想在《同义词词林扩展版》中没有与“程序员”相关的记录，故无法计算语义距离和语义相似度。

请问，具体是哪一种问题导致一个词语对自己本身的语义相似度为0？对于相应的问题，我可以怎么解决，或参考什么样例去解决？

### 触发代码

```
String content = "程序员(英文Programmer)是从事程序开发、维护的专业人员。一般将程序员分为程序设计人员和程序编码人员，但两者的界限并不非常清楚，特别是在中国。软件从业人员分为初级程序员、高级程序员、系统分析员和项目经理四大类。";
List<String> keywordList = HanLP.extractKeyword(content, 5);
System.out.println(keywordList);
System.out.printf("%-5s\t\t%-5s\t\t%-10s\t\t%-5s\n", "词A", "词B", "语义距离", "语义相似度");
for (String a : keywordList)
{
	
    for (String b : keywordList)
    {
        System.out.printf("%-5s\t\t%-5s\t%-15d\t%-5.10f\n", a, b, CoreSynonymDictionary.distance(a, b), CoreSynonymDictionary.similarity(a, b));
    }
}
```
### 期望输出
(输出结果末尾加"*"为方便提示关键行)

```
词A   		词B   	语义距离      	语义相似度
程序员  		程序员  	0              	1.0000000000*
程序员  		程序   	(非无穷)		(非0)*
程序员  		分为   	(非无穷)		(非0)*
程序员  		人员   	(非无穷)		(非0)*
程序员  		软件   	(非无穷)		(非0)*
程序   		程序员  	(非无穷)		(非0)*
程序   		程序   	0              	1.0000000000
程序   		分为   	28631246094    	0.6146479284
程序   		人员   	21054522402    	0.7166241456
程序   		软件   	14295982706    	0.8075883064
分为   		程序员  	(非无穷)		(非0)*
分为   		程序   	28631246094    	0.6146479284
分为   		分为   	0              	1.0000000000
分为   		人员   	49685768496    	0.3312720740
分为   		软件   	42927228800    	0.4222362347
人员   		程序员  	(非无穷)		(非0)*
人员   		程序   	21054522402    	0.7166241456
人员   		分为   	49685768496    	0.3312720740
人员   		人员   	0              	1.0000000000
人员   		软件   	6758539696     	0.9090358392
软件   		程序员  	(非无穷)		(非0)*
软件   		程序   	14295982706    	0.8075883064
软件   		分为   	42927228800    	0.4222362347
软件   		人员   	6758539696     	0.9090358392
软件   		软件   	0              	1.0000000000
```

### 实际输出
(输出结果末尾加"*"为方便提示关键行)

```
词A   		词B   		语义距离      	语义相似度
程序员  		程序员  	9223372036854775807	0.0000000000*
程序员  		程序   	9223372036854775807	0.0000000000*
程序员  		分为   	9223372036854775807	0.0000000000*
程序员  		人员   	9223372036854775807	0.0000000000*
程序员  		软件   	9223372036854775807	0.0000000000*
程序   		程序员  	9223372036854775807	0.0000000000*
程序   		程序   	0              		1.0000000000
程序   		分为   	28631246094    		0.6146479284
程序   		人员   	21054522402    		0.7166241456
程序   		软件   	14295982706    		0.8075883064
分为   		程序员  	9223372036854775807	0.0000000000*
分为   		程序   	28631246094    		0.6146479284
分为   		分为   	0              		1.0000000000
分为   		人员   	49685768496    		0.3312720740
分为   		软件   	42927228800    		0.4222362347
人员   		程序员  	9223372036854775807	0.0000000000*
人员   		程序   	21054522402    		0.7166241456
人员   		分为   	49685768496    		0.3312720740
人员   		人员   	0              		1.0000000000
人员   		软件   	6758539696     		0.9090358392
软件   		程序员  	9223372036854775807	0.0000000000*
软件   		程序   	14295982706    		0.8075883064
软件   		分为   	42927228800    		0.4222362347
软件   		人员   	6758539696     		0.9090358392
软件   		软件   	0              		1.0000000000
```

## 其他信息
补充一下自己同时结合调用两种方法（[语义距离](https://github.com/hankcs/HanLP#20-语义距离)和[关键词提取](https://github.com/hankcs/HanLP#14-关键词提取)）的初衷：
我期望通过输入关键词，计算关键词与句子的关联度（以下简称 关联度），以达到“关键词-句子-关联度”的结果。
而在计算关联度时，我计划：
先提取句子关键词，如，[程序员, 程序, 分为, 人员, 软件]；
再输入关键词，如，“程序员”，“编程”等，计算输入的关键词与句子关键词之间的相似度；
最后利用关键词的相似度，从一定的程度反映关联度。

以上是我目前期望的需求，如果作者有遇到或解决过类似问题，还请多多指教。
谢谢！

**Comment by hankcs** [comment]
- 词语自己和自己的距离是0没有问题的
- 从你的描述来看，你的需求其实已经在你心中有了实现方案了，可以通过com.hankcs.hanlp.suggest.scorer.IScorer来实现。
- 我当时草拟的几个scorer可能太简单，欢迎补充。

**Comment by tinyfroglee** [comment]
首先，感谢作者的回答！但自己是初次应用HanLP，对您的回答中的一些内容理解得不透彻，还请继续指教。

1.词语自己和自己的距离，我期望是0，但实际出现了非0。所以，您的回答的第3点，就是在指导我通过补充scorer来解决语义距离问题吗？如果是，还请指导下具体怎么补充？
2. com.hankcs.hanlp.suggest.scorer.IScorer的调用，没有看太明白，不知是否方便给出一个Demo以供学习？

问题难度不大，但对于初学者，可能确实是一个小小的障碍。如有叨扰，还请见谅！

**Comment by hankcs** [comment]
- 其原理请参考：https://github.com/hankcs/HanLP/wiki/FAQ#%E5%90%8C%E4%B9%89%E8%AF%8D%E8%AF%AD%E4%B9%89%E8%B7%9D%E7%A6%BB%E7%AE%97%E6%B3%95%E5%8E%9F%E7%90%86
- 并非word2vec那种灵活的映射，只是一个简单的词典
- 词林中没有程序员这类新词，所以无法应对。可以按对方的格式自行添加词汇
- 其实demo就在源码中，比如PinyinScorer就是按照拼音的相似性进行打分的，有完整的注释，欢迎参考

**Comment by tinyfroglee** [comment]
好的，感谢指点！

**Comment by Rain117E** [comment]
> * 可以按对方的格式自行添加词汇

hankcs大佬，我作为一个NLP的初学者想请教一下向同义词典里添加一些新词（专业性较强的词）的具体流程？貌似现在我还没有找到适合我这样比较笨的初学者的教程。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
