### ISSUE TITLE
"烤羊排"进行分词为"烤"和"羊排"

### ISSUE THREAD

**Issue by islandValent** [hankcs/HanLP#533]
问题
对词语"烤羊排"进行分词，
得到结果: 烤羊排 [nf]， 期望能把 烤 和 羊排 区分开

版本
程序版本号：hanlp-portable-1.2.7
数据版本号：data-for-1.3.2.zip

触发代码
`HanLP.segment("烤羊排");`

代码输出
`烤羊排 [nf]`

尝试
CoreNatureDictionary.txt中有 烤、羊排、烤羊排三个词语，我在词库CoreNatureDictionary.ngram.txt中增加 烤@羊排 2000，但是还是没有效果，麻烦帮忙看一下，非常感谢。

**Comment by hankcs** [comment]
- CoreNatureDictionary.txt将羊排的频次调大一点，比如 羊排	nf	3000
- CoreNatureDictionary.ngram.txt添加 羊排@末##末 100000

**Comment by westsince2001** [comment]
@hankcs
同样的问题，我是一个人名:"白百何"  
CoreNatureDictionary.txt将羊排的频次调大一点，比如 羊排	nf	3000
CoreNatureDictionary.ngram.txt添加 羊排@末##末 100000

但我是这样改的：
把白百何 加到“CoreNatureDictionary.txt” 中,尝试加入"百何“，没有效果啊。
最后是这样：
CoreNatureDictionary.txt将羊排的频次调大一点，比如  白百何	nf	3000
CoreNatureDictionary.ngram.txt添加 百何@末##末 100000

**Comment by westsince2001** [comment]
@hankcs  我有很多类似的词，优先级都比较高，都需要能优先识别，我都需要改这2个核心的文件么？
版本：HanLP-1.3.2

**Comment by hankcs** [comment]
现在的人名识别工作很正常啊，[有/vyou, 个/q, 人/n, 叫/vi, 白百何/nr]

如果你硬要拆成白+百何，你的确需要一个个改

**Comment by westsince2001** [comment]
@hankcs 好吧，我之前的描述不太对。之前的问题是： 白百何  出现在句子中，但是无法识别。
如：“卓伟:白百何方曾想出高价买断出轨视频 被我拒绝了”  。虽然我在词库里有“白百何”，但就是无法识别。这样的问题，是不是一定要改CoreNatureDictionary.txt和CoreNatureDictionary.ngram.txt？

**Comment by hankcs** [comment]
是的。像这类不会引起歧义的人名，可以直接加入到CoreNatureDictionary中去

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
