### ISSUE TITLE
个别句子句法依存的核心词有误

### ISSUE THREAD

**Issue by hx78** [hankcs/HanLP#538]
版本1.3.2
对于句法依存的结果，有种无从修改的感觉，是不是只能重新训练一个模型呢？

**"元旦下午8点03分提醒我去后海和老朋友聚会",**
核心词为“聚会”，应该为“提醒”，聚会本来是动词的，我修改成了名词。

1	元旦	nt	t	_	2	定中关系	_	_
2	下午	nt	t	_	3	定中关系	_	_
3	8点	nt	t	_	4	定中关系	_	_
4	03分	nt	t	_	5	状中结构	_	_
5	提醒	v	v	_	8	定中关系	_	_
6	我	r	rr	_	5	兼语	_	_
7	去	v	vf	_	5	动宾关系	_	_
8	后	nd	f	_	11	定中关系	_	_
9	海和老	nh	nr	_	10	定中关系	_	_
10	朋友	n	n	_	11	定中关系	_	_
11	聚会	n	n	_	0	核心关系	_	_

元旦 --(定中关系)--> 下午
下午 --(定中关系)--> 8点
8点 --(定中关系)--> 03分
03分 --(状中结构)--> 提醒
提醒 --(定中关系)--> 后
我 --(兼语)--> 提醒
去 --(动宾关系)--> 提醒
后 --(定中关系)--> 聚会
海和老 --(定中关系)--> 朋友
朋友 --(定中关系)--> 聚会
聚会 --(核心关系)--> ##核心##

**“每星期日中午一点半提醒我出去玩的时间到了"**
核心词为“到”，应该为“提醒”

1	每星期日	nt	t	_	2	定中关系	_	_
2	中午	nt	t	_	4	定中关系	_	_
3	一点	nt	t	_	4	定中关系	_	_
4	半	m	mq	_	5	状中结构	_	_
5	提醒	v	v	_	10	定中关系	_	_
6	我	r	rr	_	5	兼语	_	_
7	出去	v	vf	_	5	动宾关系	_	_
8	玩	v	v	_	7	并列关系	_	_
9	的	u	ude1	_	7	右附加关系	_	_
10	时间	n	n	_	11	主谓关系	_	_
11	到	v	v	_	0	核心关系	_	_
12	了	u	ule	_	11	右附加关系	_	_

每星期日 --(定中关系)--> 中午
中午 --(定中关系)--> 半
一点 --(定中关系)--> 半
半 --(状中结构)--> 提醒
提醒 --(定中关系)--> 时间
我 --(兼语)--> 提醒
出去 --(动宾关系)--> 提醒
玩 --(并列关系)--> 出去
的 --(右附加关系)--> 出去
时间 --(主谓关系)--> 到
到 --(核心关系)--> ##核心##
了 --(右附加关系)--> 到

**Comment by hankcs** [comment]
第一个句子人名识别误命中了，也许你在用98年的模型。这个模型里面应该没有后海这个词。对14年来讲没有问题

1	元旦	元旦	nt	t	_	2	定中关系	_	_
2	下午	下午	nt	t	_	6	定中关系	_	_
3	8	8	m	m	_	4	定中关系	_	_
4	点	点	q	qt	_	6	定中关系	_	_
5	03	03	m	m	_	6	定中关系	_	_
6	分	分	q	qt	_	7	状中结构	_	_
7	提醒	提醒	v	v	_	0	核心关系	_	_
8	我	我	r	rr	_	7	兼语	_	_
9	去	去	v	vf	_	7	动宾关系	_	_
10	后海	后海	nd	f	_	9	动宾关系	_	_
11	和	和	c	cc	_	12	左附加关系	_	_
12	老朋友	老朋友	n	n	_	10	并列关系	_	_
13	聚会	聚会	v	vi	_	9	并列关系	_	_

第二个句子“一点半”最好分为一个词，且为时间词性，不然不好修饰提醒。

**Comment by hx78** [comment]
tks
