### ISSUE TITLE
HanLP.properties如何引用Java系统参数

### ISSUE THREAD

**Issue by kjdongzh** [hankcs/HanLP#539]
问题产生的情景是：我有一个使用到hanlp的webapp项目工程，需要部署到windows和linux等不同的系统环境中，但是HanLP配置文件中的路径每次都需要手动修改，我想可不可以使用系统参数来代替呢
例如：修改之前HanLP.properties中的配置是这样的
```
    root=D:/dic/
```

修改之后，期望可以引用jvm参数（-Dhanlp.dic=D:/dic/），
```
root=${hanlp.dic}
```
如果hanlp没有此功能，我应该怎么扩展呢，需要修改哪些代码？

**Comment by hankcs** [comment]
1. 你可以把root设为一个占位符${hanlp.dic}，然后写代码将com.hankcs.hanlp.HanLP.Config#CoreDictionaryPath之类字符串中的占位符都替换为系统真实值
1. 否则修改com.hankcs.hanlp.HanLP.Config中的加载逻辑

**Comment by kjdongzh** [comment]
去哪里可以下载hanlp-portable-1.3.2.jar的源码，portable分支只发布到portable-1.2.11版本

**Comment by kjdongzh** [comment]
我想请教个问题：

portable版源码下载问题
我项目中使用的是hanlp-portable-1.3.2.jar版本（从maven中下载），请问去哪里可以下载hanlp-portable-1.3.2.jar的源码，因为github上的portable分支只发布到portable-1.2.11版本（我修改了portable-1.2.11源码放在hanlp-portable-1.3.2.jar中会出现各种问题，总是提示方法或者字段不存在），https://github.com/hankcs/HanLP/releases 下载地址中的源码又不是portable版的。

**Comment by hankcs** [comment]
这里有：http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.hankcs%22%20AND%20a%3A%22hanlp%22

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
