### ISSUE TITLE
remove自定义添加词的时候遇到一些问题

### ISSUE THREAD

**Issue by dengbojing** [hankcs/HanLP#540]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [ x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：portable-1.3.4
我使用的版本是：portable-1.3.4

## 我的问题

在自定义添加用户字典之后，执行删除操作，发现有些词删不掉，比如“力帆”，“摩根”。
我做了几次测试结果是：
1.单独remove “摩根”  --成功。
2.remove “摩根”，“123（123表示任意一个字符，即我添加了2个词，现在要remove这两个词） 此时失败。
3.remove “摩根”，“力帆” 此时又是成功。

本人是新手菜鸟，感觉是不是某些词直接的关联关系导致的？不知道此现象是为何原因，又是如何去解决，望大神指点。

附上部分代码：
CustomDictionary.add("123");
		CustomDictionary.add("摩根");
		CustomDictionary.remove("123");
		CustomDictionary.remove("摩根");
此时最后一行 remove摩根报错。
		CustomDictionary.add("力帆");
		CustomDictionary.add("摩根");
		CustomDictionary.remove("力帆");
		CustomDictionary.remove("摩根");

此时程序执行正常。

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

```
    public void testIssue1234() throws Exception
    {
        CustomDictionary.add("用户词语");
        System.out.println(StandardTokenizer.segment("触发问题的句子"));
    }
```
### 期望输出

```
期望输出
```

### 实际输出

```
实际输出
```

**Comment by hankcs** [comment]
感谢反馈，已经修复。 
如果还有问题，欢迎重开issue。
