### ISSUE TITLE
“糊”繁体转换后的结果为“煳“，bug

### ISSUE THREAD

**Issue by upcmill** [hankcs/HanLP#541]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [ ] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.3.4
我使用的版本是：1.3.4

## 我的问题

"糊"在进行简体转繁体结果是“糊”，从繁体转简体时结果是“煳”
互逆的操作，结果不同。应属于bug

## 复现问题

我没有修改任何代码和词典

### 步骤

1. 首先……
System.out.println(HanLP.convertToTraditionalChinese("糊涂果"));
2. 然后……
System.out.println(HanLP.convertToSimplifiedChinese("糊塗果"));
3. 接着……
出结果
### 触发代码
System.out.println(HanLP.convertToTraditionalChinese("糊涂果"));
		System.out.println(HanLP.convertToSimplifiedChinese("糊塗果"));
### 期望输出

```
期望输出
```
糊塗果
糊涂果

### 实际输出

```
实际输出
```
糊塗果
煳涂果

**Comment by hankcs** [comment]
感谢指正，以后遇到错误请参考commit修改。 
如果还有问题，欢迎重开issue。
