### ISSUE TITLE
关于字母数字组合词的建议

### ISSUE THREAD

**Issue by AnyListen** [hankcs/HanLP#543]
1. 在数学表达式以及化学表达式里面有很多的上下标，这些符号在字符表里面没有定义，常见的对应关系如下：
```
º=0
¹=1
²=2
³=3
⁴=4
⁵=5
⁶=6
⁷=7
⁸=8
⁹=9
₀=0
₁=1
₂=2
₃=3
₄=4
₅=5
₆=6
₇=7
₈=8
₉=9
ⁿ=n
```
2. 对于字母数字的组合，目前系统是直接进行分割的，例如：化学表达式H2O，目前的分词结果为H/2/O；调试发现在生成词网的时候就已经被分开了，建议能够在生成词网的时候不分开，然后在索引模式的细切分模式中进行二次切分，效果会更好一些；例如qq2017的分词结果会变为：qq2017、qq、2017；H2O的结果为h20、h、2、o；当然可以在二次切分的时候判断一下子词的长度，如果小于等于1则进行忽略；

**Comment by hankcs** [comment]
1. 这些符号可以加到data/dictionary/other/CharTable.txt，欢迎提交pr
1. 关于字母数字的切分，可通过CharType个性化，请参考：https://github.com/hankcs/HanLP/issues/517

**Comment by AnyListen** [comment]
对于字母数字的切分，试了一下上述的方法，可行，但是总感觉这样不大妥；分词结果显示词性为`m`；
还有就是中文的`一二`这样的词性也被分到了`m`里面，这样使得`1千万`在分词结果里面无法被细分

**Comment by hankcs** [comment]
数词是特意做成这种效果，即中文阿拉伯全半角大小写数字都是m，无论是代码上语义上甚至在效率上都有优势。要取消也很简单，往核心词典里塞入这些中文数词即可。
对于这类规律性很强的字符串，建议在分词前（参考URL识别）或分词后（参考数量词合并）再做个性化的合并处理。

**Comment by AnyListen** [comment]
OK 等以后想到更好的实践在进行优化
