### ISSUE TITLE
TextRankKeyword 提取窗口相近词的强化

### ISSUE THREAD

**Issue by tiandiweizun** [hankcs/HanLP#546]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.3.4
我使用的版本是：1.3.0，和1.3.4源码一样

## 我的问题

小小的功能强化，
源码：提取临近窗口词的复杂度为o(n^2)，n为窗口大小
建议：提取临近窗口词的复杂度为o(n)，n为窗口大小

想法：由于是文章，假设词的总数为C，所以时间又会被线性放大C倍，建议还是可以处理一下
地址：com.hankcs.hanlp.summary.TextRankKeyword.getRank(List<Term> termList) 方法
源码：
<pre><code>            que.offer(w);
            if (que.size() > 5) {
                que.poll();
            }

            for (String w1 : que)
            {
                for (String w2 : que)
                {
                    if (w1.equals(w2))
                    {
                        continue;
                    }

                    words.get(w1).add(w2);
                    words.get(w2).add(w1);
                }
            }
</code></pre>
建议：
<pre><code>     
            // 复杂度O(n-1)
            if (que.size() >= 5) {
                que.poll();
            }            
            for (String qWord : que) {
                if (w.equals(qWord)) {
                    continue;
                }
                //既然是邻居,那么关系是相互的,遍历一遍即可
                words.get(w).add(qWord);
                words.get(qWord).add(w);
            }
            que.offer(w);
</code></pre>
## 测试结果：
* 测试一：
  - 句子：
程序员是从事程序开发、维护的专业人员。一般将程序员分为程序设计人员和程序编码人员，但两者的界限并不非常清楚，特别是在中国。软件从业人员分为初级程序员、高级程序员、系统分析员和项目经理四大类。
  - 源码：
{专业=[人员, 从事, 分为, 开发, 程序, 程序员, 维护], 中国=[人员, 分为, 清楚, 特别, 界限, 程序员, 软件, 非常], 人员=[专业, 中国, 分为, 开发, 清楚, 特别, 界限, 程序, 程序员, 维护, 编码, 设计, 软件, 非常, 高级], 从事=[专业, 开发, 程序, 程序员, 维护], 分为=[专业, 中国, 人员, 特别, 程序, 程序员, 系统, 维护, 设计, 软件, 高级], 分析员=[程序员, 系统, 经理, 项目, 高级], 开发=[专业, 人员, 从事, 程序, 程序员, 维护], 清楚=[中国, 人员, 特别, 界限, 编码, 软件, 非常], 特别=[中国, 人员, 分为, 清楚, 界限, 软件, 非常], 界限=[中国, 人员, 清楚, 特别, 程序, 编码, 非常], 程序=[专业, 人员, 从事, 分为, 开发, 界限, 程序员, 维护, 编码, 设计, 非常], 程序员=[专业, 中国, 人员, 从事, 分为, 分析员, 开发, 程序, 系统, 经理, 维护, 设计, 软件, 项目, 高级], 系统=[分为, 分析员, 程序员, 经理, 项目, 高级], 经理=[分析员, 程序员, 系统, 项目], 维护=[专业, 人员, 从事, 分为, 开发, 程序, 程序员], 编码=[人员, 清楚, 界限, 程序, 设计, 非常], 设计=[人员, 分为, 程序, 程序员, 编码], 软件=[中国, 人员, 分为, 清楚, 特别, 程序员, 非常, 高级], 非常=[中国, 人员, 清楚, 特别, 界限, 程序, 编码, 软件], 项目=[分析员, 程序员, 系统, 经理, 高级], 高级=[人员, 分为, 分析员, 程序员, 系统, 软件, 项目]}
  - 建议：
{专业=[人员, 从事, 分为, 开发, 程序, 程序员, 维护], 中国=[人员, 分为, 清楚, 特别, 界限, 程序员, 软件, 非常], 人员=[专业, 中国, 分为, 开发, 清楚, 特别, 界限, 程序, 程序员, 维护, 编码, 设计, 软件, 非常, 高级], 从事=[专业, 开发, 程序, 程序员, 维护], 分为=[专业, 中国, 人员, 特别, 程序, 程序员, 系统, 维护, 设计, 软件, 高级], 分析员=[程序员, 系统, 经理, 项目, 高级], 开发=[专业, 人员, 从事, 程序, 程序员, 维护], 清楚=[中国, 人员, 特别, 界限, 编码, 软件, 非常], 特别=[中国, 人员, 分为, 清楚, 界限, 软件, 非常], 界限=[中国, 人员, 清楚, 特别, 程序, 编码, 非常], 程序=[专业, 人员, 从事, 分为, 开发, 界限, 程序员, 维护, 编码, 设计, 非常], 程序员=[专业, 中国, 人员, 从事, 分为, 分析员, 开发, 程序, 系统, 经理, 维护, 设计, 软件, 项目, 高级], 系统=[分为, 分析员, 程序员, 经理, 项目, 高级], 经理=[分析员, 程序员, 系统, 项目], 维护=[专业, 人员, 从事, 分为, 开发, 程序, 程序员], 编码=[人员, 清楚, 界限, 程序, 设计, 非常], 设计=[人员, 分为, 程序, 程序员, 编码], 软件=[中国, 人员, 分为, 清楚, 特别, 程序员, 非常, 高级], 非常=[中国, 人员, 清楚, 特别, 界限, 程序, 编码, 软件], 项目=[分析员, 程序员, 系统, 经理, 高级], 高级=[人员, 分为, 分析员, 程序员, 系统, 软件, 项目]}

* 测试二：
  - 句子：
算法可大致分为基本算法、数据结构的算法、数论算法、计算几何的算法、图的算法、动态规划以及数值分析、加密算法、排序算法、检索算法、随机化算法、并行算法、厄米变形模型、随机森林算法。
算法可以宽泛的分为三类，
一，有限的确定性算法，这类算法在有限的一段时间内终止。他们可能要花很长时间来执行指定的任务，但仍将在一定的时间内终止。这类算法得出的结果常取决于输入值。
二，有限的非确定算法，这类算法在有限的时间内终止。然而，对于一个（或一些）给定的数值，算法的结果并不是唯一的或确定的。
三，无限的算法，是那些由于没有定义终止定义条件，或定义的条件无法由输入的数据满足而不终止运行的算法。通常，无限算法的产生是由于未能确定的定义终止条件。

  - 源码：
{一定=[任务, 得出, 执行, 指定, 时间, 算法, 终止], 产生=[定义, 未能, 确定, 算法, 终止, 运行, 通常], 任务=[一定, 可能, 执行, 指定, 时间, 算法, 终止], 几何=[动态, 数论, 算法, 规划, 计算], 分为=[基本, 大致, 宽泛, 数据, 有限, 森林, 确定性, 算法, 结构], 分析=[加密, 动态, 排序, 数值, 算法, 规划], 加密=[分析, 动态, 排序, 数值, 检索, 算法, 规划], 动态=[几何, 分析, 加密, 数值, 算法, 规划, 计算], 取决于=[得出, 时间, 有限, 确定, 算法, 终止, 输入], 变形=[并行, 森林, 模型, 算法], 可能=[任务, 执行, 指定, 时间, 有限, 算法, 终止], 基本=[分为, 大致, 数据, 算法, 结构], 大致=[分为, 基本, 数据, 算法], 定义=[产生, 数据, 无法, 未能, 条件, 没有, 确定, 算法, 终止, 输入], 宽泛=[分为, 有限, 森林, 模型, 确定性, 算法], 并行=[变形, 检索, 森林, 模型, 算法], 得出=[一定, 取决于, 时间, 有限, 确定, 算法, 终止, 输入], 执行=[一定, 任务, 可能, 指定, 时间, 终止], 指定=[一定, 任务, 可能, 执行, 时间, 终止], 排序=[分析, 加密, 数值, 检索, 算法], 数值=[分析, 加密, 动态, 排序, 时间, 有限, 没有, 确定, 算法, 终止, 给定, 规划], 数据=[分为, 基本, 大致, 定义, 数论, 无法, 条件, 满足, 算法, 终止, 结构, 输入, 运行], 数论=[几何, 数据, 算法, 结构, 计算], 无法=[定义, 数据, 条件, 满足, 终止, 输入], 时间=[一定, 任务, 取决于, 可能, 得出, 执行, 指定, 数值, 有限, 确定, 确定性, 算法, 终止, 给定], 有限=[分为, 取决于, 可能, 宽泛, 得出, 数值, 时间, 确定, 确定性, 算法, 终止, 给定, 输入], 未能=[产生, 定义, 条件, 确定, 算法, 终止, 通常], 条件=[定义, 数据, 无法, 未能, 没有, 满足, 确定, 终止, 输入], 检索=[加密, 并行, 排序, 算法], 森林=[分为, 变形, 宽泛, 并行, 模型, 算法], 模型=[变形, 宽泛, 并行, 森林, 算法], 没有=[定义, 数值, 条件, 确定, 算法, 终止], 满足=[数据, 无法, 条件, 算法, 终止, 输入, 运行, 通常], 确定=[产生, 取决于, 定义, 得出, 数值, 时间, 有限, 未能, 条件, 没有, 算法, 终止, 给定, 输入, 通常], 确定性=[分为, 宽泛, 时间, 有限, 算法], 算法=[一定, 产生, 任务, 几何, 分为, 分析, 加密, 动态, 取决于, 变形, 可能, 基本, 大致, 定义, 宽泛, 并行, 得出, 排序, 数值, 数据, 数论, 时间, 有限, 未能, 检索, 森林, 模型, 没有, 满足, 确定, 确定性, 终止, 结构, 给定, 规划, 计算, 输入, 运行, 通常], 终止=[一定, 产生, 任务, 取决于, 可能, 定义, 得出, 执行, 指定, 数值, 数据, 无法, 时间, 有限, 未能, 条件, 没有, 满足, 确定, 算法, 给定, 输入, 运行, 通常], 结构=[分为, 基本, 数据, 数论, 算法, 计算], 给定=[数值, 时间, 有限, 确定, 算法, 终止], 规划=[几何, 分析, 加密, 动态, 数值, 算法], 计算=[几何, 动态, 数论, 算法, 结构], 输入=[取决于, 定义, 得出, 数据, 无法, 有限, 条件, 满足, 确定, 算法, 终止, 运行], 运行=[产生, 数据, 满足, 算法, 终止, 输入, 通常], 通常=[产生, 未能, 满足, 确定, 算法, 终止, 运行]}
  - 建议：
{一定=[任务, 得出, 执行, 指定, 时间, 算法, 终止], 产生=[定义, 未能, 确定, 算法, 终止, 运行, 通常], 任务=[一定, 可能, 执行, 指定, 时间, 算法, 终止], 几何=[动态, 数论, 算法, 规划, 计算], 分为=[基本, 大致, 宽泛, 数据, 有限, 森林, 确定性, 算法, 结构], 分析=[加密, 动态, 排序, 数值, 算法, 规划], 加密=[分析, 动态, 排序, 数值, 检索, 算法, 规划], 动态=[几何, 分析, 加密, 数值, 算法, 规划, 计算], 取决于=[得出, 时间, 有限, 确定, 算法, 终止, 输入], 变形=[并行, 森林, 模型, 算法], 可能=[任务, 执行, 指定, 时间, 有限, 算法, 终止], 基本=[分为, 大致, 数据, 算法, 结构], 大致=[分为, 基本, 数据, 算法], 定义=[产生, 数据, 无法, 未能, 条件, 没有, 确定, 算法, 终止, 输入], 宽泛=[分为, 有限, 森林, 模型, 确定性, 算法], 并行=[变形, 检索, 森林, 模型, 算法], 得出=[一定, 取决于, 时间, 有限, 确定, 算法, 终止, 输入], 执行=[一定, 任务, 可能, 指定, 时间, 终止], 指定=[一定, 任务, 可能, 执行, 时间, 终止], 排序=[分析, 加密, 数值, 检索, 算法], 数值=[分析, 加密, 动态, 排序, 时间, 有限, 没有, 确定, 算法, 终止, 给定, 规划], 数据=[分为, 基本, 大致, 定义, 数论, 无法, 条件, 满足, 算法, 终止, 结构, 输入, 运行], 数论=[几何, 数据, 算法, 结构, 计算], 无法=[定义, 数据, 条件, 满足, 终止, 输入], 时间=[一定, 任务, 取决于, 可能, 得出, 执行, 指定, 数值, 有限, 确定, 确定性, 算法, 终止, 给定], 有限=[分为, 取决于, 可能, 宽泛, 得出, 数值, 时间, 确定, 确定性, 算法, 终止, 给定, 输入], 未能=[产生, 定义, 条件, 确定, 算法, 终止, 通常], 条件=[定义, 数据, 无法, 未能, 没有, 满足, 确定, 终止, 输入], 检索=[加密, 并行, 排序, 算法], 森林=[分为, 变形, 宽泛, 并行, 模型, 算法], 模型=[变形, 宽泛, 并行, 森林, 算法], 没有=[定义, 数值, 条件, 确定, 算法, 终止], 满足=[数据, 无法, 条件, 算法, 终止, 输入, 运行, 通常], 确定=[产生, 取决于, 定义, 得出, 数值, 时间, 有限, 未能, 条件, 没有, 算法, 终止, 给定, 输入, 通常], 确定性=[分为, 宽泛, 时间, 有限, 算法], 算法=[一定, 产生, 任务, 几何, 分为, 分析, 加密, 动态, 取决于, 变形, 可能, 基本, 大致, 定义, 宽泛, 并行, 得出, 排序, 数值, 数据, 数论, 时间, 有限, 未能, 检索, 森林, 模型, 没有, 满足, 确定, 确定性, 终止, 结构, 给定, 规划, 计算, 输入, 运行, 通常], 终止=[一定, 产生, 任务, 取决于, 可能, 定义, 得出, 执行, 指定, 数值, 数据, 无法, 时间, 有限, 未能, 条件, 没有, 满足, 确定, 算法, 给定, 输入, 运行, 通常], 结构=[分为, 基本, 数据, 数论, 算法, 计算], 给定=[数值, 时间, 有限, 确定, 算法, 终止], 规划=[几何, 分析, 加密, 动态, 数值, 算法], 计算=[几何, 动态, 数论, 算法, 结构], 输入=[取决于, 定义, 得出, 数据, 无法, 有限, 条件, 满足, 确定, 算法, 终止, 运行], 运行=[产生, 数据, 满足, 算法, 终止, 输入, 通常], 通常=[产生, 未能, 满足, 确定, 算法, 终止, 运行]}
[测试结果.txt](https://github.com/hankcs/HanLP/files/1028723/default.txt)

**Comment by hankcs** [comment]
感谢反馈，1.3.4已经改进了这个问题，请参考：https://github.com/hankcs/HanLP/commit/229838aaa5a24b7f716a2fa94c9e0582d72ee2c0
如果还有问题，欢迎重开issue。

**Comment by hankcs** [comment]
刚才看错了，不是同一个问题，这是个好建议。

**Comment by hankcs** [comment]
欢迎提交PR，谢谢！

**Comment by hankcs** [comment]
已经merge，谢谢！
