### ISSUE TITLE
CRF的分词结果如何去除停用词？

### ISSUE THREAD

**Issue by laoyang945** [hankcs/HanLP#55]
你好，对CRF分词之后得到的List<Term>使用coreStopWordDictionary.apply之后全是空的，请问是什么情况？
版本1.2.4

**Comment by hankcs** [comment]
因为CRF分词默认不进行词性标注，词性是null。而CoreStopWordDictionary是根据词性进行过滤的，null词性都被过滤掉了。

你可以开启标注或者自己写个apply方法。

**Comment by laoyang945** [comment]
好的，我明白了，那开启标注的话对性能影响会很大吗

**Comment by hankcs** [comment]
有影响，如果你只是为了过滤停用词的话，不建议专门开启。

com/hankcs/hanlp/dictionary/stopword/CoreStopWordDictionary.java 第84行return true就可以满足你的要求了。

**Comment by laoyang945** [comment]
谢谢。另外，有些词，比如「热聊」「高能」这些总是会别分成两个词，这个有可能有好的解决方案吗

**Comment by hankcs** [comment]
算法不是万能的，这些得依靠用户词典解决。如果用CRF的话，现在并不支持用户词典，下一版可能会让CRF支持用户词典。

**Comment by laoyang945** [comment]
CRF似乎对标点符号的分隔不行，好多文本分出来的term里面都有引号

**Comment by hankcs** [comment]
请举个例子

**Comment by laoyang945** [comment]
1. 对六个空格分词，CRF的结果是三个一对空格，词性是null，实际上只要空格大于两个CRF就不能舍弃空格。
2. 「李[空格][空格]扬」的分词结果是李[空格]/null，[空格]扬/null
3. 「“碰瓷”后依靠罚球得分一直是哈登的主要得分手段」的分词结果是 “/w, 碰瓷”/null, 后/f, 依靠/v, 罚球/vn, 得分/n, 一直/d, 是/vshi, 哈登/nrf, 的/ude1, 主要/b, 得分/n, 手段/n。反引号不能识别

**Comment by hankcs** [comment]
1. 训练语料中没有空格，导致空格处理不好。现在已经将空格视为跟英文同等的地位，这样英文人名也会合并到一起，一举两得。
2. 同上
3. 中文冒号被转义为英文冒号，而训练语料中缺乏英文冒号，现在不进行转义了。

**Comment by laoyang945** [comment]
感谢，另外能提供修改后的jar下载吗？

**Comment by hankcs** [comment]
稍等下，打个小版本还是可以的。

**Comment by laoyang945** [comment]
如果文本中有两个空格，还是分成了[空格][空格]/null，这是就这么定的吗？

**Comment by laoyang945** [comment]
然后-_这些的词性也还是null

**Comment by hankcs** [comment]
HanLP.Config.enableDebug();
        HanLP.Config.ShowTermNature = false;
        Segment segment = new CRFSegment();
        System.out.println(segment.seg("李  扬"));


CRF标注结果
李	李	S	
W	  	S	
扬	扬	S	

[李,   , 扬]

**Comment by hankcs** [comment]
你在下载一次1.2.5试试，昨天打包太急了，有个地方处理得不对，今天早上重新打了一次

**Comment by hankcs** [comment]
没开开关的话，词性本来就没有

**Comment by hankcs** [comment]
多个空格的确合并成了一个，我觉得这是很自然的，你觉得不正常可以说说理由，再讨论

**Comment by laoyang945** [comment]
不不，多个空格我没意见，但是词性（包括-_.）什么的，都应该是/w才对吧？

**Comment by hankcs** [comment]
你得打开开关，请参考

CRFSegment segment = new CRFSegment();
segment.enablePartOfSpeechTagging(true);
System.out.println(segment.seg("你看过穆赫兰道吗"));

**Comment by laoyang945** [comment]
这个我打开了的，但是-_空格仍然不是/w

**Comment by hankcs** [comment]
哦，你是说空格词性没标。的确是这样的，你只能用一些后处理逻辑给标上了。

**Comment by lsq88334753** [comment]
你好，我想要将CRF的分词去掉停用词，并且无词性输出,但是
(CoreStopWordDictionary.java 第84行return true)

HanLP.Config.ShowTermNature = false; 
Segment segment = new CRFSegment();
String s = "...";
List<Term> term = segment.seg(s);
CoreStopWordDictionary.apply(term);

的结果中没有过滤掉停用词？请问是怎么回事儿？

**Comment by hankcs** [comment]
因为CRF分词默认不进行词性标注，词性是null。而CoreStopWordDictionary是根据词性进行过滤的，null词性都被过滤掉了。

你可以开启标注或者自己写个apply方法。

**Comment by lsq88334753** [comment]
CRF 不支持加载自定义词典么？
        String s = "一个萝卜一个坑儿";
        segment.enableAllNamedEntityRecognize(true);
        List<Term> term = segment.seg(s);
        CoreStopWordDictionary.apply(term);
将s分成三个词了；配置文件应该没写错路径；另外有个小bug配置文件的路径中如果有空格未导致读取错误

**Comment by hankcs** [comment]
0. 暂不支持
0. 配置文件中的空格有特殊的作用，不是bug。

**Comment by hankcs** [comment]
现在停用词典默认对CRF分词生效了：
https://github.com/hankcs/HanLP/commit/7fb292483b55eb12a4c3f2b679e4efad08887943

**Comment by lsq88334753** [comment]
CustomDictionary 全局的用户自定义词典 也不支持是么？ 一个萝卜一个坑儿  这个词是CustomDictionary 中的

**Comment by hankcs** [comment]
现在支持了：https://github.com/hankcs/HanLP/commit/22e4ba9409e5695c6d46beaadbe999d4abcbefbc

**Comment by nmdxpc** [comment]
@hankcs 你好，你说用CoreStopWordDictionary.apply处理停用词时会根据词性进行过滤（如果词性是null则直接过滤掉），如果我只是想处理停用词，你说的com/hankcs/hanlp/dictionary/stopword/CoreStopWordDictionary.java 第84行return true是指哪个呢？可能版本不同，代码行号变了，是指boolean contains(String key)么？多谢指教

**Comment by hankcs** [comment]
参考com.hankcs.demo.DemoStopWord写个自己的FILTER就行了。
