### ISSUE TITLE
依存文法运行效率问题

### ISSUE THREAD

**Issue by zzzhy** [hankcs/HanLP#551]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.3.4
我使用的版本是：1.3.4

## 我的问题
用scala做NLP的典型意见，期待效果如下：
![qq 20170531101801](https://cloud.githubusercontent.com/assets/10076707/26613211/3dd00be4-45ec-11e7-98f3-151ff9f90789.png)
我的解决方案：依存文法 + 提取核心、主谓、定中 + 形成意见
但是HanLP的依存文法运行 时间很长，spark上依存 500 条 记录需要40s，不能满足要求

## 复现问题

没有修改代码，调用：
``` scala
val sentenceWord = HanLP.parseDependency(sentence).word
```
只实现了HdfsIOAdapter：
``` scala
import java.io.{InputStream, OutputStream}
import com.hankcs.hanlp.corpus.io.IIOAdapter
import org.apache.hadoop.conf.Configuration
import org.apache.hadoop.fs.{FileSystem, Path}
/**
  * @author zzzhy
  *         2017-05-18
  */
object HdfsIOAdapter {
  private val conf = new Configuration()
}
class HdfsIOAdapter extends IIOAdapter {

  import HdfsIOAdapter._
  private val fs = FileSystem.newInstance(conf)

  override def create(path: String): OutputStream = {
    val fsDataOutputStream = fs.create(new Path(path))
    fsDataOutputStream.getWrappedStream
  }

  override def open(path: String): InputStream = {
    val fsDataInputStream = fs.open(new Path(path.replace("\\", "/")))
    fsDataInputStream.getWrappedStream
  }
}
```

### 触发代码

``` scala
val sentenceWord = HanLP.parseDependency(sentence).word
```

有何使用不当或者有何改进方式？

**Comment by hankcs** [comment]
请问测速时是否把模型加载初始化时间也算进去了？
我在MBP单机测试大约21句每秒。

        final int pressure = 100;
        long start = System.currentTimeMillis();
        IDependencyParser parser = new NeuralNetworkDependencyParser().enableDeprelTranslator(false);
        for (int i = 0; i < pressure; i++)
        {
            parser.parse(SENTENCE);
        }
        System.out.printf("依存句法分析速度: %.2f 句/s\n", ((double)pressure / (System.currentTimeMillis() - start) * 1000));

依存句法分析速度: 21.11 句/s

另外，句法分析本身就是个很复杂的任务，不能拿“分词”等低级任务的耗时作比较。几十毫秒一句在Java阵营应该算是较快的，你可以试试斯坦福的parser。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
