### ISSUE TITLE
字典缓存*.bin删除后无法再次产生

### ISSUE THREAD

**Issue by westsince2001** [hankcs/HanLP#552]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

我使用的版本是：HanLP-1.3.2

## 我的问题
windows 环境，每次分词启动后会生成bin 缓存。如果更新字典或删除缓存，下次启动后会再次生成。
但在linux 上，首次运行生成了bin，手动删掉后，下次就没有bin 文件了，这是什么情况？’

**Comment by hankcs** [comment]
估计是权限问题，给data目录777试试。

**Comment by westsince2001** [comment]
@hankcs 试过了，还是没用。我使用的是：portable-1.3.2   。下载了data库，使用HanLP.properties 作为配置。

**Comment by hankcs** [comment]
那就是路径问题了，HanLP.Config.enableDebug();

**Comment by westsince2001** [comment]
@hankcs 想到一个问题，如果是使用maven的portable-1.3.2 版本话，字典都是jar里自带的，那么再使用外部的data 和hanlp.properties 是否就无效了？我调试了几次，都是加载jar里的字典。有点懵了。然后单独用了一个非maven，导入jar的方式，就能读取hanlp.properties的配置了。。。。

**Comment by hankcs** [comment]
1. portable优先读取hanlp.properties
1. 尽量用最新版

**Comment by westsince2001** [comment]
@hankcs 惭愧，CustomDictionaryPath 配置时，末尾新增了自定义的字典，但是格式是dict 。结果造成无论配置文件怎么改，始终读取portable内置的参数。去掉自定义字典dict后，就能显示有效信息了。

**Comment by KevinChen1994** [comment]
设置好自定义词典后，并没有生成CustomDictionary.txt.bin文件，启动debug模式，在输出中没有看到读取自定义词典的日志。

**Comment by WQDestiny** [comment]
我也遇到这个问题了？请问怎么解决的？

**Comment by InterWhite188** [comment]
我也遇到了同样的问题 linux下无法自动生成bin文件，经查询不是权限问题，
