### ISSUE TITLE
自定义的词性无法识别

### ISSUE THREAD

**Issue by syncml** [hankcs/HanLP#553]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x ] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.3.4
我使用的版本是：1.3.4

## 我的问题
在零配置的情况下，自定义字典的词性识别不正确

### 触发代码

```
    public static void main(String[] args) {
        CustomDictionary.insert("别克","brand 1");
        CustomDictionary.insert("英朗","family 1");

        String text1="别克英朗";
        String text2 = "别克 英朗";
        StandardTokenizer.SEGMENT.enableAllNamedEntityRecognize(false);

        List<Term> terms1 = StandardTokenizer.segment(text1);
        System.out.println(terms1);

        List<Term> terms2 = StandardTokenizer.segment(text2);
        System.out.println(terms2);
    }
```
### 期望输出

```
[别克/brand,  英朗/family]
[别克/brand,  /w, 英朗/family]
```

### 实际输出

```
[别克英朗/nrf]
[别克/brand,  /w, 英朗/family]
```

**Comment by hankcs** [comment]
“别克英朗”被音译人名识别器命中了，你可以`enableTranslatedNameRecognize(false)`，或者删除data/dictionary/person/nrf.txt中的“别克”。

**Comment by syncml** [comment]
@hankcs

enableTranslatedNameRecognize(false) 这个加了没用

而且我代码里面加了  StandardTokenizer.SEGMENT.enableAllNamedEntityRecognize(false);
也没用,好奇怪

**Comment by hankcs** [comment]
噢，其他词典中有这个词，得删掉：

<img width="1042" alt="hankcs com 2017-06-06 9 31 37" src="https://cloud.githubusercontent.com/assets/5326890/26831725/cb303db6-4aff-11e7-8015-e5137bb530f3.png">

**Comment by syncml** [comment]
谢谢，通过删除搞定

另外问一个问题
`        CustomDictionary.insert("2016款", "A 1");
        CustomDictionary.insert("RAV4","B 1");
        System.out.println(StandardTokenizer.segment("RAV42016款"));
`
我希望能正确分词，但是结果却是这样的：
[RAV/nx, 42016/m, 款/q]

有什么办法吗？

**Comment by shibing624** [comment]
我试了一下，修改自定义词库及代码动态加载自定义词的方法都不行，而添加CoreNatureDictionary.txt 是可以的（注意删除CoreNatureDictionary.txt.bin），结果是：RAV4/nz, 2016款/nz, 豪华/a, 汽车/n

**Comment by shibing624** [comment]
也可以添加到自定义词典CustomDictionary.txt 后，使用AhoCorasickDoubleArrayTrieSegment分词，参考DemoUseAhoCorasickDoubleArrayTrieSegment，也可以解决。结果是：循环经济/nz, RAV4/nz, 2016款/nz

**Comment by syncml** [comment]
谢谢，果然如此

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
