### ISSUE TITLE
自定义词语无法被正确分出

### ISSUE THREAD

**Issue by zjlswym** [hankcs/HanLP#557]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [ ] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：
我使用的版本是：

## 我的问题

自定义词语分词错误

### 步骤

对“2016年6月大学英语六级考试真题”进行分词

### 触发代码

```
    public void testIssue1234() throws Exception
    {
		String[] testCase = new String[]{
                "2016年6月大学英语六级考试真题",
        };
		
		CustomDictionary.insert("英语六级", "nz 99999");
        for (String sentence : testCase)
        {
            List<Term> termList = HanLP.segment(sentence);
            for(Term t : termList){
            	System.out.println(t.word + ":" + t.getFrequency());
            }
        }
    }
```
### 期望输出

包含
……
英语六级：99999
……
的输出

### 实际输出

2016:0
年:14340
6:0
月:7097
大:27275
学英语:16
六:0
级:3240
考试:3281
真题:12

## 其他信息
当CustomDictionary.insert("大学英语六级");时
却可以正确分出
……
大学英语六级：1
……
的结果

**Comment by hankcs** [comment]
感谢反馈，已经解决。

类似问题可以`HanLP.Config.enableDebug();`快速定位问题。
