### ISSUE TITLE
关于solr中添加hanlp的分词插件中，配置hanlp.properties的root相对路径

### ISSUE THREAD

**Issue by legenstrike** [hankcs/HanLP#558]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：hanlp-portable.jar1.3.4和hanlp-solr-plugin.jar1.1.2
我使用的版本是：hanlp-portable.jar1.3.4和hanlp-solr-plugin.jar1.1.2

## 我的问题

我是想将hanlp的分词插件加载到solr中来，先已经把hanlp的配置文件hanlp.properties放进来了，data包放到solr项目工程的webContent下了，如果root写的绝对路径是可以正常加载的，如果写成项目的相对路径，就无法找到路径，想请教一下，root可以配置成相对路径吗？该如何配置？，还是说data包不能放到solr项目工程下的webContent下？我看了一下里面之前别人的提问 ，我看到说配置root路径里，是../的方式配置的，请大神解答，谢谢！
另，在solr中的schema文件里配置自定义词库时应该也可以写项目的相对路径吗？写法是不是和root配置是一致的？

## 触发代码
```
 直接启动solr项目
```

### 步骤

1. 首先将hanlp.properties文件放到了solr项目工程的src路径下，通过编译可生成classpath下
2. 然后在WebContent下新建了一个名为hanlp的文件夹
3. 接着将data包放到solr项目工程的WebContent中的hanlp下，
4. 最后修改hanlp.properties里的root路径，我想修改成相对路径，root=../项目名称/hanlp/

### 期望输出

```
期望可以通过相对路径找到data包
```

### 实际输出

```
实际输出，无法载入data包
```

**Comment by hankcs** [comment]
由于不同web容器父进程不同机器不同项目，所以“当前目录”是因人而异的，无法给出一个标准答案。你可以做个简单试验得到自己的当前路径:

```
System.out.println(new File(".").getAbsolutePath());
```

**Comment by legenstrike** [comment]
@hankcs 我是把项目部署到tomcat中的，把hanlp的data包放到web项目的WebContent中可行么？

**Comment by hankcs** [comment]
只要你能把WebContent下的文件打开成一个InputStream，就可以通过实现IOAdapter接口达成目标。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
