### ISSUE TITLE
请问这个项目和哈工大ltp或者复旦的那个相比，主要区别是什么？

### ISSUE THREAD

**Issue by daqulazhang** [hankcs/HanLP#56]
如题，抱歉一下子读不完所有代码就直接请教一下了：）

**Comment by hankcs** [comment]
有些项目是服务于生产的，有些项目是服务于论文的，这会导致它们在代码质量、易用性、运行效率、内存开销上产生巨大差别。只有亲自试一试，你才能知道哪个更适合你。

**Comment by daqulazhang** [comment]
好，确实项目不同和年代会导致一些区别，请问hanlp在设计目标上是为了什么？为了一个商用质量的，还是为了兴趣爱好？

**Comment by hankcs** [comment]
最开始的时候是商业目的，离职后变成了我的爱好。

**Comment by daqulazhang** [comment]
能否加个好友？貌似github不能私信了：（ 我的邮箱是daqula@zhaitech.com ，更详细的我们具体聊好不

**Comment by hankcs** [comment]
好的。

**Comment by mibdennis** [comment]
请问方便加个好友交流吗，我邮箱deny.tsai@gmail.com 谢谢

**Comment by hankcs** [comment]
Hi，我正在海外留学。因为时差，精力和个人喜好问题，不怎么用即时通讯手段。公事的话请在GitHub上发issue，私事请发邮件（地址在每份最新代码顶端）。

**Comment by mibdennis** [comment]
您好，

请问HanLP汉语转拼音的词库来源是哪些？
https://github.com/hankcs/HanLP/blob/master/data/dictionary/pinyin/pinyin.txt

似乎包含了pinyin4j
https://github.com/belerweb/pinyin4j/blob/master/src/main/resources/pinyindb/multi_pinyin.txt

但其它来源是哪些呢？

谢谢！



2018-08-07 14:56 GMT-04:00 hankcs <notifications@github.com>:

**Comment by mibdennis** [comment]
谢谢！
我目前也在美国读master，想引用hanlp做一个商业短语方面的推荐系统小项目，例如一些公司名称之类，测试的时候对比标准的hanlp统计分词和机器学习训练对输入关键词的分词，发现标准分词对一般词汇的分词更准确，但一些商标名称分词不准，后者相反，商标分词较准，一般词汇准确度较低，如物联网被断为物，联网。请问有没有相关词库或者方法帮助提升这方面的准确度呢？

**Comment by hankcs** [comment]
请参考：https://github.com/hankcs/HanLP/issues/884#issuecomment-405066582
另外，如果你讨论的话题与本issue无关，请新开一个，以免打扰到本issue的
subscribe
r。

**Comment by mibdennis** [comment]
感谢🙏！信息非常有帮助。请问您openCorpus项目的目前20M语料库能够公开获取吗？

**Comment by mibdennis** [comment]
问个个人点的问题:) 请问你目前是在读PhD吗？如有冒犯，请勿回答，谢谢

**Comment by ysjiao** [comment]
您好，请问就依存分析而言和哈工大的LTP有什么区别。感谢！
