### ISSUE TITLE
识别人名出错

### ISSUE THREAD

**Issue by feichaohao** [hankcs/HanLP#562]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [√] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.3.4
我使用的版本是：1.3.4
## 我的问题
 使用NLPTokenizer.segment（）方法调用 发现使用"刘飞在打电话" 把其中的“刘飞在” 定性为nr

### 触发代码

```
public class DemoNLPSegment
{
    public static void main(String[] args)
    {
        HanLP.Config.enableDebug();
        Segment segment = HanLP.newSegment().enableOrganizationRecognize(false);
        List<Term> termList = NLPTokenizer.segment("刘飞在打电话");
        System.out.println(termList);
    }
}
```
### 期望输出

```
“刘飞/nr” "在/p" "打电话/vi"
```

### 实际输出

```
[刘飞在/nr, 打电话/vi]
```

**Comment by hankcs** [comment]
感谢反馈，已经修复。
