### ISSUE TITLE
HanLP 汉字转换拼音时，多音字问题，“还款” 结果为：“hai kuan”，求更正。

### ISSUE THREAD

**Issue by blackcoding** [hankcs/HanLP#565]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [ ] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：
我使用的版本是：

## 我的问题

HanLP 汉字转换拼音时，多音字问题，“还款” 结果为：“hai kuan”
### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

```
 public static String convertToPinyinString(String text, String separator, boolean remainNone) {
        List pinyinList = PinyinDictionary.convertToPinyin(text, true);
        int length = pinyinList.size();
        StringBuilder sb = new StringBuilder(length * (5 + separator.length()));
        int i = 1;

        for(Iterator var7 = pinyinList.iterator(); var7.hasNext(); ++i) {
            Pinyin pinyin = (Pinyin)var7.next();
            if(pinyin == Pinyin.none5 && !remainNone) {
                sb.append(text.charAt(i - 1));
            } else {
                sb.append(pinyin.getPinyinWithoutTone());
            }

            if(i < length) {
                sb.append(separator);
            }
        }

        return sb.toString();
    }
```
### 期望输出

```
期望输出
huan kuan

### 实际输出
hai kuan
<!-- HanLP实际输出了什么？产生了什么效果？错在哪里？-->

```
实际输出
```

## 其他信息

<!-- 任何可能有用的信息，包括截图、日志、配置文件、相关issue等等。-->

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。

**Comment by blackcoding** [comment]
我如何使用了？我直接用maven重新下载
![image](https://user-images.githubusercontent.com/16200805/27622120-ac97dd1e-5c07-11e7-949a-03e5a5651d9e.png)reng仍然无法正确解决该问题，我也修改不了
