### ISSUE TITLE
分词错误，问题：你好，请问你们有宝马car的价格吗？

### ISSUE THREAD

**Issue by iwaller** [hankcs/HanLP#568]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [ ] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：v1.3.4
我使用的版本是：v1.2.9

## 我的问题

分词问题：“你好，请问你们有宝马car的价格吗？”，分词结果：[你好/l, ，/w, 请问/v, `你/r, 们/k`, 有/v, 宝马/nz, car/nx, 的/uj, 价格/n, 吗/y, ？/w]，其中词 你们 被分拆开了，应该分为“你们”。

而直接分词：“你们有宝马car的价格吗？”，是没有问题的，只有“请问你们”，这种才会有问题。

## 复现问题

没有修改代码及模型。

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

```
    public void testIssue1234() throws Exception
    {
        List<Term> terms = HanLP.segment("你好，请问你们有宝马car的价格吗？");
        System.out.println(terms);
    }
```
### 期望输出

```
[你好/l, ，/w, 请问/v, 你们/r, 有/v, 宝马/nz, car/nx, 的/uj, 价格/n, 吗/y, ？/w]
```

### 实际输出

```
[你好/l, ，/w, 请问/v, 你/r, 们/k, 有/v, 宝马/nz, car/nx, 的/uj, 价格/n, 吗/y, ？/w]
```

**Comment by hankcs** [comment]
请挂载非mini版模型，或在data/dictionary/CoreNatureDictionary.ngram.mini.txt中加入：

请问@你们 10

**Comment by iwaller** [comment]
非常感谢，经测试，挂载非mini版模型解决。
