### ISSUE TITLE
有没有办法关闭分词后的后缀词性标注

### ISSUE THREAD

**Issue by sunningboy** [hankcs/HanLP#57]
我想得到的结果是分词保留原来的形式，只是分词之后有空格分开，不会出现斜杠和后面的词性标注。
请问怎样办？

**Comment by hankcs** [comment]
分词结果是否展示词性的配置项ShowTermNature=true

**Comment by sunningboy** [comment]
谢谢！不好意思，我没找到。请问是在最新的版本中吗？

**Comment by hankcs** [comment]
不客气，v1.1.3以上

**Comment by sunningboy** [comment]
难怪我没找到。呵呵。我用的版本太低了，现在只能把源代码重新下载下来弄。
另，我想肯定可以用eclipse直接连接github更新，你的更新中提到了“Portable同步升级到v1.2.4”，请问具体怎么弄？还请指点哈，谢谢！

**Comment by hankcs** [comment]
请谷歌git用法。Portable版指的是Maven中央仓库里的版本，该版本将data打包进了jar，所以是便携的。

**Comment by zhangxu5274** [comment]
Segment segment = HanLP.newSegment().enablePartOfSpeechTagging(false);
这样不可以关闭斜杠和后面的词性标注吗？

**Comment by hankcs** [comment]
分词结果是否展示词性的配置项ShowTermNature=true，或在代码中HanLP.Config.ShowTermNature = false;    // 关闭词性显示

**Comment by gyz-GitHub** [comment]
如何在TextRank上面加入词性、词频个数、权重。一块return ?

**Comment by 2efPer** [comment]
设计的不合理…… 自定义的hanlp.properties不应该全部取代默认的配置。应该是自定义的配置有的话覆盖掉默认的配置，不存在就不启用默认的。现在是为了改一个就得把配置全部写一遍，配置还不好找
