### ISSUE TITLE
关于Android的使用

### ISSUE THREAD

**Issue by chendongde310** [hankcs/HanLP#570]
你好，很感谢你们能提供如此优秀的开源库，我想询问一下关于安卓如何使用这个库， 我用的IDE是android studio,例如HanLP.properties应该放哪儿，感谢解答

**Comment by hankcs** [comment]
1. 你可以直接用Gradle引入Maven库，参考：https://github.com/hehonghui/android-tech-frontier/blob/master/issue-17/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8Android-Studio%E6%8A%8A%E8%87%AA%E5%B7%B1%E7%9A%84Android-library%E5%88%86%E5%8F%91%E5%88%B0jCenter%E5%92%8CMaven-Central.md ，不需要.properties文件
1. 还可以直接本地引入portable的jar包，不需要.properties文件
1. 如果要挂载自定义文件，大概将.properties放到src的根目录（与你的com平级）就行了。
1. 已经有人这么干了，似乎跑得还不错

**Comment by chendongde310** [comment]
感谢解答，我的确想挂自定义文件，我将.properties分别放在项目根目录，app、src、java、目录均提示无法找到，日志如下
没有找到hanlp.properties，可能会导致找不到data
                                                         ========Tips========
                                                         请将hanlp.properties放在下列目录：
                                                         Web项目则请放到下列目录：
                                                         Webapp/WEB-INF/lib
                                                         Webapp/WEB-INF/classes
                                                         Appserver/lib
                                                         JRE/lib
                                                         并且编辑root=PARENT/path/to/your/data
                                                         现在HanLP将尝试从null读取data……

**Comment by hankcs** [comment]
哦，那只有用最后的手段了：

```
        Predefine.HANLP_PROPERTIES_PATH = "sd:/absolute/path/to/hanlp.properties";
```

**Comment by CHHJIA** [comment]
你好，想知道你最后解决这个问题了吗？

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
