### ISSUE TITLE
JDK1.6 portable包下报错

### ISSUE THREAD

**Issue by AnyListen** [hankcs/HanLP#572]
## 版本号

当前最新版本号是：hanlp-portable-1.3.4.jar
我使用的版本是：hanlp-portable-1.3.4.jar

## 我的问题

直接新建项目，加入引用hanlp-portable-1.3.4.jar，在jdk1.6环境下以下代码会报错
错误信息
```
2017-6-29 9:31:53 com.hankcs.hanlp.dictionary.TransformMatrixDictionary load
警告: 读取data/dictionary/CoreNatureDictionary.tr.txt失败java.lang.NullPointerException: Inflater has been closed
Exception in thread "main" java.lang.NullPointerException
	at com.hankcs.hanlp.algorithm.Viterbi.compute(Viterbi.java:121)
	at com.hankcs.hanlp.seg.WordBasedGenerativeModelSegment.speechTagging(WordBasedGenerativeModelSegment.java:533)
	at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.segSentence(ViterbiSegment.java:120)
	at com.hankcs.hanlp.seg.Segment.seg(Segment.java:498)
	at Main.main(Main.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

### 触发代码

```
        Segment segment = new ViterbiSegment(){{
            enableIndexMode(false);
            enableOffset(true);
            enableNumberQuantifierRecognize(false);
            enableOrganizationRecognize(true);
            enableCustomDictionary(true);
            enablePlaceRecognize(true);
            enableNameRecognize(true);
            enableJapaneseNameRecognize(false);
            enableTranslatedNameRecognize(false);
            enablePartOfSpeechTagging(true);
        }};
        System.out.println(segment.seg("看一下小王的日报"));
```
## 其他信息
1. 注释`enablePlaceRecognize(true);`可正常运行；
2. 使用portable源码调试无报错。

**Comment by hankcs** [comment]
1. 感谢反馈
1. 据说这是JDK的bug：https://stackoverflow.com/questions/4696013/java-lang-nullpointerexception-inflater-has-been-closed-on-inputstreamreader ，会在读取jar内部的资源时触发，似乎无法解决：https://github.com/MachinePublishers/jBrowserDriver/issues/227#issuecomment-267739452
1. 我当时在Windows jdk1.6下没有遇到这个问题。这是否是偶发问题？是否可以通过更高小版本的jdk1.6避免？

**Comment by AnyListen** [comment]
@hankcs 
如果使用portable包按照上述代码，为100%报错；不是偶发性质；
已经使用最新版本JDK1.6

**Comment by hankcs** [comment]
Google了一下，这是影响了很多项目的jdk6老bug：http://bugs.java.com/view_bug.do?bug_id=7003462

sun官方标注
Affected Versions:
6u22
Fixed Versions:
7 (b123)

我目前手头没有旧的jdk，应该也没有精力去应付整个互联网都无法解决的旧bug。只能提出一些规避建议：

虽然你这样调用每次都失败了，但所有tr.txt的加载都是用的一样的代码，不是100%触发。是不是有一些规避手段？

比如在程序一开始的时候手动触发data/dictionary/place/ns.tr.txt的加载：

```
        if (PersonDictionary.transformMatrixDictionary.transititon_probability != null)
        {
            System.out.println("规避了");
        }
```

**Comment by hankcs** [comment]
1. 重新加载可能解决不了这个问题，你可以试试`ByteArray.createByteArray("data/dictionary/organization/nt.txt.bin")`，应该无论几次都会失败，这是jdk1.6的bug
1. 避免断言异常只是掩盖失误而已，加载失败了就应该尽早终止。
1. 不知道加载txt会不会成功，可以尝试写个IOAdapter，在java1.6中将"data/dictionary/organization/nt.txt"重定向到一个合法的路径。

**Comment by AnyListen** [comment]
@hankcs 
1. 正在测试
2. 我的意思不是为了避免断言，而是判断size后，如果不合法直接返回加载失败；而不是让程序报错

**Comment by hankcs** [comment]
感谢建议，的确应该return false并做一个判断。

**Comment by AnyListen** [comment]
确实无法解决，使用备用文件就会增加代码复杂性；
