### ISSUE TITLE
单例模式,使用一段时间(1~2天左右)就存在内存溢出,内存配置了2G

### ISSUE THREAD

**Issue by bandhzh** [hankcs/HanLP#574]
请问下  我这样使用有没有什么问题
我截取部分代码

@Component
@Service("aiServiceHit")
public class AiServiceByHit implements IAIService {
        private Segment segment = new NShortSegment().enableAllNamedEntityRecognize(true).enableNumberQuantifierRecognize(true).enablePartOfSpeechTagging(true);

	@Override
	public boolean answerService(RequestDto requestDto) {
                   这里部分代码这样使用 
                  
                        List<Term> seg = segment.seg(text);
			LOG.info("分词算法:" + JSONArray.toJSONString(seg));
			List<String> getNsV = new ArrayList<String>();//名词集合
			for(Term t : seg){
				switch (t.nature) {
				case n://名词
				case nx:
				case ns:
				case nz:
				case nf:
				case nt:
				case m:
				case mq:
				case Mg:
					getNsV.add(t.word.toLowerCase());
					break;
				default:
					break;
				}
			}
                    下面就是部分业务
        }
}

现在的异常提醒：
J 7395 C1 com.hankcs.hanlp.recognition.nr.TranslatedPersonRecognition.Recognition(Ljava/util/List;Lcom/hankcs/hanlp/seg/common/WordNet;Lcom/hankcs/hanlp/seg/common/WordNet;)V (238 bytes) @ 0x00007f3c6dc7fe44 [0x00007f3c6dc7f720+0x724]
J 7488 C1 com.hankcs.hanlp.seg.NShort.NShortSegment.segSentence([C)Ljava/util/List; (420 bytes) @ 0x00007f3c6d46a9b4 [0x00007f3c6d469960+0x1054]
J 7618 C1 com.hankcs.hanlp.seg.Segment.seg(Ljava/lang/String;)Ljava/util/List; (458 bytes) @ 0x00007f3c6d42d12c [0x00007f3c6d42a9c0+0x276c]

是不是我的使用方法有误呢？

**Comment by hankcs** [comment]
1. 算法库内部未储存任何有关输入的数据，理论上不存在内存泄露
1. 请脱离业务逻辑，本地循环一万次、一亿次验证上述观点
1. N-最短路复杂度较高，不适合生产用，在瞬发输入较大的时候的确可能内存溢出（但不是泄露）。可换用其他分词器
1. 这不是个友好的issue。

**Comment by mythuyun** [comment]
我也遇到hanlp做实体提取和摘要时会内存泄漏的问题，使用hanlp时有什么地方需要注意吗
