### ISSUE TITLE
发现CustomDictionary字典，只有最后add()或insert()的词条，才会在分词中生效？！

### ISSUE THREAD

**Issue by Zhufei** [hankcs/HanLP#575]
# HanLP版本号
环境1：字典 v1.3.3（full）+jar包 v1.3.4
环境2：字典 v1.2.8（mini）+jar包 v1.2.8
# 我的问题
实验发现，不论是修改.txt并刷新.bin字典文件，还是途经CustomDictionary.add()|insert()方法，都是只有最后附加上去的自定义词条，在分词时才生效？！
# 复现问题
原文：北京海淀区，西八里庄，裕友大厦3层；
字典：
裕友大厦 ns 100
西八里庄 ns 100
分词结果：北京/ns 海淀/ns 区/n ，/w 西八里庄/ns ，**/w 裕/vg 友/ng 大厦/n** 3层/mq ；/w
字典：（仅调换自定义词条的次序）
西八里庄 ns 100
裕友大厦 ns 100
分词结果：北京/ns 海淀/ns 区/n ，/w **西/f 八里庄/ns** ，/w 裕友大厦/ns 3层/mq ；/w
# 继续试验
附加2个无意义的词条（“西八里”，“裕友”），就好了！
字典：
**西八里** ns 100
西八里庄 ns 100
**裕友** ns 100
裕友大厦 ns 100
分词结果正常：
北京/ns 海淀区/ns ，/w 西八里庄/ns ，/w 裕友大厦/ns 3层/mq ；/w
# 临时解决方法：
将未能成功组合分词的词条，在自定义字典中，拷贝2次！
字典：
西八里庄 ns 1
**西八里庄** ns 1
裕友大厦 ns 1
**裕友大厦** ns 1
分词结果正常：
北京/ns 海淀区/ns ，/w **西八里庄/ns** ，/w **裕友大厦/ns** 3层/mq ；/w
# 请教
@hackers
1：有无正规的解决方法？
2：能否比较清晰地，将最常用的ViterbiSegment使用字典分词时的优先级理解，明确声明一下？
3：什么样的自定义分词可以通过修改自定义词条解决，什么样的自定义分词则必须修改其它（专属）字典？

**Comment by Zhufei** [comment]
好奇怪啊！如果前面再附加2个无意义的词条（“西八里”，“裕友”），就好了！
字典：
西八里 ns 100
西八里庄 ns 100
裕友 ns 100
裕友大厦 ns 100
分词结果：
北京/ns 海淀区/ns ，/w 西八里庄/ns ，/w 裕友大厦/ns 3层/mq ；/w

@hackers
能否比较清晰地，将最常用的ViterbiSegment使用字典分词时的优先级理解，明确声明一下？
什么样的自定义分词可以通过修改自定义词条解决，什么样的自定义分词则必须修改其它（专属）字典？

**Comment by hankcs** [comment]
感谢反馈，抱歉无法复现你的问题。

```
        CustomDictionary.insert("裕友大厦", "ns 100");
        CustomDictionary.insert("西八里庄", "ns 100");
        Segment segment = new ViterbiSegment();
        System.out.println(segment.seg("北京海淀区，西八里庄，裕友大厦3层；"));
```

输出

[北京/ns, 海淀/ns, 区/n, ，/w, 西八里庄/ns, ，/w, 裕友大厦/ns, 3/m, 层/qv, ；/w]

1. 请检查你的自定义词典编码等是否符合要求，或者直接在data/dictionary/custom/CustomDictionary.txt 里面加。
1. 词典已经是老生常谈的问题了，see https://github.com/hankcs/HanLP/wiki/FAQ#%E4%B8%BA%E4%BB%80%E4%B9%88%E4%BF%AE%E6%94%B9%E4%BA%86%E8%AF%8D%E5%85%B8%E8%BF%98%E6%98%AF%E6%B2%A1%E6%9C%89%E6%95%88%E6%9E%9C ，或者搜索issue区，数以百计的提问都在重复这些问题。
1. 我只啰嗦最后一遍吧，自定义词典用于合并。当修改自定义词典解决不了问题的时候，修改ngram。当命名实体错误的时候，修改命名实体模型。
1. 跑个题，这段答案并非针对任何个人，而是针对目前重复提问的现象。有人会说，怎么修改，没文档啊，能不能说得清晰一点？通俗一点？让谁都明白？其实问题不是没有文档，也不是没有说明，答案早就白纸黑字写在那里了，博客上剖析了张华平教授的一整套算法原理，项目主页每段demo下面都有链接整理得一清二楚。唯一的问题是文档太多了，没人愿意静下心来看，都希望有个“客服”帮忙打工，跳过数学基础，把这些知识嚼烂了喂到脑袋里，早点应付完老板的差事下班打游戏去。

**Comment by AnyListen** [comment]
貌似把自定义的词条添加到自定义词典的文件开头，同时删除缓存的bin文件，即可生效

**Comment by Zhufei** [comment]
非常感谢，只有继续认真学习HMM及CRF分词的原理了！

**Comment by bushuaigege** [comment]
哈哈~跑个题这个形容的很贴切
#53 
#453 
在看过很多个类似问题后，想确认个问题：
环境：自定义词典和核心词典存在重复的词语，需要以自定义词典的词性为优先，不更改核心词典txt
看之前问题中的处理是通过api插入词典，没有配置，对于这种场景是只能api插入是把

**Comment by bushuaigege** [comment]
@hankcs  哈哈~跑个题这个形容的很贴切
#53
#453
在看过很多个类似问题后，想确认个问题：
环境：自定义词典和核心词典存在重复的词语，需要以自定义词典的词性为优先，不更改核心词典txt
看之前问题中的处理是通过api插入词典，没有配置，对于这种场景是只能api插入是把

**Comment by hankcs** [comment]
最新版没有做排重，通过文件和api插入的词条一视同仁。
