### ISSUE TITLE
TextRank 里面 max_iter = 200 如果文本字数多，性能有影响

### ISSUE THREAD

**Issue by zhaoxuan** [hankcs/HanLP#577]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [ ] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.3.4
我使用的版本是：1.3.4

## 我的问题

com.hankcs.hanlp.summary.TextRankKeyword#max_iter = 200 是 protect 的，我发现我在处理大量文本时候，出现性能问题，一次调用需要消耗 200-300ms ，可以把这个变量改成 public 的，方便我在包外修改

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

```
    public void testIssue1234() throws Exception
    {
        CustomDictionary.add("用户词语");
        System.out.println(StandardTokenizer.segment("触发问题的句子"));
    }
```
### 期望输出

```
期望输出
```

### 实际输出

```
实际输出
```

**Comment by hankcs** [comment]
感谢反馈，已经开放，请参考上面的commit。
如果还有问题，欢迎重开issue。
