### ISSUE TITLE
字符类型对应表加载失败

### ISSUE THREAD

**Issue by jdb110** [hankcs/HanLP#58]
在windows下正常，放到centos下去跑，出现这个提示。

**Comment by jdb110** [comment]
Sep 18, 2015 5:49:58 PM com.hankcs.hanlp.dictionary.CoreDictionary load
INFO: 核心词典开始加载:data/dictionary/CoreNatureDictionary.txt
Sep 18, 2015 5:49:58 PM com.hankcs.hanlp.dictionary.CoreDictionary <clinit>
INFO: data/dictionary/CoreNatureDictionary.txt加载成功，153116个词条，耗时65ms
Sep 18, 2015 5:49:58 PM com.hankcs.hanlp.dictionary.other.CharType <clinit>
INFO: 字符类型对应表开始加载
Sep 18, 2015 5:49:58 PM com.hankcs.hanlp.corpus.io.IOUtil readBytes
WARNING: 读取时发生异常java.io.FileNotFoundException:  (No such file or directory)
字符类型对应表加载失败：

**Comment by hankcs** [comment]
我在Ubuntu和centos下面测试没有问题，半年来也没有接到过其他linux用户的类似报告，请确认jar版本是否最新？

**Comment by jdb110** [comment]
谢谢hankcs，修改了hanlp.dictionary.other.CharType忘了改过来。不好意思。
