### ISSUE TITLE
对“训练HMM-NGram分词模型”产生的问题和理解

### ISSUE THREAD

**Issue by hx78** [hankcs/HanLP#582]
对你在 [训练分词模型](https://github.com/hankcs/HanLP/wiki/%E8%AE%AD%E7%BB%83%E5%88%86%E8%AF%8D%E6%A8%A1%E5%9E%8B) 中提到的HMM-NGram分词模型产生了几个问题

1、HMM是由输出量求输入量的模型，请问这里的分词输出量是什么，是指分词的序列吗？那输入量又是什么呢？

HanLP中使用了一阶隐马模型，在这个隐马尔可夫模型中，隐状态是词性，显状态是单词。见[词性标注](http://www.hankcs.com/nlp/part-of-speech-tagging.html)

2、训练后一共得出3个文件：

CoreNatureDictionary.txt：单词词性词典
CoreNatureDictionary.ngram.txt：二元接续词典
CoreNatureDictionary.tr.txt：词性转移矩阵

请问这几个字典的作用？你能简单地用最短分词结合上面的字典做一个梳理吗，即是如何分词，又是如何做词性标注的？

我的理解：

CoreNatureDictionary.txt和CoreNatureDictionary.ngram.txt是用来分词的，CoreNatureDictionary.tr.txt是用来做词性标注的。在S-segment中，先通过动态规划，即用字典CoreNatureDictionary.txt和CoreNatureDictionary.ngram.txt生成词图（动态规划路径图），然后选择最短的路径。这里只是用到了MM，并没有用到HMM，属于机械式规则+统计的分词方法。
而CoreNatureDictionary.tr.txt正如问题1的说的，根据输入的分词序列来判断词性的序列。

有资料中说到，分词方法的演进，可分为
1、机械式规则
2、规则+统计
3、MM+Viterbi
4、由字构词
5、神经网络

我认为3其实也是2，MM首先也要将句子进行动态规划进行分词（机械规则），也就是查字典，先将句子中所有可以查到的词（查核心字典），先划分出来，然后按时词到词出现的顺序（二元连续字典）生成路径的权重，也就是构造词图。

**Comment by hankcs** [comment]
我从未使用“输出量”等词语，硬要说的话，是“词网”上的一条路径。词网是我自己定义的概念，指的是句子所有构词形成的网状有向图。

你的理解大致无误，但完整的理解需要依次阅读如下资料：

- NGram分词
    - NGram语言模型
    - [NGram词网上的最短路径](http://www.hankcs.com/nlp/%E7%BB%B4%E7%89%B9%E6%AF%94%E7%AE%97%E6%B3%95%E5%9C%A8%E5%88%86%E8%AF%8D%E4%B8%AD%E7%9A%84%E5%BA%94%E7%94%A8.html)（注：称作维特比算法是谬误）
    - [NGram词网上的N-最短路径](http://www.hankcs.com/nlp/segment/n-shortest-path-to-the-java-implementation-and-application-segmentation.html)
- HMM分词与词性标注、命名实体识别
    - [隐马尔可夫模型](http://www.hankcs.com/ml/hidden-markov-model.html)
    - [HMM与分词、词性标注、命名实体识别](http://www.hankcs.com/nlp/hmm-and-segmentation-tagging-named-entity-recognition.html)
    - [基于HMM2-Trigram字符序列标注的中文分词器Java实现](http://www.hankcs.com/nlp/segment/second-order-hidden-markov-model-trigram-chinese-participle.html)
- CRF分词
    - [条件随机场](http://www.hankcs.com/ml/conditional-random-field.html)
    - [CRF分词的纯Java实现](http://www.hankcs.com/nlp/segment/crf-segmentation-of-the-pure-java-implementation.html)
- 感知机分词（补充材料）
    - [感知机](http://www.hankcs.com/ml/the-perceptron.html)
    - [200行Python代码实现感知机词性标注器](http://www.hankcs.com/nlp/averaged-perceptron-tagger.html)
    - [基于结构化平均感知机的分词器Java实现](http://www.hankcs.com/nlp/segment/implementation-of-word-segmentation-device-java-based-on-structured-average-perceptron.html)

全部细节都在这些文章里，没看的人以为这些txt是词典，看懂了就知道是什么了。

**Comment by TylunasLi** [comment]
关于把NGram的分词模型看作HMM的原因，可以参看刘群等《基于层叠隐马模型的汉语词法分析》。第3节中的意思是。将核心词典中的词语看作隐状态，输出词语看作观察值，如果词语在核心词典收录，则该词语的发射概率=1，即对没有命名实体的句子仅仅计算状态转移概率，在分词过程中，我们需要考虑未登录词的发射概率．
根据我的了解，这个模型又称作基于类别的NGram语言模型，但公式是基本一致的。［参看《自然语言处理纵论（Speech And Language Processing）》］，ICTCLAS，哈工大早期版本的LTP中的HIT-IRLAS（非开源），以及ANSJ分词采用的应该都是该文章的思想。仅有HanLP中的命名实体没有发射概率。

**Comment by javiy-lee** [comment]
你好！请问mini ngram是按什么规则裁剪出来的？

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
