### ISSUE TITLE
"仙剑奇侠传"多音字拼音（chuan）

### ISSUE THREAD

**Issue by mjz9054** [hankcs/HanLP#583]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：
我使用的版本是：
```
<dependency>
    <groupId>com.hankcs</groupId>
    <artifactId>hanlp</artifactId>
    <version>portable-1.3.4</version>
</dependency>	
```

## 我的问题
“仙剑奇侠传”得到的拼音是“xian,jian,qi,xia,chuan”

### 触发代码

```java
@Test
public void testPinyin() {
    String word = "仙剑奇侠传";
    System.out.println(word + ": " + HanLP.convertToPinyinString(word, ",", false));
}
```
### 期望输出

```
xian,jian,qi,xia,zhuan
```

### 实际输出

```
xian,jian,qi,xia,chuan
```

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。

**Comment by wchnjstar123** [comment]
类似情况还有：
楚乔传--》 增加    **乔传=qiao2,zhuan4**
三国群英传--》增加   **英传=ying1,zhuan4**
