### ISSUE TITLE
停止词中添加控制字符的问题

### ISSUE THREAD

**Issue by weiker** [hankcs/HanLP#584]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

当前最新版本号是：1.3.4
我使用的版本是：1.3.4

我希望在停用词中添加 "\t"  这样的控制字符 ,因为切分 "运动用途	用法"(中间是"\t")这个词的时候结果是:
运动/vn
用途/n
	/nx
法/n

不知道为什么把制表符认为成了字母专名.
然后我再stopword.txt中添加"	" 当读取停止词词典就报下边的错:

严重: 载入停用词词典D:/Idea_workplace/HanLP/data/dictionary/stopwords.txt失败java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:658)
	at com.hankcs.hanlp.collection.MDAG.MDAG.replaceOrRegister(MDAG.java:541)
	at com.hankcs.hanlp.collection.MDAG.MDAG.<init>(MDAG.java:220)
	at com.hankcs.hanlp.collection.MDAG.MDAG.<init>(MDAG.java:170)
	at com.hankcs.hanlp.collection.MDAG.MDAGSet.<init>(MDAGSet.java:42)
	at com.hankcs.hanlp.dictionary.stopword.StopWordDictionary.<init>(StopWordDictionary.java:44)
	at com.hankcs.hanlp.dictionary.stopword.CoreStopWordDictionary.<clinit>(CoreStopWordDictionary.java:42)
	at com.hankcs.demo.DemoCustomDictionary.main(DemoCustomDictionary.java:79)

不知道是不是我的用法有问题?

感谢大神的开源,方便我很多  :)

**Comment by hankcs** [comment]
1. 由于语料库中不可能存在控制字符，所以简单地将所有ASCII归入了nx。现在做了改进，归入分隔符
1. \t等控制字符可以动态加入，详见https://github.com/hankcs/HanLP/blob/1f29a353c9ddc3d56fbb9d8e76241684dfd3a73f/src/test/java/com/hankcs/demo/DemoStopWord.java#L33

**Comment by weiker** [comment]
大神  ,  那个手动添加停止词的方法我试过了  可以添加成功,然后其实我上边的问题不只是添加控制字符到停止词的问题,切词的结果也有点不对

如果被切分的词是"\t用途",切分出来的结果是:
	/nx
用/p
途/ng

但是如果没有这个制表符,结果就是:
用途/n

这个制表符是不是影响了词网的形成?  我不太懂这个分词的算法.
感谢大神回复

**Comment by hankcs** [comment]
删除data/dictionary/other/CharType.bin，编译版本库最新代码即可

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
