### ISSUE TITLE
"大学城里"分词错误的问题

### ISSUE THREAD

**Issue by fanyongbin** [hankcs/HanLP#586]
## 版本号

当前最新版本号是：v1.3.4
我使用的版本是：v1.3.4

## 我的问题

对以下句子进行分词"深圳大学城里各大国内外知名高校合办学校校牌在阳光下熠熠发光。"
发现“深圳大学城里”分词错误，可以在CoreNatureDictionary.ngram.txt中添加"大学城@里 10"解决该问题。

### 触发代码

```
public class DemoSegment
{
    public static void main(String[] args)
    {
        String[] testCase = new String[]{
                "深圳大学城里各大国内外知名高校合办学校校牌在阳光下熠熠发光。毗邻深圳大学城的是以创新产业为发展核心"
        };
        for (String sentence : testCase)
        {
            List<Term> termList = HanLP.segment(sentence);
            System.out.println(termList);
        }
    }
}

```
### 期望输出

```
深圳大学/ntu, 城里/s, 各/rz, 大/a, 国内外/s, 知名/a, 高校/n
```

### 实际输出

```
深圳/ns, 大学城/nz, 里/f, 各/rz, 大/a, 国内外/s, 知名/a, 高校/n
```

**Comment by hankcs** [comment]
1. 个人觉得实际输出更符合习惯
1. 加入`大学城@里`后，得到[深圳大学城/nz, 里/f, 各/rz, 大/a, 国内外/s, 知名/a, 高校/n, 合办/v, 学校/nis, 校牌/n, 在/p, 阳光/n, 下/f, 熠熠/z, 发光/vi]

**Comment by hankcs** [comment]
问题应该解决了，如果还有问题，欢迎重开issue。

**Comment by fanyongbin** [comment]
谢谢，因实际需求，需将“深圳大学城里”分为“深圳/大学城/里”，避免分为“深圳/大学/城里”，而关联到机构深圳大学。
