### ISSUE TITLE
代码质量太差

### ISSUE THREAD

**Issue by gitchennan** [hankcs/HanLP#587]
这个项目是个好东西，可惜代码质量太差
特别是 IO读写的地方，很多inputStream，outputStream打开了就没关闭过，会造成资源泄露。

下面的代码，br.readLine()抛异常后，这个流就永远不会被关闭。。。
我尝试修改这个项目的代码，发现这样低质量代码实在太多根本改不过来
try
        {
            BufferedReader br = new BufferedReader(new InputStreamReader(new FileInputStream(path), "UTF-8"));
            while ((line = br.readLine()) != null)
            {
                Map.Entry<String, Map.Entry<String, Integer>[]> args = EnumItem.create(line);
                EnumItem<NR> nrEnumItem = new EnumItem<NR>();
                for (Map.Entry<String, Integer> e : args.getValue())
                {
                    nrEnumItem.labelMap.put(NR.valueOf(e.getKey()), e.getValue());
                }
                valueList.add(nrEnumItem);
            }
            br.close();
        }
        catch (Exception e)
        {
            logger.severe("读取" + path + "失败[" + e + "]\n该词典这一行格式不对：" + line);
            return null;
        }

**Comment by hankcs** [comment]
1. 的确这是我很久之前写的IO接口，那时要求支持JDK1.6，我又不想啰嗦catch套catch
1. 这套IO速度比Java其他接口快
1. 但这个库是个自然语言处理算法库，IO的确弱但只占代码的极小一小部分，不是重点，也没放太多精力。
1. 欢迎pr，不欢迎呵呵
