### ISSUE TITLE
在Spark单机使用正常，map到节点上使用出现错误

### ISSUE THREAD

**Issue by fishermanff** [hankcs/HanLP#588]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.3.4
我使用的版本是：1.3.4

@hankcs 您好，按照您说的方法，修改配置
root=hdfs://localhost:9000/hanlpdata/
IOAdapter=com.xxx.HDFSIOAdapter
而且在scala重写了接口：
class HadoopFileIoAdapter extends IIOAdapter {
    @Override
    def open(path: String): java.io.InputStream = {
        val conf: Configuration = new Configuration();
        val fs: FileSystem = FileSystem.get(URI.create(path), conf);
        fs.open(new Path(path));
    }    

    @Override
    def create(path: String): java.io.OutputStream = {
        val conf: Configuration = new Configuration();
        val fs: FileSystem = FileSystem.get(URI.create(path), conf);
        fs.create(new Path(path));
    }
}
HanLP.Config.IOAdapter = new HadoopFileIoAdapter();

也只能在单机spark下运行分词
scala> System.out.println(HanLP.segment("你好，欢迎使用HanLP汉语处理包！"));
[你好/vl, ，/w, 欢迎/v, 使用/v, HanLP/nx, 汉语/gi, 处理/vn, 包/v, ！/w]

分发到节点的时候就出错了，请问你们在集群上使用的时候是否遇到过这种问题？需要注意哪些坑呢？
val a = sc.parallelize(Seq("中国的神威太湖之光计算机被用于天气预报","制药研究和工业设计等领域。"))
val res = a.map(e=>{
        HanLP.segment(e).toString
    })
res take 2 foreach println

Exit code: 255
Stack trace: ExitCodeException exitCode=255:
	at org.apache.hadoop.util.Shell.runCommand(Shell.java:578)
	at org.apache.hadoop.util.Shell.run(Shell.java:489)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:755)
	at org.apache.hadoop.yarn.server.nodemanager.LinuxContainerExecutor.launchContainer(LinuxContainerExecutor.java:297)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by wl142857** [comment]
我今天在spark试了一下，也是一模一样的问题!!求解~~

**Comment by fishermanff** [comment]
@wl142857 还没解决呢，你跑通了的话来share一下哈

**Comment by hankcs** [comment]
1. 可能是因为这些类都没实现序列化接口，参考： https://github.com/hankcs/HanLP/issues/236#issuecomment-303053503
1. 我不是spark工程师，需要社区贡献才能解决这个问题

**Comment by fishermanff** [comment]
@hankcs 感谢回复，期待后续有hadoop高手解决这问题

**Comment by fishermanff** [comment]
@wl142857 问题已解决，
1.  将类实现序列化接口
2. 把data文件放到hdfs上写绝对路径让每个节点可读

**Comment by Canappeco** [comment]
@fishermanff 你好！
最近我也想要实现在spark上运行，但是在序列化问题上卡住了。请问您说的“将类实现序列化接口”是指的哪一个或哪几个类？具体实现要怎么做？

非常期待您的回答，也希望能分享相关参考资料。谢谢！

**Comment by fishermanff** [comment]
@Canappeco @hankcs 已提交pull request

**Comment by Canappeco** [comment]
非常感谢，我目前的解决方法是在最外层的类上面实现序列化接口，这样在集群上跑起来虽然没有错误，但感觉速度上有点慢。当然，最佳的解决方案是在第三方类库实现序列化，我这种方法牺牲了相当一部分时间用于节点通信。

而且好像在要调用的类或者方法外面套上一层static也能支持spark集群调用，这可能是因为套上static关键字之后，在分发节点的时候会把整个static内的东西都发送到各个节点上。

**Comment by hankcs** [comment]
各位Spark用户对 @fishermanff 的贡献有什么建议可以尽管提。很多类都是工具类，连static成员都没有，Spark该不会连工具类都要实现序列化接口吧。

**Comment by fishermanff** [comment]
@hankcs 同意，有些类应该不需要实现序列化，欢迎各位优化出一个适合Spark集群使用的版本

**Comment by cyq130** [comment]
直接在mappartition中调用是没有问题的
val data_seg = data_split.mapPartitions(myfuncPerPartition)

def myfuncPerPartition ( iter : Iterator [String] ) : Iterator [String] = {
    println("run in partition")
    HanLP.Config.IOAdapter = new HadoopFileIoAdapter
    var res = for (e <- iter )  yield HanLP.segment(e).toString + "\002" + e
    res
  }

**Comment by theOtherWorld** [comment]
将data文件设为全局数据不可以吗

**Comment by zongwu233** [comment]
看了一下HanLP源码里关于初始化的部分，在第一次调用HanLP类的方法的时候，很多对象才被创建，data目录的资料才被加载。
在spark上，其实只要避免在 RDD.map()方法之外创建HanLP相关类的对象，就避免了HanLP 相关类对象在 spark 节点之间传输，也就不需要改造目前的类为序列化类了。
最简单的办法就像@cyq130  所说，在`RDD.foreachPartition` 方法里面再初始化HanLP即可。
如果改造相关类为序列化类并在driver中就初始化HanLP，势必造成data的数据在driver加载（因为相关类被实例化），然后序列化给每个task。这样做不算是最佳方式。
在`RDD.foreachPartition` 方法里初始化，让各个`Partition`自己加载数据，是在spark中访问外部资源的常用做法。比如建立与Hbase的connection。
目前我的做法是：
将data目录上传到spark集群，将该文件的HDFS URI 值写到 `hanlp.properties`的 `root `
spark中调用HanLP的实例代码：
```scala
val message =
    "受一桩涉及 5000 万用户信息泄露事件的舆论打击，Facebook 的股价从 19 日开始经历了近乎断崖式的下跌，单日内最大跌幅达到 7.92% ... Facebook、阿里巴巴这两家公司的价值分析没有太多可比性，两家的业务交集微乎其微，且短期内影响公司股价与市值的因素十分琐碎，"

    val a = sparkContext.parallelize(message.split("，"))
    a.foreachPartition(it => {
      HanLP.Config.IOAdapter = new HadoopFileIoAdapter
      for (elem <- it) {
        val result = HanLP.segment(elem)
        loger.warn("start------")
        result.forEach(new Consumer[Term] {
          override def accept(t: Term): Unit = {
            loger.warn("segment:" + t.word)
          }
        })

      }

    })
```

其中 HadoopFileIoAdapter  的实现：
```scala
class HadoopFileIoAdapter extends IIOAdapter {

  override def create(path: String): OutputStream = {
    val conf: Configuration = new Configuration()
    val fs: FileSystem = FileSystem.get(URI.create(path), conf)
    fs.create(new Path(path))
  }

  override def open(path: String): InputStream = {
    val conf: Configuration = new Configuration()
    val fs: FileSystem = FileSystem.get(URI.create(path), conf)
    fs.open(new Path(path))
  }
}
```

**Comment by hankcs** [comment]
@zongwu233 很好的发现！

也有一些类是在new的时候触发IO的，并且实现了序列化接口。但同样不建议在节点间传输这些类的实例，因为根据经验：

1. Java的序列化反序列化非常缓慢，比HanLP实现的binary IO机制慢很多
1. Java序列化的对象体积也比binary大很多

还不如让每个节点自行创建新对象加载来得快。

**Comment by hankcs** [comment]
Hi， @zongwu233 

欢迎提交PR，或者测试 https://github.com/hankcs/HanLP/pull/608 是否满足需求，谢谢。

**Comment by willysys** [comment]
@zongwu233 可以考虑mapPartitions(),该接口是transform方法，并且有返回值。

**Comment by zongwu233** [comment]
先试试 @willysys  的建议

**Comment by luyao618** [comment]
我用了重写IIOAdapter的方式读取在hdfs的词典没什么问题。不过感觉将词典的bin二进制文件打到jar包内，然后直接读取jar内的词典更方便一点。
我使用的maven assembly的方式打包，然后
配置文件：
root=
IOAdapter=com.hankcs.hanlp.corpus.io.ResourceIOAdapter
CustomDictionaryPath=data/dictionary/custom/CustomDictionary.txt; MyDic.txt
在spark 上map和mapPartitions都可以调用，测试ok

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
