### ISSUE TITLE
猜测最可能的词性方法数组越界

### ISSUE THREAD

**Issue by z172362753** [hankcs/HanLP#590]
com.hankcs.hanlp.seg.common.Vertex
 public Nature guessNature() {
        return attribute.nature[0];
    }

这个方法数组越界

**Comment by TylunasLi** [comment]
请给出能引发问题的代码。根据我的了解，构造不了没有词性何频率的Attribute

**Comment by hankcs** [comment]
由于未提供足够信息，所以只能关闭这个issue。欢迎参考[《如何提问》](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，重新提一个友好的issue。造成不便望海涵，谢谢合作。
