### ISSUE TITLE
关键词提取可能会把自定义词性的词全部过滤掉

### ISSUE THREAD

**Issue by FelixHo** [hankcs/HanLP#595]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [ x ] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.3.4
我使用的版本是：1.3.4

## 我的问题

关键词提取时会去掉停用词，即通过 KeywordExtractor的shouldInclude()方法，
任何自定义词性如果首字母满足switch条件，都会被作为停用词去掉，无法提取任何自定义词性的词汇作为关键词。我在复现步骤提供一个简单的case。
shouldInclude 的代码如下:
```
public boolean shouldInclude(Term term)
    {
        // 除掉停用词
        if (term.nature == null) return false;
        String nature = term.nature.toString();
        char firstChar = nature.charAt(0);
        switch (firstChar)  
        {
            case 'm':
            case 'b':
            case 'c':
            case 'e':
            case 'o':
            case 'p':
            case 'q':
            case 'u':
            case 'y':
            case 'z':
            case 'r':
            case 'w':
            {
                return false;
            }
            default:
            {
                if (term.word.trim().length() > 1 && !CoreStopWordDictionary.contains(term.word))
                {
                    return true;
                }
            }
            break;
        }

        return false;
    }
```
### 触发代码

```
    public void testIssue1234() throws Exception
    {
        CustomDictionary.add("我是自定义的词", "mZiDingYi 1111");
        String msg = "测试一下,我是自定义的词我是自定义的词我是自定义的词我是自定义的词,测试一下";
        System.out.println(HanLP.segment(msg));
        System.out.println(TextRankKeyword.getKeywordList(msg, 100));
    }
```
### 期望输出

```
[测试/vn, 一下/m, ,/w, 我是自定义的词/mZiDingYi, 我是自定义的词/mZiDingYi, 我是自定义的词/mZiDingYi, 我是自定义的词/mZiDingYi, ,/w, 测试/vn, 一下/m]
[测试, 我是自定义的词]
```

### 实际输出

```
[测试/vn, 一下/m, ,/w, 我是自定义的词/mZiDingYi, 我是自定义的词/mZiDingYi, 我是自定义的词/mZiDingYi, 我是自定义的词/mZiDingYi, ,/w, 测试/vn, 一下/m]
[测试]
```

**Comment by congpeixin** [comment]
你把自定义词词性的首字母换一个字母啊，换一个case里面不包括的

**Comment by FelixHo** [comment]
@congpeixin 我认为避开 case 并不是一种优雅的方式 ，没有实质性解决问题，当然它可以算是一种取巧的方式。考虑到大部分调用者可能不会深入阅读每一行代码细节，所以依然会潜在"风险"。

**Comment by hankcs** [comment]
1. 文档写了：https://github.com/hankcs/HanLP/wiki/FAQ#%E9%BB%98%E8%AE%A4%E7%9A%84%E5%81%9C%E7%94%A8%E8%AF%8D%E8%BF%87%E6%BB%A4%E5%99%A8%E4%B8%8D%E6%BB%A1%E6%84%8F
1. 所有语料库的词性标注集都遵从“前缀表示大类”这个约定速成的习惯，入乡随俗吧

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
