### ISSUE TITLE
BaseNode编译错误

### ISSUE THREAD

**Issue by fanjun1980** [hankcs/HanLP#6]
发现BaseNode的walkToLoad方法有编译错误。
错误信息：
>The method walkToLoad(ByteArray, BaseNode.ValueArray) in the type BaseNode is not applicable for the arguments (ByteArray, BaseNode<V>.ValueArray)

**Comment by hankcs** [comment]
https://github.com/hankcs/HanLP/commit/453ea981eee7b860590f3d16e67e40b768bd14ab#commitcomment-10509610

**Comment by hankcs** [comment]
最近干脆将这个问题解决了
https://github.com/hankcs/HanLP/commit/465a66fce4c756c018823ad85c1ee03487745290
