### ISSUE TITLE
Lucene5.3调用HanLP创建索引报错

### ISSUE THREAD

**Issue by liucong315** [hankcs/HanLP#60]
在Lucene5.3调用HanLP创建索引的时候，报错如下：
Exception in thread "main" java.lang.AbstractMethodError: org.apache.lucene.analysis.Analyzer.createComponents(Ljava/lang/String;)Lorg/apache/lucene/analysis/Analyzer$TokenStreamComponents;
	at org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:179)
	at org.apache.lucene.document.Field.tokenStream(Field.java:562)
	at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:607)
	at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:344)
	at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:300)
	at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:234)
	at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:450)
	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1475)
	at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1254)
	at com.ohoyee.test.search.SearchTest.createIndex(SearchTest.java:51)
	at com.ohoyee.test.search.SearchTest.main(SearchTest.java:104)

索引创建代码如下：	
static void createIndex() throws Exception {
		Directory dir = FSDirectory.open(Paths.get(indexPath, new String[0]));
		Analyzer analyzer = new HanLPAnalyzer();
		IndexWriterConfig iwc = new IndexWriterConfig(analyzer);
		IndexWriter writer = new IndexWriter(dir, iwc);
		File[] files = new File(targetPath).listFiles();
		for (File file : files) {
			Document doc = new Document();
			String content = getContent(file);
			String name = file.getName();
			String path = file.getAbsolutePath();
			doc.add(new TextField("content", content, Store.YES));
			doc.add(new TextField("name", name, Store.YES));
			doc.add(new TextField("path", path, Store.YES));
			System.out.println(name + "===" + content + "===" + path);
			writer.addDocument(doc);
			writer.commit();
		}

	}

**Comment by hankcs** [comment]
请贴一下插件jar版本。

**Comment by hankcs** [comment]
看起来像是用4.x的Lucene插件放到5.x的Lucene里用。

**Comment by lsq88334753** [comment]
请问 ：lucene5.2.1 (hanlp-portable-1.2.4, hanlp-solr-plugin-1.0)索引创建成功，搜索却无命中记录(搜索没报错，并且肯定有这个词)。
建立索引：
     Analyzer analyzer = new HanLPAnalyzer();/////////////////////////////////////////////////////////////
     IndexWriterConfig config = new IndexWriterConfig(analyzer);
     config.setOpenMode(IndexWriterConfig.OpenMode.CREATE_OR_APPEND);
     Directory directory = FSDirectory.open(Paths.get(INDEX_DIR));
     IndexWriter indexWriter = new IndexWriter(directory, config);

     Document document = new Document();
     document.add(new TextField("time", res, Store.YES));
     document.add(new TextField("content", content, Store.YES));
     indexWriter.addDocument(document);

     indexWriter.commit();
     closeWriter(indexWriter);
搜索
     Directory directory = FSDirectory.open(Paths.get(INDEX_DIR));
     Analyzer analyzer = new HanLPAnalyzer();//////////////////////////////////////////////////////////////
     IndexReader ireader = DirectoryReader.open(directory);
     IndexSearcher isearcher = new IndexSearcher(ireader);
     QueryParser parser = new QueryParser("content", analyzer);
     Query query = parser.parse(text);
     ScoreDoc[] hits = isearcher.search(query, 300000).scoreDocs;

当搜索 “time:[20140101 TO 20150101]” 有命中结果显示，而搜索 “被告人” 这个词命中结果为0个，这个词是一定有的。请问您知道是什么原因么？

**Comment by hankcs** [comment]
我测试正常

```
        Analyzer analyzer = new HanLPAnalyzer();////////////////////////////////////////////////////
        IndexWriterConfig config = new IndexWriterConfig(analyzer);
        config.setOpenMode(IndexWriterConfig.OpenMode.CREATE_OR_APPEND);
        String INDEX_DIR = System.getProperty("java.io.tmpdir") + File.separator + "index";
        Directory directory = FSDirectory.open(Paths.get(INDEX_DIR));
        IndexWriter indexWriter = new IndexWriter(directory, config);

        Document document = new Document();
        document.add(new TextField("content", "被公诉机关指控涉嫌犯罪的当事人称作被告人。", Field.Store.YES));
        indexWriter.addDocument(document);

        document = new Document();
        document.add(new TextField("content", "商品和服务", Field.Store.YES));
        indexWriter.addDocument(document);

        document = new Document();
        document.add(new TextField("content", "和服的价格是每镑15便士", Field.Store.YES));
        indexWriter.addDocument(document);

        indexWriter.commit();
        indexWriter.close();

        IndexReader ireader = DirectoryReader.open(directory);
        IndexSearcher isearcher = new IndexSearcher(ireader);
        QueryParser parser = new QueryParser("content", analyzer);
        Query query = parser.parse("被告人");
        ScoreDoc[] hits = isearcher.search(query, 300000).scoreDocs;
        for (ScoreDoc scoreDoc : hits)
        {
            Document targetDoc = isearcher.doc(scoreDoc.doc);
            System.out.println(targetDoc.getField("content").stringValue());
        }
```

如果你那边也能通过这个测试，那么问题可能并不在这里。

**Comment by lsq88334753** [comment]
折腾一天找到原因了，就是在添加的字符串(content)中存在两个或以上的换行符时后面的文本就不被识别了。例如："\n\n" + "被公诉机关指控涉嫌犯罪的当事人称作被告人。"

**Comment by hankcs** [comment]
感谢排查，问题已经确认，马上修复这个bug。

**Comment by hankcs** [comment]
这个问题应该解决了，如果还有问题，欢迎再开issue。

**Comment by lsq88334753** [comment]
非常感谢！
