### ISSUE TITLE
关于唐诗人名的简繁、拼音体转换以及convertToPinyinString函数的建议

### ISSUE THREAD

**Issue by yippeesoft** [hankcs/HanLP#602]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x ] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：portable-1.3.4
我使用的版本是：portable-1.3.4

## 我的问题

1. 唐诗诗人人名繁体转简体出现乱码
2. 某些人名似乎可不转
3.多音字人名不正确
4.convertToPinyinString函数建议

 

### 步骤

1. 下载jar，加入工程，运行代码
2. 然后从 https://github.com/chinese-poetry/chinese-poetry 获得json
3. 接着转换json，打印诗人人名、简体、拼音

### 触发代码

```
     Log.d(TAG, HanLP.convertToSimplifiedChinese("裴諴"));
    Log.d(TAG, HanLP.convertToSimplifiedChinese("拾得"));
    List<Pinyin> pinyinList = HanLP.convertToPinyinList("曾扈") ;
    String pyname="";
    for (Pinyin pinyin : pinyinList)
    {
      pyname+= pinyin.getPinyinWithToneMark()+" ";
    }
    Log.d(TAG, pyname);
```
### 期望输出

```
裴諴 拾得 zeng hu
```

### 实际输出

```
裴��   十得 céng hù 
```

## 其他信息

另外不知道为什么convertToPinyinString(String text, String separator, boolean remainNone)这么设计，能不能加个convertToPinyinString(String text, int start,int len)? 谢谢。

**Comment by hankcs** [comment]
欢迎参与修订词典：https://github.com/hankcs/HanLP/commit/2b98217ddd805c708475ed313fb1a9269ebba5ee
谢谢

**Comment by alexbobpo** [comment]
你好,如果中文和字母其他符号混合,转换后非中文符号字母丢失,我想有必要增加一个方法去专门处理这样的场景.保留非中文字符.

**Comment by hankcs** [comment]
https://github.com/hankcs/HanLP/blob/master/src/main/java/com/hankcs/hanlp/HanLP.java#L490

**Comment by alexbobpo** [comment]
@hankcs sorry !我发现之前描述的不是很清楚.
convertToPinyinFirstCharString 这个方法的非字符保留,有必要这样做,比如要简化一个中文文件名字,只需要它的首字符拼接,当文件事英文的就保留原来字符.

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。

**Comment by vnobo** [comment]
新年快乐
