### ISSUE TITLE
如何只使用自定义生成的词典分词？

### ISSUE THREAD

**Issue by RobotNever** [hankcs/HanLP#607]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.3.4
我使用的版本是：1.3.4

## 我的问题
Hancks，你好：
       因为业务需要，目前只想使用自己生成的词典进行分词，请问有关闭系统词典的方法吗？

**Comment by hankcs** [comment]
https://github.com/hankcs/HanLP/blob/master/src/test/java/com/hankcs/demo/DemoUseAhoCorasickDoubleArrayTrieSegment.java
