### ISSUE TITLE
语义距离中的同义词词林怎么怎么修改

### ISSUE THREAD

**Issue by moonyoung430** [hankcs/HanLP#609]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [ x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：hanlp-1.2.8
我使用的版本是：hanlp-1.2.8

## 我的问题

您好，我在使用HanLP中的语义距离时发现您是利用同义词词林的一维映射实现的，并且在以往的issue中看到您说，可以自己根据同义词词林的格式增加新词，那我想知道怎么添加？添加完还要按照您的映射方式进行映射对吗？能否像分词功能的customDictionary一样？

**Comment by moonyoung430** [comment]
1.作者大人！给跪了，我错了，我找到同义词词林的txt了，并且添加了新词，实验也成功了，但是我又有另一个问题了。智能推荐的算法原理是什么？
2.作者大人，我也来说个题外话，希望您能看见，之前在别的issue中看到过您说很多人问问题之前都没有好好看文档，其实我真的有认真看文档，并且把您附的链接都打开看了，但是我比较关注算法，希望能弄懂算法，然后可以根据自己的需求去修改程序。我现在看到只能推荐这里，真的没有写算法是什么。。。
3.我的废话完了，上天保佑，作者大大能看到我的留言

**Comment by Rain117E** [comment]
大佬，我想请教一下往CoreSynonym.txt里加我想加的新同义词地具体过程？（就是较为专业的那种词语）

**Comment by hankcs** [comment]
https://github.com/hankcs/HanLP/wiki/FAQ#%E5%90%8C%E4%B9%89%E8%AF%8D%E8%AF%AD%E4%B9%89%E8%B7%9D%E7%A6%BB%E7%AE%97%E6%B3%95%E5%8E%9F%E7%90%86
