### ISSUE TITLE
关于license问题，hankcs 你好，我有一个分词项目，使用了hanLP分词算法和代码

### ISSUE THREAD

**Issue by jimichan** [hankcs/HanLP#611]
hankcs 你好，我有一个分词项目，使用了hanLP分词算法和代码。

主要进行了大量的重构和结构的调整，修改面积过大没法提交pull 

如果也在github上开源，是否可以

如果可以，在license怎么声明，因为我看之前您的文档写明了版权和上海林源公司有关，是不是影响license选择

**Comment by hankcs** [comment]
你好，本项目虽然不鼓励二次开发，但是鼓励开源的。只要遵守Apache授权协议，则版权方无法收回授权。可以用任意License授权新的项目，不影响的。只需保留原copyright header，作者署名；然后注明使用或参考了本项目，以及本项目链接即可。具体可参考如下Apache协议条款：

 [Apache-2.0](https://www.apache.org/licenses/LICENSE-2.0). 根据Apache-2.0，本开源项目可以在遵守如下条款的情况下二次发布：

> Redistribution. You may reproduce and distribute copies of the Work or Derivative Works thereof in any medium, with or without modifications, and in Source or Object form, provided that You meet the following conditions:

> You must cause any modified files to carry prominent notices stating that You changed the files; and

即注明使用的文件有修改。

> You must retain, in the Source form of any Derivative Works that You distribute, all copyright, patent, trademark, and attribution notices from the Source form of the Work, excluding those notices that do not pertain to any part of the Derivative Works; and

即保留原有版权声明与署名等。

> You may add Your own attribution notices within Derivative Works that You distribute, alongside or as an addendum to the NOTICE text from the Work, provided that such additional attribution notices cannot be construed as modifying the License. You may add Your own copyright statement to Your modifications and may provide additional or different license terms and conditions for use, reproduction, or distribution of Your modifications, or for any such Derivative Works as a whole, provided Your use, reproduction, and distribution of the Work otherwise complies with the conditions stated in this License.

可以在原有版权声明下方添加自己的版权声明与署名。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
