### ISSUE TITLE
solr中强制该次请求不使用分词

### ISSUE THREAD

**Issue by zhangshenglong521** [hankcs/HanLP#613]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x ] 我在此括号内输入打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：portable-1.3.4
我使用的版本是：portable-1.3.4

## 我的问题

在solr查询的过程中，我想强制某查询字段该次请求不使用分词，一直没有找到应该修改哪里。

例如：
solr在查询时，会对传入的值分词， 中国人有可能会被分成“中国”，“国人”，“中国人”。
包含着三个短语的语句都会被搜到。强制要求solr不分词，直接匹配中国就好

**Comment by zyzhang15** [comment]
传入solr的关键字,加上 双引号.
 1. 分词搜索的方法:    title: 中国人
2.强制不分词的方法:  title: "中国人"
