### ISSUE TITLE
你好，请问这个项目有没有聊天机器人的子项目或者改为聊天机器人的计划和项目推荐吗？

### ISSUE THREAD

**Issue by ithjz** [hankcs/HanLP#615]
你好，请问这个项目有没有聊天机器人的子项目或者改为聊天机器人的计划和项目推荐吗

**Comment by Samurais** [comment]
分词和词性标注可以说是实现聊天机器人的基础，而聊天机器人的基础至少有深度学习，自然语言处理，信息检索和知识图谱。

聊天又可以分为开放域聊天和封闭域聊天，开放域聊天包括微软小冰和tuling123，封闭域聊天主要有基于事实的聊天和基于常见问题集的聊天，从不同类型的聊天中都会涉及表情包、上下文、黄反、情感、系统画像和用户画像，对于不同聊天而言，都需要不同的语料，高质量的语料才是每个聊天的主要区别。从架构上讲，聊天机器人通常被设计成包括STT, NLP, NLU, DST, POLICY, NLG和TTS等几个模块。

<img width="1025" alt="opensource projects" src="https://user-images.githubusercontent.com/3538629/29876318-fc9723da-8dce-11e7-8b97-b81cbeff3882.png">

可参考我的几个开源项目。

**Comment by TylunasLi** [comment]
”你好，你家的内存芯片不错，请问有你们家有没有GPU的产品，或者改为GPU的项目?“

如果您需要面向客服领域，Java平台下的问答机器人，可以考虑采用我司的产品。我司产品中的分词模块基于HanLP进行了深度定制开发，其分词等基础服务的准确率得到了大幅提升。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
