### ISSUE TITLE
请问是否可以提取指定的关键字

### ISSUE THREAD

**Issue by ztj1993** [hankcs/HanLP#625]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 我的问题

假如说我有一个关键字列表 (10000+)；我想提取一个文章的所有的可以匹配的关键字(没有匹配的全部剔除)；请问 HanLP 可以实现吗？

请问大家是否有相似的，高性能的开源扩展库，也可以推荐一下。主要用于提取指定关键词列表的关键词 (这个标关键词表有点大)。

比如：  
Shell是Linux运维中必不可少的脚本语言，CentOS是一款伟大的操作系统。  
我只需要：Shell，Linux，Linux运维，脚本语言，CentOS，操作系统  
这些关键字(标签)是我事先定义好的。

**Comment by hankcs** [comment]
试试com.hankcs.hanlp.collection.AhoCorasick.AhoCorasickDoubleArrayTrie#parseText(java.lang.String)

**Comment by ztj1993** [comment]
@hankcs 谢谢了

其实我不懂 java；比着葫芦画着瓢实现的，应该配合自定义词典等就能实现希望可以简单使用 jetty + HanLP 对我的网站提供简单的数据分析服务。

`
        TreeMap<String, String> map = new TreeMap<String, String>();
        String[] keyArray = new String[]
                {
                        "Shell",
                        "Linux",
                        "Linux运维",
                        "脚本语言",
                        "CentOS",
                        "操作系统"
                };
        for (String key : keyArray)
        {
            map.put(key, key);
        }
        AhoCorasickDoubleArrayTrie<String> act = new AhoCorasickDoubleArrayTrie<String>();
        act.build(map);
        System.out.println(act.parseText("Shell是Linux运维中必不可少的脚本语言，CentOS是一款伟大的操作系统。"));
`
