### ISSUE TITLE
中文人名实体精度的问题

### ISSUE THREAD

**Issue by OTAKU-Wang** [hankcs/HanLP#63]
我在使用hanlp 1.2.4 对如下句子分词的时候：
“并有望在那与1993年就结识的友人重聚。”

得到的结果是如下这样的：
并/cc	有望/v	在/p	那与/nr	1993/m	年/qt	就/d	结识/v	的/ude1	友人/n	重聚/vi	。/w

其中的“那与／nr”应该不是人名。我看源码好像是因为它这个词组符合构成人名的规则 所以把他组合成了人名？然后再进行hmm的识别？还希望作者说明一下如何改进这一块。

**Comment by hankcs** [comment]
是的，粗分后发现 那与 有可能是个人名，加入第二层HMM中细分发现得分更高。

有多种改进方法：
1. 将 那与 A 1 加入nr.txt
2. 强化对人名识别的过滤规则。如 那与 的BiGram概率低于某个阀值则排除它
3. 修改 BiGram 模型，加大 那@与 的频次。

目前采取了1，其他开源分词器多采用2。

**Comment by Tony-Wang** [comment]
这样的长的定语不太符合汉语的习惯，过度的修改字典，会导致另外一方面的劣化。越来越感觉需要针对潜在的语言习惯使用不同的分词字典。

**Comment by OTAKU-Wang** [comment]
使用的第三个方式解决的这个问题。但是不知道会不会影响其他的分词结果。


通过 Android 版 Outlook 发送





On Thu, Sep 24, 2015 at 1:06 AM -0700, "hankcs" <notifications@github.com> wrote:












是的，粗分后发现 那与 有可能是个人名，加入第二层HMM中细分发现得分更高。



有多种改进方法：

1. 将 那与 A 1 加入nr.txt

2. 强化对人名识别的过滤规则。如 那与 的BiGram概率低于某个阀值则排除它

3. 修改 BiGram 模型，加大 那@与 的频次。



目前采取了1，其他开源分词器多采用2。

**Comment by hankcs** [comment]
应该说越改越适应你所在的语境，但是越来越偏离原生的语境。
毕竟汉语语境是千变万化的，实用系统无法像写论文一样，固定一个训练集和测试集就能给出固定的准确率了。
