### ISSUE TITLE
是否考虑出个python版？或者提供python接口？

### ISSUE THREAD

**Issue by suparek** [hankcs/HanLP#632]
向python开放应该是个好的方向。

**Comment by BenDerPan** [comment]
@suparek 可以用JPype调用Java接口，自己封装就可以了。

**Comment by Samurais** [comment]
推荐使用Docker服务
https://hub.docker.com/r/samurais/hanlp-api/

**Comment by suparek** [comment]
对jdk版本什么的有什么要求吗？

**Comment by BenDerPan** [comment]
@suparek JDK我用的Ubuntu，OpenJDK1.8,目前没有问题，不过跑在Mac OS下，需要安装一下jar6.0的运行环境，苹果官网下载。

**Comment by hankcs** [comment]
https://github.com/hankcs/HanLP/wiki/%E8%A1%8D%E7%94%9F%E9%A1%B9%E7%9B%AE

**Comment by suparek** [comment]
已经成功了，谢谢。
