### ISSUE TITLE
“中国移动通信集团” 和 “中国移动” 2个词的分词词序不一样

### ISSUE THREAD

**Issue by gxy0451** [hankcs/HanLP#638]
当前最新版本号是：c57895f14801df54312e8b656ea8ac2eeef72f99
我使用的版本是：c57895f14801df54312e8b656ea8ac2eeef72f99

## 我的问题
中国移动通信集团 和 中国移动 2个词的分词词序不一样，导致solr完全匹配搜索的时候搜不到数据

### 触发代码

```
        List<Term> termList = IndexTokenizer.segment("中国移动通信集团");
        for (Term term : termList)
        {
            System.out.println(term + " [" + term.offset + ":" + (term.offset + term.word.length()) + "]");
        }
        List<Term> termList2 = IndexTokenizer.segment("中国移动");
        for (Term term : termList2) {
            System.out.println(term + " [" + term.offset + ":" + (term.offset + term.word.length()) + "]");
        }

```
### 实际输出

```
中国移动通信集团/nt [0:8]
中国移动通信/nz [0:6]
中国移动/nz [0:4]
中国/ns [0:2]
移动通信/nz [2:6]
移动/vn [2:4]
通信/vn [4:6]
集团/nis [6:8]

中国移动/nz [0:4]
中国/ns [0:2]
移动/vn [2:4]
```

”中国移动通信集团“的分词结果中 “中国”和“移动”之间多了一个“移动通信”，导致和“中国移动”的分词结果顺序不匹配。这样在solr中使用text:"中国移动"这种全词匹配模式搜索的话，是搜不到数据的

之前因为词序的事情已经麻烦过你了，经过上次的修改，分词的词序已经趋于稳定，但还有少数有问题，这个就是一个特例，希望能够得到修正，再次感谢！

**Comment by gxy0451** [comment]
刚才又发现一个例子：”广东省人民政府“ 和 ”省人民政府“。这两个词分词后分词的结果不是包含的关系，也会导致solr搜不到。
```
广东省/ns [0:3]
广东/ns [0:2]
人民政府/nis [3:7]
人民/n [3:5]
民政/n [4:6]
政府/nis [5:7]

省/n [0:1]
人民政府/nis [1:5]
人民/n [1:3]
民政/n [2:4]
政府/nis [3:5]
```
”广东省人民政府”的分词中没有“省”这个词，所以搜“省人民政府”的时候会搜不到“广东省人民政府”

**Comment by JonoloLuo** [comment]
替作者回答下问题, 类似这种完全匹配的情况, 不管任何排序都很难做到你 完全匹配哪就匹配的到的.
除非你都是单子分.  例如  在中国大陆举行      检索 完全匹配 "中国大"  怎么都匹配不到的

**Comment by gxy0451** [comment]
@JonoloLuo 谢谢您的回复，我这不是要求所有都能，像您说的这个确实无法做到。但如果是正确的词的话，还是希望能够保证词序。

**Comment by hankcs** [comment]
的确，这种排序无法方便地获得，IK也没有做到包含：

```
0 - 8 : 中国移动通信集团 | CN_WORD
0 - 6 : 中国移动通信 | CN_WORD
0 - 4 : 中国移动 | CN_WORD
0 - 3 : 中国移 | CN_WORD
0 - 2 : 中国 | CN_WORD
2 - 6 : 移动通信 | CN_WORD
2 - 4 : 移动 | CN_WORD
4 - 7 : 通信集 | CN_WORD
4 - 6 : 通信 | CN_WORD
6 - 8 : 集团 | CN_WORD

0 - 4 : 中国移动 | CN_WORD
0 - 3 : 中国移 | CN_WORD
0 - 2 : 中国 | CN_WORD
2 - 4 : 移动 | CN_WORD
```

如果不按字典序的话，需要另行设计一种排序规则，而且会损失性能，还在思考中。
暂时建议不要在搜索中开启index mode，这与Lucene的phrase设计是冲突的。

**Comment by gxy0451** [comment]
可能是词库不同，我的ik结果是这样的
![image](https://user-images.githubusercontent.com/5125893/31041393-461a3a18-a55a-11e7-91fc-213764196f42.png)
我之所以在搜索中打开index mode是为了使用全词匹配搜索，也就是phrase query。因为业务那边的同事认为这样搜索的更加准确，尽管这样召回率会低，但如果使用默认的parser，搜索的正确率会降低，所以我才会在搜索中打开index mode保证索引和搜索的时候分词是一致的。其实我一直在想，有没有可能在索引的时候只保留全切分的最细粒度分词，不保留长词，搜索时分词也采用这样的方式，这样分词词序就是固定的，就像英语一样不存在词序混乱的问题。这样不管是否使用全词匹配，都能得到好的效果。不知道我这个想法是否正确，还请作者赐教。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
