### ISSUE TITLE
停用词词典

### ISSUE THREAD

**Issue by laoyang945** [hankcs/HanLP#64]
建议加一个「没有」

**Comment by hankcs** [comment]
好的，既然有none，那也应该有“没有”

**Comment by laoyang945** [comment]
其实我有点疑惑，不知道停用词到底应该是以一个什么标准来入库，有没有一个什么权威的标准？
比如「有可能」「似乎」应该算是停用词吧

**Comment by hankcs** [comment]
没有权威，全凭感觉。最初的一版整合了网络上流传的哈工大停用词表，后来觉得如果一个词不好做关键词，那它就应该进停用词表。

**Comment by laoyang945** [comment]
嗯，看来只能这样了
刚刚做关键词提取的时候，觉得关键字提取是不是也应该加入去除停用词功能？一个iPhone的新闻，最后提取出来的关键字有GB，感觉怪怪的

**Comment by hankcs** [comment]
这种跟具体语境相关的个性化需求可能需要你自己设计后处理或预处理逻辑了。

**Comment by laoyang945** [comment]
嗯嗯，我看来得自己实现一个了
看了你的博客，到哪里都加油！
