### ISSUE TITLE
咨询HanLP与LTP的关系，及License相关问题

### ISSUE THREAD

**Issue by efeiefei** [hankcs/HanLP#644]
Hi，
  请问该项目和LTP是什么关系，哪些是移植，哪些是重新编写呢？如果商用，是否需要联系LTP取得授权呢？
  因为看到其他issue中提到依存句法分析模型训练是通过LTP训练出的。

THX

**Comment by hankcs** [comment]
1. 仅`com.hankcs.hanlp.dependency.nnparser.NeuralNetworkDependencyParser`移植自LTP，没有其他关系
2. 商用授权相关信息已经附带在数据包`data/model/dependency/NNParserModel.licence.txt`中，也可参考[文档](http://www.hankcs.com/nlp/parsing/neural-network-based-dependency-parser.html)。

**Comment by efeiefei** [comment]
感谢回复！

看其开源协议，貌似没有传染性。也就是HanLP的其他模块可以正常使用的对吧。
另外，模型 NNParserModel.txt.bin 是LTP提供的模型，还是您自己训练出来的呢。

**Comment by hankcs** [comment]
1. 是的，除`NeuralNetworkDependencyParser `模块外都是正常的Apache协议。
2. 是LTP的模型。当时没有语料，所以没有移植训练模块。

**Comment by efeiefei** [comment]
非常感谢～
@hankcs

**Comment by Ethan-Zhang** [comment]
您好，请问中文分词的哪个类别用到了`NeuralNetworkDependencyParser`这个解析器？

**Comment by hankcs** [comment]
都没有用到。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
