### ISSUE TITLE
请求和建议（违禁词、敏感词匹配）！

### ISSUE THREAD

**Issue by LilyBlooper** [hankcs/HanLP#645]
您好！
感谢百忙中回复！
只是一个请求。
目前有类似的需求：
**将一段文本中的违禁词（和谐词）进行匹配和过滤**
目前结合HanLP，我觉得先对文本进行分词，将分词后的词和敏感词库进行对比（采用hash或者trie等）
能达到 n O(1) 的时间复杂度（比如直接使用hashmap）。
不知HanLP有没有更大的办法，能够在分词过程中直接匹配某个特殊子词库的功能（违禁词库）
谢谢！

**Comment by hankcs** [comment]
https://github.com/hankcs/HanLP/issues/625

**Comment by LilyBlooper** [comment]
你好，感谢答复。 基于Trie的算法是好用的。
只是我这个需求大概是这个意思：
`java
		// 构造自定义字典，如违禁词
		TreeMap<String, String> map = new TreeMap<String, String>();
		String[] keyArray = new String[] { "处女", "月经", "口交", "性器" };
		for (String key : keyArray) {
			map.put(key, key);
		}
		AhoCorasickDoubleArrayTrie<String> act = new AhoCorasickDoubleArrayTrie<String>();
		act.build(map);
		// 1. 分词
		String rawText = "工信处女干事每月经过下属科室都要亲口交代24口交换机等技术性器件的安装工作，但是因为是处女";
		long start = System.currentTimeMillis();
		List<Term> termList = HanLP.segment(rawText);
		System.out.println("分词消耗:" + (System.currentTimeMillis() - start) + " millis");
		// 2. 分词结果进行匹配
		for (Term term : termList) {
//			System.out.println(term.word);
			System.out.println(act.parseText(term.word));
		}
		System.out.println("总计消耗:" + (System.currentTimeMillis() - start) + " millis");
`
第一步是独立的分词
第二步是进行关键词匹配
提这个issue的建议是请教下有没有好的意思可以在分词的时候直接完成

**Comment by hankcs** [comment]
可以给关键词设置自定义词性

**Comment by LilyBlooper** [comment]
感谢分享，明白你的意思了~  :notes: :ok_hand:

**Comment by LilyBlooper** [comment]
补充一个例子吧。
```java
		String text = "就是任性！敏感词全部自己造，白小洁你别走啊，又没叫你白洁";

		// 进行自定义词性的配置
		CustomDictionary.insert("敏感词", "ssr 1024");
		CustomDictionary.insert("白洁", "ssr 1024");
		CustomDictionary.insert("白小洁", "ssr 1024");
		List<String> hitWords = new ArrayList<>();
		List<Term> termList = HanLP.segment(text);
		for (Term term : termList) {
			System.out.println(term);
			if (term.nature.name().equals("ssr")) {
				hitWords.add(term.word);
			}
		}
		for (String hitWord : hitWords) {
			System.out.println("Found hit word：" + hitWord);
		}
```
