### ISSUE TITLE
自定义词典读取失败

### ISSUE THREAD

**Issue by syc961126** [hankcs/HanLP#648]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [ ] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.3.4
我使用的版本是：1.2.8

## 我的问题
我的配置文件里只改变了root路径，经测试无误
但是自定义分词时添加了自己的词典my.txt后总是出现警告读取失败不能显示分词结果，当在自定义词典路径里不加入my.txt时能显示出默认分词结果

## 复现问题
未改变任何已有词典和模型，只添加了自己的词典（UTF-8）编码
且每次都删掉了缓存文件
### 步骤
首先按照步骤把配置文件内容复制好，更改root路径，在自定义词典路径处添加了my.txt(已注意了前面的空格和后面的分号)

### 触发代码
import java.util.List;
import com.hankcs.hanlp.HanLP;
import com.hankcs.hanlp.seg.Segment;
import com.hankcs.hanlp.seg.common.Term;

public class hanlp
{  public static void main (String[] args)
	{
       String  testline="测试自定义分词词分义定自试测";
       Segment segment=HanLP.newSegment().enableCustomDictionary(true);
       
       List<Term>termlist =segment.seg(testline);
       for(Term term:termlist)
       {
    	   System.out.println(term.toString());
       }
	}
}

### 实际输出

无分词结果
 
提示：十月 11, 2017 5:28:24 下午 com.hankcs.hanlp.dictionary.CustomDictionary loadDat
警告: 读取失败，问题发生在java.lang.ArrayIndexOutOfBoundsException: 1056291
	at com.hankcs.hanlp.utility.ByteUtil.bytesHighFirstToInt(ByteUtil.java:239)
	at com.hankcs.hanlp.corpus.io.ByteArray.nextInt(ByteArray.java:68)
	at com.hankcs.hanlp.dictionary.CustomDictionary.loadDat(CustomDictionary.java:323)
	at com.hankcs.hanlp.dictionary.CustomDictionary.loadMainDictionary(CustomDictionary.java:66)
	at com.hankcs.hanlp.dictionary.CustomDictionary.<clinit>(CustomDictionary.java:53)
	at com.hankcs.hanlp.seg.Segment.combineByCustomDictionary(Segment.java:199)
	at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.segSentence(ViterbiSegment.java:57)
	at com.hankcs.hanlp.seg.Segment.seg(Segment.java:498)
	at hanlp.main(hanlp.java:12)

当删去自定义词典路径里my.txt 时输出
测试/vn
自定义/nz
分词/n
词/n
分/qt
义定/nr
自/p
试/v
测/v

自定义词典my.txt的内容：
试测

**Comment by syc961126** [comment]
调试输出：
十月 11, 2017 5:54:26 下午 com.hankcs.hanlp.dictionary.CoreDictionary load
信息: 核心词典开始加载:D:/各种资料/分词词表以及Hanlp相关数据集/data-for-1.3.3/data/dictionary/CoreNatureDictionary.txt
十月 11, 2017 5:54:26 下午 com.hankcs.hanlp.dictionary.CoreDictionary <clinit>
信息: D:/各种资料/分词词表以及Hanlp相关数据集/data-for-1.3.3/data/dictionary/CoreNatureDictionary.txt加载成功，153115个词条，耗时404ms
粗分词网：
0:[ ]
1:[测, 测试]
2:[试]
3:[自, 自定义]
4:[定, 定义]
5:[义]
6:[分, 分词]
7:[词]
8:[词]
9:[分]
10:[义]
11:[定]
12:[自]
13:[试]
14:[测]
15:[ ]

十月 11, 2017 5:54:26 下午 com.hankcs.hanlp.dictionary.CoreBiGramTableDictionary <clinit>
信息: 开始加载二元词典D:/各种资料/分词词表以及Hanlp相关数据集/data-for-1.3.3/data/dictionary/CoreNatureDictionary.ngram.txt.table
十月 11, 2017 5:54:27 下午 com.hankcs.hanlp.dictionary.CoreBiGramTableDictionary <clinit>
信息: D:/各种资料/分词词表以及Hanlp相关数据集/data-for-1.3.3/data/dictionary/CoreNatureDictionary.ngram.txt.table加载成功，耗时479ms
十月 11, 2017 5:54:27 下午 com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
信息: 自定义词典开始加载:D:/各种资料/分词词表以及Hanlp相关数据集/data-for-1.3.3/data/dictionary/custom/CustomDictionary.txt
十月 11, 2017 5:54:27 下午 com.hankcs.hanlp.dictionary.CustomDictionary loadDat
警告: 读取失败，问题发生在java.lang.ArrayIndexOutOfBoundsException: 4781575
	at com.hankcs.hanlp.utility.ByteUtil.bytesHighFirstToInt(ByteUtil.java:239)
	at com.hankcs.hanlp.corpus.io.ByteArray.nextInt(ByteArray.java:68)
	at com.hankcs.hanlp.dictionary.CustomDictionary.loadDat(CustomDictionary.java:322)
	at com.hankcs.hanlp.dictionary.CustomDictionary.loadMainDictionary(CustomDictionary.java:66)
	at com.hankcs.hanlp.dictionary.CustomDictionary.<clinit>(CustomDictionary.java:53)
	at com.hankcs.hanlp.seg.Segment.combineByCustomDictionary(Segment.java:199)
	at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.segSentence(ViterbiSegment.java:57)
	at com.hankcs.hanlp.seg.Segment.seg(Segment.java:498)
	at hanlp.hanlp.main(hanlp.java:16)

十月 11, 2017 5:54:27 下午 com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
信息: 以默认词性[n]加载自定义词典D:/各种资料/分词词表以及Hanlp相关数据集/data-for-1.3.3/data/dictionary/custom/CustomDictionary.txt中……
十月 11, 2017 5:54:28 下午 com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
信息: 以默认词性[n]加载自定义词典D:/各种资料/分词词表以及Hanlp相关数据集/data-for-1.3.3/data/dictionary/custom/现代汉语补充词库.txt中……
十月 11, 2017 5:54:29 下午 com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
信息: 以默认词性[ns]加载自定义词典D:/各种资料/分词词表以及Hanlp相关数据集/data-for-1.3.3/data/dictionary/custom/全国地名大全.txt中……
十月 11, 2017 5:54:30 下午 com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
信息: 以默认词性[n]加载自定义词典D:/各种资料/分词词表以及Hanlp相关数据集/data-for-1.3.3/data/dictionary/custom/人名词典.txt中……
十月 11, 2017 5:54:30 下午 com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
信息: 以默认词性[n]加载自定义词典D:/各种资料/分词词表以及Hanlp相关数据集/data-for-1.3.3/data/dictionary/custom/机构名词典.txt中……
十月 11, 2017 5:54:30 下午 com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
信息: 以默认词性[ns]加载自定义词典D:/各种资料/分词词表以及Hanlp相关数据集/data-for-1.3.3/data/dictionary/custom/上海地名.txt中……
十月 11, 2017 5:54:31 下午 com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
信息: 以默认词性[nrf]加载自定义词典D:/各种资料/分词词表以及Hanlp相关数据集/data-for-1.3.3/data/dictionary/person/nrf.txt中……
十月 11, 2017 5:54:31 下午 com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
信息: 正在构建DoubleArrayTrie……
十月 11, 2017 5:54:34 下午 com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
信息: 正在缓存词典为dat文件……

**Comment by syc961126** [comment]
不好意思写错了，我现在用的是1.3.3版本

**Comment by hankcs** [comment]
无法复现你的问题。日志看上去是bin文件长度不够，缓存的时候你没等它结束就强行中断程序了吧。

**Comment by zq019633** [comment]
hanlp怎么生成缓存 我删除一次后 就没有了， 在此运行也没有

**Comment by LomyCool** [comment]
@zq019633 需要开启debug模式   HanLP.Config.enableDebug();

**Comment by lyan62** [comment]
> 调试输出：
> 十月 11, 2017 5:54:26 下午 com.hankcs.hanlp.dictionary.CoreDictionary load
> 信息: 核心词典开始加载:D:/各种资料/分词词表以及Hanlp相关数据集/data-for-1.3.3/data/dictionary/CoreNatureDictionary.txt
> 十月 11, 2017 5:54:26 下午 com.hankcs.hanlp.dictionary.CoreDictionary 
> 信息: D:/各种资料/分词词表以及Hanlp相关数据集/data-for-1.3.3/data/dictionary/CoreNatureDictionary.txt加载成功，153115个词条，耗时404ms
> 粗分词网：
> 0:[ ]
> 1:[测, 测试]
> 2:[试]
> 3:[自, 自定义]
> 4:[定, 定义]
> 5:[义]
> 6:[分, 分词]
> 7:[词]
> 8:[词]
> 9:[分]
> 10:[义]
> 11:[定]
> 12:[自]
> 13:[试]
> 14:[测]
> 15:[ ]
> 
> 十月 11, 2017 5:54:26 下午 com.hankcs.hanlp.dictionary.CoreBiGramTableDictionary 
> 信息: 开始加载二元词典D:/各种资料/分词词表以及Hanlp相关数据集/data-for-1.3.3/data/dictionary/CoreNatureDictionary.ngram.txt.table
> 十月 11, 2017 5:54:27 下午 com.hankcs.hanlp.dictionary.CoreBiGramTableDictionary 
> 信息: D:/各种资料/分词词表以及Hanlp相关数据集/data-for-1.3.3/data/dictionary/CoreNatureDictionary.ngram.txt.table加载成功，耗时479ms
> 十月 11, 2017 5:54:27 下午 com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
> 信息: 自定义词典开始加载:D:/各种资料/分词词表以及Hanlp相关数据集/data-for-1.3.3/data/dictionary/custom/CustomDictionary.txt
> 十月 11, 2017 5:54:27 下午 com.hankcs.hanlp.dictionary.CustomDictionary loadDat
> 警告: 读取失败，问题发生在java.lang.ArrayIndexOutOfBoundsException: 4781575
> at com.hankcs.hanlp.utility.ByteUtil.bytesHighFirstToInt(ByteUtil.java:239)
> at com.hankcs.hanlp.corpus.io.ByteArray.nextInt(ByteArray.java:68)
> at com.hankcs.hanlp.dictionary.CustomDictionary.loadDat(CustomDictionary.java:322)
> at com.hankcs.hanlp.dictionary.CustomDictionary.loadMainDictionary(CustomDictionary.java:66)
> at com.hankcs.hanlp.dictionary.CustomDictionary.(CustomDictionary.java:53)
> at com.hankcs.hanlp.seg.Segment.combineByCustomDictionary(Segment.java:199)
> at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.segSentence(ViterbiSegment.java:57)
> at com.hankcs.hanlp.seg.Segment.seg(Segment.java:498)
> at hanlp.hanlp.main(hanlp.java:16)
> 
> 十月 11, 2017 5:54:27 下午 com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
> 信息: 以默认词性[n]加载自定义词典D:/各种资料/分词词表以及Hanlp相关数据集/data-for-1.3.3/data/dictionary/custom/CustomDictionary.txt中……
> 十月 11, 2017 5:54:28 下午 com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
> 信息: 以默认词性[n]加载自定义词典D:/各种资料/分词词表以及Hanlp相关数据集/data-for-1.3.3/data/dictionary/custom/现代汉语补充词库.txt中……
> 十月 11, 2017 5:54:29 下午 com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
> 信息: 以默认词性[ns]加载自定义词典D:/各种资料/分词词表以及Hanlp相关数据集/data-for-1.3.3/data/dictionary/custom/全国地名大全.txt中……
> 十月 11, 2017 5:54:30 下午 com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
> 信息: 以默认词性[n]加载自定义词典D:/各种资料/分词词表以及Hanlp相关数据集/data-for-1.3.3/data/dictionary/custom/人名词典.txt中……
> 十月 11, 2017 5:54:30 下午 com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
> 信息: 以默认词性[n]加载自定义词典D:/各种资料/分词词表以及Hanlp相关数据集/data-for-1.3.3/data/dictionary/custom/机构名词典.txt中……
> 十月 11, 2017 5:54:30 下午 com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
> 信息: 以默认词性[ns]加载自定义词典D:/各种资料/分词词表以及Hanlp相关数据集/data-for-1.3.3/data/dictionary/custom/上海地名.txt中……
> 十月 11, 2017 5:54:31 下午 com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
> 信息: 以默认词性[nrf]加载自定义词典D:/各种资料/分词词表以及Hanlp相关数据集/data-for-1.3.3/data/dictionary/person/nrf.txt中……
> 十月 11, 2017 5:54:31 下午 com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
> 信息: 正在构建DoubleArrayTrie……
> 十月 11, 2017 5:54:34 下午 com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
> 信息: 正在缓存词典为dat文件……

我也有以上问题，请问您解决了吗？

**Comment by zq019633** [comment]
自定义词库后 , 把原词典 那几个压缩包 删除 就好了

**Comment by lyan62** [comment]
我是直接替换了原来的custom的folder，就出现这个情况。您说的原来的压缩包是指哪几个？

多谢！

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by zq019633** [comment]
\data\dictionary  custom CustomDictionary.txt.bin 删除 




    
    
        
            
                
                    
                        
                    
                    
                        
                            用户名zq019633
                            
                            
                                
                                    邮箱：zhouq0324@qq.com
                                
                        
                    
                
            
        
    
签名由 网易邮箱大师 定制


在2018年10月18日 10:58，lyan62 写道： 我是直接替换了原来的custom的folder，就出现这个情况。您说的原来的压缩包是指哪几个？



多谢！



Get Outlook for Android<https://aka.ms/ghei36>



________________________________

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
