### ISSUE TITLE
CustomDictionary.txt第一行不能加入词典

### ISSUE THREAD

**Issue by laoyang945** [hankcs/HanLP#65]
不知道是为什么……
解决方法：前两行重复一下

**Comment by hankcs** [comment]
data/dictionary/custom/CustomDictionary.txt文件头有几个奇怪的字节：
![2015-10-2 11-12-13](https://cloud.githubusercontent.com/assets/5326890/10238758/929311dc-68f6-11e5-8e8f-79fa82066b3a.png)
好像是Windows的BOM，去掉了就正常了。

**Comment by hankcs** [comment]
这个问题应该解决了，如果还有问题，欢迎再开issue。
