### ISSUE TITLE
如何获取字符串中的所有可能分词

### ISSUE THREAD

**Issue by baiselanjingyi** [hankcs/HanLP#653]
我目前采用的是1.3.1版本，使用用户自定义字典，字典中包含：牛仔马甲、 牛仔、 马甲、牛仔马甲外套、马甲。
针对源字符串：“帅气无袖连帽牛仔马甲外套女短款2017秋装新款韩版复古牛仔马夹” 进行分词时，采用的是索引分词器，得到的结果是：“牛仔马甲外套，牛仔，马甲”，无法分词得出“牛仔马甲”。hanlp中是否有办法获取到所有可能存在的分词？

**Comment by hankcs** [comment]
用最新版
