### ISSUE TITLE
无论改变什么都分不开，包括修改语料本身

### ISSUE THREAD

**Issue by yangnianen** [hankcs/HanLP#654]
![default](https://user-images.githubusercontent.com/17618881/31812053-555d8bfa-b5b4-11e7-982b-01aaa6531a3b.png)

上第一   ，这个词就是分不开，然后我看原代码发现，代码中将 m m结构给合并。我尝试去改变，上的词性为  上 f 64454 ， 但机器却标注为 m词性？ 为什么上字词性要给我标上 m 这个词性。 我压根都没有标

**Comment by yangnianen** [comment]
一直找都没有找到解决办法，作者能给我回复一下这个？谢谢

**Comment by yangnianen** [comment]
求指导！

**Comment by hankcs** [comment]
无法复现。
[世界/n, 上/f, 第一/mq, 架/q, 望远镜/n]

请严格按照issue模板填写问题，重新发issue。
