### ISSUE TITLE
对于提取不同的词，选取哪种分词方法回更好？

### ISSUE THREAD

**Issue by mengyingzhou** [hankcs/HanLP#657]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [√ ] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：jar包-1.3.4
我使用的版本是：jar包-1.3.4

## 我的问题

您好！
我现在需要对一篇300字左右的新闻进行关键词提取，关键词的分别为：
```
时间
社会地点（eg：医院、学校）
自然地点（eg：江苏、杭州）
社会地位（eg：省长、总书记）
身份（eg：孕妇、医生）
人名
行为动词（主要是v和vi，eg：报告、安慰）
```
经过尝试以后发现不同的分词方法对于相同的文本会有不同的分词结果，例如有些就会识别更精准的行政机构，而有些则相比较差，因为对于NLP接触时间并不是很长，所以对于各种分词原理了解并不是很清晰。
请问您能否对于这些不同的关键词提取，提供在HanLP现存分词方法中，较好的分词方式，即对于不同的词的提取，采取最好的分词方式？
谢谢！

**Comment by hankcs** [comment]
com.hankcs.hanlp.tokenizer.NLPTokenizer可以解决一部分问题，但语料比较粗糙，可能无法完全满足要求。

**Comment by NullAerber** [comment]
因为有看到这个问题[#328] (!https://github.com/hankcs/HanLP/issues/328)的回答中您提到了
```
的确，NShort命名实体识别能力高那么一点点，实际上并不实用。
Nshort是支持词典的。
```
在其他回答中也提到了CRF方法相比其他更优秀。
所以我想在HanLP中是否还存在和这个分词方式类似，针对某一类词语有相对优秀的识别能力。

**Comment by hankcs** [comment]
目前com.hankcs.hanlp.seg.Viterbi.ViterbiSegment分词器enableOrganizationRecognize等等接口可以激活相应的实体识别，但务实地讲，不一定能达到你的需求。你要的词语需要很精确的词性的话，这也不是人民日报2014能提供的，该语料库中这些词可能都被标注为n，也可能一部分标注为ns或nt。人名也许还行吧。动词也没分得那么细，很多都是vn。

**Comment by NullAerber** [comment]
感谢建议～如果没有现成的方式的话，我试一下能不能对现有的算法进行的测试，如果有比较好的结果，我会在这反馈。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
