### ISSUE TITLE
能否支持观点抽取

### ISSUE THREAD

**Issue by rainsun007** [hankcs/HanLP#663]
@hankcs    你好   
我想了解一下HanLP能否支持观点抽取
比如:＂服务态度很好，环境也不错，就是点歌系统不太好用。＂
正向观点 : 服务态度很好 环境不错
负向观点 : 点歌系统落后

**Comment by tanwen19932** [comment]
可以自己在句法分析的基础之上进行简单的词语(评价对象:服务),形容词筛选(评价词:落后),以及程度词(词:很)筛选即可实现

**Comment by TylunasLi** [comment]
细粒度观点抽取需要定义评价对象，针对评价对象的情感词（例如对手机“速度快”的“快”是好，“耗电快”的“快”是差）以及情感词的强度。如果想做好，观点抽取的工作量很大，且不容易对各个领域都通用。不太容易开发通用的软件包。自己做可以参考 tanwen19932 的方法。

**Comment by rainsun007** [comment]
@tanwen19932 @TylunasLi   多谢二位  我做做测试

**Comment by rainsun007** [comment]
@tanwen19932  做了测试  简单的句子还行， 稍复杂点的句子就行了

**Comment by tanwen19932** [comment]
@rainsun007 这个就是算法的问题了.下载下相关论文吧..

**Comment by muzier** [comment]
@tanwen19932 @rainsun007 @TylunasLi 请教三位：这种观点抽取的筛选是通过什么方式实现的？写规则去筛选吗？有没有示例或者相关文章可以提供参考的呀？先谢过啦~

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
