### ISSUE TITLE
解析txt格式的个人求职简历

### ISSUE THREAD

**Issue by altraman00** [hankcs/HanLP#666]
楼主好，有个问题想请教下，我现在有这么个需求：
需要**解析txt格式的个人求职简历**
首先我通过分词来获取求职者的姓名、性别、住址、邮箱等基本信息没有什么问题，
**但是现在需要提取出简历中的求职者的项目工作经验，这个好像很不好搞，没找到好的办法能够完整的提取出项目经验的信息来，楼主有啥办法帮忙指导下么？**
感谢！！！

**Comment by AnyListen** [comment]
推荐使用正则表达式进行匹配

**Comment by TylunasLi** [comment]
要看你要提取信息的上下文或内部结构有没有什么规律，如果有规律，可以自己构造滑动的上下文窗口在词语级别进行抽取。

**Comment by altraman00** [comment]
@AnyListen 正则表达式获取邮箱手机号等基本信息可以，但是没法获取详细的工作经验内容吧，或者有啥相关正则表达式，推荐下

**Comment by altraman00** [comment]
@TylunasLi 这简历的内容和格式完全是随机的，没有固定的模板，每个人写的简历的格式都是不一样的。
另外你说的构造滑动的上下文窗口，这个是什么意思，有相关资料推荐下么，谢谢！

**Comment by 824420263** [comment]
楼主换工作吗

**Comment by altraman00** [comment]
@824420263 你是要招人么，哈哈……

**Comment by 824420263** [comment]
学习下顺便招人，推荐一个海康威视自然语言专家的职位，地点杭州，薪资60-120万，特别优秀不限制，哈哈

**Comment by altraman00** [comment]
@824420263 有这心没这能耐啊，也是才开始接触

**Comment by 824420263** [comment]
你微信多少请教请教，我也想学习下NLP

**Comment by altraman00** [comment]
微信号：ELEVEN--K

**Comment by AnyListen** [comment]
@altraman00 可以发一些实例内容，这样可以看一下

**Comment by altraman00** [comment]
@AnyListen 

下面的json例子是我需要从文本（txt/doc/docx/pdf等）中解析之后得到的最终格式
`{
    "name":"小谢",
    "sex":"男",
    "phone":"13388888888",
    "email":"2345678@qq.com",
    "workExperience":{
        "上海**商务咨询有限公司":{
            "项目一":{
                "time":"2011/05 -- 2012/05",
                "department":"总办会",
                "Position":"总经理",
                "workDesc":"一、负责公司人力资源规划、组织架构设计与建设； 二、建立与完善公司各项规章制度的编制、组织实施、监督、修订、管理等相关工作； 三、依据用人部门的招聘需求和公司的人员编制，拟定年度、季度招聘计划，实施招聘，定期对各招聘渠道进行数据分析，选择最佳招聘方式；",
                "":""
            },
            "项目二":{
                "time":"2012/06 -- 2015/05",
                "department":"总办会",
                "Position":"总经理",
                "workDesc":"1、人事各模块的管理工作（1）、进行工作分析，完成职位说明书；（2）、执行招聘计划，维护拓展各种招聘渠道；（3）、发布职位信息，收集简历，聘前测试和简历的初步筛选,安排面试；",
                "":""
            }
        },
        "北京商务咨询有限公司":{
            "项目一":{
                "time":"2011/05 -- 2012/05",
                "department":"总办会",
                "Position":"总经理",
                "workDesc":"一、***********； 二、***********； 三、***********；",
                "":""
            },
            "项目二":{
                "time":"2012/06 -- 2015/05",
                "department":"总办会",
                "Position":"总经理",
                "workDesc":"1、***********（1）、***********；（2）、***********；（3）、***********；",
                "":""
            }
        }
    }
}`



文本内容如下：

`小谢 电子信息技术及仪器   本科 专业硕士 工程师 博士
 
男 | 已婚 | 1980 年5月生 | 户口：江苏 | 现居住于上海
7年工作经验 | 无党派人士|  身份证： 320326198088888888
浦东临港新城 200433
13398858888(手机)
E-mail: xw15688888888@163.com


　求职意向
 
·工作性质：  全职
·期望职业：  人力资源专员/助理、招聘经理/主管、人力资源主管、人力资源经理
·期望行业：  贸易/进出口、医药/生物工程、加工制造（原料加工/模具）、石油/石化/化工、交通/运输/物流、办公用品及设备、能源/矿产/采掘/冶炼
·工作地区：  上海、北京、天津
·期望月薪：  4001-6000元/月
 . 目前状况：  我目前处于离职状态，可立即上岗

　自我评价
 
多年人力资源管理工作经验；精通招聘、培训和员工关系；丰富的招聘经验，有效控制招聘预算；善于从公司战略角度进行人力资源体系开发、再造和实务操作；熟悉国家、上海劳动人事政策，熟练协调、处理各类劳动关系问题，为企业规避用工风险；忠诚而敬业的职业素养，具有很强的沟通协调能力；人力资源管理师，C1证； 

　　工作经验
2011/05 -- 2012/05 
上海**商务咨询有限公司 | 总经办 | 人力资源主管  
行业类别：其它 | 企业性质：民营 | 规模：20-99人 | 职位月薪：4001-6000元/月
工作描述： 1
2009/08 -- 2011/04 
上海**信息科技有限公司 | 人力资源部 | 人力资源主管  
行业类别：IT服务（系统/数据/维护）/多领域经营 | 企业性质：民营 | 规模：20-99人 | 职位月薪：4001-6000元/月
工作描述：一、负责公司人力资源规划、组织架构设计与建设； 二、建立与完善公司各项规章制度的编制、组织实施、监督、修订、管理等相关工作； 三、依据用人部门的招聘需求和公司的人员编制，拟定年度、季度招聘计划，实施招聘，定期对各招聘渠道进行数据分析，选择最佳招聘方式； 四、负责公司培训体系,依据公司发展战略,制订培训计划并组织实施培训；对培训效果进行跟踪分析； 五、负责公司薪酬福利及员工关系等管理工作； 六、监督、管理公司人事事务性工作（面试、录用、转正、调动、薪资制作、离职、员工劳动合同签订、招退工办理、五险一金操作、建立健全员工人事档案）； 七、建立员工沟通机制，维持企业、员工双方和谐稳定的劳动关系； 八、负责对分公司人力资源工作进行指导和监控工作； 九、完成总经理临时交办的各项工作任务。
2005/06 -- 2008/07 
江苏**装饰工程有限公司 | 人力资源部 | 人力资源助理  
行业类别：家居/室内设计/装饰装潢 | 企业性质：民营 | 规模：20-99人 | 职位月薪：2001-4000元/月
工作描述：1、人事各模块的管理工作（1）、进行工作分析，完成职位说明书；（2）、执行招聘计划，维护拓展各种招聘渠道；（3）、发布职位信息，收集简历，聘前测试和简历的初步筛选,安排面试； （4）、负责办理员工入职离职等调配事务，管理员工信息档案工作，       完善公司各项人事数据资料；（5）、组织员工进行入职培训、业务培训、提升培训等；（6）、负责员工的薪酬福利管理，包括员工薪资、四险一金、商业保险等事宜（7）、跟踪评估各类人才的使用情况，更新和维护人才储备库；（7）、提供招聘分析报告和企业人员结构分析报告。2、行政管理工作（1）、办公用品、设备、车辆、宿舍的管理及审核、控制；（2）、组织策划公司的员工活动，建立形成公司的企业文化；（3）、参与公司重大决策，并提出可行性建议；（4）、外联工作。
 

　　教育背景
 
2001/09 --2005/07 
江苏常州大学| 法学| 本科


　　培训经历
 
2008/09 -- 2008/12 
上海干部培训中心/上海紧缺人才培训办公室  
 
培训课程：人事管理
所获证书：上海市人事岗位资格证书
培训地点：上海复旦大学新闻学院综合楼3楼
培训描述：    经过课程培训机构组织的阶段性的培训，掌握了人事工作中需要注意并熟知的细节处理及操作技巧;培训课程中的劳动合同法部分，也使得我更自信、更熟练地去处理员工关系。

　　 证书
2008/12
上海市人事岗位资格证书 
证书说明：2008.08-2008.12   上海干部培训中心/上海紧缺人才培训办公室

　　语言能力
 
英语：读写能力良好 | 听说能力良好
英语：读写能力良好 | 听说能力良好

　　 专业技能
 
C1 熟练 |38
　　兴趣爱好
 
旅游  美食  游泳 羽毛球 网球

　　 附件

`

**Comment by dimkang** [comment]
如果格式固定，可以考虑用正则和一些小的逻辑。

如果格式不固定，可以考虑用一些分词／ner,

在正则里面要注意相似词的问题，可以考虑同义词词林来解决。

我正在法律文书的format化，跟你这个有点类似，不过稍微复杂一点，有的时候需要运用的句法分析。



在 2017年11月8日，下午5:03，altraman00 <notifications@github.com<mailto:notifications@github.com>> 写道：


@AnyListen<https://github.com/anylisten>

下面的json例子是我需要从文本（txt/doc/docx/pdf等）中解析之后得到的最终格式
{ "name":"小谢", "sex":"男", "phone":"13388888888", "email":"2345678@qq.com<mailto:2345678@qq.com>", "workExperience":{ "上海**商务咨询有限公司":{ "项目一":{ "time":"2011/05 -- 2012/05", "department":"总办会", "Position":"总经理", "workDesc":"一、负责公司人力资源规划、组织架构设计与建设； 二、建立与完善公司各项规章制度的编制、组织实施、监督、修订、管理等相关工作； 三、依据用人部门的招聘需求和公司的人员编制，拟定年度、季度招聘计划，实施招聘，定期对各招聘渠道进行数据分析，选择最佳招聘方式；", "":"" }, "项目二":{ "time":"2012/06 -- 2015/05", "department":"总办会", "Position":"总经理", "workDesc":"1、人事各模块的管理工作（1）、进行工作分析，完成职位说明书；（2）、执行招聘计划，维护拓展各种招聘渠道；（3）、发布职位信息，收集简历，聘前测试和简历的初步筛选,安排面试；", "":"" } }, "北京商务咨询有限公司":{ "项目一":{ "time":"2011/05 -- 2012/05", "department":"总办会", "Position":"总经理", "workDesc":"一、***********； 二、***********； 三、***********；", "":"" }, "项目二":{ "time":"2012/06 -- 2015/05", "department":"总办会", "Position":"总经理", "workDesc":"1、***********（1）、***********；（2）、***********；（3）、***********；", "":"" } } } }

文本内容如下：

`小谢 电子信息技术及仪器 本科 专业硕士 工程师 博士

男 | 已婚 | 1980 年5月生 | 户口：江苏 | 现居住于上海
7年工作经验 | 无党派人士| 身份证： 320326198088888888
浦东临港新城 200433
13398858888(手机)
E-mail: xw15688888888@163.com<mailto:xw15688888888@163.com>

　求职意向

·工作性质： 全职
·期望职业： 人力资源专员/助理、招聘经理/主管、人力资源主管、人力资源经理
·期望行业： 贸易/进出口、医药/生物工程、加工制造（原料加工/模具）、石油/石化/化工、交通/运输/物流、办公用品及设备、能源/矿产/采掘/冶炼
·工作地区： 上海、北京、天津
·期望月薪： 4001-6000元/月
. 目前状况： 我目前处于离职状态，可立即上岗

　自我评价

多年人力资源管理工作经验；精通招聘、培训和员工关系；丰富的招聘经验，有效控制招聘预算；善于从公司战略角度进行人力资源体系开发、再造和实务操作；熟悉国家、上海劳动人事政策，熟练协调、处理各类劳动关系问题，为企业规避用工风险；忠诚而敬业的职业素养，具有很强的沟通协调能力；人力资源管理师，C1证；

　　工作经验
2011/05 -- 2012/05
上海商务咨询有限公司 | 总经办 | 人力资源主管
行业类别：其它 | 企业性质：民营 | 规模：20-99人 | 职位月薪：4001-6000元/月
工作描述： 1
2009/08 -- 2011/04
上海信息科技有限公司 | 人力资源部 | 人力资源主管
行业类别：IT服务（系统/数据/维护）/多领域经营 | 企业性质：民营 | 规模：20-99人 | 职位月薪：4001-6000元/月
工作描述：一、负责公司人力资源规划、组织架构设计与建设； 二、建立与完善公司各项规章制度的编制、组织实施、监督、修订、管理等相关工作； 三、依据用人部门的招聘需求和公司的人员编制，拟定年度、季度招聘计划，实施招聘，定期对各招聘渠道进行数据分析，选择最佳招聘方式； 四、负责公司培训体系,依据公司发展战略,制订培训计划并组织实施培训；对培训效果进行跟踪分析； 五、负责公司薪酬福利及员工关系等管理工作； 六、监督、管理公司人事事务性工作（面试、录用、转正、调动、薪资制作、离职、员工劳动合同签订、招退工办理、五险一金操作、建立健全员工人事档案）； 七、建立员工沟通机制，维持企业、员工双方和谐稳定的劳动关系； 八、负责对分公司人力资源工作进行指导和监控工作； 九、完成总经理临时交办的各项工作任务。
2005/06 -- 2008/07
江苏**装饰工程有限公司 | 人力资源部 | 人力资源助理
行业类别：家居/室内设计/装饰装潢 | 企业性质：民营 | 规模：20-99人 | 职位月薪：2001-4000元/月
工作描述：1、人事各模块的管理工作（1）、进行工作分析，完成职位说明书；（2）、执行招聘计划，维护拓展各种招聘渠道；（3）、发布职位信息，收集简历，聘前测试和简历的初步筛选,安排面试； （4）、负责办理员工入职离职等调配事务，管理员工信息档案工作， 完善公司各项人事数据资料；（5）、组织员工进行入职培训、业务培训、提升培训等；（6）、负责员工的薪酬福利管理，包括员工薪资、四险一金、商业保险等事宜（7）、跟踪评估各类人才的使用情况，更新和维护人才储备库；（7）、提供招聘分析报告和企业人员结构分析报告。2、行政管理工作（1）、办公用品、设备、车辆、宿舍的管理及审核、控制；（2）、组织策划公司的员工活动，建立形成公司的企业文化；（3）、参与公司重大决策，并提出可行性建议；（4）、外联工作。

　　教育背景

2001/09 --2005/07
江苏常州大学| 法学| 本科

　　培训经历

2008/09 -- 2008/12
上海干部培训中心/上海紧缺人才培训办公室

培训课程：人事管理
所获证书：上海市人事岗位资格证书
培训地点：上海复旦大学新闻学院综合楼3楼
培训描述： 经过课程培训机构组织的阶段性的培训，掌握了人事工作中需要注意并熟知的细节处理及操作技巧;培训课程中的劳动合同法部分，也使得我更自信、更熟练地去处理员工关系。

　　 证书
2008/12
上海市人事岗位资格证书
证书说明：2008.08-2008.12 上海干部培训中心/上海紧缺人才培训办公室

　　语言能力

英语：读写能力良好 | 听说能力良好
英语：读写能力良好 | 听说能力良好

　　 专业技能

C1 熟练 |38
　　兴趣爱好

旅游 美食 游泳 羽毛球 网球

　　 附件

`

**Comment by altraman00** [comment]
@dimkang 我已经用正则和分词把个人的基本信息提取出来了，现在就是后面的项目经验的提取暂时没有一个好的解决办法，你说的句法分析我还没试。你那边的法律文书的format化，只用到了hanlp么？还有没有其他方法推荐的

**Comment by dimkang** [comment]
我们也有用srl, deep dependency，还有一些word2vec（找相似词），srl/deep dependency 会比较针对句子，需要做一些主谓宾以及语义方向的分析。

**Comment by dimkang** [comment]
@altraman00

**Comment by altraman00** [comment]
@dimkang 你提的srl/deep dependency有相关资料帮忙提供下么，感谢！

**Comment by dimkang** [comment]
https://www.ltp-cloud.com/demo/
每一个人可以有18g 的流量每个月，如果你要自己training的话，估计准确度不会那么好。
这个语料不太好找。语料少了，啥也没有，模型的话，目前大家都用的deep learning 来做的

**Comment by dimkang** [comment]
@altraman00

**Comment by altraman00** [comment]
@dimkang 方便提供下联系方式么，QQ或者微信，后期想请教下您

**Comment by dimkang** [comment]
@altraman00 说不上请教，大家互相帮助，我也正在装各种门板， 你有问题可以邮件我的，dimkang@hotmail.com, 我邮件时时看的。

**Comment by dimkang** [comment]
@altraman00 说不上请教，大家互相帮助，我也正在撞各种门板， 你有问题可以邮件我的，dimkang@hotmail.com, 我邮件时时看的。

**Comment by altraman00** [comment]
@dimkang 好的，谢谢了！

**Comment by TylunasLi** [comment]
看了下你的例子，感觉可以将文本分为多个句子，然后识别块开始行和结尾行，用状态机的方式提取。
如果问题比现在看到的还要复杂，则可以分析句子的特征，用序列标注方式解决问题。

**Comment by weiarqq** [comment]
@TylunasLi  请教下，最近也遇到这方面的问题，可以说的更详细点吗？

**Comment by panxia** [comment]
@altraman00

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
