### ISSUE TITLE
关于Vector类以及相关的问题

### ISSUE THREAD

**Issue by tiandiweizun** [hankcs/HanLP#669]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.5.0
我使用的版本是：1.5.0

## 我的问题

1. 对于Vector类里面的cosine方法表示不理解
为什么计算dot的结果再开平方，加载词向量的时候已经是单位向量，也就是说计算cosine直接返回结果即可。没明白为什么这么做？

2. 对于DocVectorModel的query方法的不理解（文档向量生成）
结果除以n的目的是为了什么，求期望？如果是求期望，是不是计算完成之后应该计算单位向量。以下贴一段我的测试代码：
<pre><code>  
    public static void main(String[] args) {
        List<String> one = new ArrayList<>();
        one.add("我");
        one.add("是");
        one.add("程序员");

        List<String> other = new ArrayList<>();
        other.add("程序员");
        other.add("很");
        other.add("苦逼");

        float[] senOne = new float[200];
        for (String s : one) {
            //通过ansj提供的源码加载的二进制词向量文件
            float[] floats = WordSimilarity.getWordMap().get(s);
            if (floats == null) {
                System.out.println(s + "未找到词向量");
                continue;
            }
            for (int i = 0; i < floats.length; i++) {
                senOne[i] += floats[i];
            }
        }
        float[] senTwo = new float[200];
        for (String s : other) {
            //通过ansj提供的源码加载的二进制词向量文件
            float[] floats = WordSimilarity.getWordMap().get(s);
            if (floats == null) {
                System.out.println(s + "未找到词向量");
                continue;
            }
            if (floats == null) {
                System.out.println(s + "未找到词向量");
                continue;
            }
            for (int i = 0; i < floats.length; i++) {
                senTwo[i] += floats[i];
            }
        }
        System.out.println("词向量直接相加 + cosine ：" + cosine(senOne, senTwo));
        System.out.println("DocVectorModel.query + Vector.cosine：" + query(one).cosine(query(other)));
        System.out.println("DocVectorModel.query + cosine：" + cosine(query(one).elementArray, query(other).elementArray));
    }

    public static double cosine(float[] x, float[] y) {
        double xx = 0;
        double xy = 0;
        double yy = 0;
        for (int i = 0; i < x.length; i++) {
            xx += x[i] * x[i];
            xy += x[i] * y[i];
            yy += y[i] * y[i];
        }
        return xy / Math.sqrt(xx * yy);
    }

    /**
     * 直接copy的DocVectorModel的query方法
     * @param words 分词结果
     * @return 句向量
     */
    public static Vector query(List<String> words) {
        if (words == null || words.size() == 0) return null;
        Vector result = new Vector(200);
        int n = 0;
        for (String word : words) {
            float[] floats = WordSimilarity.getWordMap().get(word);

            if (floats == null) {
                continue;
            }
            result.addToSelf(new Vector(floats));
            ++n;
            if (n == 0) {
                return null;
            }
        }
        result.divideToSelf(n);
        return result;
    }
</code></pre>
## 测试结果
词向量直接相加 + cosine ：0.7249490543441774
DocVectorModel.query + Vector.cosine：0.5651151
DocVectorModel.query + cosine：0.7249490499784463

## 结论
个人感觉1.文档向量应该除以向量的模，2.Vector.cosine方法应该直接返回dot结果。
不知道我说的对不对。希望指正。

**Comment by hankcs** [comment]
感谢指正，已经修复。

**Comment by tiandiweizun** [comment]
女王大人，这年头很少见开源这么拼的，工程做的这么好，迭代速度这么快，终于赶好了论文，不再飞行了，谢谢你的无私奉献。

**Comment by Xiaona12** [comment]
这里边WordSimilarity函数有没有源码？

**Comment by tiandiweizun** [comment]
这个WordSimilarity是我个人写的，其实没有什么，就是读取词向量的，计算词的 语义距离，可以通过词向量计算，也可以通过同义词林计算，在上文中，仅提供读取词向量而已的功能，因为hanlp提供提取的是明文，我的词向量是二进制文件，读取词向量二进制请参考“http://blog.csdn.net/zhaoxinfan/article/details/11640573”，而WordSimilarity调用此篇文章的词向量加载后的map，通过同义词林计算相似度，参照文章“https://wenku.baidu.com/view/0b1b7d5e804d2b160b4ec030.html”，java源码网上也有。

**Comment by Xiaona12** [comment]
我现在论文里要用到这个算法，就是将一篇中文文章的词转换成词向量，然后计算相似度。是要先将文章读进来，然后具体是怎么做？还是你写的这个HanLP里边有直接实现的函数，能说一下具体怎么做？非常感谢！！！

**Comment by tiandiweizun** [comment]
抱歉，我一般浏览github比较少，你的问题描述的我看不懂，我解答一下我看的懂的吧
1.@tiandiweizun你的那个源码方便透漏吗？？  答：如果是我的源码，没有办法直接给你使用。
2.你说的网址里的代码有一段是这个，词数和大小不是一个吗？  答：词数和大小不是一个。
3.都是一句话中的词语的个数？  答：这是读取词向量，跟句子没有关系。

其他：首先，通过c语言或者hanlp训练词向量，怎么训练，看hanlp的wiki
           其实：如果是二进制版本，需要使用http://blog.csdn.net/zhaoxinfan/article/details/11640573这个网站读取，如果不是二进制，你自己打开文件你都知道怎么处理（自己写代码，很容易）
           再次：拿到一个句子，进行分词，然后取每个词的词向量，加权求和得到句子向量，也可以使用hanlp的DocVectorModel中的方法，如何使用看hanlp的wiki。
