### ISSUE TITLE
Term添加equals, hashCode方法及实现comparable接口

### ISSUE THREAD

**Issue by laoyang945** [hankcs/HanLP#67]
只是一个建议，我现在是继承了一个Term类来做各种集合相关的操作以及排序
不过如果Term原生就有的话就更好了

**Comment by hankcs** [comment]
好的

另外，有需求不一定非要通知我，也可以自己实现然后提交pull request，众人拾柴火焰高。

**Comment by laoyang945** [comment]
好的，不过我不大熟悉github的这个操作……
