### ISSUE TITLE
请问，为什么不支持分词结果最小颗粒度？

### ISSUE THREAD

**Issue by mamba8** [hankcs/HanLP#670]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.5.0
我使用的版本是：1.3.5

## 我的问题

请问，为什么不支持分词结果最小颗粒度。
在lucene场景中创建更丰富的索引，以便支持更丰富的检索场景。
我翻阅了部分代码和文档发现，以及使用作为
com.hankcs.lucene.HanLPTokenizerFactory
索引分词器。需要分词的短语为:“弹簧床”，得到的分词结果为：“弹簧”+“床”。
那么检索器无论怎样设置，是无法通过：“弹”，或者相关检索字词查询到结果？

刚接触搜索相关知识，如有不认识不周的，请包涵。

**Comment by hankcs** [comment]
因为索引分词最小粒度为词（长度>=2），不是字。如果都拆分为字的话，则与Lucene默认的分词器一样，一搜一大片。如果这是搜索用户的需求的话，欢迎点击右上角用表情投票——
+1：希望拆分为单字
-1：不希望拆分单字

如果+1的人数多，我会在下几个版本内做出调整（同时留好开关），谢谢。

**Comment by mamba8** [comment]
如果只是基于颗粒度长度>=2的词创建索引，那么用户搜索单字的场景将大概率得不到满足，我支持拆分为单字。

**Comment by AnyListen** [comment]
对于单字你可以换一种搜索方式，例如通配符、正则等；
很少人会搜索单个字，如果把单字加入索引会造成准确率下降，虽然查全率很高但是个人觉得用处不大

**Comment by mamba8** [comment]
讨论这种方式是否有用，最好的论据是淘宝和京东都是支持单字检索的，
[淘宝搜索“到”](https://s.taobao.com/search?q=到)
[京东搜索“到”](https://search.jd.com/Search?keyword=到&enc=utf-8&wq=到)
用户是否习惯使用普通单字搜索是用户习惯的讨论，业务上应该支持这种用户行为。
如果用通配和正则实在不是一个好的方式。

**Comment by AnyListen** [comment]
@mamba8 如果实在需要可以直接使用系统自带的分词器即可，此外对于商品而言，应用场景不一样，按字切分没毛病；但是对于全文搜索，按字切分效果真的不敢恭维

**Comment by hankcs** [comment]
正在考虑如何在不损失效率的前提下，做成可配置的最小长度，默认2，有需要就调成1。

**Comment by mamba8** [comment]
@junphine 麻烦看清楚的上下文。

**Comment by mamba8** [comment]
@AnyListen 在我们的电商平台，要求更高的搜全率。在保证相关性上，使用多段搜索来满足。例如用户搜索：弹簧床，检索器第一次搜索【弹簧床，第二次搜索【弹簧+床】，第三次搜索【弹+簧+床】，最后union三段结果，并返回最终结果。

**Comment by mamba8** [comment]
@hankcs 谢谢

**Comment by AnyListen** [comment]
@mamba8 如果已经是多字段，只需要在不同的字段上设置不同的分词器即可；搜索引擎默认已经有很多种类的分词器，可满足你的要求

**Comment by mamba8** [comment]
@AnyListen 
检索的字段就是一个字段，虽然说可以copySource出多个字段，并用不同的检索期，但是无疑来说加大了整体的索引大小。我们目前希望在创建索引的时候以最小颗粒度的方式，那么在结合不同产品需求的时候，能够直接调整检索器的分词策略即可，这样在应对业务需求的时候能够更加灵活

**Comment by AnyListen** [comment]
@mamba8 如果使用的是ElasticSearch 只需要建立一个字段，一个字段可以设置多种分词器

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
