### ISSUE TITLE
NShortSegment分词算法实现问题

### ISSUE THREAD

**Issue by UCASREN** [hankcs/HanLP#671]
原文件：HanLP/src/main/java/com/hankcs/hanlp/seg/NShort/NShortSegment.java

第101行： List<Vertex> vertexList = coarseResult.get(0);

问题：
1） 为什么默认只选择第1条路径进行后续分析和处理，那它前面求出至少2条最短路径的意义何在？
2） 为什么定死nKind = 2？是为了什么考虑的？

例如：我使用NShortSegment进行分词“他说的确实在理。”

中间得到两条分词结果：
coarseResult = [[ , 他, 说, 的, 确实, 在, 理, 。,  ], [ , 他, 说, 的, 确实, 在理, 。,  ]]

最后输出：
[他/rr, 说/v, 的/ude1, 确实/ad, 在/p, 理/n, 。/w]

为什么后面只选择了第1个分词结果进行分析？而忽略了第2个分词结果？
按理来说，第2个分词结果不应该更好吗？

**Comment by UCASREN** [comment]
@hankcs

**Comment by hankcs** [comment]
由于未按issue模板规定填写，所以只能关闭这个issue。欢迎参考[《如何提问》](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，严格按模板要求填写issue。造成不便望海涵，谢谢合作。
