### ISSUE TITLE
创建同义词典未定义词后调用CommonSynonymDictionary.SynonymItem.toString方法空指针异常

### ISSUE THREAD

**Issue by huangjunjun** [hankcs/HanLP#673]
## 版本号
当前最新版本号是：portable-1.5.0
我使用的版本是：portable-1.5.0

## 我的问题
创建词典未定义词调用CommonSynonymDictionary.SynonymItem.toString方法空指针异常

### 触发代码

```
    SynonymItem item = CommonSynonymDictionary.SynonymItem.createUndefined("测试版");
    System.out.println(item.toString());
```

### 实际输出
空指针异常

## 其他信息
创建同义词典中未出现的词时 com.hankcs.hanlp.corpus.synonym.Synonym 的Type为null

**Comment by hankcs** [comment]
由于未提供足够信息，所以只能关闭这个issue。欢迎参考[《如何提问》](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，重新提一个友好的issue。造成不便望海涵，谢谢合作。
