### ISSUE TITLE
姓名前面有空格（全角和半角都算），导致姓名无法识别

### ISSUE THREAD

**Issue by bugesoft** [hankcs/HanLP#675]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [ ] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：master
我使用的版本是：hanlp:portable-1.5.0

## 我的问题
姓名前面有空格（全角和半角都算），导致姓名无法识别

hanlp的DemoChineseNameRecognition.java里，姓名前面加个空格，姓名就无法识别： 原句：" 王总和小丽结婚了", 识别结果：[ /w, 王/n, 总/b, 和/cc, 小丽/nr, 结婚/vi, 了/ule]
## 复现问题

我没有修改代码，所有的hanlp版本都有这个问题
### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

```
    public void testIssue1234() throws Exception
    {
        CustomDictionary.add("用户词语");
        System.out.println(StandardTokenizer.segment("触发问题的句子"));
    }
```
### 期望输出

```
期望输出
```

### 实际输出

```
实际输出
```

**Comment by hankcs** [comment]
已修复，请参考：https://github.com/hankcs/HanLP/blob/6a235c53cf204858053963d836ced70fa212772b/src/main/java/com/hankcs/hanlp/dictionary/nr/NRDictionary.java#L50

**Comment by bugesoft** [comment]
非常感谢你的及时回复！
应该还要处理全角的空格，\t，\n等空白字符
我先测试下你的最新代码

**Comment by bugesoft** [comment]
确实，半角空格可以过滤，全角空格、\t、\n、0xA0不行

**Comment by hankcs** [comment]
你可以在此处补充你需要的字符，然后提交pr，谢谢。

**Comment by bugesoft** [comment]
map.put(" ", new EnumItem<NR>(NR.K, NR.A)); // txt中不允许出现空格词条，这里补上
        map.put("　", new EnumItem<NR>(NR.K, NR.A)); // txt中不允许出现空格词条，这里补上
        map.put("\t", new EnumItem<NR>(NR.K, NR.A)); // txt中不允许出现空格词条，这里补上
        map.put("\n", new EnumItem<NR>(NR.K, NR.A)); // txt中不允许出现空格词条，这里补上
        map.put("0xA0", new EnumItem<NR>(NR.K, NR.A)); // txt中不允许出现空格词条，这里补上

**Comment by bugesoft** [comment]
如上，姓名前一个空白没问题了。但是，如果是多个空白，一样有问题：
原文："　　赵志辉同志任北京市顺义区质量技术监督局党组成员"
结果：[　　/w, 赵/nz, 志/n, 辉/ng, 同志/n, 任/v, 北京市/ns, 顺义区/ns, 质量/n, 技术/n, 监督局/nis, 党组/nis, 成员/nnt]

**Comment by bugesoft** [comment]
针对网页里段落开始很多空格的情况，比较笨的办法：
        map.put(" ", new EnumItem<NR>(NR.K, NR.A));        // 一个半角空格
        map.put("  ", new EnumItem<NR>(NR.K, NR.A));       // 二个半角空格
        map.put("   ", new EnumItem<NR>(NR.K, NR.A));      // 三半角空格
        map.put("    ", new EnumItem<NR>(NR.K, NR.A));     // 四个半角空格
        map.put("     ", new EnumItem<NR>(NR.K, NR.A));    // 五个半角空格
        map.put("      ", new EnumItem<NR>(NR.K, NR.A));   // 六个半角空格
        map.put("　", new EnumItem<NR>(NR.K, NR.A));       // 一个全角空格
        map.put("　　", new EnumItem<NR>(NR.K, NR.A));     // 两个全角空格
        map.put("　　　", new EnumItem<NR>(NR.K, NR.A));   // 三个全角空格
        map.put("　　　　", new EnumItem<NR>(NR.K, NR.A)); // 四个全角空格
        map.put("\t", new EnumItem<NR>(NR.K, NR.A));      // 制表符
        map.put("\n", new EnumItem<NR>(NR.K, NR.A));      // 换行符
        char c = 0xA0;
        map.put("" + c, new EnumItem<NR>(NR.K, NR.A));    // 160字符

**Comment by AnyListen** [comment]
推荐先对文字进行预处理，例如trim或者正则替换，过滤到不可见字符，然后在进行实体识别

**Comment by bugesoft** [comment]
有时候需要保留原文中的空格。如果trim后再分词，经常会影响原文位置。比如搜索高亮显示

**Comment by TylunasLi** [comment]
我司修改代码时，改为对所有未登录nr.txt中的词语，均赋予“A 词频 K 1 L 1”的标签。

**Comment by TylunasLi** [comment]
我司修改代码时，改为对所有未登录nr.txt中的词语，均赋予“A 词频 K 1 L 1”的标签。
