### ISSUE TITLE
Java1.9已经不开始支持动态增加枚举的部分方法

### ISSUE THREAD

**Issue by tiandiweizun** [hankcs/HanLP#676]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.5.0
我使用的版本是：1.5.0

## 我的问题

[
![qq 20171116103726](https://user-images.githubusercontent.com/13550295/32871119-3df4c0f8-caba-11e7-9018-9d3e3bac5196.png)
](url)
![package](https://user-images.githubusercontent.com/13550295/32871723-aa166f90-cabd-11e7-818c-10b494657c50.png)
JDK1.9重构了部分东西，且放到了不支持的包，参见上图
不知道有什么什么好方法可以解决

**Comment by hankcs** [comment]
1. 最初词性标注集是固定的，用枚举类型写代码很方便，而且可以在IDE中查看每个词性的意思。最重要的是，枚举实例数量固定，最省内存，所以就这么设计了。
1. 后来有用户提意见，希望加入自定义词性。虽然这个需求根本不符合统计自然语言处理的思路，但考虑到实践过程中确实经常遇到需要额外标记某些词语的场景，所以就用反射实现了。
1. 反射有利有弊，遇到jdk升级的时候必然产生这种兼容性问题。由于我个人不会经常升级降级各种版本，这种问题是希望用户自己[参考文档](http://www.hankcs.com/program/java/enum-java-examples-of-dynamic-modification.html)协助解决的。参考：https://github.com/hankcs/HanLP/wiki/FAQ#%E5%8A%A0%E5%85%A5%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%8D%E6%80%A7%E5%90%8E%E5%8F%91%E7%94%9Farrayindexoutofboundsexception
1. 长远的计划是重新设计词性类型，这必然带来API的断层。可能会放到2.0里面去做。

**Comment by tiandiweizun** [comment]
谢谢！有时候公司的项目jdk版本比较多，没有办法，升级到1.9估计也是两年后的事情了。由于jdk升级，开发者确实没有好办法。

**Comment by tiandiweizun** [comment]
IntentConfigImpl

**Comment by tiandiweizun** [comment]
感激不尽
