### ISSUE TITLE
关于分词的效率问题，标准分词和SpeedTokenizer都存在，请教！

### ISSUE THREAD

**Issue by LilyBlooper** [hankcs/HanLP#677]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [ ] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.5.0 portable
我使用的版本是： 1.5.0 portable

## 我的问题
HanLp的分词效率如何，只看到过关于急速分词的demo。但是那个demo是重复了1百万次相同的文本，怀疑内部有缓存等，看起来分词速度很高。而我自己进行了简单的5个文本的测试。效果不是很理想。

## 复现代码
```java
	@Test
	public void testCustomizeDict() {
		String[] sentences = new String[] { "这是一个伸手不见五指的黑夜。我叫孙悟空，我爱北京，我爱Python和C++。", "我不喜欢日本和服。",
				"雷猴回归人间。", "工信处女干事每月经过下属科室都要亲口交代24口交换机等技术性器件的安装工作", "结果婚的和尚未结过婚的" };
		// 进行自定义词性的配置
		CustomDictionary.insert("敏感词", "ssr 1024");
		CustomDictionary.insert("白洁", "ssr 1024");
		CustomDictionary.insert("白小洁", "ssr 1024");
		long startTime = System.currentTimeMillis();
		for (String sentence : sentences) {
			HanLP.segment(sentence);
		}
		long endTime = System.currentTimeMillis();
		System.out.println(endTime - startTime);
**// 大概消耗 300~400ms**
	}

	@Test
	public void testCustomizeSpeed() {
		String[] sentences = new String[] { "这是一个伸手不见五指的黑夜。我叫孙悟空，我爱北京，我爱Python和C++。", "我不喜欢日本和服。",
				"雷猴回归人间。", "工信处女干事每月经过下属科室都要亲口交代24口交换机等技术性器件的安装工作", "结果婚的和尚未结过婚的" };
		// 进行自定义词性的配置
		CustomDictionary.insert("敏感词", "ssr 1024");
		CustomDictionary.insert("白洁", "ssr 1024");
		CustomDictionary.insert("白小洁", "ssr 1024");
		long startTime = System.currentTimeMillis();
		for (String sentence : sentences) {
			SpeedTokenizer.segment(sentence);
		}
		long endTime = System.currentTimeMillis();
		System.out.println(endTime - startTime);
	}
**// 大概消耗80ms**
```
相比之下，确实急速分词快很多，但是还没有达到理想状态。急速分词根据您提供的demo来看，
分词速度：11068068.62字每秒 。 然而实际上多个不同的进行分词，感觉效率很低。
**请问是我的代码哪里写的不对吗？还是说环境上有哪些不正确的配置。**

另外，**HanLp是我首选的，但是看到jieba分词的java版。相同的测试用例，分词总计才消耗8ms。**
比Hanlp急速分词还快10倍，感觉这才是正常的水平。
环境都是本地开发机，在Intellij上进行运行，i5,8g内存。

```
	public static void main(String[] args) throws Exception {
		String[] sentences = new String[] { "这是一个伸手不见五指的黑夜。我叫孙悟空，我爱北京，我爱Python和C++。", "我不喜欢日本和服。",
				"雷猴回归人间。", "工信处女干事每月经过下属科室都要亲口交代24口交换机等技术性器件的安装工作", "结果婚的和尚未结过婚的" };
		JiebaSegmenter segmenter = new JiebaSegmenter();
		long startTime = System.currentTimeMillis();
		for (String sentence : sentences) {
			System.out
					.println(segmenter.process(sentence, JiebaSegmenter.SegMode.INDEX).toString());
		}
		long endTime = System.currentTimeMillis();
		System.out.println(endTime - startTime);
	}
**//大概消耗8ms**
```

**Comment by hankcs** [comment]
1. 内部没有缓存。
1. 代码里不可能放下1万行字符串测速度，所以循环测试。你可以试试读取txt小说，速度是一致的。
1. 你的测试方法是错误的，每个分词器初始化加载模型的耗时也被你算进去了。你可以先`SpeedTokenizer.segment("")`主动触发初始化，然后跑秒开始。
1. 根据阿里巴巴架构师杨尚川的测试，HanLP的极速分词应该比结巴快一个数量级：https://github.com/ysc/cws_evaluation

**Comment by hankcs** [comment]
由于我写了不回复不签署注意事项的issue，为了避免成为反例，所以先关掉这个issue。
问题应该解决了，如果还有问题，欢迎重开issue。

**Comment by LilyBlooper** [comment]
感谢您迅速详尽的解释，谢谢！
