### ISSUE TITLE
非常奇怪的姓名识别错误

### ISSUE THREAD

**Issue by bugesoft** [hankcs/HanLP#678]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [ ] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：master
我使用的版本是：master

## 我的问题
句子中姓名识别出错，按常理推论不应该的

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

```
   Segment segment = HanLP.newSegment().enableNameRecognize(true).enableOrganizationRecognize(true);
   List<Term> termList = segment.seg(sentence);
   System.out.println(termList);
```
### 期望输出

```
期望输出
```
三亚市教育局/nt, 吴萍/nr, 局长/nnt
### 实际输出

```
实际输出
```
三亚市教育局/nt, 吴/tg, 萍/nz, 局长/nnt

**Comment by hankcs** [comment]
Segment segment = HanLP.newSegment().enableNameRecognize(true).enableOrganizationRecognize(true);
        System.out.println(segment.seg(
                "三亚市教育局吴萍局长"
        ));

[三亚市教育局/nt, 吴萍/nr, 局长/nnt]

无法复现问题。
另，请勾选注意事项，谢谢合作。

**Comment by jcjview** [comment]
I found similar case:
[三亚市/ns, 教育局/n, 吴/nr, 萍/nr, 局长/n]
Segment segment = HanLP.newSegment();


 <version>portable-1.5.2</version>

**Comment by hankcs** [comment]
请外挂data，portable内部的data过时了。
