### ISSUE TITLE
自定义词库优先级问题

### ISSUE THREAD

**Issue by solobea** [hankcs/HanLP#679]
CustomDictionary.add("政策");
StandardTokenizer.SEGMENT.enableCustomDictionaryForcing(true);
System.out.println(HanLP.segment("新政策"));

想要切出的是“政策”返回的是新政策

**Comment by solobea** [comment]
索引切词中是不是不支持自定义词库的词性标注！

**Comment by hankcs** [comment]
由于未提供足够信息，所以只能关闭这个issue。欢迎参考[《如何提问》](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，重新提一个友好的issue。造成不便望海涵，谢谢合作。
