### ISSUE TITLE
CRF模型训练求教

### ISSUE THREAD

**Issue by waiteryee127** [hankcs/HanLP#68]
你好，大神，请教一下：如果crf模型能够识别"花千骨"这个新词，是不是需要在训练语料中药包含多个  花千骨 这个词才能训练出这个模型？另您能不能提供一下CRF模型的训练语料数据，邮箱为1527zhaobin@163.com，多谢！

**Comment by hankcs** [comment]
你好，我不是大神:smirk:

0. 不一定非要精确的"花千骨"，结合前后文有类似的词语就可以，比如“你认识花千朵吗？”“有个人叫刘千骨啊”之类的出现多次后，训练出来的模型就有可能能够识别"花千骨"。
0. CRF训练语料都是由人民日报分词语料转换而来的，遗憾的是，无论是2014人民日报分词语料还是1998版都是受版权保护的，到处散布有法律风险。但网上也有流传，如：http://download.csdn.net/detail/zxlxstly/669716

**Comment by waiteryee127** [comment]
你好，你就是大神：
哦哦，现在使用的CRF模型是根据2014还是98的语料训练的？对原始语料的分词用的是HanLP还是其他第三方分词器，比如中科院分词器？~

谢谢！

2015-10-09 

1527zhaobin 



发件人：hankcs <notifications@github.com>
发送时间：2015-10-09 17:21
主题：Re: [HanLP] CRF模型训练求教 (#68)
收件人："hankcs/HanLP"<HanLP@noreply.github.com>
抄送："赵斌"<1527zhaobin@163.com>

你好，我不是大神
不一定非要精确的"花千骨"，结合前后文有类似的词语就可以，比如“你认识花千朵吗？”“有个人叫刘千骨啊”之类的出现多次后，训练出来的模型就有可能能够识别"花千骨"。 
CRF训练语料都是由人民日报分词语料转换而来的，遗憾的是，无论是2014人民日报分词语料还是1998版都是受版权保护的，到处散布有法律风险。但网上也有流传，如：http://download.csdn.net/detail/zxlxstly/669716

**Comment by hankcs** [comment]
2014，原始语料就是分好词的，与第三方分词器无关。
