### ISSUE TITLE
1.3.2版本    “停牌自查”在处于句末时进行分词，该词会消失

### ISSUE THREAD

**Issue by ZhoChoran** [hankcs/HanLP#680]
1.3.2版本中出现：
例句：武汉凡谷9日停牌自查
词语“停牌自查”在 segment.seg(sentence)操作后消失，仅出现‘武汉凡谷‘ 、’9日’；
除此之外还有些其它动词在句末时会显现此种情况。
望解决。

**Comment by hankcs** [comment]
未能复现问题：[武汉/ns, 凡/d, 谷/ng, 9/m, 日/j, 停牌/nz, 自查/vn]

由于未提供足够信息，所以只能关闭这个issue。欢迎参考[《如何提问》](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，重新提一个友好的issue。造成不便望海涵，谢谢合作。
下次发issue请严格按模板填写，勾选注意事项，谢谢合作。
