### ISSUE TITLE
NShortSegment分词算法实现问题

### ISSUE THREAD

**Issue by UCASREN** [hankcs/HanLP#681]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：v1.5.2
我使用的版本是：v1.5.2

## 我的问题
1） 为什么NShortSegment分词默认只选择第1条路径进行后续分析和处理，那它前面求出至少2条最短路径的意义何在？（文件NShortSegment.java第101行：List vertexList = coarseResult.get(0)）
2） 为什么NShortSegment分词定死nKind = 2？是为了什么考虑的？

## 复现问题

例如：我使用NShortSegment进行分词“他说的确实在理。”

虽然中间得到两条分词结果：
coarseResult = [[ , 他, 说, 的, 确实, 在, 理, 。, ], [ , 他, 说, 的, 确实, 在理, 。, ]]

但是后面默认使用第一个结果进行后续分析（第101行：List vertexList = coarseResult.get(0)），导致实际输出就是第一个分词结果。

那么这样的话，NShortSegment分词出两种分词结果，有什么意义呢？第二个分词结果后面根本就没用？而且个人认为第二个分词结果稍微好一些（路径更短）。

另外，为什么NSegment.java中定死nKind=2，即变成2-最短路径。这个nKind定死为2是出于分词效率考虑吗？是不是可以让用户来确定nKind的具体取值？
### 步骤

程序运行如下。

### 触发代码

```
   	public void testSegment() {
		Segment nShortSegment = new NShortSegment().enableCustomDictionary(true).enablePlaceRecognize(true).enableOrganizationRecognize(true);
		List<Term> term1 = nShortSegment.seg("他说的确实在理。");
		System.out.println(term1);
	}
```
### 期望输出

```
[ , 他, 说, 的, 确实, 在理, 。, ]
```

### 实际输出

```
[ , 他, 说, 的, 确实, 在, 理, 。, ]
```

**Comment by UCASREN** [comment]
@hankcs ，求解答。。。。谢谢！！！

**Comment by hankcs** [comment]
1. 求N-Best路径的目的是为了命名实体识别，不是为了粗分的准确性，而是减小CWS到NER的错误传播。
2. nKind=2的确是效率考虑，目前不支持自定义。不过欢迎PR

如果对算法存疑，请阅读张华平老师的论文。

**Comment by UCASREN** [comment]
@hankcs 可能您还没理解我的意思。我是说为什么默认选择第1个粗分结果进行后续的NER过程？假如某个句子的2-Best路径得到4种粗分结果，那按照您的代码流程，就默认选择了第一个粗分结果进行后面的命名实体识别，那前面费那么多时间求的另外3种粗分结果的有什么作用，后面也没有用到它们啊？

**Comment by hankcs** [comment]
命名实体识别的结果在List<Vertex> vertexList = coarseResult.get(0);之前就已经存到wordNetOptimum里面了，如果NERexists，vertexList将被graph上的结果覆盖。请仔细阅读这段代码：

        for (List<Vertex> vertexList : coarseResult)
        {
            if (HanLP.Config.DEBUG)
            {
                System.out.println("粗分结果" + convert(vertexList, false));
            }
            // 实体命名识别
            if (config.ner)
            {
                wordNetOptimum.addAll(vertexList);
                int preSize = wordNetOptimum.size();
                if (config.nameRecognize)
                {
                    PersonRecognition.Recognition(vertexList, wordNetOptimum, wordNetAll);
                }
                if (config.translatedNameRecognize)
                {
                    TranslatedPersonRecognition.Recognition(vertexList, wordNetOptimum, wordNetAll);
                }
                if (config.japaneseNameRecognize)
                {
                    JapanesePersonRecognition.Recognition(vertexList, wordNetOptimum, wordNetAll);
                }
                if (config.placeRecognize)
                {
                    PlaceRecognition.Recognition(vertexList, wordNetOptimum, wordNetAll);
                }
                if (config.organizationRecognize)
                {
                    // 层叠隐马模型——生成输出作为下一级隐马输入
                    vertexList = Dijkstra.compute(GenerateBiGraph(wordNetOptimum));
                    wordNetOptimum.addAll(vertexList);
                    OrganizationRecognition.Recognition(vertexList, wordNetOptimum, wordNetAll);
                }
                if (!NERexists && preSize != wordNetOptimum.size())
                {
                    NERexists = true;
                }
            }
        }

        List<Vertex> vertexList = coarseResult.get(0);
        if (NERexists)
        {
            Graph graph = GenerateBiGraph(wordNetOptimum);
            vertexList = Dijkstra.compute(graph);
            if (HanLP.Config.DEBUG)
            {
                System.out.printf("细分词网：\n%s\n", wordNetOptimum);
                System.out.printf("细分词图：%s\n", graph.printByTo());
            }
        }

**Comment by UCASREN** [comment]
那我测试的“他说的确实在理。”中不存在命名实体，因此NERexists=false。这样的话，vertexList将不会被graph覆盖。然而，根据最后分词结果，我个人认为第二种分词结果（[ , 他, 说, 的, 确实, 在理, 。, ]）是不是更好一些？换句话说，也就是路径更短一些呢？

**Comment by UCASREN** [comment]
@hankcs ，前段时间才开始研究NLP，可能理解不深，谢谢回复~

**Comment by hankcs** [comment]
模型不是人，它只选择它认为概率最大的路径，它的认知学习自有限的语料，肯定比不上人类十几年的教育。

**Comment by UCASREN** [comment]
好的，我大概了解了，谢谢解答！

**Comment by UCASREN** [comment]
@hankcs  您好，请问有HanLP的整体框架图（主要想要分词和NER部分的框架图，整体的也可以）吗？我在网上找一圈都没找着，自己画的话，又不全面。。。想求这方面的资料，可以提供一下吗？谢谢~

**Comment by hankcs** [comment]
你好，没有这方面文档。你可以参考张华平老师和刘群老师的相关论文。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
