### ISSUE TITLE
常见官职识别出错

### ISSUE THREAD

**Issue by bugesoft** [hankcs/HanLP#683]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：master
我使用的版本是：master

## 我的问题

常见官职如“外交部长”识别出错
### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

```
Segment segment = HanLP.newSegment().enableNameRecognize(true).enableOrganizationRecognize(true);
List<Term> termList = segment.seg("国防部长王毅向记者介绍此访情况。");
System.out.println(termList);
```
### 期望输出

```
[国防部长/n, 王毅/nr, 向/p, 记者/nnt, 介绍/v, 此/rzs, 访/v, 情况/n, 。/w]
```
[国防部长/n, 王毅/nr, 向/p, 记者/nnt, 介绍/v, 此/rzs, 访/v, 情况/n, 。/w]
### 实际输出

```
[国防部/nt, 长/a, 王毅/nr, 向/p, 记者/nnt, 介绍/v, 此/rzs, 访/v, 情况/n, 。/w]
```
## 其他信息

总体感觉master不够稳定

**Comment by hankcs** [comment]
感谢反馈，

1. 2014人民日报统计到的ngram中含有 未##团@长 ，引发了这个问题，现在已经删掉了
1. 1998就没有这个问题
1. 你可以打开调试模式排查这种问题：

```
        HanLP.Config.enableDebug();
        Segment segment = new DijkstraSegment();
        System.out.println(segment.seg(
                "国防部长王毅向记者介绍此访情况"
        ));
```

master默认是2014，质量不高，可能是你认为不稳定的原因吧。

**Comment by bugesoft** [comment]
hankcs太勤奋了，非常敬佩！刚醒就看到你的反馈，马上试试😊

**Comment by yufengzhixing** [comment]
您好，我也遇到了相似问题，请问我能自己修改CoreNatureDictionary.ngram.txt文件么？修改CoreNatureDictionary.ngram.txt文件，并删除CoreNatureDictionary.ngram.txt.table.bin文件，可是删除之后无法再生成CoreNatureDictionary.ngram.txt.table.bin文件，导致修改无效，请问怎会让修改有效。谢谢！

**Comment by hankcs** [comment]
遇到问题第一步`HanLP.Config.enableDebug();`排查，无非是路径不对罢了。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
