### ISSUE TITLE
常见名词和连词“和”被合并为一个名词了

### ISSUE THREAD

**Issue by bugesoft** [hankcs/HanLP#684]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [ ] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：master
我使用的版本是：master

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

```
HanLP.Config.enableDebug();
Segment segment = new DijkstraSegment();
List<Term> termList = segment.seg("开展公共资源交易活动监督检查和举报投诉处理");
System.out.println(termList);
```
### 期望输出

```
[开展/v, 公共资源/gi, 交易/vn, 活动/vn, 监督/vn, 检查/n,和/cc, 举报/vn, 投诉/vn, 处理/vn]
```

### 实际输出

```
粗分结果[开展/v, 公共资源/gi, 交易/vn, 活动/vn, 监督/vn, 检查和/n, 举报/vn, 投诉/vn, 处理/vn]
人名角色观察：[  K 1 A 1 ][开展 L 11 K 4 ][公共资源 A 20833310 ][交易 L 2 ][活动 L 13 K 3 ][监督 A 20833310 ][检查和 A 20833310 ][举报 K 100 L 33 M 22 ][投诉 K 9 L 3 ][处理 L 27 K 12 ][  K 1 A 1 ]
人名角色标注：[ /K ,开展/L ,公共资源/A ,交易/L ,活动/L ,监督/A ,检查和/A ,举报/K ,投诉/K ,处理/L , /A]

[开展/v, 公共资源/gi, 交易/vn, 活动/vn, 监督/vn, 检查和/n, 举报/vn, 投诉/vn, 处理/vn]
```

## 其他信息

debug部分输出：
to: 21, from: 19, weight:11.60, word:督@检查
to: 22, from: 20, weight:11.24, word:检@查
to: 23, from: 21, weight:03.15, word:检查@和
to: 23, from: 22, weight:04.03, word:查@和
to: 24, from: 23, weight:07.47, word:和@举

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。
下次发issue请严格按模板填写，勾选注意事项，谢谢合作。
