### ISSUE TITLE
自定义词性 + 自定义词条，与 portable 自带词典冲突

### ISSUE THREAD

**Issue by kerraway** [hankcs/HanLP#685]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号 
当前最新版本号是：portable-1.5.2
我使用的版本是：portable-1.5.2
备注：web项目，基于 springboot 1.5.8.RELEASE，docker 部署

## 代码复现
我想用 HanLP 匹配语句中的国家城市信息，国家城市名字是规定好的，在库里有一套，在 app 启动时，将库里的国家城市数据刷入 CustomDictionary 中，代码如下：
```java
/**
   * 将国家城市名添加到用户词典
   */
  @Override
  public void addCountryAndCityNameIntoDict() {
    //添加国家
    List<Country> countries = countryRepository.findAll();
    for (Country country : countries) {
      boolean countryInvalid = country.getId() == null || StringUtils.isEmpty(country.getCnName())
              || StringUtils.isEmpty(country.getEnName());
      if (countryInvalid) {
        continue;
      }
      CustomDictionary.insert(country.getCnName(), "country 1000000");
      CustomDictionary.insert(country.getEnName().toLowerCase(), "country 1000000");
      //根据国家，添加城市
      List<City> cities = cityRepository.findByCountryId(country.getId());
      for (City city : cities) {
        boolean cityInvalid = city.getId() == null || StringUtils.isEmpty(city.getCnName())
                || StringUtils.isEmpty(city.getEnName());
        if (cityInvalid) {
          continue;
        }
        CustomDictionary.insert(city.getCnName(), "city 1000000");
        CustomDictionary.insert(city.getEnName().toLowerCase(), "city 1000000");
      }
    }
  }
```
城市名称示例：
```
---------------------
  cn_name   en_name  
---------------------
  上海       Shanghai 
  北京       Beijing     
  杭州       Hangzhou 
  台北       Taibei    
  海南       Kainan    
  重庆       Zhongqing
---------------------
```
然后我试了几个分词器，分词结果都是以 portable 版本自带词典的词语为主：
```java
@GetMapping("/test")
  public Result testHanLP(@RequestParam String query) {
    //转换格式
    query = HanLP.convertToSimplifiedChinese(query.toLowerCase());

    Map<String, String> data = new LinkedHashMap<>(7);

    Segment standardTokenizer = StandardTokenizer.SEGMENT.enableCustomDictionaryForcing(true).enablePlaceRecognize(false);
    data.put("标准分词", standardTokenizer.seg(query).toString());

    data.put("NLP分词", NLPTokenizer.segment(query).toString());

    Segment indexTokenizer = IndexTokenizer.SEGMENT.enableCustomDictionaryForcing(true).enablePlaceRecognize(false);
    data.put("索引分词", indexTokenizer.seg(query).toString());

    Segment nShortSegment = new NShortSegment().enableCustomDictionaryForcing(true).enablePlaceRecognize(false);
    data.put("N-最短路径分词", nShortSegment.seg(query).toString());

    Segment shortSegment = new DijkstraSegment().enableCustomDictionaryForcing(true).enablePlaceRecognize(false);
    data.put("最短路径分词", shortSegment.seg(query).toString());

    return Results.SUCC.data(data);
  }
```
测试语句：海南省北京市上海市重庆市台湾岛台湾省台北市北京是首都海南是旅游胜地
分词效果：
```json
{
  "code": 0,
  "msg": "成功",
  "data": {
    "标准分词": "[海南省/ns, 北京市/ns, 上海市/ns, 重庆市/ns, 台湾岛/nz, 台湾省/ns, 台北市/ns, 北京/city, 是/v, 首都/n, 海南/city, 是/v, 旅游/vn, 胜地/n]",
    "NLP分词": "[海南省/ns, 北京市/ns, 上海市/ns, 重庆市/ns, 台湾岛/nz, 台湾省/ns, 台北市/ns, 北京/city, 是/v, 首都/n, 海南/city, 是/v, 旅游/vn, 胜地/n]",
    "索引分词": "[海南省/ns, 海南/ns, 北京市/ns, 北京/ns, 上海市/ns, 上海/ns, 重庆市/ns, 重庆/ns, 台湾岛/nz, 台湾/ns, 台湾省/ns, 台湾/ns, 台北市/ns, 台北/ns, 北京/city, 是/v, 首都/n, 海南/city, 是/v, 旅游/vn, 胜地/n]",
    "N-最短路径分词": "[海南省/ns, 北京市/ns, 上海市/ns, 重庆市/ns, 台湾岛/nz, 台湾省/ns, 台北市/ns, 北京/city, 是/v, 首都/n, 海南/city, 是/v, 旅游/vn, 胜地/n]",
    "最短路径分词": "[海南省/ns, 北京市/ns, 上海市/ns, 重庆市/ns, 台湾岛/nz, 台湾省/ns, 台北市/ns, 北京/city, 是/v, 首都/n, 海南/city, 是/v, 旅游/vn, 胜地/n]"
  }
}
```

### 期望输出
目前来看，索引分词还算凑合，我期望的是：
```
[海南省/ns, 海南/city, 北京市/ns, 北京/city, 上海市/ns, 上海/city, 重庆市/ns, 重庆/city, 台湾岛/nz, 台湾/city, 台湾省/ns, 台湾/city, 台北市/ns, 台北/city, 北京/city, 是/v, 首都/n, 海南/city, 是/v, 旅游/vn, 胜地/n]
```

### 提问
- 我该如何在用官方 portable jar 包的前提下，得到预期的输出？毕竟自己打包，然后放在项目下，不太优雅（我现在没有自己的 maven 仓库，如果自己打包的话，只能放在项目下了）。
- 在使用官方 portable jar 包时，能否提供一个禁用其自带的某些词典的方法？感觉这是一种解决思路。
- 我有考虑借助 hanlp.properties 和 自定义 data 目录，但是这样对于一个 web 项目来说，部署时就不太方便。

**Comment by hankcs** [comment]
目前没有封装这种方法，因为设计上是希望用户用配置文件按需挂载自己的词典。
有很多变通手段，第一可以抛弃配置文件，直接将com.hankcs.hanlp.HanLP.Config#CustomDictionaryPath写成自己的路径（位于自己jar、war包下的资源路径）
第二可以在启动时清空词库：

        CustomDictionary.dat = new DoubleArrayTrie<CoreDictionary.Attribute>();
        TreeMap<String, CoreDictionary.Attribute> dict = new TreeMap<String, CoreDictionary.Attribute>();
        dict.put("我的词条1", CoreDictionary.Attribute.create("nz 1"));
        CustomDictionary.dat.build(dict);
        System.out.println(HanLP.segment("其他词典都被清空了，只剩下我的词条1"));

**Comment by Gegoiuty** [comment]
感谢回复。
我倾向于启动时清空词库的做法，但是效果并不好。
`我的词条1` 显然在 portable 自带词库里不存在，但是 `北京` 和 `北京市` 都是存在的，所以这么写，效果并不好：
```java
CustomDictionary.dat = new DoubleArrayTrie<>();
    TreeMap<String, CoreDictionary.Attribute> dict = new TreeMap<>();
    dict.put("我的词条1", CoreDictionary.Attribute.create("nz 1"));
    dict.put("北京", CoreDictionary.Attribute.create("city 1"));
    CustomDictionary.dat.build(dict);
    System.out.println(HanLP.segment("其他词典都被清空了，只剩下我的词条1北京是首都北京市朝阳区"));
```
#### 输出：
```
[其他/r, 词典/n, 都/d, 被/p, 清/a, 空/a, 了/ul, ，/w, 只/d, 剩下/v, 我的词条1/nz, 北京/city, 是/v, 首都/n, 北京市/ns, 朝阳区/ns]
```
#### 我的期望：
```
[其他/r, 词典/n, 都/d, 被/p, 清/a, 空/a, 了/ul, ，/w, 只/d, 剩下/v, 我的词条1/nz, 北京/city, 是/v, 首都/n, 北京/city,市/n, 朝阳区/ns]
```

**Comment by hankcs** [comment]
建议使用词典分词，完全加载自己的。

**Comment by Gegoiuty** [comment]
能否展示一下代码如何实现，不太清除具体如何操作，谢谢。

**Comment by hankcs** [comment]
https://github.com/hankcs/HanLP/blob/master/src/test/java/com/hankcs/demo/DemoUseAhoCorasickDoubleArrayTrieSegment.java

**Comment by Gegoiuty** [comment]
非常感谢，:( 我还是没有好好看 demo 啊！
```java
@Test
public void test4() {
  String text = "北京市朝阳区房子贵，北京是首都，上海市是魔都，重庆市有火锅，台湾省是一个省";
  AhoCorasickDoubleArrayTrieSegment segment = new AhoCorasickDoubleArrayTrieSegment();
  segment.setTrie(this.loadDictionary());
  System.out.println(segment.seg(text));
}

private AhoCorasickDoubleArrayTrie<CoreDictionary.Attribute> loadDictionary() {
  AhoCorasickDoubleArrayTrie<CoreDictionary.Attribute> trie = new AhoCorasickDoubleArrayTrie<>();
  TreeMap<String, CoreDictionary.Attribute> map = new TreeMap<>();

  map.put("北京", CoreDictionary.Attribute.create("city 1000"));
  map.put("上海", CoreDictionary.Attribute.create("city 1000"));
  map.put("重庆", CoreDictionary.Attribute.create("city 1000"));
  map.put("台湾", CoreDictionary.Attribute.create("city 1000"));

  if (!map.isEmpty()) {
    trie.build(map);
  }
  return trie;
}
```

**Comment by mfxss** [comment]
@hankcs 这里的demo用的分词算法与NLPtokenizer相同吗？
如果我想在NLPtokenizer的默认字典data\dictionary\customCustomDictionary.txt文件中直接加词，而不是每次用insert方法，不知可行吗？
如果直接在config里面改路径和在原来的文件下修改，这两种方法貌似并没有什么区别。

**Comment by hankcs** [comment]
> @hankcs 这里的demo用的分词算法与NLPtokenizer相同吗？
> 如果我想在NLPtokenizer的默认字典data\dictionary\customCustomDictionary.txt文件中直接加词，而不是每次用insert方法，不知可行吗？
> 如果直接在config里面改路径和在原来的文件下修改，这两种方法貌似并没有什么区别。

1. 不同。
1. 可行。
1. https://github.com/hankcs/HanLP/wiki/FAQ#%E4%B8%BA%E4%BB%80%E4%B9%88%E4%BF%AE%E6%94%B9%E4%BA%86%E8%AF%8D%E5%85%B8%E8%BF%98%E6%98%AF%E6%B2%A1%E6%9C%89%E6%95%88%E6%9E%9C

**Comment by mfxss** [comment]
> > @hankcs 这里的demo用的分词算法与NLPtokenizer相同吗？
> > 如果我想在NLPtokenizer的默认字典data\dictionary\customCustomDictionary.txt文件中直接加词，而不是每次用insert方法，不知可行吗？
> > 如果直接在config里面改路径和在原来的文件下修改，这两种方法貌似并没有什么区别。
> 
> 1. 不同。
> 2. 可行。
> 3. https://github.com/hankcs/HanLP/wiki/FAQ#%E4%B8%BA%E4%BB%80%E4%B9%88%E4%BF%AE%E6%94%B9%E4%BA%86%E8%AF%8D%E5%85%B8%E8%BF%98%E6%98%AF%E6%B2%A1%E6%9C%89%E6%95%88%E6%9E%9C

我删除了缓存文件CustomDictionary.txt.bin，并重新运行程序，但是新生成的缓存文件与原来的文件相比小了很多，这是什么原因，对分词结果有影响吗？

**Comment by mfxss** [comment]
@hankcs 我看到dictionary里面有多个字典文件，NLPTokenizer在分词的时候是每个都用到了吗？还是只使用了CustomDictionary.txt

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
