### ISSUE TITLE
比较简单的问题：.txt.bin文件如何提取？

### ISSUE THREAD

**Issue by andyhxy** [hankcs/HanLP#69]
因为研究需要，想学习HanLP中的句法分析部分，按照介绍下载了data文件夹，发现里面的文件全部为txt.bin，而demo中提示
“严重: CRF分词模型加载 .../data/model/segment/CRFSegmentModel.txt 失败，耗时 12 ms”

**Comment by hankcs** [comment]
请贴一下你的配置文件。

**Comment by hankcs** [comment]
而且日志已经提示得很清楚了， .../data/model/segment/CRFSegmentModel.txt 这不可能是合法路径。
