### ISSUE TITLE
N-最短路分词 分词结果词性标注错误

### ISSUE THREAD

**Issue by icoder528** [hankcs/HanLP#691]
## 版本号

当前最新版本号是：
我使用的版本是：portable-1.5.2

## 我的问题
待分词的文本内容：
"今天，刘志军案的关键人物,山西女商人丁书苗在市二中院出庭受审。"
分词结果：
[今天/t, ，/m, 刘志军/nr, 案/ng, 的/ude1, 关键人物/nz, ,/m, 山西/ns, 女/b, 商人/nnt, 丁书苗/nr, 在/p, 市二中/n, 院/n, 出庭/vi, 受审/vi, 。/w]
问题：
中文逗号和英文逗号的词性标注错误，应该为w词性

## 复现问题
未做其它改动，直接使用项目README.md中的N-最短路分词的demo测试

### 触发代码

```
	public static void main(String[] args) {
		Segment nShortSegment = new NShortSegment().enableCustomDictionary(false).enablePlaceRecognize(true).enableOrganizationRecognize(true);
		System.out.println(nShortSegment.seg("今天，刘志军案的关键人物,山西女商人丁书苗在市二中院出庭受审。"));
	}
```

**Comment by icoder528** [comment]
类似问题，在使用同一文本进行CRF分词测试时，其中的英文逗号词性标注也不正确
```
    Segment segment = new CRFSegment().enablePartOfSpeechTagging(true);
    System.out.println(segment.seg("今天，刘志军案的关键人物,山西女商人丁书苗在市二中院出庭受审。"));
   //[今天/t, ，/w, 刘志军/nr, 案/ng, 的/ude1, 关键人物/nz, ,/nz, 山西/ns, 女/b, 商人/nnt, 丁书苗/nr, 在/p, 市二中/n, 院/n, 出庭/vi, 受审/vi, 。/w]
```

**Comment by TylunasLi** [comment]
经过测试，确认是TextUtility.isAllNum()有些问题，上次是我修改的，所以我来解决下。

**Comment by heyongcs** [comment]
解决了吗？

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
