### ISSUE TITLE
人名识别导致分词错误

### ISSUE THREAD

**Issue by iwaller** [hankcs/HanLP#693]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.5.2
我使用的版本是：1.3.4

## 我的问题

句子       ： 
```
商改后要买另外的保险保费怎么算
```

分词结果：
```
[商改后/nr, 要买/nz, 另外/c, 的/ude1, 保险/n, 保费/n, 怎么/ryv, 算/v]
```

其中 商改后 被识别为一个人名

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

```
    public void testIssue1234() throws Exception
    {
        System.out.println(StandardTokenizer.segment("商改后要买另外的保险保费怎么算"));
    }
```
### 期望输出

```
[商改/v，后/,  要买/nz, 另外/c, 的/ude1, 保险/n, 保费/n, 怎么/ryv, 算/v]
```

### 实际输出

```
[商改后/nr, 要买/nz, 另外/c, 的/ude1, 保险/n, 保费/n, 怎么/ryv, 算/v]
```

**Comment by guyuexue** [comment]
最好把debug模式开启看下是怎么识别出来的

**Comment by hankcs** [comment]
可以打开debug模式调整的。
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。
