### ISSUE TITLE
Word2Vec训练1G的语料出现java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by PKULiuHui** [hankcs/HanLP#694]
训练过程中没有出现问题，但训练到100%后会发生该错误，不晓得能不能优化一下，使得Word2Vec能支持更大的语料的训练（其实感觉1G应该不算很大）

**Comment by guyuexue** [comment]
Word2Vec 模型建议使用dl4j这个工具里面的Word2Vec工具训练，这个模型对内存管理比较好语料再大也不会OutOfMemory

**Comment by muzier** [comment]
@guyuexue @PKULiuHui 请教楼上两位：我这里有个相关问题，不知道能不能点拨一下：我想用word2vec进行文本分类，但要分的类别特别多，大概有1000+，但我不确定的是如果自己训练词向量的话，word2vec的维度是不是应该大于目标分类的维度啊？比如设定为1500，这样是不是才能保证覆盖分类的维度？我也看过《word2vec原理推导与代码分析》这篇文章，恕水平有限，还是不确定这个问题的答案，先谢过啦

**Comment by PKULiuHui** [comment]
@我原理看的不多，但从应用角度看的话维数和类别数没有直接联系，一般词向量都是50维，100维，200维这些，没有用那么大维数的 @muzier

**Comment by guyuexue** [comment]
@muzier 建议把类别本身在进行分类，通过大类别套小类别的方式做

**Comment by muzier** [comment]
多谢两位指教！！还想再请教一下 @guyuexue ，如果是大类别套小类别这种方式，那训练语料怎么处理呢？我原计划用一个大的完整语料直接训练词向量，可即使用大类别套小类别，那语料是不是都一样呢？还是单独人工区分出来一部分小类别的语料再进行训练？

**Comment by guyuexue** [comment]
词向量训练肯定是语料越多越好。分类训练应该是不用单独做的，把数据按大小分类进行分割，训练就行。这个方法还是要测试下效果，我并没有具体使用过。

**Comment by muzier** [comment]
好的，多谢！

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
