### ISSUE TITLE
分词错误

### ISSUE THREAD

**Issue by iwaller** [hankcs/HanLP#696]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.5.2
我使用的版本是：1.3.4

### 触发代码

```
    public void testIssue1234() throws Exception
    {
        System.out.println(StandardTokenizer.segment("修改稿件"));
    }
```
### 期望输出

```
[修改/v, 稿件/n]
```

### 实际输出

```
[修改稿/n, 件/q]
```

**Comment by yesseecity** [comment]
這個問題我也蠻好奇的

CRF 分出來的是 "修改/v",      "稿件/v"

CoreNatureDictionary.txt 裡面的詞頻如下
修改	v	1256	vn	322
修改稿	n	40

卻優先分出「修改稿」

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。
