### ISSUE TITLE
Python下测试NLP分词功能时出现异常“java.lang.ExceptionInInitializerError”

### ISSUE THREAD

**Issue by wlhgtc** [hankcs/HanLP#698]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.5.2
我使用的版本是：1.5.2

## 我的问题

在Python下测试NLP分词时出现异常“java.lang.ExceptionInInitializerError”，其他方式测试正常
## 复现问题

代码如下：
NLPTokenizer = JClass('com.hankcs.hanlp.tokenizer.NLPTokenizer')
print(NLPTokenizer.segment('中国科学院计算技术研究所的宗成庆教授正在教授自然语言处理课程'))

**Comment by wlhgtc** [comment]
在版本号1.3.2时正常，1.5.2时错误

**Comment by yesseecity** [comment]
這個你應該發在 hanlp-python那邊
1.5.2 release 的jar檔會有問題，
我用 1.5.2 重新 build 一個 jar檔 就可以正常用了

環境: macOS
IDE: IntelliJ IDEA CE
Java version:  1.8.0_151

**Comment by wlhgtc** [comment]
能否把您没问题的jar包发我一份呢，我测试一下，谢谢！

**Comment by hankcs** [comment]
不一定是java版本问题，我的环境是java version "1.8.0_20"，如果下一个版本还是有问题的话，可以联系我，我会支持 hanlp-python 的开发的。

**Comment by wlhgtc** [comment]
是这样的。目前我重新build了jar包，然后JAVA下测试没什么问题。但是在python下NLP分词ok，CRF分词好像有些问题，我没有用hanlp-python，只是简单调用，也有问题。

**Comment by wlhgtc** [comment]
Traceback (most recent call last):
  File "/Users/hgtc/work/code/NER/hanlp.py", line 7, in <module>
    print(segment.seg('中国科学院计算技术研究所的宗成庆教授正在教授自然语言处理课程'))
RuntimeError: Multiple overloads possible. at src/native/common/jp_method.cpp:109

Process finished with exit code 1

**Comment by hankcs** [comment]
CRF必须用配置文件指定model的路径。

**Comment by wlhgtc** [comment]
能详细说一下吗，我没找到相关文档。我当时打jar包的时候就没打配置文件，我的配置文件直接放在python项目内，要怎样添加路径呢？

**Comment by wlhgtc** [comment]
”CRFSegmentModelPath=data/model/segment/CRFSegmentModel.txt“

**Comment by wlhgtc** [comment]
这样吗？

**Comment by yesseecity** [comment]
你的 hanlp.properties 有類似下面的內容嗎？
https://gist.github.com/yesseecity/4f6f33be231110a89f2753671dfc8213

**Comment by wlhgtc** [comment]
有的，就是路径我改了！

**Comment by yesseecity** [comment]
發現 java.lang.ExceptionInInitializerError 
來自於這個commit 
c33c0b468a03ef43679db965e4bd71983b477932

在java 端 執行不會有問題，
但是Build 成 jar 後拿去給 jpype 轉給 python 用就會出現這個錯誤

**Comment by wlhgtc** [comment]
看一下QQ!!! @yesseecity

**Comment by yesseecity** [comment]
dictionary/common/CommonDictionary.java 
```
    protected boolean loadDat(ByteArray byteArray)
    {
        System.out.println("檢查點 laodDat A");
        V[] valueArray = loadValueArray(byteArray);
        System.out.println("檢查點 laodDat A1");
        if (valueArray == null)
        {
            return false;
        }
        System.out.println("檢查點 laodDat A2");
        return trie.load(byteArray.getBytes(), byteArray.getOffset(), valueArray);
    }
```

**Comment by hankcs** [comment]
@yesseecity 我在mac hanlp-portable-1.5.2.jar java1.8 python3 [jpype](https://github.com/originell/jpype/)下测试直接用jpype一切正常。

根据你的日志，你可能在打包的时候没有将一些类或资源打包进来。我将完整的工程上传在下面，欢迎运行检查。

[hanlp-python.zip](https://github.com/hankcs/HanLP/files/1543954/hanlp-python.zip)

**Comment by freecui** [comment]
jpype._jexception.RuntimeExceptionPyRaisable: java.lang.RuntimeException: Class com.hankcs.hanlp.tokenizer.NLPTokenizer not found
我也出现这种问题，但是其他分词的工具包没有问题，只有NLPTokenizer找不到

**Comment by hankcs** [comment]
我关闭这个issue，因为现在pyhanlp已经release了。
