### ISSUE TITLE
对于中文数量词改如何切分?

### ISSUE THREAD

**Issue by a198720** [hankcs/HanLP#7]
这是我的切分例子:
未分词:十九元套餐包括什么
标准分词:[十/m, 九/b, 元/q, 套餐/n, 包括/v, 什么/ry]
智能分词:[十/m, 九/b, 元/q, 套餐/n, 包括/v, 什么/ry]
索引分词:[十/m, 九/b, 元/q, 套餐/n, 包括/v, 什么/ry]

理想效果：
[十九元/mq, 套餐/n, 包括/v, 什么/ry]

**Comment by hankcs** [comment]
已经增加了数量词识别功能，请参考：https://github.com/hankcs/HanLP/blob/7f008891de48fdb78d88a5bee21fdfb28357456d/src/test/java/com/hankcs/demo/DemoNumberAndQuantifierRecognition.java

**Comment by hankcs** [comment]
另外，由于我修改了data/dictionary/CoreNatureDictionary.txt，所以需要删除缓存data/dictionary/CoreNatureDictionary.txt.bin才能生效。
