### ISSUE TITLE
繁转简中出现的“陷阱”被翻译为“猫腻”

### ISSUE THREAD

**Issue by lucifering** [hankcs/HanLP#700]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：hanlp-1.5.2
我使用的版本是：hanlp-1.5.2

## 我的问题

繁体转简体出现简体“陷阱”被替换为“猫腻”。

System.out.println(HanLP.convertToSimplifiedChinese("瓦爾．閃電陷阱"));
输出：瓦尔．闪电猫腻

## 复现问题

没有修改代码，词典和模型

### 触发代码

```
  System.out.println(HanLP.convertToSimplifiedChinese("瓦爾．閃電陷阱"));
```
### 期望输出

```
瓦尔．闪电陷阱
```

### 实际输出

```
瓦尔．闪电猫腻
```

**Comment by yesseecity** [comment]
改詞典就好了
我是用我做的python 接口測試，轉換正常

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。
