### ISSUE TITLE
较常见姓名识别出错：江,成与

### ISSUE THREAD

**Issue by bugesoft** [hankcs/HanLP#707]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：master
我使用的版本是：master

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

```
public class DemoChineseNameRecognition
{
.......
       String sentence = "山东省交通运输厅党组书记江成与大家进行交流",
       Segment segment = 
        HanLP.newSegment().enableNameRecognize(true).enableOrganizationRecognize(true);
        List<Term> termList = segment.seg(sentence);
        System.out.println(termList);
}
```
### 期望输出

```
[山东省/ns, 交通运输/nz, 厅/n, 党组书记/n, 江成/nr, 与/cc, 大家/rr, 进行/vn, 交流/vn]
```

### 实际输出

```
[山东省/ns, 交通运输/nz, 厅/n, 党组书记/n, 江/n, 成与/nr, 大家/rr, 进行/vn, 交流/vn]
```

**Comment by xchechi123x** [comment]
人名要添加到相应的词典才能识别,需要人工识别加入这个词典中data/dictionry/person/nrj.txt.建议把字典的结构和每个字典的用处分析一下

**Comment by hankcs** [comment]
党组书记似乎没有出现在语料库中。
问题应该解决了，如果还有问题，欢迎重开issue。

**Comment by bugesoft** [comment]
@hankcs 新版的hanlp，文本格式词库不提供了吗？如果核心词库不能修改，会有很多识别出错的问题没法改了

**Comment by hankcs** [comment]
版本库内是最新的。
