### ISSUE TITLE
CRF分词时，标点被分成nz

### ISSUE THREAD

**Issue by junphine** [hankcs/HanLP#710]
版本1.3.3
比如这句话：
如果一个算法有缺陷，或不适合于某个问题，执行这个算法将不会解决这个问题。
分成：

[如果/c, 一个/mq, 算法/n, 有缺陷/nz, ,/nz, 或/c, 不/d, 适合于/v, 某个/rz, 问题/n, ,/nz, 执行/v, 这个/rz, 算法/n, 将/d, 不会/v, 解决/v, 这个/rz, 问题/n, ./nz]

**Comment by hankcs** [comment]
由于未按issue模板规定填写，缺乏必要信息，无法处理只能关闭这个issue。欢迎参考[《如何提问》](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，严格按模板要求填写issue。造成不便望海涵，谢谢合作。

**Comment by TylunasLi** [comment]
请严格按模板要求填写issue。造成不便望海涵，谢谢合作。

CharacterBasedGenerativeModelSegment系列的词性标注方法和其他分词方法不一致，对于词典没有的词，WordBasedGenerativeModelSegment系列会根据CharTypes给词性，但CRF是直接给nz的。由于我工作上暂时用不到。这部分直到开发一个独立的POSTagger之前我都不准备改。
