### ISSUE TITLE
请教作者，依存句法分析，对复合句子解析不够合理，有什么方法改进？

### ISSUE THREAD

**Issue by junphine** [hankcs/HanLP#711]
比如对这个句子： 如果一个算法有缺陷，或不适合于某个问题，执行这个算法将不会解决这个问题。
整体解析感觉有问题，如下：

1	如果	如果	c	c	_	4	ADV	_	_
2	一个	一个	m	mq	_	3	ATT	_	_
3	算法	算法	n	n	_	4	SBV	_	_
4	有	有	v	vyou	_	0	HED	_	_
5	缺陷	缺陷	n	n	_	4	VOB	_	_
6	,	,	wp	w	_	4	WP	_	_
7	或	或	c	c	_	9	LAD	_	_
8	不	不	d	d	_	9	ADV	_	_
9	适合于	适合于	v	v	_	4	COO	_	_
10	某个	某个	r	rz	_	11	ATT	_	_
11	问题	问题	n	n	_	9	VOB	_	_
12	,	,	wp	w	_	4	WP	_	_
13	执行	执行	v	v	_	4	COO	_	_
14	这个	这个	r	rz	_	15	ATT	_	_
15	算法	算法	n	n	_	13	VOB	_	_
16	将	将	d	d	_	18	ADV	_	_
17	不会	不会	v	v	_	18	ADV	_	_
18	解决	解决	v	v	_	13	COO	_	_
19	这个	这个	r	rz	_	20	ATT	_	_
20	问题	问题	n	n	_	18	VOB	_	_
21	.	.	wp	w	_	18	WP	_	_

我期望的中心词是 “解决” 。 神经网络模型返回的是“有“，条件随机场模型返回的是“适合于”

**Comment by hankcs** [comment]
目前没有办法改进，因为

1. 我记得CTB语料中大部分是单句，复合句顶多只有2个子句。像这个句子，模型只注意到第一个子句。
2. 大部分来自新闻领域，不太适应IT领域。

下次发issue请严格按模板填写，勾选注意事项，谢谢合作。
