### ISSUE TITLE
custom文件夹下的词典问题？比如上海、全国地名等等。

### ISSUE THREAD

**Issue by luddongcai** [hankcs/HanLP#717]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.5.2
我使用的版本是：1.5.2

## 我的问题

您好！不好意思打扰了。我现在正在使用hanlp，想请问下custom文件夹下的词典都是怎么来的？比如上海、全国地名等等。谢谢~

**Comment by hankcs** [comment]
都是网络上搜集的，可参考：http://www.hankcs.com/nlp/corpus/tens-of-millions-of-giant-chinese-word-library-share.html

**Comment by luddongcai** [comment]
恩，谢谢！我看到hanlp词典里面有同义词词典，这个词典和哈工大同义词词林是一模一样，这个词典是不能商用的。想问下这些上海、全国地名等来源，是否也可以商用？

**Comment by hankcs** [comment]
时间有点长，具体来源无法确定，但肯定不是类似同义词词典那样有明确版权的数据。

**Comment by luddongcai** [comment]
好的，谢谢！我看hanlp下的词典含有词性和词频，但是连接给的千万条数据中没有词性和词频。词性和词频是怎么搜索出来的呢？

**Comment by hankcs** [comment]
https://github.com/hankcs/HanLP/wiki/%E8%AE%AD%E7%BB%83%E5%88%86%E8%AF%8D%E6%A8%A1%E5%9E%8B

**Comment by luddongcai** [comment]
恩，这个我知道。忘了说是custom下的词典了，这类词典不是来源于人民日报语料，是来源是网上词典的？网上词典是没有词频和词性的。

**Comment by hankcs** [comment]
我记起来了部分用户词典的来源：

1. 现代汉语补充词库.txt 是以网上的现代汉语词典为基础，对每个词条的释义中的“名词”“动词”做统计得到的
2. 机构名词典.txt 是收集了人民日报中的nt得到的
1. CustomDictionary.txt 好像来源于GitHub上一个有词性词频的repo，忘了具体名字了
3. 其他没有词性词频的来源就比较模糊了，基本都是流传的txt，出处不可考

**Comment by luddongcai** [comment]
恩，非常感谢！

**Comment by luddongcai** [comment]
我对比了一下，发现全国地名大全来源于链接上的“最详细的全国地名大全”。其中custom下的“全国地名大全”有90558条，“最详细的全国地名大全”有116200条；“上海地名”来源于链接上的“上海地名街道名”。其中，“上海地名”有20101条，“上海地名街道名”有21176条。

**Comment by hankcs** [comment]
当时没有做筛选，如果两者数据量不同，说明两者一个新一个旧（可能先下载旧版的放到Custom目录，然后共享新版的大词库出去）。

**Comment by yaleimeng** [comment]
目前自定义词典分散为多个txt文件，里面有些词条与核心词典有重复，或者自定义词典彼此之间有交集。是否做个清理会比较好，后续添加词条时只加入其中一个里面？ @hankcs

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
