### ISSUE TITLE
word2vector功能中，加载词向量模型128维度超出限制

### ISSUE THREAD

**Issue by ChenMing456** [hankcs/HanLP#719]
## 版本号
当前最新版本号是：portable-1.5.2
我使用的版本是：portable-1.5.2

## 我的问题
加载一个128维的词向量模型，抛出异常
java.lang.ArrayIndexOutOfBoundsException: 128

**Comment by muzier** [comment]
我在1.6.3版本中运行 中文wiki语料模型（300维）是可以正常运行的，不过我这里有个相关问题，不知道hankcs能不能点拨一下：我想用word2vec进行文本分类，但要分的类别特别多，大概有1000+，但我不确定的是如果自己训练词向量的话，word2vec的维度是不是应该大于目标分类的维度啊？比如设定为1500，这样是不是才能保证覆盖分类的维度？我也看过《word2vec原理推导与代码分析》这篇文章，恕水平有限，还是不确定这个问题的答案，先谢过啦~

**Comment by hankcs** [comment]
词向量维度与文本分类类别数无关。

**Comment by muzier** [comment]
哇，没想到大神有时间刷 issues，回复这么快，非常感谢！但是我的担心是，我们这个分类太多，个别分类还很接近：比如漆面厚度、漆面光泽，如果维度少的话，会不会分类效果不太好？还是说只要拿我们自己的语料进行训练，产生的词向量就足以进行区分，那这种情况下，维度一般设置多少为好呢？。。。
目前有同事是用正则匹配的方式去进行分类的，准确率还可以，但是召回率很低，所以想用word2vec试一下，但不知道这么多类别数，应该在哪些方面注意一下啊？我理解是不是只要语料足够充分（比如用全量的UGC内容）去训练词向量，就可以分出那么多类别来？

**Comment by hankcs** [comment]
这取决于你的分类器和样本数量。

**Comment by hapjin** [comment]
我用的版本是portable-1.5.3，也遇到了相似的错误：
触发代码：
```java
	WordVectorModel wordVectorModel = new WordVectorModel("F:\\HanLP\\vectors.txt");
	System.out.println(wordVectorModel.similarity("主播", "漂亮"));
```
抛出的异常：
```html
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 100
	at com.hankcs.hanlp.mining.word2vec.VectorsReader.readVectorFile(VectorsReader.java:50)
	at com.hankcs.hanlp.mining.word2vec.WordVectorModel.loadVectorMap(WordVectorModel.java:38)
	at com.hankcs.hanlp.mining.word2vec.WordVectorModel.<init>(WordVectorModel.java:32)
	at hanlp.Word2VecTest.main(Word2VecTest.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```
原因是训练出来的词向量里面有特殊的符号，比如：
![bad_word](https://user-images.githubusercontent.com/7702860/41329703-cea8f290-6f01-11e8-8385-bf2b606c8243.png)
导致VectorsReader.java的readVectorFile()方法代码：
```java
matrix[i][j] = Float.parseFloat(params[j + 1]);
```
出错了。后来发现在版本1.6.4已经把这个异常给修复了。1.6.4版本的相关的源码如下：
```java
                if (params.length != size + 1)
                {
                    logger.info("词向量有一行格式不规范（可能是单词含有空格）：" + line);
//                    System.out.println("词向量有一行格式不规范（可能是单词含有空格）：" + line);
                    --words;
                    --i;
                    continue;
                }
```

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
