### ISSUE TITLE
segment.enableAllNamedEntityRecognize(true)，有些影响其他分词的结果

### ISSUE THREAD

**Issue by jkl5515** [hankcs/HanLP#72]
“今天我们单位“，被当作一个词了。
Segment segment = HanLP.newSegment();
Segment segment = HanLP.newSegment();
segment = segment.enableMultithreading(true);
segment = segment.enableAllNamedEntityRecognize(true);
[今天我们单位/nt, 评选/vn, 出/vf, 了全单位/nt, 最/d, 漂亮/a, 的/ude1, 女同事/nz, ，/w, 但/c, 她/rr, 好像/v, 对/p, “/w, 局/n, 花/n, ”/w, 这个/rz, 头衔/n, 并不/d, 满意/v]

segment.enableAllNamedEntityRecognize(false)，结果好些。但是，又希望能识别实体。
[今天/t, 我们/rr, 单位/n, 评选/vn, 出/vf, 了/ule, 全/a, 单位/n, 最/d, 漂亮/a, 的/ude1, 女同事/nz, ，/w, 但/c, 她/rr, 好像/v, 对/p, “/w, 局/n, 花/n, ”/w, 这个/rz, 头衔/n, 并不/d, 满意/v]

**Comment by hankcs** [comment]
nt代表实体机构名，enableAllNamedEntityRecognize会开启机构名识别。但是机构名识别的训练语料没有经过人工校对，导致结果不理想。

通过后期调模型或黑名单可以去掉这种bad case:
https://github.com/hankcs/HanLP/commit/f4feed36ac90538f30dce41e0d278885fbebd082
你也可以单独enable你感兴趣的实体，而不enable机构名。

**Comment by jkl5515** [comment]
谢谢，这办法好。之前没想到。文档看过忘了
