### ISSUE TITLE
你好，关于支持自定义词库英文空格分隔符

### ISSUE THREAD

**Issue by LilyBlooper** [hankcs/HanLP#721]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.5.2
我使用的版本是：1.5.2 非Portable版本

## 我的问题

这个问题之前有同学提过，我在其他issue看到过。
就是一些，西方语言、日语等一些词是有空格作为分割符的。
如：
Mystery Ranch nz 1
Altec Lansing Technologies nz 1

## 复现问题
只要自定义词典包含这种词，就无法解析了

##解决办法
1. 动态insert ，但是感觉这样比较慢，希望统一管理
2. 等待新版本修复。 我看这个是今年3月份有计划，但是似乎现在还没有支持呢。
3. 本次的意图：想自行修改代码，自行用别的分隔符进行解析。

**Comment by hankcs** [comment]
https://github.com/hankcs/HanLP/issues/404
