### ISSUE TITLE
能关闭对于标点符号的词性标注吗？

### ISSUE THREAD

**Issue by kingsdu** [hankcs/HanLP#722]
对于标点符号的词性标注不准确。
比如 ： (记者李鑫轶 整理)
分词结果为：(/w	记者/nnt	李鑫/nr	轶/ng	 /n	整理/v	)/w	

空格标注为n，不理解。

能把标点的词性标注关闭了吗？

**Comment by hankcs** [comment]
最新版：[记者/nnt, 李鑫轶/nr,  /w, 整理/v]

由于未按issue模板规定填写，缺乏必要信息，无法处理只能关闭这个issue。欢迎参考[《如何提问》](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，严格按模板要求填写issue。造成不便望海涵，谢谢合作。下次发issue请严格按模板填写，勾选注意事项，谢谢合作。

**Comment by kingsdu** [comment]
好的，又学了一招
