### ISSUE TITLE
发现新词的方法，过滤的时候建议shiyonLinkedList

### ISSUE THREAD

**Issue by Jnoson** [hankcs/HanLP#724]
/**
     * 提取词语
     *
     * @param reader 大文本
     * @param size   需要提取词语的数量
     * @return 一个词语列表
     */
    public List<WordInfo> discover(BufferedReader reader, int size) throws IOException

在Line 83行，ArrayList替换为LinkedList，做移除时，会减少remove带来的list左移的复杂度，速度有很大提升

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。
下次发issue请严格按模板填写，勾选注意事项，谢谢合作。
