### ISSUE TITLE
如何在索引分词中只使用自定义词典分词

### ISSUE THREAD

**Issue by jimmy-walker** [hankcs/HanLP#727]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.5.2
我使用的版本是： 1.3.4

## 我的问题

您好，我希望在索引分词中只使用自定义的词典进行分词，关闭其他词典。请问有何方法吗？
因为索引分词中支持全切分，因此我希望以此来避免基于词典的分词方法只能匹配最长词的缺点。
期待你的回复谢谢。

## 复现问题
字典中为“夏洛特烦恼 n, 夏洛 nr”
List<Term> termList = IndexTokenizer.segment("夏洛特烦恼");

### 期望输出

```
夏洛特烦恼/n [0:5]
夏洛/nr [0:2]
```

### 实际输出

```
夏洛特烦恼/n [0:5]
夏洛/nr [0:2]
夏洛特/nrf [0:3]
烦恼/an [3:5]
```

**Comment by TylunasLi** [comment]
您的这种需求一般的文本处理比较少见,，知识图谱中可能会用到。
如果你只想输出自己词典里的词语，可以直接使用一个DoubkeArrayTire的数据结构装载词典，然后使用Seracher获取词语。具体可参考 WordBasedGenerativeModelSegment的GenerateWordNet方法

**Comment by jimmy-walker** [comment]
@TylunasLi 好的，我先阅读源码，尝试修改下。
此外，我想请问下，能否直接在自定义词典中定义新的词性呢，而不是动态添加新的词性？
比如我想定义“夏洛特烦恼 movie, 夏洛 role”

**Comment by jimmy-walker** [comment]
@TylunasLi 好的，感谢回复。我先阅读源码，尝试修改下。
此外，我想请问下，能否直接在自定义词典中定义新的词性呢，而不是动态添加新的词性？
比如我想定义“夏洛特烦恼 movie, 夏洛 role”。直接在自定义词典中定义会报错。

**Comment by jimmy-walker** [comment]
我尝试了下修改`WordBasedGenerativeModelSegment.java`中的源码，可以实现我想要的结果，供所需之人参考。
```java
        // 核心词典查询
//        DoubleArrayTrie<CoreDictionary.Attribute>.Searcher searcher = CoreDictionary.trie.getSearcher(charArray, 0);
//        while (searcher.next())
//        {
//            wordNetStorage.add(searcher.begin + 1, new Vertex(new String(charArray, searcher.begin, searcher.length), searcher.value, searcher.index));
//        }
        // 用户词典查询
        if (config.useCustomDictionary)
        {
//            searcher = CustomDictionary.dat.getSearcher(charArray, 0);
            DoubleArrayTrie<CoreDictionary.Attribute>.Searcher searcher = CustomDictionary.dat.getSearcher(charArray, 0);
            while (searcher.next())
            {
                wordNetStorage.add(searcher.begin + 1, new Vertex(new String(charArray, searcher.begin, searcher.length), searcher.value));
            }
        }
```

**Comment by TylunasLi** [comment]
如果你完全不用核心词典，只用数据结构。建议你用 DoubleArrayTrieSegment的方式，包装自己的Trie树，并参考WordBasedGenerativeModelSegment的GenerateWordNet方法包装一下输出所有词语。如果你用不到系统词性，你也可以在Nature类里向后添加自己的词性。

**Comment by jimmy-walker** [comment]
感谢大家的建议。我已经搞定了。
我本来想重新写一个类继承WordBasedGenerativeModelSegment。但后来根据大家的建议，直接在WordBasedGenerativeModelSegment中定义新的static方法然后实现了功能。
