### ISSUE TITLE
如何才能分出带空格的英文/数字词

### ISSUE THREAD

**Issue by laoyang945** [hankcs/HanLP#73]
比如 iPad Pro
比如 PM 2.5
谢谢！

**Comment by hankcs** [comment]
目前词典是用空格分隔的，所以无法通过词典文件引入。
但是com.hankcs.hanlp.dictionary.CustomDictionary#insert(java.lang.String)一系列的方法可以接受这种词语。
未来会逐渐用\t作为词典的默认分隔符。
