### ISSUE TITLE
调用依存语法分析接口CRFDependencyParser.compute(sentence)；出现返回结果死循环情况

### ISSUE THREAD

**Issue by iwangkang** [hankcs/HanLP#730]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.5.2
我使用的版本是：hanlp-portable-1.5.2.jar

## 我的问题
调用依存语法分析接口CRFDependencyParser.compute(sentence)；出现返回结果死循环情况
返回结果中id为5的CoNLLWord的head为6，id为6的CoNLLWord的head为5。

## 复现问题
没有修改源码直接调用CRFDependencyParser.compute(sentence)接口；

### 触发代码

```
    public void testCompute() throws Exception
    {
        String sentence = "男子从厦门游泳到金门";
        CoNLLSentence cs = CRFDependencyParser.compute(sentence);
        System.out.println(cs.word[4].HEAD.ID);
        System.out.println(cs.word[5].HEAD.ID);
    }
```
### 期望输出

```
0
5
```

### 实际输出

```
6
5
```

**Comment by hankcs** [comment]
感谢反馈，这是个老问题了：https://github.com/hankcs/HanLP/issues/650

1. 线性链CRF做句法分析的理论基础非常薄弱，一阶CRF这个标注模型根本无法阻止环的产生。
1. 这份实现也没有复现论文的结果，参考 http://www.hankcs.com/nlp/parsing/crf-sequence-annotation-chinese-dependency-parser-implementation-based-on-java.html 。
1. 在理论和工程上更合理的parser是`com.hankcs.hanlp.dependency.nnparser.NeuralNetworkDependencyParser`

综上，我决定在下个版本废弃`com.hankcs.hanlp.dependency.CRFDependencyParser`这个模块。

**Comment by iwangkang** [comment]
非常感谢给予回复。
