### ISSUE TITLE
关于商品型号（字母，分隔符，数据的组合）的分词效果探讨

### ISSUE THREAD

**Issue by LilyBlooper** [hankcs/HanLP#731]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.5.2
我使用的版本是：1.5.2 离线

## 我的问题

采用标准分词，进行一些包含商品描述的语句进行切分。商品型号通常是任意的字母，分隔符，数据的组合。不是人名、地名、机构等。
进行分词时，可能最终结果粒度过细。而希望是一个整体。
由于型号在不断增加，比较笨的做法是时候添加词库，但那样工作量比较大。较为繁琐。

## 复现问题

Sample: SAMSUNG 三星 **RS542NCAEWW/SC** 545L 风冷变频对开门冰箱，还行还行，可以看看;
分词结果： [SAMSUNG][ ][三星][ ][RS][542][NCAEWW][/][SC][ ][545][L][ ][风冷][变频][对开门冰箱][\][n][还行][还行][，][可以][看看][;]

### 期望输出

[SAMSUNG][ ][三星][ ][RS542NCAEWW/]SC[ ][545][L][ ][风冷][变频][对开门冰箱][\][n][还行][还行][，][可以][看看][;]

即。希望是一个整体 “**RS542NCAEWW/]SC**”

## 其他信息

这种例子有很多，如 
WD 西部数据 **WD20EZRZ** 台式机硬盘 蓝盘 2TB

希望 “WD20EZRZ ” 整体切分

NORITZ 能率 **JSQ25-E4/GQ-13E4AFEX** 13升燃气热水器防冻型

希望 ‘’JSQ25-E4“ 整体切分

**Comment by AnyListen** [comment]
我也遇到过这种问题，例如对化学表达式的识别等。
暂时的解决方法遍历分词结果，将连续的数字、字母还有符号要求的特殊符号进行合并作为一个新词在插入到分词结果中；
同时对于包含特殊符号的，以特殊符号分割，把子串也加入到分词结果中；
还对单个数字或者字母的字串进行了移除

**Comment by LilyBlooper** [comment]
@AnyListen

**Comment by LilyBlooper** [comment]
@AnyListen 
对于第一种方式： 如何合并？效率如何？ 感觉所有的二次操作都是比较耗时的

**Comment by hankcs** [comment]
可参考 @TylunasLi 对千位数字的识别：https://github.com/hankcs/HanLP/pull/728/commits/43b3f3896c4f157967010956ec7c5b0791294b3a

考虑到数字和字母的无限种成词方式（身份证、车牌号、ISBN……），也许我应该将 atomSegment 修改为非static的，让大家灵活写子类去override这个方法。

**Comment by TylunasLi** [comment]
我在我司内部的代码中增加了PreProcessor和PostProcessor处理词法类型的问题。
型号是字母、数字、连字符，属于PostProcessor的操作

PostProcessor 大致长成这样: 
```
    public abstract class PostProcessor
    {
    	/**
	 * 在文本中替换，并且在
	 * @param vertexList
	 * @param fullWordNet
	 * @param startVertex	开始点
	 * @param endVertex		结束点，包含
	 * @param compiledWord	等效词语
	 * @param newWordId		新节点的ID
	 * @param newAttribute	新节点的属性
	 */
        public static void mergeAndReplace(Vertex[] vertexList, WordNet fullWordNet, 
                int startVertex, int endVertex, String compiledWord, int newWordId, Attribute newAttribute)
        {
        //...
        }
        public abstract void processVertexes(Vertex[] vertexList, WordNet fullWordNet);
    }
```
用状态机可以实现。效率也就是O(n)

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
