### ISSUE TITLE
常见姓名识别出错：赵红

### ISSUE THREAD

**Issue by bugesoft** [hankcs/HanLP#734]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [ x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：master
我使用的版本是：master

## 我的问题

原句：侦查员核实了信用卡持有人赵红的情况后，

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

```
HanLP.Config.enableDebug(true);
Segment segment = HanLP.newSegment().enableNameRecognize(true).enableOrganizationRecognize(true).enablePlaceRecognize(true).enableOffset(true)
            .enablePartOfSpeechTagging(true).enableCustomDictionary(true);
```
### 期望输出

```
侦查员/nnt, 核实/v, 了/ule, 信用卡/n, 持有人/nz, 赵红/nr, 的/ude1, 情况/n, 后/f, ，/w
```

### 实际输出

```
侦查员/nnt, 核实/v, 了/ule, 信用卡/n, 持有人/nz, 赵/nz, 红/a, 的/ude1, 情况/n, 后/f, ，/w
```

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。
