### ISSUE TITLE
Lucene5.3调用HanLP关键词HightLight定位错误

### ISSUE THREAD

**Issue by liucong315** [hankcs/HanLP#74]
在Lucene5.3中调用HanLP对指定目录下的文件进行检索（文件解析用的Tika），关键字高亮位置定位不对，调用IKAnalyzer5x定位就没问题，请问是什么情况？多谢。
代码如下：
package com.std.test;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.StringReader;
import java.nio.file.Paths;

import org.apache.lucene.analysis.Analyzer;
import org.apache.lucene.analysis.TokenStream;
import org.apache.lucene.document.Document;
import org.apache.lucene.document.TextField;
import org.apache.lucene.document.Field.Store;
import org.apache.lucene.index.DirectoryReader;
import org.apache.lucene.index.IndexWriter;
import org.apache.lucene.index.IndexWriterConfig;
import org.apache.lucene.queryparser.classic.QueryParser;
import org.apache.lucene.search.IndexSearcher;
import org.apache.lucene.search.Query;
import org.apache.lucene.search.ScoreDoc;
import org.apache.lucene.search.TopDocs;
import org.apache.lucene.search.highlight.Highlighter;
import org.apache.lucene.search.highlight.QueryScorer;
import org.apache.lucene.search.highlight.SimpleFragmenter;
import org.apache.lucene.search.highlight.SimpleHTMLFormatter;
import org.apache.lucene.store.Directory;
import org.apache.lucene.store.FSDirectory;
import org.apache.tika.exception.TikaException;
import org.apache.tika.metadata.Metadata;
import org.apache.tika.parser.AutoDetectParser;
import org.apache.tika.parser.ParseContext;
import org.apache.tika.parser.Parser;
import org.apache.tika.sax.BodyContentHandler;
import org.xml.sax.SAXException;

import com.hankcs.lucene5.HanLPAnalyzer;
import com.std.core.ik5x.IKAnalyzer5x;

public class TikaFileSearch {
	/**
	 * 多格式文件内容解析
	 * 
	 * @param file
	 * @return
	 * @throws IOException
	 * @throws SAXException
	 * @throws TikaException
	 */
	public static String parseFile(File file) throws IOException, SAXException,
			TikaException {
		FileInputStream fs = new FileInputStream(file);
		Parser parse = new AutoDetectParser();// 自动获取一个合适的解析器类型
		// 如果文件很大，那么这个值可以适当调大
		BodyContentHandler handler = new BodyContentHandler(10000);
		Metadata metadata = new Metadata();
		ParseContext parseContext = new ParseContext();
		parse.parse(fs, handler, metadata, parseContext);
		System.out.println("目标文件名称：" + file.getAbsolutePath());
		System.out.println("目标文件内容：" + handler.toString());

		return handler.toString();
	}

	/**
	 * 为目标文档创建索引
	 * 
	 * @throws Exception
	 */
	public static void indexDoc() throws Exception {
		File[] files = new File("/Projects/IS/filesPath/").listFiles();
		for (File file : files) {
			String content = parseFile(file);

			Analyzer analyzer = new HanLPAnalyzer();
			// 构造字段
			TextField contentField = new TextField("content", content,
					Store.YES);
			TextField nameField = new TextField("name", file.getName(),
					Store.YES);
			TextField pathField = new TextField("path", file.getAbsolutePath(),
					Store.YES);

			// 添加字段
			Document doc = new Document();
			doc.add(contentField);
			doc.add(nameField);
			doc.add(pathField);
			IndexWriterConfig iwConfig = new IndexWriterConfig(analyzer);
			iwConfig.setOpenMode(IndexWriterConfig.OpenMode.CREATE_OR_APPEND);
			try {
				Directory fsDirectory = FSDirectory.open(Paths.get(
						"/Projects/IS/filesIndexPath/", new String[0]));
				IndexWriter indexWriter = new IndexWriter(fsDirectory, iwConfig);
				indexWriter.addDocument(doc);

				indexWriter.close();
			} catch (Exception e) {
				e.printStackTrace();
			}
		}
	}

	/**
	 * 搜索文件
	 * 
	 * @param field
	 * @param keyword
	 */
	public static void search(String field, String keyword) {
		Analyzer analyzer = new HanLPAnalyzer();
		try {
			Directory fsDirectory = FSDirectory.open(Paths.get(
					"/Projects/IS/filesIndexPath/", new String[0]));
			DirectoryReader ireader = DirectoryReader.open(fsDirectory);

			IndexSearcher isearcher = new IndexSearcher(ireader);

			QueryParser qp = new QueryParser(field, analyzer); // 使用QueryParser查询分析器构造Query对象
			qp.setDefaultOperator(QueryParser.AND_OPERATOR);
			Query query = qp.parse(keyword);
			TopDocs topDocs = isearcher.search(query, 5); // 搜索相似度最高的5条记录
			System.out.println("命中:" + topDocs.totalHits);

			SimpleHTMLFormatter simpleHTMLFormatter = new SimpleHTMLFormatter(
					"<span style='color:green'>", "</span>");
			Highlighter highlighter = new Highlighter(simpleHTMLFormatter,
					new QueryScorer(query));
			// 高亮htmlFormatter对象
			// 设置高亮附近的字数
			highlighter.setTextFragmenter(new SimpleFragmenter(200));

			ScoreDoc[] scoreDocs = topDocs.scoreDocs;
			for (int i = 0; i < topDocs.totalHits; i++) {
				Document targetDoc = isearcher.doc(scoreDocs[i].doc);
				String value = targetDoc.get("content");
				TokenStream tokenStream = analyzer.tokenStream(value,
						new StringReader(value));
				String freg = highlighter.getBestFragment(tokenStream, value);

				System.out.println(freg);

			}

		} catch (Exception e) {

		}
	}

	public static void main(String[] args) throws Exception {

		indexDoc();
		search("content", "民族");
	}

}

运行截图如下：
![079da201-023c-4232-a856-80fb063a7476](https://cloud.githubusercontent.com/assets/14268210/10640239/78728792-7846-11e5-8b93-443ca970dda1.png)

调用IK的运行结果如下：
![56e95ae2-12c8-4b04-a58c-10d00ed28921](https://cloud.githubusercontent.com/assets/14268210/10640257/8818074e-7846-11e5-85f9-208098472519.png)

**Comment by hankcs** [comment]
感谢指正，这是由于文档中有连续的\n，而Lucene是按行读取的，造成单词偏移量不准确。
请使用修正后的版本：https://github.com/hankcs/hanlp-solr-plugin/releases/tag/v1.0.2

**Comment by hankcs** [comment]
这个问题应该解决了，如果还有问题，欢迎再开issue。
