### ISSUE TITLE
关于resize(65536 * 32)的数字大小问题

### ISSUE THREAD

**Issue by jimmy-walker** [hankcs/HanLP#740]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.5.2
我使用的版本是：1.3.4

## 我的问题

我在看hanlp的源码时，看到在`src/main/java/com/hankcs/hanlp/collection/trie/DoubleArrayTrie.java`中`resize(65536 * 32); `。 这段代码的目的是为了生成双数组而设置数组的初始大小。我想请问为什么要设置这么大呢。65536是根据char的最大值设定，而32是为了什么原因选中此数值呢？

**Comment by hankcs** [comment]
经验值吧，继承自https://github.com/komiya-atsushi/darts-java/blob/master/src/main/java/darts/DoubleArrayTrie.java#L265，留大一点后面重新分配的可能性就小一些。其实从bin加载的话多余的空间会被去掉，不怎么浪费。

**Comment by jimmy-walker** [comment]
@TylunasLi 。不好意思，我刚接触java，我想请问您是在哪里看到占用了16MB内存。

**Comment by TylunasLi** [comment]
算一下可以i知道 65536*32*4*2 (base+check)
另外dump Java虚拟机的heap来分析也能看到。

**Comment by jimmy-walker** [comment]
好的。谢谢你。原来已经实现了方法去查看：getTotalSize()
