### ISSUE TITLE
Viterbi分词器模型异常

### ISSUE THREAD

**Issue by kunyin2** [hankcs/HanLP#742]
1、待分词文本：陶某、陶某某路经该处时
    public static void main(String args[]) {
        HanLP.Config.DEBUG = true;
        Segment segment = new ViterbiSegment();
        List<Term> termList = segment.seg("陶某、陶某某路经该处时");
        System.out.println(termList);
    }
经查看日志，陶某人名已经识别出，可识别结果依然为：
[陶/ag, 某/rz, 、/w, 陶/ag, 某/rz, 某/rz, 路经/v, 该/rz, 处/n, 时/qt]

程序运行日志为：
粗分结果[陶/ag, 某/rz, 、/w, 陶/ag, 某/rz, 某/rz, 路经/v, 该/rz, 处/n, 时/qt]
人名角色观察：[  K 1 A 1 ][陶 B 771 D 30 C 15 E 9 ][某 G 2055 C 1082 D 420 L 34 K 7 ][、 M 19857 L 5234 K 4094 ][陶 B 771 D 30 C 15 E 9 ][某 G 2055 C 1082 D 420 L 34 K 7 ][某 G 2055 C 1082 D 420 L 34 K 7 ][路经 A 20843310 ][该 K 18 L 13 ][处 L 52 K 10 D 9 ][时 L 228 C 137 D 134 K 106 B 88 ][  K 1 A 1 ]
人名角色标注：[ /K ,陶/B ,某/G ,、/M ,陶/B ,某/C ,某/L ,路经/A ,该/K ,处/D ,时/L , /K]
识别出人名：陶某 BG
识别出人名：陶某 BC

和预期结果不符合。

2、运用公式可能有误
经检查代码片段中，计算转移概率公式（见MathTools.calculateWeight方法）：
 double value = -Math.log(dSmoothingPara * frequency / (MAX_FREQUENCY) + (1 - dSmoothingPara) * ((1 - dTemp) * nTwoWordsFreq / frequency + dTemp));

该公式经推敲，多乘了一个frequency ，由于是底层算法，不知理解是否有误。

我将公式修改为：
 double value = -Math.log(dSmoothingPara * frequency / (MAX_FREQUENCY) + (1 - dSmoothingPara) * ((1 - dTemp) * nTwoWordsFreq / frequency + dTemp));

重新运行代码得到如下结果：
[陶某/nr, 、/w, 陶某某/nr, 路经/v, 该/rz, 处/n, 时/qt]
满足预期结果

3、由于是底层算法代码，不知是否修改有误，请指导！

**Comment by TylunasLi** [comment]
清按模板规范填写Issue。
另外我没有看出你修改前后的差别。可能是你自己原来的代码被你改错了？

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
