### ISSUE TITLE
如何使用CRF解码用CRF++训练生成的模型

### ISSUE THREAD

**Issue by freedomqp** [hankcs/HanLP#745]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.5.3
我使用的版本是：1.5.2

## 我的问题
使用CRF++解码用CRF++训练生成的模型进行实体识别时，如果开启多线程运行，则会报错，猜测是其c++底层有错误。
HanLP使用了CRF解码，但是只用于分词。
请问如果要用CRF解码用CRF++训练生成的模型进行实体识别，应该参考哪些部分，或者可以复用CRF解码用于分词的哪些思路吗？

**Comment by TylunasLi** [comment]
com.hankcs.hanlp.model.crf.CRFModel对CRF的文本模型进行了较为完整的解析。
只需要将待标记数据转换为com.hankcs.hanlp.model.crf.Table对象，将序列和特征放入二维数组即可预测。

**Comment by freedomqp** [comment]
你好，感谢你的回答，现在程序跑通了，但是预测结果不对。模型文件是用的CRF++训练生成的文本模型，加载是没问题的。问题应该是出现在tag方法的预测上。使用的测试数据就是训练数据中的一条。请问是序列和特征放入的方式不对吗，求正确方式，非常感谢

其中一条训练数据如下：
深圳市	ns	R_S
普天	nt	U_B
通	v	U_E
数码	n	I_B
实业	nis	I_E
有限公司	nis	O_S

代码如下：
CRFModel model = loadTxt("model.txt");
Table table = new Table();
 table.v = new String[][]{
            {"深圳市", "ns"},
            {"普天", "nt"},
            {"通", "v"},
            {"数码", "n"},
            {"实业", "nis"},
            {"有限公司", "nis"},
        };
model.tag(table);
System.out.println(table);

运行结果如下：
深圳市	U_B	
普天	OUT	
通	I_M	
数码	OUT	
实业	I_B	
有限公司	OUT

**Comment by hankcs** [comment]
旧的tag方法有问题，试试上面新的修改。

**Comment by freedomqp** [comment]
你好，我使用了你最新改进的编号为ce02d03的tag方法，得到的结果还是不对。

结果如下：
深圳市	I_E	
普天	I_S	
通	I_S	
数码	I_M	
实业	I_B	
有限公司	OUT

我发现其结果只出现了前几个标签，查看tag方法发现有2行代码由tagSize改为了限定长度为4，这是因为分词中只会出现BMES这4个标签的原因吗？而我的结果便签有17种，所以我试着将2行代码从4改为了tagSize，得到了比之前稍微好一点点的结果，不过还是与标准结果差的比较远。

2行代码分别是215行的  System.arraycopy(net[0], 0, maxScoreAt[0], 0, 4);
和224行的  for (int pre = 0; pre < 4; ++pre)

改为tagSize之后结果：
深圳市	U_B	
普天	OUT	
通	I_M	
数码	OUT	
实业	I_B	
有限公司	OUT

**Comment by hankcs** [comment]
感谢指正，有两个地方忘了改。

**Comment by freedomqp** [comment]
可是用于实体识别的准确率还是非常低，你们用于分词是对的吗？是否用于分词和用于实体识别是不一样的呢，分词所用的特征只有词这一列，而实体识别所用的特征有词和词性两列，是否应该建立三维数组呢？

**Comment by hankcs** [comment]
table.v = new String[text.length()][3];

**Comment by freedomqp** [comment]
没看明白，能稍微解释一下吗

**Comment by hankcs** [comment]
你的训练数据含tag在内有几列，table就必须有几列。

**Comment by zhaodp** [comment]
请问CRF预测和CRF++预测的算法是一致的吗？另外HanLP对CRF++训练的模型有特殊要求吗？比如格式啥的

**Comment by ljg-lixufeng** [comment]
> 没看明白，能稍微解释一下吗

你好，这个问题解决了吗，我现在也碰到，单列特征预测一致，多列特征预测不一致的情况

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
