### ISSUE TITLE
使用CRFSegment进行分词时，出现java.lang.NullPointerException

### ISSUE THREAD

**Issue by andyxzq** [hankcs/HanLP#747]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [ ] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.5.3
我使用的版本是：1.5.3

## 我的问题
1. 下载data-for-1.5.3.zip，解压后上传data目录到hdfs上；
2. 继承IIOAdapter来读取hdfs上的文件；
3. hanlp.properties放在src/main/resources目录下，其中指定了CRFSegmentModelPath和各个词典的路径，以及IOAdapter；
4. 程序运行时，crf模型加载成功(不然会报找不到模型文件error)，但map算子中调用segment()进行分词时，日志中报空指针异常。

### 触发代码

```
    val segment = new CRFSegment()
          .enableNameRecognize(true)
          .enableTranslatedNameRecognize(true)
          .enableJapaneseNameRecognize(true)
          .enablePlaceRecognize(true)
          .enableOrganizationRecognize(true)
          .enablePartOfSpeechTagging(true)
          .enableCustomDictionary(true)
   segment.seg(text)
```

## 其他信息
Caused by: java.lang.NullPointerException
    at com.hankcs.hanlp.algorithm.Viterbi.compute(Viterbi.java:121)
    at com.hankcs.hanlp.seg.CharacterBasedGenerativeModelSegment.segSentence(CharacterBasedGenerativeModelSegment.java:81)
	at com.hankcs.hanlp.seg.Segment.seg(Segment.java:507)

**Comment by hankcs** [comment]
1. 重新上传一次data，或者试试旧版data。
1. 建议看看日志里最开始有没有CoreNatureDictionary.tr.txt加载失败的警告。这个警告会通过logger给出，而不是exception。
2. 现在修改为报exception通知。

**Comment by andyxzq** [comment]
@hankcs ,谢谢。确实是CoreNatureDictionary.tr.txt没有加载。目前已修改正确。想请问下作者，有没有对这些分词方法进行过效果评测？

**Comment by hankcs** [comment]
https://github.com/hankcs/HanLP/wiki/FAQ#%E4%B8%BA%E4%BB%80%E4%B9%88%E4%BF%AE%E6%94%B9%E4%BA%86%E8%AF%8D%E5%85%B8%E8%BF%98%E6%98%AF%E6%B2%A1%E6%9C%89%E6%95%88%E6%9E%9C
