### ISSUE TITLE
HMM-NGram分词模型等效词替换后如何保留的原词？

### ISSUE THREAD

**Issue by jiangcoder** [hankcs/HanLP#748]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

master
当前最新版本号是：
1.5.3
我使用的版本是：
1.5.3

## 我的问题
二元接续词典地名人名等被替换成了“等效词”，这样在训练1998年语料的时候像“中国”，“北京”等地名都成了等效词。如下面：
`未##串	x	130296

未##人	nr	607718	nrf	113445

未##团	nt	112253	ntc	25517	nto	18894	ntu	5426	nth	2556	ntcb	1846	nts	677	ntch	568	ntcf	118

未##地	ns	595380	nsf	124178

未##它	xx	1000

未##数	mq	753456	m	733982

未##时	t	757118`
我训练后的结果也同上面一样，被替换后已有的词“中国”就没有了呀，但是你的二元接续词典里还有原词，比如：
`中国	ns	39573`

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

```
   /**
 * 等效词编译器
 * @author hankcs
 */
public class PosTagCompiler
{
    /**
     * 编译，比如将词性为数词的转为##数##
     * @param tag 标签
     * @param name 原词
     * @return 编译后的等效词
     */
    public static String compile(String tag, String name)
    {
        if (tag.startsWith("m")) return Predefine.TAG_NUMBER;
        else if (tag.startsWith("nr")) return Predefine.TAG_PEOPLE;
        else if (tag.startsWith("ns")) return Predefine.TAG_PLACE;
        else if (tag.startsWith("nt")) return Predefine.TAG_GROUP;
        else if (tag.startsWith("t")) return Predefine.TAG_TIME;
        else if (tag.equals("x")) return Predefine.TAG_CLUSTER;
        else if (tag.equals("nx")) return Predefine.TAG_PROPER;
        else if (tag.equals("xx")) return Predefine.TAG_OTHER;
        return name;
    }
```
### 期望输出

```
期望输出
```
期望既有等效词，也有地名等原词的条件转移词典，我看hankcs的CoreNatureDictionary.txt也是有的
### 实际输出

```
实际输出
```
CoreNatureDictionary.txt未输出：
`中国	ns	39573`
**想问下hankcs的训练的词典为什么既有等效词，也有地名等原来的词，是一个综合的结果呢?
我训练数据少了哪一步呢，跟你的结果不一样**
## 其他信息
我指的词典主要指的是：CoreNatureDictionary.txt，CoreNatureDictionary.ngram.txt，CoreNatureDictionary.tr.txt

**Comment by hankcs** [comment]
细节我忘记了，似乎是手工注释掉com.hankcs.hanlp.corpus.util.Precompiler#compile(com.hankcs.hanlp.corpus.document.sentence.word.IWord)训练出来的。

**Comment by hankcs** [comment]
然后可以通过com.hankcs.hanlp.corpus.dictionary.DictionaryMaker#combine(java.lang.String...)合并多个词典。ngram不要用注释后的，因为查询的时候只会查等效词。

**Comment by jiangcoder** [comment]
多谢hankcs回复，我又重写了标注的相关方法，加了一个参数控制，让等效词和非等效词都进入了ngram词典，跟您的一样了。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
