### ISSUE TITLE
［Reopen］HightLighter定位不准确的问题

### ISSUE THREAD

**Issue by liucong315** [hankcs/HanLP#75]
lucene插件已经更新到新版本，运行HighLighterTest.java没有问题。
但是，修改HighLighterTest.java的检索内容之后，还是会出现定位问题，麻烦帮我看一下，多谢。
下面是修改示例代码之后的内容，只是在内容中多加了几个 "\n"   ：
  IndexWriterConfig iwConfig = new IndexWriterConfig(analyzer);
            iwConfig.setOpenMode(IndexWriterConfig.OpenMode.CREATE_OR_APPEND);
            iwriter = new IndexWriter(directory, iwConfig);
            {
                // 加入一个文档
                Document doc = new Document();
                doc.add(new TextField(fieldName, "我白天是一名语言\n\n\n\n学习者，晚上是一名初级码农。空的时候喜欢看算法和应用数学书，也喜欢悬疑推理小说，ACG方面喜欢型月、轨迹。喜欢有\n\n\n\n\n思想深度的事物，讨厌急躁、拜金与安逸的人。目前在魔都某女校学习，这是我的个人博客。闻道有先后，术业有专攻，请多多关照。你喜欢写代码吗？", Field.Store.YES));
                doc.add(new TextField("title", "关于hankcs", Field.Store.YES));
                iwriter.addDocument(doc);
            }
            {
                // 再加入一个
                Document doc = new Document();
                doc.add(new TextField(fieldName, "\n\n   \n\n\n\n\n\n\n\n\n程序员喜欢黑夜", Field.Store.YES));
                doc.add(new TextField("title", "关于程序员", Field.Store.YES));
                iwriter.addDocument(doc);
            }
            iwriter.close();

运行结果如下：

test
Query = text:喜欢
命中：2
关于程序员 , 0.2972674

   

程序员<font color='red'>喜欢</font>黑夜
关于hankcs , 0.124633156
我白天是一名语言

学习者，晚上是一名<font color='red'>初级</font>码农。空的时候喜欢看算<font color='red'>法和</font>应用数学书，也喜欢悬疑推<font color='red'>理小</font>说，ACG方<font color='red'>面喜</font>欢型月、轨迹。喜欢<font color='red'>有
</font>

思想深度的事物，讨厌急躁、拜金与安逸的人。目前在魔都某女校学习，这是我的个人博客。闻道有先后，术业有专攻，请多多关照。你喜欢写代码吗？

**Comment by hankcs** [comment]
好的，我晚上看看。

**Comment by liucong315** [comment]
运行结果贴的文本没有显示出HighLighter的效果，附一个截图
![e8048e06-ddb0-437f-ac03-ee7cc0904273](https://cloud.githubusercontent.com/assets/14268210/10659053/49945d22-78cf-11e5-8f53-02a09cc62d00.png)

**Comment by hankcs** [comment]
的确有个地方没考虑好，现在修复了：https://github.com/hankcs/hanlp-solr-plugin/releases/tag/v1.0.3

**Comment by hankcs** [comment]
这个问题应该解决了，如果还有问题，欢迎再开issue。

**Comment by liucong315** [comment]
问题已经解决，多谢。
