### ISSUE TITLE
“来张北京的车票“ 分词为 “张北” “京“

### ISSUE THREAD

**Issue by whynogo** [hankcs/HanLP#750]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [X ] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

portable版
当前最新版本号是：v1.5.3
我使用的版本是：v1.5.3

## 我的问题

你好，这半年一直在用你开发的分词器做实验，感觉很好用。但是今天发现 “来张北京的车票”，无论用包中的几种分词器都分不出 “ 北京”  ，基本都分成  “”张北“  “京”  。能否赐教怎么解决这个问题？我已经向自定义辞典添加了“北京“  “来张“”，但是无效。谢谢！

## 复现问题
没有修改代码，直接调用这几个分词器

### 期望输出

```
期望输出
```
[来张,北京,的,车票]
(我忽略了词性)
### 实际输出

[来张北京/nr, 的/ude1, 车票/n]
[来张北京/nr, 的/ude1, 车票/n]
[来张北京/nr, 的/ude1, 车票/n]
[来/null, 张北/null, 京/null, 的/null, 车票/null]

```

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。
