### ISSUE TITLE
 HanLP对短文本（30字以内）分词效率低，如何解决？

### ISSUE THREAD

**Issue by UCASREN** [hankcs/HanLP#751]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：v1.5.3
我使用的版本是：v1.5.3

## 我的问题

1. 使用HanLP对短文本（30字以内），分词效率在300ms-500ms之间。属于正常情况吗？
2. 如果我想提高分词效率在50ms左右（30字左右的短文本），但又不想用极速分词算法，有什么其他办法？是需要配置吗？
## 复现问题

我使用了Portable版本和600多M的data数据都得到了同样的结果，分词效率都在300ms-500ms之间。
### 步骤

如下代码所示：

### 触发代码

```
    public static void main(String[] args)
    {
        long current = System.currentTimeMillis();
        List<Term> termList = HanLP.segment("帮我找找最近3天在三峡大坝拍的无人机照片");
        long end = System.currentTimeMillis();
        System.out.println(end-current);
    }

   或者这样：
   public static void main(String[] args)
    {
        // TODO Auto-generated method stub
        Segment segment = HanLP.newSegment().enableAllNamedEntityRecognize(true).enableMultithreading(true).enableNumberQuantifierRecognize(true).enablePartOfSpeechTagging(true);
        long current = System.currentTimeMillis();
        List<Term> termList = segment.seg("帮我找找最近3天在三峡大坝拍的无人机照片");
        long end = System.currentTimeMillis();
        System.out.println(end-current);
    }

  
```
### 期望输出

```
希望耗时在50ms以内。
```

### 实际输出

```
300ms-500ms
```

**Comment by hankcs** [comment]
测试方法错误。参考：https://github.com/hankcs/HanLP/issues/677

**Comment by UCASREN** [comment]
感谢您迅速的回复！
