### ISSUE TITLE
词网与词图的区别

### ISSUE THREAD

**Issue by yunsuyunsu** [hankcs/HanLP#757]
请教一下词网和词图这两种数据结构分别适用于怎样的算法。
在ViterbiSegment中使用了词网结构，每一行都是前缀词链。我觉得使用像DijkstraSegment中一样的词图，然后依次对节点选择最优解应该也可以实现Viterbi最短路切分。
那么，另外又定义的词网结构的意义是什么，它在效率上是更优吗？

**Comment by hapjin** [comment]
@yunsuyunsu 参考下这篇文章：[词图的生成](http://www.hankcs.com/nlp/segment/the-word-graph-is-generated.html)
比如待分词的字符串"商品和服务"，首先通过双数组树最大匹配查找，得出一个个的节点(链表)：
'商'--->‘商品’、'品'、'和'--->'和服'、'服'--->'服务'、'务'，然后查找核心词典中的词频得出节点间权重，构建出词网，最后使用动态规划的维特比算法来求解词图的最短路径。
我觉得词网这种数据结构的优势是，[词图的生成](http://www.hankcs.com/nlp/segment/the-word-graph-is-generated.html)中提到的“快速offset法”，快速定位下一个节点，并且weigth保留的是开始结点到当前结点的最短路径。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
