### ISSUE TITLE
请教添加用户字典的问题

### ISSUE THREAD

**Issue by sothic** [hankcs/HanLP#76]
首次使用NLP，请求帮忙。
这里有一个用户字典的问题，发现识别“张克智与潍坊地铁建设工程公司”里的机构实体出现以下结果：
[张克智/nr, 与潍坊地铁建设工程公司/nt]
想利用用户词典将“潍坊地铁建设工程公司”加到用户字典里，补充了/data/dictionary/custom/机构名词典.txt,添加了如下一行：
潍坊地铁建设工程公司 nt 1
在代码里设置了（enableCustomDictionary(true)), 发现仍然没有识别成功。
请教下这个做法对不对？谢谢！

**Comment by sothic** [comment]
我在代码里也动态添加了 这一句：

不过依然没有成功，debug信息如下：貌似标注了 与/C，和之后的公司的标注D后 形成了 CD，不知道为什么。

///// Debug 信息
首次编译运行时，HanLP会自动构建词典缓存，请稍候……
粗分词网：
0:[ ]
1:[张]
2:[克]
3:[智]
4:[与]
5:[潍坊]
6:[坊]
7:[地, 地铁]
8:[铁]
9:[建, 建设]
10:[设]
11:[工, 工程, 工程公司]
12:[程]
13:[公, 公司]
14:[司]
15:[ ]

Oct 27, 2015 6:31:42 PM com.hankcs.hanlp.dictionary.CoreBiGramTableDictionary <clinit>
INFO: 开始加载二元词典/Users/lee/workspace/HanLP/data/dictionary/CoreNatureDictionary.ngram.txt.table
Oct 27, 2015 6:31:42 PM com.hankcs.hanlp.dictionary.CoreBiGramTableDictionary <clinit>
INFO: /Users/lee/workspace/HanLP/data/dictionary/CoreNatureDictionary.ngram.txt.table加载成功，耗时51ms
粗分结果[张/q, 克/q, 智/ng, 与/cc, 潍坊地铁建设工程公司/nt]
Oct 27, 2015 6:31:42 PM com.hankcs.hanlp.dictionary.common.CommonDictionary load
INFO: 加载值/Users/lee/workspace/HanLP/data/dictionary/person/nr.txt.value.dat成功，耗时11ms
Oct 27, 2015 6:31:42 PM com.hankcs.hanlp.dictionary.common.CommonDictionary load
INFO: 加载键/Users/lee/workspace/HanLP/data/dictionary/person/nr.txt.trie.dat成功，耗时7ms
Oct 27, 2015 6:31:42 PM com.hankcs.hanlp.dictionary.nr.PersonDictionary <clinit>
INFO: /Users/lee/workspace/HanLP/data/dictionary/person/nr.txt加载成功，耗时35ms
人名角色观察：[  A 42634591 ][张 B 25461 C 33 L 33 D 16 K 4 E 1 ][克 C 1375 D 83 E 51 K 6 L 3 ][智 C 745 D 428 E 142 B 20 K 1 ][与 K 2534 L 1599 M 1217 C 14 ][潍坊地铁建设工程公司 A 42634591 ][  A 42634591 ]
人名角色标注：[ /A ,张/B ,克/C ,智/D ,与/L ,潍坊地铁建设工程公司/A , /A]
识别出人名：张克 BC
识别出人名：张克智 BCD
Oct 27, 2015 6:31:42 PM com.hankcs.hanlp.dictionary.nr.JapanesePersonDictionary <clinit>
INFO: 日本人名词典/Users/lee/workspace/HanLP/data/dictionary/pinyin/pinyin.txt加载成功，耗时5ms
Oct 27, 2015 6:31:42 PM com.hankcs.hanlp.dictionary.common.CommonDictionary load
INFO: 加载值/Users/lee/workspace/HanLP/data/dictionary/place/ns.txt.value.dat成功，耗时6ms
Oct 27, 2015 6:31:42 PM com.hankcs.hanlp.dictionary.common.CommonDictionary load
INFO: 加载键/Users/lee/workspace/HanLP/data/dictionary/place/ns.txt.trie.dat成功，耗时3ms
Oct 27, 2015 6:31:42 PM com.hankcs.hanlp.dictionary.ns.PlaceDictionary <clinit>
INFO: /Users/lee/workspace/HanLP/data/dictionary/place/ns.txt加载成功，耗时10ms
地名角色观察：[  S 1139590 A 23975 ][张 C 235 D 11 B 8 A 2 ][克 D 28 C 6 B 2 E 1 ][智 B 2 ][与 A 2426 B 593 X 490 ][潍坊地铁建设工程公司 A 348 B 113 X 2 ][  B 1322 ]
地名角色标注：[ /A ,张/C ,克/D ,智/B ,与/A ,潍坊地铁建设工程公司/A , /A]
Oct 27, 2015 6:31:42 PM com.hankcs.hanlp.dictionary.common.CommonDictionary load
INFO: 加载值/Users/lee/workspace/HanLP/data/dictionary/organization/nt.txt.value.dat成功，耗时6ms
Oct 27, 2015 6:31:42 PM com.hankcs.hanlp.dictionary.common.CommonDictionary load
INFO: 加载键/Users/lee/workspace/HanLP/data/dictionary/organization/nt.txt.trie.dat成功，耗时3ms
Oct 27, 2015 6:31:42 PM com.hankcs.hanlp.dictionary.nt.OrganizationDictionary <clinit>
INFO: /Users/lee/workspace/HanLP/data/dictionary/organization/nt.txt加载成功，耗时9ms
机构名角色观察：[  S 1169907 ][张克智 F 6781 B 769 A 266 X 6 ][与 A 1143 C 370 B 318 X 212 ][潍坊地铁建设工程公司 K 3547 D 1278 ][  B 8423 ]
机构名角色标注：[ /S ,张克智/A ,与/C ,潍坊地铁建设工程公司/D , /S]
识别出机构名：与潍坊地铁建设工程公司 CD

**Comment by hankcs** [comment]
请更新一下nt.txt就可以正确识别了：
[张克智/nr, 与/cc, 潍坊地铁建设工程公司/nt]
see：https://github.com/hankcs/HanLP/commit/4fab08b041e6018f4d0f38a4f490c4ad92fad33a

**Comment by sothic** [comment]
多谢hankcs，请问下用户字典失效的原因是因为命名实体识别字典（nt.txt）的优先级比较高吗？

**Comment by hankcs** [comment]
不是，基于统计模型的分词器不保证用户词一定被切分出来。

**Comment by sothic** [comment]
多谢！！

刚刚我有碰到另外一个问题，这句话
“江西省监狱管理局与中国太平洋财产保险股份有限公司南昌中心支公司保险合同纠纷案”
分词结果是
N-最短分词：[江西省监狱管理局/nt, 与/cc, 中国太平洋财产保险股份有限公司南昌中心支公司保险/nt, 合同/n, 纠纷案/nz, 一审/b, 判决书/n]

我将nt里面的如下这句：

保险 C 57 D 8 A 1
修改为
保险 C 57 A 1

就能正确识别，这样改会有影响吗？

//修改后结果
N-最短分词：[江西省监狱管理局/nt, 与/cc, 中国太平洋财产保险股份有限公司南昌中心支公司/nt, 保险/n, 合同/n, 纠纷案/nz, 一审/b, 判决书/n]

**Comment by hankcs** [comment]
改得好，D表示机构名的特征词如国务院侨务[办公室]，“保险”可能是由于训练文件中有“人寿保险/nt”这样的词语，所以得到了8个D标签，既然引发了问题，还是删了比较好。

**Comment by sothic** [comment]
多谢指导，请问下可以加下hankcs你的联系方式吗？好像没找到私信。我的邮箱:sothicor.l@gmail.com

**Comment by hankcs** [comment]
me艾特hankcs.com
