### ISSUE TITLE
请问有没有办法做到语义上的相似度匹配

### ISSUE THREAD

**Issue by yaoyasong** [hankcs/HanLP#760]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [*] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号
当前最新版本号是：1.5.3
我使用的版本是：1.5.3

## 我的问题
在做短文本相似度匹配时，我希望优先匹配语义相近的。如：
**不喜欢** 匹配到 **讨厌**，而不是匹配到 **喜欢**。
请问有没有办法实现？

### 触发代码

```
    DocVectorModel docVectorModel = new DocVectorModel(new WordVectorModel(modelFileName));

		String[] documents = new String[]{
		        "农民在江苏种水稻",
		        "山东苹果丰收",
		        "我很喜欢篮球",
		        "我很讨厌篮球",
		        "奥运会女排夺冠",
		        "世界锦标赛胜出"
		};

		for (int i = 0; i < documents.length; i++)
		{
		    docVectorModel.addDocument(i, documents[i]);
		}
	    System.out.println(docVectorModel.nearest("我不喜欢篮球"));
```
### 期望输出

不喜欢能先匹配到讨厌
```
[3=0.99999976, 2=0.87721485
```

### 实际输出
不喜欢先匹配到了 喜欢

```
[2=0.99999976, 3=0.87721485
```

**Comment by hankcs** [comment]
bag of words模型无法做到这一点。

**Comment by hankcs** [comment]
你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真填写，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
