### ISSUE TITLE
可否提供一个命令行可执行的jar包？

### ISSUE THREAD

**Issue by fishfree** [hankcs/HanLP#761]
类似于[斯坦福NLP](https://stanfordnlp.github.io/CoreNLP/cmdline.html)的:-)

**Comment by hankcs** [comment]
Check this one: https://github.com/hankcs/pyhanlp

![hanlp-parse](https://user-images.githubusercontent.com/5326890/37678453-1cf35e70-2c4c-11e8-87ac-748b5738a41b.png)

**Comment by fishfree** [comment]
Bravo! You are so diligent!

**Comment by hankcs** [comment]
你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真填写，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
