### ISSUE TITLE
词典不完整，无法验证测试源码中的test

### ISSUE THREAD

**Issue by zdz131148** [hankcs/HanLP#764]
## 在运行源码中的test类时发现有些词典是在data/test/目录下的，但是我下载下来的data包中不包含有这部分词典，请问在哪里可以获取到这些词典？

**Comment by hankcs** [comment]
你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真填写，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
