### ISSUE TITLE
python中使用hanlp，金华的词性，识别出来为nr，而不是ns

### ISSUE THREAD

**Issue by LoveFlyXa** [hankcs/HanLP#766]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [√ ] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：hanlp-portable-1.5.4
我使用的版本是：hanlp-portable-1.5.4

## 我的问题

我在python中使用hanlp来识别一段文字中出现的地区，而且大部分地区可以正常识别出来，但是金华识别出来的词性总是nr

### 触发代码

```
hanlp = JClass('com.hankcs.hanlp.HanLP')
segment = hanlp.newSegment().enablePlaceRecognize(True)
term_list = segment.seg(u'我在浙江金华出生')

for name in term_list:
    print(name.toString())
```
### 期望输出

```
我/r
在/p
浙江/ns
金华/ns
出生/v
```

### 实际输出

识别的金华词性为人名（nr）而不是地名（ns）
```
我/r
在/p
浙江/ns
金华/nr  
出生/v
```

## 其他信息
不知道是否是因为 HanLP/data/dictionary/CoreNatureDictionary.mini.txt
文件中，标识了金华的词性为nr引起的
![cosmos](https://user-images.githubusercontent.com/11661935/37083415-5ac2ccbe-21e7-11e8-8020-e6f022640af8.png)

**Comment by hankcs** [comment]
感谢反馈，目前的HMM词性标注的确效果有限。如果对精度要求较高，可以使用[感知机词性标注器](https://github.com/hankcs/HanLP/wiki/%E7%BB%93%E6%9E%84%E5%8C%96%E6%84%9F%E7%9F%A5%E6%9C%BA%E6%A0%87%E6%B3%A8%E6%A1%86%E6%9E%B6)中的在线学习功能：

```
        PerceptronLexicalAnalyzer analyzer = new PerceptronLexicalAnalyzer(Config.CWS_MODEL_FILE, Config.POS_MODEL_FILE);
        analyzer.learn("我/r 在/p 浙江/ns 金华/ns 出生/v");
        System.out.println(analyzer.analyze("我在浙江金华出生"));
        System.out.println(analyzer.analyze("我的名字叫金华"));
```

结果是完全正确的：

```
我/r 在/p 浙江/ns 金华/ns 出生/v
我/r 的/v 名字/n 叫/v 金华/nr
```

感知机代码已经提交，将会打包到1.6版本中正式发布。

对于Python用户来讲，还有个好消息。我会在近日发布一套用深度学习模型做分词、词性标注和句法分析的原型工具包，欢迎关注。

**Comment by hankcs** [comment]
你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真填写，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
