### ISSUE TITLE
文本分类：贝叶斯统计中的特征选择可否可视化？

### ISSUE THREAD

**Issue by 0311sr** [hankcs/HanLP#769]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [ ] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：hanlp-1.6.0
我使用的版本是：hanlp-1.5.3

## 我的问题

贝叶斯统计中使用卡方检测选择特征，控制台会输出类似“使用卡方检测选择特征中...耗时 80 ms,选中特征数:5857 / 15110 = 38.76%”的语句，但是我不能够看到它到底选择了哪些特征词汇。
举个例子，假如我利用情感分析对一些评论进行了分类，有正面和负面，但单单这样分类对我没有实际作用，我想知道这些正面、负面评论有哪些特点，这些负面评论又是在不满些什么东西，比如评论“早餐都凉了，我吃了肚子痛。”我就知道这个评论在不满早餐，进而对早餐做改进。

## 复现问题

没有修改代码，但我只能看到情感分析和贝叶斯统计的结果，不知道我可以看到其中的过程吗？
### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

package com.hankcs.hanlp.classification.classifiers.NaiveBayesClassifier
....
....
protected BaseFeatureData selectFeatures(IDataSet dataSet)
    {
        ChiSquareFeatureExtractor chiSquareFeatureExtractor = new ChiSquareFeatureExtractor();

        logger.start("使用卡方检测选择特征中...");
        //FeatureStats对象包含文档中所有特征及其统计信息
        BaseFeatureData featureData = chiSquareFeatureExtractor.extractBasicFeatureData(dataSet); //执行统计

        //我们传入这些统计信息到特征选择算法中，得到特征与其分值
        Map<Integer, Double> selectedFeatures = chiSquareFeatureExtractor.chi_square(featureData);

        //从统计数据中删掉无用的特征并重建特征映射表
        int[][] featureCategoryJointCount = new int[selectedFeatures.size()][];
        featureData.wordIdTrie = new BinTrie<Integer>();
        String[] wordIdArray = dataSet.getLexicon().getWordIdArray();
        int p = -1;
        for (Integer feature : selectedFeatures.keySet())
        {
            featureCategoryJointCount[++p] = featureData.featureCategoryJointCount[feature];
            featureData.wordIdTrie.put(wordIdArray[feature], p);
        }
        logger.finish(",选中特征数:%d / %d = %.2f%%\n", featureCategoryJointCount.length,
                      featureData.featureCategoryJointCount.length,
                      featureCategoryJointCount.length / (double)featureData.featureCategoryJointCount.length * 100.);
        featureData.featureCategoryJointCount = featureCategoryJointCount;

        return featureData;
    }
....
....

### 期望输出

希望看到正面评论之所以是正面评论的依据，比如特征与其分值？
### 实际输出

正在从 data/test/ChnSentiCorp情感分析酒店评论 中加载分类语料...
正面 : 2000 个文档
负面 : 2000 个文档
开始训练...
正在构造训练数据集...[正面]...50.00%...[负面]...100.00%...耗时 6448 ms 加载完毕
原始数据集大小:4000
使用卡方检测选择特征中...耗时 80 ms,选中特征数:5857 / 15110 = 38.76%
贝叶斯统计结束
训练耗时：6689 ms

**Comment by 0311sr** [comment]
FeatureStats对象包含文档中所有特征及其统计信息，这些信息该1怎么看呢？

**Comment by wenjiahua** [comment]
我想问一下你在哪里找到贝叶斯分类的模型，并把它放到data/test/classification.ser这个路径下的。

**Comment by 0311sr** [comment]
参考test.java.com.hankcs.demo.DemoTextClassification @wenjiahua

**Comment by wenjiahua** [comment]
想问一下为什么我测试DemoTextClassification 的输出结构中没有分类的输出，类别都是空？是哪里配置错误吗？
输出信息如下：《C罗压梅西内马尔蝉联金球奖 2017=C罗年》 属于分类 【null】
《英国造航母耗时8年仍未服役 被中国速度远远甩在身后》 属于分类 【null】
《研究生考录模式亟待进一步专业化》 属于分类 【null】
《如果真想用食物解压,建议可以食用燕麦》 属于分类 【null】
《通用及其部分竞争对手目前正在考虑解决库存问题》 属于分类 【null】

**Comment by 0311sr** [comment]
不是很清楚你的问题，我按原程序运行是没有问题的，《搜狗文本分类语料库迷你版》是要自己去下载的。 @wenjiahua

**Comment by hankcs** [comment]
chisquareScore
https://nlp.stanford.edu/IR-book/html/htmledition/feature-selectionchi2-feature-selection-1.html

**Comment by hankcs** [comment]
你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真填写，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
