### ISSUE TITLE
分词错误："为什么我扔出的瓶子没有人回复？"

### ISSUE THREAD

**Issue by iwaller** [hankcs/HanLP#770]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.6.0
我使用的版本是：1.3.4

## 我的问题
对句子“为什么我扔出的瓶子没有人回复？”分词错误

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

```
    public void testIssue1234() throws Exception
    {
        List<Term> terms = HanLP.segment("为什么我扔出的瓶子没有人回复？");
        System.out.println(terms );
    }
```
### 期望输出

```
[为什么, 我, 扔出, 的, 瓶子, 没有,人, 回复, ？]
```

### 实际输出

```
[为什么, 我, 扔出, 的, 瓶子, 没,有人, 回复, ？]
```

**Comment by hankcs** [comment]
在data/dictionary/CoreNatureDictionary.ngram.txt中加入 `没有@人 1000` 试试

**Comment by iwaller** [comment]
好的，添加后问题解决了。
