### ISSUE TITLE
依存分析设置使用感知机分词之后，标点符号的依存关系错误

### ISSUE THREAD

**Issue by zongwu233** [hankcs/HanLP#776]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.6.1
我使用的版本是：maven  上的 portable 1.6.1

## 我的问题

       依存句法分析可以设置分词器，在设置为感知机分词器之后，标点符号的依存关系不再是之前的 **标点符号** 关系，而是 **动宾关系** 之类。

### 触发代码

```java
        String test = "什么是自然语言处理?";
        IDependencyParser parser = new NeuralNetworkDependencyParser();
        PerceptronLexicalAnalyzer segmenter = new PerceptronLexicalAnalyzer(HanLP.Config.PerceptronCWSModelPath,
                HanLP.Config.PerceptronPOSModelPath, HanLP.Config.PerceptronNERModelPath);
        parser.setSegment(segmenter);
        CoNLLSentence sentence = parser.parse(test);
        System.out.println(sentence);
        // 可以方便地遍历它
        for (CoNLLWord word : sentence) {
            System.out.printf("%s --(%s)--> %s\n", word.LEMMA, word.DEPREL, word.HEAD.LEMMA);
        }
        CoNLLWord[] wordArray = sentence.getWordArray();
        System.out.println("-------0000----");
```

### 期望输出

```
1	什么	什么	r	ry	_	2	主谓关系	_	_
2	是	是	v	vshi	_	0	核心关系	_	_
3	自然语言处理	自然语言处理	nz	nz	_	2	动宾关系	_	_
4	?	?	wp	w	_	2	标点符号	_	_

什么 --(主谓关系)--> 是
是 --(核心关系)--> ##核心##
自然语言处理 --(动宾关系)--> 是
? --(标点符号)--> 是
-------0000----

```

### 实际输出

```
1	什么	什么	r	r	_	2	主谓关系	_	_
2	是	是	v	v	_	0	核心关系	_	_
3	自然语言	自然语言	n	n	_	4	主谓关系	_	_
4	处理	处理	v	vn	_	2	动宾关系	_	_
5	?	?	n	n	_	4	动宾关系	_	_

什么 --(主谓关系)--> 是
是 --(核心关系)--> ##核心##
自然语言 --(主谓关系)--> 处理
处理 --(动宾关系)--> 是
? --(动宾关系)--> 处理
-------0000----
```
## 其他信息

依存句法分析的默认分词器对标点符号的依存分析是正确的。

**Comment by hankcs** [comment]
感谢反馈，原因是目前感知机词性标注无法处理半角字符。目前没有做预处理，而人民日报中的标点全部都是全角。有打算做预处理，需要花点时间。

**Comment by zongwu233** [comment]
@hankcs  谢谢回复，那我用的时候先对句子中的标点处理一下。

**Comment by hankcs** [comment]
简繁全半角补丁已提交：https://github.com/hankcs/HanLP/commit/4ab7eae138252c68fde4f5751e3b09961e833bf0
需要删除data/dictionary/other/CharTable.txt.bin并重新训练模型。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
