### ISSUE TITLE
命名实体识别后分词不理想

### ISSUE THREAD

**Issue by unxia** [hankcs/HanLP#777]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：
我使用的版本是： master主分支

我新建了实体识别楼盘名，ViterbiSegment 分词 “地址是星海城三期”，
识别出楼名 
[星海城/nbd] 和 [星海城三期/nbd]，但分词结果却是
[地址/n, 是/vshi, 星海/n, 城/n, 三期/nbdp]

请问如何使结果为
[地址/n, 是/vshi, 星海城三期/nbd]

**Comment by hankcs** [comment]
我不知道你做了什么，但你的需求可以用[感知机命名实体识别](https://github.com/hankcs/HanLP/wiki/%E7%BB%93%E6%9E%84%E5%8C%96%E6%84%9F%E7%9F%A5%E6%9C%BA%E6%A0%87%E6%B3%A8%E6%A1%86%E6%9E%B6)来解决，需要标注一些语料。

**Comment by wallacexia** [comment]
@hankcs 非常感谢。
我尝试使用上述提到的感知机识别，将自己标注的语料稍作修改，添加ner楼名(nbd)训练后，效果不错。
但也存在部分误判，比如
`analyzer.learn("黄桦路/ns 与/cc 测试路/ns 交汇口/n [巴黎/ns 春天/t]/nbd");
System.out.println(analyzer.analyze("黄桦路与测试路交汇口巴黎春天"));
`

上面的在线学习标注实际在离线训练语料中也存在，输出都是
`黄桦路/ns 与/cc 测试路/ns 交汇口/n 巴黎春天/nr`

不知道是不是语料较少的原因？

还有一个疑问，ner是基于cws分词和pos标注后的 **词和标注** 两者进行命名实体识别的吗？
从代码中看好像是这样的，但我又不是很确定，这点可能影响如何标注语料使达到最好的识别效果。

**Comment by hankcs** [comment]
1. 请确认是否[重载了标注集](https://github.com/hankcs/HanLP/wiki/%E7%BB%93%E6%9E%84%E5%8C%96%E6%84%9F%E7%9F%A5%E6%9C%BA%E6%A0%87%E6%B3%A8%E6%A1%86%E6%9E%B6#%E8%87%AA%E5%AE%9A%E4%B9%89ner%E7%B1%BB%E5%9E%8B)？需要tagSet.nerLabels.add("nbd");
1. 语料规模的确很重要，ner的类型数量应该均衡。如果nbd的数量只有nr的1%，那么模型几乎不会预测nbd，因为只要盲目预测nr就能猜对99%的case。
1. ner是同时利用了词和词性作为特征，如果你觉得特征不够，可以重载`com.hankcs.hanlp.model.perceptron.instance.NERInstance#extractFeature`（下一版会改成protected）。这个方法注释掉了一些特征，为了运行效率。当然，特征越多，需要的语料也越多。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
