### ISSUE TITLE
人名中有数词（如张三）在方式一portable与方式二自定义数据包的情况下拆分结果不同

### ISSUE THREAD

**Issue by l06066hb** [hankcs/HanLP#778]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [ ×] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：
我使用的版本是：1.6.2

## 我的问题
对于句子“管理员张三”的拆分中，使用方式一portable整合版与方式二自定义数据包这两种方式获得的拆分结果不同
方式一：管理员/nr, 张三/nr
方式二：管理员/nnt, 张/q, 三/m

### 步骤

1. 分别使用两种方式拆分“管理员张三”

### 触发代码

```
    public void testIssue1234() throws Exception
    {
       String content1 = "管理员张三";
        System.out.println(NLPTokenizer.segment(content1));
    }
```
### 期望输出

```
期望输出：管理员，张三
```

### 实际输出

```
实际输出：管理员，张，三
```

## 其他信息

结果截图
方式一：
![qq 20180402162824](https://user-images.githubusercontent.com/18030444/38189476-f09255ba-3692-11e8-998a-21ccb11115ca.png)
方式二：
![qq 20180402162834](https://user-images.githubusercontent.com/18030444/38189477-f0d07fe8-3692-11e8-81e7-653578c53bc9.png)

**Comment by hankcs** [comment]
两者挂载的数据不一样，加个bigram就能解决。
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。
