### ISSUE TITLE
对部分人名中有数词（如张三丰），在拆分时会出现不如预期情况。

### ISSUE THREAD

**Issue by l06066hb** [hankcs/HanLP#779]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.6.2
我使用的版本是：1.6.2

## 我的问题
存在某些人名中有数词出现的人名时，会出现拆分不如预期的问题，如“张三丰，黄三元，刘五郎”会出现问题，而“王三强，闻一多，李四光”等经测试没有问题，不知道是不是因为有问题的属于常用词或商标名等原因导致。

### 触发代码

```
    public static void main(String[] args) {
        String content1 = "张三丰，刘五郎，黄三元，张一楠，王三强，丁一楠，李四光，闻一多，赵一楠，李四";
        System.out.println(NLPTokenizer.segment(content1));
    }
```
### 期望输出

```
期望输出：张三丰，刘五郎，黄三元，张一楠，王三强，丁一楠，李四光，闻一多，赵一楠，李四
```

### 实际输出

```
实际输出：张/q, 三丰/nz, ，/w, 刘/nr, 五郎/nz, ，/w, 黄/a, 三元/nz, ，/w, 张一楠/nr, ，/w, 王三强/nr, ，/w, 丁一楠/nr, ，/w, 李四光/nr, ，/w, 闻一多/nr, ，/w, 赵一楠/nr, ，/w, 李四/nr]

```

## 其他信息

测试结果
![jg](https://user-images.githubusercontent.com/18030444/38225667-8e0e25c2-3728-11e8-98cd-4d2070edddd1.png)

**Comment by hankcs** [comment]
感谢反馈，基于角色标注的命名实体识别其实很容易受词典影响，当“三丰”没有出现在nr.txt中时，模型几乎无法推断它可能属于人名。

如果对准确率要求较高的话，推荐使用最新的[感知机算法](https://github.com/hankcs/HanLP/wiki/%E7%BB%93%E6%9E%84%E5%8C%96%E6%84%9F%E7%9F%A5%E6%9C%BA%E6%A0%87%E6%B3%A8%E6%A1%86%E6%9E%B6)：

```
        analyzer = new PerceptronLexicalAnalyzer();
        System.out.println(analyzer.seg("张三丰，刘五郎，黄三元，张一楠，王三强，丁一楠，李四光，闻一多，赵一楠，李四"));
```

人名一个都没错：

```
[张三丰/nr, ，/w, 刘五郎/nr, ，/w, 黄三元/nr, ，/w, 张一楠/nr, ，/w, 王三强/nr, ，/w, 丁一楠/nr, ，/w, 李四光/nr, ，/w, 闻一多/nr, ，/w, 赵一楠/nr, ，/w, 李四/nr]
```

**Comment by l06066hb** [comment]
好的，感谢解答

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
