### ISSUE TITLE
com.hankcs.hanlp.summary.KeywordExtractor类的shouldInclude方法，不识别一个字的词

### ISSUE THREAD

**Issue by freebie5** [hankcs/HanLP#780]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：hanlp-1.6.2.jar
我使用的版本是：hanlp-1.5.4.jar

## 我的问题

com.hankcs.hanlp.summary.KeywordExtractor类的shouldInclude方法，为什么判断一个字的词不在计算范围内，像  霾  这个字本身就是一个词，是不是太武断了

### 触发代码

public boolean shouldInclude(Term term)
    {
        // 除掉停用词
        if (term.nature == null) return false;
        String nature = term.nature.toString();
        char firstChar = nature.charAt(0);
        switch (firstChar)
        {
            case 'm':
            case 'b':
            case 'c':
            case 'e':
            case 'o':
            case 'p':
            case 'q':
            case 'u':
            case 'y':
            case 'z':
            case 'r':
            case 'w':
            {
                return false;
            }
            default:
            {
                if (_**term.word.trim().length() > 1**_ && !CoreStopWordDictionary.contains(term.word))
                {
                    return true;
                }
            }
            break;
        }

        return false;
    }

**Comment by hankcs** [comment]
因为没有用的单字比有意义的单字的要多，所有就这么做了。现在改成了用`com.hankcs.hanlp.dictionary.stopword.CoreStopWordDictionary#FILTER`，可以写自己的filter。

**Comment by freebie5** [comment]
请问什么时候发版本

**Comment by hankcs** [comment]
这个倒没有固定周期，建议[自己编译](https://github.com/hankcs/HanLP/wiki/%E7%BC%96%E8%AF%91%E8%BF%90%E8%A1%8C)，很简单的。

**Comment by freebie5** [comment]
好的，但是我用maven编译的时候会报错，现在还在看什么原因，方便看一原因吗？
![image](https://user-images.githubusercontent.com/23119744/38474913-7c9b7418-3bd6-11e8-9e2d-376d8360a23c.png)

**Comment by hankcs** [comment]
你需要跳过测试，-DskipTests

**Comment by hankcs** [comment]
1. 5是窗口大小。
1. com.hankcs.hanlp.HanLP#extractKeyword第二个参数可以指定需要几个关键词。

**Comment by freebie5** [comment]
soga，看了半天竟然看错了算法，能说一下score分数是什么原理计算出来的吗？
{预警=1.0584117, 指引=0.8691174, 信号=1.0584117, 防御=1.0584117, 黄色=1.0584117, 霾=0.8691174}
类似这种，指引和霾两个score同样大小，为什么取了指引，不取霾，这句话里边的话，霾是比指引要关键的。。。

**Comment by hankcs** [comment]
http://www.hankcs.com/nlp/textrank-algorithm-to-extract-the-keywords-java-implementation.html

**Comment by freebie5** [comment]
textrank提取关键词的算法，有个问题，那就是一句话没有重复的关键词的情况下，首尾的关键词的score一定是最小且相等的两个，例如：
霾黄色预警信号防御指引，这句话的score如下：
{预警=1.0584117, 指引=0.8691174, 信号=1.0584117, 防御=1.0584117, 黄色=1.0584117, 霾=0.8691174}

**Comment by freebie5** [comment]
个人觉得，score的计算还应该结合词频，用词频做完权重，词频大的，权重大

**Comment by AnyListen** [comment]
@freebie5 
可以考虑 TF/IDF ， 这样的话就需要添加一个初始化词典了

**Comment by freebie5** [comment]
@AnyListen 我看了代码了，现在的流程是先分词，分词之后每个关键词都要对应的词频，我现在想把词频也结合进这个textrank算法里边，现在的textrank算法对于短的话，分词效果一般；
而且这个算法有个规律，如果一句话没有重复的关键词，那么score的分布式对称的，且score大小由中间向左右两边递减，而且左右两边的score大小是对称的

**Comment by hankcs** [comment]
有意思的发现，TextRank的确被很多人诟病。但事实上无监督的方法都不会按人想的标准来，有计划实现一些有监督的方法。

**Comment by freebie5** [comment]
还有一个问题，博主你的java代码实现textrank算法的时候，直接用float类型计算1-d会有误差

![qq 20180412162612](https://user-images.githubusercontent.com/23119744/38665386-dc5f7d46-3e6e-11e8-96be-b1c2c69130cc.png)

**Comment by hlstudio** [comment]
@freebie5  @hankcs   "如果一句话没有重复的关键词，那么score的分布式对称的"，短句子中TF都一样，只是由于投票迭代计算引起的差别，如果需要抑制这种差别，可以考虑把单词系列组成环再开窗迭代，这样首词的前面、尾词的后面都会有词，能减少这个影响。

**Comment by freebie5** [comment]
soga，这也是一个方法，我后来没用textrank提取分词了，后来直接根据词频提取

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
