### ISSUE TITLE
关于感知机分词的一点疑问

### ISSUE THREAD

**Issue by l06066hb** [hankcs/HanLP#783]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.6.2
我使用的版本是：1.6.2

## 我的问题

仿照文档中的示例可以正确识别“下雨天地面积水”，但是对“中国联通是公司”的学习不如预期，不知道是不是我在使用上有不当导致。

### 触发代码

```
    public void testIssue1234() throws Exception
    {
        PerceptronSegmenter segmenter = new PerceptronSegmenter(HanLP.Config.PerceptronCWSModelPath);
            System.out.println(segmenter.segment("下雨天地面积水"));
            segmenter.learn("下雨天 地面 积水");
            System.out.println(segmenter.segment("下雨天地面积水"));
            System.out.println(segmenter.segment("中国联通是公司"));
            segmenter.learn("中国联通 是 公司");
            System.out.println(segmenter.segment("中国联通是公司"));
    }
```
### 期望输出

```
期望输出
            [下雨, 天地, 面积, 水]
            [下雨天, 地面, 积水]
            [中国, 联通, 是, 公司]
            [中国联通, 是, 公司]
```

### 实际输出

```
实际输出
            [下雨, 天地, 面积, 水]
            [下雨天, 地面, 积水]
            [中国, 联通, 是, 公司]
            [中国, 联通, 是, 公司]
```

**Comment by hankcs** [comment]
多学习两遍就可以了：

```
        segmenter.learn("中国联通 是 公司");
        segmenter.learn("中国联通 是 公司");
        System.out.println(segmenter.segment("中国联通是公司"));
```

**Comment by l06066hb** [comment]
好的 谢谢

**Comment by hankcs** [comment]
1. 请参考com.hankcs.hanlp.tokenizer.lexical.AbstractLexicalAnalyzer#acceptCustomWord
1. 新版本希望纠正常年来的误区，词典不等于分词、分词不等于自然语言处理；推荐使用语料而不是词典去修正统计模型。当然，不接受的话可以override这个方法。

**Comment by 34127chi** [comment]
自定义词典中添加分词词性会影响其他语句的分词结果吗

**Comment by 34127chi** [comment]
@wangzhe258369 我测试发现自定义词典在感知机分词中好像并没起作用，而像其他的crf都起作用了，请问下你后期是怎么解决的？

**Comment by wangzhe258369** [comment]
@34127chi HanLP更新到1.6.2或以上的版本，然后设置analyzer.enableCustomDictionaryForcing(true);

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
