### ISSUE TITLE
人名识别错误

### ISSUE THREAD

**Issue by KevinChen1994** [hankcs/HanLP#784]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：portable-1.6.2
我使用的版本是：portable-1.3.4

## 我的问题
在自定义词典中添加了人名，分词过程中没有识别出来。

### 步骤

1. 在自定义词典中添加了“苏苏 nr 10”，然后删除掉.bin的文件。
2. 重新运行分词代码，句子为“苏苏中级会计什么时候更新”，分词结果为“[苏苏中级, 会计, 什么, 时候, 更新]”。
3. 我在代码中添加
CustomDictionary.add("苏苏");
StandardTokenizer.SEGMENT.enableCustomDictionary(true);
执行的结果还是一样。
4. 我打开调试模式，HanLP.Config.enableDebug(); 输出分词过程，观察到“识别出人名：苏中级 XD
识别出人名：苏苏中级 BXD“。但是我在人名词典中并没有发现有“苏中级”或者“苏苏中级”这样的词。
5. 我关闭人名识别后，输出结果不是我想要的，在实际使用中还有很多句子包含人名，所以这种方式我就放弃了。
### 触发代码

```
    public void testIssue1234() throws Exception
    {
        String s = "苏苏中级会计什么时候更新";
        CustomDictionary.add("苏苏");
        StandardTokenizer.SEGMENT.enableCustomDictionary(true);
        HanLP.Config.enableDebug();
        System.out.println(HanLP.segment(s));
    }
```
### 期望输出

[苏苏, 中级, 会计, 什么, 时候, 更新]

### 实际输出

[苏苏中级, 会计, 什么, 时候, 更新]

## 其他信息

附上DEBUG日志：
人名角色观察：[  K 1 A 1 ][苏 B 2141 E 105 C 102 D 34 ][苏中 X 1 ][级 D 3 C 1 K 1 ][会计 K 12 L 1 ][什么 L 4 K 3 ][时候 K 21 ][更新 Z 96 L 11 ][  A 20843310 ]
人名角色标注：[ /K ,苏/B ,苏中/X ,级/D ,会计/L ,什么/L ,时候/K ,更新/Z , /A]
识别出人名：苏中级 XD
识别出人名：苏苏中级 BXD
细分词网：
0:[ ]
1:[苏, 苏苏中级]
2:[苏中, 苏中级]
3:[]
4:[级]
5:[会计]
6:[计]
7:[什么]
8:[]
9:[时候]
10:[]
11:[更新]
12:[]
13:[ ]

**Comment by l06066hb** [comment]
可以试试感知机分词，人名的识别还是不错的
分词结果：苏苏/nr 中级会计/v 什么/r 时候/n 更新/v

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。
