### ISSUE TITLE
导航到达茂旗 分词错误

### ISSUE THREAD

**Issue by kingdeewang** [hankcs/HanLP#785]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [ ] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.6.2
我使用的版本是：1.6.2

## 我的问题
导航到达茂旗
HanLP.newSegment().enableCustomDictionary(false).enableUserDefaultDictionary(true).enablePlaceRecognize(true)
 normalsegment.seg(“导航到达茂旗 ”);

期望分词是 导航到 达茂旗
实际：
导航 到达 茂旗

## 复现问题
  在CoreNatureDictionary.ngram.txt 中增加了到@达茂旗 10000
同样分词有错误

**Comment by wangzhe258369** [comment]
1. 设置`analyzer.enableCustomDictionaryForcing(true);`
2. 添加"达茂旗"到“全国地名大全.txt”这个词典，不需要设置词性和词频。

**Comment by kingdeewang** [comment]
谢谢，可以了。另外有一个问题请教一下 运河北路1399号，我想如何分成： 
运河/ns, 北路/ns,  1399号/mq，这样的形式？ 可以指点一下吗？

**Comment by hankcs** [comment]
你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真填写，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
