### ISSUE TITLE
分词出现问题，应该如何操作才可以修正？

### ISSUE THREAD

**Issue by Chand-zhang** [hankcs/HanLP#786]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.6.2
我使用的版本是：1.6.2

### Jar和词库
1.6.2 Release版Jar；
1.6.2的Release词库（data-for-1.6.2.zip）；
hanlp.properties 仅修改了root地址；

### 问题分词
以下语句使用标准分词（HanLP.segment）出现问题：
#### 语句
 学生从简短的诗歌中感受到朱德和战士们的深厚情谊。
#### 分词结果
学生/nnt 从/p 简短/a 的/ude1 诗歌/n 中/f 感受到/nz 朱德和/nr 战士/nnt 们/k 的/ude1 深厚/a 情谊/n 。/w

#### 提取关键字结果
["感受到","朱德和","诗歌","战士","深厚","简短","情谊","学生"]
#### 提取短语结果
["中感受到","学生简短","感受到朱德和","战士深厚","朱德和战士","深厚情谊","简短诗歌","诗歌中"]

### 期望结果
 想把朱德分出来，应该如何操作？

**Comment by hankcs** [comment]
1. 感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。
1. 推荐使用感知机，[演示](http://hanlp.hankcs.com/?sentence=%E5%AD%A6%E7%94%9F%E4%BB%8E%E7%AE%80%E7%9F%AD%E7%9A%84%E8%AF%97%E6%AD%8C%E4%B8%AD%E6%84%9F%E5%8F%97%E5%88%B0%E6%9C%B1%E5%BE%B7%E5%92%8C%E6%88%98%E5%A3%AB%E4%BB%AC%E7%9A%84%E6%B7%B1%E5%8E%9A%E6%83%85%E8%B0%8A%E3%80%82)。
