### ISSUE TITLE
一个自定义词库生成bin文件的问题

### ISSUE THREAD

**Issue by tjzhaomengyi** [hankcs/HanLP#789]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号
当前最新版本号是：1.6.2
我使用的版本是：1.6.2

## 我的问题

自定义词库生成bin文件，通过配置hanlp.properties文件中CustomDictionaryPath，配置同一目录下多个自定义字典，Hanlp不能一次生成所有自定义字典的bin文件，每次只能生成CustomDictionaryPath配置项的第一个自定义字典的bin文件，导致剩下的自定义字典中的词不能识别拆分。

## 复现问题
Hadoop集群中添加自定义词典

### 步骤

1. 首先，在自定义目录custom下面添加自定义词典(比如，字典名为军事.txt; 动植物.txt; 历史.txt; 娱乐.txt; 旅行.txt)
2. 然后，在hanlp.properties中添加CustomDictionaryPath配置(比如，CustomDictionaryPath=data/dictionary/custom/军事.txt; 动植物.txt; 历史.txt; 娱乐.txt; 旅行.txt)
3. 接着，执行Hanlp拆分，执行完后，只能生成"军事.txt.bin"的bin文件，动植物、历史、娱乐、旅行对应的bin文件不能生成

### 期望输出

通过配置文件可以生成所有bin文件

### 实际输出

只有第一个配置词典的bin文件，导致后续分词，除第一个以外的字典都不能用来自定义分词

**Comment by hankcs** [comment]
1. 实际上所有词典合并为同一个bin，文件命名为第一个词典名称。
1. 算法不保证词典中的词语一定分出来，世界上不存在这样的算法。很多人不理解这个问题，以为用户词典中的词语一定会分出来。事实上，这个需求是自相矛盾的，稍微思考一下就能明白。假如用户词典中一共3个词语：商品、和服、服务，那么“商品和服务”中到底分成什么才能满足这些用户呢？无论怎么分词，这3个词语都不可能同时出现。

**Comment by tjzhaomengyi** [comment]
感谢，原来是默认都以第一个字典的名称来命名bin文件。现在我再添加新的字典都是把这个目录下对应第一个生成bin文件生成一下再用。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
