### ISSUE TITLE
关于自定义Recognition和日期或者时间的分词上的问题

### ISSUE THREAD

**Issue by l06066hb** [hankcs/HanLP#791]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.6.2
我使用的版本是：1.6.2

## 我的问题
请问在对"管理员于2017-10-12对该设备信息进行了修改操作"进行拆分时，“2017-10-12”这个日期会被单独拆开。有没有好的方式解决这点，找了找类似的issue,貌似没找到合适的方式。另外现在有提供Recognition自定义么。

### 触发代码

```
     public void testIssue1234() throws Exception
    {
        PerceptronLexicalAnalyzer analyzer =  new PerceptronLexicalAnalyzer();
        System.out.println(analyzer.seg("管理员于2017-10-12对该设备信息进行了修改操作"));
    }
```
### 期望输出

```
管理员/n, 于/p, 2017-10-12, 对/p, 该/r, 设备/n, 信息/n, 进行/v, 了/u, 修改/v, 操作/v
```

### 实际输出

```
管理员/n, 于/p, 2017-/m, 10/m, -/q, 12/m, 对/p, 该/r, 设备/n, 信息/n, 进行/v, 了/u, 修改/v, 操作/v


```

## 其他信息

运行截图：
![38286722-5e5c1772-37f9-11e8-83b0-eb77566f9c82](https://user-images.githubusercontent.com/18030444/38715484-f8034542-3f0d-11e8-8b38-3fa6236a8e5b.png)

**Comment by hankcs** [comment]
1. 这些杂项可以写规则来实现，但我对规则提不起兴趣
1. 对PerceptronLexicalAnalyzer而言，推荐用在线学习调整
1. 对其他Segment，可以试试：

```
        CharType.type['-'] =  CharType.type['1'];
        System.out.println(HanLP.segment("管理员于2017-10-12对该设备信息进行了修改操作"));
```

**Comment by l06066hb** [comment]
感谢您的回答，那对于其他的Segment的，类似的2017年12月12日这类的拆分呢

**Comment by AnyListen** [comment]
@l06066hb 时间的识别是一项单独的任务，只能通过简单分词后，通过规则进行提取，完全依赖分词是不可能实现的，如果只是你提到的这几种常见的日期类型，推荐直接使用正则表达式进行匹配。

**Comment by hankcs** [comment]
没什么问题，统计模型没有绝对的规律，不如把你批量测试的代码改成批量学习的。

**Comment by l06066hb** [comment]
好的  感谢你的回复

**Comment by junjianw** [comment]
PerceptronLexicalAnalyzer @hankcs  从哪个版本加上去。我目前使用的1.5.4 是否有必要升级

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
