### ISSUE TITLE
基于互信息和左右信息熵的短语提取识别疑问

### ISSUE THREAD

**Issue by junphine** [hankcs/HanLP#794]
左熵和右熵代表边界的结合相关性，那么左熵和右熵值越大，说明他们和边界组成短语的概率在变大，那么和当前两个词组成短语的概率就应该变小，这样短语提取时，做score时，左熵和右熵应该是负因素吧/

极限情况，两个词A和B，AB左熵为0，右熵为0，AB互熵不为0，AB明显应该成为词组

两个词C和D，CD左熵为10，右熵为0，CD互熵为2，CD和左边结合的概率不小，这样CD成词组的概率就不那么确定了。

**Comment by Scagin** [comment]
@junphine 你好，我对互信息量的计算是理解的，但是我一直没有弄明白左右熵代表的是什么。根据原作者的文章，并没有指明左右熵计算是当前词与哪些词的计算结果，所以我一直无法理解这个熵的结果代表什么。你能不能详细说一说呢？万分感谢！

**Comment by hankcs** [comment]
你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真填写，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
