### ISSUE TITLE
感知机词性标注，生成的新语料不生效问题

### ISSUE THREAD

**Issue by xtuyaowu** [hankcs/HanLP#795]
自己生成了一下语料，如下：
商品/n	和/cc	服务/vn	[商品/n	和/cc	服务/vn]/company
当/p	下雨天/n	地面/n	积水/n	分外/d	严重/a	[当/p	下雨天/n	地面/n	积水/n	分外/d	严重/a]/company
结婚/vi	的/ude1	和/cc	尚未/d	结婚/vi	的/ude1	确实/ad	在/p	干扰/vn	分词/n	啊/y	[结婚/vi	的/ude1	和/cc	尚未/d	结婚/vi	的/ude1	确实/ad	在/p	干扰/vn	分词/n	啊/y]/company
买/v	水果/n	然后/c	来/vf	世博园/n	最后/f	去/vf	世博会/n	[买/v	水果/n	然后/c	来/vf	世博园/n	最后/f	去/vf	世博会/n]/company
中国/ns	的/ude1	首都/n	是/vshi	北京/ns	[中国/ns	的/ude1	首都/n	是/vshi	北京/ns]/company
欢迎/v	新/a	老/a	师生/n	前来/vi	就餐/vi	[欢迎/v	新/a	老/a	师生/n	前来/vi	就餐/vi]/company
工信处/nt	女干事/n	每月/r	经过/p	下属/v	科室/n	都/d	要/v	亲口/d	交代/v	24/m	口/n	交换机/n	等/udeng	技术性/n	器件/n	的/ude1	安装/v	工作/vn	[工信处/nt	女干事/n	每月/r	经过/p	下属/v	科室/n	都/d	要/v	亲口/d	交代/v	24/m	口/n	交换机/n	等/udeng	技术性/n	器件/n	的/ude1	安装/v	工作/vn]/company
随着/p	页游/nz	兴起/v	到/v	现在/t	的/ude1	页游/nz	繁盛/a	，/w	依赖于/v	存档/vi	进行/vn	逻辑/n	判断/v	的/ude1	设计/vn	减少/v	了/ule	，/w	但/c	这/rzv	块/q	也/d	不能/v	完全/ad	忽略/v	掉/v	。/w	[随着/p	页游/nz	兴起/v	到/v	现在/t	的/ude1	页游/nz	繁盛/a	，/w	依赖于/v	存档/vi	进行/vn	逻辑/n	判断/v	的/ude1	设计/vn	减少/v	了/ule	，/w	但/c	这/rzv	块/q	也/d	不能/v	完全/ad	忽略/v	掉/v	。/w]/company
北京/ns	卧虎藏龙/nz	网络科技/nz	有限公司/nis	（/w	椅子/n	网/n	）/w	[北京/ns	卧虎藏龙/nz	网络科技/nz	有限公司/nis	（/w	椅子/n	网/n	）/w]/company

按照下面教程提取训练、词性标注
https://github.com/hankcs/HanLP/wiki/结构化感知机标注框架

商品/n	和/cc	服务/vn	[商品/n	和/cc	服务/vn]/company
但是 商品和服务 没有标注成 company ，求指导

**Comment by hankcs** [comment]
你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真填写，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
