### ISSUE TITLE
优化CRF分词效率的方法

### ISSUE THREAD

**Issue by TylunasLi** [hankcs/HanLP#796]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.6.3
我使用的版本是：1.6.3

## 我的问题

[CRF分词](https://github.com/hankcs/HanLP#6-crf%E5%88%86%E8%AF%8D)和[感知机分词](https://github.com/hankcs/HanLP/wiki/%E7%BB%93%E6%9E%84%E5%8C%96%E6%84%9F%E7%9F%A5%E6%9C%BA%E6%A0%87%E6%B3%A8%E6%A1%86%E6%9E%B6)的流程相差不大(都是提取特征->查概率/权重->累加->Viterbi), 
但Wiki上面的测试结果差距却很大。而且HanLP早期的CRF模型特征模板数量少于当前感知机的七个模板。
因此查看了一下HanLP构造CRF模型的逻辑，我发现了一个问题：
CRF++生成的特征都是以“U[0-9]+:”开头的，而模型使用BinTrie索引特征概率，这就导致BinTrie加速的第一层只有一个字符“U”，，所有的特征都都走了二分查找，难怪速度会慢。

## 解决思路

需要解决的是如何把汉字索引到第一级同时又不影响效率，我觉得可以考虑拆解重组特征模板和特征Key，或者直接reverse字符串。

**Comment by hankcs** [comment]
是的，感谢建议。可能还有些地方造成了效率差距，按试验结果来讲，BinTrie比MutableDAT要快很多。我觉得是特征提取的环节，现在的感知机是硬编码的特征模板，可能也是个原因。

**Comment by TylunasLi** [comment]
https://github.com/TylunasLi/HanLPToolkit
这里面有我我之前基于HanLP的CRF模型和BinTrie实现的感知机模型（带训练），有机会测试一下效率做个对比。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
