### ISSUE TITLE
HanLP进行文本转汉语拼音时需要优化

### ISSUE THREAD

**Issue by isblwang** [hankcs/HanLP#798]
用HanLP的用户目前多为做语音识别相关，目前HanLP对汉字转汉语拼音的支持仅限汉字。
但是通常情况下，用户输入的文本并不能确定是中文还是英文，那么，在这种场景中应该支持的是：如果是中文，那么就转成汉语拼音，如果不是那么就保留。

**Comment by hankcs** [comment]
/**
     * 转化为拼音
     *
     * @param text       文本
     * @param separator  分隔符
     * @param remainNone 有些字没有拼音（如标点），是否保留它们的拼音（true用none表示，false用原字符表示）
     * @return 一个字符串，由[拼音][分隔符][拼音]构成
     */
    public static String convertToPinyinString(String text, String separator, boolean remainNone)
