### ISSUE TITLE
v1.6.2感知机生效了，但是能自定义词性标签么？

### ISSUE THREAD

**Issue by xtuyaowu** [hankcs/HanLP#800]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.6.3
我使用的版本是：1.6.2

## 我的问题

按照https://github.com/hankcs/HanLP/wiki/结构化感知机标注框架 训练自己的语料，没有达到预想效果。

### 步骤

1. 生成语料
   你好/vl	自治县/n	[你好/vl	自治县/n]/company
   上街/vi	北路/n	[上街/vi	北路/n]/company

2. 分别进行如下训练
   CWSTrainer PerceptronTrainer  PerceptronTrainer 

3. PerceptronLexicalAnalyzer 测试

### 触发代码

```
        Sentence sentence = segmenter.analyze("上街北路");
        System.out.println(sentence);
```
### 期望输出

上街北路/company

### 实际输出

上街/vi	北路/n

**Comment by hankcs** [comment]
1. 语料格式错误，你重复了两遍上街北路，两遍的标注不一致
1. 你需要训练分词和命名实体识别两个模型才能达到你要的效果。

**Comment by xtuyaowu** [comment]
感谢作者，调整了一下语料，现在能分出来了，但是还有一个问题，比如语料增加：
[上海/ns	科技/n	跳/vi	好书/n	有限公司/nis]/company

然后：
PerceptronLexicalAnalyzer analyzer = new PerceptronLexicalAnalyzer
                                                             (CWS_MODEL_FILE, POS_MODEL_FILE, NER_MODEL_FILE);
System.out.println(analyzer.analyze("上海科技跳好书有限公司"));
输出结果是：[上海/ns 科技/n 跳/v 好书/n 有限公司/n]/nt

请问不能之定义词性标签么 company？

**Comment by hankcs** [comment]
完全可以实现任意标注集、任意个NER类别，但是需要重载一个方法，详情请参考[文档](https://github.com/hankcs/HanLP/wiki/%E7%BB%93%E6%9E%84%E5%8C%96%E6%84%9F%E7%9F%A5%E6%9C%BA%E6%A0%87%E6%B3%A8%E6%A1%86%E6%9E%B6#%E8%87%AA%E5%AE%9A%E4%B9%89ner%E7%B1%BB%E5%9E%8B)。

**Comment by hankcs** [comment]
样本比例太低，可以考虑注释掉nt

**Comment by xtuyaowu** [comment]
感谢，刚刚做了一个实验，把 nt 全部换成 company，可以识别了，确实是你说的样本问题，感知机在自然语言上的运用还挺有意思的，这个问题我关闭了。
