### ISSUE TITLE
分词词性识别错误

### ISSUE THREAD

**Issue by lsm307742191** [hankcs/HanLP#803]
“教练，今天晚上有空练车” 
“练车”被识别成 nr词性，词性识别错误

**Comment by hapjin** [comment]
你应该按照提问规范来提问，可参考一下别的issues中是如何提问的。因为版本、采用的算法不一样，结果就不一样。
比如，我用的HanLP1.6.3 `List<Term> termList = HanLP.segment("教练，今天晚上有空练车");`
[教练/nnt, ，/w, 今天/t, 晚上/t, 有空/vi, 练/v, 车/n]
跟你分出来的结果就不一样。

**Comment by hankcs** [comment]
你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真填写，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
