### ISSUE TITLE
你好语料预处理工具怎么使用？没有找到文档？

### ISSUE THREAD

**Issue by zhaofeiwuzhao** [hankcs/HanLP#804]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [ ] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：
我使用的版本是：

## 我的问题

我是做电子病历的，现在有大量电子病历想训练成模型，但是按照您文档说的语料格式工作量太大了。我想使用您提供的语料预处理工具，但是没有找到不知道怎么使用（我是做c++的java第一次接触，请您告知一下）。

## 复现问题
暂无

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 期望输出

```
期望输出
```

### 实际输出

实际输出
```

## 其他信息

**Comment by hankcs** [comment]
你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真填写，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
