### ISSUE TITLE
集成到Android Studio上出现错误

### ISSUE THREAD

**Issue by HungryGoogle** [hankcs/HanLP#805]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [ ] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：hanlp-1.6.3-release.zip
我使用的版本是：hanlp-1.6.3-release.zip 和1.6.2 data

## 我的问题
1、用Eclipse可以直接集成使用
2、使用android studio添加java library，创建main函数，使用hanlp分词，会出现下面的错误
Exception in thread "main" java.lang.NoClassDefFoundError: com/hankcs/hanlp/tokenizer/NLPTokenizer
	at deepin.hanlplib.myClass.main(myClass.java:12)
Caused by: java.lang.ClassNotFoundException: com.hankcs.hanlp.tokenizer.NLPTokenizer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more

## 复现问题
1、用Eclipse可以直接集成使用
2、使用android studio添加java library，创建main函数，使用hanlp分词，会出现下面的错误

### 步骤

1、用Eclipse可以直接集成使用
2、使用android studio添加java library，创建main函数，使用hanlp分词，会出现下面的错误

### 触发代码

public class myClass {
    public static void main(String[] agrs){
//        System.out.println(HanLP.segment("你好，欢迎使用HanLP汉语处理包！"));
////        System.out.println("hello");

        java.util.List<Term> termList = NLPTokenizer.segment("中国科学院计算技术研究所的宗成庆教授正在教授自然语言处理课程");

    }
}
### 期望输出

能正常使用

### 实际输出

异常报错

## 其他信息

无

**Comment by hankcs** [comment]
你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真填写，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
