### ISSUE TITLE
TextRank算法的优化

### ISSUE THREAD

**Issue by hlstudio** [hankcs/HanLP#806]
TextRank算法采用多轮迭代收敛来获取结果，目前的实现中score没有赋初值。
实际测试中依据已有信息赋初值能有效的降低迭代轮次，以作者
http://www.hankcs.com/nlp/textrank-algorithm-to-extract-the-keywords-java-implementation.html 
的例子，采用了两种不同的初值方法
1、初值采用sigmoid函数来赋值，实测示例计算从37轮迭代降低为9轮。我是用scala测试的，Java实现参考 
Map score = new HashMap(); 
for (Map.Entry<String, Set> entry : words.entrySet()){ score.put(entry.getKey(),sigmoid(entry.getValue().size()); 
}
2、把sigmoid函数更改为 1.0*entry.getValue().size()/words.size()，可以从37轮次降低为34轮次

建议采用sigmoid函数提升效率，sigmoid函数scala实现就是一行
def sigmoid(x:Double):Double ={1d/(1d+Math.exp(-x))}

**Comment by hlstudio** [comment]
对结果得分和排序都不产生影响，只是加快计算的收敛，减少迭代的轮次，从而提升计算速度。
暂未找到相关文献，简单描述一下，textrank的输入是一组单词系列(a,b,c,d,e)，输出是排好序的如
((c,2.5),(d,2.1),(a,1.8),(e,1.5),(c,1.2))单词得分情况。核心算法是pagerank的投票权体现，可以视为是一个神经网络，如果设置初值为0相当于我们对神经网络不干预，由算法迭代逐步得出结果。而最终结果和词频TF是有（正）相关性的，我们用sigmoid函数干预一下指导神经网络TF越大可能最终得分越大，开始就给每个单词不同的权重，这种正确的指导相当于减少了神经网络的尝试，实测会大幅减少迭代的次数。

**Comment by hlstudio** [comment]
刚想到textrank的算法核心原则其实是这样两条
1、TF越高的词越重要
2、和越重要的词在一起的词也越重要
第1条解释一下，TF越高的词，在文中出的次数越多，窗口关系拥有也越多，会有更多的词投票给它，会提升它的重要性
第2条解释一下，在一起其实是就是窗口关系计算，然后拿pagerank来类比，pr越高的网页引用的网页也越重要，其本质是textrank的公式中体现出越重要的词其投票权重更大。

因此，TF对textrank是正相关，但textrank的最终排序结果会和单纯TF排序结果不完全相同（也有可能会相同），主要是受规则2的影响
这也算是给依据TF的sigmoid来设置初值能提升性能的另一个解释吧。

**Comment by hankcs** [comment]
欢迎提交代码
