### ISSUE TITLE
人名识别不准确

### ISSUE THREAD

**Issue by funyaya** [hankcs/HanLP#810]
## 版本号

当前最新版本号是：1.6.3
我使用的版本是：1.6.3

## 我的问题
人名识别有误：
“他负责冲货（串货）的调查与处理，包括线上线下冲货” 
=> 
[他/r, 负责/v, 冲货/v, （/w, 串货/nr, ）/w, 的/u, 调查/vn, 与/p, 处理/vn, ，/w, 包括/v, 线/n, 上/f, 线/n, 下/f, 冲货/n]

“串货”这个词误识别为人名
### 触发代码

```
//这个问题是在运行以下代码时出现：
NLPTokenizer.ANALYZER
	.enableNameRecognize(true)
	.enableTranslatedNameRecognize(true)
	.enableJapaneseNameRecognize(true)
	.enablePlaceRecognize(true)
	.seg("他负责冲货（串货）的调查与处理，包括线上线下冲货");
```

**Comment by hankcs** [comment]
1. 可以在线学习
1. 1998一个月份的语料无法用于生产环境，在[大型语料库](https://github.com/hankcs/OpenCorpus/tree/master/cncorpus)上训练的模型完全可以[正确处理这个例子](http://hanlp.hankcs.com/?sentence=%E6%99%BA%E8%81%94%E6%8B%9B%E8%81%98_%E9%99%88%E7%84%AF%E7%83%BD_%E4%B8%AD%E6%96%87_20100214_55123123.doc)。
