### ISSUE TITLE
“C++”这个词分词时有多种结果

### ISSUE THREAD

**Issue by funyaya** [hankcs/HanLP#812]
## 我的问题
我在自定义词库txt文件中，增加“C++”这个词条，分词的结果是C和++分开了；但如果使用代码CustomDictionary.add("C++")，分词的结果是把C++看成一个词。
请问，如果我不想用CustomDictionary.add()，想在自定义词库txt文件中加C++，如果配置才能让分词结果把它们看成是一个词？

**Comment by funyaya** [comment]
我找到原因了，是因为我存放C++的txt文件里面，有一些词有问题，使得整个txt文件都不能成功纳入词库，CustomDictionary.get("C++") 等于 null

**Comment by hapjin** [comment]
发现有很多关于自定义词典的问题的issue。你可以先搜索一下相关的issue，然后自己debug。参考这个：[#828](https://github.com/hankcs/HanLP/issues/828#issuecomment-391568557)

**Comment by hankcs** [comment]
你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真填写，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
