### ISSUE TITLE
关于 HanLP.segment() 的几个问题（主要围绕自定义词典、词性与词频）

### ISSUE THREAD

**Issue by wenfeixiang1991** [hankcs/HanLP#813]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.6.3
我使用的版本是：hanlp-portable-1.6.3 （通过 maven 配置的版本）

## 我的问题

1. 我已经了解用户自定义词典拥有以下特性：
（1）、加入自定义词典的词不一定会分出来，因为HanLP.segment会基于统计模型、语料与核心词典与词频等信息对句子进行切分，如将“国新能源”加入自定义词典后，分词并不会将“我国新能源行业”分成“我/国新能源/行业”，而是分成正确的“我国/新能源/行业”，但如“国新能源股票大涨”则会分为“国新能源/股票/大/涨”，这是非常理想的效果。
（2）、加入自定义词典的词、词性、词频，在分词后，其中词性会覆盖掉其原有的词性。如将“国家 Country 1”加入自定义词典中后，会将“国家/n”变为“国家/Country”。
（3）、自定义词典中的词频（具体数值）设置，并没能起到理想的作用（指调高词频后，会将其分出），如我将“国新能源 Stock 9999999” 加入自定义词典，并未能改变“我国/新能源/行业”的分词结果，与“国新能源 stock 1” 的效果是相同的，所以今后在自定义词典中设置词频时，可以选择 1 。
上述（1）、（2）、（3）点我的理解方向大致正确吗？（相关代码在下面）

2. 我在试验时，将“龙三  Conception 1”与“国元证券 Stock 1”加入用户自定义词典后，在不同句子中并不一定能将其分出，将其词频调高至9999999也不能将其分出，我了解到如果强制使用用户自定义词典而忽略掉核心词典的话，是可以达到将词出的效果，但正如 hanks 所说，它会在某个未知的位置引发其它未知（未发现）的错误。
如果我就想针对这个发现的不能分出的词作处理，并不想将所有的自定义词典的词都一定分出，也就是仍然需要核心词典信息等，该如何处理？（相关代码在下面）

3. 如何判断一个词是否在已知的词典中？只能去 CoreNatureDictionary.txt 中找吗？因为我有一个想法是，在添加自定义词典时，先判断这个词是否已在 HanLP.segment 的词典中，如果不在，我再添加并将词频设置为1，这么做的目的是不想更改原有的词性和词频，导致一些不必要的错误，因为我觉得，HanLP.segment 在绝大多数通常情况下分词是没有问题的。

4. 在添加自定义词典时，如果这个词已经在词典中，如何只更改此词的词性？这么做的目的是想保留原有词的词频。难道需要取到该词在原有词典中的词频，然后再同新词性一起加入到自定义词典中吗？这样，新词性就会覆盖掉原有词性了。

5. `CustomDictionary.insert("国新能源", "hy 1");`与`CustomDictionary.add("国新能源", "hy 1");`有什么区别？“强行加入”和“加入”？

6. `offset`属性只有在`IndexTokenizer.segment`中起作用吗？在`HanLP.segment`中分词后所有词的`offset`值都为0？（相关代码在下面）

## 复现问题
在通过 maven 方式配置了 hanlp-portable-1.6.3 后，并未做任何修改，所有的自定义词典操作都是通过代码动态添加来进行试验的。

### 触发代码
```
    //问题1下的（1）
    public static void main(String[] args) 
    {
        CustomDictionary.insert("国新能源", "Stock 1");
        System.out.println(HanLP.segment("我国新能源行业"));
        System.out.println(HanLP.segment("国新能源股票大涨"));
    }
    期望输出与实际输出一致：
        [我国/n, 新能源/nz, 行业/n]
        [国新能源/Stock, 股票/n, 大/a, 涨/v]
```
```
    //问题1下的（2）
    public static void main(String[] args) 
    {
        System.out.println(HanLP.segment("家庭、私有制和国家的起源"));
        CustomDictionary.insert("国家", "Country 1");
        System.out.println(HanLP.segment("家庭、私有制和国家的起源"));
    }
    期望输出与实际输出一致：
        [家庭/n, 、/w, 私有制/n, 和/c, 国家/n, 的/uj, 起源/n]
        [家庭/n, 、/w, 私有制/n, 和/c, 国家/Country, 的/uj, 起源/n]
```
```
    //问题1下的（3）
    public static void main(String[] args) 
    {
        CustomDictionary.insert("国新能源", "Stock 9999999");
        System.out.println(HanLP.segment("大赞我国新能源"));
    }
    实际输出：
        [大赞/nrf, 我国/n, 新能源/nz]
    期望输出：
        [大赞/nrf, 我/r, 国新能源/Stock]
```
```
    //问题2
    public static void main(String[] args) 
    {
        CustomDictionary.insert("龙三", "Conception 1");
        CustomDictionary.insert("国元证券", "Stock 1");
        System.out.println(HanLP.segment("龙三国元证券"));
        System.out.println(HanLP.segment("龙三和国元证券"));
        System.out.println(HanLP.segment("龙三与国元证券"));
        System.out.println(HanLP.segment("龙三及国元证券"));

        System.out.println("\n");

        CustomDictionary.insert("龙三", "Conception 9999999");
        CustomDictionary.insert("国元证券", "Stock 9999999");
        System.out.println(HanLP.segment("龙三国元证券"));
        System.out.println(HanLP.segment("龙三和国元证券"));
        System.out.println(HanLP.segment("龙三与国元证券"));
        System.out.println(HanLP.segment("龙三及国元证券"));
    }
    实际输出：
        [龙三国/nr, 元/q, 证券/n]
        [龙/n, 三和/nz, 国元证券/Stock]
        [龙三/Conception, 与/p, 国元证券/Stock]
        [龙三/Conception, 及/c, 国元证券/Stock]
    期望输出：
        [龙三/Conception, 国元证券/Stock]
        [龙三/Conception, 和/c, 国元证券/Stock]
        [龙三/Conception, 与/p, 国元证券/Stock]
        [龙三/Conception, 及/c, 国元证券/Stock]
```
```
    //问题3、4为思路性问题，问题5 将 CustomDictionary.insert 换为 CustomDictionary.add 无变化
```
```
    //问题6
    public static void main(String[] args) 
    {
        List<Term> termList = HanLP.segment("打工是不可能打工的");
        System.out.println(termList);
        for (Term term : termList){
            System.out.println("offset: " + term.offset);
            System.out.println("wordLength: " + term.word.length());
        }
    }
    实际输出：
        [打工/v, 是/v, 不/d, 可能/v, 打工/v, 的/uj]
        offset: 0
        wordLength: 2
        offset: 0
        wordLength: 1
        offset: 0
        wordLength: 1
        offset: 0
        wordLength: 2
        offset: 0
        wordLength: 2
        offset: 0
        wordLength: 1
    期望输出：
        [打工/v, 是/v, 不/d, 可能/v, 打工/v, 的/uj]
        offset: 0
        wordLength: 2
        offset: 2
        wordLength: 1
        offset: 3
        wordLength: 1
        offset: 4
        wordLength: 2
        offset: 6
        wordLength: 2
        offset: 8
        wordLength: 1
```

## 其他信息
如何根据 HanLP.Config.enableDebug() 来分析分词结果？如：
```
    //当使用 HanLP.Config.enableDebug();
    public static void main(String[] args) 
    {
       CustomDictionary.insert("龙三", "Conception 1");
        CustomDictionary.insert("国元证券", "Stock 1");
        HanLP.Config.enableDebug();
        System.out.println(HanLP.segment("龙三和国元证券"));
    }
    实际输出：

        粗分词网：
        0:[ ]
        1:[龙]
        2:[三和]
        3:[和]
        4:[国]
        5:[元]
        6:[证, 证券]
        7:[券]
        8:[ ]

        粗分结果[龙/n, 三和/nz, 国元证券/Stock]
        人名角色观察：[  K 1 A 1 ][龙 D 1350 E 924 B 498 C 325 L 17 M 8 K 1 ][三和 A 20833310 ][国元证券 A 20833310 ][  K 1 A 1 ]
        人名角色标注：[ /K ,龙/B ,三和/A ,国元证券/A , /A]
        [龙/n, 三和/nz, 国元证券/Stock]
```
其中，在粗分词网中，为什么没有发现加入自定义词典中的“龙三”和“国元证券”，还有“0:[ ]"、"8:[ ]"表示什么意思啊？
多谢指教！

**Comment by hankcs** [comment]
1. 你的理解是正确的，HanLP在尽力调和统计和规则。目前自定义词典的词频不影响分词，只影响HMM词性标注，这也是HanLP要求按词性分别指定词频的原因。
1. 如果自定词典没有得到预期的效果，可以修改核心词典和bigram。对“龙三和国元证券”这个例子来讲，可以往核心词典中添加`龙三 nz 100`，同时向`data/dictionary/CoreNatureDictionary.ngram.txt`中加入`龙三@和 100`。这里@分开两个词语，后面的数字是频次，越大代表这种切分方式越可能存在。
1. 有对应的类，可调用`com.hankcs.hanlp.dictionary.CoreDictionary#contains`。
1. 的确需要自己写几行代码处理，一个词语可以有多个词性，请参考 https://github.com/hankcs/HanLP#%E8%AF%8D%E5%85%B8%E8%AF%B4%E6%98%8E
1. 如果词典中已有该词条，insert会覆盖，add会跳过。
1. 可通过`com.hankcs.hanlp.seg.Segment#enableOffset`开启。

0和8是句首和句尾，是特别的单词，用来计算词语出现在句首和句尾的概率。粗分的时候不考虑用户词典，因为用户词典缺少统计信息（bigram）。为了减小交叉歧义，用户词典仅用于分词后的合并规则。如果你可以估计一个bigram，那就可以加入到核心词典中了。你可以使用`DijkstraSegment`查看更详细的debug信息。

**Comment by wenfeixiang1991** [comment]
非常感谢，已经很清楚了，但还有两个小问题：
1. 关于`CustomDictionary.add`与`CustomDictionary.insert`,insert确实会覆盖，add也确实会跳过，但前提是判断CustomDictionary中是否包含该词条，而非CoreDictionary是否包含该词条。但直觉上，如果用户用到添加自定义词典的功能，应该判断所有的已有词典是否包含该词啊，然后如果包含，add跳过，insert覆盖。

    为什么只判断CustomDictionary中是否包含该词条呢？

    如“国家”一词是在CoreDictionary中的，但如果我`CustomDictionary.add("国家", "Conception 1");`，而“国家”一词并不在CustomDictionary中，其实还是触发insert，也就是说自定义词典强行加入了“国家”一词，且词性为“Conception”，而词频为1，这样的话，在`HanLP.segment()`分词时，除了词性会覆盖掉以外，难道不会影响本身CoreDictionary中的“国家”的切分效果吗（因为此时的词频为1，且在自定义词典中，按你所说自定义词典中的词频并不影响分词效果）？（相关代码如下）

2. 假设我不用那些复杂的如NLP分词、词性标注、以及句法分析等功能，我只想安安静静地用HanLP的标准分词器`HanLP.segment`，那么，我该如何在不影响分词效果的情况下来修改已有词的词性呢？

    如“化工”一词在CoreDictionary中，但我想将其词性改为唯一的一个“Industry”，因为同问题1的原因一样，如果我在用户自定义词典中加入“化工 Industry 1”覆盖掉的话，会不会就影响了“化工”一词的切分效果呢?

    还有就是我将一个词带有两个词性加入自定义词典，如`CustomDictionary.insert("智慧农业", "Stock 1 Industry 1");`，但`HanLP.segment`分词后，如何才能得到它的全部词性呢？（相关代码如下）

### 触发代码

```
    //问题1
    public static void main(String[] args) 
    {
        //验证 CoreDictionary 是否包含"国家"、"命大"
        System.out.println(CoreDictionary.contains("国家"));
        System.out.println(CoreDictionary.contains("命大"));

        //验证 CustomDictionary 是否包含"国家"、"命大"
        System.out.println(CustomDictionary.contains("国家"));
        System.out.println(CustomDictionary.contains("命大"));

        //结论："国家"在 CoreDictionary 中，"命大"在 CustomDictionary 中

        // add 仍触发 insert，因为 "国家" 并不在 CustomDictionary 中
        CustomDictionary.add("国家", "Country 1");
        //此时分词"国家"词性为 Country
        System.out.println(HanLP.segment("国家的本质"));
        //add 跳过该词，因为 "命大" 在 CustomDictionary 中
        CustomDictionary.add("命大", "Defination 1");
        //此时分词"命大"词性为 本身的词性 即 "a"
        System.out.println(HanLP.segment("谁的命大"));
        //强行加入
        CustomDictionary.insert("命大", "Defination 1");
        //此时分词"命大"词性为 "Defination"
        System.out.println(HanLP.segment("谁的命大"));
    }
    
    实际输出：
        true
        false
        false
        true
        [国家/Country, 的/uj, 本质/n]
        [谁/r, 的/uj, 命大/a]
        [谁/r, 的/uj, 命大/Defination]

```

```
    //问题2
    public static void main(String[] args) 
    {
        CustomDictionary.insert("智慧农业", "Stock 1 Industry 1");
        System.out.println(HanLP.segment("智慧农业既是行业又是股票"));
    }
    
    实际输出：
        [智慧农业/Stock, 既是/c, 行业/n, 又是/c, 股票/n]
    期望输出：
        [智慧农业/[Stock,Industry]?, 既是/c, 行业/n, 又是/c, 股票/n]

```

**Comment by hankcs** [comment]
1. 这只是设计上的独立，因为用户词典是可以动态disable的，所以add并不算覆盖。所谓覆盖也只是覆盖用户词典而已，当你disable用户词典的时候，分词结果不会出现自定义词汇。
1. 在没有`enableCustomDictionaryForcing`的情况下，你add核心词典中已存在的单词，并不会影响分词结果，只会影响标注结果。

有许多共有方法可以通过IDE查看，比如`com.hankcs.hanlp.dictionary.CustomDictionary#get`。

**Comment by wenfeixiang1991** [comment]
了解了，十分感谢！
