### ISSUE TITLE
依存句法分析：使用NeuralNetworkDependencyParser对相同词性结构句子得到不同依存句法分析结果

### ISSUE THREAD

**Issue by xliang10** [hankcs/HanLP#815]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号
当前最新版本号是：portable-1.6.3
我使用的版本是：portable-1.6.3（通过 maven 配置的版本）

## 我的问题
对于相同词性结构的句子<机构>的<修饰性名词><人名>，依存句法分析结果不一致。

## 复现问题
直接调用parser NeuralNetworkDependencyParser（并未进行任何修改），对以下句子进行依存句法分析：
1.上海华安工业公司的员工韩梅梅
2.上海华安工业公司的董事韩梅梅
得到的依存分析结果不一致。不知道是否有改进方法？

### 触发代码
```
    public void testIssue1234() throws Exception
    {
        IDependencyParser parser = new NeuralNetworkDependencyParser().enableDeprelTranslator(false);
        CoNLLSentence sentenceParsed1 = parser.parse("上海华安工业公司的员工韩梅梅");
        CoNLLWord[] arcs1 = sentenceParsed1.word;
        for (CoNLLWord word : arcs1) {
            System.out.printf("%s(%s) --(%s)--> %s(%s)\n", word.LEMMA, word.ID, word.DEPREL, word.HEAD.LEMMA, word.HEAD.ID);
        }
        System.out.println();
        CoNLLSentence sentenceParsed2 = parser.parse("上海华安工业公司的董事韩梅梅");
        CoNLLWord[] arcs2 = sentenceParsed2.word;
        for (CoNLLWord word : arcs2) {
            System.out.printf("%s(%s) --(%s)--> %s(%s)\n", word.LEMMA, word.ID, word.DEPREL, word.HEAD.LEMMA, word.HEAD.ID);
        }
    }
```
### 期望输出
```
上海(1) --(ATT)--> 华安(2)
华安(2) --(ATT)--> 公司(4)
工业(3) --(ATT)--> 公司(4)
公司(4) --(ATT)--> 员工(6)
的(5) --(RAD)--> 公司(4)
员工(6) --(ATT)--> 韩梅梅(7)
韩梅梅(7) --(HED)--> ##核心##(0)

上海(1) --(ATT)--> 华安(2)
华安(2) --(ATT)--> 公司(4)
工业(3) --(ATT)--> 公司(4)
公司(4) --(ATT)--> 董事(6) //对应"员工"
的(5) --(RAD)--> 公司(4)
董事(6) --(ATT)--> 韩梅梅(7)
韩梅梅(7) --(HED)--> ##核心##(0)
```

### 实际输出
但实际输出的依存分析，上海华安工业公司的ATT路径不一致，1.指向“员工”修饰性名词，2.指向“韩梅梅”实体。

```
上海(1) --(ATT)--> 华安(2)
华安(2) --(ATT)--> 公司(4)
工业(3) --(ATT)--> 公司(4)
公司(4) --(ATT)--> 员工(6)
的(5) --(RAD)--> 公司(4)
员工(6) --(ATT)--> 韩梅梅(7)
韩梅梅(7) --(HED)--> ##核心##(0)

上海(1) --(ATT)--> 华安(2)
华安(2) --(ATT)--> 公司(4)
工业(3) --(ATT)--> 公司(4)
公司(4) --(ATT)--> 韩梅梅(7) //不对应"员工"
的(5) --(RAD)--> 公司(4)
董事(6) --(ATT)--> 韩梅梅(7)
韩梅梅(7) --(HED)--> ##核心##(0)
```

**Comment by hankcs** [comment]
<img width="407" alt="hankcs com 2018-05-03 4 11 45" src="https://user-images.githubusercontent.com/5326890/39566032-bfd7de14-4eec-11e8-82bf-85819e130c94.png">
<img width="429" alt="hankcs com 2018-05-03 4 11 55" src="https://user-images.githubusercontent.com/5326890/39566025-bbdaa274-4eec-11e8-9c58-216a6a7fcd76.png">

在哈工大的词聚类中，这两个词分属不同的簇：
<img width="396" alt="hankcs com 2018-05-03 4 18 31" src="https://user-images.githubusercontent.com/5326890/39566309-bdd5b798-4eed-11e8-992a-289bf6fac8ee.png">
<img width="405" alt="hankcs com 2018-05-03 4 17 38" src="https://user-images.githubusercontent.com/5326890/39566314-c14cf422-4eed-11e8-9cbe-f7d1ce3f27bc.png">
它们的词向量肯定也不同。最关键的原因是这个模型太朴素了，其实只是特征工程套一下神经网络。最新的[Deep Biaffine](http://iparser.hankcs.com/?sentence=%E4%B8%8A%E6%B5%B7%E5%8D%8E%E5%AE%89%E5%B7%A5%E4%B8%9A%E5%85%AC%E5%8F%B8%E7%9A%84%E8%91%A3%E4%BA%8B%E9%9F%A9%E6%A2%85)模型就稳定多了。你可以考虑用该项目，可能需要替换分词器。

**Comment by junjianw** [comment]
使用：`ViterbiSegment` 分词 结果是正确的

> 上海华安工业公司的董事韩梅梅

```
6 韩梅梅/nr(人名)/HED(核心关系)
	5 董事/n(名词)/ATT(定中关系)
		3 公司/n(名词)/ATT(定中关系)
			0 上海/ns(地名)/ATT(定中关系)
			1 华安/nr(人名)/ATT(定中关系)
			2 工业/n(名词)/ATT(定中关系)
			4 的/uj(助词·的)/RAD(右附加关系)
```

> 上海华安工业公司的员工韩梅梅

```
6 韩梅梅/nr(人名)/HED(核心关系)
	5 员工/n(名词)/ATT(定中关系)
		3 公司/n(名词)/ATT(定中关系)
			0 上海/ns(地名)/ATT(定中关系)
			1 华安/nr(人名)/ATT(定中关系)
			2 工业/n(名词)/ATT(定中关系)
			4 的/uj(助词·的)/RAD(右附加关系)
```

_`ViterbiSegment`有过修改。 理论上用github的代码也没有问题_

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
