### ISSUE TITLE
分词结果是否带有词性标识的问题

### ISSUE THREAD

**Issue by qian770903** [hankcs/HanLP#816]
对文本进行分词时，可以通过：
HanLP.Config.ShowTermNature=false
将分词的结果屏蔽词性表示，可是在下面的情况中，屏蔽无效，结果中仍然带有词性标识
HanLP.Config.ShowTermNature=false

val data = sc.textFile("hdfs://master:8020/clob.txt")
val splits = data.filter(line => !line.contains("BODY")).map(line => line.replace("【","")).map(line => line.replace("】","")).map(_.replace(",","")).map(_.replace("，","")).map(_.replace(".","")).map(_.replace("。","")).map(_.replace("(","")).map(_.replace(")","")).map(_.replace("（","")).map(_.replace("）",""))

val words_splits = splits.map(line=>StandardTokenizer.segment(line).toString)

**Comment by qian770903** [comment]
请问是什么原因，怎么解决？

**Comment by hankcs** [comment]
你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真填写，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
