### ISSUE TITLE
句法分析提取关键词，采用多线程，会出现内存溢出

### ISSUE THREAD

**Issue by zero654655902** [hankcs/HanLP#817]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [打钩 ] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：0.1.5
我使用的版本是：0.1.41

## 复现问题

采用pyhanlp
加载了自定义词典， 采用多线程，同时对对句话进行句法分析关键词提取时会出现内存溢出问题
word_array = HanLP.parseDependency(sentence).getWordArray()
jpype._jexception.java.lang.OutOfMemoryErrorPyRaisable: java.lang.OutOfMemoryError: Java heap space

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

```
relations, pos, head, words = get_relations_pos_head(sentence)
```
### 期望输出

```
期望输出
```

### 实际输出

```
实际输出
```

**Comment by hankcs** [comment]
可考虑增大分配给JVM的内存：https://github.com/hankcs/pyhanlp/wiki/%E6%89%8B%E5%8A%A8%E9%85%8D%E7%BD%AE#%E6%89%8B%E5%8A%A8%E9%85%8D%E7%BD%AE

**Comment by zero654655902** [comment]
句法分析提取关键词会占六百多兆的内存， 分词占七十几兆内存，为什么会占这么大的内存

**Comment by hankcs** [comment]
你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真填写，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
