### ISSUE TITLE
计算错误，减号应该修改为加号

### ISSUE THREAD

**Issue by lsm307742191** [hankcs/HanLP#824]
cost[0][j] = transformMatrixDictionary.transititon_probability[pre.ordinal()][cur.ordinal()] - Math.log((item.attribute.frequency[curIndex] + 1e-8) / transformMatrixDictionary.getTotalFrequency(cur));

应该修改为
cost[0][j] = transformMatrixDictionary.transititon_probability[pre.ordinal()][cur.ordinal()] + Math.log((item.attribute.frequency[curIndex] + 1e-8) / transformMatrixDictionary.getTotalFrequency(cur));

**Comment by hankcs** [comment]
你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真填写，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
