### ISSUE TITLE
自定义词典识别失败

### ISSUE THREAD

**Issue by zq019633** [hankcs/HanLP#828]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [钩] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.6.3
我使用的版本是：1.6.3

## 我的问题
自定义词典读取失败

### 步骤

1.首先 ：在custom文件夹下建立了一个新的my.txt 内容的编码格式是utf-8 ，内容是 攻城狮 nz 1024

2.然后：在hanlp.properties中 添加
CustomDictionaryPath=data/dictionary/custom/CustomDictionary.txt; my.txt;现代汉语补充词库.txt; 全国地名大全.txt ns; 人名词典.txt; 机构名词典.txt; 上海地名.txt ns;data/dictionary/person/nrf.txt nrf

3.删除customdictionary.txt.bin     但是并没有生成新的

4.开启识别 读取失败

### 触发代码
HanLP.segment("攻城狮是一个昌平北七家镇平西王府村出");

期望输出
攻城狮应该是一个整体 ，因为我在自定义词典中添加了

实际输出：
以下是我的log
五月 16, 2018 5:02:42 下午 com.hankcs.hanlp.dictionary.CoreDictionary load
信息: 核心词典开始加载:/Users/zhouqiang/eclipse-workspace/hanlp/data/dictionary/CoreNatureDictionary.txt
五月 16, 2018 5:02:42 下午 com.hankcs.hanlp.dictionary.CoreDictionary <clinit>
信息: /Users/zhouqiang/eclipse-workspace/hanlp/data/dictionary/CoreNatureDictionary.txt加载成功，153083个词条，耗时59ms
粗分词网：
0:[ ]
1:[攻, 攻城]
2:[城]
3:[狮]
4:[是]
5:[一个]
6:[个]
7:[昌, 昌平]
8:[平]
9:[北]
10:[七家镇]
11:[家]
12:[镇]
13:[平]
14:[西, 西王]
15:[王, 王府, 王府村]
16:[府]
17:[村]
18:[出]
19:[ ]

五月 16, 2018 5:02:42 下午 com.hankcs.hanlp.dictionary.CoreBiGramTableDictionary <clinit>
信息: 开始加载二元词典/Users/zhouqiang/eclipse-workspace/hanlp/data/dictionary/CoreNatureDictionary.ngram.txt.table
五月 16, 2018 5:02:42 下午 com.hankcs.hanlp.dictionary.CoreBiGramTableDictionary <clinit>
信息: /Users/zhouqiang/eclipse-workspace/hanlp/data/dictionary/CoreNatureDictionary.ngram.txt.table加载成功，耗时130ms
五月 16, 2018 5:02:42 下午 com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
信息: 自定义词典开始加载:/Users/zhouqiang/eclipse-workspace/hanlp/data/dictionary/custom/CustomDictionary.txt
五月 16, 2018 5:02:42 下午 com.hankcs.hanlp.dictionary.CustomDictionary <clinit>
信息: 自定义词典加载成功:391944个词条，耗时384ms
粗分结果[攻城/vi, 狮/ng, 是/vshi, 一个/mq, 昌平/ns, 北七家镇/ns, 平西/nrf, 王府村/ns, 出/vf]
五月 16, 2018 5:02:42 下午 com.hankcs.hanlp.dictionary.nr.PersonDictionary <clinit>
信息: /Users/zhouqiang/eclipse-workspace/hanlp/data/dictionary/person/nr.txt加载成功，耗时33ms
人名角色观察：[  K 1 A 1 ][攻城 L 1 ][狮 D 17 E 5 C 1 ][是 K 2507 L 2504 M 123 C 10 E 1 ][一个 K 90 L 84 ][昌平 Z 41 ][北七家镇 A 20833310 ][平西 A 20833310 ][王府村 A 20833310 ][出 K 168 L 68 C 1 ][  K 1 A 1 ]
人名角色标注：[ /K ,攻城/L ,狮/D ,是/L ,一个/K ,昌平/Z ,北七家镇/A ,平西/A ,王府村/A ,出/K , /K]
五月 16, 2018 5:02:42 下午 com.hankcs.hanlp.dictionary.nr.TranslatedPersonDictionary <clinit>
信息: 音译人名词典/Users/zhouqiang/eclipse-workspace/hanlp/data/dictionary/person/nrf.txt加载成功，耗时26ms

以下打印结果为空
System.out.println("我是"+LexiconUtility.getAttribute("攻城狮"));

**Comment by hankcs** [comment]
```
my.txt;现代汉语补充词库.txt
```
第一个分号后好了空格。

**Comment by hapjin** [comment]
我按着你的 @zq019633 描述自己测试了一下：即把 攻城狮 nz 1024 添加到 my.txt中，然后进行如下调试：
先把 custom 目录下的 缓存bin文件删除。定位到 com.hankcs.hanlp.dictionary.CustomDictionary 的`String path[] = HanLP.Config.CustomDictionaryPath;`一行，看path[]数组中是否包含自定义词典文件my.txt，
my.txt应该正确加载了，因为有如下日志：
>五月 21, 2018 10:26:41 上午 com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
信息: 以默认词性[ns]加载自定义词典E:/idea/hanlp_hapjin/HanLP/data/dictionary/custom/my.txt中……

后面继续跟踪到 使用DAT合并粗分结果 代码(com.hankcs.hanlp.seg.Segment 的 combineByCustomDictionary方法)：
```java
            if (state > 0)
            {
                int to = i + 1;
                int end = to;
                CoreDictionary.Attribute value = dat.output(state);
                for (; to < length; ++to)
                {
                    state = dat.transition(wordNet[to].realWord, state);
                    if (state < 0) break;
                    CoreDictionary.Attribute output = dat.output(state);
                    if (output != null)
                    {
                        value = output;
                        end = to + 1;
                    }
                }
```
却发现“攻城” 、“狮”并没有被合并， `combineWords(wordNet, i, end, value);`没有被调用。我对DAT树的查找原理不是太熟悉，所以不知道具体原因。
![debug](https://user-images.githubusercontent.com/7702860/40289280-fa2045ba-5ce9-11e8-9c04-70781c5bf3d7.png)


于是，**我又把：攻城狮 nz 1024 添加到 CustomDictionary.txt中，结果 攻城狮 能被正确分出来**，因为 `combineWords(wordNet, i, end, value);`被调用了。具体结果如下：
>粗分结果[攻城狮/nz, 是/vshi, 一个/mq, 昌平/ns, 北七家镇/ns, 平西/nrf, 王府村/ns, 出/vf]
人名角色观察：[  K 1 A 1 ][攻城狮 A 20833310 ][是 K 2507 L 2504 M 123 C 10 E 1 ][一个 K 90 L 84 ][昌平 Z 41 ][北七家镇 A 20833310 ][平西 A 20833310 ][王府村 A 20833310 ][出 K 168 L 68 C 1 ][  K 1 A 1 ]
人名角色标注：[ /K ,攻城狮/A ,是/K ,一个/K ,昌平/Z ,北七家镇/A ,平西/A ,王府村/A ,出/K , /K]
[攻城狮/nz, 是/vshi, 一个/mq, 昌平/ns, 北七家镇/ns, 平西/nrf, 王府村/ns, 出/vf]

但是，攻城狮 nz 1024  添加到 my.txt 最终也是添加到 map 中，然后`dat.build(map);`构造DAT树的。所以我也对这个问题很好奇。另外我知道基于词典的统计分词的一些基本原理[#182](https://github.com/hankcs/HanLP/issues/182)：但是好像问题不出在这，貌似是DAT查找的问题？只能等大神解答了。
>新版本希望纠正常年来的误区，词典不等于分词、分词不等于自然语言处理；推荐使用语料而不是词典去修正统计模型。当然，不接受的话可以override这个方法。

**Comment by hankcs** [comment]
这可能是你的编码问题，Windows创建的文本文件默认有BOM。

建议在com/hankcs/hanlp/dictionary/CustomDictionary.java的这个位置下一个断点，看看map里面有没有这个词条（估计没有）。

```
            logger.info("正在构建DoubleArrayTrie……");
            dat.build(map);
            // 缓存成dat文件，下次加载会快很多
            logger.info("正在缓存词典为dat文件……");
```

然后你可以在com.hankcs.hanlp.dictionary.CustomDictionary#load内部下断点，看看my.txt读入进来到底是什么样子。

最简单的解决方法是复制一份CustomDictionary.txt改名为my.txt。

**Comment by zq019633** [comment]
之前的问题解决了， 缓存问题，但是后来 我在my.txt 放入攻城狮 ，识别失败 ，放入其他自定义的词 ，却可以识别出来  ，把攻城狮放入自带的CustomDictionary.txt 里，也可以识别出来，很奇怪

**Comment by hankcs** [comment]
应该就是BOM的问题，BOM跟第一行的词条混淆了。你用notepad++转成无BOM的试试。

**Comment by hapjin** [comment]
确实是BOM的问题 @hankcs。我是win10系统 IDEA2016，直接右击新建文本文档，创建的 my.txt 文件，加入词条：攻城狮 nz 1024 ，然后就将文件-->另存为 -->编码 选择了UTF-8。我用notepad++ 打开my.txt 文件，发现它是带BOM格式编码的。
![hanlp_debug2](https://user-images.githubusercontent.com/7702860/40411148-280f23ba-5ea2-11e8-85b6-56d4d9cd168f.png)
然后我按你说的在com.hankcs.hanlp.dictionary.CustomDictionary#load内部下断点：`map.put(param[0], attribute);`发现读进来的词条是"正常的"：(**被它迷惑了**)
![hanlp_debug](https://user-images.githubusercontent.com/7702860/40411657-965465dc-5ea3-11e8-8aca-e89fab7336b6.png)

分词结果如下：
[攻城/vi, 狮/ng, 是/vshi, 一个/mq, 昌平/ns, 北七家镇/ns, 平西/nrf, 王府村/ns, 出/vf]

以UTF-8无BOM格式编码保存my.txt之后，删除缓存bin 文件，重新运行程序，分词结果就准确了，如下：
[攻城狮/nz, 是/vshi, 一个/mq, 昌平/ns, 北七家镇/ns, 平西/nrf, 王府村/ns, 出/vf]

感谢大神指点。抱歉回复晚了。

**Comment by hankcs** [comment]
的确，这个属于Java的bug：https://stackoverflow.com/questions/4897876/reading-utf-8-bom-marker
已经做了兼容处理。

**Comment by hankcs** [comment]
你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真填写，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。

**Comment by panholly** [comment]
词典只支持txt格式吗？.dic、.entity可以吗？

**Comment by hankcs** [comment]
拓展名无所谓，一定要是纯文本，一定要符合HanLP文档所述的格式要求。
