### ISSUE TITLE
wiki 中word2vec章节提供的维基百科的预训练数据的训练参数

### ISSUE THREAD

**Issue by linuxsong** [hankcs/HanLP#829]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.6.3
我使用的版本是：1.6.3

## 我的问题

请问wiki 中word2vec章节提供的 维基百科的[预训练数据](https://pan.baidu.com/s/1qYFozrY) 的训练参数是什么？

**Comment by hankcs** [comment]
抱歉，时间太长没有保留下来。大概是SG模型，词频阈值选得较大。

**Comment by yaleimeng** [comment]
用维基百科训练词向量，网上教程很多是使用opencc与jiaba做语料简繁转换和分词，试过没有问题。
但我想使用pyHanLP自己的简繁转换和分词（期待处理质量会高一些），却经常遇到无法编码的字符。
UnicodeEncodeError: 'utf-8' codec can't encode character '\ud86d' in position 1200: surrogates not allowed
无中生有冒出一些utf-8字符。经网上搜索，尝试各种办法无解。还是只能放弃此方案。

**Comment by yaleimeng** [comment]
感谢您在百忙之中给予解答，大神辛苦了！ @hankcs 
对hanlp理解已经越来越深了。

**Comment by helenxu** [comment]
你好~ 请问word2vec功能中，是否可以加载基于大语料训练的词向量作为预训练词向量，在自己的小语料上fine tune?大体意思就是在自己的小语料上训练时，将词向量初始化为预训练词向量。

**Comment by hankcs** [comment]
实现上当然没问题，但只有小语料中的词语对应的词向量会得到更新，导致与其他词向量的相对位置发生不同步地改动，使最终效果变差。请参考CS224n讲义：http://www.hankcs.com/nlp/cs224n-word-window-classification-and-neural-networks.html#h3-4

**Comment by helenxu** [comment]
感谢大神的回复~

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
