### ISSUE TITLE
Caused by: java.lang.RuntimeException: java.io.IOException: data/model/perceptron/pku199801/cws.bin 加载失败 

### ISSUE THREAD

**Issue by CoolRandy** [hankcs/HanLP#830]
运行NLPTokenizer.segment的时候报了上述错误，请问一下什么原因

**Comment by hankcs** [comment]
你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真填写，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
