### ISSUE TITLE
繁体简体转换词典问题

### ISSUE THREAD

**Issue by linuxsong** [hankcs/HanLP#835]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.6.4
我使用的版本是：1.6.3

## 我的问题
dictionary/other/CharTable.txt 中有一行
橙=橘

由此产生的问题就是如果开启了Normalization=true （我使用的场景中开启这个参数的主要目的是大小写统一）
“橙子”分词以后会产生的结果是“橘子”，但是这两种水果并不是相同的水果。

另外 dictionary/tc/t2s.txt 中有一个词
橙=橘子
不太确定这个词典的用途是不是繁体到简体的转换对应，如果是的话，感觉不太对，“橙”并不等于简体的“橘子”

### 触发代码
配置文件中加入：Normalization=true

HanLP.segment("橙子")

### 期望输出

橙子

### 实际输出

橘子

**Comment by hankcs** [comment]
感谢反馈，这两个地方的确不合理。欢迎提交代码，谢谢！

**Comment by testliu123** [comment]
还发现t2s.txt中
    第3203行  捲舖蓋=卷舖盖  简体的舖是否是写错了？
    第3319行  插水=假摔  繁体转简体中，这种翻译是否合适？

**Comment by sandove** [comment]
问题类似，在t2s.txt（繁体转简体）文件中
第1968行：大众=福斯
第2031行：奔驰=賓士
第3799行：标致=寶獅
这几个汽车品牌是不是繁体和简体的位置互换一下，左边是繁体，右边是简体。

**Comment by hankcs** [comment]
> 标致=寶獅

感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。

**Comment by 1169458576** [comment]
t2s.txt中
第1134行：先進=雪铁龙
期望的是先进 怎么会变成雪铁龙
还有个问题 繁体的壹不做转换吗？

**Comment by hankcs** [comment]
> t2s.txt中
> 第1134行：先進=雪铁龙
> 期望的是先进 怎么会变成雪铁龙
> 还有个问题 繁体的壹不做转换吗？

感谢反馈，已经修订。
壹不是繁体，壹是大写数字。

**Comment by SemonCat** [comment]
請問一下，如果想要單純的簡轉繁，用語不要變，做得到嗎？

**Comment by lireagan** [comment]
第6224行：菲林=胶卷

这个词典的badcase太多了，应该提供2个接口，1是目前按照语义转换的，2是按照字本身转换的

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
