### ISSUE TITLE
分词结果中名词性语素的词性标识“Ng”同Nature枚举类中的标识“ng"不一致

### ISSUE THREAD

**Issue by wangzhe258369** [hankcs/HanLP#838]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.6.4
我使用的版本是：1.6.3

## 我的问题

使用感知机分词器（`PerceptronLexicalAnalyzer`）的分词结果中，名词性语素的词性标识输出是"Ng"，但是Nature枚举类中对应的是Nature.ng，对应字符串"ng"。这会输出一行警告：
```
五月 23, 2018 5:06:34 下午 com.hankcs.hanlp.corpus.util.CustomNatureUtility <clinit>
警告: 已激活自定义词性功能,由于采用了反射技术,用户需对本地环境的兼容性和稳定性负责!
如果用户代码X.java中有switch(nature)语句,需要调用CustomNatureUtility.registerSwitchClass(X.class)注册X这个类
```

## 复现问题
```
String s = "个人公积金如何办理？";
Segment segment = new PerceptronLexicalAnalyzer();
segment.seg(s);
```

### 期望输出

```
个人/n 公积/n 金/ng 如何/r 办理/v ？/w
```

### 实际输出

```
个人/n 公积/n 金/Ng 如何/r 办理/v ？/w
```

## 其他信息

Nature.ng -> 名词性语素

**Comment by hankcs** [comment]
这个问题我想从语料的角度解决，把语料中的大写全换成小写，而不去改代码。因为从统一的角度讲，名词性语素也算名词，那它就应该以n开头。在北大系的标注集中，大写的词性一般表示古汉语，比如:

```
    /**
     * 甲乙丙丁之类的数词
     */
    Mg,

    /**
     * 古汉语代词性语素
     */
    Rg,
```

而Ng却不符合这个约定。

不过语料库标注集千变万化，Nature枚举+反射的设计已经不合适了，未来JRE可能不让反射。建议使用新的analyze接口，词性是String类型，不存在这个问题了。

**Comment by wangzhe258369** [comment]
@hankcs 好，谢谢！

**Comment by stevenliu158** [comment]
支持这个建议，分词的好坏需要在特定场景下定义，可以从环境语料上想办理处理，如所在地理位置、行业背景、工作环境等等

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
