### ISSUE TITLE
发布的正则化字典CharTable.txt和master分支不一致的问题

### ISSUE THREAD

**Issue by tiandiweizun** [hankcs/HanLP#839]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.6.4
我使用的版本是：1.6.4

## 我的问题
我发现master分支的CharTable.txt和下载的 data-for-1.6.2.zip里面的不一致，希望 data-for-1.6.2.zip能够升级一下，把最新的字典等修改同步一下。

**Comment by hankcs** [comment]
已更新，以后可以自己替换dictionary目录。
