### ISSUE TITLE
关于歧义词典

### ISSUE THREAD

**Issue by pandaHP** [hankcs/HanLP#84]
hankcs，你好，

      我想问下现在的hanlp中分词是否支持歧义词典。例如 “远征求出货”，若按正常分词分成 [远/a, 征求/v, 出货/vi] ，但是我想分成 远征，求， 出货。 问是否有类似功能提。

    谢谢。BTW，看过你网站的about，新生崇拜！
Thanks
pan

**Comment by hankcs** [comment]
你好

并不需要歧义词典这种东西，只需要在data/dictionary/CoreNatureDictionary.ngram.txt中加入“远征@求 1000”就行了。统计模型就用统计的方法解决吧。

**Comment by pandaHP** [comment]
thanks for your answer. 另外你的data for 1.2.7 貌似有600m。 下不下来哦，不知道是什么问题。

**Comment by hankcs** [comment]
请多试几次，或者等我上传微盘。

**Comment by pandaHP** [comment]
我试了两次都停在某一点了。我还是等你上传微盘吧

**Comment by hankcs** [comment]
http://vdisk.weibo.com/s/aVfojIy2aHGO3

过段时间应该就审核好了。

**Comment by pandaHP** [comment]
刚才试过了你说的方法，修改data/dictionary/CoreNatureDictionary.ngram.txt 文件 加入“远征@求 1000” 貌似没什么效果，还是分成了“远”，“征求‘

**Comment by hankcs** [comment]
储存形式

词典有两个形态：文本文件(filename.txt)和缓存文件(filename.txt.bin或filename.txt.trie.dat和filename.txt.trie.value)。

文本文件
采用明文储存，UTF-8编码，CRLF换行符。
缓存文件
就是一些二进制文件，通常在文本文件的文件名后面加上.bin表示。有时候是.trie.dat和.trie.value。后者是历史遗留产物，分别代表trie树的数组和值。
如果你修改了任何词典，只有删除缓存才能生效。

**Comment by pandaHP** [comment]
收到 生效 感谢
