### ISSUE TITLE
使用python调用hanlp进行动态加载词典问题

### ISSUE THREAD

**Issue by AlanConstantine** [hankcs/HanLP#846]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.6.4
我使用的版本是：1.5.3

## 我的问题

在使用python动态加载词典时，报出异常：RuntimeError: No matching overloads found for get in find. at native/common/jp_method.cpp:127

google查了下解决方法：https://stackoverflow.com/questions/7797406/jpype-and-java-util-properties
但依旧没有解决

也许不是hanlp的问题，但实在找不到解决方法了。

### 步骤

1. 首先查看文档，通过python调用hanlp
2. 然后运行
3. 接着……报错了.....

### 触发代码

```
userwords=['java', 'java工程师', '数据挖掘工程师']
startJVM(getDefaultJVMPath(
), "-Djava.class.path=/Users/alanlau/Workplace/MacInstallations/Hanlp/hanlp-1.5.3.jar:/Users/alanlau/Workplace/MacInstallations/Hanlp",
         "-Xms1g", "-Xmx1g")
CustomDictionary = JClass('com.hankcs.hanlp.dictionary.CustomDictionary')
for userword in userwords:
    CustomDictionary.insert(userword, 'nski 10'))   #这一行报错
NLPTokenizer = JClass('com.hankcs.hanlp.tokenizer.NLPTokenizer')
```
### 期望输出

```
暂无期望输出
```

### 实际输出

```
Traceback (most recent call last):
  File "transformat1.py", line 8, in <module>
    from cleaner import slices_text
  File "/Users/alanlau/Workplace/Bello/projlstm/transformat/cleaner.py", line 2, in <module>
    from utils import segtools
  File "/Users/alanlau/Workplace/Bello/projlstm/transformat/utils/segtools.py", line 14, in <module>
    CustomDictionary.insert(userword, 'nski ' + str(len(userword) + 100))
RuntimeError: No matching overloads found for insert in find. at native/common/jp_method.cpp:127
```

## 其他信息

操作系统：MacOS 10.13.4

java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)

Python 3.6.2 (v3.6.2:5fd33b5926, Jul 16 2017, 20:11:06)

**Comment by AlanConstantine** [comment]
已解决，java版本过高不兼容的原因，将java版本将为java version "1.8.0_171"即可

**Comment by yilu1015** [comment]
> 已解决，java版本过高不兼容的原因，将java版本将为java version "1.8.0_171"即可

请问这是在哪里修改？我也遇到了类似问题：
`TypeError: No matching overloads found for com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.seg(float), options are:
	public java.util.List com.hankcs.hanlp.seg.Segment.seg(char[])
	public java.util.List com.hankcs.hanlp.seg.Segment.seg(java.lang.String)

	at findOverload(native/common/jp_method.cpp:242)
	at findOverload(native/common/jp_method.cpp:245)
	at invoke(native/common/jp_method.cpp:253)
	at __call__(native/python/pyjp_method.cpp:142)
`
