### ISSUE TITLE
关键词提取使用其他Tokenizer

### ISSUE THREAD

**Issue by at15** [hankcs/HanLP#85]
现在 TextRankKeyword 的代码里是使用 StandardTokenizer来进行分词的

https://github.com/hankcs/HanLP/blob/master/src/main/java/com/hankcs/hanlp/summary/TextRankKeyword.java#L45

我想问一下

**1. 能不能使用其他Tokenizer 比如  IndexTokenizer 还是因为某些原因只能用StandardTokenizer**, nlp我以前没有接触过...

比如:
````java
public List<String> getKeyword(String content)
    {
        List<Term> termList = IndexTokenizer.segment(content);
        List<String> wordList = new ArrayList<String>();
````
**2. 返回全部的关键词和对应的rank, 现在的实现是从完整的结果的Map里取一部分(当size大或者结果少时是全部), 而且只取了key并没有给rank**

https://github.com/hankcs/HanLP/blob/master/src/main/java/com/hankcs/hanlp/summary/TextRankKeyword.java#L105

比如:
````java
Map<String, Float> sortedScore = new HashMap<String, Float>();
// ... sort score
return sortedScore;
````

**3. 加入新的Term和工具类，在返回分词结果的同时返回部分(全部)term的rank. 因为调用TextRank时也要分一次词。或者允许传入已经分好的词, 第一个参数可以是 List<Term> , 第二个是文本**

比如
````java
// 返回全部分词结果和对应的rank
public Map<String,Float> getTermAndRank(String content);
// 返回部分分词结果和对应的rank
public Map<String,Float> getTermAndRank(String content, Integer size);
// 使用已经分好的词来计算rank
public Map<String,Float> getRank(List<Term> termList, String content);
````

谢谢~

**Comment by hankcs** [comment]
你好，

1、IndexTokenizer是专门面向搜索引擎的分词器，它会导致一个句子中的长词本身分出来并且长词中的短词也分出来。这样一个句子中的词就不是线性的，而是具有包含关系的。这时候就会导致TextRank算法错误地以为文章作者在用很多短词解释长词，从而提高长词的权重。如果你认为这样效果更好，可以增加一个default分词器。

2、这个也可以加进去，如果你已经实现了可以直接发pull request给我。否则我会在有空的时候实现。

3、可以的，同上。

**Comment by hankcs** [comment]
已经实现了，欢迎测试：https://github.com/hankcs/HanLP/commit/915d3ee3de0e17c2747429c30d84437fd6912a79

**Comment by at15** [comment]
@hankcs 好快! (我赶完ddl就来测....
