### ISSUE TITLE
如何利用不同的 CustomDictionary 进行 HanLP.segment()

### ISSUE THREAD

**Issue by wenfeixiang1991** [hankcs/HanLP#859]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.6.4
我使用的版本是：hanlp-1.6.4.jar、hanlp-1.6.4-sources.jar、hanlp.properties、data 版

## 我的问题
假设有两个用户自定义词典，CustomDictionary1.txt 与 CustomDictionary2.txt，如何在 HanLP.segment() 的基础上写一个分词函数，通过传入参数来控制分词的效果？
```
如：
Segment segment = HanLP.newSegment();
Segment segment1 = HanLP.newSegment();

HanLP.Config.Normalization = true;
segment.enableOffset(true);
segment1.enableOffset(true);

int availProcessors = Runtime.getRuntime().availableProcessors();
segment.enableMultithreading(availProcessors);
segment1.enableMultithreading(availProcessors);

组合 segment 与 segment1，并且他们的区别是 CustomDictionary 不同：
一个是 
CustomDictionary.insert("雄安概念产业链", "n 1");
另一个是
 CustomDictionary.insert("雄安", "n 1");
CustomDictionary.insert("概念", "n 1");
CustomDictionary.insert("产业链", "n 1");

但怎么把 CustomDictionary 当成参数传到不同的 segment 中呢？或是说怎么创建不同的 CustomDictionary 从而让 不同的 segment 依赖不同的 CustomDictionary 呢？
```

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

```
    public void testIssue1234() throws Exception
    {
        CustomDictionary.add("用户词语");
        System.out.println(StandardTokenizer.segment("触发问题的句子"));
    }
```
### 期望输出
```
雄安概念产业链 = CombineHanLP(parameter = true, normalization, offset, multithreading)
雄安/概念产/业链 = CombineHanLP(parameter = false, Normalization, offset, multithreading)
```

```
期望输出
```

### 实际输出

```
实际输出
```

**Comment by AnyListen** [comment]
请参考`AhoCorasickDoubleArrayTrieSegmentTest`与`DoubleArrayTrieSegmentTest`的实现
