### ISSUE TITLE
韩正副总理识别出错，总是识别为“正副”

### ISSUE THREAD

**Issue by bugesoft** [hankcs/HanLP#863]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [ X] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：master
我使用的版本是：master

## 我的问题

测试句子：认真落实李克强总理、韩正副总理重要批示指示精神，
总是识别为：韩 正副 总理

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

```
    String text = "认真落实李克强总理、韩正副总理重要批示指示精神，";
    HanLP.newSegment().enableNameRecognize(true)
    CustomDictionary.insert("韩正", "nr 9999")
    System.out.println(HanLP.segment(text));
```
### 期望输出

```
[认真/ad, 落实/v, 李克强/nr, 总理/nnt, 、/w, 韩正/nr, 副/b, 总理/nnt, 重要批示/n, 指示精神/nz, ，/w]
```

### 实际输出

```
[认真/ad, 落实/v, 李克强/nr, 总理/nnt, 、/w, 韩/b, 正副/b, 总理/nnt, 重要批示/n, 指示精神/nz, ，/w]
```

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。
