### ISSUE TITLE
更改 CoreNatureDictionary.txt 且删除所有 bin 文件后，未能生效

### ISSUE THREAD

**Issue by wenfeixiang1991** [hankcs/HanLP#864]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [ x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.6.4
我使用的版本是：hanlp-1.6.4.jar、hanlp-1.6.4-sources.jar、hanlp.properties、data 版

## 我的问题
1. 配置好 1.6.4 非 portable 版后，可以分词且效果正常，但在 CoreNatureDictionary.txt 中按着同等格式加入`大家电 n 1000`后，执行`CoreDictionary.contains("大家电")`结果为`false`。
2. data 文件夹中的 .bin .tr.txt 都删掉了，同样未发现有任何变化，且在`hanlp.properties`中发现，词典地址也没有用到这些如`CoreNatureDictionary.txt.bin`的文件，那么其存在的作用是什么呢？HanLP首页说是为了加速加载词典速度，但没有发现哪里用到这些 .bin 文件里呀？
3. 把 .bin 文件删掉后，重新运行分词程序，.bin 文件就不会再出现了是吗？我这 .bin 文件未再出现。 

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

```
import com.hankcs.hanlp.HanLP;
import com.hankcs.hanlp.dictionary.CoreDictionary;
import com.hankcs.hanlp.dictionary.CustomDictionary;

public class TempTest {
    public static void main(String[] args) {
        System.out.println(CoreDictionary.contains("大家电"));
    }
}

```
### 期望输出

```
期望输出
true
```

### 实际输出

```
实际输出
false
```

**Comment by wenfeixiang1991** [comment]
错误 Issue，可忽略

**Comment by ECNUHP** [comment]
我也想请假这个问题，给词典添加词条后后，删除bin文件仍然无效
