### ISSUE TITLE
请教，如何做自己的词典？

### ISSUE THREAD

**Issue by ngujdi** [hankcs/HanLP#87]
你好！
我打算使用 HanLP 做自己的词典，我仔细认真的阅读了官方文档，谁知文档巧妙的避开了这些内容，所以在这里请教下，怎么使用 HanLP 做自己的词典呢？

  顺颂
教祺

**Comment by hankcs** [comment]
你好
你指的是训练吗？请参考wiki：https://github.com/hankcs/HanLP/wiki/%E8%AE%AD%E7%BB%83%E5%88%86%E8%AF%8D%E6%A8%A1%E5%9E%8B

**Comment by ngujdi** [comment]
谢谢。
