### ISSUE TITLE
关于实体识别方面的数据集

### ISSUE THREAD

**Issue by zxgineng** [hankcs/HanLP#871]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.6.4

我使用的版本是：1.6.4

## 我的问题

感谢分享！
请问您使用的实体识别和角色语义标注的数据集是哪些 个人研究者苦于没有数据可用。
希望能分享您使用的数据，如有后续开发需要可协助一起完成，万分感谢！

**Comment by hankcs** [comment]
Hi，作为开源项目，HanLP尽量使用“开源”的语料库：https://github.com/hankcs/OpenCorpus
欢迎贡献！
