### ISSUE TITLE
HanLP.Config.Normalization = true 时，中文的“、”顿号与“，”逗号都切分成了“,”

### ISSUE THREAD

**Issue by wenfeixiang1991** [hankcs/HanLP#873]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕

## 版本号

当前最新版本号是：1.6.4
我使用的版本是：1.6.4 非portable版

## 我的问题
当 HanLP.Config.Normalization = true 时，默认分词将中文的“、”顿号与“，”逗号切分结果相同。

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

```
   HanLP.Config.Normalization = true;
   System.out.println(HanLP.segment("为什么，号与、号结果一样？"));
   // 输出为：[为什么/ryv, ,/w, 号/q, 与/cc, ,/w, 号/q, 结果/n, 一样/uyy, ?/w]
```
### 期望输出

```
期望输出
```

### 实际输出

```
实际输出
```

**Comment by hankcs** [comment]
你可以通过 https://github.com/hankcs/HanLP/blob/master/data/dictionary/other/CharTable.txt 来控制。

**Comment by wenfeixiang1991** [comment]
Thank you！
