### ISSUE TITLE
关于人名UV拆分优化建议（按格式重提）

### ISSUE THREAD

**Issue by wchnjstar123** [hankcs/HanLP#880]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕

## 版本号

当前最新版本号是：1.6.6
我使用的版本是：1.6.4

## 我的问题

例1：龚学平等表示会保证金云鹏的安全
例2：王中军代表蓝队发言
此两种情况，人名识别错误。

### 触发代码

PersonDictionary的parsePattern函数，在进行拆分时，遗漏词语。
如例1 的语句，"保证金"，当识别出人名金云、金云鹏时，需要将“保证”添加到细分词图中。同理例2中的“军代表”也需要做相应处理。

### 期望输出

```
例1：龚学平等表示会保证金云鹏的安全
[龚学平/nr, 等/udeng, 表示/v, 会/v, 保证/v, 金云鹏/nr, 的/ude1, 安全/an]

例2：王中军代表蓝队发言，分词结果为
[王中军/nr, 代表/nnt, 蓝队/n, 发言/vi]
```

### 实际输出

```
[龚学平/nr, 等/udeng, 表示/v, 会/v, 保证金/n, 云/vg, 鹏/ng, 的/ude1, 安全/an]
[王中/nr, 军代表/nnt, 蓝队/n, 发言/vi]
```

**Comment by AIwem** [comment]
分号词性标注都不对，如下
![wr9rtfdx f_jisbw5t 2c m](https://user-images.githubusercontent.com/32017215/42492385-7e726e64-844b-11e8-8e64-862802fd04a4.png)
而变革者则提出解释理解世界的新方法：凯恩斯在对斯密进行修补；弗洛伊德另辟蹊径；毕加索挑战马蒂斯；爱因斯坦修订牛顿为大自然的立法；德鲁克对组织的研究，和他提出的“知识工人”与受雇阶层。

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。
