### ISSUE TITLE
分号词性标注不准确，期待推出语义角色分析和指代消岐、初步实体和关系抽取等功能

### ISSUE THREAD

**Issue by AIwem** [hankcs/HanLP#882]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：发行版 1.6.6
我使用的版本是：发行版 1.6.6

## 我的问题

分号词性标注不准确，期待推出语义角色和指代消岐等功能

## 复现问题

输入以下句子进行词性标注：
“而变革者则提出解释理解世界的新方法：凯恩斯在对斯密进行修补；弗洛伊德另辟蹊径；毕加索挑战马蒂斯；爱因斯坦修订牛顿为大自然的立法；德鲁克对组织的研究，和他提出的“知识工人”与受雇阶层。”

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

```
       CoNLLSentence sentence =  HanLP.parseDependency(sentence0);

        CoNLLWord[] wordArray = sentence.getWordArray();
```
### 期望输出

正确的词性标注

```
期望输出
```

### 实际输出

```
实际输出
```
1	而	而	c	c	_	4	状中结构	_	_
2	变革者	变革者	n	n	_	4	主谓关系	_	_
3	则	则	d	d	_	4	状中结构	_	_
4	提出	提出	v	v	_	0	核心关系	_	_
5	解释	解释	v	v	_	10	定中关系	_	_
6	理解	理解	v	v	_	10	定中关系	_	_
7	世界	世界	n	n	_	6	动宾关系	_	_
8	的	的	u	u	_	6	右附加关系	_	_
9	新	新	a	a	_	10	定中关系	_	_
10	方法	方法	n	n	_	11	定中关系	_	_
11	：凯	：凯	nh	nr	_	12	定中关系	_	_
12	恩斯	恩斯	nh	nr	_	21	主谓关系	_	_
13	在	在	p	p	_	21	状中结构	_	_
14	对	对	p	p	_	16	状中结构	_	_
15	斯密	斯密	j	j	_	14	介宾关系	_	_
16	进行	进行	v	v	_	18	定中关系	_	_
17	修补	修补	v	vn	_	16	动宾关系	_	_
18	；	；	n	n	_	19	定中关系	_	_
19	弗洛伊德	弗洛伊德	nh	nr	_	13	介宾关系	_	_
20	另	另	d	d	_	21	状中结构	_	_
21	辟	辟	v	v	_	23	定中关系	_	_
22	蹊径	蹊径	n	n	_	21	动宾关系	_	_
23	；	；	v	v	_	25	主谓关系	_	_
24	毕加索	毕加索	Vg	Vg	_	25	主谓关系	_	_
25	挑战	挑战	v	v	_	4	动宾关系	_	_
26	马蒂斯	马蒂斯	nh	nr	_	27	定中关系	_	_
27	；爱因斯坦	；爱因斯坦	ns	ns	_	28	主谓关系	_	_
28	修订	修订	v	v	_	25	动宾关系	_	_
29	牛顿	牛顿	nh	nr	_	30	主谓关系	_	_
30	为	为	v	v	_	34	定中关系	_	_
31	大自然	大自然	n	n	_	30	动宾关系	_	_
32	的	的	u	u	_	30	右附加关系	_	_
33	立法	立法	v	vn	_	34	定中关系	_	_
34	；德鲁克	；德鲁克	n	n	_	38	定中关系	_	_
35	对	对	p	p	_	38	定中关系	_	_
36	组织	组织	v	v	_	38	定中关系	_	_
37	的	的	u	u	_	36	右附加关系	_	_
38	研究	研究	v	vn	_	28	动宾关系	_	_
39	，	，	wp	w	_	28	标点符号	_	_
40	和	和	c	c	_	42	左附加关系	_	_
41	他	他	r	r	_	42	主谓关系	_	_
42	提出	提出	v	v	_	46	定中关系	_	_
43	的	的	u	u	_	42	右附加关系	_	_
44	“	“	wp	w	_	46	标点符号	_	_
45	知识	知识	n	n	_	46	定中关系	_	_
46	工人	工人	n	n	_	28	并列关系	_	_
47	”	”	wp	w	_	46	标点符号	_	_
48	与	与	c	c	_	49	左附加关系	_	_
49	受雇	受雇	v	v	_	46	并列关系	_	_
50	阶层	阶层	n	n	_	49	动宾关系	_	_
51	。	。	wp	w	_	4	标点符号	_	_

而 --(状中结构)--> 提出
变革者 --(主谓关系)--> 提出
则 --(状中结构)--> 提出
提出 --(核心关系)--> ##核心##
解释 --(定中关系)--> 方法
理解 --(定中关系)--> 方法
世界 --(动宾关系)--> 理解
的 --(右附加关系)--> 理解
新 --(定中关系)--> 方法
方法 --(定中关系)--> ：凯
：凯 --(定中关系)--> 恩斯
恩斯 --(主谓关系)--> 辟
在 --(状中结构)--> 辟
对 --(状中结构)--> 进行
斯密 --(介宾关系)--> 对
进行 --(定中关系)--> ；
修补 --(动宾关系)--> 进行
； --(定中关系)--> 弗洛伊德
弗洛伊德 --(介宾关系)--> 在
另 --(状中结构)--> 辟
辟 --(定中关系)--> ；
蹊径 --(动宾关系)--> 辟
； --(主谓关系)--> 挑战
毕加索 --(主谓关系)--> 挑战
挑战 --(动宾关系)--> 提出
马蒂斯 --(定中关系)--> ；爱因斯坦
；爱因斯坦 --(主谓关系)--> 修订
修订 --(动宾关系)--> 挑战
牛顿 --(主谓关系)--> 为
为 --(定中关系)--> ；德鲁克
大自然 --(动宾关系)--> 为
的 --(右附加关系)--> 为
立法 --(定中关系)--> ；德鲁克
；德鲁克 --(定中关系)--> 研究
对 --(定中关系)--> 研究
组织 --(定中关系)--> 研究
的 --(右附加关系)--> 组织
研究 --(动宾关系)--> 修订
， --(标点符号)--> 修订
和 --(左附加关系)--> 提出
他 --(主谓关系)--> 提出
提出 --(定中关系)--> 工人
的 --(右附加关系)--> 提出
“ --(标点符号)--> 工人
知识 --(定中关系)--> 工人
工人 --(并列关系)--> 修订
” --(标点符号)--> 工人
与 --(左附加关系)--> 受雇
受雇 --(并列关系)--> 工人
阶层 --(动宾关系)--> 受雇
。 --(标点符号)--> 提出

## 其他信息

谢谢！！

**Comment by hankcs** [comment]
你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真填写，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
![issue](http://wx1.sinaimg.cn/large/006Fmjmcly1ft2hnlwc22j30q90bcgpe.jpg)

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
