### ISSUE TITLE
识别类似“王寒炮轰张冰冰”结构的句子时结果与预期不同。

### ISSUE THREAD

**Issue by l06066hb** [hankcs/HanLP#884]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.6.6
我使用的版本是：1.6.6

## 我的问题

在对“王寒炮轰张冰冰”的类似的句子分词时，nlp，感知机和crf都会出现不同程度的误差现象。
### 步骤

1. 分别对“王寒炮轰张冰冰”进行nlp,感知机分词和crf分词
2.查看三种方式的分词结果

### 触发代码

```
    public void testIssue1234() throws Exception
    {
       String testContent = "王寒炮轰张冰冰";
       //三种分词的方法为常规代码，暂省略
        nlpTokenizerTest(testContent);
        perceptronTest(testContent);
        crfTest(testContent);
    }
```
### 期望输出

```
期望输出
```
王寒/nr，炮轰/v，张冰冰/nr
### 实际输出

```
实际输出
```
nlp分词结果：[王寒炮轰/nr, 张冰冰/nr]
感知机分词结果：王寒炮轰张冰冰/nr
crf分词结果：[王寒炮/nr, 轰张冰冰/nr]
## 其他信息

![qq 20180711153707](https://user-images.githubusercontent.com/18030444/42557212-724bfa4e-8520-11e8-955d-8bd29747e7e1.png)

**Comment by wchnjstar123** [comment]
个人理解感知机、crf和语料有关。如果使用默认Viterbi分词没有问题。
Segment segment = HanLP.newSegment().enableNameRecognize(true);
List<Term> termList = segment.seg(sentence);
System.out.println(termList);

**Comment by hankcs** [comment]
抛开语料规模谈效果都是错误的。目前默认的感知机与CRF都是98年1月份的语料库（183万字）上训练而来的，Viterbi是2014年全年语料库（1200万字）训练得到的，差别很大。
你们可以对比我在私有语料库（5000万字）上训练的[大模型](http://hanlp.hankcs.com/?sentence=%E7%8E%8B%E5%AF%92%E7%82%AE%E8%BD%B0%E5%BC%A0%E5%86%B0%E5%86%B0)，同样是感知机，效果有云泥之别。
主页文档已经反复强调了：

> 默认模型训练自98年1月份人民日报语料，仅有183万字。语料库规模决定实际效果，面向生产环境的语料库应当在千万字量级。欢迎用户在自己的语料上训练新模型以适应新领域、识别新的命名实体。

我正在建设的OpenCorpus项目也公开了至少2000万字的语料库，还在不断增长。语料库、训练模块都是现成的，无非是自己训练一个大模型而已。

不针对具体人，针对目前项目一部分用户群谈谈我的看法。普通人调调接口就能训练出一个好模型，于是HanLP普及NLP的初衷就达到了一部分。懒人把饼挂在脖子上也懒得转一圈，饿死也是应该的。项目发展至今，我觉得不能一味迎合懒人，毕竟这是面向程序员的项目，不是面向中老年人的手机APP。懂的人会觉得这种机器学习式的设计很灵活很好用，懒人蠢人会觉得HanLP还没有他们唯一能懂的词典分词好用，这就够了。NLP本来就是一个小圈子，太多浮躁的人涌进来对项目、乃至对整个圈子都不好。特别是HanLP 2.0将会迁移到深度学习，到时候这些用户连最简单的线性模型如何训练都没有弄明白，迟早会被时代抛弃的。

**Comment by l06066hb** [comment]
好的  感谢回答

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
