### ISSUE TITLE
请教一个问题，使用CoreStopWordDictionary停用词时，如何保留数字不被停用词删除？

### ISSUE THREAD

**Issue by lg8897203** [hankcs/HanLP#888]
我在使用CoreStopWordDictionary处理停用词，发现文本里的数字都被处理掉了。请问如何保留数字呢？

**Comment by hankcs** [comment]
你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真填写，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
![issue](http://wx1.sinaimg.cn/large/006Fmjmcly1ft2hnlwc22j30q90bcgpe.jpg)
