### ISSUE TITLE
建议文件读写的统一

### ISSUE THREAD

**Issue by chasuner** [hankcs/HanLP#89]
很多地方的文件读写都没有统一使用IOUtil类中的方法，
建议统一一下，
这样放到hadoop集群上运行就只需要统一修改IOUtil就可以了！

**Comment by hankcs** [comment]
是个好意见，最初设计的时候没有考虑这么多。以后会封装类似DataProvider的接口，供hdfs实现。如果你有类似的实现，欢迎pull request。

**Comment by chasuner** [comment]
好的，谢谢！

**Comment by SunnyWiki** [comment]
请问一下，如何将data文件放到hadoop中hdfs中，进行读取啊？
