### ISSUE TITLE
WordNet类的insert方法报错

### ISSUE THREAD

**Issue by sxjsxj1994** [hankcs/HanLP#891]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.6.6
我使用的版本是：1.6.6

## 我的问题

在执行WordNet类的insert方法报Exception in thread "main" java.util.ConcurrentModificationException

## 复现问题
执行Test中的DemoSentimentAnalysis的main方法即可，里面会调用WordNet的insert方法的。

## 其他
其实问题已经解决了，但是修改了源码。错误原因大概就是你一边迭代一边往list中添加数据

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。
