### ISSUE TITLE
词共现统计异常

### ISSUE THREAD

**Issue by potenlife** [hankcs/HanLP#894]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [ x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号
1.6.6

当前最新版本号是：1.6.6
我使用的版本是：1.6.6

## 我的问题
public static void main(String[] args)
    {
        Occurrence occurrence = new Occurrence();
        String co = "共有约300个参展商的近2000辆经典老爷车参展。 "+
"1）上海加速金融业开放，确定六大方面先行先试，比如支持外国银行在沪同时设立分行和子行等。 "+
"2）社科院：预计今年房价平稳回落，一二线城市或探底。 "+
"3）第三届丝博会文化产业与资本创新融合发展分论坛在西安举行。 "+
"4）灵活智能数据驱动 “新零售”引物流行业深度变革。 "+
"5）昨日收盘： "+
"沪指3192.12/+0.57%  "+
"深成指10747.99/+0.72%  "+
"创业板1858.01/+1.48%  "+
"恒指31152.03/-1.23% "+
"1）学生减负获得感未明显提升，人民日报： 不能头痛医头脚痛医脚。 "+
"2）孔子故里曲阜举行传统礼仪活动，传承孝德文化。 "+
"3）全国首个养生马拉松在亳州体育场开跑，2万名选手参加。 "+
"4）女排新赛北仑起航，郎平确认朱婷暂时不会参赛。 "+
"1）北京PM2.5来源本地排放占2/3，区域传输占1/3，本地排放中移动源占比高达45%。北京大兴增44家注册资本过亿元企业。北京市继续实行招生资格学校名单公示制度，371所高中有招生资格。 "+
"2）上海将重塑南京路淮海路，绝代风华华丽转身。上海出口退税申报“免填报”，为企业减少逾2亿项重复录入项目。 "+
"3）深圳核发自动驾驶道路测试牌照，须有驾驶员和安全员。广东—黑龙江“寒来暑往、南来北往”旅游季日前在广州开幕。智慧交通威力初现，广东出行方式出现全方位变化。 "+
"4）湖南：锻造干部硬作风，调研不打招呼不要陪同，扶贫走访直奔基层直插现场。天津市委严肃问责市社会组织管理局不作为慢作为问题，市社管局原局长张宝甫被免职。 "+
"5）陕西搭建文化交流平台，推动“文化陕西”品牌走向世界，河南南阳：连环计骗老人——层层设套，骗老人购买“特效药”。 "+
"6）5月15日20时至16日20时，黑龙江、辽宁东部、华北东部和南部、黄淮大部、江淮北部等地有中到大雨，黑龙江中部、山东西北部和西南部、河南东部、苏皖北部等地的部分地区有暴雨，局地大暴雨 (100～110毫米)，上述地区并伴有短时强降水、雷暴大风等强对流天气。"+ 
"1）皮肤在晚10~11点进入保养状态，长时间熬夜，人的内分泌和神经系统就会失调，使皮肤干燥、弹性差、晦暗无光，出现暗疮、粉刺、黑斑等问题。 "+
"2）普洱茶多为压紧型，第二泡时茶叶往往没有完全展开，所以精华要从第三泡开始，一般三到五泡是普洱茶口感最好的";
        
       // String co = "在计算机音视频和图形图像技术等二维信息算法处理方面目前比较先进的视频处理算法，今天是星期天我很开心，希望下个星期天我依然很开心！";
        occurrence.addAll(co);//**bug出现处**
        occurrence.compute();

        Set<Map.Entry<String, TermFrequency>> uniGram = occurrence.getUniGram();
        for (Map.Entry<String, TermFrequency> entry : uniGram)
        {
            TermFrequency termFrequency = entry.getValue();
            System.out.println(termFrequency);
        }

       /* Set<Map.Entry<String, PairFrequency>> biGram = occurrence.getBiGram();
        for (Map.Entry<String, PairFrequency> entry : biGram)
        {
            PairFrequency pairFrequency = entry.getValue();
            if (pairFrequency.isRight())
                System.out.println(pairFrequency);
        }

        Set<Map.Entry<String, TriaFrequency>> triGram = occurrence.getTriGram();
        for (Map.Entry<String, TriaFrequency> entry : triGram)
        {
            TriaFrequency triaFrequency = entry.getValue();
            if (triaFrequency.isRight())
                System.out.println(triaFrequency);
        }*/
    }

![image](https://user-images.githubusercontent.com/22112317/42936929-25bf8680-8b80-11e8-90d0-dc939f62fb41.png)

## 复现问题
见代码

**Comment by hankcs** [comment]
你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真填写，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
![issue](http://wx1.sinaimg.cn/large/006Fmjmcly1ft2hnlwc22j30q90bcgpe.jpg)
