### ISSUE TITLE
“苹果”拼音问题

### ISSUE THREAD

**Issue by yhan219** [hankcs/HanLP#897]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕

## 版本号

当前最新版本号是： portable-1.6.6
我使用的版本是： portable-1.6.6

## 我的问题

中文 `苹果` 转拼音，期望输出 `pingguo`，但是结果却是 `pinguo`

### 触发代码

```
    System.out.println(HanLP.convertToPinyinString("苹果", " ", true));
```
### 期望输出

```
期望输出
```
pingguo

### 实际输出

```
实际输出
```
pinguo

## 其他信息

试过很多版本都是这样

**Comment by hankcs** [comment]
Hi, 你可以编辑`data/dictionary/pinyin/pinyin.txt`。
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。
