### ISSUE TITLE
在一个工程里面同时使用多份自定义词典

### ISSUE THREAD

**Issue by iceduanxx** [hankcs/HanLP#898]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：4.0.0
我使用的版本是：4.0.0

## 我的问题

能不能在一个工程里面同时使用多份自定义词典，例如我有两个业务场景，场景一需要自定义词典1，场景二需要自定义词典2

**Comment by hankcs** [comment]
你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真填写，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
![issue](http://wx1.sinaimg.cn/large/006Fmjmcly1ft2hnlwc22j30q90bcgpe.jpg)

**Comment by hankcs** [comment]
Hi，目前暂不支持多实例用户词典。
有计划支持。

**Comment by SCismycat** [comment]
@hankcs  请问多实例用户词典现在支持了嘛~

**Comment by hankcs** [comment]
还没有，抱歉有点忙，暂时抽不出时间做。

**Comment by robinWeng0315** [comment]
我实现了一个方案：
改造 CustomDictionary.java
将这个改造一下即可
public static DoubleArrayTrie<CoreDictionary.Attribute> dat
        = new DoubleArrayTrie<>();
===>
public static Map<String, DoubleArrayTrie<CoreDictionary.Attribute>> dict_dat_map
        = new HashMap<String, DoubleArrayTrie<>>();

dict_dat_map:
key为多个词典实例的唯一标识
dat未多个词典实例的数据

然后将reload改成加载多次，填充这个dict_dat_map即可。


使用的时候：
根据传入的自定义词典实例唯一标识，从dict_dat_map选取对应的dat进行分词即可

**Comment by jimichan** [comment]
@iceduanxx mayabot/mynlp是我的一个重构项目，里面支持这个需求，你可以创建多个不同的分词器，指定不一样的用户词典实例。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
