### ISSUE TITLE
修改词性

### ISSUE THREAD

**Issue by lordheart1** [hankcs/HanLP#90]
在一般的地址里 “号” 这个词是很特殊 比如 150号港汇广场 就成了 150号港/ns 了，怎么把"号"改成个名词，希望的结果是 150/m,号/n，港/n这样的就好。

**Comment by hankcs** [comment]
这是地名识别模块带来的问题，你可以从data/dictionary/place/ns.txt中删除
号 B 41 A 10 D 3

**Comment by lordheart1** [comment]
非常感谢。那是不说我把地名识别开关关掉，也可以做到同样效果？

**Comment by hankcs** [comment]
对

**Comment by Tony-Wang** [comment]
奇怪，你们的对话怎么会发到我的邮箱

**Comment by hankcs** [comment]
大概是因为你是issue的owner吧
