### ISSUE TITLE
维特比算法在分词之后关于词性标注的疑问

### ISSUE THREAD

**Issue by fiveddd** [hankcs/HanLP#902]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是： portable-1.6.6
我使用的版本是： portable-1.6.6

## 我的问题

我在使用`维特比`分词的时候，碰到一个很奇怪的现象：再碰到一句话，它能够在粗分词的时候正确识别词性，但是在最后的角色标注的时候，如果分词的结果可以组建为机构名（也就是可以组合为`FD`，`FCCD`这一类的组合），那么最后的结果会被识别为机构。

### 步骤

1. 首先声明一个`维特比分词`模型，强制开启自定义词典，人名识别，机构识别

### 触发代码

```
import com.hankcs.hanlp.HanLP
HanLP.Config.enableDebug()

val segment = HanLP.newSegment().enableCustomDictionaryForcing(true).enableNameRecognize(true).enableAllNamedEntityRecognize(true).
            enableJapaneseNameRecognize(true).enableOrganizationRecognize(true).
            enableTranslatedNameRecognize(true)

println(segment.seg(HanLP.convertToSimplifiedChinese("贾经理全利集团")))

println(segment.seg("贺华平办公室"))
```
### 期望输出

```
[贾经理/nr, 全利集团/nt]
[贺华平/nr, 办公室/nis]
```

### 实际输出

```
粗分词网：
0:[ ]
1:[贾]
2:[经, 经理]
3:[理]
4:[全]
5:[利]
6:[集, 集团]
7:[团]
8:[ ]

粗分结果[贾/nz, 经理/nnt, 全/a, 利/n, 集团/nis]
人名角色观察：[  K 1 A 1 ][贾 B 1308 D 4 E 2 C 1 ][经理 K 205 Z 42 L 5 ][全 B 876 D 406 C 208 E 16 L 16 ][利 D 602 C 560 E 173 B 30 L 5 K 2 ][集团 L 119 K 26 ][  K 1 A 1 ]
人名角色标注：[ /K ,贾/B ,经理/Z ,全/L ,利/B ,集团/L , /A]
识别出人名：贾经理 BZ
地名角色观察：[  S 1163565 ][贾 C 8 ][经理 A 1 B 1 ][全 A 152 C 101 D 16 B 15 ][利 D 91 C 49 A 4 B 4 ][集团 B 38 A 1 ][  B 1322 ]
地名角色标注：[ /S ,贾/C ,经理/A ,全/C ,利/D ,集团/B , /S]
机构名角色观察：[  S 1169907 ][贾经理 F 6781 B 769 A 266 X 6 ][全 B 26 C 17 A 7 ][利 C 45 A 9 B 3 D 3 ][集团 K 1000 D 1000 ][  B 8423 ]
机构名角色标注：[ /S ,贾经理/F ,全/C ,利/C ,集团/D , /S]
识别出机构名：贾经理全利集团 FCCD
识别出机构名：利集团 CD
识别出机构名：全利集团 CCD
细分词网：
0:[ ]
1:[贾经理, 贾经理全利集团]
2:[经]
3:[理]
4:[全, 全利集团]
5:[利, 利集团]
6:[集团]
7:[]
8:[ ]

[贾经理全利集团/nt]


粗分词网：
0:[ ]
1:[贺]
2:[华]
3:[平]
4:[办, 办公, 办公室]
5:[公, 公室]
6:[室]
7:[ ]

粗分结果[贺/vg, 华/b, 平/v, 办/v, 公室/nz]
人名角色观察：[  K 1 A 1 ][贺 B 1011 E 78 C 70 D 25 ][华 D 4763 B 1296 C 966 E 595 L 1 ][平 D 6844 E 544 C 189 B 36 L 11 ][办 L 4 K 2 ][公室 A 20833310 ][  K 1 A 1 ]
人名角色标注：[ /K ,贺/B ,华/C ,平/D ,办/L ,公室/A , /A]
识别出人名：贺华 BC
识别出人名：贺华平 BCD
地名角色观察：[  S 1163565 ][贺 C 41 D 4 ][华 C 385 D 196 B 22 A 8 E 1 ][平 D 1039 C 241 A 16 B 13 ][办 B 23 A 3 ][公室 Z 20211628 ][  B 1322 ]
地名角色标注：[ /S ,贺/C ,华/D ,平/B ,办/A ,公室/Z , /S]
机构名角色观察：[  S 1169907 ][贺华平 F 6781 B 769 A 266 X 6 ][办 D 213 C 11 A 2 B 2 ][公室 Z 19892007 ][  B 8423 ]
机构名角色标注：[ /S ,贺华平/F ,办/D ,公室/Z , /S]
识别出机构名：贺华平办 FD
细分词网：
0:[ ]
1:[贺华平, 贺华平办]
2:[]
3:[]
4:[办]
5:[公室]
6:[室]
7:[ ]

[贺华平办/nt, 公室/nz]
```

## 其他信息

1. 我尝试修改过`CoreNatureDictionary.txt`和`CoreNatureDictionary.ngram.txt`（根据[issue813](https://github.com/hankcs/HanLP/issues/813#issuecomment-385966927)），比如针对`贺华平办公室`这一句话，我分别将`贺华平 nr 10000`和`贺华平@办公室 10000`加入到两个文件中，结果并没有改变，请问这种时候应该怎么修改？

2. 我同时使用了感知机去分词，不存在上面说的问题，但是由于目前很想搞明白为什么会出现上面的结果。

3. 非常期待并且感谢你的回复。

**Comment by hankcs** [comment]
1. 对于`贾经理全利集团`，你可以删除FCCD这个模式串，或者将这些bad case会以“单词 Z 1”的形式加入词典`data/dictionary/organization/nt.txt`中
1. 对于`贺华平办公室`，我没有复现你的问题：

```java
        Segment segment = new DijkstraSegment().enableOrganizationRecognize(true);
        System.out.println(segment.seg(
                "贺华平办公室"
        ));
// [贺华平办公室/nt]
```

你可能改了什么东西，或者在某个质量很低的语料库上训练了模型，因为你的粗分结果已经出错了“[贺/vg, 华/b, 平/v, 办/v, 公室/nz]”。你应该查找你的`CoreNatureDictionary.ngram.txt`有没有`办@公室`这样的bigram，有的话删掉。

这套层叠隐马模型是一套老态龙钟的模型（90年代发明），它有着HMM故有的弱点：

- 无法召回OOV
- 模型太简单，消歧能力差

在新增了感知机与CRF词法分析器后，建议用户用大型语料库（https://github.com/hankcs/OpenCorpus ）结合用户自己标注的领域语料训练效果更好的模型。未来HanLP将切换到深度学习框架，那时候神经网络模型的训练将成为常态，这些线性模型又要被淘汰了。
所以我的建议是大家紧跟时代潮流，尽快适应语料标注+模型训练的模式，不要被时代抛弃了两个世代。

**Comment by wchnjstar123** [comment]
@hankcs “未来HanLP将切换到深度学习框架”，期待！！！

**Comment by fiveddd** [comment]
谢谢hankcs，期待新的框架！
