### ISSUE TITLE
提取新词的几点疑问

### ISSUE THREAD

**Issue by LoserMr** [hankcs/HanLP#905]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：master
我使用的版本是：master

1.在com.hankcs.hanlp.mining.word.WordInfo.computeProbabilityEntropy()计算左右熵的时候,如果该词位于首或者尾部时取最小值 这样取出的熵值为0,当设置默认熵值,开头结尾的词将无法取出
2.互信息
代码中给出的算法
![1](https://user-images.githubusercontent.com/36916036/43451100-c14b4b42-94e6-11e8-923a-912d6e534bd0.png)

![12379570-7c7355505813d673](https://user-images.githubusercontent.com/36916036/43620279-765a49ce-9704-11e8-80fa-7515e1a37ab4.png)
不是完全一致

**Comment by hankcs** [comment]
1. 位于首尾的片段的左右熵不一定是0，虽然它们的左右邻接字分别为`\0`，但如果该片段在字符串其他位置出现的话，它们的邻接字依然会很丰富。
1. 互信息的基本计算公式与上式相同，但一个片段可以拆分为多个x和y的组合。选择哪种组合的互信息存在许多种方法，有的学者认为应该求和，但[matrix67](http://www.matrix67.com/blog/archives/5044)的做法是取最小：

>    当然，作为一个无知识库的抽词程序，我们并不知道“电影院”是“电影”加“院”得来的，也并不知道“的电影”是“的”加上“电影”得来的。错误的切分方法会过高地估计该片段的凝合程度。如果我们把“电影院”看作是“电”加“影院”所得，由此得到的凝合程度会更高一些。因此，为了算出一个文本片段的凝合程度，我们需要枚举它的凝合方式——这个文本片段是由哪两部分组合而来的。令 p(x) 为文本片段 x 在整个语料中出现的概率，那么我们定义“电影院”的凝合程度就是 p(电影院) 与 p(电) · p(影院) 比值和 p(电影院) 与 p(电影) · p(院) 的比值中的较小值，“的电影”的凝合程度则是 p(的电影) 分别除以 p(的) · p(电影) 和 p(的电) · p(影) 所得的商的较小值。

我曾经比较过两种方法，发现后者的效果（top 100的结果肉眼观察）的确要好一些。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。

**Comment by bigbrother001** [comment]
> ## 注意事项
> 请确认下列注意事项：
> 
> * 我已仔细阅读下列文档，都没有找到答案：
>   
>   * [首页文档](https://github.com/hankcs/HanLP)
>   * [wiki](https://github.com/hankcs/HanLP/wiki)
>   * [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
> * 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
> * 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
> * [x]  我在此括号内输入x打钩，代表上述事项确认完毕。
> 
> ## 版本号
> 当前最新版本号是：master 我使用的版本是：master
> 
> 1.在com.hankcs.hanlp.mining.word.WordInfo.computeProbabilityEntropy()计算左右熵的时候,如果该词位于首或者尾部时取最小值 这样取出的熵值为0,当设置默认熵值,开头结尾的词将无法取出 2.互信息 代码中给出的算法 ![1](https://user-images.githubusercontent.com/36916036/43451100-c14b4b42-94e6-11e8-923a-912d6e534bd0.png)
> 
> ![12379570-7c7355505813d673](https://user-images.githubusercontent.com/36916036/43620279-765a49ce-9704-11e8-80fa-7515e1a37ab4.png) 不是完全一致

请问这段代码是在哪个文件中找到的？我在下载的项目中找不到这个部分。另外请教一下，新词发现的代码是用java实现的还是用python实现的？
