### ISSUE TITLE
语义距离模块计算方法

### ISSUE THREAD

**Issue by houzw** [hankcs/HanLP#91]
请问一下语义距离计算方法，具体原理是什么呢？有具体参考文献么？O(∩_∩)O谢谢

**Comment by hankcs** [comment]
这块没有论文，是自己设计的一个朴素的方案，根据同义词词林的类目计算词语相似度。
以后可能会试验word2vec，比较得出更好的方案。

**Comment by iou2much** [comment]
> 这块没有论文，是自己设计的一个朴素的方案，根据同义词词林的类目计算词语相似度。
> 以后可能会试验word2vec，比较得出更好的方案。

请问后续有用新的方法吗？
