### ISSUE TITLE
portable-1.6.7版本中使用maven构建的情况下，执行NLPTokenizer.analyze分析时，报如下错误

### ISSUE THREAD

**Issue by luoxianjiao** [hankcs/HanLP#916]
警告: 打开失败：data/model/perceptron/msra/cws.bin
Exception in thread "main" java.lang.ExceptionInInitializerError
	at HanLPTest.main(HanLPTest.java:18)
Caused by: java.lang.RuntimeException: java.io.IOException: data/model/perceptron/msra/cws.bin 加载失败
Maven构建的情况下，不是不需要额外手动导入data吗？

**Comment by hankcs** [comment]
你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真填写，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
![issue](http://wx1.sinaimg.cn/large/006Fmjmcly1ft2hnlwc22j30q90bcgpe.jpg)

**Comment by hankcs** [comment]
portable版只含有少量数据（dictionary），不含
Model。要用模型的话，你仍然需要下载
data。
