### ISSUE TITLE
无法在代码中配置数据目录，能否添加setProperty的方式在代码中自由使用

### ISSUE THREAD

**Issue by followyourheart** [hankcs/HanLP#92]
作为Lib，直接调用jar，进行分词时，无法像你说的那样用配置文件配置data的目录，导致类似如下问题发生：

ERROR HanLP: HMM分词模型[ data/model/segment/HMMSegmentModel.bin ]不存在

看到HanLP里有一段
public static final class Config 写死了词典和模型数据的地址，尽管有一个root通过配置文件实现了设置，但是还不方便，能否加一个类似setProperty的方式，在代码中自由使用？

谢谢。

PS: 我用的scala

**Comment by hankcs** [comment]
0. 不可能存在“无法像你说的那样用配置文件配置data的目录”，如果你坚持这么认为，请给出详细的环境说明。
0. 没有写死，除了root，所有配置都是活的。
0. 并不需要setProperty，properties仅仅用做将配置读入内存。如果你喜欢硬编码，你可以这么写：

HanLP.Config.HMMSegmentModelPath = "绝对路径";

**Comment by hankcs** [comment]
如果问题依然没有得到解决，欢迎继续讨论。

**Comment by YangliAtGitHub** [comment]
java.lang.System.getProperties().setProperty()的方法可以解决C# 访问HanLP的情况。目前没有发现任何问题。

**Comment by followyourheart** [comment]
@hankcs 很抱歉，因为我代码里使用方式写错了，调了很久没设置成功，以为无法修改。现在改过来。谢谢。
