### ISSUE TITLE
在自定义词典的情况下，索引分词全切分模式达不到预期的效果

### ISSUE THREAD

**Issue by liujiabin1008** [hankcs/HanLP#922]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：hanlp-portable-1.6.7
我使用的版本是：hanlp-portable-1.6.0

## 我的问题
在使用HanLP分词时，自定义词典中已经添加了“南保村”、“保村”、“南保”词条，但是对“南保村民委员会”的分词结果中没有“南保村”和“保村”，分词结果不准确；对比使用IK分词时，使用相同内容的自定义词典，“南保村民委员会”的分词结果中含有“南保村”、“保村”、“南保”。

## 复现问题

1.HanLP分词结果如下
![hanlp](https://user-images.githubusercontent.com/42425179/44185683-8cb19b80-a147-11e8-8999-67728033cbdb.png)

2.IK使用同样的自定义词典内容，分词结果为： “南保村”，“南保”，“保村”，“村民委员会”，“村民”，“民委”，“委员会”
![ik](https://user-images.githubusercontent.com/42425179/44185677-815e7000-a147-11e8-984a-03b885cee745.png)

### 步骤

1. 首先设置自定义词典
2. 然后设置schema.xml中的fieldType节点
![image](https://user-images.githubusercontent.com/42425179/44185966-3a717a00-a149-11e8-8b91-ad9413f1da8b.png)
![image](https://user-images.githubusercontent.com/42425179/44185984-4f4e0d80-a149-11e8-9c9c-ad8f39b98541.png)

3. 接着对“南保村民委员会”进行分词

### 触发代码

```
    public void testIssue1234() throws Exception
    {
        CustomDictionary.add("保村");
        CustomDictionary.add("南保村");
        CustomDictionary.add("南保");
        System.out.println(IndexTokenizer.segment("南保村民委员会"));
    }
```
### 期望输出

```
期望输出 “南保村”，“南保”，“保村”，“村民委员会”，“村民”，“民委”，“委员”，“委员会”
```

### 实际输出

```
实际输出 “南保”，“村民委员会”，“村民”，“民委”，“委员”，“委员会”
```

**Comment by hankcs** [comment]
感谢反馈，这是两种思维的冲突。对于`南保村民委员会`这句话，

- 相较于`南保村|民|委员会|委员`，NLPer绝对会认为`南保|村民|委员会|委员`才是正确的切分，这也是HanLP的输出结果。该结果避免了错误碎片“民”，当然也就不含“南保村”。
- 部分搜索工程师不关心切分是否正确，你们更加希望结果中包含所有完整的语义单元，特别是词典中已有的单元。你们不关心搜索“和服”出现“商品和服务”，也不关心搜索“川普”出现“四川普通话”，所以你们总觉得像IK这种词典分词才好用。

HanLP则一直试图提供又准又全的索引分词结果，对于你提供的案例，可以这样配置：

```
        Segment segment = HanLP.newSegment().enableIndexMode(true).enableCustomDictionaryForcing(true);
        CustomDictionary.insert("南保村");
        CustomDictionary.insert("南保");
        System.out.println(segment.seg("南保村民委员会"));
```

输出：

```
[南保村/nz, 南保/nz, 民/ng, 委员会/nis, 委员/nnt]
```

由于高优先级词典的影响，上述结果其实是错误的。
你还可以将`南保村民委员会`加入词典中，而不开启高优先级，此时的结果是

```
        Segment segment = HanLP.newSegment().enableIndexMode(true);
        CustomDictionary.insert("南保村民委员会");
        CustomDictionary.insert("南保村");
        CustomDictionary.insert("南保");
        System.out.println(segment.seg("南保村民委员会"));
// [南保村民委员会/nz, 南保村/nz, 南保/nz, 村民/n, 民委/nnt, 委员会/nis, 委员/nnt]
```

**Comment by liujiabin1008** [comment]
谢谢 @hankcs
