### ISSUE TITLE
去除停用词，提取有用的关键词

### ISSUE THREAD

**Issue by xuhaifeng017** [hankcs/HanLP#923]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：hanlp-1.6.7.jar
我使用的版本是：hanlp-1.6.7.jar

## 我的问题
我的问题在于提取的关键词会有一些不需要的词
比如：我根据一个电器公司的简介和经营产品，那么提取的关键词个人感觉应该都跟电器相关的
但是会有几个不重要的词会提取出来，请问怎么解决，有什么意见，请告诉我，谢谢大佬。

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码
![image](https://user-images.githubusercontent.com/32606897/44244108-d7ddb400-a204-11e8-8ebd-f6893840cd47.png)
```
  private static List getKeyWordRank(String path) throws IOException {
        String t1 = new String();
        BufferedReader reader = new BufferedReader(new InputStreamReader(new FileInputStream(path), "utf-8"));
        String str;
        while ((str = reader.readLine()) != null) {
            t1 += str;
        }
        List<String> list = HanLP.extractKeyword(t1, 10);
        for (String item:list) {
            System.out.println(item);
        }
        return list;
    }


```
### 期望输出

```
期望输出  [电视, 电脑, 电器, 空调, 电冰箱, 电子, 微波炉, 吸尘器, 消毒柜, 厨房]
```

### 实际输出

```
实际输出 [电视, 电脑, 电器, 空调, 海尔, 电子, 网点, 营业额, 白电, 厨房]
```

**Comment by hankcs** [comment]
你可以对提取结果再进行一遍过滤。

**Comment by xuhaifeng017** [comment]
@hankcs 对提取的结果进行过滤，那么停用词文本是不是需要自己定义。

**Comment by xuhaifeng017** [comment]
@hankcs 
![image](https://user-images.githubusercontent.com/32606897/44318020-af54f480-a466-11e8-976c-0d255a9cc6d4.png)
最近因为项目才接触，很头疼

**Comment by xuhaifeng017** [comment]
@yaleimeng谢谢你的指导，主要我得计算企业跟政策的关系度数

**Comment by himozhang** [comment]
@yaleimeng 

> 你没有理解篇章关键词提取的原理和常见方法，所以你理解的关键，跟别人理解的关键是不同的。
> 你的需求不只是提取关键词，而是要提取特定（领域）类型的词。需要自己弄一个分类器，把关键词串送进去，分为感兴趣的+不感兴趣的两组。

请问一下关于分类器的构建，有相关资料可以推荐吗？谢谢。

**Comment by yaleimeng** [comment]
分类问题是机器学习领域的一种基本问题。相关图书有《机器学习》《统计学习方法》等，网上文章也比较多。
就这个问题而言，不想搞太复杂的话，弄个领域词表就能解决。跨领域的词还是比较少的。

**Comment by AnyListen** [comment]
@himozhang 请参考 wiki ：https://github.com/hankcs/HanLP/wiki/%E6%96%87%E6%9C%AC%E5%88%86%E7%B1%BB%E4%B8%8E%E6%83%85%E6%84%9F%E5%88%86%E6%9E%90

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
