### ISSUE TITLE
CRFNERecognizer用pku1998年1-6月份数据训练，java.lang.OutOfMemoryError：GC overhead limit exceeded

### ISSUE THREAD

**Issue by SmileFangfang** [hankcs/HanLP#925]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：v1.6.7
我使用的版本是：v1.6.7

## 我的问题
CRFNERecognizer用pku1998年1-6月份数据(64.6M)训练内存溢出:java.lang.OutOfMemoryError：GC overhead limit exceeded

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

```
    public static void main(String[] args) throws IOException {
	String CORPUS = "data/test/pku98/1998-2.txt";
	String NER_MODEL_PATH = "data/model/crf/pku1998-2/ner.txt";
	CRFTagger tagger = new CRFNERecognizer(null);
        tagger.train(CORPUS, NER_MODEL_PATH);
	}
```
### 期望输出

```
期望输出
```

### 实际输出

```
实际输出
```

**Comment by hankcs** [comment]
1. 内存占用大是Java语言的通病，除非32G以上的服务器，否则不要用Java跑训练。
1. 控制台打印了相应的傻瓜CRF++命令，用C++训练，速度还更快。
1. 64MB的语料看起来小，提取的特征很多。

**Comment by hankcs** [comment]
不是内存原因，训练已经进行了408个迭代，内存基本稳定。连续三次迭代diff小于0.0001，程序已经进入了模型保存阶段。应该是CRF++的保存代码有bug，请

- 确认模型保存路径存在，并且有写权限。
- 再运行一次。
- 换一个版本的CRF++。

**Comment by SmileFangfang** [comment]
用6个月的数据训练完后，实体抽取的结果没有改善，是分析模型、POS模型的影响吗？这里是不是也需要重新训练这两个模型？还是说6个月的训练数据和1个月的训练数据相比，训练结果其实相差不大？

**Comment by hankcs** [comment]
不知道你所说“实体抽取的结果没有改善”的评判标准是怎么样的？

- 如果指的是F1准确率的话，你可以预留少量语料（10%）作为测试集，分别用50%和90%的语料训练模型，然后用`com.hankcs.hanlp.model.perceptron.utility.UtilityTest#testEvaluateNER`所示代码计算准确率，两者应该差别非常大。
- 如果你只是凭感觉，期望模型能够识别出你家楼下的`便利蜂/nt``如家/nt`的话，那是永远也不可能的。因为98年人民日报语料库中不可能有类似`便利鸟/nt``全家/nt`这样的词汇。毕竟是老旧的官话报纸，里面的机构名非常规范，所属的行业非常有限（不可能识别`特斯拉智能驾驶公司`，“智能驾驶”从未出现在语料库任何一个NER中，也就是说几乎100%的特征都支持“智能驾驶”不是NER的一部分）。另外，NER只负责识别复合词命名实体，非复合词的NER是交给CWS确定边界，POS确定类别的。许多论文把简单词也计入成绩，预测时用到的词语和POS标签又取自gold data，所以准确率虚高。
- 如果你对自己训练模型的方法是否正确存疑，可以对比 http://hanlp.hankcs.com/ ，线上用的也是98年6个月的语料库，只不过是感知机模型。
- 正如[层叠HMM-Viterbi角色标注模型下的机构名识别](http://www.hankcs.com/nlp/ner/place-name-recognition-model-of-the-stacked-hmm-viterbi-role-labeling.html)文末用外部语料增强模型一样，光靠那点人民日报语料是不可能解决NER问题，还需要很多行业语料。如果行业语料匮乏，退而求其次可以考虑用机器生成语料。

**Comment by SmileFangfang** [comment]
用不同规模的语料训练，结果相别的确非常大，谢谢。
pku199801作为测试数据，
pku199802作为训练数据训练感知机模型，测试结果：
 NER	     P	     R	    F1
avg.	 62.75	 18.67	 28.78
  ns	 30.14	  2.10	  3.93
  nt	 63.67	 20.87	 31.44
pku199802-pku199806作为训练数据训练感知机模型，测试结果：
 NER	     P	     R	    F1
avg.	 86.90	 77.17	 81.74
  ns	 65.34	 65.97	 65.65
  nt	 90.22	 78.65	 84.04

**Comment by hankcs** [comment]
nr 是非复合词，“NER只负责识别复合词命名实体，非复合词的NER是交给CWS确定边界，POS确定类别的。许多论文把简单词也计入成绩，预测时用到的词语和POS标签又取自gold data，所以准确率虚高。”

你需要多看文档，文档说了不兼容二进制，你肯定把bin当txt传进去了。

**Comment by zzypeak** [comment]
您好，OpenCorpus/pku98/199801.txt这个链接打不开，可否再上传个，多谢哈

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
