### ISSUE TITLE
android studio 始终提示“没有找到hanlp.properties”

### ISSUE THREAD

**Issue by cutesariki** [hankcs/HanLP#926]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [ ] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：
我使用的版本是：

## 我的问题

根据提示文档一步一步操作，可在使用时总是提示

【08-17 23:56:18.098 24086-24086/? E/HanLP: 没有找到hanlp.properties，可能会导致找不到data
    ========Tips========
    请将hanlp.properties放在下列目录：
    Web项目则请放到下列目录：
    Webapp/WEB-INF/lib
    Webapp/WEB-INF/classes
    Appserver/lib
    JRE/lib
    并且编辑root=PARENT/path/to/your/data
    现在HanLP将尝试从null读取data……
08-17 23:56:18.101 24086-24086/? W/HanLP: 读取data/dictionary/CoreNatureDictionary.txt.bin时发生异常java.io.FileNotFoundException: data/dictionary/CoreNatureDictionary.txt.bin (No such file or directory)
    核心词典data/dictionary/CoreNatureDictionary.txt不存在！java.io.FileNotFoundException: data/dictionary/CoreNatureDictionary.txt (No such file or directory)
08-17 23:56:18.102 24086-24086/? E/HanLP: 核心词典data/dictionary/CoreNatureDictionary.txt加载失败
08-17 23:56:18.104 24086-24086/? I/zygote64: System.exit called, status: -1
08-17 23:56:18.104 24086-24086/? I/AndroidRuntime: VM exiting with result code -1, cleanup skipped.】

hanlp.properties的root路径是改好了的

我是使用的android studio进行代码编写的，想问问这个路径总是找不到是因为我的某个环境没有配好还是什么情况，望答复

**Comment by hankcs** [comment]
你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真填写，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
![issue](http://wx1.sinaimg.cn/large/006Fmjmcly1ft2hnlwc22j30q90bcgpe.jpg)
