### ISSUE TITLE
portable 版提示【没有找到hanlp.properties，可能会导致找不到data】

### ISSUE THREAD

**Issue by jiangzeyin** [hankcs/HanLP#929]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：portable-1.6.7
我使用的版本是：portable-1.6.7

## 我的问题

        <dependency>
            <groupId>com.hankcs</groupId>
            <artifactId>hanlp</artifactId>
            <version>portable-1.6.7</version>
        </dependency>

我使用maven 的portable版  在使用HanLp 时还说提示需要指定数据目录，portable 版不是内置了data吗？ 还是现在需要单独配置或者这个提示可以忽略

![qq 20180822090353](https://user-images.githubusercontent.com/16408873/44436934-4f875680-a5ea-11e8-9358-eb06a2c30072.png)

## 其他信息

看到有个类似问题，但是他是打包，我这个直接使用maven 不需要打包吧

[https://github.com/hankcs/HanLP/issues/226](url)

**Comment by hankcs** [comment]
感谢反馈，有次merge master的时候覆盖了，不应该输出警告，忽略即可。现在1.6.8已经修复了这个问题。
