### ISSUE TITLE
CustomDirectionaryPath中存在的bug

### ISSUE THREAD

**Issue by Mev-z** [hankcs/HanLP#93]
hi，hankcs:
     我现在使用的是1.2.7版本的HanLP，当我在增加一个自定义的词典的时候发现一个bug。我直接在行尾添加" 追加名词.txt;"，结果在加载的时候定位到了data/dictionary/person/追加名词.txt。然后发现在/hanlp/HanLP.java中的201行到209行的实现中，值"data/dictionary/person/nrf.txt nrf"将行首获得的路径更改了（data/dictionary/custom/），这样就带来了一个问题，虽然这样可以在custom中调用其它路径下的词典（非data/dictionary/custom/下），但是会直接更改之后的词典的默认路径。
    我觉得可以强制只使用“data/dictionary/custom/”即第一个值的目录路径，或者在文档中注明custom词典添加格式（修改默认路径时";"之后不能有空格，且之后的词典默认路径为此路径。添加默认路径下的词典时，";"之后要有空格）。
    由于第二种方式不用改代码，所以先讨论下，再看看要不要来个Pull request。
   然后为什么不在项目中放上hanlp.properties呢，我找了好久没找到:)

**Comment by hankcs** [comment]
你好，感谢你的意见
0. 这不是bug，这是预设的功能。
0. 假如多个目录下有多个词典，该功能非常方便。既然你放到custom目录下，你为什么不写在custom的后面？
0. 如果你了解GDI中的画笔、CSS或JS中的父子属性，你会理解这其实是一种状态机机制，就跟Linux的cd一样。
0. 首页文档中已经说的很清楚了https://github.com/hankcs/HanLP#3配置文件 ，我不明白为什么找不到。
0. 配置因人而异，当然不能放到源码里。

**Comment by intohole** [comment]
大神， 我真的想问下 ， 你会高级算法又会码代码。。。人生不要太犀利啊~膜拜

在 2015年12月4日 下午6:44，hankcs <notifications@github.com>写道：

**Comment by hankcs** [comment]
你好，我不是大神，谋生而已。

**Comment by Mev-z** [comment]
谢谢解答，原来是状态机机制，说明文档没有看太明白，受教了

**Comment by intohole** [comment]
你现在在哪个公司啊。。。我也想去谋生 。。。 收了我吧

2015-12-05 23:07 GMT+08:00 hankcs <notifications@github.com>:
