### ISSUE TITLE
批量繁体转简体时碰到的问题

### ISSUE THREAD

**Issue by testliu123** [hankcs/HanLP#930]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕

## 版本号

当前最新版本号是：1.6.7
我使用的版本是：1.6.7

## 我的问题

当我尝试将一批词语（简体词和繁体词都有）转换为简体时发现【战列舰】一词转换异常

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码
    public static void main(String[] args) throws Exception
    {
               String str="战列舰";
		System.out.println(HanLP.t2s(str));
		System.out.println(HanLP.convertToSimplifiedChinese(str));
    }
### 期望输出

```
期望输出
```
战列舰
### 实际输出

```
实际输出
```
主力艦

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。
