### ISSUE TITLE
命令行训练Word2Vec模型时，如何开启debug输出训练进度？

### ISSUE THREAD

**Issue by starpipi** [hankcs/HanLP#934]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.6.7
我使用的版本是：1.6.7

## 我的问题

在训练Word2Vec模型时发现命令行训练的时候除了开始的thread和iter，没有其他输出，查看源码发现训练中是使用的logger输出进度信息。
通过代码训练可以注册callback获取训练进度，请问命令行方式执行如何打开debug输出logger以查看进度？

**Comment by hankcs** [comment]
没有，用的是`System.err.printf`：

```
                            System.err.printf("%cAlpha: %f  iter: %d  Progress: %.2f%%  Words/thread/sec: %.2fk", 13, alpha, local_iter,
                                              percent * 100,
                                              wordCountActual / (float) (cost_time));
```

运行后控制台输出：

```
java -cp target/hanlp-portable-1.6.8.jar com.hankcs.hanlp.mining.word2vec.Train -input data/test/cws/msra.train.txt -output msr.txt
Starting training using text file data/test/cws/msra.train.txt
threads = 8, iter = 5
93.41% 1200K
Alpha: 0.017600  iter: 4  Progress: 30.92%  Words/thread/sec: 140.83k  ETD: 29 s 
```

请检查你是否将stderr重定向了。

**Comment by starpipi** [comment]
感谢回复，我这边确实是只重定向了普通输出流没重定向错误输出流。
但是查看master上的代码，Train中是使用的Word2VecTraining的trainModel()训练的，里面是使用的logger。是否我看错位置了。

另外，询问这个问题的原因是使用wiki的dump分词后训练超过72小时都没结束，切词完以后语料只有1G。发现没有文档中的输出进度的问题。
后来反复检查发现，当时这次训练的分词语料并没有输出换行符，导致所有词语全在一行内。重新导出分词输入语料加入换行符以后，2小时训练就完毕了。

请问输入语料中不换行会对训练效率有影响吗？
未分行的时候8线程跑了72小时一直满负荷，内存设置了6G才没有OOM，但是由于当时没有重定向错误流，不知道训练进度。

**Comment by starpipi** [comment]
好的，十分感谢。最后再咨询一个问题。

我这边目前需要实现个需求，例如语音交互回答选择题结果，但是不限定用户输入的内容，需要识别输入的答案匹配近似的选项。

上次看过之前的issue，因为CBOW无法实现识别否定意义的词语， 例如『满意』与『不满意』的近似程度是十分接近的，而实际上应该是差别很大的。
使用文档相似度的比较，在部分情况下无法获取出结果，例如输入文档仅为词语而非短文本的情况下。

请问，如果我希望满足我这个需求的情况下，应当从哪个方面去优化提升？（例如如何调优模型之类的？）或者应当朝哪个方向努力？（是否有哪些其他模型或者算法能够达到效果）或者使用别的什么方式实现（现有的功能是否有几个在同时使用的情况下能够满足）？

目前考虑的是如果选项是短文本就使用文本相似度匹配；
如果有选项是词语，或者未能识别出相似度的时候，使用依存句法分析，获取词语的关系，再判断是否存在否定词再来辅助判断结果。

**Comment by hankcs** [comment]
这是QA，是一个很复杂的话题。有语料库的话，各种[神经网络](http://www.hankcs.com/nlp/cs224n-dmn-question-answering.html)八仙过海；没有语料库的话，先句法分析再根据每个句式写规则，人干机器干的活，纯粹体力劳动吧。

**Comment by starpipi** [comment]
好的，十分感谢
