### ISSUE TITLE
请问能否使用户词典的优先级高于核心词典

### ISSUE THREAD

**Issue by Mev-z** [hankcs/HanLP#94]
比如核心词典中有"坐火车 v 187"，而我想把它分为"坐   火车"，我在用户词典中加了"坐 v 1024","火车 n 1024"，但是并没有用。

**Comment by hankcs** [comment]
0. https://github.com/hankcs/HanLP/wiki/FAQ#%E4%B8%BA%E4%BB%80%E4%B9%88%E4%BF%AE%E6%94%B9%E4%BA%86%E8%AF%8D%E5%85%B8%E8%BF%98%E6%98%AF%E6%B2%A1%E6%9C%89%E6%95%88%E6%9E%9C
0. 在data/dictionary/CoreNatureDictionary.ngram.txt中加入坐@火车即可。
0. 还可以使用1998的模型。
