### ISSUE TITLE
请教下NLPTokenizer切分短网址问题

### ISSUE THREAD

**Issue by zymming** [hankcs/HanLP#943]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号
1.6.8

当前最新版本号是：
我使用的版本是：1.6.8

## 我的问题
集卡你最棒！家人和朋友越多，集齐瓜分奖金越多，本周集卡火热进行中，一起来 t.cn/RdHCuCh 退订回T
短网址前后有空格，切分的词是：一起来 t.cn/rdhcuch 退订/d,。
这个切分是不是有问题？我把空格去掉后切分是这样的
一起/d, 来t/v, ./v, cn/rdhcuch/nx, 退订/v
来t和.号切分成动词，怎么会这样样切分呢？

有没有补救的办法

## 复现问题
System.out.println(NLPTokenizer
            .segment("集卡你最棒！家人和朋友越多，集齐瓜分奖金越多，本周集卡火热进行中，一起来 t.cn/RdHCuCh 退订回T"));

System.out.println(NLPTokenizer
            .segment("集卡你最棒！家人和朋友越多，集齐瓜分奖金越多，本周集卡火热进行中，一起来 t.cn/RdHCuCh退订回T"));

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

```
    public void testIssue1234() throws Exception
    {
        CustomDictionary.add("用户词语");
        System.out.println(StandardTokenizer.segment("触发问题的句子"));
    }
```
### 期望输出

```
期望输出
```

### 实际输出

```
实际输出
```

**Comment by hankcs** [comment]
举一反三：https://github.com/hankcs/HanLP/blob/master/src/main/java/com/hankcs/hanlp/tokenizer/URLTokenizer.java

**Comment by zymming** [comment]
非常感谢你，URLTokenizer确实可以解决。我的本意想试用下新版本的NLPTokenizer。新版本的分词有的比较准如，购物袋可以分词一个词，标准的分词器分成两个。但是有的分出来就比较疑惑，如：抢购中>，戳> 
明显>这个是特殊符号。
原始语句：
1元特权火热抢购中>福利将售罄，您拍下的1元特权还未付款！进店联系客服有惊喜，戳>c.tb.cn/c.ZI7PZ 退订N

**Comment by hankcs** [comment]
先正面回答你未切换话题之前的问题，目前感知机和CRF都没有对任何字符做任何预处理规则，因为

1. 规则是肮脏的，与具体场景脱离不开的。
1. 用户是懒惰的，如果将URL等规则包装进去，用户会问我的email怎么不能识别？如果把email也替他实现了，他又会问为什么我的ISBN无法识别？ISBN的规则类似111-222-333，等你把ISBN实现了，又有另一波用户兴师问罪了，你怎么把数字和减号合并了，200-100-100=0怎么办……作为规则系统，你可以满足一个人，但你无法满足所有人。
1. 等你花费了体力劳动写了无数规则之后，帮大部分人干了他们的活儿之后，所有用户都会跳出来质问：为什么你的系统这么慢，越改进越慢，这么多正则表达式，还不如人家xx分词器，虽然已经不维护了，但一共三个.java .py文件，我瞎改改就能满足我的业务了。

然后回答你说的>问题，由于语料库中没有大于号，所以无法用统计方法解决。临时方案是将其重定义为一个标点符号：

```
CharTable.CONVERT['>']='!'
```

当然，这些常见的符号也许的确应该内置一个规则系统来处理，我也不是顽固老学究，欢迎探讨。

**Comment by zymming** [comment]
谢谢，明白了。

**Comment by zymming** [comment]
你好，我想再接上午那个问题提下我的想法，你看是否可行。你列的URL规则，ISBN规则等，不同场景有不同规则，这些规则是否可以做成类似拦截器模式，不同场景用户自己配置不同规则，默认可以不添加那么多规则。
     我看了下代码，URL，ISBN，繁简，停用词这些都有，但是有的是作为参数写的，有的是作为一个组件包装的，虽然可以配置，但是不够灵活。例如URL规则和NLP分词器组合的时候，只能再写一个包装类来实现。

**Comment by zymming** [comment]
每个规则可能需要扫描一遍数据，性能上会有些影响。不过好处也有，不用劳心劳力做规则平衡。

**Comment by AnyListen** [comment]
可以考虑添加到项目，管道的方式在很多场景下还是很有用的，特别是混合的NLP模式；
目前的NLP模式只能实现人名、地名、组织名的识别，借助管道机制用户可以扩展更多自定义的实体识别。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
