### ISSUE TITLE
能否指定使用一个用户词典

### ISSUE THREAD

**Issue by KevinGF** [hankcs/HanLP#95]
请问对于一个分词，能不能指定使用一个词典进行分词，而且只用这一个用户词典，不使用核心词典等其它词典

**Comment by hankcs** [comment]
当然可以，不过目前只有com.hankcs.hanlp.seg.Other.AhoCorasickDoubleArrayTrieSegment 支持。
另外，你需要自己将你的词典加载到一个AhoCorasickDoubleArrayTrie中，然后调用com.hankcs.hanlp.seg.Other.AhoCorasickDoubleArrayTrieSegment#setTrie以供一个AhoCorasickDoubleArrayTrieSegment 使用。

**Comment by KevinGF** [comment]
谢谢，有没有一个参考的例子啊

**Comment by hankcs** [comment]
请参考：https://github.com/hankcs/HanLP/blob/79a21a57f1bb59e1e83a1ad3089b0268a7c68bb0/src/test/java/com/hankcs/demo/DemoUseAhoCorasickDoubleArrayTrieSegment.java
