### ISSUE TITLE
感知机分词器不能正确处理文本中的空格

### ISSUE THREAD

**Issue by wangzhe258369** [hankcs/HanLP#955]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.6.8
我使用的版本是：1.6.8

## 我的问题
感知机分词器不能正确处理文本中的空格

## 复现问题

待分词的文本：
```北京二手房成交涨五成 业内：贷款利率仍将上升```

感知机分词器（PerceptronLexicalAnalyzer）的结果：
```北京/ns 二手房/n 成交/v 涨五成 业内/s ：/vn 贷款/vn 利率/n 仍/d 将/d 上升/v```
这里“涨五成 业内”被分成了一个词。

对比默认分词器（ViterbiSegment）的结果：
```北京/ns 二手房/n 成交/v 涨/vi 五/m 成/v  /w 业内/n ：/w 贷款/n 利率/n 仍/d 将/d 上升/vi```
这里“涨五成”后的空格被正确切分出来。

## 其他信息
hanlp.properties等都是默认配置，1.6.8加载的感知机分词模型应该是large/cws.bin。

**Comment by batizhao** [comment]
这是什么原因呢？

**Comment by xliang10** [comment]
同样遇到这个问题，感知机分词器对所有空格前后的词都会合并成一个词……

**Comment by wangtao208208** [comment]
https://github.com/hankcs/HanLP/issues/797
