### ISSUE TITLE
自建某个行业的语料及遇到的分词不准问题

### ISSUE THREAD

**Issue by himozhang** [hankcs/HanLP#956]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [ ] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

我使用的版本是：1.6.8

## 问题描述
我想咨询一下楼主，如果想自建某个行业的语料，我需要哪些操作步骤？
我现在的操作是：

1. 先对行业数据进行标准分词（标准分词后，会自动生成词性）
2. 对关键词进行自定义词性标注的检查和修正
3. 使用PerceptronLexicalAnalyzer（感知机词法分析器）进行分词和实体识别
4. 规则审核

但是在训练分好词和标注好词性的语料数据时（按照199801的语料分词标准准备的数据），有些分词和词性识别并不是很准还有些词性会被覆盖。
1. 问题1：这个时候是不是需要使用PerceptronLexicalAnalyzer.learn方法来进行学习修正，还是我上述的操作本身是不对的？
2. 问题2：在进行语料标注时，标准词性和自定义复合词性对于上下文是否有要求？如果有要求，如何界定上下文的边界？
3. 问题3：实体识别时，如果一个实体存在不同词性时，是否需要根据上下文分词来判断当前实体的具体词性？如何设置上下文的窗口大小？

### 步骤
1. 我先训练自己的语料(一份进行标准分词的合同正文)，在进行标准分词后，我对语料进行了词性修改（标注为自定义词性），然后将整篇合同进行训练
```
合同各方/htgf ：/w 
甲方/jfbq ：/w 致富银行股份有限公司记账中心/jfname
[发/v 票/n 内容/n]/fpxx
名称/fpxxmcbq ：/w 致富银行股份有限公司记账中心122号/fpxxmc
[发票/n 抬头/vi]/fptt ：/w 致富银行股份有限公司记账中心/fpttname
.......
```

2. 然后调用HanLP的API训练上面的语料
```
               //1、分词
		CWSTrainer();
		//2、词性标注
		POSTrainer();
		//3、实体识别
		NERTrainer();
```
3. 训练完成后，生成自定义的cws、pos、ner.bin和bin.txt文件，然后使用感知机分词进行生产数据的分词
```
   PerceptronLexicalAnalyzer analyzer = new PerceptronLexicalAnalyzer(CWS_MODEL_FILE, 
   POS_MODEL_FILE,NER_MODEL_FILE);
   String testInfoTxt = FileUtils.readTxt("D:\\testInfo.txt");
   List<List<Term>> list = analyzer.seg2sentence(testInfoTxt );
   
```

### 期望输出

```
--->[合同各方/htgf, ：/w]
--->[甲方/jfbq, ：/w, 致富银行股份有限公司记账中心/jfname]
--->[发票内容/fpxx]
--->[名称/fpxxmcbq, ：/w, 致富银行股份有限公司记账中心122号/fpxxmc]
--->[发票抬头：/fptt, 致富银行股份有限公司记账中心/fpttname]
```

### 实际输出

```
--->[合同各方/htgf, ：/w]
--->[甲/n]
--->[方/q, ：/w, 致富银行股份有限公司记账中心/jfname]
--->[发票内容/fpxx]
--->[名称/n, ：/w, 致富银行股份有限公司记账中心122号/jfname]
--->[发票抬头：/fptt, 致富银行股份有限公司记账中心/jfname]
```

**Comment by hankcs** [comment]
你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真填写，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
![issue](http://wx1.sinaimg.cn/large/006Fmjmcly1ft2hnlwc22j30q90bcgpe.jpg)
