### ISSUE TITLE
[提问]自建某个行业的语料及遇到的分词不准问题 

### ISSUE THREAD

**Issue by himozhang** [hankcs/HanLP#957]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.6.8
我使用的版本是：1.6.8

## 我的问题

我想咨询一下楼主，如果想自建某个行业的语料，我需要哪些操作步骤？
我现在的操作是：

1. 先对行业数据进行标准分词（标准分词后，会自动生成词性）
2. 对关键词进行自定义词性标注的检查和修正
3. 使用PerceptronLexicalAnalyzer（感知机词法分析器）进行分词和实体识别
4. 规则审核

但是在训练分好词和标注好词性的语料数据时（按照199801的语料分词标准准备的数据），有些分词和词性识别并不是很准还有些词性会被覆盖。
1. 问题1：这个时候是不是需要使用PerceptronLexicalAnalyzer.learn方法来进行学习修正，还是我上述的操作本身是有问题的？
2. 问题2：在进行语料标注时，标准词性和自定义复合词性对于上下文是否有要求？如果有要求，如何界定上下文的边界？
3. 问题3：语料训练时候，是需要将整片文章进行训练，还是只对需要提取内容的部分段落进行训练？
4. 问题4：实体识别时，如果一个实体存在不同词性时，是否需要根据上下文分词来判断当前实体的具体词性？如何设置上下文的窗口大小？

### 步骤

1. 我先训练自己的语料(一份进行标准分词的合同正文)，在进行标准分词后，我对语料进行了词性修改（标注为自定义词性），然后将整篇文章进行训练
```
客户信息/khxx ：/w 
客户方/khfbq ：/w 致富银行股份有限公司记账中心/khfname
[发/v 票/n 内容/n]/fpxx
名称/fpxxmcbq ：/w 致富科技有限公司记账中心122号/fpxxmc
[发票/n 抬头/vi]/fptt ：/w 致富科技有限公司记账中心/fpttname
.......
```

2. 然后调用HanLP的API训练上面的语料
```
               //1、分词
		CWSTrainer();
		//2、词性标注
		POSTrainer();
		//3、实体识别
		NERTrainer();
```
3. 训练完成后，生成自定义的cws、pos、ner.bin和bin.txt文件，然后使用感知机分词进行生产数据的分词
```
   PerceptronLexicalAnalyzer analyzer = new PerceptronLexicalAnalyzer(自定义_CWS_MODEL_FILE, 
   自定义_POS_MODEL_FILE,自定义_NER_MODEL_FILE);
   String testInfoTxt = FileUtils.readTxt("D:\\testInfo.txt");
   List<List<Term>> list = analyzer.seg2sentence(testInfoTxt );
   
```

### 期望输出

```
--->[客户信息/khxx, ：/w]
--->[客户方/khfbq, ：/w, 致富科技有限公司记账中心/khfname]
--->[发票内容/fpxx]
--->[名称/fpxxmcbq, ：/w, 致富科技有限公司记账中心122号/fpxxmc]
--->[发票抬头：/fptt, 致富科技有限公司记账中心/fpttname]
```

### 实际输出

```
--->[客户信息/khxx, ：/w]
--->[客户/n]
--->[方/q, ：/w, 致富科技有限公司记账中心/khfname]
--->[发票内容/fpxx]
--->[名称/n, ：/w, 致富科技有限公司记账中心122号/khfname]
--->[发票抬头：/fptt, 致富科技有限公司记账中心/khfname]
```

**Comment by hankcs** [comment]
1. 标注集不同，无法在线学习。语料库规模决定实际效果，如果你的行业语料只有几篇文章，然后你跟人民日报混合，你的标注就会被人民日报覆盖。
1. 你不必区分两类词性，它们都是词性，你需要一视同仁地重新标注。特征模板当然包括上下文，你说的上下文边界如果指的是特征提取的范围的话，目前的设置是半径为1的窗口，你也可以自定义特征模板。
1. 语料越多越好。
1. 当然，见问题2 。

你的测试输出涉及到几个问题，逐条回复。

1. “客户方”被换行符隔开，你需要预处理。
1. 语料库规模决定实际效果，如果你的行业语料只有一两篇文章，这无法构成机器学习。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
