### ISSUE TITLE
golang 版本支持

### ISSUE THREAD

**Issue by BlackCodes** [hankcs/HanLP#959]
经过多个开源项目的比较，最后的结论是Hanlp分词足够强大的，各种算法已经能满足常见的业务需求，我们现在用起来比较痛苦，我们所有的开发语言都是go版的，现在用这个，我需要先通过python调用Java，然后，再用golang调Python，实在太痛了，版主能否支持个go版的！

**Comment by hankcs** [comment]
你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真填写，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
![issue](http://wx1.sinaimg.cn/large/006Fmjmcly1ft2hnlwc22j30q90bcgpe.jpg)
