### ISSUE TITLE
股份，繁体转简体

### ISSUE THREAD

**Issue by xghrbc1001** [hankcs/HanLP#96]
股份，繁体转简体，变成了股分。

股份其实是一个简体，调用了HanLP.convertToSimplifiedChinese("股份")

**Comment by hankcs** [comment]
感谢指正，词库未必都是对的，遇到这种情况，可以如下修改：
https://github.com/hankcs/HanLP/commit/4161ac526163dbb79b1b022862bad9c21a705d59

也欢迎将修改提交Github。
