### ISSUE TITLE
I did not see the download address of 100 million corps

### ISSUE THREAD

**Issue by whaozl** [hankcs/HanLP#960]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.6.8
我使用的版本是：1.6.8

## 我的问题

1亿字的中文语料，没有看到下载地址，想自己训练模型

**Comment by hankcs** [comment]
1. 语料库标注耗费大量人力物力，需要开发一套标注系统，聘请至少一名语言学专家拟定标注方案，数十名标注员实施人工标注。根据语料库规模不同，制作组甚至可达一百多人。按平均每人每月3000元最低工资标准，一个月工期，则光人力成本就达到30万元，而实际项目远不止这个数。
1. 国外知识产权保护得当，语料库交易已经形成良性市场。在LDC网站上300万字的中文树库售价300美元，滨州树库售价1700美元。国内虽然起步较晚，但也有类似的LDC的中文语言资源联盟在运行。500万字的平衡语料售价5万人民币。为了促进中文信息处理的发展，一些研究机构甚至慷慨地向广大研究者免费开放部分语料库。其中一些版权宽松的语料库收录在：https://github.com/hankcs/OpenCorpus
1. 然而国内的版权观念淡薄，语料库几乎都有盗版。一些所谓的开源项目，公众号甚至“加星就发网盘”“关注公众号回复下载地址”。语料制作方无法盈利，反而被这些小人抄盘，长期下去整个行业都会死亡，到最后谁也没有新语料可用。

为此，我严词拒绝所有索要语料者：

**HanLP开发者及开源社区尊重知识产权，不会以任何理由散布未经授权的语料库或其他语言学资源。**

**Comment by rubby33** [comment]
感谢作者开发hanlp,真正脚踏实地做中文nlp，造福大家 @hankcs, 谢谢。
