### ISSUE TITLE
data中缺少segment文件夹?

### ISSUE THREAD

**Issue by FontTian** [hankcs/HanLP#961]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号
pyhanlp-1.6.8

当前最新版本号是：pyhanlp-1.6.8
我使用的版本是：pyhanlp-1.6.8

## 我的问题

使用自带demo中的CRF分词进行分词,出现模型加载错误,发现data-model中缺少相应segment文件夹.下载data后解压发现,还是没有该文件夹.

## 使用代码
在使用demo中的CRF分词时出现问题,代码如下
```
Config = JClass("com.hankcs.hanlp.HanLP$Config")
Config.ShowTermNature = False
CRFSegment = JClass("com.hankcs.hanlp.seg.CRF.CRFSegment")
segment = CRFSegment().enableCustomDictionary(False)

for sentence in sentence_array:
    term_list = segment.seg(sentence)
    print(term_list)

```

## 出现错误
```
---------------------------------------------------------------------------
java.lang.IllegalArgumentExceptionPyRaisableTraceback (most recent call last)
<ipython-input-6-d745364c843d> in <module>()
     25 Config.ShowTermNature = False
     26 CRFSegment = JClass("com.hankcs.hanlp.seg.CRF.CRFSegment")
---> 27 segment = CRFSegment().enableCustomDictionary(False)
     28 
     29 for sentence in sentence_array:

~/anaconda3/lib/python3.6/site-packages/jpype/_jclass.py in _javaInit(self, *args)
    109     else:
    110         self.__javaobject__ = self.__class__.__javaclass__.newClassInstance(
--> 111             *args)
    112 
    113 

java.lang.IllegalArgumentExceptionPyRaisable: java.lang.IllegalArgumentException: CRF分词模型加载 /home/font/anaconda3/lib/python3.6/site-packages/pyhanlp/static/data/model/segment/CRFSegmentModel.txt 失败，耗时 6 ms
```

**Comment by FontTian** [comment]
抱歉,我刚刚看了看更新日志.原来该部分已经被删除了,虽然不太理解为什么要删除,但是现在我的问题算算是解决了.

**Comment by FontTian** [comment]
我有一个新的问题想要请教一下,1.68版本,Python语法中如何使newSegment得到的Segment可以直接不显示分词后的词性.

现在得到seg得到的是一个java中的ArrayList,如果直接print() 获得的list是[词语/词性,词语/词性....]这种格式的.如果`.enablePartOfSpeechTagging(False)`,那么得到的将会是[词语/null,词语/null....]这种格式

```
"""
[小区/n, 居民/n, 有的/r, 反对/v, 喂/v, 养/v, 流/v, 浪/n, 猫/v]
小区/n
小区
居民/n
居民
有的/r
有的
反对/v
反对
喂/v
喂
养/v
养
流/v
流
浪/n
浪
猫/v
猫
[小区/null, 居民/null, 有的/null, 反对/null, 喂/null, 养/null, 流/null, 浪/null, 猫/null]
"""
text = "小区居民有的反对喂养流浪猫"
CRFnewSegment = HanLP.newSegment("crf")
term_list = CRFnewSegment.seg(text)
print(term_list)
for i in term_list:
    print(i)
    print(i.word)
    
CRFnewSegment.enablePartOfSpeechTagging(False)
term_list = CRFnewSegment.seg(text)
print(term_list)
```
请问如何直接得到我想要的[词语,词语,词语,...],而不再添加自定义的处理函数(我觉得那样会慢一些,而且增加了代码量)

**Comment by hankcs** [comment]
Hi，CRFSegment已经被CRFLexicalAnalyzer替代了，请查阅发行日志：https://github.com/hankcs/HanLP/releases/tag/v1.6.6

你需要在启动时加一行`HanLP.Config.ShowTermNature = false`，或者编辑配置文件中的相应条目。

**Comment by FontTian** [comment]
谢谢解答,问题解决.

**Comment by yaleimeng** [comment]
原来的CRFSegment废弃了，新的CRFLexicalAnalyzer词性标注体系改为pku98，词性种类减少，有些细分词性就不能辨别了。
@FontTian 既然问题解决，建议关闭issue。
@hankcs 示例里面一些废弃模块的demo还在（不一定能用）。可考虑去掉。

**Comment by FontTian** [comment]
> ## 注意事项
> 请确认下列注意事项：
> 
> * 我已仔细阅读下列文档，都没有找到答案：
>   
>   * [首页文档](https://github.com/hankcs/HanLP)
>   * [wiki](https://github.com/hankcs/HanLP/wiki)
>   * [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
> * 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
> * 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
> * [x]  我在此括号内输入x打钩，代表上述事项确认完毕。
> 
> ## 版本号
> pyhanlp-1.6.8
> 
> 当前最新版本号是：pyhanlp-1.6.8
> 我使用的版本是：pyhanlp-1.6.8
> 
> ## 我的问题
> 使用自带demo中的CRF分词进行分词,出现模型加载错误,发现data-model中缺少相应segment文件夹.下载data后解压发现,还是没有该文件夹.
> 
> ## 使用代码
> 在使用demo中的CRF分词时出现问题,代码如下
> 
> ```
> Config = JClass("com.hankcs.hanlp.HanLP$Config")
> Config.ShowTermNature = False
> CRFSegment = JClass("com.hankcs.hanlp.seg.CRF.CRFSegment")
> segment = CRFSegment().enableCustomDictionary(False)
> 
> for sentence in sentence_array:
>     term_list = segment.seg(sentence)
>     print(term_list)
> ```
> ## 出现错误
> ```
> ---------------------------------------------------------------------------
> java.lang.IllegalArgumentExceptionPyRaisableTraceback (most recent call last)
> <ipython-input-6-d745364c843d> in <module>()
>      25 Config.ShowTermNature = False
>      26 CRFSegment = JClass("com.hankcs.hanlp.seg.CRF.CRFSegment")
> ---> 27 segment = CRFSegment().enableCustomDictionary(False)
>      28 
>      29 for sentence in sentence_array:
> 
> ~/anaconda3/lib/python3.6/site-packages/jpype/_jclass.py in _javaInit(self, *args)
>     109     else:
>     110         self.__javaobject__ = self.__class__.__javaclass__.newClassInstance(
> --> 111             *args)
>     112 
>     113 
> 
> java.lang.IllegalArgumentExceptionPyRaisable: java.lang.IllegalArgumentException: CRF分词模型加载 /home/font/anaconda3/lib/python3.6/site-packages/pyhanlp/static/data/model/segment/CRFSegmentModel.txt 失败，耗时 6 ms
> ```
