### ISSUE TITLE
你好，不知是否可以同步共享一下1.6.8版本使用的语料库

### ISSUE THREAD

**Issue by cchangping** [hankcs/HanLP#963]
首先非常感谢作者无私的公布了在一亿字的大型综合语料库上训练的分词模型，目前在测试过程了表现不错，作者是否能同步共享此语料库，因为目前项目希望再此语料库上加入行业内的语料，已达到更好的行业内分词表现。

**Comment by hankcs** [comment]
你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真填写，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
![issue](http://wx1.sinaimg.cn/large/006Fmjmcly1ft2hnlwc22j30q90bcgpe.jpg)
