### ISSUE TITLE
你好，请问如何进行切分短语呢？

### ISSUE THREAD

**Issue by zxyza** [hankcs/HanLP#965]
比如“延庆区2018年彩色树种造林工程施工招标公告”这种句子，我其实祥要最大程度上来切词，切成的结果是“延庆区”“2018年”“彩色树种造林”“工程施工”“招标公告”这种短句子，请问你这个代码有什么好办法呢？

**Comment by hankcs** [comment]
你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真填写，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
![issue](http://wx1.sinaimg.cn/large/006Fmjmcly1ft2hnlwc22j30q90bcgpe.jpg)
