### ISSUE TITLE
DoubleArrayTrie的LongestSearcher有时候匹配遗漏

### ISSUE THREAD

**Issue by wawa8900** [hankcs/HanLP#966]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.6.8
我使用的版本是：portable-1.6.6

## 我的问题
在使用DoubleArrayTrie类的LongestSearcher方法时，有些词匹配不到。

### 步骤
1. 构建一个DoubleArrayTrie，包含以下关键词：
001乡道, 北京, 北京市通信公司, 来广营乡, 通州区
2. 用上面构建的DART，使用getLongestSearcher()，匹配下面的句子：
北京市通州区001乡道发生了一件有意思的事情，来广营乡歌舞队正在跳舞

### 触发代码
		DoubleArrayTrie<String>.LongestSearcher searcher = dart.getLongestSearcher(str, 0);
		while (searcher.next())
		{
                     ...
		}
### 期望输出
期望能按顺序匹配到下面的词：
北京 通州区 001乡道 来广营乡

### 实际输出
只匹配到了下面的词（通州区没有被匹配到）
北京 001乡道 来广营乡

## 其他信息
使用getSearcher()没有问题

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。
