### ISSUE TITLE
pyhanlp可以配置直接使用hanlp-portable-1.6.8.jar，而不需要hanlp.properties文件吗？

### ISSUE THREAD

**Issue by whaozl** [hankcs/HanLP#968]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.6.8
我使用的版本是：1.6.8

## 我的问题

    我将pyhanlp安装后，把hanlp-1.6.8.jar用hanlp-portable-1.6.8.jar替换
  
    但是依然需要hanlp.properties文件，可以直接和java一样使用快速版本吗？
    
    然后用户通过加入词典直接更新hanlp-portable-1.6.8.jar里面的txt.bin文件即可？

    恕我冒昧哈，提出这样的一个请求，里面pyhanlp代码好复杂，没怎么看懂

**Comment by hankcs** [comment]
需要，可以。
export HANLP_JAR_PATH=path/to/hanlp-portable-1.6.8.jar
export HANLP_STATIC_ROOT=
你就可以脱离外部data了。
但jar包是个静态文件，不允许更新内部的bin。
portable是面向1、maven用户方便部署。2、给那些什么都不懂的懒人体验用的。
你的需求完全可以通过编辑配置文件做：
CoreDictionaryPath=data/dictionary/CoreNatureDictionary.mini.txt
BiGramDictionaryPath=...
CustomDictionaryPath=...
或者HanLP.Config.CoreDictionaryPath=...

**Comment by whaozl** [comment]
太感谢hankcs了
