### ISSUE TITLE
elasticsearch-analysis-hanlp 插件在分词(analyze)时不支持归一化

### ISSUE THREAD

**Issue by hapjin** [hankcs/HanLP#970]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [ ] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：HanLP 1.6.8
我使用的版本是：elasticsearch-analysis-hanlp 6.3.2(ElasticSearch插件版本)

## 我的问题
我通过`./bin/elasticsearch-plugin install https://github.com/KennFalcon/elasticsearch-analysis-hanlp/releases/download/v6.3.2/elasticsearch-analysis-hanlp-6.3.2.zip`安装了 elasticsearch-analysis-hanlp 6.3.2 插件。在ElasticSearch-Kibana devTools上分析：
```html
GET index_ik_test/_analyze
{
  "analyzer": "hanlp",
  "text": ["④⑧⑦④22②8Q笳看"]
}
```
得到的分词结果如下：(用 斜杠 来分隔分词结果)。
>④⑧⑦④/22/②/8/Q/笳/看

由于有特殊的数字字符，这些数字并没有分在一起。而我的需求是：在分词之前，先将一些特殊数字字符进行归一化，这样分词之后数字就能分在一起了，在HanLP1.6.3中测试归一化如下：
```java
    @Test
    public void testNorm() {
        HanLP.Config.Normalization = true;
        System.out.println(HanLP.segment("④⑧⑦④22②8Q笳看"));
    }
```
输出：
>[48742228/m, q/nx, 笳/g, 看/v]

符合我的要求。但是ElasticSearch中用 elasticsearch-analysis-hanlp插件(hanlp、hanlp_standard、hanlp_index等分词器)来分词时，没有归一化效果。

我的问题是： elasticsearch-analysis-hanlp插件 是否考虑在分词时通过配置方式来支持归一化？

## 其他信息

我看了下插件源码中： [com.hankcs.cfg.Configuration.java](https://github.com/KennFalcon/elasticsearch-analysis-hanlp/blob/master/src/main/java/com/hankcs/cfg/Configuration.java)里面定义了一些 关于分词的配置信息，但是没有关于是否开启归一化的配置 `HanLP.Config.Normalization = true`。

**Comment by hankcs** [comment]
Hi，https://github.com/hankcs/hanlp-lucene-plugin 是支持配置Normalization的，但你用的插件的作者并没有依赖该项目。所以麻烦直接向插件作者反馈，谢谢。

**Comment by hapjin** [comment]
明白了，谢谢。
