### ISSUE TITLE
Hanlp分词遇到Unicode表情符号程序就崩溃

### ISSUE THREAD

**Issue by whaozl** [hankcs/HanLP#971]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.6.8
我使用的版本是：1.6.8

## 我的问题

只要分句中带有unicode表情符号，断点都没有作用，Python就停止工作，Java也是如此

### 步骤

```python
from pyhanlp import *

if __name__ == '__main__':
    try:
        result=HanLP.segment("🙏🙏🙏")
    except Exception:
        result=""
    print(result)

```
### 期望输出

应该根据正常的Unicode表情符号分词

**Comment by hankcs** [comment]
https://github.com/hankcs/HanLP/issues/829#issuecomment-403334749

**Comment by whaozl** [comment]
@hankcs , 您好哈，我这个问题可能不太一样哈，我这个是python3.5.4环境，执行完直接就崩溃或者报unicode错
```
from pyhanlp import *

if __name__ == '__main__':
    try:
        result=HanLP.segment("🙏你好，欢迎在😱Python中🙏调用HanLP的API😱😱🙏")
        #这种能正常，但是丢失一个表情符号
        #result=HanLP.segment("你好，欢迎在Python中调用HanLP的API😱😱")
    except Exception:
        result=""
    print(result)
```
![1](https://user-images.githubusercontent.com/6327360/46184796-daeeb880-c309-11e8-8ec7-d0930417cd15.png)

**Comment by whaozl** [comment]
@hankcs 感谢您百忙解答哈，还有一个，就是在句子尾部添加更多表情符号，程序也会崩溃：
![1](https://user-images.githubusercontent.com/6327360/46185040-ef7f8080-c30a-11e8-9302-285a5b02aa22.png)
```
#以下会崩溃
result="😱😱😱你好，欢迎在😱Pytho😱😱n中😱调用HanLP的API   😱😱😱😱😱😱😱😱😱😱"
#以下按照解决方案不会崩溃 但是尾部的表情符号丢失掉了。前面的没有丢失
result="😱😱😱你好，欢迎在😱Pytho😱😱n中😱调用HanLP的API 😱😱 "
```

**Comment by hankcs** [comment]
1. jpype在将str从python到java的转换以及反向转换时都需要特殊处理：https://github.com/jpype-project/jpype/issues/278
1. 参考代码：

```python
from jpype import java

from pyhanlp import *

text = '😱😱😱你好，欢迎在😱Pytho😱😱n中😱调用HanLP的API   😱😱😱😱😱😱😱😱😱😱'

String = java.lang.String
java_string = String(text.encode(), 'UTF8')
string_from_java = str(java_string).encode('utf-16', errors='surrogatepass').decode('utf-16')
print('原文：' + string_from_java)
print('HanLP分词结果')
for term in HanLP.segment(java_string):
    print(str(term.word).encode('utf-16', errors='surrogatepass').decode('utf-16'))
```

输出结果：

```
原文：😱😱😱你好，欢迎在😱Pytho😱😱n中😱调用HanLP的API   😱😱😱😱😱😱😱😱😱😱
HanLP分词结果
😱😱😱
你好
，
欢迎
在
😱
Pytho
😱😱
n
中
😱
调用
HanLP
的
API
   
😱😱😱😱😱😱😱😱😱😱
```

**Comment by passerbythesun** [comment]
```
String = JPackage('java').lang.String
java_string = String("😁".encode(),'UTF8')
```

**Comment by whaozl** [comment]
@passerbythesun   hanks大神已经解决了，感谢哈
