### ISSUE TITLE
hanlp 可以添加英文单词组合的作为新词放到词典里吗？

### ISSUE THREAD

**Issue by whaozl** [hankcs/HanLP#972]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.6.8
我使用的版本是：1.6.8

## 我的问题

在CustomDictionary.txt中添加如下英文单词组合的新词，英文都是空格隔开的了我把分割符换成\t也不行
air motor n 1

报错：严重: 自定义词典D:/An/HanLP/data/dictionary/custom/CustomDictionary.txt读取错误！java.lang.NumberFormatException: For input string: "n"

### 触发代码

```
    public void testIssue1234() throws Exception
    {
        CustomDictionary.add("用户词语");
        System.out.println(StandardTokenizer.segment("air motor is very good"));
    }
```

**Comment by AnyListen** [comment]
.txt 词典文件的分隔符为空格或制表符，所以不支持含有空格的词语。如果需要支持空格，请使用英文逗号,分割的纯文本 .csv 文件。在使用 Excel 等富文本编辑器时，则请注意保存为纯文本形式。

**Comment by whaozl** [comment]
纯.csv可以作为词典文件？这样就支持带有空格的词语？

**Comment by AnyListen** [comment]
@whaozl Just Try It

**Comment by whaozl** [comment]
哇，it is surprise! thank you very much.
