### ISSUE TITLE
基于信息凝固度与外部信息熵的新词识别的Java实现

### ISSUE THREAD

**Issue by SCismycat** [hankcs/HanLP#973]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕

## 版本号

当前最新版本号是：1.6.8
我使用的版本是：1.6.8

## 我的问题

Hi，Hankcs.很早以前就一直在关注和学习你的Blog。我的问题如下：
最近在做一个无监督提取领域词实验。看到您的《基于信息熵和互信息的新词识别》一文结合了内部凝固度与外部左右熵的Java实现，请问这部分代码是否在Hanlp中集成？ 在评论下看到你的回复：“哦，HanLP里面是提取短语用的，这个是提取词语用的，不一样的”，请问一下HanLP中所开源的信息熵短语识别与《基于信息熵和互信息的新词识别》文中提到的有何异同？如有不同，可否参考一下您的该文的Java实现？非常感谢！

## 复现问题
暂无

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

```
   NULL
```
### 期望输出

NULL

```
期望输出
```

### 实际输出

```
实际输出
```

## 其他信息

[《基于信息熵和互信息的新词识别》](http://www.hankcs.com/nlp/new-word-discovery.html)

**Comment by AnyListen** [comment]
请参考 wiki 的介绍：https://github.com/hankcs/HanLP/wiki/%E6%96%B0%E8%AF%8D%E8%AF%86%E5%88%AB

**Comment by SCismycat** [comment]
@AnyListen 非常感谢你的回答
