### ISSUE TITLE
n-gram关系由来

### ISSUE THREAD

**Issue by solemnrole** [hankcs/HanLP#976]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号
GitHub仓库版 master分支

当前最新版本号是： GitHub仓库版 master分支 
我使用的版本是： GitHub仓库版 master分支 

## 我的问题

我想咨询下hanlp的二元关系是怎么得到的？例如‘一@公益 1’，‘一@一对一 5’。我理解的二元关系是左元+右元能够是一个搭配之类的，但是这样的二元关系看起来有点怪，是不是我理解错了hanlp的二元关系？另外对于n-gram的搭配的‘出场顺序’也存在疑问，为什么整体上二元关系出现的频率都比较小，是跟语料有关系吗？烦请能够指点。非常感谢！

**Comment by hankcs** [comment]
1. 这些奇怪的bigram可能是语料库标注错误导致的
1. bigram的频率应当是两个unigram的频率之积，当然更小。

**Comment by solemnrole** [comment]
感谢回答~
第二个问题有一些疑问：‘bigram的频率应当是两个unigram的频率之积，当然更小’
二元关系的统计不应该是两个词同时出现的频率次数吗？

**Comment by solemnrole** [comment]
> 1. 这些奇怪的bigram可能是语料库标注错误导致的
> 2. bigram的频率应当是两个unigram的频率之积，当然更小。

感谢回答~
第二个问题有一些疑问：‘bigram的频率应当是两个unigram的频率之积，当然更小’
二元关系的统计不应该是两个词同时出现的频率次数吗？为什么是两个unigram的频率之积？两个大于一的数相乘，结果应该更大吧？是否是在频率上做了什么处理？烦请指教！蟹蟹~

**Comment by hankcs** [comment]
频率不等于频次，统计时按[最大似然估计](http://www.phontron.com/slides/nlp-programming-en-02-bigramlm.pdf)，平滑处理请参考：https://github.com/hankcs/HanLP/issues/120

**Comment by solemnrole** [comment]
> 频率不等于频次，统计时按[最大似然估计](http://www.phontron.com/slides/nlp-programming-en-02-bigramlm.pdf)，平滑处理请参考：#120

这个平滑处理我看啦，可能我说的不够明白，导致理解偏差了。我说的这个频次指的是n-gram词表中的二元关系后跟的频率。如不停@感叹 14中的14，这个频次是语料中真实出现的频次吗？因为数据频次大部分是较小的。做一才会有是否对这个频次做了什么处理的疑问。希望我说的能够让你明白。谢谢啦。

**Comment by hankcs** [comment]
人民日报语料库有2000万字，“不停感叹”出现14次不奇怪。

**Comment by solemnrole** [comment]
> 人民日报语料库有2000万字，“不停感叹”出现14次不奇
非常感谢回答~

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
