### ISSUE TITLE
stopwords能不能像自定义字典一样在配置里自定义新文件

### ISSUE THREAD

**Issue by skyrusai** [hankcs/HanLP#977]
## 注意事项
请确认下列注意事项：
* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [👍 ] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号
pyhanlp
当前最新版本号是：1.6.8
我使用的版本是：1.6.8

## 我的问题
stopwords 能不能自定义文件
print(HanLP.Config.CoreStopWordDictionaryPath)
/home/q/pyhanlp/data/dictionary/stopwords.txt; stop_dict.txt;
能不能这样配置
这样配置，下面这段代码会报错，也就是不能这样配置吗？

--------------------------------

from pyhanlp import *
NotionalTokenizer = JClass("com.hankcs.hanlp.tokenizer.NotionalTokenizer")
text = "小区居民有的反对喂养流浪猫，而有的居民却赞成喂养这些小宝贝"
print(NotionalTokenizer.segment(text))

-----------------------------------

java.lang.NullPointerExceptionPyRaisable  Traceback (most recent call last)
<ipython-input-1-bfb7f4ece71a> in <module>()
      4 
      5 text = "小区居民有的反对喂养流浪猫，而有的居民却赞成喂养这些小宝贝"
      6 print(NotionalTokenizer.segment(text))

java.lang.NullPointerExceptionPyRaisable: java.lang.NullPointerException

----------------------------------------

## 我的问题2
win10也同样配置了hanlp.properties
CustomDictionaryPath=data/dictionary/custom/CustomDictionary.txt; Custom.txt; 现代汉语补充词库.txt; 全国地名大全.txt ns; 人名词典.txt; 机构名词典.txt; 上海地名.txt ns; my.txt; feature_dict.txt; data/dictionary/person/nrf.txt nrf;
同样删除了缓存文件，不知为什么，生成出来的地址始终没有feature_dict.txt， Custom.txt; 

-----------------------------------

print(HanLP.Config.CustomDictionaryPath)
('d:/applications/pyhanlp/data/dictionary/custom/CustomDictionary.txt', 'd:/applications/pyhanlp/data/dictionary/custom/现代汉语补充词库.txt', 'd:/applications/pyhanlp/data/dictionary/custom/全国地名大全.txt ns', 'd:/applications/pyhanlp/data/dictionary/custom/人名词典.txt', 'd:/applications/pyhanlp/data/dictionary/custom/机构名词典.txt', 'd:/applications/pyhanlp/data/dictionary/custom/上海地名.txt ns', 'd:/applications/pyhanlp/data/dictionary/person/nrf.txt nrf')

-----------------------------------

上面就原始的七个，有什么检查方法吗，java也不是特别熟。

**Comment by AnyListen** [comment]
问题 1：
貌似 停用词词典不支持配置多个路径，你可以指定单个文件试一下。

问题 2：
你的 `上海地名.txt ns` 是不是配置有问题；此外 `my.txt; feature_dict.txt;`  这两个文件的目录需要在`data/dictionary/custom/` 下面。

**Comment by skyrusai** [comment]
![default](https://user-images.githubusercontent.com/25544138/46121107-cc8a9900-c244-11e8-958d-1add2918a5fc.JPG)

**Comment by hankcs** [comment]
1. 停用词典的确不支持多个路径，请合并到stopwords.txt
1. 你的配置文件没有编辑或编辑错了。`hanlp -v`获取hanlp.properties的路径，修改

```
CustomDictionaryPath=data/dictionary/custom/CustomDictionary.txt; my.txt; 全国地名大全.txt ns;data/dictionary/person/nrf.txt nr;
```

注意放到`CustomDictionary.txt;`的后面，加空格，加英文分号结束。

**Comment by hankcs** [comment]
没关系，你应该检查是否编辑了正确的配置文件，site-packages\pyhanlp\static下面有hanlp.properties和hanlp.properties.in，第一个才是正确的配置文件。你需要显示文件拓展名。
![2018-10-06_18-47-22](https://user-images.githubusercontent.com/5326890/46576492-bc875d80-c998-11e8-882c-62e5ef0a2304.png)

**Comment by skyrusai** [comment]
隔了几天，又跑了下代码，没问题了，感谢大佬耐心解答
