### ISSUE TITLE
多线程下内存溢出

### ISSUE THREAD

**Issue by zero654655902** [hankcs/HanLP#978]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [√] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：
pyhanlp 0.1.44
我使用的版本是：
pyhanlp   0.1.41

## 我的问题
多线程下调用句法依存会出现内存溢出
get_relations_pos_head(sentence)中的
word_array = HanLP.parseDependency(sentence).getWordArray()
报错：jpype._jexception.java.lang.OutOfMemoryErrorPyRaisable: java.lang.OutOfMemoryError: GC overhead limit exceeded

并且程序一开始运行时，物理内存占1.9G ，虚拟内存占5G, 运行一段时间后虚拟内存就到9G

**Comment by hankcs** [comment]
请限制输入sentence的长度。如果你把整部小说当一个句子送进去，只怕100G的内存也不够你用。

**Comment by kimi0421** [comment]
如果是高并发的时候，即使是sentence很短我发现也会泄露，是什么问题？

**Comment by kimi0421** [comment]
如果是高并发的时候，即使是sentence很短我发现也会泄露，是什么问题？
