### ISSUE TITLE
请问1.6.8中大规模语料训练的感知机模型的命名实体识别ner.bin会提供嘛?

### ISSUE THREAD

**Issue by symsimmy** [hankcs/HanLP#979]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：**1.6.8**
我使用的版本是：**1.6.8**

## 我的问题

我发现**data-for-1.6.8**数据包中data/model/perceptron/large目录下只有分词模型cws.bin,并未提供ner.bin,请问方便提供嘛?

**Comment by hankcs** [comment]
感谢反馈，

1. 亿级语料指的是分词语料，其中绝大部分还未进行NER标注，所以客观上无法训练出large/ner.bin
1. 请利用https://github.com/hankcs/OpenCorpus 提供的命名实体语料库
1. 目前HanLP演示站使用的1998年6月份的人民日报NER模型，将会在后续版本中发布。目前的考虑是尽量减小数据包体积，引导用户尊重语料库建设，自行标注训练模型。
