### ISSUE TITLE
关于DemoSuggester的最相似问题

### ISSUE THREAD

**Issue by a8313009** [hankcs/HanLP#98]
我采用的是3.3.1的版本,DemoSuggester类中查找相关度的句子,
比如说:[今天我吃饭了,今天我没吃饭]
查找关键词是吃饭,2个句子都出来了,能做否定词过滤吗?
在其次我查找没吃饭,吃饭也不因该出来.

**Comment by hankcs** [comment]
0. 这涉及到更复杂的语义计算，至少是谓词逻辑，短时间比较困难
0. 如果你看到好的论文或实现，欢迎提出

**Comment by 240668488** [comment]
你好
如果启用用户词典，词典里面同时存在 [无]、[黑便]、[无黑便]三个词，当对一句话里面出现“无黑便”的情况下，你的分词器是按 最大词分 还是 拆开来分呢？求解，此外，可配么？

**Comment by hankcs** [comment]
你好

0. 请先学习“词典分词”与“统计模型分词”的区别（必须）！
0. HanLP中有许多分词器， ![image](http://ww4.sinaimg.cn/large/6cbb8645jw1erw04dfdk0j210t0buwgi.jpg)其中一些是前者，一些是后者，可以从继承关系区别
0. 所以不要用“最大词”“最长词”之类的描述以偏概全，两大类分词器的原理完全不同
0. 如果你能区分“词典分词”与“统计模型分词”的话，那么你的问题就全明白了。否则，我只能简单地告诉你，词典分词是按最长词，统计分词可以调整模型来达到你的目的。

**Comment by 240668488** [comment]
你好，看了你的回答之后
我尝试了词典分词
Suggester测试类里面有三组数据 一个包含“无黑便”，另外两个包含“黑便”
为什么我调用suggest("黑便", 1)和suggest("无黑便", 1)最后都是出来包含“无黑便”的那组数据呢？
注：我在SpeedTokenizer里面启用了用户词典，所以分词效果是  “无黑便”、“黑便”、“黑便”

**Comment by intohole** [comment]
机器分词很久很久以前的了，很多人说分词就那几种算法，其实看到的都是机器分词，拿个词典。。。

在 2015年12月14日 下午3:45，240668488 <notifications@github.com>写道：

**Comment by hankcs** [comment]
因为Suggester用的是MotionTokenizer，与SpeedTokenizer是无关的。另外，MotionTokenizer会将“无”这样的单字作为停用词去掉。

**Comment by 240668488** [comment]
你好
MotionTokenizer是什么鬼？全局搜索啥都没有
我看你suggester里面考虑三种情形，我在IdVector里面采用SpeedTokenizer的分词方法并启用用户词典
此外，可以把某个词从停用词里面剔除么，比如“无”（题外话，我也住松江，能登门拜访请教么）
我们公司有意向跟你沟通合作，我的联系方式13918282494，恭候你的来电！

**Comment by hankcs** [comment]
不好意思，拼错了，是com.hankcs.hanlp.tokenizer.NotionalTokenizer
停用词请参考文档或demo目录，都有API。

关于合作，我现在在徐汇，你可以把需求发给我（me艾特hankcs.com），我先根据需求考虑一下。

**Comment by 240668488** [comment]
你好
请问你的HanLP是基于哪个开源项目？斯坦福分词么？
另：中英夹杂的文本，HanLP能很好的支持么？

**Comment by hankcs** [comment]
HanLP是基于HanLP的，不依赖任何第三方库。
支持。

**Comment by 240668488** [comment]
你好
那HanLP的实现原理有参考其他开源作品么？我记得你的博客提到过哈工大的中文分词，不知道对否
另：HanLP有对反义算子或否定算子 进行研究拓展么？若无，接下来会考虑拓展实现么？
最后：我测试依存句法分析的demo，发现一个问题
测试语句：篮子里有香蕉、苹果、榴莲、没有猕猴桃。
结果如下：
篮子 --(定中关系)--> 里
里 --(主谓关系)--> 有
有 --(核心关系)--> ##核心##
香蕉 --(动宾关系)--> 有
、 --(标点符号)--> 香蕉
苹果 --(并列关系)--> 香蕉
、 --(标点符号)--> 榴莲
榴莲 --(并列关系)--> 香蕉
、 --(标点符号)--> 没有
没有 --(并列关系)--> 香蕉
猕猴桃 --(动宾关系)--> 没有
。 --(WP)--> 有
猕猴桃 --(动宾关系)--> 没有
没有 --(并列关系)--> 香蕉
、 --(标点符号)--> 没有
榴莲 --(并列关系)--> 香蕉
、 --(标点符号)--> 榴莲
苹果 --(并列关系)--> 香蕉
、 --(标点符号)--> 香蕉
香蕉 --(动宾关系)--> 有
有 --(核心关系)--> ##核心##
里 --(主谓关系)--> 有
篮子 --(定中关系)--> 里
有 --(核心关系)--> ##核心##

感觉拿到这个结果也不太好分析

**Comment by hankcs** [comment]
0. 请参考https://github.com/hankcs/HanLP#鸣谢
0. 有很多高级的NLP task等待探索，我可能会优先实现我感兴趣的，或者我马上要用的，所以不能断言一定会或者不会。
0. 关于句法分析，我只是实现了一个高性能的句法分析器。具体拿工具做什么、如何分析属于具体用户或企业的业务逻辑（短语提取、实体关系、知识图谱、人机对话……）。

**Comment by 240668488** [comment]
你好
请问我在CustomDictionaryPath这个数组配置了自己的词典，词典的词性和词频都配置了，使用的是词典f分词，为什么结果不是按最长分词呢？

**Comment by hankcs** [comment]
@240668488 请参考：https://github.com/hankcs/HanLP/wiki/FAQ#%E5%88%86%E8%AF%8D%E5%99%A8%E6%98%AF%E6%8C%89%E6%9C%80%E9%95%BF%E8%AF%8D%E5%88%87%E5%88%86%E7%9A%84%E5%90%97%E5%8F%AF%E4%BB%A5%E9%85%8D%E7%BD%AE%E5%90%97

**Comment by 240668488** [comment]
这些问题我都注意了，肯定是清空了缓存的
我把词典内容直接追加到CustomDictionary这个默认的里面，就能出现我要的效果，单独存放就不行么？

**Comment by hankcs** [comment]
@240668488  我并不是指缓存，而是下面这个QA
分词器是按最长词切分的吗？可以配置吗？

**Comment by 240668488** [comment]
现在改用DoubleArrayTrieSegment这个分词器
还是和上面一样的效果，需要把词典内容追加到CustomDictionary内

**Comment by 240668488** [comment]
你好
词典的词性可以训练么？

**Comment by hankcs** [comment]
@240668488 请参考：https://github.com/hankcs/HanLP/wiki/%E8%AE%AD%E7%BB%83%E5%88%86%E8%AF%8D%E6%A8%A1%E5%9E%8B

**Comment by 240668488** [comment]
你好
最近碰到一个问题，就是 数次数量词的识别，如何扩展支持呢？比如2包或者其他类似词
看了源码还是不太懂在哪修改，麻烦告知，不甚感激！

**Comment by hankcs** [comment]
有数量词识别开关，请参考demo。

**Comment by 240668488** [comment]
亲，可能我表述不清楚
就是有的数量词能识别有的不能识别，我想把不能识别的添加进去，但不知如何操作，谢谢

**Comment by hankcs** [comment]
不能识别的量词添加q词性就行了

**Comment by 240668488** [comment]
太感谢了，醍醐灌顶的感觉

**Comment by 240668488** [comment]
新年好 hankcs

我想咨询下 关于 依存句法分析 这块，能不能很好的定位 某个量词所修饰的 中心词？或者不走 依存句法分析 这条路，有其他可行的方案么？

**Comment by hankcs** [comment]
新年快乐，除了依存句法外没听说过其他方法

**Comment by shaogx** [comment]
@hankcs 这里有篇论文说到语义相似度计算， http://www.docin.com/p-1606390946.html
