### ISSUE TITLE
【分词问题】钱己经打到卡上了=>钱己经 打 到 卡 上 了

### ISSUE THREAD

**Issue by whaozl** [hankcs/HanLP#982]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.6.8
我使用的版本是：1.6.8

**Comment by hankcs** [comment]
这种错别字看上去很像人名，孔乙己。

```java
        CustomDictionary.insert("己经", "错别字 1");
        System.out.println(HanLP.segment(
                "钱己经打到卡上了"
        ));
```

[钱/n, 己经/错别字, 打/v, 到/v, 卡/n, 上/f, 了/ule]

**Comment by whaozl** [comment]
@hankcs 您太厉害了 膜拜
