### ISSUE TITLE
关于DoubleArrayTrie的默认初始化大小

### ISSUE THREAD

**Issue by wawa8900** [hankcs/HanLP#984]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.6.8
我使用的版本是：portable-1.6.6

## 我的问题
![image](https://user-images.githubusercontent.com/26922926/46203542-b2d47900-c34c-11e8-9b0d-efccb5a6ce0e.png)
请问初始化时，初期大小必须是 65536*32这么大吗，如果要匹配的词不是很多（几个到几百个不等），也必须设定这么大吗。（程序中需要用到很多这种小字典，而且字典会频繁的变化）
我改成65536后，有时候用Searcher匹配的时候报ArrayIndexOutOfBoundsException的异常。

## 复现问题
1.用【潘家园街道】构建一个词典
2.用构建的词典匹配附件的这篇文章
3.用dart.getSearcher(text, 0)匹配，会在这个地方异常
![image](https://user-images.githubusercontent.com/26922926/46203923-e8c62d00-c34d-11e8-8a2b-c4c3db18942d.png)

[doc.txt](https://github.com/hankcs/HanLP/files/2427850/doc.txt)

**Comment by tiandiweizun** [comment]
如果几个，是不应该用doubleArrayTrie的，直接遍历indexof，如果觉的不是特别多（100以下），可以使用其他数据结构，比如BinTrie或者原始的DoubleArrayTrie，但是HanLP的DoubleArrayTrie在所有的双数组树种检索是最快的，因为他直接把unicode当做index，而不是使用map保存char to index

**Comment by hankcs** [comment]
1. 在修改代码前请保证理解原理，三思，谨慎
1. 双数组大小至少是size + 65535
1. 现在优化了构建后自动shrink到最低内存，与从磁盘加载效果一致。
