### ISSUE TITLE
pyhanlp使用SafeJClass调用crf分词器意图多线程分词，报jvm错误

### ISSUE THREAD

**Issue by SrWYG** [hankcs/HanLP#985]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：pyhanlp GitHub master
我使用的版本是：pyhanlp GitHub master

## 我的问题
      pyhanlp使用SafeJClass调用crf分词器意图多线程分词，报jvm错误

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

class Divider(threading.Thread):
    def __init__(self, threadID, data):
        threading.Thread.__init__(self)
        self.threadID=threadID
        self.data=data
        CRFLexicalAnalyzer = SafeJClass("com.hankcs.hanlp.model.crf.CRFLexicalAnalyzer")
        #CustomDictionary = LazyLoadingJClass('com.hankcs.hanlp.dictionary.CustomDictionary')
        #HanLP = SafeJClass('com.hankcs.hanlp.HanLP')
        extend_dic = format_dic(external_dic_path)
        for word_e in extend_dic:
            CustomDictionary.add(word_e)  # 添加外部军事词典
        # 打开词性标注
        s = CRFLexicalAnalyzer().enableCustomDictionary(True).enablePartOfSpeechTagging(True)
        self.segment=s

    def run(self):
        divide_word(self.data,self.threadID,self.segment)

def divide_word(data,pid,segment,Debug=False):
    all_words=[]

    for index,article in enumerate(data):
        article_contont = article["article_content"]
        article_contont = norm_article(article_contont)
        terms=segment.seg(article_contont)
        words=[term.word for term in terms]
        if Debug:
            print(words)
        all_words.append(words)
        if index%500==0:
            print("Thread:",pid,"divide...line:",index)
    return all_words

    data=load_json(data_path)
    mid=int(len(data)*0.5)
    data1=data[:mid]
    data2=data[mid:]
    thread1 = Divider( "Thread-1", data1)
    thread2 = Divider( "Thread-2", data2)

    # 开启线程
    thread1.start()
    thread2.start()
    thread1.join()
    thread2.join()

### 期望输出

```
期望输出
```

### 实际输出

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f7c4d07fbb0, pid=17521, tid=0x00007f7bc90ce700
#
# JRE version: OpenJDK Runtime Environment (8.0_181-b13) (build 1.8.0_181-8u181-b13-0ubuntu0.16.04.1-b13)
# Java VM: OpenJDK 64-Bit Server VM (25.181-b13 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [_jpype.cpython-36m-x86_64-linux-gnu.so+0x3cbb0]  JPJavaEnv::FindClass(char const*)+0x20
#
# Core dump written. Default location: /home/ygwang/workspace/hannlp/handler/core or core.17521
#
# An error report file with more information is saved as:
# /home/ygwang/workspace/hannlp/handler/hs_err_pid17521.log
[thread 140169611896576 also had an error]
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
Aborted (core dumped)

```
实际输出
```

**Comment by hankcs** [comment]
将CRFLexicalAnalyzer = SafeJClass("com.hankcs.hanlp.model.crf.CRFLexicalAnalyzer")和s = CRFLexicalAnalyzer()移到线程外部。
参考：https://github.com/hankcs/pyhanlp/blob/2a310d75fd813afb354db0a908e5bb7a01822498/tests/test_multithread.py#L40

```python
from pyhanlp import HanLP, SafeJClass

# 在线程体外部用SafeJClass线程安全地引入类名
CRFLexicalAnalyzer = SafeJClass("com.hankcs.hanlp.model.crf.CRFLexicalAnalyzer")


class MyThread(threading.Thread):
    def __init__(self, name, counter, analyzer):
        threading.Thread.__init__(self)
        self.thread_name = name
        self.counter = counter
        self.segment = analyzer

    def run(self):
        print("Starting " + self.thread_name)
        while self.counter:
            time.sleep(1)
            sentence = self.segment.analyze("商品和服务")
            print("%s: %s, seg: %s" % (self.thread_name, time.ctime(time.time()), sentence))
            self.counter -= 1


class Test(unittest.TestCase):
    def setUp(self):
        pass

    def tearDown(self):
        pass

    def test_multithread(self):
        logging.info("test_multithread")
        # 在线程外部创建对象，供多个线程共用
        analyzer = CRFLexicalAnalyzer()

        thread1 = MyThread("Thread-1", 1, analyzer)
        thread2 = MyThread("Thread-2", 2, analyzer)

        thread1.start()
        thread2.start()

        print('waiting to finish the thread')

        thread1.join()
        thread2.join()

        print("Exiting Main Thread")
```

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
