### ISSUE TITLE
关于自定义词典的问题

### ISSUE THREAD

**Issue by congjiao1988** [hankcs/HanLP#99]
您好 我配置好了property，使用CustomDictionary.add("攻城狮");和CustomDictionary.insert 方法插入，这两种方法有什么区别吗？貌似都是缓存的形式，当有insert语句时能够正确分词，去掉这句重新运行就不行了

**Comment by hankcs** [comment]
insert是覆盖，详见源码中的文档。

**Comment by congjiao1988** [comment]
那insert 和add 加入的词语被插入到了哪里呢？我在所有的自定义词典里都没有发现，而且貌似这种添加时缓存模式，重新运行之后添加的词会找不到啊



dongcongjiao1988@163.com
 
发件人： hankcs
发送时间： 2015-12-15 16:45
收件人： hankcs/HanLP
抄送： 董从娇
主题： Re: [HanLP] 关于自定义词典的问题 (#99)
insert是覆盖，详见源码中的文档。

**Comment by hankcs** [comment]
请仔细阅读demo：https://github.com/hankcs/HanLP/blob/master/src/test/java/com/hankcs/demo/DemoCustomDictionary.java

**Comment by congjiao1988** [comment]
我读源码过程中未发现新词识别的demo 不知道系统里是否有这个功能？

**Comment by hankcs** [comment]
CRF分词可活用做新词识别。
