### ISSUE TITLE
安装完pyhanlp和jpype之后，ModuleNotFoundError: No module named '_jpype'

### ISSUE THREAD

**Issue by wusaifei** [hankcs/HanLP#995]
import from pyhanlp import *
报错：+
Traceback (most recent call last):
  File "/home/vip/wusaifei/project/preprocess.py", line 2, in <module>
    from pyhanlp import *
  File "/home/vip/wusaifei/anaconda3/lib/python3.6/site-packages/pyhanlp/__init__.py", line 11, in <module>
    from jpype import JClass, startJVM, getDefaultJVMPath, isThreadAttachedToJVM, attachThreadToJVM
  File "/home/vip/wusaifei/anaconda3/lib/python3.6/site-packages/jpype/__init__.py", line 17, in <module>
    from ._jpackage import *
  File "/home/vip/wusaifei/anaconda3/lib/python3.6/site-packages/jpype/_jpackage.py", line 18, in <module>
    import _jpype
ModuleNotFoundError: No module named '_jpype'

**Comment by hankcs** [comment]
一般你不需要分开装两个package，pip会自动安装依赖。既然你手动安装，那么请检查是否真的安装成功了：

```
$ pip3 show jpype1
Name: JPype1
Version: 0.6.3
Summary: A Python to Java bridge.
Home-page: https://github.com/originell/jpype/
Author: Luis Nell
Author-email: cooperate@originell.org
```

**Comment by fooSynaptic** [comment]
@hankcs 我在安装pyhanlp遇到了build的问题：

```
Collecting pyhanlp
Collecting jpype1 (from pyhanlp)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/c4/4b/60a3e63d51714d4d7ef1b1efdf84315d118a0a80a5b085bb52a7e2428cdc/JPype1-0.6.3.tar.gz
Building wheels for collected packages: jpype1
 ** Building wheel for jpype1 (setup.py) ... error**
  Complete output from command /usr/local/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/k4/hr3f43094d9frn8nl2xdbx3r0000gn/T/pip-install-4coyn6e8/jpype1/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/k4/hr3f43094d9frn8nl2xdbx3r0000gn/T/pip-wheel-hmk3hgfk --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.6-intel-3.5
  creating build/lib.macosx-10.6-intel-3.5/jpype
  copying jpype/_jcollection.py -> build/lib.macosx-10.6-intel-3.5/jpype
  copying jpype/_classpath.py -> build/lib.macosx-10.6-intel-3.5/jpype
  copying jpype/_jio.py -> build/lib.macosx-10.6-intel-3.5/jpype
  copying jpype/_pykeywords.py -> build/lib.macosx-10.6-intel-3.5/jpype
  copying jpype/_jproxy.py -> build/lib.macosx-10.6-intel-3.5/jpype
  copying jpype/_gui.py -> build/lib.macosx-10.6-intel-3.5/jpype
  copying jpype/_darwin.py -> build/lib.macosx-10.6-intel-3.5/jpype
  copying jpype/nio.py -> build/lib.macosx-10.6-intel-3.5/jpype
  copying jpype/_cygwin.py -> build/lib.macosx-10.6-intel-3.5/jpype
  copying jpype/_properties.py -> build/lib.macosx-10.6-intel-3.5/jpype
  copying jpype/__init__.py -> build/lib.macosx-10.6-intel-3.5/jpype
  copying jpype/_refdaemon.py -> build/lib.macosx-10.6-intel-3.5/jpype
  copying jpype/_jboxed.py -> build/lib.macosx-10.6-intel-3.5/jpype
  copying jpype/JClassUtil.py -> build/lib.macosx-10.6-intel-3.5/jpype
  copying jpype/_jvmfinder.py -> build/lib.macosx-10.6-intel-3.5/jpype
  copying jpype/imports.py -> build/lib.macosx-10.6-intel-3.5/jpype
  copying jpype/_core.py -> build/lib.macosx-10.6-intel-3.5/jpype
  copying jpype/_linux.py -> build/lib.macosx-10.6-intel-3.5/jpype
  copying jpype/_jarray.py -> build/lib.macosx-10.6-intel-3.5/jpype
  copying jpype/_jobject.py -> build/lib.macosx-10.6-intel-3.5/jpype
  copying jpype/_jclass.py -> build/lib.macosx-10.6-intel-3.5/jpype
  copying jpype/_windows.py -> build/lib.macosx-10.6-intel-3.5/jpype
  copying jpype/_jwrapper.py -> build/lib.macosx-10.6-intel-3.5/jpype
  copying jpype/_jexception.py -> build/lib.macosx-10.6-intel-3.5/jpype
  copying jpype/reflect.py -> build/lib.macosx-10.6-intel-3.5/jpype
  copying jpype/_jpackage.py -> build/lib.macosx-10.6-intel-3.5/jpype
  creating build/lib.macosx-10.6-intel-3.5/jpype/awt
  copying jpype/awt/__init__.py -> build/lib.macosx-10.6-intel-3.5/jpype/awt
  creating build/lib.macosx-10.6-intel-3.5/jpype/awt/event
  copying jpype/awt/event/__init__.py -> build/lib.macosx-10.6-intel-3.5/jpype/awt/event
  copying jpype/awt/event/WindowAdapter.py -> build/lib.macosx-10.6-intel-3.5/jpype/awt/event
  creating build/lib.macosx-10.6-intel-3.5/jpypex
  copying jpypex/__init__.py -> build/lib.macosx-10.6-intel-3.5/jpypex
  creating build/lib.macosx-10.6-intel-3.5/jpypex/swing
  copying jpypex/swing/AbstractAction.py -> build/lib.macosx-10.6-intel-3.5/jpypex/swing
  copying jpypex/swing/__init__.py -> build/lib.macosx-10.6-intel-3.5/jpypex/swing
  copying jpypex/swing/pyutils.py -> build/lib.macosx-10.6-intel-3.5/jpypex/swing
  running build_ext
  /private/var/folders/k4/hr3f43094d9frn8nl2xdbx3r0000gn/T/pip-install-4coyn6e8/jpype1/setup.py:173: FeatureNotice: Turned ON Numpy support for fast Java array access
    FeatureNotice)
  building '_jpype' extension
  creating build/temp.macosx-10.6-intel-3.5
  creating build/temp.macosx-10.6-intel-3.5/native
  creating build/temp.macosx-10.6-intel-3.5/native/python
  creating build/temp.macosx-10.6-intel-3.5/native/common
  /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch i386 -arch x86_64 -g -DMACOSX=1 -DHAVE_NUMPY=1 -Inative/common/include -Inative/python/include -Inative/jni_include -I/Users/ajmd/Library/Python/3.5/lib/python/site-packages/numpy/core/include -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c native/python/jpype_python.cpp -o build/temp.macosx-10.6-intel-3.5/native/python/jpype_python.o -ggdb
  warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
  In file included from native/python/jpype_python.cpp:19:
  In file included from native/python/include/jpype_python.h:24:
  native/common/include/jpype.h:107:10: fatal error: 'map' file not found
  #include <map>
           ^~~~~
  1 warning and 1 error generated.
  error: command '/usr/bin/clang' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for jpype1
  Running setup.py clean for jpype1
Failed to build jpype1
Installing collected packages: jpype1, pyhanlp
  Running setup.py install for jpype1 ... error
    Complete output from command /usr/local/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/k4/hr3f43094d9frn8nl2xdbx3r0000gn/T/pip-install-4coyn6e8/jpype1/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/k4/hr3f43094d9frn8nl2xdbx3r0000gn/T/pip-record-2yd0udth/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.6-intel-3.5
    creating build/lib.macosx-10.6-intel-3.5/jpype
    copying jpype/_jcollection.py -> build/lib.macosx-10.6-intel-3.5/jpype
    copying jpype/_classpath.py -> build/lib.macosx-10.6-intel-3.5/jpype
    copying jpype/_jio.py -> build/lib.macosx-10.6-intel-3.5/jpype
    copying jpype/_pykeywords.py -> build/lib.macosx-10.6-intel-3.5/jpype
    copying jpype/_jproxy.py -> build/lib.macosx-10.6-intel-3.5/jpype
    copying jpype/_gui.py -> build/lib.macosx-10.6-intel-3.5/jpype
    copying jpype/_darwin.py -> build/lib.macosx-10.6-intel-3.5/jpype
    copying jpype/nio.py -> build/lib.macosx-10.6-intel-3.5/jpype
    copying jpype/_cygwin.py -> build/lib.macosx-10.6-intel-3.5/jpype
    copying jpype/_properties.py -> build/lib.macosx-10.6-intel-3.5/jpype
    copying jpype/__init__.py -> build/lib.macosx-10.6-intel-3.5/jpype
    copying jpype/_refdaemon.py -> build/lib.macosx-10.6-intel-3.5/jpype
    copying jpype/_jboxed.py -> build/lib.macosx-10.6-intel-3.5/jpype
    copying jpype/JClassUtil.py -> build/lib.macosx-10.6-intel-3.5/jpype
    copying jpype/_jvmfinder.py -> build/lib.macosx-10.6-intel-3.5/jpype
    copying jpype/imports.py -> build/lib.macosx-10.6-intel-3.5/jpype
    copying jpype/_core.py -> build/lib.macosx-10.6-intel-3.5/jpype
    copying jpype/_linux.py -> build/lib.macosx-10.6-intel-3.5/jpype
    copying jpype/_jarray.py -> build/lib.macosx-10.6-intel-3.5/jpype
    copying jpype/_jobject.py -> build/lib.macosx-10.6-intel-3.5/jpype
    copying jpype/_jclass.py -> build/lib.macosx-10.6-intel-3.5/jpype
    copying jpype/_windows.py -> build/lib.macosx-10.6-intel-3.5/jpype
    copying jpype/_jwrapper.py -> build/lib.macosx-10.6-intel-3.5/jpype
    copying jpype/_jexception.py -> build/lib.macosx-10.6-intel-3.5/jpype
    copying jpype/reflect.py -> build/lib.macosx-10.6-intel-3.5/jpype
    copying jpype/_jpackage.py -> build/lib.macosx-10.6-intel-3.5/jpype
    creating build/lib.macosx-10.6-intel-3.5/jpype/awt
    copying jpype/awt/__init__.py -> build/lib.macosx-10.6-intel-3.5/jpype/awt
    creating build/lib.macosx-10.6-intel-3.5/jpype/awt/event
    copying jpype/awt/event/__init__.py -> build/lib.macosx-10.6-intel-3.5/jpype/awt/event
    copying jpype/awt/event/WindowAdapter.py -> build/lib.macosx-10.6-intel-3.5/jpype/awt/event
    creating build/lib.macosx-10.6-intel-3.5/jpypex
    copying jpypex/__init__.py -> build/lib.macosx-10.6-intel-3.5/jpypex
    creating build/lib.macosx-10.6-intel-3.5/jpypex/swing
    copying jpypex/swing/AbstractAction.py -> build/lib.macosx-10.6-intel-3.5/jpypex/swing
    copying jpypex/swing/__init__.py -> build/lib.macosx-10.6-intel-3.5/jpypex/swing
    copying jpypex/swing/pyutils.py -> build/lib.macosx-10.6-intel-3.5/jpypex/swing
    running build_ext
    /private/var/folders/k4/hr3f43094d9frn8nl2xdbx3r0000gn/T/pip-install-4coyn6e8/jpype1/setup.py:173: FeatureNotice: Turned ON Numpy support for fast Java array access
      FeatureNotice)
    building '_jpype' extension
    creating build/temp.macosx-10.6-intel-3.5
    creating build/temp.macosx-10.6-intel-3.5/native
    creating build/temp.macosx-10.6-intel-3.5/native/python
    creating build/temp.macosx-10.6-intel-3.5/native/common
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch i386 -arch x86_64 -g -DMACOSX=1 -DHAVE_NUMPY=1 -Inative/common/include -Inative/python/include -Inative/jni_include -I/Users/ajmd/Library/Python/3.5/lib/python/site-packages/numpy/core/include -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c native/python/jpype_python.cpp -o build/temp.macosx-10.6-intel-3.5/native/python/jpype_python.o -ggdb
    warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
    In file included from native/python/jpype_python.cpp:19:
    In file included from native/python/include/jpype_python.h:24:
    native/common/include/jpype.h:107:10: fatal error: 'map' file not found
    #include <map>
             ^~~~~
    1 warning and 1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1
    
    ----------------------------------------
Command "/usr/local/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/k4/hr3f43094d9frn8nl2xdbx3r0000gn/T/pip-install-4coyn6e8/jpype1/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/k4/hr3f43094d9frn8nl2xdbx3r0000gn/T/pip-record-2yd0udth/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/k4/hr3f43094d9frn8nl2xdbx3r0000gn/T/pip-install-4coyn6e8/jpype1/
```

**Comment by dayL-W** [comment]
> @hankcs 我在安装pyhanlp遇到了build的问题：
> 
> ```
> Collecting pyhanlp
> Collecting jpype1 (from pyhanlp)
>   Using cached https://pypi.tuna.tsinghua.edu.cn/packages/c4/4b/60a3e63d51714d4d7ef1b1efdf84315d118a0a80a5b085bb52a7e2428cdc/JPype1-0.6.3.tar.gz
> Building wheels for collected packages: jpype1
>  ** Building wheel for jpype1 (setup.py) ... error**
>   Complete output from command /usr/local/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/k4/hr3f43094d9frn8nl2xdbx3r0000gn/T/pip-install-4coyn6e8/jpype1/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/k4/hr3f43094d9frn8nl2xdbx3r0000gn/T/pip-wheel-hmk3hgfk --python-tag cp35:
>   running bdist_wheel
>   running build
>   running build_py
>   creating build
>   creating build/lib.macosx-10.6-intel-3.5
>   creating build/lib.macosx-10.6-intel-3.5/jpype
>   copying jpype/_jcollection.py -> build/lib.macosx-10.6-intel-3.5/jpype
>   copying jpype/_classpath.py -> build/lib.macosx-10.6-intel-3.5/jpype
>   copying jpype/_jio.py -> build/lib.macosx-10.6-intel-3.5/jpype
>   copying jpype/_pykeywords.py -> build/lib.macosx-10.6-intel-3.5/jpype
>   copying jpype/_jproxy.py -> build/lib.macosx-10.6-intel-3.5/jpype
>   copying jpype/_gui.py -> build/lib.macosx-10.6-intel-3.5/jpype
>   copying jpype/_darwin.py -> build/lib.macosx-10.6-intel-3.5/jpype
>   copying jpype/nio.py -> build/lib.macosx-10.6-intel-3.5/jpype
>   copying jpype/_cygwin.py -> build/lib.macosx-10.6-intel-3.5/jpype
>   copying jpype/_properties.py -> build/lib.macosx-10.6-intel-3.5/jpype
>   copying jpype/__init__.py -> build/lib.macosx-10.6-intel-3.5/jpype
>   copying jpype/_refdaemon.py -> build/lib.macosx-10.6-intel-3.5/jpype
>   copying jpype/_jboxed.py -> build/lib.macosx-10.6-intel-3.5/jpype
>   copying jpype/JClassUtil.py -> build/lib.macosx-10.6-intel-3.5/jpype
>   copying jpype/_jvmfinder.py -> build/lib.macosx-10.6-intel-3.5/jpype
>   copying jpype/imports.py -> build/lib.macosx-10.6-intel-3.5/jpype
>   copying jpype/_core.py -> build/lib.macosx-10.6-intel-3.5/jpype
>   copying jpype/_linux.py -> build/lib.macosx-10.6-intel-3.5/jpype
>   copying jpype/_jarray.py -> build/lib.macosx-10.6-intel-3.5/jpype
>   copying jpype/_jobject.py -> build/lib.macosx-10.6-intel-3.5/jpype
>   copying jpype/_jclass.py -> build/lib.macosx-10.6-intel-3.5/jpype
>   copying jpype/_windows.py -> build/lib.macosx-10.6-intel-3.5/jpype
>   copying jpype/_jwrapper.py -> build/lib.macosx-10.6-intel-3.5/jpype
>   copying jpype/_jexception.py -> build/lib.macosx-10.6-intel-3.5/jpype
>   copying jpype/reflect.py -> build/lib.macosx-10.6-intel-3.5/jpype
>   copying jpype/_jpackage.py -> build/lib.macosx-10.6-intel-3.5/jpype
>   creating build/lib.macosx-10.6-intel-3.5/jpype/awt
>   copying jpype/awt/__init__.py -> build/lib.macosx-10.6-intel-3.5/jpype/awt
>   creating build/lib.macosx-10.6-intel-3.5/jpype/awt/event
>   copying jpype/awt/event/__init__.py -> build/lib.macosx-10.6-intel-3.5/jpype/awt/event
>   copying jpype/awt/event/WindowAdapter.py -> build/lib.macosx-10.6-intel-3.5/jpype/awt/event
>   creating build/lib.macosx-10.6-intel-3.5/jpypex
>   copying jpypex/__init__.py -> build/lib.macosx-10.6-intel-3.5/jpypex
>   creating build/lib.macosx-10.6-intel-3.5/jpypex/swing
>   copying jpypex/swing/AbstractAction.py -> build/lib.macosx-10.6-intel-3.5/jpypex/swing
>   copying jpypex/swing/__init__.py -> build/lib.macosx-10.6-intel-3.5/jpypex/swing
>   copying jpypex/swing/pyutils.py -> build/lib.macosx-10.6-intel-3.5/jpypex/swing
>   running build_ext
>   /private/var/folders/k4/hr3f43094d9frn8nl2xdbx3r0000gn/T/pip-install-4coyn6e8/jpype1/setup.py:173: FeatureNotice: Turned ON Numpy support for fast Java array access
>     FeatureNotice)
>   building '_jpype' extension
>   creating build/temp.macosx-10.6-intel-3.5
>   creating build/temp.macosx-10.6-intel-3.5/native
>   creating build/temp.macosx-10.6-intel-3.5/native/python
>   creating build/temp.macosx-10.6-intel-3.5/native/common
>   /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch i386 -arch x86_64 -g -DMACOSX=1 -DHAVE_NUMPY=1 -Inative/common/include -Inative/python/include -Inative/jni_include -I/Users/ajmd/Library/Python/3.5/lib/python/site-packages/numpy/core/include -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c native/python/jpype_python.cpp -o build/temp.macosx-10.6-intel-3.5/native/python/jpype_python.o -ggdb
>   warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
>   In file included from native/python/jpype_python.cpp:19:
>   In file included from native/python/include/jpype_python.h:24:
>   native/common/include/jpype.h:107:10: fatal error: 'map' file not found
>   #include <map>
>            ^~~~~
>   1 warning and 1 error generated.
>   error: command '/usr/bin/clang' failed with exit status 1
>   
>   ----------------------------------------
>   Failed building wheel for jpype1
>   Running setup.py clean for jpype1
> Failed to build jpype1
> Installing collected packages: jpype1, pyhanlp
>   Running setup.py install for jpype1 ... error
>     Complete output from command /usr/local/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/k4/hr3f43094d9frn8nl2xdbx3r0000gn/T/pip-install-4coyn6e8/jpype1/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/k4/hr3f43094d9frn8nl2xdbx3r0000gn/T/pip-record-2yd0udth/install-record.txt --single-version-externally-managed --compile:
>     running install
>     running build
>     running build_py
>     creating build
>     creating build/lib.macosx-10.6-intel-3.5
>     creating build/lib.macosx-10.6-intel-3.5/jpype
>     copying jpype/_jcollection.py -> build/lib.macosx-10.6-intel-3.5/jpype
>     copying jpype/_classpath.py -> build/lib.macosx-10.6-intel-3.5/jpype
>     copying jpype/_jio.py -> build/lib.macosx-10.6-intel-3.5/jpype
>     copying jpype/_pykeywords.py -> build/lib.macosx-10.6-intel-3.5/jpype
>     copying jpype/_jproxy.py -> build/lib.macosx-10.6-intel-3.5/jpype
>     copying jpype/_gui.py -> build/lib.macosx-10.6-intel-3.5/jpype
>     copying jpype/_darwin.py -> build/lib.macosx-10.6-intel-3.5/jpype
>     copying jpype/nio.py -> build/lib.macosx-10.6-intel-3.5/jpype
>     copying jpype/_cygwin.py -> build/lib.macosx-10.6-intel-3.5/jpype
>     copying jpype/_properties.py -> build/lib.macosx-10.6-intel-3.5/jpype
>     copying jpype/__init__.py -> build/lib.macosx-10.6-intel-3.5/jpype
>     copying jpype/_refdaemon.py -> build/lib.macosx-10.6-intel-3.5/jpype
>     copying jpype/_jboxed.py -> build/lib.macosx-10.6-intel-3.5/jpype
>     copying jpype/JClassUtil.py -> build/lib.macosx-10.6-intel-3.5/jpype
>     copying jpype/_jvmfinder.py -> build/lib.macosx-10.6-intel-3.5/jpype
>     copying jpype/imports.py -> build/lib.macosx-10.6-intel-3.5/jpype
>     copying jpype/_core.py -> build/lib.macosx-10.6-intel-3.5/jpype
>     copying jpype/_linux.py -> build/lib.macosx-10.6-intel-3.5/jpype
>     copying jpype/_jarray.py -> build/lib.macosx-10.6-intel-3.5/jpype
>     copying jpype/_jobject.py -> build/lib.macosx-10.6-intel-3.5/jpype
>     copying jpype/_jclass.py -> build/lib.macosx-10.6-intel-3.5/jpype
>     copying jpype/_windows.py -> build/lib.macosx-10.6-intel-3.5/jpype
>     copying jpype/_jwrapper.py -> build/lib.macosx-10.6-intel-3.5/jpype
>     copying jpype/_jexception.py -> build/lib.macosx-10.6-intel-3.5/jpype
>     copying jpype/reflect.py -> build/lib.macosx-10.6-intel-3.5/jpype
>     copying jpype/_jpackage.py -> build/lib.macosx-10.6-intel-3.5/jpype
>     creating build/lib.macosx-10.6-intel-3.5/jpype/awt
>     copying jpype/awt/__init__.py -> build/lib.macosx-10.6-intel-3.5/jpype/awt
>     creating build/lib.macosx-10.6-intel-3.5/jpype/awt/event
>     copying jpype/awt/event/__init__.py -> build/lib.macosx-10.6-intel-3.5/jpype/awt/event
>     copying jpype/awt/event/WindowAdapter.py -> build/lib.macosx-10.6-intel-3.5/jpype/awt/event
>     creating build/lib.macosx-10.6-intel-3.5/jpypex
>     copying jpypex/__init__.py -> build/lib.macosx-10.6-intel-3.5/jpypex
>     creating build/lib.macosx-10.6-intel-3.5/jpypex/swing
>     copying jpypex/swing/AbstractAction.py -> build/lib.macosx-10.6-intel-3.5/jpypex/swing
>     copying jpypex/swing/__init__.py -> build/lib.macosx-10.6-intel-3.5/jpypex/swing
>     copying jpypex/swing/pyutils.py -> build/lib.macosx-10.6-intel-3.5/jpypex/swing
>     running build_ext
>     /private/var/folders/k4/hr3f43094d9frn8nl2xdbx3r0000gn/T/pip-install-4coyn6e8/jpype1/setup.py:173: FeatureNotice: Turned ON Numpy support for fast Java array access
>       FeatureNotice)
>     building '_jpype' extension
>     creating build/temp.macosx-10.6-intel-3.5
>     creating build/temp.macosx-10.6-intel-3.5/native
>     creating build/temp.macosx-10.6-intel-3.5/native/python
>     creating build/temp.macosx-10.6-intel-3.5/native/common
>     /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch i386 -arch x86_64 -g -DMACOSX=1 -DHAVE_NUMPY=1 -Inative/common/include -Inative/python/include -Inative/jni_include -I/Users/ajmd/Library/Python/3.5/lib/python/site-packages/numpy/core/include -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c native/python/jpype_python.cpp -o build/temp.macosx-10.6-intel-3.5/native/python/jpype_python.o -ggdb
>     warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
>     In file included from native/python/jpype_python.cpp:19:
>     In file included from native/python/include/jpype_python.h:24:
>     native/common/include/jpype.h:107:10: fatal error: 'map' file not found
>     #include <map>
>              ^~~~~
>     1 warning and 1 error generated.
>     error: command '/usr/bin/clang' failed with exit status 1
>     
>     ----------------------------------------
> Command "/usr/local/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/k4/hr3f43094d9frn8nl2xdbx3r0000gn/T/pip-install-4coyn6e8/jpype1/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/k4/hr3f43094d9frn8nl2xdbx3r0000gn/T/pip-record-2yd0udth/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/k4/hr3f43094d9frn8nl2xdbx3r0000gn/T/pip-install-4coyn6e8/jpype1/
> ```
> 
> 请问如何解决

https://blog.csdn.net/qq_19741181/article/details/79414202

**Comment by hankcs** [comment]
> fatal error: 'map' file not found

https://www.google.com/search?q=fatal+error%3A+%27map%27+file+not+found&oq=fatal+error%3A+%27map%27+file+not+found&aqs=chrome..69i57&sourceid=chrome&ie=UTF-8

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
