### ISSUE TITLE
繁体转简体对币种转换错误的问题

### ISSUE THREAD

**Issue by petonwu** [hankcs/HanLP#998]
Hi,

调用HanLP.convertToSimplifiedChinese()做繁体到简体的转换，但是对于下面的这些币种，存在下面的问题，还烦劳看下怎么修改这个问题：
荷属安的列斯盾 ——> 荷属安的列斯斯盾
塔吉克卢布 ——> 塔吉克斯坦卢布
巴哈马币 ——> 巴赫马币
厄瓜多尔UCV ——> 厄瓜多尔尔UCV

左边是输入的Query，右边是转换后的结果，右边转换都是有问题的。

**Comment by hankcs** [comment]
1. 部分是词典有误，请修改tc目录下的txt
1. 不要尝试将简体当繁体转简体，有些简体词在繁体中是另一个意思

感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。
