### ISSUE TITLE
"大家电"分词问题

### ISSUE THREAD

**Issue by dongfengwang** [hankcs/HanLP#999]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.6.8
我使用的版本是：1.3.4

## 我的问题
"大家电"分词错误,切分为"大家"和"电", 应该切分为"大"和"家电",请问如何修改核心词典解决这个问题.
我通过删除"大家"这个词,可以解决这个问题,但是这样之后,"大家"这个词就切分不出来了.

## 复现问题
使用viterbi分词"大家电"即可复现此问题

### 触发代码

```
    public void testIssue1234() throws Exception
    {
        System.out.println(StandardTokenizer.segment("大家电"));
    }
```
### 期望输出
```
"大"和"家电"
```
### 实际输出
```
"大家"和"电"
```

**Comment by hankcs** [comment]
感谢反馈，这是由于人民日报语料库的错误影响的

> 对于/p 冰箱/n 、/w 空调/n 这样/rzv 的/ude1 大家/rr 电/n 

已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。

**Comment by dongfengwang** [comment]
http://hanlp.com/?sentence=大家电  还是分词错误. 我之前增加了你说的更改方式,但是不会生效,只有把CoreNatureDictionary.txt里边的"大家 rr"这个词删掉才能生效.  viterbi分词算法对交叉分词 "大家"和"家电"这类,更倾向于选择 最前边的词. 词频大小影响比较小.

**Comment by hankcs** [comment]
线上模型更新周期较慢。我说过请参考commit：https://github.com/hankcs/HanLP/commit/29275b5ae7ef9e804d9554527b0a3f62b0c738c7
